### ISSUE TITLE
displaying PRO names on PomBase pages.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#100]
Historically we have used

name: transcription factor sre2, Sre2P form (Schizosaccharomyces pombe)

bu I noticed that there is a "EXACT PRO-short-label"
synonym: "Spom-sre2/Sre2N" EXACT PRO-short-label [PRO:DAN]

Can we use this for display? Ideally the part after the "/"

Once I have found out  if this is consistent:
https://sourceforge.net/p/pro-obo/term-requests/113/

**Comment by ValWood** [comment]
Darren updated the linked ticket  to say  we should be able to use the short name after the "/"

examples for texting:
http://www.pombase.org/spombe/result/SPBC16D10.09#go-biological_process

active form PR:000044777
would be displayed as
active form MonoUbiq+

**Comment by mah11** [comment]
possible snag: histones, especially modified ones. Not all have "/" in the synonym, and for ones that do, often the bit after the / isn't specific enough, e.g.

id: PR:000027596
name: histone H3.3 (Schizosaccharomyces pombe)
synonym: "Spom-hht3" EXACT PRO-short-label [PRO:DNx]

id: PR:000027602
name: histone H3.3, initiator methionine removed phosphorylated 1 (Schizosaccharomyces pombe)
synonym: "H3-pT3" RELATED []
synonym: "Spom-hht3/InitMet-/Phos:1" EXACT PRO-short-label [PRO:DAN]

**Comment by ValWood** [comment]
bummer, well-spotted.

after first "/"?

We can start with the full string anyway and then see if we can trim....

**Comment by ValWood** [comment]
If we do this
https://github.com/pombase/website/issues/67
this is also sorted
