### ISSUE TITLE
refine canned query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1004]
Proteins conserved in *S. cerevisiae*
is currently

(conserved in fungi (PBO:0011064) NOT no apparent *S. cerevisiae* ortholog (PBO:0000055))

but should be
conserved in fungi (PBO:0011064) 
NOT 
((no apparent *S. cerevisiae* ortholog (PBO:0000055)) OR (orthologs cannot be distinguished (PBO:0000110)))

**Comment by kimrutherford** [comment]
That change is live now.
