### ISSUE TITLE
pombe S. cerevisiae ortholog table V23

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1005]
I still make this manually and  the contents on the website has drifted  quite a bit from the download file.

I created a new version of the download file  (V23) in the orthologs directory. Could this be put into the downloads directory and the old file archived?

Thanks,

**Comment by kimrutherford** [comment]
So replace the cerevisiae-orthologs.txt file here?:

ftp://ftp.pombase.org/pombe/orthologs/

**Comment by ValWood** [comment]
yep. 
I only noticed because I was trying to balance the numbers for my thesis... I haven't been updating it. Still need to automate this part...next time...

**Comment by kimrutherford** [comment]
OK, thanks.  I've checked in the change and it should be on the FTP site in the morning.

**Comment by kimrutherford** [comment]
> it should be on the FTP site in the morning.

It's there now.
