### ISSUE TITLE
announce new disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1007]
after https://github.com/pombase/website/issues/989

I have done an image for the tweet and Explore  PomBase:

![presentation1](https://user-images.githubusercontent.com/7359272/47951779-53761400-df5d-11e8-89b5-e09a2571628d.jpg)

 Image credit  composite from Julie McMurry's  free science icons
https://pixabay.com/en/users/mcmurryjulie-2375405/

**Comment by ValWood** [comment]
This is actually a tablet icon, but it looks like a pombe cell. 
Obviously we need to fix it up and add the correct number.

**Comment by ValWood** [comment]
![presentation1](https://user-images.githubusercontent.com/7359272/47951979-5a525600-df60-11e8-9af8-5241b2083e16.jpg)

**Comment by ValWood** [comment]
Hmm, this isn't finishing my thesis....

**Comment by kimrutherford** [comment]
> A quilt for Cancer:

Should the visualisation tool have a "Disease slim" column one we have a disease slim?  If so I'll make a separate issue for it.

**Comment by jmcmurry** [comment]
When is this due? If you commit to getting out the vote or to donate to reuniting families, I will make a polished composite for you :)

**Comment by ValWood** [comment]
I was going to do that anyway ;) so that would be great....

There is no hurry  we haven't finished the work yet....

**Comment by ValWood** [comment]
I'm being a dope but where do I do the pledge?

**Comment by ValWood** [comment]
Hi @jmcmurry I made a donation to you via pixabay.
val

**Comment by jmcmurry** [comment]
Whoops this completely fell off my radar. Will get to it soon.

**Comment by ValWood** [comment]
@jmcmurry  no hurry, I only just sent a donation, so I wanted to ping you. Don't spend too long on it... it should be difficult  to make it look better than mine, I hope!

**Comment by ValWood** [comment]
We hope to release next week. 
This import  will take pombe disease associations from ~600 to  over 900

Still to do,  from this morning group call:

- [ ]  get new data onto dev and check
- [ ]  @Antonialock  draft announcments for news feed, pombelist twitter (don't forget image and Malacards ack )
- [ ] @mah11  edit 
- [ ] @Antonialock  test loader (this does not need to be done for release)
- [ ]  use improved image from @jmcmurry  if available

Later:
- [ ]  when new disease terms added to DO
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/created_by/Antonialock%20
announce update (@Antonialock   you might want to move this and anything outstanding to a new ticket after first release)

**Comment by jmcmurry** [comment]
How's this as an idea? 
![pombase_figure_2018-12-11](https://user-images.githubusercontent.com/3658863/49957312-45040c00-febc-11e8-8a03-856c8c708bbd.png)

**Comment by Antonialock** [comment]
Nice! 3 arms would make more 'sense' (pombe has three chromosomes)

Does it look busy with that many cells? (maybe it is to avoid white space in a rectangular image?)

how about this tweak?

<img width="545" alt="screenshot 2018-12-13 at 18 55 13" src="https://user-images.githubusercontent.com/12727506/49960795-e749e100-ff08-11e8-82c2-ba2d44f0dbfb.png">

**Comment by Antonialock** [comment]
or

<img width="532" alt="screenshot 2018-12-13 at 19 02 32" src="https://user-images.githubusercontent.com/12727506/49961089-ac947880-ff09-11e8-8471-718c59e64013.png">

**Comment by ValWood** [comment]
I think they are all awesome ideas so any combo would be very cool.

since the size will be quite small;

a) https://www.pombase.org/ on  the front page rotation
b) for tweet
c) a tiny icon on our news feed (here we will probably use  a  zoomed portion (head and shoulders maybe?),  it doesn't really matter for the thumbnail it just needs to look a bit pretty and different from the others...

maybe the more streamlined version?

**Comment by ValWood** [comment]
yes that might be better...if we can tell it's a pombe and a person,  in a small space, we are good!

**Comment by kimrutherford** [comment]
I like them too.

I think with a bit of juggling it will look good in the Explore section and on the front page:
https://www.pombase.org/archive/explore

We use 300x185.  Here's what it would look like at that resolution after moving things a bit:

![pombe-disease-1](https://user-images.githubusercontent.com/90474/49963676-7ee91700-ff7d-11e8-9080-285a2fc24a15.png)

**Comment by Antonialock** [comment]
great! The arms could be made a bit smaller to squash it a bit width-wise

**Comment by ValWood** [comment]
Yes that would be good. Torso is good.


This is such a good pombe selling point!

Almost 70% of pombe proteins have a human ortholog  (actual 3530/5069 69.6% )

Almost 20%  of pombe proteins have a disease gene ortholog (20%T would be 1013 and we are currently at 902  but we need to add the ones in the DO tracker... we will get there...).

**Comment by ValWood** [comment]
I thought you meant the man's arms.... I was thinking "but he's perfectly  proportioned?", but you mean the chromosome arms!

**Comment by Antonialock** [comment]
xD oh yes, should have disambiguated the terms

**Comment by jmcmurry** [comment]
heh; if *only* there were a cross species anatomy ontology to disambiguate. (Just kidding)

**Comment by ValWood** [comment]
Hi @jmcmurry ,I noticed last week that Monarch   doesn't use DO, but used "MONDO"

Since we are hoping to work with Monarch   we should  also link to MonDO from our disease ontology pages. Does Monarch provide a mapping from MONDO to DO?

We had a  quick look at MONDO on our last call, and we  thought that MONDO is broader in scope than DO is that correct?

Cheers,

Val

**Comment by ValWood** [comment]
Which of the tasks still needs to happen to release the new disease associations? I got a bit lost.

**Comment by ValWood** [comment]
Moving the MONDO mapping query to a new ticket.

**Comment by kimrutherford** [comment]
> Which of the tasks still needs to happen to release the new disease associations? I got a bit lost.

I still have a bit of work to do getting the display right.  Mostly it's missing "PomBase" source column.  Should be done tomorrow.

In the meantime it doesn't look too bad:
![disease-section-1](https://user-images.githubusercontent.com/90474/50763539-ec663a00-12d4-11e9-8f1d-dbe4d69c29d9.png)

That's from the site running on my desktop: http://pombase2-kmr.bioinformatics.nz/gene/SPCC1183.03c

The mapping from the disease association terms to DO isn't active in the nightly loads yet.  It's ready to go any time.  The data visible at http://pombase2-kmr.bioinformatics.nz was from a test load I did a few weeks ago that does have the mapping active.  I can do another test whenever it's needed.

**Comment by ValWood** [comment]
OK great we can chat on thurs and hopefully will be able to check before.

**Comment by kimrutherford** [comment]
I think everything's done on the software side now.

**Comment by kimrutherford** [comment]
I haven't committed the final changes yet so the dev and main sites are still using the disease associations from the contig files.  The changes I haven't committed are:
 - activate Antonia's mapping file
 - config for using DO in the search
 - config for showing the DO section on the gene and reference pages

Let's chat on Thursday about what else needs doing.

**Comment by ValWood** [comment]
I don't think anything else needs doing, (other things, like MONDO mapping, are additional and can happen later). So you could get this on dev so we can give it a once-over before release.

**Comment by kimrutherford** [comment]
OK, I've committed the final bits.  It should be ready by tomorrow morning on pombase-dev.  I'll check it when it's done but I won't re-release the main site until you have had a look too.

**Comment by ValWood** [comment]
OK, this seems fine.
Will check tomorrow!
http://pombase2-kmr.bioinformatics.nz/
All looking good though!

**Comment by kimrutherford** [comment]
> http://pombase2-kmr.bioinformatics.nz/

I ran an load on my desktop including the new mapping file and the other changes.  It all worked fine so I'm hoping the nightly load will be OK too.

**Comment by kimrutherford** [comment]
The Chado load worked with Antonia's mapping file so the new disease stuff is live in pombase-dev.  eg.
http://pombase-dev.bioinformatics.nz/gene/SPCC1183.03c
http://pombase-dev.bioinformatics.nz/term/DOID:0050950

**Comment by ValWood** [comment]
exciting 907!
Antonia you can go ahead with announcements after live.

**Comment by kimrutherford** [comment]
> Antonia you can go ahead with announcements after live.

Should I update the main site or is there more to do?

**Comment by ValWood** [comment]
You can  update the main site The rest is embellishments ( waiting for new terms, the MOND mapping etc)

We can use the pic above for twitter and tiny icon, and a more polished one for the "resource spotlight"

**Comment by Antonialock** [comment]
news item created, facebooked @kimrutherford can tweet?

**Comment by ValWood** [comment]
Also need a "resource spotlight"  We will put the rotation back on. I'll open a ticket for that.

**Comment by kimrutherford** [comment]
> @kimrutherford can tweet?

Done!

**Comment by ValWood** [comment]
On the front page news item can we hyperlink Julies name to https://pixabay.com/en/users/mcmurryjulie-2375405/

**Comment by kimrutherford** [comment]
> On the front page news item can we hyperlink Julies name

I've made that change.
