### ISSUE TITLE
phenotypes, condense deletion display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#102]
srp1delta(deletion) becomes 	srp1Δ

**Comment by ValWood** [comment]
Closing as genotype is not yet displayed.

**Comment by mah11** [comment]
??? 

genotypes are displayed when you click "show details" and then "genotype details"

**Comment by ValWood** [comment]
I don't see the problem I reported  (at least I don't think I do, not  *quite* sure if things have changed since then so that it is now a non-issue)
