### ISSUE TITLE
ideas for multigene genotype display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#103]
Had a quick chat with Kim this morning. He mentioned it might be possible to unclutter this further by not displaying the "gene":

![disambiguation](https://cloud.githubusercontent.com/assets/7359272/20978560/2db7a9f8-bca1-11e6-98fa-ff09acd7fab2.jpg)

so in tis instance it would be fine not to display the gene, except
i) we need to hyperlink it
and
ii) not all genes have the gene name in the genotype name (although all of these do)

So, we were wondering how common it is not to have the gene name in the genotype, and for these the gene could be in parentheses after the name. However this would mena hyperlinking part of the geneotype to link to the gene pages which might look strange?

@mah11 
@Antonialock 
thoughts?

**Comment by ValWood** [comment]
- [ ]   sort  within geneotype allele rows alphabetically

**Comment by ValWood** [comment]
- [ ]   one of the above alleles has (wild type) but more generally it is hidden...I wonder why that one is different... maybe it is  different somehow in  the session?

**Comment by mah11** [comment]
Re gene name display, hyperlinking etc. - would it be terrible to just display the allele names on gene pages, and have the genotype link to a genotype page for all the gory details? People should be getting familiar with that sort of thing via Canto ...

**Comment by ValWood** [comment]
Good plan. 
Minimally I'd still like to see     cdc2-33(A177T)  not just   cdc2-33 though, (I think?... but maybe its not completely necessary in this view.... especially if we do other clever stuff with amino acid variation linked to phenotypes in a protein browser view, but I'm getting carried away.....)
 
I can't remember what we do in Canto now I'll need to look!

**Comment by ValWood** [comment]
Yeah, we could def miss the "allele descriptions" out of the collapsed view couldn't we....
http://www.pombase.org/spombe/result/SPBC11B10.09#fission_yeast_phenotype-multi_allele

**Comment by mah11** [comment]
yes, allele description hidden in compact (with mouseover?) and show in full view sounds good

**Comment by ValWood** [comment]
- [ ]  Don't hyperlink an allele to its own gene  page

**Comment by ValWood** [comment]
relayed to
https://github.com/pombase/website/issues/53

**Comment by ValWood** [comment]
I don't think we need this ticket?
