### ISSUE TITLE
are we updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1034]
`i was  waiting for some changes...

**Comment by ValWood** [comment]
I don't think we got an update last night so I just wanted to check if there was a problem. LAst paper on the feed was a while ago too although that is probably correct...

**Comment by mah11** [comment]
It did update last night - the old-news clearout I did yesterday has taken.

**Comment by mah11** [comment]
... and the most recent in the community curation feed is one I approved just before I disappeared for beerfest

**Comment by ValWood** [comment]
OK i presume my changes will come through tomorrow...

**Comment by kimrutherford** [comment]
If you don't see your changes in the morning, please let me know and I'll investigate.

**Comment by ValWood** [comment]
I probably committed my changes after the deadlin...especially now we are in british winter time...I guess it's a bit earlier now...
