### ISSUE TITLE
new news item

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1035]
News item:
Fission yeast transmembrane transport overhaul
The Gene Ontology “transmembrane transport” branch has recently been substantially revised. In line with these revisions,  PomBase has standardised the product descriptions, and overhauled the GO annotations to be as complete and comprehensive as possible based on current knowledge.

 icon courtesy of reactome<<link Sidiropoulos et al. 2017 PMID: 29077811>>
I'll put the icon in the drop box. It is called "antiporter.png"

**Comment by ValWood** [comment]
No, I need to put this image somewhere else.....

**Comment by ValWood** [comment]
but where....

**Comment by ValWood** [comment]
It's this anyway ![antiporter](https://user-images.githubusercontent.com/7359272/48781080-2d799f00-ecd3-11e8-9233-12c1eb3dd6a1.png)

**Comment by mah11** [comment]
Done.

Dropbox is OK for short term as long as they're cleared out once in a while. But the "real" location is https://github.com/pombase/website/tree/master/frontend/src/assets/newsfeed

**Comment by ValWood** [comment]
ahhhh....I was looking in svn....

**Comment by ValWood** [comment]
Three are probably better transporters too!

**Comment by kimrutherford** [comment]
The news item is on the front page now.

**Comment by ValWood** [comment]
link should be to
https://www.pombase.org/term_genes/GO:0055085
not to Amigo

**Comment by ValWood** [comment]
canwe also add
icon courtesy of reactome<<link Sidiropoulos et al. 2017 PMID: 29077811>>
(i will probably dip into these a lot)
