### ISSUE TITLE
2 retrospective news items

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1037]
I should have done these at the time, a) for people who don't tweet and b) the news feed might be a more permanent archive that reviewers and funders could look at /use  as part of metrics (news letters count to this, but I doubt twitter feeds will ever be a metric!). So we should be more comprehensive about reporting things we do/did/done. Remember to news item all teaching/publications/  where possible....anything that can contribute to metrics. We can think of creative ways to make them "News"

Celebrating 20 years of GO. PomBase curators are major contributors to GO (ontology content, annotations and QC procedures) and co-authors on the new GO paper. This manuscript is the current GO paper to cite, with PomBase for use of Gene Ontology Data in your analysis.
Date
8-11-2018 which is the date GO  tweeted it 
with GO icon

AND

RNA central
The RNA central consortium have published an NAR database update. PomBase is an RNA  Central consortium member... all of the cirated non-coding RNAs from PomBase should appear in RNA Central soon.
link https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gky1034/5160993
link https://rnacentral.org/search?q=pombe check out the useful faceted search
6-11-2018 the data RNA central tweeted it.

**Comment by ValWood** [comment]
assigning to @mah11   for sanity checks

**Comment by mah11** [comment]
OK, here's your sanity check ;)

- dates in ISO format (yyyy-mm-dd), please, to avoid ambiguity

- I don't see graphics for these in Dropbox or the assets/newsfeed directory. I can find and resize a GO icon easily enough, but what do you want to use for the RNA Central item?

I'll also do my usual text edits when I create the items.

**Comment by ValWood** [comment]
here you go

![rna central](https://user-images.githubusercontent.com/7359272/48839258-c1567400-ed82-11e8-9074-2ccf513027e8.png)

**Comment by kimrutherford** [comment]
Thanks Midori.

Val, I assume you'd like these to go live straight away?

**Comment by ValWood** [comment]
yep...
