### ISSUE TITLE
add presence/absence of TMM domains to QuilT

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1038]
Should be easy.  I would make them very dark for present (black or close) and white for absent (as in the figure 3)

**Comment by kimrutherford** [comment]
I've had a go at this and it's live on the main site.  Let me know if you spot any problems.

I've made a "not applicable" category for non coding genes.  It's a pale colour to make it look a bit different to the other two.  Currently "not applicable" includes pseudo genes.  Does that make sense?  All of this is easy to change.

![tm-domains-quilt-2](https://user-images.githubusercontent.com/90474/48929692-054aa400-ef50-11e8-8a50-7c0a48965cda.png)

**Comment by ValWood** [comment]
TMMs perfect.

Good point about ncNRA's. I never used it with those, they are off my radar!

**Comment by ValWood** [comment]
The ncRNA unsurprisingly look very different!

**Comment by ValWood** [comment]
was announced on pombelist
