### ISSUE TITLE
Improve gene page search result titles

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1039]
When searching in google, "pom1" pombase link doesn't even show in the first 4 pages (I didn't look further)....AspGD pom1 is on page 2.

When searching for the sysID ensembl fungi is the top hit....(and second, pombase is 4th)

<img width="937" alt="screenshot 2018-11-22 at 12 54 40" src="https://user-images.githubusercontent.com/12727506/48904412-2dee7300-ee56-11e8-989a-90fe8a4cae01.png">

Can we set the page title to include the product description?

e.g. pom1 - DYRK family cell polarity protein kinase Pom1

To see if this makes us more findable?

50% of our users come in via google searches :-) 

The product description does show when mousing over the page when open in a tab, so perhaps the <page> tag is already set to display this? 

<img width="642" alt="screenshot 2018-11-22 at 12 58 57" src="https://user-images.githubusercontent.com/12727506/48905003-38117100-ee58-11e8-9b9d-c5488dd4b85c.png">

**Comment by kimrutherford** [comment]
That's not good.  I'm confused because the publication pages have a nice description in the Google search results but gene pages don't.  As far as I can tell we're adding the title and header descriptions in the same way in both cases.

Anyway, I found a how-to that suggests adding some extra header metadata to add for Google.  I've added that code.  The logs show when Google visits pombase.org pages so I'll have a look on Monday to see if there are any changes in the search results for gene pages that Google has downloaded over the weekend.

**Comment by Antonialock** [comment]
Fab. There seems to be a black box in between adding keywords, meta tags, page titles and what nots to what is actually displayed...

Hopefully this will boost our positioning in the search results (I don’t even see us now unless I include the word pombase in the search) I’m sure we were quite high while at the EBI 


It is just strange...how can we not be one of the top hits for a search for a fypo term?

**Comment by Antonialock** [comment]
![5f581f6f-eab9-4c61-9697-7105b6983c72](https://user-images.githubusercontent.com/12727506/48934304-59776900-eefb-11e8-9483-375c44e8600a.jpeg)

**Comment by kimrutherford** [comment]
> It is just strange...how can we not be one of the top hits for a search for a fypo term?

I wonder if we could arrange for QuickGO, Amigo or Bioportal to link to our term pages?  That would definitely help our Google ranking.

**Comment by Antonialock** [comment]
@ValWood @mah11

**Comment by ValWood** [comment]
I don't think we could realy ask QuickGO and GO to link to our term pages. We aren't the ontology maintainer and the don't do this for any other MOD term page.

However, for FYPO I think we definitely could  ask bioportal and OLS

Great detective work Antonia. So  this may partially explain our hits drop.... I wish we knew how many people found us via google search before we migrated...... It is definitely worth optimising this. 

I thought Google worked largely by  presenting the link that most people used previously, but do  more used sites generally get additional weighting? 

We should be the top hit for any PomBase ID, definitely worth spending some time on. we have almost disappeared....

**Comment by ValWood** [comment]
I don't find PomBAse  pom1 page with a SPAC2F7.03 in the first 4 pages...it seems that gene pages are not recognised at all?

**Comment by kimrutherford** [comment]
Google retrieved  any1 / SPBC18H10.20c a few hours ago and now the search result doesn't look too bad.  Hopefully things will improve now.

![gene-seo-improvement-1](https://user-images.githubusercontent.com/90474/48967469-d0b91400-f045-11e8-809b-d6dc38178fcf.png)

**Comment by ValWood** [comment]
SPAC2F7.03
still doesn't find the PomBase page for me.....

**Comment by kimrutherford** [comment]
As well as fixing things so that preview site pages redirect to the main site (#1040), the old gene page URLs now redirect to www.pombase.org/gene/...

The old pombase.org gene page URLs looked like:
 https://www.pombase.org/spombe/results/SPAC2F7.03c

but we now use www.pombase.org/gene/SPAC2F7.03c etc.

When we switched to the new site I made the old URLs be aliases for the new URLs.  So https://www.pombase.org/spombe/results/SPAC2F7.03c would show a gene page as usual.

I added the alias to support sites like:
http://interactome-cmp.ucsf.edu/pombe2012/modules/genes/SPAC10F6.08C.html
which still use the old URLs.

So the old URLs used to be an alias but now they redirect to the real URLs.  That should help with our Google rankings for gene pages.

Thanks Antonia for the link (https://moz.com/learn/seo/redirection).  I hadn't thought about how the old URLs and the preview sites could make a difference to the site SEO.

**Comment by kimrutherford** [comment]
Perhaps we can arrange for NCBI to link to the gene pages?

SGD and FlyBase are linked to as the "Primary source" here:
https://www.ncbi.nlm.nih.gov/gene/852457
https://www.ncbi.nlm.nih.gov/gene/?term=CG7895

PomBase should be the primary source for pombe genes, shouldn't it?

There are lots of link-outs for human genes:
 https://www.ncbi.nlm.nih.gov/gene/1017

InterMine is there along with a bunch of companies.
For human genes HGNC is the "Primary source".  Ensembl and Vega links are under "See related"

**Comment by ValWood** [comment]
Agreed, I am sure I wrote to the NCBI about this about 6 months ago. Antonia could you try next week with these examples.

And STRING. I mailed them a few times, they didn't reply. They link to Ensembl and don't display  IDs correctly (use a mixture last time I looked). They link to SGD.

**Comment by ValWood** [comment]
> Agreed, I am sure I wrote to the NCBI about this about 6 months ago. 

Actually I didn't write about this. I wrote about proteins linking to PomBAse transcript IDs.
ENA add these links unfortunately......

But ncbi used to link to PomBAse from genes I'm sure.... anyway need to be added...

**Comment by kimrutherford** [comment]
Google Search Console was reporting that our pages weren't mobile friendly.  A few days ago I tweaked the font sizes on small screens.  The warning has gone for recently indexed pages.

@Antonialock could you have a quite check on your phone to make sure I haven't made anything worse?  It looks slightly better on my (Android) phone.

**Comment by ValWood** [comment]
check spac17h9.07 before closing.
results improved, but no product line appearing

**Comment by Antonialock** [comment]
font size looks ok on my screen....product line still not appearing in search result for the gene I tried

**Comment by kimrutherford** [comment]
> I don't find PomBase pom1 page with a SPAC2F7.03 in the first 4 pages

For me pombase.org is now the fourth result for SPAC2F7.03 and the title looks better.

> check spac17h9.07 before closing.

That one is still not good.

We're slowly getting there.

**Comment by ValWood** [comment]
pom1 is number 3 for me now. Need to be above EF ;)

spac17h9.07 is now number 2 for me, after Bahler lab...

Crazy how this works....

**Comment by Antonialock** [comment]
in a private browser spac17h9.07  is number 1 before bahlerlab and pom1 number 4 after wikipedia, uniprot and ncbi

fantastic! 

The product line shows, and some random text from the gene page, which (I think) is better than the generic text not specific to the gene (although it *is* good to say that 'we are the authority on pombe').

Don't think the description can get better than this without gene summaries...

thanks!
