### ISSUE TITLE
separation of single/multigene phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#104]
Kim pitched another idea !

He thought we could combine multi and single allele phenotypes (still keep cellular vs population split), and  have a set of filters to display

Only single/ multi
and then other filters as appropriate (conditions), allele type for single gene, etc

We weren't sure  how this would look but it might be worth a try. At present all of the phenotype data is  displayed as a single blob.

Kim- probably the best thing to do here is to  all of the other parts of streamlining the display
and leave the  multi-single split until the end?

I like the idea of being able to see the single and multi gene mutants for a single phenotype simultaneously, but the display will  need to be a bit cleverer.

**Comment by Antonialock** [comment]
I don't think i like that idea, I think it will look confusing in some cases.

e.g.
yfg1-delta = sensitive to MMS
yfg2-delta = normal growth on MMS
yfg1-delta + yfg2-delta = normal growth on MMS

in this case, I'm sure that some users will get confused when they land on the yfg1 page and the first thing they see is that it is annotated to normal growth on MMS.

I KNOW they can filter etc, and it won't be a problem for our power users. But I think more users need the information more spoon fed and less in a big table. 

I could be wrong but I think what we think is obvious is not obvious to many people (for example, spotting that not all alleles are deletion mutants, seeing that different annotations have different conditions attached etc it seems like mixing the single and multi gene phenotypes might add more confusion to the mix. 

Personally I don't mind, and if you want to go with that then that's cool, but I think it might make it harder-to-get for some people (though arguably maybe they should just spend a bit of time learning to navigate the pages better...)

**Comment by ValWood** [comment]
I'm still now sure.
I can see there could be occasions where it  would be useful  to see single gene  and multigene to the same term  simultaneously....
I was hoping that Kims  suggestion would make this possible in a way that would be clear (the multigene filter would need to be as prominent as the current suumar/full  filter for this to worm.

and...I'm still not sure.

Maybe we will be able to judge better  once the other section changes are in place (i.e Kim can leave the splitting  single-multi until last, unless this over complicates the display).

**Comment by ValWood** [comment]
I'm not sure maybe separate sections are the only way to keep these manageable.

Look at the "full" phenotypes for cdc2
http://pombase2.aska.gen.nz/gene/SPBC11B10.09
(its 99 screens in my browser!).

I know this will come down as Kim jiggles with the formatting....but these are still going to be HUGE lists

**Comment by ValWood** [comment]
OK we decided to keep separate sections (I think, at least for now)

Filtering will allow users to look at subsets of data (i.e particular alleles or terms) from both single and multigene simultaneously. If they want to  do any more than simultaneously   then they probably don't require our help ....
