### ISSUE TITLE
Improve publication search results

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1040]
When I search for a PMID -26776736 in this case pombase-preview.babraham is high in the list (search result 2). Pombase.org doesn't feature on the first 5 pages.

<img width="846" alt="screenshot 2018-11-22 at 13 15 20" src="https://user-images.githubusercontent.com/12727506/48905252-f1704680-ee58-11e8-8933-adbda4a08a69.png">

If I include "pombase" in the search, pombase is first, preview second, and uniprot protein page is third

<img width="791" alt="screenshot 2018-11-22 at 13 15 42" src="https://user-images.githubusercontent.com/12727506/48905294-0e0c7e80-ee59-11e8-9aa7-cedc0a8b543c.png">

Odd that the preview site scores higher than pombase! Can we make this one invisible from google and can we improve the main pombase search result?

(I wasn't using an incognito window)

**Comment by kimrutherford** [comment]
I just tried a Google search for PMID 26776736 and got no results.  Very strange.

I'll ask Jon at Babraham to disable preview.pombase.org and pombase-preview.babraham.ac.uk.  If they are disabled I think they will quickly disappear from the Google results.

We still have pombase-dev.bioinformatics.nz for testing.  There are some Google search hits for pombase-dev.  I should be able to fix that.

**Comment by ValWood** [comment]
oddly when it does show up, as with SPCC4G3.05c

I see this:
![pombase](https://user-images.githubusercontent.com/7359272/48948638-17ffb180-ef2d-11e8-80e4-30a681b54e76.jpg)

note: Pombase > PomBase

**Comment by Antonialock** [comment]
Would a 301 redirect be better than disable?

**Comment by Antonialock** [comment]
According to this page a 301 redirect transfers the ranking power of old url to new url

https://moz.com/learn/seo/redirection

**Comment by kimrutherford** [comment]
> I tried to configure the web server to do that yesterday. I mucked things up which is when you
> spotted that www.pombase.org was offline. :-)

That for the prod Antonia.  I've had another go at this and the redirection works now.  I only broke the main site 5 or 6 times while trying to get the right configuration.

Now if you go to a page at preview.pombase.org or pombase-preview.babraham.ac.uk it does a permanent (301) redirect to correct page on www.pombase.org.  That should mean that Google will notice take those preview pages out of the results next time they are visited.

Unfortunately the pombase-preview links from the Google search say "Your connection is not secure" in Firefox even though they just redirect.  Even a redirect has to be secure.  There isn't an easy way to fix that.  I'm hoping the links will quickly disappear from the search results soon now that they are redirects.

**Comment by ValWood** [comment]
improving already. SPAC2F7.03c id fourth hit now , before it wasn't even on the first two pages....

**Comment by Antonialock** [comment]
Thanks Kim!

I'm having a browse right now.

In an incognito window (firefox) for SPAC4G9.03
genedbspombe is the second hit
www.genedb.org/genedb/Dispatcher?formType=navBar...desc...SPAC4G9.03

it redirects to pombase.org....should these also redirect to the right gene page?

**Comment by ValWood** [comment]
SPAC4G9.03

was the top hit for me incognito (an the actual page?) (chrome)

still says 
SPAC4G9.03 - Pombase

not
SPAC4G9.03 - PomBase

**Comment by kimrutherford** [comment]
> it redirects to pombase.org....should these also redirect to the right gene page?

I don't know why GeneDB redirects to pombase.org.  Any ideas Val?

Is this a typo?:

> still says
> SPAC4G9.03 - Pombase
> not
> SPAC4G9.03 - PomBase

**Comment by kimrutherford** [comment]
For SPAC4G9.03 I get the PomBase page and a good description as the first hit:
```
PomBase - Gene - adk1 (SPAC4G9.03) - adenylate kinase Adk1
```

Maybe there's a lag?

![gene-seo-improvement-2](https://user-images.githubusercontent.com/90474/48984381-ba9f7680-f15f-11e8-84b2-d5f1266e59a2.png)

**Comment by Antonialock** [comment]
odd! I see this:

<img width="474" alt="screenshot 2018-11-25 at 21 25 54" src="https://user-images.githubusercontent.com/12727506/48984833-d58ad000-f0f8-11e8-9bfc-822cccd80d40.png">

but result number 1 - result! 

Another oddity:

when I search for adk1 pombe, the result says "missing: pombe" from pombase....The page description mentions pombe? So I don't see why this is.

<img width="403" alt="screenshot 2018-11-25 at 21 30 25" src="https://user-images.githubusercontent.com/12727506/48984873-577af900-f0f9-11e8-9211-465e1b7d1a63.png">


What this means is that if you force it to include pombe then we drop out of the search results (although trusty old genedb is there redirecting to pombase.org :-) ...).

<img width="683" alt="screenshot 2018-11-25 at 21 29 32" src="https://user-images.githubusercontent.com/12727506/48984867-4af6a080-f0f9-11e8-8fb5-9f936523ff00.png">

**Comment by Antonialock** [comment]
maybe we need to include pombe as a keyword/tag? But I thought it is ugly to have the same keyword/tag for every page?

**Comment by Antonialock** [comment]
> > it redirects to pombase.org....should these also redirect to the right gene page?
> 
> I don't know why GeneDB redirects to pombase.org. Any ideas Val?
 
is this something we need to ask Sanger to fix?

**Comment by Antonialock** [comment]
if it is as simple as a keyword or tag thing then we should probably include fission yeast too

<img width="680" alt="screenshot 2018-11-25 at 21 37 23" src="https://user-images.githubusercontent.com/12727506/48984965-5bf3e180-f0fa-11e8-8a2d-d9c185229a4c.png">

**Comment by kimrutherford** [comment]
Now I'm seeing just "SPAC4G9.03 - Pombase" in the results.  Let's check again tomorrow.  I might just need time to settle down.

> when I search for adk1 pombe, the result says "missing: pombe" from pombase....The page
> description mentions pombe? So I don't see why this is.

Maybe that will work OK once the pages have been reindexed with the description included.

When I search for "any1 pombe", the PomBase gene page is the top.  But "any1 fission yeast" doesn't find the gene page.

For some pages fission yeast work. eg. syj1 fission yeast

I'll keep an eye on the gene results over the next week or two.

**Comment by Antonialock** [comment]
yeah probably just need to let it settle and see if it is still an issue....these words are everywhere :-)

<img width="1303" alt="screenshot 2018-11-25 at 22 18 50" src="https://user-images.githubusercontent.com/12727506/48985516-310c8c00-f100-11e8-89c1-497a02272cea.png">

**Comment by Antonialock** [comment]
figure out why the genedb links don't link to the correct pombase pages?

that isn't going to happen......

Why not?
--
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
It just won't. Nobody is working on it.... (It will be folded into FungiDB, I'm guessing)

**Comment by ValWood** [comment]
Actually I could ask since some links are published in papers, forwarding should be permanent.

**Comment by kimrutherford** [comment]
As far as I can tell, all the GeneDB pombe page just redirect to www.pombase.org:
https://www.google.com/search?q=pombe+site:genedb.org&client=ubuntu&hs=gvE&channel=fs&filter=0&biw=1228&bih=716

**Comment by kimrutherford** [comment]
> If I include "pombase" in the search, pombase is first, preview second, and uniprot protein page is third

Now when I search for 26776736 pombase the preview is gone.  That's a good sign.

**Comment by ValWood** [comment]
Do you know why it still says Pombase, not PomBase?

**Comment by ValWood** [comment]
I see 👍 
above PomBase :)
Be careful what you write here ;)

Improve publication search results · Issue #1040 · pombase/website ...
https://github.com/pombase/website/issues/1040
When I search for a PMID -26776736 in this case pombase-preview.babraham is high in the list (search result 2). Pombase.org doesn't feature on the first 5 ...

**Comment by ValWood** [comment]
I still see preview, we must be behind you!

**Comment by kimrutherford** [comment]
www.pombase.org is now the top hit when searching for:
 26776736 pombase.

**Comment by ValWood** [comment]
Fab. I have noticed most things have percolated up, and the analytics seem to be improving, but not enough to say it is due tot eh changes yet.

**Comment by kimrutherford** [comment]
Amusingly this issue is now the second result when searching for: 26776736 pombase

**Comment by Antonialock** [comment]
Kim the annotations loaded using the generic  loader don't have PomBase as the source

**Comment by kimrutherford** [comment]
> Kim the annotations loaded using the generic loader don't have PomBase as the source

Could you give me an example?

**Comment by Antonialock** [comment]
I have no idea why I put that in this ticket....I'll find another one or open a new

**Comment by Antonialock** [comment]
I'll close this issue, there doesn't seem to be anything directly left to do? We can keep monitoring and open a new one if anything else should be attempted.
