### ISSUE TITLE
add items to About pulldown in header menu bar

### ISSUE THREAD

**Issue by mah11** [pombase/website#1049]
The left-hand menu on https://www.pombase.org/about lists 

- Citing PomBase
- PomBase Publications
- Terms of Use
- Privacy Policy
- Help
- Resource metrics

Of these, only Citing PomBase and Resource Metrics appear in the "About" pulldown in the header. In #893 Val expressed a desire to see the PomBase Publications added. 

@ValWood to list which items to add to the header menu (all of 'em, just the pubs, or some other selection?), and in what order; @kimrutherford to do the edits (I'm punting because this is more fiddly than most edits, so I'm a bit paranoid about breaking it).

(Note: the main body of the About page has a few items that aren't even in the left-hand sidebar on the page itself, but no one has complained about that yet. All of them simply link to other pages, which also have links from other pages.)

**Comment by ValWood** [comment]
Just PomBaase publications...

**Comment by kimrutherford** [comment]
> Just PomBaase publications...

I've done that.
