### ISSUE TITLE
PomBase Publications

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1050]
The list
PomBase Publications

Needs a section

PomBase co-authored collborative papers (or similar)
for the GO, RNA central etc...

I can add a list of these if required

**Comment by mah11** [comment]
> I can add a list of these if required

yes please ... PMIDs will do for anything that has 'em

**Comment by ValWood** [comment]
We should add everything since 2010

AnGeLi: A Tool for the Analysis of Gene Lists from Fission Yeast.
Bitton DA, Schubert F, Dey S, Okoniewski M, Smith GC, Khadayate S, Pancaldi V, Wood V, Bähler J.
Front Genet. 2015 Nov 16;6:330. doi: 10.3389/fgene.2015.00330. eCollection 2015.
PMID: 26635866 

An Ancient Yeast for Young Geneticists: A Primer on the Schizosaccharomyces pombe Model System.
Hoffman CS, Wood V, Fantes PA.
Genetics. 2015 Oct;201(2):403-23. doi: 10.1534/genetics.115.181503. Review. Erratum in: Genetics. 2016 Mar;202(3):1241.

A genome-wide resource of cell cycle and cell shape genes of fission yeast.
Hayles J, Wood V, Jeffery L, Hoe KL, Kim DU, Park HO, Salas-Pino S, Heichinger C, Nurse P.
Open Biol. 2013 May 22;3(5):130053. doi: 10.1098/rsob.130053.
PMID: 23697806 

Augmented annotation of the Schizosaccharomyces pombe genome reveals additional genes required for growth and viability.
Bitton DA, Wood V, Scutt PJ, Grallert A, Yates T, Smith DL, Hagan IM, Miller CJ.
Genetics. 2011 Apr;187(4):1207-17. doi: 10.1534/genetics.110.123497. Epub 2011 Jan 26.
PMID: 21270388 

The Gene Ontology Resource: 20 years and still GOing strong.
The Gene Ontology Consortium.
Nucleic Acids Res. 2018 Nov 5. doi: 10.1093/nar/gky1055. [Epub ahead of print]
PMID: 30395331

Expansion of the Gene Ontology knowledgebase and resources.
The Gene Ontology Consortium.
Nucleic Acids Res. 2017 Jan 4;45(D1):D331-D338. doi: 10.1093/nar/gkw1108. Epub 2016 Nov 29.
PMID: 27899567 

Gene Ontology annotations and resources.
Nucleic Acids Res. 2013 Jan;41(Database issue):D530-5. doi: 10.1093/nar/gks1050. Epub 2012 Nov 17.
PMID: 23161678 


15.
The Gene Ontology: enhancements for 2011.

Gene Ontology Consortium.

Nucleic Acids Res. 2012 Jan;40(Database issue):D559-64. doi: 10.1093/nar/gkr1028. Epub 2011 Nov 18.
PMID: 22102568 


19.
The Gene Ontology in 2010: extensions and refinements.

Gene Ontology Consortium.
Nucleic Acids Res. 2010 Jan;38(Database issue):D331-5. doi: 10.1093/nar/gkp1018. Epub 2009 Nov 17.
PMID: 19920128 

Gene Ontology Consortium: going forward.
Gene Ontology Consortium.
Nucleic Acids Res. 2015 Jan;43(Database issue):D1049-56. doi: 10.1093/nar/gku1179. Epub 2014 Nov 26.
PMID: 25428369

**Comment by ValWood** [comment]
RNAcentral: a hub of information for non-coding RNA sequences.

The RNAcentral Constortium .
Nucleic Acids Res. 2018 Nov 5. doi: 10.1093/nar/gky1034. [Epub ahead of print]
PMID: 30395267

(it really does say the RnA central constortium!)

**Comment by ValWood** [comment]
RNAcentral: a comprehensive database of non-coding RNA sequences.

The RNAcentral Consortium.

Nucleic Acids Res. 2017 Jan 4;45(D1):D128-D134. doi: 10.1093/nar/gkw1008. Epub 2016 Oct 28.
PMID: 27794554

**Comment by Antonialock** [comment]
24929579 ?

**Comment by ValWood** [comment]
yup, you can come update my CV...

**Comment by kimrutherford** [comment]
PHI-base?: https://academic.oup.com/nar/article/45/D1/D604/2631399

**Comment by mah11** [comment]
I added everything above, plus a few more I found.

**Comment by ValWood** [comment]
impressive!
