### ISSUE TITLE
NCBI linkouts

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1051]
There is a linkout section on this page. 
Apparently we are responsible for maintaining these?
https://www.ncbi.nlm.nih.gov/gene/2541889

I'll assign to Midori becasue it sounds as though it might be similar to the PMID linkouts?

**Comment by Antonialock** [comment]
yes but then we debated whether it is worth spending energy on this since we have the links at the top

**Comment by ValWood** [comment]
yeah might not be worth it if hassle. but if it can be done in a couple of hours may as well...

**Comment by ValWood** [comment]
@mah11  should we do this? I'm not even sure why they don't appear already? presumably it's a small extension to what you do already?

**Comment by mah11** [comment]
> presumably it's a small extension to what you do already?

Conceptually small, perhaps, but a larger amount of work than you might think. Our current LinkOut setup is configured in a very publication-centric way at both PomBase and NCBI ends. I've investigated enough to think it is possible to extend the configuration to genes (and maybe other things), but not enough to figure out how to do it - it would entail moderately extensive changes, and I would probably have to ask Lidia for advice.

So maybe it's worth doing, but there's no way it will fit in before Kim heads home, and after that  have a think about whether it's worth the time (likely more than a couple hours).

**Comment by ValWood** [comment]
ok, future, and then only if you feel like it....

**Comment by ValWood** [comment]
I don't know what this means now?
