### ISSUE TITLE
page not found error?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1053]
odd?

https://www.pombase.org/gene/SPBC29A10.15

**Comment by Antonialock** [comment]
I have seen that a few times today (a couple of times coming in from NCBI links...I can't remember if also from google) where did you come in from? 

They don't look like complete genes

<img width="226" alt="screenshot 2018-11-29 at 15 11 41" src="https://user-images.githubusercontent.com/12727506/49231159-424be600-f3e9-11e8-8b22-84e069f385e6.png">

**Comment by Antonialock** [comment]
Ahh...It must have to do with "redirect if there is a ".1" as part of the URL" :-(

**Comment by Antonialock** [comment]
SPBC29A10.15 


tries to go to
SPBC29A10 gene page

but SPBC29A10 doesn't exist

**Comment by Antonialock** [comment]
Every single gene contains one . as part of the sysID? so if you can make it clever enough to ignore .1 if it is following the first dot...?

**Comment by ValWood** [comment]
Yep its a new bug. This was internal, from a phenotype list.

**Comment by kimrutherford** [comment]
Sorry about that!  I think I've fixed it now.  You might need to reload.

**Comment by kimrutherford** [comment]
> Every single gene contains one . as part of the sysID? so if you can make it clever enough to ignore
> .1 if it is following the first dot...?

That's what I attempted to do, but failed.  :-)

We don't have any gene names that end in a dot then a single digit.  So that's what it looks for now.
