### ISSUE TITLE
Consider disabling the up/down stream bases if no exons selected

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1054]
It's hard to see a case where this would be useful:

![seq-download-label-2](https://user-images.githubusercontent.com/90474/49255613-6d8a1000-f491-11e8-8b5f-22bfbbb0b2fc.png)

**Comment by ValWood** [comment]
I don't think you need to do anything here.
What it does isn't wrong. We can discuss but I would be happy to close.

**Comment by kimrutherford** [comment]
> We can discuss but I would be happy to close.

Yep, I think so too now I've looked again.
