### ISSUE TITLE
not all diseases show

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1055]
on this page
https://www.pombase.org/term/PBO:5000000

for example, the disease nemaline myopathy doesn't show

<img width="279" alt="screenshot 2018-12-01 at 09 45 57" src="https://user-images.githubusercontent.com/12727506/49326699-18f89a80-f54e-11e8-9987-6eb29d5d133f.png">

act1 is annotated to this term. The association shows on the act1 gene page.

**Comment by Antonialock** [comment]
so do I need to assign a PBO ID when I add a new disease?

**Comment by Antonialock** [comment]
I think that part is automatic....

**Comment by kimrutherford** [comment]
> need to be updated manually? I was hoping it was automagic :-)

The system isn't great at the moment for terms associated with genes in the contig files.  The PBO ID is created automatically for new terms but it doesn't add the is_a(disease_associated) relation.

The hacky fix is to add the disease and annotation then come back in a day or two, check the website and get the PBO ID, then add it to the OBO file.

That process could be improved but we should be able to remove the disease_associated annotations and replace them with disease ontology annotations at some point?

**Comment by Antonialock** [comment]
yes, and I have the mappings for the really new ones....only things left 

1. need to map any of those 55 ones no previously mapped (I was only looking at the disease_associated ones)
2. waiting for some new DO term requests (we could ignore those until they have been created)

**Comment by ValWood** [comment]
> If not all diseases show then how can I map them?

good point

**Comment by ValWood** [comment]
> waiting for some new DO term requests (we could ignore those until they have been created)

I would proceed without these,  and add as  they arrive. It will be a good check that the update with a new term procedure is working

**Comment by kimrutherford** [comment]
It's looks better now: https://www.pombase.org/term/PBO:5000000

**Comment by Antonialock** [comment]
odd....

<img width="498" alt="screenshot 2018-12-02 at 12 45 56" src="https://user-images.githubusercontent.com/12727506/49339897-3e5dd500-f630-11e8-9bc9-93d6b32e29fe.png">

**Comment by Antonialock** [comment]
I think the PBO IDs have shuffled?

<img width="308" alt="screenshot 2018-12-02 at 12 57 38" src="https://user-images.githubusercontent.com/12727506/49340016-fcce2980-f631-11e8-8e6e-12aeeaa9134d.png">

**Comment by ValWood** [comment]
In some cases I fixed a spelling mistake where there would have been 2 terms.
I never deleted the existing term from the file so if somebody corrected the spelling on these later, it would result in 2 correctly spelled, one with no annotations.

(that said, I have no idea if these are they)

**Comment by kimrutherford** [comment]
> I think the PBO IDs have shuffled?

Unfortunately, yes.  The PBO IDs are assigned when a new term is seen while loading from the contig files.  The IDs change each load.

But if the term is loaded from an OBO file its ID will be consistent.  The ID in the OBO file will be used so the loader won't assign a new ID.

So now the terms are in the file the IDs will stop changing with each load.

> There are 55-ish disease_associated terms that weren't in pombe-embl/mini-ontologies/disease_associated.obo

Somehow I missed some terms when I was fixing up the file.  I added them before the load started so they'll be on the main site soon.

**Comment by Antonialock** [comment]
yay! 613 genes....

I got quite excited we had 613 disease associated, and their are 639 from malacards, but the overlap isn't very big

<img width="591" alt="screenshot 2018-12-03 at 22 00 43" src="https://user-images.githubusercontent.com/12727506/49404303-02696380-f747-11e8-9076-84484c734756.png">

I'll remap the stable IDs

**Comment by ValWood** [comment]
I got  over a 1000 when I did an overlap with their list and our list s this is close. I guess you weeded some out?  It will be exciting to release this ...

Good job...

**Comment by Antonialock** [comment]
How should we add new terms now Kim? 

On the call I think we agreed the best way would be to annotate to DOIDs
(for example controlled curation disease associated, DOID)

another way could be to manually assign a PBO ID and add it to disease_associated.obo but then we need to know what IDs are available

**Comment by Antonialock** [comment]
Actually we really shouldn't annotate to the old PBO IDs at all thinking of it. Sometimes we used a disease term, but I chose a more specific DOID after manual inspection of what genes we had annotated to the term. 

going forward it would be much safer to annotate to DOIDs

**Comment by kimrutherford** [comment]
Thanks for all the work.

> going forward it would be much safer to annotate to DOIDs

I think so too.

I'm not keen on adding more annotation to the contig files.  I'd like to move away from them.  Do we want to curate diseases in Canto?  Maybe as an annotator-only curation type?

**Comment by Antonialock** [comment]
yes but no but yeah but...

It would be possible but possibly slightly more inconvenient - I don't always look up a paper ref for an association (sometimes if the connection is really well known and existing in a database such a orphanet or OMIM I just add the connection - in these cases it would be straight forward to find an xref so it's not the end of the world - but there will be many cases where there is no PMID associated with the annotation)

**Comment by ValWood** [comment]
Yes - and it isn't always really appropriate to add a random ref, because the reference is often only for the disease, not for the association with the pombe gene.

Since the malacards data is in an external csv file what if we also maintain disease associations in a tab delimited file for now?

Later we can extend canto for unpublished curation (ISS etc), but we need a way  in the interim.

**Comment by kimrutherford** [comment]
> what if we also maintain disease associations in a tab delimited file for now?

Yep.  It might make sense to have a generic tab delimited annotation file format for the misc. annotation types.  With columns like:

- gene systematic ID
- term ID (could be any term from any ontology or CV)
- evidence (optional)
- publication (optional)
- date (optional)

It would be very easy to implement.

Does that sound useful?

**Comment by ValWood** [comment]
yes!

**Comment by kimrutherford** [comment]
OK, let's try that plan.  I'll make a generic loader.

**Comment by kimrutherford** [comment]
I've written a generic loader.  The file format documentation is here:
 https://github.com/pombase/pombase-chado/wiki/Chado-Loaders#generic

I think the new disease annotation would be a good test of the lodaer.  It just needs an annotation file checked into SVN to give it a go.

**Comment by kimrutherford** [comment]
The test load went well.  Here are the 89 warnings when loading into Chado using your mapping:
[disease_warnings.txt](https://github.com/pombase/website/files/2674884/disease_warnings.txt)

There are 89 warning but only 48 missing diseases:
[missing_diseases.txt](https://github.com/pombase/website/files/2674906/missing_diseases.txt)

Not too bad?

Do the warnings make sense?  Please let me know if there are any disease names in the warnings that should have been handled by the mapping file.

**Comment by Antonialock** [comment]
nice! Yes from spot checking a few and eye-balling others I think the missing ones make sense. 

In this case, did you put the term name in the term ID field?

**Comment by Antonialock** [comment]
ok I have added a file that you can try the generic loader on
pombase_disease_associations
in external_data⁩ ▸ ⁨disease

**Comment by kimrutherford** [comment]
> ok I have added a file that you can try the generic loader

Thanks.  That worked perfectly.

So we can add that to the nightly load whenever you like.  I think it won't change how the main site looks because we don't show disease ontology terms yet.  So maybe we should add it to the load soon?

**Comment by Antonialock** [comment]
Brilliant! Yep, may as well add it to the load - we can use dev to check how terms are displayed together with makacards annotations,  and that the slim works?

**Comment by kimrutherford** [comment]
Done!  I had the changes ready to go.

I'll check the load on Saturday to make sure I haven't broken anything.

Any errors should appear in a log file ending with `.disease_associations`

**Comment by kimrutherford** [comment]
Should we rename the "MalaCards disease association" section?  We'll soon have diseases associations from you as well as MalaCards.

![disease-1](https://user-images.githubusercontent.com/90474/49988481-b38bbb80-ffdb-11e8-8284-5f3ec2bc0eaf.png)

**Comment by Antonialock** [comment]
Yeah I think we could just call it disease associations, and hide details unless expanded?

**Comment by ValWood** [comment]
> Should we rename the "MalaCards disease association" section? We'll soon have diseases associations from you as well as MalaCards.

Yes, I'm sure this was an action in the old closed ticket.
Hopefully I can do this today.

**Comment by Antonialock** [comment]
> Hopefully I can do this today.

do what?

**Comment by ValWood** [comment]
Sorry that did not make sense. I will check the action items from the closed ticket

**Comment by kimrutherford** [comment]
> I'll check the load on Saturday to make sure I haven't broken anything.

That worked.  The annotations from `pombase_disease_associations.txt` are in pombase-dev now.  eg.
http://pombase-dev.bioinformatics.nz/gene/SPBC530.10c
http://pombase-dev.bioinformatics.nz/term/DOID:0080335

**Comment by ValWood** [comment]
when i search with 
neutropenia
i find 

poikiloderma with neutropenia (PBO:0011982)
but not
3-methylglutaconic aciduria with cataracts, neurologic involvement and neutropenia

it seems that PBO still uses the "old system"
http://pombase-dev.bioinformatics.nz/term_genes/PBO:0011982


so all of the data seems to be there, in the 2 separate systems:
http://pombase-dev.bioinformatics.nz/term/DOID:4

**Comment by kimrutherford** [comment]
> but not
> 3-methylglutaconic aciduria with cataracts, neurologic involvement and neutropenia

Is that when search in the query builder?  The auto-complete in the query builder only looks for disease_association terms.  I'll switch to disease_ontology once we're ready to flick the switch to remove the old disease annotations from Chado.

**Comment by ValWood** [comment]
got it, i think you explained that already ;)

**Comment by Antonialock** [comment]
Advanced search now shows DO.

There seems to be a problem with annotations loaded by the generic loader 

some do not show source: PomBase
e.g.
SPBC27B12.14		DOID:0080118		PMID:25008109	20181213
SPAC637.04	ypp1 	DOID:14671		PMID:29655802	20181213
SPAC19G12.12	dlp1	DOID:0070239			20181213

some do not show at all?
e.g. 
SPAC824.02	bst1	DOID:0060308			20181213
SPBC17A3.04c		DOID:0110173			20181213



This is the file loaded by the generic loader for disease associations:
external_data -> disease -> pombase_disease_associations

I presume I need to add the PBO ref yada to the ref column for these annotations?

**Comment by kimrutherford** [comment]
> I presume I need to add the PBO ref yada to the ref column for these annotations?

Yep, I think so.  I forgot about that file.

**Comment by kimrutherford** [comment]
I think this is all done now.
