### ISSUE TITLE
Have a genotypes page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#106]
A suggestion from Midori for discussion:

Re gene name display, hyperlinking etc. - would it be terrible to just display the allele names on gene pages, and have the genotype link to a genotype page for all the gory details? People should be getting familiar with that sort of thing via Canto ...

**Comment by kimrutherford** [comment]
We should talk about this before making more changes to the display of phenotype annotations.

**Comment by ValWood** [comment]
Summary

We want "genotypes" pages

The gene page will show the genotype in human readable form, much as the  "summary view" does now
i.e 
cdc2-3w (C67Y), cdc17-K42 (E298K)

cdc2Δ, puc1Δ, cdc2-cdc13 fusion (Prcdc13 cdc13-cdc2 -cdc13 terminator), cdc13Δ, cig2Δ, cig1Δ

But these will be hyperlinks to the genotype page.
The genotype page will provide the details.

**Comment by kimrutherford** [comment]
We now have genotype pages but they aren't complete:
  http://pombase2.bioinformatics.nz/genotype/d91d901cb0a83596-genotype-18

I've removed the "show details" buttons on the phenotype annotation tables on the gene pages and the genotype ID is now a link to the genotype details page.

There are a bunch of bugs that I'll fix on Monday:

  - [ ] The counts are all zero
  - [ ] On the genotype pages, the annotation are duplicated - there is a copy of the annotation of each allele (see the link above)
  - [ ] The ugly internal genotype IDs (eg. "d91d901cb0a83596-genotype-18") are still visible on the gene pages and on the genotype pages
  - [ ] The internal allele IDs are still visible
  - [ ] The cell and population heading appear even if there are no annotation of that type. Here is an example: http://pombase2.bioinformatics.nz/genotype/ce88fdccd4b3e0b0-genotype-10

Once all of that is fixed we should chat about the formatting of the page, especially the alleles section.

**Comment by mah11** [comment]
Cool - that's off to a good start :)

For these pages, do we even need to show the "genes" column with the annotations? I think not, because every annotation listed is one that's been associated with the whole genotype. That would avert problem 2 nicely, and tidy up the table.

**Comment by ValWood** [comment]
Looks fab so far.... very nice.

**Comment by kimrutherford** [comment]
> For these pages, do we even need to show the "genes" column with the annotations?

Good point.  I've removed that column.

> That would avert problem 2 nicely,

Unfortunately the duplicates are still there.

**Comment by kimrutherford** [comment]
> The cell and population heading appear even if there are no annotation of that type.

Fixed.

> On the genotype pages, the annotation are duplicated

Fixed.

**Comment by kimrutherford** [comment]
> The ugly internal genotype IDs (eg. "d91d901cb0a83596-genotype-18") are still visible on the gene pages and on the genotype pages
> The internal allele IDs are still visible

All fixed.  The internal IDs are gone and the genotype are identified by their long name - more or less as they appear in Canto.  Please let me know if you spot any that don't look right.

**Comment by ValWood** [comment]
Looks good.
So what is to do from this ticket as it stands...just counts?

**Comment by kimrutherford** [comment]
> .just "counts" ?

Yep that's the only thing left.  I'm working on it now.

**Comment by kimrutherford** [comment]
The numbers in the FYPO section are now the counts of the number of genotypes annotated with each phenotype.
