### ISSUE TITLE
updated version of community curation spotlight graph

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1063]
[papers curated (5).pdf](https://github.com/pombase/website/files/2664311/papers.curated.5.pdf)

**Comment by ValWood** [comment]
Looks like something has happened this year...

**Comment by Antonialock** [comment]
275 papers curated 2018 vs 300 in 2017

**Comment by ValWood** [comment]
well...although it would be nicer to be higher year on year, I thought we would be much lower this year  with all of the other projects....

**Comment by ValWood** [comment]
> 275 papers curated 2018 vs 300 in 2017

where di you get these numbers?

**Comment by Antonialock** [comment]
The stats page...this table


[cid:167b674807533c7092e1]
--
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by Antonialock** [comment]
285 v 302 now :-)

**Comment by ValWood** [comment]
I did ~10 really quick old ones yesterday because it was too cold to go outside, and there are ~10 in approval....

BUT, @kimrutherford  why did 2017 go up too, if this is "year curated" ?

**Comment by Antonialock** [comment]
did it?

**Comment by kimrutherford** [comment]
> BUT, @kimrutherford why did 2017 go up too, if this is "year curated" ?

The counts are for the year when the session are submitted - ie. when the go into the needs_approval state.  Could you have approved or re-approved some sessions that were first submitted in 2017?

**Comment by ValWood** [comment]
275 papers curated 2018 vs 300 in 2017

vs

285 v 302 now :-)

**Comment by ValWood** [comment]
> Could you have approved or re-approved some sessions that were first submitted in 2017?

definitely, but I thought they still had the first submitted date?

**Comment by Antonialock** [comment]
Very possible I rounded 302 to 300

**Comment by kimrutherford** [comment]
> definitely, but I thought they still had the first submitted date?

They do.  So if there is a session submitted in 2017 and you take it out of approval today, the 2017 count will go down in the table.  If you approve it later the 2017 count will go up.  Could that explain the 2017 number changing?

**Comment by ValWood** [comment]
@kimrutherford  can you do this one when you get chance, its only the image update

**Comment by kimrutherford** [comment]
I've update the image on the main site.  How does this look?

![new-community-curation-image-1](https://user-images.githubusercontent.com/90474/50437379-6f3eda80-094e-11e9-97e7-36e269f06d97.png)

**Comment by ValWood** [comment]
much better, and you can see that we are doing fewer of the newer papers..

**Comment by kimrutherford** [comment]
I think this is done now?
