### ISSUE TITLE
PBO to DOID mappings

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1064]
I added the mapping file

PBO_to_DOID_mappings

to mini ontologies directory for the disease terms

Unfortunately DO hasn't done a new release yet since I started requesting terms (it looks like quite a few of them have been added though) so it's missing quite a few of our diseases - at least it is something to try and load and then the mapping file can be updated once I have the IDs

**Comment by Antonialock** [comment]
added high priority because that was the priority on the old ticket

**Comment by kimrutherford** [comment]
Thanks Antonia.

I've moved the mapping file to the directory that has the other mappings.  So it's now:
 `pombe-embl/chado_load_mappings/pombase_disease_name_to_DOID_mapping.txt`

And I've also changed the PBO IDs in the file into disease names because it makes the loading easier.  I hope that's OK.

I'm now going to try a test load of Chado on my desktop with the new mapping file.

**Comment by kimrutherford** [comment]
What were you querying?  It's slow but it's working for the queries I tried.

**Comment by ValWood** [comment]
I could locate terms, but they all displayed zero annotation.
I tried cancer, and another one, I don't remember which but can try later.

**Comment by Antonialock** [comment]
I think it is because the advanced search still searchges annotations to PBO disease terms, the simple search searches DOIDs

**Comment by kimrutherford** [comment]
> My desktop version doesn't have any disease ontology terms loaded. So when you search for a disease
> you get a PBO term and they have no annotation, it's all mapped to DO.

Sorry, that's slightly gibberish.  Everything should be more sensible once I've fixed the other disease issues.

> Hopefully on Monday-ish.

Actually Tuesday-ish as I'm on holiday on Monday.

**Comment by kimrutherford** [comment]
> Once I've fixed some of the problems (mainly #1072 and #1071), I'll do a full load including your mapping file
> and deploy it on pombase-dev. Hopefully on Monday-ish.

I think everything is fixed now.  I've restarted my local load to use the new PB_REF that Midori added.  It should be ready to check on Wednesday morning (UK time).

**Comment by kimrutherford** [comment]
I think this is done except for:
> val asked if we could check what grouping terms we will lose, these include:

What do we need to do to check that?

**Comment by kimrutherford** [comment]
> I think it is because the advanced search still searches annotations to PBO disease terms, the simple
> search searches DOIDs

I've updated the Lucene index on my desktop so both the advanced search and search box should work now if you'd like to do more testing:
 http://pombase2-kmr.bioinformatics.nz/

**Comment by ValWood** [comment]
@kimrutherford  you don't need to worry about this. @Antonialock  will request any useful grouping terms from DO. This can happen later.

**Comment by ValWood** [comment]
I think this can close, @Antonialock  can you confirm?
