### ISSUE TITLE
still see Pombase

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1065]
When I search in a sys ID, I get  these 2 hits .

Onen for "gene" with all the correct info

and one for "resul"  with lowercase Pombase and without gene specific information

Is this still part of the 'flushing' process ?

![lc](https://user-images.githubusercontent.com/7359272/49888701-90280b80-fe37-11e8-9585-549f0064b0b1.jpg)

**Comment by kimrutherford** [comment]
The next time Google visits the .../spombe/result/... link it will spot that it is now a redirect to the real gene page.  It will then disappear from the search results.

**Comment by ValWood** [comment]
OK I think you explained that multiple times.

The optimization is really working... this is usually a quiet time of year but or hots are going up

**Comment by ValWood** [comment]
btw 

this performance search keeps popping up on the Google home page too

https://search.google.com/search-console/performance/search-analytics?utm_source=gws&utm_medium=onebox&utm_campaign=san&metrics=CLICKS%2CIMPRESSIONS%2CPOSITION&resource_id=https%3A%2F%2Fwww.pombase.org%2F&num_of_months=12

seems slightly different from our analytics, shows a steep rise...

**Comment by Antonialock** [comment]
I don't have access to see that performance search

<img width="754" alt="screenshot 2018-12-13 at 09 19 47" src="https://user-images.githubusercontent.com/12727506/49928547-45020d00-feb8-11e8-9124-4b63c8af756d.png">

**Comment by kimrutherford** [comment]
> I don't have access to see that performance search

I've just added you and Midori.  Does the link work now?

**Comment by Antonialock** [comment]
yep cheers

**Comment by Antonialock** [comment]
I wanted to see position over the last year but annoyingly it won't go back further than October?

<img width="977" alt="screenshot 2018-12-13 at 09 41 06" src="https://user-images.githubusercontent.com/12727506/49929812-45e86e00-febb-11e8-9fde-69285e79f73c.png">

This page says there's a crawl issue on 4 pages
https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.pombase.org%2F&item_key=CAMYISAE

**Comment by ValWood** [comment]
OK! Pombase gone!
