### ISSUE TITLE
malacards to DOIDs

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1066]
How many malacards annotations did not map to a DOID? Is there a file?
...I guess I should request those terms too

**Comment by kimrutherford** [comment]
The nightly load generates a log file but I forgot to change the script to copy it to the website with the other logs files.  I've copied it manually:
  https://curation.pombase.org/dumps/builds/pombase-build-2018-12-12/logs/log.2018-12-12-20-21-23.malacards_data

It will appear in the normal log directory from tomorrow:
  https://curation.pombase.org/dumps/latest_build/logs/

**Comment by Antonialock** [comment]
Wow!

**Comment by Antonialock** [comment]
So these are all possible pombe annotations - not any malacard term without a doid mapping?

**Comment by kimrutherford** [comment]
All the warnings are for MalaCards disease associations for pombe genes where the DOID is missing.

**Comment by Antonialock** [comment]
Ok, so wow!

**Comment by kimrutherford** [comment]
Sorry about the lines like:
```
seen: DOID:5212 -> SPAPB17E12.11
```
They weren't meant to be in the output.  They'll be gone tomorrow.

**Comment by ValWood** [comment]
Is this one still relevant?

**Comment by kimrutherford** [comment]
I think this is out of date (or done).

**Comment by Antonialock** [comment]
yes, out of date
