### ISSUE TITLE
quilt - see breakdown of number of genes

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1067]
I'd like to see how many genes are in each BP category (my list is large so it is impossible to eyeball the split)  Is it possible to include the number of genes in each category (or %)

either when you mouse over a category 

<img width="283" alt="screenshot 2018-12-13 at 14 29 32" src="https://user-images.githubusercontent.com/12727506/49945055-d76bd600-fee3-11e8-9741-5c7650e8a5bd.png">

or directly visible in the table

<img width="356" alt="screenshot 2018-12-13 at 14 29 50" src="https://user-images.githubusercontent.com/12727506/49945068-e18dd480-fee3-11e8-884a-ffe0a51a7e32.png">

**Comment by kimrutherford** [comment]
It makes sense to make that information available.  Maybe we should have a button that pops up a table containing all those summary numbers?  Then you could copy and paste the numbers.

**Comment by ValWood** [comment]
maybe when you scroll over the headers, you see the totals?

**Comment by kimrutherford** [comment]
> maybe when you scroll over the headers, you see the totals?

Could do, but then you couldn't copy and paste.  It's also not as obvious to new users.

**Comment by kimrutherford** [comment]
This might be related: https://github.com/pombase/website/issues/914#issuecomment-441842096

**Comment by ValWood** [comment]
I'm not sure they are so maybe they are not well-explained.
We can chat about this later.

**Comment by ValWood** [comment]
put the numbers int he pop-up.
Later we will consider a table, but before that we might want to deal precedence  view better.

**Comment by kimrutherford** [comment]
> put the numbers in the pop-up.

I've done this:

![vis-tool-gene-count-1](https://user-images.githubusercontent.com/90474/50875608-05cec980-142e-11e9-8a29-e3218c2e9f79.png)

Is that what we decided?

**Comment by ValWood** [comment]
looks good to me
