### ISSUE TITLE
Nucleus 3D plots

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1068]
Another idea from Maria

One Idea that could be super cool, but that would involve Justin O’Sullivan (from New Zeland) would be if there would be a way to implement his nucleus 3D plots with the gene list query in pombase. (like the plots in these papers https://www.ncbi.nlm.nih.gov/pubmed/25342201, https://www.ncbi.nlm.nih.gov/pubmed/26729303) 
I guess if he has some sort of 3D network of genes then the query builder could color them. For me something like this would be fantastic.

**Comment by kimrutherford** [comment]
I'm glad this is a future issue because I don't understand those plots at all.  :-)

**Comment by ValWood** [comment]
You could also ask Kimberley MacKay:
https://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-018-3507-2

Although Guy Slater has developed something too. Probably not finished yet....

**Comment by Antonialock** [comment]
That looks like chromosomal contact maps? Not localisation of genes in a nucleus

**Comment by ValWood** [comment]
It's derived from the same data-type though?
Fig 2 a-d in McKay is broadly equivalent to 3a &b in O'sullivan

**Comment by Antonialock** [comment]
I'm sure that people would also be interested in chomosomal contact sites but that is harder (since we don't have an easy way to represent these with PomBase IDs).

That is however different from the physical localization of genes inside the nucleus.

**Comment by ValWood** [comment]
I know, but it comes from the same data doesn't it? you need the contact sites to calculate/model the 3-D spatial position of the genes?

The same people will develop the software because it's related?

**Comment by Antonialock** [comment]
It incorporates some data...

G1 and G2 phase chromosomes were modeled as coarse-grained flexible chromatin fibers using a Monte Carlo approach. Spatial constraints governing the nuclear size (30), and biological constraints restricting the telomere (21) and nucleolus positioning and centromere colocalization with the spindle pole body (SPB) (21,31,32) were based on microscopic observations (33). Models with the nucleolus diametrically opposite the SPB represent ≥45% of the population that has been previously observed microscopically (31). Subsets (10%) of the captured interactions for the G1 and G2 phase genomes were incorporated as attractive forces. Three model types were generated: confined, constrained and interactions. The confined model included the spatial constraints and nucleolar excluded volume. The constrained model included the spatial and biological constraints. In addition to the spatial and biological constraints, the interactions model also included captured uniquely positioned, significant, non-adjacent interactions from the GCC data. Sets of interactions for inclusion in the interactions model were randomly selected with a probability proportional to their frequency of capture in the GCC experiment. Full details for the algorithm are available in Supplementary Methods.


I asked them if they had some software that would do the mapping based on a predefined network....I'm guessing not or else they would have made it available. Just thought it didn't hurt to ask since Maria requested it.

**Comment by ValWood** [comment]
We had a small number of requests. Still low priority but something to keep  on the radar as interest is increasing

3D genome display 4

**Comment by ValWood** [comment]
Closing as we have this  listed in the "future" doc. It was also on the curation tracker.
