### ISSUE TITLE
"Explore" item about JBrowse?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1069]
Should we add an Explore item about JBrowse at some point?  We could probably just have a screen shot, a sentence or two introduction and then a link to the "Getting started with PomBase JBrowse" page.

**Comment by ValWood** [comment]
Sounds like a good plan! I missed that opportunity...

**Comment by ValWood** [comment]
@Antonialock

**Comment by Antonialock** [comment]
I uploaded an image in the spotlight folder. I can't see where to dump the text (not good at searching github outside of tickets!)

PomBase's JBrowse instance (https://www.pombase.org/jbrowse/) provides a response online environment in which to visualise published genomic datasets. Datasets can be accessed either using the track selector within JBrowse, or by following the link on the publication page of a hosted dataset. For more information please see our JBrowse documentation page https://www.pombase.org/documentation/JBrowse_quick_start.

**Comment by Antonialock** [comment]
updated the comment because my english sucks.

**Comment by kimrutherford** [comment]
The text goes in the main website config file:
  https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json

If you search for "explore" in the file you'll see what the entries look like.  The "link" field should probably be "/jbrowse/".

If add your item I'm happy to test it locally before adding the main site.

**Comment by Antonialock** [comment]
cheers, done
