### ISSUE TITLE
Gene page specification Section 4, target of

### ISSUE THREAD

**Issue by ValWood** [pombase/website#107]
This is essentially just a display of all of the reciprocal annotations   provided by annotation extensions.

It provides a quick way to  see  all of the upstream effectors of a gene 
product  (direct or indirect). These are essentially reciprocal of the  
information captured in annotation extensions.

So for example, the "Target of"  annotation "substrate of gene x"  is 
the reciprocal of 'has substrate gene y', on the GO Molecular function 
section of the gene page of the upstream effector.

You can see many examples for cdc2

http://www.pombase.org/spombe/result/SPBC11B10.09#recipext

I think the only thing you need to know is  the display relationships which are in an old jira ticket.

@mah11  is there anything else required for this display? It seems like it took a lot more explaining that this so maybe I missed something?

**Comment by mah11** [comment]
The info on display text for annotation extensions and the "target of" reciprocal annotations are now in a file in svn:

pombe-embl/supporting_files/Annotation_extension_and_reciprocal_display.txt

I generated it by updating and merging two older files, which I've partially updated and renamed to old_annotation_extension_reciprocal_display.txt and old_annotation_extension_reciprocal_notes.txt for posterity.

**Comment by ValWood** [comment]
You are  a star.....I don't think I would have found the old tickets by now!

**Comment by ValWood** [comment]
There are also new relations we need to include 
directly activates and directly inhibits (I know these are not the correct names, I need to look that up)

**Comment by ValWood** [comment]
Also I'm not sure if we currently "reciprocate" the  regulates annotations on the BP terms. If we don't we should.....

**Comment by mah11** [comment]
> directly activates and directly inhibits (I know these are not the correct names, I need to look that up)

directly_positively_regulates and directly_negatively_regulates are in load-pombase-chado.yaml, and in Annotation_extension_and_reciprocal_display.txt with "directly activates" and "directly inhibits" as display text respectively.

**Comment by kimrutherford** [comment]
I've added a basic "Target of" table on the gene pages.  It's still a bit raw.

I've moved the configuration to: supporting_files/chado-json-config.yaml
It's a bit verbose but I hope it makes sense.

**Comment by ValWood** [comment]
Looking good!

**Comment by kimrutherford** [comment]
The extension relation display names should match what is in the config file too now.  eg. it should say "binds" rather than "has_direct_input".

**Comment by ValWood** [comment]
Will close. New tickets for new things...
