### ISSUE TITLE
Disease association display bug?

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1071]
For fxn1:

<img width="1244" alt="screenshot 2018-12-14 at 10 19 56" src="https://user-images.githubusercontent.com/12727506/49997881-ac888d00-ff8a-11e8-8a43-238161d584c1.png">

but for tsc2:

<img width="1236" alt="screenshot 2018-12-14 at 10 25 08" src="https://user-images.githubusercontent.com/12727506/49997884-af837d80-ff8a-11e8-84aa-a61827877904.png">

so for fxn1 the malacards entry is displayed twice? Bug?

**Comment by kimrutherford** [comment]
Yep.  It's a bug.

We're seeing the bug because there are two annotations for that term and gene.  One from MalaCards and one from mapping the old disease_associations.  It should only show the MalaCards link for the MalaCards annotation.

Need to fix #1072 at the same time.

**Comment by ValWood** [comment]
Looks great though.
slim looks good, and useful...

**Comment by kimrutherford** [comment]
I think I've fixed this now.  I'm running a new load on my desktop including the PBO to DO mapping file so we can check it.

**Comment by kimrutherford** [comment]
It's somewhat improved.  The "PomBase" is missing from the Source column.  I'll do that next.

![disease-refs-1](https://user-images.githubusercontent.com/90474/50277219-b2a9cc80-04a8-11e9-8d7e-a97b6ecce563.png)

**Comment by kimrutherford** [comment]
> It's somewhat improved.

Forgot to say, you can see that change here:
http://pombase2-kmr.bioinformatics.nz/gene/SPCC1183.03c
(Until I head to bed and turn my desktop off)

**Comment by kimrutherford** [comment]
It now looks like this:

![disease-section-2](https://user-images.githubusercontent.com/90474/50809450-5976df80-1368-11e9-8eb9-4dbe662f8f26.png)

**Comment by ValWood** [comment]
That's good.
Note that sometimes "pomBase curators" will have used a  specific publication. In those cases will that reference be shown?

**Comment by kimrutherford** [comment]
> Note that sometimes "pomBase curators" will have used a specific publication. In those cases will
> that reference be shown?

Yep!

Here's fol2 / SPAC17A5.13:

![disease-section-4](https://user-images.githubusercontent.com/90474/50821895-39114a00-1395-11e9-81cd-84d92f91bd90.png)

(To be honest I hadn't checked that until you asked and was surprised that it worked)
