### ISSUE TITLE
news item and tweet

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1074]
@mah11 
please could you massage my post into a news item?

@kmr could you tweet.

icon for news item/ credit reactome
![mitochondrion](https://user-images.githubusercontent.com/7359272/50027140-20ef1a80-ffe3-11e8-8e39-8327ffa49a5d.png)

**Comment by ValWood** [comment]
icon might be better rotated corner to corner if that is possible?

possible tweet:
PomBase mitochondrial protein review, reflecting  current biology for mitochondrial protein GO annotation

**Comment by ValWood** [comment]
tweet can use icon, or quilt whichever you think it best.

**Comment by kimrutherford** [comment]
OK.  I'll send a tweet on Monday.

**Comment by kimrutherford** [comment]
> possible tweet:
> PomBase mitochondrial protein review, reflecting current biology for mitochondrial protein GO annotation

Tweets can be 280 characters these days.

How's this?

Interest in mitochondrial biology has increased in recent years. In response to this, Val Wood has performed a review of the PomBase mitochondrial GO annotation and refined many inferred annotations. View the mitochondrial sub-components here: https://www.pombase.org/term/GO:0005739

I'll mention the unknowns and QuiLT in a follow-up tweet.

**Comment by ValWood** [comment]
yeah fine...it can just say "we have performed a review" though....

**Comment by kimrutherford** [comment]
I've tweeted about it.

**Comment by mah11** [comment]
> icon might be better rotated corner to corner if that is possible?

I can't make sense of this. Rotated clockwise or anticlockwise, and how far (45, 60, 90, other degrees)? Or reflected (which axis)?

**Comment by mah11** [comment]
>  "we have performed a review"

why oh why not just say "we have reviewed" ???

**Comment by ValWood** [comment]
Corner to corner? That would clearly be 45 degrees? So it fits better into a square space?

**Comment by mah11** [comment]
> Corner to corner? That would clearly be 45 degrees?

My point is precisely that it is _not_ clear, because it does not specify which corner moves where. Moreover, to bring one corner to the position of another corner requires rotating by 90 degrees or an integer multiple thereof.

Anyway you have now specified 45 degrees, for which thanks. Clockwise or anti-clockwise?

**Comment by mah11** [comment]
it looks OK rotated 45° clockwise
