### ISSUE TITLE
External links on disease pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1075]
Link to DO for specific IDs e.g. http://disease-ontology.org/term/DOID%3A0070131/

I think it would be nice to link to malacards too because they conglomerate a lot of information for a disease but we probably can't do it easily from the DO ID.

**Comment by kimrutherford** [comment]
I've added the link to DO on the pombase-dev term pages.  You'll need to reload.

**Comment by Antonialock** [comment]
thanks!

**Comment by Antonialock** [comment]
Could we change the URL to this format? 
http://www.disease-ontology.org/?id=DOID:9256

**Comment by mah11** [comment]
Done. For future reference, it's in the "external_term_references" section of pombe-embl/website/  pombase_v2_config.json
