### ISSUE TITLE
small text change, priority genes page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1076]
https://www.pombase.org/status/priority-unstudied-genes

In fission yeast the "unknown" inventory is 693 entries, many of which are c. However, a large number (410) are conserved, and a significant number of these (146) have orthologs in vertebrates

->many of which are apparently species  *fission yeast or clade* -specific. 

(becuse many of the bob-410 conserved, are conserved in other fission yeast

**Comment by ValWood** [comment]
corrected 
fission yeast or clade -specific.

**Comment by kimrutherford** [comment]
> many of which are apparently species fission yeast or clade -specific.

That doesn't make sense to me.  Is "species" supposed to be there?

**Comment by ValWood** [comment]
sorry!

many of which are apparently fission yeast clade-specific.

**Comment by mah11** [comment]
How about something readable, like "specific to the fission yeast clade" or even "found only in fission yeasts"?

**Comment by mah11** [comment]
looks done
