### ISSUE TITLE
rpb1 and hmo1 don't appear in JBrowse

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1079]
not sure why...

https://www.pombase.org/gene/SPBC28F2.12

**Comment by ValWood** [comment]
both look fine in art

![in art](https://user-images.githubusercontent.com/7359272/50378375-de53c080-0628-11e9-98d3-786c1d9aaae1.jpg)

**Comment by ValWood** [comment]
oh it because its   at the top of the view, there is a crill bar.
It might be better to default to the top ?

**Comment by kimrutherford** [comment]
It looks OK to me?  It should default to the top of the JBrowse view.

![rpb1-bug-1](https://user-images.githubusercontent.com/90474/50380958-dc4c3900-06de-11e9-816c-f8b260cc4b46.png)

**Comment by ValWood** [comment]
for some reason I was at the bottom, will close.
Can reopen if it happens in some certain circumstance ( I didn't touch the scrolll bar)
