### ISSUE TITLE
handle 'with' entry as an extension for GO protein binding annotation display purposes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#108]
The GO annotation  "with" field  for one term (protein binding) , is a piece of biologically relevant information and we display this in the "summary view" (where we hide other with/from field information which is more aligned with "supporting evidence"

Therefore, you will notice on the gene pages that we display this "with" field information as an extension with the relationship "binds"

(Long term there is talk at GO of making this an annotation extension formally).

**Comment by mah11** [comment]
Do this if the annotated term (GAF col 5) is GO:0005515 or any of its is_a descendants.

**Comment by ValWood** [comment]
- [ ] and make these display the gene names, rather than systematic IDs (minor)

**Comment by kimrutherford** [comment]
This should be working now.  It's working on the pages I've checked.  eg.
  http://pombase2.bioinformatics.nz/gene/SPAC2F7.03c

I'll leave it to you to close the issue if you're happy with the change.

Fixed in pombase/pombase-chado-json@bff54d65ebe35ab984ee2a14b6e9e2b5c06ed674

**Comment by ValWood** [comment]
yep :)

**Comment by kimrutherford** [comment]
> (Long term there is talk at GO of making this an annotation extension formally).

How long term is "Long term"?  :-)

You're comment was from 2016.  Do you know of any progress?

I'm asking because I want to make sure I really do need to implement this issue before I get started: https://github.com/pombase/pombase-chado/issues/276#issuecomment-675268875

**Comment by ValWood** [comment]
Not on the horizon....might not happen

**Comment by kimrutherford** [comment]
> Not on the horizon....might not happen

OK, thanks.  I'll go ahead and fix this: https://github.com/pombase/pombase-chado/issues/276#issuecomment-675268875
