### ISSUE TITLE
broken link in external refs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1082]
for some reason, possibly the link has changed?

Modifications | iPTMnet | P04551 | Protein modifications

**Comment by kimrutherford** [comment]
Yep, it looks like the link has changed.  It looks like it's now: https://research.bioinformatics.udel.edu/iptmnet/entry/Q10452/

I'll fix that tomorrow.

**Comment by kimrutherford** [comment]
> I'll fix that tomorrow.

I forgot that most of the links come from the GO.xrf_abbs file from GO.

I think the url_syntax should be "https://research.bioinformatics.udel.edu/iptmnet/entry/[example_id]/"

Midori, do you have the right permissions to change the entry?  If so, could you fix this?

Thanks.

```
abbreviation: iPTMnet
database: iPTMnet protein post-translational modification database
generic_url: http://annotation.dbi.udel.edu/iptmnet/
url_syntax: http://annotation.dbi.udel.edu/iptmnet/entry/[example_id]/
example_id: iPTM:P06493
url_example: http://annotation.dbi.udel.edu/iptmnet/entry/P06493/
entity_type: BET:0000000 ! entity
```

**Comment by mah11** [comment]
I don't have permissions to commit a change, so I've done a [pull request](https://github.com/geneontology/go-site/pull/967).

**Comment by kimrutherford** [comment]
> so I've done a pull request.

Thanks.  I didn't think to do that.  I'll submit a pull request rather than a Midori request next time.  :-)

The link is fixed now.

**Comment by mah11** [comment]
no worries ;)
