### ISSUE TITLE
Google chrome? website issues

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1086]
Does not work for me. After one item is selected, you can't seem to switch to another news item

**Comment by mah11** [comment]
guess what? it does work for me. ain't that always the way?
(firefox 64.0, wired network in office)

**Comment by ValWood** [comment]
really odd, this page is blank too. I see *nothing* here except the menu.
https://www.pombase.org/downloads/datasets

Google chrome.

**Comment by ValWood** [comment]
It is possible that's just an incorrect link.
I got to it from here:
https://www.pombase.org/documentation/high-confidence-physical-interaction-network

**Comment by mah11** [comment]
ok, that second one is a duff link, so I can fix it ... and if you still have the news page problem, we should hive the bad link off into its own ticket because it's different

**Comment by mah11** [comment]
moved link error to #1087; deleted comments referring to it

**Comment by kimrutherford** [comment]
> Does not work for me. After one item is selected, you can't seem to switch to another news item

Could it be that the menu has scrolled off the top of the page when you click on a news item?

On the news archive page the menu doesn't "stick" when you scroll because it's too long to fit on the screen.  It needs to scroll so you can get to everything in the menu.

**Comment by ValWood** [comment]
odddly it's now working. maybe my connection, which has been playing up.
