### ISSUE TITLE
quilt news item update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1088]
could we update this to add a link to a dataset (the unknowns)

https://www.pombase.org/query/results/from/predefined/priority-unstudied-genes:conserved_unknown

that way, if people see the news item, but they don't know anything prior about  the advanced query they can click on a link and select "visualise" to see an example.

**Comment by kimrutherford** [comment]
I've added this text:

    To see the Unknowns dataset in QuiLT, visit the unknowns results page and
    click "Visualisation".

with "unknowns results page" linked.

Let me know if that's OK.

**Comment by ValWood** [comment]
that's great. Could you change "visualisation" to "visualise" to match the button.

**Comment by kimrutherford** [comment]
Thanks for spotting that.  Fixed now.
