### ISSUE TITLE
Include a MONDO mapping/link on the disease ontology pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1089]
from https://github.com/pombase/website/issues/1007

@cmungall  commented on this somewhere.
I can't find it (mentioned json)

**Comment by kimrutherford** [comment]
Is there a MONDO term for each DO term or is it trickier than that?

**Comment by cmungall** [comment]
In general, yes, but there are deliberate exceptions. For example, MONDO
doesn't instantiate all "X allergic asthma" (see
https://www.ebi.ac.uk/ols/search?q=allergic+asthma&groupField=iri&start=0&ontology=doid
) terms. There are a few documented cases where we proxy-merge DO classes
(2 DOIDs equivalent to one MONDO). There may be sync/timing differences too.

**Comment by kimrutherford** [comment]
Thanks Chris.

Is there a mapping between the two ontologies so we can provide links to MONDO from our DO pages?

**Comment by cmungall** [comment]
You can use either the xrefs in the obo file, or the equivalence axioms in
the owl/json

**Comment by kimrutherford** [comment]
That makes sense.  Thanks.

**Comment by ValWood** [comment]
Probably this is out of date if we are switching to MONDO?

**Comment by ValWood** [comment]
@Antonialock ?

**Comment by Antonialock** [comment]
I think we are deprecating the DO pages in favour of mondo term pages?

**Comment by ValWood** [comment]
Yes, that's the plan so we can close this. But this ticket had the important information about where the  DO/Mondo equivalence  mapping was. I didn't know you had done this manually until this week....
