### ISSUE TITLE
create an "Explore PomBase" item for disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1090]
Create a research spotlight for disease associations (when slim available?)

use @jmcmurry  image, and credit
https://pixabay.com/en/users/mcmurryjulie-2375405/

Text? 
Mention coverage, and slim (link) (how many DO terms do we use)

We need to start the rotation again.

I suggest to rotate between this, unknowns, and the book chapter.
Once Kim releases the new motif search we should make a new "spotlight" for this  too and include in the rotation.

**Comment by mah11** [comment]
edited summary on the assumption that you want a PomBase thing in "explore PomBase" rather than "research spotlight"

**Comment by ValWood** [comment]
This is live and can be closed, but add credit to image for Julie McMurry

**Comment by kimrutherford** [comment]
I've added a credit for Julie.
