### ISSUE TITLE
gene count confusing in Quilt

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1099]
see pop up. This  (35)
![gene count bug](https://user-images.githubusercontent.com/7359272/51123727-8d448000-1814-11e9-87d5-825b1c1f0012.jpg)

should be  3...

**Comment by ValWood** [comment]
The number is correct at the top of the filtered gene list.

**Comment by kimrutherford** [comment]
The number is correct but maybe not obvious.  There are 35 genes in the 201-300 protein length bin.  It's more obvious if you sort by protein length.

**Comment by ValWood** [comment]
But there aren't 35. There are only 3 in this bin?

**Comment by ValWood** [comment]
Oh I get it. it is the entire bin, not the highlighted portion. I wonder if that is a bit confusing...

**Comment by kimrutherford** [comment]
> I wonder if that is a bit confusing...

I've add a discuss label.  Maybe it needs rewording.

**Comment by ValWood** [comment]
Ideally it would say
35 in this bin, 3 selected
to be unambiguous, is that possible

**Comment by ValWood** [comment]
I have hopefully put "Quick", remove if not

**Comment by kimrutherford** [comment]
> 35 in this bin, 3 selected

That should be a quick change.  Just to check, is "3 selected" useful, or would it be better to show the gene count of the block you're hovering over?  The two numbers aren't always the same.

**Comment by ValWood** [comment]
I think it's fine if they select the rows, because the context  is much clearer
![block](https://user-images.githubusercontent.com/7359272/52700893-e23cf880-2f70-11e9-9415-7fe34460aff2.jpg)

**Comment by kimrutherford** [comment]
> So as long as the user knows the number selected and the bin total I think it is OK

I'm still a bit confused by "selected"  The number selected is at the top of the list of genes on the right ("15 selected genes").  It doesn't need to be shown in the pop up box does it?

**Comment by ValWood** [comment]
>The number selected is at the top of the list of genes on the right ("15 selected genes").

There is no reference to the "15 selected" anywhere in the top view when you have only a "block" selected

**Comment by ValWood** [comment]
You only see the 15 if you select the rows (which I try not to do unless I am planning to filter. Otherwise you collect lots of genes that you probably don't want to filter)

**Comment by kimrutherford** [comment]
> when you have only a "block" selected

Ah, I think that's my confusion.  I wouldn't call that a selected block.  Maybe "highlighted" would be a better word?

**Comment by ValWood** [comment]
yes, sorry! I never have the right words!

**Comment by kimrutherford** [comment]
No problem.

So is this wording OK?:

```
Gene component: nucleus
14 genes hightlighted out of 321 in this bin
(click to toggle selection)
```

Do we need to say "in the bin"?

**Comment by ValWood** [comment]
This might not be the best wording, amybe @mah11 or @Antonialock   can think of better

We need to to be clear that it is 
15 out of the 101 AND that the 101 is not the genome total. That is obvious in the case of nucleus, but it might not always be so.

**Comment by Antonialock** [comment]
That's quite a lot of information to put concisely...

14/321 genes in list annotated to GO component: nucleus hightlighted

**Comment by ValWood** [comment]
OK let's do this for now:

Gene component: nucleus
14/321  genes in this bin highlighted.

and close this ticket.

**Comment by kimrutherford** [comment]
I've finally implemented this.  Let me know if you'd like to tweak anything.
