### ISSUE TITLE
FYPO chemical sensitivity & resistance lists

### ISSUE THREAD

**Issue by mah11** [pombase/website#11]
We've had one user request for, and think there's probably broader interest in, a web page that lists genes annotated to FYPO terms for sensitivity or resistance to specific chemicals.

It would not make sense to create a page manually because keeping it up to date would be a nightmare (or just not happen). Instead, we propose a page analogous to the GO Slim page (http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms) and its automated updates.

Each table of terms indicated below would resemble the GO Slim annotation table, only without the esyN links (i.e. have the Name, Term, and Genes columns).
## 

Title and blurb for page:
FYPO chemical sensitivity & resistance annotations

The tables below show terms in the Fission Yeast Phenotype Ontology (FYPO) representing increased sensitivity or increased resistance to specific chemicals. FYPO IDs link to BioPortal, where you can see the term in its ontology context. The annotation totals link to pages with information about the term and a list of annotated genes.

Heading 'Chemical sensitivity'
[table of terms with an is_a path to increased sensitivity to chemical (FYPO:0002683)]

Heading 'Chemical resistance'
[table of terms with an is_a path to increased resistance to chemical (FYPO:0002682)]
## 

Let us know if anything isn't clear. Note: by the time this actually happens, we may have an installation of AmiGO adapted to show FYPO and phenotype annotations. If so, we'd use that instead of BioPortal for the FYPO ID links (and there'll be another ticket for FYPO links elsewhere, e.g. ontology term pages).

**Comment by ValWood** [comment]
I'm wondering if filters will handle this ?
I'll add "not required  to go live" but we can close if it happens by chance;)

**Comment by mah11** [comment]
We have filtering now. So we can either (a) close this now or (b) add one or more canned queries and then close it.

**Comment by ValWood** [comment]
Add canned query for these I think?
Include in FAQ?

**Comment by mah11** [comment]
I have added a FAQ, with what I hope are query links. I also added the predefined queries to the config file, and I really hope I didn't break anything thereby.

@kimrutherford, could you make sure I didn't screw it up, or tell me how to fix it if I did? And release the new FAQ if it is good to go? tks :)
 
I'll check soon, and if I haven't broken anything (or once it's fixed), I'll close this.

**Comment by kimrutherford** [comment]
> could you make sure I didn't screw it up, or tell me how to fix it if I did? And release the new FAQ if it is good to go? tks :)

It was all good and is now in the main site.

**Comment by mah11** [comment]
hooray! off to do a bunch more for #535 ...
