### ISSUE TITLE
Update InterPro

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1100]
There has been a new release: https://www.ebi.ac.uk/interpro/release_notes.html

**Comment by ValWood** [comment]
great! I wondered if one was due.

**Comment by ValWood** [comment]
It would be good to get this updated if it is quick as I have some tracker tickets it  might hep with

**Comment by kimrutherford** [comment]
The process to extract the pombe results from the big InterPro XML file takes hours but I did it last week and forgot.  It's ready to go now so the new data will be included in tonight's load.

**Comment by ValWood** [comment]
fab!

**Comment by ValWood** [comment]
I didn't get any new info on any orphans,  coverage is about the same, but looks fine.
