### ISSUE TITLE
Show the extensions compactly in the summary view

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#111]
eg. show

    has substrate cdc18, crb2, sds23, nsk1, srw1, orc2, cut7

instead of:

    has substrate cdc18
    has substrate crb2
    ...

(Sorry if there is an issue for this)

**Comment by kimrutherford** [comment]
The view of extensions is now a bit more compact and tidy.  It's not as good as pombase.org yet.

The extensions are still in a random order.

**Comment by ValWood** [comment]
no I did't open one for that yet, you're ahead of me....

**Comment by kimrutherford** [comment]
I think this is done.

**Comment by ValWood** [comment]
beautiful!
