### ISSUE TITLE
research spotlight passmore

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1110]
I just put the paper through

Webster et al 2019
RNA-binding proteins distinguish between similar sequence motifs to promote targeted deadenylation by Ccr4-Not

Originally published in elife  https://elifesciences.org/articles/40670

![passmore research spotlight](https://user-images.githubusercontent.com/7359272/51693638-436b4f00-1ff7-11e9-8237-efc1744ed43b.jpg)

Could erase the A and the odd black line if it's easy

**Comment by kimrutherford** [comment]
I'll update the main site after the nightly load finishes so that the annotations are visible.

**Comment by kimrutherford** [comment]
It's live now:
  https://www.pombase.org/reference/PMID:30601114
  https://www.pombase.org/archive/spotlight
