### ISSUE TITLE
update SGD names

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1122]
I notice we are not picking up 
YGK1 for 
YGL101W

(alerts might be nice for name changes though as I can check if there is now info)

**Comment by kimrutherford** [comment]
> I notice we are not picking up
> YGK1 for
> YGL101W

I'll update the data from SGD.  They haven't updated the data file we use and they don't have an identifier file that gets automatically updated on their website or FTP site.  They suggested that we download what we need from YeastMine.  I'll do that but it's a manual job that's hard to automate.

> alerts might be nice for name changes though as I can check if there is now info

What sort of alerts do you mean?

**Comment by ValWood** [comment]
It would be nice to know when a name switch takes place, This indicated a new gene characterization. This can be later though. Also,  this sounds like a pain so it can wait until  SGD make it easier.

**Comment by kimrutherford** [comment]
> Would the YeastMine API make it less hard?

That's what I was thinking of.  It involves writing a script that would run at the start of each load.  That would work but it adds an extra step that could break the nightly update.  A file on an FTP site is more reliable.

**Comment by kimrutherford** [comment]
> Would the YeastMine API make it less hard?

I'll talk to InterMine about that when I meet with them.  If I remember correctly their API is quite easy to use.

**Comment by kimrutherford** [comment]
> I'll talk to InterMine about that when I meet with them. If I remember correctly their API is quite
> easy to use.

I forgot to talk to InterMine but I've got it working.  I decided it would be more reliable if I wrote a script that can generate a tab-delimited file for loading.

We can update the file manually as needed (by running the script).  Docs: https://github.com/pombase/pombase-chado/wiki/SGD-genes

I'm testing the change locally and I hope to get it into tonight's load.

**Comment by kimrutherford** [comment]
> I'm testing the change locally and I hope to get it into tonight's load.

I think it's OK.  It's looking good in the load on my local machine.  I'll do a check after tonight's load finishes to make sure it's OK before deploying.

**Comment by kimrutherford** [comment]
It's all OK except that the ortholog count has dipped slightly.  Here are ones that were there yesterday but aren't in last night's load:

  YER109C  SPBC1289.10c
  YER109C  SPCC1494.10
  YPL119C  SPCC1795.11

They are reported in the log: https://curation.pombase.org/dumps/builds/pombase-build-2020-02-11/logs/ortholog_problems.txt

>  I decided it would be more reliable if I wrote a script that can generate a tab-delimited file for loading.

That's not clear.  What I meant was that created a file as needed was more reliable than the other option which was to query InterMine live during the loading.

I'm going to close this.  Please re-open if you spot any problems.

**Comment by ValWood** [comment]
Re:

>Here are ones that were there yesterday but aren't in last night's load:
YER109C SPBC1289.10c
YER109C SPCC1494.10
YPL119C SPCC1795.11

I don't understand this. These orfs are still in SGD.
I didn't remove any orthologs, so where are they missing from?

**Comment by kimrutherford** [comment]
Sorry about that.

YER109C was missing because is has the feature type in SGD of "blocked reading frame". All the others have type "ORF".

YPL119C was missing because its description/product has a newline and the loading code couldn't cope.

Both problems are fixed.  I'll check the load on Friday morning.

**Comment by kimrutherford** [comment]
> I'll check the load on Friday morning.

All fixed!
