### ISSUE TITLE
toggle show/hide annotations with biogrid HTP tag

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1123]
I just noticed that biogrid has tags for HTP/LTP

could we implement the ability to toggle known HTP off? Think that would be appreciated (lots of people moan about it, especially the GI dataset)

eg.
https://thebiogrid.org/278036/summary/schizosaccharomyces-pombe/mms19.html

<img width="1074" alt="screenshot 2019-01-30 at 13 48 23" src="https://user-images.githubusercontent.com/12727506/51985642-41413e80-2496-11e9-9d22-8266894ad772.png">

**Comment by kimrutherford** [comment]
More or less all the interactions in Chado now have a HTP/LTP flag so we now have this information for all interactions.

> could we implement the ability to toggle known HTP off?

Perhaps we could have a filter drop-down like we do for the ontology annotation?

     Filter: [Throughput type...]

or

     Filter: [Throughput type...]   [Evidence...]

**Comment by ValWood** [comment]
That would be very useful! and popular!

**Comment by kimrutherford** [comment]
Great.  I don't think it will take long to implement.

**Comment by Antonialock** [comment]
we should announce this when available, I've had many people say that the more unwieldy lists are annoying

**Comment by kimrutherford** [comment]
Should we do this soon?  It would take a day or so to implement I think.

**Comment by ValWood** [comment]
Yes please, when you have time.

**Comment by ValWood** [comment]
In the survey comments:
In the publication section separate sections for high throughput and other publications (e.g. some publications show for all genes making it slower to find relevant publications)

**Comment by kimrutherford** [comment]
> Yes please, when you have time.

OK.  I'll have a go in the next week or two.

**Comment by ValWood** [comment]
related user comments

>I previously found all of candidate interactors analyzed by LC-MS/MS are listed as "physical interactor". I need a check & correction system (or please clearly show how to correct such unreliable information).

>update protein localization (some are incorrect) 

- [ ] when we announce this we should also let  people know that
i) we can filter HTP GO annotation that is incorrect if people let us know (only 1 dataset)
ii) thresholds for inclusion of physical interaction data can be improved

**Comment by ValWood** [comment]
> clear publications of large scale data papers that are present in the reference list for all genes (Hayles, Carpy, Marguerat) and add relevant papers for other organisms 

(I don't understand the second part? ,but this will satisfy the first part)

**Comment by ValWood** [comment]
and another from column BQ
> Filter out irrelevant physical and genetic interactions

**Comment by ValWood** [comment]
>protein localization information needs improve

(this is due  to HTP data which needs removing. I have filtered lots of FP's already)

**Comment by Antonialock** [comment]
> clear publications of large scale data papers that are present in the reference list for all genes 

we sort of have a workaround for this by allowing sorting on number of genes, but maybe this is not clear to everyday users

**Comment by Antonialock** [comment]
also...references are references....not a lit review - odd to have a 'filter'?

**Comment by Antonialock** [comment]
sorting is fine...

**Comment by ValWood** [comment]
> clear publications of large scale data papers that are present in the reference list for all genes

Yes but I by extrapolation that they are more bothered about the individual annotation filter since they clearly know which papers in the reference list they aren't interested in.

**Comment by kimrutherford** [comment]
I've had a go at adding a high/low through filter for the interactions.  Could you try it out?

![interaction-filter-1](https://user-images.githubusercontent.com/90474/56558958-63a9aa80-65f4-11e9-8b9d-5f88973885e5.png)

**Comment by ValWood** [comment]
Looks good

**Comment by kimrutherford** [comment]
Is there any point in adding an evidence filter on the interaction sections?  It would be quite quick to implement.

**Comment by ValWood** [comment]
This is what you have done? ;)

But we do want it to be added to other sections now it is working. Could be on phenotype, GO,  & expression

**Comment by kimrutherford** [comment]
> This is what you have done? ;)

I'm confused.  There is only a filter for throughput at the moment not evidence.

> But we do want it to be added to other sections now it is working. Could be on phenotype, GO,
> & expression

There is an evidence filter for phenotype if you click "Show details ...". 

I thought that we decided that filtering by evidence wasn't useful for GO?  It only requires a bit of configuration to add it.

**Comment by ValWood** [comment]
Ah right, I misread. 

I don't think filtering on individual evidence is so useful for GO (the users might think it is but it isn't). Filtering  on HTP  vs low throughput could be useful though, if you know you are looking for ' gene specific' studies, it could get rid of a lot of the annotations. 

I think all data types a HTP vs LTP experiments would be useful just as a way to reduce the annotation nubmer if you are looking for something specific (users will usually know if the data they are looking for is  HTP or LTP).

**Comment by kimrutherford** [comment]
> I think all data types a HTP vs LTP experiments would be useful just as a way to reduce the
> annotation nubmer if you are looking for something specific

So add a HTP/LTP filter for modifications, GO and expression?  Are there other data type where it makes sense?

**Comment by ValWood** [comment]
I think we could have it for phenotypes too. Its a useful way to reduce annotation numbers if you know your phenotype of interest could not be generated via a screen.

**Comment by kimrutherford** [comment]
I forgot phenotypes.  :-)

I'll have a go at this soon.  There's a small chunk of code that needs adding to enable a throughput filter for ontology annotations.  Once that's added we can add the filter to any ontology annotation section using the config file.

**Comment by kimrutherford** [comment]
All the ontology annotation sections now have a throughput filter. You need to click on "Show details ..." to see it.

**Comment by ValWood** [comment]
Looks good...
