### ISSUE TITLE
something weird with the gene page annotation totals

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1124]
https://www.pombase.org/gene/SPCC297.03
has
GO:0042149 | cellular response to glucose starvation | IMP | Saitoh S et al. (2015) | 75

I thought that seemed high.
When I access the list, it's 13:
https://www.pombase.org/term/GO:0042149

**Comment by ValWood** [comment]
It is particularly weird because I looked at a bzillion things today and everything else looks OK...

**Comment by kimrutherford** [comment]
Very odd!  I'll track that down.  Very likely it's just the count wrong rather than a deeper problem.
