### ISSUE TITLE
upcoming research spotlight, D'Alessio

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1127]
Abrogation of glucosidase I–mediated glycoprotein
deglucosylation results in a sick phenotype in fission yeasts:
Model for the human MOGS-CDG disorder

![alessio](https://user-images.githubusercontent.com/7359272/52163041-265c0d80-26d4-11e9-9f07-a120fe52df9d.jpg)

**Comment by mah11** [comment]
PMID?

**Comment by ValWood** [comment]
whoops, PMID: 30389790
it's not back yet but it will be soon.

**Comment by kimrutherford** [comment]
> whoops, PMID: 30389790
> it's not back yet but it will be soon.

Any progress on that?  The session has one annotation: https://curation.pombase.org/pombe/curs/661292025a8cdee8

**Comment by ValWood** [comment]
No it's stalled. I will send a reminder...

**Comment by ValWood** [comment]
Update: This can go live  after
- [ ]  adding new FYPO terms
- [ ]  confirming additions with author (also explain why I did not  request new term for " "glucosidase I " ...but double check with Celcilia which is the best primary term name

....So soon..... Pinging it back into my inbox...

**Comment by ValWood** [comment]
THis is now live so we can release the spotlight.
I forgot to ask Cecilia to check it but I will do that now....

**Comment by ValWood** [comment]
Assigning to @kimrutherford  (or if anyone else knows how to...I will learn)

**Comment by kimrutherford** [comment]
That's on the main site now.

> Assigning to @kimrutherford (or if anyone else knows how to...I will learn)

I'll run a tutorial on it when I'm in Cambridge.  :-)

**Comment by ValWood** [comment]
I know I pretty much just need to write down where the file lives!

**Comment by kimrutherford** [comment]
> I know I pretty much just need to write down where the file lives!

It's here: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json
