### ISSUE TITLE
update and pin Explore PomBase for motif search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1128]
When the motif search goes live, update and pin this image:

![motif search](https://user-images.githubusercontent.com/7359272/52175974-380ce600-27a4-11e9-8e15-61beb2f78918.jpg)

new text. 
The PomBase <link: motif search> allows you to search for any user-defined amino acid sequence, supporting exact matches, wildcards, gaps, and ambiguity codes. This search is now fully integrated into PomBase, allowing results to be sent directly to the advanced search <https://www.pombase.org/query >.

**Comment by mah11** [comment]
corrected punctuation in text above

**Comment by ValWood** [comment]
Are we ready to move this to live?

**Comment by kimrutherford** [comment]
> Are we ready to move this to live?

I haven't implemented the "Amino acid group codes" yet.  It's working otherwise.

**Comment by ValWood** [comment]
now
https://github.com/pombase/website/issues/387
(you can switch the link in the menu and put up the news item)

is done can move forward with

- [ ] rotation (see above)
- [ ] tweet 
- [ ] pombelist
- [ ] news item

**Comment by ValWood** [comment]
i.e this  switch and rotation can go ahead today

**Comment by kimrutherford** [comment]
> When the motif search goes live, update and pin this image:

Should it be pinned or just be one of the page front rotations?  There are only two that appear on the front page at the moment, "GO slim analysis for any gene list" and "Browse our inventory of conserved proteins with no known biological role"

**Comment by ValWood** [comment]
OK one of the rotations. I wrote this thinking it would get its own spotlight for a while but that was before the GO slim and the paper happened

**Comment by kimrutherford** [comment]
> OK one of the rotations.

Great.  I've changed the link in the menu and updated the Spotlight item.

**Comment by ValWood** [comment]
I don't see it, will it take a while?

**Comment by kimrutherford** [comment]
Sorry, I forgot to push the button on the Babraham server. Could you try again?

**Comment by ValWood** [comment]
There it is! can you tweet, I'll pombelist.

**Comment by ValWood** [comment]
in the rotation should we change "Motif search" to "Motif search updated"  (there is room).

so people see that it is a new rotation.

**Comment by kimrutherford** [comment]
> in the rotation should we change "Motif search" to "Motif search updated" (there is room).

Done!

**Comment by ValWood** [comment]
We never did a news item, suggest:

News item.
The PomBase motif search was recently fully integrated into PomBase. The revamped tool allows users to find protein motifs and send them directly to the PomABse advanced search.
