### ISSUE TITLE
A lot of phenotypes missing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#113]
cdc2 only has these, instead of the normal 70+ screens

![a__lot_of_phenotypes_missing](https://cloud.githubusercontent.com/assets/7359272/21420468/d302811e-c825-11e6-9569-4384898c3462.jpg)

**Comment by ValWood** [comment]
I think you got the population correct...
but the cell phenotypes might be restricted to a branch (can't work out which?)

**Comment by kimrutherford** [comment]
This seems fine now.  Perhaps it was a temporary problem?

**Comment by ValWood** [comment]
I'm only seeing the 2 cell level phenotypes above for cdc2. compare to P1, there should be 100's
val

**Comment by kimrutherford** [comment]
I see dozens.  Could you try shift-reload?

**Comment by kimrutherford** [comment]
Also I don't see the annotations you have in your screenshot.  Maybe it's showing data from the wrong gene?

**Comment by ValWood** [comment]
yep false alarm...i see them all
