### ISSUE TITLE
community curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1132]
I know we have discussed this before, but I'm not sure where. I can't find an open ticket on this tracker.

The community curation feed currently shows:
Dma1 ubiquitinates the SIN scaffold, Sid4, to impede the mitotic ...
Fission yeast Dma1 requires RING domain dimerization for its ...
The hairpin region of Ndc80 is important for the kinetochore ...

but none of these were curated recently. All of the ones showing now are those which have been 're-approved'

remind me why we can't  either use "first approved date" or somehow not put these back into the feed when  they have been "reapproved"

It would be good if we could work around this because it obscures the recently community curated papers. It will also seem a bit odd to the people who curated these *ages* ago that they are back on the front page. 

We  make minor tweaks to sessions *a lot* so this isn't an infrequent problem.

**Comment by kimrutherford** [comment]
I had a quick look and the three top papers don't have a "first approved date" because they were first approved before we added "first approved date" to Canto.  If there is no first approved date for a paper recorded in the database, we use the "approved date" when ordering the community curation sessions.

I'm not sure what the best plan is.

As a short term fix, if there's no "first approved date" we could use the "submitted date" to decide the order in the list.  That would fix the front page list but older papers on this page wouldn't be in quite the right order and they'd be listed under the submitted date:
  https://www.pombase.org/reference_list/community

Maybe that's the best we can do for old sessions from before the first submitted date was recorded?

**Comment by ValWood** [comment]
I think if there's no "first approved date" we could use the "submitted date"
would give the best approximation.

I'm trying to find examples where the citations increase after curation.
Like:
The Hsk1(Cdc7) replication kinase regulates origin efficiency.
curated 2014

![rising](https://user-images.githubusercontent.com/7359272/52306973-3bb19000-2991-11e9-960a-561b4781c751.jpg)


I think for some they seem to start to go up *before* we curated them because they have been reapproved over time...

**Comment by ValWood** [comment]
this oisn't a great example, but I need to be sure I 'm looking at dates close to curation date, not much later (particularly as it takes a while to see an effect)

**Comment by ValWood** [comment]
This is odd though. I don't see some of these recently community curated sessions in the feed at all?

![approval](https://user-images.githubusercontent.com/7359272/52307530-d1015400-2992-11e9-8812-673a695e71da.jpg)

**Comment by ValWood** [comment]
Actually they are there, they just get a bit buried by the reapproved ones...
and the 2 I could not find were probably approved today or yesterday...

**Comment by ValWood** [comment]
This will help for another reason too

**Comment by ValWood** [comment]
I didn't mean to post the previous comment because I realised as I was typing it would not help the thing I was thinking of...

**Comment by ValWood** [comment]
I'm not sure that it worked


I'm sure these:

2019-02-02
Dma1 ubiquitinates the SIN scaffold, Sid4, to impede the mitotic localization of Plo1 kinase. Johnson AE et al. (2011)
Fission yeast Dma1 requires RING domain dimerization for its ubiquitin ligase activity and mitotic checkpoint function. Johnson AE et al. (2012)
2019-02-01
The hairpin region of Ndc80 is important for the kinetochore recruitment of Mph1/MPS1 in fission yeast. Chmielewska AE et al. (2016)

were all submitted  >years ago. I edited recently...

**Comment by ValWood** [comment]
this would be a nice example because I think it was curated circa 2014/2015.
It's probably not significant , but it is  nice anecdotal evidence that curation increases citation, and if we had *enough* additive data....

![cites](https://user-images.githubusercontent.com/7359272/52346504-9db4d880-2a17-11e9-89e8-f06e206f3d8a.jpg)

**Comment by ValWood** [comment]
So this one currently shows as curated 2018...
Actually in this case community curation probably isn't  the reason for the increase. I'm guessing most of the citations are from subsequent Gould lab papers on Dma1...

**Comment by ValWood** [comment]
Actually only 2/7...but obviously it's impossible to know. 

We need to be able to demonstrate 
1/ a significant in citations for curated vs non curated papers of a similar age,  (this would not be conclusive because what id better papers are curated;)
 and 
2.  for old papers which were not curated close to the time of publication,  an increase in citation for  post curated vs pre curated

**Comment by kimrutherford** [comment]
> I'm not sure that it worked

Sorry about that.  I had a typo in my fix.  I think the dates are right now.

**Comment by ValWood** [comment]
This looks much better. All those currrently on the front page were curated recently.

Fission yeast CSL proteins function as transcription factors. Oravcová M et al. (2013)
wasn't  but it is possible we "reactivated" instead of "reapproved".
This might be due to the need to reactivate to record changes in "comments to curator". This will be fixed by https://github.com/pombase/canto/issues/407

**Comment by ValWood** [comment]
Is there an easy  way to prevent "reactivated" sessions appearing back in the feed?

**Comment by kimrutherford** [comment]
> Is there an easy way to prevent "reactivated" sessions appearing back in the feed?
> ...
> This will be fixed by pombase/canto#407

Fixing that issue would help I think.  But we probably should store a "first submitted" date too.

**Comment by kimrutherford** [comment]
> But we probably should store a "first submitted" date too.

I've done that now.

**Comment by ValWood** [comment]
So we can close this I think?
