### ISSUE TITLE
Include a list of all "curator curated publications" with data approved (or submitted)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1134]
follow on from 
https://github.com/pombase/website/issues/1132

I need to look in  the "curator curated" list for 

old papers from the 80's and 90's , not curated close to the time of publication, to detect increases in citation for post curated vs pre curated (known as sleeping beauties if the effect is very strong). However, I don't have an easy way of looking this up- In Canto we have no session dates on papers we curated.

......This would be the only to find some nice examples for talks and  to convince somebody to do the analysis

We discussed having a list of "non-community curated papers" once so this might be on the list somewhere?

**Comment by kimrutherford** [comment]
Would the "non-community curated papers" include only Canto curated papers?

**Comment by kimrutherford** [comment]
> We discussed having a list of "non-community curated papers" once so this might be on the list
> somewhere?

I've just added that because it was mostly done:
  https://www.pombase.org/reference_list/admin

It might not be very useful at the moment because it includes publications with no annotations.

**Comment by ValWood** [comment]
>It might not be very useful at the moment because it includes publications with no annotations.

I think that's OK, it means we looked but did not find any annotations, so effectively are curated...

**Comment by ValWood** [comment]
I think that's OK. A curator needed to read them to check there were no annotations. I did a lot like this recently as I was re-triaging the sequence feature papers. They did not fit any of the sub-categories, but I wanted to ensure that we knew they were "completed" for curation purposes. For most, they were sequence features which I curated in the days of yore....Centromeres and tRNAs etc. So there is curation, just not of the available types, because there were no functional experiments. So there was a big batch recently, but this isn't really normal.

Could  we link to the curatorcurated list from
https://www.pombase.org/reference_list/community
and possibly both of these pages should be under a menu...(Genome status)

Community curated publications
PomBase cutated publications

**Comment by ValWood** [comment]
> Would the "non-community curated papers" include only Canto curated papers?

I think thats will be OK, because any paper with curation will be pushed through Canto eventually.

**Comment by kimrutherford** [comment]
> Could we link to the curator curated list from ...

No problem.  What should we use as the link text?  Is "Curator curated publications" sounds a bit odd.

> and possibly both of these pages should be under a menu...(Genome status)

That makes sense.  Let me know what the menu items should say.

  - Community curated publications
  - ??? curated publications

**Comment by ValWood** [comment]
True!
PomBase curated publications?

**Comment by kimrutherford** [comment]
> PomBase curated publications?

I'll do that for now.  It's easy to change.

**Comment by kimrutherford** [comment]
I've added links on the community and PomBase pages to get from one to the other.  I'm not sure the position of the link is OK.  I've also added menu items for both pages.

It will be visible after the next nightly load.

**Comment by kimrutherford** [comment]
> I've added links on the community and PomBase pages to get from one to the other. I'm not sure the
> position of the link is OK. I've also added menu items for both pages.

All done and live on the main site.  Should we close this issue?

**Comment by ValWood** [comment]
yup
