### ISSUE TITLE
Buttons on small screen out of place 

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1135]
When looking at dev link in #914 I saw that some buttons were out of place on phone, see screen grabs 

![273674f5-06e3-4d93-a800-e2824009dd2c](https://user-images.githubusercontent.com/12727506/52399445-30a35080-2ab4-11e9-8450-a5728433b376.png)
![6cf81047-26d7-4237-af81-a3500ccdcbd4](https://user-images.githubusercontent.com/12727506/52399446-313be700-2ab4-11e9-8b1b-6a148db14c3a.png)

**Comment by kimrutherford** [comment]
I've improved things for small screens.  Unfortunately because oliver1 is offline, pombase-dev is unavailable.  Could you check on your phone when it's back?

**Comment by Antonialock** [comment]
looks good!
