### ISSUE TITLE
community curation totals

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1138]
number of community annotations for 2019 is zero?
![stats](https://user-images.githubusercontent.com/7359272/52531854-0059ed00-2d14-11e9-9fdc-a548364edf4f.jpg)

**Comment by kimrutherford** [comment]
Sorry about that.  I forgot to update the Chado that Canto uses.  Should be OK now.

I've now set a daily alarm to remind myself to update.  It's not automatic yet but it's very quick to update.

**Comment by ValWood** [comment]
yep!
