### ISSUE TITLE
"others" links incorrect?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#114]
cdc2 old

![others_old](https://cloud.githubusercontent.com/assets/7359272/21421822/cf1ac500-c82c-11e6-860a-f6d747dd7740.jpg)

cdc2 new

![others](https://cloud.githubusercontent.com/assets/7359272/21421829/d44f0798-c82c-11e6-8671-803e8c7f771b.jpg)

**Comment by kimrutherford** [comment]
I think I've fixed the main problem.  The numbers are now much closer although the protein binding count is lower in PomBase v2.  I'll check that.

Also cdc2 isn't annotated with ATP binding in the latest Chado load but is in v61.  Is that expected?

http://pombase2.bioinformatics.nz/gene/SPBC11B10.09
http://www.pombase.org/spombe/result/SPBC11B10.09

**Comment by ValWood** [comment]
weird, it has disappeared, 
grep KW-0067 pombase-build-2016-12-22-v1.gaf |grep SPBC11B10.09

I don't know why.  All of the mappings to this term have disappeared. That was one of the useful mappings....

**Comment by kimrutherford** [comment]
> weird, it has disappeared,

Where does it come from?  I'll investigate.

**Comment by ValWood** [comment]
don't worry, it isn't in the gaf,  or our blocked mappings, i will need to contact uniprot to ask why its gone

**Comment by ValWood** [comment]
The KW problem is the IEA issue.
https://github.com/pombase/pombase-chado/issues/601

The numbers are much closer now, but still very slightly lower.
I can't think why, because we haven't deleted annotations to these terms.....
Perhaps the PomBase 1 totals are wrong, but I'm sure we would have noticed.

Don't worry about this urgently.  One of us will find some term discrepancies with low numbers and see if we can figure out the difference, which should help to troubleshoot.

**Comment by ValWood** [comment]
problems reported in this ticket with
i) incorrect counts and 
ii) disappearing IEAs 
are  both fixed
