### ISSUE TITLE
Where "Pombase'  is coming from in Google results

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1140]
view-source:https://www.pombase.org/status/gene-characterisation
  <title>Pombase</title>

**Comment by kimrutherford** [comment]
The HTML source has "Pombase" but it is modified dynamically depending on which page you visit.  "View source" shows the original title not the modified one.  Google knows to index the page using the modified title.

Do you have an example Google search that still shows "Pombase"?

**Comment by ValWood** [comment]
Ah, I have seen some this week...will try to locate one...

**Comment by ValWood** [comment]
SPAC13G6.14 for example

**Comment by ValWood** [comment]
possible any systematic ID?
SPAC13C5.02

**Comment by kimrutherford** [comment]
Drat, I thought those were fixed.  I'll investigate.

**Comment by ValWood** [comment]
I only see for SPAC13C5.02 now.
I guess we can close this one. I still find it odd though...

**Comment by ValWood** [comment]
closing. I still see "pombase" links high when I seach but the seem to come from legacy pages....
