### ISSUE TITLE
title gene-characterisation etc

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1141]
https://www.pombase.org/status/gene-characterisation

could we make the table heading
Protein-coding gene characterisation -> Protein-coding gene characterisation status
and the html page title
PomBase: Protein-coding gene characterisation status?

**Comment by ValWood** [comment]
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

html title
PomBase: Fission yeast GO slim

**Comment by kimrutherford** [comment]
> Protein-coding gene characterisation status

I've changed that.

> and the html page title
> PomBase: Protein-coding gene characterisation status?

In the HTML it's:

```
<title>PomBase - Documentation - Protein-coding gene characterisation status</title>
```

> html title
> PomBase: Fission yeast GO slim

It's currently:

```
<title>PomBase - Documentation - Fission yeast GO slim</title>
```

Did you want to remove the "Documentation" bit?  It's there's for everything that was copied from Drupal.

**Comment by ValWood** [comment]
No it can stay as it is. I think I was looking at a different "title"
