### ISSUE TITLE
should we have a "ribbon release date" and "annotation total ribbon" ?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1143]
release date xx/xx/xx  xxx publications curated providing xxx annotations to xxx ontology terms
?

**Comment by Antonialock** [comment]
I like when it is really obvious when a resource was last updated.

**Comment by kimrutherford** [comment]
A ticker tape usually means a continuously scrolling message.  Is that what you're thinking of, or is static text OK?

**Comment by ValWood** [comment]
Static is OK. "ribbon"?

**Comment by ValWood** [comment]
241599 annotations, 3723 curated publications, updated 27/11/2019

**Comment by kimrutherford** [comment]
That's done now.  Let me know what formatting changes you'd like.

**Comment by ValWood** [comment]
great, we can move it around when we do https://github.com/pombase/website/issues/1425

Now we won't miss a quarter of a million!
