### ISSUE TITLE
issues on publication page

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1151]
Hoffman CS, Wood V, Fantes PA.
An Ancient Yeast for Young Geneticists: A Primer on the Schizosaccharomyces pombe Model System. Genetics. 2015 Oct;201(2):403-23.
PMID:26447128 DOI:10.1534/genetics.115.181503
(Erratum in PMID:26953269 DOI:10.1534/genetics.116.187088)
Gene Ontology Consortium
Gene Ontology Consortium: going forward.
Nucleic Acids Res. 2015 Jan;43(Database issue):D1049-56. Epub 2014 Nov 26.
PMID:25428369 DOI:10.1093/nar/gku1179

linked to the wrong pubmed page

**Comment by mah11** [comment]
> linked to the wrong pubmed page

Which link is wrong? All of the PMIDs in the pasted snippet are linked correctly.

> typo
> The RNAcentral Constortium.

originally theirs; we just copied it!
https://academic.oup.com/nar/article/47/D1/D1250/5235409

**Comment by Antonialock** [comment]
> Which link is wrong? All of the PMIDs in the pasted snippet are linked correctly.

maybe I clicked the wrong link because of the missing space between the publications

<img width="279" alt="screenshot 2019-02-21 at 17 58 07" src="https://user-images.githubusercontent.com/12727506/53190799-43fd0280-3602-11e9-959e-11fa9c6de68e.png">

**Comment by mah11** [comment]
ah, OK. I did commit an edit that I think should add the missing space.
