### ISSUE TITLE
missing research spotlight item

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1152]
https://www.pombase.org/reference/PMID:29529046

**Comment by mah11** [comment]
At first I didn't get what this is referring to, but then I looked at the spotlight archive and it has no entry for this paper. So now I can tell that this is a consequence of SVN being down: I couldn't do 'svn update' before I edited the config file to add the "explore" item for the unknowns, so I added it to a version of the file that didn't have the newest spotlight entry. Then I sent it to Kim and he deployed it, thereby overwriting that spotlight item.

I've sent a merged file (off-ticket again) that should fix it.

**Comment by ValWood** [comment]
Great I thought it was something to do with the migration, but I couldn't figure out why everything else was current!

Also, possible relate, the pombe meeting news item appears in the archive, but not on the front page.

**Comment by mah11** [comment]
> Also, possible relate, the pombe meeting news item appears in the archive, but not on the front page.

not related; fix committed; will delete these comments as off-topic

**Comment by kimrutherford** [comment]
Thanks for the fix Midori.  That item is back now.
