### ISSUE TITLE
list slimmer tool

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1153]
- [x]  @ValWood  announce
- [x] @mah11  update docs/FAQ

**Comment by mah11** [comment]
FAQ changes done; will get to the other ticket as soon as I have time (might be Monday, the way tomorrow is shaping up :P )

**Comment by ValWood** [comment]
- [ ] we should make a  PomBAse explore thing for this

 - [ ] (it could be a news item too, a new tool is newsworthy)

**Comment by mah11** [comment]
What do you want to use for pictures, especially for the Explore item?

**Comment by ValWood** [comment]
this will do:

 ![explore_slim](https://user-images.githubusercontent.com/7359272/53433175-d67b1880-39eb-11e9-8e81-d42f39ebe436.jpg)

you won't see much but it indicates 4 simple steps and it had a bit of colour

**Comment by ValWood** [comment]
if it looks terrible I'll make a simpler one.
The news item can just be the button...
