### ISSUE TITLE
Show abstract on publication pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#116]
It would be nice to be able to expand the abstract of the paper on the publication pages.

**Comment by kimrutherford** [comment]
Good idea.  I've added the abstract and a link to PubMed on the publication page.  For now it doesn't expand/collapse but I'll do that next.

**Comment by Antonialock** [comment]
looks great!....I don't think it needs to be expandable/collapsible....if we think it takes up too much space then we can open a new ticket?
