### ISSUE TITLE
add altmetrics badges to research spotlights and our publications page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1166]
Should we do this?
![badge](https://user-images.githubusercontent.com/7359272/53685756-eca01600-3d16-11e9-9c54-e303d43e1388.jpg)

also plum metrics do similar.

**Comment by ValWood** [comment]
Should we do this? Looks quick/easy to do?

**Comment by mah11** [comment]
more thorough instructions at https://api.altmetric.com/embeds.html

**Comment by kimrutherford** [comment]
> Should we do this? Looks quick/easy to do?

Which page should the badge be on?

**Comment by kimrutherford** [comment]
> Which page should the badge be on?

Do we want it for all publications?

Is here good?:

![alt-1](https://user-images.githubusercontent.com/90474/81036469-53a8f400-8ef3-11ea-98f7-8dacbe03900b.png)

**Comment by kimrutherford** [comment]
Live version here: http://desktop.kmr.nz:4242/about/citing-pombase

**Comment by mah11** [comment]
Thanks. That style would look OK on an individual publication page, but on the pages with lists ("citing pombase" and "publications by pombase") it takes up too much vertical space and adds visual clutter. The small or medium "badge" format would almost certainly look better overall (despite being a bit less ooh-ah pretty), and with the option that shows the details only on mouseover.

**Comment by ValWood** [comment]
I think just the badge too

**Comment by ValWood** [comment]
So the badge to the left of the citation, rather than underneath it...

**Comment by ValWood** [comment]
> That style would look OK on an individual publication page

I hadn't thought of that but it would be good to add either just the badge or the full monty to all publication pages.
Especially as most of the CC ones will have nice high scores...

**Comment by kimrutherford** [comment]
Do we need to contact them?:
> As a reminder: if you want to use the badges on a site that isn't your lab or personal
> homepage, blog or an institutional repository then you should first contact us at
> support@altmetric.com so that we can clear your use case. Do not use the badges
> commercially - on a journal, search engine, in an app etc. - without talking to us first!

**Comment by kimrutherford** [comment]
> I think just the badge too

Should we have a label to say what the badge is?  Is it widely known?  I hadn't heard about Altmetric until you told me.

**Comment by kimrutherford** [comment]
> So the badge to the left of the citation, rather than underneath it...

Is this OK?:
http://desktop.kmr.nz:4242/about/citing-pombase

![alt-2](https://user-images.githubusercontent.com/90474/81058902-810d9600-8f23-11ea-9807-ceed8c6da973.png)

**Comment by ValWood** [comment]
>Is this OK?: 

nice!

**Comment by ValWood** [comment]
> Do we need to contact them?:
Oh yes! well spotted. I will do that some time.

**Comment by ValWood** [comment]
> Is it widely known? 

it's widely known for our users , I think... and presumably the icon links out to an explanation

**Comment by ValWood** [comment]
better at the side (as in screen shot) than above (which is what I see via link)

**Comment by kimrutherford** [comment]
> better at the side (as in screen shot) than above (which is what I see via link)

Sorry I hadn't tried it on a small screen.  I'll work on that.

**Comment by kimrutherford** [comment]
> better at the side (as in screen shot) than above (which is what I see via link)

Can you check how it looks now?

**Comment by ValWood** [comment]
still

<img width="1049" alt="Screen Shot 2020-05-05 at 13 56 36" src="https://user-images.githubusercontent.com/7359272/81068427-40d4f600-8ed8-11ea-99b3-5af89b8a5211.png">

**Comment by ValWood** [comment]
even at full screen:
<img width="1435" alt="Screen Shot 2020-05-05 at 13 58 16" src="https://user-images.githubusercontent.com/7359272/81068586-8396ce00-8ed8-11ea-85b0-a77ca9d5c2ae.png">

**Comment by kimrutherford** [comment]
Sorry!  I forgot to save my changes.

**Comment by kimrutherford** [comment]
I've checked in what I've implemented.  We can tweak as needed once it's live.  It won't be visible until the morning.

**Comment by ValWood** [comment]
Great, thanks!

**Comment by kimrutherford** [comment]
> It won't be visible until the morning.

It's on the main site now.  Let me know if it looks OK for you Val.

https://www.pombase.org/about/citing-pombase

**Comment by ValWood** [comment]
Looks good.

can we add here too?
https://www.pombase.org/about/published-by-pombase

**Comment by ValWood** [comment]
Can we also put the badges on this page, then can close.

https://www.pombase.org/about/published-by-pombase

(I noticed that sometimes the badges only appear when you do page reload...)

**Comment by ValWood** [comment]
Are these all done?

**Comment by mah11** [comment]
Everything where all authors are PomBase (or were at the time) is done. If you want to skip the collaborations, or move them to a new ticket, this can close.

**Comment by ValWood** [comment]
Naw this can stay open. Let's add them all. Because for some of the collaborations we are major authors (e.g. I'm joint 1st author  on the Nurse lab ones)

**Comment by mah11** [comment]
OK, I'll make a note to email them about usage ...

**Comment by kimrutherford** [comment]
> (I noticed that sometimes the badges only appear when you do page reload...)

I'll look into that.

**Comment by kimrutherford** [comment]
> (I noticed that sometimes the badges only appear when you do page reload...)

I think I've fixed that.  Let me know if you spot any other problems.

**Comment by mah11** [comment]
I've done the rest of the pubs-by-pombase. Adding badges to the community publication pages would require licensing, so I'm not going to bother for now.

**Comment by ValWood** [comment]
yup, sounds like a faff.
