### ISSUE TITLE
community curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1173]
https://www.pombase.org/reference/PMID:30796050

has appeared in the feed, but from the abstract appears to have gene specific data?
This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types.

**Comment by ValWood** [comment]
I see why...the  'needs approval' sessions are now appearing in the feed...

**Comment by ValWood** [comment]
Miguel has submitted a session (gene names only but a start!)

**Comment by kimrutherford** [comment]
Whoops!  More information about the unfinished Canto sessions in getting through to Chado now.  I'll filter the feed so that non-approved sessions don't appear.

**Comment by kimrutherford** [comment]
That's fixed now.  That publication page is now back to saying "This publication has no annotations in PomBase because it hasn't been curated yet":

https://www.pombase.org/reference/PMID:30796050
