### ISSUE TITLE
improve phenotype display

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1174]
The phenotype section looks a bit like a wall of text, and could benefit from some improvement.

How about slightly darker shading of the phenotype terms (compared to the alleles and expression) or by decreasing allele/expression font size slightly?

<img width="800" alt="screenshot 2019-03-06 at 10 14 51" src="https://user-images.githubusercontent.com/12727506/53873764-ecdf3080-3ff8-11e9-90b5-c2e69f013688.png">

**Comment by kimrutherford** [comment]
I agree.  Here's what it looks like with the term name in bold.  Let's have a chat about it once the grant is out of the way.  There are a bunch of other places on the site where we could improve things.

![bold-term-name-1](https://user-images.githubusercontent.com/90474/53875406-4da65180-4069-11e9-9bf7-f7723eeeacab.png)

**Comment by Antonialock** [comment]
from survey 'phenotype section is difficult. may need summary of the functions, and explain how they are changed by deletion, mutation or over-expression.'

**Comment by ValWood** [comment]
Other than bug reports  let's not open tickets from the survey until after the grant when we will collate first, and see if they relate to existing tickets (or even if we can interpret them at all)

I only opened the ftp one because it is a bug.

**Comment by ValWood** [comment]
ah this is an existing ticket. keep the survey comments until later though. lets concentrate on grant and ISB.

**Comment by ValWood** [comment]
I wonder if we should have this view as the default, but have an "option" to  "hide allele details"?
This would allow people to scan the phenotypes before they look at specific alleles.
It would need to be carefully worded because there would be 2 types of "details"
 "show allele details" "show conditions evidence & source"

**Comment by mah11** [comment]
decided to try the bold-face term name thing soon because it's easy to do (and easy to revert if it turns out to be horrible)

keep thinking about more substantive display overhaul ...

**Comment by kimrutherford** [comment]
The term names are now bold.  Let me know if you like it.

**Comment by ValWood** [comment]
I don't know if it helps much on the gene pages, 

but I like it here
https://www.pombase.org/term/FYPO:0006031
...

**Comment by ValWood** [comment]
I guess we can close this.

I'm still leaning towards hiding allele details  by defaul but having 2 levels of sho

show "allele details" and "show all" at the top of the sections.

Maybe we could do a mini-survey to see what people would prefer here?
We could begin by asking Jurg/Mata lab and the advisory board?

I'll put this in a new ticket to ponder.....
