### ISSUE TITLE
customizable headers for fasta download

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1175]
I thought we had a ticket for this, but I can't see it covered.

We have a request for more info in FASTA headers. I think users should be able to customize this by default from download, but it might also make sense to  include more info by default in the ftp file.

I will find out which info the proteomics tools require

**Comment by kimrutherford** [comment]
I can't find the issue either.  My idea would be to have something like this in the download dialog so users could pick their own headers:

![download-dialog-1](https://user-images.githubusercontent.com/90474/53913460-43637200-40c0-11e9-8d18-558f853aa174.png)

> it might also make sense to include more info by default in the ftp file.

Yep, that makes sense.

**Comment by ValWood** [comment]
Ok for the default, from the helpdesk ticket for Nurse lab

>SPBC17D1.06| dbp3|ATP-dependent RNA helicase Dbp3 (predicted)

would seem to be sufficient if it's quick?

**Comment by kimrutherford** [comment]
> something like this in the download dialog so users could pick their own headers

I've implemented that.  I don't think "Sequence descriptions:" is a good header.  Any suggestions?

![download-dialog-2](https://user-images.githubusercontent.com/90474/56189549-546ab000-607c-11e9-88f9-ecbe15610456.png)

**Comment by ValWood** [comment]
Maybe "Fasta header content" od something similar to make it clear what they are selecting for?

**Comment by mah11** [comment]
"Include in headers"? I like that it has a verb ...

no need to repeat "FASTA" or "sequence" because they're in the tab label

**Comment by ValWood** [comment]
request from user in survey

> Parsable FASTA downloadable updated S. pombe proteome for proteomics analyses

might be the same person (anonymous).

Is this ready to announce?

**Comment by kimrutherford** [comment]
> Is this ready to announce?

I think so but could you have a quick test of downloading a fasta file?

**Comment by ValWood** [comment]
Ok, I just checked the downloadable fasta file, we should probably include more informative headers here by default?

>SPAC1002.01:pep
MLPPTIRISGLAKTLHIPSRSPLQALKGSFILLNKRKFHYSPFILQEKVQSSNHTIRSDT
KLWKRLLKITGKQAHQFKDKPFSHIFAFLFLHELSAILPLPIFFFIFHSLDWTPTGLPGE
YLQKGSHVAASIFAKLGYNLPLEKVSKTLLDGAAAYAVVKVSYFVENNMVSSTRPFVSN*
>SPAC1002.02:pep

**Comment by kimrutherford** [comment]
> Ok, I just checked the downloadable fasta file

Which file is that?  What should be added to the header?

**Comment by ValWood** [comment]
The Fasta file from here
https://www.pombase.org/downloads/protein-datasets

The default header should be
> SPBC17D1.06| dbp3|ATP-dependent RNA helicase Dbp3 (predicted)

ID| gene name| description
(At least I think that is what we decided above?)

**Comment by ValWood** [comment]
- [ ]  We would also need to update documentation and FAQ to say that if you want  coordinates in the fasta header (customizable)  you need to do this via the download

**Comment by kimrutherford** [comment]
> The Fasta file from here https://www.pombase.org/downloads/protein-datasets

Thanks.  That's generated by the nightly load.  I'll change the code for tonight's load.

**Comment by ValWood** [comment]
Draft News item.

Cutomizable Fasta headers.
If you download protein or DNA Fasta sequence from the Advanced  search https://www.pombase.org/query download options you can now  customize the Fasta header
(for example, to include coordinates, various IDs, description etc). 
We have also extended the default  headers associated with the downloadable Fasta protein database to include primary (gene)  name and gene product description.

**Comment by ValWood** [comment]
Yes the download option looks good!

SPBC1683.10c pcl1|vacuolar ferrous iron/manganese transmembrane transporter Pcl1|Q9P6J2||protein coding|163534|165317|II|reverse
MWSIFEARPKEAHSVNKIGWLRASVLGANDGILSLSGLLVGVVAANADIKVILITGVAGL
MSGALSMAVGEYVSVSSQADLEDADLQLERREMDADWDAEVDELAAIYRGRGLDEELSRT
VAVQLMEYNALEAHARDELGINIHTTAKPTLAALSSAASFSVGGIFPLLTSLITPLEYLS
LVLPIATMFFLGMLGFVGAHIGGAKRVRAILRAVVLGLLAMAATALVGRLLEIHALSLQY
AI*

**Comment by kimrutherford** [comment]
> That's generated by the nightly load. I'll change the code for tonight's load.

The code is changed.  I'll check when the load finishes.

The load failed because of a problem with an input file.  I've fixed it in SVN and restarted things.  It should finish at lunchtime or so.

**Comment by kimrutherford** [comment]
> The code is changed. I'll check when the load finishes.

It's updated now: ftp://ftp.pombase.org/pombe/genome_sequence_and_features/feature_sequences/peptide.fa.gz

How's this?:

```
>SPAC1002.01:pep mrx11|mitochondrial expression network (MIOREX) component Mrx11
MLPPTIRISGLAKTLHIPSRSPLQALKGSFILLNKRKFHYSPFILQEKVQSSNHTIRSDT
KLWKRLLKITGKQAHQFKDKPFSHIFAFLFLHELSAILPLPIFFFIFHSLDWTPTGLPGE
YLQKGSHVAASIFAKLGYNLPLEKVSKTLLDGAAAYAVVKVSYFVENNMVSSTRPFVSN*
>SPAC1002.02:pep pom34|nucleoporin Pom34
MASTFSQSVFARSLYEDSAENKVDSSKNTEANFPITLPKVLPTDPKASSLHKPQEQQPNI
IPSKEEDKKPVINSMKLPSIPAPGTDNINESHIPRGYWKHPAVDKIAKRLHDQAPSDRTW
SRMVSNLFAFISIQFLNRYLPNTTAVKVVSWILQALLLFNLLESVWQFVRPQPTFDDLQL
TPLQRKLMGLPEGGSTSGKHLTPPRYRPNFSPSRKAENVKSPVRSTTWA*
>SPAC1002.03c:pep gls2|glucosidase II alpha subunit Gls2
MRYHGICWFIFQAAIIFAIFGSCQGAFRHQFKTAEQDGFARRNRDLAKFQKENLNWNGLF
QLNSISYNSGVVSGVFEQQSENGENQHLFPFSISFLKNDVVRFQMDEKSRLEGTVEYEKN
ILTKRRFDASTELGFNERAEVYGKDAHLLEQTSTSLTIRYGSHGRFTVIVTFSPFKVEFQ
```

**Comment by ValWood** [comment]
Great!

**Comment by ValWood** [comment]
WOuld it be better to also have a "|" between sys name and gene name?

**Comment by kimrutherford** [comment]
Many programs expect the ID to be the first field followed by a space.

**Comment by ValWood** [comment]
OK, I wondered if there was a valid reason.

**Comment by kimrutherford** [comment]
What else do we need to do on this?  Just updating the docs?

**Comment by ValWood** [comment]
I think so

**Comment by ValWood** [comment]
There might be a helpdesk ticke t to close...

**Comment by mah11** [comment]
news done; documentation hived off to #1258

**Comment by kimrutherford** [comment]
Reopening to remind myself to send a tweet with screenshot after Easter.

**Comment by mah11** [comment]
Did we still want to change "Sequence descriptions:" to "Include in headers:"?

**Comment by kimrutherford** [comment]
> Did we still want to change "Sequence descriptions:" to "Include in headers:"?

I think "Include in headers" is an improvement.

**Comment by ValWood** [comment]
ok

**Comment by kimrutherford** [comment]
> I think "Include in headers" is an improvement.

Done.

**Comment by kimrutherford** [comment]
I finally got around to sending a tweet: https://twitter.com/PomBase/status/1123700015606767618

**Comment by ValWood** [comment]
As far as I can see this can close. HAs pombelist, tweet, docs all done
