### ISSUE TITLE
slim tool is broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1177]
all genes go into the "not covered by the slim bin"

v

**Comment by ValWood** [comment]
actually it works for a query, but not for an uploaded list, I think...

**Comment by mah11** [comment]
it's working for me either way

**Comment by ValWood** [comment]
Hmm, I was using lists in my history.. need breakfast and will then dig deeper....

**Comment by mah11** [comment]
I tried one and it worked too ...

**Comment by kimrutherford** [comment]
> all genes go into the "not covered by the slim bin"

That's a worry.  I have a ask: did you have a list of unknown genes?  :-)

**Comment by ValWood** [comment]
I thought that at first but no. try this list:

[gene_list.txt](https://github.com/pombase/website/files/2940510/gene_list.txt)

**Comment by mah11** [comment]
bizarre - I get the bug with that list, but not with any other list I try

**Comment by kimrutherford** [comment]
Something is very wrong.  If you start from a slim term like detoxification:
  https://www.pombase.org/term_genes/GO:0098754
Then get the gene list and press the slim button, none of the genes are in the detoxification category.  That makes no sense.

I don't think it's an ontology problem and I haven't change the slim code in weeks.

**Comment by ValWood** [comment]
OK this is weird.
The slim looks OK right now.
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

I also get the problem with this list?
SPCC306.06c
SPAC2E1P3.04
SPCC2H8.05c
SPBC21.02
SPCC126.15c
SPBC365.14c
SPAC1805.14
SPAC9G1.07
SPBC19G7.18c
SPBC557.02c
SPCC1259.08
SPCC594.02c

**Comment by mah11** [comment]
It doesn't even have the decency to affect all slim terms - query-then-slim output looks fine for DNA recombination (GO:0006310) or protein modification by small protein conjugation or removal (GO:0070647).

**Comment by ValWood** [comment]
It seems tat certain gene do not slim. bqt2 for example.

but on the gene page it is slimmed to meiotic nuclear division
https://www.pombase.org/gene/SPAC1002.06c

**Comment by mah11** [comment]
bqt2 also appears on the term page for meiotic nuclear division
https://www.pombase.org/term_genes/GO:0140013

**Comment by ValWood** [comment]
when I slim everything:

![everything](https://user-images.githubusercontent.com/7359272/53949142-575ba380-40c1-11e9-9122-debb44a9ab5c.jpg)

**Comment by ValWood** [comment]
so some terms are ignored...

**Comment by ValWood** [comment]
but not here:
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

**Comment by kimrutherford** [comment]
I think I've fixed this.  I think the slim fix won't cause problems elsewhere but please let me know if you spot any weirdness.

**Comment by ValWood** [comment]
https://github.com/geneontology/amigo/issues/558

**Comment by ValWood** [comment]
OK I just noticed you fixed it.
But did you fix it, or  did you make it more robust to an underlying transitivity issue?

**Comment by kimrutherford** [comment]
> But did you fix it, or did you make it more robust to an underlying transitivity issue?

It was definitely a bug in the code.  In some cases it was ignoring the parent-child relations when the parent had no annotations.  There was no ontology problem.
