### ISSUE TITLE
have to reload every gene page to see correct annotations

### ISSUE THREAD

**Issue by mah11** [pombase/website#118]
If I use the search box in the header, it appears to go to the gene page if there's a single match. But the annotations don't update completely unless I then reload the page. 

So far, I think it's got these symptoms, although I've only done a small amount of testing, so surprises could lurk:

- it only happens with the search box; if I follow a link to a gene, or manually stick a different systematic ID in the URL, the new page loads completely on the first try

- when a page doesn't update correctly, plain reload fixes it (i.e. I don't need shift+reload)

- I'm pretty sure it happens in all three of the browsers I've tried (Firefox, Safari, Chrome)

(Looks like this turned out to be the problem behind #113 too.)

**Comment by ValWood** [comment]
yep!

**Comment by kimrutherford** [comment]
I think this is happening when there is a Javascript error in the page.  Mostly Javascript errors are silent so you might not notice a problem.

Unfortunately sometimes after an error there is a knock-on effect.

I'll fix the error handling so that a single problem doesn't cause this.

**Comment by kimrutherford** [comment]
Was it just the phenotype annotations that weren't updating correctly.  If so, that was probably fixed by #126.

Of it was just the extensions not appearing it might have been #120, which I've also fixed.

**Comment by mah11** [comment]
Drat, I don't remember precisely, but I definitely saw it with phenotypes when I opened the ticket, and I'm not seeing the problem with GO annotations for several genes I've just checked now. So _probably_ just phenotypes ...

**Comment by kimrutherford** [comment]
OK, I think I'll close this.  Please re-open if you spot other problems.
