### ISSUE TITLE
something weird happened to this graph

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1186]
In a  nice way, but I don't think it is correct!

a lot (but not all) of the 'uncurated' paper went missing. MAinly the recent ones. Check to the version in the rotations.

![something wierd has happened](https://user-images.githubusercontent.com/7359272/54339678-6b595500-462d-11e9-8102-7afbc6d759d0.jpg)

**Comment by ValWood** [comment]
![rotations](https://user-images.githubusercontent.com/7359272/54339750-a22f6b00-462d-11e9-9422-a82f599663dd.jpg)

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now:

![curated-graph-fix-1](https://user-images.githubusercontent.com/90474/54585719-bf29cb00-4a7f-11e9-82f3-45d2293b58b1.png)
