### ISSUE TITLE
More condensing of GO

### ISSUE THREAD

**Issue by ValWood** [pombase/website#119]
iIn the current pombase, GO data is one one row unless there are mulitiple publications or extensions in which case  there is a new row.

Compare:
![screen-shot](https://cloud.githubusercontent.com/assets/7359272/21717339/3c9107ac-d408-11e6-91e7-90e6e5e7aa21.jpg)

I think this makes it quite a bit more condensed. It might only be possible with abbreviated GO evidence codes (full code mouse over)

**Comment by kimrutherford** [comment]
It's much better now.

**Comment by ValWood** [comment]
It is!
