### ISSUE TITLE
graph for curator vs community horizontal axis

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1194]
I this we discussed this but I can't find a ticket.
Were we going to put all pre 1970 papers in one bin <1970?
![graph](https://user-images.githubusercontent.com/7359272/54923163-9717ed00-4f01-11e9-9502-46484e0a3bcc.jpg)

**Comment by kimrutherford** [comment]
Yep, we discussed that but I can't find the issue.  Should I go ahead and make the change?

**Comment by Antonialock** [comment]
yeah that would look better I think

**Comment by kimrutherford** [comment]
I've made this change.  I plan to do a Canto update tonight so you'll see the change in the morning.

![fixed-curated-graph-1](https://user-images.githubusercontent.com/90474/55066578-f4b75f80-50e2-11e9-85ec-b0bab633bac0.png)

**Comment by kimrutherford** [comment]
That change is on the main site now.
