### ISSUE TITLE
Update InterPro in nightly load

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1197]
https://www.ebi.ac.uk/interpro/release_notes.html

**Comment by kimrutherford** [comment]
I've updated the InterPro input file.  I'll check the load on Wednesday morning.

**Comment by kimrutherford** [comment]
All looks good.  We've now using InterPro 73.0

**Comment by ValWood** [comment]
News item (very short)
- [ ] InterPro Update  
"PomBase is now using InterPro Version 73:0. InterPro 73.0 integrates 1,531 new methods from the CATH-Gene3D (122), CDD (330), PANTHER (1075), Pfam (2), PROSITE profiles (1) and TIGRFAMs (1) databases, and covers 81.2% of UniProt Knowledgebase release 2019_02. 
See https://www.ebi.ac.uk/about/news/service-news/InterPro-73.0 for the release notes.

- [ ] Retweet. PomBase now includes InterPro V 73:0
https://twitter.com/InterProDB/status/1111216956869357568

**Comment by mah11** [comment]
NEW TICKET for news item because it's a different task

**Comment by ValWood** [comment]
The announcements have always been part of the task so far but hey ho...
