### ISSUE TITLE
Gerry data

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1198]
~Gerry Smith lab
 DSBs in wt and various mutants
 Rec protein binding in wt and some mutants.  
Fowler et al., Mol Cell 2013, Figures 3 and 6; 
Fowler et al., Genome Res 2014, Figures 1B and D, 3B, S1D and E~
moved to https://github.com/pombase/website/issues/1441

~"3C" type of analysis, showing physical clustering of meiotic DSB hotspots by ligation, immunoprecipitation, and deep sequencing
Fowler et al., PNAS 2018 (Figure 4B and C, and S7A and B)
(this should probably move to a page where we collect 3C data).  
PMID: 30217891  
(https://github.com/pombase/website/files/3371680/Fowler.et.al.PNAS.2018.complete.pdf)~
moced to https://github.com/pombase/website/issues/1479

 Rec12-oligo data on on GSE49977 (a GEO account).

~RT ticket number 6827~

**Comment by ValWood** [comment]
Edited to provide only required information 
add helpdesk ticket link to refer to original e-mail.
v

**Comment by Antonialock** [comment]
done

**Comment by Antonialock** [comment]
[Fowler et al., PNAS 2018 complete.pdf](https://github.com/pombase/website/files/3371680/Fowler.et.al.PNAS.2018.complete.pdf)
[Uploading Fowler et al. Mol Cell 2013 supp info, genome-wide data.pdf…]()
[Uploading Fowler et al., Genome Res (2014), main plus supp info.pdf…]()

**Comment by ValWood** [comment]
Was anything  done here yet?
If not I will put in the queue ticket

**Comment by Antonialock** [comment]
yes Gerry and I sorted all metadata from their browser-suitable publications. He was going to try to get tracks from Kyle. I guess he was unsuccessful.

**Comment by ValWood** [comment]
I will e-mail Kyle.

Where is the meta-data?

**Comment by ValWood** [comment]
Closing. I think there are still some to host but Kykle said he would work through them when he has chance.
