### ISSUE TITLE
tweak advanced search

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1199]
I searched for translation but "translation" only wasn't the first hit....I had to go to quickgo to get the ID which isn't great for a regular user

<img width="562" alt="Screenshot 2019-03-30 at 21 32 02" src="https://user-images.githubusercontent.com/12727506/55281987-61c13400-5333-11e9-8dd0-dd8b5663130c.png">

**Comment by kimrutherford** [comment]
Yep, that's not good.  I've also noticed that the synonyms show up too much.  I'll have a look.

**Comment by kimrutherford** [comment]
> Yep, that's not good. I've also noticed that the synonyms show up too much. I'll have a look.

Both problems were caused by the same dodgy lucene query.  It's much better now.  Thanks for pointing out the problem.

![translation-autocomplete-1](https://user-images.githubusercontent.com/90474/55303530-42491900-54a3-11e9-828a-dc7ef4c6c9ac.png)
