### ISSUE TITLE
GO view without extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#120]
sometimes when I first access a page, I see

![1](https://cloud.githubusercontent.com/assets/7359272/21728413/07ba7e56-d43e-11e6-9abf-a02fa67d8073.jpg)

the full view is like this, so the compact view should have extensions:

![2](https://cloud.githubusercontent.com/assets/7359272/21728461/3647c7d8-d43e-11e6-9721-0005373e90bc.jpg)

then when I go back to the compact view I see:

![3](https://cloud.githubusercontent.com/assets/7359272/21728477/50f72196-d43e-11e6-85a2-39b69f6fe39b.jpg)

**Comment by kimrutherford** [comment]
Yeah, that's not good.  Which gene page was it?

**Comment by ValWood** [comment]
cds1

**Comment by kimrutherford** [comment]
Should be fixed now.
