### ISSUE TITLE
remove filter from complex file

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1201]
I think this info (Complex filters), is now in a config  file, but I can't remember where.

Id like to remove 
proteasome complex (GO:0000502)
from the filtered complexes.

rationale, for  the record
This is because at the moment the  sub parts alpha, beta, lid and  base all float around independanty in network figures. Since they are always a functional unit they should  be grouped. I tried to track down physical interactions to group them, but none were clearly direct  (co- affinity pull down).

**Comment by mah11** [comment]
If you mean you want GO:0000502 to be included in the downloadable complex file, done. (If not, I'd need more clues.)

**Comment by ValWood** [comment]
Ah it used to be a filter of complex terms to omit. Has that changed to a list of *included IDs* instead ?
Anyway  yes I want  GO:0000502 to be included in the complex file. Its a bit of redundancy but it will look better in the networks.

**Comment by mah11** [comment]
No, the config still lists IDs to exclude. My question was meant to clarify the desired outcome.

**Comment by kimrutherford** [comment]
> I think this info (Complex filters), is now in a config file, but I can't remember where.

GO:0000502 is in this file: supporting_files/GO_terms_excluded_from_pombase.txt

I think that's the only config file it appears in.  Is that what you were after?

**Comment by ValWood** [comment]
no Midori sorted it. This used to be in a complex filter file, but at some point the way we do this changed. It's now done another way in yaml. Now sorted.

**Comment by ValWood** [comment]
I'll keep this open until GO:0000502 appear here:
ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv

and here
http://www.esyn.org//builder.php?type=Graph&term=GO:0000070&interactionType=physical&source=pombase&includeInteractors=false

**Comment by mah11** [comment]
> GO:0000502 is in this file: supporting_files/GO_terms_excluded_from_pombase.txt

It also used to be in the part of pombase_v2_config.json that lists GO CC terms to be excluded from the downloadable macromolecular complex file, until I deleted it for this very ticket.

**Comment by ValWood** [comment]
Now I am confused.

Do we still use
GO:0000502 is in this file: supporting_files/GO_terms_excluded_from_pombase.txt
I thought it was replaced by some yaml. But this is what I want to check, if everything resolves as expected.

**Comment by mah11** [comment]
> Do we still use ... supporting_files/GO_terms_excluded_from_pombase.txt

Yes, but for a different purpose - this file is for terms that we don't want to use for *direct* annotation (but aren't tagged in the ontology for whatever reason). Any annotations to terms on this list get reported in the excluded_go_terms_softcheck log.

Filtering for the complex file (ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv) uses the pombase_v2_config.json file. On Monday I removed GO:0000502 from that config file, so genes annotated to it by transitivity will be associated with it in the complex_annotation file.

**Comment by ValWood** [comment]
Yes ignore. I wasn't reading it properly. Different file.
I'm just waiting for the changes to filter through.

**Comment by ValWood** [comment]
This didn't filter through to the esyN networks yet. Need to figure where the block is.

**Comment by ValWood** [comment]
GO:0000502
isn't in
ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv
yet....

**Comment by kimrutherford** [comment]
> GO:0000502 isn't in
> ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv
> yet....

There are some child terms of GO:0000502 in that file, like GO:0031595.  Are there some annotations directly to GO:0000502 that are missing?

**Comment by mah11** [comment]
> There are some child terms of GO:0000502 in that file, like GO:0031595. Are there some annotations directly to GO:0000502 that are missing?

No, GO:0000502 is on our internal don't-annotate-directly list. But it appears that whatever generates Complex_annotation.tsv doesn't work the way I thought it did. It looks like what actually happens is that if a GO CC term has no direct annotations, it's not being included in the Complex_annotation.tsv file via annotations to subclasses or parts. We thought that removing GO:0000502 from the exclusion list in the pombase_v2_config.json file would get it included in the complex file, associated with the genes annotated to its descendants, but nope.

GO:0000502 is not the only affected term; GO:0000798 is an older example that is also affected. In both cases, the term is not on the exclusion list, but also is not in the Complex_annotation.tsv file. I have not investigated enough to tell whether all affected terms are in one or more do-not-annotate lists (the GO subset or our additional file), but these two examples are.

Does a term have to have direct annotations to get into Complex_annotation.tsv? Maybe it shouldn't, in light of what Val and I thought would happen when we changed the config file.

In any case, could you clarify what is actually happening, and see if that is indeed as intended?

**Comment by ValWood** [comment]
Let's chat about this tomorrow cos I can't remember what we do.... I put it on the list...

**Comment by kimrutherford** [comment]
The Complex_annotation.tsv file contains only direct annotations.  It includes all annotations for GO:0032991 and descendants except for those configured as "excluded_terms" in the config file.  Duplicates are removed before writing the file.

```
   "file_exports": {
     "macromolecular_complexes": {
       "parent_complex_termid": "GO:0032991",
       "excluded_terms": [
         "GO:0099023", "GO:0022624", "GO:0005834", "GO:0000153", "GO:0000835",
         "GO:1990904", "GO:0032806", "GO:0000307", "GO:0016461", "GO:1990421",
         "GO:0008023", "GO:0017102", "GO:0044796", "GO:0032777", "GO:0033100",
         ...
```

**Comment by ValWood** [comment]
Ah OK, then this data won't get  into the file. It would be a bit overkill to annotate everything additionally to GO:0000502

I will go back to my original plan and try to connect the subcomplexes together using a direct physical interaction. I tried this way first of all, but I could not find any suitable data. Hopefully there is a high-quality binary interaction somewhere....
