### ISSUE TITLE
announce gene-info chrome extension

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1207]
announce gene-info chrome extension (when released later this month)

something like
https://thebiogrid.org/news/207

more info
https://gene-info.lunenfeld.ca/

**Comment by mah11** [comment]
Looks like their news item is live, so is there any reason for us to wait?

**Comment by mah11** [comment]
and is this on this tracker for a news item?

**Comment by ValWood** [comment]
We are waiting for the pombase  stuff to be included. We will appear  in the next release.

Sorry should have included:
https://github.com/knightjdr/gene-info/issues/6#issuecomment-479123171

**Comment by ValWood** [comment]
This is really  a reminder.  I want to test the chrome extension. I haven't used it yet.

**Comment by kimrutherford** [comment]
The news item is now on the main site.

The title is "S. pombe gene list".  Should we change that to "S. pombe Gene info browser extension"?

**Comment by Antonialock** [comment]
"S. pombe gene list" is a bit meaningless

 "S. pombe gene info browser extension" is a bit lengthy but say what's in the box

I've been using it last week or so....it gets a bit annoying because it keeps popping up when I don't want it to :-) at least now I can update it to include pombe

**Comment by ValWood** [comment]
Yes, I might remove it ;) It's a bit random...

**Comment by ValWood** [comment]
title 
S. pombe included in gene-info browser extension

**Comment by kimrutherford** [comment]
> I've corrected the extension name in the title (it's "Gene Info", not "gene-info").

That change will be on the main site in 5-ish minutes.
