### ISSUE TITLE
Annotation extension display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#121]
in
Annotation_extension_and_reciprocal_display.txt 
directly_positively_regulates   directly activates      directly activated by
but on website it's

![cdc25-2](https://cloud.githubusercontent.com/assets/7359272/21728563/c1495392-d43e-11e6-9506-6ac05d2c63c9.jpg)

Is this just a synching thing?

**Comment by kimrutherford** [comment]
> Is this just a synching thing?

I messed up the cases where there is a reciprocal display name for the target of section.  I'll fix it.

**Comment by kimrutherford** [comment]
> I messed up the cases where there is a reciprocal display name for the target of section.

On closer look, I actually messed up the handling of "if_descendent_of" in the configuration.  If "if_descendent_of" was there is was working fine.

Fixed now.
