### ISSUE TITLE
Publication summary page

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1214]
Create a page listing/summarising the uncurated papers (title, authors, years...- or something along those lines) with links to claiming the publication in canto

**Comment by mah11** [comment]
I worry that it'll be a boring laundry list on a page, but if users like it, I don't have to look at it.

**Comment by ValWood** [comment]
I doubt it will encourage people to curate much.... I'll put low priority and we can discuss if we really want to do this. MAybe there are better ways...

**Comment by ValWood** [comment]
I'm going to close this. I don't think it will be so helpful compared to other actions/activities. We will gear up to these in the New Year with the community curation paper/ tutorials etc

**Comment by ValWood** [comment]
We can always revisit later

**Comment by kimrutherford** [comment]
> We can always revisit later

I like Antonia's suggestion.

At some point I'd like to have a page that gives an overview of all pombe papers, with curated vs uncurated, high vs low throughput, number of annotations per paper and number of genes per paper.  So like the Canto stats page but just for papers and with links to various lists (like the list of uncurated papers).

I've put no thought into how this would work or look.  Or if it's at all useful.  :-)

**Comment by ValWood** [comment]
Yes actually I agree a summary table would be nice. It would be useful to have a public snapshot of curation progress/triage status. I was thinking  only of long lists.
I will re-open this one

**Comment by ValWood** [comment]
I'll close this.

We already have an annotation stats page
https://curation.pombase.org/pombe/stats/annotation
with details of curated/uncurated papers.

The most likely place  people will look is the actual publication page, and this will have a clear message saying the paper is uncurated and asking people to contribute.

I think we could encourage more people to curate by asking them to check the status of their publication pages.
