### ISSUE TITLE
Export a file with transmembrane regions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1215]
For Snezhka.  See helpdesk ticket #6851

**Comment by ValWood** [comment]
maybe 

>ID_tm_1_coordinate_coordinate
HHHHLLLLL
>ID_tm_2_coordinate_coordinate
LLLHHHHH

so it would end up as standard fasta, with info about position and we could make it available

**Comment by kimrutherford** [comment]
A tab delimited, one line per gene file would probably be easier to parse.  But we could have more than one file in different formats if we wanted to.

**Comment by ValWood** [comment]
OK let's make 2 files, fasta might be useful is people actually want to use the sequence in tools.
Will point Snezhka to this ticket to see if either or both are what she wants

**Comment by mah11** [comment]
housekeeping note: I have merged helpdesk ticket 6851 into 6850

**Comment by ValWood** [comment]
Dear Val,


Both files would be great, thank you!!

Snezhka

**Comment by kimrutherford** [comment]
I've had a go at this. For now it's in the nightly_update directory.  We need to decide where in the FTP site it should live long term.

ftp://ftp.pombase.org/nightly_update/misc/transmembrane_domain_coords_and_seqs.tsv

**Comment by ValWood** [comment]
Add to protein datasets
https://www.pombase.org/downloads/protein-datasets

and copy to
ftp://ftp.pombase.org/pombe/Protein_data/
?

**Comment by kimrutherford** [comment]
The file will be in ftp://ftp.pombase.org/pombe/Protein_data/ after the next load.

**Comment by mah11** [comment]
> The file will be in ftp://ftp.pombase.org/pombe/Protein_data/ after the next load.

I just looked there, and I don't see the new file. I'll add a link to https://www.pombase.org/downloads/protein-datasets once it's in its new ftp home.

**Comment by kimrutherford** [comment]
I can see it: ftp://ftp.pombase.org/pombe/Protein_data/transmembrane_domain_coords_and_seqs.tsv

**Comment by mah11** [comment]
and now I can see it too .... coulda sworn it wasn't there yesterday (but I may be losing it)
