### ISSUE TITLE
Graphical abstract for PMID: 30773398 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1217]
![Uploading fx1_lrg.jpg…]()

to do
- [x] finish session & confirm with authors
- [x] tweet
- [x] write announcement
- [x]  useful for PAINT

**Comment by ValWood** [comment]
text
Set7, a histone methyltransferase for the uncharted histone H3 lysine 37 (H3K37) mark

**Comment by ValWood** [comment]
![fx1_lrg](https://user-images.githubusercontent.com/7359272/56081941-b9b76a80-5e0a-11e9-856f-66a715db7792.jpg)

**Comment by ValWood** [comment]
This research spotlight can be activated
Val

**Comment by kimrutherford** [comment]
The Spotlight is on the main site now: https://www.pombase.org/archive/spotlight

I'll tweet this during the week.

**Comment by kimrutherford** [comment]
I've sent a tweet: https://twitter.com/PomBase/status/1123756262121005059

**Comment by ValWood** [comment]
@pgaudet  @marcfeuermann  this one will be useful for PAINt, I think it's the first 
histone H3-K37  example.
https://github.com/geneontology/go-ontology/issues/17061

https://www.pombase.org/reference/PMID:30773398
(set7)

**Comment by kimrutherford** [comment]
I think everything here is done.
