### ISSUE TITLE
Graphical abstract for PMID:30853434  research spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1226]
Brilliant session:

![fx1_lrg](https://user-images.githubusercontent.com/7359272/56157472-7f3f0080-5fb7-11e9-8cbe-1bbddf15e15c.jpg)

**Comment by ValWood** [comment]
- [ ]  finish session & confirm with alaina
 - [ ]  tweet
 - [ ]  write announcement

**Comment by ValWood** [comment]
This research spotlight can be activated
cheers
Val

**Comment by kimrutherford** [comment]
This Spotlight is also on the main site now: https://www.pombase.org/archive/spotlight

I'll tweet this after Easter.

**Comment by ValWood** [comment]
can close once pombase tweeted

**Comment by ValWood** [comment]
Actually I tweeted this whnen curated so done
