### ISSUE TITLE
research spotlight for PMID: 30925937 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1227]
- [x]  announcement text

Unexpected insertion of carrier DNA during CRISPR–Cas9, and "unknowns" remain "unknown"

image ![spotlight](https://user-images.githubusercontent.com/7359272/56200239-45f9a580-6036-11e9-9f4c-e8138a4fbde5.jpg)

- [x]  retweet https://twitter.com/macneill_lab/status/1111897468881563648

**Comment by ValWood** [comment]
I have approved this one so it can go live tomorrow

**Comment by kimrutherford** [comment]
The Spotlight is live now.
