### ISSUE TITLE
User track upload 

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1228]
I thought there was a ticket for this but I can't see it. 

I've had multiple requests from people in Jurgs group to implement the ability to upload 'private' tracks in the browser (things they are currently working on but not ready to share with the wider world)

I tried downloading a bigwig and a bed file from our FTP site and uploading them using the upload function in JBrowse, but I can't get it to display the tracks. Am I missing something or does something need tweaking with the browser to enable this?

<img width="331" alt="Screenshot 2019-04-17 at 07 49 23" src="https://user-images.githubusercontent.com/12727506/56266993-79473d80-60e5-11e9-85b5-4233150556b3.png">

<img width="610" alt="Screenshot 2019-04-17 at 07 50 18" src="https://user-images.githubusercontent.com/12727506/56266995-7cdac480-60e5-11e9-8fa0-f4d693954051.png">

**Comment by kimrutherford** [comment]
Which file were you uploading?  It's possible there's a size limit.  I just tried this small BigWig file and it worked in Firefox and Chrome: ftp://ftp.pombase.org/external_datasets/ERP001075/ERS078446.bw

**Comment by Antonialock** [comment]
I can't remember. I just tried it with Angad's files and they work fine. I'll let Maria know since she requested it. 

Will open a new ticket if they spot any oddities.
