### ISSUE TITLE
Gene count of 0 on cdc2 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#123]
In the Literature section on the cdc2 page the follow publication is listed as having zero genes:

EnsemblCompara GeneTrees: Complete, duplication-aware phylogenetic trees in vertebrates

**Comment by kimrutherford** [comment]
> EnsemblCompara GeneTrees

The bug is that it's not counting genes from orthologs towards the gene counts and we only have orthologs from that paper.

Do we want to include that paper in the Literature section on the gene pages?  We have a publication page for it:
  http://pombase2.bioinformatics.nz/reference/PMID:19029536

(In case you're on the fence about it, it's easier for me if we do include that paper so I don't need to make a special case.  I'll fix the gene count for it).

**Comment by kimrutherford** [comment]
>  I'll fix the gene count for it

The count is fixed (3459) so now if you sort by gene count it goes to the bottom of the page.

**Comment by ValWood** [comment]
No we  don't need to, again its only for a method. In  fact I don't think this is fpr the manually assigned othologs....
