### ISSUE TITLE
i) accept uniprot accessions in gene list upload 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1230]
Direct quote from survey:

I would find it particularly helpful if an additional column was included for gene names for the Uniprot reference- for e.g when searching for genes that show a specific deletion phenotype etc. * It would be helpful if uniprot numbers could be used to search in the advanced gene list search too (or protein search I suppose! **)

My annotation:
* we plan to enable so that Uniprot accessions can be included in the output. If we allow user configuration at some point we could allow the user to configure a column that displays UniProt accessions maybe? 
**note you can already do this (simple search on UniProt accessions)

**Comment by kimrutherford** [comment]
Sorry, I don't understand this one either.  What needs doing?

**Comment by mah11** [comment]
At present, the gene list search, i.e.

Advanced search -> gene IDs -> enter or upload a list

takes PomBase systematic IDs. If I understand correctly, the request is for it to accept UniProt accessions as well. (I'm getting that from the ticket title; the summary is much harder to follow.)

**Comment by mah11** [comment]
On re-reading, I've noticed that there also seems be a request to include UniProt accessions as one of the results download options ... but that's already available.

**Comment by mah11** [comment]
.. or maybe that second request is for the UniProt accessions to be included in the table that gets displayed on the search results page, or be an option there later

**Comment by ValWood** [comment]
I updated the comment. I think the user wants to be able to 
i) upload a list of uniprot accessions
ii)  view uniprot accessions when looking at a results table

(downloading uniprot accessions is also sort of related).
I will should probably split this ticket but I'll wait until I have finished  going through the reponses.

**Comment by kimrutherford** [comment]
> i) upload a list of uniprot accessions

I think that would be straightforward to implement.  We could have a "Uniprot IDs" tab under "Gene IDs" in the advanced search.

> ii) view uniprot accessions when looking at a results table

For that I think it would make sense to allow the users to customise which columns appear on a result page. So they could show the same columns that are available for download.  That would also not be too hard to implement.

**Comment by ValWood** [comment]
Yes the download option looks good!

>SPBC1683.10c pcl1|vacuolar ferrous iron/manganese transmembrane transporter Pcl1|Q9P6J2||protein coding|163534|165317|II|reverse
MWSIFEARPKEAHSVNKIGWLRASVLGANDGILSLSGLLVGVVAANADIKVILITGVAGL
MSGALSMAVGEYVSVSSQADLEDADLQLERREMDADWDAEVDELAAIYRGRGLDEELSRT
VAVQLMEYNALEAHARDELGINIHTTAKPTLAALSSAASFSVGGIFPLLTSLITPLEYLS
LVLPIATMFFLGMLGFVGAHIGGAKRVRAILRAVVLGLLAMAATALVGRLLEIHALSLQY
AI*

**Comment by ValWood** [comment]
OK, I am going to open separate tickets with different priorities.

**Comment by ValWood** [comment]
this comment
Yes the download option looks good!
SPBC1683.10c pcl1|vacuolar ferrous iron/manganese transmembrane transporter Pcl1|Q9P6J2||protein coding|163534|165317|II|reverse
is in the worng ticket
