### ISSUE TITLE
New DB xref SWISS-MODEL

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1231]
- [x] New database  xref

Classifier : Structure
Resource Name : SWISS-MODEL
ID: O74184
Link : https://swissmodel.expasy.org/repository/uniprot/G5ECJ4). 
Description : Homology modelling server

- [ ]  news item/ Announcement
The external links section now provides protein specific links  to
SWISS-MODEL, a fully automated protein structure homology-modelling server, accessible via the ExPASy web server, or from the program DeepView (Swiss Pdb-Viewer). This link will search the Swiss-model structure repository for available sequences and present results. If no structure or model is available you can easily interactively search for templates (single click)  and model  one and refine in your own workspace.

**Comment by ValWood** [comment]
Or probably Midiri can add this?
Or I can if somebody reminds me where :)

**Comment by kimrutherford** [comment]
The links are now visible in the External references sections.

**Comment by ValWood** [comment]
Small tweaks from Stefan:

here is a (minor) revision of your text:

"""
The external links section now provides protein specific links to
SWISS-MODEL, a fully automated protein structure homology-modelling 
server, accessible via the ExPASy web server. This link will lead to a 
SWISS-MODEL Repository page for each sequence and present results. If no 
structure or model is available, you can either trigger adding an entry 
to the repository with a single click or easily interactively search for 
templates and build models in your own SWISS-MODEL workspace


and

for the links

This looks good!

Can you write "SWISS-MODEL Repository" instead of just "SWISS-MODEL"? We 
like to refer to SWISS-MODEL as the modelling service/ pipelne and 
"SWISS-MODEL Repository" as our database of models. THey also go by 
different sets of publications.

**Comment by mah11** [comment]
> Can you write "SWISS-MODEL Repository" instead of just "SWISS-MODEL"?

did this bit, and a news items that lumps the new prediction-y links

**Comment by ValWood** [comment]
great...

**Comment by ValWood** [comment]
This news item has the heading
Integrated motif search?

**Comment by ValWood** [comment]
also further down:

![also](https://user-images.githubusercontent.com/7359272/56453603-d2f57500-633c-11e9-8e67-53abc779bdba.jpg)

**Comment by kimrutherford** [comment]
> This news item has the heading
> Integrated motif search?

I'll fix that.  What should the heading be?

I'll fix the image too.

**Comment by kimrutherford** [comment]
> What should the heading be?

I've changed it to: "New external links from gene pages"
which isn't very exciting.

Any suggestions for a better title?

**Comment by ValWood** [comment]
I would say
New homology modelling and ortholog links on gene pages
(a bit more precise)

**Comment by kimrutherford** [comment]
> New homology modelling and ortholog links on gene pages

I've made that change.

**Comment by ValWood** [comment]
announced on pombelist too...
