### ISSUE TITLE
Announce InterPro

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1233]
News item (very short)
- [ ] InterPro Update  
"PomBase is now using InterPro Version 73:0. InterPro 73.0 integrates 1,531 new methods from the CATH-Gene3D (122), CDD (330), PANTHER (1075), Pfam (2), PROSITE profiles (1) and TIGRFAMs (1) databases, and covers 81.2% of UniProt Knowledgebase release 2019_02. 
See https://www.ebi.ac.uk/about/news/service-news/InterPro-73.0 for the release notes.

- [ ] Retweet. PomBase now includes InterPro V 73:0
https://twitter.com/InterProDB/status/1111216956869357568

**Comment by mah11** [comment]
#1232
