### ISSUE TITLE
accept uniprot accessions in gene list upload 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1236]
from
https://github.com/pombase/website/issues/1230

accept uniprot accessions in Advanced query gene list upload

**Comment by ValWood** [comment]
kim
I think that would be straightforward to implement. We could have a "Uniprot IDs" tab under "Gene IDs" in the advanced search.

**Comment by kimrutherford** [comment]
> I think that would be straightforward to implement. We could have a "Uniprot IDs" tab under
> "Gene IDs" in the advanced search.

I've done that.  Later it might be better to include Uniprot IDs in a more general ID mapping tools.  But this was a quick fix.

Should we add a link in the search menu?

![uniprot-id-lookup-1](https://user-images.githubusercontent.com/90474/56456375-5fe11280-63bf-11e9-82c4-27fe4f6cce6a.png)

**Comment by ValWood** [comment]
We'll annnounce this next week, we now have a queue of announcements!

**Comment by ValWood** [comment]
> Should we add a link in the search menu?

I didn't answer this question, only just saw it.  WOuld be useful too.

**Comment by kimrutherford** [comment]
>> Should we add a link in the search menu?
>
> I didn't answer this question, only just saw it.  WOuld be useful too.

I've added it to the menu.

**Comment by ValWood** [comment]
removing "announce " label as this was done
