### ISSUE TITLE
Provide a mapping service  S. cerevisiae -> pombe IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1237]
User says:
Recently I would have appreciated the ability to integrate S. cerevisiae gene IDs into the advanced search function, e.g. return a list of pombe homologs of cerevisiae genes and vice versa. 

If we provide a simple mapping service, which lists

1:1
1:many
many:many
no ortholog

and then allows the user to create a list that can be sent to the query builder (or enrichment tool etc when we have one), would be cool. We have the info .....

(could do the same for HGNC IDs)

**Comment by kimrutherford** [comment]
> (could do the same for HGNC IDs)

I think we could make a ID mapping tool where the user can pick ortholog ID or UniProt ID so it's all in one place.

**Comment by ValWood** [comment]
I moved this to the "future" doc as it will be a long way off
