### ISSUE TITLE
allow the user to customize which columns they see in query results tables

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1238]
this could include Uniprot accession numbers (requested in survey)

**Comment by ValWood** [comment]
kim said"
For that I think it would make sense to allow the users to customise which columns appear on a result page. So they could show the same columns that are available for download. That would also not be too hard to implement.

**Comment by kimrutherford** [comment]
> this could include Uniprot accession numbers (requested in survey)

SGD ortholog IDs too I think so that the results from #1237 are more useful.

**Comment by ValWood** [comment]
but if 
SGD ortholog IDs too I think so that the results from #1237 are more useful.
was implimented you would not need to be able to upload SGD IDs to the list search.

The reason I suggest the preliminary step is that the user is aware of exactly what mapped and what didn't.  FungiDB have a mapping service so you can map  a list from an unnannotated genome  to an annotated one for enrichment, but they don't tell you about the things that do not map....and because of the 1:many etc, the number can end up very similar. You then miss the interesing biology in the species-specific portion!

**Comment by kimrutherford** [comment]
I agree about the preliminary mapping step.  I thought that mapping would result in a normal pombe gene list so the users could then use the results in the advanced search?

**Comment by ValWood** [comment]
Yes, sorry I think we are on the same page!

**Comment by kimrutherford** [comment]
> So they could show the same columns that are available for download.

And the download dialog should default to selecting the same columns as the user is viewing.

Should the visible columns be "sticky"?  ie. if I add a UniProt ID column to the current table should that column be shown next time I see a table.  Or should it reset to name, sys-id and product?  (Maybe related to #26)

**Comment by kimrutherford** [comment]
It was raining yesterday so I've started implementing this.  For now it's only pombase-dev and you have to notice the small gear button at the top left.

http://pombase-dev.bioinformatics.nz/term_genes/GO:0000070

![extra-columns-1](https://user-images.githubusercontent.com/90474/56857246-3a579880-69bf-11e9-8c7d-6962ce916f65.png)
![extra-columns-2](https://user-images.githubusercontent.com/90474/56857249-3cb9f280-69bf-11e9-8968-7e8af342a176.png)
![extra-columns-3](https://user-images.githubusercontent.com/90474/56857250-3fb4e300-69bf-11e9-9941-d6ec502f24ae.png)

**Comment by ValWood** [comment]
Ohh nice.

What did you plan longer term. To make it noticeable would you  put the headers in a header bar  to include the "cog" to make it stand out more?

Is there a standard way to present (we don't want to default to all so we need it to be clear that more can be included).

Not sure if it should be sticky, or not.....
@Antonialock  this might be something you could ask on the lab retreat ?

**Comment by kimrutherford** [comment]
> To make it noticeable would you put the headers in a header bar to include the "cog" to make it
> stand out more?

That's a possibility.

Or maybe have a link labelled "Add/edit columns ..." so it's clear.

> Is there a standard way to present

Here's what Thunderbird does.  It's not very obvious:
![thunderbird-table-col-1](https://user-images.githubusercontent.com/90474/57016567-d824bf00-6c6e-11e9-9c0d-dcd9cf885a46.png)

**Comment by ValWood** [comment]
The COG icon will probably  work OK if it is prominent enough:

![toll bar](https://user-images.githubusercontent.com/7359272/57022717-dbe12300-6c27-11e9-93b7-44e49e3397ed.jpg)

**Comment by kimrutherford** [comment]
How's this.  I've turned it into a button to make it more obvious.
![column-config-1](https://user-images.githubusercontent.com/90474/57176428-13600180-6eac-11e9-9da7-6b0b6dc7de4f.png)

**Comment by ValWood** [comment]
i like that

**Comment by kimrutherford** [comment]
I changed the setting button to "[cog] Columns ..." a while ago. Is that OK for now?

**Comment by ValWood** [comment]
yes done.
