### ISSUE TITLE
NOT annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#124]
Display NOT qualifier  by default (all extensions and qualifiers should show in full view).

Make NOT annotation prominent. I can't remember how we did this in PomBase1 because it isn't working correctly right now.
I have a feeling it was in red?
It was definitely displayed at the bottom of the section.

**Comment by mah11** [comment]
> Display NOT qualifier by default

iow, include NOT in the compact display

> Make NOT annotation prominent. ... I have a feeling it was in red?

Yes, it was:

- all NOT GO:nnn annotations grouped together at the bottom of each GO annotation table;

- "NOT" at the start of the line (i.e. leftmost, so it actually reads "NOT GO:nnn termnameyada");

- "NOT" in a reddish yet color-blind-friendly hue.

And it's working in pombase 1 at the moment ...

(ancient history in https://www.ebi.ac.uk/panda/jira/browse/PB-643)

**Comment by kimrutherford** [comment]
I've just queried Chado v61 to see if there are any cases where a gene is annotated with a term and has a separate NOT annotation for the same term.  I wasn't sure there would be any.  I wanted to see how we displayed things currently in that case.

I found 5 results:

    SPBC1709.01         chitin synthase activity
    SPBC15D4.10c        nuclear pore
    SPAC23C11.14        fungal-type vacuole membrane
    SPBC32F12.03c       thioredoxin peroxidase activity
    SPAC23C4.18c        nuclear replication fork

They don't seem to be displayed correctly.  eg. on http://www.pombase.org/spombe/result/SPBC32F12.03c

For: GO:0008379 thioredoxin peroxidase activity
there should be two annotations, one with NOT and one without but it shows both without the NOT.

See:
  https://curation.pombase.org/pombe/curs/ec98ab47f2b47ef1/ro
  https://curation.pombase.org/pombe/curs/50906198d7f94a7a/ro

Another example: for amo1 (SPBC15D4.10c) there is an annotation for nuclear pore and another with NOT but they are both shown as NOT here:
  http://www.pombase.org/spombe/result/SPBC15D4.10c

So I have two questions.  Are the annotations correct?

And how should we display things when there are annotations with and without NOT?

**Comment by ValWood** [comment]
Well spotted.
There will be cases where one paper says something is true and another that it is NOT. These appear to be such cases, although I have opened a tracker ticket to check this is the case based on current knowledge.
https://github.com/pombase/curation/issues/1267

We should
i) display both.
ii) display the NOT annotation at the bottom (so that the NOT is visible in the compact view)
I think?

**Comment by kimrutherford** [comment]
> i) display both.
> ii) display the NOT annotation at the bottom

OK, I'll do that.

**Comment by kimrutherford** [comment]
I think this is now working how you describe:
   http://pombase2.bioinformatics.nz/gene/SPBC32F12.03c

Please close this issue if it's OK.

**Comment by kimrutherford** [comment]
Should the NOT annotation be shown on the term pages?  Currently they aren't.

eg. http://pombase2.bioinformatics.nz/gene/SPBC32H8.02c is NOT protein sumoylation
but nep2 (SPBC32H8.02c) doesn't appear on the protein sumoylation term page:
http://pombase2.bioinformatics.nz/term_genes/GO%3A0016925

**Comment by ValWood** [comment]
I don't think the NOTs need to show on the term page.
They probably aren't necessary on most of the gene pages, but  I think they are definitely only relevant if you are looking  in detail at a gene product.

I guess there are the cases where both are reported though.....hmm, I suppose we could include then at the bottom of the page....

Anyone?

**Comment by ValWood** [comment]
NOTs on the gene pages look fine, nice and clear. But... the NOTs  should not be included in the count total (I guess in this case its easier not to show them on the term page?)

v

**Comment by kimrutherford** [comment]
> I don't think the NOTs need to show on the term page.

OK, thanks.

>  But... the NOTs should not be included in the count total

Yep, the NOTs are excluded from the counts.

> (I guess in this case its easier not to show them on the term page?)

Yep, the counts shown in the table on the gene pages are just the number of genes the are shown on the terms pages.

**Comment by ValWood** [comment]
Are we done here?
@Antonialock  @mah11  I think this seems OK?
Open new tickets for new issues.
