### ISSUE TITLE
links to 3  additional orthology resources

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1241]
Section:Orthologs

Resource: Ensembl Fungal Compara 
Description Alignments, gene trees, orthologs, families
Link format: http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/Compara?db=core;g=SPAC227.07c;r=I:507522-509960;t=SPAC227.07c.1

Resource: Ensembl Pan taxonomic Compara 
Description: Gene tree, orthologs
Link format: http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/PanCompara?db=core;g=SPAC227.07c;r=I:507522-509960;t=SPAC227.07c.1

Resource: Panther Orthologs, Gene trees, Alignments
Link Format: http://www.pantherdb.org/genes/gene.do?acc=SCHPO%7CPomBase%3DSPCC18B5.04%7CUniProtKB%3DQ9USL7

**Comment by mah11** [comment]
I'll do the config; @ValWood will announce

**Comment by mah11** [comment]
config done

**Comment by mah11** [comment]
included in lumped news item on prediction linkies

**Comment by ValWood** [comment]
I announced. Will close this and open ticket for remaining task
