### ISSUE TITLE
orthologs various

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1242]
Lots of comments/request relating to  about orthologs and alignments

ORTHOLOGS and ALIGNMENT
I would like the 'ortholog' section to be expanded to include more species, particularly other fungal model organisms. E.g. S. japonicus, N. crassa, A. nidulans, A. gossypii. 
information on orthologs
Possible tools that enable quick inverse search for pombe homolog. 
Searching orthologs
Orthology and human disease
Data for homologues/orhtologues in other organisms
More description for orthologues
homolog list
More information about ortholog functions
protein homology with other organisms
homology info in other organisms
a link to other organisms' (especially humans') gene products
links to other fungal protein databases.  eg.  homologue alignment across many yeasts (not just fission plus S. cerevisiae).  Fungal pathogens.
I'd appreciate more ways to identify homologs/link out to existing orthology databases/ integrate with phylogenetic analyses of fungi and other eukaryotes 
Relationship to higher eukaryotic proteins and complexes
Based on my memory, I used to like the older version of Pombase for looking at homologs/orthologs--I think this used to show more information than it does currently, and even some limited alignment (I htink it was pink in those days)
Relationship to higher eukaryotic proteins and complexes
orthology links with Wormbase so it is easier to identify pombe homolog of C. elegans gene and vice versa. 
new tools to check protein sequence structure and its alignments in other organisms
gene function linked with mammalian cells
druggable (homologs in human, fungi, etc) or not.
OTHEr FISSION YEAST
Compare fission yeast gene with gene from  other yeasts
link to other fission yeast species
Please inlcude the datasets of the other fission yeast species.
More comparative tools (synteny, multiple alignment, gene family trees, etc.) with the other Schizo genomes.  
other schizos/ alignments 3
Pre-computed protein sequence alignments or pre-computed BLAST results (like the discontinued NCBI BLink)

**Comment by ValWood** [comment]
We need to do a few things here:

- [ ]  1. Add links to resources  that provide trees and alignments
https://github.com/pombase/website/issues/1241

- [ ] 2. Make users aware that these links are in the external section. I plan to mail users to explain this, but maybe we should also include in the otholog section (discuss tomorrow)

- [ ] 3.  Label the ortholog section clearly "manually assigned orthologs"

- [ ] 4. Improve FAQs. FAQ link for
https://www.pombase.org/documentation/orthologs
to FAQ on orthologs in additional species. is broken

- [ ] 5. Add a web service for orthologs in the longer term

**Comment by mah11** [comment]
broken FAQ link fixed
standing down from this one; new or updated FAQ content to go in new tickets

**Comment by ValWood** [comment]
OK now only have the lower priority ticket for web services
