### ISSUE TITLE
Use rhea webservices to render reaction (on ontology term pages)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1243]
like:

![rhea](https://user-images.githubusercontent.com/7359272/56313104-ac231d00-6149-11e9-87c2-42d9c090935e.jpg)

( this in  uniprot pages)

webservices https://www.rhea-db.org/rest/1.0/

Locate Rhea->  GO mapping must be available somewhere.....

**Comment by ValWood** [comment]
> Would be useful to display the reactions enzymes catalyse.

one user request

**Comment by ValWood** [comment]
sort of related:

for enzymes it would be great to have a description of the reaction they catalyse and possibly the EC number
EC number of gene product of interest. I remember that EC number was easily found, but now we can't see it in pombase page. Or direct link to pathway map like KEGG's one.

We won't include EC  (unless we can think of a super easy way to do so) because these are no longer maintained, and have 'issues' . We can explain this when we announce Rhea.

**Comment by ValWood** [comment]
I mailed Rhea and the will elt us know when the web service is available. I forgot to update the ticket.

**Comment by ValWood** [comment]
Closing. I have this in the future list and Rhea will contact us when  webservice is available

**Comment by ValWood** [comment]
It must. be avaiable, FlyBase is doing it:
https://twitter.com/FlyBaseDotOrg/status/1669083598014619651

**Comment by kimrutherford** [comment]
Do we have RHEA IDs?  Or maybe we can get them via UniProt?

**Comment by kimrutherford** [comment]
Maybe FlyBase don't get their information direct from RHEA?  On the first page I looked at the diagram doesn't match:

https://flybase.org/reports/FBgn0002719.html#function
![image](https://github.com/pombase/website/assets/90474/2df50127-0693-43f4-9afb-c130340ded6e)

https://www.rhea-db.org/rhea/18253
![image](https://github.com/pombase/website/assets/90474/b2687347-5f23-4b60-8f08-d22999274b8e)

**Comment by kimrutherford** [comment]
> Maybe FlyBase don't get their information direct from RHEA?  On the first page I looked at the diagram doesn't match:

I reloaded both pages and then they matched, so false alarm.  Sorry.

> Do we have RHEA IDs? Or maybe we can get them via UniProt?

After a web search, they're in the OBO files: https://wiki.geneontology.org/RHEA_and_EC_mappings
You probably knew that.  :-)

I've checked Chado and the RHEA IDs are loaded for the GO terms already.  I had no idea.

> I remember that EC number was easily found, but now we can't see it in pombase page. 

The EC numbers for GO terms are loaded into Chado too.  I had no idea about that either.

> Would be useful to display the reactions enzymes catalyse.

I think that would be straightforward.  The JSON API that RHEA provide seems very simple and complete.  Good people!
For example for RHEA:18049, https://www.rhea-db.org/rhea/18049/json has all the information we need and each of the molecule images is available too, like: https://www.rhea-db.org/chebi/CHEBI:57805

**Comment by ValWood** [comment]
OK I just read your final comment. It seems we don't need any help, @kimrutherford you are on it.
v

**Comment by sjm41** [comment]
Visualizer package is here: https://www.npmjs.com/package/@swissprot/rhea-reaction-visualizer

Rhea IDs for specific genes are derived from our GO MF annotations to that gene, using the RHEA xref for that term in the GO file.  Pipeline is re-run each FB release to keep things up-to-date (with annotations and the GO itself).

I can put Kim in touch with the FB developer who implemented this if useful - just let me know.

**Comment by kimrutherford** [comment]
> I can put Kim in touch with the FB developer who implemented this if useful - just let me know.

Thanks, that's good to know.  And thanks for the pointer for the package.  That makes things simple for me.

**Comment by kimrutherford** [comment]
I have a prototype running on the dev server: http://dev.pombase.kmr.nz/term/GO:0003849
It's only term pages for now.

**Comment by ValWood** [comment]
Wow that was quick.

I don't know if we want to insert it in the GO function section of the gene pages, because it can be quite "big and disruptive"
We could have it available on the gene pages in 2 ways
i)  via a "show  reaction" link in the MF section. 
ii) We could also add a "reaction" icon in the summary widgets. It might get a bit crowded up there
later when we have pathways and protein viewers but we an re-evaluate

**Comment by ValWood** [comment]
Actually, if we have a show/hide reaction option it will be fine at the top of the MF section. People can decide for themselves whether they want to see it or not.

I

**Comment by kimrutherford** [comment]
It seems to work OK on the dev site so I updated the main site: https://pombase.org/term/GO:0003849

**Comment by ValWood** [comment]
This will be useful to @snezhkaoliferenko and team, so include on JaponicsDB too.

**Comment by ValWood** [comment]
https://pombase.org/term/GO:0090560
does not have a reaction,
But in AmiGO I see a Rhea xref:
https://amigo.geneontology.org/amigo/term/GO:0090560 (see the 'mappings' link)

**Comment by kimrutherford** [comment]
> This will be useful to @snezhkaoliferenko and team, so include on JaponicsDB too.

That's done now: https://www.japonicusdb.org/term/GO:0003849

**Comment by snezhkaoliferenko** [comment]
thank you!
________________________________

**Comment by kimrutherford** [comment]
> https://pombase.org/term/GO:0090560
> does not have a reaction,

Unfortunately we're only getting the RHEA IDs from term definitions at the moment.  So for example `GO:0003849` has the reaction on the term page: 

```
[Term]
id: GO:0003849
name: 3-deoxy-7-phosphoheptulonate synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-erythrose 4-phosphate + H2O + phosphoenolpyruvate = 7-phospho-2-dehydro-3-deoxy-D-arabino-heptonate + phosphate." [EC:2.5.1.54, RHEA:14717]
```

but `GO:0090560` doesn't:

```
[Term]
id: GO:0090560
name: 2-(3-amino-3-carboxypropyl)histidine synthase activity
namespace: molecular_function
def: "Catalysis of the reaction S-adenosyl-L-methionine + L-histidine-[translation elongation factor 2] = S-methyl-5-thioadenosine + 2-[(3S)-3-amino-3-carboxypropyl]-L-histidine-[translation elongation factor 2]." [GOC:pde, PMID:15485916]
```

I'll fix that on Monday.

**Comment by kimrutherford** [comment]
> https://pombase.org/term/GO:0090560
> does not have a reaction,

That's fixed now.  Also fixed in JaponicusDB.

Things to do:
  - mention the reaction diagrams in the docs, mostly to acknowledge RHEA and to direct users to RHEA for more detail
  - an announcement
  - news item

**Comment by snezhkaoliferenko** [comment]
thank you!
________________________________

**Comment by kimrutherford** [comment]
> -  mention the reaction diagrams in the docs, mostly to acknowledge RHEA and to direct users to RHEA for more detail
> -  news item

I've done those.  They'll be on the main site soon.

**Comment by snezhkaoliferenko** [comment]
By the way, wanted to tell you guys that I LOVE RHEA!!! It's wonderful!
________________________________

**Comment by ValWood** [comment]
It is! Such a huge amount of work by 

@amorgat
@kaxelsen
and the GO consortium members who did the Rhea to GO mapping
