### ISSUE TITLE
The ability to zoom in to the sequence in a more intuitive way

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1244]
We had a few *small* moans about the browser. Not the browsing specifically, but I  *think* most are referring to the ability to access the sequence surrounding the gene.

SURROUNDING SEQUENCE/ARTEMIS LINK

"I personally liked the layout of GeneDB better: it was so much easier to download sequences, find obvious neigbouring genes etc., which is lot more tricky from Pombase unless one goes into genome browser....is there any way of restoring this feature from GeneDB?
More user friendly genome browser. Eg. to be able to jump from map to sequence
It's better to have quick access to sequence data with annotation for the cloning.
neighboring region"

It is very difficult to do this (I tried today and it's really not possible to use the browser in this way).  Little things, like for instance when you zoom into the sequence you click on a residue and you can't centre on it, and there is no indication which residue it is.

How easy is it to add an Artemis Jave applet that we had before?

**Comment by kimrutherford** [comment]
> How easy is it to add an Artemis Jave applet that we had before?

It's a bit of a pain.  Let's discuss this sometime.

**Comment by ValWood** [comment]
We should discuss this on our next call.

**Comment by kimrutherford** [comment]
Now that I've looked into it, there's a problem: the latest versions of Java don't support applets.
https://stackoverflow.com/questions/45535112/why-were-applets-deprecated-in-jdk-9/45535138#45535138

Support was remove about 12 months ago.

So I think we need a new plan.

**Comment by ValWood** [comment]
Ah OK, then downlaoding artemis.

MAybe we can ask JBrowse for better ability to zoom in to nucleotides and amino acid sequence. It is difficult to explain what  the advantages of Artemis are to a bioinformatician though. They think you can see the sequence just fine....

**Comment by ValWood** [comment]
I will talk to Ian Holes about this when at the GO users meeting.

**Comment by kimrutherford** [comment]
> I will talk to Ian Holmes about this when at the GO users meeting.

Thanks.

**Comment by ValWood** [comment]
I didn't speak to Ian about this  because he only popped in for the session. I expected to catch him later in the week.

I will follow up on this at some point.
