### ISSUE TITLE
Allow FTP uploads for external users

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1246]
We need this to make the browser track hosting more streamlined

**Comment by ValWood** [comment]
Suggestions  for how to place files?

**Comment by kimrutherford** [comment]
I'll ask Jon at Babraham if we can enable uploading.

**Comment by kimrutherford** [comment]
I haven't asked Jon yet.  I wonder if we'd be better off recommending something like this when users need to send large files:
  https://www.swisstransfer.com/

It's a bit more obvious than uploading via FTP and it can be done via a browser.

**Comment by ValWood** [comment]
Makes sense. Should we do that then?

**Comment by ValWood** [comment]
I know we decided to recommend file transfer so this can probably close? but do we have instructions anywhere? @mah11

**Comment by mah11** [comment]
At present, we're telling people to email the helpdesk to submit files (bottom of the [documentation page](https://www.pombase.org/documentation/data-submission-form-for-HTP-sequence-linked-data)), and when they do, we include the file transfer link suggestions in our reply. That's working well enough that I don't feel an urgent need to change, but we can add to the documentation if you want.

Either way, I agree we don't need to ask people to faff around with ftp.

**Comment by ValWood** [comment]
OK so we can just close this.
