### ISSUE TITLE
announce survey results

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1248]
If I did things correctly then:
I uploaded the 2019 survey results (without freetext responses) to svn 
and added a blurb here https://www.pombase.org/documents

if this works then announce to community? We should also let them know that a number of action items have been issued on github?

**Comment by ValWood** [comment]
I don't think we need to announce the survey results specifically,  just host them, but I have some follow up e-mails to send out  (things people asked for that are already possible etc)

**Comment by ValWood** [comment]
Actually I agree, we could tell them how many actions spawned, but I didn't track this. I can estimate...

**Comment by Antonialock** [comment]
I think saying ‘a number of AIs’ is ok. Point is mainly so that they know that we are responding to requests, and that we are following the survey up.

**Comment by kimrutherford** [comment]
> If I did things correctly then:

All good!  The link and the file are now on the main site.

**Comment by ValWood** [comment]
I think we can close this.
