### ISSUE TITLE
Possible phenotype subsets (lists of lists)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1249]
From the survey

> A list of chemical and genetic perturbation sets would be most valuable
> Gene sets aside from GO terms, in GMT format. (we can think about other useful data subsets)

**Comment by ValWood** [comment]
Gene sets aside from GO terms, in GMT format.

(we can think about other useful data subsets)

**Comment by mah11** [comment]
What is GMT format?

**Comment by ValWood** [comment]
I had to Google it. 
http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#GMT:_Gene_Matrix_Transposed_file_format_.28.2A.gmt.29
I don't think we will provide this format, but  I wanted to record requests for "lists of lists". We do this anyway but good to explore what else people need.

For instance, FlyBase do "pathway lists" (Helens talk) which are the same as process lists, but include the MF annotations. I was hoping to deal with that generically this way:
http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#GMT:_Gene_Matrix_Transposed_file_format_.28.2A.gmt.29

**Comment by ValWood** [comment]
See
https://github.com/pombase/website/issues/1403
