### ISSUE TITLE
modifications count odd

### ISSUE THREAD

**Issue by ValWood** [pombase/website#125]
It seems to be not using the ontology?
see for eg sti1 in pombase 1&2

**Comment by kimrutherford** [comment]
> It seems to be not using the ontology?

We currently aren't running PSI-MOD through Owltools to generate all the parents.  We've never needed it before for the Chado load.  I'll add it.

**Comment by kimrutherford** [comment]
I've tested that Owltools works with PSI-MOD and I've added PSI-MOD to the Owltools command line in the load script.  So hopefully the modification counts will be fixed tomorrow morning.

**Comment by kimrutherford** [comment]
Fixed.
