### ISSUE TITLE
Do something with reviews (and methods) papers

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1251]
>It will be nice to have reviews also on the literature section

**Comment by kimrutherford** [comment]
We have pages for reviews and methods papers but they're not very exciting:
  https://www.pombase.org/reference/PMID:20559026

**Comment by ValWood** [comment]
Maybe we can  make the text:

This publication has no annotations in PomBase because ~the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types~
it is a  Review/Method paper

thoughts @Antonialock @mah11 @kimrutherford

**Comment by mah11** [comment]
The same thing was suggested almost two years ago, only without spurious capitalisation:
https://github.com/pombase/website/issues/627#issuecomment-346013483

**Comment by kimrutherford** [comment]
> Maybe we can make the text:

That's done now.

**Comment by ValWood** [comment]
checking a review

https://www.pombase.org/reference/PMID:31345733

It also has
Datasets from this publication are available in the PomBase JBrowse genome browser.   View...

but htis is not true

**Comment by ValWood** [comment]
same for a methods paper
https://www.pombase.org/reference/PMID:31454903

**Comment by ValWood** [comment]
Ah -in fact all publications have this regardless of type.

**Comment by ValWood** [comment]
Once this is fixed, this can be closed.

Should we announce that these are loaded? and any future plans. 

We can't really do much with these pages at present. Only locate them by PMID, but you need to know the Pubmed ID.  Do we have any future plans for enhanced searching  via the faceted search documented?

**Comment by kimrutherford** [comment]
> Once this is fixed, this can be closed.

Sorry about that.  Fixed now.

> Only locate them by PMID, but you need to know the Pubmed ID.

You can also put the publication title in the search box.

> Do we have any future plans for enhanced searching via the faceted search documented?

When we have a better search feature we could probably search the abstracts too.

**Comment by ValWood** [comment]
>You can also put the publication title in the search box.

Distributing meiotic crossovers for optimal fertility and evolution

did not  work for me?

**Comment by kimrutherford** [comment]
> did not work for me?

Did anything show up?

I get:

![search-box-1](https://user-images.githubusercontent.com/90474/64226999-db3dfd80-cf35-11e9-88b4-f7214b003b7e.png)

**Comment by ValWood** [comment]
oh yes! I was thrown by the "matching terms" as top hits since there is no annotation and the terms looked a bit random ;) I didn't look down the list...

**Comment by kimrutherford** [comment]
> I didn't look down the list...

Yep that's a problem, it's not obvious.  It will be better when you can press return and go to a full search results page.  We'll be able to format the matches into separate sections on the page.

**Comment by ValWood** [comment]
OK we can announce the existence and close.

Whay should we say @Antonialock  @mah11 ?

**Comment by ValWood** [comment]
Methods and review publications are now loaded into PomBase. 
Currently, you can search by title or PMID using the simple search box. In the future, we will add more features.

?

**Comment by ValWood** [comment]
..or not bother announcing? It's probably good for people to know they are there, even if the use is limited... (it will allow for reciprocal linking from PubMed I guess, another plus)?

**Comment by ValWood** [comment]
Closing, then it will join the list of closed with an announce label...

**Comment by Antonialock** [comment]
announced
