### ISSUE TITLE
configure JBrowse "sequence ' feature by default.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1253]
I have no idea why I suggested otherwise! It's really difficult to  locate too!

**Comment by kimrutherford** [comment]
Sorry I mis-remembered.  The sequence is on by default but if you've hidden the track in the past it will stay that way until you toggle it on again.  You can test that it's on by default by going to pombase.org in a private or incognito browser window.

**Comment by ValWood** [comment]
That's weird. It is off now even though I toggled it on last time I visited. It's also not visible using an Incognito window....???

**Comment by kimrutherford** [comment]
It looks look the view is different if you come from a gene place versus the link on the front page.  For the inline JBrowse on the gene pages the sequence track is disabled so if you click on "Full-screen view" from there the sequence track is disabled.  I'm not sure how to fix that.  I'll investigate.

**Comment by kimrutherford** [comment]
> so if you click on "Full-screen view" from there the sequence track is disabled.

As a quick fix, I've added the sequence track to the inline view on the gene pages.  I added it at the bottom so that it doesn't push the other tracks down and possible out of view.  So now the sequence track is on by default if you click on "Full-screen view".

**Comment by ValWood** [comment]
That helps. Apologies if that is how it used to be (I think Antonia said at one point I asked for the sequence not to show by default, but I have no idea why, that would be crazy!)

**Comment by kimrutherford** [comment]
Can we close this issue?
