### ISSUE TITLE
Customizable fasta download bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1254]
Omar reported that the customizable fasta download is broken for Firefox & safari

(works for me on chrome)

**Comment by mah11** [comment]
Did Omar provide any additional details (e.g. what he tried, what did or didn't happen)? We're going to need more info, because I've just had it work a treat in Safari on a Mac and in Firefox on two platforms.

**Comment by kimrutherford** [comment]
He sent a gene list.  The bug is that the list included an RNA gene and he was doing a protein export.  The code failed on that gene.  I've fixed the problem and the site will be re-released soon.

**Comment by kimrutherford** [comment]
Fixed by 9f62882b0b7ca1cb18a
