### ISSUE TITLE
new page type. All alleles of this gene

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1255]
Discussed on group call that such a page would be  a useful addition.

**Comment by Antonialock** [comment]
can these not be summarised in the phenotype section?

**Comment by ValWood** [comment]
this is basically going to be a long list, so I think a separate page might be better. 

Lets decide this when kim is in uk

**Comment by kimrutherford** [comment]
Is this related: #1325?

**Comment by ValWood** [comment]
This is a bit different. but related.
I guess it was just so people could look easily through the list of alleles.
At the moment you can control F to search for one. But  you might not know the name. I can see it would be useful to have a list of all the alleles to browse:

cdc2-r4 (D90N aa)
cdc2-Y15F (Y15F aa)
cdc2-22 (unknown)
cdc2-D152N (D152N aa)
cdc2-E51D (E51D aa)
cdc2-N22 (E42K aa)

etc

grouped by 'type' with some ordering
There are 100's for some genes now (it feels like, I might be exaggerating but lots for cdc2!)

**Comment by kimrutherford** [comment]
Would another filter on the gene page help?  We could filter by allele type.

**Comment by ValWood** [comment]
I think it is less about the type (this would just be a convenient way to group).
It's more about being able to scan the range of alleles quickly.

I would say this was low priority though (lower than actual allele pages).

We could ask if people would find this a useful feature before we go ahead and do it.

**Comment by ValWood** [comment]
I can't even remember why/when we decided this would be useful, but I am sure that it could be.

"I want to see ALL of the alleles of cdc2"
I can imagine this question. 
At present it is difficut to scan because even if you  *could * look down the page there is so much redundancy.

**Comment by ValWood** [comment]
I asked Jurg and Jacky if this would be useful

**Comment by ValWood** [comment]
I asked Jurg and Jacky if this would be useful

**Comment by mah11** [comment]
*I* would find this useful, but not a super-high priority.

**Comment by ValWood** [comment]
Yah I just think it would be nice for scanning all the alleles. I would use it.

Jurg and Jacky didn't reply though...

I agree, not super high priority, but if it's easier to do with allele pages....

**Comment by ValWood** [comment]
JB
We briefly discussed this in lab meeting, and the consensus is that it would be a useful addition.
The wild strains would of course have many new gene alleles but these may be more difficult to implement.

(I'm not sure that the second part is strictly related)

**Comment by kimrutherford** [comment]
> this is basically going to be a long list, so I think a separate page might be better.

It would be a dull page though wouldn't it?  Would it be just a list of allele names and descriptions?

**Comment by ValWood** [comment]
It will not make exciting reading true, but sometimes dull is useful...

**Comment by kimrutherford** [comment]
> Would it be just a list of allele names and descriptions?

After discussion, for each allele we'll need:
 - name
 - description
 - allele type
 - possibly a list of associated genotypes

**Comment by mah11** [comment]
also want any synonyms & comments (see https://github.com/pombase/pombase-chado/issues/752 & https://github.com/pombase/pombase-chado/issues/753 as well as synonyms entered in Canto)

**Comment by ValWood** [comment]
It seems that we decided what to do here so I am removing the "discuss" label.
However, I think we wanted
Is this related: #1325 to happen first, so I'll put this at "low priority' for now.

**Comment by ValWood** [comment]
This also might be useful to report in   the publication if could be done alongside "allele pages" .It's kind of 'on topic' for improving accessibility  to huge amounts of phenotype data.

**Comment by kimrutherford** [comment]
> this is basically going to be a long list, so I think a separate page might be better.

I'm still not sure about this.  We already have some long lists on the gene pages.  And a table of alleles won't be that long will it?  It should be a lot shorter than the phenotype annotation table for example.

If the list was its own page we'd need to link to it from the gene page.  Where would the link be in the page?  Would it get lost on a long gene page?

**Comment by ValWood** [comment]
Maybe a link at the top of the phenotype section, tucked away to the right

[Single allele phenotype]                                                      
-----------------------------------------------------------------[ Link : All alleles of this gene]
[Gene Deletion Viability: Inviable]

I'm not wedded to having this, but for a gene like cdc2 with masses of allele an alphabetical list could be really useful (linking to allele pages)

**Comment by mah11** [comment]
To me, the fact that it'll be a long and dull list for some genes is actually part of the case _for_ hiving it off onto its own page. But a list on the gene page might also do, if it can toggle between expanded and collapsed, and defaults to collapsed.

**Comment by ValWood** [comment]
I would prefer the list to be on it's own page, I think (in case I wasn't clear).

**Comment by kimrutherford** [comment]
I've had a first attempt at this: https://www.pombase.org/gene_alleles/SPBC11B10.09

There are no links to these pages yet.  You'll need to edit the URL to try other genes.

**Comment by mah11** [comment]
This looks good. A few follow-up thoughts:

Can you make "delta" resolve to Δ in the Name column?

I think it's OK that it sorts by Type, but it would be cool if you can add the sort-by-column controls. I bet people would like to be able to sort on at least the Name column; not sure anyone would want to sort by Description but I dunno.

I like that you can see genotypes that use the allele right on the page, although I think the behavior will need to be documented thoroughly (otherwise it could be unexpected and maybe even confusing that the first click shows more on the allele page, but the next click on any genotype description goes to a different page).

On a related note, is it feasible to have the display of genotypes toggle on and off?

**Comment by ValWood** [comment]
Looks good. As an asife

I wonder if these are really 2 copies of cdc2?
cdc2-33 (A177T aa) cdc2-L55M (aa)
cdc2-33 (A177T aa) cdc2-T167E (aa)
cdc2-33 (A177T aa) cdc2-E179R (aa)
cdc2-33 (A177T aa) cdc2-T167Y (aa)
and a few more
I will open a curation tracker ticket to check that.

<br class="Apple-interchange-newline">

**Comment by kimrutherford** [comment]
> Can you make "delta" resolve to Δ in the Name column?

Yep, I'll do that.

> it would be cool if you can add the sort-by-column controls

I'll do that too.

**Comment by kimrutherford** [comment]
> > Can you make "delta" resolve to Δ in the Name column?
> 
> Yep, I'll do that.
> 
> > it would be cool if you can add the sort-by-column controls
> 
> I'll do that too.

All done for the morning.

**Comment by kimrutherford** [comment]
> On a related note, is it feasible to have the display of genotypes toggle on and off?

So have a button that hides the "Show genotypes.." link?

**Comment by mah11** [comment]
>> On a related note, is it feasible to have the display of genotypes toggle on and off?
> 
> So have a button that hides the "Show genotypes.." link?

Actually, I was thinking more of having "Show genotypes" change to "Hide genotypes" after you click "Show" to, well, show them. Sorry if that wasn't clear.

**Comment by kimrutherford** [comment]
> Actually, I was thinking more of having "Show genotypes" change to "Hide genotypes" after you click "Show"

There's a button to hide all the genotypes.  Will that do?

**Comment by mah11** [comment]
>> having "Show genotypes" change to "Hide genotypes" after you click "Show"
> 
> There's a button to hide all the genotypes. Will that do?

I'll have a think. It does do the job of hiding any genotypes I've shown, but I'm not quite sure it meets the need behing my request. After I'd clicked to "open" the view of genotypes for one allele, my instinct was to look for a toggle near where I'd just clicked, so I could hide those genotypes. Also, the show all/hide all controls are up at the top, and therefore not visible if you scroll down a long page.

**Comment by ValWood** [comment]
> There's a button to hide all the genotypes. Will that do?

- [ ] I would also prefer to be able to toggle off the genotypes I just looked at. 
Particularly for long lists  (like the first example on the cdc2 page). The toggle all will not be so useful as I suspect users will open these one at a time (i.e for the specific alleles of interest). The page becomes unwieldy when all are open. I  also failed to see the hide all genotypes button (maybe because it isn't close to the 'show genotypes' options.
- [ ] could the default view put deletion, then WT to the top?
- [ ] In the genotype lists could the 'single allele genotype' be at the top of the list, followed by 'multi', then 'diploids'?
- [ ] include a synonyms column

**Comment by ValWood** [comment]
- [ ] Midori also mention comments above. These would be useful too. Mainly things like  "temperature-sensitive" " kinase-dead" "loss of function" etc so would be useful for people browsing this list. Hopefully there aren't and very long descriptions?
- [ ] Decide how to link from the gene pages

**Comment by kimrutherford** [comment]
Coming back to this after a few months, I have a suggestion.

I don't like the way the page works at the moment.  The genotype lists are long and ugly, especially when more than one is shown.  How about instead of the "Show genotypes.." link, could we link to the allele pages once they're done?  We could have the list of genotypes at the top of the allele page.

**Comment by ValWood** [comment]
can discuss. I can't think;)

**Comment by kimrutherford** [comment]
This issue is labelled with "high priority", "next" and "low priority".  Which labels should we remove?

**Comment by ValWood** [comment]
We can discuss on Thursday.
Low priroty if it is complicated
high priority if it is quick :)

**Comment by kimrutherford** [comment]
> We can discuss on Thursday.
> Low priroty if it is complicated
> high priority if it is quick :)

I think it's probably quick but it depends on what's needed.  :-)

Here's an example of how the pages currently look, for discussion:
https://www.pombase.org/gene_alleles/SPAC1782.09c

> How about instead of the "Show genotypes.." link, could we link to the allele pages once they're done? 

I still think that's a good idea.  I've (possibly temporarily) changed the allele name to be a link to the test allele pages (see https://github.com/pombase/website/issues/1294#issuecomment-1170757811) for discussion.

**Comment by kimrutherford** [comment]
> Decide how to link from the gene pages

**Comment by kimrutherford** [comment]
> Decide how to link from the gene pages

I've added a temporary link on the dev site gene pages, mostly so it's easier for me to get to the alleles pages while testing.  It's at the top of the phenotype annotation tables for now because I wasn't sure where else to put it.

![image](https://user-images.githubusercontent.com/90474/183840349-0d82e4db-47a9-4651-ab3f-9fd37711b4c2.png)

**Comment by ValWood** [comment]
II think that's a good place for now. Unless there are better suggestions @manulera

**Comment by ValWood** [comment]
Note that most pages will look better than this.
http://dev.pombase.kmr.nz/gene_alleles/SPBC1347.10
because they will have more concise descriptions.

**Comment by ValWood** [comment]
Maybe we will need to line wrap the descriptions at around 50 chars?. How many very long .ones do we have?
(note the ones above will be shorter tomorrow, I don't think very many are this long)

the genotypes look a bit confusing when displayed:
It isn't really very clear where one ends and the next one begins:

<img width="913" alt="Screenshot 2022-08-17 at 19 32 50" src="https://user-images.githubusercontent.com/7359272/185221823-1a4b2a8d-8ea3-4486-ace8-249f5089adaf.png">

**Comment by kimrutherford** [comment]
> The genotypes look a bit confusing when displayed:

I think we should consider removing the expression and genotype columns from these pages and linking to the allele pages instead.  We show the genotypes on the allele pages in a better format.

**Comment by ValWood** [comment]
> I think we should consider removing the expression and genotype columns from these pages and linking to the allele pages instead. We show the genotypes on the allele pages in a better format.

yep,

**Comment by manulera** [comment]
I agree with Kim, that the genotypes should not be displayed in this page. My only doubt is about the expression level for wild type products.

Say that I am a new comer and I would like to see the phenotypes of overexpression or shutdown of a gene. It may not be obvious to me that I will find them in wild_type. So maybe it's good to say something like "wild type knockdown or overexpression" instead of "wild_type", since anyway it is not possible to have a wild_type allele without an expression qualifier.

**Comment by ValWood** [comment]
I think we are agreed not to display genotypes of each allele.

We can probably make this page available after  the link is added.

**Comment by ValWood** [comment]
We should include synonyms on this page though, I think...

**Comment by kimrutherford** [comment]
> We should include synonyms on this page though, I think...

No problem.  Is an extra column OK?  It's mostly going to be empty though.

**Comment by ValWood** [comment]
Maybe we shouldn't include them here. I think we discussed this previously and decided not to.

I had a use case - I went to this page to see if I could find which allele a synonym belonged to.
If the simple search on a. synonym leads you to the allele page that is not necessary.

**Comment by kimrutherford** [comment]
I've found a bug.  There are no alleles on this page: http://dev.pombase.kmr.nz/gene_alleles/SPCC736.12c

**Comment by kimrutherford** [comment]
> I've found a bug. There are no alleles on this page

Fixed for Sunday morning.

**Comment by kimrutherford** [comment]
I've collected all the "to do" items here.  Some are done and some we decided not to implement.

- [ ] How about instead of the "Show genotypes.." link, could we link to the allele pages once they're done? We could have the list of genotypes at the top of the allele page.

- [ ] This also might be useful to report in the publication if could be done alongside "allele pages"

- [ ] I think we should consider removing the expression and genotype columns from these pages and linking to the allele pages instead. We show the genotypes on the allele pages in a better format.

     - ["I think we are agreed not to display genotypes of each allele."](https://github.com/pombase/website/issues/1255#issuecomment-1225857067)

- [ ] We should include synonyms on this page
     - ["Maybe we shouldn't include them here. I think we discussed this previously and decided not to."](https://github.com/pombase/website/issues/1255#issuecomment-1231222037)

- [ ] could the default view put deletion, then WT to the top?

- [ ] I would also prefer to be able to toggle off the genotypes I just looked at.

- [ ] In the genotype lists could the 'single allele genotype' be at the top of the list, followed by 'multi', then 'diploids'?

- [ ] allele comments

- [ ] Maybe we will need to line wrap the descriptions at around 50 chars?. How many very long .ones do we have?
(note the ones above will be shorter tomorrow, I don't think very many are this long)

-  [ ] The genotypes look a bit confusing when displayed: It isn't really very clear where one ends and the next one begins: See: https://github.com/pombase/website/issues/1255#issuecomment-1218386677

**Comment by ValWood** [comment]
This could maybe go ahead to get it off the list. I think its quite a useful feature, and it was pretty much completed?

**Comment by ValWood** [comment]
Are there any outstanding questions?

**Comment by kimrutherford** [comment]
I think we can go ahead but it won't be so useful without links to the alleles.  It will be more useful once we we allele pages: pombase/website#1294

**Comment by ValWood** [comment]
We can wait until allele pages are available, but I  it could be useful just to see all of the alleles of a gene.

**Comment by kimrutherford** [comment]
I've added a link to the "alleles of this gene" page from the gene page and disabled the links to the allele pages (on the main site):

![image](https://github.com/pombase/website/assets/90474/6f2b359b-e276-4ec7-b9f9-d68beda4df60)

![image](https://github.com/pombase/website/assets/90474/45283666-e797-48ba-ace9-622b60d058b0)

**Comment by ValWood** [comment]
Oh this is going to be soooo useful for everyone!

**Comment by ValWood** [comment]
One sma;ll. thing I just notices. When you list the genotypes,  can you make the allele itself be at the top of the list?

**Comment by kimrutherford** [comment]
> When you list the genotypes, can you make the allele itself be at the top of the list?

Sorry, I don't follow.  Do you want to show the allele in the list of genotypes?

**Comment by ValWood** [comment]
In the example above, it woud be better if sup35(G)(Nt) genotype was above the mutigene genotypes (I was just slightly confused by it), and  for alleles used in a lot of multi-alleles I think it would be better.

**Comment by kimrutherford** [comment]
So put the single allele genotypes first?

**Comment by ValWood** [comment]
I think so, or they may get lost in the long lists, especially for some cdc2 alleles

**Comment by kimrutherford** [comment]
I've changed the order so genotypes with fewer loci come first.  Also haploids come before diploids.

**Comment by kimrutherford** [comment]
The outstanding tasks for this issue:
  - How about instead of the "Show genotypes.." link, could we link to the allele pages once they're done? We could have the list of genotypes at the top of the allele page. 
     - I had forgotten about this plan so I didn't need to put the genotypes in order ("I've changed the order so genotypes with fewer loci come first. Also haploids come before diploids.")
     - need to finalise the allele pages before this is implemented (then it's a 5 minute job)
  - move deletion and WT alleles out of table to top of page
  - line wrap the descriptions at around 50 chars
     - "How many very long ones do we have?"
       - there are 157 descriptions that are 50 characters or more
       - and 24 descriptions longer than 100

**Comment by kimrutherford** [comment]
> move deletion and WT alleles out of table to top of page

I've implemented that [on a branch](https://github.com/pombase/website/tree/issue-1255-gene-alleles-page-fixes) which I'll merge once we have allele pages.

It currently looks like this:

![image](https://github.com/pombase/website/assets/90474/d933b49e-c8be-4ed7-8c0e-4d3760da69bb)

**Comment by kimrutherford** [comment]
I've added the "View genotypes..." links back which got lost in the changes:

![image](https://github.com/pombase/website/assets/90474/093a4ee5-c668-4d59-bffd-eff85644f9c9)

**Comment by kimrutherford** [comment]
> How about instead of the "Show genotypes.." link, could we link to the allele pages once they're done?
> add a title / tooltip

That's all done [on the branch](https://github.com/pombase/website/tree/issue-1255-gene-alleles-page-fixes).

>

**Comment by kimrutherford** [comment]
>  line wrap the descriptions at around 50 chars 

I've changed the alleles table so that the name and descriptions wrap.  Maybe good enough for now.

![image](https://github.com/pombase/website/assets/90474/9faeab8f-a9d8-4abc-8987-04315b161378)

**Comment by kimrutherford** [comment]
This issue is long and I think it's more or less done.  Or I'll close it and we can open new issues for changes.
