### ISSUE TITLE
update links out to STRING

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1256]
From Damian, STRING developer:

I have noticed that PomBase uses outdated links:
http://string-db.org/newstring_cgi/show_network_section.pl?identifier=P50537

Better way to link would be to link like this:
https://string-db.org/cgi/network.pl?species=4896&identifier=P50537

As for the identifiers, you can keep using UniProt or switch to yours.

**Comment by kimrutherford** [comment]
The links are up to date on the main site now.
