### ISSUE TITLE
motif search documentation

### ISSUE THREAD

**Issue by mah11** [pombase/website#1257]
It's not too far off self-documenting, but:
- add motif search doc page linked to main documentation page
- update link in FAQs
  - Can I use BLAST to find S. pombe sequences similar to my query sequence?
  - Can I use BLAST to search for short sequences?

... maybe wait for #1225 outcome?

**Comment by ValWood** [comment]
... maybe wait for #1225 outcome?

yeah good plan...

**Comment by Antonialock** [comment]
maybe a glossary of symbols if it exists? Apparently they come in slightly different flavours for logical defs(?)

I'm pretty sure someone in the workshop tried to use curly brackets to mean something which worked in fungiDB but not PomBase.

**Comment by ValWood** [comment]
We use the standard symbols, so I think it's fine. It's clear what the syntax  for our search should be from the examples. Curly brackets are used for number ranges.

**Comment by ValWood** [comment]
...which is broken, so that would be a bug, needs reporting?

**Comment by ValWood** [comment]
> maybe a glossary of symbols if it exists? Apparently they come in slightly different flavours for logical defs(?)

I don't fully understand this? What is needed that isn't on the current front page?

**Comment by kimrutherford** [comment]
> ...which is broken, so that would be a bug, needs reporting?

What's broken?

**Comment by kimrutherford** [comment]
>>  ...which is broken, so that would be a bug, needs reporting?
> What's broken?

Ah, got it.  Curly brackets don't seem to work.  I'll fix that.

**Comment by kimrutherford** [comment]
Thanks for the documentation.  I've added a link to it from the motif search page.
