### ISSUE TITLE
phenotypes missing (or incorrect), not sure....

### ISSUE THREAD

**Issue by ValWood** [pombase/website#126]
Phenotypes for klp5 are very different in pombase 1 & 2

compare:

pombase 2

![klp5](https://cloud.githubusercontent.com/assets/7359272/21752970/205a8616-d5da-11e6-9116-e7cf311b2f1e.jpg)

pombase 1

![klp5-2](https://cloud.githubusercontent.com/assets/7359272/21752971/233295f4-d5da-11e6-9a7a-d923352ca325.jpg)

and more

**Comment by ValWood** [comment]
It looks like it is displaying  info for a different gene. I can't figure it out ;)

**Comment by kimrutherford** [comment]
I think I've fixed this.  The phenotype annotation wasn't updating when you changed gene.  I introduced the bug when I split the phenotypes into Cell and Population.

As usual, shift-reload will probably be required.
