### ISSUE TITLE
FAQ update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1263]
https://www.pombase.org/faq/can-i-view-my-protein-interest-multiple-alignment-related-proteins-other-species

Add Ensembl Compara, as people need this for japonicus and Octosporus

**Comment by mah11** [comment]
What is the task? That FAQ already mentions Compara.

**Comment by ValWood** [comment]
I see there is a full FAQ for japonicus

https://www.pombase.org/faq/can-i-view-my-protein-interest-multiple-alignment-related-proteins-other-species

Might be good to mention Panther here,  and say that panther generally has the highest coverage (detects more distant orthologs), than most other predictionmethods.

**Comment by mah11** [comment]
> I see there is a full FAQ for japonicus

Which FAQ do you mean? The link is for the same FAQ as in the original summary, which isn't specific to japonicus.

> Might be good to mention Panther here

Where's "here"?

It would make the most sense to add PANTHER to the linked FAQ on orthologs in species other than human and S.c., i.e.

https://www.pombase.org/faq/how-can-i-find-s.-pombe-orthologs-species-other-than-human-and-s.-cerevisiae

and I would find it very helpful to have some specific suggestions for what to say about it, e.g. which part(s) of the panther site to link to, and whether to include any instructions a la compara.

**Comment by ValWood** [comment]
Can I view my protein of interest in a multiple alignment with related proteins in other species?
PomBase does not have its own alignment viewer. DIOPT and Compara, *****ADD and Panther****** ~two~ ***three*** of the tools we recommend for finding orthologs, have alignment display options. See the FAQ on orthologs in other species for more information.
