### ISSUE TITLE
replicate external links for orthology resources

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1265]
replicate external links for orthology resources in the  ortholog section

https://github.com/pombase/website/issues/1241

**Comment by kimrutherford** [comment]
What should the titles be on the links and where should they be?  Underneath?

-----------

Resource: Ensembl Fungal Compara
Description Alignments, gene trees, orthologs, families
Link format: http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/Compara?db=core;g=SPAC227.07c;r=I:507522-509960;t=SPAC227.07c.1

Resource: Ensembl Pan taxonomic Compara
Description: Gene tree, orthologs
Link format: http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/PanCompara?db=core;g=SPAC227.07c;r=I:507522-509960;t=SPAC227.07c.1

Resource: Panther Orthologs, Gene trees, Alignments
Link Format: http://www.pantherdb.org/genes/gene.do?acc=SCHPO%7CPomBase%3DSPCC18B5.04%7CUniProtKB%3DQ9USL7

**Comment by ValWood** [comment]
Sorry, missed from
https://github.com/pombase/website/issues/1242

under 2 headers:

Manually assigned orthologs

Predicted orthologs

**Comment by kimrutherford** [comment]
So have "Manually assigned orthologs" as a header at the top of the current ortholog table and then have a "Predicted orthologs" below the current table?

**Comment by ValWood** [comment]
Or just have a single table and have these as sub headers
(like Population phenotype, in phenotypes)

**Comment by kimrutherford** [comment]
I've added those links.  Let me know if you'd like any changes.

![orth-ext-refs-1](https://user-images.githubusercontent.com/90474/56894769-f3f75c00-6ada-11e9-9e62-bfc335ad1af9.png)

**Comment by ValWood** [comment]
A small one tweak. Could you also include the existing ortholog resources:

Orthologs | DIOPT | SPCC18B5.03 | DRSC Integrative Ortholog Prediction Tool
-- | -- | -- | --
Orthologs | HCOP | SPCC18B5.03 | Integrated human orthologs

**Comment by ValWood** [comment]
Also, 

1. Could we make this links available in the ortholog section for genes with no orthologs listed? (I.e every gene will now have an ortholog section and the set of prediction links). This will enable people to access  orthologs when no fungal or human ortholog reported.....

2. Panther links are broken. I'm not sure why, I will look into this...

**Comment by ValWood** [comment]
links should be
http://www.pantherdb.org/genes/gene.do?acc=SCHPO%7CPomBase%3DSPCC18B5.03%7CUniProtKB%3DP07527

we have
http://www.pantherdb.org/genes/gene.do?acc=SCHPO|PomBase%3DSPCC18B5.04|UniProtKB%3DP07527

**Comment by kimrutherford** [comment]
> Could you also include the existing ortholog resources:

What do you mean by existing resources?  Do you mean include the other two ortholog external references?

**Comment by ValWood** [comment]
> Do you mean include the other two ortholog external references?

yep. all ortholog resources should be int eh ortholog section, I think

**Comment by kimrutherford** [comment]
> links should be

Thanks for checking that.  The problem was that the Panther URLs need a UniProt ID and a PomBase ID.  I didn't notice the PomBase ID in the URL when I configured it so all our links to Panther had the same gene ID, "SPCC18B5.04" in the link.  I've fixed that now.

> yep. all ortholog resources should be int eh ortholog section, I think

OK, done.

> Could we make this links available in the ortholog section for genes with no orthologs listed?

Done.

**Comment by ValWood** [comment]
announced
