### ISSUE TITLE
research spotlight  PMID: 30528393 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1266]
![trna](https://user-images.githubusercontent.com/7359272/56581339-a6578c80-65cc-11e9-9bce-e43f9950d8eb.jpg)

Fission yeast contains separate CC- and A-adding tRNA nucleotidyltransferases

Biochem Biophys Res Commun

**Comment by kimrutherford** [comment]
I've added the configuration for this Spotlight so it should be visible in the morning.
