### ISSUE TITLE
HCOP linking in changed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1267]
(Note the old links work, but via these links the "submit" button is broken
Need updating as here:

--from HCOP--

You can now save HCOP result URLs to create links. Please see https://www.genenames.org/help/hcop/#!/#tocAnchor-1-4 for details.

This is the replacement URL for the example that you sent:

https://www.genenames.org/tools/hcop/#!/?q=SPCC18B5.03&qtype=pombase&qtax_id=284812&ttax_id=9606&submit=true

**Comment by ValWood** [comment]
I put this as next because it seems quick.

With the old links the submit button at HGNC doesn't work

**Comment by kimrutherford** [comment]
The HCOP links are fixed now.
