### ISSUE TITLE
make ".1" transcript and .pep IDs searchable from simple search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1268]
Confused Ramsay as he could not locate the .1 IDs in the simple search.
I thought we could search on these at one point?

**Comment by kimrutherford** [comment]
Yep, that makes sense.  Ensembl messes with us again.  :-(

> I thought we could search on these at one point?

I don't think so.  The URLs have have :pep and .1 at the end though.

**Comment by kimrutherford** [comment]
I guess the gene ID upload form should cope with these too?

**Comment by Antonialock** [comment]
Yeah I guess that wouldn't hurt, at least they are (very) unique

**Comment by ValWood** [comment]
I think for now we should just make them avaiable for searching.


LAter we will be implementing .1 .2 and .3 notation to describe isoforms/alternative transcripts, although we don't have many. We want to avoid people using these IDs more generally   when they mean genes not transcripts.

So until we have annotated examples I think we should not allow in the gene list  upload

**Comment by kimrutherford** [comment]
The search box is now configured to ignore ".1" and ".1:pep" at the end of systematic IDs.
