### ISSUE TITLE
new gene for "new genes" page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#127]
/systematic_id="SPNCRNA.1688"
/product="intergenic RNA"
/db_xref="PMID:25428589"
/primary_name="nc-tgp1"
will appear in the next update.
/synonym=INT_0_2957

**Comment by ValWood** [comment]
Did this slip through or is website not updating?

**Comment by kimrutherford** [comment]
That's odd.  The primary name, synonym and product aren't on the gene page in pombase 2.  I'll look into that.

**Comment by kimrutherford** [comment]
There are two features with that systematic ID:

    FT   misc_RNA        complement(352335..354234)
    FT                   /systematic_id="SPNCRNA.1688"
    FT                   /product="intergenic RNA"
    FT                   /db_xref="PMID:25428589"
    FT                   /primary_name="nc-tgp1"
    FT                   /synonym="INT_0_2957"

    FT   ncRNA           complement(4367088..4368303)
    FT                   /systematic_id="SPNCRNA.1688"
    FT                   /product="intergenic RNA (predicted)"
    FT                   /db_xref="PMID:21511999"

**Comment by ValWood** [comment]
bummer. will fix....that might fail ensembl checks....

**Comment by ValWood** [comment]
or did it just not load? in which case Ensembl will be fine...

In my original comment I was referring to the static pages, I didn't check Pombase

**Comment by kimrutherford** [comment]
> or did it just not load?

Yep, it didn't get through into Chado.

**Comment by mah11** [comment]
I will update the static "new genes" page when the v62 update is about to go live - if I do it before then, the static page will be inconsistent with the rest of pombase1 for a while.

**Comment by ValWood** [comment]
fixed the new one
FT   misc_RNA        complement(352335..354234)
FT                   /systematic_id="SPNCRNA.1688"
FT                   /product="intergenic RNA"
FT                   /db_xref="PMID:25428589"
FT                   /primary_name="nc-tgp1"
FT                   /synonym="INT_0_2957"

to
SPNCRNA.1698

**Comment by mah11** [comment]
done on dev
