### ISSUE TITLE
uniprot accession or ID

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1270]
I'm not sure we labelled this correctly.

 Q10137 is and accession and *_SCHPO is an identifier

However, this appears to be contradicted by 
https://www.uniprot.org/uploadlists/

and there is no information in an entry about which type of label is which. Anyone know?

**Comment by kimrutherford** [comment]
Yep, I think you're right: https://www.uniprot.org/help/accession_numbers

But lots of people wouldn't know what an "accession number" is.  It's especially confusion as they aren't actually numbers.

I think I'm in favour of calling them "UniProt IDs" in the interface even though it's wrong.

**Comment by mah11** [comment]
> Q10137 is and accession and *_SCHPO is an identifier

This is correct, as people at UniProt have been telling me for *years*. If they can't keep all of their documentation consistent, that's Not Our Problem.

I vote to use "UniProt accessions" in our search label, *without* including "numbers" - even if they were all digits, it would still grate to have the superfluous word there. Maybe put in one of those little mouseover 'i' thingies with that help link too?

**Comment by ValWood** [comment]
UniPRot accessions seems a good compromise, and is correct.
if people can't find things  we can add an FAQ (or an eg in brackets)

UniProt should get rid of the useless 'identifiers'

**Comment by kimrutherford** [comment]
> UniPRot accessions seems a good compromise, and is correct.

OK.  I've made that change.

**Comment by ValWood** [comment]
Can this close?

**Comment by ValWood** [comment]
closing  open if required
