### ISSUE TITLE
Confusing to have 2 levels to ftp site

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1277]
Historically the main ftp site we made available to users was
ftp://ftp.pombase.org/pombe/

there was a level above at the ebi but we didn't really use it. Mark used to put stuff here.

Now we use this as the "entry point"
ftp://ftp.pombase.org/

which lists
archive/		2/4/19, 8:07:00 PM
external_datasets/		3/13/19, 10:45:00 AM
nightly_update/		4/30/19, 2:05:00 AM
pombe/		9/4/18, 1:00:00 AM
releases/		3/13/19, 10:19:00 AM

and has no README or instructions.

I suggest we revert to using 
ftp://ftp.pombase.org/pombe/
so people see the directories they are interested in when they land. This may partly explain why people struggle to find things?

We should move the other directories (which are not advertised AFAIK) down to this  entry point and document them.

**Comment by ValWood** [comment]
in fact 
ftp://ftp.pombase.org/pombe/README
says
This is the root directory for fission yeast data files maintained by PomBase.

If you use this data in a publication please cite PomBase as described:
- http://www.pombase.org/about/citing-pombase
(i.e describes as the root directory). 
so I think we just linked to the incorrect directory?

It might be useful to design this page
https://www.pombase.org/datasets
so it describes all of the contents here 
ftp://ftp.pombase.org/pombe/
(including any moved  in from above)

and can also be used to generate the README file so it doesn't need to be maintained in 2 places (is that possible?). If not just a link to the web page describing the director/subdirectory contents  (in a way that maps to  the current contents)

**Comment by ValWood** [comment]
1
change link on the website 
https://www.pombase.org/datasets
to
ftp://ftp.pombase.org/pombe/

2.
Move archive
into 
ftp://ftp.pombase.org/pombe/

3. Make external datasets a linked file from
ftp://ftp.pombase.org/pombe/

**Comment by kimrutherford** [comment]
> Move archive into
> ftp://ftp.pombase.org/pombe/

Just to check: do we definitely want to do that?  We would need to move that directory into the pombe-embl subversion repository because the pombe directory on the FTP site is just a copy of pombe-embl/ftp_site/pombe from SVN.  The archive directory is 8GB and it would be added to everyone's checked out copy of pombe-embl next time you do an "svn update".

My vote is to add archive to SVN despite the size because I think it makes sense to keep it in SVN along with the other FTP site contents.

**Comment by kimrutherford** [comment]
These changes are done:

> change link on the website >https://www.pombase.org/datasets
> to ftp://ftp.pombase.org/pombe/

>    Make external datasets a linked file from
>    ftp://ftp.pombase.org/pombe/
>    Make releases datasets a linked file from
>    ftp://ftp.pombase.org/pombe/

**Comment by ValWood** [comment]
Could we just ling the archive from here:
ftp://ftp.pombase.org/pombe
as for external datasets?

Is that what you are suggesting?

**Comment by kimrutherford** [comment]
I was thinking that it makes sense to add the archive to SVN but I wanted to make sure that everyone's OK with the pombe-embl directory tripling in size.  A link is the other possibility.

**Comment by mah11** [comment]
> but I wanted to make sure that everyone's OK with the pombe-embl directory tripling in size

for me it would be mildly inconvenient but not worse; I don't really object

**Comment by ValWood** [comment]
I  would be happy with linking if that is possible

**Comment by kimrutherford** [comment]
I've added a link to the archive directory to SVN.  I'll check the FTP site on Wednesday and then close this issue.

**Comment by kimrutherford** [comment]
> I would be happy with linking if that is possible

I've added the link.  I think this issue is done now.

**Comment by ValWood** [comment]
OK. I wish it didn't show the size as "0" that always makes me think they don't exist.

There is a random  .tmp file in there...

**Comment by kimrutherford** [comment]
>There is a random .tmp file in there...

Thanks.  I've removed it.
