### ISSUE TITLE
external references documentation text

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1278]
the (i) for externally predicted orthologs looks a bit weird (it's written for the external ref section) - it's not wrong but perhaps the text could be tweaked?

eg from
The External references section of a gene page provides links to information on a g....

to
External references on a gene page provides links to information on a g...

<img width="775" alt="Screenshot 2019-05-01 at 09 11 22" src="https://user-images.githubusercontent.com/12727506/57009921-90138700-6bf1-11e9-9943-a8aad362a718.png">

**Comment by mah11** [comment]
> the (i) for externally predicted orthologs looks a bit weird (it's written for the external ref section) - it's not wrong but perhaps the text could be tweaked?

A better fix would be to add something about the prediction links to the documentation for the ortholog section, so that section doesn't have to bring up documentation for a different part of the gene page. I have edited the ortholog section documentation accordingly.

@kimrutherford, your share of this one is to make sure the ortholog section (i) links all go to the ortholog documentation, not the external refs documentation.

**Comment by ValWood** [comment]
This was still on my to do list as part of issues/1263 to check the existing FAQs and docs

**Comment by kimrutherford** [comment]
> @kimrutherford, your share of this one is to make sure the ortholog section (i) links all go to the
> ortholog documentation, not the external refs documentation.

Maybe it's best to just remove the (i) link beside the "Ortholog prediction resources" title?

**Comment by ValWood** [comment]
We could just add a sentence to the ortholog documentation  to explain why some are curated to  make it clear that we won't be manually curating other species orthologs

Ortholog prediction resources

Maintaining comprehensive and up to date orthology data sets using all of the ortholog available predictors  is both computationally and labour intensive and is  outside the scope of this project.

Instead, we provide links to two excellent  integrated orthology prediction services (DIOPT and HCOP) that include most of the major orthology prediction tools (Inparanoid, OMA, OrthoDB, OrthoFinder, OrthoInspector, orthoMCL, Panther, RoundUp, Compara, TreeFam etc). 

We  alsoinclude  links to Panther and Ensembl Fungal Compara which both provide gene trees adn alignments.  Ensembl Fungal Compara will provide access to alignments and gene trees for S. japonicas and S. octosporus.

Also add to curated data section:
The curated data is searchable using either a HGNC approved name (e.g. PTTG1 ), or an S. cerevisiae ORF (systematic) ID e.g. YDR113C in the “simple search” box.

**Comment by ValWood** [comment]
@mah11 I think this can be updated? Let me know if not

**Comment by mah11** [comment]
@ValWood 

> I think this can be updated?

It's not at all clear what "this" means here, but the only thing to do is for Kim to change the orthology section help link (as noted [above](https://github.com/pombase/website/issues/1278#issuecomment-488614924)). I updated the ortholog documentation months ago.

@kimrutherford ,

> Maybe it's best to just remove the (i) link beside the "Ortholog prediction resources" title?

That would be fine with me.

**Comment by ValWood** [comment]
> It's not at all clear what "this" means here

Adding  a section about "ortholog prediction resources" to the documentation

pus a bit about what in the ortholog section is searchable using the simple search

**Comment by mah11** [comment]
both are done via links to FAQs, which avoids duplication & divergence (good in evolution; not so much in documentation ;) )

**Comment by ValWood** [comment]
Done/and/ or out of date
