### ISSUE TITLE
small text change

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1279]
Ortholog section subheadings
Manually assigned orthologs 
Predicted orthologs 

I think the second one should be 

Predicted ortholog resources

(just to make it clearer that each one is a sperate resource, it might be a bit confusing because of the ID column matching the curated ones. People could be confused)

**Comment by kimrutherford** [comment]
I've changed that.  It should be visible in tomorrow's update.

**Comment by kimrutherford** [comment]
> I've changed that. It should be visible in tomorrow's update.

Now it's visible I wonder if "Ortholog prediction resources" would sound better?

**Comment by ValWood** [comment]
yes it would!

**Comment by kimrutherford** [comment]
OK, I've changed the text.
