### ISSUE TITLE
use GO xrefs for external annotation object URLs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#128]
The GO set has moved to http://amigo.geneontology.org/xrefs, which has links to yaml and plain text versions too:

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml
http://geneontology.org/doc/GO.xrf_abbs

report any missing

**Comment by kimrutherford** [comment]
I think this is done now?

**Comment by ValWood** [comment]
seems ok, only a quick spot check. new tickets for problems..
