### ISSUE TITLE
protein domains, potential FAQ update?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1280]
These were the requests:

- Accessing lists of proteins containing a specific protein domain
- New tools for looking at protein domains, motifs, and where else they're seen (which other proteins) 
- Able to come out with a list when I search for certain motifs or domains. 

Isn't it obvious?

I sent this to pombelist:

In our survey, a number of users requested the ability to search on  a specific protein domain, find domains in other proteins (lists of genes containing a specific domain). All of these features are already available.

We include  all fission yeast domain data provided  by InterPro in PomBase. InterPro  combines protein signatures from a number of member databases (Pfam, Panther, SMART, prosite etc)  into a single searchable resource, capitalising on their individual strengths to produce a powerful integrated database.
 
To access the list of other  fission yeast proteins containing a domain of interest, first find your domain in the “protein feature” section of the PomBase gene page. At the right hand side is a “count” column. This is a link to a list of all fission yeast proteins with this domain. 
e.g  
EF hand (SMART)
https://www.pombase.org/gene_subset/interpro:IPR000261
EF hand (Prosite)
https://www.pombase.org/gene_subset/interpro:IPR002048

You might want to combine the presence of multiple domains (intersection or union). You can do this by sending the domain list to the query builder using the link “Use these genes in query…”
You can apse search for a domain directly in the “advanced query interface”  if you have the identifier https://www.pombase.org/query

To find proteins in other species with this domain, click any InterPro ID link for the family, and select “Species” from the left hand “Overview” menu to access domain numbers in key model species (including fission yeast)

**Comment by mah11** [comment]
Is there a specific task here? If so, can you clarify what it is?

**Comment by ValWood** [comment]
I need to read the FAQs first to see what they say. Clearly people are missing this.

**Comment by ValWood** [comment]
actually its really clear....
https://www.pombase.org/faq/how-can-i-find-all-s.-pombe-proteins-particular-protein-family

maybe 
i) change  FAQ title to "family or domain"

ii)
If you don't have an accession, but do know any member of the family, go directly to its gene page. In the "Protein Features" section of the gene page there is a table of protein domains and families, which includes a link to a list of all family members in S. pombe.
(+ the 'count' column number )

(I have seen a few people not realise what the count column was initially)
