### ISSUE TITLE
Full JBrowse link

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1281]
2) I would like the option in the genome browser to be able to input specific positions to view, instead of dragging the window.

is this label fixed? Could it be something  clearer?
I have been asked this before...

**Comment by kimrutherford** [comment]
> is this label fixed?

Which label?

**Comment by ValWood** [comment]
I mean link "full-screen view"

It might be better if it said something like "GO to JBrowse" 

"full-screen view" slightly implies the same image but bigger!

**Comment by Antonialock** [comment]
+1

it should be more obvious it launches the full jbrowse

**Comment by kimrutherford** [comment]
I think I've worked out what to change in JBrowse.

> It might be better if it said something like "GO to JBrowse"

Can we say "Go to genome browser" to be consistent with the front page?

**Comment by ValWood** [comment]
yes, let's change to that now, we can improve if we think of something better.

**Comment by kimrutherford** [comment]
The link now says "Go to genome browser" and I've also updated to the latest version of JBrowse.

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by ValWood** [comment]
I wonder if it would be too long if we put 

Go to Genome Browser (configure tracks)
?

**Comment by mah11** [comment]
> I wonder if it would be too long if we put
> 
> Go to Genome Browser (configure tracks)

Yes, it would be too long. It would also be needlessly over-specific, since track configuration is not the only thing available in the full browser but not the gene page piccies.

**Comment by ValWood** [comment]
but this is *exactly* what a number of users do not realise.

They don't realise that the "full view" has tracks and search options. The current wording change might be enough.
