### ISSUE TITLE
misclassification of some  qualitative expression data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1283]
small issue on the wee 1 page

Qualitative gene expression

protein level | decreased during mitotic anaphase | western blot evidence used in manual assertion | Lucena R et al. (2017)
-- | -- | -- | --
RNA level | increased during cellular response to oxidative stress | expression microarray evidence | Chen D et al. (2003)

but the filter option is  "non-experimental"

This means that these must be classified incorrectly earlier on,  because I don't think we can have non-experimental expression data.
It is possible this is from Artemis in which case epression data in Artemis needs changing to "experimental, LTP"

**Comment by kimrutherford** [comment]
That annotation is from a contig file.  Should all the expression data in the contig files be LTP?  I'll fix that for tonight's load.

**Comment by kimrutherford** [comment]
> I'll fix that for tonight's load.

I've done that and I'll check tomorrow.

**Comment by kimrutherford** [comment]
That's fixed now.
