### ISSUE TITLE
New PomBase Twitter background image

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1284]
I'll like to add a higher resolution header image for PomBase: https://twitter.com/PomBase

Any suggestions?

![twitter-1](https://user-images.githubusercontent.com/90474/57177854-7b1e4880-6ebc-11e9-83d9-9917a0b4cc51.png)

**Comment by mah11** [comment]
What dimensions? I caan crop something out of one of Silke's micrographs to match the website header.

**Comment by kimrutherford** [comment]
Something like 1500x500 or in that ratio would be best.  Cheers.

**Comment by mah11** [comment]
like this? small example here; if you like it I'll stick the full-size thing in assets, or wherever else you want it.

![pombe_ascus_3to1_small](https://user-images.githubusercontent.com/5196259/57310297-71c1f580-70e1-11e9-9e06-a3ecd5519541.png)

**Comment by kimrutherford** [comment]
Thanks, that would be great.  Yep, let's put it in the assets directory.

**Comment by mah11** [comment]
OK, done.

**Comment by kimrutherford** [comment]
Thanks.  Looks great.

![twitter-2](https://user-images.githubusercontent.com/90474/57366715-b336cb80-71db-11e9-9abe-949ca7895468.png)
