### ISSUE TITLE
Jbrowse URL stuck on loading

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1287]
If you go to 
https://www.pombase.org/jbrowse/ 
JBrowse loads fine.

If you go to
https://www.pombase.org/jbrowse 
you get stuck on a page saying "loading"

is it possible to make it work without ending on / ? it's just odd!

**Comment by Antonialock** [comment]
<img width="1002" alt="Screenshot 2019-05-11 at 15 20 25" src="https://user-images.githubusercontent.com/12727506/57571015-929b8b00-7400-11e9-8479-1201d37bde13.png">

**Comment by Antonialock** [comment]
the difference in URL is:
https://www.pombase.org/jbrowse/ (this one works)
vs
https://www.pombase.org/jbrowse (this one doesn't work)

is it possible to make it work without ending on / ? it's just odd!

**Comment by kimrutherford** [comment]
> is it possible to make it work without ending on / ?

Thanks for tracking this down.  We should be able to cope with no "/" at the end.  I'll work on that.

**Comment by kimrutherford** [comment]
That's fixed now.
