### ISSUE TITLE
provide useful message if no match in search box

### ISSUE THREAD

**Issue by mah11** [pombase/website#129]
At present, if I type something that doesn't match a gene name or ID ino the search box, nothing happens when I hit return. There's no feedback.

It would be much more helpful if it went to a message saying "sorry, no match found for x" or words to that effect.

Later, when we/you implement faceted searching, we can add specificity to the messages, e.g. "no matching gene|publication|term found for x".

**Comment by kimrutherford** [comment]
I've changed it to say "No matching gene" if there is no match.

**Comment by mah11** [comment]
That works - thanks!
