### ISSUE TITLE
research spotlight PMID: 30044717 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1290]
For tomorrow

Previously uncharacterized protein, Ync13, has a role during late stages of cytokinesis

originally published in  Mol Biol Cell

![Munc_spotlight](https://user-images.githubusercontent.com/7359272/57766851-05a64980-7700-11e9-9b3c-fc0018e1d0e8.jpg)

**Comment by kimrutherford** [comment]
I've done the configuration, ready for the next update.

**Comment by kimrutherford** [comment]
That new Spotlight is visible now: https://www.pombase.org/archive/spotlight

**Comment by ValWood** [comment]
I have a new figure from the author with correct aspect ration. Includes key.

![Untitled](https://user-images.githubusercontent.com/7359272/57833692-845bbf00-77b2-11e9-98d6-9a28dfcac986.jpg)

**Comment by kimrutherford** [comment]
I've updated the Spotlight image.
