### ISSUE TITLE
jbrowse documentation broken?

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1292]
I added a section to the documentation

https://github.com/pombase/website/edit/master/src/docs/documentation/JBrowse_quick_start.md

but the preview doesn't show any images at all? Did I break something?

**Comment by kimrutherford** [comment]
Unfortunately the GitHub preview doesn't show the images.  I'll check the page looks OK next time I re-release.

**Comment by kimrutherford** [comment]
Your changes are visible now.
