### ISSUE TITLE
news item "tRNA metabolism"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1293]
image

![3d_tRNA](https://user-images.githubusercontent.com/7359272/57945162-0215ec80-78d1-11e9-84cd-b7739ab64981.png)

courtesy of Reactome

The process of tRNA metabolism, and the associated molecular functions have recently been reviewed
https://www.pombase.org/term/GO:0006399
https://www.pombase.org/term_genes/GO:0006399
Please let us know if the annotation can be further improved.

**Comment by kimrutherford** [comment]
How big would you like the image to be in the news item?  Or should we use it as the icon on the left?

**Comment by ValWood** [comment]
as icon....it scales down ok

**Comment by ValWood** [comment]
i saw it small although it looks huge here!

**Comment by kimrutherford** [comment]
> The process of tRNA metabolism, and the associated molecular functions have recently been reviewed

Should that be the title or part of the text?

**Comment by ValWood** [comment]
Title: tRNA metabolism GO annotation update

**Comment by kimrutherford** [comment]
That's on the front page now. Let me know if it needs any tweeks.
