### ISSUE TITLE
create allele pages/ display  all genotypes containing this allele

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1294]
We would like  allele pages to display
"all genotypes of an allele" 
Also the associated phenotypes for all.
(It's another useful way to cut through the complexity)

We would need, on the single allele page, 
I) all other single gene alleles (irrespective of expression or background)
2) a link to all multi-gene genotypes containing said allele

related 
 #1255 all alleles of this gene
https://github.com/pombase/website/issues/250 allele filters on phenotype section
~https://github.com/pombase/website/issues/1325 Add synonyms to allele pages~ replaced by this ticket

**Comment by kimrutherford** [comment]
Is that the same as: #250 or #353?

**Comment by ValWood** [comment]
Yes  these are related. I was thinking of a page, but with the filter, it might not be necessary to have a page. I just  found a note that we talked about it. Let's discuss this in group when Midori is back. it's low priority.

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/1255 is an *exact duplicate*

**Comment by ValWood** [comment]
actually it isn't but I'm not sure what we said we wanted. We should confirm

**Comment by ValWood** [comment]
Which genotypes include a given allele?
Display list  AND the phenotypes

Issues
On;y want dor single alleles, BUT some single alleles have different expression

Is this allele part of any other genotype=? If YES provide a link to a page with  
"all genotypes containing this allele"

Probably do this by 
i) creating an allele page
ii) listing all genotypes containing this allele on the page

2 sections with single and multi allele annotations

**Comment by kimrutherford** [comment]
Could this list go on an allele page: #1325?

**Comment by ValWood** [comment]
Yes I think that is what we decided.

>i) creating an allele page
>ii) listing all genotypes containing this allele on the page

**Comment by mah11** [comment]
yep, I concur

**Comment by ValWood** [comment]
I edited the first comment to summarize the discussion (I think)

**Comment by kimrutherford** [comment]
> Kim suggested extending the allele page

I don't understand this.  We don't have allele pages?

**Comment by ValWood** [comment]
https://www.pombase.org/genotype/mad3-KEN2-AAA-K271A,E272A,N273A-amino_acid_mutation-expression-not_assayed

**Comment by ValWood** [comment]
Oh so this is a genotype page. 
So what do we do with the background?

**Comment by kimrutherford** [comment]
Here's an example:
 https://www.pombase.org/genotype/mei4-N136A-N136A-amino_acid_mutation-expression-not_assayed

Click "Show details ..." to see the Background column.

**Comment by ValWood** [comment]
comment from Kim transferred from #1325
Allele pages wouldn't be too much work if that's what we need. I think having a good allele search system is the important thing.

Maybe the right way to handle this is to include allele/genotype searching as part of a "faceted" search: #929? So if you search for "pom1-KD" it could list the genotypes that include that allele and show "pom1" as a match in the gene section? We could also do fancy stuff like showing a list of publications that mention the allele and even phenotypes terms that are annotated on the genotype. All on one page.

**Comment by mah11** [comment]
> Maybe the right way to handle this is to include allele/genotype searching as part of a "faceted" search ...

That's a thoroughly decent idea in its own right, but I don't see how it changes the plan to add allele pages. It fleshes out more things that would be on allele pages, and ways to reach them.

> So if you search for "pom1-KD" it could list the genotypes that include that allele and show "pom1" as a match in the gene section? 

gene section of what? a list of search results?

> We could also do fancy stuff like showing a list of publications that mention the allele and even phenotypes terms that are annotated on the genotype. All on one page.

Yes ... that would be the allele page.

**Comment by ValWood** [comment]
This might be a useful thing to push through to report in the upcoming paper?

**Comment by kimrutherford** [comment]
> This might be a useful thing to push through to report in the upcoming paper?

What's the time scale?  There's quite a bit going on at the moment.

**Comment by kimrutherford** [comment]
> on the single allele page,
> I) all other single gene alleles (irrespective of expression or background)

How would the page look if it needs to show multiple expression levels?

Do we need to partition the page by expression level?  So have all the annotation and other details for abc123-overexpressed then have a separate section with annotation for abc123-knockdown?

**Comment by ValWood** [comment]
> What's the time scale? There's quite a bit going on at the moment.

I think it is August? @mah11  would need to confirm. 

We can make a plan and see if it gets to the top of the list....

**Comment by ValWood** [comment]
> Do we need to partition the page by expression level? So have all the annotation and other details for abc123-overexpressed then have a separate section with annotation for abc123-knockdown?

I think so....

**Comment by ValWood** [comment]
I think that was the plan.
We needed
https://www.pombase.org/genotype/cdc2-D134R-D134R-amino_acid_mutation-expression-not_assayed
https://www.pombase.org/genotype/cdc2-D134R-D134R-amino_acid_mutation-expression-overexpression
plus any multi gene genotypes with that allele.


It was particularly needed, I think, because  often we have "Wild type product" and "unknown expression"

https://www.pombase.org/genotype/cdc2-Y15F-Y15F-amino_acid_mutation-expression-not_assayed
https://www.pombase.org/genotype/cdc2-Y15F-Y15F-amino_acid_mutation-expression-wild_type_product_level

(this is a bit of an issue because it will *usually* be the same strain- but we don't always know that)

so a page that groups everything will allow the users to figure that out.

**Comment by mah11** [comment]
I would not defer anything that's currently higher priority just to get this out in time for the manuscript. We have enough other stuff, and a theme to which this is at best tangential.

**Comment by kimrutherford** [comment]
If we have allele pages I think we'll need to label the single-allele genotype pages more clearly.  This looks a lot like an allele page to me:
https://www.pombase.org/genotype/mcm5delta

It will be confusing if we have a page for "mcm5Δ" (the genotype) and "mcm5Δ" (the allele) with almost the same contents.

**Comment by mah11** [comment]
> If we have allele pages I think we'll need to label the single-allele genotype pages more clearly.

Good point. We've just added "Diploid genotype" to the relevant pages, so perhaps it would do (or at least help) to add "Haploid genotype" where applicable as well.

Maybe also prefix allele headers with (wait for it) "Allele:"?

**Comment by kimrutherford** [comment]
I've been wondering for a while if it would be better to clearly label the page type.  I think we discussed this long ago and decided against it.

![pub-page-label-1](https://user-images.githubusercontent.com/90474/113124979-9b0a4280-9272-11eb-9f1b-095554d5362e.png)

![gene-page-label-1](https://user-images.githubusercontent.com/90474/113125445-17048a80-9273-11eb-8b5b-20b44745f424.png)

**Comment by mah11** [comment]
> I've been wondering for a while if it would be better to clearly label the page type. I think we discussed this long ago and decided against it.

Quite possibly; I don't remember. But that probably means it was before we had quite as many page types as we do now, so there's kind of a case for changing.

I think I'd go with just "Gene", not "Gene details", for the gene pages. It's shorter; you haven't suggested including "details" for the others, and people know the gene pages well enough that we don't need to tell them they're full of details ;)

**Comment by kimrutherford** [comment]
Note from https://github.com/pombase/pombase-chado/issues/753#issuecomment-804042425:
Include allele comments on allele details pages.

**Comment by kimrutherford** [comment]
> I've been wondering for a while if it would be better to clearly label the page type.

I went ahead and did that.  Easy to change if you don't like it.

**Comment by kimrutherford** [comment]
> Also the associated phenotypes for all.

How should those be displayed?  Just a list of the phenotype names?:

```md
 - abolished cell population growth at high temperature
 - decreased cell population growth at high temperature
 - decreased cell population growth on glucose carbon source
 - decreased conjugation frequency
 - decreased mitotic index
```

etc.

**Comment by ValWood** [comment]
I think so. It won't look very exciting, but it's useful.

**Comment by ValWood** [comment]
The sde6-M210 discussion is a good example where the "show me all genotypes containing this allele" would be useful.
It's nice to see them all at once. Apart from that it's easier to see all pubs mentioning an allele, it is useful biologically to be able to see all of the phenotypes (to be able to see if there are examples of rescue/suppression etc of particular phenotypes..

**Comment by kimrutherford** [comment]
> The sde6-M210 discussion is a good example where the "show me all genotypes containing this allele" would be useful.

It won't take too long to add allele pages and an allele search - 1 or 2 days depending on how many bugs and problems I run into.  But I'd like a chat about it before I start.

**Comment by ValWood** [comment]
Yep, not super urgent. Let's park this for a few months (sorry to change the priority). Now we have Manu stating there are a few tickets that would be useful before he begins. Let's make a plan next time we chat.

**Comment by kimrutherford** [comment]
Note inspired by pombase/canto#2511: need to remember to include allele comments on the allele pages

**Comment by kimrutherford** [comment]
I think it's sensible to finish pombase/website#1882 before we try to implement allele pages.

**Comment by kimrutherford** [comment]
I've started work on the processing code for these pages.  I've made some temporary allele pages to help with testing:
https://www.pombase.org/allele/SPAC1805.17:allele-8

The only links to these allele pages are from the "all alleles of a gene" pages like:
https://www.pombase.org/gene_alleles/SPAC1805.17
There are no links to those pages as they aren't finished.

**Comment by kimrutherford** [comment]
> Also the associated phenotypes for all.

I've added a column to the allele details page containing the phenotypes.  We can talk about style/formatting (like adding bullet points) later on.  This change will be visible tomorrow.

![image](https://user-images.githubusercontent.com/90474/183832313-740b99b2-e567-478e-a31d-16cd4fe3df5d.png)

**Comment by kimrutherford** [comment]
I've put the genotypes in alphabetical order, with the diploids always last in the list.  The phenotypes are in alphabetical order too now.

![image](https://user-images.githubusercontent.com/90474/184099199-ed69f233-2f6c-436f-906e-a302283a153b.png)

**Comment by kimrutherford** [comment]
I've added the comments to the allele details pages.  It now supports having more than one comment and there are links to the reference.

(Search for "stx8-122-131A" on http://dev.pombase.kmr.nz/ to see this example)

![image](https://user-images.githubusercontent.com/90474/184782597-ebf7a4b7-0441-4e82-be8e-9f07fc627dab.png)

**Comment by ValWood** [comment]
This looks good. From a curation point of view it looks incorrect though! The second comment does not appear to belong to the allele stx8-122-131A.

@manu we should make a point in the documentation for allele descriptions that this  shorthand description syntax  for amino acid substitutions QKTTSSSEGS-122-AAAAAAAAAA.
I will open a ticket to check that 
1. for standard description types the descriptions all conform
2. that the prompts and documentation describes these

**Comment by ValWood** [comment]
One of the lines
stx8-122-131A   aa142-151 changed to alanines   PMID:33788833
was changed to 
stx8-142-131A   aa142-151 changed to alanines   PMID:33788833
so this will no longer be an example of duplicated comments

**Comment by ValWood** [comment]
I could not see comments on 
"http://dev.pombase.kmr.nz/ to see this example"

**Comment by ValWood** [comment]
> I could not see comments on
"http://dev.pombase.kmr.nz/ to see this example"

ignore, these are  allele pages not genotype pages.

**Comment by ValWood** [comment]
Looks good.
Clost this ticket as soon as you can and we con open new ones for the outstanding tasks.
How  were we going to link to allele pages, I forgot?
Also need to discuss how this will work with
https://github.com/pombase/canto/issues/2544 (for some allele types we don't really need to record the expression with the genotype). I put this at the top of the discussion list.

**Comment by ValWood** [comment]
Since alleles will have systematic names, will there be any consequences if we delete an allele. Will the systematic ID ve archived/obsoleted?

**Comment by kimrutherford** [comment]
> How were we going to link to allele pages, I forgot?

That's one of the things to discuss.

> Since alleles will have systematic names, will there be any consequences if we delete an allele. Will the systematic ID ve archived/obsoleted?

That needs thought and discussion too.  It's a bit tricky.  So is handling re-naming alleles.

**Comment by kimrutherford** [comment]
In the genotype lists could the 'single allele genotype' be at the top of the list, followed by 'multi', then 'diploids'?

**Comment by ValWood** [comment]
I think that would be OK, if there is no easy way to do

single allele genotype
single allele diploid
multi allele genotype
multi allele diploid ?

**Comment by kimrutherford** [comment]
> In the genotype lists could the 'single allele genotype' be at the top of the list, followed by 'multi', then 'diploids'?

I don't understand my comment.

> I think that would be OK, if there is no easy way to do
>
> single allele genotype
> single allele diploid
> multi allele genotype
> multi allele diploid ?

That's how it is at the moment?  Except there aren't headers for the diploid sections, we show them in bold instead like on the other pages:

![image](https://user-images.githubusercontent.com/90474/206940896-b87f6d66-0f50-4d19-8a53-f0ab9a7506f1.png)

**Comment by ValWood** [comment]
>That's how it is at the moment? Except there aren't headers for the diploid sections, we show them in bold instead like on the other pages:

That's perfect then!

**Comment by ValWood** [comment]
i just found some notes from a recent meeting about this:

GI where FYPO:blah is the double mutant phenotype
GI where FYPO:blah is the single mutant phenotype

**Genotype page**
Phenotypes, genetic interactions

**Allele page** 
(all of the genotypes that a single allele is part of + phenotypes)
Alleles comment 

**All alleles of a gene page**
Remove links to page get of expandable links to genotypes (links will be available)
Add synonyms column
Move WT and deletion to the top of the table

I think we should close this ticket and open a new on with e outstanding tasks....

**Comment by kimrutherford** [comment]
> I think we should close this ticket and open a new on with e outstanding tasks....

New issue:
 - pombase/website#2147
