### ISSUE TITLE
new research spotlight PMID:30914423 . PMID:31042107

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1295]
Simple procedure for the generation of temperature-sensitive mutations with error-prone PCR

![toda](https://user-images.githubusercontent.com/7359272/57971397-64302980-7985-11e9-8df9-48c1710fb6a7.jpg)

 PMID:31042107

**Comment by ValWood** [comment]
ALso
PMID:30914423

pretty much the same method
![hinge](https://user-images.githubusercontent.com/7359272/57971565-c7bb5680-7987-11e9-9d30-73f033d5252f.jpg)

I have pushed both papers through together.

text:
Isolation of single amino acid t-s mutants in condensin hinge domain.

**Comment by kimrutherford** [comment]
> I have pushed both papers through together.

Should we have one Spotlight or two?  What was the PMID of the second paper?

**Comment by ValWood** [comment]
ah sorry two.

PMID for second paper PMID:30914423

**Comment by kimrutherford** [comment]
> PMID for second paper PMID:30914423

Is that the PMID for the first image or the second image?

**Comment by ValWood** [comment]
Good point :)
PMID:31042107 is the first

**Comment by kimrutherford** [comment]
I've added those two Spotlights.
