### ISSUE TITLE
research  spotlight  PMID:30463883

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1296]
PMID:30463883

![balance](https://user-images.githubusercontent.com/7359272/57986143-ff4dff80-7a68-11e9-917a-d663a20b909a.jpg)

(won't go through for a while, waiting on FYPO terms)

MAPs and Microtubule Dynamics Balance with the Cut7/Kinesin-5 Motor for Mitotic Spindle Assembly

**Comment by ValWood** [comment]
https://github.com/pombase/fypo/issues/3455

**Comment by kimrutherford** [comment]
Is this Spotlight ready to go?

**Comment by ValWood** [comment]
oops yes...

**Comment by kimrutherford** [comment]
I've added this Spotlight and it should be visible in 5-ish minutes once the site is re-released.
