### ISSUE TITLE
use gene name as title for gene page (and other page title ruminations)

### ISSUE THREAD

**Issue by mah11** [pombase/website#130]
Plug the gene name, or systematic ID for unnamed genes, into the html title element so things like browser history, tab headers, etc. will say something more specific than "PomBase - gene". It's fine to keep the PomBase part, e.g. "PomBase - cdc2".

Could also do similar for reference and ontology term pages. For those it might be enough to use the PubMed or ontology ID, rather than look up term names or citation parts.

**Comment by kimrutherford** [comment]
I've done this.  The title are quite long for now but we can trim them based on experience.
