### ISSUE TITLE
enable download of Molecular function substrates

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1300]
final items from
#576

actually  this has never been asked for (physical interactions has). So let's not do this at least at present.

more like people would want to "send the MF targets to the query builder.
You can do this already for physical interactors. There is a link

View interactions for cdc2 at BioGRID ...
Query using interacting genes ...

perhaps we could add a link
Query using XXX substrates genes ...

So for cdc2 this would put all of te cdc2 targets into the query builder
 https://www.pombase.org/gene/SPBC11B10.09

cdc25,clp1,
crb2, sds23
bit61, cdc15, cdc23, crf1, csi1, dbl7, dfp1, dnt1, drc1, fkh2, ies4, iss10, lem2, mdb1, mis4, msh6, mvp1, orc1, rad2, sec16, sgo2, sld3, snt1, ulp2 during mitotic G2 phase
  | has substrate abp1, adn2, alp14, ani1, ase1, ask1, atf1, bir1, bit61, bpb1, bqt4, brf1, bud6, bun107, byr4, ccq1, cdc15, cdc23, cdc25, clp1, cmk2, cnt5, cph1, crf1, csi1, cut3, cyk3, dbl7, dbp10, dfp1, dis1, dnt1,drc1, ebs1, elo2, epe1, fkh2, gef1, hal4, hip1, hmo1, ies2, ies4, inp53, iss10, kin1, klp9, kms2, lem2, lnp1, mac1, mcm4, mdb1, mde4, mgs1, mis4, mkh1, mmb1, mmi1, mod5, mpd2, msh6, mtl2, mto1, mug176, mvp1,nrm1, nsk1, nup124, nup146, nup40, nup60, nur1, orc1, orc2, pan3, pch1, pdr16, pic1, plo1, pob1, pof1, pom1, pom2, ppc89, ppk30, pre6, prp3, psy2, puf6, pxl1, rad2, rad4, rad52, rga2, rga3, rga4, rgf3, rif1, rod1,sad1, sce3, scw1, sec16, sep1, sfr1, sgo2, shd1, sid2, sld3, slf1, snt1, sog2, spo12, spo15, srp40, sup35, swi10, tam10, tea2, tfg1, tmf1, ulp2, utp502, vps5, vts1, wis1, wis4, wpl1, SPAC24B11.07c, SPAC24H6.08,SPAC9G1.07, SPBC13E7.07, SPBC17A3.05c, SPBC17D1.05, SPBC428.10, SPBC9B6.03, SPBC9B6.11c, SPBP8B7.26, SPBPB7E8.02

**Comment by ValWood** [comment]
This is related to the 'feature' that the Nurse lab wanted (it would be useful to get lists of substrates, or targets).
I will put this on the discuss list to chat about.

**Comment by kimrutherford** [comment]
> perhaps we could add a link
> Query using XXX substrates genes ...

That would probably be quite quick.  Maybe half a day, maximum?

But it sounds quite all or nothing.  Do we need any download options so you could get, for example, just the targets of one MF term?

**Comment by ValWood** [comment]
I don't think that is necessary, but mainly because I don;t know of a gene with targets  with 2 different molecular functions.

Obviously cdc2 has
[cyclin-dependent protein kinase activity](https://www.pombase.org/term/GO:0097472)
[cyclin-dependent protein serine/threonine kinase activity](https://www.pombase.org/term/GO:0004693)
[protein kinase activity](https://www.pombase.org/term/GO:0004672)
[protein serine/threonine kinase activity](https://www.pombase.org/term/GO:0004674)
[protein serine/threonine/tyrosine kinase activity](https://www.pombase.org/term/GO:0004712)

but these are all essentially describing the same activity.

More useful might be the ability to filter by phase.

**Comment by kimrutherford** [comment]
Is this related?:
   - pombase/website#1887

**Comment by kimrutherford** [comment]
I've added a "Query using substrate genes ..." link on my desktop version:
https://desktop.kmr.nz/gene/SPBC11B10.09

It will appear in the dev site tomorrow but is currently not enabled on the main site.

I'm not sure about the "Query using substrate genes ..." link text.  I wonder if something like "Send substrate genes to the advanced search" would be better?  That would be closer to what we have in the motif search: "Send gene list to advanced search".

> More useful might be the ability to filter by phase.

I haven't implemented that yet but I don't think it would take long.

**Comment by ValWood** [comment]
This is great! We definitely want to be able to filter by phase too.
I was also wondering ( you have probably told me, but why is the phase filter only available under the full view since the phases themselves are visible in the summary view?

**Comment by ValWood** [comment]
Maybe 
Send 'substrate' gene list to advanced search
to be clear?

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/1887
is the same feature, but is more extensive (to be able to do 'target_of' lists too)

**Comment by kimrutherford** [comment]
The download substrates link is now in the dev site: http://dev.pombase.kmr.nz/gene/SPBC336.12c

> We definitely want to be able to filter by phase too.

I'll work on that after the paper is submitted.  It will probably only take half a day.

**Comment by kimrutherford** [comment]
> We definitely want to be able to filter by phase too.

Should there be an option to download the targets that don't have an annotated phase?

**Comment by ValWood** [comment]
I think for now, all targets or specific phase targets might be enough
It makes it less complicated and it is easy to figure out the "no phase annotated" in the query builder once you have the lists.
We can work on adding the phases.

**Comment by kimrutherford** [comment]
The query server side is complete now.  Here's an example:
https://pombase.org/results/from/id/e592ee17-f995-452d-8277-3c32ac413f0c

... but there's no interface to get that result yet.  I'll do that next.

I'd say this is two thirds done now.  I think another 2-3 hours.

**Comment by kimrutherford** [comment]
I've mostly got this working,  I'll demonstrate on the next call.

**Comment by kimrutherford** [comment]
I've fixed a few bugs and changed things so that you can get all the substrates if you don't select a "During" filter.  I decided that it's working enough that it be can released it so I've updated the main site.

The wording of the link text isn't great at the moment.  Any suggestions?  Currently it's:

  - Send all substrate genes to Advanced Search ...

or it includes the During term name if the list is filtered:

  - Send substrate genes during mitotic M phase to Advanced Search ...

**Comment by ValWood** [comment]
Looks good. One thing. When I did all cdc2 substrates

These appeared to be missing?

Systematic ID | Gene name | Product description
-- | -- | --
SPBC342.05 | crb2 | BRCT and tudor domain DNA checkpoint protein Crb2
SPBC83.18c | fic1 | contractile ring-membrane anchor Fic1
SPBC582.03 | cdc13 | G2/M B-type cyclin Cdc13
SPCC18B5.03 | wee1 | M phase inhibitor protein kinase Wee1
SPBC725.16 | res1 | MBF transcription factor complex subunit Res1
SPCC1322.12c | bub1 | mitotic spindle checkpoint kinase Bub1
SPBC646.13 | sds23 | serine/threonine protein phosphatase PP2A inhibitor Sds23/Moc1
SPAC144.13c | srw1 | substrate-specific mitotic G1 APC coactivator Srw1/Ste9

Systematic ID	Gene name	Product descriptionSorted by: Product description
[SPBC342.05](http://dev.pombase.kmr.nz/gene/SPBC342.05)	[crb2](http://dev.pombase.kmr.nz/gene/SPBC342.05)	BRCT and tudor domain DNA checkpoint protein Crb2
[SPBC83.18c](http://dev.pombase.kmr.nz/gene/SPBC83.18c)	[fic1](http://dev.pombase.kmr.nz/gene/SPBC83.18c)	contractile ring-membrane anchor Fic1
[SPBC582.03](http://dev.pombase.kmr.nz/gene/SPBC582.03)	[cdc13](http://dev.pombase.kmr.nz/gene/SPBC582.03)	G2/M B-type cyclin Cdc13
[SPCC18B5.03](http://dev.pombase.kmr.nz/gene/SPCC18B5.03)	[wee1](http://dev.pombase.kmr.nz/gene/SPCC18B5.03)	M phase inhibitor protein kinase Wee1
[SPBC725.16](http://dev.pombase.kmr.nz/gene/SPBC725.16)	[res1](http://dev.pombase.kmr.nz/gene/SPBC725.16)	MBF transcription factor complex subunit Res1
[SPCC1322.12c](http://dev.pombase.kmr.nz/gene/SPCC1322.12c)	[bub1](http://dev.pombase.kmr.nz/gene/SPCC1322.12c)	mitotic spindle checkpoint kinase Bub1
[SPBC646.13](http://dev.pombase.kmr.nz/gene/SPBC646.13)	[sds23](http://dev.pombase.kmr.nz/gene/SPBC646.13)	serine/threonine protein phosphatase PP2A inhibitor Sds23/Moc1
[SPAC144.13c](http://dev.pombase.kmr.nz/gene/SPAC144.13c)	[srw1](http://dev.pombase.kmr.nz/gene/SPAC144.13c)	substrate-specific mitotic G1 APC coactivator Srw1/Ste9

**Comment by kimrutherford** [comment]
> These appeared to be missing?

Fixed!

**Comment by ValWood** [comment]
I think you can release this, it will be useful

**Comment by ValWood** [comment]
I found a small issue.
If I search on all substrates for cdc2 and then send to "advanced search"
then send 

  | Results | Previous | Query history
-- | -- | -- | --
  | 143 |   | Substrates of cdc2 during mitotic M phase


to the ad vanced search, the M-phase substrates  query overwrites the total substrates (I wanted to see the difference)

**Comment by kimrutherford** [comment]
Thanks.  I've found and fixed that bug.  I'm re-releasing the main site now.

**Comment by ValWood** [comment]
on www advanced search
Substrates of cdc2 during mitotic M phase
still overwrites
All substrates of cdc2
(and vie versa)

**Comment by kimrutherford** [comment]
The site hasn't re-released yet.  oliver1 ran out disk space so the re-release failed.  I'm cleaning up the disk at the moment.

**Comment by kimrutherford** [comment]
The query overwriting issue is now fixed on the main site.

**Comment by kimrutherford** [comment]
I think this is done.  We can open new issues is we see any bugs.

**Comment by ValWood** [comment]
I will announce today
