### ISSUE TITLE
PMID:31072933 research spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1306]
Suppressor screening reveals common kleisin-hinge interaction in condensin and cohesin.

![kleisin](https://user-images.githubusercontent.com/7359272/58382773-7a159e00-7fc6-11e9-9e29-00618aedb291.jpg)

**Comment by ValWood** [comment]
Should be through tomorrow.

**Comment by kimrutherford** [comment]
I've added the Spotlight and I'll check everything in the morning.

**Comment by ValWood** [comment]
Xingya would like to switch to the summary figure - not sure why I didn't use this 
![new summary](https://user-images.githubusercontent.com/7359272/58415888-c371f600-8077-11e9-944a-1abc692de755.jpg)

Xingya has been very busy, 5 sessions this week, really great papers

**Comment by kimrutherford** [comment]
I've updated the image: https://www.pombase.org/archive/spotlight
You might need to shift-reload to see it.
