### ISSUE TITLE
PMID:29352077 research spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1308]
The aspect ratio isn't ideal but it's 3 stories so It's nice to include all 3

![cohesin2](https://user-images.githubusercontent.com/7359272/58384413-4bed8980-7fd9-11e9-836a-763edafb7ef3.jpg)

text
Sequencing of Suppressor DNA Mixtures Identifies Pathways That Compensate for Chromosome Segregation Defects

**Comment by ValWood** [comment]
also pushed through for tomorrow

**Comment by kimrutherford** [comment]
I've added this for the morning.

**Comment by ValWood** [comment]
these look great!
