### ISSUE TITLE
Gene expression section

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#131]
Currently it's not divided into "Qualitative Gene Expression" and "Quantitative Gene Expression".
And "Quantitative Gene Expression" isn't divided into "Protein Level" and "RNA Level".

Before I make the changes, are you happy with how the gene expression section looks on pombase.org?  Is there anything I should do differently?

**Comment by ValWood** [comment]
I think this section is OK, although I'm sure it can be a bit more asethetically pleasing. The information is all in the right place.

@Antonialock  @mah11  any additional suggestions?

**Comment by kimrutherford** [comment]
I've made some progress in getting the expression section to look more like old PomBase.  It's mostly the same except that "Qualitative Gene Expression" and "Quantitative Gene Expression" are top level sections rather than sub-heading of a "Gene expression" section.  That was easier to implement as a first pass but can change it if you prefer the old look.

The other difference is that "RNA level" and "protein level" aren't headings yet, instead there's a column for them.  I'll fix that soon.  Here's how it looks at the moment:

![screenshot 2017-01-25 10 12 47](https://cloud.githubusercontent.com/assets/90474/22267041/12e805ca-e2e7-11e6-9973-ddccae712c49.png)

**Comment by ValWood** [comment]
I don't mind separate sections for quantitative and qualitative.

Protein level and RNA level might be OK in columns too.

Anyone?

**Comment by mah11** [comment]
I don't have any problem with the way it looks now.

What might be more helpful than recreating the old look more closely is to add a compact view that hides the conditions, scale, evidence and reference by default, like the other sections that have compact and "show details" options.

**Comment by ValWood** [comment]
I like that suggestion. Let's do that.

**Comment by kimrutherford** [comment]
> What might be more helpful than recreating the old look more closely is to add a compact view

Does this need to be done for both the quantitative and the qualitative sections?  The quantitative section is less messy.

**Comment by ValWood** [comment]
If we implement I think both sections should  be  the same for consistency.
v

**Comment by mah11** [comment]
I think there's not as much need to make the qualitative display simpler, but consistency is good in its own right. So no objection to having a compact view for both.

On a slight tangent, I have spotted (and I feel slightly stupid for not noticing earlier) that the "Qualitative" and "Quantitative" box labels are the wrong way round.

**Comment by kimrutherford** [comment]
> "Qualitative" and "Quantitative" box labels are the wrong way round.

Whoops.  Fixed.

**Comment by kimrutherford** [comment]
What should shown in the compact view for the two data types?

**Comment by ValWood** [comment]
from Midori's comment above:

 hides the conditions, scale, evidence and reference by default

so, same for both would work?

**Comment by ValWood** [comment]
Removed "discuss" label...  I don't think we need to discuss on a call if others agree with comemtn above you can proceed.

**Comment by kimrutherford** [comment]
I've added a "Show details" button at the top of each of the gene expression sections.  Please let me know if it works as you'd except.

**Comment by ValWood** [comment]
I think that looks fine. It would be useful for somebody to double check as I only gave this a cursory glance... (and close if happy)

**Comment by Antonialock** [comment]
looks good to me
