### ISSUE TITLE
browser does not display introns in non coding genes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1316]
Re: [pombase #6947] Re: question regarding snu6 (SPSNRNA.06)

@Antonialock ?
I spot checked a number of non-protein coding genes with introns.
it looks like they are showing in dubious genes but not pseudogenes, retrotransposons, snRNAs, tRNAs, and other ncRNAs.

**Comment by ValWood** [comment]
UCSC bowser does not disply introns on snu6 either...apparently

**Comment by Antonialock** [comment]
I checked a number of genes in this list


Systematic ID | Gene name | Product description
-- | -- | --
SPNCRNA.05 | prl5 | antisense RNA, poly(A)-bearing (predicted)
SPNCRNA.56 | prl56 | antisense RNA (predicted)
SPNCRNA.57 | prl57 | non-coding RNA, poly(A)-bearing RNA (predicted)
SPNCRNA.445 | snoR61 | small nucleolar RNA snR61
SPSNRNA.06 | snu6 | small nuclear RNA U6
SPATRNASER.03 | sup3 | tRNA Serine
SPBC1E8.04 | Tf2-10 | retrotransposable element/transposon Tf2-type
SPCC1494.11c | Tf2-13 | retrotransposable element/transposon Tf2-type
SPBC1706.02c | wtf2 | pseudogene wtf element Wtf2
SPCC576.16c | wtf22 | pseudogene wtf element Wtf22
SPCC830.02 | wtf24 | pseudogene wtf element Wtf24
SPCC548.02c | wtf3 | pseudogene wtf element Wtf3 (no methionine)
SPAC19D5.10c |   | dubious
SPAC24B11.14 |   | dubious
SPAC9E9.01 |   | dubious
SPAC9E9.17c |   | dubious
SPAP27G11.11c |   | dubious
SPAPB24D3.05c |   | ring cleavage dioxygenase, pseudogene, single frameshift and no methionine
SPATRNALYS.04 |   | tRNA Lysine
SPBC1348.11 |   | membrane transporter, pseudogene
SPBC18E5.15 |   | pseudogene, DUF1773 family
SPBC2A9.13 |   | dubious
SPBC3D6.16 |   | dubious
SPBCPT2R1.06c |   | pseudogene
SPBPB21E7.08 |   | pseudogene
SPBTRNAARG.05 |   | tRNA Arginine
SPBTRNALEU.05 |   | tRNA Leucine
SPBTRNALEU.06 |   | tRNA Leucine
SPBTRNALEU.07 |   | tRNA Leucine
SPBTRNALYS.07 |   | tRNA Lysine
SPBTRNALYS.08 |   | tRNA Lysine
SPBTRNALYS.09 |   | tRNA Lysine
SPBTRNAMET.05 |   | tRNA Methionine
SPBTRNASER.06 |   | tRNA Serine
SPBTRNATYR.02 |   | tRNA Tyrosine
SPBTRNATYR.03 |   | tRNA Tyrosine
SPBTRNATYR.04 |   | tRNA Tyrosine
SPBTRNAVAL.05 |   | tRNA Valine
SPBTRNAVAL.07 |   | tRNA Valine
SPBTRNAVAL.08 |   | tRNA Valine
SPCC417.03 |   | dubious
SPCC4F11.05 |   | dubious
SPCP20C8.03 |   | pseudogene (predicted)
SPCTRNALEU.12 |   | tRNA Leucine
SPCTRNALEU.13 |   | tRNA Leucine
SPCTRNALYS.11 |   | tRNA Lysine
SPCTRNALYS.12 |   | tRNA Lysine
SPCTRNASER.10 |   | tRNA Serine
SPCTRNASER.13 |   | tRNA Serine
SPCTRNAVAL.09 |   | tRNA Valine
SPCTRNAVAL.10 |   | tRNA Valine
SPCTRNAVAL.12 |   | tRNA Valine
SPNCRNA.159 |   | non-coding RNA (predicted)

**Comment by kimrutherford** [comment]
I think I've fixed this with a small change to the JBrowse code.  Please let me know if you spot any cases where the splicing still isn't shown.

![jbrowse-spliced-rna-fix-1](https://user-images.githubusercontent.com/90474/58604579-f66ef080-82e8-11e9-8efd-a19f80ce8549.png)

**Comment by ValWood** [comment]
Brilliant, I'll tell Vincent
