### ISSUE TITLE
new research spotlight PMID:31116668

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1317]
I uploaded image
website/src/assets/spotlight/2019-05-31-31116668-chen-pkd2-separation-defects.png

**Comment by ValWood** [comment]
Where is that directory?

**Comment by ValWood** [comment]
ignore

**Comment by kimrutherford** [comment]
What text would you like with the image?

**Comment by ValWood** [comment]
Fission yeast TRP channel Pkd2p localizes to the cleavage furrow during cytokinesis

**Comment by kimrutherford** [comment]
I've added this Spotlight but it looks like the session for this paper hasn't been approved yet.  Should I remove the Spotlight for now?

**Comment by ValWood** [comment]
yes, just checked, it still has outstanding term requests.

**Comment by kimrutherford** [comment]
Looks like this is done.
