### ISSUE TITLE
new research spotlight PMID:30427751

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1319]
![spotlight-pombase-rsp1](https://user-images.githubusercontent.com/7359272/58762498-6af39a80-8548-11e9-93a4-8ef0ff339424.jpg)

The J-domain co-chaperone Rsp1 interacts with Mto1 to organize non-centrosomal microtubule assembly.

**Comment by ValWood** [comment]
author reorientated and relabelled the figure for spotlight.

**Comment by kimrutherford** [comment]
I've added that.
