### ISSUE TITLE
Reset "Show details" toggle when going to a different gene

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#132]
Currently if you show the details of a section of the gene page the details remain visible if you go to a different gene page.

Should we reset the toggle to just show the summaries each time?

**Comment by ValWood** [comment]
I think so.....
Anyone?

**Comment by Antonialock** [comment]
Fine by me...

**Comment by kimrutherford** [comment]
Thanks.  I'll make sure it resets the view.
