### ISSUE TITLE
Add allele pages and display allele synonyms on allele pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1325]
Add allele pages

allele synonyms should be  searchable and  displayed on allele pages

related 
https://github.com/pombase/website/issues/1294
https://github.com/pombase/website/issues/1255

**Comment by kimrutherford** [comment]
> displayed on allele pages

Is that a page per allele?  Would an "Alleles" section on the gene pages be enough?

**Comment by ValWood** [comment]
I thought we had discussed "allele pages" but it seems not.

We only discussed pages , for "all genotypes containing this allele"
https://github.com/pombase/website/issues/1294
and
 "all alleles of this gene" https://github.com/pombase/website/issues/1255


@Antonialock  @mah11  any opinions what we should do with allele synonyms?

**Comment by kimrutherford** [comment]
Allele pages wouldn't be too much work if that's what we need.  I think having a good allele search system is the important thing.

Maybe the right way to handle this is to include allele/genotype searching as part of a "faceted" search: #929?  So if you search for "pom1-KD" it could list the genotypes that include that allele and show "pom1" as a match in the gene section?  We could also do fancy stuff like showing a list of publications that mention the allele and even phenotypes terms that are annotated on the genotype.  All on one page.

**Comment by Antonialock** [comment]
allele pages seem good.

displaying the allele synonyms on these pages also sounds good

**Comment by ValWood** [comment]
Let's discuss today

We have allele pages.
But it bothers me that  we don't see all of the alleles irrespective of background.
Even if it isn't quite right logically, it's what users would expect.

For instance the paper I am currently approving uses this allele
https://www.pombase.org/genotype/mad3-KEN2-AAA-K271A,E272A,N273A-amino_acid_mutation-expression-not_assayed
but with nda3-KM311 background to invoke the checxkpoint.

In fact, I'm sure 

abolished protein ubiquitination during vegetative growth 
must use some similar background but this is not recorded.

Users (I believe) would want to see all sales irrespective of background. We can ask @JackyVH

**Comment by ValWood** [comment]
Ah I thought this ticket was about adding allele pages, I wondered why it was still open . We can discuss and then I will open a new ticket. I thought we already had a ticket about backgrounds but I can't find it.

**Comment by mah11** [comment]
> We have allele pages.

No we don't (this ticket is to add them). We have genotype pages, for single- as well as multi-allele genotypes.

> But it bothers me that we don't see all of the alleles irrespective of background.

I don't think I understand this, but background wouldn't be relevant on an allele page.

**Comment by mah11** [comment]
> Ah I thought this ticket was about adding allele pages, 

It is!!

> I wondered why it was still open

Because we haven't added allele pages yet ...
