### ISSUE TITLE
protein images

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1326]
Since it will be quite a long time until we get to work on the protein viewer, maybe we should update the protein images. The current Ensembl images look better:

pombase current
![update](https://user-images.githubusercontent.com/7359272/58944850-8514bf00-877a-11e9-94cd-39e097f48187.jpg)

ensembl current

![Ensembl](https://user-images.githubusercontent.com/7359272/58944885-95c53500-877a-11e9-8940-eddf83afd812.jpg)

**Comment by ValWood** [comment]
you cant see from these screenshots but  the "with"labels are replaced by domain names

**Comment by kimrutherford** [comment]
Unfortunately it's not straightforward: https://github.com/pombase/website/issues/479#issuecomment-320903762

We could hack something together if we needed to.

**Comment by ValWood** [comment]
OK let's leave open with low priority. I forgot about that.

**Comment by ValWood** [comment]
I'm closing this. It isn't important no point making extra work since we will have improvement down the line.
