### ISSUE TITLE
small tweak to GO display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#133]
spotted this, (klp5)

![tweak](https://cloud.githubusercontent.com/assets/7359272/22185756/1b26e022-e0e3-11e6-8d2e-cbe204cd8001.jpg)

**Comment by ValWood** [comment]
here  the bottom 2 should be

binds dis2, part of deactivation of spindle assembly checkpoint
and
binds dis2, part of mitotic sister chromatid biorientation

**Comment by kimrutherford** [comment]
It wasn't handling the case where there was an extension and a with - I should have tested that.

It's fixed now.
