### ISSUE TITLE
new research spotlight is a movie

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1338]
Nurse lab paper, I should get it through today.

I checked  the movie into  the top level directory of pombe_embl since my Drop Box appears to have expired/disappeared

It's a square shape, so not ideal. How easy is it to crop to a rectangle?

text to follow once I get the paper through....

**Comment by ValWood** [comment]
The paper is
PMID:31015410

I suggest 
Nuclear "blebbing" in Lem2 mutants from "Nuclear membrane protein Lem2 regulates nuclear size through membrane flow"

**Comment by ValWood** [comment]
The paper is through approval so   it should be in the feed toomorrow

**Comment by kimrutherford** [comment]
> It's a square shape, so not ideal. How easy is it to crop to a rectangle?

Google has told me how to crop a video so I've added the Spotlight.  Let me know if it needs fixing.  The video works well in FireFox but sometimes doesn't play in Chrome.  I don't know why.

https://www.pombase.org/archive/spotlight

There are lots Spotlights that have the front page flag on at the moment, 14-ish.  Should I trim that back a bit?

**Comment by ValWood** [comment]
That looks  great, they will be pleased with that. The paper images weren't really suitable.

can it be done by number or does it need to be done by date?
I would say the previous 8 (since don't really want to lose all of May yet)

**Comment by ValWood** [comment]
Yeah in chrome it played for me on the first visit, but now it's a still...

**Comment by ValWood** [comment]
It works  again if I open a new browser. I think that's fine.

**Comment by kimrutherford** [comment]
> can it be done by number or does it need to be done by date?

Each Spotlight has a flag to say if it should be on the front page so to remove an item from the front page we change the flag and re-release.

> I would say the previous 8 (since don't really want to lose all of May yet)

OK, I'll trim it to the most recent 8.

**Comment by kimrutherford** [comment]
> OK, I'll trim it to the most recent 8.

That's done.
