### ISSUE TITLE
Advanced query on small screens

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1343]
I was using the query builder on a laptop yesterday with small browser window.  Before querying the screen looked like:

![small-screen-toaster-1](https://user-images.githubusercontent.com/90474/60056647-ba874980-9735-11e9-8abc-2192a39654bc.png)

After querying it looked exactly the same and it took me a second to realise that I needed to scroll down to see anything.  It looked like nothing happened when I click on Submit so I thought my local development website copy was broken.  I think we should do something about this.

I'm experimenting with a 5 second message at the top of screen to let the user know that the query did something:

![small-screen-toaster-2](https://user-images.githubusercontent.com/90474/60056731-09cd7a00-9736-11e9-8d4c-556d66404140.png)

but that still doesn't tell the user where to find the query results.

Any ideas on how to improve this?

**Comment by ValWood** [comment]
Query results added to history *below* ?

(that must be a  really tiny screen with a large font?)

**Comment by kimrutherford** [comment]
> Query results added to history below ?

That's clearer I think.

> (that must be a really tiny screen with a large font?)

It's not a Mac so the resolution is quite low.

**Comment by kimrutherford** [comment]
That's on the main site now.  We can easily change the message, the colours and position.  Or remove it if it's too annoying.  Let me know.
