### ISSUE TITLE
new research spotlight PMID:30573453

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1344]
Epe1 associates with the SAGA complex to promote transcription of repeats for heterochromatin assembly.
PMID: 30573453

uploaded here
https://github.com/pombase/website/blob/master/src/assets/spotlight/2019-06-28-30573453-Bao-Epe1-associates-with-SAGA.png

**Comment by ValWood** [comment]
Nice!

**Comment by kimrutherford** [comment]
The curation and the Spotlight are on the main site now.
