### ISSUE TITLE
Display genotype-genotype style genetic interactions correctly

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1348]
Once pombase/pombase-chado#739 is implemented the web code needs changing to correctly display the new style interactions.

**Comment by ValWood** [comment]
I think either would work. I don't have a strong preference, can't see any immediate advantages/disadvantages of one over the other...are there any?

**Comment by manulera** [comment]
I think the first one (by kim) would be better in case there are phenotypes with long names.

**Comment by kimrutherford** [comment]
I have quite a lot of questions about this for when we next chat.

**Comment by kimrutherford** [comment]
> I have quite a lot of questions about this for when we next chat.

Here are some of the questions I'd like to chat about:

 - What details about the double mutant phenotype annotation do we need to show in the table?  Just the phenotype?  Do we need to show the evidence code or condition(s)?
 - Should we add an interaction table on the phenotype pages to view interactions associated the phenotype of the double mutant?  Like on the [FYPO:0000080 page](https://www.pombase.org/term/FYPO:0000080) for "ctf1Δ mmi1Δ" annotated in [PMID:32546512](https://curation.pombase.org/pombe/curs/95ec493fb8fa90cf/ro/)?
 - What about on the term page for the rescued phenotype (for example "increased acid phosphatase activity" in PMID:32546512)?  So on [the "increased acid phosphatase activity"/FYPO:0002243 page](https://www.pombase.org/term/FYPO:0002243) would it be useful to have a table of interactions where FYPO:0002243 is the rescued phenotype?
 - Should the table appear on the double mutant genotype page, like [the ctf1Δ mmi1Δ page](https://www.pombase.org/genotype/ctf1delta__mmi1delta)?
   - if the table is on the genotype page, should we hide the genotype column in the table since the double mutant genotype "ctf1Δ mmi1Δ" will be the same for all rows?
 - Should the double appear on the single allele genotype pages?  ([ctf1Δ](https://www.pombase.org/genotype/ctf1delta) and [mmi1Δ](https://www.pombase.org/genotype/mmi1delta) in the example above)
 - In Canto we have separate columns for each of the two single alleles of an interaction.  Should we do the same on the website pages?  Or follow the mock-up and have a single "genotype" column?
   - mock up with two columns: https://jsfiddle.net/osc0L7bw/

**Comment by manulera** [comment]
Let's discuss this in the call, but here some thoughts.

> What details about the double mutant phenotype annotation do we need to show in the table? Just the phenotype? Do we need to show the evidence code or condition(s)?

I think phenotype would be enough (they can always go to the phenotype annotation to see it)

> Should we add an interaction table on the phenotype pages to view interactions associated the phenotype of the double mutant? Like on the FYPO:0000080 page for "ctf1Δ mmi1Δ" annotated in PMID:32546512?
> What about on the term page for the rescued phenotype (for example "increased acid phosphatase activity" in PMID:32546512)? So on the "increased acid phosphatase activity"/FYPO:0002243 page would it be useful to have a table of interactions where FYPO:0002243 is the rescued phenotype?

Yes! I think both would be great, an interaction table, including the interactions for which the phenotype is either on the single or on the double mutant.

For example, cut7D -> monopolar spindle. It would be nice that on the monopolar spindle term page one finds that cut7D pkl1D causes phenotype suppression.

In fact, I think the single mutant is more interesting (the interactions that rescue / worsen a given phenotype). Especially because synthetic phenotype (new genotype that does not exist on either single mutant) is currently not a GI (and that would be the most interesting case, I would say).

> Should the table appear on the double mutant genotype page, like the ctf1Δ mmi1Δ page?

I would say yes, as for many cases it would show the reason of creating the mutant in the first place.

> if the table is on the genotype page, should we hide the genotype column in the table since the double mutant genotype "ctf1Δ mmi1Δ" will be the same for all rows?

Don't know

> Should the double appear on the single allele genotype pages? (ctf1Δ and mmi1Δ in the example above)

I think so

> In Canto we have separate columns for each of the two single alleles of an interaction. Should we do the same on the website pages? Or follow the mock-up and have a single "genotype" column?
> mock up with two columns: https://jsfiddle.net/osc0L7bw/

I think the double is more clear, but either is good.

**Comment by ValWood** [comment]
PMID:35011726 also has new style interactions for website  testing. In this case, I deleted the legacy ones already because the author thought they were misleading.

**Comment by kimrutherford** [comment]
Thanks for your reply Manu.  That's a good start for our Zoom call.

> I think phenotype would be enough (they can always go to the phenotype annotation to see it)

Will it be hard to find the relevant annotation if there are many annotations on the phenotype or genotype pages?

**Comment by kimrutherford** [comment]
While implementing this, I've thought of some more questions:

  - If the double mutant phenotype has an annotation extension, should that be displayed with the double mutant phenotype in the interaction table?
  - Will the rescued phenotype ever have an annotation extension?  Should it be shown in the table?
  - What about the background of double mutant?  Should that be shown in the table?

**Comment by kimrutherford** [comment]
As a stepping stone I'm going to get the new style interactions displaying in the existing genetic interaction tables.  It will just display the genes from the new interactions and ignore the genotypes and phenotypes.

That's mostly done but it needs another hour or two of work before I can release the changes.  Once it's working we can check that all the old style and the new style annotations appear in the pages.

Then I'll work on the new improved genetic interaction table that includes the genotypes and phenotypes.

**Comment by kimrutherford** [comment]
In the existing interaction tables we include columns for the gene products.  Should we include products in the new tables?  Just in the detailed view?  We might have chatted about this but I can't remember what we decided.

**Comment by kimrutherford** [comment]
> As a stepping stone I'm going to get the new style interactions displaying in the existing genetic interaction tables. It will just display the genes from the new interactions and ignore the genotypes and phenotypes.

Done!  It will be visible on Sunday morning if all goes well.

**Comment by kimrutherford** [comment]
> PMID:35011726 also has new style interactions for website testing. In this case, I deleted the legacy ones already because the author thought they were misleading.

The genetic interactions table on the page for PMID:35011726 looks like this on [my desktop](https://desktop.kmr.nz/reference/PMID:35011726).  It should be on the main site tomorrow:

![image](https://user-images.githubusercontent.com/90474/198826574-966a6b4e-5837-464d-ad59-ecbfb4fc88cd.png)

**Comment by ValWood** [comment]
>Should we include products in the new tables? Just in the detailed view? We might have chatted about this but I can't remember what we decided.

I think the suggestion is to **only** include the product for the **interacting gene** because we already know the product of the gene page, but we would need to consider the direction

**Comment by kimrutherford** [comment]
> I think the suggestion is to only include the product for the interacting gene because we already know the product of the gene page

OK, thanks.  That's what we do at the moment on the gene page.  On the publication page we show both the genes and products.

**Comment by kimrutherford** [comment]
Do we want the interface of the genotype interaction table to be similar to the other annotation tables, with `[+]`/`[-]` buttons for each interaction and "Show details ..." and "Show summary ..." buttons at the top to show/hide details of all interactions?

We'll need to decide which columns to show in the summary.  I think we discussed that a while ago but I can't remember what we decided.

**Comment by kimrutherford** [comment]
Note to myself: the directional interactions from new interface in Canto aren't being handled correctly.  The directionality is being ignored.

**Comment by kimrutherford** [comment]
> Yes! I think both would be great, an interaction table, including the interactions for which the phenotype is either on the single or on the double mutant.

On the phenotype terms page, should we separate the interactions into two tables, one for the case where the current phenotype is the double mutant phenotype of the interaction, and one for interactions where the current phenotype is the rescued phenotype?

**Comment by kimrutherford** [comment]
> On the phenotype terms page, should we separate the interactions into two tables,

We need to think about how to label the genetic interaction table(s) on the phenotype pages.

**Comment by ValWood** [comment]
> OK, thanks. That's what we do at the moment on the gene page. On the publication page we show both the genes and products.

Good point. I was only thinking about the gene pages.

**Comment by kimrutherford** [comment]
I've made some progress.  The details are now visible in my development version.  Still need to make it look nicer and implement the show/hide details buttons.

The filter for throughput needs fixing too.

Currently it's only visible on the gene and reference pages.

https://desktop.kmr.nz/reference/PMID:32546512
https://desktop.kmr.nz/gene/SPAC3G9.04

![image](https://user-images.githubusercontent.com/90474/199443552-d17d075a-e5b8-4779-a26a-f90d88a9a19b.png)

**Comment by kimrutherford** [comment]
Note to self: don't forgot to show the term extensions!

**Comment by kimrutherford** [comment]
I've fixed the throughput filtering and the extension (if any) of the double mutant phenotype is now shown.   Unfortunately showing the extension of the single allele phenotype is going to take longer because I didn't model things correctly in Chado.

![image](https://user-images.githubusercontent.com/90474/199650603-655bb987-f48d-4bae-bda3-632bc63fa35b.png)

**Comment by kimrutherford** [comment]
Now with show/hide buttons.  https://desktop.kmr.nz/reference/PMID:32546512

![image](https://user-images.githubusercontent.com/90474/199675476-1e5b7fd7-7356-41de-b3cf-b747a2f52181.png)

**Comment by manulera** [comment]
Looking good 👀👀👀.

**Comment by kimrutherford** [comment]
> Unfortunately showing the extension of the single allele phenotype is going to take longer because I didn't model things correctly in Chado.

That's mostly fixed now (on my desktop at least): https://desktop.kmr.nz/reference/PMID:32546512

I'm still doing a bit of testing before I release the changes.

We should talk about how to improve the formatting/style to make the tables more readable:

![image](https://user-images.githubusercontent.com/90474/200478940-f193ecc5-018a-44d7-93c3-15ef7ae998bd.png)

**Comment by kimrutherford** [comment]
Here's what it will look like in the morning:

![screenshot-2022-11-09_07-00](https://user-images.githubusercontent.com/90474/200641245-8baa4298-2f64-4fd3-a677-d077b844682b.png)

**Comment by ValWood** [comment]
Nice.
So is the only things to do
i) the alternating colour
ii) the reference in the legacy style over to the right
and then
iii) remove the redundancy (later)

It's really great to see the alleles and phenotypes!

**Comment by kimrutherford** [comment]
> the alternating colour

Ah, thanks.  I knew there was something else we talked about.

> the reference in the legacy style over to the right

Like this?:
![image](https://user-images.githubusercontent.com/90474/200656427-4bd184d7-7d5a-46f8-ac56-ebf8e2939256.png)

**Comment by ValWood** [comment]
Yes I think it's better to preserve the positioning of the fields.
I wonder if the headers should not show if the fields are absent. Would that be weird?

@manulera ?

**Comment by kimrutherford** [comment]
> I wonder if the headers should not show if the fields are absent. Would that be weird?

Here's a mock-up:

![image](https://user-images.githubusercontent.com/90474/200666307-68befc00-dc82-4de5-bd51-6e4422c7bf62.png)

**Comment by kimrutherford** [comment]
> i) the alternating colour

I've picked a subtle colour to start with:

![image](https://user-images.githubusercontent.com/90474/200668011-b54b89ee-a4b9-4a42-8219-2bb9580398c3.png)

**Comment by ValWood** [comment]
It isn't quite working and I don't know why!
- It might be improved if the white part did not look so much le an independent block  (it needs to be more 'joined' visually to the details above it.
- Also I think the contrast  needs to be clearer. the colours are  similar shades so they don't indicate a real transition between the datum.

Maybe we could ditch the white now we have the formatting sorted , and then sharpen the contract a little between the 2 alternating shades

**Comment by kimrutherford** [comment]
I think we should try the changes on a call because then we can tweak them while we chat.

**Comment by ValWood** [comment]
OK, good plan. It's very close!

**Comment by kimrutherford** [comment]
This is what the dev site looks like after yesterday's changes.  I've delayed the update of the main site.

Unfortunately, the single allele phenotypes have gone missing on dev.  I think I should be able to fix that without a full reload.

![image](https://user-images.githubusercontent.com/90474/200725854-7e061fdf-adfa-40cd-9216-0427b9c5e40d.png)

**Comment by kimrutherford** [comment]
> I've delayed the update of the main site.

> Unfortunately, the single allele phenotypes have gone missing on dev. I think I should be able to fix that without a full reload.

I was wrong.  The single allele phenotypes are missing from Chado.  I'm fixing that now for tonight's load.

I've updated the main site with what we have from last night's load.  But if you think it's best to wait until the single allele phenotypes are fixed I can switch back to Monday night's update.

**Comment by kimrutherford** [comment]
> I've updated the main site with what we have from last night's load.

I've changed my mind on that and the main site now has Monday night's load.  It turns out that the interactions with single allele phenotypes were missing entirely from Chado.  All fixed now and I'll check things tomorrow morning.

**Comment by kimrutherford** [comment]
>  The single allele phenotypes are missing from Chado. I'm fixing that now for tonight's load.

Fixed!  I think.  And the extensions are visible too.

https://www.pombase.org/reference/PMID:31276588

![image](https://user-images.githubusercontent.com/90474/201001065-c9913f68-c3a6-4e7f-b3fc-a789e72f904e.png)

**Comment by kimrutherford** [comment]
> I think we should try the changes on a call because then we can tweak them while we chat.

Shall we do that on Tuesday?

As far as I know the functionality is OK, we just need to improve how it looks.  Is there anything I've missed?

**Comment by ValWood** [comment]
Yes, unless I decide to travel. Still waiting  on stuff. we can def chat one day next week.

**Comment by kimrutherford** [comment]
> Yes, unless I decide to travel. Still waiting on stuff. we can def chat one day next week.

I forgot about that!  There's no problem as this isn't urgent.  If you're away for the week we can chat when you get back.

**Comment by manulera** [comment]
Sorry somehow I did not see this ticket.

Yes let's discuss next week, I agree with what @ValWood said here:

> It might be improved if the white part did not look so much like an independent block (it needs to be more 'joined' visually to the details above it.

**Comment by kimrutherford** [comment]
I've made the changes that I remember us discussing.  They'll be visible in the morning.

**Comment by kimrutherford** [comment]
This is how the reference page looks now ([PMID:32546512](https://www.pombase.org/reference/PMID:32546512)).  Could you check how it looks for you?

![image](https://user-images.githubusercontent.com/90474/203689823-87f7f357-cb8a-426b-b5ac-2d2fe8c3b5a2.png)

**Comment by kimrutherford** [comment]
I think we talked about putting the reference on one line.  Sometimes there is more than one reference: 

![image](https://user-images.githubusercontent.com/90474/203690796-0d0a340a-d143-4146-9e45-5e4c8f4e1435.png)

Does this look OK for those cases?:

![image](https://user-images.githubusercontent.com/90474/203694977-46e38414-c925-443c-9022-f68324d5b69f.png)

**Comment by kimrutherford** [comment]
This is how it would look with a mixture:

![image](https://user-images.githubusercontent.com/90474/203695332-836e4b0e-db28-4d3e-9c09-6d4de2a4d937.png)

**Comment by ValWood** [comment]
I think it looks great!
Re the references, I am not sure..... It looks OK. 
Also, it can indicate that there is something slightly different about these. I wonder if they could be labelled in some way as "legacy style"?

 note that on the main site right now, the references do not appear at all.

**Comment by kimrutherford** [comment]
> note that on the main site right now, the references do not appear at all.

Which page were you looking at?  I can see the reference here for example: https://www.pombase.org/gene/SPBC337.03

**Comment by ValWood** [comment]
ignore, I must have been on a publication page

**Comment by kimrutherford** [comment]
> Also, it can indicate that there is something slightly different about these. I wonder if they could be labelled in some way as "legacy style"?

We could add a help icon beside them if that would help:

![image](https://user-images.githubusercontent.com/90474/203874844-1c52d6e2-f5db-4a9a-a3f5-3e198cd421d8.png)

(Needs better text in the pop-up)

![image](https://user-images.githubusercontent.com/90474/203874876-54de73ae-ceaf-41ad-885b-fcd65a33c539.png)

The help icon doesn't look great if every legacy reference has one:

![image](https://user-images.githubusercontent.com/90474/203875030-0bcea8fb-710b-4d22-95c9-9af82b52eda7.png)

but it looks OK if it shows only when you mouse-over the reference section.  You'll need to imagine that my mouse pointer is somewhere in the second interaction reference here:

![image](https://user-images.githubusercontent.com/90474/203875086-b08af2d1-e5ee-4a0f-b763-c9eab2adba25.png)

**Comment by ValWood** [comment]
I'm not sure. If we do use this it should say "legacy style interaction" otherwise it implies the data is legacy.

@manulera  do you have any ideas how the 2 types can be distinguished at a glance? or  is it fine as it is?

**Comment by kimrutherford** [comment]
Would this be a better message?  Although it's slightly stating the obvious:

![image](https://user-images.githubusercontent.com/90474/203946639-28404010-c605-41bb-95e7-9e3101b7c0e3.png)

**Comment by ValWood** [comment]
Maybe 
"The genotypes/phenotypes  for this interaction are not currently curated"

i) makes it clearer they can be added
ii) for some interactions we don't report both genotypes and phenotypes

**Comment by kimrutherford** [comment]
> Maybe "The genotypes/phenotypes for this interaction are not currently curated"

I've made that change.

**Comment by ValWood** [comment]
sorry small tweak"

The genotype/phenotype details for this interaction are not currently curated

**Comment by manulera** [comment]
Sorry, I had not seen notifications from this ticket. Sounds good to have that message, and the display looks good!

**Comment by ValWood** [comment]
We are happy for now. New tickets for further changes.
