### ISSUE TITLE
research spotlight : PMID:30840879

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1349]
Text: The F-BAR Domain of Rga7 Relies on a Cooperative Mechanism of Membrane Binding with Rng10.

The aspect ratio isn't ideal, as it won't make sense to crop the top or the bottom.

![rga7_rng10](https://user-images.githubusercontent.com/7359272/60568966-13726580-9d66-11e9-941f-1ba0bd4c8ff7.jpg)

I asked the author if they could provide another but we can use this as a placeholder

**Comment by ValWood** [comment]
Paper was just approved... so should appear tomorrow

**Comment by kimrutherford** [comment]
I've added the configuration, so the Spotlight should appear tomorrow too.

**Comment by ValWood** [comment]
great. The author prepared a better aspect ratio:

[Liu et al-research spotlight.pdf](https://github.com/pombase/website/files/3358702/Liu.et.al-research.spotlight.pdf)

**Comment by kimrutherford** [comment]
> great. The author prepared a better aspect ratio:

That's on the main site now.
