### ISSUE TITLE
Change order  cell / population phenotype sections

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#135]
I think I preferred seeing the population phenotype section before the cell phenotype section.

If the gene is well curated then the population phenotype section is more likely to contain fewer and more 'general' annotations e.g. cdc2

Or maybe it's just because I'm used to it...thoughts?

**Comment by ValWood** [comment]
I prefer population first too.

**Comment by mah11** [comment]
no preference, so no objection to switching back

**Comment by kimrutherford** [comment]
I've swapped the section order.  As usual, you'll need to reload to see the change.
