### ISSUE TITLE
decrease font size?

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1358]
The text

"This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types."

looks a bit big?

<img width="1347" alt="Screenshot 2019-07-10 at 17 45 59" src="https://user-images.githubusercontent.com/12727506/60988026-b9ac0580-a33a-11e9-9e75-940869db7176.png">

**Comment by kimrutherford** [comment]
Maybe.  I think those messages should be quite prominent in some way because apart from the publication title they are the most useful things on the page.

**Comment by Antonialock** [comment]
but in this case it detracts from the link to JBrowse? Maybe remove if there is "data" incorporated from the paper whether it be tracks, or annotation

**Comment by ValWood** [comment]
I see what you mean. It is even slightly bogger. Slightly smaller would be better, but at least the same size otherwise it looks odd.

MAybe if there is a JBowse track we can just omit the message?

**Comment by kimrutherford** [comment]
> MAybe if there is a JBowse track we can just omit the message?

I vote for keeping the message in some form, just so it's clear.

It's going to look different once we implement Antonia's suggestion: https://github.com/pombase/website/issues/801#issuecomment-492152992

In the meantime I've increase the size of the JBrowse text.  It's now slightly bigger than the no annotations message.

**Comment by Antonialock** [comment]
Thanks
