### ISSUE TITLE
Add a disease slim column to QuiLT?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1360]
I can't remember if we talked about this but should we add a disease column to QuiLT once we're happy with the disease slim?

**Comment by ValWood** [comment]
I think we talked about it. We should do but we might do that when we think of a way to not restrict to a single category for these mutlicategory things (like process).

I'm not totally happy that we use a hierarchy for these, but it would be really hard to do any sort of precedence for disease....

**Comment by kimrutherford** [comment]
> We should do but we might do that when we think of a way to not restrict to a single category
> for these mutlicategory things

That make sense.  That's another thing to chat about when the current big jobs are under control.

**Comment by kimrutherford** [comment]
One way to handle this is to let the user add a column for a slim term which just has two colours (present/absent or yes/no) the shows genes annotated with that term.  It could act a bit like the ortholog and TM domain columns.

The would work for any slim term and (maybe later) potentially for any term at all.  It would be reasonable to allow adding more than one term column this way.

This is all slightly hard work so wouldn't be a quick job.

**Comment by ValWood** [comment]
Yeah I would like to put this on hold and revisit. 
We should chat about this some time to see  what ideas we can come up with  to improve.

**Comment by ValWood** [comment]
Closing, because what we can di here is covered by
https://github.com/pombase/website/issues/879
