### ISSUE TITLE
news item about slack

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1367]
Title “join  the fission yeast conversations you care about on Slack”
The vibrant fission yeast community now has a Slack channel. Slack provides a  forum to follow the conversations you care about. Message colleagues privately, or in groups, ask questions, post responses. All archived and searchable….

use the slack icon as an image

Also I told Gutam we would add a slack icon to the front page (we can get rid of Google groups)

**Comment by kimrutherford** [comment]
I've added the news item and icon.  I added a link to the sign up link in the news item.  The icon is a link to the sign-up page too.  Let me know if that doesn't make sense.

**Comment by ValWood** [comment]
link to flyer broken

**Comment by kimrutherford** [comment]
> link to flyer broken

Ah, thanks.  It's fixed now.
