### ISSUE TITLE
rad21 cleavage site

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1376]
the residue does not display:

/controlled_curation="term=sequence feature, cleavage site; residue=R231-D232; db_xref=PMID:15329725; date=20100125"
/controlled_curation="term=sequence feature, cleavage site; residue=R179-N180; db_xref=PMID:15329725; date=20100125"

**Comment by kimrutherford** [comment]
Fixed!

I've added a "Residue" column to the "Protein sequence feature" table: https://www.pombase.org/reference/PMID:15329725
