### ISSUE TITLE
Count out of line for cdc5

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1378]
![count-bug-1](https://user-images.githubusercontent.com/90474/61993134-4553bf00-b0bb-11e9-8072-93af2a11453a.png)

**Comment by kimrutherford** [comment]
I'm not sure how common this is but the count column is wonky in the modification section on the cdc5 page.  I haven't seen this on other pages.  If you spot any other cases please let me know.

(Not the world's biggest problem but it annoys me)

**Comment by Antonialock** [comment]
I've never seen that (though I usually only look at the count column for GO annotations or protein domains)

cdc5 protein mod page doesn't look wonky to me...I've tried making the displayed page wider and narrower than image shown and it's still not wonky (chrome)

![Screenshot 2019-07-28 at 10 04 23](https://user-images.githubusercontent.com/12727506/62004622-41f21f00-b11f-11e9-870d-05aecba9be7e.png)

**Comment by kimrutherford** [comment]
> cdc5 protein mod section doesn't look wonky to me...I've tried making the displayed page wider
> and narrower than image shown and it's still not wonky (chrome)

Thanks for checking.  I have a wide screen which might make the difference.

I'm going to ignore this unless we see it elsewhere.

**Comment by ValWood** [comment]
I have never seen it.....

**Comment by Antonialock** [comment]
aha yes, I have a 1920 x 1200 screen but rarely  maximise my browser

I see it too when I do

![Screenshot 2019-08-01 at 19 58 34](https://user-images.githubusercontent.com/12727506/62319906-e6b18b00-b496-11e9-99b6-908eda2cfd06.png)

**Comment by kimrutherford** [comment]
> aha yes, I have a 1920 x 1200 screen but rarely maximise my browser

Thanks for checking.  I'm glad it's not just me.  :-)

**Comment by kimrutherford** [comment]
I can't reproduce this now so I'm going to pretend that it was a temporary browser bug.

**Comment by Antonialock** [comment]
I still see it 

<img width="1654" alt="Screenshot 2019-10-28 at 09 21 57" src="https://user-images.githubusercontent.com/12727506/67666806-76ff4f00-f964-11e9-8f5e-1db7528eb0f1.png">

**Comment by kimrutherford** [comment]
> I still see it

Thanks for checking.  Is that in Firefox?  I can't trigger the problem no matter what I try.  Frustrating!

**Comment by ValWood** [comment]
Has this bug gone away?

**Comment by kimrutherford** [comment]
> Has this bug gone away? (I don't see it)

I can't reproduce the problem on the cdc5 page, but I can with Antonia's suggestion of cdc2.

Now I can reproduce it I might be able to fix it.  :-)

**Comment by kimrutherford** [comment]
> Now I can reproduce it I might be able to fix it.

And now I can't reproduce it.  So I give up.  It's not a big issue so I'll close this.

**Comment by ValWood** [comment]
yes, it never bothered me....
