### ISSUE TITLE
term list  display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#138]
currently looks like this:
![change view](https://cloud.githubusercontent.com/assets/7359272/22405011/a9c33e8e-e633-11e6-9fd5-9798582fe59e.jpg)

but I don't think there should be any collapsing on this page, we should just present the list:

**Comment by ValWood** [comment]
scrub the above:

From discussion, instead:
- [ ]  1. merge current landing page with "all annotation view"
- [ ]  2.  in "all annotation view" (this will become the current landing page)
 display gene name & product, and hide extensions 
- [ ]  3. Make extensions  visible under show details view

**Comment by kimrutherford** [comment]
> display gene name & product

I can't remember what we decided to do about multiple gene phenotypes in this summary.  How should multiple products be displayed?

**Comment by kimrutherford** [comment]
This is somewhat done, but not for phenotypes until we talk about how genotypes should be displayed.

Here's an example:
  http://pombase2.bioinformatics.nz/term/GO%3A0010389

As you can see it's not very elegant.  Any suggested about the formatting?

There are two problems that I've seen that I'm going to fix now: the lines should be sorted by gene and need to remove duplicate genes.

**Comment by kimrutherford** [comment]
> the lines should be sorted by gene

That bit is done.

**Comment by kimrutherford** [comment]
> I can't remember what we decided to do about multiple gene phenotypes in this summary.
> How should multiple products be displayed?

I think that is covered by #140 so I'll close this.
