### ISSUE TITLE
new spotlight for PMID:31285271

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1383]
I uploaded a new spotlight 
https://github.com/pombase/website/blob/master/src/assets/spotlight/2019-07-31-31285271-Asc1-stabilizes-the-interaction-between-eIF3a-and-Rps0A-uS2-for-protein-synthesis.png

PMID
31285271

text
Asc1 stabilizes the interaction between eIF3a and Rps0A/uS2 for protein synthesis

**Comment by kimrutherford** [comment]
The Spotlight is ready to go.  Could you let me know when the session is approved?

**Comment by ValWood** [comment]
asc1 inferred-> published

**Comment by kimrutherford** [comment]
> asc1 inferred-> published

What has been published?

**Comment by mah11** [comment]
> >  asc1 inferred-> published
> 
> What has been published?

I wouldn't worry about this - it looks like that message is really a note-to-self (i.e. curation tracker fodder).

**Comment by ValWood** [comment]
> asc1 inferred-> published
done

**Comment by kimrutherford** [comment]
I'm reopening this issue because the Spotlight isn't ready yet.

**Comment by kimrutherford** [comment]
That's live now.
