### ISSUE TITLE
problems connecting to ftp site

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1384]
when I click on the  link
  ftp://ftp.pombase.org/archive/Intron_Data/OLD/

i get
![ftp1](https://user-images.githubusercontent.com/7359272/62284163-0753f380-b44b-11e9-9767-e00e432ae78e.jpg)

if I select guest here, I get

![ftp2](https://user-images.githubusercontent.com/7359272/62284204-176bd300-b44b-11e9-94b7-9c5770f1c440.jpg)

**Comment by mah11** [comment]
I can't reproduce the problem - connecting as "guest" works for me.

If it's specific to the intron link, you might have to reload the page to pick up the link fix Kim did a few hours ago.

**Comment by kimrutherford** [comment]
Val, is that from Firefox?

**Comment by ValWood** [comment]
chrome, but Midori was probably correct, it works for me now...

**Comment by kimrutherford** [comment]
> chrome, but Midori was probably correct, it works for me now...

It's annoying that it puts a dialog box in your face before letting you in.  Maybe that's a Mac thing?  I don't see that with Firefox or Chrome on Linux.

**Comment by ValWood** [comment]
It's odd because it doesn't happen all the time...
