### ISSUE TITLE
link faq item directly to browser track

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1385]
I think we can do this now ? @Antonialock / @mah11 
https://www.pombase.org/faq/how-can-i-find-intron-branch-sites

**Comment by mah11** [comment]
What would the link be?

**Comment by ValWood** [comment]
https://www.pombase.org/jbrowse/?loc=I%3A4183644..4203644&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CDNA%20sequence%2CIntron%20Branch%20Points%20-%20Bitton%20et%20al.%20(2014)&highlight=

**Comment by Antonialock** [comment]
I'll update to this link
https://www.pombase.org/jbrowse/?loc=I%3A704338..724338&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CDNA%20sequence%2CIntron%20Branch%20Points%20-%20Bitton%20et%20al.%20(2014)&tracklist=1&nav=1&overview=1&highlight=

it shows introns :-)

**Comment by Antonialock** [comment]
done

**Comment by ValWood** [comment]
Thanks!
