### ISSUE TITLE
All "misc" comments are not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1387]
SPAC212.08c

/controlled_curation="term=genome organization, telomeric
FT duplication; cv=genome_org; date=19700101"
FT /controlled_curation="term=sequence feature, N-terminal
FT signal sequence; qualifier=predicted; cv=sequence_feature;
FT date=19700101"

appears, but

FT /controlled_curation="term=misc functional group, cell
FT surface glycoprotein; cv=m_f_g; date=20100104"

doesn't.

I wonder if there are any others which don't display.

Is it easy to find which ones we do display. I'm not even sure that all misc comments have a "CV". I think some might be just "misc,"

**Comment by ValWood** [comment]
Yep the ones without a "cv" type are

  /controlled_curation="term=misc, repeat expansion SQRSQRS;
FT                   date=20140823"
FT                   /gene="SPAC212.04c"

these do display...

**Comment by kimrutherford** [comment]
The annotation from the "misc" CV are displayed but the "m_f_g" CV annotations aren't configured.  It's very quick to add the m_f_g annotations if you're happy for them to be in a separate section on the gene pages.  Each section corresponds to one CV in the current code so displaying annotations from two CVs in the same section would require a code change.

**Comment by ValWood** [comment]
Yes I think we can add. We can decide what to do with them for real later, but it is useful info.
I think there are only a few
histone chaperon
glycoprotein
nucleocytoplasmic shuttling protein.

We can remove them if another way to capture crops up....

**Comment by kimrutherford** [comment]
How's this?:

![misc-1](https://user-images.githubusercontent.com/90474/62362015-3c0d9b00-b570-11e9-828d-6bc7169e4977.png)

**Comment by ValWood** [comment]
great!

**Comment by kimrutherford** [comment]
That's live now: https://www.pombase.org/gene/SPCC63.02c

Let me know if you spot any problems.
