### ISSUE TITLE
"modified residue" extensions duplicated

### ISSUE THREAD

**Issue by mah11** [pombase/website#1389]
If a phenotype annotation has a "modified residue" extension, it shows up twice in the detailed view, as in this example from the cds1 gene page:

![Screen Shot 2019-08-09 at 2 22 41 PM](https://user-images.githubusercontent.com/5196259/62782067-56380380-bab1-11e9-8d03-cdd40ee45df0.png)

All page types are affected. Summary views are OK.

**Comment by kimrutherford** [comment]
I'll fix that.  It's a problem here too: https://www.pombase.org/term/FYPO:0002098

**Comment by kimrutherford** [comment]
That's fixed now.  I forgot to check the phenotype annotations.
