### ISSUE TITLE
With/from field

### ISSUE THREAD

**Issue by ValWood** [pombase/website#139]
- [x] Is currently called "with" - but is "with/from"
- [ ]  Lots of  entries in this field (Database IDs, GO terms etc) currently don't hyperlink

**Comment by ValWood** [comment]
To be honest I would not be fussed if we did not display this field as a column, but just made it show in a pop up if you mouse over the evidence.
It isn't critical biological information (except for the IPIs and we  treat those as extensions anyway).

Something to consider (maybe for the future as these evidence codes will become less utilized and then the column will be a bigger waste of space)

Q Should we not show the with column if these is no with field data to display?
Or would that be a bit inconsistent?

**Comment by ValWood** [comment]
How do people feel about this....(SGD do it)

Saves quite a lot of space:

![space saver](https://cloud.githubusercontent.com/assets/7359272/22487731/70582e78-e806-11e6-94db-1b0851bcd667.jpg)

**Comment by Antonialock** [comment]
looks fine to me

**Comment by kimrutherford** [comment]
> How do people feel about this....(SGD do it)

It's an easy change so I've done that.  It's easy to change back if we don't like it.

**Comment by ValWood** [comment]
I don't see the change despite much  alt control reload thingummying

**Comment by ValWood** [comment]
Fuck......I'm editing my comments for grammatical errors today. Somebody- please stop me wasting time....what is wrong with me?.... I have never done this before (maybe y'all didn't even notice?).

**Comment by ValWood** [comment]
I mean the corrections, not the errors (obviously....)

**Comment by ValWood** [comment]
I'm reading before sending. How did I ever not do this? (I think its the yoga....).

**Comment by kimrutherford** [comment]
> I don't see the change despite much alt-control-reload thingummying

That's odd.  

It looks like this to me (on http://pombase2.bioinformatics.nz/gene/SPBC11B10.09 ):

<img width="125" alt="screenshot 2017-02-02 11 50 25" src="https://cloud.githubusercontent.com/assets/90474/22529873/0861b710-e93e-11e6-9594-d1327ab98ba4.png">

**Comment by ValWood** [comment]
Got it. You implemented for BP only. Only needs propagating. Can then close.

V

**Comment by kimrutherford** [comment]
> Got it. You implemented for BP only. Only needs propagating. Can then close.

I should be changed everywhere.  Can you let me know an example where it isn't working?

**Comment by mah11** [comment]
For me the whole thing is acting buggy now. I'm going to open a new ticket, because the problems I'm having aren't restricted to the with/from display (which I did see briefly yesterday - it looks good).

**Comment by ValWood** [comment]
I have another small space saving suggestion, new ticket...
