### ISSUE TITLE
New website features, for NAR paper

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1392]
Just thought we could have a ticket to collate implemented improvements, for the next NAR paper

 - QLT
 - Graphical abstracts on publication pages
 - Methods and review papers loaded
 - Customizable download of gene list (ability to download orthologs, and starts and ends of genes, FASTA nucleotide and proteien seequence)
 - Ability to filter on HTP/LTP annotations

**Comment by ValWood** [comment]
Wow you are ahead ;)

It would also be nice to have one big thing (protein viewer or pathway representation), but that may mean punting to  2021 instead of 2020...

**Comment by ValWood** [comment]
I think we also have a ticket for this on the curation tracker

**Comment by ValWood** [comment]
~Should we move this . to a Goolgle doc?

**Comment by mah11** [comment]
closing because this does not describe any work to be done on the website
