### ISSUE TITLE
Move UTRs out of embl files

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1396]
Rhind used a greedy algorithm so our UTRs are too long. 

1. Take out the uncharacterized ones from the embl files
2. Leave the characterized ones (from small scale studies)
3. Provide Rhind, Lanterman etc UTR predictions on tracks in genome browser.

@ValWood  does that sound right?

**Comment by ValWood** [comment]
pending decision
https://github.com/pombase/curation/issues/2806
