### ISSUE TITLE
Change input_for label on gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#14]
Here it might be nicer to have
"transcribed by"
and "ubiquitinated by"
if we can.

![better](https://cloud.githubusercontent.com/assets/7359272/16592192/5b3577e6-42d7-11e6-8e85-10432c9bf2db.jpg)

I think Mark does some stuff t change the display labels in the existing code. Eventually this should be a curator maintained config file like Canto.

**Comment by ValWood** [comment]
@mah11  is there a config file for this.
Is this the same  question I always ask?
Or is that about a different config file?

If this is not configurable at present add pls add "discuss".

**Comment by kimrutherford** [comment]
The configuration for extensions and labels is here:
  pombe-embl/supporting_files/chado-json-config.yaml

When should it be "transcribed by" and when should it be "ubiquitinated by"?

**Comment by ValWood** [comment]
Can anyone help here?
We just need to change the config file to allow more detailed display labels?

**Comment by mah11** [comment]
That's correct. I can do the config file changes if you put more specifics here about what display text  you want to appear for which GO terms in both "forward" and "target of" directions. (That's essentially what Kim was asking for with "When should it be "transcribed by" and when should it be "ubiquitinated by"?".)

**Comment by ValWood** [comment]
I guess the info is here (with different display labels as appropriate....?)

/Users/val/Desktop/pombe-embl/supporting_files/annotation_ex_config

except  at present  "ubiquitinated by" would be plain "modified by" because I haven't configured that deeply yet in this branch...

Ideally we would do this in a way that we didn't  need to maintain 2 config files?

**Comment by mah11** [comment]
Right now there are two config files/sets of files because one is for Canto and the other is for the web page display. Kim will have to comment on whether it's code-riffically* feasible and sensible to merge them.

> pombe-embl/supporting_files/annotation_ex_config

Only the "forward" direction is in the files in that directory, because Canto has no need to display the reciprocal ("target of") text. Reciprocal display text is in the file Kim indicated - pombe-embl/supporting_files/chado-json-config.yaml



*yeah, I just made that word up

**Comment by ValWood** [comment]
hmm, of course, it probably makes sense to have 2 files then....
pinta to keep them aligned but not beyond us.
Let's see what Kim says...

**Comment by mah11** [comment]
The admin vs. user distinction is also only relevant to Canto.

**Comment by kimrutherford** [comment]
> Let's see what Kim says...

I think we can merge them but I'd like to put it off.  In the Canto file there are domain restrictions like "FYPO:0001985-FYPO:0005448&FYPO:0005449" which make it fiddly.

**Comment by ValWood** [comment]
No problem to wait. We will keep separate files for now. 
In the whole scheme of things we have far less duplication of anything, than anyone, for anything ;)

**Comment by ValWood** [comment]
so for example if the input term is

DNA-binding transcription activator activity (GO:0001216)
or one of its descendants the relation would be "transcribed by"

If
DNA-binding transcription activator activity (GO:0001216)
or one of its descendants the relation would be "ubiquitinated by"

protein kinase activity (GO:0004672)
or one of its descendants the relation would be "phosphorylated by"

phosphoprotein phosphatase activity (GO:0004721)
or one of its descendants the relation would be "dephosphorylated by"

This would  cover a lot and be enough to get it working.
Then we can  extend on an ad-hoc basis. Is this what you needed? or do you need more?

**Comment by mah11** [comment]
@ValWood 
> DNA-binding transcription activator activity (GO:0001216)
> or one of its descendants the relation would be "ubiquitinated by"

what's the correct GO term for this one?

**Comment by mah11** [comment]
@kimrutherford question:

Right now the website config has this for "catalytic activity":

    {
      "rel_name": "has_input",
      "if_descendant_of": "GO:0003824",
      "display_name": "has substrate",
      "reciprocal_display": "substrate of"
    },

Val has some more specific display suggestions for some, but not (yet) all, descendants of GO:0003824. What will happen if I add them to the config? E.g. will a phosphatase substrate get both "substrate of (kinase)" and "dephosphorylated by (kinase)" or will it be clever enough not to include the less specific one?

Do we (read: you, lucky ol' you) need to use the "FYPO:0001985-FYPO:0005448&FYPO:0005449"-style syntax for the website config too?

Happy to chat if talking you through it will help.

**Comment by ValWood** [comment]
what's the correct GO term for this one?
corrected above

**Comment by kimrutherford** [comment]
> What will happen if I add them to the config?

It currently uses the first configuration that matches.  So if you put the more specific ones first it should work.

**Comment by mah11** [comment]
> It currently uses the first configuration that matches. So if you put the more specific ones first it should work.

Cool. I've added a bunch of new entries, so I'll close this. If I've botched it, fix or reopen for me; for new entries open a new ticket.

> DNA-binding transcription activator activity (GO:0001216)
> or one of its descendants the relation would be "transcribed by"

Well, no, actually, it's always transcribed by RNA polymerase, so I used "transcription activated by" for this one.
