### ISSUE TITLE
publication pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#140]
We have a "gene"   column n the "publication pages"
![add gene](https://cloud.githubusercontent.com/assets/7359272/22405100/21aa8b54-e635-11e6-88ef-c0df92313663.jpg)

**Comment by kimrutherford** [comment]
> The gene should be the first column in this view

I think that's going to look odd, especially when there are extensions.  Here is before and after:

![screenshot 2017-02-07 11 56 24](https://cloud.githubusercontent.com/assets/90474/22670274/642c63cc-ed2d-11e6-9be0-34ea00490661.png)
![screenshot 2017-02-07 11 56 24-new](https://cloud.githubusercontent.com/assets/90474/22670283/6a11a072-ed2d-11e6-9c4a-8cda666c1907.png)

**Comment by kimrutherford** [comment]
> The "gene" should appear in the "default view" 

We need to decide how that should interact with the extension display.  For example, here:
﻿﻿http://pombase2.bioinformatics.nz/reference/PMID%3A23695302

in the summary/default view we have:
  regulates urg1 , urg2 , urg3 , ura6 , SPAC1399.04c , SPBC3H7.05c

We'd need to split that onto two lines because the "regulates SPBC3H7.05c" is for a different gene (toe2) than the other extensions.

Would it be simpler to just show the full view on the publication pages like Antonia suggests in #146?

![screenshot 2017-02-07 12 06 04](https://cloud.githubusercontent.com/assets/90474/22670424/f37b656e-ed2d-11e6-8a08-118af381946e.png)

**Comment by ValWood** [comment]
lets do this one...

**Comment by ValWood** [comment]
OK, 
> I think that's going to look odd, especially when there are extensions. Here is before and after:

I think that looks OK. Why odd?


For the second example, the annotation is quite difficult to determine unless the gene the annotation is annotated to is primary..

**Comment by ValWood** [comment]
I'm looking at this and it won't really make sense unless gene is the first column int he default view.
The other decision is how to group stuff on this page (within section).

By gene, or by annotation type....

**Comment by ValWood** [comment]
Decisions from call:

- [ ] 1.  The gene needs to be in the first column in summary view (and details)
- [ ] 2. The details view shows extension
- [ ] 3. phenotype same except show genotype (extensions evidence conditions in detailed view)
- [ ] 4. For first pass just have term at top
- [ ] 5. We recognise that there is a problem with genotype / gene name display

**Comment by mah11** [comment]
In case it's not clear from the preceding comment, the summary view should show only genes (or genotype) and term names. Everything else appears only in the detailed view.

**Comment by kimrutherford** [comment]
This is done for genes(*), but not for genotypes.  I'll do the genotype changes soon.

(*) the gene names are sometimes duplicated - I'll fix that too.

**Comment by kimrutherford** [comment]
> I'll do the genotype changes soon.

I've moved the genotype to the first column on the term and on the reference pages.  There are a lot of horizontal lines that don't look good.  The easiest fix is to remove them.  Let me know if you have a better suggestion.

**Comment by kimrutherford** [comment]
I forgot about the product.  Should that be shown in the summary?  The full view?  Both?  Should be be shown on the term pages and on the reference pages?

**Comment by kimrutherford** [comment]
Should we close this in favour of the new issue #175?

**Comment by ValWood** [comment]
yes, i think most here is done or is new issues, which can be new tickets...
