### ISSUE TITLE
welcome pack

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1404]
Create a "welcome pack" pdf containing

- link to pombelist/slack/susan forsburgs page
- link to documentation/faq
- quick how to's for stuff e.g. how to do a sequence download, how to use the query builder, jbrowse (containing links to relevant faq/docs)
- quick intro to gene/annotation pages
- intro to community curation
- introductory references (eg primer)

**Comment by ValWood** [comment]
We should include this!
https://jcs.biologists.org/content/joces/121/11/1771.full.pdf

**Comment by ValWood** [comment]
This was a nice idea of @Antonialock , I thought we even started to gather the materials together somewhere. It probably doesn't need to be a pdf but a new starter page with all of the useful materials gathered together?

Any way we should start a web page with  a list links that a lab head can point new starters to.

How to join pombelist
https://lists.cam.ac.uk/sympa/suboptions/ucam-pombelist

Slack

Publication
include pombase papers, 
gentics primer,  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4596657/
history https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4896181/
Antonias book chapter

Tutorials
https://www.pombase.org/documentation/JBrowse_quick_start

https://www.pombase.org/faq

https://www.pombase.org/community/fission-yeast-community-curation-project (page needs improving)

Importance of citing PomBAse https://www.pombase.org/about/citing-pombase

**Comment by ValWood** [comment]
@manulera you can announce this and close?
