### ISSUE TITLE
our slack link (icon)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1405]
gives:

https://spombe.slack.com/join/shared_invite/enQtNjk3MjEwODg2ODE2LWMxY2I1Y2ZjNjE3NTYzNGQ2OTYzMjM5NDVhNzQwOGRlY2RlNWQzYmYxYWE2MzNiMmMwNDg0OGVlMzM1ZmVkNmM

Which link should we use instead?

**Comment by ValWood** [comment]
Thank you. I searched and could not find what to link to. This is more sensible.

**Comment by kimrutherford** [comment]
I've changed the icon link.
