### ISSUE TITLE
Add documentation for adding a new Spotlight or Explore item

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1407]

**Comment by kimrutherford** [comment]
I've started work on this: https://github.com/pombase/website/wiki/Adding-a-Spotlight

**Comment by ValWood** [comment]
Should I test this with the next spotlight?

**Comment by kimrutherford** [comment]
> Should I test this with the next spotlight?

It would be good if you could give it a go but maybe we should wait until we decide on changing the image sizes.

**Comment by ValWood** [comment]
close?

**Comment by kimrutherford** [comment]
Yep, we can close this.  We can improve the documentation as we go.
