### ISSUE TITLE
new drug / target

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1408]
mycophenolic acid
inhibits IMP dehydrogenase and thus limits cellular GTP pools (10).
MPA exacerbates growth impairment in mutants defective in transcript elongation (8, 11, 50), although the precise mechanism of this effect is unknown (34)

10.is
 Escobar-Henriques M, Balguerie A, Monribot C, Boucherie H, Daig- nan-Fornier B. 2001. Proteome analysis and morphological studies reveal multiple effects of the immunosuppressive drug mycophenolic acid specifically resulting from guanylic nucleotide depletion. J. Biol. Chem. 276:
46237– 46242.

we need to make this page/data more visible...

**Comment by ValWood** [comment]
from PMID:22508988 but the primary  paper is the one above. I don't know what we record

**Comment by mah11** [comment]
a lot of this looks like aspects of curating this entry, and maybe a bit on curating the drug target inventory more generally ... complements the pile of website content in the curation ticket, I guess :P

**Comment by ValWood** [comment]
see
https://github.com/pombase/curation/issues/2593
