### ISSUE TITLE
position of "count" column

### ISSUE THREAD

**Issue by ValWood** [pombase/website#141]
Would it be a bit more aesthetically pleasing to have the count column positioned to the far right?

Did we discuss this already?

**Comment by kimrutherford** [comment]
> Would it be a bit more aesthetically pleasing to have the count column positioned to the far right?

Do you mean in the summary view?  I've made that change.  Let me know if it's what you were thinking of.

**Comment by ValWood** [comment]
Yep....


I think it makes sense to tuck this over at the far right of the page. Anyone disagree?

We will lose a lot of the space once the menu bar is in place...if that worries people.
Personally I think it looks neater, but I might be just used to the old pages....
