### ISSUE TITLE
news item

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1410]
Please add a suitable version of this announcment to the news feed.

We could use the WT icon maybe?

We are pleased to announce that the recent PomBase application for continued Wellcome Trust funding was successful.  Although the grant was not fully funded, we are confident that we can cover the shortfall by small grants for stand-alone projects and collaborations.  We would like to thank the pombe community for their support with the application, and the Wellcome Trust for their continuous funding.  We look forward to supporting your research until 2025 (and beyond).

**Comment by kimrutherford** [comment]
> We could use the WT icon maybe?

I did that.  It looks OK.

**Comment by ValWood** [comment]
Actually sorry to be a pain. I mean to edit this ticket. We should use the PomBase icon for this...

**Comment by kimrutherford** [comment]
No problem, I've changed the icon.
