### ISSUE TITLE
pending spotlight zinc repression

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1413]
A new TF binding site (Loz1 response element)  for zinc repression.

PMID:31515876

![zinc](https://user-images.githubusercontent.com/7359272/66236109-8551a680-e6e9-11e9-9a09-72940a4a6c16.jpg)

**Comment by kimrutherford** [comment]
I've scaled the image and added it to git.

**Comment by ValWood** [comment]
This paper should go live tomorrow  so this spotlight can be made live.

**Comment by kimrutherford** [comment]
The Spotlight is live but it looks like the curation session didn't make it into last night's load.

**Comment by ValWood** [comment]
I see the paper?
https://www.pombase.org/reference/PMID:31515876

**Comment by kimrutherford** [comment]
> I see the paper?

I must have been looking at the wrong page.
