### ISSUE TITLE
new spotlight meiotic spb separation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1414]
![spotlight](https://user-images.githubusercontent.com/7359272/66236153-a1554800-e6e9-11e9-9f39-519242b1b0ca.jpg)

**Comment by ValWood** [comment]
Kinetochore-mediated outward force promotes spindle pole separation


PMID:31532702
--

**Comment by ValWood** [comment]
https://twitter.com/intent/retweet?tweet_id=1174834440758943744
https://twitter.com/intent/retweet?tweet_id=1174657663373729793

**Comment by kimrutherford** [comment]
I've scaled the image and added it to git.

**Comment by ValWood** [comment]
This one will  is through (only a few minutes ago so I guess I missed the update tonight and this will go live on Wednesday?) . Could the spotlight be activated on Wednesday too.?

**Comment by kimrutherford** [comment]
It looks like the curation session annotations are in Chado: https://www.pombase.org/reference/PMID:31532702

So I've added the Spotlight.
