### ISSUE TITLE
Make config editing friendlier (especially for browser track descriptions)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1416]
From Antonia:

So, I wonder if we can make the environment in which to update track descriptions easier? 

When I click on 'edit' I see this:
<img width="1605" alt="Screenshot 2019-10-05 at 11 30 52" src="https://user-images.githubusercontent.com/90474/66275234-1475de80-e8e3-11e9-9ec7-04635b603889.png">
The editing window doesn't fill the screen left to right, so you need to do a lot of scrolling left and right.

I can do small changes like this but because everything is displayed in CSV format it is really difficult to make sense of where you are within the table. 

Therefore, I copied everything into excel, and when I was happy with my changes I exported as CSV and pasted that in. I then did some further changes within the github interface.

Is there a way to make editing this friendlier? I can keep pasting into excel and then "If you need to check the syntax you can paste them here and click "Validate JSON": https://jsonlint.com/ "
But if there is an easier way that you know of then any tips would be helpful?

(it would be useful for updating other tables as well  - but the other tables we have are much smaller so not as much of a pain)

**Comment by ValWood** [comment]
@kimrutherford  any ideas for this?

Ideally users will be able to supply this data  via a web form, and upload the data to the ftp site
https://github.com/pombase/website/issues/1246
  so  maybe we need to move towards this?

**Comment by kimrutherford** [comment]
> So, I wonder if we can make the environment in which to update track descriptions easier?

Probably the quickest improvement for editing the config files is to use Git to get local copies.  There are quite a few free Mac Git applications: https://git-scm.com/download/gui/mac

For editing the JSON config file, some editors show JSON syntax errors as you type.  VS Code is an example: https://code.visualstudio.com/  (that's what I use).

> Ideally users will be able to supply this data via a web form, and upload the data to the ftp site

Rather than implementing a system ourselves, we could use Google Forms to collect the data: https://www.google.com/forms/about/

Uploading via FTP would be a bit of work.  I'd rather just suggest that users use something like Firefox Send (https://send.firefox.com/) so we can avoid maintaining an FTP upload system.

**Comment by ValWood** [comment]
This sounds like a plan.
Good idea to make a Google form- I will assign @mah11 to that part

**Comment by mah11** [comment]
superseded by the spreadsheet template that's in the works

reopen this or do a new ticket if we're ever in a position to do a web form in pombase.org
