### ISSUE TITLE
Don't hide help text in motif search

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1417]
Val asked that the help text not disappear when you start typing a motif pattern because she needs to refer it.

**Comment by ValWood** [comment]
Thanks, I forgot to open  this!

**Comment by kimrutherford** [comment]
I've change the motif search so that the help moves to the right and gets smaller once you start typing.  Let me know if that helps.

![motif-help-fix-2](https://user-images.githubusercontent.com/90474/66282679-bbc33780-e91c-11e9-9e83-0f9a54776d2c.png)

**Comment by kimrutherford** [comment]
The main site will have the change in 5 minutes or so.

**Comment by ValWood** [comment]
perfect!
