### ISSUE TITLE
Promoter binding inventory (transcription factor motifs)

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1419]
- [ ] Extend page using Maria's data
- [ ] Ask pombelist if they know of any additional (and find a more prominent place to host the list)
- [ ] Kim to regenerate tracks once above is done

**Comment by ValWood** [comment]
@Antonialock  
what data is needed for
 Extend page using Maria's data?

cheers

val

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/website/issues/1654
