### ISSUE TITLE
tRNAs missing GO and product information

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#142]
tRNAs are missing GO and product information for some weird reason...they might be missing other types of info too..
e.g.
http://pombase2.bioinformatics.nz/gene/SPATRNASER.03
http://pombase2.bioinformatics.nz/gene/SPBTRNAALA.11
http://pombase2.bioinformatics.nz/gene/SPMITTRNAARG.02

**Comment by kimrutherford** [comment]
I had forgotten about non coding genes.  snRNA, rRNA and others where missing too.  I've fixed the code and I'm updating pombase2 now.
