### ISSUE TITLE
random file on ftp

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1421]
In
ftp://ftp.pombase.org/pombe/exports/

some  pombase-web-.....image.xz

I don't know what it is? I downloaded it but I couldn't iopen it?

**Comment by kimrutherford** [comment]
That's a Docker image containing all the data and code for running the web site.  That's what gets copied to Babraham each night.  It's in the nightly directory so that we can include it in the monthly release: ftp://ftp.pombase.org/pombe/releases/

**Comment by ValWood** [comment]
Ah I see. I was wondering why it was int he directory with the HCPI data, but I guess that is because the HCPI  data is in the 'home' directory?

**Comment by kimrutherford** [comment]
What is "HCPI"?

The exports directory hasn't got a great name.  It's for the files that get "exported" from Chado during the nightly load where there isn't a better place for them.  It's sort of a "misc." directory.

**Comment by ValWood** [comment]
see
https://github.com/pombase/website/issues/1423

**Comment by ValWood** [comment]
I think this on can close..
