### ISSUE TITLE
hyperlink to HCPI docs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1423]
Add link to 

https://www.pombase.org/documentation/high-confidence-physical-interaction-network

from

https://www.pombase.org/datasets

Physical interaction and GO substrate data that make up the High Confidence Physical Interaction Network datasets (ftp)

i.e hyperlink  High Confidence Physical Interaction Network datasets

**Comment by ValWood** [comment]
As fas as I can see, these data still don't appear in the root directory?

**Comment by ValWood** [comment]
I think the problem here is that the directory is called "exports"

**Comment by kimrutherford** [comment]
Should we rename it?

**Comment by ValWood** [comment]
yes please

high_confidence_physical_interactions

**Comment by kimrutherford** [comment]
> high_confidence_physical_interactions

I've changed the nightly load script so that directory should be there on Wednesday morning.  I'll check then.

**Comment by kimrutherford** [comment]
> I've changed the nightly load script so that directory should be there on Wednesday morning.

I've just changed the documentation to point to the new location.  That change will also be visible on Wednesday morning.

**Comment by kimrutherford** [comment]
All done.
