### ISSUE TITLE
test hosting more spotlights on front page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1425]
From Chat with @kimrutherford 

We think we can host more if we  make the images wider and  use some of the margin (the text will then be less prominent)

Will test on some of the larger images.

Then if we go ahead:
Kim to provide list =of images with too low resolution
Val will re-download with better resolution

**Comment by kimrutherford** [comment]
> Kim to provide list =of images with too low resolution

It we want to update all the Spotlight images we'll need to get copies of all except the images here:
 https://github.com/pombase/website/tree/master/src/assets/graphical_abstract

We should decide on an aspect ratio before getting the larger images.

**Comment by ValWood** [comment]
So first could we do a mockup with some of the larger images that we already have?

There is no hurry for this anyway. It's a nice task for those days when your  brain needs a little rest...

We can  also play around with this on a call some time

**Comment by kimrutherford** [comment]
> So first could we do a mockup with some of the larger images that we already have?

Do we need bigger images for the Explore PomBase items too?

**Comment by ValWood** [comment]
Yeah I think they should all be the same size.... but I only probably  need to do the onses in the current rotation? The size can just increase in the archive, probably (I can do the older ones too if it looks crazy).

**Comment by kimrutherford** [comment]
Here's how it looks it the images are scaled up by 20% and the panels are 20% wider:

![bigger-front-page-images-1](https://user-images.githubusercontent.com/90474/69857026-d352e700-12f3-11ea-86a4-ec013ddfada0.png)

If we remove on community curation title the panels get shorter:

![bigger-front-page-images-2](https://user-images.githubusercontent.com/90474/69857135-1ca33680-12f4-11ea-9e35-1d57d1cff2ee.png)

**Comment by kimrutherford** [comment]
Here's a more radical idea (only a mock up).  I like having less wasted space on the sides but I'm worried about it looking too busy.  I think if we did something like this we should make the panel boxes look less like boxes.  They look good side-by-side but not so much when they are spread around.

We also need to make the entry points (search, gene pages, JBrowse) stand out more.

![bigger-front-page-images-3](https://user-images.githubusercontent.com/90474/69858719-778a5d00-12f7-11ea-8fe1-0b126ba42ea5.png)

**Comment by ValWood** [comment]
I like aspects of both and prefer some of the existing. Lets try some things when we next chat...

**Comment by ValWood** [comment]
I'll put this as low priority, because we might want to revisit with new stuff like micropubs.

**Comment by kimrutherford** [comment]
Try this instead:

![image](https://github.com/pombase/website/assets/90474/3fdb4a82-163b-485c-ae47-5e94d4624a21)
