### ISSUE TITLE
default   display protein not DNA sequence on gene pages sequence section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1427]
I still think we should default to protein sequence not DNA...more people are interested int he protein sequence.

I know we discussed this before but I can't think why we decided not to do it?

**Comment by kimrutherford** [comment]
I don't remember discussing this.  It's a quick change.  Should I go ahead and do it?

**Comment by ValWood** [comment]
Well I wondered if there was a reason we didn't do it before, it seems like a "no brainer'.
Any objections?

**Comment by Antonialock** [comment]
I'd be happy with this change

**Comment by kimrutherford** [comment]
I've made that change.
