### ISSUE TITLE
CLASP paper spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1428]
[Screenshot 2019-11-04 at 10.33.40.pdf](https://github.com/pombase/website/files/3804734/Screenshot.2019-11-04.at.10.33.40.pdf)

(not through yet)

**Comment by ValWood** [comment]
This can go live now...

CLASP promotes microtubule bundling in metaphase spindle independently of Ase1
PMID:31615768
Biology Open

**Comment by ValWood** [comment]
hi kim, can you make this  one live for me?
Thanks

Val

**Comment by kimrutherford** [comment]
It's ready on the dev site: http://dev.pombase.kmr.nz/archive/spotlight

If it's OK I'll update the main site.

**Comment by ValWood** [comment]
yep
