### ISSUE TITLE
gene page download no longer offers format option s

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1429]
I don't remember it doing this but maybe it happened when we switched the default from amino acid to protein?

(see helpdesk ticket)

**Comment by ValWood** [comment]
Instead of  the sequence section showing 

"show  translation" checked

can it display  "show nucleotide sequence" unchecked?

**Comment by kimrutherford** [comment]
Is this the same as #1427?

I don't understand the issue title: "gene page download no longer offers format options"

And I don't understand: "I don't remember it doing this but maybe it happened when we switched the default from amino acid to protein?"

**Comment by ValWood** [comment]
ignore...
