### ISSUE TITLE
the future PomBase protein feature viewer

### ISSUE THREAD

**Issue by ValWood** [pombase/website#143]
Ideally, this will be more of a "tool" accessible from the top of the page.

Features required
1. display domains, modifications, mutants (if applicable to sequence a region) etc, as tracks
2.  Ability to click on annotated features (domains, modified residues) and see
i) sequence context (maybe the amino acid sequence could be a bit like Artemis, scrollable track)
ii) Annotations related to the feature
3.? please add to list

Some ideas are
1. The NextProt viewer

https://cloud.githubusercontent.com/assets/7359272/20640045/d8406fb4-b3cc-11e6-847d-35a040d0ab0d.jpg

Code is available from http://www.biojs.io/

2.
UniProt's "ProtVista" thingy in ticket #17. Example: [human p53](http://www.uniprot.org/uniprot/P04637#showFeaturesViewer)

**Comment by ValWood** [comment]
note,  (we : Kim) can probably use this code for the  gene context image too?

**Comment by ValWood** [comment]
also look at

from @Antonialock in https://github.com/pombase/website/issues/15
 iPTMnet "Interactive Sequence view"
see here for an example:
http://research.bioinformatics.udel.edu/iptmnet/entry/P06493/

also their sequence alignment is cool, see here
http://research.bioinformatics.udel.edu/iptmnet/visual/msa/tree/P06493/

**Comment by ValWood** [comment]
Also look at
dbPAF: an integrative database of protein phosphorylation in animals and fungi.

**Comment by kimrutherford** [comment]
I'm not sure if we can use this but the PBD/EBI web component library might make things easier.

 - docs: https://www.ebi.ac.uk/pdbe/pdb-component-library/doc.html
 - code: https://github.com/ebi-webcomponents/

**Comment by ValWood** [comment]
http://ebi-uniprot.github.io/ProtVista/

**Comment by mah11** [comment]
... as noted in the original summary of this very ticket ;)

**Comment by kimrutherford** [comment]
> http://ebi-uniprot.github.io/ProtVista/

It's now here:
https://github.com/ebi-webcomponents/nightingale

Note to self after a bit of investigation:
  - might need to load the protvista JS code asynchronously using eg. https://stackoverflow.com/a/42766146
  - or maybe like this: https://github.com/pombase/website/blob/5c5defcb2c83c19ead653753c497987a4687552e/src/app/documentation/docs/docs.component.ts#L89-L92
  - need to experiment with adding the protvista tags into the page in the same way

**Comment by kimrutherford** [comment]
I decided writing a simple domain viewer was easier than integrating existing packages.  So I've had a go.

It's not finished yet:

  - it needs a scale
  - it might be helpful to have a popup box with details as you move your mouse around
  - it's currently a bit big
  - the highlighting when you mouse over a feature is a bit naff 

An example is here: http://desktop.kmr.nz:4242/gene/SPAC821.13c

![new-prot-view-1](https://user-images.githubusercontent.com/90474/94105599-bfcdc980-fe8d-11ea-8f6b-7207fd2779c7.png)

**Comment by kimrutherford** [comment]
This one is a bit busy: http://desktop.kmr.nz:4242/gene/SPAC23G3.02c

Maybe we need to think about being able to collapse or show/hide tracks?

**Comment by kimrutherford** [comment]
Forgot:

  - transmembrane domains
  - coiled coils?
  - fix the labels so they aren't all in capitals eg. "PFAM" should be "Pfam"

**Comment by kimrutherford** [comment]
We can probably use the same code to make a diagram for Rfam features: https://github.com/pombase/website/issues/39

**Comment by mah11** [comment]
Nice! I pretty much agree about all the to-do points but it's off to a lovely start.

**Comment by ValWood** [comment]
Agreed.

I wonder if the labels would work to the right hand side if it was scaled down a little?

**Comment by ValWood** [comment]
> I wonder if the labels would work to the right hand side if it was scaled down a little?

that is unlikely to work as some labels are long.

A bit of white space between each database might make it look less busy...

**Comment by ValWood** [comment]
Is it possible to see the residue number on mouseover?
If so we could reduce to just start and end coordinates in the table below.

**Comment by ValWood** [comment]
I just read this properly. You just wrote this, as you do ;)

**Comment by ValWood** [comment]
Note though that this might not scale for displaying modifications and mutants. We will likely need something that we can zoom and scroll (as in the Interpro tweet link, which I can't find for some reeason)

**Comment by ValWood** [comment]
Yes, I tried it and it seems ideal for our future needs from a quick test. We can chat about this sometime.

Although we don't need to do this immediately (we have 5 years) so updating the protein image would be  a good start (and  they could exist independently (like the  thumbnail on the page, and clicking through to the full-blown browser)

**Comment by kimrutherford** [comment]
> like the thumbnail on the page, and clicking through to the full-blown browser

That might be best.  The code from the EBI is very full-featured so it's also quite heavy and will make the gene pages a bit slower.

**Comment by ValWood** [comment]
>That might be best. The code from the EBI is very full-featured so it's also quite heavy and will make the gene pages a bit slower.

Yes I don't think the full blown protein viewer should be on the gene page. It will have many features for some genes. I imagine a page that you would click through to get the full functionality and it would be a bit like this
https://www.nextprot.org/entry/NX_Q14566/proteomics

So the  new simple domain viewer os perfect for the gene pages.

**Comment by kimrutherford** [comment]
Inspired by #1683, I worked on this a bit today.  I've added a scale bar and fixed the labels so they aren't always ALLCAPS.

As an example, here's the current page for ubp7 and how it looks in the new view.  The new view is live on my desktop until about noon each day: http://desktop.kmr.nz:4242/gene/SPAC23G3.08c 

Old:
![prot-view-old-1](https://user-images.githubusercontent.com/90474/112817370-d8d66200-90de-11eb-9fa8-69222c05821b.png)

New:
![prot-view-new-1](https://user-images.githubusercontent.com/90474/112817385-de33ac80-90de-11eb-9df2-d3b586be1b76.png)

**Comment by mah11** [comment]
The new view is a lot more readable - worth the extra vertical space, methinks.

**Comment by mah11** [comment]
ooh, I just noticed the mouseovers - cool!

**Comment by kimrutherford** [comment]
I'm keen to switch to the new view as soon as possible and then work on fixing bugs and adding features.  The Ensembl images are very out of date and they are the only thing on the gene pages that don't get updated regularly.

> ooh, I just noticed the mouseovers - cool!

I haven't done it yet but I was thinking of a small pop-up with some details.  Maybe just feature name, start and end initially.

**Comment by mah11** [comment]
> I'm keen to switch to the new view as soon as possible 

I vote "go for it" :)

> I was thinking of a small pop-up with some details. Maybe just feature name, start and end initially.

That would be cool. Up to you whether to add it before or after you deploy the new look.

**Comment by ValWood** [comment]
Yes I vote go for it too. I missed the window of opportunity to see it live but from the image it looks great.

**Comment by kimrutherford** [comment]
> Yes I vote go for it too.

OK, will do.

> I missed the window of opportunity to see it live but from the image it looks great.

It's back now: http://desktop.kmr.nz:4242/gene/SPAC23G3.08c

**Comment by ValWood** [comment]
Lovely.
We can remove links:

View at InterPro ... (repeated below the table)
View protein features in Ensembl browser ... (no longer required)
at the top.

**Comment by kimrutherford** [comment]
> We can remove links:

I've done that and the new code will be on the main site in the morning.

**Comment by kimrutherford** [comment]
> I've done that and the new code will be on the main site in the morning.

It's there now.  Let me know any changes you'd like.

**Comment by kimrutherford** [comment]
> Is it possible to see the residue number on mouseover?

That's done now.

**Comment by ValWood** [comment]
OMG, that is lovely!  I  love the mouse over too.

@mah11  could you announce to pombelist and make a news item?
(should mention that these  have been static since  Pombase2 release but will now be automatically updated every interpro release)

Are there any other small things we did not announce that could fit in too?
https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aclosed+label%3Aannounce

I can tweet after the announcement....

**Comment by kimrutherford** [comment]
> OMG, that is lovely! I love the mouse over too.

Cheers!

**Comment by kimrutherford** [comment]
I think I'll close this.  We can open new issues for bugs and new features.

**Comment by ValWood** [comment]
Just a heads up that longer term we might still want a 'bigger' protein viewer that we can flag protein modifications and attach phenotypes to specific amino acid changes.   I envisaged this a bit more like Jbrwse in that we would link to it from the gene pages because it would need to be scrollable widthways to fit in all the detail we wanted to host, which is why we were looking at Prot Vista etc.

Anyway, we could do this towards the end of the grant because it is a bigger but self-contained project, and it isn't urgent. We can discuss one day....
