### ISSUE TITLE
announce  sharable links for advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1430]
remind me of the features...

links can be shared and will be added to your query history?

Anything else?

**Comment by kimrutherford** [comment]
> links can be shared and will be added to your query history?

Yep the results, slim and visualisation page links can now be shared.  They are also permanent so they can be bookmarked and returned to anytime later.

I think we should hold off on announcing for a week or so, until we've used it a bit more.  It was quite a big internal change and I'm a bit nervous.

> Anything else?

The browser "back" button now works more consistently when you're on a results, slim or visualisation page.

**Comment by ValWood** [comment]
OK no hurry!

**Comment by mah11** [comment]
I've just updated the search documentation to mention the stable URLs.

**Comment by ValWood** [comment]
News item:

Lists in the Query builder https://www.pombase.org/query,  have a unique permanent URL that can be  bookmarked and shared with your colleagues.

or similar

**Comment by ValWood** [comment]
Hi @kimrutherford  can you transfer the above into a news item (tweak if necessary)

**Comment by kimrutherford** [comment]
> can you transfer the above into a news item (tweak if necessary)

That's done now.  I tweaked it a bit and added some example links.  Let me know if you'd like any changes.

**Comment by ValWood** [comment]
great!
