### ISSUE TITLE
include "spotlight" videos on publication pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1431]
I notice that these are not available on the pubmed pages as the graphical abstracts are. Not a biggee, but is it possible?

**Comment by kimrutherford** [comment]
Yep, it's possible.  Adding the images was easier than the videos so I did that first:
 https://github.com/pombase/website/issues/1229#issuecomment-487030246

Then I forgot about it.

**Comment by kimrutherford** [comment]
That's done now.

bf8085bfea2a83b1f9e8dccd9120b9bfc44fd370
