### ISSUE TITLE
spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1432]
The Bub1-TPR Domain Interacts Directly with Mad3 to Generate Robust Spindle Checkpoint Arrest

Curr Biol
https://www.cell.com/current-biology/fulltext/S0960-9822(19)30704-3?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0960982219307043%3Fshowall%3Dtrue

<img width="490" alt="Screenshot 2019-11-14 at 14 33 32" src="https://user-images.githubusercontent.com/7359272/68870238-78fe3780-06f2-11ea-95ae-7574eb996e88.png">

**Comment by kimrutherford** [comment]
That's on the main site now.
