### ISSUE TITLE
When DOI is available, link from publication page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1433]
Depends on
https://github.com/pombase/pombase-chado/issues/610

**Comment by kimrutherford** [comment]
Any thoughts on where the DOI should be shown on the publication pages?

**Comment by kimrutherford** [comment]
For testing I have:

![doi-example-1](https://user-images.githubusercontent.com/90474/71619171-f1c83d00-2c27-11ea-8c59-46fbb2ba9e31.png)

Easy to put it somewhere else though.

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
I've made that change on the main site.
