### ISSUE TITLE
community curated papers

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1436]
community curated papers here:
https://curation.pombase.org/pombe/stats/annotation
755

here
https://curation.pombase.org/pombe/track
Curated publications (3740)
Community curated publications (855)

**Comment by kimrutherford** [comment]
The list on the admin pages (https://curation.pombase.org/pombe/track) contains all sessions that ever had a community curator.  Like this one:
https://curation.pombase.org/pombe/view/object/curs/4291?model=track

The stats page count is sessions where the current curator is a community curator.

**Comment by ValWood** [comment]
I think we can this?
