### ISSUE TITLE
more paper types to include in Pombase

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1437]
With this message

This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types.

Mutagenicity or toxicity study eg PMID:106268
Biotech e.g. PMID:14522690
Modelling e.g. PMID:2520196
Phylogeny and evolutionary studies PMID:2398900
Cell composition or WT feature e.g. PMID:52399
Not physically mapped  e.g. PMID:21700
'Other'  e.g PMID:65986 .  (I need to retriage these but they are pombe papers)

**Comment by kimrutherford** [comment]
I've added those to the config.  I'll check the site on Wednesday morning.

**Comment by kimrutherford** [comment]
All your example PMIDs now have pages on the main site.  eg. https://www.pombase.org/reference/PMID:2398900
