### ISSUE TITLE
tweaks to ribbon display

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1439]
Currently looks like this

<img width="650" alt="Screenshot 2019-12-05 at 10 57 29" src="https://user-images.githubusercontent.com/12727506/70229411-14ad2180-174e-11ea-9d64-e38104e70d01.png">

1. change 'publication' to 'publications'?

2. I think it would look nicer if it was in the PomBase header and shown whichever page you are on.

Personally I like how it is shown in the GO banner on their front page (ignore the fact that the top part is a mile high) 
<img width="1431" alt="Screenshot 2019-12-05 at 10 59 29" src="https://user-images.githubusercontent.com/12727506/70229716-a2890c80-174e-11ea-98fa-2a37355767f9.png">

**Comment by mah11** [comment]
> change 'publication' to 'publications'?

definitely yes!

I also think the date should go first; it's much more important than the annotation & paper counts (personally, I feel no need to see the numbers on any pombase pages, but I know I'm not the target audience). Anyway, suggested text:

"Last updated 2019-12-04: 247,682 annotations from 3726 curated publications"

**Comment by Antonialock** [comment]
I second sticking the date first.

The reason I would like it in the banner is because personally I rarely go to the homepage of a website - I just go to whatever drops down when I start typing the address in the address bar (so my most visited page). 

I do think however that whenever I am using other resources, I find it very reassuring if I see that it has recently been updated. So this would make it visible to anyone not visiting the homepage frequently, but do visit other pages :)

**Comment by mah11** [comment]
Clarifying my thoughts in light of Antonia's latest comment: yes, I think it would be good to see the last updated date on every page.

It's the paper and annotation counts that I don't need everywhere.  If it were up to me, I'd just show the date on all pages, and carry on having the counts only on the dedicated stats page. But either way it doesn't merit coding up the home page as a special case, and the counts don't bother me much.

**Comment by kimrutherford** [comment]
I'll changed the wording.  It will be visible in the morning.

**Comment by ValWood** [comment]
I like the GO ribbon. This was what I was looking for. I thought it was on EBI, I forgot it was GO.

**Comment by ValWood** [comment]
closing....
