### ISSUE TITLE
GO data, missing qualifiers contributes_to and colocalizes_with

### ISSUE THREAD

**Issue by ValWood** [pombase/website#144]
GO data, missing qualifiers contributes_to and colocalizes_with

(tangent: We can probably get rid of colocalizes_with, I think we use it fewer then 40 times,  and I'm sure it is never necessary)

**Comment by kimrutherford** [comment]
> GO data, missing qualifiers contributes_to and colocalizes_with

The "qualifiers" column wasn't configured to show for GO data.  Fixed now.
