### ISSUE TITLE
new spotlight . 	PMID:31483748

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1442]
Not quite ready, but

<img width="1006" alt="Screenshot 2019-12-13 at 11 54 02" src="https://user-images.githubusercontent.com/7359272/70798677-7c431c80-1d9f-11ea-841f-13108e0957f9.png">

Effects of the microtubule nucleator Mto1 on chromosome movement, DNA repair and sister chromatid cohesion

Published in MBoC
https://www.molbiolcell.org/doi/10.1091/mbc.E19-05-0301

**Comment by ValWood** [comment]
I approved this one today so the spotlight can go live.

**Comment by mah11** [comment]
done
