### ISSUE TITLE
spotlight: PMID: 30602572 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1443]
<img width="1026" alt="Screenshot 2019-12-13 at 12 01 35" src="https://user-images.githubusercontent.com/7359272/70798997-59fdce80-1da0-11ea-945b-db31b1b8cb7b.png">

Association of mitochondria with microtubules inhibits mitochondrial fission.

Published in  J. Bil. Chem.
http://www.jbc.org/content/294/10/3385

(not quite ready to go live)

**Comment by kimrutherford** [comment]
> (not quite ready to go live)

Is it ready now?  There are annotations on the main site: https://www.pombase.org/reference/PMID:30602572%20

I've added the images to Git so adding the Spotlight will be quick.

**Comment by ValWood** [comment]
oh yes please!

**Comment by kimrutherford** [comment]
Done!
