### ISSUE TITLE
citation PMID:31483748

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1446]
appears as 

Mol. Biol. Cell 2019 Sep 04;:mbcE19050301

is that normal?

**Comment by kimrutherford** [comment]
That's a weird one.  The citation comes from the PubMed XML.  Maybe that publication has a an odd format for the citation information.  I've had a quick look and couldn't see what's going on.  I'll investigate it.

**Comment by kimrutherford** [comment]
I couldn't see anything weird in the PubMed XML for PMID:31483748 and I couldn't see anything wrong with the code.  So in slight desperation I deleted the cached local data from PubMed for that publication before last night's load (which causes the XML to be re-fetched).

Now the citation looks much better:
Mol. Biol. Cell 2019 10 01;30(21):2695-2708

So think there was a temporary problem with the PubMed XML and we were unlucky.

If you see this sort of odd citation again, please let me know and I'll dig deeper.
