### ISSUE TITLE
news item and spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1448]
News item

title: Making pombe molecular  biology easier, more reliable and reproducible.

Commonly used vectors yield unstable genomic loci. Aleks Vjestica and Magdalena Marek in  Sophie Martin’s  have therefore designed and constructed a series of simple, but very well characterized, plasmids for use in pombe. 
The vector series provides a highly modular toolbox to introduce heterologous sequences and includes antibiotic resistance markers, promoters, fluorescent tags and terminators. A large set of ready-to-use, fluorescent probes to mark organelles and cellular processes is also provided.
links (JCS) https://jcs.biologists.org/content/early/2019/11/29/jcs.240754
  (pombase)https://www.pombase.org/reference/
See 
All plasmids and strains available from @Addgene and @nbrp_info

Spotlight
Vještica et al 2019
A highly modular toolbox to introduce heterologous sequences and includes antibiotic resistance markers, promoters, fluorescent tags and terminators.

links (JCS) https://jcs.biologists.org/content/early/2019/11/29/jcs.240754
  (pombase)https://www.pombase.org/reference/

**Comment by ValWood** [comment]
spotlight image

![spotlight vectors](https://user-images.githubusercontent.com/7359272/71830558-e4cfa180-309e-11ea-92ca-13296b099012.jpg)

**Comment by ValWood** [comment]
news icon

**Comment by ValWood** [comment]
news icon ![news icon](https://user-images.githubusercontent.com/7359272/71830709-3710c280-309f-11ea-80cf-1a55f1a5af8b.jpg)

**Comment by mah11** [comment]
PomBase link is incomplete ... what's the PMID?

**Comment by ValWood** [comment]
oh yes PMID: 31801797
(I just triaged as 'metrhod' it so will be available soon)

**Comment by mah11** [comment]
I have put the images in git, got a news item ready to go, and done most the config edits for the spotlight. All that still needs doing is to make them live (add the 'frontpage' flag to the news and set '"show_on_front_page": true' for the spotlight - a few seconds apiece when the pub page is up). 



edited news text:

To enable fission yeast researchers to manipulate *S. pombe* molecular biology reproducibly and easily, Aleks Vještica and Magdalena Marek in Sophie Martin's lab have designed and constructed a series of simple, fully characterized plasmids.

The Stable Integration Vector (SIV) series provides a highly modular toolbox to introduce heterologous sequences more stably was possible with than previously available vectors. The toolkit includes antibiotic resistance markers, promoters, fluorescent tags, and terminators, as well as large set of ready-to-use fluorescent probes to mark organelles and visualize cellular processes.

The work is published in the [Journal of Cell Science](https://jcs.biologists.org/content/early/2019/11/29/jcs.240754.long), and a PomBase [publication page](https://www.pombase.org/reference/PMID:31801797) is available.

**Comment by kimrutherford** [comment]
The news item is live and the Spotlight is now in the front page rotation.

**Comment by mah11** [comment]
tag team!

**Comment by ValWood** [comment]
;)))

**Comment by mah11** [comment]
is that a winking face with a double chin?

**Comment by ValWood** [comment]
Well you know- post-christmas

**Comment by mah11** [comment]
I'm also happy (even a bit relieved) that the special character displays ok
