### ISSUE TITLE
Query history display misleading for count queries

### ISSUE THREAD

**Issue by mah11** [pombase/website#1449]
This is a small thing, but it just caught me out, so I'm bringing it up.

If I do a "number of exons" query with a minimum but no maximum, the display in the query history isn't quite right. E.g. querying for min. 2:

![Screen Shot 2020-01-08 at 3 02 59 PM](https://user-images.githubusercontent.com/5196259/71990052-a4049380-322a-11ea-9560-3a98b9919f38.png)

shows up as "exon_count(>2)" in the history:

![Screen Shot 2020-01-08 at 3 03 13 PM](https://user-images.githubusercontent.com/5196259/71990080-af57bf00-322a-11ea-9bb0-6123c37921c2.png)

It should show ">1" or "≥2", because the result set includes genes with exactly 2 exons as well as those with more than 2. The same goes for number of TM domains.

Even more minor point: if min. and max. are the same
![Screen Shot 2020-01-08 at 3 03 07 PM](https://user-images.githubusercontent.com/5196259/71990145-cc8c8d80-322a-11ea-9899-db8e3f95dc80.png)

 the "exon_count(2..2)" display is redundant. It can just be "exon_count(2)". But that one isn't actively misleading.

**Comment by kimrutherford** [comment]
> "≥2"

I went for that option.

> the "exon_count(2..2)" display is redundant. It can just be "exon_count(2)". 

That's fixed too now.
