### ISSUE TITLE
problem with with/from and "show details"

### ISSUE THREAD

**Issue by mah11** [pombase/website#145]
I've just started seeing very buggy behavior with the "show details" toggles on the gene pages. Sometimes they stop working, and don't work again until I reload the page (plain reload works).

There may be a connection with the new with/from display done for #139, because it goes awry when I show details for GO annotations that have certain with/from entries. Pombe gene IDs in 'with' and GO IDs in 'from' seem to be OK, but 'with' entries that point to IDs for non-pombe genes make it mess up.

In addition to breaking the details toggle, not all of the annotation shows up - it's as if it can only show part of one annotation and none of the rest for any given ontology when it encounters any of that type that has a problem 'with' entry.

Seen in Firefox, Safari and Chrome. Appears to affect the page for any gene that has annotations with a non-pombe/GO 'with' entry.

Examples where you can see if you can reproduce: mre11, cdc2, tra2, arp3, gyp7 (compare 'n contrast MF vs BP, and pombe gene vs. GO vs. non-pombe gene in with/from)

Note: once I've seen the bug, I also have to reload to search for another gene. The tab label shows the name of the new gene as soon as I put it in the search box and hit return, but the page content doesn't update until I reload.

**Comment by kimrutherford** [comment]
Sorry about that.  You're right it was the with/from changes that broke things.

It's fixed now.

**Comment by mah11** [comment]
much better - thanks!
