### ISSUE TITLE
Add a public API

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1450]
From the ELIXIR node reviewers:
"Also, we would encourage to provide a public API to access the resource."

Have we had many users ask for API access?  Do we just point them to https://www.pombase.org/faq/can-i-access-pombase-via-api ?

In my experience, APIs get talked about a lot but not used a lot.  :-)
If I have the option of using an API or downloading a file to parse, I would always go for the file.  It's easier to work with and easier to debug problems.  We use NCBI APIs in Canto and it's mostly OK but we do have problems like this: https://github.com/pombase/canto/issues/1572

If we add an API we should concentrate on stuff that isn't easy to get from Ensembl Genomes or from GO.  Maybe a phenotype/genotype API would be helpful?

**Comment by ValWood** [comment]
Pombemine
