### ISSUE TITLE
add elixir logo somewhere on website

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1451]
At the bottom of the homepage?

**Comment by kimrutherford** [comment]
How prominent does it need to be?  Would the About page be OK?: https://www.pombase.org/about

**Comment by ValWood** [comment]
Most people seem to put it at the bottom of the home page with the sponsors.
In that case we should make the sponsor links more prominent by adding their icons.
Maybe something like this:

**Comment by ValWood** [comment]
![Screen Shot 2015-09-17 at 21 51 32](https://user-images.githubusercontent.com/7359272/72680306-5a306e80-3ab0-11ea-9494-6f1f2d656138.png)

but side by side instead of one above the other?

**Comment by ValWood** [comment]
Maybe something like this but side by side instead of one above the other?

![Untitled](https://user-images.githubusercontent.com/7359272/72680317-84822c00-3ab0-11ea-830d-60f6129e0cde.jpg)

**Comment by ValWood** [comment]
or

<img width="802" alt="Screenshot 2020-01-22 at 17 31 47" src="https://user-images.githubusercontent.com/7359272/72977496-97f10800-3dcc-11ea-93f0-201312f0d46b.png">

but it should be clearer  who does what..

**Comment by kimrutherford** [comment]
> Most people seem to put it at the bottom of the home page with the sponsors.

Our current blurb is at the bottom of every page.

ie. PomBase is funded by the Wellcome Trust, run by a consortium comprising the University of Cambridge, University College London, and hosted by the Babraham Institute.

**Comment by kimrutherford** [comment]
I've added some logos to the footers of the dev site pages to see how it looks:
![new-footer-1](https://user-images.githubusercontent.com/90474/90710588-cdbe8680-e2f2-11ea-95d7-915bb9154a08.png)

Cambridge and UCL spend a lot of energy on their "brand":
https://www.cam.ac.uk/brand-resources
https://www.ucl.ac.uk/cam/brand/brand-resources/logo-requests

Maybe we need to ask for permission?  Perhaps Jürg would prefer that we use his group or department logo as well or instead?

It's live on the dev site if you'd like to see them in a browser: http://dev.pombase.kmr.nz/

@bahler

**Comment by ValWood** [comment]
Looks good  !

**Comment by bahler** [comment]
Looks great Kim. No need for more specific logos or permissions.

Cheers,
-Jürg

**Comment by mah11** [comment]
Ugh. I've always liked the fact that the pombase website wasn't a logo soup. But at least they're down at the bottom where I don't have to look, so I'm not going to die on this hill.

**Comment by kimrutherford** [comment]
OK, I'll go ahead and add the logos to the main.
