### ISSUE TITLE
Is analytics set up correctly? (not all publication page visits appear to be recorded)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1455]
I'm not sure that everything is being counted. 
On Tuesday after announcing the  EuropePMC feature, I wondered if anyone had followed the link, but when I looked only 2 reference pages appeared to be accessed all day:

https://analytics.google.com/analytics/web/#/report/content-drilldown/a98997285w156805306p158341248/_u.date00=20200121&_u.date01=20200121&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePathLevel1:~2Freference~2F/

I accessed at least 20 or 30  reference pages myself throughout the day. Even the page I included in the  announcement does not appear to have any accesses.

I wondered if this is something to do with the Babraham set up? Or am I making a mistake.
It seems odd though...

**Comment by ValWood** [comment]
For instance "all pages"

https://analytics.google.com/analytics/web/#/report/content-pages/a98997285w156805306p158341248/_u.date00=20200121&_u.date01=20200121&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=1000/

list 732 pages.
only 2 reference pages  appear in this list too.

**Comment by kimrutherford** [comment]
> I accessed at least 20 or 30 reference pages myself throughout the day.

Were you using Firefox?

> I wondered if this is something to do with the Babraham set up?

That's unlikely because the logging is done by Google Analytics using a small bit of Javascript embedded in each page.

**Comment by ValWood** [comment]
Google chrome. Always.
Antonia checked too. She had also accessed lots of reference pages. So it seems not to be logging either of us?

**Comment by kimrutherford** [comment]
> So it seems not to be logging either of us?

That's not good.  Could you try accessing some page while watching the real time stats page in Analytics?  When I do that I see my accesses.

I've updated the website code to use the very latest version of the little library that inserts Google's Javascript into our pages.  The change log for the library doesn't mention any bugs that are likely to cause this problem, but I thought it wouldn't hurt.

Are you using any Firefox extensions that block adverts?

**Comment by ValWood** [comment]
I'm using Google chrome and I do have an ad-blocker  "AdBlock", but I need to explicitly  turn it on for a specific page or website.


I did used to be able to see my accesses in real time, but no longer seem to...

I'm pretty sure that we have more than 2 publication page views in a day ! so it seems that we are missing a big slice of the accesses.

**Comment by ValWood** [comment]
I will try Safari though ...

**Comment by ValWood** [comment]
Hmm, maybe it was a bug in alalytics.

Today

4. | /reference/ | 89(4.74%)


Which is more in line with my expectations!

**Comment by ValWood** [comment]
Tuesday 21st still has


3. | /reference/ | 3(0.26%)

**Comment by ValWood** [comment]
Let's assume this was some sort of glitch, but  monitor occasionally.

**Comment by ValWood** [comment]
For the record, I was accessing POmbase from 3 devices, and there was only a single reported user in Spain (realtime)
