### ISSUE TITLE
broken FAQ GO link

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1456]
The GO Consortium provides further information on annotation extensions in its file format guide

**Comment by mah11** [comment]
Which FAQ?

**Comment by ValWood** [comment]
PomBase?

**Comment by ValWood** [comment]
What is an annotation extension?

**Comment by mah11** [comment]
always helps to have the URL for the page that contains the broken link, but I found it anyway

**Comment by ValWood** [comment]
Yeah sorry. I was ^F ing through the  whole FAQ, and I was on a short fuse because it was  3:30 and I hadn't had lunch  but was trying to finish up so crap was happening... Now sorted.
