### ISSUE TITLE
simplify text for Query builder  search descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1457]
From https://github.com/pombase/website/issues/56

@Antonialock  said:

Retrieve genes based on phenotypes of mutations annotated using Fission Yeast Phenotype Ontology (FYPO) terms:

Should we simplify to
‘ retrieve genes based on mutant phenotypes’

vw:
(I'm not sure if these headings are templated in some way?)

**Comment by kimrutherford** [comment]
> I'm not sure if these headings are templated in some way?

I've just moved the configuration for the query builder to the config file rather than being hard coded.  So the phenotype header text can now be edited here:

https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L150

**Comment by kimrutherford** [comment]
> Should we simplify to ‘ retrieve genes based on mutant phenotypes’

I think that would be OK but only if there is a direct link to the documentation from here.

**Comment by ValWood** [comment]
What if we change from

Retrieve genes based on phenotypes of mutations annotated using Fission Yeast Phenotype Ontology (FYPO) terms:


To
Retrieve genes based on mutant phenotypes  annotated using Fission Yeast Phenotype Ontology (FYPO):

It is slightly shorter and less clunky, but I think it is still good to say how they were annotated.
?

**Comment by kimrutherford** [comment]
> It is slightly shorter and less clunky

I think it's better.  I've gone ahead and made that change.  It will be visible at 7am-ish.

**Comment by mah11** [comment]
closing because the shorter text is live
