### ISSUE TITLE
PomBase publication page text

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1458]
This  papers says "curated by PomBase staff"

but hasn't been (AFAIK, it's just BIOGRID)

https://www.pombase.org/reference/PMID:28357272

I thought we had a different message for this?

Note to self, link recent history to this ticket

**Comment by mah11** [comment]
The other ticket is #858. It's still open, and has more details, so I'd keep that one open.

**Comment by ValWood** [comment]
Ah OK closing
