### ISSUE TITLE
Queries related to YD Tay's phosphodata

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1459]
https://www.pombase.org/reference/PMID:30726745

1. Only a subset annotation (abc3, aha1) n appears to have "affected by orb6"?

2. There seem to be about 3000 +1667  phosphosites. However, the annotation number jumped from just under 250,000 to 259,000. Did any other large datasets get added this past 2 days?

**Comment by ValWood** [comment]
Maybe some of the annotations are the new disease gene connections, but unlikely there are ~>5000

**Comment by mah11** [comment]
The file has 10827 lines, of which 570 include an affected_by extension.

**Comment by ValWood** [comment]
OK thanks.
Maybe  I did not see all the totals. It's a long page...
I will  check with @Antonialock , I though all were "affected by orb6" but perhaps not...

**Comment by kimrutherford** [comment]
> Did any other large datasets get added this past 2 days?

PMID:30726745 is the only recent dataset.

**Comment by ValWood** [comment]
Yep, I miscounted.

**Comment by mah11** [comment]
From this bit of the paper, it looks like the orb6 extensions are OK:

> From three biological replicate experiments, we identified 10,866 phosphosites, of which 8,134 phosphosites could be quantified. Among the quantified phosphosites, 326 (4%) showed a 2-fold or greater decrease in phosphorylation after Orb6 inhibition in at least one experiment, 121 (1.5%) showed this decrease in at least two experiments, and 55 (0.7%) showed this decrease in all three experiments (Table S2).
