### ISSUE TITLE
tweak the 'show details' option for publication pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#146]
i.e. this page
http://pombase2.bioinformatics.nz/reference/PMID%3A22182414

1) for GO I don't think we need an 'undetailed' view - just show the details?

2) for phenotypes I think we should show the gene column in the detailed view

**Comment by mah11** [comment]
partial overlap with #140

**Comment by kimrutherford** [comment]
> or GO I don't think we need an 'undetailed' view - just show the details?

For some references, that will be quite big. eg. http://pombase2.bioinformatics.nz/reference/PMID%3A25373780

Would that be OK?

> for phenotypes I think we should show the gene column in the detailed view

I've added a genotype column.  Should we have a gene column too?

**Comment by ValWood** [comment]
duplicate https://github.com/pombase/website/issues/140
