### ISSUE TITLE
news item, meeting

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1461]
thumbnail:

<img width="198" alt="Screenshot 2020-01-31 at 11 47 33" src="https://user-images.githubusercontent.com/7359272/73537097-87214180-441f-11ea-8236-1ccc9e42b279.png">

Text:
The 14th edition of the “Levures, Modèles et Outils” meeting (LMO14) will be held in July 9-11, 2020 at the University of Strasbourg in France. You will find more information about the meeting here: https://lmo-14-2020.sciencesconf.org/ Registration will be open from February 3rd to June 30th.
Abstract submissions will be possible from February 3rd to April 10th. Authors will be notified early May and the final program will be available early June. The sessions will be diverse and present the latest findings using yeast as a model organism on the following topics:
[1] Cell biology, cell cycle, cytoskeleton  [2] Gene expression regulation [3] Population, functional and evolutionary genomics [4] Replication, repair and recombination [5] Transport, sensing and signaling                                  
[6] Pathogenic yeast and filamentous fungi [7] Tools, resources and databases [8] New technologies, yeast and industry

**Comment by mah11** [comment]
That image seems to be specific for the 10th conf ... does that pose any problem?

**Comment by ValWood** [comment]
ah right, I will find . out if 14 has one

**Comment by mah11** [comment]
well, I can download the banner image from the lmo14 page, but of course it's totally the wrong aspect ratio for our news thumbnails

**Comment by mah11** [comment]
I've made a teensy, slightly cropped version of the poster Dom included in the pombelist email. If you get anything better, reopen this and we can swap a new thumbnail in.

**Comment by ValWood** [comment]
I mailed Dom, he didn't reply to me yet, but I'm sure  your thumbnail will be  fine!

**Comment by mah11** [comment]
well, I forgot the 'frontpage' flag (doh) so we'll see what it looks like tomorrow
