### ISSUE TITLE
Constrain phenotypes by multiple conditions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1462]
Now #56 is done do we want to be able to constrain by multiple phenotype conditions?

**Comment by kimrutherford** [comment]
The server side code supports this so to implement this we just need to decide what the user interface should look like.

**Comment by ValWood** [comment]
Could this  look like Canto Condition selection?

<img width="656" alt="Screenshot 2021-12-30 at 16 35 37" src="https://user-images.githubusercontent.com/7359272/147770775-469a7e00-266f-4a96-a50e-6f36ac77d020.png">

**Comment by ValWood** [comment]
See also https://github.com/pombase/website/issues/1463
for alleles that do not have a particular condition.

**Comment by kimrutherford** [comment]
> Could this look like Canto Condition selection?

I wasn't able to implement that in the same way as Canto, but I've done something similar.  It's all working, but I won't deploy the change until we've all had a chance to test it and discuss it.  We might need help text and a documentation update.

![image](https://user-images.githubusercontent.com/90474/183577022-b0958b3b-77c4-47a3-91b9-f59808e1ba58.png)

**Comment by ValWood** [comment]
Is this on dev? I don't see it looking like this.

**Comment by kimrutherford** [comment]
It was tricky to enable just for the dev site so it's only available on my desktop at the moment: https://desktop.kmr.nz

**Comment by kimrutherford** [comment]
I think this change is ready to go.  I've done some more testing and it all seems OK.

It's running on my desktop if you'd like to give it a try: https://desktop.kmr.nz/

**Comment by ValWood** [comment]
I couldn't test because the phenotype search box doesn't appear to be working?

**Comment by kimrutherford** [comment]
Sorry, I was working on something else.  It should be OK now.

**Comment by kimrutherford** [comment]
> I think this change is ready to go. I've done some more testing and it all seems OK.

I decided that the easiest plan is to release the change to the dev server: http://dev.pombase.kmr.nz/query

If it's all OK, I'll update the main site.

**Comment by kimrutherford** [comment]
The excluded conditions are dev-site only because they aren't working properly.  It's still using the old system.

**Comment by ValWood** [comment]
OK! I was on dev.
So you still need to make the excluded conditions behave like the  present conditions?
Also we need different headers , they are all constraints:

Constrain conditions
Present
Excluded
?

**Comment by kimrutherford** [comment]
> So you still need to make the excluded conditions behave like the present conditions?

Yep.

I'd like to have a chat on Zoom about excluding conditions to make sure it's useful before implementing it.

**Comment by ValWood** [comment]
It might also be useful to constrain on allele type (i.e. deletion) so that you can retrieve all annotations to a phenotype without, for example over-expression.

**Comment by ValWood** [comment]
This is almost implemented so we should figure out what we still need to do in the next couple of weeks if possible

**Comment by kimrutherford** [comment]
The remaining question is how things should work if multiple conditions are excluded.  For example if you exclude "high temperature" and "+ NaCl" should that filter out an annotation with just "high temperature" as a condition?  Or should it only filter out annotations with both "high temperature" and "+ NaCl" as conditions?

But maybe I'm overthinking this.  :-)

**Comment by ValWood** [comment]
I think it should be both, but let's chat about it

**Comment by ValWood** [comment]
we can chat about this tomorrow!

**Comment by kimrutherford** [comment]
> I just tried and I don't thin the advances search is working on your desktop (tried FYPO and GO)

If you need to test the excludes constraints, the dev site is a better bet.

**Comment by kimrutherford** [comment]
For Kim:
 - disable constraining on multiple conditions
 - enable exclude constraints

**Comment by kimrutherford** [comment]
> -    disable constraining on multiple conditions
> -    enable exclude constraints

Done.

**Comment by kimrutherford** [comment]
Thanks!

> The “Exclude condition” option restricts the results to exclude any gene with phenotype annotations to the phenotype term of interest including the specified condition, for any allele, but only where they are not present with another condition.

I think we should re-word this slightly to be clear that we exclude annotations not genes.

How's this:
The “Exclude condition” option excludes from the results any annotations to the phenotype term of interest that include the specified condition

> for any allele, but only where they are not present with another condition.

I don't understand that bit.

**Comment by ValWood** [comment]
Let's refine tomorrow...

**Comment by ValWood** [comment]
The “Exclude condition” option excludes from the results any annotations to the phenotype term of interest that include the specified condition (now that annotations to the same gene with a different condition, or no condition specifies will remain).

**Comment by kimrutherford** [comment]
The docs now have the changes we discussed on Zoom.

**Comment by kimrutherford** [comment]
I think this is done?

**Comment by ValWood** [comment]
Yep, one small suggestion. Would it be possible to have a "I" icon right next to the "contain condition" option linking to the appropriate place in the docs, since its a bit complicated?

**Comment by kimrutherford** [comment]
> Would it be possible to have a "I" icon right next to the "contain condition" option linking to the appropriate place in the docs, since its a bit complicated?

Good plan.  I've made that change to the code.  The main site will be updated in 30 minutes or so.

**Comment by kimrutherford** [comment]
> Good plan. I've made that change to the code. The main site will be updated in 30 minutes or so.

Done.
