### ISSUE TITLE
protein ontology links broken

### ISSUE THREAD

**Issue by mah11** [pombase/website#1465]
Links to PRO entries aren't working, because the "PR:" prefix is missing from the URLs
For example, the link for GTP-bound Cdc42 is coming out as https://proconsortium.org/app/entry/000044799/ (broken) instead of https://proconsortium.org/app/entry/PR:000044799/ (works, as does the version with an underscore https://proconsortium.org/app/entry/PR_000044799/)

The entry in the [GO db-xrefs collection](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml) doesn't make it very clear that the prefix has to be added to form the working URL. Should we use a local config entry instead? (If so, I guess this could move to the pombase-config tracker.)

**Comment by kimrutherford** [comment]
> Should we use a local config entry instead?

Yep, that was the easiest fix.  The links should be working again by the morning.
