### ISSUE TITLE
does search work on secnday IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1466]
Advanced search
0 | cytoskeletal protein membrane adaptor (GO:0140362)

gene pages:

https://www.pombase.org/term/GO:0106006

GO:0140362 is a secondary ID.

(terms merged recently)

**Comment by kimrutherford** [comment]
The searching only works for name, synonyms and the term ID.  We have the secondary IDs in Chado but the website isn't using them.

**Comment by kimrutherford** [comment]
> The searching only works for name, synonyms and the term ID. We have the secondary
> IDs in Chado but the website isn't using them.

I've fixed that now so you can search for "GO:0140362".

**Comment by kimrutherford** [comment]
Just fixed a small problem.  The term details weren't shown for secondary identifiers.  You could paste one in and press return and get to the right page.  But it now shows the drop down:

![alt-id-complete-1](https://user-images.githubusercontent.com/90474/74699144-d8756180-5264-11ea-93ee-453b6314c437.png)

Ideally it should say "matches secondary ID" but it's not urgent.
