### ISSUE TITLE
pombelist page needs update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1467]
old EBI links

https://www.pombase.org/news/pombelist-has-moved

also, does anyone know where we put the EBI archive. I wanted to search for an old post......

**Comment by mah11** [comment]
That is not the pombelist page. It is a news item from July 2013. I'll add a warning to it.

>  does anyone know where we put the EBI archive

Try this file on the curation.pombase.org server:
/data/pombase/backups/pombelist-ebi-archive-2018-10-10.tar.xz

**Comment by ValWood** [comment]
I thought that was odd. Good plan to add a warning, Google found this...
