### ISSUE TITLE
Links to Gene3D not working

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1469]
All the links return "Temporarily unavailable"

For example G3DSA:3.30.200.20 on https://www.pombase.org/gene/SPCC18B5.03

I don't if it's actually temporary or we have the wrong URLs.

**Comment by mah11** [comment]
Well, their own pages have links in this syntax:

    http://gene3d.biochem.ucl.ac.uk/family?family=1.10.510.10

but that one also gives the "Temporarily unavailable" right now, so it looks like they're having some sort of issue and maybe the url syntax that we (and GO) use will work again when they've sorted it.

**Comment by kimrutherford** [comment]
There are other places we could link to instead:
  - https://www.ebi.ac.uk/interpro/entry/cathgene3d/G3DSA:3.30.200.20/
  - www.cathdb.info/version/latest/superfamily/3.30.200.20

**Comment by ValWood** [comment]
I forget where we obtain the links from.
it's very odd that they change them....

The interpro link isn't really  the right place for CATH  so I guess we could use the other one...

**Comment by kimrutherford** [comment]
> The interpro link isn't really the right place for CATH so I guess we could use the other one...

I've changed the links to point to CathDB.
