### ISSUE TITLE
Error for PANTHER link on wee1 gene page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1471]
If I follow the link to PANTHER in the Orthologs section I get:
```
HTTP Status 400 – Bad Request
```

**Comment by kimrutherford** [comment]
Also from the External references section.

**Comment by ValWood** [comment]
These did work. @thomaspd  who should we contact about broken PANTHER links? did they change?

**Comment by ValWood** [comment]
I reported this on the PANTHER helpdesk

**Comment by mah11** [comment]
It looks like the links work if you substitute %7C for | , e.g.

**Comment by kimrutherford** [comment]
Thanks for that!

I'm sure it used to work.  Oh well.

I've fixed the configuration so the links are working again.

**Comment by ValWood** [comment]
They did work for sure. I use them all the time...
