### ISSUE TITLE
Link to SUPERFAMILY not working from wee1 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1472]
In the "Protein families and domains" table.

http://supfam.org/scop/SSF56112

I get this.  I kid you not.

![Screenshot from 2020-02-19 20-48-55](https://user-images.githubusercontent.com/90474/74813022-70547780-5359-11ea-86b8-15d30117f803.png)

**Comment by ValWood** [comment]
Okaaaaay....it certainly did...

**Comment by mah11** [comment]
Cool to see some creativity ;)

Where are we getting the IDs to plug into the URLs? The example in GO doesn't have the 'SSF', and if I remove SSF from our URL it works, i.e. 

    bad: http://supfam.org/scop/SSF56112
    good: http://supfam.org/scop/56112

**Comment by kimrutherford** [comment]
Thanks for investigating.

We get the IDs from Interpro who have "SSF56112" etc.  That's a bit of a pain.  I don't like special cases.

**Comment by mah11** [comment]
Thanks for the hint. It seems InterPro is linking to SUPERFAMILY 1.75, whereas GO has URL syntax for the current SUPERFAMILY 2. The supfam.org home page calls 1.75 "legacy".

So I think we have two options:
1. adjust our IDs to work with SUPERFAMILY 2 and the GO URL syntax, or
2. configure our SUPERFAMILY links to go to 1.75

If you prefer option 2, the URL syntax looks like 

    http://supfam.org/SUPERFAMILY/cgi-bin/scop.cgi?ipid=[ID]

**Comment by ValWood** [comment]
We are using Interpro version 76.
77  is out  (Nov) we don't always update every release, but it might be worth checking of the IDs are updated. If not I will report to them  becasue presumably, they will fix the IDs...

**Comment by mah11** [comment]
In that case, maybe we should go with option 2, because that would be a config change that we could do now, and then revert when InterPro switches to supfam 2 and the IDs that work with it.

**Comment by mah11** [comment]
oh, and the InterPro stuff I put in my earlier comment is what's on their (i.e. InterPro's) website right now

**Comment by ValWood** [comment]
Ah OK, I'll report to InterPro...

**Comment by ValWood** [comment]
InterPro

The Superfamily team is working on updating the hmm library based on the recent release of SCOP version 2 classification. This is expected to be completed in the next two months. When we get the data, it might take us two to three months to make the update in InterPro.
We use a link like:
http://supfam.org/SUPERFAMILY/cgi-bin/scop.cgi?ipid=SSF100879
to Superfamily and it works ok for us

**Comment by kimrutherford** [comment]
> We use a link like:
> http://supfam.org/SUPERFAMILY/cgi-bin/scop.cgi?ipid=SSF100879
> to Superfamily and it works ok for us

I've overridden the GO xrfs config to use that link instead.  We can worry about a proper fix once InterPro is updated.  The link should work in the morning.
