### ISSUE TITLE
add a news item for 250,000 annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1474]
We should have a news item for this. It was a bit late because adding Tay's data  zoomed us past it before christmas.

**Comment by ValWood** [comment]
thumbnail
<img width="326" alt="Screenshot 2020-02-20 at 11 26 25" src="https://user-images.githubusercontent.com/7359272/74929721-00cf9e00-53d4-11ea-9356-b55435569183.png">

**Comment by ValWood** [comment]
PomBase recently reached 250,000 annotations to 
controlled vocabularies and ontologies. 

The majority, (over 90%) are assigned manually from fission yeast experimental data derived from 3776, mainly low-throughput, hypothesis-driven publications.

You can query and combine any of these data types here: https://www.pombase.org/query

Thank you to everyone who contributed  to this significant achievement through community curation.

**Comment by kimrutherford** [comment]
On the main site now.
