### ISSUE TITLE
Update curation graph image on front page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1475]
See: https://github.com/pombase/canto/issues/2226

**Comment by kimrutherford** [comment]
Currently we label the "Community" and "PomBase curators" colours.  Should we label "Uncurated, community assigned" and "Uncurated, curator assigned" colours?

![2018-12-24-community_papers_curated](https://user-images.githubusercontent.com/90474/75010445-061b0e80-54e2-11ea-97ca-197b38d3bb95.png)

Also I've only just noticed that you can click on the labels in the key of the graph to toggle datasets on and off.  It work for the Cumulative annotations by type and year graph too.
Here is the curation graph with just community curated:

![click-graph-key-1](https://user-images.githubusercontent.com/90474/75010515-38c50700-54e2-11ea-9f0a-70ee9bf3c173.png)

**Comment by ValWood** [comment]
Yes if we could include labels
"community assigned" and
"Pombase assigned" too, that would be good

I had never noticed the toggling either!

**Comment by kimrutherford** [comment]
> "Pombase assigned" too,

I've had a go at this but it's a bit rough.  I'll redo it again soon.  I left out "PomBase assigned" because I was running out of room and they don't show up on the graph.  Is that OK?

It will be visible in the morning.

![2020-02-24-community_papers_curated](https://user-images.githubusercontent.com/90474/75122926-b9b11800-5707-11ea-92de-9d15b0114857.png)

**Comment by ValWood** [comment]
I think that looks just fine!

**Comment by ValWood** [comment]
For me on the homepage, it just shows up as a small icon in the corner (i.e the image doesn't resolve)
v

**Comment by kimrutherford** [comment]
> For me on the homepage, it just shows up as a small icon in the corner (i.e the image doesn't resolve)

Fixed!  Sorry about that.

**Comment by ValWood** [comment]
This looks cool and new. Let's disable the word cloud and just show this.

**Comment by kimrutherford** [comment]
> This looks cool and new. Let's disable the word cloud and just show this.

Done!  It's easy to add the word cloud back later.
