### ISSUE TITLE
Research spotlight CDP-DAG Synthase Tam41 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1476]
Needs finalising, will add text later

<img width="734" alt="Screenshot 2020-02-19 at 19 50 20" src="https://user-images.githubusercontent.com/7359272/74954898-bc57f880-53fb-11ea-9f6c-eb78882eb856.png">

**Comment by ValWood** [comment]
PMID:31178220 
Structures of the Mitochondrial CDP-DAG Synthase Tam41 Suggest a Potential Lipid Substrate Pathway from Membrane to the Active Site.

**Comment by ValWood** [comment]
Template
 {
      "title": "***XXXXX*** et al., YYYY",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["assets/spotlight/****YYYY-MM-DD-PMID-name*****.png"],
      "content": "****TEXT****.\nOriginally published in <a href='URL'>***JOUNAL***</a>.",
      "reference_id": "PMID:*******",
      "link_label": "Publication record in PomBase ...",
      "date_added": "YYYY-MM-DD",
      "show_on_front_page": true
    },

**Comment by ValWood** [comment]
Template
{
"title": "XXXXX et al., YYYY",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/YYYY-MM-DD-PMID-name*.png"],
"content": "Structures of the Mitochondrial CDP-DAG Synthase Tam41 Suggest a Potential Lipid Substrate Pathway from Membrane to the Active Site.\nOriginally published in Structure.",
"reference_id": "PMID:*******",
"link_label": "Publication record in PomBase ...",
"date_added": "YYYY-MM-DD",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
I did it. Can somebody check that it looks OK I think I did everything.
It would be good to move these requests to a config tracker and have a template?

**Comment by mah11** [comment]
> It would be good to move these requests to a config tracker 

You're the one who keeps opening them here instead of https://github.com/pombase/pombase-config/issues ;)

**Comment by ValWood** [comment]
Nobody has ever used the config tracker for spotlights ?

**Comment by mah11** [comment]
True up to date, but your comment yesterday said you thought they should move to "a config tracker". Have you changed your mind, or do you want to switch to using the config tracker for spotlights? I have no preference, really, but your last couple of comments don't seem mutually consistent re what you want to do.

**Comment by ValWood** [comment]
My (complete) thought was, that if we used the config tracker for the spotlights etc, we could template them, a bit like this:

<img width="915" alt="Screen Shot 2020-03-03 at 12 57 44" src="https://user-images.githubusercontent.com/7359272/75777874-b1338f80-5d4e-11ea-9e61-29c3edb7b8e4.png">

Which would provide a template for each config.

I will put this on the group meeting list of things to discuss.
Or if people think this is a good plan I can open a ticket for it.

**Comment by kimrutherford** [comment]
> I did it.! Can somebody check that it looks OK I think I did everything.

It looks OK.

In the older Spotlights we have made the journal name a link to the journal article.  i.e. the "Cell Reports" in "Originally published in Cell Reports" is a link.  Should we keep doing that?

**Comment by ValWood** [comment]
yes, sorry I  thought that must happen automagically

**Comment by kimrutherford** [comment]
> yes, sorry I thought that must happen automagically

No problem.  I'll fix those.  It's a nice quick Friday afternoon job.
