### ISSUE TITLE
News item 50% response rate

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1478]
Title
Community curation  response rate reaches 50%

800/1600 publications assigned to community members for curation are finished.  A big thank you to everyone who has participated so far.

**Comment by ValWood** [comment]
Do we have a canto logo  thumbnail size? I guess we could use that here?

**Comment by ValWood** [comment]
Hi KIm, if you can size me down a logo, I can make the news item later.

v

**Comment by kimrutherford** [comment]
I've added a Canto thumbnail. You should be able to use it with this in your news item:
```
 <!-- newsfeed_thumbnail: canto.png -->
```

**Comment by ValWood** [comment]
I committed this one

**Comment by kimrutherford** [comment]
That's live now.
