### ISSUE TITLE
add count for characterisation status

### ISSUE THREAD

**Issue by ValWood** [pombase/website#148]
Very trivial and not important, but  I'm guessing that it will only take you a few minutes :)
Could we add a count to this:

![count](https://cloud.githubusercontent.com/assets/7359272/22612108/6201a608-ea66-11e6-9a94-f8a40010262d.jpg)

Its one of my obsessions ;)

http://www.pombase.org/status/gene-characterisation

**Comment by kimrutherford** [comment]
Sorry, I don't understand this.  Do you want a count to appear on every gene page?

**Comment by ValWood** [comment]
Actually, now we are moving counts off main page, probably we don't want to do this. 
Will be available via query builder, and page eventually:
http://www.pombase.org/status/gene-characterisation
(which will be replaced by a graph)
https://github.com/pombase/pombase-chado/issues/566

I wanted it for poster figures but I can access this from contigs with grep....
