### ISSUE TITLE
Research spotlight PMID:32023460 Scs2-Pil1

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1481]
{
"title": "Ng et al., 2020",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/2020-02-29-PMID-Scs2-Pil1-interactions.png"],
"content": "Plasma Membrane Furrows Control Plasticity of ER-PM Contacts.\nOriginally published in Cell Rep.",
"reference_id": "PMID:32023460",
"link_label": "Publication record in PomBase ...",
"date_added": "2020-02-29",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
still need to add to config an upload image

**Comment by ValWood** [comment]
done with 
<img width="655" alt="2020-02-29-PMID-Scs2-Pil1-interactions" src="https://user-images.githubusercontent.com/7359272/75616468-29c8ff00-5b49-11ea-9b2c-1ddfe63ab09e.png">

**Comment by ValWood** [comment]
changed to false, still need to  add terms

**Comment by ValWood** [comment]
I thought I put

changed to "false", still need to add new terms/approve

but this one is live

**Comment by ValWood** [comment]
yeah has
      "show_on_front_page": false
?

**Comment by kimrutherford** [comment]
> "show_on_front_page": false

Are you seeing it on the archive page or on the front page?  Setting that flag to false only removes the Spotlight from the front page rotation, not from the archive.  The only way to remove it from the archive is to remove the configuration.

**Comment by ValWood** [comment]
Ah got it. I forgot about the flag to remove from the rotation. It an stay because it will be through soon. Just waiting for some terms.

**Comment by ValWood** [comment]
This one can appear in the rotations from tomorrow. I changed the label from false to true
