### ISSUE TITLE
News item InterPro release

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1482]
This will be the same as the previous InterPro news item, but will  change the text as follows:

PomBase now uses InterPro Version 77.0

PomBase now uses InterPro Version 77.0, which integrates 145 new methods from the CATH-Gene3D (134),  and SUPERFAMILY (11) databases. InterPro cites 59894 publications in PubMed. See the InterPro release notes for further information.

**Comment by ValWood** [comment]
I would have done this one yesterday, but I wanted a screenshot with the annotation stats for the community curation talk next week ;)

It can go live sometime this week.

**Comment by kimrutherford** [comment]
> It can go live sometime this week.

Done!
