### ISSUE TITLE
small tweak to publication page messages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1483]
The papers which have been sent out for curated but not yet accepted (i.e just SESSION_CREATED)

e.g 

PMID:31564494
PMID:24449894

these say

Community curation is in progress for this paper. Please contact the curators if you would like to suggest annotations from it.

In this case I don't think the message should say 

"Community curation is in progress for this paper."

but
This session is assigned to one of the authors for community curation.

(It might confuse people to see'curation is in progress' if they have ignored my e-mails.  Or they may think that another author is doing it. I think it's better to be precise here).

**Comment by kimrutherford** [comment]
I've made that change.
