### ISSUE TITLE
News item (Angeli)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1484]
AnGeLi   (developed by Danny Bitton) is an enrichment tool that allows you to perform enrichments over gene lists. Angeli was recently updated with PomBase ontology data from 04-03-2020 to provide 9320 lists  including ontology terms annotated by PomBase, and many additional datasets from the Bahler laboratory.

**Comment by ValWood** [comment]
thumbnail
<img width="226" alt="Screenshot 2020-03-09 at 16 16 42" src="https://user-images.githubusercontent.com/7359272/76234977-56080e00-6222-11ea-9bda-c6a4478e5194.png">

**Comment by ValWood** [comment]
date added, news item can go live

**Comment by ValWood** [comment]
@mah11 can you check this?
https://github.com/pombase/website/commit/9a012d0a391ef552e1951fb473f79d1e555fd3e9

**Comment by ValWood** [comment]
angeli.png

**Comment by mah11** [comment]
What do you want me to check about it?

**Comment by ValWood** [comment]
Does it look OK. I only did one before and I f**ed it up.
I wasn't sure if I got the mark-up right.
Or if the text needs teweaking

**Comment by mah11** [comment]
OK, here's what I did:

corrected the flags to:

     
     

put the thumbnail where it needs to go (src/assets/newsfeed)

edited the text, mainly to make it less redundant
