### ISSUE TITLE
 search on synonyms is not working?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1486]
I could not search in dss1? or sem1?

That might be the problem Maria was experiencing?

**Comment by ValWood** [comment]
rai1
rat1

(this is pretty recent, it used to work I think?)

**Comment by ValWood** [comment]
Also -  Maria has reported that here problem appears to be browser-specific. 
cdc2 works using Chrome, but not on Firefox

**Comment by ValWood** [comment]
and ortholog searches
e.g. YKL077W  (https://www.pombase.org/gene/SPCP31B10.04)

(me, Chrome)

**Comment by ValWood** [comment]
I'm getting the same issue MAria reported earlier. Searching on cdc2 is giving me nothing???

**Comment by ValWood** [comment]
GO IDs usually work too, but they are not working today in the simple search or the Advanced search

**Comment by kimrutherford** [comment]
Sorry about that.  I'm working on a fix now.

**Comment by ValWood** [comment]
no worries.

Systematic IDs also affected.

**Comment by kimrutherford** [comment]
That's fixed now by reverting the change that caused the problem.  I had updated all the supporting Javascript libraries to their most recent versions.  That shouldn't have caused a problem as the updates are bug fixes.  I'm going to leave this open and dig deeper later.

**Comment by kimrutherford** [comment]
> I'm going to leave this open and dig deeper later.

I've updated to the most recent release of the Javascript libraries and it all seems OK.

Also it fixes the problem (for me at least) that list of completions for the search box wasn't always visible.  For example, sometimes I'd type "cdc2" and nothing would show until I pressed space.  That's fixed now.
