### ISSUE TITLE
Implement GO ids in  advanced tool download spreadsheet

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1487]
User request helpdesk ticket Request 7629

**Comment by kimrutherford** [comment]
Should we have one column per aspect, with the GO IDs separated by commas?  That's easy to implement but is it useful?

**Comment by ValWood** [comment]
I think that is what the user wants. It would. be fine if they were then going to manipulate the data in R or whatever (i.e something which  can interpret the hierarchy). But if they wanted to use these GO IDs to summarize annotations I would be worried. Hold on for now and I will check how the user wants to use them.

**Comment by kimrutherford** [comment]
Maybe GAF download would make more sense for that user?: https://github.com/pombase/website/issues/949

**Comment by kimrutherford** [comment]
> Hold on for now and I will check how the user wants to use them.

Any news?

**Comment by ValWood** [comment]
nope....

**Comment by ValWood** [comment]
duplicate of https://github.com/pombase/website/issues/949
