### ISSUE TITLE
[phenotype querying weirdness

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1488]
No results for: increased cortical endoplasmic reticulum remodeling (FYPO:0007273) [single allele genotypes]

but
https://www.pombase.org/reference/PMID:32023460

**Comment by ValWood** [comment]
also
No results for: decreased histone H4-K12 acetylation during vegetative growth (FYPO:0005014) [single allele genotypes]

but
https://www.pombase.org/term/FYPO:0005014

**Comment by ValWood** [comment]
I think it might be all phenotypes ;)

**Comment by kimrutherford** [comment]
Sorry about that! I'm not having a good week. I'm working on a fix.

**Comment by kimrutherford** [comment]
I've temporarily reverted to the previous day's release while I investigate.

**Comment by kimrutherford** [comment]
Sorry about the bug.  It's fixed now.
