### ISSUE TITLE
display of relationaship type for residues bound

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1489]
The  Canto GOGAF export identified

"residue" annotations on MF terms

mf.gaf:PomBase SPAC12B10.10 nod1 GO:0005515 PMID:23966468 IPI PomBase:SPAC31A2.16 F medial cortical node Gef2-related protein Nod1 protein taxon:4896 20141023 PomBase residue(957-1101)
mf.gaf:PomBase SPAC6F6.16c tpz1 GO:0005515 PMID:24013504 IPI PomBase:SPAC19G12.13c F shelterin complex subunit Tpz1 mug169|SPAC6F6.18c protein taxon:4896 20131112 PomBase residue(426-450),part_of(GO:0032211)
mf.gaf:PomBase SPAC6F6.16c tpz1 GO:0005515 PMID:24013504 IPI PomBase:SPAC26H5.06 F shelterin complex subunit Tpz1 mug169|SPAC6F6.18c protein taxon:4896 20131112 PomBase residue(488-499),happens_during(GO:0032211)
mf.gaf:PomBase SPBC27B12.02 mis19 GO:0005515 PMID:24774534 IPI PomBase:SPCC970.12 F centromere protein Mis19/Eic1 eic1|kis1|SPBC30B4.10 protein taxon:4896 20140605 PomBase residue(4-63)
mf.gaf:PomBase SPBC27B12.02 mis19 GO:0005515 PMID:24774534 IPI PomBase:SPCC1672.10 F centromere protein Mis19/Eic1 eic1|kis1|SPBC30B4.10 protein taxon:4896 20140605 PomBase residue(53-112)

These identify the region of a protein where binding occurs.
I think these are be quite useful, although I forgot that we can do this.

The annotations display in PomBase, but the qualifier is a bit strange:

https://www.pombase.org/gene/SPAC31A2.16
modified residue 329-419
should instead say
"residues bound"

**Comment by mah11** [comment]
This is weird because there's nothing in the config files (I looked at both Canto extensions and website display) for "residue" extensions on GO annotations. The "modified residue" phrase only appears under PSI-MOD in the website config, where it makes sense; I don't see how it's getting into the display for anything in the GO department.

So I'm not moving this to the config tracker ;)

**Comment by kimrutherford** [comment]
> This is weird because there's nothing in the config files

It's an awkward case that is currently hard coded.  The residues are displayed like extensions but aren't stored that way.  So there is a bit of special case code to handle it:
  https://github.com/pombase/website/blob/fae1141244bc56dda66abbd450ccaaaddc4a7b2f/src/app/pombase-api.service.ts#L1223-L1229

I've changed the code and the fix should be visible soon.  I'll check later.

**Comment by kimrutherford** [comment]
> I've changed the code and the fix should be visible soon. I'll check later.

Turns out that the code I pointed out is obsolete and I've now removed it.  That was website code.  The "modified residue" text is in the code that processes the data from Chado to feed to the website.

Before I change that code: should the text be changed to "residues bound" just for MF annotations?  And is it all MF annotations or just a sub-set?

**Comment by ValWood** [comment]
actually can we use the phrase "binding site" instead?

I think this will be quite useful. Users can figure it our from deletion phenotypes but it is quite tricky to do. If we know the binding region we should annotate it.

It only applies to MF "protein binding" (for the descendants, but we don't really use those)

**Comment by kimrutherford** [comment]
> It only applies to MF "protein binding" (for the descendants, but we don't really use those)

Thanks.  It's not quite a quick fix so I'm going to leave this for a while.  Let me know if it becomes more urgent.

**Comment by kimrutherford** [comment]
I think I've fixed this now.  I'll check on Monday morning.

The name displayed for residue properties can now be configured using the `extension_display_names` field in the config file (`pombase_v2_config.json`):
```json
    {
      "rel_name": "modified residue",
      "if_descendant_of": "GO:0005515",
      "display_name": "binding site"
    }
```
