### ISSUE TITLE
"with/from" field compacting and hyperlinking

### ISSUE THREAD

**Issue by ValWood** [pombase/website#149]
at present we display:

- [x] cdc13 for (PomBase:SPBC582.03)

For these
UniProtKB-KW:KW-0067
UniPathway:UPA00031
UniProtKB-SubCell:SL-0022
InterPro:IPR000058
PANTHER:PTHR1092/Panther:PTHR31492 (CHECK CORRECT CASE)
Pfam:PF00005
SMART:SM00317
Prosite:PS01164
I don't think our users pay much attention to these sources anyway. We could just hyperlink the object ID (KW-0067, UPA00031, IPR000058 etc), and have the full  prefix:ID visible only via a mouse over). This would save quite a bit of space on some pages where these are often the only with field entries.

These are OK
EC:1.1.1.100
PDB:1TA9

MODS
-----
These are all fine (they are very rarely used anyway, most only a couple of times)
AGI_LocusCode:AT4G20910
ECOGENE:EG10451
FB:FBgn0004837
MGI:101917
WB:WBGene00000988
dictyBase:DDB_G0269150  
RGD:621834

This one is special, because we have  6669 of them.
SGD:S000000002

I nicer display for users/ and a space saver would be SGD:VPS8 so they immediately know which gene (would this be bad practice if   you could see  SGD:S000000002 by mouse over?)

Kim do you know where to access the information to make the hyperlinks for the above?

The display text/mouse over  part of this could be Yaml  file for curators?

**Comment by kimrutherford** [comment]
> Kim do you know where to access the information to make the hyperlinks for the above?

Yep, the web code needs to use GO.xrf_abbs

I think this overlaps with: #65

**Comment by ValWood** [comment]
It overlaps with #65 in that that answers the question that you know where  to get the hyperlinks from.

The other part I would like input from @mah11  and @Antonialock  about whether sensible...
If no consensus we can iron out on Tuesday...

**Comment by ValWood** [comment]
particularly:

(would this be bad practice if you could see SGD:S000000002 by mouse over?)

**Comment by ValWood** [comment]
OK, Hope this is a good plan.

For all "with" column (except the PomBase ones which are fine as the are)

i) Display only the ID as the link. 
ii) Display the prefix by mouse over

(this means SGD will use S000000002)

We can reassess  whether we show the  prefix too once we get rid of (suppress) the remaining 4000 IEA annotations ;)

It may seem a little unconventional, but
i) it matches what SGD do
ii) Users pay little attention to the sources of inferred information. Also the source is often arbitrary (in fact we flip-flop between which source we used for many annotations of this type dependent on the parsing.

However, this will change once this ticket is implemented:
https://github.com/pombase/pombase-chado/issues/594
(this ticket will also substantially reduce the number of  with fields from IEAs)

**Comment by kimrutherford** [comment]
> i) Display only the ID as the link.
> ii) Display the prefix by mouse over

I've done that.  I got a bit carried away and did for external IDs in extensions too.  Does that make sense?

**Comment by ValWood** [comment]
I think for now we  should keep them in extensions. Probably we will handle some(most) of these differently by having  "natural language" in most cases.
We have discussion tickets about how to display PRO ID labels.
For most things (like" GO terms we already show descriptions rather than IDs...)

**Comment by kimrutherford** [comment]
I've put the prefixes back on the external IDs in extensions.

I think this is done now.
