### ISSUE TITLE
news item talks

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1494]
Virtual PombeTalks, Wednesday the 29th of April at 17:00 Central European Time.
Aleksandar Vjeṧtica, Sophie Martin’s lab, University of Lausanne
Cycling for reproductive fidelity: Coupling the cell cycle and re-fertilisation blocks ensures ploidy maintenance during sexual lifecycle

Haitong Hou, Julia Cooper’s lab, NCI, NIH/ University of Colorado
Centromeres are dismantled by foundational meiotic proteins Spo11and Rec8

To attend, join pombelist or @PombeSlack for the Zoom link details.
Mark your calendar for the next two on May 13 and May 27! Same place, same time.  

If you would like to speak at a future session, please fill out this form https://docs.google.com/forms/d/e/1FAIpQLSdjnkJfadUwM2eKIBJBQXeLt3aOfzrQEb3D8lvNym1g93DIRQ/viewform

**Comment by mah11** [comment]
image attached to https://github.com/pombase/pombase-config/issues/12

**Comment by ValWood** [comment]
this can go live if you can do it, tweak as necessary
