### ISSUE TITLE
news item chromatin silencing (soon)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1497]
Thumbnail:
<img width="460" alt="Screen Shot 2020-04-24 at 14 51 12" src="https://user-images.githubusercontent.com/7359272/80220020-275fbe80-863b-11ea-98b8-66aac960498b.png">

Title
Changes to GO and annotation review (chromatin silencing).
Body
Working with the GO consortium we have removed "chromatin silencing" (a phenotype) from GO (which represents normal processes that individual gene products are directly involved in). Chromatin silencing in GO was a legacy term and conflated various heterochromatin assembly, formation, and maintenance pathways with more indirect processes that affect repression mediated by chromatin more indirectly (i.e. tethering to the nuclear envelope).  "Chromatin silencing" terms remain available in our phenotype ontology "FYPO".  Existing annotations to Gene Ontology chromatin silencing terms were reviewed and either removed or reannotated based on what could be inferred from the phenotypes. This has provided a revised heterochromatin assembly annotations <<https://www.pombase.org/term/GO:0031507>>. Further work is required so please mail us with any corrections.

**Comment by ValWood** [comment]
Need to
1. check heterochromatin assembly is not a child of silencing
2. Check silencing  annotation is purged

**Comment by ValWood** [comment]
check subtelomeric heterochromatin assembly is under heterochromatin assembly
check heterochromatin island assembly is under heterochromatin assembly

**Comment by mah11** [comment]
ping when everything else is ready and I'll do the text

**Comment by ValWood** [comment]
Hopefully tomorrow, definitely by Monday...

**Comment by ValWood** [comment]
double check these form my toDO list

LATER, STILL WAITING FOR PASCALE
chromatin silencing at telomere
conversion of ds siRNA to ss siRNA involved in chromatin silencing by small RNA
heterochromatin assembly involved in chromatin silencing by small RNA
negative regulation of chromatin silencing by small RNA
regulation of chromatin silencing by small RNA
When these are done, can announce heterochromatin changes and send out sessions

**Comment by ValWood** [comment]
chromatin silencing at telomere
 conversion of ds siRNA to ss siRNA involved in chromatin silencing by small RNA

are still present, but annotations are purged in pombase and will disappear from GO soon so we can go ahead with this.

**Comment by ValWood** [comment]
This one can go live now
