### ISSUE TITLE
GO update?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1499]
did Our GO update? I am waiting for a change that has appeared in quickgo, but not in pombase, which is unusual...

**Comment by mah11** [comment]
Ontology structure or annotations?

The GAF was last updated for GO on 2020-04-20 (because I had this past Monday off).

The CV Versions page (click the grey "database created ..." text at the bottom right of the home page) says the website is using the releases/2020-04-27 ontology.

**Comment by kimrutherford** [comment]
What's the change?  I can check the OBO file if it helps.

**Comment by ValWood** [comment]
ontology. That's weird then.

I'm still seeing heterochromatin assembly propagating to "chromatin silencing"

that  was definitely  removed before 27th...I will take another look...

**Comment by ValWood** [comment]
heterochromIN assembly
https://www.ebi.ac.uk/QuickGO/term/GO:0031507
should not have
"chromatin silening" as an ancestor.
In quickGO it doesnt

**Comment by ValWood** [comment]
In pombase
heterochromatin assembly (GO:0031507)
is a
heterochromatin organization involved in chromatin silencing (GO:0070868)
is_a chromatin silencing (GO:0006342)

**Comment by ValWood** [comment]
ignore. I thought it was 27th.
We updated 27th
QuickGO updated 28th
Today is 29th.

**Comment by kimrutherford** [comment]
OK.  Let me know if it's still there tomorrow.

**Comment by kimrutherford** [comment]
That relation is gone from today's GO OBO file so it should be gone from the website in the morning.

**Comment by ValWood** [comment]
all good.
