### ISSUE TITLE
iPTMnet

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#15]
integrate iPTMnet "Interactive Sequence view"
at least as an image
see here for an example:
http://research.bioinformatics.udel.edu/iptmnet/entry/P06493/

also their sequence alignment is cool, see here
http://research.bioinformatics.udel.edu/iptmnet/visual/msa/tree/P06493/

**Comment by ValWood** [comment]
It would be great if this is available as a web service (I think we have asked about this already?).
There is a bug if you click  try the browse option and click 'fission yeast' (needs reporting)

**Comment by ValWood** [comment]
We can link to this view quite soon
http://research.bioinformatics.udel.edu/iptmnet/entry/Q09170/
but ideally long term we would want to
a) enbed widget in gene  page
b) with ability to  toggle the alignment view on the fly?
c) widget would ideally also display extension on mouse over (added by, removed by etc)

**Comment by ValWood** [comment]
Also look at 
dbPAF: an integrative database of protein phosphorylation in animals and fungi.

**Comment by ValWood** [comment]
again, will be very cool....

**Comment by mah11** [comment]
as a first step, added to external links for #477

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/website/issues/143
