### ISSUE TITLE
news item, mitochondrial geneome update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1500]
The mitochondrial genome sequence in PomBase has been updated to the sequence provided in Tao et. al < https://www.ncbi.nlm.nih.gov/pubmed/31364709
>. This work corrects  20 errors in the reference mitogenome. The annotations of mt-tRNAArg(UCU) and mt-tRNAGlu(UUC) were revised. 

@lilindu is this correct?  we have 3 annotated introns now but before we had 3?

https://github.com/pombase/curation/issues/2497

**Comment by ValWood** [comment]
Actually all 3 annotated  introns were already known (and annotated).
Am I missing something?

**Comment by ValWood** [comment]
We can use this image for the thumbnail :

<img width="471" alt="Screen Shot 2020-04-30 at 17 12 31" src="https://user-images.githubusercontent.com/7359272/80733573-d00f9180-8b05-11ea-889c-f4df099f3fc2.png">

**Comment by ValWood** [comment]
I think I get it, the new introns are in other strains?

**Comment by lilindu** [comment]
Yes, the new introns we discovered are present in some non-reference strains but not in the reference strain.

**Comment by ValWood** [comment]
note from Kim:
The load failed again.  It looks like SPMIT.04 is slightly shorter now
so the predicted TM domains have the wrong coordinates.  One domain has
an end coordinate off the end of the new protein sequence and the code
that generates the web site died because of that.  I've fixed the code
to print a warning instead and I've restarted the load.

**Comment by kimrutherford** [comment]
As far as I can tell the load worked so the news item now matches the database and website.

There are two issue to look at:

  - https://github.com/pombase/website/issues/784  (fix the reverse mito. strand in JBrowse)
  - https://github.com/pombase/pombase-chado/issues/772  (update InterPro to fix the TM domains)
