### ISSUE TITLE
news item, community curation paper

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1501]
anyone want to have a stab? 

Suggest

@Antonialock 
@mah11

**Comment by Antonialock** [comment]
A paper describing the PomBase community curation effort has been published in Database (https://academic.oup.com/database/article/doi/10.1093/database/baaa028/5827230?searchresult=1). We share our strategy, progress, and the insights we have gained from the project.

**Comment by ValWood** [comment]
How about 

Our paper describing the PomBase community curation project is now published in Database (https://academic.oup.com/database/article/doi/10.1093/database/baaa028/5827230?searchresult=1). We share our progress,  and identify the benefits of community curation. An unexpected gain is the improvement in annotation quality of both professional curators and community curators from the curation-and-review cycle. 

I'm thinking that this could provide a hook for people who have not curated yet.  ...and it   might remove some of the barrier if people are worried about doing it wrong,  as it makes it clear there is some dialogue and a checking process?

**Comment by Antonialock** [comment]
Sounds good!

**Comment by ValWood** [comment]
Nice revision @mah11 !

**Comment by Antonialock** [comment]
xD yes thanks
