### ISSUE TITLE
Explore Pombase spot, communty curation takeover

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1502]
Although not strictly an "Explore PomBase"

Can we have something along the lines:

Community Curation: Most suitable  fission yeast papers are now author curated ~PomBase users now curate their own papers~. Find out how you can benefit in our new publication "Community curation in PomBase: enabling fission yeast experts to provide detailed, standardized, sharable annotation from research publications" (https://academic.oup.com/database/article/doi/10.1093/database/baaa028/5827230#.XqvRaBbbKsY.twitter)
and take the plunge here <https://curation.pombase.org/pombe>

pinned to this slot
<img width="531" alt="participation,spotlight" src="https://user-images.githubusercontent.com/7359272/80798682-dac93580-8b9c-11ea-97d1-3660f9c562bd.png">

**Comment by ValWood** [comment]
@mah11 can you word this in such a way that it is true without it being as wordy.
It isn't  'most authors' its most suitable publications

**Comment by mah11** [comment]
> pinned to this slot

does this mean take everything else out of the rotation?

**Comment by ValWood** [comment]
>does this mean take everything else out of the rotation?
yop, but I don't think it is rotting at the moment anyway  (the open biology paper is currently  'pinned')

**Comment by ValWood** [comment]
rotating!

**Comment by mah11** [comment]
>  don't think it is rot[a]ting at the moment anyway (the open biology paper is currently 'pinned')

not true

**Comment by mah11** [comment]
I've put it in without the paper title, because that's what was making it so long & wordy. I can add it back if you think it's important enough to take up the space. (Closing this in the meantime tho.)

**Comment by ValWood** [comment]
Yeah that was definitely too much text for that box!
