### ISSUE TITLE
Altmetrics scores

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1505]
You can embed the free Altmetric badge for this research output on your website, CV, or blog. Just copy and paste the code below into the HTML of your page:

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div class="altmetric-embed" data-badge-type="donut" data-altmetric-id="80942203" />

we might as well, we have good attention scores...

e.g. 
Unknowns paper 85

MOD paper 19 (1st percentile (ranked 1st) of the 1 tracked articles of a similar age in BMC Biology)

https://www.pombase.org/about/published-by-pombase

**Comment by mah11** [comment]
duplicates #1166
