### ISSUE TITLE
news item: switch from DO to Mondo

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1506]
Rationale: better inferences
What is included: i.e only genes known to be disease-causing, not candidate genes. Not biomarkers
Metrics: increase in number  of assignments (annotations and genes) 
Slim: ?  existence, and improvements
Anything else? future plans?

Before snapshot for reference:
<img width="444" alt="Screenshot 2020-05-02 at 13 53 57" src="https://user-images.githubusercontent.com/7359272/80864735-6cf43b00-8c7c-11ea-8f49-4d7c5ceab913.png">

**Comment by ValWood** [comment]
How many human genes have a disease association. I thought Alliance would have this onf. I found a spreadsheet but I'm a bit puzzled. It has things like this:

NCBITaxon:9606	Homo sapiens	gene	HGNC:8959	PIGB	implicated_via_orthology	DOID:10112	sleeping sickness	SGD:S000003110			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance

So a human disease,  automatically asserted by ortholog to SGD. That sounds a bit bonkers? why not use the primary source?

**Comment by ValWood** [comment]
and I'm not sure what "implicated_in" means
I gues it means disease causing?

This is baffling me though

NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	implicated_via_orthology	DOID:2717	Bloom syndrome	SGD:S000004802			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	implicated_via_orthology	DOID:2717	Bloom syndrome	MGI:1328362			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	implicated_via_orthology	DOID:2717	Bloom syndrome	FB:FBgn0002906			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	implicated_via_orthology	DOID:5688	Werner syndrome	SGD:S000004802			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	implicated_via_orthology	DOID:2717	Bloom syndrome	WB:WBGene00001865			ECO:0000501	evidence used in automatic assertion	MGI:6194238	20200401	Alliance
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	is_implicated_in	DOID:2717	Bloom syndrome				ECO:0007191	inference by association of genotype from phenotype used in manual assertion	RGD:7240710	20180130	HUMAN
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	is_implicated_in	DOID:2717	Bloom syndrome				ECO:0007191	inference by association of genotype from phenotype used in manual assertion	PMID:9388480	20180130	HUMAN
NCBITaxon:9606	Homo sapiens	gene	HGNC:1058	BLM	is_implicated_in	DOID:2717	Bloom syndrome				ECO:0007191	inference by association of genotype from phenotype used in manual assertion	PMID:10779560	20180130	HUMAN


why do this. We know BLM is causing Bloom Syndrome and Werner Syndrome. I don't see what inference is necessary from other species. Right. Filtering anything by ortholog...

**Comment by ValWood** [comment]
grep -v "biomarker_via_orthology" DISEASE-ALLIANCE_HUMAN_57.tsv |  grep -v "is_marker_for" | grep -v "implicated_via_orthology" | cut -f 4 |sort |uniq |wc
    4339  
I removed the biomarkers and the implicated by orthology filtered on non redundant gives 4339 human genes. @Antonialock  is that number ball park right?

interesting factoid
4339 disease causing genes /19737   21.98%
pombe 1005 disease gene othologs/ 5067 proteins 19.83%

(it would. be funny if the remapping gets us over 1113 because then pombe would have a higher percentage  of human disease-associated genes than human  ;)))

**Comment by ValWood** [comment]
Waiting for
https://github.com/pombase/website/issues/1108

**Comment by ValWood** [comment]
we can cite this in the announcement from Feb 2020
https://www.genetics.org/content/214/2/233#:~:text=It's%20fair%20to%20say%20that,genes%20have%20already%20been%20solved.

**Comment by ValWood** [comment]
we can cite this in the announcement from Feb 2020
https://www.genetics.org/content/214/2/233#:~:text=It's%20fair%20to%20say%20that,genes%20have%20already%20been%20solved.


It’s fair to say that progress in identifying disease genes has been spectacular. Disease-gene associations are now being discovered at a rate of 300 per year (∼5 per week!); ∼5400 diseases caused by variants in 3800 genes have already been solved.

we should sanity check this figure because I got a much higher number of genes from the Alliance (above), although to be fair it wasn't really clear what I was looking at....

**Comment by ValWood** [comment]
@mah11  this is the stuff I wanted to say in the news item. it's quite long but I think it would be nice to record all of this. Can you massage the text?


PomBase disease gene curation associates disease descriptors with fission yeast orthologs of human disease causing genes. We have recently added more gene-disease term connections increasing the number of disease genes  to 1183 (from 907 in Jan 2019) and the number of individual disease associations from *** to ****. This provides disease annotations 23.05% of fission yeast protein coding genes (33.4% of protein coding genes with human orthologs).

We have also remapped our disease curation to Monarch disease Ontology (MONDO) from the Disease Ontology (DO). MONDO (add URL) contains all of the disease concepts in DO but has richer links to 'ancestor' terms proving more inferences to 'general' disease classifiers (e.g. anemia, cancer, kidney disease) in our 'Disease slim set' (https://www.pombase.org/browse-curation/disease-slim).
The PomBase disease slim set is is a work in progress. We are collaborating with MONDO to improve the inferences, particularly to revise the number of monogenic disorders (one classifier which has decreased from the existing disease slim). 
We will continue to improve the slim set to provide better coverage of  each of the orthogonal types of descriptors i.e. multicellular systems or tissue level (e.g. dystonic disorder), cell level (lysosomal disorder), or mode of inheritance (autosomal dominant disease). If there is a particular disease grouping that you would find useful in the disease  set, please let us know.

**Comment by kimrutherford** [comment]
> number of individual disease associations from *** to ****.

It was 2588 on 2020-05-10.  It's now 3954 after the MONDO update.

**Comment by ValWood** [comment]
I am just about to check the actual human coverage in MONDO is ball park the same as the numbers  quoted in that paper.

**Comment by ValWood** [comment]
>I am just about to check the actual human coverage in MONDO is ball park the same as the numbers quoted in that paper.

It was.  3883.

**Comment by ValWood** [comment]
This could also be 2 announcement. 

One about the increased numbers, new assignments.

One about the migration and the new slim giving better classification.

That might be more digestable, and it is really 2 separate, although related blocks of work.

**Comment by mah11** [comment]
I made the Mondo news item pretty brief & newsflash-y. Here's a longer version you can use for the pombelist email - it includes the monogenic disorder business and some other bits I cut from the news (they detracted from the journalistic punchiness):

PomBase has switched from the [Disease Ontology](https://disease-ontology.org/) (DO) to the Monarch Initiative's [Mondo Disease Ontology](https://mondo.monarchinitiative.org/) (Mondo) for disease gene curation. Mondo covers the same set of disease descriptions as DO, but has a richer hierarchical structure that classifies more specific descriptions into broad categories (e.g. anemia, cancer, kidney disease). Accordingly, PomBase has created a fission yeast slim using Mondo terms that group diseases by various orthogonal aspects such as tissue or system level (e.g. digestive system disease), cell or organelle level (e.g. lysosomal storage disease), or mode of inheritance (e.g. autosomal dominant disease). 

PomBase curators are also collaborating with Mondo to improve its disease classification, especially in areas that will affect fission yeast disease annotation inferences in the new [PomBase Mondo slim](https://www.pombase.org/browse-curation/disease-slim). For example, we are reviewing monogenic disorders, as it is one of a few classifiers that has fewer fission yeast genes associated via the new slim than in the old one. The new disease slim is a work in progress, so if there is a particular disease grouping that you would find useful, please [let us know](mailto:helpdesk@pombase.org).

**Comment by mah11** [comment]
This ticket never did get back to an updated "explore pombase" entry. Open a new ticket with a new graphic (or link to one) for it, so it doesn't get lost in all the news drafts here.

**Comment by ValWood** [comment]
Thanks! all good.
