### ISSUE TITLE
EMBL/Genbank format export from JBrowse (is this possible?)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1509]
A few times we have had requests for the java applet (via the survey and helpdesk).

It seems that historically one of the uses of this was to export EMBL format (for a specific region). I have pointed to the desktop Artemis, but I wondered if there  is a  (configurable) JBowse option to export highlighted region (I looked but could. not find)

**Comment by mah11** [comment]
sadly, not available at present, so you'd have to request it from the JBrowse developers

https://jbrowse.org/docs/data_export.html

**Comment by ValWood** [comment]
I asked.
But I see this says you can export gff.  But I could not see how to do that....

**Comment by mah11** [comment]
At least some of the data tracks (including the handful I spot-checked) do offer GFF3 as an option, but the sequence track doesn't. Maybe that's a config thing that @kimrutherford could investigate; I know no more.

**Comment by kimrutherford** [comment]
> But I could not see how to do that....

It's "Save track data" in the menu beside each track name:
![save-track-1](https://user-images.githubusercontent.com/90474/81170373-aca98280-8fee-11ea-8d5e-040ac0e435be.png)

**Comment by ValWood** [comment]
But only the entire track not a selected region?

**Comment by ValWood** [comment]
Yeh you can do visible region, or entire track, but not specific coordinates, it seems?

**Comment by ValWood** [comment]
Oh but you can change the region you are viewing I guess...

**Comment by kimrutherford** [comment]
> Oh but you can change the region you are viewing I guess...

Yep, or put the range you need in the box at the top.

**Comment by cmdcolin** [comment]
using the highlight tool, which can specify an exact range, also adds an extra option to the Save track data to export highlighted region. the region that you enter into the "location search box" e.g. the one next to the zoom buttons sometimes ends up being slightly different than what gets loaded for some weird technical reasons, the highlight tool->exact range->save data->export highlighted region is the best way to get exact

**Comment by cmdcolin** [comment]
using view->set highlight you can specify the exact highlight coordinates

**Comment by ValWood** [comment]
OK thanks!

@mah11  can we add this to our FAQ as a way to export  gff?
The user who based has managed to get the EMBL via Ensembl so that could be a stop gap.

**Comment by mah11** [comment]
> can we add this to our FAQ as a way to export gff?

Would it make sense to phrase the question as "what formats can I export from the genome browser"? (i.e. rather than specifically "can I get gff" or "can I get embl format?")

> The user who based has managed to get the EMBL via Ensembl so that could be a stop gap.

Does this part require any action?

**Comment by ValWood** [comment]
What   formats can I export from the genome browser is OK.


but the thing I think most people want to do is  "extract a region" rather than download the entire  track (otherwise they could just use the  gff download file) , so it would be great if the answer would convey that part is covered.

"How do I export/What formats can I export"  my sequence  **region** of interest  from JBrowse

(This stuff might even be covered in the quickstart  guide that Antonia did?)

**Comment by ValWood** [comment]
I should read that!
