### ISSUE TITLE
small  genotype (wild type) rendering issue, plus deletion display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#151]
![wild type](https://cloud.githubusercontent.com/assets/7359272/22712135/97319c1c-ed7b-11e6-9fdf-daf12c09eaca.jpg)

also, every time a genotype contains string delta, display Δ

**Comment by mah11** [comment]
wild type should be displayed as "yfg1+"

**Comment by kimrutherford** [comment]
> wild type should be displayed as "yfg1+"

Whoops, fixed.

**Comment by kimrutherford** [comment]
I've changed things to show a delta symbol.
