### ISSUE TITLE
News item: InterPro version 79

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1511]
PomBase now uses InterPro Version 79.0

PomBase now uses InterPro Version 79.0, which integrates 
* 128 new InterPro entries
* An update to PIRSF [3.10].
* Integration of 151 new methods from the SUPERFAMILY (4), CATH-Gene3D (6), PIRSF (9), PANTHER (106), CDD (26) databases.
InterPro cites 48466 publications in PubMed. See the InterPro release notes for further information.

 (Oddly the number of cited publications dropped?)

**Comment by ValWood** [comment]
https://github.com/pombase/pombase-chado/issues/772#issuecomment-623829515

**Comment by kimrutherford** [comment]
I've added the news item.
