### ISSUE TITLE
revise disease ontology blurb and links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1518]
From

> http://desktop.kmr.nz:4242/browse-curation/disease-slim

The text on that page needs updating.

Here's the current text.  Let me know what you'd like instead.

---------------

Disease Ontology slim

A “slim” is a high-level subset of terms from an ontology, used to analyze sets of annotated genes. The table below shows a slim set of grouping terms that we have selected from the Disease Ontology (DO), and the number of annotations to each term. DO IDs link to PomBase ontology term pages. The annotation totals link to pages with information about the term and a list of annotated genes. A gene may be included in the annotation sets for more than one slim term.

If you would like to have any terms added to the DO slim, please contact the helpdesk.

**Comment by ValWood** [comment]
Disease Ontology slim

A “slim” is a high-level subset of terms from an ontology, used to analyze sets of annotated genes. The table below shows a slim set of grouping terms that we have selected from the Monarch Disease Ontology (MONDO), and the number of annotations to each term. MONDO IDs link to PomBase ontology term pages. The annotation totals link to pages with information about the term and a list of annotated genes. A gene may be included in the annotation sets for more than one slim term.

If you would like to have any terms added to the POmBase MONDO slim set, please contact the helpdesk.

**Comment by ValWood** [comment]
@mah please proof

Also we need a suitable link out...

**Comment by ValWood** [comment]
from
https://github.com/pombase/pombase-chado/issues/751
We also need to change the "External links" section on the term pages to point to MONDO. What should we link to?

http://desktop.kmr.nz:4242/term/MONDO:0004992

**Comment by kimrutherford** [comment]
> We also need to change the "External links" section on the term pages to point to MONDO.
> What should we link to?

I had a look and Monarch looks like an easy option:
https://monarchinitiative.org/disease/MONDO:0006025

**Comment by ValWood** [comment]
Perfect (although slow to load!)

**Comment by ValWood** [comment]
OK @kimrutherford  go with these changes, we can revise later, but should. be OK as mainly straight swap

**Comment by mah11** [comment]
blurb looks fine (it's essentially the already-reviewed old one with s/DO/MONDO/g)

**Comment by kimrutherford** [comment]
I've updated my desktop version with the text: http://desktop.kmr.nz:4242/browse-curation/disease-slim

> Suggest: Disease Ontology slim

Do you still wan to say "Disease Ontology" in the title?

**Comment by ValWood** [comment]
Monarch disease ontology  slim?

@mah11 ?

**Comment by kimrutherford** [comment]
> Monarch disease ontology slim?

Changed in my desktop version:
http://desktop.kmr.nz:4242/browse-curation/disease-slim

**Comment by ValWood** [comment]
cant reach right now
