### ISSUE TITLE
source info in JBrowse

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1519]
The feature source always says "PomBase" but  should display the PMID   of the supporting db_xref (especially for features) 
i.e the one we display for source coordinates on pombase pages

https://www.pombase.org/jbrowse/?loc=mitochondrial%3A1..14627&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CDNA%20sequence&highlight=

**Comment by ValWood** [comment]
ACtually for the mitochondrial geneomethe features afre not showing the new 'sources'

https://www.pombase.org/gene/SPMIT.09

but the wtf's do show this info
https://www.pombase.org/gene/SPCC1620.02

also  we get an error for the mitochondrial Genome in  JBrowse (it displays OK  but says there was an error for the reverse stand). But all of the features are on one strand....

**Comment by kimrutherford** [comment]
> Also we get an error for the mitochondrial Genome in JBrowse (it displays OK but says there
> was an error for the reverse stand). But all of the features are on one strand....

There's a separate issue for that: #784

**Comment by kimrutherford** [comment]
> The feature source always says "PomBase" but should display the PMID of the supporting db_xref

That's the Source column from the GFF file.  I think "PomBase" is correct.  I'll add a Dbxref attribute to the files and see if that's visible in JBrowse.

https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

"The source is a free text qualifier intended to describe the algorithm or operating procedure that generated this feature. Typically this is the name of a piece of software, such as "Genescan" or a database name, such as "Genbank." In effect, the source is used to extend the feature ontology by adding a qualifier to the type creating a new composite type that is a subclass of the type in the type column."

**Comment by kimrutherford** [comment]
> but the wtf's do show this info
> https://www.pombase.org/gene/SPCC1620.02

The source comes from the /db_xref of the feature in the contig file.  SPCC1620.02 has:
```
FT                   /db_xref="PMID:30991417"
```

**Comment by ValWood** [comment]
OK, the source does display for the features  where the gene coordinated changed, e.g.
https://www.pombase.org/gene/SPRRNA.01
so this is OK
