### ISSUE TITLE
pipe separated with field

### ISSUE THREAD

**Issue by ValWood** [pombase/website#152]
displays only the entry before the pipe

(check comma separated behaviour too)

**Comment by mah11** [comment]
shouldn't this be a non-issue anyway? we should always have separate annotations instead of pipe separation ...

**Comment by mah11** [comment]
comma-separated entries do have a problem, though, as described

**Comment by ValWood** [comment]
There are some pipe separated one for IC (2 GO Ids required)
The pipe in the with/from filed used to mean "required together.

Maybe GO changed this, so that it matched the annotation extension filed.....I know it was discussed.... but was it implemented?

Of crikey now I have no idea what we  are supposed to do, or what we actually do!

**Comment by mah11** [comment]
> There are some pipe separated one for IC (2 GO Ids required)

not any more

> The pipe in the with/from filed used to mean "required together.
> 
> Maybe GO changed this, so that it matched the annotation extension filed.....I know it was discussed.... but was it implemented?

GO did change a while back (maybe a year or so ago?), so "both required" is now indicated by comma-separated entries for with/from and extensions. I fixed everything in the contig files except that one you found in https://github.com/pombase/curation/issues/1283 (I'd done 'em all at one point; the one you fixed today appears to have snuck in since).

Background in https://github.com/pombase/pombase-chado/issues/483 and https://github.com/pombase/pombase-chado/issues/504

Take-home message: use commas (for two or more required together) or separate annotations.

**Comment by ValWood** [comment]
Yep still pipe separated in our file...

ECOGENE:EG10986|ECOGENE:EG11222
GO:0000033|GO:0006488
GO:0000083|GO:0000790

**Comment by mah11** [comment]
which file is that?

**Comment by ValWood** [comment]
there are 87 in our  current gaf these aren't all new are they? (I rarely concatenate  with field, ony if absolutely necessary)

So I am guessing that  GO does not catch these?

**Comment by ValWood** [comment]
That is the current  canto gaf file (I think I downloaded it yesterday  to check with field contents?)

**Comment by mah11** [comment]
There were 4 stragglers in the contig files (for which I'm about to commit a fix), so something is going wrong with GAF output. For example, the ECOGENE one has commas, as it should, in the c1 contig file:

    FT                   /GO="aspect=F; term=DNA-3-methyladenine glycosylase
    FT                   activity; GOid=GO:0008725; evidence=IGI;
    FT                   db_xref=PMID:8921872;
    FT                   with=ECOGENE:EG10986,ECOGENE:EG11222; date=20120830"

Chado ticket for Kim!

**Comment by mah11** [comment]
GO still allows pipes to mean OR (i.e. semantically equivalent to separate lines with one 'with' entry apiece), so those lines will be allowed, and then misinterpreted if anyone pays that close attention.

**Comment by ValWood** [comment]
ok i forgot they were still allowed. Maybe we can have an internal check eventually since we do these one per line?

**Comment by ValWood** [comment]
this
https://github.com/pombase/pombase-chado/issues/608

makes me think that our pipes in with rally are ORs. they are not ANDS.
we only need one ortholog to support an ISS/ISO, they  must mean OR?

Solution might be just to pick one? I always use one (although historically I might have used two)

**Comment by mah11** [comment]
There are now no pipes in any 'with' or 'from' entries in the contig files.

**Comment by ValWood** [comment]
But are there commas in "with" field entries? 
If so there should not be because | was the correct interpretation (both entries are not required to make the assertion)

**Comment by mah11** [comment]
The commas that are there should be correct - I reviewed all of the pipe-separated entries around the time of https://github.com/pombase/pombase-chado/issues/483 and https://github.com/pombase/pombase-chado/issues/504 and changed to commas where, and only where, multiple with/from entries should mean AND.

**Comment by ValWood** [comment]
I'm closing this. I think there may still be a little problem here. Ticket later on curation tracker.
Not a problem for Kim
