### ISSUE TITLE
add an "excluding regulates",column to the slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1521]
Our current docs imply we do this already:

Most current implementations of software to create “GO slims” include the regulates relationship by default, so that (for example) genes involved in regulation of cytokinesis will be included with the set of genes annotated to cytokinesis. See the GO Ontology Relations documentation for further information about relationships in GO. The annotation totals presented for the PomBase default S. pombe slim, by contrast, are calculated both explicitly including or excluding the genes which are involved in a process via regulation only.

**Comment by mah11** [comment]
Wow, shows how long it's been since the slim-tips page was updated - old pombase had those two columns for with & without regulates (one of a very tiny number of things we've yet to add back). I've edited the text for now, and will restore the version above when this ticket is done.

**Comment by ValWood** [comment]
I had even forgotten that we ever did that!

**Comment by kimrutherford** [comment]
Could you explain what needs to go in the new column?

**Comment by ValWood** [comment]
The current total is the total  annotation using is_a, part_or and regulations relationships.

Historically we had a column which excluded "regulates" relationship too.

**Comment by ValWood** [comment]
@kimrutherford  let me know if this isn't clear, or easy. We can rethink.
It isn't particularly urgent, but we can do it if quick, or punt if not...

**Comment by ValWood** [comment]
Actually, in some ways, I think we should probably not do this. and it might be superseded in the future, so I will close for now. It probably wont be helpful to users. 

I will open a new ticket if we need to do something...
