### ISSUE TITLE
new slim set, component

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1522]
I made a slim set for cellular component. This maps most things (I intentionally ommitted cytoplasm" )

4171 | cytoplasm (GO:0005737
)

2260 | cytosol (GO:0005829) | ...
-- | -- | --
  | 34 | division septum (GO:0000935) | ...
  | 33 | prospore membrane (GO:0005628) | ...
  | 18 | extracellular region (GO:0005576) | ...
  | 68 | cell surface (GO:0009986) | ...
  | 216 | endoplasmic reticulum membrane (GO:0005789) | ...
  | 111 | actin cytoskeleton (GO:0015629) | ...
  | 33 | cytoplasmic stress granule (GO:0010494) | ...
  | 19 | P-body (GO:0000932) | ...
  | 25 | phagophore assembly site (GO:0000407) | ...
  | 23 | peroxisome (GO:0005777) | ...
  | 348 | Golgi apparatus (GO:0005794) | ...
  | 207 | cell cortex (GO:0005938) | ...
  | 55 | cell wall (GO:0005618) | ...
  | 192 | cytosolic ribosome (GO:0022626) | ...
  | 52 | actin cortical patch (GO:0030479) | ...
  | 2649 | nucleus (GO:0005634) | ...
  | 68 | kinetochore (GO:0000776) | ...
  | 49 | nuclear pore (GO:0005643) | ...
  | 50 | nuclear periphery (GO:0034399) | ...
  | 360 | nucleolus (GO:0005730) | ...
  | 251 | nucleoplasm (GO:0005654) | ...
  | 98 | endosome (GO:0005768) | ...
  | 187 | vacuole (GO:0005773) | ...
  | 50 | contractile ring (GO:0070938) | ...
  | 95 | mitotic spindle (GO:0072686) | ...
  | 156 | spindle pole body (GO:0005816) | ...
  | 502 | endoplasmic reticulum (GO:0005783) | ...
  | 232 | plasma membrane (GO:0005886) | ...
  | 749 | mitochondrion (GO:0005739) | ...
  | 574 | chromosome (GO:0005694)

**Comment by ValWood** [comment]
This will need its own page similar to the biological process slim.
It won't have esyN links

**Comment by kimrutherford** [comment]
Excellent.  Is this ready to go or are you still tweaking?

**Comment by ValWood** [comment]
This one is  ready.

**Comment by kimrutherford** [comment]
I've done a quick test to make sure there aren't any major problem.  Seems OK except I missed cytosol when copying and pasting.

> This will need its own page similar to the biological process slim.
> It won't have esyN links

I'll work on that later.  We'll need some new text for the top of the CC slim page.  The current text is BP specific.

Here's how it looks:

![cc-slim-1](https://user-images.githubusercontent.com/90474/81529241-8ac74b80-93b2-11ea-92ec-78632a13793b.png)

And on the gene page:

![cc-slim-gene-1](https://user-images.githubusercontent.com/90474/81529595-48523e80-93b3-11ea-871b-b50a7338e4d5.png)

**Comment by kimrutherford** [comment]
>  We'll need some new text for the top of the CC slim page. The current text is BP specific.

This page and the menu on the left will need updating too: https://www.pombase.org/browse-curation

**Comment by ValWood** [comment]
That looks great!
I should have done these  MF  and CC slims years ago.

What does the relationship between 
endoplasmic reticulum membrane and endoplasmic reticulum look like in the  current obo file

https://github.com/geneontology/go-ontology/issues/19436
( in PomBAse  endoplasmic reticulum membrane  does not slim to ER, but I see the relationship in QuickGO)

**Comment by ValWood** [comment]
1. Fission yeast GO slim -> Fission yeast GO Biological Process slim


2 Fission yeast GO Cellular Component slim
A “GO slim” is a subset of the Gene Ontology terms selected for a specific purpose in interpreting large-scale data, such as functional annotation of a genome or high-throughput experimental results. PomBase uses ~a GO slim~ GO slims to provide a simple summary of S. pombe’s biological capabilities by grouping gene products using broad classifiers.

The table below shows terms in the current fission yeast cellular component  GO slim, and the number of annotations to each term. GO IDs link to PomBase ontology term pages. ~Icons beside each GO term link to esyN, which provides a graphical view of interactions for the genes from the PomBase High Confidence Physical Interaction Network (HCPIN) dataset. Only the subset of genes linked into the interaction network will be displayed in the esyN network view.  ~The annotation totals link to pages with information about the term and a list of annotated genes.

**Comment by ValWood** [comment]
Might also add
Note: We have intentionally excluded "cytoplasm" from the cellular componet slim  set since  4171 fission yeast gene products (3919 proteins) are annotated to this term. You may wish to add this term to your own slim sets.

**Comment by ValWood** [comment]
So all this needs is the link to the list of proteins which 
a) Have a CC annotation but do not map to the slim
b) Have no CC annotation

**Comment by ValWood** [comment]
>This page and the menu on the left will need updating too: https://www.pombase.org/browse-curation

I forgot this page existed and I still need to Google to find the DNA binding  page
We need to get this page under a menu somehow! I will open a ticket for that.

**Comment by kimrutherford** [comment]
I'll set up a slim page for CC without linking to it so we can fine tune things and sort out documentation.  We can link to the new page when everything's ready.

**Comment by kimrutherford** [comment]
> So all this needs is the link to the list of proteins which
> a) Have a CC annotation but do not map to the slim
> b) Have no CC annotation

Would you like a similar section on the disease slim page or the MF slim page?

**Comment by ValWood** [comment]
Yes we already have this on the BP page
We want the same for CC and MF.

For disease  we may as well have both too. The 2nd list might be useful for me  anyway

**Comment by kimrutherford** [comment]
> Yes we already have this on the BP page
> We want the same for CC and MF.
> For disease we may as well have both too. The 2nd list might be useful for me anyway

Great.  I've added that section to all three slim pages on my desktop:

BP: http://desktop.kmr.nz:4242/browse-curation/fission-yeast-go-slim-terms
CC: http://desktop.kmr.nz:4242/browse-curation/fission-yeast-cc-go-slim-terms
MONDO: http://desktop.kmr.nz:4242/browse-curation/disease-slim

There is a little bit of debugging to do because the numbers don't add up on the MONDO page.  It says:
  - Total slimmed gene products (protein and ncRNA): 1088
  - Gene products with MONDO annotation that are not in a slim category: 101

Those numbers add to 1189 but we have 1184 disease genes:
  http://desktop.kmr.nz:4242/results/from/id/c72d1a18-ff11-4cca-a1f8-ad391c0b7740

I'll work on that.

Because there have been lots of overlapping changes, I'll need to release the CC slim page and the DO->MONDO update at the same time.  We don't need to have a link to the CC slim page straight after release if it's not ready for the public.

**Comment by ValWood** [comment]
1 . Did you add the MF section?
2. I think there are a few genes where the annotation  does not get through. I. found 2. That might be it? https://github.com/pombase/curation/issues/2701
3. I have done all the MODO cross checking that I intend to do. It looks good, and will only get better as any issues reported are fixed
https://github.com/pombase/curation/issues/2700
4. I'm happy for all of this to go live together whenever you are ready.

**Comment by kimrutherford** [comment]
> Did you add the MF section?

Not yet.  I wanted to get everything else working first.

> I'm happy for all of this to go live together whenever you are ready.

Great.

Some are some changes needed to the documentation.  It's mostly small things so I'll have a go at it and ask you and Midori to check my work.

I also need to see what happens to existing DO queries in the query builder history when the DO IDs disappear.

**Comment by ValWood** [comment]
>I also need to see what happens to existing DO queries in the query builder history when the DO IDs disappear.

If they just disappear and say "rerun" that isn't do bad...

**Comment by kimrutherford** [comment]
> If they just disappear and say "rerun" that isn't do bad...

We won't be able to re-run them because the term ID will be gone from the database.  All we can do is remove the query from the history or somehow mark it as obsolete.

**Comment by ValWood** [comment]
Yeah that sounds OK ...that must happen other times anyway. GO terms often go obsolete too?

**Comment by kimrutherford** [comment]
> Yeah that sounds OK ...that must happen other times anyway. GO terms often go obsolete too?

Good point.

I just checked.  If a term goes missing the query just returns zero results - no error.

**Comment by kimrutherford** [comment]
> Those numbers add to 1189 but we have 1184 disease genes:

I think I've worked it out.  The 5 genes below have a MONDO annotations that do not have an is_a path to MONDO:0000001 "disease or disorder", instead they have path to "disease susceptibility" (MONDO:0042489).

An example term is:

```
myocardial infarction, susceptibility to (MONDO:0012039)
```

Here are the genes:

Systematic ID | Gene name
-- | --
SPBC25H2.12c | cct7
SPCC737.06c | gcs2
SPBC646.16 | scl1
SPAC1486.01 | sod2
SPBC1709.18 | tif452

(I'm off to bed so my desktop will be off until 10pm-ish UK time)

**Comment by ValWood** [comment]
I think we decided that we would avoid susceptibilities for these multifactorial diseases (At least for the time being).

Thoughts?
@mah11  @Antonialock 

Otherwise there are probably 100s more. I think these  causal genes are more interesting from a MOD perspective?

**Comment by kimrutherford** [comment]
Now we know that it's not a bug that's causing the numbers to not add up I think we can go ahead and release the MONDO stuff.  I'll do a little bit more testing and I'll check the documentation today so we can try it on Wednesday night (UK).  If it all looks OK on the dev site on Thursday morning I'll update the main site.  Otherwise I'll skip the update while I fix things.

The CC slim changes will go live at the same time.

**Comment by ValWood** [comment]
GReat! We c an make the descision about scope on Thursday. 
We will probably have time to chat with @Antonialock  in side chats at the GO meeting tomorrow.

**Comment by kimrutherford** [comment]
Now live at: https://www.pombase.org/browse-curation/fission-yeast-cc-go-slim-terms

**Comment by ValWood** [comment]
queued here
https://github.com/pombase/website/issues/1535
