### ISSUE TITLE
Advances query builder actions, allow other slims

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1523]
Here, we will need to call this  slim bottom BP slim
and add "disease slim" and CC and MF slim once available

<img width="668" alt="Screenshot 2020-05-10 at 21 04 50" src="https://user-images.githubusercontent.com/7359272/81509379-19c85b00-9302-11ea-8188-d7e80c320c06.png">

**Comment by kimrutherford** [comment]
Perhaps the button for open a small menu with the different slims?  That would avoid clutter in the interface.

**Comment by ValWood** [comment]
>Perhaps the button for open a small menu with the different slims? That would avoid clutter in the interface.

good plan!

**Comment by kimrutherford** [comment]
I've added a small menu on the results pages for slimming with BP, CC or disease.  Let me know what changes you'd like.  The MF slim will appear there once it's added to the configuration file.

http://desktop.kmr.nz:4242/results/from/id/8e3b36f2-9790-4c90-aceb-fd6e61d81927

![slim-menu-1](https://user-images.githubusercontent.com/90474/81641477-30db8a00-9475-11ea-9006-ae34ec4cda4c.png)

**Comment by ValWood** [comment]
Nice. This is very cool. It's very useful that you can see immediately how one disease list intersects with all of the other disease lists.
Or  a process  list with diseases.
Or a disease with components
I'm quite excited about this!

**Comment by kimrutherford** [comment]
Done!  Now on the main server.

**Comment by kimrutherford** [comment]
Closed by accident - needs an announcement.

**Comment by ValWood** [comment]
queued here https://github.com/pombase/website/issues/1535
