### ISSUE TITLE
new slim set molecular function

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1524]
Firt stab at a function slim. Covers most non-binding (I think). I will tweak it later when I can see the "non-slimmed", and I might combine some existing as it is a little long

|- | - | ...
-- | -- | --
  | 39 | actin binding (GO:0003779) | ...
 |24 | microtubule binding (GO:0008017)  | ...
  | 4 | pheromone activity (GO:0005186) | ...
  | 13 | signal sequence binding (GO:0005048) | ...
  | 9 | deacetylase activity (GO:0019213) | ...
  | 14 | cell adhesion mediator activity (GO:0098631) | ...
  | 18 | motor activity (GO:0003774) | ...
  | 251 | hydrolase activity, acting on ester bonds (GO:0016788) | ...
  | 61 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (GO:0016810) | ...
  | 55 | hydrolase activity, acting on glycosyl bonds (GO:0016798) | ...
  | 205 | ATPase activity (GO:0016887) | ...
  | 134 | peptidase activity (GO:0008233) | ...
   | 41 | exonuclease activity (GO:0004527) | ...
  | 89 | ubiquitin-like protein transferase activity (GO:0019787) | ...
  | 95 | nucleotidyltransferase activity (GO:0016779) | ...
  | 37 | transferase activity, transferring alkyl or aryl (other than methyl) groups (GO:0016765) | ...
  | 3 | transferase activity, transferring aldehyde or ketonic groups (GO:0016744) | ...
  | 23 | transferase activity, transferring nitrogenous groups (GO:0016769) | ...
  | 115 | transferase activity, transferring one-carbon groups (GO:0016741) | ...
  | 14 | transferase activity, transferring sulfur-containing groups (GO:0016782)
  | 89 | transferase activity, transferring acyl groups (GO:0016746) | ...
  | 89 | transferase activity, transferring glycosyl groups (GO:0016757) | ...
  | 4 | 1,3-beta-glucanosyltransferase activity (GO:0042124) | ...
  | 31 | protein methyltransferase activity (GO:0008276) | ...
  | 11 | peptide N-acetyltransferase activity (GO:0034212) | ...
  | 57 | translation factor activity, RNA binding (GO:0008135) | ...
  | 11 | molecular carrier activity (GO:0140104) | ...
  | 295 | structural molecule activity (GO:0005198) | ...
  | 100 | lipid binding (GO:0008289) | ...
  | 90 | ligase activity (GO:0016874) | ...
  | 287 | oxidoreductase activity (GO:0016491) | ...
  | 257 | catalytic activity, acting on RNA (GO:0140098) | ...
  | 109 | catalytic activity, acting on DNA (GO:0140097) | ...
 | 480 | catalytic activity, acting on a protein (GO:0140096)
  | 45 | unfolded protein binding (GO:0051082) | ...
  | 18 | disulfide oxidoreductase activity (GO:0015036) | ...
  | 79 | lyase activity (GO:0016829) | ...
  | 40 | guanyl-nucleotide exchange factor activity (GO:0005085) | ...
  | 58 | GTPase activity (GO:0003924) | ...
  | 294 | molecular adaptor activity (GO:0060090) | ...
  | 4 | protein sequestering activity (GO:0140311) | ...
  | 100 | catalytic activity, acting on a tRNA (GO:0140101) | ...
  | 188 | kinase activity (GO:0016301) | ...
  | 167 | enzyme regulator activity (GO:0030234) | ...
  | 7 | signaling receptor activity (GO:0038023) | ...
  | 65 | isomerase activity (GO:0016853) | ...
  | 35 | phosphoprotein phosphatase activity (GO:0004721) | ...
  | 3 | cyclase activity (GO:0009975) | ...
  | 5 | peroxiredoxin activity (GO:0051920) | ...
  | 8 | histone demethylase activity (GO:0032452) | ...
  | 6 | protein deacetylase activity (GO:0033558) | ...
  | 117 | protein kinase activity (GO:0004672) | ...
  | 54 | general transcription initiation factor activity (GO:0140223) | ...
  | 49 | transcription coactivator activity (GO:0003713) | ...
 | 11 | transcription elongation regulator activity (GO:0003711) | ...
 | 63 | transcription coregulator activity (GO:0003712) | ...
  | 15 | nucleocytoplasmic carrier activity (GO:0140142) | ...
  | 15 | protein transporter activity (GO:0140318) | ...
  | 15 | lipid transfer activity (GO:0120013) | ...
  | 9 | intramembrane lipid transporter activity (GO:0140303) | ...
  | 290 | transmembrane transporter activity (GO:0022857)

**Comment by ValWood** [comment]
Remainder includes histones, actin, various chaperones

**Comment by kimrutherford** [comment]
First MF slim attempt here: http://desktop.kmr.nz:4242/browse-curation/fission-yeast-mf-go-slim-terms

That URL will work until 1pm or so.

If everything looks OK on Thursday morning (from the CC slim and disease changes) I'll commit the MF slim so it will be available on Friday morning (UK).

**Comment by ValWood** [comment]
Looks good!
Please add
DNA-binding transcription activator activity (GO:0001216)

I'm happy for this to go live. I have some tweaking to do but that can be done over time.

**Comment by ValWood** [comment]
ah I put this in by mistake

DNA-binding transcription activator activity | GO:0001216 | 43
please switch to
DNA-binding transcription factor activity (GO:0003700)

**Comment by kimrutherford** [comment]
> please switch to
> DNA-binding transcription factor activity (GO:0003700)

Done.

**Comment by kimrutherford** [comment]
Now live at https://www.pombase.org/browse-curation/fission-yeast-mf-go-slim-terms

**Comment by kimrutherford** [comment]
Sorry, got too keen and closed before announcing.

**Comment by ValWood** [comment]
It all looks very nice!

**Comment by ValWood** [comment]
Will close everything possible and pull together the announcements here:
https://github.com/pombase/website/issues/1535
