### ISSUE TITLE
menu question for new slims

### ISSUE THREAD

**Issue by mah11** [pombase/website#1527]
In light of #1522, #1524, etc. I've made a grand plan / to-do list for the slim pages and documentation -- I'm happy to do most of it barring a few bits where I'll probably need Kim to help (or just do a thing).

The question here is about the header menu. Right now there's just one "GO slim overview" link:
![top_menu_slim](https://user-images.githubusercontent.com/5196259/81575420-eb4c8d80-939e-11ea-9ca6-9051f86a0335.png)

When there are three slim pages, we could keep one link or have three. Which do you prefer? @ValWood @kimrutherford 

Three links:
- text TBD, likely "GO biological process slim", "GO molecular function slim", "GO cellular component slim"
- pro: direct links to actual slims
- con: clutters menu with a bunch of long entries; a tiny bit more work to implement

Single link:
- use existing "GO slim overview" text to link to the GO slim documentation page (which will get links to all slims added in any case)
- pro: keeps menu short and tidy, with a link to content that applies to all slims; easy to implement
- con: one more click to reach any actual slim page

Note that we can have each slim listed separately in the "Browse curation" left-hand menu no matter what we decide about the header menu.

**Comment by ValWood** [comment]
I think I prefer the 3 added to the list, but I'm not sure.
So you can decide...

**Comment by mah11** [comment]
In a chat we decided to add two links in the short term, i.e. have links to all three GO slims in the existing 'Genome status' menu.

We'll also have a farther-reaching, longer-term rethink about the header menus, especially 'Genome status' but at least some of the others as well. But this ticket doesn't have to wait for that; close it when the MF and CC slim links are in the menu and we'll open new ones later.

**Comment by kimrutherford** [comment]
> text TBD, likely "GO biological process slim", "GO molecular function slim", "GO cellular component slim"

Shall I go with that text?  We talk about "GO Overviews" on the front page and "Disease association overview" in the menu so would "GO biological process overview" etc. be better?

**Comment by kimrutherford** [comment]
![slim-menu-1](https://user-images.githubusercontent.com/90474/82300534-196b4680-9a0b-11ea-8ce2-170f71f73d5f.png)

**Comment by mah11** [comment]
> We talk about "GO Overviews" on the front page and "Disease association overview" in the menu so would "GO biological process overview" etc. be better?

I don't have very strong feelings either way, so I'm happy to stick with "overview" for this menu (especially if you've already done it).

**Comment by ValWood** [comment]
i agree

**Comment by kimrutherford** [comment]
Great.  I've added those menu items.

**Comment by ValWood** [comment]
close?

**Comment by mah11** [comment]
your call - if you're happy with what's there now, sure, close

**Comment by ValWood** [comment]
OK  everything  new is there so I will close this. 
We need to discuss the menu  more generally (there are also other tickets about this, and it's  close to the top of the group  discussion list)
