### ISSUE TITLE
redundant pages for genotypes, & multiple extensions on gene pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#153]
I've just noticed that there are multiple genotype pages for quite a few genotypes. From the link URLs on reference pages and FYPO terms pages, I gather that this happens when one genotype appears in more than one Canto session. E.g. d2288b20e67eb62d-genotype-4 and d378014af8ea8779-genotype-5 are both rad3delta.

It would be a lot more useful to lump these identical genotypes into one page than to keep them separate - if they're lumped, people can see which phenotypes have been curated from which papers for the genotype without going to multiple pages (and therefore knowing they'd have to look at multiple pages).

I think you should be able to use the genotype description (i.e. allele descriptions + expression levels) to tell when two genotypes from different sessions are really the same genotype.

**Comment by kimrutherford** [comment]
I think this is because of: pombase/pombase-chado#577

**Comment by mah11** [comment]
That does look relevant, tho the page issue isn't restricted to deletions. For example, http://pombase2.bioinformatics.nz/genotype/c1136816cdaa2d17-genotype-1 and http://pombase2.bioinformatics.nz/genotype/6998329e8f9ad0bc-genotype-1 are both cdc19-P1 (an allele of mcm2) at the same expression level.

**Comment by kimrutherford** [comment]
> That does look relevant, tho the page issue isn't restricted to deletions.

Thanks for the mcm2 example.  I've updated pombase/pombase-chado#577.

**Comment by kimrutherford** [comment]
I'll close this since I think it's the same problem as #245.
