### ISSUE TITLE
linkouts from term ontology pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1530]
I don't think we should link out to Reactome from GO term pages, because the linnks won't often be useful

<img width="756" alt="Screen Shot 2020-05-14 at 08 15 00" src="https://user-images.githubusercontent.com/7359272/81904498-44910880-95bb-11ea-990e-fb4211ade8b7.png">

(I'm also not sure that Bioportal is required for GO, we need it for FYPO because we have no browser)

**Comment by kimrutherford** [comment]
> I don't think we should link out to Reactome from GO term pages

I've removed the Reactome links.

> (I'm also not sure that Bioportal is required for GO, we need it for FYPO because we have no browser)

We use it for PSI-MOD too.

I don't think having the Bioportal link on the GO pages does any harm.  The two important links are first.  It's easy to remove it though.

**Comment by ValWood** [comment]
No Bioportal is OK and it's consistent. Can close this.
