### ISSUE TITLE
community curation page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1531]
We link to this page. Maybe we should make it more up to date and punchy.

https://www.pombase.org/community/fission-yeast-community-curation-project

**Comment by ValWood** [comment]
@mah11 Any suggestions here?
Cold we make a short summary from the  community curation paper on the current status etc?

**Comment by mah11** [comment]
> @mah11 Any suggestions here?

No; I've been waiting for you to provide something specific enough to act on.

**Comment by mah11** [comment]
I have added a link to the paper. If you want any other changes, please make specific suggestions.

**Comment by ValWood** [comment]
I think this is fine.
