### ISSUE TITLE
 Make the gene product-> gene alphabetization toggles clearer

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1534]
Currently gene (product is more systematic alphabetically)
See if anyone complains.

Longer term  maybe make the toggles clearer

**Comment by kimrutherford** [comment]
This change should be visible in the morning.

**Comment by kimrutherford** [comment]
> default the list toggle to alphabetised product

Done!

> Longer term maybe make the toggles clearer

I'll leave this issue open while we discuss that.

**Comment by ValWood** [comment]
Can we implement the column sorting solution used in canto here  (^)?
Would that help?

**Comment by kimrutherford** [comment]
> Can we implement the column sorting solution used in canto here (^)?

I think that's a good idea.  I'll work on that.

**Comment by kimrutherford** [comment]
> Can we implement the column sorting solution used in canto here (^)?

I've done that.  Let me know if it helps.

**Comment by kimrutherford** [comment]
I think this is done.  Please re-open if I've missed something.
