### ISSUE TITLE
Announcements for new features, slim related

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1535]
First news item:

Draft for news item for CC and MF slims:

News item
To complement the GO biological process overview we have created  two new GO overviews (slims) for cellular component and molecular function terms. (ADD LINKS)
We also provide downloadable slims here (link)

**Comment by ValWood** [comment]
Second news item

New features on  Advanced search results pages

You can now slim/subset any lists in the Query builder to any of our defined slim sets.
For example select a class (list) from the process slim,  and slim this list by disease, or function.

**Comment by ValWood** [comment]
Thumbnail for new feature:

<img width="138" alt="Screenshot 2020-05-15 at 08 14 08" src="https://user-images.githubusercontent.com/7359272/82039860-85614e00-969d-11ea-83e3-2cc7d933b18b.png">

**Comment by ValWood** [comment]
We already have a disease thumbnail

**Comment by kimrutherford** [comment]
> Thumbnail for new feature:

Added as:
src/assets/newsfeed/dropdown_menu.png
