### ISSUE TITLE
Change label on  disease slim?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1536]
Monarch disease ontology slim
is a bit weird

On the front page we say
Disease association overview
so maybe
Disease association overview (using Monarch disease ontology)

suggestions?

**Comment by mah11** [comment]
"Fission yeast MONDO slim" would follow the pattern established on our GO slim pages. We've got the blurb to explain further.

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
That's done now.

**Comment by kimrutherford** [comment]
Sorry, I mis-read this and changed the front page by mistake.  Is this the page that needs changing?:
https://www.pombase.org/browse-curation/disease-slim

**Comment by ValWood** [comment]
Only the front page..

**Comment by kimrutherford** [comment]
Can this issue be closed then?

**Comment by ValWood** [comment]
yes
