### ISSUE TITLE
final Mondo mappings

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1537]
Please add to config

[Mondo_mappings.txt](https://github.com/pombase/website/files/4638031/Mondo_mappings.txt)

**Comment by kimrutherford** [comment]
What is reference and date should we use for these?

**Comment by ValWood** [comment]
date today, reference  PMID: 31701156 I guess

**Comment by kimrutherford** [comment]
> reference PMID: 31701156 I guess

A lot of the others have PB_REF:0000003 as the reference.  Would that make more sense?

https://www.pombase.org/reference/PB_REF:0000003

**Comment by ValWood** [comment]
OK yes !

**Comment by kimrutherford** [comment]
Thanks.
I've added them to the associations file:
`pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.txt`

There are 6 columns:
  - systematic ID
  - gene name (optional)
  - term ID
  - reference ID
  - date in this format: 2020-05-17

I've also started a wiki page listing the data files we load into Chado:
https://github.com/pombase/pombase-chado/wiki/Input-data-files
I'll add to it over time.

**Comment by ValWood** [comment]
I should have checked before I made my file!

**Comment by kimrutherford** [comment]
I did a spot check and the new mappings look OK.

**Comment by ValWood** [comment]
yep and to me
