### ISSUE TITLE
changes to the disease slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1538]
-  [x]  remove paraplegia (if we lose anything by this I can mop it up later
-  [x] remove cerebral degeneration | MONDO:0024238
-  [x] add diabetes mellitus (disease) MONDO:0005015
- [x] ameiloidosis ->  proteostasis deficiencies (MONDO:0021179)

**Comment by kimrutherford** [comment]
The config file is here if you'd like to have go at editing:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json

have a search for the section that starts with:
```
    "pombe_mondo_slim": {
      "slim_display_name": "Disease slim",
      "description": "High level disease terms",
      "cv_name": "mondo",
      "terms": [
```
then change the "terms" bit.

If you commit a change with a syntax error you should get an email from Travis-CI reporting the problem and hopefully the line number.

I'm happy to double check changes after you check them in.

**Comment by ValWood** [comment]
Done, although I did "commit changes' before I realised I was supposed to add a comment above.
This got a lot easier now I figured how to search the edit box (Control F doesn't work, do I had been struggling to find locations in config files)

**Comment by kimrutherford** [comment]
Thanks.  Looks good.  I'll check the load tomorrow.

**Comment by kimrutherford** [comment]
All done.
