### ISSUE TITLE
Add to MF slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1540]
GO:0031386 | protein tag

**Comment by kimrutherford** [comment]
I've added that term to the config file in the section that starts:
```
    "mf_goslim_pombe": {
       "slim_display_name": "Molecular Function slim",
       "description": "S. pombe high level GO molecular function terms",
       "cv_name": "molecular_function",
```

You'll see it on the main site on Monday morning.

**Comment by ValWood** [comment]
I don't see that...

**Comment by kimrutherford** [comment]
Ah, sorry.  I forgot to push the change to GitHub.  I've just done that, I think in time for it to make it into the current Chado load.

**Comment by kimrutherford** [comment]
It's there now.
