### ISSUE TITLE
front page label for disease overview

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1541]
says
Fission yeast MONDO slim

but I don't think people will know what this is.

Needs "Disease overview"?

**Comment by kimrutherford** [comment]
Sorry, I misread this issue: https://github.com/pombase/website/issues/1536

It used to say "Disease association overview".  Should I change it back to that?

**Comment by ValWood** [comment]
Yep I think that is better on the front page.

**Comment by kimrutherford** [comment]
I've changed it back now.
