### ISSUE TITLE
need a new Explore Pombase item for the disease ontology

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1543]
placeholder

**Comment by ValWood** [comment]
I  reactivated the spotlight rotations a couple of days ago and put  a  new disease spotlight.
However the URL isn't linking.
@mah11  could you look at this one, and edit the text because it reads terribly?

**Comment by kimrutherford** [comment]
> However the URL isn't linking.

Which URL?

**Comment by ValWood** [comment]
I put a url in the pombase focus rotation item and it appears as a raw URL, I committed the markdown , I could fix it but I think @mah11  could tweak the wording and I'm too tired :)

**Comment by kimrutherford** [comment]
OK.  I've fixed the URL but I'll leave it to Midori to do any tweaks.

**Comment by ValWood** [comment]
Actually I will take this one back. I know how I would like to tweak it...
