### ISSUE TITLE
Search result slim summary links

### ISSUE THREAD

**Issue by mah11** [pombase/website#1544]
The spiffy new slim options for search results (#1523) all link to the GO BP slim in the "Summary" message accompanying the slim table (here's an [example using the CC silm](https://www.pombase.org/slim:cc_goslim_pombe/from/id/a2d14d5d-a407-4368-9645-a16a93e279e6)).

Thas seems sub-optimal for the non-BP slims. We could either link to the correct slim page every time, or take the quick & easy route of linking them all to the slim documentation (located at documentation/pombase-go-slim-documentation.md). I don't have a strong preference, but let me know which you implement in case I need to update the search documentation.

**Comment by ValWood** [comment]
I think going to the full slim set is good, because most people will want to see the full slim for reference...

**Comment by kimrutherford** [comment]
We also need to decide what to show on the disease slim page.  eg. https://www.pombase.org/slim:pombe_mondo_slim/from/id/c9b59036-9c59-40e1-b28e-6e31aae991c7

**Comment by mah11** [comment]
How about:

A "slim" is a high-level subset of terms from an ontology, used to analyze sets of annotated genes. PomBase has created a slim from the Mondo Disease Ontology (Mondo) to provide a simple summary of *S. pombe* genes with human orthologs implicated in disease.

and, of course, "See full Mondo slim set for more information"

**Comment by kimrutherford** [comment]
> and, of course, "See full Mondo slim set for more information"

Should that link to this page?:
https://www.pombase.org/browse-curation/disease-slim

**Comment by mah11** [comment]
yup

**Comment by kimrutherford** [comment]
I've had a go at this.  I'll fix any problems tomorrow.

I've added to new settings in the slim config section:
  - "slim_results_description" is the text at the top of the slim results page, currently CC and MF have the same text and BP has an extra sentence
  - "full_slim_path" so we don't have to hard code it everywhere

Here is the CC config for example:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L3546

**Comment by mah11** [comment]
That looks promising. Thanks!

**Comment by kimrutherford** [comment]
> currently CC and MF have the same text and BP has an extra sentence

Here are the three for comparison.  Should we add anything on the MF and CC result pages?

https://www.pombase.org/slim:mf_goslim_pombe/from/id/3f3d0723-300a-4531-ac6f-8a0b5cb869d8
https://www.pombase.org/slim:bp_goslim_pombe/from/id/3f3d0723-300a-4531-ac6f-8a0b5cb869d8
https://www.pombase.org/slim:cc_goslim_pombe/from/id/3f3d0723-300a-4531-ac6f-8a0b5cb869d8

**Comment by ValWood** [comment]
This seems fine to me. However, previously the summary appeared at the top right rather than at the bottom. The summary is really useful as you see immediately how many map and a link to more info and the full slim. I much prefer this at the top somewhere.

**Comment by kimrutherford** [comment]
It's always been at the right hand side unless you have a narrow window?

**Comment by kimrutherford** [comment]
![slim-page-1](https://user-images.githubusercontent.com/90474/82533972-73e5dd80-9b98-11ea-82a7-82f9c848335c.png)

**Comment by ValWood** [comment]
Weird. I tried narrowing my window and it stayed at the bottom. Will check again...

**Comment by ValWood** [comment]
This time I widened my window ..... oh dear it's going to be a long day. Was  up at 5:30...

**Comment by mah11** [comment]
I'm going to close this because the originally requested fix is done.
