### ISSUE TITLE
MONDO update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1546]
HI Kim,

could you let me know when MONDO next updated?
I'd like to check  when this comes through:
https://github.com/monarch-initiative/mondo/issues/1493

(I might use amino acid metabolic diseases in the live demo next week)

v

**Comment by kimrutherford** [comment]
There hasn't been a recent release:
 https://github.com/monarch-initiative/mondo/releases/

**Comment by ValWood** [comment]
@cmungall is there anywhere we can sign up for new release notifications?

**Comment by mah11** [comment]
> is there anywhere we can sign up for new release notifications?

responded off-ticket

**Comment by kimrutherford** [comment]
I've updated to the latest MONDO for tonight's Chado load.

**Comment by ValWood** [comment]
We should put a news item, 
"PomBase now used Mondo release v2020-06-01"
just to show-off ;)

**Comment by ValWood** [comment]
We won't report this update, but we will announce future ones.
