### ISSUE TITLE
add/remove from disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1547]
REMOVE
- [x] SPBC29A3.14c MONDO:0009136  (malacards) (TERT)
- [x] SPBC29A3.14c  MONDO:0007485  (malacards) (TERT)
- [x] SPAC1782.10c MONDO:0009136  (malacards) (NHP2)
- [x] SPCC24B10.22 MONDO:0004069  (malacards) (POLG)
- [x] SPCC550.03c  MONDO:0024541 (malacards) (SKIV2L)
- [x] SPMIT.07 MONDO:0007250  (malacards) (MT-ATP6
- [x] SPMIT.07 MONDO:0007778 (malacards)  hypertelorism, sounds like a symptom? (ATP6)
- [x] SPBC1306.01c MONDO:0000732 (GFM1)
- [x] SPCC1827.03c MONDO:0012191  (ACSF3)
- [x] SPBC8D2.12c MONDO:0013620 (malacards) (TACO1)
- [x] SPCC737.02c MONDO:0007415 (malacards) (UQCRB)
- [x] SPBC577.09 MONDO:0019570 (ERCC8)
- [x] SPBC4F6.15c MONDO:0019570 (ERCC1)
- [x] SPCC970.01 MONDO:0019569 (ERCC4)
- [x] SPCP25A2.02c MONDO:0019569 (ERCC6)
- [x] SPCC338.17c MONDO:0007387 (RAD21, RAD21L1)
- [x] SPCC16C4.18c  MONDO:0007387 (malacards)  (TAF6 TAF6L)

ADD
- [x] SPBC1306.01c MONDO:0012191 
- [x] SPCC1827.03c MONDO:0013661

**Comment by ValWood** [comment]
and from 
nhp2 / SPAC1782.10c

**Comment by kimrutherford** [comment]
Are these curation issues?

**Comment by ValWood** [comment]
Yep. I can do them tomorrow though. Some on the curatiomn tracker too.

**Comment by ValWood** [comment]
MONDO:0009640

SPAC11E3.12 (Malacards)
SPAC11E3.12 (Pombase)
SPBC18E5.10 (Malacards)
SPBC18E5.10 (Pombase)
SPAC9E9.15 (Malacards)
SPAC9E9.15 (Pombase)

Pombe does not have complex I...
Pombe does not have complex I...
Pombe does not have complex I...

(that actually makes complox 1 deficiency rather a misleading grouping term. 
any disease which is a subunit of a 46 subunit complex which is a NADH dehydrogenase but has other unknown functions).
I'll com back to this when I have finished

**Comment by ValWood** [comment]
OK these are ready to implement. Remind me where do I find the MONDO annotation file again?

And where do I put new assignments ?

**Comment by kimrutherford** [comment]
Add them to: pombase_disease_associations_mondo_ids.txt
Here are the docs: https://github.com/pombase/pombase-chado/wiki/Input-data-files

**Comment by ValWood** [comment]
grepping for the first 2 to remove in 
disease/
I don't find them in any file?

**Comment by kimrutherford** [comment]
Sorry, I didn't read the top of the issue.  For MalaCards annotation edit:
pombe-embl/external_data/disease/malacards_data_for_chado_mondo_ids.tsv

Columns are documented here: https://github.com/pombase/pombase-chado/wiki/Input-data-files

**Comment by kimrutherford** [comment]
I've looked again.  The first annotation to remove is in `external_data/disease/malacards_data_for_chado_mondo_ids.tsv` I think:

```
dyskeratosis congenita, autosomal recessive 1      dyskeratosis_congenita_autosomal_recessive_1    Dyskeratosis Congenita, Autosomal Recessive 1   NOP10   MONDO:0009136
```

**Comment by ValWood** [comment]
I'm a bit confused.
So there is no file with SPBC29A3.14c?

I don't want to remove 
dyskeratosis congenita, autosomal recessive 1      dyskeratosis_congenita_autosomal_recessive_1    Dyskeratosis Congenita, Autosomal Recessive 1   NOP10   MONDO:0009136

because the mapping to NOP10 ortholog SPAP27G11.13c is correct. I just can't see how it gets onto SPBC29A3.14c

I would like to move so that we have a single file with all of the disease associations  if possible.
We won't reimport from Malacards. Periodically I will check ours against Mondo and add new ones (I can do this relatively easily ). I'll open a ticket about this.

**Comment by kimrutherford** [comment]
Sorry about that!  I copy and pasted the wrong line from the MalaCards file.  I should have copied:
```
dyskeratosis congenita, autosomal recessive 1   dyskeratosis_congenita_autosomal_recessive_1    Dyskeratosis Congenita, Autosomal Recessive 1   TERT    MONDO:0009136
```

> I would like to move so that we have a single file with all of the disease associations if possible.

That makes sense.  We should be able to mostly do that automatically.

**Comment by ValWood** [comment]
For the first one
SPBC29A3.14c  MONDO:0009136  (malacards)
I searched for the human name TERT in this file with MONDO:0009136 but I could not find it?

@kimrutherford

**Comment by kimrutherford** [comment]
It's line 5206 of pombe-embl/external_data/disease/malacards_data_for_chado_mondo_ids.tsv:
```
dyskeratosis congenita, autosomal recessive 1   dyskeratosis_congenita_autosomal_recessive_1    Dyskeratosis Congenita, Autosomal Recessive 1   TERT    MONDO:0009136
```

**Comment by ValWood** [comment]
just one more question.

Do I need to remove the PomBAse one from both of these files?

ombase_disease_associations.txt:SPAC9E9.15		DOID:0060536		PB_REF:0000003	2018-12-13
pombase_disease_associations_mondo_ids.txt:SPAC9E9.15		MONDO:0009640		PB_REF:00000032018-12-13

**Comment by ValWood** [comment]
I got it. Just
malacards_data_for_chado_mondo_ids.tsv 

All done. Sorry, I made a right meal of that one!

**Comment by ValWood** [comment]
Committed revision 6301.
because I put "var" in the comment and could not fix

**Comment by ValWood** [comment]
For example
 SPCC970.01 MONDO:0019569 (ERCC4)
 SPCP25A2.02c MONDO:0019569 (ERCC6)
still visible

**Comment by ValWood** [comment]
caching !
