### ISSUE TITLE
missing annotations, no log report

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1548]
~SPAC1556.02c
/controlled_curation="term=disease associated, cancer; date=20180621"
does not seem to show up.
@kimrutherford  can you see why?~

resolved

**Comment by ValWood** [comment]
also
/controlled_curation="term=disease associated, mitochondrial cardiomyopathy; date=20060821"
on SPAC22E12.18

**Comment by ValWood** [comment]
also
/controlled_curation="term=disease associated, succinate-CoA ligase deficiency; date=20160106"
SPAC16E8.17c

**Comment by ValWood** [comment]
Since these are all genes where I am fixing another disease mapping issue is it possible that the parser bails o the first disease issue?

**Comment by kimrutherford** [comment]
> Since these are all genes where I am fixing another disease mapping issue is it possible that the parser bails o the first disease issue?

Could be.  I thought it was more robust.   But this error in the log for the same gene is not common:

```
term 'MONDO:0018859' in mondo is obsolete: failed to load qualifier 'term=disease associated, Leigh syndrome; date=20060920' from SPAC1556.02c
```

https://curation.pombase.org/dumps/latest_build/logs/all_warnings.txt

Maybe that's enough to make it bail out.

**Comment by ValWood** [comment]
Well let me fix the ones in the logs (mainly they are already  covered by the files Antonia made, so I am removing them).

If I spot any  terms in the artemis annotation which are not  visible I'll add them to this ticket.

Then I will check again tomorrow.

**Comment by kimrutherford** [comment]
> /controlled_curation="term=disease associated, cancer; date=20180621"

That one is there if you "Show details ..." on the gene page: https://www.pombase.org/gene/SPAC1556.02c

> /controlled_curation="term=disease associated, mitochondrial cardiomyopathy; date=20060821"
> on SPAC22E12.18

I can't see that annotation in the contig file.

> /controlled_curation="term=disease associated, succinate-CoA ligase deficiency; date=20160106"
SPAC16E8.17c

There is a mapping for that term:
```
  succinate-CoA ligase deficiency    MONDO:0004069
```

So it's there on the gene page:

https://www.pombase.org/gene/SPAC16E8.17c
MONDO:0004069 | inborn mitochondrial metabolism disorder

if you "Show details ..."

**Comment by ValWood** [comment]
> succinate-CoA ligase deficiency    MONDO:0004069

that's very weird.
succinate-CoA ligase deficiency    MONDO:0004069
is more specific than 
MONDO:0004069 | inborn mitochondrial metabolism disorder

**Comment by ValWood** [comment]
Ah got it.
succinate-CoA ligase deficiency MONDO:0004069 is something MONDO will need to fix

**Comment by ValWood** [comment]
SPAC22E12.18 -> SPAC22E12.10c

**Comment by kimrutherford** [comment]
> /controlled_curation="term=disease associated, mitochondrial cardiomyopathy; date=20060821"
> on SPAC22E12.10c

That's on the gene page https://www.pombase.org/gene/SPAC22E12.10c as "fatal infantile encephalocardiomyopathy" (MONDO:0015487)

Due to the mapping:
```
  mitochondrial cardiomyopathy     MONDO:0015487
```
in disease_name_to_MONDO_mapping.txt

**Comment by kimrutherford** [comment]
> Maybe that's enough to make it bail out.

I think they're all being loaded and it's not bailing out.

**Comment by ValWood** [comment]
Yes I think I got thrown by this missing link
https://github.com/monarch-initiative/mondo/issues/1566
no annotation to cardiomyopathy

at first glance that mapping looked too specific, but it works for the current annotation
https://www.pombase.org/term/MONDO:0015487
(we must remember though that  this mapping might not work in all contexts in this case. but I guess we will mothball it once we are done?).
@Antonialock ?

anyway this ticket is satisfied
