### ISSUE TITLE
untraceable log file error

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1549]
Not sure where this one is:

no Db found with name 'ONDO': failed to load qualifier 'term=disease associated, Schneckenbecken dysplasia; date=20091106' from SPAC144.18

**Comment by kimrutherford** [comment]
It was a typo in disease_name_to_MONDO_mapping.txt:
Schneckenbecken dysplasia       ONDO:0010013

I've just checked in a fix.

**Comment by ValWood** [comment]
Thanks.
