### ISSUE TITLE
put  the name description of the  standard name first

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1552]
Not a biggie , but it might be better.  e.g. here:

<img width="1140" alt="Screenshot 2020-05-23 at 07 33 30" src="https://user-images.githubusercontent.com/7359272/82764080-3be2d280-9e04-11ea-96dd-f918412731da.png">

**Comment by ValWood** [comment]
Yeah that would be quite tricky I guess (Not that the capitalized part of the name description should always match the gene names though)

**Comment by ValWood** [comment]
Putting this as "future" because it's very picky

**Comment by kimrutherford** [comment]
I *think* the names are displayed in the order the name description annotations appear in the contig file.   As a test I've swapped them for scd2 so that "Shape and Conjugation Deficiency" is first.  We'll be able to see the difference on Friday morning.

**Comment by ValWood** [comment]
Yeah this isn't critical at all so close if it will take more than a few minutes.

**Comment by kimrutherford** [comment]
> As a test I've swapped them for scd2 so that "Shape and Conjugation Deficiency" is first. 

That worked so if you need to swap the order on the gene pages, swap the order in the contig file.
