### ISSUE TITLE
should these 2 links take you to the same page?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1553]
both "view  255 genes...."  links go to the same page. Is this intentional?

<img width="1029" alt="Screenshot 2020-05-24 at 21 13 50" src="https://user-images.githubusercontent.com/7359272/82764133-9845f200-9e04-11ea-9ad0-9cdd08c7f185.png">

**Comment by kimrutherford** [comment]
They don't go to the same page.  The first is a table of genes.  The second link is a table of single allele genotypes and has an Allele column.

**Comment by ValWood** [comment]
Of course. I was not seeing  the "allele". I don't use this link much. 

I wonder if it would be better to present the allele column first in this view? (it should not affect anything because  the download options are not available from here).

**Comment by kimrutherford** [comment]
> I wonder if it would be better to present the allele column first in this view?

Sounds sensible.  Shall I go ahead and do it?

**Comment by ValWood** [comment]
Just wait in case @mah11  thinks there is a good reason not to.

I think it would be useful for this page to be a bit more obvious that it's  genotypes (and a bit different from other pages), so I'm for it

**Comment by mah11** [comment]
no objection; no strong preference

**Comment by kimrutherford** [comment]
> I wonder if it would be better to present the allele column first in this view?

Should we continue order by the product as we do for gene tables?

**Comment by ValWood** [comment]
OK...

**Comment by kimrutherford** [comment]
All done.
