### ISSUE TITLE
MOtif search, cannot use multiple  residue 'types' in brackets

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1554]
e.g

C22[ MSQAC]$

 C, aliphatic, aliphatic , any residue, peptide end

I wanted to add into that 
C[29][29] [ MSQAC] for aliphatic + small
but that doesn't work

**Comment by ValWood** [comment]
not urgent, because you can type the full strings, but would be useful

**Comment by kimrutherford** [comment]
> C22[ MSQAC]$

You should be able to do:
```
C22([MSQA]|C)$
```

**Comment by ValWood** [comment]
Ah right I can do 
C[2|1]
I thought I tried that.

**Comment by kimrutherford** [comment]
> Ah right I can do
> C[2|1]

If that works hen "C[21]" should work too.

**Comment by ValWood** [comment]
I think I was just being dim. I assumed it wasn't working, but I bet I had not closed the bracket yet...it seems to be fine...
