### ISSUE TITLE
WORLD _> MONDO

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1557]
In the disease slim (from advanced search filter)
Autocomplete?

WORLD: 0002280 | 3
-- | --
autosomal dominant disease | WORLD: 0000426 | 35
autosomal recessive disease | WORLD: 0006025 | 72
bone development disease | WORLD: 0005497 | 7
cancer | WORLD: 0004992 | 14

**Comment by ValWood** [comment]
but not here:
https://www.pombase.org/browse-curation/disease-slim

**Comment by kimrutherford** [comment]
> In the disease slim (from advanced search filter)
> Autocomplete?

I don't understand.  Are you seeing "WORLD" somewhere on the site?

**Comment by ValWood** [comment]
I was!

Whe I filtered on disease from the advanced search the prefix was "WORLD". Now it is MONDO.

Am I going mad? I should have done a screenshot ;)

**Comment by kimrutherford** [comment]
You haven't got some wacky auto-translate thing going on in your browser have you?  "mondo" is Italian for "world".

**Comment by ValWood** [comment]
Not that I know of and the rest of the page wasn't translated. Oh I'm not going mad, the copy-paste is at the top!

**Comment by kimrutherford** [comment]
> Not that I know of and the rest of the page wasn't translated.

But presumably the rest of the page was already in English so wouldn't need translating?

**Comment by ValWood** [comment]
Ah right, it  I can't figure it out anyway.... will ignore
