### ISSUE TITLE
"active form" extensions should be hidden by default

### ISSUE THREAD

**Issue by ValWood** [pombase/website#156]
so you see this:

![default view for protein binding active form hidden](https://cloud.githubusercontent.com/assets/7359272/22852843/2abf4d8a-f03d-11e6-93e1-72af68c6eb45.jpg)

rather than this
![not](https://cloud.githubusercontent.com/assets/7359272/22852852/60199288-f03d-11e6-974a-46f412102e88.jpg)

**Comment by kimrutherford** [comment]
Should they be hidden just in the summary view?  Is that what you mean by "by default"?

**Comment by ValWood** [comment]
Just the summary view. I *will* get used to calling it the summary view ;)

**Comment by ValWood** [comment]
lovely ;)

http://pombase2.aska.gen.nz/gene/SPBC11B10.09
