### ISSUE TITLE
remove allele name/description redundancy

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1560]
see
https://github.com/PHI-base/curation/issues/19

Maybe we should consider now  'collapsing' other descriptions that are identical to the allele name
on gene pages?

eg.

myo1-S61D (S61D aa)
myo1::his3+ (myo1::his3+)

and only display if  different?

We would need to describe what is equivalence by allele type....

**Comment by ValWood** [comment]
So do we want to do this?

cut12-G71V, T75A, T78A (G71V, T75A, T78A aa)
would become
cut12-G71V, T75A, T78A 

it might be easier to 'read' pages in places like this:

cut12

<img width="618" alt="Screenshot 2020-12-15 at 21 49 14" src="https://user-images.githubusercontent.com/7359272/102276881-62db3000-3f1f-11eb-9b9a-131b6ee1402f.png">

but would the inconsistency be odd?  ( although note we already do this for deletion, for example)

We can make a yes or no decision on this on Thursday.

@mah11  any opinion?

**Comment by kimrutherford** [comment]
> So do we want to do this?
> cut12-G71V, T75A, T78A (G71V, T75A, T78A aa)
> would become
> cut12-G71V, T75A, T78A 

I've got the code change ready to go if we decide it's a good idea.

**Comment by mah11** [comment]
Inconsistency doesn't sit well with me, and if we hide the description the "aa" vs "nt" won't show up. But I don't really have strong feelings.

**Comment by kimrutherford** [comment]
I don't know what's best.  If it helps we could leave "(aa)" or "(nt)" (as appropriate) after the allele name after removing the redundancy.

**Comment by ValWood** [comment]
We will implement.
Mouse over  (and genotype pages) will show full detail.
include (aa)

**Comment by kimrutherford** [comment]
I've made that change.  Let me know if you'd like any tweaks.

Before:
![allele-display-fix-before-1](https://user-images.githubusercontent.com/90474/102763838-1ee4a100-43df-11eb-88d1-71bd94350f4c.png)

After:
![allele-display-fix-after-1](https://user-images.githubusercontent.com/90474/102763858-23a95500-43df-11eb-946c-57623a5e3fda.png)

**Comment by ValWood** [comment]
Great thanks.
