### ISSUE TITLE
EMBL files on centromere page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1561]
1. @mah11 remove links to these out of date files
2. @kimrutherford Move into the ftp site archive

Thanks!

**Comment by ValWood** [comment]
I'm not even sure where these CEN EMBL files came from, have we always had them? I assume so?

**Comment by mah11** [comment]
> remove links to these out-of-date files

done

> I'm not even sure where these CEN EMBL files came from, have we always had them? 

Yep, the content of that page has pretty much just been carried over from the beginnings of PomBase ... or even before.

**Comment by ValWood** [comment]
Yeah I went to way back but I think I went too far back. Anyway  that's enough reminiscing for today ;)

**Comment by kimrutherford** [comment]
> Move into the ftp site archive

Done.
