### ISSUE TITLE
protein features is a 'separate' menu item

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1564]
<img width="167" alt="Screen Shot 2020-06-17 at 17 03 29" src="https://user-images.githubusercontent.com/7359272/84921912-00fb5400-b0bd-11ea-8002-3e7eda93d1da.png">

A while ago we combined the "protein sequence feature" section in the protein feature section.

But at the moment it appears twice. Once embedded in the "protein feature" section.
But there is also another link below "Quantitive gene expression"

**Comment by kimrutherford** [comment]
Fixed for the morning.

**Comment by ValWood** [comment]
this page has the separate  'protein feature' section
https://www.pombase.org/gene/SPCP31B10.04

**Comment by kimrutherford** [comment]
The change won't be visible until the morning.

**Comment by kimrutherford** [comment]
> The change won't be visible until the morning.

Sorry, that doesn't make sense as I made the change 23 hours ago.  I'll investigate!

**Comment by kimrutherford** [comment]
That's fixed now.  The nightly load failed last night and I hadn't noticed.  I've updated the website with the fix.
