### ISSUE TITLE
misc, annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1568]
I think we used to display these

But these 3 (https://github.com/pombase/website/issues/1387 top of the ticket)

I apparently moved at some point, are not displaying:

here is an eg crm1

/controlled_curation="term=misc, target of leptomycin B; db_xref=PMID:10430904; date=19700101"

**Comment by kimrutherford** [comment]
Sorry, you're right.  The cat_act, m_f_g, genome_org and ex_tools sections had gone missing too.  I think I probably broke this when I moved the list of gene pages sections into the config file.  Previously they were embedded in the code.

They'll be back in 10-15 minutes.
