### ISSUE TITLE
add a 'gene' column to drug target table

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1569]
It's hard to look up the gene at the moment because it is sometimes absent ,  or it's integrated into the target descrription

This will make it easier if we want to have a drug_target section on the gene pages

I'll work through this ticket and note any missing information
https://github.com/pombase/curation/issues/89

**Comment by ValWood** [comment]
- [ ] lovastatin  add gene name hmg1 and note competitive inhibitor
 - [ ] prevastatin  add gene name hmg1
 - [ ] benomyl add nda3

**Comment by ValWood** [comment]
- [ ]  trichostatin A    add genes  clr6,clr3, hos2 (inhibits class I &II HDAcs)
- [ ] cyclohexamide   standardize   translation->     translation inhibitor (or protein synthesis inhibitor, see chloramphenicol )
- [ ] compactin (alt. mevastatin) ame hmg1 and note competitive inhibitor


Other 
thialysine naturally occurring lysine analogue
canavanine (group with this?)

**Comment by ValWood** [comment]
- [ ] Alternative name  for isopropyl N-3-chlorophenyl carbamate  "chlorpropham"
https://www.potatopro.com/news/2019/not-enough-support-european-ban-potato-sprout-inhibitor-chlorpropham-cipc
a spindle poison and they spray this on spuds to stop them sprouting. OMG!

**Comment by ValWood** [comment]
...It is not persistent in soil but may be persistent in water systems. Chlorpropham has a low mammalian toxicity but it may bioaccumulate. It is a recognised irritant. It is moderately toxic to birds, honeybees and most aquatic organisms.

still disturbed by this.... I'm presuming it acts on tubulin but I can't locate that information.

**Comment by ValWood** [comment]
- [ ] monesin    Golgi transmembrane Na+/H+ antiporter
- [ ] brefelfin A  gea1  blocking  coats assembly and vesicle budding https://www.nature.com/articles/360352a0
 

(this one is included in animal feed... Monensin, the active compound in Rumensin®, has a very wide safety margin for humans and cattle. But, it can be toxic if not fed according to the FDA-approved label. In other species, such as horses, monensin can be extremely toxic.)

**Comment by kimrutherford** [comment]
Hi Val.

Could you add a screenshot of the table that needs a gene column?  I don't know which one you mean.

**Comment by ValWood** [comment]
https://www.pombase.org/browse-curation/drugs-known-pombe-targets
but this is website tasks for @mah11

**Comment by mah11** [comment]
I have committed a revised table. In addition to Kim's excellent point about the ambiguous referent in the original title, it was *not* easy to tease all of the desired changes out of the various comments. So if I've missed anything, please open a new ticket.
