### ISSUE TITLE
Existing QuickGO graphs embedded on gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1570]
Related to https://github.com/pombase/website/issues/1565

we actually already have the graph on the gene page, but it is quite hidden and so I forgot!
(the gene page graph and the term page graph would show slightly different things)

on the gene pages there is a link at the bottom of the Exp[naded table

show process terms ancestry
https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/%7Bids%7D/chart?ids=GO:0072583%2CGO:0061166%2CGO:1903475%2CGO:1902406%2CGO:0140281%2CGO:1903476%2CGO:1904498%2CGO:0097753

We should do two things to this graph though
1. make it more prominent
2. Don't display NOT annotations

**Comment by kimrutherford** [comment]
> We should do two things to this graph though
>  -  make it more prominent
>  -  Don't display NOT annotations

Both of those are done and should be visible in the morning.  I'll close the issue once they're on the main site.
