### ISSUE TITLE
"This term is part of the biological process overview (GO slim)" for MF and CC?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1571]
On the term pages for terms in the BP slim there is a link to the slim page:

```
This term is part of the biological process overview (GO slim)
```
eg. https://www.pombase.org/term/GO:0030036

Should we have similar links on the MF and CC term pages?

**Comment by mah11** [comment]
sure

**Comment by ValWood** [comment]
yep.

**Comment by kimrutherford** [comment]
Fixed for tonight's load.
