### ISSUE TITLE
possible bug in advanced query interface.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1574]
Previusly in the advanced query,  if you ran thte same query it only appeared once. 
Now the sem qeury often a[pears twice.

This is a screen shot I saved a day or so ago:

<img width="636" alt="Screen Shot 2020-06-30 at 22 52 09" src="https://user-images.githubusercontent.com/7359272/86791882-dec47880-c061-11ea-94ca-f68274281f7e.png">

and  this is at the top of my query list right now

<img width="1017" alt="Screen Shot 2020-07-07 at 14 54 03" src="https://user-images.githubusercontent.com/7359272/86791963-ea17a400-c061-11ea-85c2-179ec5f53f08.png">

(I actually don't remember running these queries more than once so it might be doubly odd).

**Comment by ValWood** [comment]
in the second list  queries
1,3, and 4 are identical
queries 2 and 5 are identical.

Note, I did not relabel or edit any of these queries.

**Comment by mah11** [comment]
weird ... it's not doing that for me

**Comment by ValWood** [comment]
It doesn't always do it for me either. I will dig deeper...
Sometimes I can get the same query to appear, sometimes not.

**Comment by kimrutherford** [comment]
Could you try clicking "[Details]" to see what the differences are between the queries?

**Comment by ValWood** [comment]
I think it is OK, or at least I have not been able to reproduce, will reopen if I do
