### ISSUE TITLE
Historical data for gene characterization progress

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1578]
We should try to add 2019 total to this table.

https://www.pombase.org/status/gene-characterisation-statistics-history
required by JB to update a graphs

I can probably get the numbers from the contig files or @kimrutherford   could you query  end of 2019 chado ?

**Comment by kimrutherford** [comment]
> I can probably get the numbers from the contig files or @kimrutherford could you query end of 2019 chado ?

I queried the values from the 2019-12-31 Chado and I've updated the table on that page.

**Comment by ValWood** [comment]
thank you!
