### ISSUE TITLE
split single and multi gene phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#158]
Feedback from the meeting
JB, JM, SGO thought that single and multi-gene phenotypes were  different enough to be in their own sections.

The numbers also caused some confusion. There is a problem with the counts if we  only have one section and count by genotype...

So
viable vegetative cell population	11548
and
inviable vegetative cell population	4252

Instead of
viable vegetative cell population		3850
inviable vegetative cell		1358

The numbers when summing on genotypes the numbers become pretty arbitrary (for example cdc2  could be 10 or 100  alleles as part of the count.
The numbers when considering only single gene have a 'biological meaning', and people largely think and work in terms of genes, and gene lists, not genotype lists.

Complex genotypes with the exception of viability the phenotype will usually be annotate to  (at least one) the single gene anyway. The additional mutants are often/usually to assess suppression or different  penetrance in different backgrounds.

So, one of the things which is absolutely required for this list is to be able to see single gene annotations to a phenotype. So I suggest that on the gene pages themselves, we do the same as we do in pombase 1 and only show the counts for the single gene phenotypes, no counts  for multi gene phenotypes.

 Somebody (possibly JM) mentioned that  single genes could link to genes and multi-genes could link to genotypes so maybe users would not have a problem with this?

This does not prevent us from somewhere, probably not so prominent providing a link to "all single and multi gene genotypes with this phenotype)

**Comment by kimrutherford** [comment]
I've done the first step - the phenotypes are split into two sections.  Currently they are in separate boxes rather than under one "Phenotypes" heading with two sub-headings because that was easier.  I will change that later.  Example:  http://pombase2.bioinformatics.nz/gene/SPCC1739.11c

**Comment by ValWood** [comment]
Yep I think it does make sense to split. Its much better to make people look in 2 places than the confusion that lumping could cause.

Tomorrow we can discuss what the cunts should show and how we should handle genes and genotypes in the linked pages.

**Comment by ValWood** [comment]
whoops, typo fixed.

**Comment by Antonialock** [comment]
glad you caught that one!

**Comment by ValWood** [comment]
I think we are done here becasue counts are discussed elsewhere ?
