### ISSUE TITLE
Make the Gene page  JBrowse  RH scroll bar default to the top  of the image

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1583]
transferred from
https://github.com/pombase/website/issues/784

Is there a way on the PomBase gene pages to make the right-hand scroll bar  in the JBrowse embed default to the top of the image

currently defaults to the bottom but you see no features if all the features ore on the top strand
https://www.pombase.org/gene/SPRRNA.01

**Comment by ValWood** [comment]
currently defaults to the bottom but you see no features if all the features ore on the top strand
https://www.pombase.org/gene/SPRRNA.01

**Comment by kimrutherford** [comment]
It's at the top for me.  Which browser are you using?

![jbrowse-scroll-1](https://user-images.githubusercontent.com/90474/89828010-8a567080-dbac-11ea-90e8-21d6c5a98152.png)

**Comment by ValWood** [comment]
chrome Version 84.0.4147.105

**Comment by ValWood** [comment]
shall we close this one? I'm just puzzled why it defaults to the bottom for me. Maybe it's in my settings...
