### ISSUE TITLE
Add term definition to search box results

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1584]
Related to #718 but for the main search box.

**Comment by kimrutherford** [comment]
I've added the term definition under the term name in the autocomplete results from the search box.

Before:

![terms-before-1](https://user-images.githubusercontent.com/90474/90762041-7511dc80-e338-11ea-98d2-63debe82cc6b.png)

After: 

![terms-after-2](https://user-images.githubusercontent.com/90474/90762787-b787e900-e339-11ea-8dbf-19799fd2a6c6.png)

I'm not sure it's that helpful but it may be useful is some cases.

While testing the change I was annoyed that the menu went off the right of the screen:

![big-before-1](https://user-images.githubusercontent.com/90474/90762946-fd44b180-e339-11ea-9da1-08792f6a54a9.png)

So I moved the search box a bit:

![big-after-1](https://user-images.githubusercontent.com/90474/90763055-25ccab80-e33a-11ea-8076-44baf550174d.png)

I then got annoyed by how naff the header looks on a small screen (and how the search results are _way_ off the right hand side):

![small-before-1](https://user-images.githubusercontent.com/90474/90763262-7a702680-e33a-11ea-8fc8-5cb1839e9c8b.png)

So I've change that too.  So the search is much more usable on tablets and phones now:

![small-after-1](https://user-images.githubusercontent.com/90474/90763496-e783bc00-e33a-11ea-9cf9-cd9064dca0e0.png)

**Comment by mah11** [comment]
cool!
