### ISSUE TITLE
unresponsive header menu items

### ISSUE THREAD

**Issue by mah11** [pombase/website#1585]
Hi @kimrutherford 

I regret to inform you that one/some of the changes in #1584 has broken the header menu. When I click on any of the menu items below the search box, or below and to the right, nothing happens. Search and Submit are unaffected; Genome status works if I click the left-hand third but not the rest (roughly, clicking on 'Geno' works), and Downloads, Community, About, and Help don't respond at all. It seems like there's some invisible box overlying most, but not all, of the menu.

The problem affects every browser/platform combination I can test (Firefox & Chrome on Linux, and Firefox, Chrome, & Safari on Mac).

I know it's new because I happened to have a couple of unrefreshed tabs open in FF and the menus still work there.

**Comment by kimrutherford** [comment]
Thanks for finding that.  I'm about to re-release with a fix.
