### ISSUE TITLE
Announcement about hosting browser datasets

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1587]
Follow on from
https://github.com/pombase/website/issues/814

Once we are happy with the  data hosting process, we should announce the existence of the spreadsheet to describe metadata, and remind people about the  submission process for hosting browser datasets.

**Comment by mah11** [comment]
pombelist email sent; I included 3 new datasets as well as the submission doc link

does this warrant news, or shall I close it?

**Comment by ValWood** [comment]
A short news item wouldn't do any harm since it would be an 'in your face' reminder for a while that the submission process is updated. It could link also to the publication pages so that people can quickly launch the tracks. 

Also the news feed is accessible easily to funders and reviewers and makes us look busy ;)

**Comment by mah11** [comment]
all righty, I'll commit one for tonight's update :)
