### ISSUE TITLE
JBrowse gene page view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1588]
Is looking a bit weird:

I can't quite figure the problem but it is similar to the mitochondrial genome problem. I can no longer see both strands.
Screenshot below:

<img width="1099" alt="Screenshot 2020-08-25 at 11 21 18" src="https://user-images.githubusercontent.com/7359272/91164994-de427880-e6c7-11ea-9895-2b8b60bd97fc.png">

**Comment by kimrutherford** [comment]
I think it's because of the big stack of feature just off screen to the right.  It pushes the reverse strand down and off the bottom of the view.  I think it's the same problem for the mitochondrial genes.

![gene-page-jbrowse-1](https://user-images.githubusercontent.com/90474/91167623-5b053f00-e728-11ea-938d-00a9c8aa16e6.png)

**Comment by ValWood** [comment]
I know what is causing this problem. These "DNA replication origin" features, are in the main annotation  rather than in their own track:

<img width="789" alt="Screenshot 2020-08-25 at 12 11 25" src="https://user-images.githubusercontent.com/7359272/91167714-56ab3880-e6cc-11ea-83f8-37dd97e97133.png">

**Comment by ValWood** [comment]
OK, this is sounding vaguely familiar. Are these in the artemis files? 
I don't have Artemis on my new laptop yet (won't install).

**Comment by kimrutherford** [comment]
> OK, this is sounding vaguely familiar. Are these in the artemis files?

Yep:

```
FT   rep_origin      1095554..1095603
FT                   /colour=2
FT                   /note="ars1, segment 1 (Clyne & Kelly)"
FT   rep_origin      1095554..1096335
FT                   /note="ars1, minimal sequence (Clyne & Kelly)"
FT   rep_origin      1095568..1095608
FT                   /colour=4
FT                   /note="protected region F (PMID 11717425), protected
FT                   region D (PMID 12374757)"
FT   rep_origin      1095736..1095739
FT                   /colour=7
FT                   /note="Initiation site in ars1 determined by RIP mapping
FT                   (PMID:10523311)"
FT   rep_origin      1095858..1095884
FT                   /colour=4
FT                   /note="protected region E (PMID 11717425)"
FT   rep_origin      1095921..1095936
FT                   /colour=4
FT                   /note="protected region D (PMID 11717425); protected
FT                   region C (PMID 12374757)"
FT   rep_origin      1095954..1096003
FT                   /colour=2
FT                   /note="segment 9 (Clyne and Kelly)"
FT   rep_origin      1096013..1096030
FT                   /colour=4
FT                   /note="protected region C (PMID 11717425)"
FT   rep_origin      1096094..1096131
FT                   /colour=4
FT                   /note="protected region B (PMID 11717425)"
FT   rep_origin      1096206..1096230
FT                   /colour=4
FT                   /note="protected region A (PMID 11717425)"
```

**Comment by ValWood** [comment]
It's these

FT   rep_origin      1095554..1095603
FT                   /colour=2
FT                   /note="ars1, segment 1 (Clyne & Kelly)"
FT   rep_origin      1095554..1096335
FT                   /note="ars1, minimal sequence (Clyne & Kelly)"
FT   rep_origin      1095568..1095608
FT                   /colour=4
FT                   /note="protected region F (PMID 11717425), protected
FT                   region D (PMID 12374757)"
FT   rep_origin      1095736..1095739
FT                   /colour=7
FT                   /note="Initiation site in ars1 determined by RIP mapping
FT                   (PMID:10523311)"
FT   rep_origin      1095858..1095884
FT                   /colour=4
FT                   /note="protected region E (PMID 11717425)"
FT   rep_origin      1095921..1095936
FT                   /colour=4
FT                   /note="protected region D (PMID 11717425); protected
FT                   region C (PMID 12374757)"
FT   rep_origin      1095954..1096003

**Comment by ValWood** [comment]
OK, these are very old from when single origins were studied.
I suggest we  just keep the main replication origin feature and delete all of the 'protected region' and 'minimal sequence' annotations.
These were annotated by me about 25 years ago I think!

So it seems that the new JBrowse is recognising  and displaying annotated features that were previously ignored?

When I do the  feature annotation update, I might create a separate tracks for other  manually curated features if this begins to get crowded/ continues to be a problem.

**Comment by ValWood** [comment]
I need to fix this...

**Comment by ValWood** [comment]
I just left the actual "replication origin" feature

**Comment by kimrutherford** [comment]
> I just left the actual "replication origin" feature

Did you commit a fix?

**Comment by ValWood** [comment]
oops no. done for tomorrow

**Comment by kimrutherford** [comment]
Fixed now.  Thanks.
