### ISSUE TITLE
small issue with "transcript maps"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1593]
If the feature is a ncRNA the exon is still labelled as a CDS exon bottom left

<img width="1076" alt="Screenshot 2020-09-03 at 18 39 01" src="https://user-images.githubusercontent.com/7359272/92148721-dfd11680-ee14-11ea-8c23-e26c577955b0.png">

**Comment by kimrutherford** [comment]
Good point.  :-)

I've fixed that.  It now says
```
exon 1   4651792-4651351
```

Does that make sense for pseudogenes too?

**Comment by ValWood** [comment]
> Does that make sense for pseudogenes too?

yes I think so

**Comment by kimrutherford** [comment]
OK, thanks.
