### ISSUE TITLE
PomBase publications update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1594]
add
 https://royalsocietypublishing.org/doi/10.1098/rsob.200149
to
https://www.pombase.org/about/published-by-pombase

**Comment by kimrutherford** [comment]
Done!

Let me know if it doesn't look OK.

**Comment by ValWood** [comment]
should I see it now?

**Comment by ValWood** [comment]
Ah I see it. The newer ones usually go at the top ;)

**Comment by kimrutherford** [comment]
> The newer ones usually go at the top ;)

Fixed!
