### ISSUE TITLE
 Grech fitness landscape data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1595]
I don't understand what the top and bottom tracks are by looking at the labels.

1. There is no "data type". Track labels should begin with "data type"
2. What are HDE units? S1-S3 states?

~3. Is the first track data that can be displayed in the browser (currently it isn't). That's fine if not, there is no harm in having it easily accessible to download.~

<img width="1083" alt="Screenshot 2020-09-05 at 08 38 12" src="https://user-images.githubusercontent.com/7359272/92300500-2cbb0700-ef53-11ea-9c7f-11363f7e0e14.png">

@bahler can you suggest more informative labels? - thanks!

**Comment by bahler** [comment]
Where do these labels originally come from? Were they provided by Dan Jeffares?

Cheers,
-Jürg

**Comment by ValWood** [comment]
I don't know.
@Antonialock  did Dan supply these?

**Comment by Antonialock** [comment]
Hmm, not sure what happened here, the data types suggested by Dan were "transposons" and " comparative genomics"

**Comment by ValWood** [comment]
Do you think we could just call 

HDE units‚ continuous runs of states S1-S3 - Grech et al. (2019)

Transposon insertion sites, continuous runs of insertions  - Grech et al. (2019)

(a casual browser user will not understand what states S1-S3 are)



Ignore 3. that one is fine. I thought it did not load from the publication page, but it does
https://www.pombase.org/reference/PMID:31077324

**Comment by ValWood** [comment]
IN the spreadsheet there is a label

Nucleosome   positioning | yes | nucleosome positioning in WT

Do we have this file?

**Comment by ValWood** [comment]
so the states are some sort of HMM? not sure how valuable that could be for insertion sites? There is either an insertion at a site or not? the insertion track is probably informative enough?

**Comment by bahler** [comment]
The 4 states essentially reflect how likely it is that a transposon gets inserted in that region, the less likely to more ‘important’ the region is deemed to be.

Cheers,
-Jürg

**Comment by ValWood** [comment]
OK so the HMM is not based on the actual insertions. Its just trained on  partitioned data that is expected to be mor or less important for fitness. Is that correct?

We could do with labels that would explain to a casual user of the browser what the tracks are. It doesn't seem right to include the 2 HMM tracks in the "transposon insertion" set or it could confuse people?

**Comment by ValWood** [comment]
This finding was not surprising, given that HMM states are strongly correlated with insertion density (Pearson r = 0.78)

**Comment by ValWood** [comment]
HMM states indicative of conserved, functionally significant regions?

**Comment by ValWood** [comment]
I'm a bit inclined no to include these.  The HMMs are based on partitioning the coding non coding essential non essential genes. 
Although the data may be useful in the paper for analysis  it all becomes a bit circular if we have real fitness data?

**Comment by ValWood** [comment]
these are the original label suggestions anyway:

transposons | yes | Hermes transposon insertions
-- | -- | --
Nucleosome positioning | yes | nucleosome positioning in WT
transposons | yes | Hermes HMM state
comparative genomics | yes | conservation (phyloP)
transposons | yes | Hermes HMM-defined elements

**Comment by ValWood** [comment]
action item
This data is announced but the labels will need tweaking at some point  so that it is clearer whet the data represents.

**Comment by bahler** [comment]
Just catching up now with this thread. Yes, I agree that the HMM are confusing and not necessary here. They were essentially used to model the insertions, normalize for insertion bias, and classify the insertions into 5 types of different density (the latter could be helpful).
But perhaps just the transposons insertion would be sufficient for time being.

**Comment by ValWood** [comment]
Hi Jurg,

So do you think we should "hide" HDE units and transposon insertion sites smoothed.
My understanding is that these are not based on the actual insertion sites and are potentially confusing?

**Comment by bahler** [comment]
The smoothed sites might be useful for some users but I agree that it can be confusing as it does not directly reflect the data.
So yes, why not hide for now and I’ll consult with Dan and others.

**Comment by ValWood** [comment]
action:
hide tracks "HDE units..." and "Transposon insertion smoothed to states..."

@kimrutherford  can these just be commented out.
This solves a mystery. I had

54. hide transposon data
on my todo list for weeks and had no idea what it meant!

**Comment by mah11** [comment]
That's what column 2 in the track metadata file is for - change 'yes' to 'no' for tracks you don't want displayed.

I've done that for two rows for the Grech data. If there aren't any more to do, this can close.

**Comment by ValWood** [comment]
Thanks!
