### ISSUE TITLE
JBrowse label obscures features.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1596]
Is there any way to prevent this?

<img width="1093" alt="Screenshot 2020-09-06 at 13 02 30" src="https://user-images.githubusercontent.com/7359272/92325425-82baa800-f042-11ea-9bb5-d794acb86af6.png">

the features are often under the label.  It is difficult to scroll to position them so that they are not under the label.

**Comment by kimrutherford** [comment]
I don't know of a solution apart from having shorter labels.

> perhaps #1588 will fix it?

I think that's about the features labels rather than the track labels.

**Comment by ValWood** [comment]
Ah ok.  that would be daft.

**Comment by ValWood** [comment]
actually I can see the features and read the labels.  this wasn't clear when I was looking. Maybe  a different (stronger) feature colour would help?

**Comment by kimrutherford** [comment]
> Maybe a different (stronger) feature colour would help?

I tried a few colours and they were all a bit hard to see.  Darker colours were more visible but were also ugly.

**Comment by ValWood** [comment]
ok we will stay as we are...

**Comment by kimrutherford** [comment]
> I tried a few colours and they were all a bit hard to see. 

That didn't work but in the documentation it says:
```
Set "trackLabels": "no-block" to enable the trackLabels to be out of the way
of the features. 
```

**Comment by kimrutherford** [comment]
I've made the config change.  Let me know if we should keep it or revert to what we had.

**Comment by ValWood** [comment]
much better
<img width="772" alt="Screenshot 2020-09-08 at 07 44 30" src="https://user-images.githubusercontent.com/7359272/92442091-38067080-f1a7-11ea-973c-79378bd86847.png">

**Comment by ValWood** [comment]
I think it will be better not to obscure the features. It wasn't so bad here but sometimes it can be tricky
