### ISSUE TITLE
update to new and changed gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1598]
update
https://www.pombase.org/status/new-and-removed-genes

new gene (partially overlaps with existing ncRNA prl46 so I kept this name for  now. It can become a synonym later)

/primary_name="SPAC144.19"
/primary_name="prl46"
/colour=12
/controlled_curation="term=species distribution, Schizosaccharomyces specific; date=20200908"
/controlled_curation="term=warning, new gene; db_xref=PMID:32594847; cv=warning; date=20080513"
/product="Schizosaccharomyces specific protein"
/obsolete_id="SPNCRNA.46"
/db_xref="EMBL:AB084858"
/db_xref="PMID:12597277"
/synonym=ORF692

removed SPNCRNA.46
prl46 complement(4651351..4651792) SPNCRNA.46
-> becomes the 5'UTR of  SPAC144.19

**Comment by mah11** [comment]
done, but it looks like the dates are the wrong way round for these items:

> /controlled_curation="term=species distribution, Schizosaccharomyces specific; date=20200908"
> /controlled_curation="term=warning, new gene; db_xref=PMID:32594847; cv=warning; date=20080513"
