### ISSUE TITLE
Li et al TSS data not loading

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1600]
error ( I can't C-P it)
<img width="444" alt="Screenshot 2020-09-09 at 10 28 23" src="https://user-images.githubusercontent.com/7359272/92581198-3d3aec80-f287-11ea-86c1-8478b6883ade.png">

**Comment by mah11** [comment]
Weird. The filename in the error message ends with ".tbi", which isn't there in either the actual file names or the metadata file.

**Comment by ValWood** [comment]
Also weird becasue I'm sure it was fine at one point!

**Comment by kimrutherford** [comment]
The .tbi is the index file for BED files to speed up access for big files.  It seems like JBrowse requires it now.  I've added the .tbi file and the site is re-releasing.  I'll check the other datasets that use BED files.

**Comment by kimrutherford** [comment]
OK, those two tracks are fixed.  I've checked the other BED tracks and they already have .tbi files.
