### ISSUE TITLE
 add query builder option to retrieve genes with annotated alternative transcripts

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1601]
We should add a query builder option to retrieve these....

**Comment by kimrutherford** [comment]
The quickest way to implement this is to add a "Number of transcripts" option to the query builder so I've done that.  We can do something cleverer later.

The list of query builder query types is getting quite long.  We might need to work on that.  Maybe by grouping together similar types.

**Comment by ValWood** [comment]
To be clearer maybe 
"Number of *alternative* transcripts

The list is quite long. We can have a think about sensible grouping.

**Comment by mah11** [comment]
> To be clearer maybe
> "Number of *alternative* transcripts"

I dunno ... to me that's almost *less* clear - "min 1 alternative transcript" could be taken to mean "min 2 total transcripts" (one's primary, the rest "alternative").

**Comment by ValWood** [comment]
number of transcript structures?

**Comment by mah11** [comment]
> number of transcript structures?

Specific to this suggestion: risks being taken to mean something about RNA secondary structure

General q: why does it need any more words? What's unclear about "number of transcripts"?

**Comment by ValWood** [comment]
Because if you came to the  query builder and you didn't know it was gene based you could (I imagine) think this was something to do with "expression level". If you think that is unlikely it can stay as it is.

**Comment by mah11** [comment]
I do think it's unlikely, but if you think it's a real concern, perhaps the query could be called "number of annotated transcripts".

**Comment by ValWood** [comment]
Let's keep it as it is. It's obvious anyway once you try to use it.

**Comment by kimrutherford** [comment]
> Number of alternative transcripts

I originally had "Number of annotated transcripts" but it seemed a bit long.

**Comment by mah11** [comment]
It sounds like we're probably OK to leave it as is, but if we do want a more explanatory label, I'm reliably informed that the phrase currently in favor is "number of transcript isoforms".

**Comment by ValWood** [comment]
I think we should change
Retrieve genes by number of annotated transcripts:
to
"number of transcript isoforms".

Then,  this can close. Does any documentation need to be altered?

**Comment by ValWood** [comment]
https://www.pombase.org/documentation/advanced-search
Images won't be affected by this text change.

This is worded a bit strangely:
Find genes with a specified number of annotated transcripts; genes with two or more have one or more alternative transcripts in addition to the primary transcript. Enter the desired minimum and maximum number and click “Search”.

Perhaps just:

Find genes with a specified number of annotated transcript isoforms;  Enter the desired minimum and maximum number and click “Search”.
(Note: alternative transcripts are only explicitly annotated if functional differences between isoforms are identified- see the browser datasets for the full extent of known transcript variation)

(I did not understand the ommitted part)

**Comment by kimrutherford** [comment]
> Perhaps just:

I've made that change.  The source file is here if you'd like to tweat the text:
https://github.com/pombase/website/blob/master/src/docs/documentation/advanced-search.md

**Comment by ValWood** [comment]
This text didn't come through to the query builder yet:
<img width="691" alt="Screenshot 2022-01-04 at 12 14 28" src="https://user-images.githubusercontent.com/7359272/148057581-a1a78fdb-62a1-4916-bcdb-cd61fbbf2b10.png">

**Comment by kimrutherford** [comment]
Ah, sorry.  I updated the documentation but not the interface.  I've committed a fix.

**Comment by kimrutherford** [comment]
I think this is done.
