### ISSUE TITLE
Missing coordinates for UTR introns

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1602]
eg. https://www.pombase.org/gene/SPBC725.10

**Comment by ValWood** [comment]
what do you mean, in Artemis?
or in chado?

**Comment by kimrutherford** [comment]
> what do you mean, in Artemis?
> or in chado?

Just in the display.  We're not showing the UTR intron coordinates.  Like here:

![missing-introns-1](https://user-images.githubusercontent.com/90474/93081708-cae16680-f6e3-11ea-9671-8f8749142b23.png)
