### ISSUE TITLE
publication pages with browser tracks - suggestions

### ISSUE THREAD

**Issue by mah11** [pombase/website#1606]
Received from @Antonialock via the helpdesk (but you are welcome to open a ticket here yourself) (ticket 8115):

> I have a suggestion:
> 
> On publication pages, include the data type on the left-hand side and make the columns sortable (e.g. you might want to sort on data type, or by growth phase/response). It might also be nice to see if the track is for a mutant [or WT] 'at a glance'

That's three suggestions ;)

- add data type column (see below)
- make table sortable by column
- add "WT or mutant" column

> include the data type on the left-hand side

@Antonialock Do you mean the left-hand side of the table of browser tracks, or somewhere else on the pub page? How important is it that it's on the left?

**Comment by mah11** [comment]
Old ticket is #801. It's very long, and bits about which columns to show are scattered among the comments, so maybe it's better just to have a fresh look.

**Comment by ValWood** [comment]
Catching up, I suggest we just replace the "track label" column on the publication pages with "data type" column

The 'track label' is really just a composite of information from the meta-data to "uniquify" the track.
No objection to adding the WT/mutant column
Sortable would be nice if it's easy,  and might be nice to make track selection a bit easier if there are a lot of tracks

**Comment by kimrutherford** [comment]
> The 'track label' is really just a composite of information from the meta-data to "uniquify" the track.

I don't think that's always the case.  For example these two tracks are the same except for the label and the data file URL:
```
Rec12-DNA covalent linkage sites during meiosis; repeat 1 0h - Fowler et al. 2013
Rec12-DNA covalent linkage sites during meiosis; repeat 1 3h - Fowler et al. 2013
```

**Comment by ValWood** [comment]
Good point!

**Comment by ValWood** [comment]
Here is an example page
https://www.pombase.org/reference/PMID:23395004
we can discuss if we want to do this, and how important it is

Comments
The data type label is very long. Maybe that would be better as header for the table. A few papers have multiple data types so for these the tables would be split.

I agree to add the Wt or mutant column.

I'm not fussed about table sorting unless it is easy.

**Comment by ValWood** [comment]
1. Ditch study ID /Sample ID (add to publication header above the table linked)
2. Add data type and WT/mutant column

**Comment by kimrutherford** [comment]
>  1.  Ditch study ID /Sample ID (add to publication header above the table linked)
>  2.  Add data type and WT/mutant column

Done.

**Comment by kimrutherford** [comment]
> I'm not fussed about table sorting unless it is easy.

It's not a big job.  I'll do it one Friday afternoon.

I've changed this to "low priority".

**Comment by kimrutherford** [comment]
> I'm not fussed about table sorting unless it is easy.

It was easy so it's done now.

I think that's the last item to do here.
