### ISSUE TITLE
advanced search query type list

### ISSUE THREAD

**Issue by mah11** [pombase/website#1607]
Comments on #1601 note that the list of query types in the advanced search is getting long and a bit disorganized.

Here's a suggested reorganization to use as a starting point for discussion (or to deploy, if you like it well enough as is):

- Commonly used queries
- Gene list queries
	- Gene name and IDs
	- UniProt accessions
- Ontology queries
	- GO
	- Phenotype
	- Disease
- Gene product queries
	- Product type
	- Protein modification
	- Protein domain
	- Protein feature
	- Protein length
	- Protein mol. weight
	- Number of TM domains
	- Number of exons
	- Number of transcripts
- Genome overview queries
	- Taxonomic conservation
	- Characterisation status
	- Genome location

The headings I've put in could either be displayed or just stay behind the scenes as implicit groupings; I don't have a strong preference.

**Comment by ValWood** [comment]
I think this classification is great. It will make it *much* easier to home in on the appropriate query.

I wonder if the display  even needs to be a vertical list?  It could be  5 boxes arranged in 2 columns  (gene product queries to the left and the others to the right would probably work with the current set) . We could then make  some things   a bit more obvious  with supplemental  info if required - like the "gene list queries" (i.e "upload gene list")

I have to say I struggle with the current list sometimes when I am looking for a specific query type......I think this separation will be really helpful.

Also, I have never noticed this before because I never click on it but the "New Query" link doesn't do anything?

**Comment by kimrutherford** [comment]
> I wonder if the display even needs to be a vertical list? It could be 5 boxes arranged in 2 columns

Could you make a mock up when you get a chance?  Currently the options look like tabs.  That would need to change if we had two columns.

> Also, I have never noticed this before because I never click on it but the "New Query" link doesn't do anything?

It's not a link, it's a tab.  Maybe the label could be clearer?  Maybe "Start"?

**Comment by ValWood** [comment]
I was thinking something like this
But probably not worthwhile unless the list gets very long...

<img width="652" alt="Screenshot 2020-09-18 at 11 04 19" src="https://user-images.githubusercontent.com/7359272/93585428-b5e42c00-f99e-11ea-8e95-74dfea886682.png">

**Comment by ValWood** [comment]
Ignore the part about New query...

**Comment by mah11** [comment]
I would prefer to stick with the current vertical layout. It leaves plenty of space for the query-parameter setting controls once a type is selected.

**Comment by ValWood** [comment]
OK, I prefer the vertical layout too.  So  this one can move to implementation.

**Comment by kimrutherford** [comment]
I'm not sure how to get the tabs to look OK in the new organisation.  I'll have to think about it.

**Comment by ValWood** [comment]
I removed "next" and "quick" from this while you think about it. Since it is an enhancement it isn't urgent.

**Comment by kimrutherford** [comment]
> I removed "next" and "quick" from this while you think about it. 

Thanks.  I'm also a bit worried that the list will be a bit long.  It's already a bit too much on my screen.

**Comment by ValWood** [comment]
I'll put at low priority for now. We can revisit if/when more queries are added...

**Comment by kimrutherford** [comment]
> We can revisit if/when more queries are added...

We'll soon need to add a new query type: #1729

It's currently disabled on the main site.

**Comment by kimrutherford** [comment]
> We'll soon need to add a new query type: #1729

Also #1720

**Comment by ValWood** [comment]
Shall we discuss on next call?

**Comment by kimrutherford** [comment]
> Shall we discuss on next call?

I've added it to my list.

**Comment by kimrutherford** [comment]
> Here's a suggested reorganization to use as a starting point for discussion

I like that organisation.

I've also been experimenting with moving some query types into sub-tabs.  Here's how my prototype looks.  I don't think it looks great at the moment but I'll try a few options. 

![query-sub-nodes-1](https://user-images.githubusercontent.com/90474/134339882-0d74e9ed-00a9-4e6b-a058-499f9a8e0b4f.png)

![query-sub-nodes-2](https://user-images.githubusercontent.com/90474/134339978-181e3ec8-951c-4308-b237-0a5950ad7d2d.png)

**Comment by ValWood** [comment]
That works for me.

**Comment by kimrutherford** [comment]
> That works for me.

Great.  I can do a quick demo on Thursday if you like.

**Comment by ValWood** [comment]
That would be great!

**Comment by kimrutherford** [comment]
Here's my first attempt at grouping the query types.  It's still a bit in progress.  Like the other query builder changes it's only in my local copy for now.

![query-builder-headings-1](https://user-images.githubusercontent.com/90474/135600930-d3987ba0-f0f6-4f6a-b192-1f70935fd3d7.png)

**Comment by mah11** [comment]
Looks good. I suppose it wants the little arrows for the items that have options in tabs but I can't see anything else to change.

It also occurs to me that if we wind up adding a lot more "commonly used queries", we can group them into tabs using the same categories.

**Comment by kimrutherford** [comment]
>  I suppose it wants the little arrows for the items that have options in tabs but I can't see anything else to change.

Good point!  The arrows got lost while I was making these changes.  I'll add them back before release.

> It also occurs to me that if we wind up adding a lot more "commonly used queries", we can group them into tabs using the same categories.

That makes sense.

**Comment by ValWood** [comment]
I like it too.
I'm not sure about the grouping of 
protein modification and domains features and motifs under 'gene product queries'
but I don't have good suggestions

**Comment by ValWood** [comment]
I have a small text change:

rather than
protein with any coiled-coils
oe
number of coiled-coils 
per protein.

Change to
number of coiled-coils regions per protein.

A coiled -coil  region may contain >1 coiled-coil
(also more consistent with the other 2 features)

**Comment by kimrutherford** [comment]
> A coiled -coil region may contain >1 coiled-coil

Ah, I didn't know that.  I've change it.

> will this work for japonicus too?

It will once the configuration is updated.

**Comment by kimrutherford** [comment]
> I hope that makes sense.

I think so.  :-)

It's all live now: https://www.pombase.org/query

Let me know if you spot any problems.

The version on my desktop is now JaponicusDB with the new style query builder and configuration: https://desktop.kmr.nz/query

**Comment by ValWood** [comment]
@mah11  could you add a news item on Monday
