### ISSUE TITLE
Community curated paper stats

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1608]
This is probably on the wrong tracker.

One the stats page:
To date 1671 publications have been assigned to community members for curation. 847 are finished and are either in the main PomBase database or are currently being checked by the PomBase curators. That's a response rate of 50.6%.

In Canto admin interface:
Community curated publications (940)
Community curatable publications (1764)
= 53.28%

(preparing Elixir presentation for 28 Sept, but this is not urgent  at all because I can use the lower number, which is respectable  although I much I prefer the second one)

**Comment by kimrutherford** [comment]
Unfortunately the count in the admin interface was wrong.  It was including publications where the session had been assigned to community curator in the past which had then been re-assigned to an admin curator.  The stats page count only counts sessions where the current curator is a community curator.

I've fixed the admin interface query.
