### ISSUE TITLE
MF chaperone activity displayed under 'binding' not under 'activity'

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1611]
Hi Kim,

on the website when we display annotations under "activities" or "binds"
the term "copper chaperone" displays as "binds"
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016531

Should the fact that it has a non-binding parent place it under "activity"?
(I forgot how this works)

**Comment by kimrutherford** [comment]
> Should the fact that it has a non-binding parent place it under "activity"?

Currently terms with binding as a parent are displayed in the binding section.  Term that don't have binding as a parent are displayed under activities.

**Comment by ValWood** [comment]
OK I think when GO converts to has_part binding  these will move to the MF section
