### ISSUE TITLE
motif search broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1614]
Whatever your search on, it only find one result (and that result  does not match the full string)

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now.  I had corrected the protein IDs from eg. "SPAC11D3.18c:pep" to "SPAC11D3.18c.1:pep" and forgot to change the motif search to match.

**Comment by ValWood** [comment]
thanks! sorry to interrupt your hol!
