### ISSUE TITLE
update synching issue?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1615]
Not urgent but I noticed that a session I approved yesterday did not. appear today
PMID:31315658,

but also the community curation feed on the front page does not seem to be updating.
For example
PMID:32909946 from the day before, is appearing in the spotlight rotations, but not in the  feed, or the archive and the curation is not showing.

**Comment by mah11** [comment]
The only thing you really need to report is the datestamp on the home page - right now it says " Last updated 2020-09-28: 265934 annotations from 3880 curated publications".

**Comment by kimrutherford** [comment]
The load failed because pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.txt has spaces on the first two lines instead of tabs.

I've fixed that so it should be OK for tonight's load.

Tuesday night's load failed for the same reason.

**Comment by ValWood** [comment]
doh...

**Comment by ValWood** [comment]
something is still a bit weird

https://www.pombase.org/reference/PMID:32909946
is now in Pombase, and on the front page rotations, but not in the archive

**Comment by mah11** [comment]
date typo, fixed in https://github.com/pombase/pombase-config/commit/37f418fb333872d683b278dffad35d73f71f6170
(it was in the archive, but at the bottom)
