### ISSUE TITLE
PRO ID

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1616]
the pro Ids I added for
https://www.pombase.org/reference/PMID:23333317
are giving an erreor

https://proconsortium.org/app/entry/PR%3A000050399/
is giving an error, do I just need to wait, or was there an additional step?

**Comment by mah11** [comment]
Just a guess, but it might be that the terms need to reach a PRO release -- everything in their "current downloads" directory is datestamped 2020-08-18.

**Comment by kimrutherford** [comment]
It looks like this error has gone.

**Comment by ValWood** [comment]
Is there  still a config file that new PRO Ids need to go in?

https://www.pombase.org/reference/PMID:23333317
the  gene page link gives
https://proconsortium.org/app/entry/PR%3A000050398/

**Comment by ValWood** [comment]
Although that seems more like a PRO issue?

**Comment by kimrutherford** [comment]
I'm struggling with this one.  Is PR:000050398 mentioned in one of the annotations of PMID:23333317?  I couldn't see it on the page.

**Comment by ValWood** [comment]
Under "signalling adaptor activity'

We are hiding the active form  by default 
This isn't ideal, (we are hiding some of the important biology) but was pragmatic when we had the long labels but will be addressed by
https://github.com/pombase/website/issues/1623

**Comment by ValWood** [comment]
In fact this is the 2nd e.g. here:

https://github.com/pombase/website/issues/1623

**Comment by kimrutherford** [comment]
Is this still an issue?

**Comment by ValWood** [comment]
No this is good. I have already used it as an example in a couple of presentations!
