### ISSUE TITLE
display redundancy, GO  (rum1 page)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1619]
I have been tidying the rum1 annotation a bit.

I expected here
<img width="791" alt="Screenshot 2020-10-09 at 16 22 07" src="https://user-images.githubusercontent.com/7359272/95601934-22a59000-0a4c-11eb-97dc-56128d976866.png">

that the third annotation would be subsumed by the second in the default display

**Comment by mah11** [comment]
That would require the display code to follow paths in the ontology to compare *extensions*. @kimrutherford will correct me if I'm wrong, but I think it only follows ontology paths for the "primary" annotated term, and just checks whether extensions exist and if so, if they differ.

If I'm right, this is effectively a new feature request (albeit a sensible one in principle).

**Comment by ValWood** [comment]
Yes makes sense. I was blindly thinking of the part_of process as the main annotation and the 'during' as the extension.

So  yes new  feature request to follow ontology paths for annotation extensions

**Comment by kimrutherford** [comment]
> @kimrutherford will correct me if I'm wrong, but I think it only follows ontology paths for the "primary" annotated term, and just checks whether extensions exist and if so, if they differ.

That's right.  I thought there was an issue about fixing that but I can't find it.

> So yes new feature request to follow ontology paths for annotation extensions

I haven't had a go at that yet because it's a bit mind-bending dealing with the term relationships when there are multiple terms mentioned in the extension.

**Comment by ValWood** [comment]
Not urgent either.... Save for some future day(s) when you fancy a little  mind-bending challenge...

**Comment by ValWood** [comment]
redundant with 
https://github.com/pombase/website/issues/1627
