### ISSUE TITLE
display redundancy, phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1620]
I expected  nuf2delta "inviable after spore germination"  to be hidden here

<img width="870" alt="Screenshot 2020-10-13 at 12 03 24" src="https://user-images.githubusercontent.com/7359272/95886291-46cbde80-0d76-11eb-9cc2-3c21350a2b05.png">

based on any of the 3 annotations below it?

**Comment by kimrutherford** [comment]
The summary code isn't smart enough to handle that at the moment.  If the first annotation had a "has penetrance low" extension or if the term of that annotation was the same as any of the three below, it would be hidden.

The code can't handle a more specific term and more specific extension at the same time.

**Comment by ValWood** [comment]
This isn't a big deal. I'll move it to 'future'  so if you are ever rewriting this for another reason it might be included.

**Comment by ValWood** [comment]
replaced by/redundant with
https://github.com/pombase/website/issues/1627
