### ISSUE TITLE
big image issue

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1621]
https://www.pombase.org/reference/PMID:32361273

**Comment by kimrutherford** [comment]
The spotlight images need to be 300x185 pixels.  I've scaled the image and I'm re-releasing the dev site to check things.  I can't easily update the main site without including the changes from: https://github.com/pombase/pombase-chado/issues/678#issuecomment-708101655

**Comment by ValWood** [comment]
It's not urgent.

Also I will put on my list for you to tell me how to scale images. I suspect I need some image manipulation tool?

**Comment by mah11** [comment]
> The spotlight images need to be 300x185 pixels.

I thought the publication pages used images from the graphical_abstract directory. Does it have the same size restriction?

**Comment by kimrutherford** [comment]
The publication pages use the spotlight images.  The graphical abstracts aren't used yet.  I think it would be good to make the spotlight images into links to the full graphical abstract image.  I haven't done that yet.

The main site is now updated but you might need to shift-reload to see the change: https://www.pombase.org/reference/PMID:32361273
