### ISSUE TITLE
change order of "binds" extension in display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1622]
ase1

Currently:
<img width="1082" alt="Screen Shot 2020-10-14 at 13 17 55" src="https://user-images.githubusercontent.com/7359272/95987805-d6799780-0e1f-11eb-9241-bb6bda840243.png">

binds should be first , so these  extensions would read:

GO:0005515	protein binding	1037

binds klp9  during mitotic anaphase                     IPI	Fu C et al. (2009)

binds peg1  (occurs) at mitotic spindle midzone          IPI	Bratman SV et al. (2007)

binds klp9 part of microtubule sliding involved in mitotic spindle elongation active form anaphase spindle elongation protein 1 unmodified form during mitotic anaphase            IPI	Fu C et al. (2009)

This would be similar to how we display the extensions using "diretc input", and binds is a  type of diretc input

**Comment by ValWood** [comment]
(I will have some suggestions for  further rearrangment shortly  how we deal with 'modified form')

**Comment by ValWood** [comment]
What is the current ordering?

It should probably be
active form, binds, part_of, in/at, during

**Comment by mah11** [comment]
> What is the current ordering?

Since I had the file open anyway, the extension order is:

    "extension_relation_order": {
      "relation_order": [
        "directly_positively_regulates",
        "directly_negatively_regulates",
        "has_direct_input",
        "has_input",
        "has_regulation_target",
        "binds",
        "involved_in",
        "part_of",
        "occurs_at",
        "occurs_in",
        "added_by",
        "added_during",
        "present_during",
        "in_presence_of",
        "removed_by",
        "removed_during",
        "absent_during",
        "has_severity",
        "has_penetrance"
      ],
     "always_last": [
       "happens_during",
       "exists_during"
     ]

Active form is handled separately because it's from GAF column 17, not an annotation extension.

In the list, it looks like extension relations are already in the desired order, so @kimrutherford will have to explain why the actual display probably? (type in the screenshot is kinda small so I'm not sure) differs.

**Comment by ValWood** [comment]
OK yes that is the desired order.
For this ticket we can just get the order agreeing with this, ignoring "active form"

I'll open a different ticket for active form as it's a special case .  I had another idea which I will run by you.

**Comment by ValWood** [comment]
I think I know the reason that 'binds' is at the end here.
It's because it isn't obtained via a Canto-style extension, it's derived from the "with " field 

Kim how easy is that to fix?

**Comment by kimrutherford** [comment]
> It's because it isn't obtained via a Canto-style extension, it's derived from the "with " field

Yep, that's the problem.  It would be a quick fix to always put these binds extensions bits at the start of the extension.  Changing thing to follow the order in the config file would take longer.

**Comment by ValWood** [comment]
>Yep, that's the problem. It would be a quick fix to always put these binds extensions bits at the start of the extension. Changing thing to follow the order in the config file would take longer.

Putting "binds" at the front may be enough?
Because I think the rest of the ordering is OK?
Or did I misunderstand?

**Comment by kimrutherford** [comment]
I think it's OK. It's definitely closer to what you're after so I'll make that change. We can tweak it if needed.

**Comment by kimrutherford** [comment]
> It's definitely closer to what you're after so I'll make that change.

That's live now.

**Comment by ValWood** [comment]
better already. Simple change, big improvement :)

**Comment by ValWood** [comment]
Closing as the "active form" part which is more complicated is dealt with in
https://github.com/pombase/website/issues/1623
