### ISSUE TITLE
filtering, binding and extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1624]
ase1
https://www.pombase.org/gene/SPAPB1A10.09

Here
<img width="1082" alt="Screen Shot 2020-10-14 at 13 17 55" src="https://user-images.githubusercontent.com/7359272/95995492-72f46780-0e29-11eb-8e87-30c200c5e73c.png">

There is a redundant annotation from the same paper:

protein binding | 
during mitotic anaphase binds klp9 | IPI | Fu C et al. (2009)

is redundant with
unmodified form during mitotic anaphase binds klp9 | IPI | Fu C et al. (2009)

So I went in to remove. However, the 1st annotation is not instantiated. It must come from reciprocal annotation perhaps? So perhaps this is not doing a redundancy check (this should be eliminated  based on exact matching to extensions, even without the fact that  the filter doesn't handle the ontology in extensions?)

**Comment by ValWood** [comment]
<img width="784" alt="Screen Shot 2020-10-14 at 14 26 54" src="https://user-images.githubusercontent.com/7359272/95996042-22c9d500-0e2a-11eb-88fa-f9b0758c04c0.png">

Top and bottom line are the ase1/klp9 interactions

(I have added a PR: ID to one of these inappropriately, Just about to fix that....)

**Comment by kimrutherford** [comment]
Hi Val.  That looks like a screenshot of the details view rather than the summary.  We only remove redundancy in the summary view.

**Comment by ValWood** [comment]
That is a very good point :)
