### ISSUE TITLE
Displaying modified residues, part 2 (PR:IDs in column 16 protein binding extensions)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1625]
Display of  modified entities  where  the "modified form" of the bound entity is captured  using "has_substrate".
==

e.g. crb2

<img width="768" alt="Screen Shot 2020-10-14 at 14 52 06" src="https://user-images.githubusercontent.com/7359272/95998679-054a3a80-0e2d-11eb-8436-c0fff956a387.png">

In these situations, the "bound" entity is displayed twice as  **"histone H2A-beta phosphorylated 1"** and "**hta2"**

However, once  https://github.com/pombase/website/issues/1623 is implemented. This will be displayed as:

**phosphorylated histone binding**
  binds **histone hta2-S128** _part of_  **positive regulation of signal transduction involved in mitotic G2 DNA damage checkpoint** _binds_ **hta2**
  binds **histone Hta2-S128** _part of_ **positive regulation of signal transduction involved in mitotic G2 DNA damage checkpoint** _binds_ **hta1**

Which is already better. But displaying the  entity and the modified entity is redundant
So ideally this would become:

**phosphorylated histone binding**
  binds **histone hta2-S128** _part of_ positive **regulation of signal transduction mitotic G2 DNA damage checkpoint** 
  binds **histone Hta2-S128** _part of_ **positive regulation of signal transduction mitotic G2 DNA damage checkpoint**

**Comment by ValWood** [comment]
One downside of this would be that the current situation allows us to link out to PRO and to PomBase. 

Options
1. The linkout does not add so much other than  the ID. Do we need both links.
(in this case,  could we do anything else with the curated modified froms (i.e make tem avaiable in the modification section?)

2. A pop up allow 2 link outs?

3. Display a single 'binds' with both linkouts:
binds hta2 (hta2-S128)

**Comment by ValWood** [comment]
another e.g.
https://www.pombase.org/gene/SPAC8E11.02c

**Comment by ValWood** [comment]
We all like

Display a single 'binds' with both linkouts:
binds hta2 (hta2-S128)

Kim will look into  feasibility.

Otherwise we  will investigate other options. 

We also discussed putting interacting entity (from column 16) in the 'with' field as an option (but this would not work well for display of both)

**Comment by kimrutherford** [comment]
> Kim will look into feasibility.

I think we can do that.  Would you like it to look the same in the summary and the detailed view?

**Comment by kimrutherford** [comment]
> Display a single 'binds' with both linkouts:
> binds hta2 (hta2-S128)

That's implemented now, ready for tonight's load.  I think it's probably a good idea for you to do a quick test before it goes live in the morning.

You should be able to access my desktop for the next hour or two if you'd like a peek: https://desktop.kmr.nz/gene/SPBC342.05

> Would you like it to look the same in the summary and the detailed view?

For now it does.

**Comment by mah11** [comment]
looks good!

**Comment by ValWood** [comment]
Yes, great!

**Comment by kimrutherford** [comment]
This change is now on the dev server, eg. http://dev.pombase.kmr.nz/gene/SPBC342.05

Should I update pombase.org or would you like to do some checking first?

**Comment by ValWood** [comment]
It looks lovely. Go for it...

**Comment by kimrutherford** [comment]
OK, done.  Anything more to do on this issue?

**Comment by ValWood** [comment]
no, thanks!
