### ISSUE TITLE
update Pombase process slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1628]
as per
https://github.com/geneontology/go-ontology/issues/20142

please swap
GO:1901990 regulation of mitotic cell cycle phase transition
with
GO:0044772 mitotic cell cycle phase transition

**Comment by kimrutherford** [comment]
That's done for tonight's load.  I'll check in the Monday before it goes live.

**Comment by kimrutherford** [comment]
Looks OK.

**Comment by ValWood** [comment]
thanks!

**Comment by ValWood** [comment]
I have taken this ticket.
I have rerun the slim and checked in the slim file that is required for easyN.

This should  improve the connections a lot. Connections only show for things in the correct slim category 
I'll check that everything worked (Cut12 new connections  should appear in the G2/M transition network), before closing.

**Comment by ValWood** [comment]
Cut12 still doesn't appear in the GO slim output. It isn't clear why because it should slim in other categories  than the new G2/M transition. It's in the GOslim input but totally missing from the output. I have mailed GO term mapper to locate the bug.
Can close this as it is on my radar...

**Comment by ValWood** [comment]
The reason it isn't appearing is the same issue as this
https://github.com/pombase/curation/issues/2899
