### ISSUE TITLE
human ortholog not displaying

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1629]
compara_orths.tsv
SPAC3F10.17   HGNC21171

Can you figure why? The ID is correct. I don't see anything in the logs.

**Comment by kimrutherford** [comment]
> SPAC3F10.17 HGNC21171

I can't see that one in compara_orths.tsv.  This is the only ortholog for SPAC3F10.17:
```
SPAC3F10.17        HGNC:21173
```

I just did an `svn update` to check.

**Comment by ValWood** [comment]
Doh, I was looking at  http://paint.pombase.kmr.nz/gene/SPAC3F10.17
then I got the ID wrong...
