### ISSUE TITLE
grx5 missing annotation display

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1633]
grx5 has lots of annotations to mitochondrion

Component
--
  |   | SPOM | Q9HDW8 | grx5 |   | GO:0005739 | mitochondrion | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:20085751 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)
  |   | SPOM | Q9HDW8 | grx5 |   | GO:0005739 | mitochondrion | ECO:0007005(HDA) | ECO:0007005 | (HDA) |   | PMID:16823372 |   |   |   |   |   |   |   |  
ECO:0007005 | (HDA)
  |   | SPOM | Q9HDW8 | grx5 |   | GO:0005739 | mitochondrion | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15796926 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)
  |   | REFG | Q9HDW8 | grx5 | part_of | GO:0005759 | mitochondrial matrix | ECO:0000318(IBA) | ECO:0000318 | (IBA) |   | PMID:21873635 |   | PANTHER:PTN000033555\|SGD:S0... |   |   |   |   |   |  
ECO:0000318 | (IBA)
  |   | SPOM | Q9HDW8 | grx5 |   | GO:0005759 | mitochondrial matrix | ECO:0000250(ISS) | ECO:0000250 | (ISS) |   | PMID:10087920 |   | UniProtKB:Q02784 |  
ECO:0000250 | (ISS)

but on website only this shows
 | GO:0005759 | mitochondrial matrix | ISS                        with                                            Q02784 | Nakai K et al. (1999) | 238
-- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
weird...
the IBA would be filtered but the others should be displayed...

**Comment by Antonialock** [comment]
also SSC1


Gene Product | Symbol | Qualifier | GO Term | Evidence | Reference | With / From | Taxon | Assigned By | Annotation Extension
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:P22774 | ssp1 | part_of | GO:0005739                mitochondrion | ECO:0000314              IDA | PMID:2123810 |   | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | PomBase |  
UniProtKB:P22774 | ssp1 | part_of | GO:0005739                mitochondrion | ECO:0007005              HDA | PMID:16823372 |   | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | PomBase |  



but only

- | GO:0001405 | PAM complex, Tim23 associated import motor | ISO                        with                                            S000003806 | GO_REF:0000024 | 6
-- | -- | -- | -- | -- | --


do EXps get filtered when more specific ISO?

**Comment by ValWood** [comment]
Historically  they didnt. I think this has happened only recently...

**Comment by kimrutherford** [comment]
I'm confused.  Both genes have annotations for mitochondrion in the detailed view.

**Comment by ValWood** [comment]
This is what I see in the detailed view:

<img width="1126" alt="Screen Shot 2020-11-04 at 20 02 51" src="https://user-images.githubusercontent.com/7359272/98162108-c3b32980-1ed8-11eb-823b-0d53b037b235.png">

**Comment by ValWood** [comment]
I see the annotation here:
https://www.pombase.org/reference/PMID:20085751

**Comment by kimrutherford** [comment]
Did you click the "+" or click on "Show details ..."?

**Comment by ValWood** [comment]
durrrrrr

Clearly I clicked on the +.

**Comment by Antonialock** [comment]
Phew. Must have just clicked the wrong thing :)
