### ISSUE TITLE
active form and bound form confusion

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1635]
https://www.pombase.org/reference/PMID:14585996

not sure if this is a curation or a display issue

<img width="599" alt="Screenshot 2020-11-12 at 15 36 10" src="https://user-images.githubusercontent.com/7359272/98960967-f377b800-24fc-11eb-9a5e-a7795a49528a.png">

**Comment by ValWood** [comment]
@mah11 can you see how to fix this?

**Comment by mah11** [comment]
curation -- it comes from this annotation:

    FT                   /GO="aspect=F; term=protein binding;
    FT                   column_17=PR:000027613; GOid=GO:0005515; evidence=IPI;
    FT                   db_xref=PMID:14585996; with=PomBase:SPCC18B5.11c;
    FT                   date=20040712"

I'm deleting the PR:id because the paper doesn't say anything about S604 in the mrc1-cds1 interaction (it does show that mrc1 T645 is important but doesn't look into the effect of phosphorylation on the interaction).
