### ISSUE TITLE
'binds' and 'active form' display not playing nice

### ISSUE THREAD

**Issue by mah11** [pombase/website#1636]
In annotations where a specific protein isoform binds to another protein, the display of the active form and interacting protein is garbled. The active form is listed after the interactor, and the "binds" text is missing. Example from the cdc25 page:

   **active form** rad25 (cdc25/Phos:(S99,S192,S359)) 

It should show:

   **active form** (cdc25/Phos:(S99,S192,S359)) **binds** rad25 

related to #1623, #1626 and https://github.com/pombase/curation/issues/2891 (note: there was also an error in the annotation in the screenshot on the curation ticket, which has been fixed, so it's no longer a good example of this problem)

**Comment by ValWood** [comment]
thanks @mah11 !

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now.
