### ISSUE TITLE
my curation appearing in CC feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1638]
I curated this last week
https://www.pombase.org/reference/PMID:16111942

and it appeared in the community curation feed.

**Comment by kimrutherford** [comment]
It's because you curated it as  valeriewood1000@gmail.com but that account is a user not an admin:

https://curation.pombase.org/pombe/view/object/curs/5736?model=track

The easiest fix is to re-assign the session to you cam.ac.uk account and then re-approve it.

**Comment by ValWood** [comment]
I didn't even know I had that e-mail in the system. I must have re registered...
I will do that!

**Comment by ValWood** [comment]
needed to submit and approve!

**Comment by ValWood** [comment]
I'm sure it will be fine now...
