### ISSUE TITLE
Fix (or hide) the ortholog section for RNAs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1639]
![SPNCRNA-orth-section-1](https://user-images.githubusercontent.com/90474/99342280-69f72a00-28f0-11eb-80d8-d497a9d4ebac.png)

**Comment by ValWood** [comment]
Hide....

**Comment by kimrutherford** [comment]
I've hidden the Orthologs section for genes that aren't protein coding or pseudogenes.
