### ISSUE TITLE
publication pages - changes for top matter

### ISSUE THREAD

**Issue by mah11** [pombase/website#164]
This is a grab bag of small (I hope) changes to the details at the top of the publication pages. The 'discuss' tag is mainly for the bit where I have two alternative suggestions (tho curators are welcome to comment on any of it).

- [x] Make the title harder to overlook: use bold text, and remove the horizontal line between it and the ID, citation, etc.

- [ ] Add DOI where available. Link it using https://dx.doi.org/[$DOI] (we may want a little disclaimer somewhere to say we don't guarantee full-text access - mouseover?).

- [ ] Change the order of some details. I have a couple of suggestions:

 - Simply swap to: authors, citation, IDs, links, abstract.

 - Or: link the PMID to PubMed, and move Links below the abstract. Then a second PubMed link could go there fairly unobtrusively, along with DOI and EuropePMC.

- [x] You'll notice that I haven't mentioned publication date. I'm not sure we need to list it separately if we keep the version of the citation that basically includes date info anyway. Either lose the separate Publication Date entry, or use a more concise Citation that doesn't have date info (e.g. Mol. Biol. Cell 20(7):2096-107). I don't have a strong preference, so if it's easier not to munge the citation you get from PubMed, just go with the no-separate-date option.

- [x] Add a header for the annotation section, e.g. "Annotations from this publication", just below the horizontal line, outside of the annotation table boxes.

**Comment by kimrutherford** [comment]
> Add DOI where available.

I've added a Chado issue for that: pombase/pombase-chado#610

**Comment by kimrutherford** [comment]
> Make the title harder to overlook: use bold text, and remove the horizontal line

Done

> Simply swap to: authors, citation, IDs, links, abstract.

I've done that for now.  Let me know any changes you'd like.

> so if it's easier not to munge the citation you get from PubMed, just go with the no-separate-date option

I removed the date.

**Comment by ValWood** [comment]
I'm happy as it is for now....
We can rethink links when we have Doi if necessary?

**Comment by mah11** [comment]
this should stay open a bit longer because the DOI part isn't done - the task on the original list is to add the DOI at all, whatever we do with links in subsequent tickets.

(I don't mind if you want to count the reordering item as done)

**Comment by ValWood** [comment]
ah right I thought there was a new ticket for DOI but that is for canto...

**Comment by mah11** [comment]
Kim created and linked a new ticket to add DOIs to Chado. The outstanding bit of this ticket requires it.

**Comment by ValWood** [comment]
I'll contact WT about trailling curation with review when this is done, but we have enough on our plate right now so this outstanding task is non urgent

**Comment by ValWood** [comment]
closing  will open a ndew ticket for a DOI so I don't need to read all of this again
