### ISSUE TITLE
RNA sequence search widgit

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1640]
To search RNA central (add to RNA pages sequence search section?)

<img width="1057" alt="Screen Shot 2020-11-20 at 19 21 32" src="https://user-images.githubusercontent.com/7359272/99884373-b8c0fe80-2c25-11eb-809d-efb61980d348.png">

**Comment by ValWood** [comment]
consider with 
https://github.com/pombase/website/issues/39

**Comment by ValWood** [comment]
This is a widget to search NRA central 
I think this is an example of it in use at snoDB
 http://scottgroup.med.usherbrooke.ca/snoDB/sequence_similarity_search/

The button  would be added on the RNA pages sequence section here:

<img width="1159" alt="Screenshot 2020-12-15 at 20 25 00" src="https://user-images.githubusercontent.com/7359272/102268802-a760ce80-3f13-11eb-8da0-a0eafccdb72c.png">

**Comment by ValWood** [comment]
@AntonPetrov can you point us to the complete instructions/source. This was a screengrab from the talk.

**Comment by AntonPetrov** [comment]
Here you go: https://github.com/RNAcentral/rnacentral-sequence-search-embed

Please let us know if you need any help - @carlosribas or I will be happy to answer any questions.

**Comment by kimrutherford** [comment]
> The button would be added on the RNA pages sequence section here:

Just so I understand, what does the widget do?

**Comment by ValWood** [comment]
Try the snoDB e.g. 
http://scottgroup.med.usherbrooke.ca/snoDB/sequence_similarity_search/
(there are some examples).

It searched RNA central, and the output is
alignment
similar sequences
links to expert databases
Rfam classification
I think also secondary structure prediction, although none of the examples have that.


It might make this unecessary:
https://github.com/pombase/website/issues/39

**Comment by kimrutherford** [comment]
OK, thanks.  So we should show the widget in the sequence section, prefilled with the sequence of the RNA?

**Comment by ValWood** [comment]
yes please.
Can it be configured to use our existing  prefilled search box (just  an additional button for Rfam alongside the other search buttons)?

**Comment by kimrutherford** [comment]
Hi @AntonPetrov

Is it possible to pre-fill the widget with an RNA sequence when the widget is displayed?

**Comment by AntonPetrov** [comment]
@kimrutherford Not at the moment, as far as I know. 

Just to make sure I understand, you would like to host the RNAcentral search widget somewhere on pombase.org and link to that search page from individual RNAs? I think this would be a very cool way of using the widget!

Carlos is away until January but we can work with him on adding the sequence configuration option when he is back. @carlosribas - this is very similar to what you've done with r2dt-web where the URS can be pre-configured. And we could use it ourselves to restore the "Find similar sequences" button that was removed after the transition to the cloud search.

**Comment by carlosribas** [comment]
If I understand correctly, @kimrutherford wants to display the widget with an RNA sequence in the search field. Is that right? Whatever the request, I will be happy to work on improving this tool.

**Comment by ValWood** [comment]
Hi @carlosribas  we discussed this yesterday. We decided it would be more consistent  to link directly to RNA central   as we do with other resources (I think I misunderstood the widget)

**Comment by ValWood** [comment]
i.e the RNA central search is a bit different , in that it identifies the actual entry  rather than our other search options at this point   to identify similar sequencess in other organisms.

We will just add the RNA central link tot he external references (we have another ticket for this)

**Comment by AntonPetrov** [comment]
Thanks @ValWood. Regarding this point:

> the RNA central search is a bit different , in that it identifies the actual entry rather than our other search options at this point to identify similar sequences in other organisms

Our search does find similar sequences in other organisms - in addition to the sequence itself. If you choose to search all of RNAcentral, it's conceptually no different than blasting against NCBI or something like that.

**Comment by ValWood** [comment]
OK, the similarity search will be useful. Wee will take another look.

**Comment by ValWood** [comment]
We don't need this  search feature as we link to Rfam  on a gene by gene basis anyway.
