### ISSUE TITLE
Network/pathway project step1

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1641]
We  currently display a subset of networks for GOslim processes in EsyN 
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

This is limited to GO slim set because EsyN requires  this file:
[26275_slimTab.txt](https://github.com/pombase/website/files/5605022/26275_slimTab.txt)
(the output of GO term mapper).

I rerun this periodically to pick up new members and copy  to here:
pombe-embl/supporting_files

We could begin to  include links to networks for more processes if we generated this file ourselves. 
This would be useful for network building.

For example I am usually working in  a subset of the current networks
for example
http://www.esyn.org//builder.php?type=Graph&term=GO:0044772&interactionType=physical&source=pombase&includeInteractors=false
is quite large and I would usually want only mitotic G/2M transitions (for example), and to see this subset I need to get the gene list and GO to EsyN.

So
-  This would  improve my current workflow (speed up checking of the networks I'm working on - looking to see where  the gaps are, and then if they got filled correctly) even though  we intend to replace EsyN eventually it will be quite a while away, and this moves closer to our final destination.

- Networks would be updated  more regularly to show new members (at present the other files are generated daily so the updates are rapid (a couple of days)  if a gene is already in a slim set, but slower if not (i.e months usually, although I will need to do much more frequently now I am much more actively gap filling).

- It should be less buggy:
https://github.com/pombase/website/issues/1628#issuecomment-734481448
cut12 seems to have disappeared from the GOterm mapper database, I'm currently trying to locate it!

- Users would be much more exposed to the networks because they would link from a few orders of magnitude mote GO term pages.

I suggest  including any descendent of an existing BP slim term with >20 genes annotated.
 It isn't super urgent but this is one of my main projects now so I'd like it as soon as in feasible, especially if it isn't too difficult.

**Comment by ValWood** [comment]
HJmm, although there is a website component to this it should probably be on the chado tracker?

**Comment by ValWood** [comment]
-  Another (big ) advantage is that it would use PomBase GO data. The current GOslim.tab uses the GO database which still includes a lot of the annotations I am filtering (so 100's)

**Comment by ValWood** [comment]
I know we decided to recomment file transfer so this can probably close? but do we have instructions anywhere? @mah11

**Comment by kimrutherford** [comment]
> We could begin to include links to networks for more processes if we generated this file ourselves.

What's in the file and how do we generate it?

**Comment by ValWood** [comment]
It's the GO term slimmer output - but Dan only uses the term ID and the gene IDs, the rest is ignored, so can be empty columns.

**Comment by ValWood** [comment]
so
1 GO ID
2. GO term
9. comma separated gene list

**Comment by kimrutherford** [comment]
> It's the GO term slimmer output

Where is the GO term slimmer?  I've never used it.

> if we generated this file ourselves

Isn't that what you do already?  I'm still confused.

**Comment by ValWood** [comment]
It's this tool
https://go.princeton.edu/cgi-bin/GOTermMapper
but all we are doing is using the output file to provide gene lists to esyN.
This means it is only done any few months when I get the gene list, run the reach, download the file, check it in to our supporting files from where esyN collects it when updated (with the other esyN files). This wasn't too bad but the limitations are i) it only works for terms in the slim set and I want to see networks for subsets. The only way I can see these networks is to  take the list for the term and GO to esyN and generate the network with the sublist.  

Neither of these tasks has been a problem  before because they have been intermittent, but now I'm focussing on network based curation it becomes a bit arduous because I need to do it more frequently.
We have the data to create the file and include more processes. We can chat about it if it doesn't make sense.

**Comment by mah11** [comment]
> I know we decided to recommend file transfer so this can probably close? but do we have instructions anywhere? @mah11

It's pretty obvious this comment is on the wrong ticket, but I don't know where it does belong.

**Comment by ValWood** [comment]
THIS TICKET IS OUT OF DATE
