### ISSUE TITLE
JBrowse track, AT content

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1643]
Find out if Is there a JBowse plug-in to plot AT content?

**Comment by Antonialock** [comment]
https://github.com/elsiklab/gccontent ?

**Comment by kimrutherford** [comment]
Thanks Antonia.  I'll give it a go.

**Comment by kimrutherford** [comment]
I've made a first attempt at this: https://www.pombase.org/jbrowse/

It's under the "Genome sequence and features" data type in the track selector.  I had to muck about slightly with the DNA sequence track to get it all working so please let me know if you see any weirdness.

**Comment by ValWood** [comment]
It looks OK to me. I'll let Nick know. I think it should probably  have its own datatype 
GC content as it won't be easy to find otherwise.

**Comment by kimrutherford** [comment]
> I think it should probably have its own datatype

No problem.  What do you suggest?

**Comment by ValWood** [comment]
Maybe "base composition" ?

**Comment by kimrutherford** [comment]
> Maybe "base composition" ?

I've made that change for tonight's load.  It's easy to tweak later.

**Comment by kimrutherford** [comment]
> > Maybe "base composition" ?
> 
> I've made that change for tonight's load. 

That's live now.

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by ValWood** [comment]
Yes, I was waiting to hear back from Nick but he didn't respond.
