### ISSUE TITLE
minor text change

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1645]
I noticed  that when we describe the region for a sequence feature, it looks like this:

<img width="771" alt="Screenshot 2020-11-27 at 17 54 47" src="https://user-images.githubusercontent.com/7359272/101182587-30d7ed00-3646-11eb-9892-0ec1dd9a860e.png">

I wonder if it is possible to change the wording of the residues from "modified residue" to "just "residue" for these (they aren't modifications, it's just a region that has some specified function assigned)

**Comment by kimrutherford** [comment]
Should the relation name change for all protein sequence features or just the one in your screenshot?

**Comment by ValWood** [comment]
All please....

**Comment by kimrutherford** [comment]
Would it make more sense to remove the "modified residue P16-R20" text because there is a "Residue" column?

**Comment by ValWood** [comment]
Yes! completely redundent ...

**Comment by kimrutherford** [comment]
> Yes! completely redundent ...

Great.  I've changed the code and I'll check the pages after the next load.
