### ISSUE TITLE
gene upload list behaviour

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1649]
Maria reported that if a gene list has mixed names
"I just noticed that when inputing a long list of genes in the advanced query from Pombase if there are 2  or more instances of the gene name they are all kept in the query results"

e.g.

SPBC1604.08c
and
imp1

gives
https://www.pombase.org/results/from/id/6362bb69-b651-4e04-a219-76330d7a65e4

**Comment by kimrutherford** [comment]
Whoops!  I hadn't thought of that case.  It's fixed now if you reload.
