### ISSUE TITLE
Link the mitochondrial genome publication to the MT browser track

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1657]
is not working on
PMID:31364709
even though it's in Canto

**Comment by kimrutherford** [comment]
Hi Val.

That publication is not exported to Chado because it's triaged as "Sequence feature or region":
https://curation.pombase.org/pombe/view/object/pub/12776?model=track

Here is the current list of triage types that we export:
https://github.com/pombase/canto/blob/a4787106e49bfaa35be4d476b75544cd64363545/canto.yaml#L1330

Would you like to add "Sequence feature or region"?

We've been adding more types to the list over time: pombase/website#1352 pombase/website#1437 pombase/website#858

**Comment by ValWood** [comment]
Yes please!

**Comment by ValWood** [comment]
This particular paper is special because it is the now the source of the mitochondrial genome sequence.
Is there a way to recognise that? I can't think of one in the current system....

**Comment by kimrutherford** [comment]
I've added "Sequence feature or region" for tonight's load.

> This particular paper is special because it is the now the source of the mitochondrial genome sequence.
> Is there a way to recognise that? I can't think of one in the current system....

There's no good way at the moment.  I'm sure we could sort something out though.

**Comment by ValWood** [comment]
Action: See if we can come up with a way to link this publication to the mitochondrial genome in the browser...

**Comment by kimrutherford** [comment]
The easiest option is to add a link from the publication page to the MT track in JBrowse:
   https://www.pombase.org/jbrowse/?loc=mitochondrial%3A1..19433&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CDNA%20sequence&highlight=

Suggested link text:
  View the mitochondrial chromosome sequence in the PomBase genome browser

I think the link should go above the "This publication has no annotations in PomBase ..." text in the same font size.

This wouldn't be a lot of work.

**Comment by ValWood** [comment]
That would be perfect!

**Comment by kimrutherford** [comment]
How's this?: https://www.pombase.org/reference/PMID:31364709

**Comment by ValWood** [comment]
Great. I also approved the session so that the message will disappear.

@Lilindu for your information, Kim has linked your paper to  the mitochondrial sequence in the browser.

**Comment by kimrutherford** [comment]
> Great. I also approved the session so that the message will disappear.

Which message?

Can this issue be closed?

**Comment by ValWood** [comment]
I was thinking of this message

"This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types."

but I guess this is still true.
