### ISSUE TITLE
active_form isn't the first extension on cdc12 page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1658]
Did we decide that active form come first?
I think it does for activities already, but not for "binds"

cdc12 page: 
<img width="411" alt="active form first?" src="https://user-images.githubusercontent.com/7359272/104042843-e44a7900-51d2-11eb-8d6c-22954998d3aa.png">

ase1 is another example

**Comment by kimrutherford** [comment]
Could you give me an example gene page?

**Comment by ValWood** [comment]
Sorry! This is cdc12. I'll see if I can find others tomorrow.

**Comment by kimrutherford** [comment]
> Did we decide that active form come first?

Yep, in: pombase/pombase-config#45

The binds ends up at the start because it's a fake extension created from the "with" part of the annotation.  The order specified in the config is ignored in this case.  It is fixable but needs some code changes.

**Comment by ValWood** [comment]
ase1 is another example

**Comment by ValWood** [comment]
This will be great I was looking fwd to this one. Small change, big impact, annotations will be much more human readable.

**Comment by ValWood** [comment]
Looks good.
