### ISSUE TITLE
retrospective news item for PAINT annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1659]
Retrospective News Item (say 1st Nov)
We should have done a news item for this since it is a big annotation increase 
(over 3000), but I forgot....

Can we add a retrospective news item?

PomBase now includes annotation inferences using the Phylogenetic Annotation and INference Tool (PAINT). PAINT is used to manually infer annotations among members of a protein family and to make precise assertions as to when functions were gained and lost during evolution. PAINT annotations use the evidence code IBA (inferred from biological ancestor). The PAINT procedure is described in more detail in https://pubmed.ncbi.nlm.nih.gov/21873635/

**Comment by mah11** [comment]
Do you want it to appear on the front page or just in the news archive?

**Comment by ValWood** [comment]
Front page too if it is possible.
