### ISSUE TITLE
new "bin" for curation stats graphs?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1660]
do we need a new 'bin' added to
Annotations/genes for low throughput publication in 5-year intervals
https://curation.pombase.org/pombe/stats/annotation

**Comment by kimrutherford** [comment]
My suggestion is that we leave it a while until there are a few more publications in that bin.

**Comment by ValWood** [comment]
Makes sense. The sample size is still a bit small (1 HTP?)
I think this numbers has started to decrease quite a lot, which wasn't obvious from the previous 5 year bin, so we don't need to wait for it to be higher. A few months probably makes sense though.

**Comment by ValWood** [comment]
The 2021 bin is there now.
