### ISSUE TITLE
Update InterPro to v83.0

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1663]

**Comment by kimrutherford** [comment]
That's done now.  Let me know if you spot any oddities.

**Comment by mah11** [comment]
This ticket is closed. Is there an outstanding task?

**Comment by ValWood** [comment]
Ah could you add a news item.

**Comment by mah11** [comment]
OK

**Comment by ValWood** [comment]
this was announced, so removing the 'announce' label. But I think we had another update since this (In the past couple of weeks?) @kimrutherford  is that right?

**Comment by kimrutherford** [comment]
Yep, two weeks ago we updated to v84: #1680
