### ISSUE TITLE
add core promoter info to DNA binding sites inventory

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1664]
See abstract of
https://www.pombase.org/reference/PMID:25747261

**Comment by mah11** [comment]
There is a question mark in the title of this ticket. Have you decided that you do want to add something to the list? If so, which thing(s) do you want to add -- "Inr", "Inr immediate downstream motif", or both?

**Comment by ValWood** [comment]
I wasn't sure, but include both, why not.
