### ISSUE TITLE
ftp links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1666]
the links to ftp site no longer work for me.
For example link to slim on this page:

https://www.pombase.org/browse-curation/fission-yeast-bp-go-slim-terms

**Comment by ValWood** [comment]
I can't find the slim IDs file on the ftp site. Anyone know where it lives?

**Comment by mah11** [comment]
Slims are in the ftp://ftp.pombase.org/nightly_update/misc/ directory.

Whether ftp links work or not is entirely down to your browser. Kim has been thinking about switching to all https links for a little while now, as discussed in #1240. This ticket is therefore essentially redundant with that one.
