### ISSUE TITLE
Filtering by extension in summary doesn't work

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1667]
From https://github.com/pombase/website/issues/1637#issuecomment-766785354

> > Because "during" is visible by default, could the "during" filter be visible in the summary view?
>
> I tested it and it didn't work sensibly.  If I select "mitotic cell cycle" it shows only terms with that extension (which is good) but shows all the extensions for that term (which is bad):

![new-look-gene-ex-4](https://user-images.githubusercontent.com/90474/105706458-6e863180-5f76-11eb-832b-e8ee139e69e2.png)

**Comment by ValWood** [comment]
OK not to worry. It is good as it is.

**Comment by kimrutherford** [comment]
Now fixed!
