### ISSUE TITLE
Menu / quick links for gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#167]
For various reasons (space, aesthetics and prominence),
we decided that a left hand menu bar.
Could not resist posting my high tech mock up...

![mock](https://cloud.githubusercontent.com/assets/7359272/22973514/d8d5f1cc-f375-11e6-8349-e214f7392bdd.jpg)

**Comment by ValWood** [comment]
Did we say anything else about this?

**Comment by kimrutherford** [comment]
There is now a basic menu bar on the left of the gene pages.

The list is too long for the page at the moment.  Should I make the font smaller?

My next task is to make it a bit smarter, there is a gap at the top once you start scrolling that doesn't need to be there.

I also need to remove items from the menu if that section is missing from the page.  Current the menu is the same on every page.

**Comment by ValWood** [comment]
looking good so far!

I think the menu font could be smaller.

Pombase family or domain can be renamed"Protein features", because this piece of info is only a small part of this section.

We can see what it looks like after font change...

**Comment by ValWood** [comment]
Apart from the practicalities of being able to get to the parts of long pages it really does improve the page visually.
I think I  prefer this to horizontal which I thought might be better for  page width saving.
I can  for some very visual websites horizontal is fine, but for information  dense pages this provides a bit of a visual break from the text.

**Comment by ValWood** [comment]
Can you also pin the menu bar to the top of the browser view? (more chance of seeing all items)

**Comment by ValWood** [comment]
- [ ] need menu item for "basic information- to pop you back to the top of the page

**Comment by kimrutherford** [comment]
> Can you also pin the menu bar to the top of the browser view?

Yep, will do.  That's what I was trying to saying here but didn't express very well:

> My next task is to make it a bit smarter, there is a gap at the top once you start
> scrolling that doesn't need to be there

"pin" was the word I needed.

I'll try to do something like what SGD does but hopefully without the annoying jump as you scroll.

**Comment by ValWood** [comment]
Ah right I thought  your comment was this:

- [ ]  some sections do not come to the top if the preceeding section is short.
(see "target of" on cdc2 page if "complementation" is pinned already)

**Comment by Antonialock** [comment]
Awesome! 

I'd also like an option to go to the top of the page, and the literature section

**Comment by mah11** [comment]
>  some sections do not come to the top if the preceding section is short.

Actually, I think it's got nothing to do with the length of the preceding section. It's a bug: some of the links simply don't work, and "target of" on the cdc2 page is one of them. More examples are on the rad52 page, where neither "physical interaction" (follows a short section) nor "orthologs" (follows physical interactions, which is a fairly long section for rad52). Conversely, the rad52 "modification" link works. It doesn't matter whether I've previously used a menu link to go to any other section or not - each menu link either works or doesn't as soon as I arrive on a page.

> I'd also like an option to go to the top of the page, and the literature section

both seconded

**Comment by mah11** [comment]
And now here's my one request for the menu:

Can you please, PLEASE make it go to the destination WITHOUT the scrolling animation? I'm genuinely not going to be able to use the menu links with the scrolling -- seeing the text whoosh by literally gives me a headache.

If the animation added anything useful for others I might try to train myself to close my eyes at appropriate times (which I have done on some other sites when I can't just give up and go read something else), but I don't think it does. It's just some flashy whiz-bang that doesn't make intra-page linking work better than without it.

**Comment by kimrutherford** [comment]
> I think the menu font could be smaller.

It's smaller now.

> I'd also like an option to go to the top of the page, and the literature section.

I've added those.

> some sections do not come to the top if the preceding section is short

Fixed.

> Can you please, PLEASE make it go to the destination WITHOUT the scrolling animation?

Yep, fixed.  No need to shout.

> Can you also pin the menu bar to the top of the browser view?

I'll do that next.

**Comment by kimrutherford** [comment]
> Pombase family or domain can be renamed "Protein features", because this piece of info is only
> a small part of this section.

Just to be clear: Do you want to rename just the link in the menu or rename the section too?

**Comment by kimrutherford** [comment]
>  Can you also pin the menu bar to the top of the browser view?

Done.

**Comment by kimrutherford** [comment]
> I also need to remove items from the menu if that section is missing from the page. Current
> the menu is the same on every page.

The menu now shows only sections that are visible on the gene page.

I think this is the last thing to do:

> Pombase family or domain can be renamed "Protein features",

**Comment by ValWood** [comment]
All wonderful ;)

- [ ] "Protein features", rename the link in the menu and  the section

**Comment by kimrutherford** [comment]
I've renamed the family and domain section and link.

**Comment by ValWood** [comment]
Sorry, I boobed. The section should be called
"Protein Features" as on the current site...

**Comment by kimrutherford** [comment]
> The section should be called "Protein Features" as on the current site...

I'm confused - that's what I changed it to.

**Comment by ValWood** [comment]
Ignore me....shift reload is my friend...

**Comment by mah11** [comment]
>> Can you please, PLEASE make it go to the destination WITHOUT the scrolling animation?
> 
> Yep, fixed. No need to shout.

Next I suppose you'll tell me I don't need to do a happydance now that it's fixed.
(thanks :) )

**Comment by ValWood** [comment]
Phew, I'm very glad too. We really didn't need Midori with a headache all the time.....

(and I much prefer it like this too, although my aversion to wooshing was not quite so strong)
