### ISSUE TITLE
ID. mapper

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1670]
can you make it also work on the db ids?
SGD:S000003289
SGD:S000003289
SGD:S000002691

these are the only IDs I can  download from Amigo.

**Comment by kimrutherford** [comment]
We're not currently loading the SGD:... IDs into Chado.  It's not a big job to load them too.

**Comment by ValWood** [comment]
no hurry, but it would be useful. It would also be useful for Amigo to export gene names or of names but I tried every option.....

**Comment by kimrutherford** [comment]
I mostly implemented it today so it should be live on Tuesday morning.

**Comment by ValWood** [comment]
brill ;)

**Comment by kimrutherford** [comment]
That's working now.

**Comment by kimrutherford** [comment]
As a bonus we can now put SGD: IDs in the search box.

**Comment by mah11** [comment]
I updated the documentation :)
