### ISSUE TITLE
Advanced search bug (new) duplicate queries are being stored

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1672]
I trried both laptops which have different versions of chrome

<img width="1115" alt="Screenshot 2021-02-23 at 09 01 39" src="https://user-images.githubusercontent.com/7359272/108821654-d6e82300-75b5-11eb-8356-5c475d4cdc2b.png">

**Comment by ValWood** [comment]
Weird, it's had this behaviour for the past half hour but seems to have stopped now?

**Comment by kimrutherford** [comment]
Next time you see it could you see what "[details]" shows for the duplicates?

**Comment by ValWood** [comment]
Actually it is still doing it. But not for every query...

**Comment by ValWood** [comment]
It's the same, the old query remains when you 'rerun'

<img width="1129" alt="Screenshot 2021-02-23 at 09 19 18" src="https://user-images.githubusercontent.com/7359272/108823373-3c3d1380-75b8-11eb-8997-7543dadf6e23.png">

**Comment by kimrutherford** [comment]
What does the "[details]" link show for those queries?

**Comment by ValWood** [comment]
Ah, there is no 'details' link for those queries?

**Comment by ValWood** [comment]
Like these: 

<img width="742" alt="Screenshot 2021-02-23 at 09 30 52" src="https://user-images.githubusercontent.com/7359272/108824612-d5205e80-75b9-11eb-9123-3cf08b48dd99.png">

**Comment by ValWood** [comment]
So these were querries which changed this morning:

<img width="844" alt="Screenshot 2021-02-23 at 09 31 41" src="https://user-images.githubusercontent.com/7359272/108824768-0436d000-75ba-11eb-81a4-3a2611bbf9aa.png">

I reran and the 'details still doesn't appear'

**Comment by kimrutherford** [comment]
Sorry for the confusion.  The details link only appears if the query name doesn't match the details.

I'll try to reproduce the bug locally.

**Comment by kimrutherford** [comment]
> I'll try to reproduce the bug locally.

I haven't been able to so far.  If it happens again could you sends me the steps you took?

**Comment by ValWood** [comment]
Did you have any queries where the numbers had changed recently.

If not load

mitochondrial membrane fission (GO:0090149)
Proteins conserved in human/vertebrates

and
endoplasmic reticulum (GO:0005783) AND REFERENCE mitochondrion 
(GO:0005739) as these should be different tomorrow.
-- 
University of Cambridge
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by kimrutherford** [comment]
Thanks.  I've reproduced that and I think I've fixed it.

I did a quick update of the website code before the nightly load started.  It looks OK.

**Comment by ValWood** [comment]
all good!
