### ISSUE TITLE
position of new website pop-ups

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1674]
These are a bit annoying, as they obscure the link. I now know that clicking the pop-up is the same as clicking the link, but  this didn't feel intuitive, so it might be better if the pop up could be positioned so that it did not obscure the link.

**Comment by mah11** [comment]
Which pop-up(s) on which page(s)? I have not seen a pop-up obscure a link, and I suspect it may be browser- and/or platform-dependent (although I did just try 4 combinations and every pop-up appeared neatly over or under the link).

**Comment by ValWood** [comment]
The pop-ups on a gene page. Mainly GO terms.
I know  now why it is annoying.  If you want to copy past the term name you are forced to follow though to the link page to get a  the "stable" text to copy.

For example on this page:
https://www.pombase.org/reference/PMID:8515818
I think it happens when the browser isn't full screen. It's definitely browser size-dependent, but seems to happen at default browser width.

**Comment by ValWood** [comment]
I think it depends on the position int he table.


https://www.pombase.org/reference/PMID:8515818
here
protein serine/threonine kinase inhibitor activity (GO:0030291)
is obscured
and
viable small vegetative cell with normal cell growth rate (FYPO:0006822)

**Comment by kimrutherford** [comment]
> These are a bit annoying, as they obscure the link.

Is the popup appearing over the top of the term name?  I haven't seen that problem.  It's suppose to appear below the term name if there's space or above if there isn't.

> If you want to copy paste the term name you are forced to follow though to the link page to get a the "stable" text to copy.

Perhaps it's a browser specific thing?  I'm able to copy the term name in Firefox even with the popup:

![popup-term-details-1](https://user-images.githubusercontent.com/90474/109454594-7414f100-7ab9-11eb-8813-57b7113e7ee4.png)

**Comment by kimrutherford** [comment]
I've added more of a delay before the popup appears.  Maybe that will help?  Let me know if you're like the delay to be longer (or shorter).

**Comment by ValWood** [comment]
I think that works.
