### ISSUE TITLE
duplicate queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1676]
I'm still seeing this, but only occasionally:

<img width="1069" alt="Screenshot 2021-03-03 at 07 32 05" src="https://user-images.githubusercontent.com/7359272/109775033-e6401f80-7bf8-11eb-927a-180f7b260f4b.png">

**Comment by kimrutherford** [comment]
I'll have another look.  I thought I'd fixed things.

If you notice a way to reproduce this could you like me know?

**Comment by ValWood** [comment]
Seems OK now.
