### ISSUE TITLE
box in header bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1677]
I can't find the original ticket. Was it on the wrong tracker:

This is now:

<img width="679" alt="Screenshot 2021-03-03 at 15 10 14" src="https://user-images.githubusercontent.com/7359272/109848693-72c5fe80-7c48-11eb-8ab1-69c1b6027cec.png">

**Comment by mah11** [comment]
I have seen no previous report of this bug. (I also haven't seen the symptoms myself.)

**Comment by kimrutherford** [comment]
> I can't find the original ticket. 

I think we discussed it by email.

I'll work on fixing this.

**Comment by kimrutherford** [comment]
I've had go at reproducing the problem but couldn't.  Could you keep an eye on it to see if you see a pattern?

**Comment by ValWood** [comment]
Will do. I don't notice it straight away, but I'll try to be more observant ;)

**Comment by kimrutherford** [comment]
I managed to reproduce this by clicking on the gene link quickly before the pop up appeared.  Should be fixed in the morning.
