### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1678]
"hightlighted"

<img width="407" alt="Screenshot 2021-03-05 at 18 33 58" src="https://user-images.githubusercontent.com/7359272/110163580-1e598500-7de8-11eb-899a-df9eef4f39be.png">

**Comment by kimrutherford** [comment]
Thanks Val.  I make that typo a lot.  I did a grep and found a few other cases too.  It will be fixed on the main site in the morning.
