### ISSUE TITLE
Annotation_datasets

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1679]
Page is blank
https://www.pombase.org/downloads/genome-datasets%23Annotation_datasets

I can see why, but it's slightly disconcerting.

**Comment by kimrutherford** [comment]
@mah11 unfortunately in the current documentation system, anchors within pages (like "#Annotation_datasets") don't work.  If you think that is something we need could you make an issue?

That link is in two places: src/docs/downloads/menu.md and src/docs/datasets/menu.md

**Comment by mah11** [comment]
@kimrutherford 
Let's not bother changing anything. If anchors already worked it'd be convenient to use them in a handful of places, but they're nowhere near important enough to bother changing anything.

I think I got all the anchors cleared out everywhere -- I did find a few more, in addition to the specific one originally reported here (note @ValWood it's generally Very Helpful Indeed if you include the page where you find a broken or useless link, i.e. the page linked from).
