### ISSUE TITLE
ordering of extensions has changed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1681]
At one point, the substrate always appeared first?
This seems to have changed in some cases.
This is plo1:
https://www.pombase.org/gene/SPAC23C11.16
The substrate sometimes appears at the end of the extensions?

<img width="845" alt="Screenshot 2021-03-16 at 11 11 09" src="https://user-images.githubusercontent.com/7359272/111300159-accfd100-8648-11eb-86d9-26f3661a7015.png">

**Comment by ValWood** [comment]
This might be a consequence of changing  over to has_input from has_direct input?

**Comment by kimrutherford** [comment]
> This might be a consequence of changing over to has_input from has_direct input?

I don't think so because those changes won't come through until Wednesday morning.

Also that was for has_direct_input not has_substrate?

The website generation code is currently configured to put has_substrate last.  Should I change that?

**Comment by ValWood** [comment]
Damn, I added a comment to this  yesterday, but clearly didn't submit it.

I still think it is something to do with the recent changes as it only happened in the past few days.
I think the has_substrate used to be converted to "has_direct_input" and that this change is somehow not happening. In this instance I think probably  "has_substrate" would be converted to "has_direct_input" and then displayed as 'phosphoryltes'. So it htink what is different here is the display of has_input at all. If the remapping was working it would display in the right place again. Dies that make sense?

I'm sure I explained this better in my  first attempt  ;)

**Comment by mah11** [comment]
tangent alert ...

> I think the has_substrate used to be converted to "has_direct_input" and that this change is somehow not happening.

hmm, if true, that would explain the pile of errors in the latest GO snapshot report on our annotations (I also have a fix in place for monday's commit)

**Comment by kimrutherford** [comment]
> I think the has_substrate used to be converted to "has_direct_input" and that this change is somehow not happening.

Ah, sorry about that.  When I copied the obsoleted relations from gorel.obo to our OBO file is didn't copy the "alt_id:" lines.  And  is an alt IDs of has_direct_input.  When has_substrate was in the input file the loader was finding the has_direct_input term using the alt IDs and then storing has_direct_input instead.  It can't do that now.  It's a quick fix though.

**Comment by kimrutherford** [comment]
The load failed because we ended up with two relation terms that had "has_substrate" as a synonym.  Fixed now and I'll check the load on Saturday.

**Comment by kimrutherford** [comment]
It's finally fixed:
![has_substrate-fix-1](https://user-images.githubusercontent.com/90474/111857233-fac03e00-8994-11eb-91ac-78efad23a8ae.png)
