### ISSUE TITLE
Old Ensembl graphics for  dropped protein families

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1683]
this still shows the old Ensembl image (I think, because the pombe member has disappeared from the family). I have contacted Pfam about that.

<img width="970" alt="Screen Shot 2021-03-25 at 17 47 40" src="https://user-images.githubusercontent.com/7359272/112659174-0657ad00-8e4c-11eb-9917-f4c52ba88eca.png">

We might not  need to do anything about this other than locate the others and  get Pfam to fix the families. Are there any others? is it easy to find out?  (low priority)

**Comment by mah11** [comment]
Actually, that looks consistent with all the other graphics in "Protein features" sections on gene pages. Every one I've looked at recently has the "View in Ensembl browser" link, I guess because we haven't deployed a more updated protein feature display (a la #143 & #667).

**Comment by kimrutherford** [comment]
> this still shows the old Ensembl image (I think, because the pombe member has disappeared from the family).

All of the protein images were grabbed just before we switched to PomBase v2.  They haven't been updated since.

We nearly have a replacement: https://github.com/pombase/website/issues/143#issuecomment-698130830

**Comment by ValWood** [comment]
For some reason I thought we were using the new. ones. Ignore!
