### ISSUE TITLE
Display TM and coiled-coil regions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1685]
KathyG.  reported a discrepancy in the reported TMMs for cut11 (see helpdesk ticket).
This made me realise we don't display the TMMs  in the new Protein domain viewer (they should be in the InterPro file, because that is where the coordinates come from).
Also, are coiled-coil regions in there?

**Comment by kimrutherford** [comment]
> That's done now and will be on the main site in the morning.

TM domains are there now.

Let me know what you'd like to do about coiled-coils.

**Comment by ValWood** [comment]
Great!

Coiled-coil regions will be very useful too.

**Comment by ValWood** [comment]
1.  Q. Now we have TMM domains with mouseover, is this a waste of space?

"Coordinates of predicted transmembrane domains:
31..49, 59..81, 108..127, 154..176, 183..205, 220..242, 255..277"

2. We should probably say "predicted TMM domains" on the image label.

**Comment by ValWood** [comment]
Discussed with KIm. Will use Pfam Json. for coiled-coil, low complexity and disordered region.

**Comment by kimrutherford** [comment]
It will be interesting to see what this one looks like once the coiled-coil, low complexity and disordered regions are added: 

https://www.pombase.org/gene/SPBPJ4664.02
http://pfam.xfam.org/protein/Q96WV6

**Comment by ValWood** [comment]
Yes! ideally Pfam would remove that domain, it isn't very helpful!

**Comment by kimrutherford** [comment]
I've added coiled-coil, low complexity and disordered regions from Pfam to the protein details section.  Let me know if you spot any problems or if you'd like the colours changed.

The Pfam data is in this file in SVN: `pombe_embl/supporting_files/pfam_pombe_protein_data.json`

**Comment by ValWood** [comment]
looks goods!
