### ISSUE TITLE
background display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1686]
I have been wondering recently why this is in bold?
<img width="1208" alt="Screenshot 2021-04-19 at 11 42 40" src="https://user-images.githubusercontent.com/7359272/115255146-e2734880-a125-11eb-8aaf-226b44b8851a.png">

**Comment by kimrutherford** [comment]
> I have been wondering recently why this is in bold?

It seemed like a good idea at the time?  :-)

I can't remember we I made it bold.  It was added due to this tissue: #284

Shall I un-bold it?

**Comment by ValWood** [comment]
It seems odd to me to have the background in a heavier font than the allele. I hadn't really noticed it but it becomes more obvious if a genotype has a lot of background alleles.

One option would be to switch the bolding to the word "background"
dis1+[Overexpression]**background:** h- leu1-32 ura4-D18 pmd1::hisG bfr1::ura4+ DBAP

that might make more sense and be less prominent.

**Comment by kimrutherford** [comment]
This is done for the next update.
