### ISSUE TITLE
Allow gene-expression columns on gene results pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1687]
We have the data available so we should allow users to view the expression levels as columns, and to download the expression levels.

**Comment by kimrutherford** [comment]
I have a prototype of this for us to chat about sometime.  I think we may need to re-visit the layout of the column selection dialog and possibly re-think the formatting of the results table.  I don't like the way the table looks when the are lots of missing values.

<img src="https://user-images.githubusercontent.com/90474/118953492-f9b98600-b9b0-11eb-9c56-f0657aed8061.png" width="50%"/>

![gene-ex-res-table-1](https://user-images.githubusercontent.com/90474/118953511-fd4d0d00-b9b0-11eb-865b-dcae1c446a39.png)

**Comment by ValWood** [comment]
Can't you just but "Not available" in the empty columns?

**Comment by mah11** [comment]
> Can't you just put "Not available" in the empty columns?

That might work if there are no values in the column for any genes/rows (i.e. the column is completely empty).

But I think the issue is with columns that have entries for just a few of the genes in a results lists. It would look absolutely ghastly to have a column that repeats "not available" for half or more of the rows.

**Comment by ValWood** [comment]
It wouldn't look pretty but it would be useful to know NO_DATA would be better.
Also, these would likely not be columns that would be used frequently.
We could always do this until anyone thinks of a feasible alternative.

**Comment by kimrutherford** [comment]
How does this look with "NA", but faded out a bit?:

![na-gene-ex-table-1](https://user-images.githubusercontent.com/90474/119920301-3ba18800-bfc0-11eb-8887-78eca70ae939.png)

**Comment by ValWood** [comment]
I like that !

**Comment by kimrutherford** [comment]
> I like that !

Great.  I think it's an OK compromise.

I'm still working on getting the column selection dialog under control.  I thinking about hiding the gene expression check-boxes initially because otherwise there are just too many checkboxes.

**Comment by kimrutherford** [comment]
I think the dialog is a bit overwhelming when all the options are visible: https://github.com/pombase/website/issues/1687#issuecomment-844904555

So I think we should do something like this for selecting columns and for downloading:

![gene-ex-dialog-1](https://user-images.githubusercontent.com/90474/120118432-9e746880-c1e6-11eb-8844-052bbd3f65c7.png)

**Comment by ValWood** [comment]
I like that.

**Comment by kimrutherford** [comment]
These changes are now enabled on the dev site.  When you're happy with things I'll enable it on the main site.

**Comment by mah11** [comment]
One tiny thing: "ND" stands for "no data" more obviously than "NA" ... worth changing?

Documentation will only require a bit of text, so I'll do that when it's on the main site.

**Comment by kimrutherford** [comment]
Thanks for having a look.

> One tiny thing: "ND" stands for "no data" more obviously than "NA" ... worth changing?

It's an easy change.  I'm neutral on which is best.  "NA" was just the first that came to mind.

**Comment by ValWood** [comment]
yed go with ND.

**Comment by kimrutherford** [comment]
OK, I've made that change.  It will be visible in the morning.

**Comment by kimrutherford** [comment]
There is a inconsistency in the current implementation: the "ND" is displayed for missing data in every column, except for the gene name column which is left blank for no data.  Should I change that?

**Comment by mah11** [comment]
> Should I change [ND for gene names]?

I'm neutral. On one hand, consistency is nice; on the other hand, gene names are a bit different from the rest. They kinda cancel each other out.

**Comment by ValWood** [comment]
Let's add them. It makes it easier to pull out genes with no names.

**Comment by kimrutherford** [comment]
I've added "ND" for gene names.  Let me know if you like/dislike it.

And the gene expression columns are now enabled on the main server.  Let me know if you spot any problems.

**Comment by mah11** [comment]
> I've added "ND" for gene names.

Looks fine; thanks.

Two things:

- Should the gene expression columns also be available for download? They are on the dev site but not the main one.
- Should we add a way to re-hide the gene exp options once they've been revealed? (I don't have strong feelings, but the thought occurred to me. At present, "cancel" hides them but also loses anything else you've selected.)

**Comment by mah11** [comment]
p.s. I've done the documentation edit on the assumption that downloads will match dev soon enough ;)

**Comment by kimrutherford** [comment]
> Should the gene expression columns also be available for download? They are on the dev site but not the main one.

Thanks for testing.  That's fixed now.

**Comment by mah11** [comment]
I knew it would be OK to go ahead and update the documentation :D

**Comment by mah11** [comment]
> I favour not adding a hide link [reason]

OK. The only reason I thought of it is that we have show/hide toggles in other places (as does the rest of the web), but we don't have to pursue consistency to the point of absurdity.

**Comment by kimrutherford** [comment]
Thanks for the documentation.  I'm going to close this issue as it's a bit long.  If there are problems we can open new issues.
