### ISSUE TITLE
display of penetrance and expressivity in summary vs. full view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#169]
How do we feel about  moving this to detailed view? It isn't much use to know this without seeing the genotype, so there is not really any benefit to showing it in <s>full</s> summary view. Will make the compact view a bit neater...

**Comment by kimrutherford** [comment]
I guess you mean the summary when you say full view?

**Comment by Antonialock** [comment]
I think it would be ok to hide it

**Comment by mah11** [comment]
I agree that pen. & expr. can be hidden in the compact/summary view.

(I also took the liberty of editing the title and original description to reduce confusion over "full".)

**Comment by ValWood** [comment]
doh yes ;)

**Comment by kimrutherford** [comment]
Just to check: do we want to remove the "has penetrance" and "has expressivity" from the extension but keep the rest of the extension?

**Comment by ValWood** [comment]
Yes, just hide "has penetrance" and "has expressivity" in the summary view, because you need the genotype (which is already hidden in summary), for interpretation.

For now, keep the others visible because they provide useful biological context (even when the genotype is hidden).

**Comment by ValWood** [comment]
At the same time could you check that penetrance has %

**Comment by kimrutherford** [comment]
> At the same time could you check that penetrance has %

They are always displayed with a "%"

I've hidden penetrance and expressivity in the summary.
