### ISSUE TITLE
add mouseovers for our 'contacts' related icons

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1690]
<img width="647" alt="Screenshot 2021-04-22 at 20 21 42" src="https://user-images.githubusercontent.com/7359272/115773636-748a8380-a3a8-11eb-8e3c-e9f0175df0e0.png">

I think it would be useful if these icons  each had a mouse-over popup describing what each thing is:
Here are some suggested text for editing:

1. pombelist. The fission yeast community (and friends) mailing list for any discussions, announcements or questions related to fission yeast.
2. pombeSlack  Many discussion channels including conferences, talks, technical ????
3. PomBase twitter feed -announcements, anything we spot related to fission yeast and some fun stuff.
4. PomBase facebook (we don't use this much)
5. PomBase GitHub, all our project tasks organised by curation, FYPO, website, Canto (curation tool), Chado(database) feel free to browse, join, suggest....
6. PomBase Linked in (we don't use this much)

**Comment by mah11** [comment]
They all do have mouseovers with very brief text descriptions (often just the name spelled out).

I'm honestly not convinced most of them need any more than that. Anyone who doesn't already know what Twitter is won't click the icon; those who do will want to see for themselves what's there, and will likely know to expect a Twitter-ish grab bag. I suspect the same applies to Facebook and maybe also LinkedIn.

Specific suggestions:

icon | mouseover text | my comment
-----|----------------|-----------
pombelist | Fission yeast community mailing list (pombelist) | links to the info page so I don't think we need more in a mouseover
Slack | pombeSlack - Community discussion channels | not sure how much more to say; don't want any of these to be wordy
Twitter | @PomBase on Twitter | No change
Facebook | @PomBase on Facebook | No change
GitHub | PomBase code on GitHub - Canto, Chado, website, etc. | could use different examples, but don't want to laundry-list all the repos
LinkedIn | PomBase on LinkedIn | No change

Some of the rest would probably be better handled by adding some FAQ entries, and maybe a new FAQ category for "community" or something to that effect. (I'm thinking of things like how to join pombeSlack or switching digest mode off for pombelist ...)

**Comment by ValWood** [comment]
OK. I never saw the mouse overs. I see them now.
