### ISSUE TITLE
Query builder old queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1691]
NOw when a query number changes and you need to rerun it, the old query stays and you need to delete it manually.
Is that intentional? Maybe this is better?

Not a big issue, we can discuss it briefly on the next call.

**Comment by kimrutherford** [comment]
Was this only happening for phenotype queries?  If so, the small fix I just released might help.

**Comment by ValWood** [comment]
It could have been, I can't remember. But I'll keep an eye out for it  again. Not critical.

**Comment by ValWood** [comment]
seems to be fixed.
