### ISSUE TITLE
Re-visit the idea of the "Single locus genotypes annotated with .." table

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1692]
I've just fixed the [display bug](https://pomrt.gen.private.cam.ac.uk/rt/Ticket/Display.html?id=8791) reported by Meredith Betterton.  The rows of this table were empty:
https://www.pombase.org/term_genotypes/FYPO:0006715

The problem was that I hadn't fixed the code for this table to cope with the diploid changes.  I've made a quick patch so that it copes with both haploids and diploids.  But for diploid genotypes it displays just one of the two alleles at the locus.

Is that OK, or should we only display haploid single locus genotypes in this table?

**Comment by ValWood** [comment]
> Is that OK, or should we only display haploid single locus genotypes in this table?

It will depend  on the filter used in the advanced search. It's haploid by default. If the user selects diploids  too then no reason not  to include in  the table (did I understand the. question?)

**Comment by kimrutherford** [comment]
It's possible to get to the single locus genotypes table without using the query builder.

For example from here, click "View 30 single locus genotypes associated with this term ...":
https://www.pombase.org/term/FYPO:0006715

**Comment by ValWood** [comment]
OK got iot.

from here:
https://www.pombase.org/term/FYPO:0006715

I don't see
psf2Δ/psf2+[Wild type product level]
as one of the 30 single locus genetypes associated with this term?

Otherwise,  it looks good and the filtering  works fine.

**Comment by kimrutherford** [comment]
> I don't see
> psf2Δ/psf2+[Wild type product level]

Good point!  I've checked the code and it's only showing haploid single locus genotypes.

So a quick fix is to change the header to be "Haploid single locus genotypes annotated with ..."

Is that OK?

**Comment by ValWood** [comment]
I think you can implement as  a 'quick fix'  (or wait) ....we can discuss on Thursday what the expected behaviour would be. My head is full from pathogen-host interactions.

**Comment by kimrutherford** [comment]
> I think you can implement as a 'quick fix'

I've changed the page title and description to be more accurate until we can chat about it.

I've also changed the link on the term pages from:
```
View 357 single locus genotypes associated with this term ...
```
to:
```
View 357 haploid single locus genotypes associated with this term ...
```

**Comment by ValWood** [comment]
We will think about this later.
