### ISSUE TITLE
query builder with no queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1693]
If the query builder has no queries., you have the option to import queries

<img width="884" alt="ticket_canto" src="https://user-images.githubusercontent.com/7359272/116250704-ddd21400-a765-11eb-81ec-ba214888b9a0.png">

Could there be an icon  linking to the help for this? (if there is any)

**Comment by kimrutherford** [comment]
> If the query builder has no queries., you have the option to import queries

Were you on the dev site?  Import/export isn't enabled on the main site yet: #1563

**Comment by ValWood** [comment]
yeah ignore. I spotted this on dev (it's the only place I would  see  an empty query builder).
