### ISSUE TITLE
stop codons and products, e.g. crd1

### ISSUE THREAD

**Issue by mah11** [pombase/website#1694]
Last week I updated the gene structure for crd1, based on data in PMID:29958934. There are now two transcript isoforms, reflecting alternative splicing (and neither is identical to what was annotated before the paper came through). 

This gene is going to need all the isoform-specific goodies noted in #1613 ... and it reveals another issue: Product size calculations apparently don't take "internal" stop codons into account. 

The interesting biology for crd1 is that in one of the transcripts, one intron isn't spliced (intron IV), and the product is a tandem fusion protein. In the other transcript, all the introns are spliced, and the 4th exon ends up with stop codons in it, so a shorter protein gets made, corresponding to just the N-terminal part of the fusion protein coded by the other transcript isoform. It's 389 aa, and the aa sequence on the crd1 gene page shows the stop codons. But the page reports the product size as 569 aa, counting the stops as if they were aa residues.

So it'll be very good at some point to make the product size calculation clever enough to handle this sort of situation. We may run into it again (and it'll be important for the World Domination plans too; more seriously, it'd make pombase code more useful for species with lots of alternative splicing).

Also note, I made the completely spliced isoform the ".1" one - even though the other one is longer and makes a longer protein product -  because it's about 85% of the total mRNA for the gene.

**Comment by kimrutherford** [comment]
The AA counts match what Artemis calculates.  Perhaps we need to truncate the CDS in the contig file and make a UTR for the bits after the stop codon?

**Comment by ValWood** [comment]
I'm looking at this now. Kim is correct,  I think the way to do it is truncate the CDS at the stop codon. I will do that now and we can check tomorrow.

**Comment by ValWood** [comment]
I have done that. I'm wondering if there is a special reason to call the long form 02 and the short form 01? If we call the long form 01 that should solve the GO issue too?

**Comment by ValWood** [comment]
OK I switched over, will check tomorrow.

**Comment by ValWood** [comment]
did the update work?

**Comment by kimrutherford** [comment]
Sorry, the load failed and I haven't worked out why - it just exit without an error message.  I'm hoping it was just an aberration and it will work tonight.  But I'm also doing some local test loads to see it I can see anything strange.

**Comment by kimrutherford** [comment]
> Sorry, the load failed and I haven't worked out why 

I worked out why - I made a typo.  :-)

The load worked on Friday and Saturday nights.  I think this issue is all done now.

**Comment by ValWood** [comment]
the only idd thing is that although everything else is resolved by me swapping which is .01 and .02 the displayed name is still .02

mitochondrial hydrolase, N-terminal portion of Crd1 fusion protein
rather than
/product="cardiolipin synthase/ hydrolase fusion protein Crd1"

**Comment by kimrutherford** [comment]
> the only odd thing is that the displayed name is still .02

It was using the product from the highest numbered transcript instead of the lowest.  I've fixed it for the next load.  I'll check things on Tuesday morning.

**Comment by kimrutherford** [comment]
>  I've fixed it for the next load. I'll check things on Tuesday morning.

I had to re-release the site so it's now fixed.
