### ISSUE TITLE
revise scope of FY GNC

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1697]
We will be the Schizosaccharomyces GNC
update:

https://www.pombase.org/submit-data/gene-names
https://www.pombase.org/submit-data/gene-naming-guidelines
https://www.pombase.org/submit-data/gene-naming-committee-members

Snezhana will replace Matthias who has retired.

We also need to remove Matthias from the GNC mailing list, add snezhana and update Takashi and Yoshi's e-mails (their correct e-mails are in Canto).

I mailed all members to update details as I think there will be additional changes required. hang fire for a day or two.

**Comment by ValWood** [comment]
Steve Aves | School of Biological Sciences, University of Exeter |
-- | -- | --
Susan Forsburg | Molecular and Computational Biology Section, University of Southern California |
Olaf Nielsen | Department of ~Genetics~ Biology, University of Copenhagen | active, details need editing, e-mail correct
Osami Niwa | Kazusa DNA Research Institute, Kisarazu, Chiba, Japan | ?
Matthias Sipiczki | Department of Genetics, University of Debrecen | inactive
Takashi Toda | The Francis Crick Institute, London | active, details and e-mail incorrect
Nancy Walworth | Robert Wood Johnson Medical School, NJ |
Yoshinori Watanabe | Laboratory of Chromosome Dynamics, Institute of Molecular and Cellular Biosciences, University of Tokyo | active, details and e-mail incorrect
Valerie Wood | PomBase, University of Cambridge | active, details and e-mail correct
Paul Young | Queens University at Kingston, Ontario | active, details and e-mail correct

**Comment by mah11** [comment]
I used Snezhka's KCL email address for the GNC list, since I've had more from that one than the Crick address recently, but I can use both if you want.
