### ISSUE TITLE
place penetrance/severity after other extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1698]
https://www.pombase.org/reference/PMID:33771877

For the phenotype extensions can we make any severity or penetrance qualifier come at the end after the other extensions? 

<img width="980" alt="Screenshot 2021-05-11 at 13 02 03" src="https://user-images.githubusercontent.com/7359272/117811956-1808de80-b259-11eb-8f12-05481377ae54.png">

**Comment by kimrutherford** [comment]
Fixed!
