### ISSUE TITLE
explore microPubs

### ISSUE THREAD

**Issue by mah11** [pombase/website#1699]
Text, image, links for an Explore PomBase item on microPublications

**Comment by mah11** [comment]
@ValWood @kimrutherford how's this for text and links?

> [*S. pombe* microPublications](https://www.micropublication.org/journals/biology/species/s-pombe/) describe brief, novel findings, negative and/or reproduced results, and results which may lack a broader scientific narrative. Find microPublications in the PomBase simple search, or [submit your own](https://www.micropublication.org/submit-new-article/).

I've asked Daniela & co about using their cartoon in the image. I'll put something in src/assets/explore/ after I hear back.

**Comment by ValWood** [comment]
Nice!

**Comment by mah11** [comment]
a couple of possible images - preference? want any changes?
![explore_pb_micropub-2](https://user-images.githubusercontent.com/5196259/118139091-ee89b780-b3fe-11eb-98a0-dd3afaa57ba2.png)
![explore_pb_micropub-1](https://user-images.githubusercontent.com/5196259/118139094-ef224e00-b3fe-11eb-88e2-b7c6d6474d58.png)

**Comment by ValWood** [comment]
hmm, I don't mind. Both look good.

Yesterday I was also looking at micropub site to see if there was a link to all pombe micropublications. I could not see one, does that exist?

**Comment by ValWood** [comment]
Maybe the one without the pombase logo looks a bit nicer aesthetically...

**Comment by mah11** [comment]
> Yesterday I was also looking at micropub site to see if there was a link to all pombe micropublications. I could not see one, does that exist?

In [this comment](https://github.com/pombase/website/issues/1699#issuecomment-840473423) the text "*S. pombe* microPublications" links to https://www.micropublication.org/journals/biology/species/s-pombe/. To find it from the micropub home page, "microPublications" menu item --> Biology --> Species --> S. pombe

**Comment by ValWood** [comment]
Nice, our rate of publication is good.

**Comment by mah11** [comment]
added in https://github.com/pombase/pombase-config/commit/cf4dbacc37e3d258243a6b7b1ea8ce2603561dce
