### ISSUE TITLE
improve modification display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#17]
We need to display modifications better.

![arange better](https://cloud.githubusercontent.com/assets/7359272/16707030/0214ed28-45ba-11e6-90e3-508ea7c425aa.jpg)

Wishlist
- It would be useful to be able to group by residue
- Long term We's like to display modifications on a graphic see https://github.com/pombase/website/issues/15

**Comment by mah11** [comment]
On a related note ... a while back Yo & Julie showed me an InterMine beta where they've deployed a protein feature viewer using some code that UniProt actually released on GitHub - linky 

https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer

(I've been meaning to mention this for ages but kept forgetting)

**Comment by ValWood** [comment]
Is this what is currently used in the UniProt pages ? or is it new.

UniProt pages show a separate image for each modification....
http://www.uniprot.org/uniprot/Q29RF7#ptm_processing
or are they doing something swankier?

**Comment by mah11** [comment]
I would have to see it again, but I think at the very least the graphical bits were prettier! We should have Julie (or whoever) give us another tour, since I've managed to forget a lot of details by now.

**Comment by ValWood** [comment]
I wonder if this is the same thing I found. It wasn't UniProt but it was SIB/NextProt....
Unlikely that they are doing the same thing independently? Perhaps not....
When I rediscover the ticket about that I'll link these together....

@mah11 maybe we can grab a screenshot of the thing InterMine are using? and compare pros/cons in next call if different?

**Comment by ValWood** [comment]
Ah it clearly says Uniprot above. I liked the NextProt viewer.....We shall look at both... Oh the luxury of having developers in the same resource doing the same thing but differently....

**Comment by ValWood** [comment]
This is the ticket showing the NextProt viewer
https://github.com/pombase/website/issues/96
it looks a bit busy but it doesn't need to be quite like this....

**Comment by mah11** [comment]
Found the UniProt thingy I saw via InterMine - EBI did a news puff piece on it [here](http://www.ebi.ac.uk/about/news/service-news/new-view-proteins). To see it deployed go to a UniProt entry page, and click the "Feature viewer" link in the left-hand menu.

It's much prettier than the PTM view on the main entry page.

e.g. [human CDK1 (cdc2 ortholog)](http://www.uniprot.org/uniprot/P06493#showFeaturesViewer)
[human p53](http://www.uniprot.org/uniprot/P04637#showFeaturesViewer) has loads of stuff

**Comment by ValWood** [comment]
I think this is probably a better fit than the nextprot one:

https://cloud.githubusercontent.com/assets/7359272/20640045/d8406fb4-b3cc-11e6-847d-35a040d0ab0d.jpg

and it does the sequence row as a track which was what I wished that the nextprot one did:

![nextprot](https://cloud.githubusercontent.com/assets/7359272/25479228/15886cfa-2b3c-11e7-9754-03233d34d8a8.jpg)

so this seems that it will work nicely for us....

**Comment by ValWood** [comment]
nice and simple, does the job...

**Comment by ValWood** [comment]
This is a long ticket,  for the future, but if it is quick, I think it would be really really useful to have the  display order to be "residue number" in the first instance

![cdc25](https://user-images.githubusercontent.com/7359272/33562485-4aaf1b70-d90d-11e7-8bba-45bae73c74a9.jpg)

**Comment by kimrutherford** [comment]
> I think it would be really really useful to have the display order to be "residue number" in the first instance

No problem, that's quite quick(*).  Currently it's sorted by extension so those will become unsorted.

Can you remind me what the "S" means in "S178"?

Should rows with no residue be sort to the top or the bottom?

(*) It's quick as long as you're happy to sort by residue number within each modification type (cdc2 has lots).  If you want to sort the whole table it will take a bit longer because of re-formatting.

**Comment by ValWood** [comment]
Serine

Is it possible to keep the extensions "subsorting" This would mean that in cases like cdc2 tyrosine15 the list  would remain the same (because only one tyrosine is phosphorylated)

No residue at the bottom, I think...

OK to sort *within* each modification type

**Comment by kimrutherford** [comment]
So sort by residue number, then sort by extension within those sets?  I'll give that a go.

**Comment by ValWood** [comment]
Perfect, I think that would be helpful to find things in long lists...

**Comment by kimrutherford** [comment]
This is done now and will be in the main site by mid morning if all goes well.

**Comment by ValWood** [comment]
seems to be working on dev.

we'll keep this ticket as low priority for future stuff

**Comment by kimrutherford** [comment]
> seems to be working on dev.

I've updated the main site too now.

**Comment by ValWood** [comment]
I'll open a new ticket for the "future" stuff. This one is a bit long...

**Comment by ValWood** [comment]
replaced by 
Future modification display #667
