### ISSUE TITLE
decide what "basic info" we should show, and how

### ISSUE THREAD

**Issue by ValWood** [pombase/website#170]
![basic info](https://cloud.githubusercontent.com/assets/7359272/23058657/fe99f678-f4ed-11e6-9652-9421d60e0575.jpg)

**Comment by ValWood** [comment]
1. We don.t need to show obsolete names by default
(could we hide these by doing  "...."?)
Any other suggestions?

2. Is there some way that we can combine the "gene standard anme" "systematic" ID and header occurances? into the top space?
Any ideas?
(look what others do...)

3. Name description would be better at the bottom of the left hand list (there are often multiple)

4. Hmm complete aside, but I think we could delete 
swo2,tws1 and wee2 (these are just allele names)

**Comment by ValWood** [comment]
@mah11  any suggestions  for improvements here?

**Comment by mah11** [comment]
I don't actually have a big problem with the way it is now (except that I'll be glad when the product size info gets filled in). I'm not keen on trying to combine the gene name and ID entries.

**Comment by ValWood** [comment]
OK,

- [ ] I would still like to hide obsolete names by default  (with a .... ?)

- [ ] I think name description needs to go to the left because they are usually long (and often multiple),

- [ ] name description does not need to be present if there aren't any

- [ ] maybe the font size for this section could be the same as the other sections? Its slightly larger

**Comment by kimrutherford** [comment]
> I would still like to hide obsolete names by default (with a .... ?)

Do you mean just have a "..." that is a link that shows the obsolete IDs?

> I think name description needs to go to the left because they are usually long (and often multiple),
> name description does not need to be present if there aren't any

That's fixed.  Here's an example: http://pombase2.bioinformatics.nz/gene/SPAC24B11.06c

> maybe the font size for this section could be the same as the other sections? Its slightly larger

The text already looks quite small on my screen:

![screenshot from 2017-02-24 17-16-31](https://cloud.githubusercontent.com/assets/90474/23290391/3f05f1d6-fab5-11e6-80f4-a2008421c641.png)

**Comment by ValWood** [comment]
Its quite a bit bigger than the other data...

compare to MF here:

![font](https://cloud.githubusercontent.com/assets/7359272/23295360/1c826cfe-fa68-11e6-9353-8db865a24c3b.jpg)


The sty1(SPAC24B11.06c) should stay the same (or could even be a little larger?)

**Comment by ValWood** [comment]
> Do you mean just have a "..." that is a link that shows the obsolete IDs?

yes.

Maybe we could do the same for multiple "name descriptions" too. These are not very important.
That  do instead of reducing font size...

**Comment by ValWood** [comment]
Some pages look a bit strange eg:
![looks weird](https://cloud.githubusercontent.com/assets/7359272/24498718/49a20ba6-1537-11e7-81d4-f933d34f77f0.jpg)

**Comment by ValWood** [comment]
maybe this would be ok if the 2nd column was much narrower than the first column?

**Comment by ValWood** [comment]
Would this be better:

![suggestion](https://cloud.githubusercontent.com/assets/7359272/25562940/90a968f4-2d89-11e7-9bde-5f733c671db4.jpg)

**Comment by ValWood** [comment]
I still think the gene name centrally withough the systematic ID would be better. The only DB that puts the systematic ID up froont is SGD and it's a bit more meaningful for them.  The systematic ID is clearly below in the header.

It could even be
                                  Gene standard name: Sws1 
in the header o that hte first line below could be deleted

**Comment by kimrutherford** [comment]
> I still think the gene name centrally withough the systematic ID would be better. 

OK, I'll do that.

I'll have go at fixing the whitespace but it's a bit fiddly with tables in HTML.  It's especially tricky to get it to look right when the page is resized.

**Comment by ValWood** [comment]
I think I would rather see the product   at the top too...

--------------------------Gene standard name: Sws1
Product                                                                   
Systematic ID
synonyms (only if present)
Location

**Comment by ValWood** [comment]
If you have any other ideas.....

**Comment by kimrutherford** [comment]
I've moved the gene name to be centred and moved the product to the top.  To fix the gaps in the table I've made the table centred.  Previously it was always as wide as the window.  On a small display it looks the same as the previous layout.  On a large display it looks odd but slightly better I think.

I've moved the other details around a bit.  It's now:

    Product               Characterisation status
    Systematic ID         Feature Type
    Genomic location      Product size
    Name description      Synonyms

I put Name description and Synonyms at the bottom because they are the two things that not every gene has.  It looks a bit odd to have empty cells in the table when they were missing.  What do you think?

**Comment by ValWood** [comment]
Hmm, I think its better in some ways but now I see it
	cdc2 (SPBC11B10.09)
gene standard name cdc2 probably  looked better....

How many font sizes is it bigger than the rest of the page?

**Comment by ValWood** [comment]
I often don't have my browser full width (its easier to find things on the desktop with a small screen)...

this makes the  basic info a little messy...
![full width](https://cloud.githubusercontent.com/assets/7359272/25590799/ca550e3e-2ea9-11e7-8512-95fc380f1286.jpg)

Do others do this, or is it only me?

Anyway it made me wonder if the whole section would be better if it was just a single column , instead of 2 colums...at leas then each item could be restricted to a single line which would be unlikely to wrap??
thoughts?

**Comment by ValWood** [comment]
I think that right now, the browser needs to be wider than default to prevent the line wrapping kicking in.....

**Comment by mah11** [comment]
I don't like the "Gene standard name:" in the header. It's boring and makes you read too much before the interesting thing, i.e. the gene name.

I also think it's kind of odd that the text in the top table is larger than in the rest of the page. Only the gene name at the top really needs to be big.

**Comment by ValWood** [comment]
yeah, I though the same once I saw it.

So gene name large at top.
Include "gene standard name" cdc2 underneath

I'm still wondering if a single column format would be better than 2 column....

**Comment by mah11** [comment]
hmm, not sure I have an opinion, especially without seeing 1 vs. 2 columns side-by-side

I suspect I'll get used to either, as long as things stay in the same place once we decide and Kim deploys it.

**Comment by kimrutherford** [comment]
> So gene name large at top.
> Include "gene standard name" cdc2 underneath

I've done those changes.

**Comment by ValWood** [comment]
I think that looks better...anyone else?
