### ISSUE TITLE
emboldened diploids

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1703]
See phenotypes here https://www.pombase.org/reference/PMID:33888556

I'm not keen on diploids being bold and haploids non-bold.
They look different but it isn't necessarily clear why, and it makes alleles difficult to distinguish from terms. I don't have any immediately better ideas though....but on balance I prefer that  they are non-bold.

Maybe the slash in bold would help it to stand out a bit?
I don't have e a problem with people not noticing they are looking at diploids because if they see the same allele twice with a "/" in between, that screams 'diploid'. Also the term itself is often a 'giveaway'

thoughts @mah11  @JackyVH @juanmatacambridge

**Comment by kimrutherford** [comment]
> I'm not keen on diploids being bold and haploids non-bold.

I think I agree that bold is too much but I also think we should distinguish them in some way.

> They look different but it isn't necessarily clear why,

It's clear once you mouse-over.

**Comment by ValWood** [comment]
No action.
