### ISSUE TITLE
search result help icon and mouseover

### ISSUE THREAD

**Issue by mah11** [pombase/website#1704]
From an email thread ...

In the table of advanced search results, could we add the little info "i" to the "Results" header cell, with helpful mouseover text (e.g. "Number of matching genes. Click to go to the gene list.")? The idea is to help people notice that the result counts are links.

**Comment by kimrutherford** [comment]
That's done now and will be visible in the morning.  It looks like this.  Let me know if you'd like the wording or pop-up position changed:

![history-help-1](https://user-images.githubusercontent.com/90474/130382729-15451274-6466-460b-9c51-50cb58057e62.png)
