### ISSUE TITLE
BUG, inflated number of annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1705]
See npr2

GO:0034198 | cellular response to amino acid starvation | ISO&nbsp;with&nbsp;S000000778 | GO_REF:0000024 | 603

says 603, but there are  only 8

**Comment by kimrutherford** [comment]
I think it's because it's counting the genes from all annotations of the gene where GO:0034198 appears in an extension.  Not helpful!  I'm working on a fix.

**Comment by kimrutherford** [comment]
I've fixed this in time for the nightly load.  I'll check everything is OK in the morning.
