### ISSUE TITLE
phaf date disconnect between documentation and data

### ISSUE THREAD

**Issue by cmungall** [pombase/website#1708]
https://www.pombase.org/downloads/phenotype-annotations

The date is the date on which the annotations are created. Format: YYYY-MM-DD

Me like. ISO-8601 good.

however:

```bash
$ cut -f20 download/pombase.phaf.tsv | head
Date
20151208
20151208
20151208
20151208
20151208
20151208
20151208
20190712
20141120
```

**Comment by kimrutherford** [comment]
Thanks Chris.  I think I was copying GAF when I wrote the code.  I've fixed the download file and changed the code to use ISO in future nightly updates.
