### ISSUE TITLE
suggestions  for if you want to "see details" for a single section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#171]
If you are scrolling down the huge set of phenotypes for cdc2

say multi allele phenotypes, scroll down to cdc2
viable elongated vegetative cell, and you are interested in the  details,
you need to go up, uncollapse the age, and then find the term gain in the uncollapsed page.

In the old site we has the + option....

I wasn't keen on adding this back, it looks a bit messy).
Maybe it could be neater?

Other suggestions?

**Comment by ValWood** [comment]
Suggestion:

Link opens up section.
Then this section has a link  displays the annotation details and links to the term details and lists


Short term use " +" legacy style

**Comment by Antonialock** [comment]
one alternative to " +" legacy style:

paypal has clickable row (cursor changes to a grabby hand when mousing over) with separately clickable  hyperlinks inside each row. When you click the row it expands, when you click a hyperlink it opens in a new tab.

**Comment by kimrutherford** [comment]
I think this is more complicated now that we are hiding redundant terms.  If you click the [+] to show a term but that term has hidden ancestors should it show the ancestors too?

**Comment by kimrutherford** [comment]
> I think this is more complicated now that we are hiding redundant terms. I

We decided to ignore the hidden terms.

**Comment by kimrutherford** [comment]
I've had first go at this.  Formatting of the columns is a bit naff for now but it's a start.  I copied the [+]/[-] buttons from PomBase v1 while we think about what to use instead.

I've only just got it working so I haven't tested it thoroughly.  Could you have a play with it and let me know what bugs you find?

**Comment by ValWood** [comment]
well, it seems to be working pretty well to me and the formatting isn't so bad, at least for those I looked at.

For the icon, I wonder if a simple "+" would suffice without the box?

**Comment by kimrutherford** [comment]
Bug From Val: the opened up terms don't reset when you change page.

**Comment by kimrutherford** [comment]
> For the icon, I wonder if a simple "+" would suffice without the box?

I'm happy to try that if you'd like.

**Comment by kimrutherford** [comment]
> Bug From Val: the opened up terms don't reset when you change page.

Fixed.

**Comment by ValWood** [comment]
> I'm happy to try that if you'd like.

what do you think? anyone? I guess its worth trying....might be a bit neater?

**Comment by ValWood** [comment]
We can probably close this,  I think its fine. Or should we try just a '+"? Would that look a bit lost?

**Comment by kimrutherford** [comment]
I'm closing this while we think about it.  :-)
