### ISSUE TITLE
update JBrowse quick start

### ISSUE THREAD

**Issue by mah11** [pombase/website#1715]
from @Antonialock via helpdesk:

add to access routes in documentation/JBrowse_quick_start: 

"Go directly to a primary publication page for a dataset and choose what tracks to view in the browser
e.g. https://www.pombase.org/reference/PMID:21151114"

**Comment by ValWood** [comment]
Can we also add the instructions how to export a sequence region to the QuickStart guide and as part of the main FAQ.

2 users have asked for this  (Nick and Frank)

I'm not sure where the instructions are. @kimrutherford  can you paste a link  to the YouTube video?

**Comment by kimrutherford** [comment]
> I'm not sure where the instructions are. @kimrutherford can you paste a link to the YouTube video?

It was from an email on the 10th: https://www.youtube.com/watch?v=mH6kwbqiLiQ

I'm wondering if we need an easier to find sequence download tool that we can add to the "Downloads" menu.

**Comment by ValWood** [comment]
I still think people would like to do it from the browser where they can see the context of the surrounding features.

**Comment by ValWood** [comment]
Right, I actually sent that video to Frank!

**Comment by ValWood** [comment]
> I'm wondering if we need an easier to find sequence download tool that we can add to the "Downloads" menu.

this would be good too though...

**Comment by mah11** [comment]
>> I'm wondering if we need an easier to find sequence download tool that we can add to the "Downloads" menu.
> 
> this would be good too though...

It is, however, completely & utterly off-topic for this ticket.

**Comment by kimrutherford** [comment]
> I'm wondering if we need an easier to find sequence download tool that we can add to the "Downloads" menu.

I've made an issue about it: #1716
