### ISSUE TITLE
BUG, when I search on GO terms I get FYPO terrms.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1722]
<img width="986" alt="Screenshot 2021-07-11 at 14 14 10" src="https://user-images.githubusercontent.com/7359272/125196585-5ec38680-e252-11eb-8ff8-6770405db918.png">

**Comment by ValWood** [comment]
Only seesm to happen with this term though...

**Comment by kimrutherford** [comment]
Sorry about that.  I've fixed the bug and the site is re-deploying now.  I'm off to bed.  If all goes well the site should be fixed in 30-ish minutes.
