### ISSUE TITLE
bug in TMM domains

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1724]
I was trying to find the maximum, out of curiosity.
Weirdly we have 
6998 | tm_domain_count(≤31

and it seems to include everything (including onion coding sequence).

This seems to be because I did not select a minimum, and it is therefore including 'zero' ?. we should force people to select a minimum, and only include proteins.

**Comment by ValWood** [comment]
anyway maximum is 20 ;)
 wonder what is max for low complexity or coiled-coil region ? (this will be a little bit arbitrary because it might be a single region which is fragmented, but people can ignore and retrieve everything if they know the maximum.

**Comment by kimrutherford** [comment]
> This seems to be because I did not select a minimum, and it is therefore including 'zero' 

I don't think that's a bug just unexpected.  :-)

If you ask for ≤31 and don't set a minimum you get the genes with no TM domains.  0 ≤ 31 after all.  Just like if you ask for all genes with less the 5 introns - you should get the genes with no introns (not that we can do that in a query).

> we should force people to select a minimum,

I think the easiest fix to make these queries less surprising is to use "1" as the default minimum.  And document that by using "min (default 1) ..." as the placeholder in the box.  Would that be OK?

![min-max-query-builder-1](https://user-images.githubusercontent.com/90474/125291538-a0008700-e375-11eb-83a9-2785ec82d6a1.png)

**Comment by ValWood** [comment]
That would work. Probably not worth fretting about as I have never done it before. I didn't realise until I saw that the results were more than the number of protein-coding genes.

You could do this sometime though.

**Comment by kimrutherford** [comment]
OK.  I'll fix it when I implement #1720 since it's the same code.

**Comment by kimrutherford** [comment]
I'm going to close this as the fix is implement in #1720.
