### ISSUE TITLE
Do not display ND for absence of gene name on website.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1725]
Re:
https://github.com/pombase/website/issues/1687
There is a inconsistency in the current implementation: the "ND" is displayed for missing data in every column, except for the gene name column which is left blank for no data.  Should I change that?

_Originally posted by @kimrutherford in https://github.com/pombase/website/issues/1687#issuecomment-854564267_

--

Me and @mah discussed today in light of comments from @snezhkaoliferenko

ND  makes sense 'data columns' like 'expression'  but seems weird for a gene name, as the (is not data from a data point that wasn't tested).

So  for gene name just have blank, the inconsistency is OK.

**Comment by kimrutherford** [comment]
> is not data from a data point that wasn't tested
> So for gene name just have blank, the inconsistency is OK.

There are a bunch of columns like that.  Should I remove the ND everywhere except for gene expression data point?

**Comment by ValWood** [comment]
Maybe, not sure - we can discuss later.

**Comment by ValWood** [comment]
I forgot about this. Discuss Thursday?
v

**Comment by ValWood** [comment]
Action, remove ND from everywhere except for gene expression. (will probably use in the future for other individual datasets).

**Comment by kimrutherford** [comment]
> Action, remove ND from everywhere except for gene expression.

Done.
