### ISSUE TITLE
remove old EBI ftp site warning

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1726]
I think we can remove:
Warning: S. pombe files are no longer available from the old “pombase” FTP site within the EBI domain. If you have a link that contains ftp.ebi.ac.uk, please check these pages for a link using https://www.pombase.org/. Please contact the PomBase curators if you need help finding a file or directory.

and if people do get tot he EBI directory, this message is in the README:
PomBase is no longer hosted at EMBL-EBI. Please visit 
https://ftp.pombase.org/. For release files please see 
ftp://ftp.pombase.org

**Comment by mah11** [comment]
I moved the text to the bottom of the main datasets page, and deleted it from other pages.
