### ISSUE TITLE
Add links to alpha fold

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1728]
example link
https://alphafold.ebi.ac.uk/entry/Q9C0Y8

@mah11  can we do this with Uniprot accessions directly?  I assume so?
If so can you add because  I'm not sure where!

**Comment by kimrutherford** [comment]
The cleanest way of doing this is to get that site added to the GO xrfs file

**Comment by mah11** [comment]
pull request here: https://github.com/geneontology/go-site/pull/1720

**Comment by ValWood** [comment]
but I don' think they have a prefix in the same way, they just use the uniprot accession

we already have link which work with a uniprot accession, like
https://swissmodel.expasy.org/repository/uniprot/P04551

**Comment by ValWood** [comment]
ok i clearly don't know what I am talking about ;)

**Comment by mah11** [comment]
I think our stuff also consults GO xrefs for the URL syntax as well as IDs ...

**Comment by kimrutherford** [comment]
> I think our stuff also consults GO xrefs for the URL syntax as well as IDs ...

Yep.  That hopefully gives us a little bit of protection in the case where the URL changes.  With luck the GO xrfs file will be fixed in that case and we'll pick up the change on the next load.

Once GO xrfs has an entry for AlphaFold we can make it appear in the External references section by adding something like this:

```

    {
      "ref_type": "Structure",
      "feature_types": ["mRNA gene"],
      "name": "AlphaFold",
      "description": "AlphaFold structure predictions",
      "field_name": "uniprot_identifier",
      "go_xrf_abbrev": "AlphaFold"
    },
```

to the `external_gene_references` setting in `pombase_v2_config.json`.

Some documentation is here: https://github.com/pombase/website/wiki/Config-file#external_gene_references

**Comment by ValWood** [comment]
well I seemed to have permission to merge the GO pull request, so I did it.....

So you can go ahead and add...

**Comment by kimrutherford** [comment]
> So you can go ahead and add...

We'll need to wait until http://current.geneontology.org/metadata/db-xrefs.yaml is updated.

**Comment by ValWood** [comment]
Right doesn't the pull request do that?

**Comment by kimrutherford** [comment]
It probably needs to go through the GO release pipeline.

We don't get our copy of GO xrefs straight from Git.  We use the version that goes with the GO releases.

**Comment by ValWood** [comment]
If that is the case we probably need to wait for a month ..... I hope that file isn't connected to the release.....

**Comment by ValWood** [comment]
Unless it is included with the snapshot. If it doesn't update I will ask.

**Comment by kimrutherford** [comment]
It might be the snapshot.  I don't know what is on current.geneontology.org

**Comment by mah11** [comment]
Every GO release and snapshot, and the "current" page, has a little "summary.txt" link that leads to a page with various tidbits including a datestamp.

The ... er, current [summary for current.geneontology.org](http://current.geneontology.org/summary.txt) has the same datestamp as the [summary for the most recent release](http://release.geneontology.org/2021-07-02/index.html). (Even the snapshot doesn't have the AlphaFold entry yet; it [last ran](http://snapshot.geneontology.org/summary.txt) before I did the pull request.)

**Comment by kimrutherford** [comment]
Since it seems that it's going to take a while I've temporarily added configuration for AlphaFold locally.  So it will be visible in the morning.

I plan to remove the local configuration once it's available from current.geneontology.org so I'd like to leave this issue open.

**Comment by kimrutherford** [comment]
> So it will be visible in the morning.

That worked, so there are now AlphaFold links on every protein coding gene page.

**Comment by kimrutherford** [comment]
I swapped the config to use the AlphaFold URL from GO db-xrefs.yaml
