### ISSUE TITLE
Allow direct querying of existence of orthologs 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1729]
It would be useful to have a query option for:
  - has cerevisiae ortholog
  - has human ortholog
  - has japonicus ortholog

Currently you can do this with QuiLT by clicking in the ortholog columns (which isn't obvious to new users).  Or you can use the taxonomic conservation query.  But there's no direct way to do it.

Needed for: japonicusdb/japonicus-config#41

**Comment by kimrutherford** [comment]
I've had a go at this so for japonicus we can now query by ortholog using the new "Genes with orthologs" tab in the query builder.  This allows queries like "has ortholog with: S. cerevisiae NOT has ortholog with: S. pombe":
https://www.japonicusdb.org/results/from/id/563498cf-e74c-4c39-b760-8946e5145e67

It works in the dev PomBase too:
http://dev.pombase.kmr.nz/results/from/id/9672c479-6817-48c0-9168-c7d77345cede

It's not enabled in the main PomBase site yet because I wanted to do more testing and to improve the heading and text.  Also I think there are now too many tabs.  I'd like to think about how to group the tabs together so it doesn't take up so much vertical space.

Now this is implemented I can work on: japonicusdb/japonicus-config#41

**Comment by kimrutherford** [comment]
I think the interface is a bit bare-bones at the moment.  Any suggestions?  Could the text prompt be expanded.  It's currently
"Retrieve proteins that have an ortholog in:"

![has-organism-query-node-1](https://user-images.githubusercontent.com/90474/130374396-ee3c1568-c41a-46ec-8d2f-1007b57e397b.png)

**Comment by ValWood** [comment]
I think that seems OK, unless @mah11  has further suggestions.

**Comment by kimrutherford** [comment]
I've added "Protein with orthologs" to the PomBase configuration.  It will be visible on the main site on Thursday morning.  It's already enabled for JaponicusDB.

**Comment by ValWood** [comment]
Great. I  suggest we combine 
Taxonomic conservation 
and 
Proteins with orthologs 
as 
Orthologs and Conservation

**Comment by ValWood** [comment]
Ithink this one can close, seems complet? Reopen if not...
