### ISSUE TITLE
redundancy in GO display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#173]
pom1

has_substrate pom1 part_of negative regulation of protein localization to plasma membrane
appears twice

(not that antonia updated these extensions  this week to make them the same (they were different). I can't think how this could affect things  but I thought I would mention it.

**Comment by ValWood** [comment]
![look at pom1](https://cloud.githubusercontent.com/assets/7359272/23094113/bfd0bea6-f5ea-11e6-80c3-da662e068998.jpg)

**Comment by kimrutherford** [comment]
I've fixed it to avoid showing identical extension in the summary.
