### ISSUE TITLE
pipe separated GO ID in from field do not resolve properly

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1731]
Very minor.

see
https://www.pombase.org/gene/SPAPYUK71.03c
protein membrane adaptor
IC from 0005543|GO:0061817

**Comment by ValWood** [comment]
Also the link.This might be a duplicate ticket tho'

**Comment by mah11** [comment]
Those look like they should be comma-separated.

**Comment by ValWood** [comment]
Oh. yes, they should! Pip isn't valid here. will fix...

**Comment by kimrutherford** [comment]
I've just been looking to work out where the annotation comes from, but failed.  Do you know?

GOA has this so it must be a PomBase annotation?:

```
UniProtKB       Q9UT00  SPAPYUK71.03c           GO:0043495      GO_REF:0000111  IC      GO:0005543|GO:0061817   F       Uncharacterized protein PYUK71.03c      SPAPYUK71.03c   protein taxon:
284812  20200319        PomBase
```

**Comment by kimrutherford** [comment]
Sorry, I see it in the contig file.  I'll go to bed instead.  :-)

**Comment by ValWood** [comment]
> Sorry, I see it in the contig file. I'll go to bed instead. :-)

YES!!!!!
