### ISSUE TITLE
false positives from link checker

### ISSUE THREAD

**Issue by mah11** [pombase/website#1733]
When I ran the link-checking script, it flagged these:

     src/docs/documentation/orthologs.md:13:  faq/how-can-i-search-s.-cerevisiae-ortholog-s-homolog-s-s.-pombe-gene
        [budding yeast](faq/how-can-i-search-s.-cerevisiae-ortholog-s-homolog-s-s.-pombe-gene)

     src/docs/documentation/JBrowse_quick_start.md:179:  faq/there-any-rdna-repeat-sequences-pombase
        [rDNA](faq/there-any-rdna-repeat-sequences-pombase).

     src/docs/status/sequencing-status.PomBase.md:54:  faq/there-any-rdna-repeat-sequences-pombase
        #### [Ribosomal DNA information (FAQ)](faq/there-any-rdna-repeat-sequences-pombase)

     src/docs/about/data-sources.md:7:  archive/spotlight
        For images used on the home page, see the [Research Spotlight archive](archive/spotlight)

     src/docs/faq/how-can-i-display-a-sequence-region-using-sequence-coordinates-in-the-genome-browser.md:13:  can-i-view-nucleotide-sequence-genome-browser
        To see the DNA sequence, see [this FAQ](can-i-view-nucleotide-sequence-genome-browser). 

     src/docs/faq/how-can-i-find-protein-localization-data.md:22:  faq/there-list-protein-complexes-s.-pombe-and-their-subunits
        [FAQ](faq/there-list-protein-complexes-s.-pombe-and-their-subunits)).

But in each case, the link works when I try it, and the file has the correct url as far as I can tell (for FAQs I checked against what I copied from the inspector thingy).

Meanwhile, I've fixed the true positives it caught.

(from https://github.com/japonicusdb/japonicus-config/issues/3)

**Comment by kimrutherford** [comment]
I've fixed all the false positives by improving the script.

I've fixed one warning that seemed to be a true positive: bc52534643a9ca40ea23620fbaa8f9e224ca1252

**Comment by mah11** [comment]
thanks!
