### ISSUE TITLE
ID mapper question (pombe/japonicus)

### ISSUE THREAD

**Issue by mah11** [pombase/website#1738]
Question for @kimrutherford: Do you plan to update the PomBase ID mapper take japonicus gene names and/or IDs?

If so, let me know when it's done and I'll update the documentation to match (will be useful for the JaponicusDB version too, since that already does the equivalent).

**Comment by ValWood** [comment]
That would be  really useful.

**Comment by kimrutherford** [comment]
> Do you plan to update the PomBase ID mapper take japonicus gene names and/or IDs?

Yep!  The configuration is ready to go for when JaponicusDB is released.

**Comment by kimrutherford** [comment]
> If so, let me know when it's done

Done!
(a few days ago)

**Comment by mah11** [comment]
looks like I updated the documentation already too :)
