### ISSUE TITLE
News item and updated rotation feature for disease associations:

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1739]
https://www.pombase.org/results/from/id/58ea50d0-d07d-4933-89d8-fca9adf2f2cf

Add a news item, it's a good increase...

and a new rotation to replace:
Explore PomBase: 25% of pombe proteins have disease associations
Access Disease associations for 1239 of the 3540 pombe genes with human orthologs (up from 987 in 2019), using the MONDO disease ontology. Or browse the disease slim set here.

(keeping the old one in archive)

We can rotate  the rotsations between micropub and disease genes.

**Comment by mah11** [comment]
Should the new "explore" item use the same image as the old one?

**Comment by ValWood** [comment]
yeah...I like that image.
