### ISSUE TITLE
should we display single extensions on the same line

### ISSUE THREAD

**Issue by ValWood** [pombase/website#174]
Havve been wondering about this for a while...

![look at pom1](https://cloud.githubusercontent.com/assets/7359272/23094122/e419d2f2-f5ea-11e6-83d8-3d0f5bf03baf.jpg)

**Comment by ValWood** [comment]
Do in the example above, the "protein serine/threonine kinase activity"
would be on  multiple lines, but all of the others would be on the same line?

**Comment by Antonialock** [comment]
For me it looks ok & is quite space saving when browsing. It might look confusing though if you don't know that's how it is organized?

**Comment by ValWood** [comment]
non issue
