### ISSUE TITLE
default behaviour for haploid/diploid filter in Advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1740]
We need to discuss the behaviour of the conditions filter for haploid/diploid multi-single allele loci

I'm not sure that it makes sense to have 'haploid' selected by default, especially if you search on a phenotype which only occurs in diploids.

I think my preference would be to have this 'unselected' by default (currently not possible)

**Comment by mah11** [comment]
It does have a "Haploid or Diploid" option ... and that is the default.

Does your browser cut off the selector width so it's too short to see the whole thing?

**Comment by kimrutherford** [comment]
The default is "Haploid or Diploid" if there are both haploids and diploid genotype in the list.

If there are just haploid genotypes, it selects "Haploid" and greys-out "Diploid".  Perhaps it should show "Haploid or Diploid" greyed-out too?

**Comment by mah11** [comment]
> If there are just haploid genotypes .... Perhaps it should show "Haploid or Diploid" greyed-out too?

That would make it really hard to misinterpret, so is fine by me.

**Comment by kimrutherford** [comment]
> I think my preference would be to have this 'unselected' by default (currently not possible)

I think my reasoning was that if there was an "unselected" option and there were only haploids in the list then "Unselected" and "Haploid" would do the same thing - no filtering would happen either way.  I thought that would be confusing.  I admit though that the current implementation isn't entirely un-confusing.  :-)

**Comment by ValWood** [comment]
I'm more bothered that  people won't always check the default selection.

If you search on 
"abnormal meiotic chromosome segregation"
haploid is selected by default. This doesn't really make sense (we are dealing with it), but we do have annotations.

Most people would probably hit submit because they are *used* to using the defaults, they. are likely not to think to check them.

but


87 | abnormal meiotic chromosome segregation (FYPO:0000151) [single locus haploid genotypes]
-- | --

 I think it would be better, if both haploid and. diploid alleles were present, then BOTH were selected by default.

497 | abnormal meiotic chromosome segregation (FYPO:0000151) [single locus genotypes]
-- | --

This would make people really aware that both haoploid and diploid annotations existed (they can always then use the checkbox as a filter to remove haploids if they really do not want them. I suspect that really they need both to get a complete dataset.

**Comment by ValWood** [comment]
I know that is the opposite of what I suggested originally....

**Comment by mah11** [comment]
It's probably not helping that I got confused between search options and web page displays because my email client truncated the subject line :P

**Comment by ValWood** [comment]
I was thinking I would need my browser  with to be very narrow for that to happen ;)

**Comment by kimrutherford** [comment]
Sorry, I was confused too.  I should have read the subject.

> I think my preference would be to have this 'unselected' by default (currently not possible)

Would that mean unselected would work the same as selecting both checkboxes?

**Comment by ValWood** [comment]
> Would that mean unselected would work the same as selecting both checkboxes?

Yes. That would be a bit strange but the behaviour I wanted is that the default is both and people need to filter to remove one. This is because many phenotypes will be only haploid or only diploid (but we  have legacy data that is not annotated correctly to diploid)  so preselecting  one would seem strange.

I think we should discuss this one on a call  with JAcky and Juan to see what users expect.

**Comment by kimrutherford** [comment]
> That would be a bit strange but the behaviour I wanted is that the default is both and people need to filter to remove one.

Is there any problem with having both checkboxes selected by default?  I think that's clearer than having both unselected by default.

**Comment by ValWood** [comment]
You are right- having both selected is clearer.

**Comment by kimrutherford** [comment]
> You are right- having both selected is clearer.

OK.  Should I go ahead and do that or should we have a quick chat about it on Thursday?

**Comment by ValWood** [comment]
If @mah11  thinks this would be OK we can go ahead. I think the people like me  who don't always check the defaults until the results are not what we expected will be less surprised by including everything, and that most phenotype will be either (or) not both (and) in which case  filtering post query makes more sense to me. The division might also encourage people to tell us when we have haploid but  where is should  be diploid.

**Comment by mah11** [comment]
I don't mind - go ahead.

**Comment by kimrutherford** [comment]
OK, done.

Val, could you have a test and close the issue if you think we're done?  Thanks.

**Comment by ValWood** [comment]
Good,
