### ISSUE TITLE
"Constrain condition" in query builder phenotype search not working

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1743]
If I add a condition it makes no difference to the number of results.

For example "high glucose YES" for "abnormal cell wall (FYPO:0002946)" gives the same results as just "abnormal cell wall (FYPO:0002946)".  It checked on of the results (https://www.pombase.org/gene/SPAC27D7.04) and there no phenotypes with that condition.

@ValWood @mah11 do you ever constrain by condition?  Did you notice that it stopped working?

**Comment by mah11** [comment]
Sorry, the only time I ever even ticked the box was when I had a look to update the documentation right after the feature got added :/

I can confirm it's not making any difference for me now, on FYPO:0002061 & temperature conditions ...

**Comment by kimrutherford** [comment]
OK, thanks.  I'll get this fixes soon.

**Comment by ValWood** [comment]
I don't really use it, I can't remember when I last did...

**Comment by kimrutherford** [comment]
I think I'll temporarily disable it until I can fix it since the results are incorrect.

**Comment by kimrutherford** [comment]
> I think I'll temporarily disable it until I can fix it since the results are incorrect.

I've done that.  I'll fix it properly soon.

**Comment by kimrutherford** [comment]
I've tracked down the bug.  Unfortunately I broke things when I added support for querying diploids.  I've fixed the problem and I've now re-enabled condition constraints.  Please reopen this issue if you spot any more issues.
