### ISSUE TITLE
PomBase slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1745]
chromatin remodelling is in our slim and will shortly be obsoleted.

so we should switch our slim class to "heterochromatin assembly"

I think all the annotations will fall into 
"heterochromatin assembly"
or 
GO:0140673 co-transcriptional chromatin reassembly
or
GO:0048096  chromatin-mediated maintenance of transcription

(Note to self: Ineed to open a curation  tracker ticket for the reannotation, and a ticket to update the pombase slim at GO)

**Comment by kimrutherford** [comment]
> No problem. I've changed it in the configuration and I'll check tomorrow.

That looks OK on the main site.

**Comment by kimrutherford** [comment]
Can this be closed?  Do you need to open a curation tracker issue for it?
