### ISSUE TITLE
Separate the current and previous counts in query history?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1747]
I don't really like how we display the out of date query results.  For one thing you can't see the old and new counts at the same time.  I was wondering if we could do something like this instead?  We could hide the "Previous" column in the case where there are no counts that have changed.

![results-table-previous-col-2](https://user-images.githubusercontent.com/90474/131207313-1c6ef994-8c0d-4e77-99a2-d57813b90170.png)

**Comment by ValWood** [comment]
I would really like that! It would be very. useful for tracking odd differences that arise from non-curation (i.e. GO ontology issues)

**Comment by kimrutherford** [comment]
Good morning!

I had made the changes already so I could make the screenshot.  I've updated JaponicusDB (which is quick).  PomBase will be updated in 5-10 minutes.

Let me know any changes you'd like.

**Comment by ValWood** [comment]
this will be really nice. It must be frustrating when people  see the number has changed but they have no idea what went in or out....

**Comment by kimrutherford** [comment]
Hi Midori.

This change probably needs a mention in the docs.

I've included a help icon in the column header which should explain it to users in the meantime.

@mah11

**Comment by mah11** [comment]
OK, I'll get to it this week.

**Comment by mah11** [comment]
This is up and running, and the documentation's done, so I'll close this.
