### ISSUE TITLE
Better display of query structure

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1748]
I'm wondering about improving what you get from the "details" button/link in the query history.  Currently it shows the query as one long string in an unfriendly format.  Like:

**(normal mitotic recombination (FYPO:0000503) [single or multi-locus genotypes] NOT ((cell wall (GO:0005618) [single or multi-locus genotypes] OR gene list: [SPBC713.12 SPBC216.05 SPAC20H4.04] OR positive regulation of cell cycle G2/M phase transition (GO:1902751) [single or multi-locus genotypes]) AND (disease_associated (DOID:4) OR gene list: [SPAC3F10.03 SPBC14C8.06] OR tm_domain_count(≥12))))**

(Please excuse the nonsense query)

I'm experimenting with displaying them in a more structured way (see screenshot).  You can try this on your own queries using the slightly secret "..." menu at the end of each history line.

![query-structure-view-1](https://user-images.githubusercontent.com/90474/131430648-9eba9d97-c896-43a8-a06e-f5a9fdbb2a12.png)

![query-structure-view-menu-1](https://user-images.githubusercontent.com/90474/131431527-e2319085-bb95-4119-8b2a-e87e180f290a.png)

**Comment by ValWood** [comment]
I doon't see the 'secret '  link n live, or dev, but I. like the screenshots....

**Comment by kimrutherford** [comment]
> I don't see the 'secret ' link on live or dev, but I like the screenshots....

They're only visible when you hover over them.

**Comment by ValWood** [comment]
I still don't see them ;)

**Comment by mah11** [comment]
> I'm experimenting with displaying them in a more structured way (see screenshot).

That's very nice :)

**Comment by mah11** [comment]
>> I don't see the 'secret ' link on live or dev, but I like the screenshots....
> 
> They're only visible when you hover over them.

... and it seems to be fussy about exactly where you hover. Mouse just *outside* the box outline on the right, and at juuuuust the right height ....

**Comment by kimrutherford** [comment]
> Mouse just outside the box outline on the right, and at juuuuust the right height ....

Yep!

Just like in my screenshot.

I plan is to make the `[details]` button show the structure like this in a dialog box.  I don't think `[details]` is very helpful at the moment.

**Comment by kimrutherford** [comment]
> I plan is to make the [details] button show the structure like this in a dialog box.

Done!  I'll close this issue but let me know if you'd like any changes or if you spot any problems.

**Comment by ValWood** [comment]
Looks awesome!
