### ISSUE TITLE
reduce redundancy in gene /term list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#175]
- [x] need to see each gene only once (until you get to 'annotations)"
- [ ]  ~~Also display product name~~

![duplicates](https://cloud.githubusercontent.com/assets/7359272/23094157/850fd8c8-f5eb-11e6-85b0-0c16be553318.jpg)

**Comment by kimrutherford** [comment]
I think this is out of date since we are now showing the genes on one line.

>  Also display product name

That doesn't make sense if the genes are on one line.  Are the products still needed?

**Comment by ValWood** [comment]
> That doesn't make sense if the genes are on one line. Are the products still needed?
nah, these are accessible via the gene list, or one click away so thats fine...

**Comment by ValWood** [comment]
yep out of date, presuming only individual annotation (gene + extension) is shown once in "summary term view"

**Comment by kimrutherford** [comment]
I think this is the same issue as #184 so I'll close it.
