### ISSUE TITLE
ontology slim file location

### ISSUE THREAD

**Issue by mah11** [pombase/website#1753]
The GO and Mondo slims are in locations that are a teensy bit awkward for link management between PomBase and JaponicusDB.

For PomBase they're in
https://www.pombase.org/data/releases/latest/misc/

and for JaponicusDB they're in
https://curation.pombase.org/japonicus_nightly/latest_build/misc/

Could the slims be copied over to a more variable-interpolation-friendly directory? I suggest directly in `${base_url}/data/annotations/`.

(I guess we don't need the Mondo slim for JaponicusDB yet, but would it hurt to have it copied to the "stable" location anyway?)

**Comment by mah11** [comment]
Note to self: update links when this is done

**Comment by mah11** [comment]
I've also just noticed that both the old and current disease slims are also in https://www.pombase.org/data/documents/ ... that makes less sense to me than data/annotation, and we might want to move the old disease_ontology_slim_ids_and_names.tsv file to an "OLD" directory somewhere.

**Comment by mah11** [comment]
> We don't generate a japonicus Mondo slim at the moment ... So can we leave that one for while?

Sure.

I'll poke around and adjust documentation etc. pages to reflect your whole comment.

**Comment by kimrutherford** [comment]
> As a first step for the GO slims, I'll rename the japonicus slim files

I've fixed that fix Wednesday morning.  I'll check then.

**Comment by kimrutherford** [comment]
> As a first step for the GO slims, I'll rename the japonicus slim files

The slim files are now called `bp_goslim_japonicus_ids_and_names.tsv` etc.

**Comment by ValWood** [comment]
Done?

**Comment by ValWood** [comment]
It seems that this is done, but it isn't clear to me whether the documentation and/or links were updated?

The link from here works:
https://www.pombase.org/datasets
but I'm not sure where it is retreiving from.

The old slim is still in here:
https://www.pombase.org/data/documents/

ANd I can't  the  proposed new directory

**Comment by kimrutherford** [comment]
The japonicus files weren't in the right place.   I've fixed that now so I think this is done.
