### ISSUE TITLE
additions/changes to MF slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1757]
Add to MF slim 
molecular sequestering activity (GO:0140313) | ...
 small molecule sensor activity (GO:0140299) | ...
 cargo receptor activity (GO:0038024)
These  are new term immediately under the root node, added during MF refactoring. Numbers will increase

swap
translation regulator activity, RNA binding (GO:0008135)
for
translation regulator activity, (GO:0045182)

**Comment by ValWood** [comment]
these changes will not affect the quilt figure

**Comment by kimrutherford** [comment]
I've made those changes.  They'll be on japonicusdb.org in a few hours and will be on pombase.org on Tuesday morning.

**Comment by ValWood** [comment]
Also chromatin remodelling should be replaced by GO:0006325 chromatin organization (chromatin remodelling will be axed soon)
(this should have been a BP slim change, not a quilt change)

**Comment by kimrutherford** [comment]
> Also chromatin remodelling should be replaced by GO:0006325 chromatin organization

GO:0006325 chromatin organization is already there?

**Comment by ValWood** [comment]
sorry ! all good.

**Comment by ValWood** [comment]
I was confused becuse this fig has "rem modelling"
https://user-images.githubusercontent.com/90474/132119957-accb7307-63ec-44f6-96e6-d0bcbcb7a9fa.png
but I think we swapped last week
