### ISSUE TITLE
addition to quilt summary

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1758]
Please add 

molecular adaptor activity | GO:0060090 | 365
after 'other catalytic activity' 
and before
ienzyme regulator activity'

this WILL affect the figure. It should be a good growth term, and can refer to in legend (this will be one. of the connected terms)

**Comment by ValWood** [comment]
Also remove organelle localization from the Quilt terms, it isn't very useful here.


 (this is a permanent change to Quilt)

**Comment by ValWood** [comment]
Also chromatin remodelling should be replaced by GO:0006325    chromatin organization (chromatin remodelling will be axed soon)

**Comment by kimrutherford** [comment]
Is this a change for both pombe and japonicus?

**Comment by ValWood** [comment]
yes, we will always use the same slims/Quilt subset  I expect, unless we make it user configurable...

**Comment by kimrutherford** [comment]
> Also chromatin remodelling should be replaced by GO:0006325 chromatin organization

I can't see chromatin remodelling in the QuiLT configuration.

I've made the other changes.

**Comment by kimrutherford** [comment]
> I've made the other changes.

The change will be on japonicusdb.org by the morning.  It will take an extra day for pombase.org because I didn't make the changes in time.

**Comment by ValWood** [comment]
> I can't see chromatin remodelling in the QuiLT configuration.


Actually it is there, but it is BP. I forgot I said MF  changes!
