### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1759]
This is in Canto, but I don't find it when I search PomBase PMID:34464389?

**Comment by kimrutherford** [comment]
It looks like the session was only created today?  It will probably be there in the morning.

**Comment by kimrutherford** [comment]
It's there now: https://www.pombase.org/reference/PMID:34464389

**Comment by ValWood** [comment]
right, it must have just been imported. I was only checking because I thought it was od though it was one of those papers indexed in duplicate- it wasn't.
