### ISSUE TITLE
Missing link to InterPro on cdc12 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#176]
In molecular function:

    actin binding
       binds InterPro:IPR010472

**Comment by ValWood** [comment]
Yep.
Refinement to previous instructions.

We should only do the conversion of protein binding terms to annotation extensions malarky IF the evidence code is IPI. Forgot to mention that ;).

**Comment by kimrutherford** [comment]
> Refinement to previous instructions.

OK, I'll restrict it to IPI but I'll also fix the linking which should be working.

**Comment by kimrutherford** [comment]
> OK, I'll restrict it to IPI but I'll also fix the linking which should be working.

Both things are fixed now.
