### ISSUE TITLE
Display of synonyms in pop ups and on genotype pages  (was Mis19, standardize deletion allele names)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1762]
17) Mis19, standardize. Deletion allele names

eic1Δ,   kis1Δ,   mis19Δ

**Comment by kimrutherford** [comment]
> Do we display allele synonyms yet?

Not yet.

> I think we should show allele synonyms here too

Would an extra column ("synonyms") be too much?  Another option is to add them after the name:

```
   mis19Δ (synonyms: mis19-zzz, mis19-yyy)
```

**Comment by ValWood** [comment]
This will be really helpful if  the genotype in the paper doesn't match up - I sometrimes run into this.
I like your solution.

**Comment by mah11** [comment]
> Would an extra column ("synonyms") be too much? Another option is to add them after the name:

I have a slight preference for a separate column, but it's not a big deal either way for me.

**Comment by ValWood** [comment]
OK separate column would be good too.

**Comment by kimrutherford** [comment]
That's done now.

**Comment by ValWood** [comment]
great! Little niggle-  displays as eic1delta,   kis1delta not eic1Δ,   kis1Δ

**Comment by kimrutherford** [comment]
> displays as eic1delta, kis1delta not eic1Δ, kis1Δ

Good point.  That's fixed now if you reload or maybe shift-reload.
