### ISSUE TITLE
move About menu to config

### ISSUE THREAD

**Issue by mah11** [pombase/website#1768]
Can we put the About navbar stuff into the config files, like you [did for Genome Status](https://github.com/pombase/website/issues/1714#issuecomment-920506209)?

Right now the "Citing JaponicusDB" menu item tries to link to www.japonicusdb.org/about/citing-pombase, which of course isn't a thing. The same happens for "publications by ...". Both are OK in the left-hand menu on any About page.

**Comment by kimrutherford** [comment]
This is done now, but not in time for last night's load.  I'll check it's all OK tomorrow morning.

> Right now the "Citing JaponicusDB" menu item tries to link to www.japonicusdb.org/about/citing-pombase,

In the japonicus config file, I've changed that to point to citing-japonicusdb.

**Comment by kimrutherford** [comment]
All done.  The About menu config is [here](https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L203) (for PomBase).
