### ISSUE TITLE
copy FASTA sequences for convenient linking

### ISSUE THREAD

**Issue by mah11** [pombase/website#1769]
Right now, there are chromosome sequences in FASTA format for both S. pombe and S. japonicus, but they're not being copied over to locations other than the "nightly"/"latest" release places. It would help if they were -- it's almost certainly the best way to address helpdesk ticket 9214.

Could the pombe chromosome files in www.pombase.org/data/releases/latest/fasta/chromosomes/ be copied to
pombe-embl/ftp_site/pombe/genome_sequence_and_features/genome_sequence/

and the japonicus files in curation.pombase.org/japonicus_nightly/latest_build/fasta/chromosomes/ copied to 
www.japonicusdb.org/data/genome_sequence_and_features/genome_sequence/ (a new directory)?

I could change the link to point to the latest release directory, but that would be a little more fiddly because the paths are different for PomBase and JaponicusDB. If the file copying gets done I can just plug in `${base_url}/data/`yada in a few places. Let me know if that's a better solution anyway.

For ticket 9224, I manually copied over the mitochondrial chr file, so it'll be OK for a while as none of the others have changed. But if Val really does get updates through ENA submission, the copy-over will be good future-proofing.

**Comment by kimrutherford** [comment]
> I'll check that it worked on Wednesday morning.

It looks OK.  Let me know if it needs tweaking.

**Comment by mah11** [comment]
I'm happy with it -- I updated a page to point to it already :)
