### ISSUE TITLE
target of section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#177]
we should discuss today  how we want to order this section.

Anything else?

**Comment by ValWood** [comment]
- [x] remove sys ID
- [ ] 2. Make ontology terms "GO" /"FYPO"
- [ ]  separate (group) by ontology
- [ ]  within ontology list alphabetically by gene or genotype
- [ ]  link mutants  to genotypes
- [ ] call column genes/geneotypes

**Comment by kimrutherford** [comment]
I've changed the ontology labels to "GO" and "FYPO" and the table is now sorted by ontology label and gene name.

I haven't added the genotypes yet.

**Comment by ValWood** [comment]
great!....

- [ ] can we also  order
GO
FYPO single
FYPO multi allele
(GO provides the most functional detail)

**Comment by kimrutherford** [comment]
So would you like it to say

"FYPO single"
"FYPO multi allele"

instead of "FYPO"?

**Comment by ValWood** [comment]
I don't think that matters, will be obvious when we should genotypes for multi's.

**Comment by kimrutherford** [comment]
Still need to order by genotype in the FYPO section.

**Comment by kimrutherford** [comment]
As discussed, I've removed the product column from the target-of section.  Now the product is show just after the gene name.  Let me know if you can think of a better way to format it.

**Comment by kimrutherford** [comment]
> Still need to order by genotype in the FYPO section.

That's done.  Please create new issues for bugs or changes.

**Comment by ValWood** [comment]
is better!
