### ISSUE TITLE
External links to Intact

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1772]
InterPro has a new website
Qe can add protein specific links using this URL format:

https://www.ebi.ac.uk/intact/search?query=Q9USV1&interactionTypesFilter=direct%20interaction,physical%20association

**Comment by kimrutherford** [comment]
I've added that.  It will be visible in the morning.

The line in the external refs table looks like this:

```
Interactions       IntAct          Q9USV1      IntAct Interaction Network
```

Let me know if you'd like any changes.

**Comment by kimrutherford** [comment]
I've added those links but for some genes it just says "No results found", like for Wee1: https://www.ebi.ac.uk/intact/search?query=P07527&interactionTypesFilter=direct%20interaction,physical%20association

But this link does work for wee1: https://www.ebi.ac.uk/intact/search?query=P07527

Should we switch to that?

**Comment by kimrutherford** [comment]
Done!
