### ISSUE TITLE
examples for SO protein feature search

### ISSUE THREAD

**Issue by mah11** [pombase/website#1773]
to go under the search box in the Protein motifs tab (protein domains, features and motifs):

"Examples: short motifs such as NLS or KEN box, signal sequence, cleaved region, helix"

(tangent from #1720)

**Comment by kimrutherford** [comment]
Thanks Midori.

I've added the code and config in my local copy.  It will be released when I commit the other query builder changes.

It's configured like this in the main website config file:
```json
           {
             "id": "SO_protein",
             "displayName": "protein motifs",
             "nodeType": "ontology",
             "ontologyName": "SO-protein",
             "topDescription": [
               {
                 "text": "Retrieve protein-coding genes based on features annotated using the protein sequence feature branch of the Sequence Ontology (SO)"
               }
             ],
             "extraDescription": "Examples: short motifs such as NLS or KEN box, signal sequence, cleaved region, helix"
           }
```
and looks like:

![query-builder-improved-motif-mess-1](https://user-images.githubusercontent.com/90474/135565679-d0ddb83c-9850-4758-87c6-7bb458bffadb.png)

**Comment by mah11** [comment]
Looks good; thanks :)
