### ISSUE TITLE
ID searching broken (PMID, FYPO, possibly others?)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1775]
At least I could not locate PMID:27984744
which is curated
https://www.pombase.org/reference/PMID:27984744

**Comment by ValWood** [comment]
Seems to be a general searching issue with IDs.
FYPO IDs do not work currently in the simple search or the advanced search.

**Comment by kimrutherford** [comment]
Could you give some examples?

I just tried FYPO:0006145 in the search box and advanced search with no problem.  And PMID:27984744 worked in the search box.

The search box still has the problem that you need to type/paste the ID and then press return.  It says "No matches" until you press return.

**Comment by ValWood** [comment]
doh!

**Comment by mah11** [comment]
I added a note to the documentation.

**Comment by kimrutherford** [comment]
Thanks for fixing the docs.

I think the search box needs improving so I made an issue about it: #1777
