### ISSUE TITLE
display of background on phenotype and allele full view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1776]
I noticed whn discussiing H+/H- backgrounds with Sophie Martin that we show

<html><head></head><body>
FYPO:0000569 | abolished                     shmoo formation | mam2Δ             background: h- | cell growth assay                 evidence
-- | -- | -- | --
</body></html>

in the 'full view' on the gene pages, but not on the allele or phenotype pages.
Maybe we should have this info in all 3 places?

**Comment by ValWood** [comment]
Good, that's what I meant. Genotype pages, and phenotypes pages, detailed view.
 I did not see on the genotype page detailed view, but it's there.
Also publication pages it is missing.
I think we are in agreement about what is needed (at least as a first pass, always show background in detailed view)

**Comment by kimrutherford** [comment]
> I did not see on the genotype page detailed view, but it's there.

Sorry, I missed that bit of your comment.

> Also publication pages it is missing.

That's fixed now too and the change will be visible in the morning.
