### ISSUE TITLE
physical interaction section needs "directional qualifier"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#178]
see first column on pombase 1.
forms complex with
affinity captured by
affinity captures

@mah11  where be these?

**Comment by ValWood** [comment]
likely to be a duplicate ticket

**Comment by mah11** [comment]
https://curation.pombase.org/pombase-trac/wiki/BioGridBaitHitNotationMapping

**Comment by ValWood** [comment]
I only put this to "next " because it looks quick....

**Comment by kimrutherford** [comment]
What should the column headings be on the publication pages?

See also #216.

**Comment by kimrutherford** [comment]
> https://curation.pombase.org/pombase-trac/wiki/BioGridBaitHitNotationMapping

Thanks Midori.

What doesn't the "(peptide)" mean here?:

    Protein-peptide	N	binds to peptide	(peptide) binds to protein

**Comment by kimrutherford** [comment]
I think this is done now.  The interaction sections on the gene pages now seem to match what is on the old site.  Could you have a look and see if it's OK?

> What should the column headings be on the publication pages?

And let me know what you think of the interaction sections on the publication pages.

**Comment by kimrutherford** [comment]
Sorry I meant to say: you're likely to need to shift-reload.

The configuration for this is here:
  https://github.com/pombase/website/blob/master/frontend/src/app/config.ts

Search for: interactionDirectionalLabels

**Comment by kimrutherford** [comment]
> It all looks good to me. I don't have a strong preference about the column headings.

OK, thanks.

> I'm happy to edit the config if V&A do want the wordy versions.

Thanks for the explanation.  If you edit the config in future, let me know and I'll update the live pombase2 with the changes.

**Comment by ValWood** [comment]
Yeah, maybe the wordier will help.

**Comment by kimrutherford** [comment]
Change "Interactor gene/product" to "Interacting gene/product".
