### ISSUE TITLE
https://www.pombase.org/status/gene-coordinate-changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1781]
This table is quite unwieldy as a web page and contents are often obscured by the menu as you scroll left and right.

I think it would be better if this page had some minimal information about gene structure alterations and a link to a config file or view only google sheet.

Column headings would be
systematic ID
standard name
old coordinates
new coordinates
description of comment
source
date

I'm mentioning this now because I have a large bunch of new ones, I'd like to change over format before these are added.

At present
old coordinates
new coordinates
description of comment
are munged into a single field.
We would not always have old and new coordinates, but this is fine. Somebody can dig these out later if necessary
(actually, since these are all changes since the last submission, they will be the coordinates in the current EMBL file, so easy to find)

**Comment by ValWood** [comment]
I'd like to implement these gene structure updates in the main contig files once I finish chromosome I 5'UTRs
https://github.com/pombase/curation/issues/3024

@mah11  could you see if you can have a stab at arranging a tab delimited file for the existing ones next week ?

Although, if we have a format I can  make sure I compile them correctly.

**Comment by ValWood** [comment]
Brilliant. I can check the ones from the curation ticket.

In fact, thankyou for adding these. I still need to actually implement the changes, but adding to the spreadsheet already will save a task. I haven't done the gene structure changes in the main contigs  yet (I'm working on the UTRS in a copy of the file so that I can import them all in one go). 

I will be able to import chromosome 1 new UTRs shortly and adjust the gene structures in the contigs to match them.
I'm up to 4.97Mb....it is soooo boring...

**Comment by ValWood** [comment]
I think we can go ahead and switch to display these files.
I'm not so worried about losing a few notes, most are  jut gloss if the change is recorded.

**Comment by kimrutherford** [comment]
The dev PomBase now has these changes - the TSV files are turned into tables when the site is released

Before:
 - https://www.pombase.org/status/new-and-removed-genes
 - https://www.pombase.org/status/gene-coordinate-changes

After:
 - http://dev.pombase.kmr.nz/status/new-and-removed-genes
 - http://dev.pombase.kmr.nz/status/gene-coordinate-changes

Please let me know if you see any problems.  The change will be in the main site on Tuesday morning.

**Comment by ValWood** [comment]
The new gene coordinates changes table is very short. 

existing
https://www.pombase.org/status/gene-coordinate-changes

**Comment by mah11** [comment]
The table at http://dev.pombase.kmr.nz/status/gene-coordinate-changes is truncated. The first missing entry is also the first of several lines in which the Comments column contains a frameshift description that includes an arrow (e.g. `Frameshifted by Chr_II:825012!G→A`).

Coincidence? I suspect not ....

**Comment by kimrutherford** [comment]
Thanks.  Fixed now and I've updated the main site.
