### ISSUE TITLE
some protein binding should be grouped (e.g. hht1)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1782]
<img width="1095" alt="Screenshot 2021-10-21 at 12 14 13" src="https://user-images.githubusercontent.com/7359272/138327850-25022a2a-7dc4-4661-82f5-a3f1fad87528.png">

This should display as:

active form hht1/InitMet-/Me:(K9)  binds clr4,swi6
binds bir1,spt16,chp1,chp2

**Comment by kimrutherford** [comment]
Which gene is that?
