### ISSUE TITLE
Improve the genome location query type

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1784]
The range searching was improved in #1720, but I forgot about the genome location queries.

**Comment by kimrutherford** [comment]
I meant to show you this change before deploying, but I released it by accident.  Sorry.

Please let me know if you'd like any wording changes, any fixes or if you spot any bugs.

![query-node-genome-location-1](https://user-images.githubusercontent.com/90474/140910254-9e7dac0f-229f-4571-93b7-e579f5378602.png)

**Comment by mah11** [comment]
Seems to work nicely for me; I edited the documentation for it

**Comment by ValWood** [comment]
Looks good

**Comment by kimrutherford** [comment]
> Seems to work nicely for me; I edited the documentation for it

Thanks!  I'll close this then.
