### ISSUE TITLE
Bring "phase filtering" filter forwards onto the summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1785]
Normally the annotation filters are present at the level which thy are applicable.
I.e most phenotype term and haploid/diploid are available on the summary view.

For GO,  all filters are hidden in the summary view. We should move the 'phase' filter forwards to the summary view, because phases are visible at this point.

**Comment by kimrutherford** [comment]
This will be just a config change once this issue is fixed:
  - #1667.

**Comment by kimrutherford** [comment]
Now that #1667 is fixed I've configured this for GO and for the qualitative gene expression annotation.

**Comment by ValWood** [comment]
Nice, that is really useful on cdc2 page.
I will suggest some tweaking of the filter labels in the filter option....
