### ISSUE TITLE
fasta option for sequence searches

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1787]
from https://github.com/pombase/website/issues/1780

You can link to our FASTA page using this link
https://www.ebi.ac.uk/Tools/services/web/toolform.ebi?tool=fasta&context=
protein&sequence=<your sequence (URL encoded)>

Use the sequence GET parameter to pass your URL encoded sequence to the
service which makes it auto-populate the sequence on the page.

**Comment by kimrutherford** [comment]
Thanks for contact the EBI.

This is implemented now.
