### ISSUE TITLE
Show properties for all transcripts in the "Protein features" section

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1790]
We currently just show transcript 1 in the "Protein properties" table.

(Moved from #1613)

**Comment by kimrutherford** [comment]
If there are multiple transcripts there are now extra columns in the table.  (From tomorrow morning)

It only show different values for prp10 / SPAC27F1.09c but at least it's consistent.

![prot-props-table-1](https://user-images.githubusercontent.com/90474/139769741-16aa2d3d-41d9-4cfd-b862-aee3d54fb039.png)

**Comment by ValWood** [comment]
The wtfs should show different values too?

**Comment by kimrutherford** [comment]
> The wtfs should show different values too?

I forgot about them.  They have different values too.
