### ISSUE TITLE
Arrange search icons vertically

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1793]
I wonder if these icons will be better arranged vertically. I found  when checking an allele residue for this protein that the residue indicator at the top was not visible when I selected the amino acid of interest.

<img width="1266" alt="Screenshot 2021-10-31 at 16 57 17" src="https://user-images.githubusercontent.com/7359272/139686117-5a2ca788-5185-433b-8903-6a69508b533f.png">

**Comment by ValWood** [comment]
This is Tor2.

also the search icons were only visible for the sequence type that they were applicable to before (protein or nucleotide).

If this returns that might do the job.

**Comment by kimrutherford** [comment]
> also the search icons were only visible for the sequence type that they were applicable to before (protein or nucleotide).

The blast buttons work for protein or nucleotide.  They change from blastp to blastn depending.  I'll arrange for the two new buttons to be hidden when you're viewing the nucleotide sequence.

**Comment by kimrutherford** [comment]
> The blast buttons work for protein or nucleotide. They change from blastp to blastn depending. 

Sorry, you're right.  I was imaging this.

**Comment by kimrutherford** [comment]
> search icons were only visible for the sequence type that they were applicable to before (protein or nucleotide).

I've fixed that.

**Comment by kimrutherford** [comment]
Val, is the layout OK for this now?

**Comment by ValWood** [comment]
It must be because I have been using with no issues :)
