### ISSUE TITLE
reduced number of annotations to cytoplasmic translation 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1796]
possibly related to 
https://github.com/pombase/website/issues/1795

cytoplasmic translation has only  48 genes assigned.

(note this could also be caused by a GO problem!, I will do a little digging)

**Comment by ValWood** [comment]
For example, all tRNAs are excluded:

One e.g.
https://www.pombase.org/gene/SPCTRNAALA.12

**Comment by kimrutherford** [comment]
> cytoplasmic translation has only 48 genes assigned.

I see 468 here: https://www.pombase.org/term/GO:0002181

Where do you see 48?

**Comment by ValWood** [comment]
Phew! ignore me, I was looking at initiation!
