### ISSUE TITLE
Missing "with" on wtf13 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1798]
https://www.pombase.org/gene/SPCC162.04c

"ISS with ___"

![missing-with-wtf13-1](https://user-images.githubusercontent.com/90474/140723109-e8a00c8c-28fe-410f-86b3-d69156014946.png)

**Comment by mah11** [comment]
Ah, a wtf. Let me know if the annotations need any adjustments -- I noticed that the legacy GAF doesn't have the transcript isoform IDs in column 17 (yet?), but the `with` entries are there.

The same sort of thing is also happening on the [wtf19](https://www.pombase.org/gene/SPCC1906.03) page, which doesn't have an IDA annotation suppressing display of any ISSs.

**Comment by kimrutherford** [comment]
> The same sort of thing is also happening on the wtf19 page

Thanks.  I've fixed the immediate problem so the wtf19 page looks better now.

![missing-with-wtf19-1](https://user-images.githubusercontent.com/90474/140737254-6d62a4d0-035a-4a52-9fa8-8c18a897bf24.png)

**Comment by kimrutherford** [comment]
I'll close this.  We can open separate issues for other problems.
