### ISSUE TITLE
Missing transcript IDs in cytoplasm section of PMID:32032353 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1799]
https://www.pombase.org/reference/PMID:32032353

![PMID32032353-missing-transcript-ids-1](https://user-images.githubusercontent.com/90474/140739625-7ae1dd3c-5c97-4a97-b7dd-758395bc081e.png)

**Comment by kimrutherford** [comment]
The missing transcript IDs are for genes that have only one transcript.  That makes sense because that's how I wrote the code.  :-)

Do any of these options appeal?:
   - leave the fields blank (maybe that looks like there is missing data?)
   - use: "All"
   - "Single transcript"
   - transcript ID "SPCC1183.10.1"
   - "SPCC1183.10.1 (single transcript)"

**Comment by ValWood** [comment]
Is something a bit wrong here?
<img width="1265" alt="Screenshot 2021-11-10 at 08 10 16" src="https://user-images.githubusercontent.com/7359272/141074835-c452a99a-06f5-4d77-893e-6f1d915f47cd.png">

I thought that only one isoform localized to the epiplasm?
Are we inferring this one?
SPCC162.04c.1 | ISS with wtf4
-- | --


In answer to the question, I think my preference would be  that if the annotation applies to all isoforms we do not need to add isoforms, but we can if we think it makes things less confusing (which it might for wtfs when the isoforms are so radically different).
So, I would leave it blank unless if we felt there was no  need to  specify a particular isoform.

**Comment by kimrutherford** [comment]
> Is something a bit wrong here?
>
> I thought that only one isoform localized to the epiplasm?

I think it's gone weird because there are some non-transcript specific annotations in the legacy GAF file:

```
PomBase SPCC1620.02     wtf23   GO:0072324      PMID:32032353   ISS     PomBase:SPCC548.03c     C       wtf meiotic drive poison Wtf23          protein taxon:4896      20200914        PomBase
PomBase SPCC1906.03     wtf19   GO:0072324      PMID:32032353   ISS     PomBase:SPCC548.03c     C       wtf meiotic drive poison Wtf19          protein taxon:4896      20200914        PomBase
PomBase SPCC162.04c     wtf13   GO:0072324      PMID:32032353   ISS     PomBase:SPCC548.03c     C       wtf meiotic drive poison Wtf13          protein taxon:4896      20200914        PomBase
```

Sorry about that.  I thought I'd sorted that out but clearly not.  I'll try again tomorrow.

**Comment by ValWood** [comment]
I guess they just need an isoform adding.  The need to be done in the legacy GAF because they are ISS.

**Comment by mah11** [comment]
also noted [here](https://github.com/pombase/website/issues/1798#issuecomment-963015148)

**Comment by kimrutherford** [comment]
> Sorry about that. I thought I'd sorted that out but clearly not. I'll try again tomorrow.

I've removed the annotation from `legacy_go_annotations_from_contigs.txt` for multi-transcript genes that I coped there from the contig files by mistake.  Hopefully that will fix some of the oddities by the morning.

**Comment by kimrutherford** [comment]
> Hopefully that will fix some of the oddities by the morning.

The nightly load failed because it was unable to download from BioGRID.  I'll check the transcript fixes on Friday morning.

**Comment by kimrutherford** [comment]
> The nightly load failed because it was unable to download from BioGRID. I'll check the transcript fixes on Friday morning.

It failed again.  This time because the GOA GAF couldn't be downloaded.  I'll keep an eye on the next load(s).

**Comment by kimrutherford** [comment]
The load worked and the GO sections for multi-transcript genes are looking much better.
