### ISSUE TITLE
Question, have there been any behind the scenes changes for NOT annotations?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#18]
I spotted this:
![ssl3](https://cloud.githubusercontent.com/assets/7359272/16707109/535a67b0-45bc-11e6-8a11-aa3a9e13757f.jpg)

I haven't previously noticed any  problems with NOT annotations, so I wonder if the issue is specific for NOT annotations curated in Canto?
![not](https://cloud.githubusercontent.com/assets/7359272/16707121/8ed1121c-45bc-11e6-90ca-5251ff09d944.jpg)
 (this one is)

**Comment by ValWood** [comment]
I'm not sure the data the curations were made so I don't know if it is something which has been fixed post release...

**Comment by ValWood** [comment]
grep NOT pombase-build-2016-06-25-v1\ \(3\).gaf  |grep ssl3

gives nothing, but other NOTs are there so we should explore the Canto  problem idea first....

**Comment by ValWood** [comment]
I labelled as a bug but it isn't super urgent right now....ideally before the build to create the next update....

**Comment by ValWood** [comment]
The gene is ssl3
and there is no NOT in PomBase 2 so I will keep this open for now:

http://pombase2.aska.gen.nz/gene/SPAC1687.18c

**Comment by kimrutherford** [comment]
Looks like a loading bug as there is no NOT for that annotation in Chado.

**Comment by kimrutherford** [comment]
The annotation seems to be there now:
  http://pombase2.aska.gen.nz/gene/SPAC1687.18c

And it's in the GAF file.

I don't know why it disappeared and then came back.

**Comment by ValWood** [comment]
The screenshot above is the live site. I see now its there its just not rendering
(PBHQ:002)
