### ISSUE TITLE
modification section, remove extensions from summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#180]
- [ ] Show residues in summary view by default?
- [ ] Any other changes? we will continue to think....maybe clustering on amino acids. maybe arranging by extensions

**Comment by ValWood** [comment]
maybe we will tie this in with protein feature viewer work....

**Comment by kimrutherford** [comment]
>  Show residues in summary view by default?

How should that interact with the extensions?  Should the residues be grouped with the extensions somehow?  For example for cdc11 where should residues be displayed in this section?:

    Term name
    O-phospho-L-serine
       present during mitotic M phase                                                                                                                                        
       removed by clp1                                                                                                                                                       

(Some of the residues are for annotations without extensions - those would need to be handled separately)

**Comment by ValWood** [comment]
Added "discuss" label because too tired to think ;)

**Comment by ValWood** [comment]
OK, we decided in the short/medium  term, rather than try to overload the summary view we would just show "types of modification here"


We can change this later a) based on user feedback, and b)  we will have a feature map at some point, that we would  encourage people to use to see this detail.

So, the only action is to remove the extensions from the summary view (the extensions they apply to specific modifications, and as we don't show these they can't be interpreted here).

**Comment by kimrutherford** [comment]
I've removed the extensions.
