### ISSUE TITLE
Add configurable text after publication page  linkouts to additional datasets

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1802]
From Tiffany Mak:

> Thanks for looking into this, and it looks great! Perhaps for the texts, we could do something like this:
>
> Link to interactive web-app
> (for visualising time-dependent changes from the respective phosphorylation studies)

The configuration setting is `reference_page_extra_links`.

PMID:34296454

**Comment by kimrutherford** [comment]
How's this:

![ref-page-extra-link-1](https://user-images.githubusercontent.com/90474/145529591-8e06166b-c518-4de5-a0a5-74e69e5ea4bd.png)

**Comment by ValWood** [comment]
This should provide a generic way to link to external datasets, software, repositories.

**Comment by ValWood** [comment]
Also add for this (and others)
https://github.com/pombase/website/issues/629#issuecomment-1003165721

**Comment by kimrutherford** [comment]
> This should provide a generic way to link to external datasets, software, repositories.

It's in the configuration file.  Is that what you mean?
