### ISSUE TITLE
extend the list of phase filters

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1804]
At present this is what we have
<img width="218" alt="Screenshot 2021-11-11 at 07 33 04" src="https://user-images.githubusercontent.com/7359272/141802864-08c436bf-fe2a-4c85-ad4b-e6739e45afd2.png">

I would prefer if we can specify 

mitotic interphase and meiotic interphase instead of  'interphase' 
mitotic G1 phase and meiotic G1 phase instead of  G1 phase
mitotic S phase and premeiotic S phase instead of   S phase
meiotic M phase  mitotic M phase instead of   S phase
and the same for prophase, metaphase, anaphase, telophase.

I'm hoping we always provide the specificity, but if not this needs to be fixed (It should always be possible to specify)

I guess the first question is have we ever used the none mitotic or meiotic terms in extensions?

**Comment by ValWood** [comment]
I had a quick reccy and I don't think we use the parents at all in GO annotation. It is possible that we have used these in gene expression though (which use the same filters) so we would need to check both.

so the question is do we have any during
interphase 
G1 phase 
S phase
M phase
prophase
metaphase
anaphase
telophase.

**Comment by kimrutherford** [comment]
> I would prefer if we can specify

The menu might end up a bit long.  Is that OK?

> premeiotic S phase

I can't find that term.  Should it be "meiotic S phase"?

> so the question is do we have any "during" extensions using:
> interphase GO:0051325
> G1 phase GO:0051318
> S phase GO:0051320
> M phase GO:0000279
> prophase GO:0051324
> metaphase GO:0051323
> anaphase GO:0051322
> telophase GO:0051326

I can't see any annotation that have any during extensions using those terms.

**Comment by ValWood** [comment]
I think it is OK that the menu is a bit long. It won't get any longer.... It might be useful to put the mitotic terms to the top as they are used the most (for most use cases most terms will be greyed out)

**Comment by kimrutherford** [comment]
I get this list:
  - meiotic G1 phase
  - meiotic M phase
  - meiotic S phase
  - meiotic anaphase
  - meiotic interphase
  - meiotic metaphase
  - meiotic prophase
  - meiotic telophase
  - mitotic G1 phase
  - mitotic M phase
  - mitotic S phase
  - mitotic anaphase
  - mitotic interphase
  - mitotic metaphase
  - mitotic prophase
  - mitotic telophase


but I can't find these terms in GO:
  - meiotic metaphase
  - meiotic anaphase
  - meiotic telophase
  - meiotic prophase

GO has: "meiotic metaphase I", "meiotic metaphase II" etc.

Also: what order should they be in?  Currently it's alphabetical but maybe it should be something more biologically sensible?

**Comment by ValWood** [comment]
yes sorry 
GO:0007132    meiotic metaphase I
GO:0007137    meiotic metaphase II
GO:0007133    meiotic anaphase I
GO:0007138    meiotic anaphase II
GO:0007134    meiotic telophase I
GO:0007139    meiotic telophase II
GO:0007128    meiotic prophase I
GO:0007136    meiotic prophase II

**Comment by ValWood** [comment]
Also add 
mitotic G2 phase GO:0000085    

the order should be:
mitotic interphase
mitotic G1 phase
mitotic S phase
mitotic G2 phase
mitotic M phase
mitotic prophase
mitotic metaphase
mitotic anaphase
mitotic telophase

~meiotic G1 phase~ https://github.com/geneontology/go-ontology/issues/22451
meiotic S phase
meiotic M phase
meiotic interphase
meiotic prophase I
meiotic metaphase I
meiotic anaphase I
meiotic telophase I
meiotic prophase II
meiotic metaphase II
meiotic anaphase II
meiotic telophase II

**Comment by ValWood** [comment]
I think this list and this order is OK.
if it looks too long in the dropdown it would be useful to get a count of how many times each extension is used. That would allow me to decide if we should use some superclasses instead for the meiosis phases.

**Comment by kimrutherford** [comment]
> the order should be:
> mitotic interphase
> mitotic G1 phase
> mitotic S phase
> mitotic G2 phase

Is "mitotic interphase" needed?  It's a part_of parent of the next three in the list by the looks of it.

Same with meiotic interphase.

**Comment by ValWood** [comment]
In kept the interphase and M phase grouping terms  in addition to the specific ones.

I suspect mitotic interphase and mitotic M phase will be the most popular options, but on some pages, like cdc2 you really need the more specific ones.

**Comment by kimrutherford** [comment]
OK, thanks.  I've change the terms in the filter in time for the current load.

The load is running a bit late because I needed to restart it.  GitHub had an outage at an awkward moment during the load but it's back in action now.

It will be finished at 11am-ish.

**Comment by kimrutherford** [comment]
> The load is running a bit late because I needed to restart it. 

And then it failed because I forgot to commit all the PECO to FYECO SVN changes.  I'll check on Monday morning.

**Comment by kimrutherford** [comment]
I think is (mostly) worked: http://dev.pombase.kmr.nz/term/FYECO:0000268

There 94 fewer annotations then the previous successful load so I'm going to investigate that before updating the main site.

**Comment by kimrutherford** [comment]
The filters are updated on the main site.  Could you have a look are see if it looks OK?

I update GO and the gene expression section filters.  Does that make sense?

**Comment by ValWood** [comment]
> I updated GO and the gene expression section filters. Does that make sense?

That makes sense.
The menu length is fine too.

It seems to be working for MF and BP but not CC (I tried on the cdc2 page)

**Comment by kimrutherford** [comment]
> It seems to be working for MF and BP but not CC

Whoops!  The filtering was tripping over the "at origin_of_replication" extension on one of the CC annotations.  I've fixed it so that correctly ignores extensions that aren't "during" extensions.

It should be working in the morning.

**Comment by ValWood** [comment]
Oh one other thing that I ommitted to mention. This filter should be ontology aware. So a filter on mitotic M-phase should retrieve 
mitotic M-phase,  mitotic metaphase, mitotic anaphase, etc

and a search on mitotic interphase should retrieve mitotic G1 phase/mitotic G2 phase/mitotic Sphase.

This is quite important because  a lot of changes are really about the switch between interphase and M-phase, but are observed at the sub-phases. 
I think this could be really useful.

**Comment by kimrutherford** [comment]
> This filter should be ontology aware.

It should be doing that already.  If it's not can you give me an example?

**Comment by ValWood** [comment]
It does seem to be working. I don't know what I was doing wrong.

**Comment by ValWood** [comment]
Reopening temporarily. Kim could you add a news item (edited if necessary)? I will announce to list (or you can!)

News
We have migrated the Gene Ontology annotation filter for _'during’_ a specific cell cycle phase from the   **“Summary”**  view to the **“Details”** view to make it more visible. We have also added additional phases to cover all annotation, and added some useful grouping terms. This filter is  ‘ontology aware’ (so a search on interphase will also display G1/S/G2 phase annotation). This filter is very useful on pages like cdc2 that display increasing volume of phase-specific curation.
The revised phase filter options are also available in/on? the gene expression section.

**Comment by kimrutherford** [comment]
I've added a news item about this.  I haven't sent a message to the mailing list.

**Comment by ValWood** [comment]
Announce p-list
