### ISSUE TITLE
Ortholog section weirdness for RNA genes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1805]
This gene page has an ortholog section but "Orthologs" doesn't appear in the left hand menu:
https://www.pombase.org/gene/SPNCRNA.128

This one has a truncated ortholog section: https://www.pombase.org/gene/SPNCRNA.214

![missing-ortholog-section-1](https://user-images.githubusercontent.com/90474/142137096-d57f6108-8737-428f-aba8-06bb9a71f888.png)

**Comment by kimrutherford** [comment]
Another example: https://www.pombase.org/gene/SPNCRNA.82

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPNCRNA.214
now has its ortholog, but still. needs to appear in the menu bar

**Comment by kimrutherford** [comment]
I've fixed this for the morning.  The nightly update is running late so "morning" means 10am or so.
