### ISSUE TITLE
Project funding is out of date

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1806]
Project funding
PomBase is funded by the Wellcome Trust [104967/Z/14/Z].

should be 218236/Z/19/Z

**Comment by mah11** [comment]
Do you want to do this as a walk-through of how to edit the static pages?

**Comment by ValWood** [comment]
Could do but I think @kimrutherford  is going to handle this in the short term.

**Comment by ValWood** [comment]
Yeah go ahead. I'll concentrate on the ontology stuff.
