### ISSUE TITLE
small tweak to simple search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1807]
Should exact match come first?

I noticed here that it doesn't

<img width="335" alt="Screenshot 2021-11-17 at 12 38 13" src="https://user-images.githubusercontent.com/7359272/142237139-68094feb-6c95-4513-aca0-17086a3a97f3.png">

**Comment by kimrutherford** [comment]
> Should exact match come first?

Definitely!  That's a bit of an oversight.  I've fixed it for the morning.
