### ISSUE TITLE
make allele  names and synonyms searchable

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1809]
The simple search should allow allele name search and suggest the genotype page (and eventually also  allele page).

Without this feature is it difficult to find some historical allele names.
For example cdr1-K41A is also called nim1-K41A in older publications.

**Comment by kimrutherford** [comment]
Would #1255 help if the page included the synonyms?  I'm working on a prototype of that.

**Comment by ValWood** [comment]
Yes but the genotype page already includes the synonyms 
https://www.pombase.org/genotype/cdr1-K41A-K41A-amino_acid_mutation-expression-not_assayed

it's just that currently, if you came to Pombase and all you have is
nim1-K41A you might be a bit stuck...
(or any allele really, it would be useful if an allele search returned the gene page(s) that mention it, the genotype page and, eventually the allele page)

at least if you were sensible would probably search with "nim1" which would get you to the gene page ( nim1 is a synonym of cdr1). In this example, you would probably be OK because  cdr1-K41A is probably obviously nim1-K41A
but in other situations, where the synonym is not an allele description then it becomes really difficult to find the allele of interest from the synonym.

This isn't super urgent but I thought I would mention it because of  in-progress allele page work..

**Comment by kimrutherford** [comment]
> The simple search should allow allele name search and suggest the genotype page

We'll need to have a think about this.  The suggestions list is already a bit too long.  Maybe we could suggest fewer genes, references and terms.

**Comment by ValWood** [comment]
We can chat about this, is maybe moving into the territory of this ticket?
https://github.com/pombase/website/issues/929

It's tricky one, because if you are searching on a gene name you usually want  a gene, a title, author or PMID a paper, etc.  Only very occasionally if I search on a gene am I looking for a specific publication. Maybe we can somehow improve the results by 'guessing' the context?

Alleles and genes should be mutually exclusive?

**Comment by kimrutherford** [comment]
> We can chat about this, is maybe moving into the territory of this ticket?  #929

I was wondering about that too.

> Alleles and genes should be mutually exclusive?

They could be: will the user be always searching for the exact allele name?  If so that will make it easier because most allele names won't be a sub-string of a gene name.  So if you paste in "wee1-50", we can show a match to that allele and we won't show any genes because "wee1-50" isn't a substring of a gene name.

The matches for publications and terms would probably need to be tweaked because currently "wee1-50" matches all the terms and pubs containing "wee1".

**Comment by ValWood** [comment]
How difficult is this:

if they type a gene name (wee1) they are searching gene names.
As soon as they type an additional character "wee1-" or "wee1( " 
the search switches to alleles?

**Comment by kimrutherford** [comment]
> The simple search should allow allele name search and suggest the genotype page (and eventually also allele page).

Now I think about this more, we probably will need to implement allele pages first.  There often are many genotypes for an allele (241 for cdc25-22!) so showing genotype in the completion we links to the genotype pages isn't going to work.

**Comment by ValWood** [comment]
Removing 'next' from this too. I will put it back when some  tickets  that will make training easier are done.
I will locate all of these next week (or at the weekend depending how today pans out)

**Comment by kimrutherford** [comment]
I've now finished most of the behind the scenes code to enable searching for alleles using Lucene.  I haven't made any changes to the search box or other website code because we still have stuff to discuss and we need allele pages first.

**Comment by kimrutherford** [comment]
I did some work on this over the weekend.  You can now search for alleles in the search box on the [dev website](http://dev.pombase.kmr.nz/).  It's disabled on the main site for now.

Currently, it only shows allele matches if no gene name or gene ID matches.  So you won't see any alleles if you type just "nhe1".

If you have typed or pasted in an exact allele name or synonym like "cdc2-M55" or "mcm4-2T->2S" it will show just that allele and/or any allele with a matching synonym:

![image](https://user-images.githubusercontent.com/90474/183318461-465bae2e-b891-41a8-8529-8bc5f12a8c2b.png)

![image](https://user-images.githubusercontent.com/90474/183319503-1f791736-bff0-4f4b-9927-973c30f65263.png)

Clicking or pressing return will take you to the prototype allele pages.

If it's not an exact match to an allele name it will have a go at matching the description, gene name and allele type.  That might be useful in some cases but will need tuning and can be disabled entirely if we don't need it.  Some examples:

![image](https://user-images.githubusercontent.com/90474/183319110-059ecf86-2969-421d-ad91-012a7ffb1b43.png)

![image](https://user-images.githubusercontent.com/90474/183319180-2b5ad4de-0796-4ec7-8c57-e8419ab975dc.png)

![image](https://user-images.githubusercontent.com/90474/183319253-8646f273-57a2-4254-a2dc-cffa7f4b8810.png)

![image](https://user-images.githubusercontent.com/90474/183319662-fc04b702-74eb-4193-8a82-fa66cd32edcf.png)

**Comment by ValWood** [comment]
most alleles begin with name- (name hyphen)

If I type cdc25-  I get only one suggestion. I don't see cdc25-22 etc.
even if I type cdc25-2 I don't see cdc25-22?
but I do see some cdc1- and rap1- allele suggestions

**Comment by ValWood** [comment]
I think the search might be trying to match the entire string name+description
cdc25-9A(S99A, S148A, S178A, S192A, S204A, S206A, T226A, S234A, S359A aa)
which means that the match is penalized.
It work better to make the search against name only?

**Comment by kimrutherford** [comment]
> It work better to make the search against name only?

Yep, we can do that.  We won't then be able to search for things like "cdc25 disruption" or "bub1 fusion".   If that's not useful we can disable it:

> If it's not an exact match to an allele name it will have a go at matching the description, gene name and allele type. That might be useful in some cases but will need tuning and can be disabled entirely if we don't need it.

**Comment by ValWood** [comment]
> Yep, we can do that. We won't then be able to search for things like "cdc25 disruption" or "bub1 fusion". If that's not useful we can disable it:

these would be generally harder to search for , and will usually also have a name. I think that is OK.

**Comment by kimrutherford** [comment]
I've changed the search to return alleles only where the name or synonym matches exactly.  (Dev site only)

**Comment by ValWood** [comment]
That does work.
However, I think the problem was that the name(description) was being treated as a single string. I think we wanted to be able to still do a substring search, but only on  the 'name' part, not the description part. We can chat about this tomorrow to be sure.

**Comment by kimrutherford** [comment]
> However, I think the problem was that the name(description) was being treated as a single string. I think we wanted to be able to still do a substring search, but only on the 'name' part, not the description part. We can chat about this tomorrow to be sure.

I think the search is working correctly now but let's have a quick chat about it on our next call.

I'd like to get this issue done.

**Comment by ValWood** [comment]
This is good to release. Further changes if requested will be in new tickets.
