### ISSUE TITLE
contig map image

### ISSUE THREAD

**Issue by ValWood** [pombase/website#181]
We might not have this at the top of  the page by default eventually...we can see..

For the relaunch it will probably still be there. Would it be better if it was slightly smaller?

e talked about cropping, but I don't know how easy this would be?

The bit we need is slightly variable because the key changes depending which feature types are shown.

I think we could lose the labels at the side
and the "tracks turned off" at the bottom like so:

![crop](https://cloud.githubusercontent.com/assets/7359272/23279251/60a37498-fa0c-11e6-8d2c-6ce6351c047a.jpg)

it would be a bit neater....

**Comment by ValWood** [comment]
things like this may make it impossible to trim the image....

http://pombase2.aska.gen.nz/gene/SPMIT.06

no point spending any time on this as it will be replaced eventually...
Maybe just resize and make smaller if possible.... It really is only for orientation, and the image can be much smaller for that. If people are really interested in  sequence detail, they will go to the browser... here, knowing the identity of, and being able to get to a neighbouring gene is sufficient...

**Comment by ValWood** [comment]
Kim what are your thoughts on the trimming?
How long would something like this take (will help decide if we should do it or ditch it)

**Comment by kimrutherford** [comment]
> Kim what are your thoughts on the trimming?

It's fairly easy to trim a fixed number of pixels from the edge of each image.  Anything else would be harder.

To do that we'd download all the images and run a script over them to do the processing.

> How long would something like this take

Not long at all.  An hour-ish maybe?

**Comment by ValWood** [comment]
Actually as it would need rerunning periodically  to pick up gene name changes etc, probably not useful to invest any time here (especially as these will be replaced eventually).

Can we just make the images slightly smaller (Antonia and I just discussed and thought 70% of  current size would be fine)

**Comment by kimrutherford** [comment]
> Antonia and I just discussed and thought 70% of current size would be fine

I've just done that.  Maybe 70% is too small?

**Comment by ValWood** [comment]
Hmm, maybe...
I think the size is good.... if the bottom part with the redundant key and "tracks turned  on" was not there....
Shall we try 80%?

**Comment by kimrutherford** [comment]
> Shall we try 80%?

I've done that.

**Comment by ValWood** [comment]
We'll call  this OK for now, until we have better.
We could make it bigger but the font has been quote "to hell and back" , so even if you make it bigger most of the labels are still illegible.....
