### ISSUE TITLE
make the ncRNA's in the browser paler and thiner

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1810]
We chatted about this when we spoke with Juan and @bahler about the ncRNAs. Jurg mentioned it again recently.  He thinks that they should not be so prominent. Could we make them pale grey?

**Comment by kimrutherford** [comment]
> Could we make them pale grey?

That will be the same as LTRs.  Is that OK?

https://www.pombase.org/jbrowse/?loc=III%3A760501..798900&tracks=Forward%20strand%20features%2CReverse%20strand%20features&tracklist=1&nav=1&overview=1&highlight=

**Comment by ValWood** [comment]
We could change the colour of the LTTRs and transposons. They could be a stronger colour as they are better defined features.
The problem with the RNAs is that a lot of them are cryptic and immediately degraded, they are only seen in certain contrived experimental conditions.

**Comment by kimrutherford** [comment]
I've changed the colours but I think I made the LTR colour too similar to the CDS colour.

The genes are now a little bit taller than LTRs, which are slightly taller than the RNAs.  Let me know if you'd like it to be more exaggerated.

**Comment by kimrutherford** [comment]
> I've changed the colours but I think I made the LTR colour too similar to the CDS colour.

That's improved now.  Let me know if it needs changing.
