### ISSUE TITLE
Annotation type "misc" has disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1812]
I don't see this on the gene pages, or in the menu.

e.g foy myh1
FT                   /controlled_curation="term=misc, soluble Myh1 level
FT                   decreases in presence of cisplatin or hydrogen peroxide;
FT                   db_xref=PMID:23677513; date=20130712"SPAC977.07c

I think these were displayed for CDS until recently (although not completely sure!)

**Comment by kimrutherford** [comment]
The misc annotations are shown in the "Comment" section.

![missing-misc-1](https://user-images.githubusercontent.com/90474/143661580-d91ee4d3-2208-4164-aa30-34d6681a2256.png)

**Comment by ValWood** [comment]
right!
