### ISSUE TITLE
more prominent link to licencing info (front page)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1813]
Should it be a link from the footer?
Separate menu link under about?
https://www.pombase.org/about/terms-of-use

**Comment by kimrutherford** [comment]
> Separate menu link under about?

I went for that option to start with.

**Comment by kimrutherford** [comment]
> I went for that option to start with.

I did try putting the text in the page footer too but it looked out of place.

**Comment by ValWood** [comment]
I think just in the menu is fine.
