### ISSUE TITLE
viewing "all annotations" to a protein feature

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1815]
This doesn't work

https://www.pombase.org/term/SO:0001528

I expected to see  evidence, extensions, annotation sources as for other data types

**Comment by kimrutherford** [comment]
Hi Val.  This isn't really a bug.  We've never had a term page section for SO annotation.  These annotations appear in the "Protein sequence features" sub-section of the "Protein features" section on gene pages.  I'll work on adding a "Protein features" section for term pages.

**Comment by kimrutherford** [comment]
Does this look OK?:

Summary:

![so-annotations-1](https://user-images.githubusercontent.com/90474/148303215-d9de66ce-90a0-4c52-9de6-730bf73a7a31.png)

Details:

![so-annotations-2](https://user-images.githubusercontent.com/90474/148303223-293761a0-93db-432e-a1e9-8f924000fbc6.png)

Reference page:

![so-annotations-3](https://user-images.githubusercontent.com/90474/148303229-1e9e5f57-118f-4f18-93cc-ae6b9fb53cb3.png)

**Comment by ValWood** [comment]
looks good!

**Comment by kimrutherford** [comment]
I fixed the bug I found so the change should be visible in the morning.
