### ISSUE TITLE
fasta search download bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1817]
downloading fasta nucleotide sequence for some tRNAs 

gives:
https://www.pombase.org/results/from/id/e1090d20-0d89-41c9-b634-96f44ea82057

IHDRÍ™ÔNbiCCPICC ProfileHâïWXS…û[RIhÅP§ÑﬁDÈêBã  UïêJå	A≈Œ∫¨ÇkQ,+∫*¢ËZY"v≈ﬁ* ∫X∞°Ú&$∞Æ˚ ˜Œ˜Õù?gŒ¸ßdÊﬁt:¯2Y>™@Å¥Pû óñŒ"u¿Å0Ê|ÅB∆âèèP˚øÀ€kQıó]U\ˇˇØ¢/) g	Çàõ¿K2y!ƒ0®∑ôZ(Sa1ƒr ƒ3U8Gçó™pño∞IJ‡B‹ô∆ÁÀs–nÖzVë Úh?ÇÿM*îH–1Ä8H Ê!NÇxxA¡dû±#¥óAºbv÷Wú9„œ‚ÁÛsÜ∞:Ø!áI≤|˛Ùˇ≥4ˇ[
ÚïÉ>Ïa£âÂQ	™¸a
o‰MéVaƒ›“¨ÿ8U≠!~/™ÎJ+£í’ˆ®ô@¡ÖıLà›Ñ¸∞hàÕ éêÊ«∆hÙYŸíƒpµ†”$Öº$Õ‹"Ex¢Üsù|rB‹ Œñs9öπu|˘Ä_ï}´2/ô£·ø!Ò˘ﬂãìR!¶ÄQã$)±kCl†»KåV€`÷≈bnÏ†ç\ô†äﬂb∂H™Ê«2≤Â	{YÅb0_¨T,·≈jpe°8)J]láÄ?ø1ƒı")'yêG§3òãPÆŒkIì5˘b˜dÖ°	öπ=≤¸xç=NÂG™Ù÷õ*ä5sÒQÖpq™˘ÒYa|í:N<3ó?:^^bÑP¬ñ&É\ iÎnËÜø‘#Ä‰ àÄ´F38#u`D
üâ†¸ë(ÜÊÖåä@‘“™üÆ {`¥h`Fxqà˘∑r`ñt»[
x5íx¿XÛaSç˝S«ÅöçF9»À“¥$Ü√àQƒ¢nä·x|Ü¿ÊÅ≥qø¡hˇ≤'<&¥Æ:7'IJ‰ﬂƒ2t@˛M∆Y_gå€CNo<ÑÏêg‚¶¿˜Ç~8x0ÙÏ
µ\M‹™‹Yˇ&œ°æ™π∆é‚FA)Fîä„∑3µùµΩáXT˝∫>ÍX≥Ü™ ˘÷?˜´:a˝≠%∂€áù¬éag∞CX`aG±FÏ<vXÖá÷–£Å54Ë-a û<»#˘á?æ∆ß™í
∑Z∑.∑Oö1P(öV®⁄`‹…≤ÈrIé∏ê≈Å_ã'åŒÚpÛp@ıMQø¶^3æÛÏ_∫í7
˚˚˚˝•ãÅ{zˇ˜põ?˛KÁpæå8].P ã‘:\ı ¿∑Å‹Q&¿ÿGòë ÑÉ— $Å40÷Y◊≥L3¡<P
 ¡R∞
¨¡f∞Ï{A8éÅì‡∏ÆÇ€p˝tÇÁ†º}Çê:¬@LKƒqA<6ÑÑ#1HíÜd"9àQ"3ëÔêrd9≤ŸÑ‘ ø ëc»§πâ‹G∫êW»GCi®jé⁄£#Q6 A£—$töÉNAã—˘Ëb¥≠Fw¢ıË1ÙzÌ@ü£Ω¿¥0&fÖπblåã≈aÈX6&«fceXVç’aMüæåu`›ÿúà3pÓ
◊pûå)¯l|æﬂé◊„≠¯e¸>ﬁÉ!–	fÇ?ÅGG»!L%î*[	'‡nÍ$º%âL¢—Ó∆4b.qqq=q7±ôÿN|HÏ%ëH&$R )éƒ'íJIkH;IGIóHù§˜d-≤%ŸÉAN'K…%‰
ÚÚÚ%ÚrEóbGÒßƒQÑîÈî%î-î& J'•è™Gu†Rì®π‘y‘Jjıııµñññµñü÷X-â÷\≠J≠=ZßµÓk}†È”úi\ZMI[L€Fk¶›§Ω¶”ÈˆÙz:Ωêæò^C?NøGØÕ–°Õ”jœ—Æ“Æ◊æ§˝Bá¢cß√—ô®S¨S°≥OÁÇN∑.E◊^ó´À◊ù≠[•{P˜∫nØCœ]/NØ@oëﬁΩ3zOıI˙ˆ˙·˙B˝˘˙õıèÎ?d`ó!`|«ÿ¬8¡Ë4 8r

**Comment by kimrutherford** [comment]
Hi Val.  Sorry, I can't reproduce that.  I got a correct FASTA file when I tried to download from that link.  Which browser where you using?

**Comment by ValWood** [comment]
I think I did not select nucleotide. It works.
