### ISSUE TITLE
allele names with 2 'deltas' not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1818]
https://www.pombase.org/reference/PMID:33526714

<img width="521" alt="Screenshot 2021-12-20 at 11 15 35" src="https://user-images.githubusercontent.com/7359272/146759119-7e25e6de-8db5-4245-923a-99401e3043bc.png">

the first delta resolves, but not the second one.

**Comment by kimrutherford** [comment]
I've fixed the code so that all the delta will be shown correctly, not just the first one.
