### ISSUE TITLE
do not display  lab strain from background

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1819]
for  Hayles et al 2013

<img width="1127" alt="___where is this background from" src="https://user-images.githubusercontent.com/7359272/118870247-3b2d3100-b8de-11eb-9c62-17efca7fe495.png">

**Comment by ValWood** [comment]
Note that the rest of the background is in column 7. So here it is just a case of not displaying column 6 (we can still store it in case we decide it is required in the future, but it looks odd in the background field because we don't usually capture it for LTP.

**Comment by kimrutherford** [comment]
> I don't think we should display this information on the website as we don't consistently collect it, and it isn't really necessary to understand the data.

Should we remove this information from Canto/Chado?

**Comment by ValWood** [comment]
I think we should still store it in Canto, just in case we decide to do anything with strains in the future, (we are unlikely to, but potential  collaborators working on strain manipulation tools etc may want this info).

**Comment by kimrutherford** [comment]
> The lab strain (SP286) name is displayed from column 6
>
> new_PMID_23697806_phaf.tsv

I don't have that file.

We have `PMID_23697806_phaf.tsv` in SVN but it doesn't have the "SP286" lab strain in any column.

`external_data/phaf_files/chado_load/htp_phafs/PMID_23697806_phaf.tsv`

**Comment by ValWood** [comment]
Right,  I think Midori must have fixed this in PMID_23697806_phaf.tsv
new_PMID_23697806_phaf.tsv is not checked in.
The  the "SP286" lab strain  has disappeared.
(maybe I did it but I have no recollection)

**Comment by ValWood** [comment]
So we can close this. If we ever want to add it we know the labstrain for the deletion collection is SP286
