### ISSUE TITLE
migrate existing "deletion mutant expression profiling" (see also  issues/629)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/website#1821]
we need to remap the existing

misc, deletion mutant expression profiling
http://www.pombase.org/spombe/related/PBO:0000206

to the new format:
/controlled_curation="term=external link; type=
where
type = the description of the link which will appear on the gene page
the accession will usually be of the form
GEO:GSE57040
ArrayExpress:E-MTAB-2543

TYPES
gene expression profiling
chromatin immunoprecipitation, h3k9me2
small RNA expression profiling

this will take some time as will need to dig in each paper for the Array Express or GEO ID

**Comment by ValWood** [comment]
See also https://github.com/pombase/website/issues/629
