### ISSUE TITLE
Add a GO slim filter option 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1822]
We probably discussed this a while ago and thought it did not add anything, but since it is possible (and the code already exists)  we should add it (in the odd cases like Cdc2 where there are a lot of slim terms, it can be quite useful to filter on specific processes).

e.g.
<img width="1294" alt="____Open ticket add filter" src="https://user-images.githubusercontent.com/7359272/148110231-2de9e116-6adc-43b8-bcc1-11b005b88051.png">

**Comment by kimrutherford** [comment]
I've had a go at this.

It required a bit of a code change to automatically configure the filter based on the slim terms but I don't think I've broken anything.

I configured it for disease association too. I assume that makes sense?

Let me know if you'd like any changes.

**Comment by ValWood** [comment]
Great! highlights  some fundamental ontology problems with regulation and signalling !, but I knew about those.I can use this to illustrate ;)
