### ISSUE TITLE
add 'product' to  popup and genotype & publication  page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1826]
I would find it useful if the pop up from the genotype on the gene/publication pages also included **'product'**
Often I can't remember which gene it actually is, and it is 2 clicks to get to the gene page, which is frustrating if you are looking at lots of different genotypes.

<img width="700" alt="Screenshot 2022-01-17 at 14 24 52" src="https://user-images.githubusercontent.com/7359272/149825536-49886fb3-0a57-41af-b512-bd00a2bc91a7.png">

**Comment by ValWood** [comment]
Obviously for single allele genotypes it isn't an issue from the gene page, but for multi allele genotypes it is:

<img width="878" alt="Screenshot 2022-01-17 at 19 10 21" src="https://user-images.githubusercontent.com/7359272/149825748-f3ac5893-b8e3-48ca-aad7-6ec5a236e181.png">

**Comment by kimrutherford** [comment]
It's easy enough to add but it might be a bit too much detail for the popup in some cases:

![product-for-genotypes-1](https://user-images.githubusercontent.com/90474/149858487-2da8df30-e679-4f91-a2ae-e7de2e851214.png)

-------------------

It's less of a problem on the genotype page:

![product-for-genotypes-2](https://user-images.githubusercontent.com/90474/149858551-4b60e039-dbcc-4ff6-8422-eaba8246c20b.png)

**Comment by ValWood** [comment]
Yep agreed, let's just add to the genotype (and pending allele) pages.

Although, it would be interesting which info the community would find the most useful in the pop-up.  Perhaps the product would be more useful than the 'type' because that is usually  obvious from the name and description.
This pop-up  is probably most useful to provide a quick way to recognise the gene before you click through to the genotype page for all the details.

Asking
@Lilindu 
@JackyVH 
@bahler 
@juanmatacambridge 
@deygautam
@smarguer

preferences anyone?

**Comment by kimrutherford** [comment]
> Yep agreed, let's just add to the genotype (and pending allele) pages.

I've added the product on the genotype pages.

**Comment by ValWood** [comment]
nice.
