### ISSUE TITLE
RHEA prefix is not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1827]
See:
https://www.pombase.org/term/GO:0004712

(not I am filtering these so it won't be visible by tomorrow, I can find other examples though)

**Comment by kimrutherford** [comment]
Do we want to display prefixes for RHEA?  We don't for other databases.  Should we make a special case?

**Comment by ValWood** [comment]
Ah right in.  that case no. It just looks a bit odd because it is a number and most IDs include something recognisable  IPR, PTN, UR, PF, S...
ignore!
