### ISSUE TITLE
possible bug in interaction display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1829]
https://www.pombase.org/reference/PMID:31064814

At PomBase on the apt1 gene page we have:

<img width="1034" alt="Screenshot 2022-01-24 at 11 44 31" src="https://user-images.githubusercontent.com/7359272/150777247-97768660-5cee-455a-a9ee-4e819f24ea9f.png">

(i.e apt1 interacting with itself)

but on the publication page it is:

<img width="1131" alt="Screenshot 2022-01-24 at 11 41 34" src="https://user-images.githubusercontent.com/7359272/150777008-249d2d76-7643-41fa-bb30-1aac1941d06c.png">

(rmt3 interacts with apt1)

and at BioGrid it is :
<img width="1174" alt="Screenshot 2022-01-24 at 11 39 21" src="https://user-images.githubusercontent.com/7359272/150777047-75c4eb52-c16c-4555-871d-fa3a475fb682.png">

(rmt3 interacts with apt1)

**Comment by ValWood** [comment]
.....and the corresponding physical interaction does not show on the rmt1 page

**Comment by ValWood** [comment]
Ignore previus comment. It should be rmt3.
The interactions do appear on the rmt3  page, but the first field (which has no header, did it always look like this?) is blank (maybe it should be?)

**Comment by ValWood** [comment]
same for 
https://www.pombase.org/gene/SPBC1703.07
same dataset.

**Comment by ValWood** [comment]
Is this a new evidence code that we don't know about?
"Proximity Label-MS"

**Comment by kimrutherford** [comment]
> Is this a new evidence code that we don't know about?
> "Proximity Label-MS"

Yep!  Thanks for spotting that.  Probably that's what's causing the display weirdness.  Would these be symmetrical or directional interactions?

**Comment by ValWood** [comment]
directional.
I think the 'relation' would be 'affinity captures'

Proximity Label-MS - An interaction is inferred when a bait-enzyme fusion protein selectively modifies a vicinal protein with a diffusible reactive product, followed by affinity capture of the modified protein and identification by mass spectrometric methods, such as the BioID system PMID: 24255178. This system should not be used for in situ proximity ligation assays in which the interaction is measured by fluorescence, eg. PMID: 25168242, which should be captured as co-localization.

it just seems to be a different pre-step.

(will need adding to Canto too)

**Comment by kimrutherford** [comment]
> directional.
> I think the 'relation' would be 'affinity captures'

Thanks.

I've added the configuration to the website, Canto and for Chado loading.  I'll check how it looks tomorrow morning.

**Comment by kimrutherford** [comment]
It looks OK to me now.  Could you have a look to double check?

**Comment by ValWood** [comment]
all good
