### ISSUE TITLE
News item and citation page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1830]
PomBase & JaponicusDB publications in the  GENETICS MOD reports special issue.
2022-02-01

Papers describing PomBase and JaponicusDB are now published (early online). These articles are part of a special issue of GENETICS devoted to model organism database (MOD) reports. The MOD papers will highlight the journal’s new section on Computational Resources, Software & Databases.

Add links

Citation page will also require updating

**Comment by kimrutherford** [comment]
I've added the news item.  It the screenshot below looks OK, I'll update the main site.

The file is here if you'd like to tweak things: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-02-02-pombase-and-japonicusdb-papers.md

![new-news-1](https://user-images.githubusercontent.com/90474/152131697-b9bb1ca0-5b7d-426a-83c0-89bfac091b7d.png)

**Comment by ValWood** [comment]
LOoks good!

**Comment by kimrutherford** [comment]
Great.  Should I remove the curator advert item while I'm at it?

**Comment by ValWood** [comment]
yes please!

**Comment by kimrutherford** [comment]
All done.
