### ISSUE TITLE
Missing menu links?

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1832]
I wanted to get to the page listing the DNA binding sites
https://www.pombase.org/browse-curation/dna-binding-sites

but i can't see how to get there from the existing menu links?

I had this page cached:
https://www.pombase.org/browse-curation

I'm sure there used to be a "drug target" menu link?!

**Comment by ValWood** [comment]
I can't even find the link from her:
https://www.pombase.org/documentation
and I'm sure I have used it!

**Comment by Antonialock** [comment]
Maybe a new category "inventories" some of the genome status items could move there too
curated pubs...disease association overview...?

**Comment by Antonialock** [comment]
or "catalogs"? :-)

**Comment by kimrutherford** [comment]
> I can't even find the link from here:
> https://www.pombase.org/documentation

There's a link at the bottom of this page: https://www.pombase.org/datasets

And on this page: https://www.pombase.org/browse-curation  (which I can't see a link to anywhere)

**Comment by kimrutherford** [comment]
Related, I think: #901

**Comment by ValWood** [comment]
duplicate!
