### ISSUE TITLE
some graphical abstracts not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1833]
https://www.pombase.org/reference/PMID:23703609
https://www.pombase.org/reference/PMID:34895466
https://www.pombase.org/reference/PMID:1899230

**Comment by ValWood** [comment]
Actually,this one does not have a graphical abstract,
https://www.pombase.org/reference/PMID:1899230
but it looks as if it does (but not rresolving)

**Comment by kimrutherford** [comment]
I think the border of the image is being shown even for cases when no image is available.  I'll fix that.

**Comment by kimrutherford** [comment]
Fixed!
