### ISSUE TITLE
FYPO slim?

### ISSUE THREAD

**Issue by mah11** [pombase/website#1838]
@matentzn emailed to ask  for a set of phenotypes that reflect the "priorities and interests of the users when browsing gene-related phenotype data of your own resources", which sounded a lot like phenotype ontology slims to me. So I cobbled together a list based on the fission yeast GO slims and my gut feelings, and am plunking it here for reference -- if you ever get motivated to build a FYPO slim, this might be a reasonable starting point.

[proto-fypo-slim.txt](https://github.com/pombase/fypo/files/7498418/proto-fypo-slim.txt)

**Comment by ValWood** [comment]
HI KIm,

since ee have the code, let's implement this as one of our default slim sets.
I would like to do some grouping for different drug sensitivities  but we can do this later. It will be interesting to see what does not slim at present.

**Comment by kimrutherford** [comment]
No problem.  We'll need a short description of the slim for headings and the like.  Is "Fission yeast phenotype ontology overview" OK?

And we'll need the text to put at the top of the slim page.  Like on these pages:
  - https://www.pombase.org/browse-curation/fission-yeast-mf-go-slim-terms
  - https://www.pombase.org/browse-curation/disease-slim

**Comment by ValWood** [comment]
... especially since soon we will be extending the page types to include "allele" and genotype" we need to consolidate a little

**Comment by kimrutherford** [comment]
> to just "Overviews" ?

That makes sense.  I should be able to get these changes into tonight's update.

**Comment by kimrutherford** [comment]
The overview on some gene pages is quite big.  Is that OK?  Is the slim slim enough?  This is cdc2:

![fypo-slim-gene-page-1](https://user-images.githubusercontent.com/90474/154375725-8f6a73b1-8e0a-4a7b-940a-7015ce9e98c0.png)

**Comment by kimrutherford** [comment]
Should this be enabled for JaponicusDB too or are there not enough FYPO annotations?

**Comment by ValWood** [comment]
I think a few terms can be removed.
For now, delete :
1. cell cycle arrest phenotype & mitotic cell cycle checkpoint phenotype (covered by cell cycle phenotype)
2. abnormal DNA recombination  (covered by DNA metabolism phenotype)
3. abnormal DNA replication   (covered by DNA metabolism phenotype)
4. cell population viability (covered by viable & inviable terms)
5. remove "protein localization phenotype" (localization phenotype will do)
6. change "abnormal microtubule cytoskeleton organization" to "abnormal cytoskeleton organization" (more general)

There may be some more refinements later. This 'overview' is always going to be larger because phenotypes are often pleiotropic. This illustrates the difference between GO (what activity/process a gene is directly involved in), and phenotypes  observed when a gene is mutated (functions and processes  affected both  directly and indirectly).

I think we can implement for japonicus. There will be very little of the slim populated, but this will indicate the breadth of study.  Again, it is slightly different in purpose from the GO slim. For the GO slim we want to infer what is missing wrt normal conserved roles.  Phenotypes need to be directly observed in the species of interest (so we are only interested in what has been seen).

**Comment by kimrutherford** [comment]
> For now, delete :

I've removed those terms and checked-in the config for the FYPO slim.  I'll check the result on Saturday morning.

**Comment by kimrutherford** [comment]
Note to self: we'll need to make sure that we don't show the "Fission yeast phenotype overview" on the gene page multi-allele phenotype section.

**Comment by kimrutherford** [comment]
> In the slim we should only include single locus phenotypes (and make this clear).

I've changed the code to include only single locus genotypes.  So the numbers in the FYPO slim table will be lower tomorrow.  

There are still some things to do:
Tomorrow the counts will be links to the single locus genes pages like: https://www.pombase.org/term_single_locus_genotype_genes/FYPO:0004803
I think that's correct but we need to be clear what's on those pages maybe with a description somewhere.

**Comment by kimrutherford** [comment]
> So the numbers in the FYPO slim table will be lower tomorrow.

The nightly load worked so the numbers in the FYPO slim table are now only for single locus genotypes and the links go to the matching `/term_single_locus_genotype_genes/...` pages.

> I think that's correct but we need to be clear what's on those pages maybe with a description somewhere.

I've made a note to talk about that on a Skype call at some point.

**Comment by kimrutherford** [comment]
I've added the configuration for a FYPO slim for JaponicusDB.  I think that was the plan?

It will be visible from Saturday morning.

**Comment by ValWood** [comment]
I'm not sure- I thought we decided not to add the phenotype slim for now because such a small fraction of genes are annotated it wouldn't make much sense. But maybe it does make sense. Lets see  once it is in place. We can ask snezka...

**Comment by ValWood** [comment]
We still need the front page link too..

**Comment by kimrutherford** [comment]
> We still need the front page link too..

Which link?

**Comment by ValWood** [comment]
Also still need a front page link... https://www.pombase.org/browse-curation/fypo-slim

**Comment by kimrutherford** [comment]
> Also still need a front page link...

How's this?  It's getting a bit busy on that side of the page.  We might want to think about reformatting it.

![fypo-link-1](https://user-images.githubusercontent.com/90474/163085261-d0d6c09f-7dc4-44f8-8428-546cb39dc318.png)

**Comment by ValWood** [comment]
yep, this is fine for now

above we discussed:
to just "Overviews" ?

Overviews: Function * Process * Component
Phenotype * Disease association

that might work.

But you should not be working! rest! for a few days! Nothing is urgent.

**Comment by kimrutherford** [comment]
> above we discussed:
> to just "Overviews" ?

Which of these do you prefer?:

-----------------------------------

![fypo-front-page-1](https://user-images.githubusercontent.com/90474/163099523-d9619e40-84c7-4529-9988-d799e983ecfc.png)

----------------------------------

![fypo-front-page-2](https://user-images.githubusercontent.com/90474/163099535-ac56ef81-c623-482f-802c-2cf54b39c100.png)

**Comment by ValWood** [comment]
I think the first?

**Comment by kimrutherford** [comment]
> I think the first?

OK, that's on the main site now.

**Comment by ValWood** [comment]
new tickets for further changes
