### ISSUE TITLE
Publication and term page summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#184]
Need to show gene/genotype in default view.

see

![which genes](https://cloud.githubusercontent.com/assets/7359272/23309129/6aac6f3c-faa5-11e6-9cf6-0fe3e241e775.jpg)

you don't know which genes these annotations belong to until you go to "full view"

**Comment by kimrutherford** [comment]
Moved from #168:

> Hmm, good point, not sure....I think I prefer totally unambiguous:
>  cdc2 has substrate cut7
>  abc1 has substrate cut7
>  any1 has substrate cut7

> (I don't think this will inflate too much)
> interested what A&M think though.....

**Comment by kimrutherford** [comment]
> (I don't think this will inflate too much)

Some pages are going to be quite long.
eg. http://pombase2.bioinformatics.nz/term/FYPO%3A0002060

**Comment by ValWood** [comment]
closing in favour of 
https://github.com/pombase/website/issues/190
