### ISSUE TITLE
author search does not work if name has 'special characters'

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1840]
Gomez
does not retrieve 
https://www.pombase.org/reference/PMID:18505873
Gómez EB
(the paper I was looking for)

Is there a way to male the leucene search cope with this?

**Comment by kimrutherford** [comment]
After a bit of trail and error I think I've fixed this.  The change should be working on Sunday morning.

**Comment by ValWood** [comment]
that will be nice, we have so many users with awkward chars!

**Comment by kimrutherford** [comment]
It seems to work.  I get the same completion list for "Gómez" and "Gomez".
