### ISSUE TITLE
Update JBrowse and report scrolling bug

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1842]
The inline JBrowse isn't always at the top when it's displayed on gene pages.  We should check for the bug after the next update and report it if it's still there.

**Comment by ValWood** [comment]
I'm not sure if this is the issue:
https://github.com/GMOD/jbrowse/issues/688

**Comment by kimrutherford** [comment]
I don't think it's the same issue.  We're not using a popup.

**Comment by ValWood** [comment]
We are already using JBrowse2 aren't we?
I thought I had opened a ticket about this but I can't find it f we are using JBrowse2 I will open one.

**Comment by kimrutherford** [comment]
We're using JBrowse v1.  I haven't tried v2 yet.  It's quite a re-write so upgrading to it might be a bit of work.

**Comment by ValWood** [comment]
transferred to 
https://github.com/pombase/website/issues/2038
