### ISSUE TITLE
Restore old Trac wiki pages as html pages somewhere

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1843]
This wiki was a  basically a flat list (no nested pages IIRC, or at least in the ones we used)

The 'front page provided a list of the linked pages. I  have slowly been moving all of the ones that we do not use under 'deprecated'. This is the vast majority of them. If you can put up a copy of the front page I can provide a list of  precisely which pages I still use (I don't think it is very many). Then we can decide which once need to be incorporated into our documentation (I think some can just be lists on the wiki. The pages are a bit messy but I can tidy them during training.

**Comment by kimrutherford** [comment]
Is anything else needed here?

**Comment by ValWood** [comment]
Where are they again?

**Comment by kimrutherford** [comment]
https://curation.pombase.org/kmr44/trac_wiki_contents/

**Comment by ValWood** [comment]
I have a ticket!
https://github.com/pombase/curation/issues/3202
I forgit!
