### ISSUE TITLE
display of diploid single locus

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1848]
<img width="684" alt="Screenshot 2022-03-01 at 18 26 01" src="https://user-images.githubusercontent.com/7359272/156318789-341441eb-19aa-4231-a864-dea38870de79.png">

Here the genotypes should also include the diploids. Diploids are same locus. There may be a ticket about this already.

**Comment by kimrutherford** [comment]
Whoops, it's supposed to already.  Do you have an example where it's not working?

**Comment by ValWood** [comment]
Oh I didn't check, I was just reading these links

<img width="684" alt="Screenshot 2022-03-01 at 18 26 01" src="https://user-images.githubusercontent.com/7359272/156332611-2296a083-c8fd-462a-8bf5-df0143cdda78.png">

So maybe just the links need updating.

View XX genes from single locus genotypes associated with this term...
View XX ~haploid~ single locus genotypes associated with this term...

**Comment by kimrutherford** [comment]
This was easier to fix than I thought.  Both links were only including haploid genotypes but the first link wasn't mentioning that.

This is fixed for the morning and both links will include haploid and diploid genotypes.
