### ISSUE TITLE
small display redundancy in GO extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#185]
![small display redundancy](https://cloud.githubusercontent.com/assets/7359272/23310216/a6e37172-faa9-11e6-913e-a16abcaa5994.jpg)

**Comment by ValWood** [comment]
So above 

because we have
has substrate dis2 during yada yada

we don't need to show
has substrate cdc18, rum1 ~~dis2~~

**Comment by ValWood** [comment]
I did some annotation jiggling on cdc2 page,
this section now looks like this:

![temp](https://cloud.githubusercontent.com/assets/7359272/23331243/d9c46866-fb59-11e6-9739-0006f6019185.jpg)

**Comment by ValWood** [comment]
So, in summary view srw1,  cdc18, and dis2 are redundant
I'm still trying to link  cut7 and hcn1 to  biological process....

**Comment by kimrutherford** [comment]
So are there any extensions where we wouldn't want to do this?  If there is a more specific extension should we always hide the less specific one?

**Comment by ValWood** [comment]
In the summary view yes.

Its  not really a more specific extension, rather a more specific combination of extensions.

So in this instance,
cyclin-dependent protein kinase activity
has substrate cdc18

is less specific (yes you are correct!) than 
cyclin-dependent protein kinase activity
has substrate cdc18, involved in negative regulation of DNA replication..yada

This will always be the case...you only need to see the separate annotations in full view (because they will likely be different citations), but in the summary view they don't add any information.

**Comment by ValWood** [comment]
Also
https://github.com/pombase/website/issues/45

Although one is about terms, and one about extensions, probably  best to treat together? Both about display redundancy.....

**Comment by kimrutherford** [comment]
I've been working on this (and #45).  I've temporarily made things worse.  There is now a lot of redundancy again.  This is temporary while I fix things to handle terms and extensions and the same time.

**Comment by kimrutherford** [comment]
> I've temporarily made things worse.

In the case of phenotypes, quite a lot worse.  Sorry about that I only just noticed.  I'll fix it.

**Comment by kimrutherford** [comment]
The genes in otherwise identical annotations are now collected together like this:

    has substrate atf1 , srk1 during cellular response to hydrogen peroxide

There are still some things to fix:

- [ ] the gene appears beside each annotation on the gene page
- [ ] the extensions with two or more binds relations don't get turned into "any1 *and* any2" etc.
- [ ] on the term pages the genes with no extensions should be groups together onto one line
- [ ] the redundancy problem Val created this ticket about is still there

**Comment by ValWood** [comment]
- [ ] and the substrate genes are missing (although the relation s there)

**Comment by kimrutherford** [comment]
> and the substrate genes are missing (although the relation s there)

Ah, sorry.  It was working for me locally but I forgot to release the changes.  Should be working now.

**Comment by ValWood** [comment]
nice

- [ ]  "directly inhibits" and  "directly activates" are used (by us incorrectly as it happens) as more specific forms of "has_substrate".
For now they should be treated as "has_substrate". We need new relationships to  capture this exactly so this is kind of a "place holder". I'm still thinking what to do.

Anyway in the meantime, treat them like a type of "has_substrate" for ordering....

**Comment by kimrutherford** [comment]
> "directly inhibits" and "directly activates"

Could you suggest an example gene or two that I can look at to check things are working?

> Anyway in the meantime, treat them like a type of "has_substrate" for ordering

When you have a "directly activates" extension, should it be displayed as "has substrate"?

**Comment by ValWood** [comment]
cdc2 MF has a couple of examples.
"directly activates"/"directly inhibits" should be displayed, but when we have used it, we have used *instead* of "has_substrate".

Because it isn't quite GO -compliant, we might even need to convert it to "has_direct_input"  (the real name for has_substrate) in the GAF.

Sorry about this one!

**Comment by kimrutherford** [comment]
> the extensions with two or more binds relations don't get turned into "any1 and any2" etc.

That's done, although I've spotted an oddity on the bqt1(SPAC6G9.13c) page:
  http://pombase2.bioinformatics.nz/gene/SPAC6G9.13c

It's showing:

    protein binding, bridging
      binds sad1 and rap1 binds bqt2

because although we're showing "binds", the actual extension is:
 has_direct_input(sad1), has_direct_input(rap1), binds(bqt2)

The code isn't merging the binds(bqt2) with the rest because the relation is different.  I can easily change the code to collect the genes together based on the displayed relation rather than the relation in Chado but I thought I should check with you before I do.

**Comment by kimrutherford** [comment]
>  "directly inhibits" and "directly activates" are used (by us incorrectly as it happens) as more specific forms of "has_substrate".
> For now they should be treated as "has_substrate".

I'm still a bit confused by this.  Do you mean we should replace "directly inhibits" and "directly activates" with has_substrate in Chado?  Or is this just a display thing?

**Comment by kimrutherford** [comment]
> That's done, although I've spotted an oddity

Also this looks odd on the dsc1 (SPBC947.10) page:

    sterol regulatory element binding protein cleavage
      has input sre1 and sre2 , sre2

http://pombase2.bioinformatics.nz/gene/SPBC947.10

**Comment by ValWood** [comment]
transferred dsc1 query to the curtion tracker, We'll look into it. I suspect it needs refining...

https://github.com/pombase/curation/issues/1338

**Comment by ValWood** [comment]
I already opened a ticket about the bqt 1 one oddity, I think we need to refine this one too:
https://github.com/pombase/curation/issues/1335

**Comment by ValWood** [comment]
> I'm still a bit confused by this. Do you mean we should replace "directly inhibits" and "directly activates" with has_substrate in Chado? Or is this just a display thing?

Yes it is a bit confusing, sorry.
For now, store/display the qualfier we have used 
directly_negatively_regulates (display label directly inhibits)
directly_positively_regulates (display label directly activates)

We have used instead of "has direct input, display label/has substrate"
I thought it was a descendant of has_substrate, but it has a slightly different meaning, it refers to the activity of the gene product, not the gene product itself".
In reality it should only be used in LEGO modelling where gene products can be connected directly to the "activities" they enable.

At some point we will need to migrate to a new qualifier with the correct meaning.

For now treat like a "has_substrate" in the display label ordering hierarchy. I am trying to think if there is a better/alternative way to do this, but I haven't had time to devote any head space to it yet.
It will be at the top of my list once I have the new matrix rules ready for GO and I have summarized the data for Seth's talk.

So you have enough info now to deal with it in the interim?
If not, we can also chat about it tomorrow.

**Comment by ValWood** [comment]
Add discuss label to this ticket if you are still stuck.

**Comment by kimrutherford** [comment]
> we don't need to show
> has substrate cdc18, rum1 ~~dis2~~

This bit is finally done.  The redundant rows in the summaries have been removed.  Please let me know if you see any weirdness.

**Comment by ValWood** [comment]
Well its looking very good!
There will be some tiny tweaks but we'll open new tickets.
