### ISSUE TITLE
redundancy  filtering in Molecular function

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1850]
The second binds cdc15 is redundant 

<img width="575" alt="Screenshot 2022-03-08 at 10 02 49" src="https://user-images.githubusercontent.com/7359272/157246154-5f9e8f96-f3fa-433a-bff1-39b73f5a6f34.png">
g

(it is possible this is a duplicate,  if so I will close on my next tracker review)

**Comment by kimrutherford** [comment]
I don't think I've seen that bug before.

It's probably due to the active form extension which has special handling and has caused problems in the past: pombase/website#1782

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  I'll check things on Saturday.

**Comment by kimrutherford** [comment]
Since I updated the website to fix the news item, this change has gone live too.  This issue is fixed but it's tricky code so sorry if something else goes weird.

**Comment by ValWood** [comment]
Hmm, I don't think this is fixed. It still looks like this
:
<img width="1037" alt="report binds *** binds ***" src="https://user-images.githubusercontent.com/7359272/181039851-168287af-0386-434a-ad16-c7ab56617e54.png">

At least it is partially fixed because now the bound entity os present as a linked gene, and a linked modification. However the bound gene is present redundantly?

**Comment by kimrutherford** [comment]
> It still looks like this

Which gene page is that?

**Comment by ValWood** [comment]
That was actually a pub page
https://www.pombase.org/reference/PMID:28367989
gene page is
https://www.pombase.org/gene/SPAC222.09

**Comment by kimrutherford** [comment]
I think that's a different issue.  This issue is about the case where there are two separate annotations with a binds extension that need to be merged in the summary.  Your screenshot looks like two binds in the same annotation.  Maybe there's another issue about that somewhere?

**Comment by kimrutherford** [comment]
> I think that's a different issue.

Maybe this?: https://github.com/pombase/website/issues/1710#issuecomment-1089870469

**Comment by kimrutherford** [comment]
I think I've found the problem.  I hadn't finished off this issue:
https://github.com/pombase/pombase-chado/issues/974
The website generation code was only combining the `binds` extensions if the PR ID bit used the `has_direct_input()` relation but should have looked for `has_input()` after pombase/pombase-chado#974.

(Note to self: the extension is displayed as `binds` but the annotation has `has_input()`)

I'm testing a fix now to change the web code to look for `has_input()` instead.

**Comment by kimrutherford** [comment]
I think this is fixed now on the main site.
