### ISSUE TITLE
odd display of compound extensions on GO term page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1851]
On website.
See https://www.pombase.org/term/GO:0006338
<img width="1151" alt="Screenshot 2022-03-10 at 10 13 46" src="https://user-images.githubusercontent.com/7359272/157672502-50ec9155-23a8-48cf-8cd8-037595cd6c6a.png">

and the link gives a page not found

in canto
<img width="498" alt="Screenshot 2022-03-10 at 13 28 05" src="https://user-images.githubusercontent.com/7359272/157672597-d4a4480d-4c1d-4760-a56f-eddc8019dcbf.png">

ideally it would be yaf9,swc4,rvb1

**Comment by ValWood** [comment]
the gene here is arp6,
but this annotation does not display on the arp6 page? even though it is experimental

**Comment by kimrutherford** [comment]
It looks like it's failing to parse all the with fields from that publication: https://www.pombase.org/reference/PMID:19040720

I think they are from the GOA GAF which has "PomBase:SPAC17G8.07,PomBase:SPAC9G1.13c,PomBase:SPAPB8E5.09" in the with field for that arp6 annotation.

The loading code is assuming that if there are multiple withs then they will be separated by "|" but in the GOA GAF they are separated by commas.

The GAF docs say to use "|": http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/#with-or-from-column-8

The quick fix is for the code to split on pipe or comma.  I'll make that change and close this in the morning if it works.

**Comment by ValWood** [comment]
pipe and comma have different meanings.
pipe means separate annotations  comma means compound annotation.

Here, I am trying to say that all 3 are bound at the same time (they are members of the same complex)  so it is a compound annotation. However, I don't want 3 separate annotations  so I am going to remove two of the "with" entries.  
You don't need to do anything.....

**Comment by kimrutherford** [comment]
The docs don't mention comma: http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/#with-or-from-column-8

> However, I don't want 3 separate annotations so I am going to remove two of the "with" entries.

There won't be 3 separate annotations.  The loader doesn't do that for with fields, only for extensions.

**Comment by ValWood** [comment]
OK will change to a pipe...

**Comment by ValWood** [comment]
Does this go into the logs? I couldn't see it.

**Comment by kimrutherford** [comment]
> Does this go into the logs? I couldn't see it.

It wasn't logged.  The code was splitting on "|" and then assuming the parts were valid if they started with "PomBase:".  So the code was treating "PomBase" as the prefix and "SPAC17G8.07,PomBase:SPAC9G1.13c,PomBase:SPAPB8E5.09" as the identifier.  It doesn't do any sanity checks on the identifiers at the moment.  I'll change it to at least complain if there's a comma after the prefix.

So it was going straight through to Chado and the website.  Which is why it's so messed up in the screenshot you made

**Comment by ValWood** [comment]
Of course!

**Comment by ValWood** [comment]
I changed IPI and IGI seperator  to a pipe in  legacy GO file.

**Comment by kimrutherford** [comment]
Thanks.  I've changed the loading code to warn about commas in with fields.

I'll check the site in the morning.

**Comment by kimrutherford** [comment]
It looks OK now: https://www.pombase.org/term/GO:0006338
