### ISSUE TITLE
PomBase external link to QuickGO

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1854]
For some reason, we only lin from pombe external links to AmiGO, but not to QuickGO

GO annotation | AmiGO | SPBC11B10.09 | GO Consortium browser

For japonicus we include both

GO annotation | QuickGO | B6JZV3 | QuickGO Gene Ontology annotation viewer
-- | -- | -- | --
GO annotation | AmiGO | SJAG_01143 | GO Consortium browser

**Comment by kimrutherford** [comment]
I don't know how that happened.  I've added QuickGO to the configuration and I'll check the gene pages in the morning.
