### ISSUE TITLE
README FILE for orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1864]
Manual ortholog prediction methods: The human and budding yeast orthologs are manually predicted based on a variety of sources. In some cases the consensus ortholog from the major ortholog predictors (Compara, Inparanoid, OrthoMCL, Panther, RoundUP, OrthoInspector etc.) is used. Many distant orthologs have also been identified by PSI-BLAST, or Jackhmmr matches ~that  are uniformly one-to one across species~; these alignments have been submitted to the [Pfam](http://pfam.xfam.org/) protein family database. Other ortholog predictions come from experimental data demonstrating functional correspondence or involving membership of corresponding complexes. These predictions are also aligned and submitted to Pfam before inclusion. PomBase’s approach ensures that the breadth of coverage is greater than any individual prediction method, and includes many ortholog calls which are not detected by any automated method.

Note that most orthologs represent co-linear proteins which align over most of their length, the following proteins represent  tandem repeat proteins in one species. In these cases there are independent proteins in the other species mapping to the N and C terminal regions. Some, but not all of these are known to be post translationally cleaved.
SPAC1782.04     YLR204W(N)|YNL295W(C)
SPAC806.02c     YIL003W(N)|YDR267C(C)
SPAC22A12.08c   YKR070W(N)|YDL142C(C)
SPBC16A3.11     YDR419W(N)|YFR027W(C)
SPCC1450.15     YDR302W(N)|YBR265W(C)
SPAC6F12.05c    YJR142W(N)|YOR143C(C)
SPBP4H10.15     YJL200C(N)|YJL096W(C)
SPAC22E12.10c   YER141W(N)|YPL252C(C)
SPAC19B12.13    YPL132W(N)|YKL155C(C)
SPAC1420.04c    YPL132W(N)|YKL155C(C)
SPBC530.12c     NONE(N)|YGR036C
SPAC15E1.04     NONE(N)|YOR074C(C)
SPCC1223.08c    YOR280C(N)|YMR222C(N)|YHR049W(N)|YOR236W(C)  
SPBC29A3.02c    YCL030C(FUSION-N)
SPBC1711.13     YCL030C(FUSION-C)

Also please delete the x-ed out line from the first paragraph from the documentation

**Comment by ValWood** [comment]
here
... https://www.pombase.org/documentation/orthologs

**Comment by ValWood** [comment]
Should we also describe the difference between the 2 file formats in the docs/README?

**Comment by kimrutherford** [comment]
Which directory should this new README go in?

> Should we also describe the difference between the 2 file formats in the docs/README?

I think so.

**Comment by kimrutherford** [comment]
> Also please delete the x-ed out line from the first paragraph from the documentation

I've done that for the morning.

It's here if you'd like to tweak it: https://github.com/pombase/website/blob/master/src/docs/documentation/orthologs.md

**Comment by kimrutherford** [comment]
> It's here if you'd like to tweak it: https://github.com/pombase/website/blob/master/src/docs/documentation/orthologs.md

As well as the edit / pencil button, you can also press the full stop key to go straight to editing the file in VSCode inside your browser.  I'll give you a quick demo some time.

**Comment by ValWood** [comment]
Oh please. Thare was also some issue with VS code markup that we did not figure out

**Comment by kimrutherford** [comment]
This is done.
