### ISSUE TITLE
ortholog display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1865]
We did plan to include the information about ~tandem repeats~ fusion proteins in the orthlog file. However, there are not very many of these and it will make the ortholog file more complicated. Instead, we will add this info to the READMe File.

However, I found a ticket that says we already capture this information thus:
https://github.com/pombase/pombase-chado/issues/202

/controlled_curation="term=orthologous to S. cerevisiae YDR267C; qualifier=SPAC806.02c,C_term; date=19700101"
/controlled_curation="term=orthologous to S. cerevisiae YIL003W; qualifier=SPAC806.02c,N_term; date=19700101"
OR
tandem fusion in S. cerevisia
his7
/controlled_curation="term=orthologous to S. cerevisiae YCL030C; qualifier=YCL030C(N-term); date=19700101"
his2
/controlled_curation="term=orthologous to S. cerevisiae YCL030C; qualifier=YCL030C(C-term); date=19700101"

so we could put a  flag on the ortholog section of the web pages.
What do you think?

**Comment by kimrutherford** [comment]
> so we could put a flag on the ortholog section of the web pages.
> What do you think?

Yep, no problem.  The qualifiers are already in Chado so it's easy to add them to the website.  Could you let me know how you'd like them displayed.

The syntax for the qualifiers is a bit variable.  Do you think we should standardise?

**Comment by kimrutherford** [comment]
> The qualifiers are already in Chado so it's easy to add them to the website.

I added them in a column to see if that would work.  Here's an example: https://www.pombase.org/gene/SPAC22A12.08c

**Comment by kimrutherford** [comment]
> so we could put a flag on the ortholog section of the web pages.

Reading this again I think I misunderstood things.  I went ahead and added the ortholog qualifiers to the table but that's not what you meant?  What do you mean by flag?  Let's sort this out on Zoom.  :-)

**Comment by ValWood** [comment]
I did mean a qualifier and not a flag, so you interpreted correctly.
I think this is fine, it makes it clearer that the orthologous relation is different.
The only minor change I would make is to supply the pombe primary gene name rather than systematic ID, then it will be clear to users (because that is the page they are on). Unfortunately, that is probably a pain because it is better to keep the SGD IDs here as 'systematic' IDs.

We can chat about itt.

**Comment by ValWood** [comment]
We can put this to the bottm of things to discuss this today, it isn't urgent..

**Comment by kimrutherford** [comment]
We had a chat about this and I think we're done for now?

We mostly talked about #486 instead.

**Comment by ValWood** [comment]
I will close this, but at some point I'll open a new ticket about migrating the S. cerevisiae orthologs out of Artemis so we can just maintain in a table.  So in that case we will need a table with columns to represent fusions . But for now we are good.
