### ISSUE TITLE
Website issues cdc15 page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1866]
Hi Kim,

We noticed a number of issues with the website today. Not urgent to look at until you feel better.

The cdc15 page appears to be broken, att least, some links no longer work.
Specifically the GO term link to 
cytoskeletal protein-membrane anchor activity](https://www.pombase.org/term/GO:0106006)
Takes you to a page with just  the header and the footer

Lots of errors in the console:
core.mjs:6485 ERROR TypeError: Cannot read properties of undefined (reading 'name')
    at I.ngOnInit (gene-link.component.ts:54:19)
    at Pt (core.mjs:2542:22)
    at ot (core.mjs:2511:17)
    at ge (core.mjs:2462:9)
    at Va (core.mjs:8405:17)
    at Object.V6 (core.mjs:8388:5)
    at ei (extension-display.component.html:64:13)
    at Ra (core.mjs:9618:9)
    at q4 (core.mjs:9484:13)
    at jl (core.mjs:10609:17)

Also some of the menu bar does not work (all items below"single locus phenotype")

And down a the bottom of the page, sections are missing (every section below transcript details is not populated)
Sequence and External references session headers are present, but empty.

Most pages seem to be OK but the issues were noticed on another page too. I will try to remember the page...

**Comment by ValWood** [comment]
This problem seems to have gone away...

CC @manulera

**Comment by kimrutherford** [comment]
> This problem seems to have gone away...

I fixed the problem just after you reported it.

Sorry about the bug.  I slightly broke things when I made the changes for pombase/website#1710
