### ISSUE TITLE
"slim with" menu option for phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1868]
This should probably say "Phenotype slim" to be consistent with other items and the front page links?

<img width="719" alt="Screenshot 2022-04-13 at 23 48 14" src="https://user-images.githubusercontent.com/7359272/163323779-1c55b7d2-a7f4-4343-9b48-c126ca366360.png">

**Comment by kimrutherford** [comment]
I've made the change in the config file.  It will change a few other places around the site like the "This term is part of the FYPO slim" here: https://www.pombase.org/term/FYPO:0002114

It will be visible in the morning.
