### ISSUE TITLE
news item draft

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1869]
I drafted 2 news items, for the slim, and the filter option (or could be combined- I though it might not look such a bit block if split because it's quite a lot of words?)
once the menu is changed I will try a tweetorial ;)

New phenotype slim 
We have added a phenotype slim overview to complement those provided for disease biological process, molecular function and cellular component annotation. The purpose of the phenotype slim is to provide subsets of commonly used 'broad' phenotypic classes or annotation subsets that can provide a useful starting point for accessing phenotype lists.  The phenotype slim page provides links to ontology term pages, annotated genes, and to download files containing the slim terms and IDs.

New phenotype slimming option for advanced search results
The phenotype slim option has also been added to the PomBase advanced search results panel [Slim with:] option. For example, you can query for all genes involved in a GO process, another phenotype, or any other list, and  'slim' the results using the "Phenotype slim option" to view categories of phenotypes assigned to the list.

**Comment by ValWood** [comment]
edited a bit.

**Comment by kimrutherford** [comment]
I've added the news items.  They'll be on the main site in the morning.  I can make the live sooner if you like.

For now they're here for proof-reading: https://desktop.kmr.nz/

If you'd like to tweak the text you can edit them here:
  - https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-04-13-phenotype-slim.md
  - https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-04-14-phenotype-slim-in-search-results.md

**Comment by ValWood** [comment]
Looks great, can we add this link to the slim item?
https://www.pombase.org/browse-curation/fypo-slim

**Comment by ValWood** [comment]
Should we also 
a) link advanced search in

The phenotype slim option has also been added to the PomBase advanced search results panel “Slim with” option. For example, you can query for all genes involved in a GO process, another phenotype, or any other list, and “slim” the results using the “Phenotype slim option” to view categories of phenotypes assigned to the list.

and
b) change 

The phenotype slim (see news item below)  option has also been added to the PomBase advanced search results 

? do you think that would help?

I will do a tweetorrial on Mon/Tues

**Comment by kimrutherford** [comment]
> Looks great, can we add this link to the slim item?
> https://www.pombase.org/browse-curation/fypo-slim

I've done that.

> Should we also
> a) link advanced search in

I've done that too.

> and
> b) change
> The phenotype slim (see news item below) option has also been added to the PomBase advanced search results

I changed "phenotype slim" to be a link to https://www.pombase.org/browse-curation/fypo-slim
Is that OK?

**Comment by ValWood** [comment]
The link helps but it reads a bit oddly without the pointer to the news item below

The phenotype slim  **has also** been added to the PomBase advanced search results

if you read it without reference to the preceding news item. Maybe it should be combined into a single news item?

**Comment by kimrutherford** [comment]
> Maybe it should be combined into a single news item?

That might be the simplest plan.

I've concatenated the text below and I think it sounds OK.  Any edits?  Should the other slims be links in this sentence:
"... provided for disease biological process, molecular function and cellular component ..."?

--------------------------------------------------------------------------

We have added a [phenotype slim overview](https://www.pombase.org/browse-curation/fypo-slim) to complement those provided for disease biological process, molecular function and cellular component annotation. The purpose of the phenotype slim is to provide subsets of commonly used ‘broad’ phenotypic classes or annotation subsets that can provide a useful starting point for accessing phenotype lists. The phenotype slim page provides links to ontology term pages, annotated genes, and to download files containing the slim terms and IDs.

The phenotype slim has also been added to the PomBase [advanced search](https://www.pombase.org/query) results panel “Slim with” menu. For example, you can query for all genes involved in a GO process, another phenotype, or any other list, and “slim” the results using the “Phenotype slim” option to view categories of phenotypes assigned to the list.

**Comment by ValWood** [comment]
sounds good. We could link the other slims. The links are  right there on the front page but  eventually the news item will be in the news archive.

**Comment by ValWood** [comment]
You can also move 2021 new items to the archive. The news is getting quite long...

**Comment by kimrutherford** [comment]
I've combined the news items, turned the other slims into links and removed the 2021 news items.

Let me know if the text needs tweaking.  Or edit directly here: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-04-13-phenotype-slim.md
