### ISSUE TITLE
ideas for phenotype section filters

### ISSUE THREAD

**Issue by ValWood** [pombase/website#187]
I think we should begin with filters on the phenotype section.
We probably don't hugely even need filters on the GO sections, we can be guided by user requests for this, or add later....

Should do something similar to MGI
![filter](https://cloud.githubusercontent.com/assets/7359272/23331439/ff78b496-fb5d-11e6-909f-5ccf04c09a4d.jpg)

For phenotypes filters required would be

1. FYPO term
2. allele type  
3. Expression (or do we combine 2&3?)
4. genotype
5. condition (this one worries me because lots of times this info

For  filters we would have a pop-up (sorry everyone any other way?, could be more of a drop-down?)

![filter2](https://cloud.githubusercontent.com/assets/7359272/23331473/a09e0240-fb5e-11e6-8601-e8f92a9c145f.jpg)
 is absent)

This will show a selection of useful phenotype categories (we have a list and can extend based on user requests). Also  ideally an option at the bottom  with autocomplete for any term?

**Comment by ValWood** [comment]
OK, I found existing ticket which got here from a different starting point. Remarkably consistent final decision to I'll transfer any relevant bits to this new ticket, as there are a few tangents in the old ticket.
https://github.com/pombase/website/issues/93

**Comment by ValWood** [comment]
Suggested phenotype "classes" for "default options"
Lists needs refining but we can gather all suggestions here.
This could be a config file that curators could maintain anyway?
The filter options  should be clever enough to only show classes for which annotation is present...

- normal process, 
- abnormal process
- abolished process
- vegetative phenotype
- meiotic phenotype 
-drug sensitivity 
- morphology phenotype
- altered activity
- altered localization
- altered modification
- cell cycle phenotype
- other specific processes?.....

**Comment by ValWood** [comment]
Also need to think about options for multi gene phenotypes,  allele type  options need some thought. But now we have separate  single/multigene phenotypes we can get it working for single first. "We" ha ha ;)

**Comment by ValWood** [comment]
Kim made a good point in old ticket
> genotype name (to see all of the phenotypes for a particular genotype)
> Is this necessary since you can click on a genotype to go to the genotype details page?

decide

**Comment by ValWood** [comment]
reason why sorting on genotypes is not good is described in this ticket (duplicated terms)
https://github.com/pombase/website/issues/93

**Comment by ValWood** [comment]
can discuss this on call tomorrow. Anything to add anyone?

**Comment by ValWood** [comment]
Test to code up:
filter for allele type.
wild type
deletions
everything but deletions

**Comment by ValWood** [comment]
Very simple filter by category for phenotypes., based on list above

**Comment by ValWood** [comment]
create a config file for curators to  make the list

**Comment by ValWood** [comment]
curators to make basic list of
ID term name

**Comment by ValWood** [comment]
Midori: have all the filter options available, but grey out the ones which do not have annotation on the page

**Comment by kimrutherford** [comment]
> create a config file for curators to make the list

If someone could make a list of IDs and descriptions I'll plug them into the config file.  The list doesn't need to be complete, I just need some examples for testing.

The config file is: pombe-embl/website/pombase_v2_config.json

**Comment by kimrutherford** [comment]
I've added a wiki page about the [Config file](../wiki/Config-file).  There's not much there yet except a short description of configuring a term ancestor filter.

**Comment by kimrutherford** [comment]
I added a _very_ basic term ancestor filter to get the filtering system in place.  It seems to work.  I have configured three random terms so my testing is very incomplete.  The code is live but not useful until we've configured it better.  I'm happy to do that if you can add terms and the category descriptions (like "normal process") as a comment here.

**Comment by ValWood** [comment]
Wow that's a great start. We'll plug some terms in.

One thing I noticed is that the filter is "sticky", so if you change pages and you have filtered, you  see no phenotype annotations on subsequent pages.

**Comment by ValWood** [comment]
I'm not totally sure that it is working properly as yet. I expected "cell phenotype" to retain most things, but it keeps very little for cdc2?

**Comment by ValWood** [comment]
ignore previous...

**Comment by kimrutherford** [comment]
> One thing I noticed is that the filter is "sticky"

I've just made an update that should fix that.

**Comment by ValWood** [comment]
I'm doing a list next. That will allow us to evaluate better..

**Comment by ValWood** [comment]
OK here is my starting list. Based on previous suggestions. This looks pretty good as they all apply to many (often most) gene products, so they will be useful on most pages, which is what we want....

FYPO:0000257 normal phenotype (1767)
FYPO:0001985 abnormal phenotype  (3507)
FYPO:0001320 vegetative cell phenotype  (4814)
FYPO:0002683 sensitive to chemical (1831)
FYPO:0005447 abnormal biological process  (2968)
FYPO:0000005 abnormal cell morphology   (1662)
FYPO:0000631 cell cycle phenotype   (1106)
FYPO:0000138 localization phenotype (698)
FYPO:0000004 - cell viability (4780)
FYPO:0002057 - cell population viability (4945)
FYPO:0000707 - abnormal molecular function (522)

I would have liked to include an "abnormal meiotic phenotype", will need to speak to Midori about that...

**Comment by ValWood** [comment]
Exciting...!

**Comment by kimrutherford** [comment]
I've added those terms.  It seems to work in the cases I've checked.

**Comment by kimrutherford** [comment]
I had a look at a big page:
  http://pombase2.bioinformatics.nz/reference/PMID%3A23697806

The page is slow to load but the filtering is quick.

**Comment by ValWood** [comment]
Can you add a clear way to deselect the filter? (i.e category "no filter")

**Comment by ValWood** [comment]
on this page, if I filter on abnormal morphology I should still see
inviable elongated vegetative cell
inviable normal volume spheroid vegetative cell
inviable small tapered vegetative cell
inviable spore with abnormal shape
inviable swollen curved vegetative cell
etc,

Its not all bad though...the 3 terms I do see ARE morphology terms. I guess it is to do with relationships?

**Comment by ValWood** [comment]
As far as I can tell, the results presented are correct, but some are missing.

**Comment by kimrutherford** [comment]
> Can you add a clear way to deselect the filter?

I've changed "Select a category" to "No filter".

> Its not all bad though...the 3 terms I do see ARE morphology terms. I guess it is to do with relationships?

Currently it's using is_a and part_of relationship for looking for descendants.

> but some are missing.

Can you give me an example of something missing?

**Comment by kimrutherford** [comment]
> Can you give me an example of something missing?

I checked your examples.  I think adding has_part will help.  I'll do that now.

**Comment by ValWood** [comment]
yes that makes sense!

**Comment by ValWood** [comment]
- [ ] next grey out filter options with no terms.

**Comment by kimrutherford** [comment]
> I think adding has_part will help.

That's done now.

**Comment by ValWood** [comment]
very nice. I think that's all working!

**Comment by mah11** [comment]
> I would have liked to include an "abnormal meiotic phenotype"

see whether "abnormal meiotic cell cycle" FYPO:0000052 covers what you want

**Comment by ValWood** [comment]
hmm, thats a can of worms. Lets ignore that for now...we can be "user lead" for additional filters...

**Comment by Antonialock** [comment]
This is awesome, so quick.  thumbs up!

**Comment by kimrutherford** [comment]
> next grey out filter options with no terms.

Done!  You might need to shift-reload.

**Comment by kimrutherford** [comment]
For evidence filtering, should the drop-down just have all possible evidence types (with those with no annotations greyed out)?  Or should it just have the ones that are actually in the table?

Or would you like some higher level categories like the ones here?:
  http://geneontology.org/page/guide-go-evidence-codes

-  Experimental Evidence 
-  Computational Analysis Evidence
-  Author Statement Evidence

(etc.)

**Comment by ValWood** [comment]
We'll have a separate ticket for each aspect of filtering, because I suspect each could generate quite a bit of "curator discussion", so I opened one for the "evidence" filters.

**Comment by ValWood** [comment]
For this filter the cdc2 single allele cellular phenotypes is greyed out for "cell cycle phenotype"

**Comment by ValWood** [comment]
...and morphology

**Comment by ValWood** [comment]
wierdly its working here:
http://pombase2.aska.gen.nz/gene/SPAC11E3.03

**Comment by kimrutherford** [comment]
> For this filter the cdc2 single allele cellular phenotypes is greyed out for "cell cycle phenotype"

I think I've fixed that.  It wasn't resetting what was greyed-out when you move to another page.

**Comment by ValWood** [comment]
yep, works for me.
