### ISSUE TITLE
Replace current Google Analytics with new Google Analytics

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1870]
This hopefully will only take an hour or two but what a pain:
https://support.google.com/analytics/answer/11583528?hl=en

Deadline is the end of June (2023).

**Comment by ValWood** [comment]
yes I saw that. very short notice really.....

**Comment by kimrutherford** [comment]
> Deadline is the end of June.

This issue is my priority for Monday.

**Comment by kimrutherford** [comment]
> This issue is my priority for Monday.

Good news!  We misread it (or maybe they changed the date).  We have until July 1, 2023 so I can ignore this for a bit longer.

https://support.google.com/analytics/answer/11583528

**Comment by ValWood** [comment]
Will we need to set up Analytics for pombeMine or will Intermine take care of that? If we need t set it up maybe do both together? (It would PomBbeminAnalytics e good to have the analysis before we announce it. I will be very curious to see user numbers)

**Comment by kimrutherford** [comment]
They'll need to handle that.  Maybe they have some analytics system already but if so it was after my time.

**Comment by kimrutherford** [comment]
I'll following this issue about it: https://github.com/angulartics/angulartics2/issues/411

That's the library we use to interact with Analytics.

**Comment by kimrutherford** [comment]
It looks like the analytics will be automatically migrated to the new system:
https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article

I approve!  :+1:

**Comment by ValWood** [comment]
I assume it's much better?

**Comment by kimrutherford** [comment]
> I assume it's much better?

Maybe, we'll have to see.

**Comment by kimrutherford** [comment]
Hi Val.  I've made an attempt at setting up the new analytics thing.  I don't know if it's working OK but there is activity.  I don't know if you'll be able to access this: https://analytics.google.com/analytics/web/#/p356604550/reports/reportinghub?params=_u..nav%3Dmaui

![image](https://user-images.githubusercontent.com/90474/223099391-b4a195cc-25c4-4ffe-af0a-06b992b80569.png)

**Comment by ValWood** [comment]
I can!

**Comment by kimrutherford** [comment]
It's quite different from the old version.  I haven't been able to find everything I used to look at.

**Comment by ValWood** [comment]
yup.

**Comment by kimrutherford** [comment]
The new Google Analytics is now active for JaponicusDB too.  Could you try this URL?: https://analytics.google.com/analytics/web/#/p357147151/realtime/overview?params=_u..nav%3Dmaui

**Comment by kimrutherford** [comment]
And for Canto: https://analytics.google.com/analytics/web/#/p357161322/realtime/overview?params=_u..nav%3Dmaui

**Comment by ValWood** [comment]
Yes that works too.
So currently it only shows the data since the setup. will it eventually show all the legacy analytics from the old site?

**Comment by kimrutherford** [comment]
> will it eventually show all the legacy analytics from the old site?

I don't think so: https://www.gtechme.com/insights/migrating-to-ga4-how-to-save-your-historical-data/#Google-Analytics-Historical-Data

**Comment by kimrutherford** [comment]
> That's a bit poor....

I agree.  The old analytics and data will be available for at least 6 months according to their docs.  But I'd rather it didn't go away.

I've exported some of the data to a directory is Dropbox:
`Dropbox/pombase/old_google_analytics`

**Comment by ValWood** [comment]
Wow that is a big problem for resources to monitor usage over time!

**Comment by kimrutherford** [comment]
I'm going to call this done.  We can open new issues as needed.
