### ISSUE TITLE
Add link-outs for CHEBI and CL terms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1875]
Examples:

https://www.pombase.org/gene/SPCC18B5.01c
should have an external link for CHEBI:48080

https://www.pombase.org/gene/SPAC1296.03c
should have an external link for CL:0002674

**Comment by kimrutherford** [comment]
I went ahead and implemented that.

All CHEBI and CL terms are now external links.  It's configurable so we can add others when needed.

At the moment the only other CV I could find in the extensions that might make sense as external links is PATO.  There aren't many examples:
https://www.pombase.org/term/FYPO:0000741

But the go-xrefs files doesn't provide a URL template for linking to PATO terms so it will need to stay as is.

**Comment by ValWood** [comment]
I think we do eventually want pages for terms in extensions:
https://github.com/pombase/website/issues/473
(at least for CHEBI, SO and phase terms)

I don't think it is worth linking to PATO for this edge case. I don't think anybody needs an explainer for 'colour'
