### ISSUE TITLE
report to fix links into PomBase

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1876]
@kimrutherford  and I recently had a discussion for the possible explanation for why we have slipped down the Google ranking when we search with PomBAse systematic IDs. Many less used (not updated) resources 9like PINT) come higher.

Kim wondered if this might be something to do with 'link-ins' to PomBAse using the old linking format.

I will contact resources and ask them to update. Is it possible to get a link of the resources that use the old linking format?

(the e-mail thread is "google indexing"

**Comment by kimrutherford** [comment]
> Kim wondered if this might be something to do with 'link-ins' to PomBAse using the old linking format.

I can't guarantee that it makes a difference.  We redirect to the correct pages which you'd hope would be enough for Google.

Here's what I found in the logs where the URL was www.pombase.org/spombe/result/...:
 - AnGeLi
 - https://yeast.nig.ac.jp/yeast/fy/CdnaAllItemsList.xhtml
 - https://epd.epfl.ch/cgi-bin/get_doc?db=spEpdNew&format=genome&entry=SPBC36B7.08c_1
 - http://pantherdb.org/genes/gene.do?acc=SCHPO%7CPomBase%3DSPAC1002.16c%7CUniProtKB%3DQ9US44
 - http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/Summary?g=SPAC15E1.10;r=I:3732274-3733363;t=SPAC15E1.10.1;db=core
 - https://dnaconda.riken.jp/search/SPD_pombe/Sp03/Sp03F11.html
 - https://www.uniprot.org/uniprot/P10651
 - https://www.ontobee.org/search?ontology=&keywords=HBA1&submit=Search+terms
 - https://www.genome.jp/dbget-bin/www_bget?spo:SPAC1F7.04
 - https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl  (when pombe appears in a results table)
 - http://www.candidagenome.org/cgi-bin/locus.pl?dbid=CAL0000195855

Sites that appear to be dead but were in the logs with the old format:
 - http://pombe.kaist.ac.kr
 - www.aspergillusgenome.org
 - www.aspgd.org

**Comment by ValWood** [comment]
I did the ones I know for now.
