### ISSUE TITLE
small text change in documentation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1877]
On page
https://www.pombase.org/documentation/orthologs

existing text
The second subsection provides links to several resources that predict orthologs in all fungi or all species (PomBase cannot manually curate orthologs in species other than budding yeast and human).

we can but we don't: edit to 

The second subsection provides links to several resources that predict orthologs in all fungi or all species (PomBase **does not** manually curate orthologs in species other than budding yeast and human).

**Comment by kimrutherford** [comment]
I've made that change for tonight's update.

The page is here if you'd like to make further changes:
https://github.com/pombase/website/blob/master/src/docs/documentation/orthologs.md

Just click the edit icon.
