### ISSUE TITLE
news item: next pombe talks

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1878]
Here is the announcement. Pls add news item in the usual format:

Join us Wednesday, May 18th for the first pombeTalks session of the year at 08:00 San Francisco / 11:00 New York / 16:00 London / 17:00 Paris / 20:30 Delhi / 23:00 Beijing / 00:00 Tokyo
We’ll have two exciting talks lined-up to start this season:
Jennifer Porat, Bayfield Lab, York University
“The methyl phosphate capping enzyme Bmc1/Bin3 is a stable component of the fission yeast telomerase holoenzyme”
Ingrid Billault-Chaumartin, Martin Lab, UNIL
“Fus1, the fusion focus formin”

**Comment by kimrutherford** [comment]
That's done for the morning.

**Comment by kimrutherford** [comment]
If you need to tweak the text, it's here: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-05-05-pombetalks-may18-2022.md

**Comment by kimrutherford** [comment]
If you need to tweak the text, it's here: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-05-05-pombetalks-may18-2022.md
