### ISSUE TITLE
Small update to query  builder "commonly  used queries" list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1879]
Follow up https://github.com/pombase/website/issues/1871

Here 
"priority unstudied genes" refers to
https://www.pombase.org/status/priority-unstudied-genes
 "and a significant number of these (133) have orthologs in vertebrates. These genes are listed below"

so we should make this clearer:

"Priority unstudied proteins (vertebrate orthologs, unknown process, protein coding)"
or is that a bit long? I just feel we should qualify exactly what the list is.

also could we put 
Priority unstudied genes (vertebrate orthologs, unknown process, protein coding)
and
Protein coding genes, unknown process
together in the list

**Comment by ValWood** [comment]
<img width="430" alt="Screenshot 2022-05-13 at 06 14 50" src="https://user-images.githubusercontent.com/7359272/168291004-19fbb507-a35a-4a00-90fc-8c5143a47c8b.png">

**Comment by kimrutherford** [comment]
> "Priority unstudied proteins (vertebrate orthologs, unknown process, protein coding)"
> or is that a bit long?

I don't think that's too long.

> also could we put
> Priority unstudied genes (vertebrate orthologs, unknown process, protein coding)
> and
> Protein coding genes, unknown process
> together in the list

Yep.  Which one should move?

**Comment by ValWood** [comment]
I think they can both go at the bottom of the list.

**Comment by kimrutherford** [comment]
> I think they can both go at the bottom of the list.

That's done now.

You suggested this wording change.  Should I go ahead with that?
> Priority unstudied proteins (vertebrate orthologs, unknown process, protein coding)

**Comment by ValWood** [comment]
Yes go with that,

**Comment by kimrutherford** [comment]
All done.
