### ISSUE TITLE
publication page oddity PMID:16823372

### ISSUE THREAD

**Issue by ValWood** [pombase/website#188]
reference/PMID%3A16823372

When I ask  "show details" for warnings I get this:

![16823372](https://cloud.githubusercontent.com/assets/7359272/23333581/87aa5172-fb85-11e6-82b2-fc7d751c14dc.jpg)

(fewer details ;)

**Comment by ValWood** [comment]
Also the show details does not work for the components on this page (it would be huge, 1000s)

**Comment by kimrutherford** [comment]
> When I ask "show details" for warnings I get this:

Fixed.

> Also the show details does not work for the components on this page (it would be huge, 1000s)

It works eventually.

**Comment by ValWood** [comment]
O.K. ! The main problem was the fixed one. Nothing is slow compared to anything I'm used to ;)
