### ISSUE TITLE
Changes of gene structures

### ISSUE THREAD

**Issue by manulera** [pombase/website#1886]
Hello,

Here some changes in gene structures following exchange with author of Porat et al. 2022:

snu6
old coords: complement(join(2562276..2562323,2562374..2562427))
new coords: complement(join(2562276..2562323,2562374..2562419))

snu4
old coords: complement(467233..467361)
new coords: complement(467489..467615)     

I have added them to the artemis file, but Val told me to put it here to add the warnings to the website. If you point me to the changes in the next commit when you add the warning, I can do it myself next time.

**Comment by kimrutherford** [comment]
Hi Manuel.

The file is here I think: https://github.com/pombase/curation/blob/master/data_files/gene-coordinate-change-data.tsv

I've never edited it before so maybe it's best if you try?

That file is included in the web site documentation Markdown files here:
https://github.com/pombase/website/blob/master/src/docs/status/gene-coordinate-changes.PomBase.md

The "%%table file=..." directive is not standard Markdown, we invented it.

**Comment by manulera** [comment]
Fixed in 5cd55768532e835703121ba5629f6e938e4f4559
