### ISSUE TITLE
Allow sending of  MF targets and target of lists to the query builder

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1887]
This ticket has 2 parts.

1. Allow the export of "target of" section (i.e upstream genes for any gene) to the Advanced search (with a checkbox to include GO only/ or GO and FYPO)
2.  Allow the export from the  Molecular Function table  "has_input" (i.e downstream genes/proteins for any gene/protein ) to the Advanced search
(also allow  export to work on filtered subsets  (i.e. on phases, like M-phase or Interphase subset). Use only activities, ignore "binds.
also for now we will just export every target even if the  terms  and relations are slightly different.
Good use cases are for cdc2 kinase substrates
https://www.pombase.org/gene/SPBC11B10.09

Less important but might be useful

3. ~Allow export  from the FYPO single gene annotation table of gene protein entities as extensions of FYPO annotations~
4. ~Same for GO process annotation table  has_input~

**Comment by kimrutherford** [comment]
Would you like to be able to similar query in the phenotype section for "affecting", "affecting activity of" or "affecting substrate" or other relations?

What about for BP?  For example, would you want to query the genes the are annotated as regulated by your current gene?

Would it be helpful to be able to get different lists out, like genes phosphorylated by the current gene versus substrates of the current gene?  Or do you just need all the target genes in one list?

(Sorry I don't understand the biology around all this)

**Comment by ValWood** [comment]
I  guess it wouldn't hurt. Although they are a bit more of a mixture, and probably not as useful).

**Comment by kimrutherford** [comment]
Should all the genes be grouped together or would you like to be able to query using the relations?  So for example would you ever want to get just the genes phosphorylated by the current gene, rather than all genes for all relations?  Some MF sections contain a variety of relations.

**Comment by ValWood** [comment]
> Some MF sections contain a variety of relations.

 I think when they have different relations  the  entity is not a gene
except, occasionally (Like for some phosphatases the entries are a mix of 'has_substrate' and 'dephosphorylates' (I I have been meaning to track this down) OR they have the 'directly_negatively_regulates' poor 'directly_positively_rregulates' relation. (which would still be phosphorylates or dephosphorylates and we would want them in the same bin).

Did you notice any examples that were not like this?

**Comment by ValWood** [comment]
Hmm, 
https://www.pombase.org/gene/SPBC32C12.02

This transcription factor  2 functions annotated (repressor and activator) with different targets.

**Comment by kimrutherford** [comment]
I don't know if this is the sort of case you were thinking of: https://www.pombase.org/gene/SPCC1259.13
There aren't many genes involved so it's not really a problem for that one.

Some other example with more than one relation:
https://www.pombase.org/gene/SPAC1782.09c
https://www.pombase.org/gene/SPAC24B11.06c
https://www.pombase.org/gene/SPAC1783.07c
https://www.pombase.org/gene/SPBC1604.14c

There aren't that many gene pages where there are going to be long list of genes so it's probably not a problem.

**Comment by kimrutherford** [comment]
Sorry for all the questions.  This is not a high priority issue!

Is a link to get the target genes (or anything else) on the term pages any use?

For example on this page is there any value in being able to get a list of genes that are anchored?:
https://www.pombase.org/term/GO:0106006

Or a list of genes that can be phosphorylated from here?:
https://www.pombase.org/term/GO:0004672

We can discuss all this after things are quieter.

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAC1782.09c
in this case 
dephosphorylates
has substrate
directly inhibits
all mean "dephosphorylates"

HAs substrate needs to display as "dephosphorylates" I need to check the config file for this. I don't know why it is sometimes has_input and sometimes dephosphorylates.

The relationship config is more complicated than when I  first set it up so perhaps we could all have a look next week. 

directly inhibits  can be assumed to be the same as whatever the 'default relation' is. It is a temporary cludge to capture  negative relation between genes.

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAC1783.07c
is a bit awkward, but I think for now we can say that export the entire set that is not filtered for some reason.
People will have to do due diligence on the meaning of that (and the filters will probably allow separation)

**Comment by kimrutherford** [comment]
> I don't know why it is sometimes has_input and sometimes dephosphorylates.

They have different relations in the extensions:

 - has substrate = has_direct_input
 - dephosphorylates = has_input
 - directly inhibits = directly_negatively_regulates

The labels in the display can be configured but it's slightly tricky: https://github.com/pombase/website/wiki/Config-file#extension_display_names

**Comment by ValWood** [comment]
> Sorry for all the questions. This is not a high priority issue!
exciting though. I have wanted to do this for ages but I didn't want t side-track you ;) I have wanted to do this a  lot.

I think the term export will often not be useful, but sometimes it will be so we should allow it. Users should be able to figure if it makes sense biologically. For instance this could be useful to find all of the known
proteasome targets which are usually. identified by many genetic experiments involving adaptors and ligases but not the proteasome itself.
https://www.pombase.org/term/GO:0043161
I can think of quite a few use cases.

**Comment by ValWood** [comment]
has_direct_input is a legacy relation. We used to use it for GO MF, but it was decided that ALL inputs on MY were direct and we did not need to distinguish has_input and has_direct input.
Can we do a global replace of has_direct_input with has_input (anywhere that we have used it). That will get rid of quite a lot of differences in the summaries and make everything collapse better.
(for some reason I thought we had done this, but perhaps we just replace has_direct_input with has_input in the GO export?)

**Comment by kimrutherford** [comment]
> (for some reason I thought we had done this, but perhaps we just replace has_direct_input with has_input in the GO export?)

We do that replacement for the file we send to GO:
  https://curation.pombase.org/dumps/latest_build/misc/go_style_gaf.tsv

But we keep them in the PomBase GAF:
  https://curation.pombase.org/dumps/latest_build/misc/pombase_style_gaf.tsv

**Comment by kimrutherford** [comment]
> Users should be able to figure if it makes sense biologically.

So it is OK to lump all the genes together, whatever the relation?

Like in this case?: https://www.pombase.org/gene/SPAC1783.07c
should the gene from "recruits atf1" be included with the "activates transcription of" genes in the query output?

Or your example: https://www.pombase.org/gene/SPBC32C12.02

**Comment by ValWood** [comment]
Tricky. In this particular case it does not makes sense. 

We could export by MF term, but in cases like
https://www.pombase.org/gene/SPBC11B10.09
- all of the MF are in the same branch, we would not want to split (I wish some of these terms did not exist, like cyclin-dependent)

OR, we could  say which labels should go together (using our display labels). I could provide a configuration which  relations labels could be co-exported)

Which is easiest?
I think we will regret it if we don't allow to split.

**Comment by kimrutherford** [comment]
> Which is easiest?

I'm not sure.

I thought this would be a quick issue.  But since it requires a bit of thought and a chat I'm going to leave it for now.

**Comment by kimrutherford** [comment]
Note to self: the in-progress code is on local branch `target-of-query-website-1887`

**Comment by ValWood** [comment]
Is this a duplicate?   The other ticket probably doesn't cover the target_of section so I'll keep this open.

**Comment by kimrutherford** [comment]
> 2.  Allow the export from the  Molecular Function table  "has_input"

That's done, more or less: pombase/website#1300

**Comment by kimrutherford** [comment]
> Allow the export of "target of" section (i.e upstream genes for any gene) to the Advanced search (with a checkbox to include GO only/ or GO and FYPO)

I have a prototype running on [my desktop](https://desktop.kmr.nz/gene/SPCC18B5.03) - no checkboxes yet.  Can we discuss this on the next call?

![image](https://github.com/pombase/website/assets/90474/00c5de8d-2a30-4c4b-9c8c-f325309c66e1)

**Comment by kimrutherford** [comment]
New, improved version will be on the main site tomorrow morning:

![image](https://github.com/pombase/website/assets/90474/2a9821a0-9ced-4635-bbf5-cf091855bd62)

**Comment by kimrutherford** [comment]
> I suspect that the hierarchy is not being used for during fiters 

You're right.  I'll fix that.

**Comment by ValWood** [comment]
noite to self: announce when this is fixed

**Comment by kimrutherford** [comment]
> I suspect that the hierarchy is not being used for during fiters

Fixed!

The links to the query builder in the target of section are fixed too.

**Comment by kimrutherford** [comment]
I think this is done.
