### ISSUE TITLE
Gene Deletion Viability: Depends on conditions

### ISSUE THREAD

**Issue by manulera** [pombase/website#1888]
How do you indicate `Gene Deletion Viability: Depends on conditions` ? I would need that for last Goshima's paper with plo1.

![Screenshot 2022-05-25 at 15 41 35](https://user-images.githubusercontent.com/22526102/170289570-3b763ed5-56f1-4eef-bd7f-250218c0d9c5.png)

**Comment by ValWood** [comment]
That label happens automatically if there are viable and inviable population phenotypes.

**Comment by manulera** [comment]
ok! 

* [ ] Double check pol1 when the paper goes live

**Comment by ValWood** [comment]
Changed to vegetative terms

**Comment by kimrutherford** [comment]
plo1 is now:

```
Gene Deletion Viability: Depends on conditions 
```
