### ISSUE TITLE
filtering molecular function number query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1890]
When I filter cdc2 from "kinase" to "protein kinase"
the number of  displayed "associations" drops from 237 to 235.
I can't figure why, because they are all protein kinase terms?

**Comment by kimrutherford** [comment]
Hi Val.  That's fixed now.  There was a bug in the filtering code: it was including the descendant terms in the filter but not the term itself.  There are two annotations directly to "protein kinase activity" that weren't being included in the filtered annotations.

If I had a top ten list of bugs I cause, I think this one (only matching descendants) would number one.

**Comment by ValWood** [comment]
I like your consistency ;)

**Comment by kimrutherford** [comment]
> I like your consistency

I think it's because dealing with descendants is the trickier case, so I work on that first.  Then I forget about the easy case.
