### ISSUE TITLE
information icon for deletion visability?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1898]
Should we add an information icon next to the "viability" header.

Details of individual viability phenotypes  and conditions are in the "population phenotype" section below.

<img width="424" alt="Screenshot 2022-06-11 at 11 22 43" src="https://user-images.githubusercontent.com/7359272/173241262-1ad02848-3fd0-4a1f-86e6-b43be7897e1c.png">

@kimrutherford 
@manulera

**Comment by ValWood** [comment]
Yep, it occurred to me that people might not realise that the information was curated in detail below.
It probably doesn't help that the phenotype ontology called, more precisely "inviable population" , but users will probably look for "lethal"

**Comment by kimrutherford** [comment]
Is this what you were thinking of?:

![image](https://user-images.githubusercontent.com/90474/189277632-c002a303-42c8-4eeb-b570-2d5bbe0a076f.png)

**Comment by ValWood** [comment]
Yes, perfect.
