### ISSUE TITLE
need a pointer to the GO bulk submission format

### ISSUE THREAD

**Issue by ValWood** [pombase/website#19]
(our simplified version)

under "submit data"
and
in the FAQ

**Comment by mah11** [comment]
Do we even have one? I don't have any record of us devising a simplified format, nor do I recall accepting any GAF or GPAD submissions before now.

Can the Chado loader accommodate submitted GAFs? If so, it'll be straightforward enough to document.

**Comment by ValWood** [comment]
Yep, its a GAF. 

 We use them  for external datasets
pombe-embl/external_data/external-go-data
(Orfeome data and old NAS mappings)

PAINT and GOA data are also loaded into Chado from GAFs. So if  there are any HTP datasets we can easily accommodate them in GAF format...
