### ISSUE TITLE
Display of genes &extensions on GO term pages and publication pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#190]
http://pombase2.aska.gen.nz/term/GO%3A0004693

at present we don't know which gene these apply to in the summary view.
We only see the gene when we go to the "detail view"

So, we need to see "gene" in summary view too.

**Comment by kimrutherford** [comment]
Is this the same issue as #184?

**Comment by ValWood** [comment]
Actually it is a bit odd, because at the moment you don't know which gene the extensions apply to?

It needs to be

protein serine/threonine kinase activity
clp1, plo1 etc
cdc2, has substrate orc2 involved in negative regulation of mitotic DNA replication initiation during mitotic G2 phase
cdc2 has substrate cut7 , srw1 , sds23 , crb2
cdc2 has substrate clp1 involved in negative regulation of protein serine/threonine cdc2 se A

The gene needs to be connected to the substrate, if there are no substrates it can be listed at the top.

(maybe in this view we should include only substrates but exclude part of links? )

kim: would this be clearer?
protein serine/threonine kinase activity
    cdc2, abc1, any1
        has substrate cut7
   any2, wee1, ...
        (other extension ...)

Val: more
cdc2 has substrate cut7
abc1 has substrate cut7
any1 has substrate cut7

**Comment by ValWood** [comment]
outstanding transferred from
https://github.com/pombase/website/issues/168

**Comment by ValWood** [comment]
This also applies to publication pages as well as term pages.


Kim commented https://github.com/pombase/website/issues/184
Some pages are going to be quite long.
eg. http://pombase2.bioinformatics.nz/term/FYPO%3A0002060

it is long, but it is shorter than the page it replaces!
http://www.pombase.org/spombe/related/FYPO:0002060

Although for this  particular term, I'm not sure how useful the page is, I think we will just have this case sometimes, and it is unlikely that people will use this page for anything other than sending  a list to the query tool...

Maybe  in the summary view we do want to limit the gene  list length
(say to 100).

This will look even crazier when we use "genotypes" instead of genes!

**Comment by ValWood** [comment]
@mah11 @Antonialock  could you  give your thoughts tomorrow....will discuss Tues morning...

**Comment by ValWood** [comment]
- [ ] Implement display of genes and  extensions in summary view on GO term pages

**Comment by ValWood** [comment]
well that's how it is now, so closing
