### ISSUE TITLE
new news item and rotating  "explore" feature

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1901]
News item
========
77 new disease associations.

We have added 77 new disease-gene associations for 71 fission yeast human gene orthologs. These were identified using "PombeMIne" to identify the disease genes curated by OMIM  not annotated with an existing Mondo mapping. The number of human disease gene associations is currently 1475.  Disease genes can be browsed via the disease slim  set https://www.pombase.org/browse-curation/disease-slim 
or from the Mondo root node term https://www.pombase.org/term/MONDO:0000001

**Comment by kimrutherford** [comment]
Sorry, I missed this.

Can you suggest a title for the news item?  Is "New disease associations" enough?  Or "77 new disease-gene associations"?

**Comment by kimrutherford** [comment]
> Let's put the number

OK, I'll do that now.

For the Spotlight, is the number for the human orthologs up to date?:

> Browse [Disease associations](https://www.pombase.org/term/MONDO:0000001), annotated using the Mondo disease ontology, for 1471 (up from 1401 in August 2021) of the 3560 S. pombe genes that have human orthologs

I get 3599 from the ortholog query on the website.

**Comment by kimrutherford** [comment]
> Alpha fold orthologs until the paper is published

Is there a pre-print?

I'll add the Spotlight for tonight's load.   I've updated the ortholog count.  I won't publish the news item yet.

**Comment by kimrutherford** [comment]
> but won't be able to announce the Alpha fold orthologs until the paper is published (it is submitted and should not be long).

Should we do a news item now?

**Comment by ValWood** [comment]
We can wait a bit. The paper is still in review, hopefully it shouldn't be long

**Comment by ValWood** [comment]
Actually, this news item is about the disease association increase that used pombemine. That's why it is pending. The ortholog number is a tangent and that difference will be dealt with by the Alpha fold paper. I did not write that announcement yet (I don't think!)

**Comment by ValWood** [comment]
Let's keep the pombeMine front page news item short.

As part of an Elixir funded collaboration with the Intermine http://intermine.org/ team we have created a PombeMine https://www.pombase.org/im/pombemine.  Gene lists can be sent directly from PomBase query results pages directly to Intermine (under the “export” tab), providing direct (2 click) access to GO and phenotype enrichment tools.

so there are 2 new news items here. I edited/hid all of the comments to do with orthlogs, we will announce those when the AlphaFold paper is published. I have another announcement for that.

**Comment by ValWood** [comment]
Could you add these 2 news items and retire the old  "Explore" item and replace with the new one ? Let me know if anything sounds odd, or isn't clear (keep the old one in the archive even though they are similar, I occasionally use them as a reference point).

**Comment by kimrutherford** [comment]
> retire the old "Explore" item and replace with the new one

Which Explore item?  I can only see two news items?

**Comment by ValWood** [comment]
I think we must have updated the "explore" item already. The numbers are close to the actual.

**Comment by ValWood** [comment]
Yep 06-08

**Comment by kimrutherford** [comment]
Could you check the new items here?: https://desktop.kmr.nz/

**Comment by ValWood** [comment]
I don't see it?

**Comment by kimrutherford** [comment]
Do you need shift-reload?

![image](https://user-images.githubusercontent.com/90474/190641710-254bf5d1-d3c3-42e1-a4c4-4828422070a5.png)

**Comment by ValWood** [comment]
Perfect, thanks
