### ISSUE TITLE
Diploid single locus genotypes on the "Haploid single locus genotypes" page 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1904]
I'm surprised we didn't notice this before:
https://www.pombase.org/term_genotypes/FYPO:0000151

The quick fix is to remove the word "Haploid" here:

![image](https://user-images.githubusercontent.com/90474/174734245-327b93d2-a01f-4c85-be96-bc4c3c8354be.png)

Would that be OK?

We don't mention haploid in the link to get to the page:

![image](https://user-images.githubusercontent.com/90474/174734923-5ae781c3-cbf3-4aef-839d-588a64598708.png)

**Comment by ValWood** [comment]
Removing "haploid" works (And is want we want because it is likely all will be diploid)
