### ISSUE TITLE
searching on author

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1906]
When I search on Minc in the simple search, I don't find
https://www.pombase.org/reference/PMID:34666001

I still don't find it even when I add "2021". This usually works. I'm reporting because I thought it was odd

**Comment by kimrutherford** [comment]
It's there, it's just not first in the list.  I'll see if I can tweak the weightings.

![image](https://user-images.githubusercontent.com/90474/176889558-41a02416-9e4b-484b-98cb-a10335371a4d.png)

**Comment by kimrutherford** [comment]
> I'll see if I can tweak the weightings.

It should be better tomorrow.  I'll check then and close the issue.
