### ISSUE TITLE
CI passes with weird path for image

### ISSUE THREAD

**Issue by manulera** [pombase/website#1908]
Hi @kimrutherford, not sure if this is worth addressing, but flagging it just in case.

I added a new image to the spotlight (`spotlight/2022-07-14-Hokuto-Tschimganine.png`).

But in the json config I wrote the wrong path (added wrong leading `/`), as:
```
/spotlight/2022-07-14-Hokuto-Tschimganine.png
instead of
spotlight/2022-07-14-Hokuto-Tschimganine.png
```

This passed the tests, but the image could not be found https://www.pombase.org/spotlight/2022-07-14-Hokuto-Tschimganine.png

I don't think it's a real issue, but just letting know it happenned. Feel free to close. I already fixed it, so it should be ok on the next update.

**Comment by kimrutherford** [comment]
I've added a few more checks for the config file.  So if this happens again there will be a CI error like:
```
"head_image" shouldn't start with "/": /spotlight/2018-01-22-jaspersen-centrosome.png
```
