### ISSUE TITLE
Two different alleles with the same name

### ISSUE THREAD

**Issue by manulera** [pombase/website#1909]
Hi @kimrutherford . Following this warning:

```
warning in 17cceecf86230427: description for new allele "alp7-5A(K341,Y344,R346,K347,Y348)" does not match the existing allele with the same name "alp7-5A(S50A,S51A,T100A,T116A,T131A)" (from session f134593392c70d97)
```

@ValWood has flagged an issue with alleles that have the same name. We have found this example:

* alp7-5A that represents `(S50A, S51A, T100A, T116A, T131A)`
* alp7-5A that represents `(K341,Y344,R346,K347,Y348)`

This caused a problem in the website, and only one of the two alleles was displayed for both publications, even if different alleles could be found in the canto sessions, where annotations were correct.

For now, what I have done is including the modifications in the allele name, renamed to `alp7-5A(S50A, S51A, T100A, T116A, T131A)` and `alp7-5A(K341,Y344,R346,K347,Y348)`. And added the following warning in `allele_comments.txt` in the svn repo:

```
alp7-5A(S50A, S51A, T100A, T116A, T131A)	warning: same name as alp7-5A(K341,Y344,R346,K347,Y348)	PMID:29021344
alp7-5A(K341,Y344,R346,K347,Y348)	warning: same name as alp7-5A(S50A, S51A, T100A, T116A, T131A)	PMID:24790093
```

The "problem" with this is that the alleles will be displayed as `alp7-5A(S50A, S51A, T100A, T116A, T131A)(aaS50A, S51A, T100A, T116A, T131A)` name + description. Since this is rare (probably first occurrence), it might not be urgent, but possible solutions could be:

* Easiest: Make a config file where we list the alleles in which we don't want to display the description after the name in gene pages and others.
* Best long term: unique identifiers for alleles so they can have the same name.
* Probably not great: Allow several alleles to have the same name, and require allele name + description to be unique, instead of having unique names, but that would mean that annotations are made to the combination of both, so I guess not ideal.

**Comment by kimrutherford** [comment]
It may not be possible, but for me it would be best if all alleles have unique names.  It would make my life simpler.  :-)

**Comment by ValWood** [comment]
In this case @manu made the names unique by including  the description in the name.
 
alp7-5A(S50A,S51A,T100A,T116A,T131A)

We will always make allele names (and descriptions) unique.

I think there is only one that is not, according to the logs
https://curation.pombase.org/dumps/latest_build/logs/log.2022-08-16-19-54-08.chado_checks.duplicated_allele_names

but I am. bit baffled by this one?
 cut1-C1730A	SPCC5E4.04:allele-15	C1730A	amino_acid_mutation	310b16bb1a103044,809618c56c11583b
  cut1-C1730A	SPCC5E4.04:allele-26	C1730A	amino_acid_mutation	809618c56c11583b

**Comment by ValWood** [comment]
I think this one can close?
