### ISSUE TITLE
small documentation update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1910]
current
<img width="1057" alt="Screenshot 2022-07-26 at 12 32 33" src="https://user-images.githubusercontent.com/7359272/181032949-be5f3322-505b-416e-89c9-c4f99ce12829.png">

Proposed

Annotations are made to the definition of a term, not the term name itself, so we recommend that users always read the term definition.  The definition is critical because an ontology term name may change over time, but if the _meaning_ of a definition changes the term must be obsoleted, and the associated genes must be reannotated to the correct definition. This procedure makes ontologies very robust to changes in biological knowledge, because if the ~meaning of~ the definition is constant terms can be repositioned in the ontology (i.e. parents terms can be added or removed) without affecting the validity of the annotations that are attached to it.

The definition of a term can be found on the ontology term page linked to the term name and ID.

**Comment by kimrutherford** [comment]
> because if the meaning of the definition is constant terms can ...

I think this could be:
```
because if the definition is constant terms can ...
```

**Comment by kimrutherford** [comment]
That's done now.  If you need to tweak it, it can be edited here:
https://github.com/pombase/website/blob/master/src/docs/documentation/gene-page-gene-ontology.md

**Comment by kimrutherford** [comment]
> it can be edited here:

If you'd like to edit using github.dev (which is like VS Code online), use the menu:
![image](https://user-images.githubusercontent.com/90474/181435680-6b68d8d9-b820-4a11-a6ff-63b502fcb8b2.png)

That gives you highlighting and has some other useful features like showing changes as you edit.  I'm happy to do a demo some time to get you started.

**Comment by ValWood** [comment]
Yes I should do this. I have used the git edit for other config files.
But I like to run these edits by you first ;)

**Comment by kimrutherford** [comment]
> But I like to run these edits by you first ;)

:-)

You can always make the edit and then let me know.  They don't go live until 6pm NZ time so I have plenty of time to have a look.
