### ISSUE TITLE
The genetype page links appear to be broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1913]
I tried some on the rad21 page

https://www.pombase.org/genotype/mis4-C-A-1-191,K873A,K877A-amino_acid_deletion_and_mutation-expression-not_assayed__rad21M-middle%3F-other-expression-not_assayed

**Comment by ValWood** [comment]
It's only multi gene ones

**Comment by kimrutherford** [comment]
It looks like it's only a problem for the genotypes containing the allele "rad21M(middle?)".  I'm guessing the question mark is what's triggering the bug.  I'll fix that tomorrow.  :-)

**Comment by kimrutherford** [comment]
Here are some other examples here: https://www.pombase.org/gene/SPBC30B4.01c

**Comment by ValWood** [comment]
well it shouldn't be there really! DOn't worry about this at the weekend.

**Comment by ValWood** [comment]
I need to chase those up too! on my list...

**Comment by kimrutherford** [comment]
All fixed now.

>  I'm guessing the question mark is what's triggering the bug.

Question marks need special handling in URLs.
