### ISSUE TITLE
clp1 missing a "target of" annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1915]
Clp 1 should have a GO target of annotation for rad24
<img width="1149" alt="_______bug missing rreciprocal" src="https://user-images.githubusercontent.com/7359272/183069024-7ec95d8f-892f-4828-9b90-d5d55e8f2430.png">

so I suspect "protein sequestering" is not in the reciprocal configuration?

rad24
<img width="1067" alt="Screenshot 2022-08-05 at 12 33 11" src="https://user-images.githubusercontent.com/7359272/183069131-88cf70cf-dd4d-453e-9d45-e107207856db.png">

(I am not sure where to do this).

Also we should get a list of all of the relations used with MF so we can check that others are not missing from the config.

Not urgent we can look at this when I get back.

**Comment by kimrutherford** [comment]
> (I am not sure where to do this).

The configuration is here: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L4625

Docs: https://github.com/pombase/website/wiki/Config-file#extension_display_names

Here's a similar issue: https://github.com/pombase/website/issues/1881#issuecomment-1129224745

Let's have a chat when you're back.

**Comment by ValWood** [comment]
It might be the whole file

cds1-FKBP-Cds1cat	dimerization inducible	PB_REF:0000005

is not here
https://www.pombase.org/genotype/cds1-FKBP-Cds1cat-fusion-FKBP:Cds1%28150-460%29-other-expression-not_assayed

**Comment by ValWood** [comment]
right!  We can document on the wiki.

**Comment by ValWood** [comment]
OK next call we should do this. It should be quick, and easy

**Comment by ValWood** [comment]
At the same time we should try to configure more of these "substrstrate of" to nice human readable labels:
<img width="991" alt="Screenshot 2024-01-01 at 14 58 53" src="https://github.com/pombase/website/assets/7359272/b633c737-647a-48a1-88ae-e359d8f4ccd5">

**Comment by kimrutherford** [comment]
> Clp 1 should have a GO target of annotation for rad24

I've fixed that bug.  The missing target of rows will be there in the morning.

> At the same time we should try to configure more of these "substrstrate of" to nice human readable labels:

Still need to work on that.
