### ISSUE TITLE
New advanced search option: "target of"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1917]
From Val:
given list of genes, provide everything that this list is a "target of"

(Needs discussion)

**Comment by kimrutherford** [comment]
I've implemented part of the code to add a target of query.  The rest needs to wait for discussion because I don't understand what's needed.

Some questions I have:
  - is this useful only for GO?  The target of annotation table has FYPO entries too
  - do we want to be able to constrain by relation?  For example substrate of vs phosphorylated by, or is it easier than that?

**Comment by ValWood** [comment]
Let's discuss before you proceed.

**Comment by ValWood** [comment]
also discuss with https://github.com/pombase/website/issues/1887

**Comment by ValWood** [comment]
One problem is  that for a given list, there will be multiple targets per gene.
It probably won't make sense to separate them, so it might need to be only a download option, like 'physical interactions'
or both the ability to get the entire list (i.e to make network), but also to be able to download with the individual regulators...

**Comment by kimrutherford** [comment]
There's also this one:
  - #1917

**Comment by ValWood** [comment]
Closing because we won't do this as a  query. But we  have a ticket for the option to dens the target_of genes  to the advanced search for any individual gene
https://github.com/pombase/website/issues/1887#issuecomment-1830279510
