### ISSUE TITLE
phenotypes should link to genotypes not genes by default

### ISSUE THREAD

**Issue by ValWood** [pombase/website#192]
I think that is what was decided. 

I prefer genes but I guess we need to be consistent between single and multi allele so it needs to be genotypes...

then we will need a basic list with genes and products for all genes contributing to the genotype:

- [ ] need a link to a list of "genotypes with this term" from the phenotype term page

- [ ] multi allele phenotypes (genes) (maybe later if required)
I haven't done this bit yet. The link is there on the phenotype term pages but the list includes all genes for all genotypes annotated with that term. I'm working on fixing that.

 "genes from single-allele genotypes associated with this term"

**Comment by ValWood** [comment]
from
https://github.com/pombase/website/issues/168

**Comment by kimrutherford** [comment]
> phenotypes should link to genotypes not genes by default

So put the genotypes column back in the full details annotation table on the term and publication pages?  And remove the gene column?

> then we will need a basic list with genes and products for all genes contributing to the genotype

Is this the list you mean?:
  http://pombase2.bioinformatics.nz/genotype/addd2b43e02fbb5c-genotype-4

I can add the gene products to that table.

> need a link to a list of "genotypes with this term" from the phenotype term page

I'll add that.

**Comment by kimrutherford** [comment]
> need a link to a list of "genotypes with this term" from the phenotype term page

Should that be the single allele genotypes or all genotypes?

**Comment by ValWood** [comment]
I think we need to discuss this one on Tuesday as a group, because I'm not sure  what others would like, and I'm too biased towards "genes"

**Comment by kimrutherford** [comment]
> Should that be the single allele genotypes or all genotypes?

I've added a link the single allele genotypes because I had that code ready to go.

**Comment by ValWood** [comment]
Wow!. That's helpful.  Now we can see these it will help us to decide the best way to display.

**Comment by ValWood** [comment]
Phenotype term pages, currently show genes list (mixed for multi and single gene)
Need to:
- [ ] Change genes to genotypes
- [ ] Order single gene first, multi later
- [ ]  hide penetrance and expressivity on term page summary view
 later we'll add a filter
 later we'll consider separate tables (after consultation)

**Comment by kimrutherford** [comment]
> Change genes to genotypes

Done.

> Order single gene first, multi later

I've done that but the summary is still a bit messy.  It will improve once the duplicate genotypes are fixed.

>  hide penetrance and expressivity on term page summary view

Done (I think that was fixed by a different issue).

**Comment by kimrutherford** [comment]
> need a link to a list of "genotypes with this term" from the phenotype term page

Isn't that what the phenotype term page is? Like this page?:
  http://pombase2.bioinformatics.nz/term/FYPO%3A0000082

> multi allele phenotypes (genes) (maybe later if required)

Does this need doing?

**Comment by mah11** [comment]
>>  need a link to a list of "genotypes with this term" from the phenotype term page
>
> Isn't that what the phenotype term page is?

I think so, but Val might mean a list of just the genotypes, without the evidence, conditions, etc. from the annotations (and with each genotype listed only once). There is a link for single-allele genotypes but not for multi-allele genotypes.

On the phenotype term page, it would probably be good to list single-allele genotypes first, and then multi-allele genotypes. In the detailed view they could be separate tables if V&A prefer.

>> multi allele phenotypes (genes) (maybe later if required)
> 
> Does this need doing?

To clarify, this refers to adding links for "Multi-allele genotypes associated with this term ..." and "Genes from multi-allele genotypes associated with this term ..." analogous to the existing single-allele links. I'm not sure how important or urgent it is. From Val's comment the multi-allele genotype 
list sounds like a higher priority than the "genes from" list.

**Comment by ValWood** [comment]
Lets open new tickets for outstanding here...
