### ISSUE TITLE
Pfam links to update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1925]
update Pfam links from
https://pfam.xfam.org/family/PF00069
to
https://www.ebi.ac.uk/interpro/entry/pfam/PF00069

remove
http://pfam.xfam.org/protein/P04551 (there is no Pfam gene specific view in Interpro)

Do I need to get the GO DB xrefs file updated for this?

**Comment by kimrutherford** [comment]
> remove
> http://pfam.xfam.org/protein/P04551 (there is no Pfam gene specific view in Interpro)

I've changed the code.  The link will be gone on Wednesday morning.

> Do I need to get the GO DB xrefs file updated for this?

Yep, xrefs needs changing.  I've made a pull request: https://github.com/geneontology/go-site/pull/1899

**Comment by kimrutherford** [comment]
> I've made a pull request: https://github.com/geneontology/go-site/pull/1899

That has been merged.  I'll check the main site in the morning.

**Comment by kimrutherford** [comment]
> I'll check the main site in the morning.

The main file at GO hasn't been updated yet:
http://current.geneontology.org/metadata/db-xrefs.yaml

I'm guessing it is updated only when the main GO pipeline runs.  I'll close this issue when the change comes through.

**Comment by kimrutherford** [comment]
> The main file at GO hasn't been updated yet:

It's now updated in the snapshot version: 
http://snapshot.geneontology.org/metadata/db-xrefs.yaml

So I assume it will be in the "current"/release version soon.

**Comment by kimrutherford** [comment]
This is finally fixed.
