### ISSUE TITLE
Front page news item (altered proteins)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1926]
Title:
 Protein sequence changes:
Body:
78  protein have been shortened. This set includes 34 published proteins (Apl4, Brc1, Cdc48, Cdt1, Cho1, Cmb1, Cut2, Cut6, Cwf26, Dbr1, Dri1, Elo2, Eri1, Lsd2, Lys2, Med13, Naa38, Nup107, Nup82, Orc2, Pof10, Ppt1, Rec24, Rga2, Rmt3, Rns1, Rpn7, Sap145, Skb1, Snf5, Snt2, Spn3, Tpp2, Trm1, and Tup12). 

Also we can retire to the archive the old pombe talks news item and  everything older than
New human orthologs including 3 MRP complex subunits 2022-03-23 (inclusive)

we will have quite a few more news items coming along...(AlphaFold,  InterMIne, UTRS, allele pages etc. etc)

**Comment by kimrutherford** [comment]
Should we add this news straight away?

**Comment by ValWood** [comment]
Yes we can, this is announced on pombelist.

**Comment by kimrutherford** [comment]
Should we include a link to the Gene coordinate changes page?

**Comment by ValWood** [comment]
we can add that link when:
https://github.com/pombase/curation/issues/3024 is done.
But the nes item can go live now.

**Comment by kimrutherford** [comment]
The new item is up on the front page.

The text is here is you'd like to tweak it: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-09-06-protein-sequence-changes.md

**Comment by kimrutherford** [comment]
> we can add that link when:
> https://github.com/pombase/curation/issues/3024 is done.

OK.

> Also we can retire to the archive the old pombe talks news item and everything older than
> New human orthologs including 3 MRP complex subunits 2022-03-23 (inclusive)

That's done.

**Comment by ValWood** [comment]
Can we alter this slightly to

78 protein have been shortened **(at the N-term)**. This set includes 34 published proteins (Apl4, Brc1, Cdc48, Cdt1, Cho1, Cmb1, Cut2, Cut6, Cwf26, Dbr1, Dri1, Elo2, Eri1, Lsd2, Lys2, Med13, Naa38, Nup107, Nup82, Orc2, Pof10, Ppt1, Rec24, Rga2, Rmt3, Rns1, RRpn7, Sap145, Skb1, Snf5, Snt2, Spn3, Tpp2, Trm1, and Tup12). **Allele description changes and modification position changes are pending.**

**Comment by kimrutherford** [comment]
OK, I've changed the text.  The change will be visible in 30-ish minutes.

The text is here is you'd like to tweak it: https://github.com/pombase/website/blob/master/src/docs/news.PomBase/2022-09-06-protein-sequence-changes.md

**Comment by kimrutherford** [comment]
Val, can this be closed?

**Comment by ValWood** [comment]
I think we wanted to update the news item with a link to the gene structure updates page when these were added in https://github.com/pombase/curation/issues/3024 (remember Li-lin also mentioned at the SAB that we dod not link this news item to the changes page so he could not see the coordinates of the change)

but now we talked about getting rid of this page and linking to
1) the log  with all coordinate changes and dates
2) a  before and after coordinates  browser track  (@manulera will this be possible if there are multiple changes?
I will close this ticket and put this part in a new ticket.
