### ISSUE TITLE
versions page  / sequence versioning

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1927]
https://www.pombase.org/internal-details

can we also data versions  include
InterPro version
GOA data version
BioGriD data version
on this page?

**Comment by kimrutherford** [comment]
Yep, but it will take a bit of work.  The ontology versions are easy because they're in the OBO file and there's a good place to store them in Chado.  So when the files are parsed, the versions are stored at the same time.  The makes it easy to display the versions on the internal-details page.  It just shows everything that's in Chado.

InterPro and GOA have the versions in the data files so with a bit of a change to the loaders we can parse the versions and put them in a file or files for the website code to read.

As far as I can see BioGRID doesn't have version in the file we download.  So that might need to be added to the website config file manually when they make a release.  (Do they have releases?)

**Comment by ValWood** [comment]
From the SAB:
A web page explaining the relationships between PomBase version number, NCBI version number, and Ensembl version number would be useful (Note: need to distinguish between sequence version, and annotation version, I am not sure that Ensembl has an annotation version number)
	• Report sequence feature changes accompanying each release

**Comment by kimrutherford** [comment]
> As far as I can see BioGRID doesn't have version in the file we download

The version is in the file name.

**Comment by kimrutherford** [comment]
Note to self: `chadoprop` now has property types for the external datasets:
   - goa_version
   - interpro_version
   - biogrid_version

**Comment by kimrutherford** [comment]
Note to self: the best place to get the GOA version number from seems to be this file: https://ftp.ebi.ac.uk/pub/databases/GO/goa/current_release_numbers.txt

**Comment by kimrutherford** [comment]
I've added a new section "Data source versions" to the [internal details page](https://www.pombase.org/internal-details).  It has only InterPro for now.  I'm still working on BioGRID and GOA.

----------------------------


![image](https://github.com/pombase/website/assets/90474/92e7b734-4151-4f03-89ef-f14f240d19cd)

**Comment by kimrutherford** [comment]
I've added the code for storing the GOA version in Chado.  So that will be in the list on Friday morning too.

**Comment by kimrutherford** [comment]
The BioGRID version will be on the page in the morning too.

**Comment by kimrutherford** [comment]
The internal versions page now has:

 - BioGRID
 - InterPro
 - UniProt GOA

https://pombase.org/internal-details

At some point we should chat about making the versions page tidier, maybe with a bit of documentation about the data sources are (with links to them) and a bit about the list of CVs.  Then make it public?

**Comment by kimrutherford** [comment]
After a small fix, the data source versions are now on the JaponicusDB page too: https://www.japonicusdb.org/internal-details

**Comment by kimrutherford** [comment]
> UniProt GOA

There was a GOA update yesterday and so PomBase has the new data.  It was a good test that the versions page updated too.  It didn't :-)
I've fixed that bug for tomorrow.

**Comment by kimrutherford** [comment]
I think the only think left for this issue is to make the page public and add it to a menu.

We should talk about what to name it and what to include.  Should it just be for data versions?   Currently there is also a "Annotation stats" section.  Maybe we should move that to the [curation stats](https://pombase.org/curation_stats) page?

**Comment by ValWood** [comment]
We decided to release, add to about menu 
The outstanding tasks are listed here https://github.com/pombase/website/issues/2142

**Comment by ValWood** [comment]
Thats something else

**Comment by ValWood** [comment]
Action,
Remove annotation part.
Decide where to put this.

**Comment by kimrutherford** [comment]
> Action,
> Remove annotation part.

Done.

**Comment by kimrutherford** [comment]
> Decide where to put this.

I've been experimenting with adding the numbers beside the graphs:

![image](https://github.com/pombase/website/assets/90474/3ec53e2e-923e-4156-91bd-ce58000f61a6)

**Comment by ValWood** [comment]
Looks good!

**Comment by kimrutherford** [comment]
Great.  I was think of including the counts of annotations of each type in that section too.

**Comment by ValWood** [comment]
Good idea!

**Comment by kimrutherford** [comment]
I think we can close this.

**Comment by ValWood** [comment]
Do we link to this versions page from anywhere? https://www.pombase.org/internal-details
This was also a SAB request.

**Comment by kimrutherford** [comment]
> Do we link to this versions page from anywhere? https://www.pombase.org/internal-details

We link to it from the bottom of this page:
  - https://www.pombase.org/about/data-sources

which we link to from these pages:
  - https://www.pombase.org/about
  - https://www.pombase.org/about/terms-of-use

So not exactly easy to find.

**Comment by kimrutherford** [comment]
> Should we add a menu item "versions" under "about"

We could do.  My worry is that that page is a bit ugly and most of contents won't be meaningful to users.

Maybe a link on the Datasets page would be enough?

**Comment by ValWood** [comment]
That sounds sensible!

**Comment by kimrutherford** [comment]
I've added a link from the datasets page.

Perhaps we should change the URL?  "/internal-details" doesn't match the page contents.

**Comment by ValWood** [comment]
data_sources_and_cv_versions?

(remover KEGG)

**Comment by ValWood** [comment]
I don't recognize some of these ;)
And perhaps we should ass another column to say what they are? or even a link to the ontology?
Maybe group internal and external sources?

PSI-MOD: 11:12:2020 15:38
PSI-MOD_extension_relations: 13:07:2012 17:15
PomGeneEx: 16:02:2021 15:25
PomGeneExProt: 16:02:2021 15:25
PomGeneExRD: 16:02:2021 15:25
PomGeneExRNA: 16:02:2021 15:25
SO_feature_relations: 13:07:2012 17:15
biological_process: releases/2024-11-04
cell: 13:01:2012 09:59
cellular_component: releases/2024-11-04
chebi_ontology: 89
external: releases/2024-11-04
feature_property: 10:06:2005 15:07
fission_yeast_phenotype: fypo/releases/2024-10-28/fypo-simple-pombase.obo
fission_yeast_phenotype_condition: 30:07:2021 14:14
fypo_extension_relations: 06:07:2012 17:25
fypo_extensions: 13:08:2012 11:25
go/extensions/gorel: 13:07:2012 17:15
iao: 13:08:2012 11:25
kegg_pombe_pathway: 1.0
molecular_function: releases/2024-11-04
mondo: mondo/releases/2024-10-01/mondo-simple.owl
pato.ontology: releases/2015-11-18
pb_quiescence: 27:02:2013 10:05
pombase_has_qualifier_range: 13:07:2012 17:15
pombase_relations: 1.0.
protein: 49.0.
quality: releases/2015-11-18
sequence: 2024-06-05

**Comment by kimrutherford** [comment]
> (remover KEGG)

It should be gone when the load finishes in a few hours.  I had to restart it because I broke things while trying to remove KEGG.

> I don't recognize some of these ;)

Me neither.  Some get pulled in by other ontologies.  Like "iao" seems to be pulled in by `fypo_extensions`.

> And perhaps we should ass another column to say what they are? or even a link to the ontology?
> Maybe group internal and external sources?

Perhaps we should hide most of the ontologies and keep the major ones we want to highlight, like: GO, FYPO, Mondo, SO.  There are many in the list that have very old dates and versions which is a little hard to explain.  Like "cell: 13:01:2012 09:59" and "chebi_ontology: 89"  (ChEBI is on version 237)

**Comment by ValWood** [comment]
>Perhaps we should hide most of the ontologies and keep the major ones we want to highlight, like

even better.

**Comment by ValWood** [comment]
Although we export data with some of these ontology IDs so they do need to be traceable/explainable.
Remember when Andrew was handling the  expression data etc for RNA central and we had obscure identifiers in the extensions...

**Comment by kimrutherford** [comment]
> Although we export data with some of these ontology IDs so they do need to be traceable/explainable.

OK, I've shared a Google spreadsheet where we can add links and descriptions.

**Comment by ValWood** [comment]
I started to fill this in until I got stuck. We can discuss the rest next week.
