### ISSUE TITLE
SAB page update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1928]
Update SAB page with this at the top:

The PomBase Scientific Advisory Board (SAB) will provide strategic scientific advice to the PomBase team covering current and future priorities related to curation, tools provided and outreach. They will advise how can we better align S. pombe knowledge to human genetics and health. The SAB is an independent body, made up of leading experts in both fission yeast biology and Model Organism Databases from around the world.

**Comment by kimrutherford** [comment]
Should Sue Jaspersen be moved to the "Past members" section?

**Comment by ValWood** [comment]
Yes, although I guess since we never had a meeting yet we could just remove her.

**Comment by kimrutherford** [comment]
> Yes, although I guess since we never had a meeting yet we could just remove her.

Good point, I'll do that.

**Comment by kimrutherford** [comment]
That's done.  It can be tweaked / edited here:
https://github.com/pombase/website/blob/070eecb1e81c14e7303150094ac84b5424154b51/src/docs/about/pombase-sab.PomBase.md
(although GitHub seems a bit broken currently)

**Comment by ValWood** [comment]
note to selef , italicise S. pombe (GitHub still broken)

**Comment by kimrutherford** [comment]
Sorry, I had the wrong link.  This one should work:
https://github.com/pombase/website/blob/master/src/docs/about/pombase-sab.PomBase.md

**Comment by kimrutherford** [comment]
I noticed the entry for Doug Howe wasn't formatted correctly.  I've fixed that and changed S. pombe to italics at the same time.  The main site will have the change in 30 minutes or so.
