### ISSUE TITLE
news item for Alpha Fold RBSH paper (pending)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1929]
~Ready for when accepted:~

Reciprocal Best Structure Hits: Using AlphaFold models to discover distant homologues
We collaborated with the Pfam group at the EBI to evaluate predictions generated from AlphaFold reciprocal best structure hits to identify potential distant orthologs. The RBSH approach provided 11 novel human homologues, including Pho86 Q10436 NAT8 (ER acetyltransferase), Mug174 -> human COIL Colin), Ach1 -> OXCT1 succinyl-CoA:3-ketoacid coenzyme A transferase, SPAC1952.08c -> CREG1, imt1 A4GALT (Lactosylceramide 4-alpha-galactosyltransferase), rtc5 MEAK7 MTOR associated protein. A further 41 novel orthologs were predicted between _S. pombe_ and _S. cerevisiae_ which had fallen under the radar for all other methods used at PomBase.  Most of the novel connections provided additional functional information, or supported existing knowledge for poorly characterised proteins. See supporting data tables  S4 and S5 for the complete list of predictions included in PomBase. 

https://academic.oup.com/bioinformaticsadvances/advance-article/doi/10.1093/bioadv/vbac072/6749558

**Comment by ValWood** [comment]
We can make this news item live now...

**Comment by ValWood** [comment]
I tried to add this

2022-09-16-Alpha-fold_RBSH.md

### Reciprocal Best Structure Hits: Using AlphaFold models to discover distant homologues




We collaborated with the Pfam group at the EBI to evaluate predictions generated from AlphaFold reciprocal best structure hits to identify potential distant orthologs. The RBSH approach provided 11 novel human homologues, including Pho86 Q10436 NAT8 (ER acetyltransferase), Mug174 -> human COIL Colin), Ach1 -> OXCT1 succinyl-CoA:3-ketoacid coenzyme A transferase, SPAC1952.08c -> CREG1, imt1 A4GALT (Lactosylceramide 4-alpha-galactosyltransferase), rtc5 MEAK7 MTOR associated protein. A further 41 novel orthologs were predicted between S. pombe and S. cerevisiae which had fallen under the radar for all other methods used at PomBase. Most of the novel connections provided additional functional information, or supported existing knowledge for poorly characterised proteins. See supporting data tables S4 and S5 for the complete list of predictions included in PomBase. [Full Article](https://academic.oup.com/bioinformaticsadvances/advance-article/doi/10.1093/bioadv/vbac072/6749558).


I have an icon image but I wasn't sure how to make it the correct number of pixels, so I left it out for now.

**Comment by ValWood** [comment]
Deal with

**Comment by kimrutherford** [comment]
Could you send me your icon image?

**Comment by kimrutherford** [comment]
> Could you send me your icon image?

Sorry, I didn't notice you'd attached it by email.  It's blurry as an icon:

![image](https://user-images.githubusercontent.com/90474/196122205-68452362-6c19-43a2-a717-0f2f4d2da8d3.png)

How about this instead:

![image](https://user-images.githubusercontent.com/90474/196129486-5f3f68b8-ae3d-45bb-9624-502d905dc67a.png)

**Comment by kimrutherford** [comment]
> How about this instead:

I forgot to say, that's not from the publication but maybe it makes sense to have a generic protein structure news icon.

But now I think about it, it looks quite like a double helix so maybe I'll try again.

**Comment by ValWood** [comment]
I think your image is ok. It's clearly a protein structure. anything more detailed will not be clear.

I don't know what is happening abut the tweeting around this publication. I am waiting to forward it. It does not even seem to be possible to retweet from the journal at present (the link is broken- I reported that).
I don't want to tweet it before the 1st author really. she migh also waiting for the journal to fix the link).

**Comment by kimrutherford** [comment]
> I think your image is ok. It's clearly a protein structure. anything more detailed will not be clear.

The icon is now on the main site.  It doesn't look too bad.

Anything more to do here?

**Comment by ValWood** [comment]
nope!
