### ISSUE TITLE
term page additional link

### ISSUE THREAD

**Issue by ValWood** [pombase/website#193]
One of the links for the "term page"  should be "view term ancestors" (that pretty much means we would have  an ontology browser, because we can already see the descendants...).

I have been using the new pages  *a lot* this weekend and this would  be really useful (I need to switch to QuickGO at the point when I need this)

**Comment by kimrutherford** [comment]
> view term ancestors

It's not too hard to implement.  We just need to think about how it should look.

**Comment by kimrutherford** [comment]
I've added a very basic table of term ancestors on the term details page.  You might need to shift-reload to see it.  Example: http://pombase2.bioinformatics.nz/term/FYPO%3A0003756

**Comment by ValWood** [comment]
fantastic, that will be really useful. I often want to go to a broader term from a   list, and if the gene product isn't directly annotated  I  need to do a query.

I don't think we need   to include has_part here, probably just is_a and part_of will do...

**Comment by kimrutherford** [comment]
> I don't think we need to include has_part here, probably just is_a and part_of will do...

I've changed it to show just those relations.

**Comment by ValWood** [comment]
this is so useful.......

**Comment by ValWood** [comment]
so cool to be able to get to these terms, AND see the descendant lists:
http://pombase2.aska.gen.nz/term/FYPO%3A0000127
