### ISSUE TITLE
page organization, publications

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1930]
I'm not sure  why we need to separate "pombase publications" from "collaborative publications" which are hidden down at the bottom of the page.

https://www.pombase.org/about/published-by-pombase

Can we just have a single list "Publications including PomBase authors".
I think the GO  etc papers are equally important, but are quite hidden. You would not know they were there unless you scrolled to the bottom

**Comment by kimrutherford** [comment]
> You would not know they were there unless you scrolled to the bottom

It going to be long list and you'll still need to scroll to the bottom to see some of them.  Do we want to categorise the publications in some other way?  Or just have most recent at the top?

**Comment by ValWood** [comment]
I think it should just be date order. I don't think we need categories. Also we have this:
https://www.pombase.org/about/citing-pombase.

with the current arrangement collaborative papers are quite hidden, and for many  (like GO papers) we make a substantial contribution. If reviewers look they would likely miss this separate list.

**Comment by ValWood** [comment]
To me, it seems a strange split. For example, I was co-first author on the genome deletion papers. 
I don't think we should treat publications differently just because they are collaborations. Their positioning below book chapters, pre prints and posters makes them seem less important.

**Comment by kimrutherford** [comment]
OK. I'll make that change.

Should I leave the Preprints, Book chapter, Infographics and More sections as they are?

**Comment by kimrutherford** [comment]
> I'll make that change.

I'm going to take a bit of time to tidy the page implementation up a bit.  There's currently a lot of hand-crafted HTML which makes things hard to manage.

**Comment by ValWood** [comment]
> Should I leave the Preprints, Book chapter, Infographics and More sections as they are?
yep please

**Comment by kimrutherford** [comment]
That's done now.  I've tried to put them in date order but let me know if you spot any mistakes.

https://www.pombase.org/about/published-by-pombase

If there are any you'd like to emphasise, we could think about highlighting them in some way:

![image](https://user-images.githubusercontent.com/90474/190900842-c131574d-b66c-4b35-af19-1ee9d4e56976.png)

**Comment by ValWood** [comment]
Thanks for this. Its all good for now.
