### ISSUE TITLE
See if it is possible to record JBrowse analytics

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1931]
@kimrutherford  
"It might be possible to record when the user first click trough to JBrowse, with some work.  The tricky thing is that JBrowse isn't a web page it's an application."

I wonder what other resources do?

**Comment by ValWood** [comment]
JBrowse appear to have something?
https://github.com/GMOD/jbrowse/search?q=Analytics&type=

**Comment by kimrutherford** [comment]
I noticed yesterday that we are seeing JBrowse in Google Analytics.  I don't know how that works.

![image](https://user-images.githubusercontent.com/90474/190096853-bac9ed68-3275-4e3b-8311-fc58672773c0.png)

**Comment by ValWood** [comment]
Actually, I did know that but I forgot. Clever JBrowse.
