### ISSUE TITLE
Broken link to ELIXIR

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1934]
The link in the text "PomBase is an ELIXIR-UK Node Service" at the bottom of each page is now broken.  It looks like ELIXIR removed or moved the page without adding forwarding link.

**Comment by ValWood** [comment]
Was it definitely a deep link, or did the link only fo to the Elixir home page?

**Comment by kimrutherford** [comment]
The link is still in the footer, I haven't changed it: https://elixiruknode.org/node-services/

**Comment by ValWood** [comment]
Right it is now
https://elixiruknode.org/services/
I will let them know that people need to be informed.

**Comment by ValWood** [comment]
(I was clicking on the icon, not the services link)

**Comment by kimrutherford** [comment]
> Right it is now
> https://elixiruknode.org/services/

Thanks.  I've changed it and the update will be visible in 30-ish minutes.
