### ISSUE TITLE
Do these extension relations get substituted to has_input?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1937]
388 | has_regulation_target         | molecular_function
   175 | has_regulation_target         | biological_process

If so we should probably fix globally and check they are configured corre ctly at the display level.

Which term use these relations?

**Comment by kimrutherford** [comment]
I missed another configuration for `has_regulation_target`.  Should this be removed or changed to `has_input`?:

```
         {
             "rel_name": "has_regulation_target",
             "if_descendant_of": "GO:0008150",
             "display_name": "regulates",
             "reciprocal_display": "regulated by"
         },
```

**Comment by ValWood** [comment]
that's (GO:0008150 biological process). I think it should be removed?

**Comment by kimrutherford** [comment]
> change the config file for the website to has_input -> display 'activates transcription of for this term'

Then it will look like:

 **activates transcription of for this term** mcs6 **part of ...**

That doesn't seem right?


> Fix display labels pinned to has_regulation_target (7)

That's done for tonight's load.

> change all instances of has_regulation_target ->has_input

I'm hoping to get that done before the nightly load.  Working on it now.

**Comment by ValWood** [comment]
A very badly placed quote!

display 'activates transcription of' for this term

**Comment by kimrutherford** [comment]
OK, all good then.  I've changed has_regulation_target to has_input in Canto and in pombe-embl in time for the nightly load.  I'll check in the morning.

**Comment by kimrutherford** [comment]
>  I've changed has_regulation_target to has_input in Canto and in pombe-embl in time for the nightly load. 

I got the command wrong so not everything in Canto was updated.  I'll check again tomorrow.
