### ISSUE TITLE
"Load tracks from this publication" link on publication pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1938]
"Load tracks from this publication" should also load genome feature and sequence tracks

**Comment by kimrutherford** [comment]
> "Load tracks from this publication" should also load genome feature and sequence tracks.

I got the feature and sequence tracks when I tried it from https://www.pombase.org/reference/PMID:25908789

Which publication were you looking at?

I did get an error though "Not found: I%3A1..5579133" which I'm fixing now.  I think the error is unrelated.

https://github.com/pombase/pombase-config/commit/f1ee9d63f36464d26884fa06a63f79a8660dca8b

**Comment by ValWood** [comment]
I was looking at:
https://www.pombase.org/reference/PMID:29914874
(it might be due to the 16 track limit, if so we should ensure the genome annotation is always 2 of the tracks)

**Comment by kimrutherford** [comment]
> I was looking at:
> https://www.pombase.org/reference/PMID:29914874

I just tried that page and the feature tracks were there in JBrowse.  Let's try this on a call some time.

**Comment by kimrutherford** [comment]
I think we decided that this can be closed?
