### ISSUE TITLE
Motif search, how do I see the motifs that are not shown?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1939]
I want to see the MELT motifs in spc7

[MI][EDN][ILM][ST] 

but they are not visible. I think there used to be a way to see all.

There are 641 matches, but the default list displayed is quite short (100)

541 other matching genes not shown - Send gene list to advanced search to see all genes

Do we really need the default list size?

**Comment by kimrutherford** [comment]
> Do we really need the default list size?

The page gets slow if the list is too long.  I picked 100 initially to be on the safe side.

**Comment by ValWood** [comment]
Maybe we

**Comment by ValWood** [comment]
Maybe we could keep the default as it is, but then have a 'show all' bo
button (I though we used to have this?)

**Comment by kimrutherford** [comment]
> Maybe we could keep the default as it is, but then have a 'show all'
> I thought we used to have this?

Not that I can remember.  I've just changed the maximum displayed genes to 500 which is small enough that it does get too slow.

**Comment by kimrutherford** [comment]
While testing things I found that the "Show all ..." button wasn't working at all.   The button is supposed to show all matches within a gene rather than just the first 20 (not a common case).  It's fixed for tomorrow night's update.

![image](https://user-images.githubusercontent.com/90474/197449422-01f3b651-fd93-4232-bdb4-c78e1dca0938.png)

**Comment by ValWood** [comment]
Sorry I forgot that the link I clicked on was "show all". That is what I am clicking on. So in that case if the link works it will be fine for the default to be 20!
Apologies!

**Comment by kimrutherford** [comment]
No problem.  I'll close this after testing the main site tomorrow.

**Comment by ValWood** [comment]
The "show all" link is not back yet (at least I don't see it)
Whrn "show all" is back you can reduce the default back to 20 or so

**Comment by ValWood** [comment]
[MI][EDN][ILM][ST]

you can only send to the advanced search to see all the genes, but you cant see the actual motis. In fact something else changed recently. Not you only see one row per protein int eh output. So you only see one motif even if there are multiple copies (You used to see multiple rows). I thought I saw multiple rows when I reported this issue? did I imagine this?

**Comment by kimrutherford** [comment]
> you can only send to the advanced search to see all the genes, but you cant see the actual motis.

I changed it to [show 500 instead of 100](https://github.com/pombase/website/issues/1939#issuecomment-1288357311), but there is still no way to see all genes at once.  I tried displaying all matches on my desktop but it caused my browser to freeze for 30 seconds for some motifs.  I'll come back to this later to see if I can find a solution.

> In fact something else changed recently. Not you only see one row per protein int eh output. So you only see one motif even if there are multiple copies (You used to see multiple rows). 

I tried that motif and got this result.  `gto1` has two rows?

![image](https://user-images.githubusercontent.com/90474/198129894-62fd7545-88cf-46fe-9965-3f7c5ce4a6fb.png)

**Comment by ValWood** [comment]
OK, that's odd, there are only a couple of proteins with more than one motif in the first 500. I thought because MELT was a phosphorylation motif, there would be many proteins with lots

"multiple conserved MELT motifs in the Spc7 "
https://www.pombase.org/reference/PMID:27618268

but maybe that isn't the case, or maybe all of the ones with multiple motifs are in the hidden part of the results.

One option, if it is possible, would be to show the proteins with the highest number of hits first. Anyway this isn't super urgent because it isn't a common problem, and it isn't giving wrong results.

**Comment by ValWood** [comment]
Outstanding item 
One option, if it is possible, would be to show the proteins with the highest number of hits first. Anyway this isn't super urgent because it isn't a common problem, and it isn't giving wrong results.

@kimrutherford  how much work would this be do you think?

**Comment by ValWood** [comment]
I think the "Show all" would be sufficient.

You might have already implemented but not activated:

See above:
"While testing things I found that the "Show all ..." button wasn't working at all. The button is supposed to show all matches within a gene rather than just the first 20 (not a common case). It's fixed for tomorrow night's update."

**Comment by kimrutherford** [comment]
> You might have already implemented but not activated:

That's for showing all the matches within one gene if there are more than 20.  I'll add a show all button to show the matches from all genes.  That's half implemented.

**Comment by ValWood** [comment]
Keep this one in mind if you need a diversion.

**Comment by kimrutherford** [comment]
Hi Val.

I've added a message above the table making it clear how many peptides are show.  And added a "Show all" button:

![image](https://github.com/user-attachments/assets/3e9fe6e4-99a9-4eb8-bc0c-53e82012f86f)

[*click*]

![image](https://github.com/user-attachments/assets/c01f0aa6-6840-49fc-87f0-b524bea27d98)

These changes are on the dev site but not on the main site for now:
https://dev.pombase.org/motif_search

I don't think there are any major bugs but there might be minor ones.  :-)

**Comment by ValWood** [comment]
cool! thanks

**Comment by kimrutherford** [comment]
The changes are now on pombase.org

Is there anything else to do on this issue?

**Comment by ValWood** [comment]
no all good
