### ISSUE TITLE
are these labels OK?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#194]
![midori](https://cloud.githubusercontent.com/assets/7359272/23344848/950cd4d8-fc7b-11e6-9abd-e60ce162c58b.jpg)

**Comment by ValWood** [comment]
can you improve?
It might be OK as is but it looks a bit inconsistent...

**Comment by mah11** [comment]
What specific text are you asking about?

**Comment by ValWood** [comment]
"Level" and "Extension"

**Comment by mah11** [comment]
I think it's not essential to have them at all. I could happily remove them, but if we keep them the current words are as good (or bad) as any.

**Comment by ValWood** [comment]
OK lets leave as is for now
