### ISSUE TITLE
Look at gene page menu bar contents and functionality

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1940]
Kathy preferred the SGD menus

We will
i) look at PomBase and SGD menus side -by -side and compare contents to assess the difference and see where improvements can be made
ii) @manulera suggested  seeing the sub menus only when in the section
iii) @manulera Also clearer to highlight where you are
iv) I'll ask Kathy to fire us an e-mail next time she can't locate things easily when using the menus. That will give us a better idea where the problems are.

**Comment by kimrutherford** [comment]
As well as different content, the menus have a very different style.  The SGD menus have plenty of whitespace to make them easy to read.  Our menus are cramped and have a smaller font so are harder to read (in my opinion).

**Comment by ValWood** [comment]
Yes, maybe if we  simplify and then have sub menus when you get to the relevant section, they don't need to be so crowded:

Gene Ontology
Phenotype
Expression
Interaction

etc

**Comment by ValWood** [comment]
- [ ] Change "molecular pathway" to KEGG pathway
 (I think that will be clearer in the shorter term- and reduce expectations)

**Comment by ValWood** [comment]
- [ ] Will ask advice on this, but I think protein families might deserve their own section
 (protein features is a bit obscure)

**Comment by manulera** [comment]
> Our menus are cramped and have a smaller font so are harder to read (in my opinion).

I think the clustering that Val proposes can really help. Initially present higher-order categories in the menu that expand either when you click to go to that position, or when you move to that position with the scrollbar. Also the highlighting that sgd does is also nice (highlighting the category on which you are in purple)

**Comment by ValWood** [comment]
We can do this with the new person. Fresh eyes.

**Comment by ValWood** [comment]
@PCarme 
we need some input on the sidebar menu labels (this was from  Kathy G> at the last SAB meeting, I am preparing for the next one)
I will chat to you about this next time we speak.

**Comment by ValWood** [comment]
GO
Target
Phenotype
Domains
Modification
Expression
Comment/Warning/Misc
Interaction 
Disease
Homologs
Taxon
Transcript 
Sequence
External
Literature

**Comment by kimrutherford** [comment]
> Comment/Warning/Misc

Can we think of a different title for this one?  Would "Comments and warnings" be OK?

**Comment by kimrutherford** [comment]
> GO

We need think about what to do with the current "Activities" and "Binds" sub-menus  of "GO molecular function".

**Comment by kimrutherford** [comment]
> I guess my question really should be what are all the possible menu items?

Here's the list:

 - jbrowse (reference pages only)
 - molecular_function
 - biological_process
 - cellular_component
 - target_of
 - single_locus_phenotype
 - multi_locus_phenotype
 - fission_yeast_phenotype_condition
 - complementation
 - kegg_pombe_pathway
 - transcript_view
 - protein_domains_and_properties
 - PSI-MOD
 - qualitative_gene_expression
 - quantitative_gene_expression
 - misc
 - cat_act
 - m_f_g
 - genome_org
 - ex_tools
 - sequence
 - physical_interactions
 - genetic_interactions
 - double_mutant_genetic_interactions
 - single_allele_genetic_interactions
 - orthologs
 - paralogs
 - species_dist
 - mondo
 - warning
 - subunit_composition
 - external_references (gene pages only)
 - literature (gene pages only)

**Comment by ValWood** [comment]
OK  misc must be comment

fission_yeast_phenotype_condition (I don't know what this is?)

These are so rare we can just show them when they occur:
complementation
cat_act
m_f_g
genome_org
ex_tools
subunit_composition

kegg_pombe_pathway (I don't think we show this any more?)

single_allele_genetic_interactions (what's a single allele GI?)

**Comment by kimrutherford** [comment]
> These are so rare we can just show them when they occur:

Yep, that's how it's implemented.

> kegg_pombe_pathway (I don't think we show this any more?)

KEGG is still in the load script, but there are lots of errors:
https://curation.pombase.org/dumps/latest_build/logs/log.2024-11-05-21-33-31.kegg-pathway
Should I fix that or remove KEGG from the load?

> single_allele_genetic_interactions

There's an example here:
https://www.pombase.org/term/FYPO:0002061
"Genetic interactions where FYPO:0002061 is the single mutant phenotype"

**Comment by kimrutherford** [comment]
> fission_yeast_phenotype_condition (I don't know what this is?)

It appears on pages like:
https://www.pombase.org/term/FYECO:0000248
"Phenotype condition annotations for FYECO:0000248 and its descendants"

**Comment by kimrutherford** [comment]
> KEGG is still in the load script, but there are lots of errors:

It looks like KEGG have changed the format of data from their API.  It used to look like this, which is easy to parse:
```
spo:SPAC1002.09c        path:spo00010
spo:SPAC13A11.06        path:spo00010
spo:SPAC186.08c path:spo00010
```

Now it looks like this, with no gene IDs:
```
spo:2538729     path:spo00010
spo:2538797     path:spo00010
spo:2538802     path:spo00010
```

The change happened about July 28th according to the logs.

**Comment by ValWood** [comment]
yeah I noticed it was missing for a while, but it seems nobody misses it, and it will soon .
I have always got the impression KEGG isn't very keen on data reuse...
Let's just remove it.

**Comment by ValWood** [comment]
>It appears on pages like:
https://www.pombase.org/term/FYECO:0000248

I completely forgot about this page! I'm not even sure how I would get to it!

**Comment by kimrutherford** [comment]
> I have always got the impression KEGG isn't very keen on data reuse...
> Let's just remove it.

Done!

I'm glad you suggested removing it because it looked like a bit of a pain to get the gene IDs with their API.

**Comment by kimrutherford** [comment]
Today I refactored the code for the left hand menus.  The same code is used for the menu on the term, reference, genotype and gene pages but I think it's only the gene page where the menu is too long.

The refactoring makes is possible to fix this issue and also makes this one fixable:
 - pombase/website#2155

Tomorrow morning I'll fix #2155 and I'll add the sub-menu items.

**Comment by kimrutherford** [comment]
> OK misc must be comment

Yep!  Sorry for the slow answer.  I checked the configuration and "misc" is displayed as "Comment"

**Comment by kimrutherford** [comment]
> We need think about what to do with the current "Activities" and "Binds" sub-menus of "GO molecular function".

Is this how we want it to look in the new system?:

![image](https://github.com/user-attachments/assets/ca862651-bc4f-435f-8d20-5fb4d5c32fb6)

**Comment by kimrutherford** [comment]
This is working for "Expression" and "Comments and Warnings" because those are the easy cases.  The harder cases are the menu items that have existing sub-items: molecular function and phenotypes.
It's on dev if you want to give it a go: https://dev.pombase.org/gene/SPCC18B5.03

**Comment by kimrutherford** [comment]
Do you think we could put "Taxonomic conservation" under "Homologs" or under a combined heading like "Homologs and taxonomy"?

And I wonder if we can shorten "Protein domains and features".  It's longer than the other menu items, so it wrap around to the next line.

**Comment by kimrutherford** [comment]
With fewer items in the menu, we can think about making the items a bit less tightly packed:

![image](https://github.com/user-attachments/assets/26522bb7-bf20-400f-8ce3-ed01759d5013)

**Comment by kimrutherford** [comment]
Or if we wanted to make the page look a bit less heavy, we could try something more radical:

![image](https://github.com/user-attachments/assets/1c1b6be9-06c1-4c5c-b5db-58db95185303)

**Comment by ValWood** [comment]
> Should the menu item here be "Gene expression" or "Expression"?

Just expression,  (it covers gene and protein levels!)
well spotted, don't know how we missed that

**Comment by ValWood** [comment]
>>We need think about what to do with the current "Activities" and "Binds" sub-menus of "GO molecular function".
>Is this how we want it to look in the new system?:

I think so!

**Comment by ValWood** [comment]
It looks great so far.

I think we can make "homologs and conservation"
This will reduce the menu number from 21 down to 14 which is great.
 I like both styles. We can even ask the SAB which they prefer (a nice easy decision for them!)

**Comment by ValWood** [comment]
The only way I can think to shorten
Protein domains and features
is
Protein domain/feature
is that yucky?

I guess we could  just have Protein feature"
because a domain is a protein feature......

**Comment by kimrutherford** [comment]
> I think we can make "homologs and conservation"

OK, I'll do that next.

> We can even ask the SAB

Good plan!

Currently the Phenotype sub-items look like this:

![image](https://github.com/user-attachments/assets/210275c7-4964-465a-a57e-37b04e4497b4)

Would this be better or at least OK, to make the text shorter?:

![image](https://github.com/user-attachments/assets/72bafacc-45ac-4e5a-b0c4-477374ac9332)

**Comment by kimrutherford** [comment]
The new menu sub-items, including for GO and phenotypes are live on my desktop: https://desktop.kmr.nz/gene/SPCC18B5.01c

It's more or less working except that I haven't fixed this problem yet as it's a bit tricky:
 - https://github.com/pombase/website/issues/2155

It's the same bug for the phenotype cell/population menu items.  So on this page:
https://desktop.kmr.nz/gene/SPCC18B5.01c

**Comment by kimrutherford** [comment]
It's the same bug for the phenotype cell/population menu items. So on this page:
https://desktop.kmr.nz/gene/SPCC18B5.01c
there is a menu item for Multi-locus population phenotype, but there isn't a section for that.

**Comment by ValWood** [comment]
Above manu commented on the SGD menu highlighting the item for the section you are on. This might be quite useful too:

<img width="513" alt="Screenshot 2024-11-08 at 10 32 07" src="https://github.com/user-attachments/assets/891f13dd-d416-4c65-996a-7fdb0765273d">

**Comment by kimrutherford** [comment]
> Above manu commented on the SGD menu highlighting the item for the section you are on. This might be quite useful too:

I think I looked into that in the past and it was a challenge to implement.  I'll look again.

**Comment by ValWood** [comment]
Yes to the shortened phenotype sub menu labels.

Note that the label for homologs needs to be "homologs and conservation" not "homologs and taxonomy" because  it is about conservation, not taxonomy. Unfortunately it's is longer.

**Comment by kimrutherford** [comment]
Would it be sensible to have a "Transcripts and sequence" menu item?

**Comment by ValWood** [comment]
Yes, but I'd name it "Sequence and transcripts"

**Comment by kimrutherford** [comment]
I think it's better already.  Old vs new:

![old-vs-new](https://github.com/user-attachments/assets/d3b48fc9-70b8-4003-8448-1a6ccea3df3f)

**Comment by kimrutherford** [comment]
The changes are on pombase.org now.

I'm still working on this.  It's a bit tricky:
 - pombase/website#2155

**Comment by ValWood** [comment]
much!

**Comment by kimrutherford** [comment]
I forgot to fix the configuration for JaponicusDB.  I noticed today that the site was quite messed up.  I've gone back to Thursday's version until I fix it.

**Comment by kimrutherford** [comment]
> I forgot to fix the configuration for JaponicusDB.

It's usable again now although it could do with tweaks.
