### ISSUE TITLE
Add linkouts  to https://idr.openmicroscopy.org/

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1942]
Add linkouts to IDR from this publication page
https://www.pombase.org/reference/PMID:25373780

Also gene page specific links from "external references" section

@kimrutherford  I could not see the instructions (although @manulera  might be able to find it)

**Comment by kimrutherford** [comment]
> @kimrutherford I could not see the instructions

The reference page instructions are here:
https://github.com/pombase/website/wiki/Config-file#reference_page_extra_links

For the gene page external references there is a bit of documentation here:
 - https://github.com/pombase/website/wiki/Configuration#adding-a-new-external-reference
 - https://github.com/pombase/website/wiki/Config-file#external_gene_references

It's easier to add a gene page link if the external site is in the `GO.xrf_abbs` GO refs file.

@manulera I'm happy to help with this.

**Comment by manulera** [comment]
Ok, I will check this out!

**Comment by manulera** [comment]
Addressed in https://github.com/pombase/pombase-config/pull/88, will close automatically if @kimrutherford approves merge

**Comment by manulera** [comment]
In this one I did not specify that the gene has to be a `CDS`. For now there is no data of non-CDS as far as I know, but I think it's better to leave it like this in case in the future data linked to these genes is added.
