### ISSUE TITLE
Make JBrowse RNA labels dark grey / grey

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1943]
From the SAB.

We could maybe make the labels a bit smaller too.

https://github.com/GMOD/jbrowse/issues/4

![image](https://user-images.githubusercontent.com/90474/196768086-fc0818d2-18e5-49be-9195-513bf71abbf1.png)

**Comment by kimrutherford** [comment]
Does this help?:

![image](https://user-images.githubusercontent.com/90474/199921475-44ebdf7c-d4d7-4246-8284-c36ad644a74a.png)

**Comment by ValWood** [comment]
I think so!
@Lilindu

**Comment by kimrutherford** [comment]
We could also make the font a bit smaller for RNA features:

![image](https://user-images.githubusercontent.com/90474/199926742-70dccecc-290a-4eec-91ae-49731207abef.png)

**Comment by ValWood** [comment]
Yes to that too. Can we keep the CDS labels bold?

**Comment by lilindu** [comment]
Very helpful changes. Thanks.

**Comment by kimrutherford** [comment]
> Can we keep the CDS labels bold?

No problem.

![image](https://user-images.githubusercontent.com/90474/200155610-10d9470c-6fdd-4f35-a084-8a6ca239c7cb.png)

**Comment by kimrutherford** [comment]
That's on the main site now: https://www.pombase.org/gene/SPCC18B5.03

Please let me know if you'd like it darker or lighter, or any label size changes.

**Comment by ValWood** [comment]
Looks good
