### ISSUE TITLE
Allow hiding of the browser view on gene pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1944]
At the SAB Kathy didn't want to see the inline browser view on the gene pages.

Maybe add a button to toggle JBrowse which would make it tidier while we work on adding the other options.

We should keep a link to the full browser.

**Comment by ValWood** [comment]
I don't think we need to hide it. I don't think KAthy was so bothered about it being there, but something more informative for people interested in proteomes rather than genomes would be a nice alternative. So I don't think you need to do anything until we have a choice.

**Comment by kimrutherford** [comment]
OK.  I thought I heard her say that she would rather not see it on the gene pages.

**Comment by ValWood** [comment]
I think you are correct actualy, I think that is what she said. So a toggle would be good. Not urgent ..

**Comment by kimrutherford** [comment]
I've added a show/hide button on the dev site for testing: http://dev.pombase.kmr.nz/gene/SPBC30D10.10c

![image](https://user-images.githubusercontent.com/90474/204080720-5ec27823-0a4e-44d6-854c-218cb3e651ed.png)

**Comment by kimrutherford** [comment]
Once that's done, how do you feel about making the JBrowse image wider?  I think the whitespace at the edges is unnecessary.  I think I was trying to make it look like the Ensembl PomBase.

So change this:

![image](https://user-images.githubusercontent.com/90474/204080890-25727451-3238-4f31-b50f-965716ea44e3.png)

To this:

![image](https://user-images.githubusercontent.com/90474/204081964-a6acffe0-7a1d-4eae-8e20-e15942d35e43.png)

Although we eventually want it to look like:

![gene-page-tool-tabs-1](https://user-images.githubusercontent.com/90474/47064326-7f925500-d23b-11e8-88b2-3eea717f9125.png)

**Comment by ValWood** [comment]
The only issue I see with making the browser wider is that the structures are usually similar height to width aspect ratio so it would not work so well for structures once we change to the multi-view (especially when there are 4 options, pathway, protein viewer, sequence viewer, structure viewer). 

I imagined that when we moved to the multi-viewer the image could be wider (to use up the real estate), but would also be deeper.
I also wondered if making the image deeper would also remove the need for the scroll bar ( it's more important to be able to see everything in the sequence window than to see  more surrounding context, or to have the image elongated widthways).

**Comment by kimrutherford** [comment]
> The only issue I see with making the browser wider is that the structures are usually similar height to width aspect ratio so it would not work so well for structures once we change to the multi-view

That's true, we'll have to change things again once we have the other widgets.

> I also wondered if making the image deeper would also remove the need for the scroll bar

I think that would help.

But a wider image would help too because we can stretch out the image which will, on average, mean the two tracks need less vertical space.  So we can change this:
![image](https://user-images.githubusercontent.com/90474/204085163-179b6fa0-d67f-45df-84f1-5f003d7663f3.png)

to this (using [mcm4](https://www.pombase.org/gene/SPCC16A11.17) as an extreme example):
![image](https://user-images.githubusercontent.com/90474/204085172-93256f74-96bd-4f52-a20a-88703bff354e.png)

**Comment by ValWood** [comment]
Yes we can do this as a stop gap, as it will be a while before we have the other views.
Much better.

**Comment by kimrutherford** [comment]
I've made JBrowse wider:

![image](https://user-images.githubusercontent.com/90474/204157499-1b84c2f3-2bed-4f4f-a4c6-6977873136f3.png)

On the dev site, there's a hide/show button too:

![image](https://user-images.githubusercontent.com/90474/204157693-48a66457-c988-45e5-98e4-5835849629aa.png)
