### ISSUE TITLE
Format of sequence viewer

### ISSUE THREAD

**Issue by manulera** [pombase/website#1950]
Hi @kimrutherford 

I have been working on fixing a few alleles lately and I think it would be nice if the lines of the sequence viewer were not independent divs. The way it is now, if I want to use browser find text (Ctrl+F) to find a sequence motif that is break into two different lines, I cannot. Maybe setting the width to number of characters instead of splitting into divs would work.

```
.hello {
  max-width: 10ch;
  word-wrap:break-word;
}
```

Not really urgent, but if it is a quick fix, I think it would be quite helpful.

cc: @ValWood

**Comment by ValWood** [comment]
Do you mean the  sequence section of the gene page?
Are you proposing we show the sequence on a single line (or something else)?

**Comment by manulera** [comment]
Hi @ValWood, yes I mean the sequence section, but I don't mean to put it in a single line.

You can still put it on multiple lines, but make it so that words or motifs that are broken between lines are searchable. It depends on the html (whether each line is a separate `div` or the same `div` with line breaks). You can see an example here, if you do Cmd+F and search for `hello`.

https://jsfiddle.net/h563aoe4/11/

**Comment by ValWood** [comment]
Oh wow cool! yes +10 !

**Comment by kimrutherford** [comment]
Thanks for the suggestion Menu.  I'll give it a try soon.

**Comment by kimrutherford** [comment]
I've got it working on Firefox, but the lines are uneven in Chrome.  It's not the worst bug but it's annoying.  I'll see if I can fix that tomorrow. 

Chrome:
![2022-11-10_19-18](https://user-images.githubusercontent.com/90474/201016083-98a8e08f-d801-47aa-9313-d4b2b1689a07.png)

The searching across lines works though:
![image](https://user-images.githubusercontent.com/90474/201016443-690903be-1af9-492c-84ba-607f0a9a714c.png)

Firefox:
![image](https://user-images.githubusercontent.com/90474/201019482-fa7375bf-9316-4677-97d7-cbc935def94f.png)

**Comment by kimrutherford** [comment]
Looks like it's a known Chrome bug that's been around for over a year.  Luckily there's a simple work-around:
https://bugs.chromium.org/p/chromium/issues/detail?id=1162838#c1

It's seems to work OK now I've applied the work-around.  I'll do a bit more testing tomorrow and then release the change.

**Comment by manulera** [comment]
Nicee

**Comment by kimrutherford** [comment]
Those changes will be on the main site tomorrow.  It's on the dev site now if you'd like to try it: http://dev.pombase.kmr.nz/gene/SPCC18B5.11c

**Comment by manulera** [comment]
Awesome! Thanks!

**Comment by kimrutherford** [comment]
Thanks for the suggestion!  Using CSS to split the lines means I was able to remove some code, which makes me happy.  :-)
