### ISSUE TITLE
improve messaging  for list upload feature if genes are not found:

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1951]
Unknown identifiers: SPBC32F12.17  Only extant systematic identifiers can be supplied. Names may not be recognised due to genes merges (use the simple search to check this), or deprecation (check [https://www.pombase.org/status/new-and-removed-genes](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fstatus%2Fnew-and-removed-genes&data=05%7C01%7Cvw253%40cam.ac.uk%7C5c14ef81e5b043a4267c08dac0d5e4fa%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638034322143521798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IEBfLDxRn2L9e0zk%2FahYPk9lEKfF0E5iZvbN1H8tBcg%3D&reserved=0))

**Comment by ValWood** [comment]
Update https://www.pombase.org/status/new-and-removed-genes

i) SPBC36.13 was on the opposite strand to SPNCRNA.1391 

ii) SPCC794.16   low complexity homopolymeric region on the opposite strand to SPNCRNA.6762

iii) SPBC32F12.17  was on the opposite strand to SPNCRNA.1550  

iv) remove SPCC1672.14 - it looks OK

**Comment by kimrutherford** [comment]
It this what you are thinking of?:

![image](https://user-images.githubusercontent.com/90474/201005823-dcf1ea57-a60b-493e-85a5-07c456e7965b.png)

**Comment by ValWood** [comment]
yes, it could all be part of the red text? then it can't be ignored.

Maybe change the text to
Only the current unique systematic identifier for a gene is recognised by the list upload. Systematic IDs may be changed to synonyms if features are merged.  Locate the current ID via the simple search to update your input list if required. Others  identifiers could be removed from the gene set entirely (check the new and removed gene list for details).

to be completely explicit

**Comment by kimrutherford** [comment]
Hi Val.

I tried red first but thought it was a bit hard to read.  What do you think?:

![image](https://user-images.githubusercontent.com/90474/201182759-9e148f6c-7ff0-43f8-aefc-ac4907b16146.png)

**Comment by ValWood** [comment]
good point. Also the comment I wrote only applies to a systematic ID list.

More edits

Only the current unique systematic identifier OR the primary symbol for a gene is recognised by the list upload. Systematic IDs may be changed to synonyms if features are merged. Gene names may be relegated to synonyms if name ambiguities exist. Locate the current ID or gene symbol via the simple search and update your input list if required. Occasionally systematic identifiers are removed from the gene set if they are not considered to be coding (check the new and removed gene list for details).

**Comment by kimrutherford** [comment]
I've changed the text on my desktop.  It's here if you'd like to have a look:
https://desktop.kmr.nz/query/start_from/gene_list

**Comment by ValWood** [comment]
another set of edits (sorry)

Only the current unique systematic identifier OR the primary symbol for a gene is recognised by the list upload. 
Troubleshooting: Occasionally systematic IDs may be changed to synonyms when features are merged. Gene names may be relegated to synonyms if name ambiguities exist. To locate the current ID or gene symbol use the "simple search" in the header. Occasionally  identifiers are removed from the gene set if they are no longer considered to be coding (check the [new and removed gene list](https://desktop.kmr.nz/status/new-and-removed-genes))

**Comment by kimrutherford** [comment]
I've lost track: should we make the text red?

**Comment by ValWood** [comment]
I don't know. Maybe it is a bit jarring. we can do it in black I guess.

**Comment by kimrutherford** [comment]
We could also have a slightly red colour if that's better.  Or just leave it black while we think about it.  :-)

How about I deploy it with black and then we test some options live on Zoom sometime?

![image](https://user-images.githubusercontent.com/90474/201304448-f6769f68-7253-471d-bc90-1fb5c0ca76a1.png)

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
That's done for tonight's update.  It's on the dev site already: http://dev.pombase.kmr.nz/query/start_from/gene_list

**Comment by kimrutherford** [comment]
This change is deployed now I'm going to close this issue.  Please reopen if it needs tweaks.
