### ISSUE TITLE
change column heasing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1954]
<img width="876" alt="Screenshot 2022-11-10 at 18 48 54" src="https://user-images.githubusercontent.com/7359272/201181021-1c36f8d6-6304-4bb4-9d07-1f578df72cc6.png">

The column heading "double mutant"  
should just say "genotype"

@manulera  do you agree

**Comment by kimrutherford** [comment]
I've made that change on the dev site so we can see how it looks.  eg. http://dev.pombase.kmr.nz/reference/PMID:32546512

**Comment by manulera** [comment]
Looks good! Also the colour shading is nice as well

**Comment by kimrutherford** [comment]
OK, thanks Manu.  It will be on the main site in the morning.

**Comment by ValWood** [comment]
It looks good.
However, I am wondering if we should omit the product labels from this view completely since you can see them immediately with a mouse over.
It looks fine, but when you try to read the data it sort of gets in the way. For most people the gene labels are probably sufficient.
@manulera  what do you think. Are the products really helping?

**Comment by ValWood** [comment]
...They look fine in the collapsed view, but in the show details view they are a bit in the way...
