### ISSUE TITLE
odd annotation, can't trace

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1957]
I wondered why this annotation had no details 

<img width="798" alt="Screenshot 2022-11-11 at 12 06 53" src="https://user-images.githubusercontent.com/7359272/201337481-d3fb6f51-7ce7-4faa-aa84-1afab71ee434.png">

so I went to fix it, but there is only one allele for erh1/swd22 in this session, and it has no annotations?

<img width="505" alt="Screenshot 2022-11-11 at 12 07 22" src="https://user-images.githubusercontent.com/7359272/201337375-6bd52909-56c6-439c-8a84-2094ffae284e.png">

**Comment by kimrutherford** [comment]
Is it a legacy genetic interaction?

**Comment by ValWood** [comment]
yep.
