### ISSUE TITLE
Some unique extensions not displayed by default

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1960]
pka1

default
<img width="355" alt="Screenshot 2022-11-15 at 16 47 22" src="https://user-images.githubusercontent.com/7359272/202240323-711e5bf6-6d7d-4d4e-a375-416ec760c1e4.png">

full
<img width="743" alt="Screenshot 2022-11-15 at 16 47 27" src="https://user-images.githubusercontent.com/7359272/202240419-8fbe3135-ecfe-4603-9106-265ea7f6cc16.png">

**Comment by kimrutherford** [comment]
I think that's because of this annotation further down:

```
fungal-type vacuole  during  cellular response to glucose starvation
```

Which is more specific than:

```
cytoplasm  during  cellular response to glucose starvation
```

Due to: https://github.com/pombase/website/issues/45#issuecomment-289006688

**Comment by ValWood** [comment]
Yes , correct, its kind of weird, but correct.
it would be fixed by changing the annotations to cytosol which is sibling of vacuole.
