### ISSUE TITLE
Remove RNA genes from gene neighbour list?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1963]
Is this list on the gene pages useful?  Would it be more useful to filter out the RNA genes?  I was thinking about this because I was considering implementing pombase/website#1944. Without the JBrowse image the list of genes is going to look even weirder.

![image](https://user-images.githubusercontent.com/90474/203687069-a49ad514-f847-4dd5-84d4-f966ea0f70c3.png)

**Comment by kimrutherford** [comment]
I think it looks better:

![image](https://user-images.githubusercontent.com/90474/204077270-904081d7-88ab-4e48-8eac-b53dc340c8c9.png)

Should I go ahead and make that change?

**Comment by ValWood** [comment]
OK, we can see if anyone complains ;)

**Comment by kimrutherford** [comment]
OK, I've made that change for tonight's update.

**Comment by kimrutherford** [comment]
Done:

![image](https://user-images.githubusercontent.com/90474/204077270-904081d7-88ab-4e48-8eac-b53dc340c8c9.png)
