### ISSUE TITLE
Representing coordinate changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1965]
Currently 
https://www.pombase.org/status/gene-coordinate-changes

Does not show all changes
- - Does not show all historical changes
- - These recent changes are not yet included:
Protein sequence changes
2022-09-06
78 protein have been shortened (at the N-term). This set includes 34 published proteins (Apl4, Brc1, Cdc48, Cdt1, Cho1, Cmb1, Cut2, Cut6, Cwf26, Dbr1, Dri1, Elo2, Eri1, Lsd2, Lys2, Med13, Naa38, Nup107, Nup82, Orc2, Pof10, Ppt1, Rec24, Rga2, Rmt3, Rns1, RRpn7, Sap145, Skb1, Snf5, Snt2, Spn3, Tpp2, Trm1, and Tup12). Allele description changes and modification position changes are pending.

Does not always  include the source of all changes 
- - All changes that mention Solexa should be
https://www.pombase.org/reference/PMID:18488015 (even though the changes predate the paper, they were done as part of this work). That will cover most of the missing references in the webpage.

We discussed  
- [ ] replacing this page  with a link to a log file reporting all changes (including  the source info)
PLUS a before and after coordinates browser track (@manulera will this be possible if there are multiple changes?
- [ ] We would also need to align the annotated "warnings" on the gene pages
-- ensure that all have the source included
-- add links to log from  individual warning? or from this page https://www.pombase.org/term/PBO:0000070

**Comment by manulera** [comment]
I think we can close this one, addressed with https://github.com/pombase/website/issues/1993

**Comment by ValWood** [comment]
Did you add this ref [PMID:18488015](https://www.pombase.org/reference/PMID:18488015)
to everything with Solexa in the comment field?

**Comment by ValWood** [comment]
@manulera Close?
