### ISSUE TITLE
Show genetic interaction on genotype and phenotype pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1968]
From pombase/website#1348, which I closed, these two cases still need fixing:

> Should the table appear on the double mutant genotype page, like the ctf1Δ mmi1Δ page?

> Should the double appear on the single allele genotype pages? (ctf1Δ and mmi1Δ in the example above)

We'll add a menu on the left hand edge for navigation.  Currently genotype pages don't have one: https://www.pombase.org/genotype/aps1delta__erh1delta

Also:

> > - Should we add an interaction table on the phenotype pages to view interactions associated the phenotype of the double mutant?  Like on the [FYPO:0000080 page](https://www.pombase.org/term/FYPO:0000080) for "ctf1Δ mmi1Δ" annotated in [PMID:32546512](https://curation.pombase.org/pombe/curs/95ec493fb8fa90cf/ro/)?
> > - What about on the term page for the rescued phenotype (for example "increased acid phosphatase activity" in PMID:32546512)?  So on [the "increased acid phosphatase activity"/FYPO:0002243 page](https://www.pombase.org/term/FYPO:0002243) would it be useful to have a table of interactions where FYPO:0002243 is the rescued phenotype?

@manulera said:
> Yes! I think both would be great, an interaction table, including the interactions for which the phenotype is either on the single or on the double mutant.

**Comment by kimrutherford** [comment]
> Should the double appear on the single allele genotype pages?

Here's a screen shot of my prototype on my desktop (https://desktop.kmr.nz/genotype/mmi1delta__ppn1delta).

I've also added a Literature section for completeness.  It's not so useful in this screenshot but for some genotypes there is a bit of list of publications (eg. [any1 on my desktop](https://desktop.kmr.nz/genotype/any1delta))

![image](https://user-images.githubusercontent.com/90474/205433716-a91779e6-9777-4ee8-b1d4-36754f3cd140.png)

**Comment by kimrutherford** [comment]
The genotypes now appear on single allele genotype page in the prototype on my desktop.
We might want to think about changing the header of the table as "Genetic interaction" is a bit generic.

https://desktop.kmr.nz/genotype/aps1delta

![image](https://user-images.githubusercontent.com/90474/205474723-ee67171d-c8e9-48d7-a380-5cd78f9447bb.png)

**Comment by ValWood** [comment]
Table on the phenotypes page will be split
GI where FYPO:blah is the double mutant phenotype
GI where FYPO:blah is the single mutant phenotype

**Comment by kimrutherford** [comment]
> Table on the phenotypes page will be split
> GI where FYPO:blah is the double mutant phenotype
> GI where FYPO:blah is the single mutant phenotype

I have a prototype on my desktop: https://desktop.kmr.nz/term/FYPO:0002243
but I'm still testing the changes.

![image](https://user-images.githubusercontent.com/90474/206415331-62165bc9-87a4-40cb-b092-78c0a63c7350.png)

**Comment by manulera** [comment]
Looks perfect for me. I would just rename the menu items for consistency (either `single mutant` or `double allele`).

**Comment by kimrutherford** [comment]
> Looks perfect for me. I would just rename the menu items for consistency (either single mutant or double allele).

Good point.  Which would be best?

**Comment by manulera** [comment]
I would use `allele`

**Comment by kimrutherford** [comment]
Thanks Manu.  I've made that change.

I'll deploy the new code later so that it's in [dev site](http://dev.pombase.kmr.nz/term/FYPO:0002243) in the morning.  If it's all OK we can deploy it to the main site.

**Comment by kimrutherford** [comment]
> I'll deploy the new code later so that it's in [dev site](http://dev.pombase.kmr.nz/term/FYPO:0002243) in the morning. If it's all OK we can deploy it to the main site.

After some bug fixing the dev site is updated with these changes:
http://dev.pombase.kmr.nz/term/FYPO:0002243

I won't update the main site today (because I'm going to bed) but it will be updated automatically on Saturday morning.

**Comment by kimrutherford** [comment]
I think this can be closed.  If there are problems we can open new issues.
