### ISSUE TITLE
RNA length query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1969]
ncRNAs (ex tRNA, rRNA, snRNA and snoRNA) 
are aritrarily classified as short ncRNA <200 and long noncoding RNA lncRNA)

Jurg's ncRNA papers (Wilhelm/Atkinson) seem to only refer to lncRNA , but I don't remember there  being a nucleotide cut-off on the wilhelm paper.

I tried to do a down;oad,  but we don't include nucleotide download length  so it is not possible to get this info for RNA features.
I wonder if it can be included easily?

Could you provide me a list of any ncRNA under  200 nt?

**Comment by kimrutherford** [comment]
It's a quick job.  Maybe an hour or two?

Do you want the length after splicing?

**Comment by ValWood** [comment]
Good question, I would say before, but I don't know if the lncRNA short RNA distinction is pre or post splicing, but so far only 4  non-conventional ncRNA have annotated introns (1 is telomerase)

@bahler do you know?

**Comment by kimrutherford** [comment]
I think this query should be called "Transcript sequence length" (or something) and it should work for protein coding genes too for consistency.

**Comment by kimrutherford** [comment]
> Do you want the length after splicing?

It would be very easy to include the spliced and unspliced lengths as separate query types in the query builder.

**Comment by kimrutherford** [comment]
> It would be very easy to include the spliced and unspliced lengths as separate query types in the query builder.

I've done both in a prototype: https://desktop.kmr.nz/query

> Could you provide me a list of any ncRNA under 200 nt?

Here's the list: [gene_list.tsv.txt](https://github.com/pombase/website/files/10148148/gene_list.tsv.txt)

I got it using this query: https://desktop.kmr.nz/results/from/id/05d78fc2-ba4f-4aac-99f6-b68ee0873a41
(My desktop is on until 11am or so each day)

![image](https://user-images.githubusercontent.com/90474/205482958-4f1aa485-99f0-4988-9ad4-afe1507722d6.png)

**Comment by bahler** [comment]
I would go for post-splicing as the 200 nt cut-off is based on experiments to isolate RNAs for sequencing (and the standard method would bias against shorter RNAs <200 nt). These RNAs will normally be spliced as splicing largely occurs co-transcriptionally, but it will make a difference for only very few RNAs anyway. The 200 nt cutoff is essentially arbitrary, based on experimental reasons above, but widely used in the field.

**Comment by ValWood** [comment]
...prototype looks good though.

**Comment by kimrutherford** [comment]
> Here's the list: gene_list.tsv.txt

Sorry I got that wrong.  That list included protein coding genes.  Try this instead:
https://desktop.kmr.nz/results/from/id/a0653cbf-8ab2-400a-9d54-bbc7692fee4d

**Comment by kimrutherford** [comment]
I haven't added the RNA length options to the query builder yet.  I think they make the list too long.  Perhaps we could combine them into a sub-menu?

See also:
  - pombase/website#1873

**Comment by kimrutherford** [comment]
That's done now and the two new options are available under the "Transcripts and exons" sub-heading in the query builder.
