### ISSUE TITLE
problems with contents of genes annotated to this term list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#197]
term/GO%3A0004693

some things in this list are not "cyclin dependent protein kinases"

pombe has 6 "cyclin dependent protein kinases"

cdc2	SPBC11B10.09	cyclin-dependent protein kinase Cdk1/Cdc2
cdk9	SPBC32H8.10	P-TEFb-associated cyclin-dependent protein kinase Cdk9
lsk1	SPAC2F3.15	P-TEFb-associated cyclin-dependent protein kinase Lsk1
mcs6	SPBC19F8.07	TFIIH associated cyclin-dependent protein kinase Mcs6
pef1	SPCC16C4.11	Pho85/PhoA-like cyclin-dependent kinase Pef1
srb10	SPAC23H4.17c	cyclin-dependent protein Srb mediator subunit kinase Srb10

but this list has 25 genes

I looked at the first 2 (byr4 and cdc18)
I though the problem was likely to be "regulates relation" over molecular function, but it does not appear to be....I can't see any immediate reason whey these 2  would get annotated to this term?

**Comment by kimrutherford** [comment]
Sorry about that.  It looks like the list includes genes in the extensions.  I'll fix it.

**Comment by kimrutherford** [comment]
Fixed now.

**Comment by ValWood** [comment]
that will shorten a few lists ;)
