### ISSUE TITLE
Including FAQs in the documentation page?

### ISSUE THREAD

**Issue by manulera** [pombase/website#1972]
Hello @kimrutherford @ValWood 

I was looking at the Documentation page and I think people would expect to find there some of the things we addres in the FAQs (e.g. Data submission and formats).

Even if those pages are written in Q&A format, I think it may make sense to list the FAQ submenu below the current documentation menu. There is some overlap (gene pages mentioned in both), but I think it would be better.

The idea would be to have this FAQ menu:

![Screenshot 2022-12-07 at 14 50 11](https://user-images.githubusercontent.com/22526102/206210895-cb0c8424-c541-4914-9012-60fe09060f69.png)

As the Gene Pages menu item here:

![Screenshot 2022-12-07 at 14 50 57](https://user-images.githubusercontent.com/22526102/206211168-02776188-9404-4c0a-9e36-dc902208c252.png)

**Comment by ValWood** [comment]
Yes please!
