### ISSUE TITLE
add small non coding RNA to the advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1973]
after 
https://github.com/pombase/pombase-chado/issues/1043

 once  small non coding RNA is recognised it will be good to be able to search on this class under
product type https://www.pombase.org/query

**Comment by kimrutherford** [comment]
> once small non coding RNA is recognised it will be good to be able to search on this class under
product type

No problem.  We'll need to add an entry to the `gene_product_queries` config here:
https://github.com/pombase/pombase-config/blob/0081d5f5efd8b35540d932ffc0d91e25aabe616b/website/pombase_v2_config.json#L473

**Comment by ValWood** [comment]
SO:0002247 sncRNA
(I don't know why but the edit button on Git isn't working for me right now...)

**Comment by kimrutherford** [comment]
I checked in a change that adds sncRNA features to the query builder before I noticed the [loading bug](https://github.com/pombase/pombase-chado/issues/1043#issuecomment-1341904217).  It's not going to return any results until Friday morning.

**Comment by ValWood** [comment]
closing?
