### ISSUE TITLE
provide deep links to Proteome effects of genome-wide single gene, perturbations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1977]
We can now add external links for this dataset

Should we put it in the "Expression " section 
Text "protein level changes resulting from the individual knockout"

@manu does that text sound clear?

==

We now implemented both, the 'How to' page as well as gene specific URLs that can be integrated in pombase if you want:

[https://butterlab.imb-mainz.de/SpProtQuant/?data=KOLibrary&data2=searchByKOStrain&KOStrain=SPBC2D10.18](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbutterlab.imb-mainz.de%2FSpProtQuant%2F%3Fdata%3DKOLibrary%26data2%3DsearchByKOStrain%26KOStrain%3DSPBC2D10.18&data=05%7C01%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C6b37a6ba6fc64a50c60e08dadc3e2a56%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638064458972279385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=OM0JrQaArZuL8v3fZA6hXjjNBxiWztFHVZRgUdkszH8%3D&reserved=0) would lead you direcly to the data of the SPBC2D10.18 KO strain.
The second link [https://butterlab.imb-mainz.de/SpProtQuant/?data=KOLibrary&data2=searchByProtein&protein=SPBC2D10.18](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbutterlab.imb-mainz.de%2FSpProtQuant%2F%3Fdata%3DKOLibrary%26data2%3DsearchByProtein%26protein%3DSPBC2D10.18&data=05%7C01%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C6b37a6ba6fc64a50c60e08dadc3e2a56%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638064458972279385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=cvYTbFpzSlpKwme8%2FlfU1j7A3Oyi%2BqT0xKdfk2DVXL8%3D&reserved=0) leads directly to the expression of SPBC2D10.18 across all KO strains.

**Comment by ValWood** [comment]
@manulera can do with?
https://github.com/pombase/website/issues/1942

**Comment by manulera** [comment]
I can do this one, yes. For the legends I would say:

* Changes in the protein level of this gene product resulting from deletion of other protein coding genes.
* Proteomic changes resulting from the deletion of this gene.

**Comment by manulera** [comment]
Addressed in https://github.com/pombase/website/issues/1942, will close automatically if @kimrutherford approves merge

**Comment by kimrutherford** [comment]
It looks like this is done.

**Comment by manulera** [comment]
I guess it would not close automatically! I thought I had added one of those commit messages that makes the issue close

**Comment by ValWood** [comment]
Should those links be announced?

**Comment by manulera** [comment]
I will do it tomorrow!

Best,
Manu
