### ISSUE TITLE
target of section, redundancy

### ISSUE THREAD

**Issue by ValWood** [pombase/website#198]
There is quite a lot of duplication in this section (multiple refs).

Eventually we should do similar as we do for term annotation and hide redundancy.

We don't do this on the live site, so this can wait...

**Comment by ValWood** [comment]
not absolutely required for release, but I think the code already exists?

**Comment by kimrutherford** [comment]
Could you give me an example of duplication?

**Comment by ValWood** [comment]
Actually I thin this was done by another ticket...hiding refs etc

Let's keep this open until we group chat  to discuss ordering.

I wonder if for GO
directly inhibited/activated
substrate of
regulated by
localized by
as primary ordering , with alphabetical by gene within would be better.

**Comment by ValWood** [comment]
We discussed ordering in the other ticket

https://github.com/pombase/website/issues/299
