### ISSUE TITLE
Add lncRNA to query builder

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1981]
I noticed that we include lncRNA in the "All genes" commonly used query, but we can't select it in the "Product type" query.   Should we add it there?

![image](https://user-images.githubusercontent.com/90474/211748610-07554043-0ac6-4236-b8f5-c26d366a07cf.png)

**Comment by ValWood** [comment]
We can change **ncRNA** to lncRNA not because I have moved all of the ones under 200 nt to the new class sncRNA. This will also get around the current weirdness that our current use of ncRNA is ncRNA- (tRNA/snRNA/snoRNA/rRNA/sncRNA).

It we do keep ncRNA it should receive all of the  RNAs (total)

**Comment by kimrutherford** [comment]
> We can change ncRNA to lncRNA not because I have moved all of the ones under 200 nt to the new class sncRNA. This will also get around the current weirdness that our current use of ncRNA is ncRNA- (tRNA/snRNA/snoRNA/rRNA/sncRNA).

Should I go ahead and change ncRNA to lncRNA everywhere once pombase/pombase-chado#1019 is done?

**Comment by ValWood** [comment]
Should I go ahead and change ncRNA to lncRNA everywhere once https://github.com/pombase/pombase-chado/issues/1019 is done?

yes you can do. Only ncRNA 200 or over are not ncRNA.

Once this is done, we can use ncRNA to correctly mean rRNA + tRNA+ sncRNA + lncRNA + snRNA + snoRNA+ (i.e everything Except mRNA)

**Comment by kimrutherford** [comment]
I've changed all the ncRNA features to lncRNA.

**Comment by ValWood** [comment]
note, they are still ncRNA in the advanced search.

**Comment by ValWood** [comment]
I see, still on the gene pages, because you only just did it ;)

**Comment by kimrutherford** [comment]
> I see, still on the gene pages, because you only just did it ;)

Yep!  I meant to say that in my comment.  Should be there tomorrow morning.

I'll also change ncRNA to lncRNA in the "Product type" query before the morning.

> Once this is done, we can use ncRNA to correctly mean rRNA + tRNA+ sncRNA + lncRNA + snRNA + snoRNA+ (i.e everything Except mRNA)

We can change the "Product type" query so that ncRNA type returns all non-coding RNA genes if you think that's a good idea.  That will take maybe 2 hours of work.

**Comment by ValWood** [comment]
> https://curation.pombase.org/dumps/latest_build/logs/log.2023-01-15-21-23-11.chado_checks.GenotypeBackgrounds

definitely!

**Comment by kimrutherford** [comment]
I've made the config changes needed for lncRNA to work in the query builder.  I'm now changing the code so that ncRNA will show all RNAs.

**Comment by kimrutherford** [comment]
> We can change the "Product type" query so that ncRNA type returns all non-coding RNA genes if you think that's a good idea. That will take maybe 2 hours of work.

That's done for tonight's update.  I'll check it's working on Wednesday morning.

**Comment by kimrutherford** [comment]
> We can change the "Product type" query so that ncRNA type returns all non-coding RNA genes if you think that's a good idea. 

That change is on the main site now.  So if you query for [ncRNA](https://www.pombase.org/results/from/id/5b879fdf-ff8b-4fd3-a678-d388aefb8c47) you get the same results as querying for [all non-coding RNAs](https://www.pombase.org/results/from/id/266a2728-bd99-4e72-925c-b74d3a8ec49a).

Do you think we should change the label in the dropdown to make things more clear?  Like "ncRNA (all non-coding)"?  Or is it obvious enough as it is?

![image](https://user-images.githubusercontent.com/90474/213064411-e4923779-c794-4310-abba-3074d048c53e.png)

**Comment by ValWood** [comment]
Let's make that change. We can remove in 12 month or so, but for a while it may confuse those who regularly use that classifier.

I will announce soon anyway.

**Comment by kimrutherford** [comment]
> Do you think we should change the label in the dropdown to make things more clear? Like "ncRNA (all non-coding)"?

That's done for Thursday night's load.

**Comment by kimrutherford** [comment]
> That's done for Thursday night's load

Done!
