### ISSUE TITLE
Update gene characterization history

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1983]
we need to update the gene chracterization history page
Kim could you add the current totals as the end of 2022

https://www.pombase.org/status/gene-characterisation-statistics-history
it's supposed to be a year end snapshot of 
https://www.pombase.org/status/gene-characterisation
but sometimes  the dates are a bit random.

Even though the data types are a bit orthogonal, I'm quite attached to this data. Its what I used for 
https://royalsocietypublishing.org/doi/10.1098/rsob.180241 figure 1
It's a useful snapshot

@manulera  these classes come from the 
/colour labels in the contig files, so maybe you could pull out the numbers for each year end?

/colour=2 =published
/colour=7 =inferred role
/colour=10 = conserved unknown role
/colour=8 = unchracterized S. pombe specific
/colour= 10 = unchracterized  Schizosaccharomyces specific
(until Aug 2014 colour 10 was not used and colour 8 covered 8&10)

**Comment by kimrutherford** [comment]
> Kim could you add the current totals as the end of 2022

Done for tonight's load.

**Comment by manulera** [comment]
This is only for CDSs, right?

**Comment by ValWood** [comment]
yes, this is CDS only.

**Comment by manulera** [comment]
Is this something we wanted to include in the things that are ran overnight? Or since it is a once a year thing we just do it like we have so far? If so we can close I think

**Comment by ValWood** [comment]
@ValWood Provide table

**Comment by manulera** [comment]
Related to https://github.com/pombase/website/issues/2048#event-9594666043
