### ISSUE TITLE
possible bug, but most likey some PubMed glitch?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1984]
https://www.pombase.org/reference/PMID:36617881

page looks like this:

<img width="1094" alt="Screenshot 2023-01-20 at 20 15 43" src="https://user-images.githubusercontent.com/7359272/213797571-f711bcc5-8071-4ad8-b769-f8f659821c88.png">

**Comment by kimrutherford** [comment]
Turns out that there was a pubmed ID that contained a semi-colon from a db_xref.  The format isn't checked when they're read from the contig files.

That ID was causing the code that queries PubMed to quit early and not query the following IDs.

I've fixed the ID in time for the tonight's load.

```
 FT   lncRNA          complement(2381012..2382004)
 FT                   /db_xref="PMID:21511999"
 FT                   /db_xref="PMID:29914874"
-FT                   /db_xref="PMID:18641648;"
+FT                   /db_xref="PMID:18641648"
 FT                   /systematic_id="SPNCRNA.1293"
 FT                   /synonym="SPNCRNA.523"
 FT                   /product="non-coding RNA, LTR-associated"
```

**Comment by ValWood** [comment]
All back.
Sorry about that!
