### ISSUE TITLE
News item. Revised canonical 5' UTRs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1988]
Revised canonical 5' UTRs
We have revised the curated canonical 5’UTRs  using Transcription Start Sites (TSS) data (in vegetative growth/ minimal media) from the Cap Analysis of Gene Expression (CAGE) data provided by Thodberg et al (PMID:30566651 link to -> https://www.pombase.org/reference/PMID:30566651).

**Comment by kimrutherford** [comment]
That's done for the morning.
