### ISSUE TITLE
Add RNA 2D structure to RNA pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1989]
This should be possible with the r2dt-web web component :

 - https://github.com/RNAcentral/r2dt
 - https://github.com/RNAcentral/r2dt-web
 - https://r2dt.readthedocs.io/en/latest/widget.html

**Comment by ValWood** [comment]
SGD have just done this 👍 https://www.yeastgenome.org/blog/sgd-newsletter-summer-2023
Maybe we should add sooner.

**Comment by kimrutherford** [comment]
Try to embed as a widget on the tRNA, snRNA, snoRNA and rRNA pages (only).  It should be the default widget for those RNAs.

**Comment by kimrutherford** [comment]
> SGD have just done this 👍 https://www.yeastgenome.org/blog/sgd-newsletter-summer-2023

As far as I can see, the SGD pages have only schematic 2d RNA structure:

https://www.yeastgenome.org/locus/YNCQ0010W#overview

![image](https://github.com/pombase/website/assets/90474/112d0ee6-fab4-44fe-bd58-05841be21fd2)

Is that what we want?

The images are just embedded links to RNAcentral so would be easy to add to our gene pages:

https://rnacentral.org/api/v1/rna/URS00004C1880/2d/svg/

![RNAcentral](https://rnacentral.org/api/v1/rna/URS00004C1880/2d/svg/)

**Comment by ValWood** [comment]
they have the interactive structure on the "sequence" pages:
https://www.yeastgenome.org/locus/YNCQ0010W/sequence#secondary_structure

**Comment by kimrutherford** [comment]
> they have the interactive structure on the "sequence" pages:

Ah, thanks!

**Comment by kimrutherford** [comment]
I've had a look at the r2dt-web widget.  I can't see any configuration options for making it smaller.  I'm about to open some issues on their GitHub repo.

We also need to remove some of the text above and below.

All of this:

![image](https://github.com/pombase/website/assets/90474/7a350ee7-34b0-4f8f-bfd0-64b050bb9041)

and this:

![image](https://github.com/pombase/website/assets/90474/802f6b53-e269-42b0-b4c5-dc01e16209cb)

is part of the widget

That's why the SGD page has the text "Secondary Structure" twice:

![image](https://github.com/pombase/website/assets/90474/beb97a79-b1ef-42b4-8904-dd3455c62f62)

**Comment by ValWood** [comment]
Why do we need to remove the key and the other bits (don't want to repeat the title but presumably the other parts are useful?)

**Comment by kimrutherford** [comment]
> Why do we need to remove the key and the other bits (don't want to repeat the title but presumably the other parts are useful?)

If we match the other widgets then we only have a limited amount of vertical space - about 400 to 500 pixels .  The key on its own is 200 pixels high.

**Comment by kimrutherford** [comment]
I decided to just add the full 2D structure widget to the RNA pages because it was easier than making a proper widget.  It takes up a bit of space but it will probably do for now:

https://www.pombase.org/gene/SPRRNA.54

![image](https://github.com/pombase/website/assets/90474/ed85d60a-7232-45e0-a81a-b69550012a26)

**Comment by kimrutherford** [comment]
I noticed that this structure isn't available:

https://www.pombase.org/gene/SPRRNA.01
https://rnacentral.org/rna/URS0001BBE0D5/4896

**Comment by ValWood** [comment]
I think its greayt like that. The RNA pages don't have much else on them anyway

**Comment by ValWood** [comment]
> I noticed that this structure isn't available:

is this something to do with it being mitochondrial genome?

**Comment by kimrutherford** [comment]
> is this something to do with it being mitochondrial genome?

I tried running r2dt manually (https://rnacentral.github.io/r2dt-web/) with the sequence of SPRRNA.01 but it returned "The sequence did not match any of the templates."

I don't know what that means.  :-)

**Comment by ValWood** [comment]
So here are we trying to get structures for all
sn/sno,tRNA/rRNA?
If so, it is possible that  SPRRNA.01  is excluded because it  possibly doesn't have a recognisable 2-d structure...

**Comment by kimrutherford** [comment]
> So here are we trying to get structures for all
> sn/sno,tRNA/rRNA?

We're showing the widget for the types in your list ("tRNA, snRNA, snoRNA and rRNA pages (only)") but only if they the RNA has an ID like `URS0001BBE0D5` in Chado (because that's the ID that the widget uses).

**Comment by kimrutherford** [comment]
> If so, it is possible that SPRRNA.01 is excluded because it possibly doesn't have a recognisable 2-d structure...

I tried the sequence in a different RNA structure predictor.  The result is quite funky.  :-)

http://rna.tbi.univie.ac.at//cgi-bin/RNAWebSuite/RNAfold.cgi?PAGE=3&ID=rliF4Fn77w

![image](https://github.com/pombase/website/assets/90474/1ee75c7e-7fef-43e0-93a8-27cd52bcff24)

**Comment by ValWood** [comment]
It is, I suspect it is probably processed before it is folded. it's very long 2827 nt

**Comment by kimrutherford** [comment]
Decision from Zoom: change to widget

**Comment by kimrutherford** [comment]
There are a bunch of snoRNAs that have no structure.
Here are a sample:
https://www.pombase.org/gene/SPSNORNA.18
https://www.pombase.org/gene/SPSNORNA.04
https://www.pombase.org/gene/SPSNORNA.02
https://www.pombase.org/gene/SPNCRNA.498

For others the structures are a bit unconvincing:
https://www.pombase.org/gene/SPNCRNA.7474
https://www.pombase.org/gene/SPSNORNA.23

**Comment by kimrutherford** [comment]
> Decision from Zoom: change to widget

I've done that and deployed the change to pombase.org.  It's usable as is but I'm still tweaking things.

![image](https://github.com/pombase/website/assets/90474/8cd21fe7-d6e7-44b7-8bd4-ca601d5d1694)

**Comment by ValWood** [comment]
In this example, when you click on the structure, the rest of the page disappears:
https://www.pombase.org/gene/SPSNORNA.18

**Comment by ValWood** [comment]
>There are a bunch of snoRNAs that have no structure. Here are a sample: https://www.pombase.org/gene/SPSNORNA.18 
This one looked odd becasue it was shsort. I have extended it to 74 nt. It will  probable get a stucture in the futire

>https://www.pombase.org/gene/SPSNORNA.04 https://www.pombase.org/gene/SPSNORNA.02 https://www.pombase.org/gene/SPNCRNA.498

Have no structrue in RNACentral
(on the whole I would not expect snoRNAs to have  folded strucures becase they mainly have base pairing with other RNAs rather than internal base paiting




For others the structures are a bit unconvincing: https://www.pombase.org/gene/SPNCRNA.7474 This is the primary "unprocessed transcript"
We need to think of a better way to annotate this....

https://www.pombase.org/gene/SPSNORNA.23
Yes this looks odd...

**Comment by ValWood** [comment]
> I get this message because it has no structure. Is that what you mean?

I see now that the rest of the page its there, but there is a big blank section

**Comment by ValWood** [comment]
<img width="1260" alt="Screenshot 2024-06-26 at 08 14 42" src="https://github.com/pombase/website/assets/7359272/a225c3d8-1d54-4b00-9b44-0b7750bcd760">

**Comment by kimrutherford** [comment]
Yep.  Because of the way it's implemented, the space used by the widget is fixed.

Perhaps we should query RNACentral to find which RNAs have structures?  That way we can insert the widget only if there's a structure to show.

> on the whole I would not expect snoRNAs to have folded strucures

Should we not show the widget for snoRNAs in that case?

**Comment by ValWood** [comment]
Ignore that, the snoRNA's are probably OK
<img width="526" alt="Screenshot 2024-06-26 at 08 26 50" src="https://github.com/pombase/website/assets/7359272/fc724e04-23c9-4e6d-96d5-72b53c4cbbfd">

**Comment by kimrutherford** [comment]
> Yeah maybe query for structures...a pain...

No problem.  It's only a little bit of a pain.  :-)

Once we have a script that does the querying, re-running to update the data will be simple.

**Comment by kimrutherford** [comment]
> Yeah maybe query for structures...a pain...

Turns out it's easy to query RNACentral for pombe RNAs that have a structure.  Well done them!

From here: https://rnacentral.org/expert-database/pombase
Click on "Browse all PomBase sequences" to get to this list:
https://rnacentral.org/search?q=expert_db:%22PomBase%22

Then tick the "Secondary structure: available" checkbox to get:
https://rnacentral.org/search?q=expert_db:%22PomBase%22%20AND%20has_secondary_structure:%22True%22

Excellent stuff!

Here's the list: https://www.pombase.org/results/from/id/68cd3116-9daa-40be-8ece-0a62cc6f2964

I've add a file to SVN with this information:
```
pombe-embl/supporting_files/rna_genes_with_2d_structure.tsv
```

**Comment by kimrutherford** [comment]
> Perhaps we should query RNACentral to find which RNAs have structures? That way we can insert the widget only if there's a structure to show.

From Friday morning we'll only show the widget if the structure is available at RNAcentral.  That's a better user experience.

**Comment by ValWood** [comment]
I will write a short  announcement /news item for tomorrow.

Didi you try to hide the error?

**Comment by kimrutherford** [comment]
Yep, that's what I've fixed: from tomorrow the widget will be displayed only on RNA pages where there is a structure available from RNAcentral.  So no more errors from tomorrow.

**Comment by ValWood** [comment]
I meant hide the title!

**Comment by kimrutherford** [comment]
I've added a reminder to the PomBase calendar to update the file of genes with RNA structure predictions.  It's currently every two months but I can do it more regularly if think that's needed.

**Comment by ValWood** [comment]
they are unlikely to change. 6 monthly (or even annually) would probably be fine...

**Comment by kimrutherford** [comment]
> they are unlikely to change. 6 monthly (or even annually) would probably be fine...

It's now three times a year.  I sometime miss these things in the calendar so I thought 3 times would be better than 1 or 2.

**Comment by kimrutherford** [comment]
I've added a new item.  Let me know if you'd like any changes.

Is there anything else to do on this issue?

**Comment by ValWood** [comment]
no, all finished thanks!

**Comment by kimrutherford** [comment]
I haven't been able update this month as the RNAcentral export page gives me "Status: FAILURE".

I've contacted them about it.
