### ISSUE TITLE
removal of MF redundancy

### ISSUE THREAD

**Issue by ValWood** [pombase/website#199]
protein serine/threonine kinase activity
pom1	has substrate cdr2
pom1
pom1	has substrate pom1 involved in negative regulation of protein localization to plasma membrane
pom1	has substrate cdr2
pom1	directly activates cdr2 involved in regulation of cell size
pom1	has substrate pom1 involved in negative regulation of protein localization to plasma membrane
pom1	has substrate cdr2
pom1	has substrate tea4
pom1	has substrate mod5
pom1	has substrate syt22
pom1	has substrate rga7
pom1	has substrate pal1

protein serine/threonine kinase activity
has substrate tea4,mod5,syt22,rga7,pal1
has substrate pom1 involved in negative regulation of protein localization to plasma membrane
directly activates cdr2 involved in regulation of cell size

**Comment by ValWood** [comment]
protein serine/threonine kinase activity
has substrate tea4,mod5,syt22,rga7,pal1
has substrate pom1 involved in negative regulation of protein localization to plasma membrane
directly activates cdr2 involved in regulation of cell size


if multiple have the same extension should we do this:

protein serine/threonine kinase activity
has substrate tea4,mod5,syt22,rga7,pal1
has substrate pom1,mod5,syt22 involved in negative regulation of protein localization to plasma membrane
directly activates cdr2 involved in regulation of cell size

**Comment by ValWood** [comment]
question 1
has substrate pom1,mod5,syt22 involved in negative regulation of protein localization to plasma membrane

**Comment by ValWood** [comment]
yes go ahead...

**Comment by ValWood** [comment]
Just this for now....

**Comment by ValWood** [comment]
Exceptions, 
GO protein binding, bridging (this term required comma separated extensions anyway), so don't 

could be done like this

protein binding,bridging
binds bqt2 and sad1, binds bqt2 and rap1

**Comment by ValWood** [comment]
Need to add syntax for equivalent for FYPO where 2 genes comma separated in an extension

**Comment by ValWood** [comment]
Kim will check if there are any other times that different genes in the extension......

**Comment by kimrutherford** [comment]
> Need to add syntax for equivalent for FYPO where 2 genes comma separated in an extension

Could you give me an example of that?

> Kim will check if there are any other times that different genes in the extension......

There are some cases where there are two relations in an extension that have a gene as the relation range.  They seem to be mostly for modifications.  Here's an example from pcn1 (SPBC16D10.09):

   added by **rad8** added during S phase removed by **ubp15** required for error-free translesion synthesis

Currently the code always groups together the genes from the first relation in the extension that has a gene as the range.  I don't have any examples of extensions being grouped together where there are multiple relations with gene ranges.  Perhaps it's uncommon.

**Comment by ValWood** [comment]
>Need to add syntax for equivalent for FYPO where 2 genes comma separated in an extension

sometimes we can have both assayed protein, and assayed substrate, but they are different extensions....I'm not sure  if this is whet I meant?
Can anyone remember?

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by ValWood** [comment]
let's close. I'm not sure if everything is done, but we can open new tickets for stragglers.
