### ISSUE TITLE
mouse over warning on RNA pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1991]
This takes quite a long time to appear. In fact, I think some precision is required in the mouse over. Maybe the area could be larger. For a while, I thought that the pop-up wasn't working at all.

**Comment by kimrutherford** [comment]
> Maybe the area could be larger.

I've made it a bit larger.  Making it pop up faster will take slightly longer.  I'll do that tomorrow.

**Comment by kimrutherford** [comment]
> This takes quite a long time to appear.

I've fixed that for tonight's load.  Should be OK in the morning.
