### ISSUE TITLE
Can we automate the spotlight hash type thingymajig

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1992]
I just created 2 new spotlights  in:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json

{
      "title": "Bai et al., 2022",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["spotlight/2023-01-20_36108046_dnt1_Li_Sun_QW_Win.png"],
      "content": "Recovery from spindle checkpoint-mediated arrest requires a novel Dnt1-dependent APC/C activation mechanism.\nOriginally published in <a href='https://www.pombase.org/reference/PMID:36108046'>PLoS Genet</a>.",
      "reference_id": "PMID:36108046",
      "link_label": "Publication record in PomBase ...",
      "date_added": "2022-01-20",
      "show_on_front_page": true
},
{
      "title": "Wang et al., 2022",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["spotlight/******.png"],
      "content": "Ubiquitination of CLIP-170 family protein restrains polarized growth upon DNA replication stress.\nOriginally published in <a href='https://www.nature.com/articles/s41467-022-33311-y'>Nat Commun</a>.",
      "reference_id": "PMID:36138017",
      "link_label": "Publication record in PomBase ...",
      "date_added": "2023-01-20",
      "show_on_front_page": true
}

These take me *ages*  (around 15 mins each). But I think they could largely be automated  because we don't create the spotlight until the publication is live and so all of the info is available from  chado
https://www.pombase.org/reference/PMID:36108046

All we should really need to supply is 
2023-01-20_36108046_dnt1_Li_Sun_QW_Win.png  and the PMID and everything could be automated?

This would save me about 9 hours last year, and probably more in years with more curation.

**Comment by ValWood** [comment]
It just took me 45 minutes to do 2 spotlights, and I still haven't figured the problem
 (probably I am doing it in a really stupid way because I'm using the Git hub editing thing, but these are lots of potential places to make an error, this time I screwed up my template so I didn't realize what I had done wrong for ages). Anyway, I was wondering if we could use a "Git App"  for this? I don't know how it works but we have one for GO now to generate annotation update spreadsheets from a list of GO IDs. This seems a bit similar, since we only need to supply the PMID everything else should already be in the database?

@manulera 
@kimrutherford

**Comment by kimrutherford** [comment]
> I now get an errror

The file name looks fine to me.  It only waits 5 minutes before it starts running the checks.  Maybe it was uploaded too late?  It works best if you upload the images first.

**Comment by ValWood** [comment]
@manulera  has a little app for this.

**Comment by ValWood** [comment]
> It works best if you upload the images first.
Yeah I do but I made a m istake with that too ;)

**Comment by kimrutherford** [comment]
> The file name looks fine to me. 

I can see the problem now.

`assets/spotlight/2023-03-05-36695178-DAG-Foo.png`
should be
`spotlight/2023-03-05-36695178-DAG-Foo.png`
in the fle.

**Comment by manulera** [comment]
This is the small repo that I did

https://github.com/pombase/create_pombase_spotlight

You can use it here @ValWood 

https://pombase.github.io/create_pombase_spotlight/

You will still have to copy-paste the json in the right place, and add the files, but at least it creates the json chunk and resizes the image.
