### ISSUE TITLE
Table of new genes and deleted genes

### ISSUE THREAD

**Issue by manulera** [pombase/website#1995]
In this page:

https://www.pombase.org/status/new-and-removed-genes

Use the data from this autogenerated table from the genome_changelog repo.

https://github.com/pombase/genome_changelog/blob/master/results/genome_changes_summary_comments.tsv

Like in #1993, the columns `comment_addition` `reference_addition` `comment_removal` `reference_removal` are taken from the comments in the two files from the curation repo that were used to populate the current pombase website: `data_files/new-gene-data.tsv` and `data_files/removed-gene-data.tsv`. I have copied them into [the changelog repo](https://github.com/pombase/genome_changelog/tree/master/gene_changes_comments_and_pmids). I think it makes more sense in the future to edit them there.

The `category` column can be used to filter for either added genes or removed/merged genes. The possible values are:

* `added` include in new genes
* `added_and_changed` include in new genes
* `added_and_merged` maybe should not be included?
* `added_and_removed` maybe should not be included?
* `added_changed_and_merged` maybe should not be included?
* `added_changed_and_removed` maybe should not be included?
* `changed` not include
* `changed_and_merged` include in removed genes
* `changed_and_removed` include in removed genes
* `merged` include in removed genes
* `multi_CDS` I have to fix this manually eventually, ignore those for now. These were problematic genes that had several CDS with the same id 
    * [ ] For @manulera: fix this (https://github.com/pombase/genome_changelog/issues/36)
* `removed` include in removed genes

In the future, to add new comments to additions or removals, we can add extra rows to the files [here](https://github.com/pombase/genome_changelog/tree/master/gene_changes_comments_and_pmids).

And maybe, once this is working:

* [ ] Delete comment files from [here](https://github.com/pombase/curation/tree/master/data_files), since they are copied to the genome_changelog repo. 

* [ ] #2017

**Comment by kimrutherford** [comment]
Hi Manu.

It looks like you've done all the hard work and now we only need to use `genome_changes_summary_comments.tsv` to re-create `data_files/new-gene-data.tsv` and `data_files/removed-gene-data.tsv`.  Is that right or am I missing something?

**Comment by manulera** [comment]
Yes, just filtering with the `category` value.

**Comment by manulera** [comment]
I do this on my side, homogenise column names, add the merge_into in the comment. Kim may add links to the merged into ids (they should exist)

**Comment by manulera** [comment]
Manu: Replace the table of changes with the new one as well (add some documentation to explain what the file contains)

**Comment by manulera** [comment]
These files should be included in the monthly release

**Comment by manulera** [comment]
Hi @kimrutherford I addressed this. These tables:

https://github.com/pombase/genome_changelog/tree/master/results/pombase_tables

Should replace these ones:
https://github.com/pombase/curation/tree/master/data_files

In addition to this, I still have to add better documentation to the page where the changes are displayed https://www.pombase.org/status/gene-coordinate-changes

* [ ] Add brief description to the page.

**Comment by manulera** [comment]
Hi @kimrutherford. Actually I thikn I made the headers of the table in https://www.pombase.org/status/gene-coordinate-changes sufficiently self-explaining. let me know if you agree. If so, I won't add the description on top.

**Comment by kimrutherford** [comment]
Here's how the new and removed gene page will look after this change:
https://desktop.kmr.nz/status/new-and-removed-genes

It's quite big and slow.

Perhaps we should move the "removed" genes to a separate page?  And/or have a separate page for RNAs?

Val, what do you think?

**Comment by ValWood** [comment]
I agree, most people will be interested in either protein or RNA so definitely separate these (99.9% of RNAs are new)
Also separating new and removed would be helpful.

**Comment by ValWood** [comment]
Kim could you make the reference column narrower? At least it would be better  if the date never wrapped because it makes it difficult to  read the rows (the gene name never aligns)

**Comment by kimrutherford** [comment]
> Kim could you make the reference column narrower?

I've done that by change the HTML to encourage line breaks after commas in that column.

> At least it would be better if the date never wrapped

I'll see what I can do about that.  It doesn't happen in Firefox so I didn't notice the problem.  It's good that we test in different browsers.  :-)

**Comment by kimrutherford** [comment]
> At least it would be better if the date never wrapped

Should be improved now.  I checked in Chrome too this time.

https://desktop.kmr.nz/status/new-and-removed-genes

> I agree, most people will be interested in either protein or RNA so definitely separate these (99.9% of RNAs are new)
Also separating new and removed would be helpful.

Would be OK to replace the "New and removed genes" item in the "Genome status" menu with "New coding genes", "New RNA genes" and "Removed genes"?  Does that make the menu too long?

**Comment by manulera** [comment]
> Would be OK to replace the "New and removed genes" item in the "Genome status" menu with "New coding genes", "New RNA genes" and "Removed genes"? Does that make the menu too long?

I think it's fine. Probably good to have them separated if the tables are so long.

**Comment by ValWood** [comment]
We could also have this go to a "landing page" with the 4 links if that would be better
(would also be able to have a bit of blurb).

**Comment by kimrutherford** [comment]
> Separation of RNA and protein is addressed here:

Thanks Manu.

> We could also have this go to a "landing page" with the 4 links if that would be better

I've done that now.  Let me know if you think we need more explanation or other changes.

https://www.pombase.org/status/new-and-removed-genes

**Comment by ValWood** [comment]
Can we make it reverse date order so that the most recent change is at the top?

**Comment by kimrutherford** [comment]
> Can we make it reverse date order so that the most recent change is at the top?

I've made a pull request for Manu to review:
  - pombase/genome_changelog#46

**Comment by kimrutherford** [comment]
Hi @manulera

I should have tested my PR better.  I don't know why my previous change doesn't work.

I've tried again with better testing: https://github.com/pombase/genome_changelog/pull/48

**Comment by kimrutherford** [comment]
> Can we make it reverse date order so that the most recent change is at the top?

That's done now: https://www.pombase.org/status/removed-protein-coding-genes
