### ISSUE TITLE
add term to PomBase BP slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1996]
GO:0030643 intracellular phosphate ion homeostasis

**Comment by kimrutherford** [comment]
I've made that change.  It should be live on Sunday.

**Comment by ValWood** [comment]
doh actually I need to remove that term. It is covered by 
GO:0098771   
inorganic ion homeostasis

**Comment by kimrutherford** [comment]
> doh actually I need to remove that term.

OK, done.
