### ISSUE TITLE
Add links to /and data from  pdb

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1997]
- [ ]  I thought we had these in the external references, but we don't
- [x]  Add links to pdb next to AlphaFoLd if a structure is available

Later
- [x] display pdb structures when available   (maybe as the default).
probably we need some sort of heuristic to rank when there are multiple structures

**Comment by kimrutherford** [comment]
> Add links to pdb next to AlphaFoLd if a structure is available

We'll need to find out which genes have structures and then load information that into Chado.

>  I thought we had these in the external references, but we don't

We can add links like this: https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/P40847/structures
but we'll get a 404 if there are no structures for that protein.  Maybe that's OK as a temporary fix?

Once we have the PDB IDs in Chado we can hide the PDBe link if there are no structures for the gene.

The structures and links to PDB and AlphaFold are on the UniProt pages too.

> display pdb structures when available (maybe as the default).
> probably we need some sort of heuristic to rank when there are multiple structures

Perhaps we can embed a structure picker like UniProt does so we don't need to rank the structures?:

![image](https://user-images.githubusercontent.com/90474/215247863-404ba854-fb52-49cb-a342-be5bfc6914b5.png)

**Comment by ValWood** [comment]
> but we'll get a 404 if there are no structures for that protein. Maybe that's OK as a temporary fix?

lets wait until we have the IDs loaded

> structure picker 

Oh that would be cool!

**Comment by ValWood** [comment]
If you want to do this before the allele pages go ahead...

**Comment by kimrutherford** [comment]
> We'll need to find out which genes have structures and then load information that into Chado.

I was able to get quite a long way using the [PDBe Advanced search](https://www.ebi.ac.uk/pdbe/entry/search/index/?advancedSearch%3Atrue) to search for all Schizosaccharomyces PDB entries.

That took me to this [results page](https://www.ebi.ac.uk/pdbe/entry/search/index/?searchParams=%7B%22q_genus%22:%5B%7B%22value%22:%22schizosaccharomyces%22,%22condition1%22:%22AND%22,%22condition2%22:%22Contains%22%7D%5D,%22resultState%22:%7B%22tabIndex%22:0,%22paginationIndex%22:1,%22perPage%22:%2210%22,%22sortBy%22:%22Sort%20by%22%7D%7D).  I downloaded the results, with all columns included, and I've added the files to SVN:

  - pombe-embl/supporting_files/pdbe_all_schizosaccharomyces_entries.csv
  - pombe-embl/supporting_files/pdbe_all_schizosaccharomyces_entries.json

I think there's enough in the files to get what we need to load into Chado, but I have a few questions for Zoom sometime.

**Comment by kimrutherford** [comment]
> I've added the files to SVN:

Now moved to a more appropriate directory:
`pombe-embl/external_data/protein_structure`

**Comment by kimrutherford** [comment]
I've added a script in `pombe-embl/external_data/protein_structure` to process the raw PDB file into a file with pombe IDs.  The script is `process_pdbe_data_file.py` and the processed file is:
`pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv`
It has just three columns:
  - pombe systematic ID
  - PDB ID
  - taxon ID(s)

There's a README to show how to run the processing script: `pombe-embl/external_data/protein_structure/README.txt`

I've added a new step to the nightly script to load the PDB IDs into Chado and attach them to genes (using the `featureprop` table).

That's the easy bit.  On Monday I'll have a look at what is needed to implement something like the [viewer and table that UniProt has](https://github.com/pombase/website/issues/1997#issuecomment-1407298748).

**Comment by kimrutherford** [comment]
There is now a temporary implementation on the dev site.  It's temporary because it copes badly with window resizing and there is more in the table than we need.  I think we can remove the "--Select--" dropdowns and the column that says "PDB" on every row.  I'm working on a smaller replacement.

Here's http://dev.pombase.kmr.nz/gene/SPBC56F2.08c

![image](https://user-images.githubusercontent.com/90474/216857538-3d91a688-4025-49e9-8afb-33aa43da0941.png)

**Comment by kimrutherford** [comment]
I'm trying to think of ways to make the table smaller.  Everything is available on the PDB pages (which we will link to) so is there anything we can remove?

 - I was thinking of removing the "source" column and just showing PDB structures in this table
 - One link (to PDB or PDBe) is probably enough
 - There's no need for a download link 
 - The headers will take less space if they are not all in capitals

**Comment by ValWood** [comment]
I agree  we don't need so many links, but I don't know which link we need?
I wonder if the table could go underneath?

Good progress though...

**Comment by kimrutherford** [comment]
> I agree we don't need so many links, but I don't know which link we need?

I've added a link to PDBe for now.

> I wonder if the table could go underneath?

That made the page longer and pushed the annotation further down.  I think a small table to the right is a good use of space.

Here's my current prototype.  It should be in a releasable state soon but let's have a chat on Zoom.
It's available on my desktop until 1pm or so: https://desktop.kmr.nz/gene/SPAC26H5.06

![image](https://user-images.githubusercontent.com/90474/217162673-0851edd9-5063-4416-88f7-df41a4db2963.png)

**Comment by kimrutherford** [comment]
I've added a wiki page about updating the PDB data file in SVN:
https://github.com/pombase/pombase-chado/wiki/Update-the-PDB-data-file

**Comment by kimrutherford** [comment]
> Here's my current prototype. It should be in a releasable state soon but let's have a chat on Zoom.

It's all committed and will be in the dev site on Wednesday morning for testing.

**Comment by ValWood** [comment]
I think we will still need chain and residues.

Maybe we can not write. "Angstrom" just have the symbol and show "Angstrom" on mouse-over. that will save, like, 2mm ;)

**Comment by ValWood** [comment]
Corrected the comment above

**Comment by ValWood** [comment]
You got the colour working. UniProt haven't figured that one out!

**Comment by kimrutherford** [comment]
As discussed on the call I've changed the table of PDB structures to abbreviate the "Method" and to use "Res (Å)" instead of "Resolution" in the header.

I'm still working on getting the chain and position from the EBI APIs.

The change is only on my desktop for now:
https://desktop.kmr.nz/gene/SPCC1020.04c

![image](https://user-images.githubusercontent.com/90474/217428356-ebf790e2-fa37-4d7c-ae75-0e074377da32.png)

**Comment by ValWood** [comment]
That works!

**Comment by kimrutherford** [comment]
> I'm still working on getting the chain and position from the EBI APIs.

I found a PDBe API that returns a mapping between UniProt accessions and PDB IDs, which includes the chain and position in the JSON result.  It's also possible to lookup all the accessions with one API call which is just what we need.  I should have the chain and position on the dev site by the morning.

**Comment by ValWood** [comment]
Whoop!

**Comment by kimrutherford** [comment]
The changes are checked in.  I'll check the dev site in the morning.

https://desktop.kmr.nz/gene/SPCC584.04

![image](https://user-images.githubusercontent.com/90474/217507662-cd2869d0-a372-4865-a381-9fe2ec3a572e.png)

**Comment by ValWood** [comment]
Looks really good!

**Comment by kimrutherford** [comment]
I've fixed the problem with incorrect chain IDs that we noticed on the call.

So the chain and position for PDB ID 3e20 is now different on these two pages:
  - https://desktop.kmr.nz/gene/SPCC584.04
  - https://desktop.kmr.nz/gene/SPAC1834.01

The dev site will be fixed on Friday morning.

**Comment by kimrutherford** [comment]
I've add a mouse-over with the title and author.  Thomas Schalch only asked for the title but I thought the author(s) might be useful.  I've also added a thumbnail as an experiment.  Unfortunately I haven't been able to get the thumbnail to match the image orientation.  The thumbnails are stolen from the PBDe web pages.  (https://www.ebi.ac.uk/pdbe/entry/pdb/5we0 in the example below).

These changes are only on my desktop version for now: https://desktop.kmr.nz/gene/SPBC1778.02
They be on the dev site on Friday.

![2023-02-09_17-11](https://user-images.githubusercontent.com/90474/217716004-54753158-eb45-42e0-9aa0-6b075a87216a.png)

**Comment by ValWood** [comment]
That's very helpful!

**Comment by ValWood** [comment]
Where's Wally
Can you find  the rap1 fragment in the second or third image
https://desktop.kmr.nz/gene/SPBC1778.02

**Comment by ValWood** [comment]
>Unfortunately I haven't been able to get the thumbnail to match the image orientation.
I don't think that matters.
It's a useful addition.

**Comment by kimrutherford** [comment]
> It's a useful addition.

OK, great.

If it's all working on the dev site on Friday morning should we go ahead and release it to the main site?

**Comment by ValWood** [comment]
Yes lets do that!

As a follow up step should we  also add the structure to the publication pages?

**Comment by kimrutherford** [comment]
> As a follow up step should we also add the structure to the publication pages?

I think that would work.  Is it useful?

**Comment by kimrutherford** [comment]
> I think that would work. Is it useful?

I hope it's useful because I've implemented a prototype:
https://desktop.kmr.nz/reference/PMID:17937917

![2023-02-10_19-24](https://user-images.githubusercontent.com/90474/218018633-801a1904-9a58-4c60-ba26-c35ae352d142.png)

**Comment by ValWood** [comment]
I think so. It's only the same as including browser dataset access on  the sequence dataset pages.

**Comment by kimrutherford** [comment]
> I think so. It's only the same as including browser dataset access on the sequence dataset pages.

OK.

> If it's all working on the dev site on Friday morning should we go ahead and release it to the main site?

I suggest we release it today (if it's still works) but hold off on announcements until Monday.  That will give me time to finish the changes needed for structures on the publication pages.

One thing we should do is test on a few other browsers.  I'll try on Windows later.  Could one of you try Safari?  Thanks.

**Comment by ValWood** [comment]
Yes go for it.

I will try Safari now

**Comment by ValWood** [comment]
Safari, all seems to work OK, but the table always renders underneath the pdb viewer, even at full page size:

<img width="1426" alt="Screenshot 2023-02-10 at 11 23 13" src="https://user-images.githubusercontent.com/7359272/218082784-0341580c-5920-465b-b038-a4a5f8604427.png">

**Comment by kimrutherford** [comment]
> Safari, all seems to work OK, but the table always renders underneath the pdb viewer, even at full page size

By "full page size" do you mean that the Safari window was as big as you could get it?

I'm releasing the gene page PDB viewer to the main site now.  I'm still working on the publication page viewer.

**Comment by kimrutherford** [comment]
> I'm still working on the publication page viewer.

There are a few things to decide about the publication page view, like should we show a list of the genes for the current structure?  If so where?

On the gene page maybe we need to think about having links to the publication pages in the structure table?  I'd like to avoid making the table wider though.

**Comment by kimrutherford** [comment]
> I'm releasing the gene page PDB viewer to the main site now.

Done!  https://www.pombase.org/gene/SPBC56F2.08c

The PDB structures are also now visible on the publication pages of the dev site: http://dev.pombase.kmr.nz/reference/PMID:17937917

**Comment by ValWood** [comment]
> By "full page size" do you mean that the Safari window was as big as you could get it?

yes, sorry I mean full-screen

**Comment by ValWood** [comment]
> Done! https://www.pombase.org/gene/SPBC56F2.08c

Looks good. Will you do the announcemnt on Monday. We can tweet this too.

**Comment by ValWood** [comment]
> There are a few things to decide about the publication page view, like should we show a list of the genes for the current structure? If so where?

I think they could just be listed under the menu , they could be horizontal, like the JBrowse gene links, and they would need to wrap for large structures like the ribosome.

**Comment by ValWood** [comment]
>On the gene page maybe we need to think about having links to the publication pages in the structure table? I'd like to avoid making the table wider though.

1. Maybe we could make the id also function as the link to ePDB?
2.  I think we could compress Method and resolution into a single colum


Method (Å)
-- | --
X-ray(1.78)

**Comment by kimrutherford** [comment]
> yes, sorry I mean full-screen

Is the text a lot bigger than in Chrome?

**Comment by ValWood** [comment]
Ah yes sorry, my default text size was bigger in safari, they are the same

**Comment by kimrutherford** [comment]
I decided to try showing the publication and gene links just for the currently displayed entry because sometimes the list of genes for a publication is quite long.  For now it's only on my desktop.  It will be on the main site in time for us to chat about it on Tuesday.

https://desktop.kmr.nz/reference/PMID:36423630

![image](https://user-images.githubusercontent.com/90474/218377295-7bc870ab-5894-4c81-b8af-f90d3fe2158f.png)

![image](https://user-images.githubusercontent.com/90474/218377676-7d4bc94e-0a0a-49c4-a56f-c0b317509061.png)

![image](https://user-images.githubusercontent.com/90474/218377550-8418af4f-4b2e-494e-9f49-212406dad6c3.png)

**Comment by ValWood** [comment]
Looks good. 
1. tiny bug: z=11-17 in name list
<img width="183" alt="Screenshot 2023-02-13 at 08 35 12" src="https://user-images.githubusercontent.com/7359272/218411602-f2179d39-b83c-4cdb-b473-41ea880f0a6f.png">

2. MIght be better to have "author et al" to be consistent with the rest of the site?

**Comment by kimrutherford** [comment]
> tiny bug: z=11-17 in name list

That was me attempting to include the position and chain ID beside the gene names.  Fixed now.

> MIght be better to have "author et al" to be consistent with the rest of the site?

That's fixed too.

Both changes will be visible in the morning.

**Comment by kimrutherford** [comment]
There is one more small bug to fix which I'm working on now.  Some genes are duplicated on the pub pages.

https://www.pombase.org/reference/PMID:31010807

![image](https://user-images.githubusercontent.com/90474/218929347-cfc02217-c1e4-4588-99fe-b7bde8293a55.png)

**Comment by kimrutherford** [comment]
> There is one more small bug to fix which I'm working on now. Some genes are duplicated on the pub pages.

That's fixed now.

**Comment by kimrutherford** [comment]
> I thought we had these in the external references, but we don't

Is it still worthwhile to add the PDB links in the external references section?  Maybe it's good for completeness?

**Comment by ValWood** [comment]
> Is it still worthwhile to add the PDB links in the external references section? Maybe it's good for completeness?

I think  so.

**Comment by kimrutherford** [comment]
As discussed on Zoom, I've changed order of the PDB entries to match the order from the "best_structures" PDB API.  It might not be a complete fix but hopefully it will help.  The change will be visible on Thursday morning.

**Comment by kimrutherford** [comment]
> It might not be a complete fix but hopefully it will help.

I forgot to compare to the structure order on the UniProt pages.  It's completely different so maybe we need to rethink this.

**Comment by ValWood** [comment]
We can ask pdb. I notice they are not following us

**Comment by kimrutherford** [comment]
> Is it still worthwhile to add the PDB links in the external references section? Maybe it's good for completeness?

I've added those links but only when the gene has PDB structures.

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
Is this the longest ticket ever?

I'll open a new ticket with any outstanding tasks for pdb viewer.

**Comment by kimrutherford** [comment]
> Is this the longest ticket ever?

This is the winner with 78 comments: https://github.com/pombase/canto/issues/1491

For the website, this has 72 comments: https://github.com/pombase/website/issues/98

:-)

**Comment by kimrutherford** [comment]
I've just updated the PDB data.  Very little has changed.  The only new structure is for `tbf1` in this paper:
https://www.pombase.org/reference/PMID:38677290
which is already annotated.
