### ISSUE TITLE
spaces in allele names display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1999]
We have a small problem.

In gene nameing and allele description, we are mandating that people do not include space. So
https://www.pombase.org/genotype/vtc4-R262A,R264A-R262A,R264A-amino_acid_mutation-expression-not_assayed
allele name vtc4-R262A,R264A
 but the description s displayed with spaces here R262A, R264A aa

(I think this was possible  done to allow us to line break long descriptions)

**Comment by kimrutherford** [comment]
Could you example what the problem is?  I don't understand.

**Comment by ValWood** [comment]
It was just because the website displays the descriptions *with* spaces, this implies that this is the correct way to enter them into Canto.

It isn't really an issue, because we can deal with it with Canto prompts when users include inappropriate spaces.

**Comment by kimrutherford** [comment]
> I think this was possible done to allow us to line break long descriptions

I looked into this again and found a better way to do this in HTML that I didn't know about.  So the spaces should be gone, but the genotype will wrap to a new line after commas when needed.  Does that solve this issue?

**Comment by ValWood** [comment]
perfect!
