### ISSUE TITLE
phenotype query default haploid/diploid selection

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2002]
I think for the phenotype query, the default should be to have both haploid and diploid selected (non-sticky)

You can see that , for instance if you wanted all chromosome segregation phenotypes how many you lose with the filter on.

<img width="1134" alt="Screenshot 2023-02-08 at 17 49 44" src="https://user-images.githubusercontent.com/7359272/217776219-f56edda1-8eb0-4414-9198-d354b79161f3.png">

@manulera  do you agree?

I can't remember why we set it that way?

**Comment by manulera** [comment]
Sounds right to me, I don't know why it's like that, but probably chromosome segregation is one of the few cases where this would happen.

**Comment by ValWood** [comment]
That's true, except we may have many legacy alles which should probably be annotated as diploids, but aren't.
Anyway, I'm not sure how useful this particular filter is. I was writing a draft announcement because I don't think we ever told people when we we separated diploid on the gene pages, and added to the query interface.
@kimrutherford  do you remember?
I searched the pombe list archive and I couldn't see anything.

**Comment by ValWood** [comment]
Actually it must have been announced to some extent, because I reported this was corrected
https://github.com/pombase/website/issues/1949

**Comment by kimrutherford** [comment]
> I think for the phenotype query, the default should be to have both haploid and diploid selected (non-sticky)

I'll make that change now.  What do you mean by "non-sticky"?

**Comment by kimrutherford** [comment]
> I'll make that change now.

I've changed the code.   The fix will be visible on the main site on Friday.

**Comment by ValWood** [comment]
Sorry I mena "sticky" If youchange it to haplois or diploid only, when you come back it should revert to both checked

**Comment by kimrutherford** [comment]
OK, it does that.
