### ISSUE TITLE
Add 2 new explore PomBase rotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2003]
The rotations are getting a bit stale, we haven't updated in a while.

1
Explore JaponicusDB: PomBase's 'sister' database for fission yeast _Schizosaccharomyces japonicus_

We cloned PomBase to create a fully community-maintained resource for the emerging model _S. japonicus_; providing  genome browser, literature curation,  and query tools.

~2. Explore PomBase: Focus on Protein Structure
To make the functional clues from protein structures more immediately accessible we now display all available structures (400? experimental structures from pdb and predicted AlphaFold structures for  XX% of proteins)  at the top of every gene page.~
See [add example page]

~3. Explore PombeMine: 
As part of an Elixir-funded collaboration with the [InterMine team](http://intermine.org/) we have created [PombeMine](https://www.pombase.org/im/pombemine). Gene lists can be sent directly from PomBase query results pages directly to Intermine (under the “export” tab), providing direct (2 click) access to GO and phenotype enrichment tools.~

For the images we can just use logos for JaponicusDB and a nice structure  for the Protein structure feature

We should still keep microPublications in the current rotations

**Comment by ValWood** [comment]
Actually, I don't think we need one for structure.They will be difficult to miss. But we have no links between PomBase and JaponicusDB on the front page. The only within site links are in the ortholog section.

**Comment by kimrutherford** [comment]
> Explore JaponicusDB: PomBase's 'sister' database for fission yeast Schizosaccharomyces japonicus

That's done for the morning.
