### ISSUE TITLE
New Advanced query/ protein structure

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2004]
It would. be nice is we could do advanced query for any protein with a pdb structure.

This would enable users to easily locate a member of a large protein family (like ATPase , WD repeat or kinase), with a protein structure (by intersecting with a domain query).

I'm not sure where it would go in the list, it doesn't fit easily so it might need it's own category.

**Comment by kimrutherford** [comment]
> I'm not sure where it would go in the list, it doesn't fit easily so it might need it's own category.

I'm not sure either.  Perhaps we could add it under "Commonly used queries", at least initially?

**Comment by ValWood** [comment]
That would be OK!

**Comment by kimrutherford** [comment]
>  Perhaps we could add it under "Commonly used queries"

I've just implemented that.  It's currently only available on my desktop.
Here are the proteins with structures: https://desktop.kmr.nz/results/from/id/42d957d9-5e50-422a-9f16-cef39325aace

It will be on the main site tomorrow.

You'll also be able show the PDB IDs in the results table and download them.   I don't know how useful that is but it was quick to implement.

![image](https://user-images.githubusercontent.com/90474/218254713-00bfd5dd-0be4-4d9b-bbcc-4bf03e03bf93.png)

![image](https://user-images.githubusercontent.com/90474/218254741-fdc84e77-9473-4618-a07c-ffb49c534003.png)

**Comment by kimrutherford** [comment]
> It will be on the main site tomorrow.

https://www.pombase.org/results/from/id/6e8401aa-bab8-48fc-bbb7-c85d13ea10a2

**Comment by kimrutherford** [comment]
I think this is all done and announced.
