### ISSUE TITLE
possible bug , protein length with alternative transcriptd

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2005]
For crd1 the reported protein length is 389, but transcript 1 has  595 aa?

<img width="1131" alt="Screenshot 2023-02-12 at 13 46 27" src="https://user-images.githubusercontent.com/7359272/218570767-03a6a67a-e6ba-4024-8e4f-e4ae57d7b1b3.png">

**Comment by kimrutherford** [comment]
It was showing the protein length of transcript 2 instead of the primary transcript due to some very naff code.  Fixed for the morning.

**Comment by kimrutherford** [comment]
> Fixed for the morning.

It's fixed on the dev site but not on the main site yet.  I'm having trouble accessing the machine at Babraham and I'm waiting for help from them before I can update things.
