### ISSUE TITLE
PMID:19581297 publication page message

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2007]
https://www.pombase.org/reference/PMID:19581297
I put this through curation yesterday. It is classed as 'curatable' because I don't know how else to classify it  (structure is just a temporary bin to find the structure papers that need to go through curation).

I added genes, but no annotation, but I would like to keep it as 'curatable' because it has been read.
I submitted with the message "no data of avaiable types'.

This has the message:
This publication has no annotations in PomBase because it hasn't been curated yet. Please [contact the curators](mailto:helpdesk@pombase.org?subject=Request%20to%20contribute%20annotations%20for%20PMID:19581297) if you want to contribute annotations for this paper.

but it should really be somthing like "This publication has no annotations in PomBase because it has no data of available types"

**Comment by ValWood** [comment]
Actually we need to check this one. The structure presented in the image is S. cerevisiae Tom70. The linked gene is  pombe ssa1, one of the heatshock proteins. MAybe these are incorrectly flagged in the pdb?

**Comment by kimrutherford** [comment]
It's fixed for tonight's load so on Tuesday morning it should say:

This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types.
