### ISSUE TITLE
space below some structure views

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2008]
See
<img width="1205" alt="Screenshot 2023-02-17 at 18 46 52" src="https://user-images.githubusercontent.com/7359272/219781292-e94690d9-c938-45d8-a600-5961e15855e0.png">
<img width="1373" alt="Screenshot 2023-02-17 at 18 24 04" src="https://user-images.githubusercontent.com/7359272/219781375-39908a1f-843f-435b-9f09-013cb4d5191b.png">

**Comment by ValWood** [comment]
I'm wondering if it would be better to force the selection menu to always be to the right of the image, and have a scroll bar if they are too wide?

**Comment by kimrutherford** [comment]
I've fix the extra space for tonight's load.  I think it's better for the table to move underneath as needed because that works better on small screens like tablets and phones.
