### ISSUE TITLE
count of single genes annotated to a term

### ISSUE THREAD

**Issue by ValWood** [pombase/website#201]
I wanted this link:
http://pombase2.aska.gen.nz/term/FYPO%3A0001122
Single-allele genotypes associated with this term ...
http://pombase2.aska.gen.nz/term_genotypes/FYPO%3A0001122

to give me a count of genes.
Currently the count is genotypes

cdc13 (SPBC582.03)	G2/M B-type cyclin Cdc13	cdc13-117(C379Y)
.
.
.
and separated like this
cdc13 (SPBC582.03)	G2/M B-type cyclin Cdc13	cdc13+
.
.
.
cdc13 (SPBC582.03)	G2/M B-type cyclin Cdc13	cdc13Δ

need to group by gene and genotype.
Add count for gene (probably keep the count for genotype, although it is more arbitrary)

**Comment by kimrutherford** [comment]
Does the other link on that page give you what you were thinking of?:
  "Genes from single-allele genotypes associated with this term ..."

**Comment by ValWood** [comment]
Doh yes,
I didn't read it properly!
I do think that for single -allele genes should precede genotypes though?

Others?

**Comment by ValWood** [comment]
and the number is spot on ;)

**Comment by ValWood** [comment]
Actually the number here isn't correct...

![number is annotation](https://cloud.githubusercontent.com/assets/7359272/23772032/64f3d0b4-0511-11e7-96ca-3db9370c6210.jpg)


What is displayed int he list is correct, but the number is the number of annotations, not genes

**Comment by kimrutherford** [comment]
Whoops, now fixed.
