### ISSUE TITLE
Revise news item text

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2010]
<img width="630" alt="Screenshot 2023-02-21 at 08 44 43" src="https://user-images.githubusercontent.com/7359272/220412649-55ddc9b4-4fee-4fa6-966f-c7280414c8b8.png">

We have revised the curated 5’UTRs using Transcription Start Sites (TSS) data (in vegetative growth/ minimal media) from the Cap Analysis of Gene Expression (CAGE) data provided by [Thodberg et al](https://www.pombase.org/reference/PMID:30566651). All new gene structures were manually reviewed, around ~80 protein features had  N-terminal coordinate revisions to align with TSS data.

(Once we have the log, we can link to it)

**Comment by kimrutherford** [comment]
Done for tonight's load.
