### ISSUE TITLE
new druglist entry

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2011]
https://www.pombase.org/browse-curation/drugs-known-pombe-targets
drug name NSC624206  (catchy!)
gene uba1
Cellular target Inhibits thioester bond formation between Ub and Uba1 without affecting
adenylation activity
Process target, leave blank
PMID: 22274912

**Comment by kimrutherford** [comment]
Done for tonight's load.

**Comment by ValWood** [comment]
Add also PYR-41 (all same details and refernece)
Remove text  (PubMed link) from end of row

**Comment by kimrutherford** [comment]
> Remove text (PubMed link) from end of row

Should I remove the text from all rows or just that one row?

**Comment by kimrutherford** [comment]
Should we link to ChEBI: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:192973

**Comment by ValWood** [comment]
> Should I remove the text from all rows or just that one row?
Ah yes there are a few, no idea why they are there

> Should we link to ChEBI: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:192973


Please

**Comment by kimrutherford** [comment]
OK, done for tonight's load.
