### ISSUE TITLE
no link to publication page for single structure:

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2012]
e.g smg1

<img width="840" alt="Screenshot 2023-02-21 at 22 31 01" src="https://user-images.githubusercontent.com/7359272/220473691-0a0c3b6c-70d5-455b-b1fb-eda42b553adc.png">

I can't access the publication page, because the link to publication only seems to be present if there is >1 structure?

**Comment by kimrutherford** [comment]
The publication for that structure (PMID:26292707) isn't in PomBase, so we don't have a link.

There are some genes with one structure that have links, like: https://www.pombase.org/gene/SPAC15A10.08

**Comment by ValWood** [comment]
Ah right, I thought we had imported all of the 'missing'  publications associated with pombe structures?

**Comment by kimrutherford** [comment]
> I thought we had imported all of the 'missing' publications associated with pombe structures?

They are all loaded into Canto.

That publication is triaged as "Wrong organism" so it doesn't come through to Chado:
https://curation.pombase.org/pombe/view/object/pub/10938?model=track

**Comment by ValWood** [comment]
OK, that will be in my list. I didn't get to that one yet.

**Comment by ValWood** [comment]
that was the last wrong  organism, so everything will be there once I have done that one
