### ISSUE TITLE
Caltech URL links changed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2013]
links on
https://www.pombase.org/reference/PMID:34017941
have changed

https://data.caltech.edu/records/tfcg1-zdc84
https://data.caltech.edu/records/4grkw-d1474

We should check if there are any others on micropubs but I think these are the only ones.
v

**Comment by kimrutherford** [comment]
I've changed those links on the main site.  I can't see any other links to data.caltech.edu in the configuration file.

**Comment by ValWood** [comment]
That is the only one I remember
