### ISSUE TITLE
can't access publication for  structure

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2015]
https://www.pombase.org/gene/SPAC806.04c

It's this paper I think
https://www.pombase.org/reference/PMID:35314193

maybe it isn't linked to the pdb entry?

**Comment by ValWood** [comment]
I see it here
https://www.ebi.ac.uk/pdbe/entry/pdb/7u1y

**Comment by ValWood** [comment]
Probably not clear what the issue is. From the gene page, I can't access the publication from the structure.

**Comment by kimrutherford** [comment]
> maybe it isn't linked to the pdb entry?

That PMID is on the PDB web page but not in the data file I downloaded.  I'll contact them about it.

PMID:35314193 isn't found when using the PDBe advanced search either:

https://www.ebi.ac.uk/pdbe/entry/search/index/?searchParams=%7B%22q_pubmed_id%22:%5B%7B%22value%22:%2235314193%22,%22condition1%22:%22AND%22,%22condition2%22:%22Contains%22%7D%5D,%22resultState%22:%7B%22tabIndex%22:0,%22paginationIndex%22:1,%22perPage%22:%2210%22,%22sortBy%22:%22Sort%20by%22%7D%7D

It is possible to find other PMIDs:
https://www.ebi.ac.uk/pdbe/entry/search/index/?searchParams=%7B%22q_pubmed_id%22:%5B%7B%22value%22:%2223921640%22,%22condition1%22:%22AND%22,%22condition2%22:%22Contains%22%7D%5D,%22resultState%22:%7B%22tabIndex%22:0,%22paginationIndex%22:1,%22perPage%22:%2210%22,%22sortBy%22:%22Sort%20by%22%7D%7D

**Comment by ValWood** [comment]
I assume can close...
