### ISSUE TITLE
Consider a query builder option for finding gene with UTR introns

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2016]

**Comment by kimrutherford** [comment]
Prototype:

![image](https://user-images.githubusercontent.com/90474/221158512-66c082b8-0a0e-426a-8981-602c01f15cf1.png)

**Comment by ValWood** [comment]
nice ;)

**Comment by kimrutherford** [comment]
It's here if you'd like to try it: https://desktop.kmr.nz/query

**Comment by kimrutherford** [comment]
I've fixed a few remaining bugs with this code and it's checked in now.  I haven't checked in the configuration changes so it's only available on my desktop for now.

**Comment by ValWood** [comment]
I have been trying , it tells me the results are loading but they don't appear. It might just be  slow internet.

**Comment by ValWood** [comment]
perefect!

**Comment by kimrutherford** [comment]
Do you think we should release this change onto the main site?

**Comment by ValWood** [comment]
yes , why not. go for it.
v

**Comment by kimrutherford** [comment]
I forgot about this.  It's released now.
