### ISSUE TITLE
Add column headings to download files

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2019]
<img width="679" alt="Screenshot 2023-02-27 at 21 12 50" src="https://user-images.githubusercontent.com/7359272/221809427-f57bc8d8-e817-47f0-8f17-43823e4b1dd5.png">

**Comment by ValWood** [comment]
<img width="544" alt="Screenshot 2023-02-27 at 21 12 30" src="https://user-images.githubusercontent.com/7359272/221809520-761f635d-f48f-4a2b-af94-b78e0f92b671.png">

**Comment by ValWood** [comment]
<img width="759" alt="Screenshot 2023-02-27 at 21 12 17" src="https://user-images.githubusercontent.com/7359272/221809613-e84dec41-88ad-4852-8fa0-23c302ff1753.png">

**Comment by kimrutherford** [comment]
I've added headers to 5 files:
 - gene_IDs_names_products.tsv
 - gene_IDs_names.tsv
 - sysID2product.tsv
 - sysID2product.rna.tsv
 - pseudogeneIDs.tsv

I wasn't in time for the current load, but they be fixed on Thursday.

**Comment by kimrutherford** [comment]
Sorry, I forgot to `git push`.  I've done that now so it should be fixed on Friday.
