### ISSUE TITLE
Table formatting reduce width given to gene synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2020]
<img width="1328" alt="Screenshot 2023-02-27 at 18 58 19" src="https://user-images.githubusercontent.com/7359272/221809925-aa2cc56e-6df6-4788-9f40-835cc1f9f7a1.png">

**Comment by kimrutherford** [comment]
Fixed for the morning.  It will be a bit more balanced:

![image](https://user-images.githubusercontent.com/90474/222002768-f09d684a-6eae-402b-b47e-735f1b386eae.png)
