### ISSUE TITLE
which relations are allowed with expression data?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2023]
https://www.pombase.org/documentation/qualitative-gene-expression-data-bulk-upload-format
says:

The Extension column documents circumstances under which the RNA or protein level is observed (or changes). Follow one of these patterns: “during (GO:0000084)” - when a specific biological process, such as a response to a stimulus, is taking place, or during a cell cycle phase; “in_presence_of(CHEBI:18420)” - when a specific chemical substance is present; “occurs_in(GO:0005634)” when the level is observed in part, rather than all, of a cell.

but this does 't see like a complete list. I thought we had another page with these relations.

So first question, what is the complete list of relations we have used with expression data?

**Comment by kimrutherford** [comment]
> what is the complete list of relations we have used with expression data?

  - during
  - in_absence_of
  - in_presence_of
  - occurs_in

**Comment by ValWood** [comment]
OK, I thought there were  more
in_absence_of  is the only one not mentioned here:
https://www.pombase.org/documentation/qualitative-gene-expression-data-bulk-upload-format

**Comment by kimrutherford** [comment]
I've added `in_absence_of()` and re-formatted a bit.  Is this OK?:

![image](https://user-images.githubusercontent.com/90474/227401498-2c931efe-6c5f-4bce-b16e-f03b07b69664.png)

It will be on the main site by the morning.

**Comment by ValWood** [comment]
yep
