### ISSUE TITLE
reporting 2 translations for alternative transcripts when only one

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2026]
For alternative transcripts, sometimes we  report

<img width="549" alt="Screenshot 2023-03-16 at 09 58 47" src="https://user-images.githubusercontent.com/7359272/225651536-b66a4785-9a66-414e-806d-43f8afa62dd5.png">

which is true for zas1, wtf's

but for some (mei3, pgr2), the trancript is different, but there is only a single translation 

<img width="1081" alt="smae for pgr2" src="https://user-images.githubusercontent.com/7359272/225652116-647fce8f-0d01-4ea4-bb50-dc26c0c5fc39.png">

**Comment by kimrutherford** [comment]
I've fixed that.  I'll double check that the main site is fixed in the morning.

**Comment by kimrutherford** [comment]
That's fixed on the main site but should we change:
```
... with 1 translation
```
to:
```
... with 1 unique translation
```

so that's it's clearer?

**Comment by kimrutherford** [comment]
Done for tomorrow.
