### ISSUE TITLE
Display extra details from new PHAF file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2029]
See: https://github.com/pombase/pombase-chado/issues/1066

 - allele variant ( add url for genotype format variant syntax)               
 - condition details:
   - Temperature (degrees C)                
   - Chemical or agent (concentration units)
 - Chemical or agent dose   
 - Phenotype score / Phenotype score units
    - fitness_log2(0.123)
    - normalised_difference(-0.4234)
    - stored as properties in Chado (in `feature_cvtermprop`)

--------
Edit: [Some documentation](https://github.com/pombase/pombase-chado/wiki/Chado-Notes#extra-phenotype-details)

**Comment by kimrutherford** [comment]
We need to discuss where and how to display the extra details.  I think it would be good to have a chat and make a plan before Manu leaves PomBase, even if we don't implement things before then.

**Comment by kimrutherford** [comment]
> I think it would be good to have a chat and make a plan before Manu leaves PomBase, even if we don't implement things before then.

:-)

**Comment by ValWood** [comment]
We will need to borrow you for an hour or so @manulera !

**Comment by kimrutherford** [comment]
How's this for displaying the extra condition details?

The prototype is here: https://desktop.kmr.nz/term/FYPO:0000797

![image](https://github.com/pombase/website/assets/90474/d4135285-53df-41a5-8bdf-1c6123c9439e)

**Comment by ValWood** [comment]
Looks good!

(note that I dont see this   via the link)

**Comment by kimrutherford** [comment]
> (note that I dont see this via the link)

Ah, sorry.  The change was temporarily missing while I tested the fix for pombase/website#2113

**Comment by manulera** [comment]
Ah yes! That looks good

**Comment by kimrutherford** [comment]
> Looks good!

Great.  The changes will be visible in the morning.

We may need to tweak the formatting a bit because sometimes the details wrap onto the next line and look odd:

![image](https://github.com/pombase/website/assets/90474/1809afaa-a0c4-465c-8770-5c914524f36d)

**Comment by ValWood** [comment]
When we announce this we should say that the  temperature and concentration can only be collected for HTP submission at present , and update the docs there to specify *exactly* the format for including temperature and concentration.

https://www.pombase.org/documentation/phenotype-data-bulk-upload-format

**Comment by kimrutherford** [comment]
> The changes will be visible in the morning.

That's working now.  Here's good example: https://pombase.org/genotype/alg6delta

**Comment by ValWood** [comment]
I wonder if we could tidy the syntax of these fields a little so that it will be consistent when I document that these values are allowed for HTP data

Percentage are usually (0.1%) but occasionally 2 % (with or without space)

Molarity is usually  (20mM) but sometimes  (20 mM) (with or without space)

Somemtimes (2.5 % v/v) and sometimes  (2 % (w/v)) ( different use of brackets)

Just on https://pombase.org/genotype/alg6delta

Is it usual to mix molarity, ratio µg/ml, percentages  in a single study?

Anyway, just standardizing use of spaces and brackets would be helpful.

**Comment by kimrutherford** [comment]
> I wonder if we could tidy the syntax of these fields a little so that it will be consistent when I document that these values are allowed for HTP data

Moved to: pombase/curation#3627

**Comment by kimrutherford** [comment]
> "allele variant"
> what is that ? isn't it just the allele description?

They are the longer allele descriptions using chromosome coordinates like this:
`````
III:g.217516_218406del
`````

We haven't included these strings for all alleles yet but there are examples in the last column of this file:

`pombe-embl/external_data/phaf_files/chado_load/htp_phafs/PMID_34984977_phaf.tsv`

**Comment by ValWood** [comment]
I don't think we need to dispay it one the green pages , but it could eventiualy be added to the are pages as additional information?

**Comment by kimrutherford** [comment]
>   - Phenotype score / Phenotype score units:
>      -  fitness_log2(0.123)
>      -  normalised_difference(-0.4234)

Should these be display on the website?

Should we display them in the same style as extensions like we do for severity ("**has severity** high")?:

**normalised_difference** -0.4234
**fitness_log2** 0.123

**Comment by ValWood** [comment]
I'm not sure @manulera will these be meaningful to users?

**Comment by manulera** [comment]
Hi both,

I think this may make sense in the publication pages, to compare the extent since these numbers are only relevant when compared with those obtained in the same experiment. Not critical, but it can be neat.

In the gene page I don't think they would be useful.

**Comment by ValWood** [comment]
That's a good plan, only on the publication page for this detail.

**Comment by kimrutherford** [comment]
> I think this may make sense in the publication pages, to compare two phenotypes since these numbers are only relevant when comparing phenotypes obtained in the same experiment. Not critical, but it can be neat.

Thanks Manu.  Good plan.

> That's a good plan, only on the publication page for this detail.

That's implemented and will be on the main site tomorrow.  The new column is only visible in the detailed view and only on this page: https://www.pombase.org/reference/PMID:34984977

Let me know if the column name needs changing.

Unfortunately that page is still slow to load but I'm working on it: pombase/website#2100

![image](https://github.com/pombase/website/assets/90474/0e807605-0f23-43ff-80a6-564ba5c9cd54)

**Comment by kimrutherford** [comment]
If there's anything needed, let's open new issues.
