### ISSUE TITLE
feedback form/to helpdesk links on gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#203]
We'll need these for release. People don't really use them *very* much  for suggestions (although we don't really have any idea if a helpdesk ticket comes in via a webform or the e-mail address, standard stuff etc....), but there isn't really an impetus to do so with such infrequent updates...I  hope this will change.....

**Comment by kimrutherford** [comment]
As a temporary fix, I've added a contact email link on the gene pages.  It's at the top right on the gene pages.  If that's useful I can add it to other pages.

A real contact form needs a bit more work.

**Comment by ValWood** [comment]
thats fine for now.
Should we have that link on every page?

**Comment by kimrutherford** [comment]
> Should we have that link on every page?

I've added a basic email link to the term, genotype and publication pages.

**Comment by ValWood** [comment]
Furhter work is non urgent

**Comment by ValWood** [comment]
I think a form would be overkill here. An email link is just fine. Personally I hate forms...I just want to send a bloody message and get a copy.
