### ISSUE TITLE
Website fixes after merging wild type and not assayed in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2039]
After implementing:
  - pombase/pombase-chado#1076

we'll need to update:
  - the documentation:
    - https://www.pombase.org/documentation/genotype-page
    - https://github.com/pombase/website/blob/master/src/docs/documentation/genotype-page.md
  - and some code:
    - https://github.com/pombase/website/blob/master/src/app/shared/util.ts#L65
    -  ~~https://github.com/pombase/website/blob/master/src/app/pombase-query.ts#L388~~ - no change needed

The text in the query builder might need tweaking too:

![image](https://user-images.githubusercontent.com/90474/234215355-6022e9b7-f4eb-405f-9fce-7f12a3545ef3.png)

**Comment by manulera** [comment]
That's fine as it is, we think.

**Comment by kimrutherford** [comment]
This is done now, but not in time for the current load.  I'll check things on Wednesday morning.

**Comment by kimrutherford** [comment]
> https://www.pombase.org/documentation/genotype-page

I've updated the text.  I'll update the screenshots once tomorrow's load it finished.

**Comment by kimrutherford** [comment]
> I'll check things on Wednesday morning

It's all working now.  I'll update the screenshots then close this issue.

**Comment by kimrutherford** [comment]
> I'll update the screenshots then close this issue.

I've done that now.  I can't update the main site because oliver1 is offline.
