### ISSUE TITLE
transcript length

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2040]
This query currently does not seem to be working. I can't specify a maximum lenght.

**Comment by kimrutherford** [comment]
> transcript length

Do you mean RNA length?  That's working for me:

![image](https://user-images.githubusercontent.com/90474/234582789-82ae0a87-eb02-47ad-900d-3c863e0caf46.png)

**Comment by ValWood** [comment]
ignore I was using the exon query. Too tired...
