### ISSUE TITLE
Gene page structure history docs not linked

### ISSUE THREAD

**Issue by manulera** [pombase/website#2041]
Hi @kimrutherford

I think this page https://www.pombase.org/documentation/gene-page-gene-structure-history

should be linked from the gene page section, with the info icon like "External references" below

![Screenshot 2023-05-12 at 15 12 35](https://github.com/pombase/website/assets/22526102/5cbf0f41-e82d-4ca2-8679-6d77bb843cd8)

**Comment by kimrutherford** [comment]
Good plan.  I've done that.

**Comment by manulera** [comment]
Nice!
