### ISSUE TITLE
Separated structure changelog for RNA and protein genes

### ISSUE THREAD

**Issue by manulera** [pombase/website#2043]
Hi @kimrutherford, I have separated the gene-coordinate-change-data into RNA and protein coding genes, as we discussed, you can find the two tables here:

https://github.com/pombase/genome_changelog/tree/master/results/pombase_tables

`gene-coordinate-change-data-RNA.tsv` and `gene-coordinate-change-data-protein-coding.tsv`

That's to make this page: https://www.pombase.org/status/gene-coordinate-changes

Separate into two, like this page: https://www.pombase.org/status/new-and-removed-genes

Once you do that, you can remove the file `results/pombase_tables/gene-coordinate-change-data.tsv` from the allele_qc repository since it will not be used anymore (it's no longer updated when the action runs).

**Comment by kimrutherford** [comment]
Thanks Manu!

That change will be visible tomorrow.

**Comment by kimrutherford** [comment]
> That change will be visible tomorrow.

That's live now:
https://www.pombase.org/status/gene-coordinate-changes

The page looks a bit silly since it's just a title and two links.  So before closing this issue, I'll add a sentence or two of documentation.

**Comment by kimrutherford** [comment]
> The page looks a bit silly since it's just a title and two links. So before closing this issue, I'll add a sentence or two of documentation.

We have separate issue for that:
 - #2017

**Comment by kimrutherford** [comment]
Thanks for spotting that!  It's fixed now.
