### ISSUE TITLE
Make an alias for https://www.pombase.org/spombe/query/builder

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2044]
Seen in an older paper: https://www.pombase.org/spombe/query/builder

**Comment by kimrutherford** [comment]
URLs like that now redirect to https://www.pombase.org/query

> Seen in an older paper

Examples:
  - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4596657/
  - https://plos.figshare.com/articles/dataset/_5FU_induced_RNA_processing_genes_in_S_pombe_/840138/1
  - https://www.academia.edu/85993074/An_Ancient_Yeast_for_Young_Geneticists_A_Primer_on_the_Schizosaccharomyces_pombe_Model_System
  - https://www.cell.com/cell/pdfExtended/S0092-8674(15)01425-7

It's also in an old news item - "PomBase web site fully live":

> The updated site features a Gene List Search that provides behavior equivalent to GeneDB’s List Download. You can now type or paste lists into the Gene Systematic IDs and Gene Names filters, and use the Query History to combine a gene list search with other search options. For convenience, there is a direct link to a search page pre-configured to accept a list of systematic IDs available in the Find menu, on the Find page, and here: [http://www.pombase.org/spombe/query/builder?filter=12](https://www.pombase.org/spombe/query/builder%3Ffilter%3D12)

Maybe we should remove that item or add a disclaimer at the top?

**Comment by ValWood** [comment]
Add a disclaimer, I like to keep the news history intact. Never know when we might want to check a date

**Comment by kimrutherford** [comment]
> Add a disclaimer, I like to keep the news history intact. Never know when we might want to check a date

OK, I've checked in that change for tonight's update.
