### ISSUE TITLE
Update to latest PDB data

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2045]

**Comment by kimrutherford** [comment]
There are some existing PDB entries that have now have associated PMIDs.  These publications should have structures on gene pages and on publication pages after the update:
https://www.pombase.org/reference/PMID:36774373
https://www.pombase.org/reference/PMID:27354705

There are also 15 new pombe structures in the data, all from:
https://www.pombase.org/reference/PMID:37076472

There is a structure for PMID:37192628 which PDB says is from pombe, but it's not in PomBase.  I had a look and it mentions pombe twice in the paper: https://www.sciencedirect.com/science/article/abs/pii/S1097276523003167?via%3Dihub

**Comment by kimrutherford** [comment]
I've updated the mapping file with the latest data: `pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv`

(See `pombe-embl/external_data/protein_structure/README.txt` for details)

I've also made a file for japonicus: [japonicusdb/japonicus-config#96](https://github.com/japonicusdb/japonicus-config/issues/96#issuecomment-1582419094)

**Comment by ValWood** [comment]
We should do a Japonicus news item for structures!

and let @snezhkaoliferenko know, for @japonicusdb

**Comment by kimrutherford** [comment]
> We should do a Japonicus news item for structures!

In progress!: https://github.com/japonicusdb/japonicus-config/issues/96

**Comment by snezhkaoliferenko** [comment]
THANK YOU
________________________________

**Comment by kimrutherford** [comment]
> Once the new data is loaded I'll check that all these changes actually happened on the website.

The new structure are on the website.  There's a separate issue about japonicus.

I've made separate curation issue about PMID:27354705 and PMID:37192628:

  - https://github.com/pombase/curation/issues/3505
  - https://github.com/pombase/curation/issues/3506
