### ISSUE TITLE
missing reaction

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2046]
I noticed there isn't a reaction 
https://www.pombase.org/term/GO:0042054

but I see this reaction in uniprot

https://www.uniprot.org/uniprotkb/O74467/entry

**Comment by kimrutherford** [comment]
The only reference to RHEA:10024 in the GO OBO file is in the definition of this obsolete term:

```
[Term]
id: GO:0018024
name: obsolete histone lysine N-methyltransferase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: S-adenosyl-L-methionine + histone L-lysine = S-adenosyl-L-homocysteine + histone N6-methyl-L-lysine. The methylation of peptidyl-lysine in histones forms N6-methyl-L-lysine, N6,N6-dimethyl-L-lysine and N6,N6,N6-trimethyl-L-lysine derivatives." [RHEA:10024]
```

GO:0042054 does have any xrefs.  Maybe it needs one for RHEA:10024?

**Comment by ValWood** [comment]
right that makes sense
