### ISSUE TITLE
Improve characterization data and provide a graph

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2048]
I think that we are beginning to see an 'uptick' in the number of unknowns characterized.
It would be useful to graph this data on the curation stats page
https://www.pombase.org/status/gene-characterisation

The historical data is here
https://www.pombase.org/status/gene-characterisation-statistics-history
(Ideally we would reparse the colour= qualifier from the EMBL files at each year end)

I'd like to start promoting the unknown stuff a bit more widely. There is definitely a lot of increased interest in them. An accessible graph would be very useful for tweeting etc.

**Comment by ValWood** [comment]
Step 1
Manu will extract the colour data from the contig files

/colour=2 =published
/colour=7 =inferred role
/colour=10 = conserved unknown role
/colour=8 = uncharacterized S. pombe specific
/colour= 12 = uncharacterized Schizosaccharomyces specific

Note that until Aug 2014 colour 12 was "S. pombe specific protein families" 
and colour 8 was "unpublished sequence orphans" 
(i.e both 8 and 12 were fission yeast specific, but there was a bit more confidence for the ones present in muti copy)

After 2014, we other fission yeast genomes become available. The status were re-evaluated so that
"colour 12" were those conserved in pombe and at least on other fission yeast), and colour 8 were those only present in S. pombe.

In  we can combine these bins  in a graph as a "fission yeast specific" bin because that will work for all use cases.

**Comment by manulera** [comment]
Hi @ValWood @KimRutherford. This is done now. You can see the resulting graph in here:

https://github.com/pombase/genome_changelog/blob/master/gene_characterisation_status/results/figure.svg

The numbers do not exactly match the ones in the page:

|What|Website|Script|
|------|------|-----|
|published|2509|2502|
|biological role inferred|1916|1912|
|conserved unknown|369|375|
|Fission yeast unknown|263|263|

The script keeps only CDS that have a systematic id, and only one transcript per locus. Lower numbers in the script can be because I do not count multiple transcripts, and because I do not use features without a systematic id. This probably does not fully account for all discrepancies, but the numbers are close enough.

**Comment by ValWood** [comment]
Hmm, I expected the current numbers to match exactly the website. The website query is gene based, not transcript based and as far as I know there are no CDS loaded without systematic IDs. Is your svn repository up to date? I updated some in the past week, it was possibly 2502 published last week (I thought it was 2503) but I could be mistaken.

This is the query from advanced search:
https://www.pombase.org/results/from/id/10833211-5c75-4e5f-b0c7-c4d34d405fca
2509 genes.

**Comment by ValWood** [comment]
I like the graph, although progress is still as slow as it was (which will please Jurg). I thought we were seeing an increase for pombe, but the numbers are still so small it doesn't seem so.
Basically I'm not going to finish this before I die!

**Comment by manulera** [comment]
Hi @ValWood here you can find a table with the ids and their colour. See if you can spot the differences. I was not running on the latest version, but on the closest one to the first of the month, so now it looks better, but still the numbers do not match.

https://github.com/pombase/genome_changelog/tree/master/gene_characterisation_status/latest_revision

```
published	inferred_role	conserved_unknown	fission_yeast_unknown
2508	1912	369	263
```

**Comment by manulera** [comment]
> telomeric.contig?

I am not using that file. Since when is it there?

**Comment by ValWood** [comment]
A long time, I can't remember precisely  the contig was published in 2008 so shortly after that I think. I don't think there are any gene changes, or published genes in there so it won't affect other stuff (except we described these as 'new genes' when they were added.


Systematic ID | Gene name | Product description
-- | -- | --
SPBC460.01c |   | amino acid transmembrane transporter
SPBC460.04c |   | sulfonate/alpha-ketoglutarate dioxygenase
SPBC460.02c |   | translation elongation factor, glutathione S-transferase
SPBC460.05 |   | transmembrane transporter
SPBC460.03 | vba2 | vacuolar amino acid uptake transporter

**Comment by ValWood** [comment]
def  before 2012
https://www.pombase.org/reference/PMID:20944394

**Comment by ValWood** [comment]
Sorry about that, it probably seemed a bit picky but I always worry when things aren't as I expected that there is some other problem that we missed. It's a sort of OCD I think!

If there is a remaining off-by one error, that could be the gene in the mating type contig, but that shouldn't really be there.

**Comment by manulera** [comment]
No, it's good! Actually I had not realised I was not using the telomeric file at all for the changelog, so it's good. I am almost done fixing that.

**Comment by manulera** [comment]
Now it's fixed, I think. The latest numbers are in the same place:

https://github.com/pombase/genome_changelog/tree/master/gene_characterisation_status/latest_revision

**Comment by ValWood** [comment]
Yep, thanks all balances. This is great. The graph will be useful and it is nice to have accurate numbers for talks etc.

The current graph goes from 2014, is it possible to  go back to 2006 (or even earlier, but that might represent when the genome was contiguated). It should work since we are combining colour 8 and colour 12 and  the combined bin represents fission yeast specific (even thought the meaning of the split between the 2 changed). The graph will show the 'slow down' more clearly. 


@kimrutherford We could host the image on 
https://www.pombase.org/status/gene-characterisation
and
https://curation.pombase.org/pombe/stats/annotation pages
and we can archive
https://www.pombase.org/status/gene-characterisation-statistics-history

**Comment by manulera** [comment]
The graph starts in 2004

https://github.com/pombase/genome_changelog/blob/master/gene_characterisation_status/results/figure.svg

**Comment by manulera** [comment]
I added axis labels, if you are going to use the graph.

**Comment by ValWood** [comment]
Assigning to Kim not for website changes

**Comment by kimrutherford** [comment]
Thanks for implementing that Manu.

Val, where should we put the graph on the website?

**Comment by ValWood** [comment]
On this page, above the table
https://www.pombase.org/status/gene-characterisation

remove this sentence from the bottom of the page
A set of [historical data](https://www.pombase.org/status/gene-characterisation-statistics-history) recorded at various intervals is available.

then, we no longer need to link to this page
https://www.pombase.org/status/gene-characterisation-statistics-history
(we now have the numbers if asked, instead of these erratic snapshots)

Add the title for the graph
Protein-coding gene characterisation status changes

**Comment by kimrutherford** [comment]
I've added the new diagram to the website docs.  It should look a bit like this tomorrow:

![image](https://github.com/pombase/website/assets/90474/9a45cfe2-5540-4b44-9ce2-30915411e241)

**Comment by kimrutherford** [comment]
The diagram is on the main site now: https://pombase.org/status/gene-characterisation

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
No looks great, thanks both!
@manulera

**Comment by ValWood** [comment]
I will wait for the uptick!

**Comment by ValWood** [comment]
Can this go under the "overviews" menu in addition to "genome status"

**Comment by ValWood** [comment]
Also we should link to:

existing
Note: You can retrieve current lists of genes with each characterisation status using the [advanced search](https://www.pombase.org/query). Select the Characterisation status query, then choose a status from the pulldown menu, and submit.

Add 
A list of "Priority unstudied genes (vertebrate orthologs, unknown process, protein coding)" is updated daily

link https://www.pombase.org/status/priority-unstudied-genes

**Comment by ValWood** [comment]
Answers the question in
https://github.com/pombase/website/issues/2084

**Comment by kimrutherford** [comment]
I've added the link to the Priority unstudied genes page and added the gene characterisation status link to the Overviews menu.

**Comment by kimrutherford** [comment]
The changes I made for adding the gene characterisation graph have broken the JaponicusDB nightly build.

**Comment by kimrutherford** [comment]
> The changes I made for adding the gene characterisation graph have broken the JaponicusDB nightly build.

Should be fixed now.  I'll check on Tuesday.

**Comment by kimrutherford** [comment]
> The changes I made for adding the gene characterisation graph have broken the JaponicusDB nightly build.

That's fixed now.
