### ISSUE TITLE
Rearrange menu items

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2049]
New menu:
  - Overviews
    - move overviews from Genome Status menu
    - include DNA binding list
    - and drug list

Move
  - Curation statistics to Community and About
  - Community curated pubs to Community
  - Remove PomBase curated publications

(See #901)

**Comment by kimrutherford** [comment]
Should we include the "Genome overview" menu item in the Overviews menu?

**Comment by kimrutherford** [comment]
I've made those changes but they aren't in the main site yet.  If you'd like to check before it goes live, have a look at my desktop: https://desktop.kmr.nz/
(until 1pm or so)

Let me know if there are other changes to make.  I think we talked about some other ideas but can't remember.

**Comment by ValWood** [comment]
> Should we include the "Genome overview" menu item in the Overviews menu?

I guess it doesn't harm

**Comment by ValWood** [comment]
I didn't say explicitly , but this can go live.

**Comment by kimrutherford** [comment]
OK, I've checked in the changes.  It will be visible on Thursday morning.

**Comment by kimrutherford** [comment]
The rearranged menus are now on the main site.  Let me know if there are other changes to make (or if I forgot something).

![image](https://github.com/pombase/website/assets/90474/6dde7450-095a-4f8e-b23b-3773c5b36bf8)

**Comment by ValWood** [comment]
Much better!

@Antonialock you can find drug targets and DNA binding sites here ^

**Comment by Antonialock** [comment]
no more googling! 🥳

**Comment by kimrutherford** [comment]
We should change the JaponicusDB menus as well.

**Comment by kimrutherford** [comment]
> We should change the JaponicusDB menus as well.

There isn't much to put in a "Genome status" menu for japonicus so instead I've:

  - renamed "Genome Status" to "Overviews"
  - removed these items because they're empty or don't apply (for now):
     - "Genome updates"
     - "Gene coordinate changes"
     - "New and removed genes"
 - I've moved "Community curated publications" to the "Community" menu

japonicusdb.org will have these changes soon.
