### ISSUE TITLE
Make S. cerevisiae  (all ortholog) gene matches visible even when the pombe gene is matched.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2050]
Actually it would be clearer to understand in these situations if we showed the S. cerevisiae orthologs in all cases. Currently it seems we don't show the S. cerevisiae orthologs if there is an exact match to a pombe gene. But this is a bit misleading if you are actually looking for the orthologs, and we do say that you can search on those. I have been confused by this behavior myself.

<img width="293" alt="Screenshot 2023-06-21 at 14 36 22" src="https://github.com/pombase/curation/assets/7359272/3c5d1079-0d2e-4821-b770-335752a98648">

_Originally posted by @ValWood in https://github.com/pombase/curation/issues/3518#issuecomment-1600854847_

**Comment by kimrutherford** [comment]
> Currently it seems we don't show the S. cerevisiae orthologs if there is an exact match to a pombe gene.

Is this better?  I've changed it to show the ortholog if it matches a cerevisiae gene name:

![image](https://github.com/pombase/curation/assets/90474/32f54562-e39e-4d30-8140-26e5c971451a)

We could also show the human ortholog name if that matches:

![image](https://github.com/pombase/curation/assets/90474/30447362-c887-4e9a-b42c-2520dc5026d2)

**Comment by ValWood** [comment]
Yes I think it's much less confusing than only showing an ortholog name that matches if it is  not the same as the gene name. So for both  hu and Sc.

**Comment by kimrutherford** [comment]
OK, that changes is now live on pombase.org.  Let me know if it works the way you think it should.

**Comment by manulera** [comment]
I agree, I think it's better like this as well.

**Comment by ValWood** [comment]
Done.
