### ISSUE TITLE
Rhea reactions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2051]
https://github.com/pombase/website/issues/1243

We still need to decide whether to also list the reactions, maybe under a "show Rhea reaction link"
 a the top of the GO MF section on the gene pages

@snezhkaoliferenko
would this be helpful? or is the ontology term page enough?

**Comment by snezhkaoliferenko** [comment]
I would not mind having it there but then am interested in metabolism 😉
________________________________
From: Val Wood ***@***.***>
Sent: 21 June 2023 16:58
To: pombase/website ***@***.***>
Cc: Snezhana Oliferenko ***@***.***>; Mention ***@***.***>
Subject: [pombase/website] Rhea reactions (Issue #2051)


#1243<https://github.com/pombase/website/issues/1243>

We still need to decide whether to also hist the reactions, maybe under a "show Rhea reaction link"
a the top of the GO MF section on the gene pages

@snezhkaoliferenko<https://github.com/snezhkaoliferenko>
would this be helpful? or is the ontology term page enough?

**Comment by kimrutherford** [comment]
> the top of the GO MF section on the gene pages

We need to consider how it will look on genes with there are lots of reactions to show.
As an extreme example, this gene has 9 GO functions that have Rhea reactions: https://www.pombase.org/gene/SPAC926.09c

**Comment by ValWood** [comment]
Good point, that could look messy. Maybe we will stay as we are.
One option would be to introduce a 
"catalytic activity" subsection like Uniprot do
https://www.uniprot.org/uniprotkb/Q9UUG0/entry

I also wondered in cases like this:
https://www.pombase.org/term/GO:0008659
where the chemical structure is quite large it is difficult to see. Uniprot used to have an option to zoom in or out on the entire reaction which was quite nice. They now changed this so that you can zoom in or out on the individual chemicals. I don't know if either of these are possible with the widget?

Another feature that could be very useful would be to have link all genes with a reaction containing a **specific reaction component**. Would be very useful for metabolic pathway reconstruction.

**Comment by kimrutherford** [comment]
> They now changed this so that you can zoom in or out on the individual chemicals. I don't know if either of these are possible with the widget?

I'll give that a go.

**Comment by kimrutherford** [comment]
If it helps, we could add them to the term name mouse-over.  They wouldn't be very readable but at least you would know which terms have Rhea reactions without having to click:

![reaction-1](https://github.com/pombase/website/assets/90474/7128e59f-fdcd-4c7e-b4a7-3676dadccf62)

(this is just a mock-up)

**Comment by snezhkaoliferenko** [comment]
melikes!
________________________________

**Comment by ValWood** [comment]
Me too!

**Comment by ValWood** [comment]
I  know not everyone is as interested in metabolism as @snezhkaoliferenko but it's something we should  all be thinking about more.  Anything we do to make the info more easily accessible will bring it to more people's attention. It will also help us to build metabolic pathways whenever that might happen...  It will be a bit like the structures. Nobody missed them until we had them ;)

**Comment by kimrutherford** [comment]
> we could add them to the term name mouse-over

I've finished implementing that.  It needs to nightly update before it will work so it won't be visible until Thursday morning.

The diagrams are too small to read but at least it shows that something is available if you click:

![image](https://github.com/pombase/website/assets/90474/cf5a56b7-ba81-4f00-82d1-7b6a112b9b23)

**Comment by kimrutherford** [comment]
> They now changed this so that you can zoom in or out on the individual chemicals. I don't know if either of these are possible with the widget?

That turns out to be not straightforward because of the way the Rhea code interacts with the website code.  I'm sure there's a fix but I haven't worked it out yet.

**Comment by kimrutherford** [comment]
> It needs to nightly update before it will work so it won't be visible until Thursday morning.

I fixed a few bugs today.  It's now on the main site:

![image](https://github.com/pombase/website/assets/90474/adf4f13e-a9b9-40a6-b9a9-9d9dbb8d0044)

I'll leave this issue open for now.  I plan to have another look at getting the zoom function to work but not immediately.

**Comment by kimrutherford** [comment]
>> They now changed this so that you can zoom in or out on the individual chemicals. I don't know if either of these are possible with the widget?
>
> That turns out to be not straightforward because of the way the Rhea code interacts with the website code. I'm sure there's a fix but I haven't worked it out yet.

I've looked more into this and there's no reliable way to implement the zoom function.

**Comment by ValWood** [comment]
ok, let's close this. its good as it is.
