### ISSUE TITLE
Protein sequence feature viewer (for domains mutants and modifications)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2053]
Replaces 
https://github.com/pombase/website/issues/667

**Features**

**Essential**

- Actively maintained
- Good speed, especially for loading, and viewing multiple features quickly with mouse-over

Configurable
- Ability to configure tracked of different types
- Ability to configure pop-ups associated with tracks

Browser features essential
- Zoomable feature viewer (into amino acid residue)
- Coupling to protein feature viewer (only need to pick one full length representative structure)
- Coupling mutants to phenotypes (probably via pop-ups or tables)

**Desirable** 
Ability for user configure  active tracks on and off (Calipho has this)
Download svg image ? Calipho has this)
Ability to link to the equivalent residue in human (I'm not sure how that could happen, it would need to be precomputed from alignments (possibly Panther families could be used for this). This isn't super urgent.

**Tracks we would like to display initially**
1 Single sequence region mutants (i.e A123G,  OR A234G,A235G OR 123-223 delta) with associated phenotypes
2. Modifications (ALL)
3. Pfam domains
4. TMM regions
5. Low complexity regions
6. Coiled coils

Ideally, these  regions would display  in structure viewer and give a mouse-over pop-up with “details”

**Later datatypes**
Secondly structure regions
Hydropathy?
Others?

**Examples**
RCSB https://www.rcsb.org/3d-sequence/4OFB?asymId=A
Calipho https://www.nextprot.org/entry/NX_P38398/sequence
Protista https://www.uniprot.org/uniprotkb/P38398/feature-viewer

**Comment by kimrutherford** [comment]
Progress so far:
https://desktop.kmr.nz/gene/SPBC19C2.09
![image](https://github.com/pombase/website/assets/90474/5e5e3f14-a736-406c-acc4-672b3c3da177)

**Comment by ValWood** [comment]
Looking good!

**Comment by kimrutherford** [comment]
Modifications!

https://desktop.kmr.nz/gene/SPBC19C2.09
![image](https://github.com/pombase/website/assets/90474/e472bfd9-c672-4e77-8073-0bc2e33fd5e2)

**Comment by kimrutherford** [comment]
Should we put the allele/variants and modifications at the top since they're important?:

![image](https://github.com/pombase/website/assets/90474/3cdf122b-8a8d-45ce-8bbb-f5413615a524)

Also are "Variants" and "Modifications" OK as labels?

**Comment by kimrutherford** [comment]
RCSB use capitals for the track labels.  Should we do the same to make them stand out?:

![image](https://github.com/pombase/website/assets/90474/37e0c224-ce3d-469d-beb2-c89a06be4ed4)

**Comment by kimrutherford** [comment]
We should cite:
Joan Segura, Yana Rose, John Westbrook, Stephen K Burley, Jose M Duarte. RCSB Protein Data Bank 1D tools and services, Bioinformatics, 2020; https://doi.org/10.1093/bioinformatics/btaa1012

**Comment by ValWood** [comment]
I don't think it is working on your desktop right now. Hopefully you went to bed.
I'm leaning towards the capitalization. @manulera what do you think?

Good progress!

**Comment by ValWood** [comment]
The example for multiple modification types for a single residue was hht1
I will try to find one with more...

**Comment by ValWood** [comment]
I also agree to switch the order.

**Comment by kimrutherford** [comment]
> I don't think it is working on your desktop right now. 

While I'm changing things it often breaks or goes offline.  It should be working in the morning.  I'm off to bed now so I'll be turning the desktop off.

I've added Pfam families, but since there's on mouse-over details, it's not very useful.  I plan to add mouse-overs tomorrow.

![image](https://github.com/pombase/website/assets/90474/6978f1cf-f83d-4dec-97c7-0f554ee264f8)

> I also agree to switch the order.

Done.

> The example for multiple modification types for a single residue was hht1

OK, thanks.  That will be good for testing tomorrow:

![image](https://github.com/pombase/website/assets/90474/653aca46-f0a4-4165-8e23-66ef03904b7b)

**Comment by ValWood** [comment]
Very nice!

**Comment by kimrutherford** [comment]
I've added mouse overs on my desktop version: https://desktop.kmr.nz/gene/SPAC1834.04

The text is very minimal at the moment.  What should be displayed for variants and modifications?  I think it will look best if we don't have more than two lines of text, if possible.

![image](https://github.com/pombase/website/assets/90474/51deae35-74f3-4ba0-9e2c-7b518222a0ee)

![image](https://github.com/pombase/website/assets/90474/63314bfd-5b4f-4add-86b9-0667fddf9ee2)

**Comment by kimrutherford** [comment]
I've now added the protein feature view to the dev site so you don't need to rely on my machine being online: http://dev.pombase.kmr.nz/gene/SPBC19C2.09

**Comment by ValWood** [comment]
It looks very nice. We. can discuss the text. This is soooo useful.

Some random thoughts which should probably be in new tickets
i) we will need to deal with the histone special case for modifications, histones residues are always referred to (numbered) after the methionine has been removed in the mature form (check out hht1 lysine K14).
ii) special case 2 CTD domain residues in rpb1 and spt5 (will affect variants, but for rpb1 I see we also have
modified residue CTD_S5 removed by etc

**Existing Page Section** It will be odd to have 2 sections named "protein features" so I suggest that  before release:
i) rename the 'other' protein feature section to 'protein domains' and 
ii) split out the  protein properties into their own section  (we can discuss this, we might be able to ditch and just add charge back to the top matter)

**Linking to the structure viewer**- bear in mind that many of the pdb entries are fragments (e.g. dcr1), so for these we will need to use alpha fold when mapping residues.

**Comment by ValWood** [comment]
This is all so good. Especially with all the corrected alleles and modifications @manulera is doing we can be confident about the displays being correct.

I think we should rename the Variants row as mutants (otherwise for non pombe people they might assume natural variation)

Some suggestions for the "click through" version.
- Maybe we should split rows of different classes (major) of modification 
- Thinking of a way to show 'conjoined' alleles (and possibly deleted regions) I noticed that some of the Pfam domains had 'connectors" maybe this can be used?
- I wonder if we can get "active sites" from anywhere. I know pdb have then, but we should be able to get active sites for many domains without structures. I think Pfam make this data (perhaps it is in the InterPro release). Otherwise we might be able to get some from UniProt. 
-

**Comment by manulera** [comment]
Wow! Looks great! I would have loved it back in the day. Here are some comments:

> i) we will need to deal with the histone special case for modifications, histones residues are always referred to (numbered) after the methionine has been removed in the mature form (check out hht1 lysine K14).

This should be OK if using the allele descriptions, since they are corrected for histones, even if the name is different.

**Comment by manulera** [comment]
> ii) special case 2 CTD domain residues in rpb1 and spt5 (will affect variants, but for rpb1 I see we also have modified residue CTD_S5 removed by etc

For the CTD, let's wait a little bit until I finish with the allele pipeline, and I think we should get a solution

**Comment by ValWood** [comment]
>This should be OK if using the allele descriptions, since they are corrected for histones, even if the name is different.

I should have been clearer. The alleles already render OK. But the modifications use actual sequence coordinates and so are 'off by one'
A simple shift in the affected genes should fix it.
 This is K14 modification on hht1, displays on residue 13:
<img width="51" alt="Screenshot 2023-07-06 at 07 19 42" src="https://github.com/pombase/website/assets/7359272/35706806-5d89-4b49-b8c9-376c47c24937">

**Comment by manulera** [comment]
@ValWood I see, but those should be ammended at some point as well (I think). For now we have only fixed the ones in the HTP files, not the ones stored in Canto. We can discuss this on the next meeting

**Comment by kimrutherford** [comment]
> I'm leaning towards the capitalization.

I've done that so we can see how it looks.

> I also agree with Val that the order is better with variants and modifs on top

That's done now.

> I think we should rename the Variants row as mutants

Done.

**Comment by ValWood** [comment]
The old sequence feature was much shorter! Pesky little exon...
<img width="508" alt="Screenshot 2023-07-06 at 11 12 37" src="https://github.com/pombase/website/assets/7359272/1a52cc6f-5c22-40f2-9069-0ca61c9c55bf">

**Comment by manulera** [comment]
> The old sequence feature was much shorter! Pesky little exon...

I think that comment belongs in https://github.com/pombase/curation/issues/3525

**Comment by ValWood** [comment]
removed!

**Comment by kimrutherford** [comment]
> Single sequence region mutants (i.e A123G, OR A234G,A235G OR 123-223 delta) with associated phenotypes

How should the phenotypes look?  Some alleles have multiple associated phenotypes.

> 123-223 delta

Are those the alleles with type "partial_amino_acid_deletion" and descriptions like "ccq1(131-441)"?

**Comment by manulera** [comment]
> How should the phenotypes look? Some alleles have multiple associated phenotypes.

I think that's going to be a bit tricky, specially for famous alleles, like cdc25-22 and so, which will have many many phenotypes. If there is an ontologic way to restrict to the high order terms that would be the best, I think (some kind of slim, but not sure that's possible).

However, I am not sure variant -> phenotype is the most meaningful link. Probably the user would like to see which alleles give a certain phenotype, rather than what a particular sequence modification does when hovering over it. This does not seem possible/easy on the gene page. However, if we are still thinking of a separate view like the one in the PDB, in which the sequence opens in a different window and you also have the structure, then we could have a scrollable list of all phenotypes like in the gene page, where the user can pick some and only the alleles that give those phenotypes can be displayed. In the same way, it could be that when you click on a particular modification, a list with all phenotypes associated with the modification is rendered below the graph (clearly this cannot be a tooltip when mouseover).

I thought what would be really nice instead of a phenotype list is to have some ontology tree with only the FYPO terms of that gene so you can also pick high-order terms, but then I had a look at the `cut` phenotype tree in OLS and realised that it would look atrocious (https://www.ebi.ac.uk/ols4/ontologies/fypo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFYPO_0000229). That tree is for one term only! Admitedly, perhaps one of the most connected, and famous phenotypes in pombe, but still...

**Comment by manulera** [comment]
> Are those the alleles with type "partial_amino_acid_deletion" and descriptions like "ccq1(131-441)"?

Yes, in principle the descriptions of `partial_amino_acid_deletion` alleles always contain the missing residues, while their names may contain the missing or kept amino acids, depending on the authors. Say, protein ase1 has 100 aminoacids, they may name an allele missing aa 60-100 as ase1(1-59) -what's kept- or ase1delta(60-100) -what's missing-. In theory, in the description there should only be the missing ones, independently of what the name is, but I am sure there are some errors out there.

**Comment by kimrutherford** [comment]
> Thinking of a way to show 'conjoined' alleles (and possibly deleted regions) I noticed that some of the Pfam domains had 'connectors" maybe this can be used?

I tried that but unfortunately it doesn't work well in every case.  It's good on the cdc10 page:

![image](https://github.com/pombase/website/assets/90474/b956ab10-eca4-4877-973b-2a5ceeb938e1)

but not so friendly on the mrc1 page:

![image](https://github.com/pombase/website/assets/90474/a55abc61-9cc3-437c-b4b5-cb0bf87691be)

because of allele descriptions like "T121A,T327A,T513A,S572A,S599A,S604A,S614A,T634A,S637A,T645A,T653A,S938A,T965A,S1000A"

**Comment by kimrutherford** [comment]
>> Are those the alleles with type "partial_amino_acid_deletion" and descriptions like "ccq1(131-441)"?
> Yes, in principle the descriptions of partial_amino_acid_deletion alleles always contain the missing residues,

Thanks Manu.

What does it mean if a partial_amino_acid_deletion has a description like "W316*"?

Also I found one that seems a bit strange.  It's a partial_amino_acid_deletion for an RNA gene?:  [nc-tco1-LΔ::ura4+(-395-+146)](http://dev.pombase.kmr.nz/genotype/nc-tco1-Ldelta::ura4%2B--395-%2B146-partial_amino_acid_deletion-expression-not_assayed_or_wild_type)

**Comment by kimrutherford** [comment]
> Are those the alleles with type "partial_amino_acid_deletion" and descriptions like "ccq1(131-441)"?

I tried adding those alleles and it didn't work out too well in some cases.  Below is the diagram for mrc1.

Gene page: https://desktop.kmr.nz/gene/SPAC694.06c
Full diagram: https://desktop.kmr.nz/protein_feature_view/widget/SPAC694.06c
It will be at https://dev.pombase.kmr.nz/gene/SPAC694.06c on Monday morning.

![image](https://github.com/pombase/website/assets/90474/8020faa0-0280-4210-88d0-cb1bc04bc7bf)

**Comment by kimrutherford** [comment]
> What does it mean if a partial_amino_acid_deletion has a description like "W316*"?

The nomenclature paper says that the `*` is a stop codon, which makes sense.  But in that case why doesn't `W316*` have the type "amino_acid_mutation"?  Is it because the protein gets truncated?

**Comment by manulera** [comment]
> The nomenclature paper says that the * is a stop codon, which makes sense. But in that case why doesn't W316* have the type "amino_acid_mutation"? Is it because the protein gets truncated?

Yes, this is a truncated protein. In the past we used to record them as "nonsense_mutation" but we decided to merge with partial aminoacid deletion, since at the product level there is no difference in principle.

So, for the sake of the feature viewer, `W136*` is equivalent to `1-316` as a description.

**Comment by kimrutherford** [comment]
> > Are those the alleles with type "partial_amino_acid_deletion" and descriptions like "ccq1(131-441)"?
>
> I tried adding those alleles and it didn't work out too well in some cases

On some pages it looks very nice though.  This is sre1 on the dev server as of this morning: http://dev.pombase.kmr.nz/gene/SPBC19C2.09

![image](https://github.com/pombase/website/assets/90474/69dec5cf-df23-4c13-b283-6b68b4ad89fe)

**Comment by manulera** [comment]
Looks great!

I noticed that in the truncation section the "chunks" that are on the same lane do not necessarily belong to the same construct. For example:

![Screenshot 2023-07-10 at 09 39 49](https://github.com/pombase/website/assets/22526102/920777e8-f965-4319-852b-da94d6f74902)

![Screenshot 2023-07-10 at 09 42 03](https://github.com/pombase/website/assets/22526102/fa62d7f3-c9db-4a39-9418-66f16563a7b4)

All chunks may get distributed to minimise the rows or something, perhaps that's why there are many rows in that example where ends meet perfectly. If there is a way to link two fragments to indicate they belong to the same construct and force them to appear in the same lane, that would be the best (with a thin line in the middle like the disulfide bonds in the PDB display?) not sure if that's possible / supported.

**Comment by ValWood** [comment]
I suggest we open new tickets for each outstanding task, or  feature request, as this ticket is in danger of becoming difficult to navigate.

**Comment by ValWood** [comment]
Hi @kim the stop codon change was documented here in the news item
Curation update - “nonsense mutation” merged into “partial amino acid deletion”
I'll close off those comments but let us know if it doesn't make sense

**Comment by kimrutherford** [comment]
> All chunks may get distributed to minimise the rows or something, perhaps that's why there are many rows in that example where ends meet perfectly. If there is a way to link two fragments to indicate they belong to the same construct and force them to appear in the same lane, that would be the best

Here's what that would look like: https://desktop.kmr.nz/protein_feature_view/widget/SPAC694.06c

(Note that the zooming and scrolling doesn't work correctly on that page.  I've created [a issue](rcsb/rcsb-saguaro/issues/37) about that)

**Comment by manulera** [comment]
> Here's what that would look like:

![Screenshot 2023-07-10 at 10 40 35](https://github.com/pombase/website/assets/22526102/62f871a5-8c06-4cc3-af46-9f14f53b5f76)

Yes! That's perfect! That was fast!

**Comment by ValWood** [comment]
I think all the tasks are now in new tickets:

https://github.com/pombase/website/issues/2068
#2068 opened now by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)

https://github.com/pombase/website/issues/2067
#2067 opened 16 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)
[ 4](https://github.com/pombase/website/issues/2067)

https://github.com/pombase/website/issues/2066
#2066 opened 26 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)
[ 1](https://github.com/pombase/website/issues/2066)

https://github.com/pombase/website/issues/2065
#2065 opened 36 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)
@ValWood

https://github.com/pombase/website/issues/2064
#2064 opened 38 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)

https://github.com/pombase/website/issues/2063
#2063 opened 38 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)

https://github.com/pombase/website/issues/2062
#2062 opened 46 minutes ago by [ValWood](https://github.com/pombase/website/issues?q=is%3Aissue+is%3Aopen+author%3AValWood)
[ 1](https://github.com/pombase/website/issues/2062)

**Comment by ValWood** [comment]
Task in new tickets

Protein feature viewer: decide text for mouse overs
#2068 opened 1 minute ago by ValWood

Protein feature viewer: "partial_amino_acid_deletion"
#2067

Protein sequence feature viewer show 'conjoined' alleles (and possibly deleted regions) I noticed that some of the Pfam domains had 'connectors" maybe this can be used?
#2066 

Protein sequence feature viewer: Find external active site sources
#2065 


protein sequence feature viewer: linking to structures
#2064 


Protein sequence feature viewer: existing page section
#2063 


Protein sequence feature viewer: enable phenotype-> residue in full view
#2062

**Comment by ValWood** [comment]
The only thing in this ticket is

Also I found one that seems a bit strange. It's a partial_amino_acid_deletion for an RNA gene?: [nc-tco1-LΔ::ura4+(-395-+146)](http://dev.pombase.kmr.nz/genotype/nc-tco1-Ldelta::ura4%2B--395-%2B146-partial_amino_acid_deletion-expression-not_assayed_or_wild_type)

I will fix that one.
