### ISSUE TITLE
Rhea reactions, small tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2054]
<img width="640" alt="Screenshot 2023-06-29 at 09 38 18" src="https://github.com/pombase/website/assets/7359272/edac5d74-66ee-4510-a02c-99975ef58f4a">

Change the text to
"Click to  view term details, annotations and larger Rhea reaction diagram)

Also I was confused by the 
"From the GO molecular function ontology" because I thought that test referred to the reaction diagram. I now realise is is on every pop-up.

Maybe move the ontology aspect  to the top of the popup above the term like:
"~From the~ GO molecular function ~ontology~

**Comment by kimrutherford** [comment]
How's this?:

![image](https://github.com/pombase/website/assets/90474/595d793f-548a-4c36-8203-494f5a6f7ec2)

**Comment by ValWood** [comment]
great! bed!
