### ISSUE TITLE
Tweets not working

### ISSUE THREAD

**Issue by manulera** [pombase/website#2056]
Hello @kimrutherford @ValWood

I think thanks to last Elon Musk's last idea now you have to log in to access tweets. Maybe this has also changed how to show the widget we have in the landing page. I cannot see them even if I am logged in on twitter in Chrome:

<img width="1020" alt="Screenshot 2023-07-03 at 17 28 17" src="https://github.com/pombase/website/assets/22526102/91d7ecbe-89b3-4884-94e1-f663faa38dfa">

**Comment by ValWood** [comment]
@elonmusk is such a knob

@kimrutherford  can we put Mastadon in a feed instead, is that possible?
Maybe we should use that instead.

**Comment by kimrutherford** [comment]
> can we put Mastadon in a feed instead, is that possible?

Looks like it's possible.  Here's a small Javascript library to make it do it:  https://gitlab.com/idotj/mastodon-embed-feed-timeline

**Comment by ValWood** [comment]
Let's chat about this today. I forgot all of our Mastodon details..

**Comment by kimrutherford** [comment]
I thought that breaking every public Twitter feed in the world was such a dumb move that it would only be temporary.  I was very wrong.

Although it wouldn't be a "Twitter" feed now even if it did work: https://www.nbcnews.com/news/us-news/twitter-rebrands-x-elon-musk-loses-iconic-bird-logo-rcna95880

So much dumbness :-(

> Here's a small Javascript library to make it do it: https://gitlab.com/idotj/mastodon-embed-feed-timeline

And another: https://github.com/andy-blum/fed-embed

I'll look closer at that after the protein feature viewer is released.

**Comment by manulera** [comment]
Silly Elno :(

**Comment by kimrutherford** [comment]
I think we should go ahead and hide the Twitter feed as it's now useless.  Any objections?

**Comment by ValWood** [comment]
It's is working for again me the past few days. I think we can consider hiding it though, let's keep it  while the protein viewer is fresh.

**Comment by kimrutherford** [comment]
> It's is working for again me the past few days.

It's still not working for me.

**Comment by manulera** [comment]
I can see it as well. Maybe you have to be logged into twitter in your browser @kimrutherford? Some "remember me" cookie that you wisely do not accept and we do?

**Comment by kimrutherford** [comment]
I tried with Firefox on Linux and Microsoft Edge on Linux and Windows, which all didn't work.  It does work on Chrome on Linux.  I should have tried that earlier.

Unfortunately users without a Twitter account are still going miss out on seeing the timeline.

**Comment by kimrutherford** [comment]
I was able to get it working in Firefox by logging in to Twitter and disabling a Firefox feature called [Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) when browsing pombase.org

Luckily most users don't use Firefox.  :-)

**Comment by ValWood** [comment]
Let's  discuss when I get back. I guess we should remove  and we could just link to twitter and Mastadon instead. There still doesn't appear to be much pombe community activity on Mastadon.

**Comment by kimrutherford** [comment]
The Twitter timeline has now disappeared entirely for me.  I did a quick Google search but couldn't find anything.  I'll look harder if it doesn't come back by itself in a day or two.

**Comment by ValWood** [comment]
do you mean this?
https://twitter.com/PomBase

**Comment by kimrutherford** [comment]
I meant the Twitter timeline on pombase.org.  It's completely missing for me:

![image](https://github.com/pombase/website/assets/90474/9da4c373-1e92-4206-b6f3-333be99ffa2b)

**Comment by ValWood** [comment]
Oh I thought you had removed it because it was giving that error. It's been like that for months ;)

**Comment by kimrutherford** [comment]
After the comments in July I didn't change anything because it was working for Twitter users at least.  Not any more.  Oh well.

**Comment by kimrutherford** [comment]
I tested the Twitter timeline again today and it's working again for Chrome, if you're logged into Twitter.  So I've re-enabled the timeline on the front page.  It doesn't work on FireFox.  I don't know about Safari.

![image](https://github.com/pombase/website/assets/90474/4783826a-dc60-4f6b-9be2-7d3ce51f89e3)
