### ISSUE TITLE
small display bug on sequence viewer in gene pages

### ISSUE THREAD

**Issue by manulera** [pombase/website#2059]
Hi @kimrutherford. A little display bug when switching from an empty DNA sequence to aminoacid sequence, it still shows the empty sequence message:

https://github.com/pombase/website/assets/22526102/efb3e9dd-c661-42cd-a7c2-328a7e799ddb

**Comment by kimrutherford** [comment]
Thank Manu.  That's fixed on the dev site and will be fixed on the main site in the morning.

**Comment by manulera** [comment]
yaay
