### ISSUE TITLE
change "gene standard name" to "gene symbol" on gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2061]
On gene pages we have
Gene standard name cdc2

Change to "gene symbol" (this seems to be what The Alliance has settled on), and was recommended by one of our nomenclature publication reviewers.

Also, we should revisit how we name column headers for downloadable data.

In embl files we use "primary_name", we should consider changing this to "gene symbol"

Need to figure out dependencies first.

**Comment by ValWood** [comment]
Only the gene page change is urgent. The rest we should discuss.

**Comment by kimrutherford** [comment]
> Change to "gene symbol"

That's done on the gene pages.

**Comment by ValWood** [comment]
Thanks!

CC @manulera

**Comment by ValWood** [comment]
Reopening until we review other files and how we name  the "gene symbol column"

**Comment by ValWood** [comment]
I raised this issue on Elixir biocuratio focus group call (i.e use of different labels).
I will park this as future until this is figured out.

**Comment by ValWood** [comment]
I'll close this, the rest is out of scope until global standards are in use
