### ISSUE TITLE
Protein sequence feature viewer show 'conjoined' point mutations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2066]
> Thinking of a way to show 'conjoined' alleles (and possibly deleted regions) I noticed that some of the Pfam domains had 'connectors" maybe this can be used?

I tried that but unfortunately it doesn't work well in every case.  It's good on the cdc10 page:

![image](https://github.com/pombase/website/assets/90474/b956ab10-eca4-4877-973b-2a5ceeb938e1)

but not so friendly on the mrc1 page:

![image](https://github.com/pombase/website/assets/90474/a55abc61-9cc3-437c-b4b5-cb0bf87691be)

because of allele descriptions like "T121A,T327A,T513A,S572A,S599A,S604A,S614A,T634A,S637A,T645A,T653A,S938A,T965A,S1000A"

_Originally posted by @kimrutherford in https://github.com/pombase/website/issues/2053#issuecomment-1626906483_

**Comment by ValWood** [comment]
I don't think we should have these "conjoined" mutants on the main page, but when you click through to the 'full version' it could be an optional track maybe (I don't think it looks so bad, but we will need to figure if it is useful)

**Comment by ValWood** [comment]
Action:  show summary row only on front page.

**Comment by kimrutherford** [comment]
>  show summary row only on front page.

That's implemented now but needs a nightly load to update the dev site.  The changes should be there on Thursday morning.

My local version has the changes: https://desktop.kmr.nz/gene/SPBC1778.02

![image](https://github.com/pombase/website/assets/90474/aac8a611-0155-45d2-83a4-17aab3b9daa2)


https://desktop.kmr.nz/gene_protein_features/SPBC1778.02

![image](https://github.com/pombase/website/assets/90474/a7e63773-abc1-4d6b-9199-c2286861cbc3)

**Comment by kimrutherford** [comment]
I think this is done now.  Let's open new issues for bugs and changes.
