### ISSUE TITLE
Protein feature viewer:  "partial_amino_acid_deletion" 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2067]
> I tried adding those alleles and it didn't work out too well in some cases.  Below is the diagram for mrc1.

Gene page: https://desktop.kmr.nz/gene/SPAC694.06c
Full diagram: https://desktop.kmr.nz/protein_feature_view/widget/SPAC694.06c
It will be at https://dev.pombase.kmr.nz/gene/SPAC694.06c on Monday morning.

![image](https://github.com/pombase/website/assets/90474/8020faa0-0280-4210-88d0-cb1bc04bc7bf)

_Originally posted by @kimrutherford in https://github.com/pombase/website/issues/2053#issuecomment-1627677882_

**Comment by ValWood** [comment]
@man commented

Looks great!

I noticed that in the truncation section the "chunks" that are on the same lane do not necessarily belong to the same construct. For example:

Screenshot 2023-07-10 at 09 39 49

Screenshot 2023-07-10 at 09 42 03

All chunks may get distributed to minimise the rows or something, perhaps that's why there are many rows in that example where ends meet perfectly. If there is a way to link two fragments to indicate they belong to the same construct and force them to appear in the same lane, that would be the best (with a thin line in the middle like the disulfide bonds in the PDB display?) not sure if that's possible / documented.

**Comment by ValWood** [comment]
I agree that different alleles on the sem row will be confusing here.
I wonder if this could be data that the users can optionally switch on and off and every deletion alelle should have its own row?

My other immediate reaction was that it wasn't  clear whether the blocks represented the retained residues or the deleted ones?
Intuitively I would expect to see the retained region.

**Comment by ValWood** [comment]
Although as you say, many pages look fine....but I think we need to limit what we show on the front page view, we can discuss if there is a way to summarize this section, or at least indicate there is data available in the full view. I wonder if a  datatype has over a certain number of tracks we can just display some text like:
"Too many rows to show, go to the full? protein feature viewer instance for this data"

**Comment by ValWood** [comment]
@kim wote

> All chunks may get distributed to minimise the rows or something, perhaps that's why there are many rows in that example where ends meet perfectly. If there is a way to link two fragments to indicate they belong to the same construct and force them to appear in the same lane, that would be the best

Here's what that would look like: https://desktop.kmr.nz/protein_feature_view/widget/SPAC694.06c

(Note that the zooming and scrolling doesn't work correctly on that page.  I've created [a issue](rcsb/rcsb-saguaro/issues/37) about that)

**Comment by kimrutherford** [comment]
We discussed inverting the partial deletion display so the deleted part of the protein is shown with dashed lines rather than the retained part.

Here's what we used to have:

![image](https://github.com/pombase/website/assets/90474/8d69cd6f-0891-4e45-be62-cfa4ad7c7051)

Here's how it looks now:

![image](https://github.com/pombase/website/assets/90474/d9797859-7573-45a0-bb25-cedd9243c4db)

http://dev.pombase.kmr.nz/gene/SPCC962.02c

This also forces each partial deletion onto a separate line, which we also discussed.

Here's a more complicated example.  Before:
![image](https://github.com/pombase/website/assets/90474/eabbe7d2-8be4-4368-86d3-c569747f5551)

After:
![image](https://github.com/pombase/website/assets/90474/32f6ae2f-fa35-4dc0-823e-c72d50d8d599)

**Comment by ValWood** [comment]
I much prefer this! It looks great. What is the second example?

**Comment by kimrutherford** [comment]
> What is the second example?

It's mrc1, which is a good example for testing: http://dev.pombase.kmr.nz/gene/SPAC694.06c

http://dev.pombase.kmr.nz/protein_feature_view/widget/SPAC694.06c

**Comment by ValWood** [comment]
Looks great. We need some sort of heuristic to give the best display order. 
Essentially we need to (loosely) group the "most similar" deletions together.

One suggestion
i) Sort first by number of alleles deleted so that the most remaining amino acids is at the top
ii) Iterate through and place any allele which matches any coordinate of the previous entry next (in the previusly sorted order)

We can discuss tomorrow.

**Comment by kimrutherford** [comment]
As discussed on the call, I've made a basic effort to group the deletions together.  From tomorrow they will be sorted by the first AA of the first deleted segment, then by the last AA of the first deleted segment as a tiebreaker.

In some case that makes it very tidy, like for sre1:

![image](https://github.com/pombase/website/assets/90474/0aeec059-b994-4fdb-97b5-011eb249d07f)

-----------------------

For mrc1 it helps but still needs some work:

Before:
![image](https://github.com/pombase/website/assets/90474/407e6f4b-1736-44f0-ba66-889018f002ae)

---------------------

After:
![image](https://github.com/pombase/website/assets/90474/c6dd9309-a44d-4761-8055-738aeceae8ad)

**Comment by kimrutherford** [comment]
I'm going to close this because more or less done.

I made a separate issue about ordering the deletions better:
  - pombase/website#2076

**Comment by ValWood** [comment]
I think that's great as it is!
