### ISSUE TITLE
redundancy  on gene page hide redundant terms 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#207]
![redundancy](https://cloud.githubusercontent.com/assets/7359272/23891864/32e9e342-0890-11e7-9d37-fe297e33ddbe.jpg)

here, cyclin dependent protein kinase activity can be hidden in default view because it has no unique extensions.

**Comment by kimrutherford** [comment]
Is this the same as #45?

**Comment by ValWood** [comment]
yep dupe
