### ISSUE TITLE
Gene structure history displaying "File" instead of revision number

### ISSUE THREAD

**Issue by manulera** [pombase/website#2070]
Hi @kimrutherford, I noticed today that a row displays "File" instead of the revision number.

<img width="1061" alt="Screenshot 2023-07-14 at 09 45 06" src="https://github.com/pombase/website/assets/22526102/5d8ad815-d311-496b-ac5d-f309bdca2abe">

https://www.pombase.org/gene/SPBC25B2.07c

**Comment by kimrutherford** [comment]
Fixed!

**Comment by manulera** [comment]
nice!
