### ISSUE TITLE
Add links to Rcsb from protein structures

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2072]
We only link to  PDBe (protein databank in europe)

We should also link from protein structures  to RCSB pdb
https://www.rcsb.org/sequence/4ro1

We should also consider linking from our citation guidelines to the guidelines for citing  the protein structure data we import
https://www.rcsb.org/pages/policies#References
and any equivalent link for pdb

**Comment by kimrutherford** [comment]
![image](https://github.com/pombase/website/assets/90474/dec8a0a2-7287-49a1-876b-ab9a0076b506)

**Comment by kimrutherford** [comment]
> We should also link from protein structures to RCSB pdb
> https://www.rcsb.org/sequence/4ro1

Your example is a link to their protein feature view.  Did you mean this instead:
https://www.rcsb.org/structure/4RO1

**Comment by kimrutherford** [comment]
That's on the main site now.
