### ISSUE TITLE
Sequence selection info inconsistent behaviour

### ISSUE THREAD

**Issue by manulera** [pombase/website#2074]
Hi @kimrutherford, when selecting residues in the sequence section of gene pages, when the selection spans separate features (e.g. upstream and 5UTR) the info on top that shows the selected residues sometimes disappears. However, for long selections it seems to work again, see video below at the end:

PS: this happens both in Crhome and firefox

https://github.com/pombase/website/assets/22526102/a920df36-7ea0-45f3-abcc-1ec20aec1391

**Comment by kimrutherford** [comment]
Thanks Manu!  That bug must have been there for a long time.  It's fixed now.

**Comment by manulera** [comment]
Thanks! That will be very useful for allele curation
