### ISSUE TITLE
Protein feature viewer: modification tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2079]
It could be good to colour the modifications by type (phosphorylation, acetylation, methylation, ubiquitin(like), glycosylation etc 
OR by residue if this was too complicated. Colours could be in a key below the full viewer.

We could also display some info with the modification mouse over (perhaps **added  during** would be most useful, but we could include **added by/affected** by too if space

**Comment by kimrutherford** [comment]
> It could be good to colour the modifications by type (phosphorylation, acetylation, methylation, ubiquitin(like), glycosylation etc

That shouldn't be a problem.  It looks like there are 7 common modifications and lots of uncommon ones.  So I guess 8 colours makes sense?

Do we need to do this before releasing the feature viewer?

**Comment by kimrutherford** [comment]
We'll need to choose the colours carefully so the modifications don't look like a fruit salad.  :-)

Here's my first attempt:

![image](https://github.com/pombase/website/assets/90474/a78ae2f7-f71f-4875-b16b-6f8109917747)

Zoomed in a bit:

![image](https://github.com/pombase/website/assets/90474/359048c3-fcf9-4e73-957c-8fba8c959ac3)

**Comment by ValWood** [comment]
We don't need it for release.

What are the common modifications? We can lump all 
phosphorylation/dephosphorylation  (serine/threonine/tyrosine) together.
acetylation/deacetylation together.
methylation/demethylation together.

**Comment by kimrutherford** [comment]
These are the 15 most common modifications:
```
 count |  term_id  |                  term_name                  
-------+-----------+---------------------------------------------
 33865 | MOD:00046 | O-phospho-L-serine
  7133 | MOD:00047 | O-phospho-L-threonine
  1606 | MOD:01148 | ubiquitinylated lysine
  1304 | MOD:01149 | sumoylated lysine
  1068 | MOD:00048 | O4'-phospho-L-tyrosine
   982 | MOD:00696 | phosphorylated residue
   430 | MOD:00006 | N-glycosylated residue
    89 | MOD:00595 | mannosylated residue
    39 | MOD:00818 | glycosylphosphatidylinositolated residue
    34 | MOD:00693 | glycosylated residue
    17 | MOD:00739 | iron-sulfur cluster containing modification
    14 | MOD:00394 | acetylated residue
    11 | MOD:00437 | farnesylated residue
    11 | MOD:00427 | methylated residue
     9 | MOD:00663 | methylated lysine
```

**Comment by kimrutherford** [comment]
> We could also display some info with the modification mouse over (perhaps added during would be most useful, but we could include added by/affected by too if space

That's done on my desktop.  It will be on the dev site on Wednesday morning.

![image](https://github.com/pombase/website/assets/90474/73b9da03-ce25-4644-8215-3c7925aa4fcc)

**Comment by ValWood** [comment]
We need to combind
33865 | MOD:00046 | O-phospho-L-serine
  7133 | MOD:00047 | O-phospho-L-threonine
  1304 | MOD:01149 | sumoylated lysine
  1068 | MOD:00048 | O4'-phospho-L-tyrosine
   982 | MOD:00696 | phosphorylated residue

into a single  colour and type  (phosphorylated residue) we don't need to specify by amino acid becasue this will  (should) be curated.

**Comment by ValWood** [comment]
We should also combine these 2 into "methylated residue"
    11 | MOD:00427 | methylated residue
     9 | MOD:00663 | methylated lysine

I'm surprised how few acetylated and methylated residues are curated!

**Comment by ValWood** [comment]
Combine
[glycosylated residue](https://www.pombase.org/term/MOD:00693)
and children
[galactosylated](https://www.pombase.org/term/MOD:00728)
[mannosylated residue](https://www.pombase.org/term/MOD:00595)
[N-glycosylated residue](https://www.pombase.org/term/MOD:00006)
[N-linked glycan core N4-glycosylated asparagine](https://www.pombase.org/term/MOD:00506)
[N4-glycosyl-L-asparagine](https://www.pombase.org/term/MOD:00160)
[O-glycosylated residue](https://www.pombase.org/term/MOD:00396)

to use a single colour (can keep the individual descriptions)

**Comment by ValWood** [comment]
If this is too complicated you can release with the single colour  for modifications and we can  do this later.

**Comment by kimrutherford** [comment]
I've disabled the modification colours for now.

**Comment by ValWood** [comment]
Since this was done  (I had forgotten) we should make it live. It is REAY useful.
We need to  group the modifications as I described above. If it doesn't make sense we can discuss on next call.

**Comment by kimrutherford** [comment]
It looks like most of the groups have a single parent term:
 - "phosphorylated residue"
 - "methylated residue"
 - "glycosylated residue"

But not for this case:
> ...
>  MOD:01149 | sumoylated lysine
> ...
> into a single colour and type (phosphorylated residue)

"sumoylated lysine" isn't a "phosphorylated residue" in [the ontology](https://www.ebi.ac.uk/ols4/ontologies/mod/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMOD_01149).  Is that the correct group for it?  Should we have a separate group for "acylated residue"

Also, which group should MOD:01148 ubiquitinylated lysine be in?

**Comment by ValWood** [comment]
Acetylated residue should work (It groups a Ac and Ub-like), but I think people will figure that out

**Comment by kimrutherford** [comment]
I've made a first attempt at that which will be on the main site in the morning.  There are currently four groups/colours.  There is no colour key yet.

 - "phosphorylated residue"
 - "methylated residue"
 - "glycosylated residue"
 - "acylated residue"

![image](https://github.com/pombase/website/assets/90474/bb05c73e-009e-47ab-b22e-9f0989a9386f)

**Comment by ValWood** [comment]
nice!

**Comment by ValWood** [comment]
split acetylayed into 3 colours

GROUP sumoylated lysine/neddylated lysine/ubiquitinylated lysine

lipoconjugated residue (MOD:01155)

N-acetylated residue (MOD:00408)

**Comment by kimrutherford** [comment]
> GROUP sumoylated lysine/neddylated lysine/ubiquitinylated lysine
 
Can we use this as the grouping term for those three?: MOD:01875 ! N6-acylated L-lysine

**Comment by kimrutherford** [comment]
We might need to workshop the colours. :-)

![image](https://github.com/pombase/website/assets/90474/50f33aba-f448-419b-a20f-6bfd1aec4879)

**Comment by kimrutherford** [comment]
> split acetylated into 3 colours

I've done that but it won't be on the main site until Saturday morning.

**Comment by ValWood** [comment]
> Can we use this as the grouping term for those three?: MOD:01875 ! N6-acylated L-lysine

That will work OK

We might need to workshop the colours. :-)

If you use a royal blue instead instead of purple I think  it  will be OK, (It's fine anyway really but there are probably too many pinks and purples, will improve the contrast)

**Comment by kimrutherford** [comment]
> If you use a royal blue instead instead of purple I think it will be OK,

We already have a royal-ish blue so won't that make them hard to distinguish?

**Comment by ValWood** [comment]
Where is the royal blue? It doesn't matter if it is used for another feature type. I'm thinking more like
the colour of the Canto submit buttons

**Comment by kimrutherford** [comment]
These ubiquitinylated lysine modifications from hht1 are dark-ish blue on my screen:

![image](https://github.com/pombase/website/assets/90474/08d82142-37a7-4784-a25d-c3b437275953)

The methylated lysine to the left is purple on my screen.  There are only a few methylated residues so we mostly won't see the purple.

**Comment by ValWood** [comment]
That's purple ;)

**Comment by ValWood** [comment]
For the colour key, I think we can just add the groupings  here:https://www.pombase.org/documentation/gene-page-protein-features-widget
will be enough

**Comment by ValWood** [comment]
phosphorylated residue (MOD:00696)
methylated residue (MOD:00427)
glycosylated residue (MOD:00693)
lipoconjugated residue (MOD:01155)
N-acetylated residue (MOD:00408)
N6-acylated L-lysine  (MOD:01875) 

I think these are the grouping terms we are now using? do they cover all of the modifications?

**Comment by ValWood** [comment]
If you update the page
https://www.pombase.org/documentation/gene-page-protein-features-widget
with the modification colour key, and the image
<img width="967" alt="Screenshot 2024-01-30 at 10 16 04" src="https://github.com/pombase/website/assets/7359272/efd59355-8400-41a8-a784-f751d794ae8f">

I'll do a pombelist post

**Comment by kimrutherford** [comment]
I've updated the screenshots in the documentation and added a key for modification colours.

It's only visible in my desktop version at the moment.  It's a bit slow to load.

https://desktop.kmr.nz/documentation/gene-page-protein-features-widget

![image](https://github.com/pombase/website/assets/90474/8003d905-07a1-4ff9-bce5-2e6b0b1e1291)

**Comment by ValWood** [comment]
Looks good. Maybe we should switch the example for one with more modification colours. Perhaps sre1 (it only has 3 colours but it's the only thing I can think of with another example)

**Comment by kimrutherford** [comment]
I looked for a better example that pap1 but I couldn't find a better example that had some modifications and some alleles.

I think the detailed view looks better for pap1 because it has some multi-locus genotypes:

 - https://www.pombase.org/gene_protein_features/SPAC1783.07c
 - https://www.pombase.org/gene_protein_features/SPBC19C2.09

hht1 is a good example for modifications but not for alleles/genotypes:

  - https://www.pombase.org/gene_protein_features/SPAC1834.04

We could have two screenshots?

**Comment by ValWood** [comment]
> We could have two screenshots?
we could do that, and on the hht1 one have the mouse over "active" so that users can see that the info about the residue is there from the image.

**Comment by kimrutherford** [comment]
> we could do that, and on the hht1 one have the mouse over "active" so that users can see that the info about the residue is there from the image.

Done!

I think this can be closed now?
