### ISSUE TITLE
protein feature viewer small text changes 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2081]
track label PROTEIN FAMILIES-> PROTEIN DOMAINS

track label MUTANT POSITIONS -> AMINO ACID SUBSTITUTIONS @manulera Do you agree?

**Comment by kimrutherford** [comment]
> track label PROTEIN FAMILIES-> PROTEIN DOMAINS

Do you mean Pfam families -> Pfam domains?

**Comment by manulera** [comment]
> AMINO ACID SUBSTITUTIONS

Sounds good to me

**Comment by kimrutherford** [comment]
> AMINO ACID SUBSTITUTIONS

Would "AA SUBSTITUTIONS" be OK to keep the track name short?


![image](https://github.com/pombase/website/assets/90474/a8f14d63-9664-4cc5-8f88-0a823bdcb84b)

**Comment by ValWood** [comment]
Yes, sorry Pfam domains.
Also I think you can abbreviate to AA

**Comment by kimrutherford** [comment]
> track label MUTANT POSITIONS -> AMINO ACID SUBSTITUTIONS

I forgot to ask, does the current "Mutants" track name need to change too?

![image](https://github.com/pombase/website/assets/90474/f8cd618a-e426-4033-ae6e-581e727b5f37)

**Comment by ValWood** [comment]
Yes, sorry I wasn't clear.

The row which shows "all" should be 
"AA SUBSTITUTION POSITIONS" and the rows underneath should be
"AA SUBSTITUTION ALLELES"

**Comment by kimrutherford** [comment]
I've made those changes and updated the doc page.  It should be on the dev site in the morning.

I needed to widen the track name column to avoid this:

![image](https://github.com/pombase/website/assets/90474/81e83bb9-1bd9-499a-81d8-705720f27249)

**Comment by kimrutherford** [comment]
All done: http://dev.pombase.kmr.nz/gene_protein_features/SPAC20G8.05c

**Comment by ValWood** [comment]
will try to think of shorter names....
