### ISSUE TITLE
Protein viewer: show residues in AA substitution position track

### ISSUE THREAD

**Issue by manulera** [pombase/website#2082]
I think rather than `AA43`, it would be better if it would show the aminoacid (e.g. `P43`)

![Screenshot 2023-07-27 at 09 10 36](https://github.com/pombase/website/assets/22526102/99140b93-7d44-4841-9125-76247a6f976b)

**Comment by ValWood** [comment]
yep

**Comment by kimrutherford** [comment]
I hadn't noticed before but the allele summary track acts a bit oddly when there are multiple adjacent substitutions like in "mre11-CL454RR(CL-454-RR)".  It shows both a 2 residue feature labelled "AA 454..455" and two single residue features.  Having both seems wrong.  Should I change the code to show only single substitutions in that track?  So for "CL-454-RR" always have just two features, "C454" and "L455"?

![image](https://github.com/pombase/website/assets/90474/a96d5c37-a073-40c1-a727-cd937f8b3e70)

**Comment by manulera** [comment]
Oh, yes, that makes sense. I had not thought of that case

**Comment by kimrutherford** [comment]
I've changed the code.  The display will be updated on the main site on Saturday morning.

![image](https://github.com/pombase/website/assets/90474/1a4b76c2-89da-45de-90e0-9a6f9f29524e)
