### ISSUE TITLE
Small website changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2084]
https://www.pombase.org/status/priority-unstudied-genes
and
https://www.pombase.org/status/gene-characterisation
should also appear under "overviews"

Also we need to make sure these 2 pages are linked together.
I will put the URL to 
https://www.pombase.org/status/priority-unstudied-genes
in the paper, but it should link clearly to
https://www.pombase.org/status/gene-characterisation
(with the new graph), there is a ticket about that somewhere.

**Comment by ValWood** [comment]
https://www.pombase.org/documentation/getting-started
should also be under the 'help' menu

**Comment by kimrutherford** [comment]
> should also appear under "overviews"

Should we move them or duplicate them?

> getting-started should also be under the 'help' menu

Does it need to be in 3 menus?

**Comment by ValWood** [comment]
3 seems a bit overkill.
Maybe  "about" and "help" might be better for getting started, than "community" @manulera  what do you think?

**Comment by kimrutherford** [comment]
> but it should link clearly to https://www.pombase.org/status/gene-characterisation

Do you have a suggested sentence we could put in?

**Comment by manulera** [comment]
> Maybe "about" and "help" might be better for getting started, than "community" @manulera what do you think?

Sounds good

**Comment by kimrutherford** [comment]
> Maybe "about" and "help" might be better for getting started, than "community"

OK, I've removed it from the Community menu.

**Comment by kimrutherford** [comment]
> I will put the URL to
> https://www.pombase.org/status/priority-unstudied-genes
> in the paper, but it should link clearly to
> https://www.pombase.org/status/gene-characterisation

That's done for the morning but let me know if you'd like different wording.  This is how it currently looks:

![image](https://github.com/pombase/website/assets/90474/56a59139-5dfd-4b27-9995-5c8dca09bc51)

**Comment by ValWood** [comment]
All good!

**Comment by kimrutherford** [comment]
> This is how it currently looks:

It's currently showing a previous revision of the text.  I forgot to commit the changes from my screenshot.  It will be updated on the site soon.
