### ISSUE TITLE
Link Literature gene counts and add a publication gene list page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2087]
I know this isn't a priority, but I got annoyed that the gene counts in the Literature section weren't links.  I've changed that and also add a page that shows the list as a normal gene results list (with QuiLT, slim links etc.).  This functionality works like the "View x genes annotated with this term ..." on the term pages.

![image](https://github.com/pombase/website/assets/90474/7e9ee7f7-81de-4629-9725-aff199fc545f)

Publication gene page:

![image](https://github.com/pombase/website/assets/90474/dee0a961-f942-48a2-96af-4dc68a957632)

On the dev site I've added a direct link from the publication pages to the list of genes from the publication:

![image](https://github.com/pombase/website/assets/90474/ae9dc37a-c8ec-4598-8fb4-1b539d411c9a)

When you're back we can discuss putting that on the main site.

I've used "reference" in some links instead of "publication" because some references aren't publications.  But I think I'll change to use "publication" everywhere to be more consistent.

See also:
  - pombase/pombase-chado#1038
  - c747b68bdde994e0066a389e6e83725c812ab3ac
  - 43c00a10a347352faefd50ea72bd647c1e6f05ef

**Comment by ValWood** [comment]
Looks good.

Can discuss.

**Comment by kimrutherford** [comment]
> When you're back we can discuss putting that on the main site.

Yes!

**Comment by kimrutherford** [comment]
> we can discuss putting that on the main site.

Done!  Example: https://www.pombase.org/reference/PMID:26404184

**Comment by ValWood** [comment]
If yu like you can add a single d=screenshot to the news feed with a short description. It's useful if we do this becasue this is the source of  website updates for publications etc

**Comment by kimrutherford** [comment]
Good plan.  I've added a news item for tomorrow morning.
