### ISSUE TITLE
I know why we don't see an "uptick"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2088]
https://www.pombase.org/status/gene-characterisation

I'm pretty sure we will see it if we include 2023. The graph only goes to 2022.

@kimrutherford   could you add this year?

**Comment by ValWood** [comment]
@manulera

**Comment by kimrutherford** [comment]
> The graph only goes to 2022.

I suspect it does goes to 2023 but it's not labelled, like 2019, 2021, etc. aren't labelled.
