### ISSUE TITLE
publication pages, what is currently hidden by default?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#209]
We can have a look at this
http://pombase2.aska.gen.nz/reference/PMID%3A27918601
http://pombase2.aska.gen.nz/reference/PMID%3A27887640

only one gene deletion is shown by default?
what was the plan here? I forgot...

**Comment by kimrutherford** [comment]
I think the plan was you show all the genotypes.  We hadn't decided if they should be on one line or one per line.

It's definitely a bug that there's only one shown.

**Comment by kimrutherford** [comment]
Should be fixed now.
