### ISSUE TITLE
Display of adaptor extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2091]
Although  it isn't configured this way,
Adaptores where possible we need to supply 2 entities as inputs (we often only know one, so we can't enforce this, I add them in the text interface)

When we capture both, it would be really good if the wording on the gene and publication page could be a bit different

Currently:

<img width="698" alt="Kim config1" src="https://github.com/pombase/website/assets/7359272/19ddf23a-36ec-445d-aee1-461df211375c">

<img width="821" alt="Kim config2" src="https://github.com/pombase/website/assets/7359272/75fcc179-4359-4af2-b9d4-8fee1f61b968">

**Comment by ValWood** [comment]
Instead, it would be useful instead of

GENE PAGE
connects tor1 connects hsp90, it said

connects tor1 **to** hsp90

PUBLICATION PAGE

tti1 connects tor1 to hsp90,  tra1 to hsp90

on the gee pages particularly, it isn'obvious that tor1 and hsp90 are connected to each other

**Comment by ValWood** [comment]
Ignore this request. It looks really odd when we only have one input for an adaptor. Could we change anything which is currently configured as "connects" back to "recruits.
That should fix everything.

**Comment by ValWood** [comment]
Ignore this request. It looks really odd when we only have one input for an adaptor. 

Instead could we change anything which is currently configured as "connects" back to "recruits.
That should fix everything.

**Comment by kimrutherford** [comment]
> Instead could we change anything which is currently configured as "connects" back to "recruits.

Done for tonight's load.

**Comment by kimrutherford** [comment]
> Instead could we change anything which is currently configured as "connects" back to "recruits.

It's back to displaying "recruits".

**Comment by ValWood** [comment]
Better thanks
