### ISSUE TITLE
Two new terms for the disease slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2094]
MONDO:0002320 congenital nervous system disorder 
MONDO:0700092 neurodevelopmental disorder

No hurry for this. I am sure it was in the website config , bu I couldn't find it.
I also need you to remind me the other way to edit in the web interface, so will wait until you can show me.

**Comment by kimrutherford** [comment]
The config file is here: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json

> I also need you to remind me the other way to edit in the web interface, so will wait until you can show me.

The steps are to go to the GitHub page for the [config file](https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json) and then choose "github.dev" from the edit menu.  Or press the fill stop key (".") on the page.

I've added some minimal documentation for the fields: https://github.com/pombase/website/wiki/Config-file#slims

**Comment by ValWood** [comment]
I just can't locate where in the file the slim terms are added?

**Comment by ValWood** [comment]
That has reduced the disorders that are not in a slim category!
