### ISSUE TITLE
check post date

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2095]
I think the date on this post must be a year out
<img width="598" alt="Screenshot 2023-09-26 at 15 46 10" src="https://github.com/pombase/website/assets/7359272/596b9622-5564-451c-a1cc-5107b9f9bd42">
should it be 2022?

**Comment by kimrutherford** [comment]
> should it be 2022?

Yep!  I got the month and day correct but the year wrong.  I've fixed the config and the site will be updated soon.
