### ISSUE TITLE
new news items required and doc links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2096]
~i) Manu's videos~
~ii) The Nomenclature paper (this should also be added to the publications page)~

We can also put some new explore PomBase rotations
i) the videos
ii) The unknowns graph

I   work these up

**Comment by kimrutherford** [comment]
I've added a news item about the paper.  Let me know if you'd like any changes.

**Comment by ValWood** [comment]
Did you get the video news item?

**Comment by kimrutherford** [comment]
> Did you get the video news item?

I haven't added that yet.

**Comment by ValWood** [comment]
OK no hurry, just checking you have it.

**Comment by ValWood** [comment]
Good to have the nomenclature item at the top of the feed for a while so maybe leave it another week anyway

**Comment by ValWood** [comment]
We should link to the videos from the "submit"  menu and the "help menu"
I suggest  making the help/documentation link "PomBase documentation" and adding a link to "Canto Documentation"
I realise they are separate sites, but I think people will look for the docs on PomBase.....

**Comment by kimrutherford** [comment]
How's this?  It's on https://desktop.kmr.nz/ if you want to have a look.

![menu_2](https://github.com/pombase/website/assets/90474/7f6ee5ee-fbb0-4385-b1f0-9ae5564f52e0)

**Comment by ValWood** [comment]
I think thats OK, but maybe it's a bit weird under 'submit', but it should be clearly visible on the Canto landing page.

**Comment by kimrutherford** [comment]
> I think thats OK, but maybe it's a bit weird under 'submit', but it should be clearly visible on the Canto landing page.

So include it in the "Submit" menu?

**Comment by ValWood** [comment]
No let's leave it off the submit menu. It will be fine as long as it is all prominent in Canto.
Since we are removing the old I'd like to check the old vs new to see that everything is covered. I don't think I will bet chance to do this until new starter training.
So for now I think we should add a link to the video docs on the Canto from page and have them both available side by side.

**Comment by kimrutherford** [comment]
Is this enough?:

![image](https://github.com/pombase/website/assets/90474/f280420d-87e5-429a-83bc-9c240c78475c)

**Comment by ValWood** [comment]
Yes!

**Comment by ValWood** [comment]
I made tickets for the 2 rotation spotlights.
I still need to consolidate the documentation but there is a curation tracker ticket for that.
