### ISSUE TITLE
make the mouse over work even when not over the precise residue

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2098]
Here:
<img width="1159" alt="Screenshot 2023-09-29 at 19 38 39" src="https://github.com/pombase/website/assets/7359272/c89945f3-e9ab-4b26-8adb-db1a6ed28baf">

I need to hover precisely over the vertical bar associated with a multi-residue allele. It would be better of the entire block activated the pop-up

**Comment by ValWood** [comment]
Is this possible easily?

**Comment by kimrutherford** [comment]
Unfortunately it's possible to get mouse-overs to work like that as far as I know.

**Comment by ValWood** [comment]
ok, i'll close this.
