### ISSUE TITLE
Speed up big term and publication pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2100]
We have some pages that load very slowly, particularly high level FYPO terms:
https://www.pombase.org/term/FYPO:0001355

and HTP publication pages, for example: https://www.pombase.org/reference/PMID:23697806
and now also: https://www.pombase.org/reference/PMID:37787768

For PMID:37787768 I'm wondering about truncating the genotype list and adding a "show me more" button:

![image](https://github.com/pombase/website/assets/90474/d972755c-106a-4034-9792-05b80b9f5b4e)

That's running on my desktop, but it's got bugs: https://desktop.kmr.nz/reference/PMID:37787768
(It's the un-optimised development version with so loading that page will still seem slow even with that change)

And we should probably also remove the "Show details ..." link at the top of the section for big pages because that's *really* slow.

**Comment by ValWood** [comment]
That works for me. We should probably add a prominent disclainer at the top

This publication has over XXX annotations and so we have truncated the displayed data in the initial view. To see all use the "show all genotype features below). Page loading may be slow. We have also disabled the "show details link". you can see specific details on any gene page.

(Needs work!)

We could also link to the spreadsheets in case anyone just wants the data to do something with,  extensions terms and all
(You can't really do this via the download because it is gene focusssd not datatype)

e.g
https://curation.pombase.org/dumps/latest_build/pombe-embl/external_data/phaf_files/chado_load/htp_phafs/PMID_37787768_phaf.tsv

**Comment by kimrutherford** [comment]
I think if we have a disclaimer it should be short and not at the top of the page.  I'd prefer it to be in the section where the annotations are truncated, probably the single locus phenotype or modification sections.

**Comment by kimrutherford** [comment]
Branch with initial code: https://github.com/pombase/website/tree/tickets/ticket-2100

**Comment by ValWood** [comment]
> I'd prefer it to be in the section where the annotations are truncated, probably the single locus phenotype or modification sections.

sounds goods

**Comment by kimrutherford** [comment]
The change I made to truncate the list of genes/genotypes (like [in the screenshot](https://github.com/pombase/website/issues/2100#issue-1929735783)) helps a lot on some pages.  Other pages have long list of gene/genotype + extension like here: https://www.pombase.org/reference/PMID:23697806
where there are lots of "has penetrance high"

That will need a different fix.

**Comment by kimrutherford** [comment]
This still needs work, but I thought I should release what I've done since it helps in some cases.  I put in a warning at the top of the section but I tried to keep it brief.  The text needs work.

![image](https://github.com/pombase/website/assets/90474/f0ee46f5-3748-4172-9fff-2ff628a00b83)

Mouse over for "Show details ..."

![image](https://github.com/pombase/website/assets/90474/06eb13ff-642f-4c25-b0df-3f93305cd8a1)

**Comment by kimrutherford** [comment]
I've made those changes and deployed it.

**Comment by ValWood** [comment]
I'll close this as done, if there is more to do it probably doesn't need to be high priority  because this is a big win, but you can put that in a new ticket.

**Comment by ValWood** [comment]
Is this working?
doesn't seem to be on
https://www.pombase.org/reference/PMID:23697806

**Comment by kimrutherford** [comment]
Hi Val.  There are two problems.  The first is that the code for truncating gene/genotype lists only kicks in if there are a large number of annotations.  That's so we don't truncate the lists on small publication pages where it's not necessary.  The number of annotations needed was set to 6000 which is more than the number of annotations in that paper (5012).  I've changed the cut off to 5000 so that page renders a little faster now.

The second problem is that that publication has a large number of extensions in summary mode, which slows it down.  That's something I haven't fixed:  https://github.com/pombase/website/issues/2100#issuecomment-1846283076
I can work on that it you think it's worthwhile.

**Comment by ValWood** [comment]
No it's fine, I just noticed the list were not truncated as I expected.

I think 5000 is a good cut off.
v
