### ISSUE TITLE
Improve copy and paste of PMID from PubMed pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2102]
This is just an annoyance, but on the PubMed pages the PMIDs have a space after the colon, like: "PMID: 37288768".  I sometimes copy and paste them into the PomBase search box but makes a mess of things.  It shows an autocomplete menu like:

![image](https://github.com/pombase/website/assets/90474/e55fbd0d-e6a4-493d-a54f-88c49929c63d)

So if you paste a PMID string from PubMed and then immediately press enter you get taken to rather random term page which usually doesn't mention the PMID at all (it's just matching the string "PMID" from the string which is why "PMID" is bold in the autocomplete results).

Grrr!  That's never what I want.

I'll fix this to remove the random terms from the autocomplete so we can paste and then press enter:

![image](https://github.com/pombase/website/assets/90474/347618af-41c5-4f10-8d11-6dbf88cb4966)

Much less surprising!

**Comment by ValWood** [comment]
OOh yes that was annoying. Thanks!

**Comment by kimrutherford** [comment]
Done!
