### ISSUE TITLE
Link to InterPro in "External references" section?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2105]
We usually have links to InterPro in the "Protein domains and properties" section, if there is an InterPro domain for the protein.

Do you think we should link to InterPro from the "External references" section for completeness?

**Comment by ValWood** [comment]
yes, definitely!

**Comment by kimrutherford** [comment]
No problem.  Is "Sequence Resources" the correct category?:

![image](https://github.com/pombase/website/assets/90474/8a9b10c8-4071-40ca-9d05-b5d383b2543b)

**Comment by ValWood** [comment]
Yes, without creating another category

**Comment by kimrutherford** [comment]
Done.
