### ISSUE TITLE
new external reference

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2107]
add linkouts to Monarch
https://monarchinitiative.org/PomBase:SPBC11B10.09

(probably need a new section, phenotype resources)

**Comment by kimrutherford** [comment]
How's this?:

![image](https://github.com/pombase/website/assets/90474/5fbef9d1-d787-41cf-8519-2f26d0e944e7)

**Comment by kimrutherford** [comment]
> ![image](https://github.com/pombase/website/assets/90474/5fbef9d1-d787-41cf-8519-2f26d0e944e7)

I went ahead and added that.  Let me know if you'd like any wording changed.

**Comment by ValWood** [comment]
I think it should be "phenotype resources" rather than disease. It includes disease but the primary purpose (and what they load from us ) is phenotypes

**Comment by ValWood** [comment]
Their tagline is "phenotype driven discovery'

**Comment by kimrutherford** [comment]
I've made those changes for tonight's load.
