### ISSUE TITLE
tRNA sequence section mentions "translation"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2108]
<img width="993" alt="Screenshot 2023-10-23 at 19 44 40" src="https://github.com/pombase/website/assets/7359272/d2da3e41-ff45-49f0-881e-efe2cd971571">

**Comment by kimrutherford** [comment]
I've fixed that.  The same fix hides the "Show nucleotide sequence" checkbox for non-coding genes and instead always show the nucleotide sequence.
