### ISSUE TITLE
Use a consistent order for conditions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2111]
This is unhelpful:

![image](https://github.com/pombase/pombase-chado/assets/90474/9b0d740f-1fb9-49a9-88ca-9ae4f0872c03)

**Comment by kimrutherford** [comment]
I fixed this while changing the code to show the condition details:
  - https://github.com/pombase/website/issues/2029#issuecomment-1807860463

**Comment by ValWood** [comment]
Yes it was a bit annoying, I kept meaning to open a ticket!
