### ISSUE TITLE
display of transcript variants in GO annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2112]
On the website, it might be nicer to display these as trm1.1 or trm1.2
so it is clear that there are not the normal sys ID

<img width="1355" alt="Screenshot 2023-11-12 at 09 59 45" src="https://github.com/pombase/website/assets/7359272/2caef7fe-414c-42f0-82c1-3dbc4c95269b">

**Comment by kimrutherford** [comment]
That's implemented now.  I'll check the main site on Wednesday morning then close the issue.
