### ISSUE TITLE
display of non- directional GIs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2113]
It might be better to switch the order so that the gene of the gene page always comes first:

<img width="1333" alt="Screenshot 2023-11-12 at 09 55 00" src="https://github.com/pombase/website/assets/7359272/4cb1ac38-3683-4c8c-9dda-582e1bab8f28">

**Comment by ValWood** [comment]
i.e rad2 exo5 here

**Comment by kimrutherford** [comment]
I'll do that.

I don't know if it's related, but looks like there is a bug displaying that interaction.  There is no relation between the "rad2" and the "exo5".  Probably missing configuration.

**Comment by kimrutherford** [comment]
> Probably missing configuration.

I think that's the problem.  I've added the config locally and it's displays correctly, with exo5 in the first column.

**Comment by kimrutherford** [comment]
> There is no relation between the "rad2" and the "exo5". 

Can you suggest what the text should be?  In Canto it's "displays Synthetic Phenotype with"

**Comment by ValWood** [comment]
Just "synthetically interacts with"

**Comment by kimrutherford** [comment]
Thanks.  That's fixed now.
