### ISSUE TITLE
target_of annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2114]
We don't need to  display a target_of annotation if the target is "itself"
<img width="1332" alt="Screenshot 2023-11-12 at 09 53 45" src="https://github.com/pombase/website/assets/7359272/78abf07e-d041-4888-847c-e282872c7e43">

**Comment by kimrutherford** [comment]
That should be fixed in the morning.

**Comment by kimrutherford** [comment]
Fixed.
