### ISSUE TITLE
Explore PomBase:  New documentation and videos for Canto (rotation)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2118]
image
https://www.pombase.org/assets/newsfeed/new_canto_video_docs.png

Explore PomBase: New documentation and videos for Canto

 [A new website](https://pombase.github.io/canto_tutorial/) with videos and documentation for [Canto](https://curation.pombase.org/), our community curation tool. The website includes short step-by-step text and video guides on how to make annotations in Canto.
[New Canto documentation front page](https://pombase.github.io/canto_tutorial/)

**Comment by kimrutherford** [comment]
That's done and on the main site.  Let me know if I've made any typos.  :-)
