### ISSUE TITLE
Making it clear when modification residues might have been updated

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2121]
Nurse lab reported difficulty in knowing when modifications have changed:

Add a warning to the top of the modification section for all genes with new coordinates

Show short text: 
Warning - residue position changes more......

Expand to full text:
"warning, the protein sequence of this feature has changed during its history, and any affected modification residues were mapped over to the new coordinates. The residues displayed here may be revised compared to the original residues described in the publications below. Please see the "gene structure history section" for sequence coordinate change(s) details.

Later we might see if we can put this information in a mouse over "previously blah"

**Comment by kimrutherford** [comment]
Note to self: put notice at top of modification sections if the gene structure has changed in the past.

**Comment by ValWood** [comment]
Additional text for
https://www.pombase.org/documentation/gene-page-modifications

The residue(s) modified (where available). 

Add
Note that the PomBase reported residues may differ from the published residues in cases where the gene structure coordinates have changed. In these cases we remap the modification to the new  residue number. If it is possible that residue numbers have changed for a given protein there is a warning at the top of the protein modification section.

**Comment by kimrutherford** [comment]
Done for the morning.

**Comment by kimrutherford** [comment]
> Note to self: put notice at top of modification sections if the gene structure has changed in the past.

Here's what I have so far.  Can you improve the message for me? 
```
Note: The intron/exon structure of this gene has changed since the genome was published
so protein modifications positions from older studies may be incorrect 
```

It's running here:
https://desktop.kmr.nz/gene/SPAC1002.17c

![image](https://github.com/pombase/website/assets/90474/17fd55b3-409d-4630-8936-a6c952f13c38)

**Comment by kimrutherford** [comment]
> Done for the morning.

I meant the changes to the docs rather than the message at the top of the modifications section.

**Comment by ValWood** [comment]
Warning ~Note~ : The **translation start or** intron/exon structure of this gene has changed since the genome was published **(see history section for change details)** ~so protein~  **Changed M**odification positions from older studies ~may be incorrect~ have been revised to match their current amino acid location.

Is that OK? we can revise on call today.

**Comment by kimrutherford** [comment]
Thanks.  I've added that message for tonight's load.  I changed "history section" to "Gene structure history section".

**Comment by kimrutherford** [comment]
I think this is done now.

**Comment by ValWood** [comment]
I don't see the message on cdc18 modification section?

**Comment by kimrutherford** [comment]
The is no gene structure history for cdc18.

**Comment by ValWood** [comment]
hmm, good point. I was thinking of cdc48
