### ISSUE TITLE
Show genes from PubMed keywords and unannotated genes from Canto on publication pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2123]
We need to decide where and how to display genes from PubMed keywords and unannotated genes from Canto on publication pages.

This is a follow on from:
 - pombase/pombase-chado#104
    - nearly done
 - pombase/pombase-chado#1038
    - I'll do this next

**Comment by kimrutherford** [comment]
Here are some examples for discussion.

This publication is a review so no annotations: https://pombase.org/reference/PMID:21572561
Genes from PubMed keywords: lsm8, rex1, rpc11, rrp6, sla1

This paper is triaged as curatable but is not yet annotated in Canto:
https://pombase.org/reference/PMID:26918805
mik1 is in the PubMed keywords, but it not in the currently annotated genes.


Note to self, query for details of publications with genes from keywords:

```sql
SELECT pub.uniquename, f.uniquename, f.name, ppt.name, pp.value,
  (SELECT value FROM pubprop pp2
   WHERE pp2.pub_id = pub.pub_id
     AND pp2.type_id in
       (SELECT cvterm_id FROM cvterm
        WHERE name = 'canto_annotation_status'))
FROM feature_pub fp
JOIN feature f ON f.feature_id = fp.feature_id
JOIN pub ON pub.pub_id = fp.pub_id
JOIN pubprop pp ON pp.pub_id = pub.pub_id
JOIN cvterm ppt ON ppt.cvterm_id = pp.type_id
JOIN feature_pubprop fpp ON fp.feature_pub_id = fpp.feature_pub_id
WHERE fpp.value = 'pubmed_keyword'
  AND ppt.name = 'canto_triage_status'
ORDER BY pub.uniquename, f.name;

```

**Comment by kimrutherford** [comment]
> This publication is a review so no annotations: https://pombase.org/reference/PMID:21572561
> Genes from PubMed keywords: lsm8, rex1, rpc11, rrp6, sla1

To test that the keyword genes are getting through to the website, I've added a table to the publication pages on my desktop version:
https://desktop.kmr.nz/reference/PMID:21572561
https://desktop.kmr.nz/reference/PMID:26918805

**Comment by kimrutherford** [comment]
> unannotated genes from Canto on publication pages.

I've had a look and I don't think it's an issue.  There are very few genes that are in Canto session but have no annotation in PomBase.  These are more or less this the only ones:
 - SPNCRNA.2244
 - SPNCRNA.5527
 - SPNCRNA.5580

They have no annotation but used are in extensions in this session: https://curation.pombase.org/pombe/curs/2278d0c4da671cf5/ro

Those three genes are in the gene list for the publication: https://pombase.org/ref_genes/PMID:21436456
and the Literature section of the three gene pages include PMID:21436456 eg. https://pombase.org/gene/SPNCRNA.5527

**Comment by ValWood** [comment]
I annotated that paper yesterday!

**Comment by kimrutherford** [comment]
> I annotated that paper yesterday!

That caused me some (self-inflicted) confusion because I was looking at the Canto webapp and pombase.org which had your new annotation but I had a local, older copy of the Canto data.  They didn't match.  :-)

**Comment by kimrutherford** [comment]
In my desktop version the genes from keywords are displayed like this:
![image](https://github.com/pombase/website/assets/90474/8b58471b-f44f-48cc-a6c2-cba88aeb88a6)

Maybe that's enough for now?

**Comment by ValWood** [comment]
Looking good!

**Comment by kimrutherford** [comment]
I've released that change: https://pombase.org/reference/PMID:21572561

**Comment by ValWood** [comment]
Are there no keywords on this?
https://www.pombase.org/reference/PMID:37525511
I can't see any other examples...

**Comment by kimrutherford** [comment]
> Are there no keywords on this?
> https://www.pombase.org/reference/PMID:37525511

It has keywords but no pombe gene name or IDs are listed.  The keywords are:
```
 Schizosaccharomyces pombe; TORC1; fission yeast; lifespan; starvation
```
from: https://pubmed.ncbi.nlm.nih.gov/37525511/

**Comment by kimrutherford** [comment]
I think this is done.
