### ISSUE TITLE
RNA sequence search widget

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2124]
We could add this to the RNA pages

It might  be only useful on the tRNA/snoRNA/snRNA/rRNA though...
<img width="1029" alt="RNA sequence search widget" src="https://github.com/pombase/website/assets/7359272/2b5256dd-a516-42a1-947d-534b400265b9">

**Comment by kimrutherford** [comment]
Is that a BLAST search?

**Comment by ValWood** [comment]
No, it looks like  nhmmer so it will be much more sensitive
https://rnacentral.org/sequence-search/

**Comment by kimrutherford** [comment]
Link to RNACentral search, with the sequence pasted in (via the link).

**Comment by kimrutherford** [comment]
> Link to RNACentral search, with the sequence pasted in (via the link).

I've had a look at this and I don't think linking to the RNAcentral search is possible.

But maybe it's not critical because we link to the RNAcentral page for RNA genes?    Those pages have a "Search for similar sequences" link: https://rnacentral.org/rna/URS00003F73E3/4896

**Comment by ValWood** [comment]
OK not critical.
