### ISSUE TITLE
minor white space issue

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2126]
There is quite a lot of white space below this image:

<img width="1314" alt="Screenshot 2024-01-11 at 19 43 29" src="https://github.com/pombase/website/assets/7359272/b009c832-13c8-4260-abc0-d18dc697938e">

**Comment by kimrutherford** [comment]
Hi Val.

I've reduced the whitespace a bit for the morning:

![image](https://github.com/pombase/website/assets/90474/16f734e8-b465-486f-a35c-ae09079e39f2)
