### ISSUE TITLE
look into reference

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2127]
I need to look into this.
I think I know what the issue is.
<img width="1323" alt="report-ref" src="https://github.com/pombase/website/assets/7359272/6800d081-adeb-4dcf-962e-efeece58b3bf">

**Comment by ValWood** [comment]
@manulera  somewhere in your code for gene structure updates, when a gene structure changes, it is assumed that any reference added during that period describes the feature coordinates. This is likely trui in 99% of cases, but we also added globally a db_xref:
/db_xref="SPD:19/19F02" which actually provides a link to the orfeome collection
which sometimes gets pulled in. 

Could these references be "blocked" at some point?
@kimrutherford

**Comment by kimrutherford** [comment]
> Could these references be "blocked" at some point?

Would it be OK just remove all the db_xrefs that aren't PubMed IDs?

**Comment by manulera** [comment]
Hi both, sorry about the late reply. Yes, that's a possibility, otherwise we could make a list of refs we want to exclude from the list in a separate text file and have the script remove those?

I can implement the change.

**Comment by ValWood** [comment]
PMID:16823372 SPD:19/19F02
is the only one I am aware of. Most of the. others. should be correct.

**Comment by manulera** [comment]
Hi @ValWood now those two references are excluded if they are picked up from the changes in contig files (this commit: [87605c9fd7aba0b1cdee9c4ff944fb9e86c21aa4](https://github.com/pombase/genome_changelog/commit/87605c9fd7aba0b1cdee9c4ff944fb9e86c21aa4)). However, in the [manual changelog](https://github.com/pombase/genome_changelog/blob/master/gene_changes_comments_and_pmids/gene-coordinate-change-data.tsv) (the one you used to maintain manually), the reference PMID:16823372 is included several times (list below). Should I remove it from there as well?

```tsv
systematic_id	comments	reference	date
SPAC3H1.04c             PMID:16823372   2010-10-21
SPCC1442.04c    frameshifted    PMID:16823372   2009-02-02
SPAC1F8.07c     frameshifted    PMID:16823372   2009-02-02
SPAC22F3.11c    frameshifted    PMID:16823372   2009-02-02
SPBC1A4.06c     frameshifted; C term exon changed from 1987076..1987675 to 1987044..1987675     PMID:16823372   2009-02-02
SPBC29A3.08     frameshifted; truncated to 2048336..2049892, 2049894..2049896   PMID:16823372   2009-02-02
SPBC13E7.01     frameshifted    PMID:16823372   2009-02-02
SPBC23G7.06c    frameshifted; now a single exon PMID:16823372   2009-02-02
SPBC14C8.09c    merged with SPBC14C8.08c; frameshifted  PMID:16823372   2009-02-02
```

Also, I noticed that `SPD:19/19F02` is only associated with `SPCC1442.04c`. Did you mean to get rid of all the refs that started with `SPD*`?

**Comment by ValWood** [comment]
The SPD:19/19F02 type links need to stay. Those are used  to create the orfeome links
in the external resources section of the gene page https://www2.riken.jp/SPD/19/19F02.html
(usually there are images associated but not for this one for some reason).

They predate PomBAse, but we never migrated over to the current system. @kimrutherford  should we do that?

**Comment by manulera** [comment]
Hi @ValWood I am not sure I follow here. From your comment "@manulera somewhere in your code for gene [...]" it seemed that you wanted those references not to appear in the gene structure history. What references did you want not to appear?

**Comment by ValWood** [comment]
AH sorry, yes they should not appear in the gene structure history.

When you  asked:
Also, I noticed that SPD:19/19F02 is only associated with SPCC1442.04c. Did you mean to get rid of all the refs that started with SPD*?

I thought you were asking that we no longer needed them in the contig file at all


PMID:16823372 should not be in the manual log either, I have no idea which paper I meant   here...

**Comment by ValWood** [comment]
Yes!

**Comment by manulera** [comment]
Should be fixed now
