### ISSUE TITLE
New front page layout

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2128]
![image](https://github.com/pombase/website/assets/90474/b8220c9b-3831-4a54-a8ea-f24329ad0cfe)

**Comment by kimrutherford** [comment]
Prototype:

![image](https://github.com/pombase/website/assets/90474/877e0823-4b1e-4d60-924d-4cc3823e9c8a)

Moving the "Last updated" section is a bit more work.

**Comment by ValWood** [comment]
We could now add another "overview"  called "Status/unknowns" 
https://www.pombase.org/status/gene-characterisation

**Comment by kimrutherford** [comment]
Here's what it looks like on my phone:
![Screenshot_20240118-220605_Firefox](https://github.com/pombase/website/assets/90474/1702f9a6-079e-44c4-83cb-3c364f2e8db8)

**Comment by ValWood** [comment]
nice!

**Comment by kimrutherford** [comment]
> moving the "last updated" section to the header will help too, it definitely feels that it's the wrong place for it.

Would it work to have it in the header?

![image](https://github.com/pombase/website/assets/90474/c3134914-d25c-4536-aa16-9c45a17941b0)

**Comment by kimrutherford** [comment]
Alternative:

![image](https://github.com/pombase/website/assets/90474/93ace1f3-0242-4600-bc12-54b7fe0f66bb)

**Comment by kimrutherford** [comment]
> We could now add another "overview" called "Status/unknowns"

Like this?:

![image](https://github.com/pombase/website/assets/90474/9f992b19-ed96-4493-8327-f5edc38beead)


https://desktop.kmr.nz/

**Comment by ValWood** [comment]
I like it in the header, or underneath the header.   Possibly in the header looks cleaner, and the tag line isn't particularly useful? Which do you prefer? I think it makes sense to have it at the top of every page.

The unknowns overview looks good, that is what I envisaged. especially since we talk about it in the paper.

**Comment by kimrutherford** [comment]
> I like it in the header, or underneath the header. Possibly in the header looks cleaner, and the tag line isn't particularly useful? Which do you prefer?

I prefer to have it just under the logo instead of the tag line.

Here's how it looks with the news feed on the right:

![image](https://github.com/pombase/website/assets/90474/f540f2bf-0238-45b1-a3ad-f40f96f82ddf)

**Comment by kimrutherford** [comment]
All those changes will be in the dev site in the morning.  I'll update the main site if there are no problems.

**Comment by kimrutherford** [comment]
I made a mistake which messed up JaponicusDB, so I've gone back to yesterday's release.  It should be OK tomorrow.

**Comment by ValWood** [comment]
Oh that looks fab!

I think we should make the text for 
"Last updated: 2024-01-19 395593 annotations"
the same green as the PomBase logo (it will make it pop without being too garish)

Also suggested text change:

PomBase is a comprehensive ~database~ knowledgebase for the fission yeast Schizosaccharomyces pombe, providing ~structural and functional annotation~, literature curation, analysis tools, genome annotation and access to large-scale data sets

also can we make the "status unknown link to 
" https://www.pombase.org/status/gene-characterisation

**Comment by kimrutherford** [comment]
> I think we should make the text for
> "Last updated: 2024-01-19 395593 annotations"
> the same green as the PomBase logo (it will make it pop without being too garish)

On my screen the contrast between the text and the background isn't great if we use that green:

![image](https://github.com/pombase/website/assets/90474/d9297535-f1b4-42fa-a110-534c07ead151)

![image](https://github.com/pombase/website/assets/90474/a790cf5b-d9ac-422e-99df-526567aa5dfa)

**Comment by kimrutherford** [comment]
> Also suggested text change:

> also can we make the "status unknown link to

I've made those changes and they'll be live in 20 minutes-ish.

**Comment by ValWood** [comment]
>On my screen the contrast between the text and the background isn't great if we use that green:

good point, also not good for red green colour blind, we ca leave that

**Comment by kimrutherford** [comment]
> I made a mistake which messed up JaponicusDB, so I've gone back to yesterday's release. It should be OK tomorrow.

It's OK now, but it doesn't look as good as PomBase.  It's a bit minimal.

Is there anything we could or should say after "This is the Schizosaccharomyces japonicus genome database"?

![image](https://github.com/pombase/website/assets/90474/ba3040fd-7d9c-46a3-a79c-0c186f78afa8)

**Comment by ValWood** [comment]
Yes!
JaponicusDB is a comprehensive knowledgebase for the fission yeast Schizosaccharomyces japonicus, providing literature curation, analysis tools, and genome annotation. A sentence about japonicus as a model? @snezhkaoliferenko ?
JaponicusDB is currently the only knowledgebase maintained entirely by community curation.


@snezhkaoliferenko also if you have any japonicus related news items we can post them in this news feed.

**Comment by kimrutherford** [comment]
> JaponicusDB is currently the only knowledgebase maintained entirely by community curation.

Maybe "JaponicusDB is currently the only knowledgebase for a model organism that is entirely maintained by community curation."?

**Comment by ValWood** [comment]
Can we change the "archive" lables to

1 Spotlight "View more spotlights"
2. Pombase features "View more PomBase features"

Might be more enticing.

**Comment by kimrutherford** [comment]
Perhaps we should add a more prominent link to the new archive?

![image](https://github.com/pombase/website/assets/90474/576bb233-0a6b-4791-9673-b3d0ddb2989d)

(Mock up)

**Comment by kimrutherford** [comment]
> Can we change the "archive" lables to

I agree, those are better.  I've made that change.

**Comment by ValWood** [comment]
yes do that too!

**Comment by ValWood** [comment]
We can move everything from 2022 to the archive, that's quite old news now. But we'll keep all of 2023 on the front page  for a while because they correspond to the new paper.

**Comment by kimrutherford** [comment]
> We can move everything from 2022 to the archive

Done!

**Comment by kimrutherford** [comment]
New JaponicusDB front page:

![image](https://github.com/pombase/website/assets/90474/d4b9d307-ea09-4eac-81e8-d23ca758cad7)

**Comment by kimrutherford** [comment]
> Perhaps we should add a more prominent link to the new archive?

I've done that for the morning.

**Comment by kimrutherford** [comment]
> We can move everything from 2022 to the archive

Is there anything from 2023 that we can move off the front page?

**Comment by ValWood** [comment]
Lets keep it all for a while because most is related to the new publication. We'll move it over a month or so after that

**Comment by kimrutherford** [comment]
I think we can close this and open new issues for other changes.
