### ISSUE TITLE
exact duplicate phenotype annotation in  term page detail view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#213]
http://pombase2.aska.gen.nz/term/FYPO%3A0005633

maybe conditions are missing , otherwise identical annotations from same paper

**Comment by ValWood** [comment]
Doesn't appear to be due to condition according to gene page. Looks like true duplicates...

**Comment by kimrutherford** [comment]
Drat.  I think the annotation for genotypes with 2 alleles appear twice, genotype with 3 alleles appear three times, etc.  I'll fix that.

**Comment by kimrutherford** [comment]
I've removed the duplicates for multi-allele phenotype annotations on the term and ref pages.
