### ISSUE TITLE
Add coordinates of features to pop-ups

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2131]
It would be nice if when you click on any feature it provides the precise coordinates in the pop-up (not required fo modification or mutant as these are already in the description)

<img width="1252" alt="Screenshot 2024-01-18 at 13 54 51" src="https://github.com/pombase/website/assets/7359272/0ee9abcf-1051-4e58-95be-2dab1a26441f">

**Comment by kimrutherford** [comment]
I've added the coordinates to the tooltip when you mouse-over a feature.  Adding a separate popup when you click was tricky.  Is this OK?:

![image](https://github.com/pombase/website/assets/90474/13e72b7e-053a-4fde-a530-28a7ddd765d2)

It's easy to re-format.

**Comment by ValWood** [comment]
perfect!
