### ISSUE TITLE
mmi1 structure missing from gene page?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2133]
This mmi1  structure doesn't appear to be available from the mmi1 gene page?
https://www.pombase.org/reference/PMID:27165520

**Comment by kimrutherford** [comment]
It looks OK to me?

Publication page:
![image](https://github.com/pombase/website/assets/90474/34a2b778-b62f-49bb-a2cc-6d536d2f41e8)

Gene page:
![image](https://github.com/pombase/website/assets/90474/aaf22719-21cd-4ea8-908a-bd75c94a2578)

**Comment by ValWood** [comment]
Yes you are right.

I was confuse by this:
<img width="786" alt="Screenshot 2024-01-23 at 23 21 00" src="https://github.com/pombase/website/assets/7359272/dcefba80-ce0f-44d0-887b-8819f86bd327">

when I went to Mmi1 page because I thought that all the structures sere from this publication,
maybe we should workshop that?
