### ISSUE TITLE
Allow export from the FYPO single gene annotation table of gene protein entities

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2137]
Allow export from the FYPO single gene annotation table of gene protein entities as extensions of FYPO annotations

See: pombase/website#1887

**Comment by kimrutherford** [comment]
Hi @ValWood 

I created this issue but I don't understand it.  Whoops.

Do you remember?

**Comment by ValWood** [comment]
I think its the same as you just did for GO, to be able to send the RNAs or proteins captured in extensions to the query builder.

e.g.
<img width="683" alt="Screenshot 2024-02-28 at 09 12 29" src="https://github.com/pombase/website/assets/7359272/00c8000f-b930-412a-a52f-fb3594d16ab1">

**Comment by kimrutherford** [comment]
OK. thanks.   That shouldn't be to much work - half a day at most.  Do we just need to send the genes from the "affecting()" relations to the query builder?

**Comment by ValWood** [comment]
I think probably just "affecting", but I can't remember the full range of extensions

**Comment by ValWood** [comment]
Alos allow to send all of the "target_of" genes to the advanced query:

eg
<img width="1081" alt="Screenshot 2024-03-05 at 14 54 34" src="https://github.com/pombase/website/assets/7359272/949a208d-0b21-47b0-b323-6f6a19584f9e">

**Comment by kimrutherford** [comment]
> I think probably just "affecting", but I can't remember the full range of extensions

Here's the result of a slightly dodgy Chado query.  The extensions used in FYPO annotations with the counts:
```
      4 occurs_at
     49 is_bearer_of
     58 assayed_region
    232 assayed_substrate
   1016 assayed_enzyme
   1083 assayed_transcript
   1713 assayed_protein
  11622 has_penetrance
  16622 has_severity
  19748 assayed_using
```

"affecting" on the website is "assayed_using", "assayed_substrate", "assayed_protein" or "assayed_transcript" in Chado.

**Comment by kimrutherford** [comment]
> allow to send all of the "target_of" genes to the advanced query:

Can't we do that already?

**Comment by kimrutherford** [comment]
> I thought we could to but it seems not...

I still don't get it.  There are GO and Phenotype buttons.  That's all the targets isn't it?

**Comment by ValWood** [comment]
This is a bit different. It's all genes in the "target-of" section (these are all of the upstream genes instead of the downstream genes)

**Comment by kimrutherford** [comment]
"Send all downstream (affected) genes to the Advanced Search ..."

> "affecting" on the website is "assayed_using", "assayed_substrate", "assayed_protein" or "assayed_transcript" in Chado

Send "assayed_enzyme" too.

Use "downstream" in the query code.

**Comment by kimrutherford** [comment]
Hi Val.

This is mostly done.  Should the new "send to query link" appear in just the single-locus genotype section?

**Comment by ValWood** [comment]
yes, single only

**Comment by kimrutherford** [comment]
You'll need to look under the "Cell phenotype" sub-heading for the link:

![image](https://github.com/pombase/website/assets/90474/8eb736a5-d4f4-4bfd-bffc-5451bd1d5542)

![image](https://github.com/pombase/website/assets/90474/a4b8ce18-8f07-4925-a6fc-49f77c40bcc2)

**Comment by kimrutherford** [comment]
>  It needs more testing though

I've done some more testing and I think this is OK.  Let me know what you think.  It's only running on my desktop for now.
https://desktop.kmr.nz/gene/SPCC16A11.17

**Comment by ValWood** [comment]
Looks good, sorry I was too late to test yesterday!
v

**Comment by kimrutherford** [comment]
No problem.  It's all checked in now ready for tonight's load.

**Comment by kimrutherford** [comment]
This is working now.  Let me know if you see any problems.

Here's an example: https://pombase.org/gene/SPCC16A11.17
You'll need to scroll to the cell phenotype section to see the link.  I can explain the reason for that on a call sometime.

**Comment by ValWood** [comment]
reopening, because we can now do phenotype extensions, but not "target of"

**Comment by kimrutherford** [comment]
Could you give me an example of what's missing?

**Comment by kimrutherford** [comment]
It's configured for JaponicusDB now too: https://www.japonicusdb.org/gene/SJAG_03892

**Comment by ValWood** [comment]
so we also want to be able to do the same for "target of".

Sorry, I added this to this ticket, it should really be in its own ticket. we can move this to a new ticket...

https://private-user-images.githubusercontent.com/7359272/310783648-6836ef93-55f0-4975-8a24-ce30da2f681e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODkwOTksIm5iZiI6MTcxMDQ4ODc5OSwicGF0aCI6Ii83MzU5MjcyLzMxMDc4MzY0OC02ODM2ZWY5My01NWYwLTQ5NzUtOGEyNC1jZTMwZGEyZjY4MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDc0NjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE5ZjcyMjcyZmY5Y2I0ZjI1MzZmZmRmNDMzMDIzYzYzMzZlMTdjZTM1MDdjMmVhNzRkZTJjOTczZGYxNGVkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q5IoJEO93rdc8TUT2bwJwv8XWgbeAoOI66-BKsJoI5Y

**Comment by ValWood** [comment]
So we also want to be able to do the same for "target of".

Sorry, I added this to this ticket, it should really be in its own ticket. we can move this to a new ticket...




> I thought we could to but it seems not... <img alt="Screenshot 2024-03-07 at 07 23 52" width="884" src="https://private-user-images.githubusercontent.com/7359272/310783648-6836ef93-55f0-4975-8a24-ce30da2f681e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODkyMjcsIm5iZiI6MTcxMDQ4ODkyNywicGF0aCI6Ii83MzU5MjcyLzMxMDc4MzY0OC02ODM2ZWY5My01NWYwLTQ5NzUtOGEyNC1jZTMwZGEyZjY4MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDc0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I1YWZjZjFhZGU0OTQzNzU4ZDI2MjQzNDc5ODAzZGJhMTdiZWZiY2I2YjIyODRkZGM4ZjIxMmMzZGRhZTdkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HdpypV2cOQQ-5Dhz1WgeJoRHsmPv_4QjC67wNwkUdIQ">
> 
> I think we are confusing with "target"

**Comment by kimrutherford** [comment]
> So we also want to be able to do the same for "target of".

I still don't understand sorry.  What do we need to do that we can't do already?

**Comment by ValWood** [comment]
Ignore me, we  went through this already!
