### ISSUE TITLE
text for unknowns page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2138]
I think this page  https://www.pombase.org/status/gene-characterisation needs a bit more explanation the top:

We can 'workshop' this next call:

Suggest:
Proteins without a known function have become an area of increased concern, following observations that gene characterization rates have stagnated and a large proportion of proteins remain unstudied or understudied even in model organisms. PomBase maintains an  unknown protein inventory, first described in (PMID: 30938578). We periodically review unknown proteins for available functional data from other species. 

There are multiple ways to classify whether a gene is functionally characterized, and the concept of “characterization” is clearly a continuum. However, as an initial step in defining “unknowns” we devised a simple binary classification, based on biological processes at the level of the (fission yeast GO slim set. Link this) The rationale for this process-focussed is described in more detail in ( link to new paper)  

Also the statement at the bottom:
"A list of [“Priority unstudied genes (vertebrate orthologs, unknown process, protein coding)”](https://www.pombase.org/status/priority-unstudied-genes) is updated daily."

needs to move up, probably to directly under the new text.

Timeline- before new PomBase paper is published

**Comment by kimrutherford** [comment]
I think the new text is good as it is.  Should we go ahead and add it?  We can add the link to the new paper later.

**Comment by ValWood** [comment]
yes, please.

**Comment by kimrutherford** [comment]
Does this look OK?:  https://desktop.kmr.nz/status/gene-characterisation

Manu's graph is missing because it's my desktop.

**Comment by ValWood** [comment]
yep


a few text tweaks
Proteins without a known function  >"Unknown proteins" want to move away from using "function"

Also I think the text can be displayed as a single paragraph to save space- we want the graph to be the most prominent..

**Comment by kimrutherford** [comment]
No problem.  How's this: https://www.pombase.org/status/gene-characterisation

**Comment by kimrutherford** [comment]
> The rationale for this process-focussed is described in more detail in ( link to new paper)

Note to self: add this when paper published.

**Comment by ValWood** [comment]
you can do this

**Comment by kimrutherford** [comment]
Done for tonight's load.
