### ISSUE TITLE
paper on website not in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2139]
This paper is on the rpb1 literature list?

<img width="1227" alt="Screenshot 2024-02-05 at 13 37 52" src="https://github.com/pombase/website/assets/7359272/e456b511-5e74-4ca8-9988-02163ec788e1">

**Comment by ValWood** [comment]
got it, PMID: 29899453

**Comment by ValWood** [comment]
I don't know where it's coming from though, I thought it must be in the 'legacy' gaf, but not

**Comment by kimrutherford** [comment]
Hi Val.  I think it's because of this line in `pombe-embl/supporting_files/allele_synonyms.txt`:
```
cdk9-T212A      cdk9T212A       PMID:2989945
```

It shouldn't be showing on the rpb1 page though - that's a bug which I'll fix.  It's showing in the literature list because `cdk9-T212A` is an allele in one of the genotypes on the rpb1 page and PMID:2989945 is a reference associated with `cdk9-T212A`.

**Comment by kimrutherford** [comment]
> It shouldn't be showing on the rpb1 page though - that's a bug which I'll fix.

I've thought about this.  It is a bug but it's a pain to fix and it's only a problem if there's a data error (probably only with the allele comments and synonyms files).   I prefer to fix every bug but sometimes it's lots of effort for little gain.

So let's close this once allele_synonyms.txt is fixed.

**Comment by ValWood** [comment]
Agreed. Is it possible to do a diff between papers in Canto and papers in Pombase CHado. That could  identify  any others?

**Comment by ValWood** [comment]
This one is fixed btw.

**Comment by kimrutherford** [comment]
> Agreed. Is it possible to do a diff between papers in Canto and papers in Pombase CHado. That could identify any others?

There are 175.  This is the full list:  [non_canto_pubs.txt](https://github.com/pombase/website/files/14178055/non_canto_pubs.txt)

The ones I've spot checked look sensible.

Here's a sample:

|uniquename     |title                                                                                                                                                                        |
|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|                                                                                                                                                                     
|PMID:8580465   |The beta 7 integrins in mucosal homing and retention.                                                                                                                       |
|PMID:29514954  |Assembling the mitochondrial ATP synthase.                                                                                                                                  |
|PMID:19893618  |Roles for the conserved spc105p/kre28p complex in kinetochore-microtubule binding and the spindle assembly checkpoint.                                                     |
|PMID:29440398  |Assembly of the membrane domain of ATP synthase in human mitochondria.                                                                                                      |
|PMID:27903914  |Proteomic analysis of the human KEOPS complex identifies C14ORF142 as a core subunit homologous to yeast Gon7.                                                              |
|PMID:35190689  |Using deep learning to annotate the protein universe.                                                                                                                       |
|PMID:29937227  |The Inner Nuclear Membrane Is a Metabolically Active Territory that Generates Nuclear Lipid Droplets.                                                                       |
|PMID:28335716  |Human MFAP1 is a cryptic ortholog of the Saccharomyces cerevisiae Spp381 splicing factor.                                                                                   |
|PMID:24823650  |RNA mimicry by the fap7 adenylate kinase in ribosome biogenesis.                                                                                                            |
|PMID:19933165  |CYSTM, a novel cysteine-rich transmembrane module with a role in stress tolerance across eukaryotes.                                                                       |
|PMID:35633597  |UBAP2/UBAP2L regulate UV-induced ubiquitylation of RNA polymerase II and are the human orthologues of yeast Def1.                                                          |
|PMID:25008109  |A mutation in the human CBP4 ortholog UQCC3 impairs complex III assembly, activity and cytochrome b stability.                                                              |
|PMID:11083870  |Bovine coupling factor 6, with just 14.5% shared identity, replaces subunit h in the yeast ATP synthase.                                                                   |
|PMID:28162953  |Molecular Architecture of the Major Membrane Ring Component of the Nuclear Pore Complex.                                                                                    |

**Comment by ValWood** [comment]
yep, of course, sometime I use non-pombe papers to annotate GO

**Comment by ValWood** [comment]
How is 
PMID:35190689 | Using deep learning to annotate the protein universe.
used? I can't think how I could use that?

**Comment by kimrutherford** [comment]
>How is PMID:35190689 | Using deep learning to annotate the protein universe.
> used? I can't think how I could use that?

Looks like an ortholog: https://www.pombase.org/reference/PMID:35190689

**Comment by ValWood** [comment]
i don't remember that!

**Comment by kimrutherford** [comment]
Can we close this?

**Comment by ValWood** [comment]
yep!
