### ISSUE TITLE
some phenotype display redundancy in summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#214]
![redundancy in summary view](https://cloud.githubusercontent.com/assets/7359272/23959103/1c6c530e-099c-11e7-83e8-ebb4af24274f.jpg)

**Comment by mah11** [comment]
same underlying problem as #153; also see chado ticket https://github.com/pombase/pombase-chado/issues/577

**Comment by ValWood** [comment]
duplicate

**Comment by kimrutherford** [comment]
> same underlying problem as #153; also see chado ticket

Yep, it is.  After a bit more work on the gene pages I'll fix that Chado problem - it's annoying.

**Comment by ValWood** [comment]
But its all so flippin cool. I'm really enjoying the term pages...
http://pombase2.aska.gen.nz/term/GO%3A0005741
http://pombase2.aska.gen.nz/term/GO%3A0008175
http://pombase2.aska.gen.nz/term/GO%3A0022857
You can see straight away which things are well characterized vs poorly characterised in any area now that you can see the annotation specificity...I was pleased to see how few tRNA methyltransferases and transmembrane transporters we don't know the specificity of...

and how few protein kinases we  don't yet have a single substrate for...
http://pombase2.aska.gen.nz/term/GO%3A0004674

and being able to get to ancestors is going to be so useful to people......

I'm going to show a few people (community curators) very soon.

We can begin to send people a link to their publication page when they curate a session...
Then they can start to have a play around if they want...

Its one big Noctua model...
