### ISSUE TITLE
add  images  for non spotlight publications

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2141]
Sometimes it might be useful to add images , even for publications which are not community curated but where a good model is published. In these cases we would not want the publication to appear in the spotlight archive. Is this possible?

**Comment by ValWood** [comment]
I wanted to add this one PMID:36423630

<img width="561" alt="_______spotlight-image only, malic" src="https://github.com/pombase/website/assets/7359272/375ab788-1855-4fc9-aa87-a9d95dd81272">

**Comment by kimrutherford** [comment]
> We'll need a little bit of new configuration and code. Might take an hour or two -ish.

I think we can get away with no extra config.  We already have a directory for graphical abstracts:

`website/src/assets/graphical_abstract/`
https://github.com/pombase/website/tree/master/src/assets/graphical_abstract

(I know they aren't all graphical abstracts)

How about we add non-spotlight images to that directory and I'll change the code to pick them up for display on the publication page?  I suggest we put the PMID first in the image file name so the code can match them we the publication.  I've just added the image for PMID:36423630 as:
`website/src/assets/graphical_abstract/36423630-Ugolini-Chromatin.png`
https://github.com/pombase/website/blob/master/src/assets/graphical_abstract/36423630-Ugolini-Chromatin.png

**Comment by ValWood** [comment]
yes go ahead

**Comment by kimrutherford** [comment]
> How about we add non-spotlight images to that directory and I'll change the code to pick them up for display on the publication page? I suggest we put the PMID first in the image file name so the code can match them we the publication. 

That's done for the morning.  It's a bit of a hack.

> I've just added the image for PMID:36423630 as:

We can check for the graphical abstract in the morning:
https://www.pombase.org/reference/PMID:36423630

**Comment by kimrutherford** [comment]
Hi Val.

Did we discuss changing the text "This is an existing allele"?  I can't remember what we decided.

![image](https://github.com/pombase/website/assets/90474/4d2f027f-4a31-49ba-bc01-b420dce91617)
