### ISSUE TITLE
Gene naming documentation minor updates

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2143]
https://www.pombase.org/submit-data/gene-names

1. Remove
https://www.pombase.org/submit-data/gene-names
we won't do this, and nearly all genes are named anyways...

To reserve a gene name ~in the meantime~, please [email the helpdesk](mailto:helpdesk@pombase.org?subject=gene%20name%20reservation) and include:

2. Add
Allele naming guidelines
Revised allele naming guidelines are published in << Lera-Ramirez et al>>. 

3. On
https://www.pombase.org/submit-data/gene-naming-guidelines
remove "The gene name registration form will return soon. "
from point 2

4. revise point 5
Please include your gene name(s) in the abstracts  and/or of any relevant papers. This simplifies the task of identifying yeast gene names that are already in use, and we will be able to use this data to preload the cutration tool

**Comment by ValWood** [comment]
Also, add an FAQ 
Q How do I reserve a gene name.
A To reserve a gene name please refer to our gene naming documentation 
https://www.pombase.org/submit-data/gene-names

**Comment by kimrutherford** [comment]
I've made those changes but I wasn't sure where to put the new section about allele names:
https://www.pombase.org/submit-data/gene-names

**Comment by ValWood** [comment]
Looks good!
