### ISSUE TITLE
scree wrap text?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2146]
this text is fixed and doesn't scree wrap like most of the text?

<img width="1219" alt="use screen width" src="https://github.com/pombase/website/assets/7359272/ffd5a3a6-ceb8-4fd5-80c2-70fa9a907604">

**Comment by kimrutherford** [comment]
I've set it to not be full width because it looks a bit odd.  We can tune this on the call.

**Comment by kimrutherford** [comment]
I thought it might look tidier if we split the line where the first sentence ends:

![image](https://github.com/pombase/website/assets/90474/518d786c-ee79-40e6-88e7-80e9d9463248)

The lines will wrap if the screen is narrow:

![image](https://github.com/pombase/website/assets/90474/a3c0d74b-b221-42e3-8bbb-7d67e6c4a597)

**Comment by ValWood** [comment]
yeah, I think its fine.
