### ISSUE TITLE
Remaining tasks for allele page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2147]
From @ValWood:

i just found some notes from a recent meeting about this:

GI where FYPO:blah is the double mutant phenotype
GI where FYPO:blah is the single mutant phenotype

Genotype page
Phenotypes, genetic interactions

Allele page
(all of the genotypes that a single allele is part of + phenotypes)
Alleles comment

All alleles of a gene page
Remove links to page get of expandable links to genotypes (links will be available)
Add synonyms column
Move WT and deletion to the top of the table

**Comment by kimrutherford** [comment]
Perhaps the allele pages are OK now?  Let me know if there is anything still needs doing.

Here's how they currently look:

![image](https://github.com/pombase/website/assets/90474/95ac7cc8-5857-48b7-ac6c-f81e9b1c8e38)

**Comment by ValWood** [comment]
Looks great! I think anything else can come from user suggestions.

**Comment by kimrutherford** [comment]
Great, I'll close this then.
