### ISSUE TITLE
ability to load only 1:1 or 1:many etc in iD mapping tool

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2148]
When answering a user query  using the id mapper the other day, I noticed that here, you can only send the full list to the search :

<img width="857" alt="Screenshot 2024-02-23 at 13 22 42" src="https://github.com/pombase/website/assets/7359272/ce18ffaa-2ffd-4835-98a4-d1c3eed3d656">

(I wanted to get all of the 1:many S. cerevisiae)
I could easily do it because I just screen scraped the one to many from this input view and pasted them into the search (it is clever enough to ignore anything that isn't a pombe ID), but a user would not expect that they could do this.

**Comment by ValWood** [comment]
(I was doing all of cerevisiae, not this eg !)

**Comment by kimrutherford** [comment]
I'm not sure how to do this without making the page more messy or confusing.  Any ideas?

**Comment by ValWood** [comment]
Only  making into 3 clearly separate sections

and putting
Use the matching genes as a gene list in the Advanced Search: [Use genes]

after each...

**Comment by kimrutherford** [comment]
I tried a few options and I think the tidiest plan to do something like this:

![image](https://github.com/user-attachments/assets/ad22ec32-f2db-4e36-9d9c-485075b836c8)

We can discuss what to put in the menu:

![image](https://github.com/user-attachments/assets/6c6a47ed-59a5-4d45-928b-d56ba5f66806)

Let me know what you think.

**Comment by ValWood** [comment]
looks good! I like it.

**Comment by kimrutherford** [comment]
Great.

Can you recommend what the text in the selector should be:
 
  - All matches
  - One to one matches
  - Many to one matches
  - One to many matches
  - Many to many matches

The description on the current page for the "One to many" case says:
One identifier in your list mapped to multiple genes (paralogs) in S. pombe. All paralogs were included.

It doesn't mention one-to-many so should we say something like "matches to paralogs" in the selector?

**Comment by kimrutherford** [comment]
I have a prototype running here: https://desktop.kmr.nz/identifier-mapper-results

This is my test list to cover all of the possibilities:
any1 cdk1 nedd4 acta1 acta2 prkca prkcb

**Comment by ValWood** [comment]
It looks good, works as expected and the labelling is fine!

**Comment by kimrutherford** [comment]
OK, that's live on the main site.
