### ISSUE TITLE
check/add for line required for display labels in pro-mini ontology

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2151]
check/add for line required for display labels in pro-mini ontology

**Comment by kimrutherford** [comment]
There are 66 terms that don't have a "property_value: pombase_gene_id" line.  Some of them might not need a pombe gene ID, like:
```
[Term]
id: PR:000005216
name: cell division cycle 5-like protein
def: "A protein that is a translation product of the human CDC5L gene or a 1:1 ortholog thereof." [PRO:DNx]
comment: Category=gene.
synonym: "cdc5-like protein" EXACT []
synonym: "CDC5L" EXACT PRO-short-label [PRO:DNx]
synonym: "KIAA0432" RELATED []
synonym: "PCDC5RP" RELATED []
synonym: "pombe cdc5-related protein" EXACT []
is_a: PR:000000001 ! protein
```

A lot of entries with a missing `pombase_gene_id` have a pombe display name like:
```
synonym: "Rhb1/GTP+" EXACT PomBase_display_name [PomBase:curators]
```

So it's obvious in those cases what the pombase_gene_id should be.  I'll add the missing pombase_gene_id in the easy cases and then ask for help for the hard cases.

**Comment by kimrutherford** [comment]
I've managed to add the pombase_gene_id to a lot of the terms.  There are some cases where it's not possible.

There are some complexes where we can't add the gene ID.  Mostly the term names are quite descriptive.  eg.
```
id: PR:000037318
name: cdc13:cdk1 complex (Schizosaccharomyces pombe)
```

Maybe the complexes won't appear in extensions anyway?

That cdc13:cdk1 complex doesn't appear to be used in PomBase so we don't have to worry about it.

This is a tricky case because it's the same PRO term for two genes.   But it's a parent term not a modified protein so maybe it wouldn't be used in an extension?  It's a parent term with no child terms so maybe it can be removed.
```
[Term]
id: PR:Q9UTS8
name: UPF0695 membrane protein C977.11/PB8B6.06c (Schizosaccharomyces pombe 972h-)
def: "A protein that is a translation product of any of the following genes in Schizosaccharomyces pombe 972h-: fex1/fex2." [PRO:DNx, UniProtKB:Q9UTS8]
comment: Category=organism-gene.
synonym: "Spom972h-fex2" EXACT PRO-short-label [PRO:DNx]
xref: UniProtKB:Q9UTS8
is_a: PR:000029043 ! Schizosaccharomyces pombe 972h- protein
```

Same with this case.  I'm not sure which gene this is.  Maybe it's rpn501 and rpn502?
```
[Term]
id: PR:Q9UTM3
name: 26S proteasome regulatory subunit rpn5 (Schizosaccharomyces pombe 972h-)
def: "A 26S proteasome non-ATPase regulatory subunit 12 that is encoded in the genome of Schizosaccharomyces pombe 972h-." [OMA:SCHPO02037, PANTHER:PTHR10855\:SF1, PRO:DNx]
comment: Category=organism-gene.
synonym: "Spom972h-PSMD12" EXACT PRO-short-label [PRO:DNx]
xref: UniProtKB:Q9UTM3
is_a: PR:000029043 ! Schizosaccharomyces pombe 972h- protein
```

Same again, yip11/yip12:
```
[Term]
id: PR:Q9P347
name: survival of motor neuron protein-interacting protein yip1 (Schizosaccharomyces pombe 972h-)
def: "A protein that is a translation product of any of the following genes in Schizosaccharomyces pombe 972h-: yip11/yip12." [PRO:DNx, UniProtKB:Q9P347]
comment: Category=organism-gene.
synonym: "SMN-interacting protein yip1 (Schizosaccharomyces pombe 972h-)" EXACT [UniProtKB:Q9P347]
synonym: "Spom972h-yip12" EXACT PRO-short-label [PRO:DNx]
synonym: "yab8-interacting protein 1 (Schizosaccharomyces pombe 972h-)" EXACT [UniProtKB:Q9P347]
xref: UniProtKB:Q9P347
is_a: PR:000029043 ! Schizosaccharomyces pombe 972h- protein
```

**Comment by ValWood** [comment]
I think we can add these problem ones. We don't appear to use them, and they appear to be grouping terms (possibly required by PRO from before uniprot disambiguate duplicate genes)

**Comment by kimrutherford** [comment]
I'll close this issue because most of them are fixed.  If we see any others on the gene pages we can open a new issue.
