### ISSUE TITLE
3 small text changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2152]
1.
News item about modification

could we change "hht3 gene page" here to "histone H3.3 gene page" 
<img width="153" alt="Screenshot 2024-03-03 at 10 23 15" src="https://github.com/pombase/website/assets/7359272/329a505a-2221-4d4b-a2ba-4954e11bf1ca">

2.
Typo in Canto (sorry wrong tracker!)
<img width="292" alt="Screenshot 2024-03-03 at 10 54 11" src="https://github.com/pombase/website/assets/7359272/16e0fa46-faac-4843-8f5f-5bc153c07f07">

cyle -> cycle

3.
https://www.pombase.org/status/gene-characterisation

here
<img width="974" alt="Screenshot 2024-03-04 at 06 57 15" src="https://github.com/pombase/website/assets/7359272/f1c7eef8-7974-4776-85bd-81a1cfe20d37">

process-focussed > process-focussed approach

**Comment by kimrutherford** [comment]
> could we change "hht3 gene page" here to "histone H3.3 gene page"

Do you mean change "hht1 gene page" to "histone H3.1 gene page"?

I've fixed 2 and 3 but it will take a while for the fixes to appear.

**Comment by kimrutherford** [comment]
> Do you mean change "hht1 gene page" to "histone H3.1 gene page"?

I've made that change.
