### ISSUE TITLE
GO  manual vs IEA over time

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2153]
This is a very old one I found:
<img width="1235" alt="Screenshot 2024-03-04 at 12 56 58" src="https://github.com/pombase/website/assets/7359272/7f71f0ad-05b0-4554-9832-faa463b10215">

It has
GO IEA (reducing)
GO manual (increasing)
GO total

**Comment by ValWood** [comment]
If we do this,
we should do total IEA too
Also would need to include IBA (and show how the coverage of that improves too.

Most files are available but in different places, from PomBase/GeneDB / GO/GOA

**Comment by kimrutherford** [comment]
Is this the same as?:
  - https://github.com/pombase/pombase-chado/issues/567

**Comment by ValWood** [comment]
Yes!
