### ISSUE TITLE
"Binds" menu item but no "Binds" section on gene page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2155]
https://www.pombase.org/gene/SPAC13D1.01c

We should hide the "Binds" in the menu in this case.

![image](https://github.com/pombase/website/assets/90474/bf2211c0-452d-4690-8952-f8205928494f)

**Comment by ValWood** [comment]
This is definitely low priority, becasue GO are discussing making binding a separate aspect

**Comment by ValWood** [comment]
Will keep it open for now in case that doesn't happen

**Comment by kimrutherford** [comment]
Fixed for Monday night's load.  I'll check on Tuesday morning.

This was also a problem for phenotypes for Population vs Cell menu items.

**Comment by kimrutherford** [comment]
> Fixed for Monday night's load. I'll check on Tuesday morning.

I didn't commit the first in for the PomBase load but it was in before the JaponicusDB load started.  It's fixed for japonicus which is a good sign.
