### ISSUE TITLE
Don't always display "residue" as "modified residue"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2157]
<img width="568" alt="Website-Canto-tickets" src="https://github.com/pombase/canto/assets/7359272/c9e8893a-8523-4c04-af59-b427edf95967">

to discuss

https://www.pombase.org/term/GO:0052723

**Comment by kimrutherford** [comment]
I found the code that's doing this but it has turned into a can of worms.  I've found a couple of areas of code that only worked by accident.  When I started tried to fix the residue display those bits of code failed in odd ways.  I think I've worked things out though.

So currently most `residue` properties in Chado get shown as fake `modified_residue()` extensions in the website.  This means there is a bit of special case code and config for residues (which is what was only working by accident).

Residues on protein binding annotations are handled as a different special case.  They are turned to "binding site" like here:
https://www.pombase.org/gene/SPAC31A2.16

As a test I changed the code and config locally to show the residues as `residue()` extensions on the web pages.  That fixed the problem with GO:0052723 above.

Only two other GO annotations were changed by this.

There's a second annotation on the asp1 / SPCC1672.06c page:
```
ATP hydrolysis activity  modified residue 1-385 
```

For https://www.pombase.org/gene/SPAC22E12.09c
```
serine-type endopeptidase activity  modified residue S371
```

Should those be "residue" or "modified residue"?

I've added configuration for the protein modification annotations that have residues so they still display as "modified residue" after the changes.

And I've configured the FYPO annotations that have a residue property in Chado to display as "modified residue".

Sorry, long comment.  I'll commit the changes soon and check the website on Saturday.

**Comment by kimrutherford** [comment]
> I'll commit the changes soon and check the website on Saturday.

I've done some more testing and code-tidying.  The code and config changes are committed for tonight's load.

**Comment by ValWood** [comment]
serine-type endopeptidase activity  modified residue S371

IN this one S371 is an active site residue so just "residue". It might look a bit weird because an active site is more than one residue, but it's fine for now.

We don't really curate active sites etc, but we could probably do them as protein features.
http://www.sequenceontology.org/browser/current_svn/term/SO:0001104

we have talked about importing protein features from external sources
https://github.com/pombase/pombase-chado/issues/1126
 to display in the protein feature viewer etc, so we should see what  formats and standards they use.

**Comment by kimrutherford** [comment]
It now says "residue" on the inositol hexakisphosphate 1-kinase activity (GO:0052723) page:
https://www.pombase.org/term/GO:0052723
