### ISSUE TITLE
Residue(s) not displayed for F-box protein annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2158]
Hi @ValWood

While fixing #2157 I noticed that there is an F-box protein annotation in the "Protein domains and properties" that has residues annotated in Chado but they aren't displayed.  Should they be?

From Chado: 
```
 PomBase family or domain  SPAC13D6.01  PMID:17016471  F-box protein  C172-C214
```

**Comment by ValWood** [comment]
Are there any others with residues? I deleted the residues from this one because we already have the coordinates from InterPRo.
The only reason we have curated F-boxes is that InterPro misses some....otherwise I would remove them all...

**Comment by kimrutherford** [comment]
> Are there any others with residues? 

That is the only one.

> I deleted the residues from this one because we already have the coordinates from InterPRo.

That solves the problem.  :-)

I'll close this issue.
