### ISSUE TITLE
Display of promoter info on gene pages, and genotype pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2161]
Collect all genotypes which differ only by promoter onto the same genotype page
(this is analogous to background)

Rationale:
Most users will want to see all of the associated phenotypes.

How it looks on 
Gene Page
Term page
Publication page
- display in same way and place as background
- 
Genotype page
- display in its own column like background

All alleles of a gene
Allele page

Also need to think about multi locus

**Comment by kimrutherford** [comment]
Part of this is implemented already, by accident.  Genotypes with and without promoters are already combined on the same page.  For example `mad1+[Overexpression]`  has two versions:

 - https://curation.pombase.org/pombe/curs/ed9652a888c24c94/feature/genotype/view/1/ro
 - https://curation.pombase.org/pombe/curs/ed9652a888c24c94/feature/genotype/view/7/ro

But there is only one genotype page:
 - https://www.pombase.org/genotype/mad1%2B%28wild_type%29-expression-overexpression

The promoter is getting lost when the the genotypes are merged but the annotation is kept.

One of the genotype comments is getting lost too.  Maybe the comments need to be included in the annotation table like we do for the background and we plan to do with the promoters?

**Comment by ValWood** [comment]
Some of the genotype comments are really long,  and I think many of them need to be migrated to allele comments.
Can I a list of genotype comments I can view? I think most will be relevant to any genotype,
 or even a few examples (I can't think of any genotypes with comments although there are loads)

**Comment by kimrutherford** [comment]
Here are all the genotype comments, with links to the genotype pages:  [genotype_comments.txt](https://github.com/pombase/website/files/14771447/genotype_comments.txt)

Here are some examples:

  - Bioneer library, incomplete deletion        https://www.pombase.org/genotype/atg43-1-49-203-partial_nucleotide_deletion-expression-not_assayed_or_wild_type
  - P cell genome       https://www.pombase.org/genotype/mei3delta
  - protease cleavable  https://www.pombase.org/genotype/plo1-TEVAA341-plo1%281-341%29-%28ENLYFQGAS%29-plo1%28342-405%29-%28ENLYFQGAS%29-plo1%28406-683%29-fusion_or_chimera-expression-not_assayed_or_wild_type
  - protease cleavable  https://www.pombase.org/genotype/cnp3C-TEV-cnp3C-TEV-other-expression-not_assayed_or_wild_type__plo1-TEVAA341-plo1%281-341%29-%28ENLYFQGAS%29-plo1%28342-405%29-%28ENLYFQGAS%29-plo1%28406-683%29-fusion_or_chimera-expression-not_assayed_or_wild_type
  - nak1+ and orb6+ wild type product levels    https://www.pombase.org/genotype/nak1-K39R-orb6-GFP-nak1-K39R-orb6-fusion_or_chimera-expression-not_assayed_or_wild_type
  - nak1+ and orb6+ wild type product levels    https://www.pombase.org/genotype/nak1-orb6-GFP-nak1-orb6-fusion_or_chimera-expression-not_assayed_or_wild_type
  - TPPR from dis3 C-term       https://www.pombase.org/genotype/sds21-TPPR-313-322,A312ATPPRKNKTGNSK-amino_acid_insertion_and_deletion-expression-overexpression
  - AS inserted after initiator methionine      https://www.pombase.org/genotype/cdc8-AS-M1MASM-amino_acid_insertion-expression-not_assayed_or_wild_type
  - deletion of cyclin destruction box  https://www.pombase.org/genotype/cdc13delta90-1-90-partial_amino_acid_deletion-expression-overexpression
  - medium overexpression       https://www.pombase.org/genotype/cnp1+%28wild_type%29-expression-overexpression
  - analogue sensitive  https://www.pombase.org/genotype/cdk9-T120G-T120G-amino_acid_mutation-expression-not_assayed_or_wild_type__ssu72-C13S-C13S-amino_acid_mutation-expression-not_assayed_or_wild_type
  - reported as P611S in PMID:15546915  https://www.pombase.org/genotype/cdc42+%28wild_type%29-expression-overexpression__ehs2-1-P612S-amino_acid_mutation-expression-not_assayed_or_wild_type
  - reported as P611S in PMID:15546915  https://www.pombase.org/genotype/ehs2-1-P612S-amino_acid_mutation-expression-not_assayed_or_wild_type
  - reported as P611S in PMID:15546915  https://www.pombase.org/genotype/ehs2-1-P612S-amino_acid_mutation-expression-not_assayed_or_wild_type__rho1+%28wild_type%29-expression-overexpression
  - P81nmt promoter     https://www.pombase.org/genotype/rgf3+%28wild_type%29-expression-knockdown
  - phosphomimetic      https://www.pombase.org/genotype/atf1-10D-S2D,S4D,T77E,S140D,S152D,S172D,T204E,T216E,S226D,T249E-amino_acid_mutation-expression-overexpression
  - Another version of  atf1-11M exists with T77A       https://www.pombase.org/genotype/atf1-11M-T77I-S2A,S4A,T77I,S140A,S152A,S172A,T204I,T216I,S226A,T249I,S438A-amino_acid_mutation-expression-overexpression
  - the pho8 deletion has decreased alkaline phosphatase activity in high zinc conditions       https://www.pombase.org/genotype/pho2delta__pho8delta
  - zinc binding mutant , site2 https://www.pombase.org/genotype/pho8-m2-D352A,H353A-amino_acid_mutation-expression-null
  - zinc binding mutant, site1  https://www.pombase.org/genotype/pho8-m1-D311A,H315A-amino_acid_mutation-expression-null
  - Sequence position was annotated as G1038 in the paper, but it is G1039 (Manu)       https://www.pombase.org/genotype/kms1-1-1039-partial_nucleotide_deletion-expression-not_assayed_or_wild_type
  - kinase dead https://www.pombase.org/genotype/gsk3-K61A-K61A-amino_acid_mutation-expression-not_assayed_or_wild_type
  - description based on restriction site       https://www.pombase.org/genotype/ksg1delta409-592-409-592-partial_amino_acid_deletion-expression-not_assayed_or_wild_type
  - REII Deletion of a 1.5-kb cis-acting region (REII) proximal to mat2-P       https://www.pombase.org/genotype/sir2delta
  - nmt-promoter, thiamine repressible  https://www.pombase.org/genotype/spg1+%28wild_type%29-expression-knockdown
  - nt -1790 to -1250 replaced with ura4+       https://www.pombase.org/genotype/nc-tco1-Ldelta::ura4+-%28-395%29,146-partial_nucleotide_deletion-expression-not_assayed_or_wild_type
  - analogue sensitive  https://www.pombase.org/genotype/mcs6-L87G-L87G-amino_acid_mutation-expression-not_assayed_or_wild_type
  - non-hydrolyzable ATP        https://www.pombase.org/genotype/nse4-L68C-L68C-amino_acid_mutation-expression-not_assayed_or_wild_type__smc5-E995Q-E995Q-amino_acid_mutation-expression-not_assayed_or_wild_type
  - non-hydrolyzable ATP        https://www.pombase.org/genotype/smc5-E995Q-E995Q-amino_acid_mutation-expression-not_assayed_or_wild_type
  - Kinase dead https://www.pombase.org/genotype/ark1-K147R-K147R-amino_acid_mutation-expression-overexpression
  - C-terminal truncation       https://www.pombase.org/genotype/spo5-N-225-297-partial_amino_acid_deletion-expression-not_assayed_or_wild_type
  - catalytic site mutant       https://www.pombase.org/genotype/eso1-D147N-D147N-amino_acid_mutation-expression-not_assayed_or_wild_type
  - another atf1-11M exists with T77I   https://www.pombase.org/genotype/atf1-11M-T77A-S2A,S4A,T77A,S140A,S152A,S172A,T204I,T216I,S226A,T249I,S438A-amino_acid_mutation-expression-not_assayed_or_wild_type
  - P81nmt-rgf1rgf2delta        https://www.pombase.org/genotype/rgf1+%28wild_type%29-expression-knockdown__rgf2delta
  - temperature sensitive       https://www.pombase.org/genotype/sds22-140-6-1-52-partial_amino_acid_deletion-expression-not_assayed_or_wild_type
  - duplication of codons 345 to 363    https://www.pombase.org/genotype/git7-93-S345SSYTESNGTALSTNWKDVKS-amino_acid_insertion-expression-not_assayed_or_wild_type

**Comment by kimrutherford** [comment]
Most of the code for this is finished now but the display is a bit messy.   Let's chat about it on the next call.  Possibly this case is worse than most because there are promoters and a genotype background.

This is the publication page:

![image](https://github.com/pombase/website/assets/90474/09088b90-5924-4d4f-8547-84314b2fb16a)

The genotype page is tidier:

![image](https://github.com/pombase/website/assets/90474/b1493431-fe23-46a8-8174-54da5ac597f6)

**Comment by kimrutherford** [comment]
> The genotype page is tidier:

I forgot about the plan to move the promoter into its own column in the annotation table.  That's done now:

![image](https://github.com/pombase/website/assets/90474/74457667-e454-4dcc-a152-431cb1cfa1d2)

------------------

![image](https://github.com/pombase/website/assets/90474/77872800-c993-41a0-ba51-9d4329c2bc61)

**Comment by kimrutherford** [comment]
I've just changed this:

![image](https://github.com/pombase/website/assets/90474/22e69e19-c7da-4fb8-ba58-886d4c2e4970)

to display as this instead to make it clear about exogenous promoters:

![image](https://github.com/pombase/website/assets/90474/cb26d1dd-f483-4287-b176-88dc063d6577)

Do you have any suggestions to improve this?

**Comment by ValWood** [comment]
I think the label is a bit confusing because this is a manipulated  s. pombe promoter.
As far as I remember the only reason we have the ability for people to select the pombe name when its an exact swap is to control  the contents (we can't control the contents of the free text one).  So I don't think we need to display "exogenous promoter" on the website. I'm not even sure that  we even need to link to the gene when its a swap?

CC @PCarme

**Comment by PCarme** [comment]
Linking to the gene to which the promoter is endogenously associated  doesn't seem very useful to me. Aside from the expression data, most of the information about this gene are irrelevant to the case of a promoter swap anyway...

**Comment by kimrutherford** [comment]
>  So I don't think we need to display "exogenous promoter" on the website.

So remove the text "exogenous promoter"?

**Comment by ValWood** [comment]
>I don't follow that. What do you mean by control the contents? We could just have a "Promoter swap (S. pombe)" checkbox if that's all that's needed. We could remove the ability for people to select the pombe gene if that detail isn't necessary.

I can't remember the original rationale. We want the gene, but there isn't a big reason to separate exogenous and endogenous (IMHO).

We could just always have a single field and make them  type the promoter. I think it is better to discuss this on a call.

**Comment by kimrutherford** [comment]
> Check whether the promoters we already captured in this way are not loaded as genes associated with a session

I'll remove that code when I change the loading code:
  - pombase/pombase-chado#1163

**Comment by kimrutherford** [comment]
I changed the web site code to handle having just one sort of promoter to display.  I'll push the changes at the weekend once I upgrade the Canto database to the new schema (pombase/canto#2823).

**Comment by kimrutherford** [comment]
> I'll push the changes at the weekend once I upgrade the Canto database to the new schema

That's done now.  I'll check the website on Sunday.

**Comment by kimrutherford** [comment]
> I'll push the changes at the weekend once I upgrade the Canto database to the new schema

All seems OK except that I found a case where the promoters aren't appearing in the annotation table on the gene page. 

For `mad2+[Knockdown] slp1+[Knockdown]` the promoters are on the genotype page

https://pombase.org/genotype/mad2%2B%28wild_type%29-expression-knockdown__slp1%2B%28wild_type%29-expression-knockdown

![image](https://github.com/pombase/website/assets/90474/56cf8b39-ea76-4ea7-889f-e7549b396b44)

And on the term page:
https://pombase.org/term/FYPO:0003762

![image](https://github.com/pombase/website/assets/90474/482cb94b-51eb-4efa-9ea9-375a53985660)

But they are missing from the gene page:
https://pombase.org/gene/SPAC821.08c

**Comment by kimrutherford** [comment]
> All seems OK except that I found a case where the promoters aren't appearing in the annotation table on the gene page.

Fixed.  I'll close this because it seems mostly done and there are a lot of comments.
