### ISSUE TITLE
search missing result

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2166]
when I search on the string
RNA 5'-gamma-phosphate methyltransferase activity

in the 'quick serch' or GO advanced search

I do not find
https://www.pombase.org/term/GO:1990276
RNA 5'-gamma-phosphate methyltransferase activity (GO:1990276)

**Comment by kimrutherford** [comment]
I've fixed that bug.  The auto-complete wasn't coping with the character combination "'-"
