### ISSUE TITLE
Most popular journals 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2171]
we made a list in 2022.
A couple of people said they would find it useful to see over the past 5 years, and maybe we could host on PomBase somewhere.

It doesn't need to be very prominent,  maybe:
https://www.pombase.org/documents

**Comment by kimrutherford** [comment]
Do you have the previous list to jog my memory?

**Comment by kimrutherford** [comment]
Action: add to "Other documents" here: https://pombase.org/documents

**Comment by kimrutherford** [comment]
> Action: add to "Other documents" here: https://pombase.org/documents

That's done for Tuesday morning.  I'll check then.

**Comment by kimrutherford** [comment]
> That's done for Tuesday morning. I'll check then.

https://pombase.org/documents

I turned it into an Excel file.  It's the last link on the page, under "Other documents".  It's not exactly prominent.  Should it be in a different section maybe?

The Documents page could do with updating anyway.

**Comment by ValWood** [comment]
I will tag this onto a future announcement, but I just tried the link and I can't open the file.

**Comment by kimrutherford** [comment]
> I just tried the link and I can't open the file.

What error do you get?

**Comment by ValWood** [comment]
I get this:

<img width="395" alt="Screenshot 2024-07-03 at 20 50 37" src="https://github.com/pombase/website/assets/7359272/9069c684-3266-48c9-ac5b-528c2d66c0dc">

then when I  say yes I get a message that just says "style" and still nothing opens

**Comment by kimrutherford** [comment]
Can you open this one?:

[journal_count_with_year-2024.xlsx](https://github.com/user-attachments/files/16090204/journal_count_with_year-2024.xlsx)

**Comment by ValWood** [comment]
yes!

**Comment by kimrutherford** [comment]
I've swapped in the file that works.   I've put the file in its own "Statistics" sub-heading because it was very hidden under the "Other documents" heading.  Do you have a better suggestion for the heading?

**Comment by ValWood** [comment]
Maybe call it 'publication metrics' (and we can broaden if we include other data?)

**Comment by kimrutherford** [comment]
> Maybe call it 'publication metrics' (and we can broaden if we include other data?)

Sounds good.  That change will be on the main site in a little while.

**Comment by ValWood** [comment]
all done.
How often is the file updated?

**Comment by kimrutherford** [comment]
> How often is the file updated?

It has to be done manually.  I can put it in the calendar to remind myself.  How often do you think it should be updated?

**Comment by ValWood** [comment]
every 3- (earth!) months.
But maybe update it next week  to pick up all the new Nature/Cell papers (I will put it in the next list of announcements).

**Comment by ValWood** [comment]
that was meant to be every 3-6 months closer to 6 would be ok,

**Comment by kimrutherford** [comment]
> that was meant to be every 3-6 months closer to 6 would be ok,

I've put it in the calendar for every 5 months.

**Comment by ValWood** [comment]
Out of curiosity what do we include int he journal list?  Ideally everything except "wrong organism" and "loaded in error".
I suddenly wondered about this last night...

**Comment by kimrutherford** [comment]
> Out of curiosity what do we include int he journal list? Ideally everything except "wrong organism" and "loaded in error".
I suddenly wondered about this last night...

It comes from a Chado query so includes every publication in Chado.  It might not be very accurate because there are non-pombe papers in Chado (like the UniProt paper and the SignalP paper now).

This is the list of triage types we export from Canto:

 - Curatable
 - Browser datasets, to host
 - Browser datasets, hosted
 - Method or reagent
 - Review or comment
 - Mutagenicity or toxicity study
 - Biotech
 - Modelling
 - Database
 - 3D genome organization
 - Phylogeny and evolutionary studies
 - Cell composition or WT feature
 - Not physically mapped
 - Transposon related
 - Mating-type related
 - DNA replication related
 - DNA recombination related
 - Mitochondrial sequence related
 - Sequence feature or region
 - Structure
 - Other

**Comment by ValWood** [comment]
OK sounds good!

**Comment by kimrutherford** [comment]
I've updated https://www.pombase.org/data/documents/journal_count_with_year-2024.xlsx

**Comment by ValWood** [comment]
That looks too low? Only around 80 publications so far this year?
What do we include here?

**Comment by kimrutherford** [comment]
Sorry!  I should have said that I've updated it in SVN and it will be on pombase.org tomorrow.

The updated file is here if you do svn update:
```
pombe-embl/ftp_site/pombe/documents/journal_count_with_year-2024.xlsx
```

**Comment by ValWood** [comment]
I was looking at the attached file though?
The current number for 2024 should be ~200 I would have thought (all in scope papers- there are >100 curated)

**Comment by kimrutherford** [comment]
> I was looking at the attached file though?

I didn't attach a file.  I just included the website link which will be up to date tomorrow,

The file in SVN has 203 publications for 2024.

**Comment by kimrutherford** [comment]
I've updated the file on pombase.org:
https://www.pombase.org/data/documents/journal_count_with_year-2024.xlsx

**Comment by ValWood** [comment]
OK, I thought I has looked at an attached file. Ignore!

**Comment by kimrutherford** [comment]
I've updated the Most popular journals table so it now includes all of 2024.  I've also renamed it to remove "-2024" from the file name, which was a bit odd.

It's here:
```
pombe-embl/ftp_site/pombe/documents/journal_count_with_year.xlsx
```

It will be on the main site on Wednesday, linked at the bottom of the Metrics page:
https://www.pombase.org/metrics

**Comment by ValWood** [comment]
nice!
