### ISSUE TITLE
minor issue, link in news item

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2172]
In this news item
Viewing protein modifications
2024-02-08
Modified amino acids in the protein feature viewer are now coloured by modification type. See the [histone H3.1 gene page](https://www.pombase.org/gene/SPAC1834.04) for an example.

If the default is no longer protein modifications  it won't be obvious from this link how to see the modifications, so maybe w should link to the full modification page instead?
https://www.pombase.org/gene_protein_features/SPAC1834.04

**Comment by kimrutherford** [comment]
> maybe w should link to the full modification page instead?

Good plan.  I've made that change and the site is re-releasing now.
