### ISSUE TITLE
Add the GO cam widget to the gene ontology page for the process

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2173]
Add the GO cam widget to the gene ontology page for the process

(I also have a not for 'gene set' but I can't remember what this means because  the gene set is already on the GO opage, so I thin this must mean on the widget page...

**Comment by kimrutherford** [comment]
I'm working on getting the GO-CAM details via the API.  Hopefully we can pull out the process term from those details.

**Comment by kimrutherford** [comment]
> Hopefully we can pull out the process term from those details.

Seems like that's not true?  Can we chat about this on Zoom?

**Comment by ValWood** [comment]
We can chat about this on  Friday

**Comment by kimrutherford** [comment]
Action: investigate parsing the process from the model data
  - the process will always be the object of a `part_of` relation in the model
  - we should be able to parse the GO-CAM OWL file with [rdflib](https://rdflib.readthedocs.io/en/stable/) (Python)
    - example OWL file: http://noctua.geneontology.org/download/gomodel:662af8fa00001284/owl
  - need to store the GO-CAM ID as a `gocam_id` type `cvtermprop` for the `cvterm` of the process

**Comment by kimrutherford** [comment]
> we should be able to parse the GO-CAM OWL file

We could also (I think) query the process term ID with SPARQL.   But probably we'll need to parse the OWL file anyway (to find the genes in the pathway) so we can get the process at the same time.

Note to self: the GO-CAM could change after the first time it's downloaded so we'll need to either re-download when changes occur or re-download all models (and re-parse) occasionally.

**Comment by ValWood** [comment]
>Note to self: the GO-CAM could change after the first time it's downloaded so we'll need to either re-download when changes occur or re-download all models (and re-parse) occasionally.

good point, we will be constantly tweaking and extending the models.

**Comment by kimrutherford** [comment]
> We could also (I think) query the process term ID with SPARQL.

I think this does what we need.  It returns the process term ID and model IDs for all model provided by PomBase
```
PREFIX gocam: <http://model.geneontology.org/>
PREFIX provided_by: <http://purl.org/pav/providedBy>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?gocam ?processgoid WHERE {
  GRAPH ?gocam {
    ?gocam provided_by: "http://www.pombase.org"^^<http://www.w3.org/2001/XMLSchema#string> .
    ?part obo:BFO_0000050 ?process .
    ?process rdf:type ?processgoid
  }
  FILTER(strstarts(str(?processgoid), str(obo:)))
}
```

**Comment by kimrutherford** [comment]
Curl example for using in a script:

```
curl https://rdf.geneontology.org/blazegraph/sparql \
    --data-urlencode format=json --data-urlencode query="$QUERY" -X POST > results.json
```

**Comment by kimrutherford** [comment]
I've made a wrapper script for the SPARQL query to retrieve the GO-CAM model IDs and the term IDs of the process terms mentioned in the model.

The output is here in SVN: `pombe-embl/supporting_files/production_gocam_process_id_mapping.tsv`
And here's the file as an attachment: [production_gocam_process_id_mapping.tsv.txt](https://github.com/pombase/website/files/15398511/production_gocam_process_id_mapping.tsv.txt)

@ValWood @PCarme When you have time could you let me know if those process IDs make sense for the model IDs in the file?

It's not done yet, but we should be able to run this script regularly with cron to update the file.

The next step is to load the contents of this file into Chado so the website code(*) can know which models should display on which process term page.

--------------
(*) code yet to be written  :-)

**Comment by ValWood** [comment]
Looks good to me, but I don't see ubiquinone biosynthesis, or ergosterol biosynthesis which are both in production?

**Comment by kimrutherford** [comment]
> but I don't see ubiquinone biosynthesis, or ergosterol biosynthesis which are both in production?

Are they recent models?

I think there's a delay before the models are available via the API.  Maybe it updates when there is a GO release?

**Comment by PCarme** [comment]
Is it normal that the terms listed in the attached text file only relate to my models and none of Val's ? 

Concerning my models, the main BP terms are all here, which is good. For the anomalies :
- in the Septation initiation signaling model, it lacks the GO:0031029 term. It has the  GO:0031030 and  GO:0031031 children terms, and I only added a gene annotated to the parent term recently, so it could be a question of delay
- in the silent mating-type cassette heterochromatin formation model, it lists the GO:1902801 and the GO:0006366 terms, which are not used in my model, and it lacks a few terms that I added recently again. 
- I also don't see the adenylate cyclase-activating G protein-coupled receptor signaling pathway model at all. Perhapsit is not in the release yet, although I don't think I made this one a lot later than the others. 
 
Note for myself : No gene is annotated to GO:1902406 in PomBase. Check Clp1 BP annotation.

**Comment by kimrutherford** [comment]
Thanks for checking the file.

It could be that delay is a problem.  The terms will probably be from about May 14th which is when the last GO release happened.  We should talk to the GO developers about this.

> Is it normal that the terms listed in the attached text file only relate to my models and none of Val's ?

That might be because of the time of the GO release too.

It will be interesting to see how the results change after the next GO release.

**Comment by PCarme** [comment]
I definitely made the adenylate-cyclase pathway model before May 14th, so it doesn't seem to depend on the GO release though...

**Comment by kimrutherford** [comment]
> I definitely made the adenylate-cyclase pathway model before May 14th, so it doesn't seem to depend on the GO release though...

OK, interesting.  Do you think you marked the model as "production" before May 14th?

**Comment by PCarme** [comment]
I am pretty sure of that. And Noctua shows the last modification date as April 29th.

**Comment by kimrutherford** [comment]
> I am pretty sure of that. And Noctua shows the last modification date as April 29th.

OK, thanks.  I'll ask the GO-CAM developers about that.

**Comment by ValWood** [comment]
@PCarme  note that "maturation" refers to the pre- division "maintenance" of the ring.

historically the steps of cytokinesis were described as
i) division site positioning
ii) contractile ring assembly
iii) contractile ring maintenance 
iv) contractile ring constriction/septum assembly
which is followed by mitotic exit (this bit of the ontology is a bit of a mess).

contractile ring maturation  was recently renamed  from 
contractile ring maintenance involved in cell cycle cytokinesis involved in mitotic cell cycle
based of feedback from Kathy G, this stage is now more commonly called maturation (I'm not sure what happens in maturation, but  there are some pot assembly changes to the ring before constriction)

(I need to add "contractile ring maintenance" back as an exact synonym)
So I'm not sure Clp1 should be "maturation", but I don't know what distinguishes maintenance from assembly.

**Comment by PCarme** [comment]
Alright, thanks for the precisions ! I'll keep that in mind while reviewing the role of Clp1. In any case, it shows an annotation to "maturation" in Noctua, but not on PomBase. In fact, nothing is annotated to this process on PomBase.

**Comment by ValWood** [comment]
Thats a realy old PomBase annotation, I must have deleted it recently:
<img width="1090" alt="Screenshot 2024-05-23 at 10 24 49" src="https://github.com/pombase/website/assets/7359272/edd95def-b3eb-4ab8-85b5-2ee801c15b82">
 and the change has not filtered through yet. Odd because I don't remember doing it!

**Comment by kimrutherford** [comment]
> > I am pretty sure of that. And Noctua shows the last modification date as April 29th.
>
> OK, thanks.  I'll ask the GO-CAM developers about that.

I asked.  Seth confirmed that the data is only updated when there is a GO release.  That is a bit disappointing for us because sometimes it is many weeks between releases.  The last release was April 24th: https://release.geneontology.org/

**Comment by ValWood** [comment]
Yes that is a long time, also to complete models we need to often wait until new annotations come through to add them to our model which means that really it takes 2 releases, which can be a  really long time.

Hopefully  this will improve? @pgaudet @vanaukenk  are there any plans to shorten this time lag?

**Comment by kimrutherford** [comment]
> I've made a wrapper script for the SPARQL query to retrieve the GO-CAM model IDs and the term IDs of the process terms mentioned in the model.

That will work for now but Seth says that the SPARQL query server will be deprecated at some point.  So we'll need to find a different solution.

**Comment by kimrutherford** [comment]
> That will work for now but Seth says that the SPARQL query server will be deprecated at some point. So we'll need to find a different solution.

SPARQL is being deprecated by GO in favour of the [GO API](https://api.geneontology.org)

We can query for terms given a list of GO-CAM IDs with this end-point: `/api/models/go`

That returns all the terms in the model so we'll need to narrow the result down to process terms.

https://geneontology.org/docs/tools-guide/

**Comment by kimrutherford** [comment]
I'm implemented a prototype of this.  It will be available on the dev site on Sunday morning.

The widget should appear on these term pages:
 - GO:0006366
 - GO:0006370
 - GO:0030466
 - GO:0031028
 - GO:0031030
 - GO:0031031
 - GO:0031507
 - GO:0140281
 - GO:1902406
 - GO:1902801

Hopefully I haven't broken the existing Rhea reaction widget on term pages.

![Screenshot 2024-05-25 at 22-35-48 PomBase - Ontology term - GO 0031030 - negative regulation of septation initiation signaling](https://github.com/pombase/website/assets/90474/f36208fc-0a9b-4cb0-a735-a7376ee98957)

**Comment by kimrutherford** [comment]
> I'm implemented a prototype of this. It will be available on the dev site on Sunday morning.

I forgot to check in one of the changes so I broke the nightly load.  At least it was at the weekend.  :-)

I'll check on Monday morning.

**Comment by kimrutherford** [comment]
> I'm implemented a prototype of this. It will be available on the dev site on Sunday morning.

It's on the dev site now.  Here's an example: http://dev.pombase.kmr.nz/term/GO:0031030

**Comment by kimrutherford** [comment]
It's a little thing, but I've added a note to the term mouseover in the case where there's is a model for the term.  Ideally in future I'd like a thumbnail of the model to appear in the mouse-over, like we do for the Rhea reactions.  But we don't have the technology for that yet.

![go-cam-mouseover](https://github.com/pombase/website/assets/90474/27a8bf94-bd3c-4353-a5dc-a7a90de97851)

**Comment by PCarme** [comment]
That's a good idea, although some (most ?) processes might be a bit too complicated to be shown in a small thumbnail. 

![image](https://github.com/pombase/website/assets/163283897/f49f27cd-8718-4a8b-b970-e956fb58736e)

I mean, models like this one will probably look more like a mess than anything...

**Comment by kimrutherford** [comment]
> although some (most ?) processes might be a bit too complicated to be shown in a small thumbnail.

Good point!

It's easier to make a small version of the Rhea reactions.

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
This can close. New issues, new tickets.  MAinly we are waiting on GO fixes
