### ISSUE TITLE
Add a filter for interaction type

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2174]
I think this could be quite useful since currently they are alphabetical  by gene

<img width="1372" alt="add a filter for interaction type" src="https://github.com/pombase/website/assets/7359272/77934b83-6ba5-439c-871e-3aa0e518c676">

**Comment by kimrutherford** [comment]
Good plan.  It's probably 2-3 hours work.

**Comment by kimrutherford** [comment]
That's done now:

![image](https://github.com/pombase/website/assets/90474/fca028d4-a51f-4a2d-a2fd-c250f23a0b31)

**Comment by ValWood** [comment]
nice, will announce this with some other stuff
