### ISSUE TITLE
genes link

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2175]
this page  doesn't have the genes listed
https://www.pombase.org/ref_genes/PMID:16884933

**Comment by kimrutherford** [comment]
Oh dear.  Looks like all publication pages that contains orthologs have the bug.  I'll fix that now!

**Comment by kimrutherford** [comment]
I think I've fixed that in time for the nightly load.  I'll check in the morning.

**Comment by kimrutherford** [comment]
Fixed.
