### ISSUE TITLE
publications are giving   a server error

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2181]
e.g.

https://www.pombase.org/reference/PMID:37531259

**Comment by kimrutherford** [comment]
Thanks for spotting that.  I've switched back to yesterday's load while I investigate.

**Comment by kimrutherford** [comment]
Sorry for that bug.  I've committed a fix and the main site will be updated with today's release in 30-40 minutes.

It was an unintended side-effect of the fix for:
  - pombase/website#2178

**Comment by kimrutherford** [comment]
> I've switched back to yesterday's load

Turns out that doesn't help, but the real fix is on its way.
