### ISSUE TITLE
External links to phosphoproteomics dataset mating and  cell cell fusion

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2182]
It's only on bioarchiv right now but we can add the links any time.

[pombephosphoproteomics.unige.ch]

An example gene with data is SPAC20G4.02c

 I think you would need to access the lists of genes for each dataset from the publication
https://www.biorxiv.org/content/10.1101/2024.06.04.597361v1

**Comment by kimrutherford** [comment]
Should we always have a link or only for genes where there is data?

I've had a look at the supplementary data and pulled out a list for genes that have data.  I can add links for only those genes quite easily.

Note to self:
These cases will need to be handled with care:

UniProt ID | S. pombe genes
-- | --
O14460 | eft201 (SPAC513.01c)                                     eft202 (SPCP31B10.07)
P09322 | hhf1 (SPAC1834.03c)                                     hhf3 (SPBC1105.12)                                     hhf2 (SPBC8D2.03c)
P09988 | hht1 (SPAC1834.04)                                     hht2 (SPBC8D2.04)

**Comment by kimrutherford** [comment]
What text should appear in the external references table for these links?  What section (column 1 of the table) should they appear in?

**Comment by kimrutherford** [comment]
@ValWood 

I'll need your advise for this one:

**Comment by kimrutherford** [comment]
I've added a data file: `pombe-embl/external_data/pombephosphoproteomics.unige.ch.genes.tsv`
and it will be loaded into Chado on Monday night.

It's a pombe systematic ID to UniProt mapping, but only for the genes that have data at pombephosphoproteomics.unige.ch

**Comment by kimrutherford** [comment]
> What text should appear in the external references table for these links? What section (column 1 of the table) should they appear in?

I realised that "Proteomics" was the obvious choice.  :-)

How's this for the external references table?:

```
Proteomics   PombePhosphoproteomics   A9ZLL8   Phosphorylation changes during sexual reproduction
```

**Comment by ValWood** [comment]
that's perfect.

**Comment by kimrutherford** [comment]
Great.  The links will be live in the morning if all goes well.

**Comment by ValWood** [comment]
fantastic!

**Comment by kimrutherford** [comment]
Done!

**Comment by ValWood** [comment]
I tweeted, do you want to post to pombelist ?

**Comment by kimrutherford** [comment]
Sophie has suggested that we add a second link so that we can link directly to the cell-cell-fusion data.

**Comment by kimrutherford** [comment]
The new data files from Sophie are here:

```
pombe-embl/external_data/pombephosphoproteomics.unige.ch.starvation_mating_genes.tsv
pombe-embl/external_data/pombephosphoproteomics.unige.ch.fusion_genes.tsv
```

> Sophie has suggested that we add a second link so that we can link directly to the cell-cell-fusion data.

I've made the configuration and load script changes so the new link should be on the site in the morning.

**Comment by ValWood** [comment]
I added the "announce " label. This can be closed. We won't announce until we load the into modifications, can announce both together. I expect it won't be long until it is published.
