### ISSUE TITLE
Add a table of GO-CAMs on the GO-CAM documentation page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2183]
See:
 -  https://github.com/pombase/website/issues/2169#issuecomment-2167315266

**Comment by kimrutherford** [comment]
(Copied from https://github.com/pombase/website/issues/2169#issuecomment-2169195118)

> Maybe we could have a table of models on the documentation page? It could be automatically generated.

I've had a first attempt at this.  The table is generated from the data in Chado.  As you can see, there is some missing information that needs to be added.

http://dev.pombase.kmr.nz/documentation/go-cam-pathway-models

![image](https://github.com/pombase/website/assets/90474/8e356905-2493-4566-86ce-ade4d279e1f9)

------------------------
[Val's reply](https://github.com/pombase/website/issues/2169#issuecomment-2169202280):

Let's discuss on Tuesday.
I  think we need to include the title of the model.

For example 
662af8fa00000499 
|soprenoid biosynthetic process
ergosterol biosynthetic process

for this the model  title is "ergosterol biosynthetic process"  (soprenoid biosynthetic process is included because isoprenoids are a precursor to ergosterol)

and  for 
silent heterochromatin formation  model some of the other processes like "siRNA-independent heterochromatin formation" are sub-processes which are part of "heterochromatin formation, but cannot have this parentage in the ontology because it isn't always true  are 'sub processes'

...although looking at the current model these have changed, because we are refining the existing annotations as we go.
The differences are due to a synchronization issue.

I guess we need to wait until the  Noctua update to see these revisions...

but it needs to be clear  what the overall model is.

--------------------------------

Current status:

We're waiting on API bug fixes so we can add the model titles to the table.

**Comment by kimrutherford** [comment]
From tomorrow the title will have titles are will look something like this:

![image](https://github.com/pombase/website/assets/90474/fa2c30e3-63a8-4657-980b-b5ec6c3285cb)

**Comment by ValWood** [comment]
nice!

**Comment by kimrutherford** [comment]
> From tomorrow the table will have titles are will look something like this:

http://dev.pombase.kmr.nz/documentation/go-cam-pathway-models

**Comment by kimrutherford** [comment]
I'm going to close this because I haven't closed enough issues today.  :-)

Let's open new issues for fixes/changes.
