### ISSUE TITLE
New commonly used query: RNA genes with predicted 2D structures

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2187]
@ValWood 
We have "Proteins with PDB structures".  Should we add something similar for RNA structures?

**Comment by ValWood** [comment]
`That would be nice, it's diffiuclt to know which ones have secondary structures

We should call it "RNA secondary structure predictions"

**Comment by kimrutherford** [comment]
That's done for Saturday morning.  It needs a nightly load and I didn't push the changes in time.

**Comment by kimrutherford** [comment]
https://github.com/pombase/website/issues/1989#issuecomment-1926720128
> Try to embed as a widget on the tRNA, snRNA, snoRNA and rRNA pages

The list of RNA genes produced by the new query includes some RNA types that aren't in your list: lots of lncRNAs and one sncRNA ([SPNCRNA.463](https://www.pombase.org/gene/SPNCRNA.463)).  Here's the full list that will be the new query tomorrow:
https://www.pombase.org/results/from/id/68cd3116-9daa-40be-8ece-0a62cc6f2964

Should we show the 2D structure widget on those lncRNA pages?

Most of them don't look useful but there are some that fold sensibly:
https://rnacentral.org/rna/URS000230DC2B/4896
https://www.pombase.org/gene/SPNCRNA.6405

The one sncRNA with a predicted structure ([SPNCRNA.463](https://www.pombase.org/gene/SPNCRNA.463)) doesn't look great:
https://rnacentral.org/rna/URS00003E9371/4896

**Comment by ValWood** [comment]
>Most of them don't look useful but there are some that fold sensibly:
https://rnacentral.org/rna/URS000230DC2B/4896
https://www.pombase.org/gene/SPNCRNA.6405


blimey that's a tRNA embedded in a lncRNA, I will take a look at that!

**Comment by kimrutherford** [comment]
> blimey that's a tRNA embedded in a lncRNA, I will take a look at that!

There are a bunch of other lncRNA genes that look similar:

[SPNCRNA.7042](https://www.pombase.org/gene/SPNCRNA.7042) - https://rnacentral.org/rna/URS000230D4B2/4896
[SPNCRNA.7125](https://www.pombase.org/gene/SPNCRNA.7125) - https://rnacentral.org/rna/URS000230D734/4896
[SPNCRNA.7383](https://www.pombase.org/gene/SPNCRNA.7383) - https://rnacentral.org/rna/URS000230DD31/4896
[SPNCRNA.7463](https://www.pombase.org/gene/SPNCRNA.7463) - https://rnacentral.org/rna/URS000230DE76/4896
[SPNCRNA.2529](https://www.pombase.org/gene/SPNCRNA.2529) - https://rnacentral.org/rna/URS000230DC70/4896
[SPNCRNA.1669](https://www.pombase.org/gene/SPNCRNA.1669) - https://rnacentral.org/rna/URS000019CED9/4896
[SPNCRNA.2479](https://www.pombase.org/gene/SPNCRNA.2479) - https://rnacentral.org/rna/URS000230D749/4896
[SPNCRNA.2656](https://www.pombase.org/gene/SPNCRNA.2656) - https://rnacentral.org/rna/URS000230D399/4896
[SPNCRNA.2777](https://www.pombase.org/gene/SPNCRNA.2777) - https://rnacentral.org/rna/URS000230DE13/4896
[SPNCRNA.2990](https://www.pombase.org/gene/SPNCRNA.2990) - https://rnacentral.org/rna/URS000230E2E9/4896
[SPNCRNA.3131](https://www.pombase.org/gene/SPNCRNA.3131) - https://rnacentral.org/rna/URS000230DDBA/4896
[SPNCRNA.4841](https://www.pombase.org/gene/SPNCRNA.4841) - https://rnacentral.org/rna/URS000230D36A/4896

And one that RNAcentral lists as 5S ribosomal RNA:
[SPNCRNA.4731](https://www.pombase.org/gene/SPNCRNA.4731)  - https://rnacentral.org/rna/URS000230E3F3/4896

**Comment by kimrutherford** [comment]
> blimey that's a tRNA embedded in a lncRNA, I will take a look at that!

Moved to:
  - pombase/curation#3715

> That's done for Saturday morning. It needs a nightly load and I didn't push the changes in time.

That's available now.

> Should we show the 2D structure widget on those lncRNA pages?

Maybe we can discuss this on the next call.

**Comment by ValWood** [comment]
yes show them, they should all be fixed eeventually

**Comment by kimrutherford** [comment]
OK.  This can be closed then.
