### ISSUE TITLE
publication pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#219]
make long lists into rows? comma separated

![pub pages](https://cloud.githubusercontent.com/assets/7359272/24209020/000ab3b4-0f1d-11e7-87c7-f4554bb04391.jpg)

I think we discussed this so apologies if already in a ticket. I couldn't see it...

**Comment by kimrutherford** [comment]
I can't find the older ticket either.  I didn't put the genotypes without extensions on one row because we weren't sure it would look good.  I'll try it now so we can see it live.

**Comment by kimrutherford** [comment]
I've made the change.  It also changes how the phenotype sections look:
  http://pombase2.bioinformatics.nz/gene/SPBC11B10.09

Let me know what you think.

**Comment by ValWood** [comment]
For the publication pages, I think its easier to consume like this.
http://pombase2.aska.gen.nz/reference/PMID%3A16371652

especially for very long lists
http://pombase2.aska.gen.nz/reference/PMID%3A27887640

(I will ask Mikel and Jurg if they prefer this way to the long vertical list from yesterday.

For the phenotype section, I can't remember *exactly* how it looked before.
What were we displaying on the gene page?

**Comment by ValWood** [comment]
I thought we were only displaying  the  genotypes int he detailed view. Did I misremember?

**Comment by ValWood** [comment]
Yes, we were only showing int he detail view before....

**Comment by ValWood** [comment]
this page looks a bit odd:
http://pombase2.aska.gen.nz/reference/PMID%3A9177184

**Comment by kimrutherford** [comment]
> Yes, we were only showing int he detail view before....

The genotypes were there on the gene pages before, but now they are on one line if there is no extension.

> this page looks a bit odd:

Which bit is odd?

**Comment by kimrutherford** [comment]
> this page looks a bit odd:

It might look a little bit better now - the genotype descriptions aren't so squished.

**Comment by ValWood** [comment]
> It might look a little bit better now - the genotype descriptions aren't so squished.

thats better. 
However, I'm still wondering if on the publication we shouldn't  have the extension column further to the right. Maybe I'm overlooking something though which becomes obvius on other pages so you can ignore this for now.
We can revisit at the end.

**Comment by ValWood** [comment]
> The genotypes were there on the gene pages before, but now they are on one line if there is no extension.

OK I misremembered...

**Comment by ValWood** [comment]
So the question is.

Is this single line better on the gene pages and the publication pages?

Should it be publication pages only (this is where the lists can tend to be longer because it can be 1000's of genotypes for a single term)

**Comment by kimrutherford** [comment]
> the extension column further to the right

To my eye if the extension is too far from the gene or genotype it's quite hard to match them up visually.

**Comment by ValWood** [comment]
Good point. Also most of the offending alleles are of type "other" where we have written little stories  because we don't have a concise descriptor format.

Hopefully eventually we will be able to shorten most of these
So
cdc18-NLSdelta138(amino acids 1-138 deleted; T-antigen NLS fused to N-terminus)
might become something like:

NLS-N,aa1-138Δ

**Comment by ValWood** [comment]
On first look, I like this better Val. Tidier and less scrolling involved.

Cheers,
-Jürg


Subject: Re: FW: Make your data visible in PomBase (Curate PMID:27918601)/ a question
I have a question for you.
We changed the way alleles are displayed on publication pages from the long list version which you would have seen yesterday, to listed on a row
http://pombase2.aska.gen.nz/reference/PMID%3A27887640
Is this better?

**Comment by kimrutherford** [comment]
Shall we close this issue?

**Comment by ValWood** [comment]
OK, any tweaks changes, new tickets
