### ISSUE TITLE
left hand menu on documents page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2191]
Should. we chance this menu so that  instead it is

Abstract books
Survey results
Publication metrics

I think we can move the infographic to the publications list?

**Comment by ValWood** [comment]
>I think we can move the infographic to the publications list?

It's already there, but it doesn't need to be in 2 places, since it's now quite out of date

**Comment by kimrutherford** [comment]
Could you add a link to the page that needs changing?

**Comment by ValWood** [comment]
https://www.pombase.org/documents

**Comment by ValWood** [comment]
Action,
remove page
We don't need the old presentations.
Put the bottom 2 sections on the metrics page

**Comment by kimrutherford** [comment]
That's done now.
