### ISSUE TITLE
ortholog references

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2192]
Are we displaying references for orthologs? I ask because

SPBC354.10	UBAP2	PMID:35633597

reference is not showing

**Comment by kimrutherford** [comment]
The ortholog loader only reads 2 columns - the 2 gene IDs.  It ignores any other columns.

The orthologs from Compara and the pombe-japonicus orthologs have publications attached because we set the publication for all orthologs in those files with a command line argument on the loader.

**Comment by ValWood** [comment]
Does the loader read the db_xrefs for  the ones curated in Artemis?

**Comment by kimrutherford** [comment]
> Does the loader read the db_xrefs for the ones curated in Artemis?

Yep, it does.

I've never added the same code for the TSV ortholog file reader.

**Comment by ValWood** [comment]
OK I will migrate this one , I usually put them there I forgot

**Comment by ValWood** [comment]
This worked, but the reference only appears on one of the orthologs, but it supports both:

<img width="1004" alt="Screenshot 2024-07-16 at 09 09 51" src="https://github.com/user-attachments/assets/2b5f095a-ae76-412a-bb51-7900a67efd46">

**Comment by kimrutherford** [comment]
Looks like a very old bug!  There are other cases too: https://www.pombase.org/gene/SPBC25H2.09

The reference was only being applied to the first ortholog from `/controlled_curation`.  I think I've fixed this.  I'm doing a test load on my desktop to confirm.

**Comment by kimrutherford** [comment]
> I think I've fixed this. I'm doing a test load on my desktop to confirm.

The test worked so that fix should be on the main site in the morning.

**Comment by kimrutherford** [comment]
> The test worked so that fix should be on the main site in the morning.

Now fixed:

![image](https://github.com/user-attachments/assets/2a620928-9286-4296-beb4-4d564ebd5e44)
