### ISSUE TITLE
move  external links to Sophies data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2193]
I just noticed these are under "proteomics" but they would be better under modifications (sorry, I checked this but didn't notice until I went to look at something)

The proteomics link is really only to the proteomics repository ( i.e peptides)
but this is specific data for phosphosites

<img width="1147" alt="fix links" src="https://github.com/user-attachments/assets/7a1d636f-6456-4dc0-812e-ff6f21a6c698">

**Comment by kimrutherford** [comment]
No problem.  I've changed  the configuration.

It will need a nightly load to update the main site.  I'll check in the morning.

**Comment by kimrutherford** [comment]
I mis-remembered.  This just needed a config change and to re-release the site.  Done now.
