### ISSUE TITLE
small website bug in gene expression section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2194]
For qualitative the ID is appearing instead of the description?

<img width="410" alt="ticket-website-bug" src="https://github.com/user-attachments/assets/1b4e8849-8e6f-4226-84a8-22dd13b2ef88">

**Comment by ValWood** [comment]
Damn I didn't record which gene page this was.

And i suddenly thought it might be a syntax error (since it seems specific to this page)

but I grepped on
grep "PomGeneEx:0000011" *
in external_data/qualitative_gene_expression_data
and it gives me nothing?

**Comment by kimrutherford** [comment]
> For qualitative the ID is appearing instead of the description?

The term name is in the next column.  Should we hide the term ID in this case?

![image](https://github.com/user-attachments/assets/44eaf4db-daa9-4808-a79f-10c620fa4d2f)

https://www.pombase.org/gene/SPAC57A10.06

**Comment by kimrutherford** [comment]
> And i suddenly thought it might be a syntax error (since it seems specific to this page)

It's how the Qualitative annotations look in the detailed view.

https://www.pombase.org/gene/SPAC688.04c

>but I grepped on
> grep "PomGeneEx:0000011" *
> in external_data/qualitative_gene_expression_data
> and it gives me nothing?

Looks like it's from `chromosome1.contig`:

```
FT   CDS             join(1376587..1376947,1377032..1377072)
FT                   /colour=12
FT                   /product="Schizosaccharomyces specific protein Mug15"
FT                   /primary_name="mug15"
FT                   /systematic_id="SPAC57A10.06"
FT                   /controlled_curation="term=gene expression, RNA level;
FT                   annotation_extension=during(GO:0051321);
FT                   qualifier=increased; evidence=ECO:0000006;
FT                   db_xref=PMID:16303567; date=20100103"
```

The `qualifier=increased` in the controlled_curation gets mapped to `PomGeneEx:0000011` and that term is stored for the annotation in Chado.

**Comment by ValWood** [comment]
OK I forgot there were some expression in contigs, I guess we could export those into a flat file at some point.

We don't need to display the ID, those are just internal really.

**Comment by kimrutherford** [comment]
> We don't need to display the ID, those are just internal really.

I've added code to allow the term_id column to be hidden or shown by configuration.  For now it's only hidden for Qualitative annotations.

To implement this I needed to change the annotation table code so let me know if you spot anything odd.

**Comment by kimrutherford** [comment]
I got the JaponicusDB configuration wrong so the Qualitative gene expression table still has a Term ID column.  Fixed for tomorrow.
