### ISSUE TITLE
Gene pages: broken paralogs sections

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2195]
This issue inspired me to see how paralogs are displayed at the moment:
 - https://github.com/pombase/pombase-chado/issues/31

It's not good.

There are duplicates and no Descriptions:

https://www.pombase.org/gene/SPCC622.03c
![image](https://github.com/user-attachments/assets/86efe1bb-5301-4771-914f-c459cfa65fd9)

https://www.pombase.org/gene/SPAC17A2.01
![image](https://github.com/user-attachments/assets/31172355-83a1-4ce1-a762-0178f0920db3)

https://www.pombase.org/gene/SPAC2F7.03c
![image](https://github.com/user-attachments/assets/5a2ff568-699d-4de3-b83f-c39699fd5ed6)

**Comment by kimrutherford** [comment]
First fix, add the product:

![image](https://github.com/user-attachments/assets/fe93f91f-e797-42fa-b35b-a673475780fd)

(The fix will be on the main site on Wednesday morning)

**Comment by kimrutherford** [comment]
> There are duplicates

That's fixed now.

I also noticed that some paralogs we're displayed.  There was a bug in the loading code that had been there 13 years.  :-(
Whoops.

It's taken 13 years but the paralogs section on the gene page is now useful:

![image](https://github.com/user-attachments/assets/6f92be06-b9e8-47f9-abf9-73075bbb2c72)

**Comment by ValWood** [comment]
Excellent!
