### ISSUE TITLE
Add disease associations to annotation datasets

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2197]
Add disease associations to annotation datasets
here:
https://www.pombase.org/datasets

**Comment by kimrutherford** [comment]
Which file should we link to?

**Comment by ValWood** [comment]
Good point, we don't export this file.

We only have:
vw253$ more pombase_disease_associations_mondo_ids.tsv 
SPAC27F1.06c            MONDO:0016002           PB_REF:0000003  2024-04-04
SPBC83.01               MONDO:0016576           PB_REF:0000003  2023-12-12
SPBC800.10c             MONDO:0016576           PB_REF:0000003  2023-12-12
SPAC1687.09             MONDO:0016576           PB_REF:0000003  2023-12-12
SPBC11G11.02c           MONDO:0016576           PB_REF:0000003  2023-12-12
SPAC1420.04c            MONDO:0016387           PMID:38068960   2023-12-12
SPAC19B12.13            MONDO:0016387           PMID:38068960   2023-12-12
SPBC16D10.08c           MONDO:0859237           PB_REF:0000003  2023-09-14
SPBC16D10.08c           MONDO:0014561           PB_REF:0000003  2023-09-14
SPBC16D10.08c           MONDO:0030726           PB_REF:0000003  2023-09-14
SPAC977.17              MONDO:0859237           PB_REF:0000003  2023-09-14
SPAC977.17              MONDO:0014561           PB_REF:0000003  2023-09-14


as one input file and the rest  generated from Ortholog table and Monarch data.

So could we write out a file of all disease associations in this format?

**Comment by kimrutherford** [comment]
Looks like we already write a file:
 - https://curation.pombase.org/dumps/latest_build/misc/disease_association.tsv
 - https://github.com/pombase/pombase-chado/issues/888

Maybe done for PombeMine?

We need to decide where to put in the data directory:
  https://www.pombase.org/data/

Looks like we already have a good place in the new release directory structure:
  https://www.pombase.org/public_releases/pombase-2024-06-01/human_disease_annotation/

**Comment by ValWood** [comment]
> We need to decide where to put in the data directory:
[https://www.pombase.org/data/](https://eur03.safelinks.protection.outlook.com/?


We could put in "annotations" or give it its own directory.

We also need to link from here:
https://www.pombase.org/datasets
under "annotation datasets"
so maybe "annotation" is the best place?

**Comment by kimrutherford** [comment]
> We could put in "annotations" or give it its own directory.

I've put it in "annotations" to keep things tidy.  I've changed the load script to update the files each night.

I'll make sure everything is in place after Wednesday night's load, then update the datasets docs page.

**Comment by kimrutherford** [comment]
We need a description to put in the table.  Can you improve this for me?:

"Fission yeast orthologs of human disease associated genes with disease descriptions and Mondo ontology terms"

(Mostly copied from: https://www.pombase.org/documentation/disease-association)
("Mondo" could be a link to https://mondo.monarchinitiative.org/)

Thanks.

**Comment by ValWood** [comment]
sounds good!

**Comment by kimrutherford** [comment]
I think this is done now.

**Comment by ValWood** [comment]
We have the disease association file in the annotation datasets, but it isn't linked to from the annotations section of the annotation datasets downloads
https://www.pombase.org/datasets

**Comment by ValWood** [comment]
Also orthologs doesn't have a page, although it does have a menu item.

We could combine the orthlogs and disease datasets and  change the 
menu tab to "orthologs and disease)?
Thoughts?

**Comment by kimrutherford** [comment]
> We have the disease association file in the annotation datasets, but it isn't linked to from the annotations section of the annotation datasets downloads

There's a "Human disease associations" link in the "Annotation datasets" table?

**Comment by ValWood** [comment]
Of course.
I was looking at the l.h. menu. Should we have all the datasets mentioned in the menu?
