### ISSUE TITLE
Other SO terms for protein sequence feature view

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2198]
I noticed that there are some other SO term annotated that have residues.  Should any of these feature be included in the feature viewer?   (Show details to see the residues)

 - https://www.pombase.org/term/SO:0100011
 - https://www.pombase.org/term/SO:0002235
 - https://www.pombase.org/term/SO:0001068
 - https://www.pombase.org/term/SO:0001096
 - https://www.pombase.org/term/SO:0001810
 - https://www.pombase.org/term/SO:0001531
 - https://www.pombase.org/term/SO:0001528
 - https://www.pombase.org/term/SO:0001806

![image](https://github.com/user-attachments/assets/919f1c67-fa4f-4251-a842-71271d566679)

**Comment by ValWood** [comment]
Yes for sure!

**Comment by kimrutherford** [comment]
I can implement this on Tuesday or Wednesday (I'm on holiday on Monday).

Should we have one track or multiple tracks for these?  What should the track/tracks be labelled as?

**Comment by ValWood** [comment]
cleaved_peptide_region (SO:0100011)

this would probably work best with PROPEPTIDES

if we changed the label to PROPEPTIDES & CLEAVAGE SITES
if not it can have its own track CLEAVAGE SITES


SUMO_interaction_motif (SO:0002235)
polypeptide_copper_ion_contact_site (SO:0001096)
 PIP_box (SO:0001810)
add to BINDING SITES track

nuclear_export_signal (SO:0001531)
nuclear_localization_signal (SO:0001528)
 ER_retention_signal (SO:0001806)
change the name of  SIGNAL PEPTIDE  to LOCALIZATION SIGNALS
(Also merge mitochondrial transit peptide into this track)


https://www.pombase.org/term/SO:0001068

I'm not sure about this one. Do you have examples?

**Comment by kimrutherford** [comment]
> https://www.pombase.org/term/SO:0001068
> I'm not sure about this one. Do you have examples?

It looks like we can ignore that one.  We used to have some genes annotated with that term but they are now misc features since mid August:

```
-FT                   /controlled_curation="term=sequence feature, repeat
-FT                   containing; cv=sequence_feature; date=19700101"
+FT                   /controlled_curation="term=misc, repeat containing;
+FT                   date=19700101"
```

https://www.pombase.org/term/PBO:0114316

**Comment by kimrutherford** [comment]
> SUMO_interaction_motif (SO:0002235)
> polypeptide_copper_ion_contact_site (SO:0001096)
> PIP_box (SO:0001810)
> add to BINDING SITES track

The existing binding site features from UniProt have a ligand.  Would is the ligand for these three SO annotation types?

Example of binding site from UniProt:

https://www.pombase.org/gene/SPAC11E3.13c
![image](https://github.com/user-attachments/assets/ece2b08f-6fdb-4ab5-9e63-8353b14ae21b)

**Comment by ValWood** [comment]
SUMO_interaction_motif (SO:0002235) -> SUMO (a protein)
polypeptide_copper_ion_contact_site (SO:0001096) -> copper ion
PIP_box (SO:0001810) -> PCNA (a protein)

**Comment by kimrutherford** [comment]
> I can implement this on Tuesday or Wednesday (I'm on holiday on Monday).

Sorry, I got distracted for 5 weeks.  :-)

> cleaved_peptide_region (SO:0100011)
> this would probably work best with PROPEPTIDES
>
> if we changed the label to PROPEPTIDES & CLEAVAGE SITES
> if not it can have its own track CLEAVAGE SITES

Now that I've implemented it, I think it might look better to have a separate track for cleavage sites.  What do you think?

![image](https://github.com/user-attachments/assets/f5ffd92c-ab1d-40d5-a6da-6024db851a13)

(This is https://desktop.kmr.nz/gene/SPAPB8E5.05)

> change the name of SIGNAL PEPTIDE to LOCALIZATION SIGNALS
> (Also merge mitochondrial transit peptide into this track)

That's done for Tuesday morning.

I'm still working on the other SO terms.

**Comment by PCarme** [comment]
> Now that I've implemented it, I think it might look better to have a separate track for cleavage sites. What do you think?

I agree, it would be clearer. 

> (This is https://desktop.kmr.nz/gene/SPAPB8E5.05)

On this specific example, I'm wondering:
- why does it have 2 propeptides but only one cleavage site ? 
- is it normal that in the mouse over panel for the cleavage site, it says "Imported from: PomBase" ?

**Comment by ValWood** [comment]
I agree 2 tracks

**Comment by kimrutherford** [comment]
> I agree 2 tracks

Propeptides and Cleavage sites are now separate tracks:
https://desktop.kmr.nz/gene_protein_features/SPAPB8E5.05

> LOCALIZATION SIGNALS

That track now includes `nuclear_export_signal` (SO:0001531), `nuclear_localization_signal` (SO:0001528) and `ER_retention_signal` (SO:0001806) sites (on my desktop at least).  There aren't many of those features.

Example with a `nuclear_localization_signal`:
https://desktop.kmr.nz/gene_protein_features/SPAC890.02c

**Comment by kimrutherford** [comment]
I noticed a bit of duplication:

https://desktop.kmr.nz/gene/SPAC22E12.09c

![image](https://github.com/user-attachments/assets/99a534c6-b1d1-45c8-aacc-b1578c586bfb)

![image](https://github.com/user-attachments/assets/2b8b679b-addf-4d5e-8771-3429caa39c58)

The two features from [Powner D et al. (1996)](https://desktop.kmr.nz/reference/PMID:8736869) are a bit weird because they are visible on the gene page in the protein features section, but on the publication page there is just one feature: https://desktop.kmr.nz/reference/PMID:8736869

I'll check that as it's a bit suspicious.

**Comment by kimrutherford** [comment]
> I'll check that as it's a bit suspicious.

Turns out it's 2 different publications:
   - https://github.com/pombase/curation/issues/3143#issuecomment-996691612
 
This is an unusual situation so I suggest not spending time writing special case code to remove the duplicate in the table.

Let's discuss on the call if it's worth collapsing the features in the protein viewer since this is the only case.

**Comment by ValWood** [comment]
@PCarme  All SO features (give egs) are also now displayed in the protein feature viewer.

**Comment by kimrutherford** [comment]
These changes are now on the main site.

I forgot about this though:
> is it normal that in the mouse over panel for the cleavage site, it says "Imported from: PomBase" ?

I'll fix that now.

**Comment by kimrutherford** [comment]
> is it normal that in the mouse over panel for the cleavage site, it says "Imported from: PomBase" ?

I've fixed that problem in the code but the change won't be on the main site until Thursday morning.

**Comment by PCarme** [comment]
Great, I'll announce that and the sequence search box on PombeList then.
