### ISSUE TITLE
Can't find legacy cleaved_peptide_region (SO:0100011)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2199]
I wanted to remove some unsupported annotations from
https://www.pombase.org/term/SO:0100011
(i.e some ISS that have a better annotations,  some are wrong, plus I used to assume that  all of the odd fusion proteins were cleaved on import, it seems that some are, but some are not)

However, I can't find them in:
manual_so_term_annotations.tsv

**Comment by kimrutherford** [comment]
So far I've only moved the  signal_peptide (SO:0000418) annotations out of the contig files.

I think cleaved_peptide_region is annotated like:

```
FT                   /controlled_curation="term=sequence feature, cleavage
FT                   site; cv=sequence_feature; evidence=ISS;
```

**Comment by ValWood** [comment]
OK, I'll wait until they are all migrated. It isn't the most urgent task and editing will be quicker in the .tsv

**Comment by kimrutherford** [comment]
> OK, I'll wait until they are all migrated. 

Done!

`pombe-embl/supporting_files/manual_so_term_annotations.tsv`

**Comment by ValWood** [comment]
fixed
