### ISSUE TITLE
genotype pages not showing all associated terms

### ISSUE THREAD

**Issue by ValWood** [pombase/website#220]
If I access wee1-delta from Mikel's paper , I only see a small fraction of the terms associated with wee1-delta?

![geneotpe pages](https://cloud.githubusercontent.com/assets/7359272/24240033/26e9c37c-0fa8-11e7-8b26-96004558e1cf.jpg)

**Comment by mah11** [comment]
#153 
#214 
https://github.com/pombase/pombase-chado/issues/577

**Comment by kimrutherford** [comment]
Yep, sorry, Midori's right.  It's the same annoying redundancy problem.  I'm going to fix it soon.
