### ISSUE TITLE
Allow SO term name in Quick Search?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2201]
Hi @ValWood 

Do you think it would be useful to allow searching with SO term name ("transit peptide") in the search box?  It's just a config change if you'd like to try it.

**Comment by kimrutherford** [comment]
> You would only get the top 8? in the simple search.

Yep, it only shows the first matches.

I've configured my desktop to add SO to the search box if you'd like to try it out: https://desktop.kmr.nz

**Comment by ValWood** [comment]
OK I get you. I was going to suggest this instead, but it is what you have done ;)

**Comment by kimrutherford** [comment]
Do you think we should enable this change on pombase.org?

**Comment by ValWood** [comment]
yes, go for it. Its also more consistent with GO

**Comment by kimrutherford** [comment]
OK, that's enabled now on the main site.  Let me know if you see any problems.
