### ISSUE TITLE
Integrate the 2 protein viewers

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2203]
We have one viewer focused on variants, modifications and all sequence features, that ~should~ shows only Pfam domains

then we have the protein domains and families feature table showing all Interpro families and recording their details and links to other identical features below.

Ideally we would like to somehow integrate these better.

In the short term links between the 2 viewers will be added.

Pease add ideas of how to integrate below.

**Comment by ValWood** [comment]
ACTION ITEMS

DOMAINS & SEQUENCE FEATURES 
- [ ]   Relabel gene page left hand menu to "protein domains and features" which is the main content. We need to decide later what to do about properties
- [ ]  Use the new style display for the protein domain and features section (it will only be possible to highlight from the viewer to the table/ not from the table to the viewer). Consider asking the developers to add that ability to hook into the viewer from a table
- [ ] The protein families and features display should include
a) protein families and domains
b) tmms
c) signal peptides, transit peptides and other Sequence ontology features
d) active sites binding sites
e) low complexity, disordered and coiled coil
- [ ] Add link to ALL features view so that these features can be viewed in the context of modifications and mutants
f) We talked about merging the PomBAse curated domains into  the domain feature table but I will review these and decide which we need to keep

MODIFICATIONS
- [ ]  Add a summary view of modifications to the top of the modification section
<img width="1012" alt="display modifications summary at top of section" src="https://github.com/user-attachments/assets/ff5042da-d9ae-4e1d-9460-bab92fc18b47">
- [ ]  Add link to ALL features view so that these features can be viewed in the context of  protein features and mutants


@kimrutherford @PCarme 
I think this was everything we discussed about integrating the views.
I left out the bit about moving the TMM link and the InterPRo link, we can decide that when we see the new pages
If you can think of anything  else, or have any alternative  suggestions please add these to the ticket

**Comment by kimrutherford** [comment]
As first step I'm testing loading all the InterProScan results into the fancy viewer to see how it looks.

This is only on my desktop for now: https://desktop.kmr.nz/gene_protein_features/SPAC22F3.06c

![image](https://github.com/user-attachments/assets/238cf52f-6bd3-4768-95b4-82bfb769ac38)

**Comment by kimrutherford** [comment]
I've been working on swapping using the new viewer widget in the Protein domains and properties section.  It's works OK but there is still quite a bit of fine tuning needed, like using the MobiDB disordered regions instead of the existing features.

You can see it in action here: https://desktop.kmr.nz/gene/SPBC12D12.04c

The protein feature viewer widget at the top of the page is temporarily a bit broken on my desktop version.

![image](https://github.com/user-attachments/assets/f2e6709c-b139-40c0-a2c8-20ed35914192)

**Comment by ValWood** [comment]
That is a lot neater than the existing view! and so nice that you can zoom in to see the amino acids.
The only down side  is that you need to mouse over to see the label, but people will get used to that, and it will be better when the mouse over the domain highlights the row in the table - what  functionality would we need to ask for to enable clicking the table and highlighting in the image?

**Comment by kimrutherford** [comment]
> and it will be better when the mouse over the domain highlights the row in the table - what functionality would we need to ask for to enable clicking the table and highlighting in the image?

We should be able to implement highlighting in the same style as when you click on a feature.  That's supported already in their code.  The yellow bar here:

![image](https://github.com/user-attachments/assets/d4a62bf2-149d-48e0-867a-e9ba91449363)

**Comment by ValWood** [comment]
You mentioned that it would be possible to click on the image and highlight the table, but it wouldn't be possible to click on the table and highlight the image without changes to the RCSB code.
We could ask for that,  it would be good if they added it in the future, but not critical

**Comment by kimrutherford** [comment]
> You mentioned that it would be possible to click on the image and highlight the table, but it wouldn't be possible to click on the table and highlight the image without changes to the RCSB code.

I was wrong about that.  We'll need to do some re-implementing of the code for the table but it will 
be possible to highlight a range of residues if we mouse-over a feature in the table.

**Comment by kimrutherford** [comment]
Work in progress, with the InterProScan output moved up and a track per Pfam entry: 

https://desktop.kmr.nz/gene_protein_features/SPBC146.13c

![image](https://github.com/user-attachments/assets/640f507f-51e5-4079-8ebf-51ff0f4c5d2a)

**Comment by kimrutherford** [comment]
> Add a summary view of modifications to the top of the modification section

First prototype:

https://desktop.kmr.nz/gene/SPAC3C7.11c

![image](https://github.com/user-attachments/assets/db8e7bec-eb1f-4fe3-b1dc-ff65d412097e)

**Comment by ValWood** [comment]
nice!

**Comment by kimrutherford** [comment]
A lot of this work is finished now.

The next big task is re-writing the code for the table of InterPro domains so that it integrates with the new feature viewer.  I think that's a job for Monday.

**Comment by ValWood** [comment]
Yes not one to begin on Friday evening. Great progress on this though! So much useful stuff.

**Comment by kimrutherford** [comment]
> it will only be possible to highlight from the viewer to the table/ not from the table to the viewer

I've got the highlighting work from the viewer to the table (on my desktop) but no the other way yet.  It needs a bit more work.

**Comment by ValWood** [comment]
>I've got the highlighting work from the viewer to the table 

ooh well done!

**Comment by ValWood** [comment]
How do I see that?

**Comment by ValWood** [comment]
no hurry, talk tomorrow

v

**Comment by ValWood** [comment]
O I see the picture, it looks good!

**Comment by kimrutherford** [comment]
> How do I see that?

On my desktop version, in the Protein domains and features section, mouse over a row in the table or a feature in the viewer.

https://desktop.kmr.nz/gene/SPBC146.13c

The table is quite long now so the highlighting isn't as useful - the feature is more likely to be off the bottom of the screen.  Perhaps we could think about changing the order of rows in the table and in the diagram so that the most useful/informative feature types are at the top?

Currently the order of rows in the table doesn't match the diagram.

**Comment by kimrutherford** [comment]
As discussed, I've replaced the Pfam IDs on the left hand side with the domain names:

![image](https://github.com/user-attachments/assets/d67db52f-3bd5-4d2e-8e96-17b2cb219b7d)

**Comment by kimrutherford** [comment]
I've fixed some missing match names (just for FUNFAM I think).

We talked about merging the "Match name" and "InterPro name" into a single "Name" column.  Should I go ahead and do that?

I'm also wondering about renaming the "DB name" column to something like "Source".  Any thoughts on that?

The rows in the table are now in the same order as the diagram, with Pfam domains at the top:

https://desktop.kmr.nz/gene/SPBC146.13c

![image](https://github.com/user-attachments/assets/086ba744-1eff-4ee4-a485-29b67ab7dadd)

**Comment by kimrutherford** [comment]
> As discussed, I've replaced the Pfam IDs on the left hand side with the domain names:

To do: add a mouse-over for the names of the Pfam domains on the left hand side.

**Comment by ValWood** [comment]
> As discussed, I've replaced the Pfam IDs on the left hand side with the domain names:

looks a bit weird doesn't it. Wopuld it help if we still had the PFAM prefix?

**Comment by ValWood** [comment]
> We talked about merging the "Match name" and "InterPro name" into a single "Name" column. Should I go ahead and do that?

I think that would help. I think we said we would retain the InterPro name if there was one.

> I'm also wondering about renaming the "DB name" column to something like "Source". Any thoughts on that?

That seems like a good idea too.

**Comment by kimrutherford** [comment]
> > We talked about merging the "Match name" and "InterPro name" into a single "Name" column. Should I go ahead and do that?
>
> I think that would help. I think we said we would retain the InterPro name if there was one.

I've implemented that.  It looks tidier:

![image](https://github.com/user-attachments/assets/6ca35a09-5080-420e-bb60-f13d972f7929)

**Comment by ValWood** [comment]
A lot!

**Comment by kimrutherford** [comment]
> I'm also wondering about renaming the "DB name" column to something like "Source"

That's done now too.

> It looks a bit weird, doesn't it? Would it help if we still had the PFAM prefix?

It helps a bit:

https://desktop.kmr.nz/gene/SPBC146.06c

![image](https://github.com/user-attachments/assets/48733f29-7033-49e9-a622-07238d452b69)

**Comment by ValWood** [comment]
> It helps a bit:
yep it's clearer where they come from and why they are on different lines

**Comment by kimrutherford** [comment]
I've made some fixes today to tidy up loose ends and I think it's mostly looking good now.

So I think we should consider releasing what we have.  We can fine tune things and fix bugs as needed.

How does that sound?

**Comment by ValWood** [comment]
Yes, go for it. I will write a pombelist post today or tomorrow.

**Comment by ValWood** [comment]
Note that on your desktop, and on dev the summary view is still showing "low complexity" and "coiled coils" from Pfam is that correct?

**Comment by kimrutherford** [comment]
Great.

InterProScan for japonicus has just finished running and the output looks OK.

I'll release all the changes for pombe and for japonicus in time for tonight's load then we can check things in the morning.  If there's a major problem we can go back to today's version.

**Comment by ValWood** [comment]
yep!

**Comment by kimrutherford** [comment]
> I'll release all the changes for pombe and for japonicus in time for tonight's load then we can check things in the morning. If there's a major problem we can go back to today's version.

Everything is committed and pushed to GitHub and ready to go for tonight's load or PomBase and JaponicusDB.

I'll check the sites in the morning.

**Comment by kimrutherford** [comment]
> Everything is committed and pushed to GitHub and ready to go for tonight's load or PomBase and JaponicusDB.

Both loads failed because I forgot that that the load scripts needed to be tweaked to remove the old Pfam data file.  I also forgot to push the JaponicusDB configuration changes to GitHub.  Good effort Kim!  :-)

I fixed the PomBase load script and re-started it at 2am.  If it works this time it should be done by 6:30am-ish.  I'll let you know.

I've fixed the JaponicusDB load script for Friday night's load.

**Comment by kimrutherford** [comment]
It all nearly worked.  :-)

The MobiDB disorder predictions are missing.  For now pombase.org is on yesterday's release while I debug that.
The dev site has the new Chado version with the InterProScan features: https://dev.pombase.org

**Comment by ValWood** [comment]
I didn't write the announcement yet anyway, I'll do that today

**Comment by kimrutherford** [comment]
> The MobiDB disorder predictions are missing.

I've opened an issue to ask about that:

 - ebi-pf-team/interproscan#386

By luck (only) I have an InterProScan JSON file that includes the MobiDB predictions that we can use in the meantime.  That file is from the first time I ran InterProScan.  I don't know what I did differently.  Possibly I misconfigured things so that it didn't use the precalculated results service.

I had been using that JSON file (with the MobiDB matches) on my desktop but I thought I'd re-run InterProScan on the server yesterday to make sure everything worked.  That turned out to be a bad plan.  :-)

I'll put the JSON file with the MobiDB matches in place for tonight's load and check in the morning.

**Comment by kimrutherford** [comment]
>  I don't know what I did differently. 

I think I've worked it out.  Between the time I downloaded InterProScan and trying it with the JSON output format, a new version was released.  I don't notice for a while.

In order to use the precalculated results service, the local version of InterProScan must match the version of the InterPro API server.  So I think I ended up running the whole thing locally without any pre-calculated results.  Because of that we got the MobiDB matches.  So no mystery and it should be OK on pombase.org in the morning.

**Comment by kimrutherford** [comment]
It all worked OK last night so pombase.org has the new data and code.  It's looking good!

 - https://www.pombase.org/gene_protein_features/SPBC19C2.09
 - https://www.pombase.org/gene_protein_features/SPBC354.05c
 - https://www.pombase.org/gene_protein_features/SPAC3H5.06c
 - https://www.pombase.org/gene_protein_features/SPBC146.03c
 - https://www.pombase.org/gene_protein_features/SPCC5E4.06
 - https://www.pombase.org/gene_protein_features/SPBC1A4.03c

**Comment by ValWood** [comment]
very, very nice
I have a suggestion to teak the display ordering. I'll open a new ticket for that.

**Comment by kimrutherford** [comment]
Looks OK for JaponicusDB too: https://www.japonicusdb.org/gene/SJAG_04001

@snezhkaoliferenko we've improved the PomBase code to use up to date data from InterPro.  And the Protein domains and features section has been updated to look and work better:

![image](https://github.com/user-attachments/assets/68ac64a8-8449-4070-aee1-b498e29ec8a0)

**Comment by snezhkaoliferenko** [comment]
Thank you!! LOVE IT
________________________________
