### ISSUE TITLE
citation widget on PomBase publication page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2205]
if this is possible...

**Comment by kimrutherford** [comment]
It's more or less working on my desktop.  I've had to reformat a bit to get it looking OK.
How's this?

https://desktop.kmr.nz/about/pombase-and-collaborative-publications
(Sorry, slow to load)

![image](https://github.com/user-attachments/assets/72168587-bc1e-4ef5-af12-5c1ea8de3e34)

Mouse-over:

![image](https://github.com/user-attachments/assets/35ad3104-5515-4026-bc8d-4bcb153fe2a7)

------------------------

For comparison, it looks like this at the moment:

![image](https://github.com/user-attachments/assets/bcc6de83-ba4f-4946-97e8-40b66c8a0932)

**Comment by kimrutherford** [comment]
I've also updated the Citing PomBase page:
https://desktop.kmr.nz/about/citing-pombase

**Comment by kimrutherford** [comment]
> It's more or less working on my desktop.

Sometimes the new badges don't display unless you reload the page.  I'm working on that now.

**Comment by ValWood** [comment]
> I've also updated the Citing PomBase page:
https://desktop.kmr.nz/about/citing-pombase

on this page we should update the recommended GO citation to the 2023 publication

**Comment by ValWood** [comment]
You could also add to the preprints.

**Comment by kimrutherford** [comment]
> You could also add to the preprints.

Which preprints?

**Comment by kimrutherford** [comment]
> Sometimes the new badges don't display unless you reload the page. I'm working on that now.

I think I've fixed that now so I'm going to commit the changes and update the main site.

I'll make your changes first.

**Comment by ValWood** [comment]
At the top of the publicatins page. The mondo preprint has been cited >40 times I think....

**Comment by kimrutherford** [comment]
> At the top of the publicatins page.

Ah, sorry!  I misread your comment as "You could also add the preprints" and was confused.

It didn't occur to me that the pre-print would have DOIs.  Good plan!  This will be on the main site in a little while:

![image](https://github.com/user-attachments/assets/58232a00-383e-4a83-9cf3-8f5268231b00)

**Comment by PCarme** [comment]
I noticed a typo on the "citing PomBase" page here
<img width="695" alt="Screenshot 2024-08-07 at 10 08 46" src="https://github.com/user-attachments/assets/364e36cf-26f3-4a5a-af15-1844768241d2">
the 'i' is missing in "curation tool"

**Comment by kimrutherford** [comment]
> I noticed a typo on the "citing PomBase" page here

Thanks!  I'll fix that now.

**Comment by kimrutherford** [comment]
I think this is all done now.

**Comment by ValWood** [comment]
Thanks, it's a bit silly but funders love metrics. It looks pretty anyway ;)
