### ISSUE TITLE
2 new plots on curated papers graph

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2207]
It would be useful to have two more lines on this graph.

1 community curated
1 pombase curated

<img width="739" alt="Screenshot 2024-08-06 at 19 27 30" src="https://github.com/user-attachments/assets/8aa36271-bf65-4039-a615-ab7b9c1d18e2">

This year our overall rate is really good since we are only half way through the year. At the moment we are definitely  curating more than published.

**Comment by kimrutherford** [comment]
I wonder if we want something like this graph but cumulative?  But to simplify thing, perhaps all the uncurated papers should be grouped together rather than splitting into assigned and unassigned.

I'll add this to my list of issues to discuss on a call sometime.

![image](https://github.com/user-attachments/assets/515d309d-3531-427e-ad19-fbabc66f06d5)

**Comment by ValWood** [comment]
Yes probably, I think people don't often understand this graph  is based on date published /vs data curated and and think we are curating less.

**Comment by ValWood** [comment]
Remember to use date of first approval

**Comment by kimrutherford** [comment]
Here's how it looks with two extra lines.  I'm still working of making a stacked plot:

![image](https://github.com/user-attachments/assets/96e9e2b0-18b8-4133-9c24-56b770972f61)

**Comment by kimrutherford** [comment]
First attempt at a stacked graph.  Are the labels OK?:

![image](https://github.com/user-attachments/assets/c38478ce-b885-439c-ae87-10719f5a11b0)

**Comment by ValWood** [comment]
That looks great.
labels: maybe if the title is "Publication Status" we can remove the word "papers" from uncurated

We do need to get community curation up!
But at least uncurated is going down consistently.

**Comment by kimrutherford** [comment]
> labels: maybe if the title is "Publication Status" we can remove the word "papers" from uncurated

How's this?

![image](https://github.com/user-attachments/assets/db49256b-6b21-40e0-a885-65399f0cd3ea)

**Comment by ValWood** [comment]
Great!
