### ISSUE TITLE
fasta export appears to be broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2208]
for
https://www.pombase.org/results/from/id/39ec585e-d1d6-4b76-9977-faa017908408
first  I tried to export just UniProt IDs for 

but, I got an empty file error.

I thought this may be because I excluded a systematic ID, but I still get the error in this case also.

**Comment by kimrutherford** [comment]
> but, I got an empty file error.

What was the error?

It all worked OK for me.  When exporting the sequences as protein fasta I got a file with 11 sequences.  When exporting as nucleotide I got all 294.

When exporting UniProt IDs to a tsv file I got the 11 UniProt IDs and a bunch of blank lines.  We should warn the user in that sort of case.

If you can reproduce the problem, could you leave the tab open so we can debug things next time we're on a call?

**Comment by ValWood** [comment]
https://www.pombase.org/results/from/id/90430e41-24ed-474e-9058-83e165b3836e

I think it might be because I restricted the columns to the UniProt identifier

<img width="1461" alt="Screenshot 2024-08-10 at 08 58 38" src="https://github.com/user-attachments/assets/02765021-830f-4b02-a19a-8ad65a025f97">

**Comment by ValWood** [comment]
I get the same if I include the systematic Identifier

**Comment by kimrutherford** [comment]
OK.  I still can't reproduce the problem.  I've tried with just the UniProt ID and it works OK for me.  Could you keep the tab open until next time we chat?
