### ISSUE TITLE
Misleading phrasing for annotated binding sites

### ISSUE THREAD

**Issue by PCarme** [pombase/website#2211]
I looked at the extensions for the protein-binding annotations, for most of them the residues indicated are on the annotated protein, which is what we want. 
It is only not the case for the nod1 and gef2 annotations which are reciprocally inverted, the residues indicated in the nod1 annotation are on gef2, and the residues in the gef2 annotation are on nod1. Although, with the way the annotation in worded, it might make more sense as it is now.
<img width="332" alt="image" src="https://github.com/user-attachments/assets/19533c7a-bac5-4746-a688-2abe80bcdbe3">
I think a user who reads this annotation (on nod1) as a sentence, would get it as nod1 binds to the site on residues 957-1101 of gef2, so in the correct way.

_Originally posted by @PCarme in https://github.com/pombase/pombase-chado/issues/1194#issuecomment-2273237715_

Related to this comment from another issue, I think the way residue extensions in GO MF annotations are displayed on PomBase can easily be misinterpreted. 

<img width="339" alt="Screenshot 2024-08-13 at 15 15 36" src="https://github.com/user-attachments/assets/d847acb9-bd3a-4e04-b950-7526ed867e38">

Here, for mis19 for example, I think these annotations look like Mis19 binds to the indicated residues on Mis18 and Mis16. But we kind of describe the opposite, the indicated binding sites are the Mis19 residues which bind to Mis16/18.

**Comment by ValWood** [comment]
binding site mis19(4-63) binds mis18


(document this on the curation wiki)

**Comment by kimrutherford** [comment]
The main site looks like this now.  Is that OK?  It's easy to reformat now the code is in the right place.

https://www.pombase.org/gene/SPBC27B12.02

![image](https://github.com/user-attachments/assets/2461eaf0-5a93-4267-ab1e-35813cdd5829)

![image](https://github.com/user-attachments/assets/ab3d2d46-2c04-42dc-a922-5489e4de2405)

![image](https://github.com/user-attachments/assets/a2868e87-9455-45f1-8271-9ab9a96bce7b)

**Comment by PCarme** [comment]
Yes, that's clearer now !
