### ISSUE TITLE
position of contributes_to

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2213]
In this situation
<img width="1241" alt="ticket contributes to on wrong line" src="https://github.com/user-attachments/assets/7286ec53-eac6-4da0-8655-96dad4bc9ccd">

It would be better if the "contributes_to" qualifier appeared on the line level with the term rather than the level of the extension, as it really only belongs with the  MF term

**Comment by kimrutherford** [comment]
What should happen in this case where not every annotation has the qualifier?

https://www.pombase.org/gene/SPNCRNA.82

![image](https://github.com/user-attachments/assets/2ab1253c-5151-49b0-9b03-37b485afbd02)

https://www.pombase.org/term/GO:0004523

![image](https://github.com/user-attachments/assets/606eae9d-ca54-40a1-a0bf-ccbca7acbc33)

**Comment by ValWood** [comment]
Yeah, let's not worry about this. We don't use contributes_to very much, so it isn't really resolvable. I think we discussed this before; it's a very minor issue.
