### ISSUE TITLE
Remove help link for external ortholog resources

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2214]
I think we should remove this help link:

![image](https://github.com/user-attachments/assets/d9209104-a82b-4e9b-b810-100349d92abe)

I have two reasons:
 - it goes to the documentation for the external references which doesn't help
 - the main help link for the orthlogs section goes to a documentation page which discusses the external resources

**Comment by ValWood** [comment]
agreed!

**Comment by kimrutherford** [comment]
That's done.
