### ISSUE TITLE
new "commonly used query"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2215]
All genes with paralogs

**Comment by kimrutherford** [comment]
This will take an hour or three to implement as the query server code will need to change to understand paralogs.

**Comment by kimrutherford** [comment]
We have optional columns in the query builder output table for the various types of orthologs.  Should we add a paralogs column?

**Comment by ValWood** [comment]
cool, yes please!

**Comment by kimrutherford** [comment]
> All genes with paralogs

That's implemented for tomorrow - it needs an overnight load.

**Comment by kimrutherford** [comment]
> We have optional columns in the query builder output table for the various types of orthologs. Should we add a paralogs column?

That's also implemented and will be available in the query builder from tomorrow.

Is "Paralog IDs" OK as the column name?  Or would "Paralogous genes" be better?  Or something else?

Here's an example:
https://desktop.kmr.nz/results/from/id/1f354d06-ddeb-415d-885b-42ebfbbcbadd

![image](https://github.com/user-attachments/assets/3f1ab9a0-6f36-4ce7-9b7e-a9a50be70039)

**Comment by ValWood** [comment]
Wow! speedy!

**Comment by ValWood** [comment]
I think Paralog IDs is clear
