### ISSUE TITLE
investigate predict protein

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2217]
This tool uses protein embeddings.
Referred to in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9374478/pdf/baac062.pdf
https://predictprotein.org/about
https://predictprotein.org/

We should evaluate this at some point

**Comment by PCarme** [comment]
This tool predicts quite a lot of features, so I'm not really sure how to evaluate it. 
We should probably discuss about the use we would make of it as well.
