### ISSUE TITLE
ftp download, cannot unzip file

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2219]
I could unzip

cds+introns.fa.gz

but not
cds+introns+utrs.fa.gz

**Comment by kimrutherford** [comment]
Was it this file?:
https://curation.pombase.org/dumps/builds/pombase-build-2024-09-01/fasta/feature_sequences/cds+introns+utrs.fa.gz

That worked OK for me.  What was the error?

**Comment by ValWood** [comment]
<img width="384" alt="Screenshot 2024-09-02 at 09 42 44" src="https://github.com/user-attachments/assets/ff69ff4a-10ba-4fdb-ad92-a14df772a752">

**Comment by kimrutherford** [comment]
Could you let me know what the file size is?  It should be 5124639.

Which URL did you use to download?

**Comment by ValWood** [comment]
5.1 MB
following link from
https://www.pombase.org/downloads/genome-datasets
[Sequences in FASTA format](https://www.pombase.org/data/genome_sequence_and_features/feature_sequences/) for:

**Comment by kimrutherford** [comment]
> 5.1 MB

What is the file size in bytes?  ls -al cds+introns+utrs.fa.gz

>following link from
>https://www.pombase.org/downloads/genome-datasets 
> Sequences in FASTA format for:

I just tried the link from there and didn't have a problem uncompressing the file.

Could you see what gzip reports from the command line?:
gzip -tv cds+introns+utrs.fa.gz

Thanks.

**Comment by ValWood** [comment]
gzip -tv cds+introns+utrs.fa.gz
cds+introns+utrs.fa.gz:	  OK


but it isn't unzipped

**Comment by kimrutherford** [comment]
> cds+introns+utrs.fa.gz: OK

Looks OK then?  Perhaps OS X has a problem with the file?

> but it isn't unzipped

The "-t" flag just tests that the file is OK.  It doesn't unzip.

**Comment by kimrutherford** [comment]
Maybe we should discuss this on a call?

**Comment by ValWood** [comment]
Appear to be the "+" in the file name, and archive utility combination

**Comment by kimrutherford** [comment]
It took a bit of Googling but I think this same problem:
https://apple.stackexchange.com/questions/388759/archive-utility-cant-open-some-gzipped-text-files-based-on-their-contents

This was linked to from that post: https://github.com/libarchive/libarchive/issues/1051#issuecomment-1267882936
Looks like someone is having trouble with a fasta file.

So it's a known Mac bug.

Val, what version of MacOS are you using?

I saw several posts suggesting using this instead on this buggy built in archive program: https://theunarchiver.com/

**Comment by ValWood** [comment]
Ventura 13.2.1

**Comment by kimrutherford** [comment]
> Ventura 13.2.1

OK, so hopefully most Mac users will have a more recent version with fewer bugs.

**Comment by ValWood** [comment]
yep, ignore unless anyone complains. I will update soon
