### ISSUE TITLE
wonky counts for GO

### ISSUE THREAD

**Issue by ValWood** [pombase/website#222]
http://pombase2.aska.gen.nz/term/GO%3A0000002
24 unique here

http://pombase2.aska.gen.nz/term_genes/GO%3A0000002
reports 21

**Comment by ValWood** [comment]
might be related?
https://github.com/pombase/website/issues/225

**Comment by mah11** [comment]
I don't see a problem - on the first page you linked, cce1, mgm101, and pog1 each show up twice, so it's 24 rows but 21 unique genes (and there's no count shown on that page).

**Comment by ValWood** [comment]
I counted, supposedly unique, and totally missed all 3 duplicates. Scary!
