### ISSUE TITLE
canned query Proteins conserved in human/vertebrates

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2220]
This list is vertebrates and contains 3 genes that are conserved to metazoa but absent from humans (related to amino acid biosynthesis).

I used to think this was OK, but instead can we make this query reflect proteins  with annotated human orthologs (also I think it has a couple of RNAs too)

**Comment by kimrutherford** [comment]
Can you make the query you'd like in the query builder and then send me the link?

**Comment by ValWood** [comment]
I don't think we can do this in the query builder.
We could only do it if we were able to query "genes with human orthologs" and we can't do that query.

The "vertebrates" list has


SPBC1A4.02c | leu1 | 3-isopropylmalate dehydrogenase Leu1
SPBC405.01 | ade1 | phosphoribosylamine-glycine ligase/phosphoribosylformylglycinamidine cyclo-ligase
SPCC569.08c | ade5 | phosphoribosylglycinamide formyltransferase
SPAC23H3.09c | gly1 | threonine aldolase Gly1

that are in vertebrates (some even in mouse) but not human

It would be good if there could be some way to engineer the procise human query

**Comment by ValWood** [comment]
This isn't super urgent but we should keep it on the radar

**Comment by kimrutherford** [comment]
> We could only do it if we were able to query "genes with human orthologs" and we can't do that query.

We can do that in the query builder:

![image](https://github.com/user-attachments/assets/8b40ed5f-1c80-4da0-b971-cbff187231e2)

**Comment by ValWood** [comment]
OK we should use that  for the canned query!

I had got so used to using the canned query I forgot about this.

We should also update this FAQ!
https://www.pombase.org/faq/how-can-i-find-all-s.-pombe-genes-are-conserved-human
which explains that  the query  has a couple of proteins without human orthologs (now 3 I think!)

**Comment by kimrutherford** [comment]
Should the new query be named "Proteins with human orthologs" or "Proteins conserved in human"?

The cerevisiae query is a bit complicated.  Should we change it to be an ortholog query too?

![image](https://github.com/user-attachments/assets/cbeb7b44-c77c-4c81-a616-12294c629871)

**Comment by kimrutherford** [comment]
> We should also update this FAQ!

Is this enough?:

```
To retreive a list of genes with a human ortholog, go to the advanced search,
click the “Commonly used queries” option and choose “Conserved in human”.
```
![image](https://github.com/user-attachments/assets/77001a86-6758-463b-9d0d-8efabb24b73b)

**Comment by ValWood** [comment]
yes, the rest is out of date, that'd enough
tks
v

**Comment by ValWood** [comment]
> The cerevisiae query is a bit complicated. Should we change it to be an ortholog query too?

yes please!

**Comment by kimrutherford** [comment]
> The cerevisiae query is a bit complicated. Should we change it to be an ortholog query too?

The results will change a bit, mostly because of RNA orthologs:

Proteins conserved in S. cerevisiae:
https://www.pombase.org/results/from/id/2a22121d-ecb2-431b-a9f6-6ee86c20443b
has 4012

has ortholog with: S. cerevisiae:
https://www.pombase.org/results/from/id/dd028f57-6ff7-455f-ba85-fabafa5da00f
has 4042

There are 5 genes that are returned by the current "Proteins conserved in S. cerevisiae" query but which don't have a cerevisiae ortholog?:
https://www.pombase.org/results/from/id/ea94807f-77ea-4ae0-85fe-5ec17f139605

**Comment by kimrutherford** [comment]
> Proteins conserved in S. cerevisiae:

Should we rename that commonly used query to: "Genes conserved in S. cerevisiae" since it includes RNA genes?

**Comment by kimrutherford** [comment]
> Or change the query so that it matches the protein coding genes (doing it the same way as the human one).

The "Proteins conserved in human" query was all orthologs, not just proteins.  I've fixed that now.
I've also updated the cerevisiae and japonicus queries to also be just protein coding orthologs.  It doesn't make a difference for japonicus but I wanted to be consistent.

Can we close this now?

**Comment by ValWood** [comment]
Yes, I will check the content, but I think the remaining issues are annotation!
