### ISSUE TITLE
ftp: Protein data files (features and aa composition)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2221]
https://www.pombase.org/data/Protein_data/

Need to decide what is required 

PeptideStats.tsv | 2017-11-23 21:10 | 190K |  
-- | -- | -- | --
 Protein_Features.tsv | 2017-10-20 21:35 | 2.8M |  
 aa_composition.tsv | 2017-10-20 21:35 | 333K |  

make sure these are copied and updated with the other files

**Comment by ValWood** [comment]
I think we should write out the updated versions of these. I think we have been asked for them in the past.

**Comment by kimrutherford** [comment]
> make sure all currently linked files are up to date

They'll be updated nightly from Wednesday night.  (I'll check on Thursday)

For now I haven't made any other changes.

**Comment by kimrutherford** [comment]
> If we do decide the protein features file is worth keeping, we should
> i) remove tmhmms from it because they are in their own file

The TM domains aren't in that file anymore.

> ii) Rename it as protein domains and families

We renamed the gene page section to "Protein domains and features" so how about "protein_domains_and_features.tsv" as the file name?

**Comment by ValWood** [comment]
>so how about "protein_domains_and_features.tsv" as the file name?

definitely!

**Comment by kimrutherford** [comment]
> so how about "protein_domains_and_features.tsv" as the file name?

I've changed the load script but not in time for tonight's load.

Note to self: need to fix link in this page after the load: https://www.pombase.org/downloads/protein-datasets
