### ISSUE TITLE
ftp: 2 identical files in downloads/ & protein IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2228]
There seem to be 2 identical files?

allNames.tsv | 2023-02-05 20:57 | 217K |  
gene_IDs_names.tsv | 2023-02-05 20:57 | 217K |  

Also, should we add  a protein ID column for completion? The protein ID is the gene name but with the first letter uppercase.

**Comment by kimrutherford** [comment]
I think we can close it.
