### ISSUE TITLE
skip the basic ontology term page for the conserved in lists....

### ISSUE THREAD

**Issue by ValWood** [pombase/website#223]
These are a bit different, they are always huge lists, and  you need to see the gene names, so this page is not much use:

http://pombase2.aska.gen.nz/term/PBO%3A0011069
becasue it is always "one annotation per gene" and there are no nested terms, papers or other details to complicate things  further.

I do use these lists occasionally (even though they are huge they are useful if you want a quick reccy of all proteins conserved to human etc, but i think people who want this would always need this list:
http://pombase2.aska.gen.nz/term_genes/PBO%3A0011069
by default , so I think for these  could go straight to this page.

**Comment by kimrutherford** [comment]
I've added a flag the can be set per CV to skip the term details page.

Here is where it is configured for species_dist:
  https://github.com/pombase/website/blob/a5da06913118b5d7107393ecc142b77d3aa72c94/frontend/src/app/config.ts#L159

**Comment by ValWood** [comment]
That made species distribution disappear from the gene pages too;)

**Comment by ValWood** [comment]
Oh thats odd. Its there now.....
