### ISSUE TITLE
Pro-peptide display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2230]
I was looking at this with @Antonialock, and we both thought the display is a bit confusing for propeptide.

The "blocks" should be part of the protein remaining (maybe the excised parts could be a ------- line?)

v

can explain if not clear

<img width="1269" alt="Screenshot 2024-09-07 at 21 21 04" src="https://github.com/user-attachments/assets/641a64e3-9b4a-4b48-ae3d-51a8ad544cf1">

**Comment by kimrutherford** [comment]
> The "blocks" should be part of the protein remaining

I'm confused by that.  Aren't the purple blocks for pro-peptides already showing the bits that remain?

**Comment by ValWood** [comment]
no, unintuitively, they are the deleted part. This is a tine pheromone, only 9 amino acids!

**Comment by Antonialock** [comment]
The label is ‘propeptide’ so it makes sense that the propeptide portion is
highlighted. It is just a bit unintuitive showing it like a box as at least
to me that implies the coding region, not what’s cut out…

**Comment by ValWood** [comment]
Of course, yes, the propeptide is the label. maybe we don't highlight the protein at all, but represent the propeptide as a dashed line?

**Comment by Antonialock** [comment]
Yes I think that would probably look more intuitive...?

**Comment by Antonialock** [comment]
this is how it looks in the uniprot viewer. I think the graphic is hard to look at since there is no legend, but is clear when "interacting" with it (clicking on regions to highlight them).

![image](https://github.com/user-attachments/assets/1b83ecf3-9930-49a0-98aa-98b6c362d4d8)

**Comment by kimrutherford** [comment]
We currently display the pro-peptide in a similar way to UniProt.  Maybe we should keep it consistent?

If there is a `chain` annotated makes the pro-peptide annotation clear I think?

-------

https://www.uniprot.org/uniprotkb/O13351/feature-viewer

![image](https://github.com/user-attachments/assets/bbc5ac66-c54e-4f55-9594-ed3aab5934b6)

![image](https://github.com/user-attachments/assets/c3acf739-a95b-43f5-bf0b-07122d3fade7)

-------

https://dev.pombase.org/gene_protein_features/SPBC365.06

![image](https://github.com/user-attachments/assets/4fe74f00-631c-43fe-831e-6a03da668a9b)

------

Here's how it looks if the pro-peptide is shown as the remaining residues:

![image](https://github.com/user-attachments/assets/eff24eff-8d03-4a3f-b815-0386d909205c)

**Comment by ValWood** [comment]
OK , agreed!

**Comment by kimrutherford** [comment]
Can we close this?

**Comment by ValWood** [comment]
yep
