### ISSUE TITLE
Show source/evidence for features onmouse over

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2231]
I think we should add this. It seems a bit odd not to....

<img width="1257" alt="Screenshot 2024-09-08 at 15 01 51" src="https://github.com/user-attachments/assets/2fe95107-c5e5-4b3d-80de-5086df6b022d">

**Comment by kimrutherford** [comment]
Some of the features from UniProt have an evidence qualifier that includes a PubMed ID:

```
/evidence="ECO:0000269|PubMed:18257517"
```

In that case we should use that as the reference instead of the UniProt paper.

**Comment by ValWood** [comment]
Yes definitely but that links to the comment in this this ticket:

"First, I think we need to extend our MOD data format file to include an "assigned by" column so that all of these have "assigned_by" UniProt"

so that we can capture the  experimental source, and the source of the curation.

**Comment by kimrutherford** [comment]
> First, I think we need to extend our MOD data format file to include an "assigned by" column so that all of these have "assigned_by" UniProt

I've implemented that for the annotations created directly from the UniProt data file.  That's the lipidation sites, glycosylation sites, disulfide bonds and modifications from `pombe-embl/external_data/uniprot_data_from_api.tsv`.

Those annotations will have the `assigned_by` "UniProt" property in Chado from Wednesday.

There are also some UniProt that were put annotations in `pombe-embl/supporting_files/manual_so_term_annotations.tsv`.  I need to do a bit investigation with SVN to work out which came from UniProt.  I'll do that next.

After that I'll work on display the assigned_by in the display.

**Comment by kimrutherford** [comment]
> There are also some UniProt annotations that were put in pombe-embl/supporting_files/manual_so_term_annotations.tsv. I need to do a bit investigation with SVN to work out which came from UniProt. I'll do that next.

I've now added an "Assigned_by" column to `manual_so_term_annotations.tsv` and filled it in as best I can.  And I've changed the loading code to store that value in Chado.

**Comment by kimrutherford** [comment]
The code for showing the assigned by in a mouse-over in the protein feature table was added a few years again.  I'll add the same information to the protein feature viewer mouse-overs today.

![image](https://github.com/user-attachments/assets/c4e8d69e-be6c-4f8a-a9ec-0aa1397cfacf)

**Comment by kimrutherford** [comment]
I've added the assigned by and evidence to the pop-up for modifications first because that was the easiest case.  I'm still working on the other feature types.

![image](https://github.com/user-attachments/assets/a0ac96e5-dd36-4f13-884c-75ddfe36b6e6)

![image](https://github.com/user-attachments/assets/d275704a-f1f5-47ab-a675-1e2fb872f8cb)

![image](https://github.com/user-attachments/assets/8fef0446-8c25-4d9a-830b-9342fc8b5562)

**Comment by kimrutherford** [comment]
> Some of the features from UniProt have an evidence qualifier that includes a PubMed ID:
>
> ```
> /evidence="ECO:0000269|PubMed:18257517"
> ```

I'm working on storing and displaying the PubMed ID .

Some features from UniProt have more than one evidence code and reference.  For example csx1 / SPAC17A2.09c:

```
MOD_RES 42; /note="Phosphoserine; by MAPK sty1"; /evidence="ECO:0000269|PubMed:14633985, ECO:0000269|PubMed:18257517";
```

For now the code is just using the first evidence code and reference.  Most of the processing and display code can only handle one evidence code and one reference per annotation so we would need to split these cases into multiple annotations if we want to capture them.

**Comment by kimrutherford** [comment]
> I'm working on storing and displaying the PubMed ID .

That's done for Wednesday morning.

Before:

![image](https://github.com/user-attachments/assets/91c292cd-9045-42ef-9c0d-ac686ff53a7f)

After:

![image](https://github.com/user-attachments/assets/0095fe66-e6ff-4515-a18f-8fa50f627d72)

**Comment by ValWood** [comment]
This is great. Will  we be able to see the PubMed ID in the pop-up on the protein feature viewer? This would be very useful.

**Comment by ValWood** [comment]
>For now the code is just using the first evidence code and reference. Most of the processing and display code can only handle one evidence code and one reference per annotation so we would need to split these cases into multiple annotations if we want to capture them.

Ideally we would split them into separate annotations. That would probably mean that more were filtered anyway because the annotations already existed?

**Comment by ValWood** [comment]
>Ideally we would split them into separate annotations. That would probably mean that more were filtered anyway because the annotations already existed?

ignore!  you have already done it!

**Comment by ValWood** [comment]
Actually, I'm a bit confused.  We already had the data from the Wilson-Grady paper so these annotations should be filtered as duplicate shouldn't they?

**Comment by kimrutherford** [comment]
> Will we be able to see the PubMed ID in the pop-up on the protein feature viewer?

I'll add it.  It will be a little annoying that you can't click on it though.

> Actually, I'm a bit confused. We already had the data from the Wilson-Grady paper so these annotations should be filtered as duplicate shouldn't they?

There is no filtering yet.

**Comment by ValWood** [comment]
OK!
but which gene is the  example?

**Comment by kimrutherford** [comment]
> but which gene is the example?

Do you mean the example in the screenshots?  It was https://www.pombase.org/gene/SPAC26H5.10c (I think).  Sorry, I should have included a link.

**Comment by kimrutherford** [comment]
> Will we be able to see the PubMed ID in the pop-up on the protein feature viewer?

Is the PubMed ID best?  We could put the citation as well or instead?

**Comment by kimrutherford** [comment]
> Maybe the citation would be better than the PMID

That's done for Friday morning:

![image](https://github.com/user-attachments/assets/f957323d-8953-4fc3-9922-479268b5b784)

**Comment by ValWood** [comment]
That's good,  out of curiosity can you have hyperlinks to other pages in pop-ups?

**Comment by kimrutherford** [comment]
>  out of curiosity can you have hyperlinks to other pages in pop-ups?

Unfortunately that's not possible because the pop-up disappears when you move the mouse.

**Comment by ValWood** [comment]
of course!
