### ISSUE TITLE
Advanced search, small change to default view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2233]
Currently, Domain ID comes first and is the default.
Because everyone will have a good idea what domianID is, I think we should change the default to the "protein feature" query (I guess this just involves changing the order so that it comes first?)

<img width="1191" alt="ticket order, default" src="https://github.com/user-attachments/assets/8fc4c600-054a-4751-aa7c-cdf33eb183eb">

**Comment by kimrutherford** [comment]
That's done now.

**Comment by ValWood** [comment]
thanks!
