### ISSUE TITLE
Add data classes to protein feature summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2235]
Suggestions from @Antonialock 

Some of these classes are not used often, but  only show the classes that are present anyway

**Comment by kimrutherford** [comment]
By "data class" do you mean tracks?  Some are very big and wouldn't work well in a summary:
 - https://www.pombase.org/gene_protein_features/SPAC20G8.05c
 - https://www.pombase.org/gene_protein_features/SPCC4B3.15

**Comment by ValWood** [comment]
You are right.
I think there is no need to show chains, helices, strands, and turns on the front page. They are an algortihm rather than specific data points.
Deletions don't really work as a summary track.

I think we could show active sites, I can't remember the other types and I can't find the original e-mail about this for some reason?
Which ones do we currently show/not show?

**Comment by kimrutherford** [comment]
These are the tracks configured for the genes pages.  The choices are a bit random sorry.  It's mostly tracks that aren't usually very tall.

 - AA substitution positions
 - Modifications
 - Glycosylation sites
 - Pfam domains
 - TM domains
 - Disordered regions
 - Low complexity
 - Coiled coils
 - Signal peptide
 - Transit peptide

**Comment by ValWood** [comment]
What are the ones that aren't configured

**Comment by ValWood** [comment]
I think we should display: 
Propeptides
Lipidations sites (as modifications)
Disulfide bonds
Binding sites
Active sites

we already display

**Comment by ValWood** [comment]
we already display "aa substitution positions"

**Comment by kimrutherford** [comment]
> I think we should display:

I've added those to the configuration for the summary, except for:

> Lipidations sites (as modifications)

That's covered by this issue:
  - pombase/pombase-chado#1220

**Comment by ValWood** [comment]
I no longer see
Beta strands
Helices
Turns
in the full view?

**Comment by ValWood** [comment]
Actually they are there, I see them here
https://www.pombase.org/gene_protein_features/SPCC1672.06c

but I would expect these features to cover the full length of most proteins (excluding the low complexity regions)
Are they importing correctly?

**Comment by ValWood** [comment]
Where do UniProt display these helices and sheets?
I don't t find them on the page https://www.uniprot.org/uniprotkb/O74429/ ?

**Comment by Antonialock** [comment]
They are/were generated from odd structures. I don’t know more than that,
we don’t touch them in manual curation. You’d have to ask the uniprot
helpdesk

Are they useful to anyone you think?

**Comment by ValWood** [comment]
I thought they must be after I posted this
maybe not useful, they might be useful for orientation to the structures....
They won't so any harm. Hopefully they will get more complete over time.

**Comment by kimrutherford** [comment]
> Where do UniProt display these helices and sheets?
> I don't t find them on the page https://www.uniprot.org/uniprotkb/O74429/ ?

They are in the Feature viewer under "Structural features"

UniProt has the same as PomBase:
![image](https://github.com/user-attachments/assets/654d7501-20a7-4db9-9c63-c336099955fe)

**Comment by kimrutherford** [comment]
Can we close this?

**Comment by ValWood** [comment]
y
