### ISSUE TITLE
very minor improvement on characterization graph (possibly)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2236]
Could we strecth the y axis on this graph to 2x the current?
https://www.pombase.org/status/gene-characterisation

It might show the current incremental increases better?

**Comment by ValWood** [comment]
Is it also possible to add  a scale bar to the left.

**Comment by kimrutherford** [comment]
> Is it also possible to add a scale bar to the left.

It has a scale bar on the left?

**Comment by ValWood** [comment]
right!
It would just make it a bit easier to see where we are numbers wise.

we could even have a "zoomed in" plot for the current year, or past 2 years

**Comment by kimrutherford** [comment]
> It would just make it a bit easier to see where we are numbers wise.

Perhaps a table containing the numbers over time would make things clear?
