### ISSUE TITLE
Query by percentage rather than count for "Disordered regions"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2237]
From Alison Pidoux:

> It’s great that there’s an option to search for disordered regions in proteins in the Advanced Search.  I wonder if it would be possible to modify it so that rather than specifying eg ‘number of DRs > 6’ (which can give back proteins that have several tiny DRs, but not a protein with only a few long regions) it could give the option of ‘DR is > xx% of protein’ or ‘DR of > xx amino acids’ ?  I don’t know if that’s easy or hard to ask for or if there’s some reason that number of DRs is a good idea.

**Comment by kimrutherford** [comment]
My prototype is here: https://desktop.kmr.nz/query

We should work on the wording.

![image](https://github.com/user-attachments/assets/9988460a-0d3d-460c-b6cc-35d240101c91)

**Comment by PCarme** [comment]
Maybe something like "Percentage of residues in disordered regions" would be clearer ?

**Comment by kimrutherford** [comment]
All the changes are checked in, including a percentage query option for coiled-coils.  I'll close this issue in the morning if it all looks OK.
