### ISSUE TITLE
disordered region query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2239]
Pro1 has a "disordered region" feature of 2 amino acids. This seems odd to me. I'm not sure you can call disordered for 2 amino acids.
What is the source of this (I think they come from InterPRot, but I don't see it on the InterPro website)

**Comment by ValWood** [comment]
I see similar here in wee1

<img width="505" alt="Screenshot 2024-09-25 at 11 24 24" src="https://github.com/user-attachments/assets/ac33ee69-3a50-43b9-a15b-00ba1bda78ea">

there is no such thing as a disordered region of 1 or 2 amino acids.

Do we have other sources of disordered region? This seems a bit flaky,  (don't we also get them from InterPRo?)

**Comment by kimrutherford** [comment]
> Do we have other sources of disordered region?

We don't have any other sources at the moment.  I'm still trying and failing to run the InterPro pipeline locally.  But I don't know if that has any disorder or complexity output.

>  This seems a bit flaky, (don't we also get them from InterPRo?)

They all come from Pfam (3 years ago) not from InterPro.

**Comment by ValWood** [comment]
>Does InterPro not provide them at all?

ignore me, you just said that you didn't know!

**Comment by ValWood** [comment]
If we can't locate them, I will ask InterPro if they can include them in InterProscan.

**Comment by kimrutherford** [comment]
> If we can't locate them,

They are definitely from the data I grabbed from Pfam before it disappeared.

> I will ask InterPro if they can include them in InterProscan.

InterPro does provide disordered regions in a file (but not low complexity regions).  I found an old email titled "[pfam-help #751585] Pfam-N" where you asked InterPro about it.  They said:

> From the InterPro FTP: extra.xml.gz  contains all sequence features, such as trensmembrane regions predicted by TMHMM, intrinsically disordered regions predicted by MobiDB-lite, etc. Pfam-N regions are also included in this file. There are more Pfam-N regions that the first file as it's based on UniProtKB 2024_03.

I think we talked about it and decided it was still a problem because they have out of date protein sequence so the positions will sometimes be wrong.   I'm looking at installing InterPro locally.

**Comment by kimrutherford** [comment]
> Pro1 has a "disordered region" feature of 2 amino acids.

InterProScan doesn't find any disordered regions in pro1

> I see similar here in wee1

The 2 AA match for wee1 is gone too.

The predictions from InterProScan are quite different to the prediction from Pfam.

This is from Pfam for wee1:

![image](https://github.com/user-attachments/assets/5506cc47-4b4b-4e58-9253-2f713a4d7420)

Here's what we get from InterProScan, on the same scale:

![image](https://github.com/user-attachments/assets/0db6579e-6e69-489c-a0bf-ac0ebb1681a8)



A bit worrying maybe?

The screenshots are from: https://desktop.kmr.nz/gene/SPCC18B5.03

**Comment by ValWood** [comment]
I think it is OK, wee 1 is largely disordered outside of the kinase domain:

![Uploading Screenshot 2024-10-07 at 07.16.46.png…]()

I guess InterPro have chosen the algorithm they believe performs the best. I wonder if  this incorporates AlphaFold data (that would be the sensible way to do it...)

**Comment by ValWood** [comment]
I think we can close this, it's covered by [MobiDB-lite] features.
I was just going to send an announcement about that, but they aren't live yet. Which ticket is that? (That's what I was looking for when I found this.)

It seems from this ticket that the old disordered regions were from various sources that were no longer reproducible:

"That two AA region has type "IUPred" in the data from Pfam. Probably from this tool: https://iupred3.elte.hu/
(Although I tried the protein on the site just now and didn't predict anything)"

**Comment by kimrutherford** [comment]
> Which ticket is that?

Mostly:
 - pombase/pombase-chado#1218

but partly:
 - pombase/website#2203

**Comment by ValWood** [comment]
Right we haven't switched yet! OK. I guess the new domains panel can go together with the switch

**Comment by kimrutherford** [comment]
> I guess the new domains panel can go together with the switch

That's what I was thinking.  There are a lot of interrelated changes in various places so it's easier just to get everything done and released at once rather than bit by bit.
