### ISSUE TITLE
ability to sort term associated gene   lists on products

### ISSUE THREAD

**Issue by ValWood** [pombase/website#224]
for any of these  term list pages

http://pombase2.aska.gen.nz/term_genes/PBO%3A0011069
http://pombase2.aska.gen.nz/term_genes/GO%3A0006511
http://pombase2.aska.gen.nz/term_genotypes/FYPO%3A0000059

you can easily see why the ability to sort alternatively by product would be a bonus
(we have not so much control over the names, but we things will group together much better biologically using the products- especially complex members and the like...

**Comment by kimrutherford** [comment]
The gene list can now be sorted by product or gene - click on the column headings.

I'll do the sorting of the genotypes table next.

**Comment by ValWood** [comment]
that is soooo useful!
Really much better way to "read" long lists, by product

**Comment by kimrutherford** [comment]
I've added sorting to the single allele genotypes list:
  http://pombase2.bioinformatics.nz/term_genotypes/FYPO%3A0001382

Table sorting is easy to implement so let me know if you see any other cases that would be useful.
