### ISSUE TITLE
add uniprot reference for imported glycosylation sites? (and residue)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2240]
add uniprot reference for imported glycosylation sites
I noticed this was excluded

<img width="1237" alt="Screenshot 2024-09-26 at 15 42 56" src="https://github.com/user-attachments/assets/408768a8-fd85-40a7-a71b-b54cf5e05cc1">

also check for other imported modifications

**Comment by ValWood** [comment]
Only the signal peptides and the Peptides have the reference
https://www.pombase.org/reference/PMID:36408920

should we add to 
propeptides 
active site 
binding sites

**Comment by kimrutherford** [comment]
> add uniprot reference for imported glycosylation sites

That's done for Friday night's load.  It's done for the other feature types too.

**Comment by kimrutherford** [comment]
> Also, the glycosylated sites don't have the residue only the positon.
> I think these should always be N (AsparagiNe), Can we try that?

I've made that change for Friday night's load.
