### ISSUE TITLE
small change to assigned by display in pop ups

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2243]
As I was writing the announcement I was thinking that perhaps we should  not show "assigned by Pombase"

i.e. 
<img width="737" alt="cdc25 modification" src="https://github.com/user-attachments/assets/b6e3a74a-f95a-418b-a51d-3c9075f60399">

and only show for imported residues. But instead of showing assigned by Unipart, we should say imported from uni product, i.e. imported from where ever it is in the assigned by Column, when it isn't  PomBase.

It would be less cluttered and more accurate, and "saaigned by pombase" might look strange to the community curators

**Comment by ValWood** [comment]
also the ordering, I think the evidence should come before the citation.

"imported by" when relevant can be at the end

**Comment by kimrutherford** [comment]
I've made those changes.  It will be on the main site on Saturday morning.

**Comment by ValWood** [comment]
So, if there are cases where it isn't an N at this position, where will that be reported, I can't remember

**Comment by kimrutherford** [comment]
> So, if there are cases where it isn't an N at this position, where will that be reported, I can't remember

The results of Manu's pipeline are here: https://github.com/pombase/allele_qc/tree/master/results

There are lots of errors here: https://github.com/pombase/allele_qc/blob/master/results/protein_modification_cannot_fix_other_errors.tsv
mostly because the UniProt positions don't have a residue at the start.

Errors about incorrect residues should appear there too.

**Comment by kimrutherford** [comment]
> The results of Manu's pipeline are here: https://github.com/pombase/allele_qc/tree/master/results

The pipeline runs twice a week.  The next run will be early Wednesday morning.  I'm still working on fixing residues so hopefully by Wednesday there will be fewer reported errors.

**Comment by ValWood** [comment]
This is done, but we want "imported from UniProt"  always, whether there is a reference or not

**Comment by ValWood** [comment]
Will that fix the absence of "imported from" also>
<img width="306" alt="Screenshot 2024-10-05 at 20 27 41" src="https://github.com/user-attachments/assets/6e1b286a-6d85-44fd-80b6-2643f92b226f">

**Comment by kimrutherford** [comment]
> Will that fix the absence of "imported from" also

That requires a change which is part of a slightly larger re-shuffling of code.  I'll be working on that this week.

**Comment by kimrutherford** [comment]
> I'm still working on fixing residues so hopefully by Wednesday there will be fewer reported errors.

Most were fixed, but we needed a special case for disulfide crosslinked residues (MOD:00689).  I've added a fix.  I'll check the results in Chado on Tuesday and set off Manu's pipeline.

**Comment by kimrutherford** [comment]
> That requires a change which is part of a slightly larger re-shuffling of code. I'll be working on that this week.

I've changed the code to add "Imported from UniProt"/InterPro/Pfam etc.  I'll check on Tuesday.

We have "Imported from Pfam" for some features at the moment, but they'll go away once we switch to InterProScan:
   - pombase/pombase-chado#1218 

![image](https://github.com/user-attachments/assets/8e3f0e78-e5e2-4d40-b6a5-015f8d77ad5e)

**Comment by kimrutherford** [comment]
> There are lots of errors here:

Down to one error!:
https://github.com/pombase/allele_qc/blob/master/results/protein_modification_cannot_fix_other_errors.tsv

> I've changed the code to add "Imported from UniProt"/InterPro/Pfam etc. I'll check on Tuesday.

That's done so I think we can close this now.

**Comment by ValWood** [comment]
Excellent!
