### ISSUE TITLE
entity in reference field

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2244]
I don't think there are many of these, this is the only one I spotted:
<img width="1218" alt="Screenshot 2024-09-26 at 19 45 03" src="https://github.com/user-attachments/assets/f470dadf-3e50-4c4c-bfa9-dd66da3bba11">

In these ISS cases, I think it would be better to report the  Uniprot paper

**Comment by ValWood** [comment]
Actually, now I think this might be in the legacy modifications file. Will check tomorrow....

**Comment by kimrutherford** [comment]
> Actually, now I think this might be in the legacy modifications file.

It was from the UniProt data file.  There were lots of other cases where the reference was not a PubMed ID.  I've removed them for Friday night's load.
