### ISSUE TITLE
changes to front page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2245]
I have been meaning to suggest this for a while.

I think we should get rid of this panel

<img width="410" alt="Screenshot 2024-09-27 at 09 02 43" src="https://github.com/user-attachments/assets/6cb7541c-dda7-41be-8a73-ad43cc87c667">

and move the links
All community curation
and
PomBAse staff curated publications
up to the panel above

This would fit the rotating feature

Also we can remove the twitter feed (I notice everyone embedded feeds look like this, I gues they expect us to pay something)

**Comment by ValWood** [comment]
1. Keep panel but remove image and swap with bottom panel

**Comment by kimrutherford** [comment]
All done.
