### ISSUE TITLE
Duplicate annotation on publications page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2247]
Annotations from
https://www.pombase.org/reference/PMID:25720772
are duplicated on the publication page (but appear to be filtered on the gene page)

<img width="1292" alt="Screenshot 2024-09-29 at 08 47 35" src="https://github.com/user-attachments/assets/632cf5dd-ce58-498c-8d23-6dbed2304622">

**Comment by kimrutherford** [comment]
Should be a quick fix.  The duplicates are in the data file.  eg.:
```
SPAC3F10.11c            MOD:00048       ECO:0007464     Y865            PMID:25720772   4896    2016-06-27
SPAC3F10.11c            MOD:00048       ECO:0007464     Y865            PMID:25720772   4896    2016-06-27
```

**Comment by kimrutherford** [comment]
That's: `pombe-embl/external_data/modification_files/PMID_25720772_modifications.tsv`

**Comment by ValWood** [comment]
ah is that in our file?
