### ISSUE TITLE
Add a column of PomBase papers, other

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2248]
To this table
<img width="528" alt="Screenshot 2024-10-01 at 11 46 10" src="https://github.com/user-attachments/assets/f0e1d478-84b1-4d55-8751-01f3486cd81e">

**Comment by kimrutherford** [comment]
Here's my first attempt so I can't guarantee that it's correct.  It looks a bit odd with the Other proportion increasing over time.

![cumulative_curated_by_year](https://github.com/user-attachments/assets/3c95785d-3198-4dd8-bf21-9c3d7f02cd0f)

**Comment by ValWood** [comment]
I think its OK. I would put other at the bottom in a 'non-descript' colour

**Comment by ValWood** [comment]
And curated at the top

**Comment by kimrutherford** [comment]
How's this?  I've finally worked out how to change individual colours so we can change any of them.

![cumulative_curated_by_year](https://github.com/user-attachments/assets/edf0b1dd-3633-4268-8bcf-8de2862cf617)

**Comment by ValWood** [comment]
Looks good. It. can go live, we can workshop the labels on the next call

**Comment by kimrutherford** [comment]
OK, I've committed the changes.  They'll be on the main site in the morning.
