### ISSUE TITLE
colour pathological/non pathological mutants differntly

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2249]
I think it would be really useful if we coloured the pathological  single amino acid mutants differently from the non pathological.

I.e  if a single amino acid mutant is either 
abnormal or inviable phenotype colour  them red
if viable  or normal colour them grey
(some may have both abnormal and normal phenotypes, in these cases abnormal would trump.

Rationale.
I though of this when reviewing the InterPro website changes. They report/dispaly only pathogenic mutants (which is what most users will be interested. in).
We are unusual in that we also report non-pathological.
We report the non-pathological for information  and completion, but it would be great if, when looking at this view you could see clearly which residues were the most important ones.

**Comment by kimrutherford** [comment]
> I think it would be really useful if we coloured the pathological single amino acid mutants differently from the non pathological.

That should be no problem and it will make the display look more interesting.  What's the rationale for only colouring the single amino acid mutants?
For cdc15 most of the mutants are multi-locus:
https://www.pombase.org/gene_protein_features/SPAC20G8.05c

**Comment by ValWood** [comment]
We could do both. I was biased toward point mutations because  I was thinking about survivorship bias and this image:

<img width="258" alt="Screenshot 2024-10-02 at 07 17 58" src="https://github.com/user-attachments/assets/45ec3222-c172-4e5b-905b-5efeca030060">

**Comment by ValWood** [comment]
This has some aspect of pathology so this would be red.

**Comment by kimrutherford** [comment]
> abnormal or inviable phenotype colour them red
> if viable or normal colour them grey

So when should an allele be grey?  Only when it's viable and also normal?

Are these the terms we need?:

```
id: FYPO:0000124
name: viable cell
```
```
id: FYPO:0000257
name: normal phenotype
```

**Comment by ValWood** [comment]
If it is inviable  (Cell or population) OR abnormal it should be red.

**All others should be grey.** So they would be grey if they have ONLY viable  (cell or population) OR normal

**Comment by kimrutherford** [comment]
> If it is inviable (Cell or population) OR abnormal it should be red.

So inviable cell (FYPO:0000049) or inviable cell population (FYPO:0002059) or abnormal phenotype (FYPO:0001985)?

**Comment by ValWood** [comment]
red if
inviable cell population (FYPO:0002059)  or any of its descendants
inviable cell (FYPO:0000049) or any  of itsdescendants
"abnormal phenotype" (FYPO:0001985)  or any of its descendants

all others grey

**Comment by ValWood** [comment]
yes sorry  posts  crossed, i was looking them up and got side tracked

**Comment by kimrutherford** [comment]
First attempt:

![image](https://github.com/user-attachments/assets/8ceea12b-ba36-486f-a2ce-7fbbc2929c42)

**Comment by kimrutherford** [comment]
We can do the same for partial deletions if you think that's useful:

![image](https://github.com/user-attachments/assets/b3ad5c1a-b697-4419-9685-89f54f773fc5)

**Comment by kimrutherford** [comment]
An example with both:

![image](https://github.com/user-attachments/assets/a7635d69-23a2-4ad0-bb9d-91f9ff9f713f)

**Comment by ValWood** [comment]
This will be really useful!

Could you zoom in on this a bit?
The same alleles seem to. be present as both grey, and red?


<img width="215" alt="Screenshot 2024-10-02 at 13 11 48" src="https://github.com/user-attachments/assets/b14b5047-e92c-4ae9-8d23-7dea16023f70">

**Comment by ValWood** [comment]
> We can do the same for partial deletions if you think that's useful:

Yes, I think we should

**Comment by kimrutherford** [comment]
> Could you zoom in on this a bit?
> The same alleles seem to. be present as both grey, and red?

It's here if you want for have a look:
https://desktop.kmr.nz/gene_protein_features/SPAC694.06c

**Comment by ValWood** [comment]
Yep, I just looked:

So this one
<img width="118" alt="Screenshot 2024-10-02 at 13 15 17" src="https://github.com/user-attachments/assets/ee6fea83-23c7-4a04-bf19-df2a425c0f11">

is the same allele separating normal and abnormal phenotypes.

I envisaged that we would represent each allele once but colour it red *even if* it had some normal phenotypes, and long as it had some abnormal phenotypes.

The rationale is that every allele will have lots of normal things, depending on what is tested. This is just a way to focus people attention on the alleles that have at least some identified detrimental effects.
However,  now I don't know which option is best.

@PCarme  what do you think?

**Comment by kimrutherford** [comment]
They look different to me.  Same positions but the substitutions are different (S572A vs S572C, etc.)

```
mrc1-SQ 	                S572A,S599A,S604A,S614A 	
mrc1-S572C,S599C,S604C,S614C 	S572C,S599C,S604C,S614C 	
```

**Comment by ValWood** [comment]
doh, ignore me!

**Comment by kimrutherford** [comment]
Are there any changes to make before I release this?

**Comment by ValWood** [comment]
No go for it!

**Comment by ValWood** [comment]
This is really useful.
I think we can improve it even more.
The grey normal are  fine, but it would be good to see a separation between inviable  and abnormal so 
And we should maybe use the same colour scheme for both aa subs and partial deletion

perhaps
anything inviable  >> anything abnormal  > normal 

And we should maybe use the same colour scheme for both aa subs and partial deletion
anything inviable (red) >> anything abnormal  (pale pink?) > normal (grey)

**Comment by kimrutherford** [comment]
It was a challenge to find an example gene that has inviable, abnormal and normal alleles.  Inviable is quite a lot less common than abnormal - I guess that makes sense.

I tried pale pink and it was difficult to see the difference between the inviable and the abnormal alleles.  So here's how it looks with a more contrasting colour:

https://desktop.kmr.nz/gene_protein_features/SPAC23C4.18c

![image](https://github.com/user-attachments/assets/fc14df6c-cce5-429a-bd8a-675aeda82a11)

**Comment by PCarme** [comment]
That's a good idea to distinguish between abnormal phenotypes and inviable, but I would have chosen an in-between color for abnormal. Orange maybe ?

**Comment by kimrutherford** [comment]
> It was a challenge to find an example gene that has inviable, abnormal and normal alleles. 

Here are a few other examples:

https://desktop.kmr.nz/gene_protein_features/SPBC2F12.08c
https://desktop.kmr.nz/gene_protein_features/SPCC777.14
https://desktop.kmr.nz/gene_protein_features/SPAP8A3.06
https://desktop.kmr.nz/gene_protein_features/SPCC188.06c
https://desktop.kmr.nz/gene_protein_features/SPCC1672.02c

**Comment by kimrutherford** [comment]
Here's how it looks with orange:

![image](https://github.com/user-attachments/assets/7d85c50e-8f49-4fab-ab5e-f17cc946d59f)

**Comment by ValWood** [comment]
I think Orange is a good plan. Can you use a stronger orange (as strong as you can go without it merging with the red)

Hex #F06631 

Hex #FD963D

Hex #FD5602

Hex #F5883F 

Hex #FF8000

Hex #E78400

Hex #FF6E00

Hex #FF6700 

Hex #FF9B00

Hex #FE5000 

Hex #FF6E4A 

Hex #FF7518

Hex #F76806

Hex #FF9916

Hex #FFA500

Hex #F96815

Hex #F05E23
<img width="159" alt="Screenshot 2024-10-03 at 09 18 47" src="https://github.com/user-attachments/assets/34043f77-2cc6-4dec-a13d-db17d0c4d270">

**Comment by ValWood** [comment]
maybe most of these are too close to the red?

**Comment by ValWood** [comment]
perhaps Hex #FF9B00 or Hex #FF9916

which red shade are we using ?

**Comment by ValWood** [comment]
>which red shade are we using ?

I was wondering if we could 'up the contrast' by moving the red shade towards one which is very slightly pink...we can try that once we have a stronger orange which works well.

**Comment by kimrutherford** [comment]
The contrast varies between monitors so perhaps we can try a few options live on the next Zoom call.

Whatever colours we decide on I think it's good to make the inviable alleles clear because they are the uncommon case.  Point mutations are the trickiest case.  For example:
https://desktop.kmr.nz/gene_protein_features/SPBC25H2.13c
https://desktop.kmr.nz/gene_protein_features/SPAC20G8.01
https://desktop.kmr.nz/gene_protein_features/SPAC4A8.12c

**Comment by ValWood** [comment]
OK, we can do that, there's no hurry.

**Comment by kimrutherford** [comment]
> which red shade are we using ?

It's `#f00` in the configuration but the feature viewer code changes that to `#ff7f7e` for the interior of the features and `#fceeed` for the border.  So it's difficult to directly set feature colours.  There's a bit of trail and error.

**Comment by kimrutherford** [comment]
> #fceeed for the border.

Sorry, I got that wrong.  We configure `#f00` (also known as `#ff0000`) and that's what gets used for the border.  The interior is a paler version of that colour: `#ff7f7e`.

**Comment by kimrutherford** [comment]
I've committed those changes so it should be on pombase.org on Wednesday morning.
This is a page to check: https://www.pombase.org/gene_protein_features/SPBC2F12.08c

**Comment by kimrutherford** [comment]
I forgot to update documentation for the modification colours here: https://www.pombase.org/documentation/gene-page-protein-features-widget

**Comment by kimrutherford** [comment]
> I forgot to update documentation for the modification colours

Done a few days ago.
