### ISSUE TITLE
Approved community session appearing as not curated on PomBase

### ISSUE THREAD

**Issue by PCarme** [pombase/website#2250]
The publication page for PMID:38188419 indicates that it is not curated yet 
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/7e036e38-cde2-4d07-9ac3-39fa804f878d">

Although it has been curated and approved in Canto 
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/84677757-73c9-49b3-87fb-bdaf25426388">

**Comment by kimrutherford** [comment]
Hi Pascal.  That paper now has annotation on pombase.org.  It can take up to 24 hours for an approved paper to appear on the main site.

```
Community curation provided by Yongjie Xu
Added to PomBase on 2024-10-01
```

**Comment by PCarme** [comment]
Oh yeah, I was thinking I had curated it a few weeks ago, but it was waiting for a new FYPO term, so I only approved it yesterday !
Sorry for the false alert
