### ISSUE TITLE
reporting source on modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2252]
I just spotted this:

pcn1 source, reported a Frampton:
<img width="385" alt="pcn1" src="https://github.com/user-attachments/assets/4e3d05a9-c271-4724-9f08-3bf550842c87">

but Frampton isn't the source of all the data we display for K164

<img width="1228" alt="___report display issue " src="https://github.com/user-attachments/assets/6816453f-ad3f-4e2a-a78b-af3b653dcc51">

**Comment by kimrutherford** [comment]
Ah, yep, that's a mistake.  The alleles aren't supposed to show references because there can be more than one.

**Comment by ValWood** [comment]
This is a modification.

**Comment by kimrutherford** [comment]
Ah right, we probably shouldn't show them on modifications either.

**Comment by ValWood** [comment]
Yep, this  info will need to wait for the tables

**Comment by kimrutherford** [comment]
This is fixed for Tuesday morning.
