### ISSUE TITLE
small change to figure

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2254]
We should pu "uncurated" on top because that's the declining number. It will be clearer:

<img width="704" alt="Screenshot 2024-10-14 at 09 54 52" src="https://github.com/user-attachments/assets/566ad9a0-9089-437d-9af1-6db88298a019">

**Comment by kimrutherford** [comment]
Like this?:

![image](https://github.com/user-attachments/assets/09cecd1e-e7f9-4cf9-b509-6200d762b701)

**Comment by ValWood** [comment]
Yes that s clearer to see, all the growth sets are now together

**Comment by kimrutherford** [comment]
No problem.  I've committed the change.  It will be on the main site in 20-30 minutes.
