### ISSUE TITLE
term page, moving up ontology

### ISSUE THREAD

**Issue by ValWood** [pombase/website#226]
from regulates terms, you can only move up to other regulates terms
http://pombase2.aska.gen.nz/term/GO%3A0046822
should also be able to move up to other parents.

**Comment by kimrutherford** [comment]
Currently it only shows is_a and part_of parents.  See #193

Should it show regulates parents too?

**Comment by ValWood** [comment]
yep...

**Comment by kimrutherford** [comment]
Fixed now.  Might need a shift-reload.

**Comment by ValWood** [comment]
looks good
