### ISSUE TITLE
protein feature display ordering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2260]
MobiDB should be with the disorder and low complexity

the domains
pfam
cdd
prosite
smart
prints
funfam

then  "superfamilies" & gene3d  (both superfamiles)

then panther & PIRSF  

(I think that's about tight, may need another tweak)

And in the table COIls should be below the domains and superfamilies

**Comment by kimrutherford** [comment]
There's a bit of overlap with this issue:
 - https://github.com/pombase/website/issues/2259

**Comment by kimrutherford** [comment]
I've made those changes on desktop:
https://desktop.kmr.nz/gene_protein_features/SPBC3E7.01

Let me know if any further tweaking is needed.

The change will be on pombase.org on Tuesday morning.

**Comment by ValWood** [comment]
Smart and protein profiles should move up to be with domains
Panter should move below superfamilies.
MAybe you didn't check in the change?

**Comment by kimrutherford** [comment]
Which gene page are you looking at?

> MAybe you didn't check in the change?

The changes are checked in but won't be on pombase.org until Tuesday morning.

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now on my desktop: https://desktop.kmr.nz/gene_protein_features/SPBC3E7.01

**Comment by ValWood** [comment]
looks good, thanks!
