### ISSUE TITLE
modifications docs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2262]
1. is this  true
Note: unlike GO annotations, for modification annotations extensions are not considered for display filtering. Annotations to less specific terms are hidden in the summary view whether they have extensions or not.

2. doc do not mention "multiplicity" - we should add that

**Comment by kimrutherford** [comment]
> Note: unlike GO annotations, for modification annotations extensions are not considered for display filtering.
> Annotations to less specific terms are hidden in the summary view whether they have extensions or not.

As far as I can remember it's the same code for GO annotation and modifications so the summary should work the same for both.

I don't understand what "display filtering" is.

**Comment by ValWood** [comment]
I think "display filtering" must refer to what is shown be default. I could not immediately see  anything that was not filtered where I expected that it would be. We can probably remove that comment?

**Comment by kimrutherford** [comment]
> We can probably remove that comment?

OK, I'll remove that when I tidy up the modification documentation

> doc do not mention "multiplicity" - we should add that

I've forgotten.  What's "multiplicity" for modifications?

**Comment by ValWood** [comment]
I had too!
its recorded here:
https://www.pombase.org/documentation/modification-data-bulk-upload-format

multiplicity | number of modified sites detected within the same peptide fragment (relevant to mass spec. methods) | multiplicity(2)

**Comment by kimrutherford** [comment]
> doc do not mention "multiplicity" - we should add that

Is multiplicity related to this from the bottom of the current documentation page?:

The annotation extension field can also be used to indicate modification site occupancy, for experiments that measure the proportion of copies of the protein (or RNA) that have the modification.

**Comment by kimrutherford** [comment]
> doc do not mention "multiplicity" - we should add that

Is this OK?:

https://desktop.kmr.nz/documentation/gene-page-modifications

![image](https://github.com/user-attachments/assets/9a0702c5-f369-4309-9437-418d2445972d)

**Comment by kimrutherford** [comment]
I've updated the documentation with new screenshots and I've trimmed the text down a bit.  Let me know if there is anything to fix:

https://www.pombase.org/documentation/gene-page-modifications

**Comment by ValWood** [comment]
Re:
Is multiplicity related to this from the bottom of the current documentation page?:

The annotation extension field can also be used to indicate modification site occupancy, for experiments that measure the proportion of copies of the protein (or RNA) that have the modification.

I think occupancy and multiplicity are differnt
