### ISSUE TITLE
TMM,s and signal pepetides and transit peptides. are missing from gene page  protein feature view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2264]
Reporting this because I think the existing ticket is specifically for the other SO features that we don't yet display

**Comment by kimrutherford** [comment]
For "protein feature view" for you mean the "Protein domains and features" section?

**Comment by ValWood** [comment]
yep sorry!

**Comment by kimrutherford** [comment]
That should be fixed now on my desktop: https://desktop.kmr.nz/gene/SPAC167.01
