### ISSUE TITLE
Add a search box in the gene page sequence section

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2266]
It would be very useful to be able to type eg. `100..120` into a field and then have those residues selected.

**Comment by kimrutherford** [comment]
I started implementing this but this realised that it's trickier than I thought.  :-)

It's especially tricky when showing the nucleotide sequence because the exons, introns and bases upstream all change the residue positions.  We might have to just ignore the nucleotide sequence mode initially.

I've put what I've done so far on a branch and I'll come back to it later:
https://github.com/pombase/website/tree/issue-2266-sequence-search-box

**Comment by ValWood** [comment]
could just implement for proteins - I never look at DNA nt ;)

**Comment by kimrutherford** [comment]
> could just implement for proteins

OK, I've done that.  It's on my desktop if you'd like to test it.  Press return after typing the range.
https://desktop.kmr.nz/gene/SPAC8F11.08c

It will be on the dev site in 20-30 minutes from now.  I won't add it to the main site yet as there are a few things to fix and tidy.

![image](https://github.com/user-attachments/assets/a02a7fde-a626-44d8-b4ba-1613bf9c27cf)

![image](https://github.com/user-attachments/assets/75167344-4e94-42fa-bbab-1d4a4baa988e)

![image](https://github.com/user-attachments/assets/e5a64b20-98de-43d1-abd1-a7343e2da7bc)

**Comment by ValWood** [comment]
Niiiice

**Comment by kimrutherford** [comment]
Could try this on Safari when you get a chance?

I'll try it on Windows.

Selection of text on screen is a bit platform specific so there could be differences or bugs.  I found some differences in behaviour even between Firefox and Chrome on Linux.

**Comment by ValWood** [comment]
seems fine on firefox

**Comment by PCarme** [comment]
> Could try this on Safari when you get a chance?

That works well on Safari

**Comment by kimrutherford** [comment]
Thank you both for testing.

I've now tried on Microsoft Edge on Windows and that works OK too.

**Comment by kimrutherford** [comment]
I fixed the remaining issues that were annoying me and I've added a "Clear selection" button.

It's now available on the main site.  Let me know if you see any problems.
