### ISSUE TITLE
PFAM domains display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2267]
Because we have the PFAM domains separated out, is it useful to have the 'combined row" in the protein feature section
where do we provide the description on the left-hand menu?

@PCarme @kimrutherford  what do you think?

(Obvs. we should keep the combined row in the summary view)

**Comment by kimrutherford** [comment]
> @PCarme @kimrutherford what do you think?

I don't have a strong opinion.  Maybe remove the combined row?

**Comment by ValWood** [comment]
that was my thinking. Its redundant which makes it slightly  confusing

**Comment by PCarme** [comment]
> > @PCarme @kimrutherford what do you think?
> 
> I don't have a strong opinion. Maybe remove the combined row?

I agree. The combined row is not required but not a real problem either.

**Comment by kimrutherford** [comment]
OK, that's done now.

**Comment by kimrutherford** [comment]
Need to fix this for JaponicusDB too.

**Comment by kimrutherford** [comment]
> Need to fix this for JaponicusDB too.

Fixed for Wednesday morning.
