### ISSUE TITLE
KEN box residues

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2268]
<img width="335" alt="check shows up" src="https://github.com/user-attachments/assets/7f2d005c-4a56-4409-adf9-aa3712f001d7">

I added
SPAC15A10.03c		SO:0001807	ECO:0000044	PMID:18426916	2009-11-24		residue(26-28)	PomBase

but still not showing up here
 https://www.pombase.org/gene/SPAC15A10.03c

can you see the problem?

**Comment by kimrutherford** [comment]
When did you add it?  We're still on yesterday's release for the next 2 hours (or more if I messed things up again).

**Comment by ValWood** [comment]
Ah, that's OK. I checked yesterday but I might have fixed something, I can't remember, in which case it wouldn't be expected until today

**Comment by kimrutherford** [comment]
Should we add this KEN box feature to the protein view?  Which track should it go in?

**Comment by kimrutherford** [comment]
> but still not showing up here
> https://www.pombase.org/gene/SPAC15A10.03c

It's there now.  You might need to shift-reload.

**Comment by ValWood** [comment]
> Should we add this KEN box feature to the protein view? Which track should it go in?

I thought we had a track for the misc SO features? Is there another ticket about this?

**Comment by ValWood** [comment]
Maybe can just use "https://www.pombase.org/term/SO:0100017"

There are not many , but we can ask SO to add parents for the missing ones

**Comment by kimrutherford** [comment]
> I thought we had a track for the misc SO features? Is there another ticket about this?. 

We managed to add the rest of the SO annotations to other tracks so we haven't needed a misc track yet.  We certainly could if needed.

> Maybe can just use "https://www.pombase.org/term/SO:0100017"

Use it for what?  I don't follow.

> There are not many , but we can ask SO to add parents for the missing ones

Sorry, I don't understand that either.  What parents are needed?  A what missing ones do you mean?

**Comment by ValWood** [comment]
If we add a track for
polypeptide_conserved_motif
that would include most (or all) of the misc.

If we have any new misc, this SO parent would probably work for those too.

**Comment by kimrutherford** [comment]
> If we add a track for
> polypeptide_conserved_motif
> that would include most (or all) of the misc.

The is only 1 polypeptide_conserved_motif with a location at the moment: https://www.pombase.org/term/SO:0100017
Do you think we'll get more over time?

**Comment by ValWood** [comment]
Yes, and we should be able to add coordinates for these from the papers used to curate the.
Can you move this to the curation tracker when you are done and we''ll take a look.

**Comment by kimrutherford** [comment]
I've added a "Conserved motifs" track.  It will be visible on the  rad54 / SPAC15A10.03c  page on Tuesday.

![image](https://github.com/user-attachments/assets/3a896295-cd87-4a1d-a595-9d2b66b52747)

https://desktop.kmr.nz/gene_protein_features/SPAC15A10.03c

**Comment by ValWood** [comment]
Great, this will encourage us (and the community) to capture these motifs)
