### ISSUE TITLE
Hide `has_penetrance` and `has_severity` in the phenotype summmary?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2269]
I noticed that there is a bug in how the summary mode extension configuration is used.   The configuration file says that `has_penetrance` and `has_severity` should be hidden in the summary but that config is being ignored due to the bug.

On the left is how is looks at the moment, on the right is how it would look if the bug was fixed (assuming we keep the current config):

![missing_ext](https://github.com/user-attachments/assets/3046a7c7-ad7b-4fb4-9f26-b6266d736339)

(This from cdc15: https://www.pombase.org/gene/SPAC20G8.05c)

I'm about to fix the bug, but should we hide `has_penetrance` and `has_severity` in the summmary?

Spotted while fixing:
 - pombase/website#1940

**Comment by ValWood** [comment]
Maybe they should be displayed by default. I'm not sure......we will have a think about that... @PCarme maybe ask the lab?

**Comment by PCarme** [comment]
In cases where several alleles of the same gene have annotations to the same phenotype (e.g. the image below), would the fix put all the alleles on one line, or keep them on separate lines ?
<img width="370" alt="image" src="https://github.com/user-attachments/assets/2feea7f6-57a9-4390-9ce5-8d229ae059ce">

  

> @PCarme maybe ask the lab?

I can ask during this afternoon's lab-meeting

**Comment by kimrutherford** [comment]
It would look like this:

![image](https://github.com/user-attachments/assets/017dac0b-ef53-4338-b4df-9bf40b93f3dc)

**Comment by PCarme** [comment]
It would have the advantage of making the Summary display a bit shorter for genes with lots of alleles then

**Comment by ValWood** [comment]
might be worth double checking penetrance of cdc13-9

form the same paper (possibly different conditions, or a mistake?)

FYPO:0000252 | increased spontaneous diploidization
-- | --
has penetrance 85% | cell growth assay evidence |   | Hayles J et al. (1994)
has penetrance 99% | cell growth assay evidence |   | Hayles J et al. (1994)

[FYPO:0000252](https://www.pombase.org/term/FYPO:0000252)	[increased spontaneous diploidization](https://www.pombase.org/term/FYPO:0000252)
has penetrance 85%
cell growth assay evidence	
[Hayles J et al. (1994)](https://www.pombase.org/reference/PMID:8087848)
has penetrance 99%
cell growth assay evidence	
[Hayles J et al. (1994)](https://www.pombase.org/reference/PMID:8087848)

**Comment by PCarme** [comment]
It seems to come from this table 
<img width="461" alt="image" src="https://github.com/user-attachments/assets/94e0e429-5e15-44c4-b278-b55aaed5ecec">
So different conditions, 99% with heat shock, 85% without.

**Comment by kimrutherford** [comment]
The same because was causing the summary to be less compact than it was configured to be.

This is yesterday's version:

![image](https://github.com/user-attachments/assets/da531b60-7d92-4723-b517-04053750e65f)

This is what we'll see this morning:

![image](https://github.com/user-attachments/assets/b91c9e35-526e-4f0f-85be-3b61d90bf97a)

(https://dev.pombase.org/gene/SPBC216.07c)

There is a still a problem with the last three annotations.  I'll make a separate issue about that.

**Comment by ValWood** [comment]
These changes are really useful!  Will be much easier to read.

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by ValWood** [comment]
yep
