### ISSUE TITLE
Manually curated signal peptide feature not appearing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2270]
I added the residues of a signal peptide reported in  https://www.pombase.org/reference/PMID:39477503

It appears on the gene page  https://www.pombase.org/gene/SPBC1709.03
in the Protein sequence features table, but not in the feature viewer

Also here:

SO:0000418 | signal_peptide | match to sequence model evidence | 1-19 | Inagawa T et al. (2024) | 368

SO:0000418  | sequence similarity evidence used in manual assertion |   | UniProt Consortium (2023)

Once we have residues, we can suppress sources that don't supply residues

**Comment by kimrutherford** [comment]
Sorry about that.  When I combined the signal peptide and transit peptides into the localisation signals track, I forgot to add the new track to the gene pages.

I've fixed that for Tuesday morning.

**Comment by ValWood** [comment]
its there now.
