### ISSUE TITLE
Weird output with PMID search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2275]
check this out:

<img width="669" alt="Screenshot 2024-11-12 at 19 03 36" src="https://github.com/user-attachments/assets/af548ac2-4bfa-4946-87c5-5ec3cd7d894c">

I never saw this before, it's reporting GO reefs s the IDs?

**Comment by ValWood** [comment]
and not finding the publication match?

**Comment by kimrutherford** [comment]
That's very weird.

I tried PMID:38830897 and got the expected result:

![image](https://github.com/user-attachments/assets/79f06d25-ef84-44c7-9f3c-51b2039195a9)

**Comment by kimrutherford** [comment]
I noticed that we get the same weird result if we change the colon to a space "PMID 38830897" or an underscore "PMID_38830897".  It's probably related and I can fix that.

Also we get no matches at all for PMID38830897.  We should fix that too.

**Comment by kimrutherford** [comment]
> I noticed that we get the same weird result if we change the colon to a space "PMID 38830897" or an underscore "PMID_38830897". It's probably related and I can fix that.
> 
> Also we get no matches at all for PMID38830897. We should fix that too.

I've fixed all those cases for the morning.

Still don't know what caused your bug though.

**Comment by kimrutherford** [comment]
Since we can't reproduce this problem should we close the issue?

**Comment by ValWood** [comment]
yep, maybe there were some funny charcters in my string

**Comment by kimrutherford** [comment]
If you see other weird search box behaviour in future could you try pasting into an email or GitHub issue?  Thanks.
