### ISSUE TITLE
News item 1 Changes to protein features view on gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2276]
The protein domains and features section of the gene pages now uses the same  XXXX protein feature display as the "full view" linked to from the summary section to provide a consistent view of protein features across the website. We now also display active and binding sites, signal peptides, transit peptides, TMMs, and other Sequence Ontology features in this view.

Illustrated using cpy1
<img width="943" alt="Screenshot 2024-11-14 at 12 43 07" src="https://github.com/user-attachments/assets/21aa80b4-fb33-412d-bf52-6d3a3a10bb25">

**Comment by kimrutherford** [comment]
> the same XXXX protein feature display

What's the XXXX?

**Comment by ValWood** [comment]
I meant to look that up.  We should credit the developers RCSB (somehow)

**Comment by kimrutherford** [comment]
> I meant to look that up. We should credit the developers RCSB (somehow)

We could included this underneath like with previous news items:

-----------------

Thanks to the team at [RCSB PDB](https://www.rcsb.org/) for providing the [Open Source software](https://github.com/rcsb/rcsb-saguaro) used to implement this feature.

**Comment by ValWood** [comment]
sounds good

**Comment by kimrutherford** [comment]
OK, thanks.  I've added that acknowledgement which will be on the site by morning.
