### ISSUE TITLE
News item 2 Additional protein features imported from UniProtKB

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2277]
Additional protein features and modifications inferred from sequence context by the UniProt database have been imported to supplement our large curated experimental datasets.  (Imported data  <LINK https://www.pombase.org/reference/PMID:36408920>) includes propeptides, active site binding sites, mitochondrial targeting signal and 212 additional signal peptides. Features are listed in the "protein domains and properties" section of the gene page and features with coordinates provided are displayed in the protein feature viewer. Signal peptides and mitochondrial targeting signals from all sources can also be retrieved using the queries in the "domains features and motifs section of the "Advanced Search (link)". We have also imported an additional 445 inferred modifications from UniProtKB to supplement the ~69,000 PomBase curated modifications.

**Comment by kimrutherford** [comment]
> We have also imported an additional 445 inferred modifications

Should we say "curated" instead of "inferred"?

**Comment by ValWood** [comment]
>>We have also imported an additional 445 inferred modifications
>Should we say "curated" instead of "inferred"?

I think they are largely inferred from conserved positions

**Comment by ValWood** [comment]
They all seem to be "match to sequence model evidence used in manual assertion"

We could say curated or inferred

**Comment by kimrutherford** [comment]
> We could say curated or inferred

OK, thanks for checking.  I'll leave it as inferred.
