### ISSUE TITLE
remove 2025 from histogram

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2279]
<img width="1152" alt="Screenshot 2024-11-15 at 11 48 13" src="https://github.com/user-attachments/assets/23992fbd-ec89-4250-bd97-4f2f2aa01892">

**Comment by kimrutherford** [comment]
Hi Val.

I'll change the code to truncate the graph at the current year.

The bug is triggered by this annotation in `pombe-embl/supporting_files/legacy_go_annotations_from_contigs.gaf.tsv`:

```
PomBase    SPBC16C6.06     vps10           GO:0010209      GO_REF:0000024  ISO     SGD:S000000113  F       XXXX    pep1    protein taxon:4896      20251108 PomBase
```

Looks like the date is a typo: "20251108"

**Comment by kimrutherford** [comment]
> I'll change the code to truncate the graph at the current year.

I've fixed code and updated pombase.org

**Comment by ValWood** [comment]
oops, I will fix that!

**Comment by ValWood** [comment]
fixed date
