### ISSUE TITLE
extensions of the same type on different rows

### ISSUE THREAD

**Issue by ValWood** [pombase/website#228]
![pom1](https://cloud.githubusercontent.com/assets/7359272/24392721/00f2ca0e-138d-11e7-8bf5-13ab3485429c.jpg)

pom1

has substrate cdr2 , mod5 , pal1
and
has substrate syt22 , tea4 , rga7

**Comment by kimrutherford** [comment]
Antonia reported this too:
  https://github.com/pombase/website/issues/45#issuecomment-289388828

**Comment by kimrutherford** [comment]
I think this is fixed now.

**Comment by ValWood** [comment]
Looks good except.....
