### ISSUE TITLE
modification download

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2282]
Currently, the link takes you directly to the Ftp site.
I think it would be better if we had a page like GO and FYPO where the format is described (and also duplicate this in the README)

The format is currently only available from the submission page:
https://www.pombase.org/documentation/modification-data-bulk-upload-format
(also I think the export format now has an assigned_by column so we need to add that)

**Comment by ValWood** [comment]
At the same time can we change the assigned by Label from UniProt to UniProtKB

**Comment by kimrutherford** [comment]
> At the same time can we change the assigned by Label from UniProt to UniProtKB

I've made that change.

**Comment by kimrutherford** [comment]
While we're doing this I think we should rename the file.  Currently it's `pombase-chado.modifications.gz`.  The "chado" isn't meaningful to most users.  I don't know why I did that.  :-)

I'd prefer something like: `pombase_protein_modifications.tsv.gz`

I like having the "pombase" in the file name because I've had cases where I've downloaded a file and then later on couldn't remember where I got it.  "pombe" in the file name would work too.

**Comment by kimrutherford** [comment]
I've made a first attempt at a modifications file documentation page, linked from the Datasets page:

 - https://www.pombase.org/datasets
 - https://www.pombase.org/downloads/modifications

It can be edited here: https://github.com/pombase/website/blob/master/src/docs/downloads/modifications.md

I'd like to improve the description for "assigned_by" and perhaps we need to describe what the extensions mean?

**Comment by ValWood** [comment]
I think pombase is good in the label. It's clearer than just pombe and will remind people

**Comment by ValWood** [comment]
I think the docs are great, nice clear and concise.
For extensions we could refer people to the full list on  the submission page
https://www.pombase.org/documentation/modification-data-bulk-upload-format

**Comment by kimrutherford** [comment]
> For extensions we could refer people to the full list on the submission page
> https://www.pombase.org/documentation/modification-data-bulk-upload-format

Thanks.  That solves that problem!

**Comment by kimrutherford** [comment]
> I'd prefer something like: pombase_protein_modifications.tsv.gz

That will be updated in the morning.

I'll close this after checking tomorrow.
