### ISSUE TITLE
phosphorylation phenotype grouping, small thing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2283]
<img width="856" alt="ticket group alleles" src="https://github.com/user-attachments/assets/78a9a8eb-1673-4087-96d5-64e41fdefadb">

This is great,  but it would be even better organized by allele too

so

  | cdc2-as(F84G aa)
  | cdc2-as(F84G aa) affecting cut12 modified residue T75

  | cdc2-33(A177T aa) affecting cdc13, orc2, pol1, sld3
  | cdc2-33(A177T aa) affecting rap1 modified residue S422, S513, T378
  | cdc2-33(A177T aa) affecting cdc18 modified residue T104A, T10A, T134A, T374A, T46A, T60A

  | cdc2-56(G183E aa) affecting cdc13
  | cdc2-L7(P208S aa) affecting cdc13, orc2
  | cdc2-ts(unknown) affecting fkh2 modified residue S462, T314
  | cdc2-DL2(E215K aa)[Overexpression] affecting activity of cdc2

**Comment by kimrutherford** [comment]
So split the row of genotypes with no extension:
```
 cpc2Δ, int6Δ, psk1Δ, puf2(1-592)(593-1065 Δaa)[Overexpression], tif308Δ,   ...
```

and then order group all the alleles together in alphabetical order?

![image](https://github.com/user-attachments/assets/55613431-171f-49f5-839f-99e8f9c16022)

**Comment by ValWood** [comment]
I hadn't considered the rows with no extensions. let's chat about this tomorrow...

**Comment by ValWood** [comment]
1. Make sure the "abnormal translation" is pinned to "assayed_protein"
2. Groups by "affecting"  (i.e display label rather than underlying relation)
3. Implement the sorting of grouping by allele

**Comment by kimrutherford** [comment]
> Groups by "affecting" (i.e display label rather than underlying relation)

That's done now.

It makes quite a difference on some pages.  This is https://dev.pombase.org/reference/PMID:39476757

Before:
![image](https://github.com/user-attachments/assets/abbc61fb-42aa-49ff-a81a-38a688e8aaf7)

After:
![image](https://github.com/user-attachments/assets/9ed8fd39-0a7a-4da2-b78c-0be0b19b24a1)

**Comment by ValWood** [comment]
much better!

**Comment by kimrutherford** [comment]
> Implement the sorting of grouping by allele

How's this?:

![image](https://github.com/user-attachments/assets/1361fc42-bd60-45ff-bde2-767ca79dc250)

**Comment by kimrutherford** [comment]
> Make sure the "abnormal translation" is pinned to "assayed_protein"

Can you remind me what that means?

**Comment by ValWood** [comment]
I have no idea  🤷‍♀️

**Comment by ValWood** [comment]
but seriously , *I think* it's just referring to making sure everything has the same display label. I'm not sure why I used the word 'pinned'

**Comment by ValWood** [comment]
did we add that to another ticket?

**Comment by PCarme** [comment]
Wasn't it about configuring the assayed_protein extension for cytoplasmic translation and its children ?

**Comment by kimrutherford** [comment]
> Wasn't it about configuring the assayed_protein extension for cytoplasmic translation and its children ?

Thanks!

What should we display to the user instead of "assayed_protein" in Canto?

There are no other BP terms with configuration for "assayed_protein".  Is that OK?

**Comment by kimrutherford** [comment]
From the call:
 - Add assayed_protein as an extension option for FYPO:0003124 "abnormal cytoplasmic translation"

Many of the other "assayed_protein" configurations are admin-only.  Should this new configuration be admin-only or for all users?

**Comment by ValWood** [comment]
I don't remember why these would be admin only, I guess make them available to everyone and see what happens ;)

**Comment by ValWood** [comment]
OK this might be about modified forms (because it refers to proteins). Any extension which refers to modified forms is "admin only" because we need to make sure we have an identifier for the modified form.
I can't remember which terms this applied to, or whether modified forms are allowed for phenotype terms.
Remind me which phenotype terms have this extension.

**Comment by kimrutherford** [comment]
Here are all of the "assayed_protein" configurations.  For all the user configs the Range ID is ProteinID which means it's restricted to genes.  The admin-only config has range ID of "Text" meaning you can paste in anything, which will be a modified form for these cases.  So I think it makes sense.  The extensions that allow modified forms are only configured for admin users.

|domain ID           |range ID            |role   |Canto display text                                               |
|--------------------|--------------------|-------|-----------------------------------------------------------------|
|FYPO:0003845        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0000213        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0000601        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0000682-is_a(FYPO:0004916)|ProteinID           |user   |assayed enzyme                                                   |
|FYPO:0000702-is_a(FYPO:0007157)|ProteinID           |user   |affected proteins (add TWO, i.e. both binding partners)      |
|FYPO:0000834        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0001092-is_a(FYPO:0000702)&is_a(FYPO:0002131)|ProteinID           |user   |assayed protein                                                  |
|FYPO:0001679        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0001945        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0002114        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0002131        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0002274-is_a(FYPO:0000661)&is_a(FYPO:0006458)|ProteinID           |user   |assayed protein                                                  |
|FYPO:0002333-is_a(FYPO:0001679)&is_a(FYPO:0006163)|ProteinID           |user   |assayed protein                                                  |
|FYPO:0002671        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0003086        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0003452        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0003578        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0004083        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0004849-is_a(FYPO:0006458)|ProteinID           |user   |assayed protein                                                  |
|FYPO:0005493        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0005800        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0005807        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0005904        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0006163        |ProteinID           |user   |assayed protein                                                  |
|FYPO:0000137        |ProteinID           |admin  |assayed protein                                                  |
|FYPO:0000702-is_a(FYPO:0007157)|Text                |admin  |affected protein isoforms (add TWO, i.e. both binding partners)|
|FYPO:0000834        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0002274        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0002333        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0002671        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0003452        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0004083        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0004849        |Text                |admin  |assayed protein isoform                                          |
|FYPO:0003124        |Text           |admin  |assayed protein isoform                                          |

**Comment by kimrutherford** [comment]
> Add assayed_protein as an extension option for FYPO:0003124 "abnormal cytoplasmic translation"

That's done now so we can probably close this issue.
