### ISSUE TITLE
exact term not located in Advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2285]
"protein kinase activity" an exact term name is not found

<img width="733" alt="Screenshot 2024-11-27 at 09 43 22" src="https://github.com/user-attachments/assets/f30851a1-d0cc-491b-a69c-dd80f4e7e2c2">

**Comment by kimrutherford** [comment]
> "protein kinase activity" an exact term name is not found

Frustrating!  I thought it was doing OK.

**Comment by ValWood** [comment]
Yeah it  usually is, but it still sometimes seems to fail "exact matches" if there are longer matching terms.

**Comment by ValWood** [comment]
fab, that will be really helpful

**Comment by ValWood** [comment]
Yep I just tested a couple that I knew came way down the list. Much improved.

**Comment by kimrutherford** [comment]
> Yep I just tested a couple that I knew came way down the list. Much improved.

Thanks!  Please keep a look out for other problems though.
