### ISSUE TITLE
no modifications showing for meu1 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2287]
no modifications showing for meu1 
maybe. because of alternative transcripts?

<img width="881" alt="Screenshot 2024-11-28 at 22 25 21" src="https://github.com/user-attachments/assets/a6cbc711-0ade-46b1-afd9-e1995fe5d8e9">

**Comment by kimrutherford** [comment]
> maybe. because of alternative transcripts?

Very likely!  Which transcript should the modifications be associated with?

**Comment by kimrutherford** [comment]
Your comment ended up as a milestone: https://github.com/pombase/website/milestone/6

> maybe. because of alternative transcripts?

Now I've looked this with a clearer head, `meu1` has only one transcript so the missing modification diagram must have a different cause.

My guess is that the problem with `meu1` is the comma separated positions like "**modified residue** S174,S344":

![image](https://github.com/user-attachments/assets/38a14d7f-bf9d-48ca-93e7-442805ad77e4)

I noticed that on some other gene pages, the comma separated positions aren't shown, like "**modified residue** S546,S93" here:
https://www.pombase.org/gene/SPBC25D12.05

The `meu1` modifications annotation with "**modified residue** S174,S344" comes directly from a PHAF file:
`external_data/modification_files/PMID_39367033_modifications.tsv`

Should that be split into two separate annotations in Chado?

**Comment by ValWood** [comment]
Yes I thought we had already split those in the pHAF files!

**Comment by ValWood** [comment]
oops hyes still need to represent as alt transcripts https://github.com/pombase/curation/issues/61

**Comment by PCarme** [comment]
> The `meu1` modifications annotation with "**modified residue** S174,S344" comes directly from a PHAF file:
> `external_data/modification_files/PMID_39367033_modifications.tsv`

I made this modification file recently. Should I use separators "|" between the different modified positions in bulk modification annotations ?

**Comment by kimrutherford** [comment]
> Should I use separators "|" between the different modified positions in bulk modification annotations ?

In the other files we have each modified residue on a separate line.  So instead of:

```
SPAC1556.06    meu1    MOD:00046       ECO:0006056     S174,S344       increased_during(GO:0007127)     PMID:39367033   4896    2024-11-07
```

we would have:

```
SPAC1556.06    meu1    MOD:00046       ECO:0006056     S174       increased_during(GO:0007127)     PMID:39367033   4896    2024-11-07
SPAC1556.06    meu1    MOD:00046       ECO:0006056     S344       increased_during(GO:0007127)     PMID:39367033   4896    2024-11-07
```

It's not very efficient!  Let's discuss it on Zoom.

**Comment by kimrutherford** [comment]
I have split the lines with multiple residues onto multiple lines.  I'll check the results in the morning.

**Comment by kimrutherford** [comment]
> I have split the lines with multiple residues onto multiple lines. I'll check the results in the morning.

All good.  meu1 now has a modifications graphic.
