### ISSUE TITLE
some duplicate proteins have no InterPro domains

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2288]
I don't think this is likely anything to do with the new release, it might be to do with the way the pipeline works

Systematic ID | Gene name | Product description
-- | -- | --
SPAPB8E5.02c | rpn502 | 19S proteasome regulatory subunit Rpn502
SPAC144.11 | rps1102 | 40S ribosomal protein S11
SPAC3H5.05c | rps1401 | 40S ribosomal protein S14

i.e rnp501 is an exact duplicate of rpn502 and does have Pfam domains
https://www.pombase.org/gene/SPAC1420.03

**Comment by kimrutherford** [comment]
> i.e rnp501 is an exact duplicate of rpn502 and does have Pfam domains

Thanks for the hint.  That was the problem.  The InterProScan pipeline produces one result for each unique AA sequence its given.  It was producing a single result for rnp501 and rpn502, with a section like this at the end of the result JSON:

```
  "xref" : [ {
    "name" : "SPAC1420.03.1:pep rpn501|19S proteasome regulatory subunit Rpn501",
    "id" : "SPAC1420.03.1:pep"
  }, {
    "name" : "SPAPB8E5.02c.1:pep rpn502|19S proteasome regulatory subunit Rpn502",
    "id" : "SPAPB8E5.02c.1:pep"
  } ]
```

My code was only using the first "xref" so rpn502 wasn't getting any domains.

Fixed for tonight's load.  I'll check in the morning.
