### ISSUE TITLE
PMID: search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2293]
check Pubmed search
PMID:24223771 does not seem to be working? but others are??

**Comment by PCarme** [comment]
Strange, could it have something to do with the fact that I have just curated it earlier today ?

**Comment by ValWood** [comment]
Maybe but it should be in the database already?
I  was checking its status because I got an e-mail non deliver notification from ucl, but I couldn't remember sending the session to you.

**Comment by PCarme** [comment]
You didn't send it to me, it was one of the abstract Andrew's model judged as curatable which I wanted to have a quick look at because because it seemed like there was just a few curable phenotypes anyway.

**Comment by ValWood** [comment]
OK that's good to know. We don't have a problem with the PMID search, AND my memory isn't completely failing!
We only need to address the e-mail bouncing issue.

**Comment by kimrutherford** [comment]
> Maybe but it should be in the database already?

Yep, seems like a bug to me.

**Comment by ValWood** [comment]
I guess it depends what it was classified as previously...

**Comment by kimrutherford** [comment]
I can't work out what's going on.  That paper was in Chado on Thursday, then missing on Friday and now it's back.

Until Friday it was "Mutagenicity or toxicity study" in Canto which is one of the triage statuses that gets loaded into Chado.  It's now "Curatable".

**Comment by ValWood** [comment]
I don't think it's an issue. maybe it was not classed as classified when it was being curated?

**Comment by kimrutherford** [comment]
Yep, I think it must be something like that.
