### ISSUE TITLE
send all physical and genetic interactors of a gene to advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2294]
It would be useful if we could
send all physical and genetic interactors of a gene to advanced search
(in the same way that we can send all "targets")

**Comment by kimrutherford** [comment]
> send all physical and genetic interactors of a gene to advanced search

Where would the link go?

I noticed that the "Query using interacting genes ..." link is missing from the genetic interactions section.  I'll add it back.

**Comment by kimrutherford** [comment]
> I noticed that the "Query using interacting genes ..." link is missing from the genetic interactions section. I'll add it back.

Fixed!

I got lost when we started showing the genotype to genotype interactions.

**Comment by ValWood** [comment]
OK! I thought we used to have it. this is done then! it is there for physical
