### ISSUE TITLE
Change the GO section filter from  Throughput to Evidence type and expand options

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2297]
Change the GO section filter from Throughput to Evidence type and expand options 

This would allow people to filter inferences.

**Comment by ValWood** [comment]
We already have the filter for non-experimental under  the full-view:

<img width="1106" alt="Screenshot 2024-12-10 at 15 15 37" src="https://github.com/user-attachments/assets/ba99cf93-2405-40ad-aa7f-897d2d78d361">


but  for some reason we didn't include "experimental" as an option

**Comment by kimrutherford** [comment]
I think adding "Experimental" could be confusing.  The three current menu items are mutually exclusive.  With "Experimental" added there will be overlap between the options.

**Comment by kimrutherford** [comment]
> add the following evidence groups

Those are the three groups we have already.  Do you mean rename rather than add?

**Comment by kimrutherford** [comment]
Here is the current configuration for evidence/throughput types.  This config is how GO annotation gets assigned a throughput type on loading.

IRD, NR and RCA don't have a configured type but we don't have any of those annotations.

|type|codes|
|--|--|
|high throughput|HDA HEP HGI HMP HTP|
|low throughput|EXP IDA IGI IMP IPI|
|non-experimental|IBA IBD IC IEA IEP IGC IKR ISA ISM ISO ISS NAS TAS|
|unset|IRD ND NR RCA|

**Comment by kimrutherford** [comment]
I've implemented this on my desktop: https://desktop.kmr.nz/gene/SPAC1565.08

**Comment by ValWood** [comment]
That's great.

 I think the labels should be

Low  => Experimental (LTP)
High => Experimental (HTP)
All experimental => Experimental (All)
and Inferred

If we think everyone won't know what HTP/LTP is then we need to put this in full. The labels would be quite long but I think that is OK?

@PCarme thoughts?

**Comment by PCarme** [comment]
I'm not sure everyone will understand what HTP and LTP mean. If the full labels are too long, maybe we could do:
Experimental (all)
Exp. (low throughput)
Exp. (high throughput)
Inferred

**Comment by kimrutherford** [comment]
Hi.

I've rudely ignored your suggestions and changed the labels to:
     - High throughput experiment
     - Low throughput experiment
     - Inferred
     - All experimental annotation

(Sorry I got the order wrong - I'll fix that)

I've done this to see if they are too long.  What do you think?:

![ev_type_filter](https://github.com/user-attachments/assets/4cefc4da-bced-4370-b460-5caaf635b2fd)

**Comment by ValWood** [comment]
Looks good!

**Comment by kimrutherford** [comment]
> (Sorry I got the order wrong - I'll fix that)

They are now in the order that you suggested.

Is that all OK?  Can we close this issue?

**Comment by ValWood** [comment]
I think so

**Comment by ValWood** [comment]
@PCarme   when you  do ontology data for "Just one thing" remember to include/explain these filters. (since we never announced this improvement)
