### ISSUE TITLE
localization filter, possible bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2299]
For some reason,
cytosol and nucleus are greyed out here. I thought based on how the filter works , that since these are slim terms,  is should be possible to filter on either one of these?

<img width="1026" alt="Screenshot 2024-12-09 at 11 14 20" src="https://github.com/user-attachments/assets/368e6fe8-ad52-4942-8c74-363ea632ae76">

**Comment by kimrutherford** [comment]
Which gene page is that?

**Comment by ValWood** [comment]
nit sure but here's an example
https://www.pombase.org/gene/SPCC1494.01

**Comment by kimrutherford** [comment]
Yep, sorry, it's a bug.  It's been there quite a while.  It's only a problem when there is a annotation to a top-level slim term and there are no annotations to child terms of that top-level term.  Might be more common for component annotations.

It's fixed for the morning.
