### ISSUE TITLE
genome browser track for cDNAs

### ISSUE THREAD

**Issue by mah11** [pombase/website#23]
Data from INSDC nucleotide db. Suggestion that bed format will do the trick.

https://github.com/pombase/curation/issues/903 may also be useful.

Background and a few more details in Jira PB-579 (ignore part that refers to PB-1275).

**Comment by ValWood** [comment]
we might not even do this.... we have plenty of good transcriptome datasets to host.

**Comment by ValWood** [comment]
out of date
