### ISSUE TITLE
List single-allele genotypes first, and then multi-allele genotypes.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#231]
from
#192

 single-allele genotypes first, and then multi-allele genotypes. In the detailed view they could be separate tables if V&A prefer.

**Comment by ValWood** [comment]
detailed view might be better separate tables....

**Comment by ValWood** [comment]
This refers to term pages yes?

**Comment by kimrutherford** [comment]
> This refers to term pages yes?

I assume so.  Perhaps it would be more consistent to split the phenotype annotations into single and multi-allele tables to match the gene pages.

**Comment by ValWood** [comment]
2 tables please.

**Comment by kimrutherford** [comment]
> 2 tables please.

It's now split into two tables but the tables headers aren't great.  I'll improve them.

**Comment by kimrutherford** [comment]
> but the table headers aren't great. I'll improve them.

It now says something like:
  "Single allele phenotype annotations for FYPO:0000059 and its descendants"

If that's OK I'll close this issue.

**Comment by ValWood** [comment]
yep

single_allele_phenotype annotations for FYPO:0001355 and its descendants

should we remove the underscores here?

**Comment by kimrutherford** [comment]
> should we remove the underscores here?

Ah, sorry.  That's what I just fixed but I forgot to re-release.  It should be fixed now if you shift-reload.

**Comment by ValWood** [comment]
ok
