### ISSUE TITLE
viability summary

### ISSUE THREAD

**Issue by mah11** [pombase/website#233]
The "viability summary" is whichever of these statements is true for the gene:

- Gene deletion viability: viable
- Gene deletion viability: inviable
- Gene deletion viability: viability depends on conditions

Put it in a friendly little box at the top of the Single-allele phenotype section (above and separate from the table of actual annotations).

Use "viable" if the deletion allele is annotated only to  FYPO:0002058 or any of its is_a descendants.
Use "viable" if the deletion allele is annotated only to FYPO:0002059 or any of its is_a descendants.
Use "viability depends on conditions" if the deletion allele is annotated to both FYPO:0002058 and FYPO:0002059 (directly or to an is_a descendant), with different conditions specified for the annotation.

(If any allele is annotated to both FYPO:0002058 and FYPO:0002059 with the same conditions, we should investigate in case one's a mistake. But that's outside the scope of this ticket.)

**Comment by kimrutherford** [comment]
I've added a viability section at the top of the phenotypes.  I've copied the HTML from PomBase v2 but it's easy to change.

What it shows may or may not be right, see: https://github.com/pombase/curation/issues/1406
