### ISSUE TITLE
some more grouping on ontology pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#235]
Yesterday we discussed whether there were any other ways that terms should be grouped together.

I think we are OK for now on the gene pages, but on the ontology pages, it might be better for process terms if regulation terms were listed immediately underneath the regulated process.

See:
![grouping regulates with term](https://cloud.githubusercontent.com/assets/7359272/24468887/97f8bc4a-14b1-11e7-871e-4568b4cbd1c4.jpg)

mitotic spindle assembly
regulation  of mitotic spindle assembly
positive regulation  of mitotic spindle assembly

mitotic spindle elongation
regulation of mitotic spindle elongation
positive regulation of mitotic spindle elongation
negative regulation of mitotic spindle elongation

much easier to consume ....

**Comment by ValWood** [comment]
This is in no way critical but do others think it would be useful?

**Comment by ValWood** [comment]
assess if it would be better to order terms so more specific terms first 
Kim suggested this. It might work for function, not sure about process.
Need to add some page examples, and discuss pros & cons

(transferred from  https://github.com/pombase/website/issues/229)
will discuss term age display again later

**Comment by ValWood** [comment]
also  consider with this one
https://github.com/pombase/website/issues/235

**Comment by ValWood** [comment]
A small improvement might be to always have the term in question at the top...
MAybe we discussed this and decided against it...

I'm thinking 
Term...
Descendants...

Sometimes its a bit odd that the term referred to can get a bit buried...
But there may be disadvantages to doing this?

**Comment by ValWood** [comment]
Action:
Put the  'term page' term at the top.

**Comment by kimrutherford** [comment]
> Action:
> Put the 'term page' term at the top.

I've made that change.  I'll close the issue after checking on Tuesday morning.

**Comment by kimrutherford** [comment]
> Action:
> Put the 'term page' term at the top.

Done and now on the main site.
