### ISSUE TITLE
GO slim page and slim summary

### ISSUE THREAD

**Issue by ValWood** [pombase/website#238]
Can we copy this ?

http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

and the process slim summary
![go slim](https://cloud.githubusercontent.com/assets/7359272/24499336/398c6cdc-1539-11e7-87e7-9b2f5af05dc5.jpg)

(pombe slim terms are in the Obo file)

**Comment by ValWood** [comment]
![link to network](https://cloud.githubusercontent.com/assets/7359272/24506191/95a22c44-1554-11e7-8a58-859add045fd1.jpg)

here we should add a small network icon/button, with a link to the network
http://www.esyn.org//builder.php?type=Graph&term=GO:0007005&interactionType=physical&source=pombase&includeInteractors=false

**Comment by kimrutherford** [comment]
> pombe slim terms are in the Obo file

We should be able to get the slim terms from the OBO files and store a property on each one marking it as a slim term.  We already do that for Canto, but we should put that information in Chado too.

**Comment by ValWood** [comment]
goslim_pombe is the  subset catagory

**Comment by kimrutherford** [comment]
So are these links the same on every gene page?

**Comment by ValWood** [comment]
No, only the GO categories a  gene product is in.
This is cdc2 which has a lot. Most GPs only have 1 unless they are signalling pathway.

**Comment by kimrutherford** [comment]
Thanks!  Got it now.

**Comment by kimrutherford** [comment]
Do we just need to follow is_a relations to those slim terms to get the categories?

**Comment by ValWood** [comment]
ia_a part_of and regulates..

**Comment by kimrutherford** [comment]
> Can we copy this ?

Done!  (But might need a shift-reload)

> here we should add a small network icon/button, with a link to the network

Not done!  :-)

I think I've more or less replicated the GO slim links from PomBase v1 but I haven't added the esyN link.  I'll do that tomorrow.

> We should be able to get the slim terms from the OBO files

It was quicker just to configure the slims terms in pombase-embl/website/pombase_v2_config.json
We can do something fancier with subsets in future.

**Comment by kimrutherford** [comment]
> I haven't added the esyN link

Do you want an icon beside each slim term name?  Or would be better to have a prominent link to esyN on the term pages?

**Comment by ValWood** [comment]
Was planning also to have a link on the term pages.

I am going to suggest that when we ditch esyN and use cytoscape directly (esyN is  built  using cytoscape components and I think these  network images are pretty trivial to embed. I have a task on my list to open a ticket about this... It has been brewing nicely...

This would allow us to generate networks for every process term, not only the GO slim terms and this will be absolutely amazingly useful for curators and users.

At the moment,  the networks are quite large (when well curated processes)

regulation of mitotic cell cycle transition looks like this:

http://www.esyn.org//builder.php?type=Graph&term=GO:1901990&interactionType=physical&source=pombase&includeInteractors=false

 but it is difficult to interpret because it includes all transitions. Would be better if you could also see networks for all of the sub processes 
G2/M transition
G1/S transition
metaphase/anaphase
etc...

G2/M transition would look like this:
https://cloud.githubusercontent.com/assets/7359272/23817233/692f943c-05e9-11e7-9212-456da112a789.jpg
and then there are sub components of this (checkpoint pathways)

...it will be amazing ;)

But, if it is easy, add the esyN link to the GOslim term pages now ;)

**Comment by kimrutherford** [comment]
> But, if it is easy, add the esyN link to the GOslim term pages now ;)

Done.

> I am going to suggest that when we ditch esyN 

Shall we close this issue and make a new one for ditching esyN?

**Comment by ValWood** [comment]
I'll open the new ticket, likely today, with the subtasks that I  can think of, its near  the top of my list to do this....I'll curate a paper first...
