### ISSUE TITLE
reimplement gene list search

### ISSUE THREAD

**Issue by mah11** [pombase/website#24]
At present the gene list search (http://www.pombase.org/spombe/query/builder?filter=12) requires IDs to be pasted into the search box. Add a(nother) "browse" button to upload a file of IDs.

**Comment by ValWood** [comment]
We need to be able to upload a gene list into the "query builder tool"
http://www.pombase.org/spombe/query/builder?filter=12

and to upload a file (as above)

**Comment by ValWood** [comment]
Also if possible,
We don't know if this will be feasible, but we've had users request it, so:

Option for the gene name and systematic ID filters, to have results returned with genes in the same order as in the input list.

User requests in https://rt.sanger.ac.uk/Ticket/Display.html?id=303908 & https://rt.sanger.ac.uk/Ticket/Display.html?id=456638

from
https://github.com/pombase/website/issues/31

**Comment by kimrutherford** [comment]
> to have results returned with genes in the same order as in the input list.

That should be possible.  There's no reason we can't have preserving the order as the default action.

**Comment by ValWood** [comment]
The wording of the ticket is from our previous life;) lower expectations.

**Comment by ValWood** [comment]
We can upload a gene list, the rest is post release enhancement territory.

**Comment by kimrutherford** [comment]
> Option for the gene name and systematic ID filters, to have results returned with genes in the same
> order as in the input list.

Yep that possible.  Currently if you OR two queries together the order is maintained.  AND queries come out is a random order but that can be fixed later.

**Comment by ValWood** [comment]
that isn't such an issue. Its more when you upload a single list, and I think the order for this is already preserved?

**Comment by kimrutherford** [comment]
> Add a(nother) "browse" button to upload a file of IDs.

It was quick to implement so I've added a read from file button.

The gene lookup is still quite dumb as it only handles systematic IDs not gene names.

**Comment by ValWood** [comment]
fixed or at least in another ticket?
https://github.com/pombase/website/issues/583
