### ISSUE TITLE
 genome statistics page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#240]
auto generated:
http://www.pombase.org/status/statistics

We should review the content. I think there were outstanding problems with some of this....

**Comment by ValWood** [comment]
currrent page has:

About HTML Tidy: https://github.com/htacg/tidy-html5 Bug reports and comments: https://github.com/htacg/tidy-html5/issues Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/ Latest HTML specification: http://dev.w3.org/html5/spec-author-view/ Validate your HTML documents: http://validator.w3.org/nu/ Lobby your company to join the W3C: http://www.w3.org/Consortium
Do you speak a language other than English, or a different variant of English? Consider helping us to localize HTML Tidy. For details please see https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md

we can punt sorting this page until after release. I don't think anyone uses it much and it is not going to be so far out of date....

**Comment by kimrutherford** [comment]
> About HTML Tidy:

Whoops.  I've removed that text.

**Comment by ValWood** [comment]
MArtin Kollmar
"- Genome statistics, Chromosome table: part of "gene density": "(genes per Mb)" is clear. But what is "Gene" there? It is almost the same as "Exon (All)". Are "Gene" and "Exon" as part of "gene density" really useful measures for S.pombe? As "mean length", are partial base pairs (numbers after decimal comma) really biological useful information, wouldn't it make much more sense to just round these numbers to base pairs?"

I agree but we did not intend to replace this...

**Comment by ValWood** [comment]
Oh I see we already have this big table on the new site.

http://preview.pombase.org/status/statistics

Let's just delete all the table
and add
rRNA 47
snoRNA 57
etc.

We don't need all the stuff other stuff, we can add more stats later if  requested

**Comment by kimrutherford** [comment]
> etc.

What's the "etc." bit?

> rRNA 47
> snoRNA 57

Do you mean delete all but those columns?

**Comment by ValWood** [comment]
yep  just keep those 2 columns. the rest are just numbers for numbers sake....

**Comment by ValWood** [comment]
what would the graph show though?
This page is  'equivalent' to this page
https://www.yeastgenome.org/genomesnapshot (table version)
I don't find the graph view so useful.
I'm not sure that it is necessary  to break down by chromosome either...

Any ideas?

**Comment by kimrutherford** [comment]
> what would the graph show though?

I can't think of anything.  :-)

I'll try to improve the style of the tables or at least put a little bit of vertical space between them.

**Comment by kimrutherford** [comment]
We removed the link to this page in #1714 so I guess we can close this issue?

**Comment by ValWood** [comment]
yup
