### ISSUE TITLE
priority unstudied genes list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#242]
This is basically a table of  unstudied genes conserved to human
There are some numbers in the text which are  calculated and updated to.

In fission yeast the "unknown" inventory is around 836 entries, many of which are apparently species-specific. However, a large number (511) are conserved, and a significant number of these (214) have orthologs in vertebrates. These genes are listed below.

836 = 
Query: ( PBO_ID(PBO:0000003 - conserved unknown) ) OR ( PBO_ID(PBO:0017405 - Schizosaccharomyces pombe specific protein, uncharacterized) ) OR ( PBO_ID(PBO:0017406 - Schizosaccharomyces specific protein, uncharacterized) )

511 = 	PBO_ID(PBO:0000003 - conserved unknown)

214 = Query: ( PBO_ID(PBO:0000003 - conserved unknown) ) AND ( PBO_ID(PBO:0011070 - conserved in vertebrates) )
(this is the list in the table)

**Comment by ValWood** [comment]
seems quicK

**Comment by kimrutherford** [comment]
I think I'll leave this one until we have discussed the new query builder and I've had a think about it.  It might be possible to reuse some query builder code to do this.

**Comment by ValWood** [comment]
The new table does not need to display  chromosome,strand,start,end

**Comment by ValWood** [comment]
I think the part of the query builder to plug in the current numbers/lists to
http://pombase2.aska.gen.nz/status/priority-unstudied-genes
is done, and would be useful, so labelling as quick...

If its  not that simple, punt to soon after release...

**Comment by ValWood** [comment]
These are the current numbers and queries required:

![queries](https://user-images.githubusercontent.com/7359272/28499647-643fac72-6fb2-11e7-9d94-8d33c7462637.jpg)

I have been working on these...A big drop since the last update!

**Comment by kimrutherford** [comment]
I was hoping to get this done today, but didn't manage it.  Hopefully tomorrow.

I've had to make some breaking changes to the query builder to fix this and to support saving queries between sessions.  I'll test on pombase2.bioinformatics.nz first so queries might fail on that for a while.

**Comment by kimrutherford** [comment]
This is sort of done:
  http://pombase2.bioinformatics.nz/status/priority-unstudied-genes

but I'd like to do some more testing.

**Comment by ValWood** [comment]
It's spot on ( the difference from the static one on preview is that I have been through and made lots of assignments)

Two minor text changes.

Now we have constant updates, there is no need to say  around  734,  ( (delete around)

You can also  change this text

From
You can retrieve a current list of conserved unknown genes using the Advanced Search, with or without specifying whether the genes are conserved. See the relevant FAQ and the Advanced Search documentation for details.

to
You can recreate this query, or variations of it, using the Advanced Search. See the relevant FAQ and the Advanced Search documentation for details. You can  also send this list directly to the advanced  search (For example to mine for phenotypes or locations of interest).

**Comment by kimrutherford** [comment]
> Two minor text changes.

I've made those changes.

**Comment by ValWood** [comment]
can close this, all done!

**Comment by ValWood** [comment]
as an aside "734" from this method  is nicely close to:
Gene products with no biological process annotation: 749
(2 slightly different ways of assessing unknowns, one based on chracterization status, and one based on presence of BP slim annotation).

difference partly due to
https://github.com/pombase/curation/issues/1664

also some "published" but not yet curated.

Anyway, these numbers are closer that they have ever been, and the differences are largely to do with "in progress curation", or edge cases.
