### ISSUE TITLE
A little bit more redundancy removing from ontology term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#243]
These term pages are really nice to show annotation specificity:

![today](https://cloud.githubusercontent.com/assets/7359272/24557670/65f63ba2-1630-11e7-8113-0682c541fded.jpg)

 We could also only show the most "specific" annotation in any branch.
This would not hide much here,
it would hide trm1 and trm10 in tRNA methylation because
trm1 tRNA N2-guanine methylation
trm10  tRNA N1-guanine methylation

it would hide trm8 from tRNA modification, because it also has tRNA methylation.

Although it doesn't hide a lot, it enables the user to see at a glance exactly the specificity of all the annotation for a particular process.... which will be really amazingly useful...

**Comment by kimrutherford** [comment]
I think this is just a bug.  I had a look for a simpler case.  

Should we hide the "ase1" on "mitotic spindle midzone assembly" here?:
  http://pombase2.bioinformatics.nz/term/GO%3A0051256

**Comment by ValWood** [comment]
yes that should be hidden. I don't think its a bug as such, we never previously mentioned hiding this redundancy on term pages...

**Comment by kimrutherford** [comment]
> I don't think its a bug as such

It's the same code that does all the summaries.  I think it's getting it wrong on the term pages because the summaries have the genes IDs in them.  I'll look into it.

**Comment by kimrutherford** [comment]
This is fixed now.   Two operations in the summary creation code were in the wrong order.  It was an easy fix once spotted.

**Comment by ValWood** [comment]
Yes, nice!
