### ISSUE TITLE
redundancy in phenotype section in gene page summary view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#245]
![redundancy](https://cloud.githubusercontent.com/assets/7359272/24579362/b389d9f8-16eb-11e7-9dfa-507730415e50.jpg)

here "viable vegetative cell with normal cell morphology" should  hide
"viable vegetative cell"?

**Comment by kimrutherford** [comment]
That's almost certainly caused by this problem:
  https://github.com/pombase/pombase-chado/issues/577

Note to self, check pet802 page after fixing the Chado bug:
  http://pombase2.bioinformatics.nz/gene/SPBC1271.11

**Comment by kimrutherford** [comment]
Fixed!  The summary for pet802 now looks right.

I'll get on with fixing this now: #279
