### ISSUE TITLE
stats page query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#246]
This looks as though it might not be up to date?

![i hope that isn t correct](https://cloud.githubusercontent.com/assets/7359272/24586332/bf4bdeb2-1795-11e7-855b-8e110f0ac79d.jpg)

I know we haen't curated very much recenty but this does seem   a tad low :)

**Comment by kimrutherford** [comment]
That might make sense because the x-axis is the publication date not the date of annotation.

**Comment by ValWood** [comment]
durr of course!
