### ISSUE TITLE
comma at the end of comma separated alleles on gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#247]
A comma has appeared at the end of the allele row. I don't think it was there yesterday?

**Comment by kimrutherford** [comment]
Sorry, that was a typo while fixing #171.  Fixed now.

**Comment by ValWood** [comment]
but now...
![comma](https://cloud.githubusercontent.com/assets/7359272/24608551/e67d26ba-186e-11e7-8ade-7c3baf25ec61.jpg)

**Comment by kimrutherford** [comment]
Whoops, sorry.  Should be fixed now.
