### ISSUE TITLE
more relationships to consider  for phenotype filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#248]
from
I noticed that
"decreased punctate nuclear protein localization"

is not present when the "localization phenotype " filter is set. I think it might be missing a parent?
https://github.com/pombase/fypo/issues/2983

==
This is because the parent, mislocalized protein during vegetative growth, has the link output_of FYPO:0000443 ! abnormal protein localization during vegetative growth (not is_a or part_of). To get the behavior you want, Kim will have to have the filters use the output_of relation for FYPO, and probably also has_output.

**Comment by ValWood** [comment]
I thought you did that already though?

**Comment by kimrutherford** [comment]
> I thought you did that already though?

The filter configuration wasn't using all the relations.  I've fixed it and simplified the config.  The localization phenotype filter works correctly for "decreased punctate nuclear protein localization" now.
