### ISSUE TITLE
put  "Curated vs uncurated by publication date" on front page 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#25]
To alternate with the word cloud
Is the current version OK, or does it require changes?

**Comment by mah11** [comment]
I need the date - @kimrutherford, are the data fresh from 2016-08-04?

**Comment by mah11** [comment]
I put it up on dev with the 4 Aug. date; can edit if that's not correct

**Comment by kimrutherford** [comment]
> I need the date - @kimrutherford, are the data fresh from 2016-08-04?

It was from the db loaded on 2016-08-03 but I've just updated to a db from 2016-08-08.

The date is now in the description on the stats page:
  https://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
well this is on the current rotation so closing for now...
