### ISSUE TITLE
simple gene name search should recognize synonyms

### ISSUE THREAD

**Issue by mah11** [pombase/website#252]
At present it doesn't. This was annoying when I was reading a paper that referred to a gene (mto1) by TWO of its synonyms (mbo1 & mod20) but didn't mention its standard name.

Labeled "next" because it's required to go live (not just because the lack of it makes me crazy ;) )

**Comment by kimrutherford** [comment]
It now searches synonyms but it's not perfect.  For example if you type a prefix that matches two synonyms of the same gene, the gene appears twice in the suggestions:

![screenshot at 2017-04-05 09-43-56](https://cloud.githubusercontent.com/assets/90474/24680342/adff8ca2-19e4-11e7-80de-a70bbc07bf24.png)

**Comment by ValWood** [comment]
I love the way it works though, matching any substring without the need for wild cards and putting the most sensible suggestions first. Genius.

**Comment by kimrutherford** [comment]
@mah11 Can you close this if you're happy with it?

**Comment by mah11** [comment]
That's fine - for the duplicate matches it's clear why a gene appears more than once. Thanks :)

**Comment by ValWood** [comment]
the same gene can appear twice though, I think that's the outstanding issue.

**Comment by mah11** [comment]
How big a problem is that, though? And would putting multiple matching synonyms on one line really be better?

**Comment by ValWood** [comment]
ah yeah its matching 2 different things, that's fine

**Comment by kimrutherford** [comment]
OK, I'm glad you're happy with it as-is for now.  It will need to be revisited anyway when we expand the search to terms, product and the other stuff.
