### ISSUE TITLE
show expression in phenotype detail view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#253]
we need a columns for expression details in phenotype detail view

**Comment by kimrutherford** [comment]
How should this be displayed for multi-allele genotypes?  Currently you need to click through to the genotype page to see the expression which keeps it tidy.

**Comment by ValWood** [comment]
well usually you can guess, or mostly it wasn't assayed...

![expression](https://cloud.githubusercontent.com/assets/7359272/24691232/2e00218e-19ca-11e7-9390-0e4e85e2fbfd.jpg)

It probably is OK to have it in genotype details now we have this page.....

?

**Comment by kimrutherford** [comment]
> It probably is OK to have it in genotype details now we have this page.....

A compromise is to have more details pop up when you mouse-over the genotype.

**Comment by ValWood** [comment]
that would be good too...

**Comment by kimrutherford** [comment]
> that would be good too...

OK, I'll try that to see if it helps.

**Comment by kimrutherford** [comment]
> A compromise is to have more details pop up when you mouse-over the genotype.

I've added a pop up that shows the allele expression details when you mouse-over a genotype description (like those in the phenotype annotation section).  I suspect it will be a bit annoying, but let me know what you think.

**Comment by ValWood** [comment]
I don't mind it *so* much lets see what others think.....maybe we only need something subtler ...

(you can't move int the pop up to click on the hyperlinked gene).

**Comment by ValWood** [comment]
...I'm still in 2 minds whether it is needed, its only one click away and often its obvious...

**Comment by mah11** [comment]
I can live with that, especially if it saves Kim coding and us testing something more complicated.

**Comment by kimrutherford** [comment]
I think I'll close this.  Please re-open or create a new issue for changes.
