### ISSUE TITLE
update sequence coodinate changes and sequence updates pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#254]
add changes described here:
https://github.com/pombase/curation/issues/1381

to here
http://www.pombase.org/status/gene-coordinate-changes

and to support changes reported by the broad here:
http://www.pombase.org/status/sequence-updates-pending

**Comment by ValWood** [comment]
before this we can ask  Kim how to maintain these files in the new system....
No need for  the changes go on the old site....

**Comment by kimrutherford** [comment]
I found that Pandoc does an OK job of turning HTML back into Markdown so I've copied the gene coordinate page across:
  http://pombase2.bioinformatics.nz/status/gene-coordinate-changes

GitHub displays it like this:
  https://github.com/pombase/website/blob/master/frontend/src/docs/status/gene-coordinate-changes.md

You can edit it online by clicking the pencil at top right.  If you do GitHub makes a big mess of displaying it in the edit box.  Changing the "Soft wrap" option at the top right to "No wrap" make it much better.

I've copied the status page too but most of the links don't work yet: http://pombase2.bioinformatics.nz/status

Also the formatting of both these new pages isn't great.  We can work on that.

**Comment by mah11** [comment]
Well, that seemed to work well enough - I added a bunch of rows to the gene-coordinate-changes table. I haven't tried to touch page formatting.

note to self - still to do, per val's comments on the curation ticket (https://github.com/pombase/curation/issues/1381): tif223, SPCC1442.04c, lsc1

**Comment by kimrutherford** [comment]
Thanks.  There are two lines near the bottom that seem to be missing bits.

There's a line that starts with:
  Chr_II:1950050!A→AG; coordinates changed from complement
that should start with a gene column.

And the line before it seems to be truncated.

**Comment by mah11** [comment]
Aha, those were supposed to be one line. Should be fixed now.

**Comment by kimrutherford** [comment]
Thanks.  Tomorrow I'll fix the style to make it look more like a table.

http://pombase2.bioinformatics.nz/status/gene-coordinate-changes

**Comment by kimrutherford** [comment]
The table looks a bit better now - more or less like the old site.

**Comment by kimrutherford** [comment]
Can this be closed now?

**Comment by mah11** [comment]
I think so. There are a few more updates to do, but I can get details from the curation ticket.
