### ISSUE TITLE
synonym search no longer working

### ISSUE THREAD

**Issue by ValWood** [pombase/website#258]
mts2 does not find 
http://pombase2.aska.gen.nz/gene/SPBC4.07c

**Comment by kimrutherford** [comment]
It works for me.  Does it show any results at all for you?

I get:


![screenshot_20170413_123855](https://cloud.githubusercontent.com/assets/90474/24985144/63c75e90-2046-11e7-842d-f62b6fb7674b.png)

**Comment by ValWood** [comment]
works for me now too!
