### ISSUE TITLE
legacy ftp site migration

### ISSUE THREAD

**Issue by ValWood** [pombase/website#262]
When this is done, we need to make sure that this ticket is fixed:

https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=182715

(V30 files are  have V 29 names)

**Comment by kimrutherford** [comment]
Can you paste the text into this issue?  My EBI login doesn't work any more.

**Comment by ValWood** [comment]
so basically the file names are
Schizosaccharomyces_pombe.ASM294v2.30.dna.genome.fa.gz
but when unzipped the file is called
Schizosaccharomyces_pombe.ASM294v2.29.dna.toplevel.fa

> Daer vall,
>
> I have difficulties finding the lastest version of the S. pombe genome 
> for .seq analyses.
>
> I found on pombase the file 
> "Schizosaccharomyces_pombe.ASM294v2.30.dna.genome.fa.gz. I dowload 
> the file on my computer, unzipp it and discover inside a file named 
> "Schizosaccharomyces_pombe.ASM294v2.29.dna.toplevel.fa", and not a 
> file "ASM294v2.30.dna.genome.fa" as I would expect.
>
> Could you please tell what is ASM294v2.29.dna.toplevel.fa, and, if it 
> is not the latest genome version of our favorite yeast, then where can 
> I find this piece of data.

**Comment by ValWood** [comment]
so basically I want ebi to fix the files before we migrate...

**Comment by ValWood** [comment]
The ftp issue above is resolved.

**Comment by ValWood** [comment]
This ticket isn't very explicit.
We will need to write out various files
protein datasets
gff
etc...
I will make a list of the files we need to generate....

**Comment by ValWood** [comment]
We   need to migrate the  archived files.

**Comment by ValWood** [comment]
we can use this ticket for ftp data
https://github.com/pombase/website/issues/355
