### ISSUE TITLE
redundancy in term and gene page  view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#264]
Example cytokinesis
http://pombase2.aska.gen.nz/term/GO%3A0061640
cdc8, fim1 mid1  appears in

	mitotic actomyosin contractile ring assembly
act1 , ain1 , arp3 , cdc12 , cdc15 , cdc3 , cdc4 , cdc8 , fim1 , for3 , hob3 , imp2 , klp6 , mid1 , myo51 , myp2 , plo1 , pxl1 , rng2 , rng3 , wsp1

and

	mitotic cytokinesis
acp1 , acp2 , arc1 , cdc11 , cdc8 , cyk3 , fic1 , fim1 , mac1 , mid1 , mid2 , mkh1 , myo52 , myp2 , pek1 , pom2 , pos1 , rng2 , rng8 , rng9 , spn1 , spn2 , spn3 , spn4 , stg1 , ypt3

They could appear in only  the most specific list in the term ontology  summary view as they do on the gene pages. this gives the user much more feel for the degree of characterisation of a list because  genes which are not so well studied tend to cluster at the  less specific terms.

**Comment by ValWood** [comment]
also see this, where  could be

prp2-1(C387Y)  affecting mba1,nab2,naa10,nda3,rbd4 etc

![redundancy](https://cloud.githubusercontent.com/assets/7359272/25173652/de1bf9bc-24ec-11e7-904a-10474ed6be63.jpg)

**Comment by ValWood** [comment]
and on gene pages, this

![split on multiple lines](https://cloud.githubusercontent.com/assets/7359272/25173720/17b6355c-24ed-11e7-8d1e-877707ec0207.jpg)

which could be

directly inhibits cdr2 involved in regulation of cell size
has substrate pol1 involved in
has substrate mod5, pal1, syt22, tea4, rga7

**Comment by kimrutherford** [comment]
> They could appear in only the most specific list in the term ontology summary view as they do on the
> gene pages

I thought that should be happening already.  I'll investigate.

> prp2-1(C387Y) affecting mba1,nab2,naa10,nda3,rbd4 etc

I think that will fix itself once the genotypes and alleles aren't stored redundantly in Chado:
  https://github.com/pombase/pombase-chado/issues/577

> which could be
> directly inhibits cdr2 involved in regulation of cell size
> has substrate pol1 involved in
> has substrate mod5, pal1, syt22, tea4, rga7

That's this bug: #228

**Comment by ValWood** [comment]
yep, sorry if I'm submitting any duplicates. I'm not sure which ones are done and which not because they seem to be subtly different.

Would be good to address the redundancy next .....i'm looking for example pages for my talk  so as I go through finding and tidying the annotations I'll submit tickets...

**Comment by kimrutherford** [comment]
> > They could appear in only the most specific list in the term ontology summary view as they do on the
> > gene pages
>
> I thought that should be happening already.  I'll investigate.

I mis-remembered.  Redundant terms only get removed on the gene pages and only if there are no annotations that have extensions which use that term.

**Comment by ValWood** [comment]
this is high on my list, it will make the annotation easier to consume...

some which look quite messy:


![2 redundancy things](https://cloud.githubusercontent.com/assets/7359272/25446974/385cec9c-2aab-11e7-8ec4-383ff698987a.jpg)

will compact quite a lot...

**Comment by kimrutherford** [comment]
> some which look quite messy:

That's #228.  Ihe problem in your first comment only occurs on term pages whereas #228 can occur anywhere with extensions.

**Comment by kimrutherford** [comment]
I've fixed the redundancy in the summaries on the term pages that you reported in your first comment.
