### ISSUE TITLE
gene annotated to this term page does not appear to load

### ISSUE THREAD

**Issue by ValWood** [pombase/website#266]
at least this one
http://pombase2.aska.gen.nz/term_genes/GO%3A0010389

**Comment by ValWood** [comment]
yep. I think they worked earlier though? maybe not.

Works for phenotypes, maybe that is what I was looking at earlier.

**Comment by kimrutherford** [comment]
Sorry I broke it when fixing #231.  Should be fixed now if you shift-reload.
