### ISSUE TITLE
odd filter behavior

### ISSUE THREAD

**Issue by ValWood** [pombase/website#268]
FYPO:0002029 - abnormal cell division, large and small daughter cells

shows here
	http://pombase2.aska.gen.nz/term/FYPO%3A0000059
when I filter on "localization phenotype"

but I can't see why? I can't see anything in the parentage

**Comment by mah11** [comment]
There is a path in the ontology from FYPO:0002029 to localization, via one output_of link:

 FYPO:0002029 ! abnormal cell division, large and small daughter cells output_of FYPO:0000033 ! abnormal actomyosin contractile ring localization

and
 FYPO:0000033 ! abnormal actomyosin contractile ring localization is_a FYPO:0001337 ! localization phenotype during vegetative growth

The catch is, if these displays don't use output_of links, they also miss out some terms you would want to see, e.g. FYPO:0001369 ! mislocalized actomyosin contractile ring, which is also output_of FYPO:0000033.

**Comment by ValWood** [comment]
Ok its obvious now, its cytokinetic ring. For some reason I was reading "large and small daughter nuclei" which is a  chromsome mis segregation  so I couldn't work it out
