### ISSUE TITLE
trivial order swap

### ISSUE THREAD

**Issue by ValWood** [pombase/website#269]
On the phenotype ontology term pages, can we swap the order of these 2 links around:

Single-allele genotypes associated with this term ...
Genes from single-allele genotypes associated with this term ...

I think most/many people will still want the gene lists by default...and you can already see the alleles/genotypes in the term view page so it makes sense to put the gene list in the more prominent position

In fact, now we have separate boxes for single and multi allele phenotypes on this page
http://pombase2.aska.gen.nz/term/FYPO%3A0001128

perhaps  it would be better to 
a) move these 2 links inside the single allele frame
b) shorten the names accordingly to
i) gene list
ii) gene/allele list
or similar?

**Comment by ValWood** [comment]
inuput required @mah11 @Antonialock

**Comment by mah11** [comment]
no pref

**Comment by ValWood** [comment]
If we made shorter links and moved them, what would sensible labels be?

I don't think we need that "full text" ....

**Comment by kimrutherford** [comment]
> can we swap the order of these 2 links around:

I've done the swapping.  Let me know what you'd like the link text to be.

**Comment by ValWood** [comment]
that's fine. Let's keep as is for now.
