### ISSUE TITLE
Make it clear when filtering is active

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#271]
From https://github.com/pombase/website/issues/249#issuecomment-293709533:

Show the user when any filter is active.  Maybe by showing something like this clearly (maybe bold or a different colour) at the top of the table:
  **Showing 123 of 200 annotations**

**Comment by ValWood** [comment]
that would be nice...

**Comment by kimrutherford** [comment]
> Showing 123 of 200 annotations

I've added a message like that.  As usual you'll probably need to shift-reload.

The message isn't very eye-catching at the moment.  Please let me know what changes you'd like.

**Comment by ValWood** [comment]
Great!

I think I would position it in the middle at the same level as "show details" and the filter
This would be more prominent, and it would have the added advantage of keeping the page "static"

**Comment by kimrutherford** [comment]
> I think I would position it in the middle at the same level as "show details" and the filter

I thought about that but perhaps it's a bit crowded on a small screen.  Is this OK?:

<img width="1222" alt="screenshot 2017-04-27 21 31 34" src="https://cloud.githubusercontent.com/assets/90474/25477267/0bc54440-2b91-11e7-8831-b371959994a9.png">

**Comment by ValWood** [comment]
I see what you mean, it would work fine in the summary view but its a bit crowded in full view.

This is partly a consequence of the damn long evidence code names. Perhaps we could have a set of shorter display names here?

like:
highthroughput nuclotide sequencing assay  - > HTP nucleotide sequencing

Also maybe the filters:term and evidence text could  be above the filters, would that work?

Or do the filters need to be as wide as the drop downs?

**Comment by kimrutherford** [comment]
> Also maybe the filters:term and evidence text could be above the filters, would that work?

Is it better to move the "term" and "evidence" into the dropdown like this?:

<img width="1034" alt="screenshot 2017-04-27 21 47 34" src="https://cloud.githubusercontent.com/assets/90474/25477909/45cb26c6-2b93-11e7-8ea4-53a4ac3802c9.png">

(ie. "No term filter" and "No evidence filter" in the dropdowns)

**Comment by kimrutherford** [comment]
> Showing 123 of 200 annotations

I've just noticed that the numbers are wrong - it's giving the number of terms filtered instead of annotations.  I'll fix that.

**Comment by ValWood** [comment]
I think having the filter label in the drop down is better...

**Comment by mah11** [comment]
I think the current position of "showing x of y annotations" on the live web pages is fine; I would not prefer to move it up and towards the middle as in the examples in the comments here. To me it's actually easier to spot when it has a line to itself. If it needs to me more prominent, perhaps the message line could have a background in a non-egregious highlight color.

> Is it better to move the "term" and "evidence" into the dropdown ...?

I'm not immensely keen on this, because once anything other than "no filter" is selected, you then have to recognize from the selection which is the term filter and which is the evidence filter. And for all it should be obvious from the content, real life is just not that tidy. Things that shouldn't confuse peope do so all the time.

**Comment by ValWood** [comment]
> I'm not immensely keen on this, because once anything other than "no filter" is selected, 

good point...

**Comment by ValWood** [comment]
> I think the current position of "showing x of y annotations" on the live web pages is fine; 

ok happy to leave where it is....it's fine

**Comment by kimrutherford** [comment]
> ok happy to leave where it is....it's fine

OK.

> I've just noticed that the numbers are wrong

That's fixed now.

This is done now I think.
