### ISSUE TITLE
genotype pages do not show all annotations associated with a genotype

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#272]
Apologies if tehre is an existing issue for this but it appears that the genotype pages don't show all phenotypes associated with an allele (maybe it is publication specific?) see wee1-50 and wee1-delta as examples

**Comment by mah11** [comment]
https://github.com/pombase/pombase-chado/issues/624, which follows on from https://github.com/pombase/pombase-chado/issues/577, which is linked to a slew of website tickets, including #220
