### ISSUE TITLE
Create a macromolecular complex file

### ISSUE THREAD

**Issue by ValWood** [pombase/website#273]
We mantain a file of all of the complexes present in fission yeast (experimental  and inferred),
as requested byt the MAss/spec/proteomics people.

This file has the format

acc	
GO_name	
systematic_id	
symbol	
gene_product_description	
evidence_code	
source	
assigned_by

example
GO:0000110	nucleotide-excision repair factor 1 complex	SPBC4F6.15c	swi10	DNA repair endonuclease non-catalytic subunit Swi10	IPI	PMID:8114734	PomBase

It includes everything annotated to 
GO:0032991 macromolecular complex and descendants

but  the following terms are filtered

pombe-embl/supporting_files/Complex_annotation_filters
These are less specific complex grouping terms, for example we filter "ribosome" in favour of 
"small/large ribosomal subunit"

Only represent each complex/gene association once.

I think we  just keep the  one with preference for IDA<IPI>ISS<IEA

I think that's it. I looked at the old jira tickets and I can't think of anything else...

**Comment by ValWood** [comment]
As an aside, the current file does not appear to be updating because it contains the term
"tethring complex"
which was corrected in October
2016-10-28	Updated	TERM	tethering complex

so I don't think it was really generated on 3/22/17.....

**Comment by ValWood** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Complexes/

**Comment by ValWood** [comment]
This can be after public release. We can just put the current file for a while. It does not change a lot.....

**Comment by ValWood** [comment]
Will keep this as public release, just to remind us that the file should be there

**Comment by ValWood** [comment]
Since the old file is linked to we can do this after release...

**Comment by ValWood** [comment]
I can discuss contents with you. If not quick we can punt this for a while longer

**Comment by ValWood** [comment]
there is also a filter for this file.
We remove "grouping" complex terms
/pombe-embl/supporting_files/Complex_annotation_filters

**Comment by kimrutherford** [comment]
I've been ignoring this issue.

> I can discuss contents with you.

I'd appreciate that some time.

**Comment by ValWood** [comment]
Yep, we don't need to discuss on a group call. I can chat to you about this at some point soon....

**Comment by ValWood** [comment]
waiting for feedback from @ValWood

**Comment by ValWood** [comment]
Raising the priority of this as the file is getting a little out of date and people are using the data.

Complexes don't change much but we have annotated new ones in over a year.

I know you wanted to chat about this so we can discuss next time we speak.

**Comment by ValWood** [comment]
ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/

**Comment by kimrutherford** [comment]
> but the following terms are filtered
> pombe-embl/supporting_files/Complex_annotation_filters

Is it OK if I move this list into the main site config file?: pombe-embl/website/pombase_v2_config.json

It's easier to have a single config file for the website data processing.

**Comment by ValWood** [comment]
Absolutely!

**Comment by kimrutherford** [comment]
I've had a go at this.  The new file has less lines (2135 vs 2569) so I'm not sure it's right.  Maybe we do more filtering now?

There are also quite a few differences where the term used for annotation is now more specific.
eg. "U4/U6 x U5 tri-snRNP complex" instead of "spliceosomal tri-snRNP complex"

An example of the new file is in Dropbox:

Dropbox/pombase/temp/Complex_annotation.tsv.gz

**Comment by ValWood** [comment]
The following complexes appear to be in teh old list but not in the new list
Will check the ontology...

GO:0033180	cellular_component	proton-transporting V-type ATPase, V1 domain
GO:0033179	cellular_component	proton-transporting V-type ATPase, V0 domain
GO:0033176	cellular_component	proton-transporting V-type ATPase complex
GO:0045254	cellular_component	pyruvate dehydrogenase complex
GO:0045252	cellular_component	oxoglutarate dehydrogenase complex
GO:0045257	cellular_component	succinate dehydrogenase complex (ubiquinone)
GO:0045261	cellular_component	proton-transporting ATP synthase complex, catalytic core F(1)
GO:0045265	cellular_component	proton-transporting ATP synthase, stator stalk
GO:0045269	cellular_component	proton-transporting ATP synthase, central stalk
GO:0045273	cellular_component	respiratory chain complex II
GO:0045277	cellular_component	respiratory chain complex IV
GO:0045275	cellular_component	respiratory chain complex III
GO:0045283	cellular_component	fumarate reductase complex
GO:0045281	cellular_component	succinate dehydrogenase complex
GO:0090576	cellular_component	RNA polymerase III transcription factor complex
GO:0099023	cellular_component	tethering complex
GO:0045240	cellular_component	dihydrolipoyl dehydrogenase complex
GO:0031105	cellular_component	septin complex
GO:0035976	cellular_component	transcription factor AP-1 complex
GO:0008024	cellular_component	cyclin/CDK positive transcription elongation factor complex
GO:0033061	cellular_component	DNA recombinase mediator complex
GO:0035032	cellular_component	phosphatidylinositol 3-kinase complex, class III
GO:0035097	cellular_component	histone methyltransferase complex
GO:0072588	cellular_component	box H/ACA RNP complex
GO:0035327	cellular_component	transcriptionally active chromatin
GO:0016591	cellular_component	RNA polymerase II, holoenzyme
GO:0031371	cellular_component	ubiquitin conjugating enzyme complex
GO:0070993	cellular_component	translation preinitiation complex
GO:0031465	cellular_component	Cul4B-RING E3 ubiquitin ligase complex
GO:0000133	cellular_component	polarisome
GO:0005753	cellular_component	mitochondrial proton-transporting ATP synthase complex
GO:1990077	cellular_component	primosome complex
GO:0005947	cellular_component	mitochondrial alpha-ketoglutarate dehydrogenase complex
GO:0030897	cellular_component	HOPS complex
GO:0030875	cellular_component	rDNA protrusion
GO:0005834	cellular_component	heterotrimeric G-protein complex
GO:0005839	cellular_component	proteasome core complex
GO:0005663	cellular_component	DNA replication factor C complex
GO:0070775	cellular_component	H3 histone acetyltransferase complex
GO:0031201	cellular_component	SNARE complex
GO:0031205	cellular_component	endoplasmic reticulum Sec complex
GO:0030689	cellular_component	Noc complex
GO:0042575	cellular_component	DNA polymerase complex
GO:1990251	cellular_component	Mmi1 nuclear focus
GO:1990574	cellular_component	meiotic spindle astral microtubule
GO:0030062	cellular_component	mitochondrial tricarboxylic acid cycle enzyme complex
GO:0032797	cellular_component	SMN complex
GO:0036409	cellular_component	histone H3-K14 acetyltransferase complex
GO:0036452	cellular_component	ESCRT complex
GO:0061673	cellular_component	mitotic spindle astral microtubule
GO:0061638	cellular_component	CENP-A containing chromatin
GO:0022624	cellular_component	proteasome accessory complex
GO:0036387	cellular_component	pre-replicative complex
GO:1990707	cellular_component	nuclear subtelomeric heterochromatin
GO:0071256	cellular_component	translocon complex
GO:0000275	cellular_component	mitochondrial proton-transporting ATP synthase complex, catalytic core F(1)
GO:0000235	cellular_component	astral microtubule
GO:0097526	cellular_component	spliceosomal tri-snRNP complex
GO:0097525	cellular_component	spliceosomal snRNP complex
GO:0048500	cellular_component	signal recognition particle
GO:1904949	cellular_component	ATPase complex
GO:0030286	cellular_component	dynein complex
GO:0000939	cellular_component	condensed chromosome inner kinetochore
GO:0000940	cellular_component	condensed chromosome outer kinetochore
GO:0000798	cellular_component	nuclear cohesin complex
GO:0032117	cellular_component	horsetail-astral microtubule array
GO:0034518	cellular_component	RNA cap binding complex
GO:0008278	cellular_component	cohesin complex

**Comment by ValWood** [comment]
The ones I spot-checked seem to be protein containing-complexes?

**Comment by kimrutherford** [comment]
Do you have an an example of a missing annotation?

**Comment by ValWood** [comment]
All these:
https://www.pombase.org/term/GO:0033176

these 3 subcomplexes
https://www.pombase.org/term/GO:0098803

all these 3 had a recent name change, maybe that's somthing to do with it
GO:0045273	cellular_component	respiratory chain complex II
GO:0045277	cellular_component	respiratory chain complex IV
GO:0045275	cellular_component	respiratory chain complex III

**Comment by ValWood** [comment]
https://www.pombase.org/term/GO:0033176
had a name change too:
GO:0033180	cellular_component	proton-transporting V-type ATPase, V1 domain
GO:0033179	cellular_component	proton-transporting V-type ATPase, V0 domain
GO:0033176	cellular_component	proton-transporting V-type ATPase complex

**Comment by kimrutherford** [comment]
> All these:
> https://www.pombase.org/term/GO:0033176

I can see those annotations in the file in Dropbox and in the nightly file ftp://ftp.pombase.org/nightly_update/misc/Complex_annotation.tsv

```
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPAC16E8.07c    vph1    V-type ATPase V0 subunit a (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPAC17A2.03c    vma6    V-type ATPase V0 subunit d (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPAC1B3.14      vma3    V-type ATPase V0 subunit c (proteolipid subunit)        ISO     PMID:14735354   PomBase
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPAC2C4.13      vma16   V-type ATPase V0 subunit c''(predicted) ISO     GO_REF:0000024  PomBase
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPAC732.01      vma11   V-type ATPase V0 proteolipid subunit (predicted)        ISO     GO_REF:0000024  PomBase
GO:0000220      vacuolar proton-transporting V-type ATPase, V0 domain   SPBC1685.16     vma9    V-type ATPase V0 subunit e (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPAC11E3.07     vma4    V-type ATPase V1 subunit E (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPAC343.05      vma1    V-type ATPase V1 domain, subunit A      ISO     PMID:14735354   PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPAC637.05c     vma2    V-type ATPase V1 subunit B      ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPAC7D4.10      vma13   V-type ATPase V1 subunit H (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPAPB2B4.05     vma5    V-type ATPase V1 subunit C (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPBC1289.05c    vma10   V-type ATPase V1 domain subunit G (predicted)   ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPBC3B9.18c     vma7    V-type ATPase V1 subunit F (predicted)  ISO     GO_REF:0000024  PomBase
GO:0000221      vacuolar proton-transporting V-type ATPase, V1 domain   SPCC965.03      vma8    V-type ATPase V1 subunit D (predicted)  ISO     GO_REF:0000024  PomBase
```

**Comment by ValWood** [comment]
Hmm, maybe I got old and new mixed up.

I'll try a different way, this term isn't in the file:
1,3-beta-D-glucan synthase complex

**Comment by ValWood** [comment]
GO:0005754 | mitochondrial proton-transporting ATP synthase, catalytic core

**Comment by ValWood** [comment]
nuclear nucleosome (GO:0000788)

**Comment by ValWood** [comment]
mRNA cleavage and polyadenylation specificity factor complex (GO:0005847)

**Comment by ValWood** [comment]
heterotrimeric G-protein complex (GO:0005834)

**Comment by ValWood** [comment]
I don't see them  in this config?

but I cans svn update right now... so maybe you put them here recently?

**Comment by kimrutherford** [comment]
> but I cans svn update right now... so maybe you put them here recently?

I committed the changes on Friday about 2pm.

The file with the changes is here:
ftp://ftp.pombase.org/nightly_update/pombe-embl/website/pombase_v2_config.json

**Comment by ValWood** [comment]
OK, It seems that I had not been maintaining the filter very well to keep pace with ontology and annotation.

This will be easier now because I can periodically check the proteins in the file against my expected.
 
You can implement the new file generation pipeline, as everything seems to be working correctly,  and I can weed out the filters a bit more after the next update.

**Comment by kimrutherford** [comment]
> You can implement the new file generation pipeline, as everything seems to be working correctly

I've changed the script to add the complex file to SVN and to the FTP site each night, starting tomorrow.

**Comment by kimrutherford** [comment]
I've just manually updated the file on the FTP site.  From tomorrow it will be automatic.

ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv

**Comment by kimrutherford** [comment]
I noticed that the PMIDs and sources sometime had duplicates.  I've fixed that and made sure they are in a consistent sort order (eg. always "PomBase, UniProt" rather than "UniProt, PomBase").

**Comment by ValWood** [comment]
From the website I get

ftp://ftp.pombase.org/pombe/annotations/GO_complexes/

This site can’t be reached

**Comment by ValWood** [comment]
link from this page
https://www.pombase.org/downloads/go-annotations

**Comment by ValWood** [comment]
can announce to pombelist when links fixed.

I will continue to extend inventory.
https://github.com/pombase/curation/issues/2166

**Comment by kimrutherford** [comment]
> link from this page
> https://www.pombase.org/downloads/go-annotations

Thanks.  I've checked in a fix which should be visible in the morning.

**Comment by kimrutherford** [comment]
> I've checked in a fix which should be visible in the morning.

That's fixed now.

**Comment by ValWood** [comment]
OK will announce later, or tomorrow....

**Comment by ValWood** [comment]
Announced to pombelist 29/08/2018
