### ISSUE TITLE
funny lines to right of (cell) phenotype section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#275]
![funny lines](https://cloud.githubusercontent.com/assets/7359272/25335776/59d72c86-28ec-11e7-995b-3adc77af78ec.jpg)

**Comment by kimrutherford** [comment]
Which browser is that?  I haven't seen that before.

**Comment by ValWood** [comment]
chrome. 
I can see when it happens now.
go to cdc2, scroll down to phenotypes. Looks normal.

Then  resize your browser to make the page narrower... then scroll right....

**Comment by kimrutherford** [comment]
I get some display oddness when I do that but not like your screenshot.  I'll work on that.

**Comment by ValWood** [comment]
oddly I only see it for cdc2 cellular phenotype.
I was just looking at ral3 and that was fine?

**Comment by ValWood** [comment]
duplicate

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/227
