### ISSUE TITLE
filtring GO

### ISSUE THREAD

**Issue by ValWood** [pombase/website#276]
I don't see

/GO="aspect=F; term=histone deacetylase activity; GOid=GO:0004407; evidence=IDA; db_xref=PMID:11884604; date=20070718"
/GO="aspect=F; term=histone deacetylase activity; GOid=GO:0004407; evidence=IMP; db_xref=PMID:11884604; date=20041214"

in full view, only:

/GO="aspect=F; term=histone deacetylase activity (H3-K14 specific); GOid=GO:0031078; evidence=IMP; db_xref=PMID:11884604; date=20041214"

This might be becaue they are same paper? If so this is OK, but we should show 
/GO="aspect=F; term=histone deacetylase activity; GOid=GO:0004407; evidence=IDA; db_xref=PMID:11884604; date=20070718"
in full view because it is different evidence code...

**Comment by kimrutherford** [comment]
Which gene was that?

**Comment by ValWood** [comment]
ignore me, I'm talking rubbish, its the correct behaviour.

(it was sir2)
