### ISSUE TITLE
directly inhibits /directly activates, extension range relations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#277]
For compact display, can we treat these  (directly_negatively_regulates and directly_positively_regulates) as a more specific form of has substrate ?

This would hide has_substrate wee1 here in the summary view

![redundancy](https://cloud.githubusercontent.com/assets/7359272/25447103/c69c2478-2aab-11e7-9bd2-6d674dae83f1.jpg)

This might be an issue because  they are not parent child in RO. Can live with it if so...

**Comment by ValWood** [comment]
Will look at this later, non urgent...

**Comment by ValWood** [comment]
GO now has regulation of activity of relation

Actions
i) Request +/- ve of the 'new ' relation 
ii) Make a way of swapping our use of whatever relation is hidden behind "directly inhibits" and "directly activate" to the new relations. 
iii ) Continue to display  as "directly activates" or "directly inhibits".

**Comment by mah11** [comment]
I think what you really want to capture would need one of those "chained relations" to connect has_direct_input with regulates_activity_of. We would have to ask which way round - has_direct_input_o_regulates_activity_of or regulates_activity_of_o_has_direct_input.

**Comment by ValWood** [comment]
OK! I've been sweeping this under the carpet, will deal with it soon.

https://github.com/geneontology/annotation_extensions/blob/master/doc/regulates_activity_of.md

One thing, when the GO file is  next submitted, we will need to  replace these with has_substrate
until we figure out how to  has_substrate + thingamajiggy_o_palaver

**Comment by ValWood** [comment]
> has_direct_input_o_regulates_activity_of or regulates_activity_of_o_has_direct_input

Did you say these relationships existed in RO?
If so where can I see them, I forgot?

**Comment by ValWood** [comment]
ignore, I see see next comment...

**Comment by ValWood** [comment]
I have sent an e-mail to Chris &Co to try to identify the correct relationship.

**Comment by ValWood** [comment]
Not strictly "low priority" but don't want to look at it until after matrix and grant

**Comment by kimrutherford** [comment]
See also: https://github.com/pombase/website/issues/930#issuecomment-122144379

**Comment by ValWood** [comment]
This one is out of date because we shouldn't be curating in this way. The "directly inhibits " will be fixed by GO-CAMs.
