### ISSUE TITLE
"occurs_at"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#280]
if we use this as an extension of a function term, it should display last

**Comment by kimrutherford** [comment]
Currently the order of extensions is the same for all annotation types:

    directly_positively_regulates
    directly_negatively_regulates
    has_direct_input
    has_input
    has_regulation_target
    binds
    involved_in
    occurs_at
    occurs_in
    added_by
    added_during
    present_during
    in_presence_of
    removed_by
    removed_during
    absent_during
    has_expressivity
    has_penetrance

Do you need a special case for function annotations?

**Comment by ValWood** [comment]
that isnt happening here:

	protein serine/threonine kinase activity
directly inhibits cdr2  **at cell cortex** involved in signal transduction involved in G2 cell size control checkpoint involved in positive regulation of protein localization to cell cortex

http://pombase2.aska.gen.nz/gene/SPAC2F7.03c

I have deleted that "occurs at" this morning, its unecessary, but it didn't appear where I expected...

**Comment by kimrutherford** [comment]
Oh dear.  I'll fix that.

**Comment by kimrutherford** [comment]
That confused me.  The code is working OK but the configuration might need to be changed.  The confusion is that the extension is displayed with "involved in" but the actual extension relation is "part_of".  Here is how the term looks in Chado:

protein serine/threonine kinase activity
 [directly_negatively_regulates] SPAC57A10.02
 [part_of] signal transduction involved in G2 cell size control checkpoint
 [part_of] positive regulation of protein localization to cell cortex
 [occurs_at] cell cortex

In the web site "part_of" is configured to be displayed as "involved in".

Currently "part_of" isn't in the extension ordering config in my comment above.  I guess it makes sense to put it just before or after "involved_in" in that list.  Shall I make that change?

**Comment by ValWood** [comment]
Oh yes please. You can just change involved in to part_of, or add it...

**Comment by kimrutherford** [comment]
I've updated the configuration and regenerated the web site data.  The next time you see part_of is should be in the right place.
