### ISSUE TITLE
Loss of substrate on a MF term

### ISSUE THREAD

**Issue by ValWood** [pombase/website#281]
https://github.com/pombase/website/issues/228 changes worked nicely, but might be responsible for this annotation

![this annotation](https://cloud.githubusercontent.com/assets/7359272/25477200/9f1c67d0-2b34-11e7-8835-123622317a8f.jpg)

appearing as

involved in negative regulation of protein localization to plasma membrane

(substrate lost)

**Comment by ValWood** [comment]
It should be identical to the term above (from a different paper)

has substrate pom1  involved in negative regulation of protein localization to plasma membrane

**Comment by ValWood** [comment]
My "ideally by end of April milestone is unrealistic" please just read as "earliers".

These  are the ones I need for slides, screenshots, screencasts (but I can remake them at the end, I'm still in the process of refining the annotation and deciding on the examples, and what to show...so it isn't hugely urgent...)

**Comment by kimrutherford** [comment]
> has substrate pom1 involved in negative regulation of protein localization to plasma membrane

I'm confused - that's the annotation I see here, in the summary and details view: http://pombase2.bioinformatics.nz/gene/SPAC2F7.03c

**Comment by mah11** [comment]
I think I get it - Val is talking about the pom1 GO:0004674 annotation from PMID:21703453 (Hachet et al. 2011), not the one from PMID:26150232 (Hersch et al. 2015). For PMID:21703453 two extensions, 'has_substrate pom1' and 'involved in neg. reg. loc. to PM', appear on separate lines.

That's a curation issue, not a website code issue, though - Val's screenshot from the Canto session shows that the extensions are separated by a pipe. To get a single line of annotation with 'has_substrate pom1 and involved in yada' as one extension, change it to a comma or delete and re-add with the clever interface.

**Comment by ValWood** [comment]
doh!
