### ISSUE TITLE
no slim term on SPBC8D2.16

### ISSUE THREAD

**Issue by ValWood** [pombase/website#283]
Maybe because it is annotated to the slim term itself?

(I'm actually going to delete this annotation, this should be unknown, rather than an ISS based on a chromosome segregation phenotype, not really enough to infer chromosome segregation, could be indirect)

**Comment by ValWood** [comment]
I added chromosome segregation back for this is CENP-32

**Comment by kimrutherford** [comment]
> Maybe because it is annotated to the slim term itself?

Yep, that was it!  It's fixed now.
