### ISSUE TITLE
Duplicate genotypes with different backgrounds

### ISSUE THREAD

**Issue by ValWood** [pombase/website#284]
![duplication](https://cloud.githubusercontent.com/assets/7359272/25489967/5c2300fe-2b63-11e7-87a0-75809c38135a.jpg)

**Comment by kimrutherford** [comment]
That's annoying.  On the plus side they all seem to come from the Canto loading so it should be an easy fix.

**Comment by kimrutherford** [comment]
It's less bad than I thought.  Although it's not obvious, those three genotypes really are different - they have different backgrounds.  As a temporary fix I've added the background to the details you see when you mouse-over a genotype.

How should we display this?  The easiest for me is something like:

    cdc13+,  cdc13+ (background cdc2+),  cdc13 (background cdc2-33), ...

**Comment by ValWood** [comment]
We should group the  irrespective of background, because the background should not really affect the outcome,  as such, and if it does it should be part of the genotype.

I think people need to see all the phenotypes for a genotype together, regardless of background.

**Comment by kimrutherford** [comment]
> We should group the irrespective of background

If we show:

    cdc13+

instead of:

    cdc13+,  cdc13+ (background cdc2+),  cdc13 (background cdc2-33)

which of the three genotype should "cdc13+" be a link to?

**Comment by ValWood** [comment]
Oh bummer is background part of the genotype...i did not realise that.

Hmm, not sure @mah11  what should we do here?

**Comment by kimrutherford** [comment]
> Oh bummer is background part of the genotype

Yep, each of the links goes to a separate page which shows only the annotations for that allele and background combination.

**Comment by mah11** [comment]
Val and I had a quick chat, and decided

- For gene pages and FYPO term pages, we'll just stick with the mouseover details unless we get complaints.

- For genotype pages, we want to group all genotypes with the same "foreground" allele(s) on one page, regardless of background, but list the annotations for each genotype separately. The display could be modeled on the ontology term page arrangement, with a list of phenotype annotations for each combination of the allele(s) of interest + background.

Let me know if it would help to mock up what a genotype page might look like, or if I haven't explained well enough.

**Comment by ValWood** [comment]
here is an example
http://preview.pombase.org/genotype/e70a1374f7a8719d-genotype-3

Gene	Allele	Type	Expression
nda3	nda3-KM311(unknown)	unknown	Not assayed

http://preview.pombase.org/genotype/1275ee66e3ff4666-genotype-2
Gene	Allele	Type	Expression
nda3	nda3-KM311(unknown)	unknown

Expression here is blank...not sure why, maybe these are from Artemis but they seem to be newer phenotypes

Anyway these should group together.

We also need a page which groups a particular genotype regardless of background...
(can discuss this on Thursday)

**Comment by mah11** [comment]
On today's call we:

- revisited and confirmed our decision that we want one genotype page to group all genotypes that share the same "foreground" alleles of interest;

- decided that if it's technically feasible, annotations should all be in one table (not separate tables per genotype), since we'll still have the mouseover to show the background for each annotation;

- did not discuss how to display the different genotypes with their respetive backgrounds, but can come back to that point if you want mockups or other input.

**Comment by ValWood** [comment]
de prioritise this if more than a few hours

**Comment by kimrutherford** [comment]
> de prioritise this if more than a few hours

Yep, I think it's more than a few hours.  I'd guess it would take a day (+/- half a day).  It's a bit fiddly because what's in Chado isn't how you'd like it to be displayed.

**Comment by ValWood** [comment]
https://www.pombase.org/genotype/0c53b7a36b2fe15f-genotype-1
https://www.pombase.org/genotype/4d4822dbe566aaac-genotype-9

We chatted about this and the preferred solution is to
a) integrate alleles with different background o summary view
b) make background visible on mouseover for  specific annotations on gene pages (as now). But this will be a bit more complicated because the background will need to remembered for the pop-up
c) on the genotype page show the background in a column. BUT only have the column for genotypes which have a background.

**Comment by ValWood** [comment]
@kimrutherford  do you know what is required to implement this or do you have outstanding questions?

If you do, please add and I will add it to the call list.

**Comment by kimrutherford** [comment]
> @kimrutherford do you know what is required to implement this or do you have outstanding questions?

I don't have any questions.  I'm still thinking about how to implement it.  :-)

**Comment by kimrutherford** [comment]
I've made some progress fixing this problem.  In my local version the genotypes that are the same except for background are combined on one page.  Currently the backgrounds aren't displayed.  That's my next task.

As an experiment, the URL is now very sensible for deletions:
  http://pombase2-kmr.bioinformatics.nz/genotype/any1delta
(That's my desktop proxied via oliver1 so it's slow and will only work until 1pm each day)

Unfortunately complicated genotypes have long unpleasant URLs:
  http://localhost:4200/genotype/cdc2-V67-C67V-amino_acid_mutation-expression-not_assayed__cdc25-22-C532Y-amino_acid_mutation-expression-not_assayed

I'll work on that.

**Comment by kimrutherford** [comment]
> We chatted about this and the preferred solution is to
> a) integrate alleles with different background on summary view

Just to check: you mean put all the genotypes whatever their background on the same genotype page?

> b) make background visible on mouseover for specific annotations on gene pages (as now).

That now works again in my local version.  It shows the background in the popup but if you click the link you go to the new genotype page that isn't background specific.

> c) on the genotype page show the background in a column. BUT only have the column for
> genotypes which have a background.

I've tried that locally.  Having a separate column doesn't look great if there are many genotypes but only a few have backgrounds - there's a lot of whitespace.

We could add a filter-by-background if it would help.

In this example there are a few backgrounds but you need to scroll down:

![genotype-background-test-1](https://user-images.githubusercontent.com/90474/40339801-21ec2334-5dd0-11e8-8ec8-aadab7bc08c8.png)

Could we put the background under or beside the genotype like this instead?:

![genotype-background-test-2](https://user-images.githubusercontent.com/90474/40339876-8091d62c-5dd0-11e8-8f24-780b45a8ac42.png)

another example:

![genotype-background-test-3](https://user-images.githubusercontent.com/90474/40340118-88e54ba0-5dd1-11e8-917c-b325d2390ed6.png)

**Comment by kimrutherford** [comment]
> I've tried that locally. Having a separate column doesn't look great if there are many genotypes
> but only a few have backgrounds - there's a lot of whitespace.

Sorry, I got confused.  :-)  Those screenshots are from a gene page where we weren't going to have a background column.  Having an extra column is not big a problem on the genotype pages.  I've changed my local copy to only add the background column on the genotype pages.

**Comment by ValWood** [comment]
>Just to check: you mean put all the genotypes whatever their background on the same genotype page?

yes this would totally make sense for users.
We *could* have a "filter by background" option genotype pages. This still bothers me though, because background curation is often an afterthought, or  totally omitted, it is almost never consistently annotated.....

**Comment by kimrutherford** [comment]
Due to the load failing last night due to network issues I've accelerated the schedule and the genotype background changes are now in pombase-dev, eg.
  http://pombase-dev.bioinformatics.nz/genotype/cdc25-22-C532Y-amino_acid_mutation-expression-not_assayed__pwis2-wis2%2B-other-expression-not_assayed__wee1-50-G850E-amino_acid_mutation-expression-not_assayed__win1-1-unknown-unknown-expression-not_assayed

(Sorry about the long URL)

Currently on the gene pages the background appears under the genotype name and also in the popup.  Which do you prefer?  Here's an example of both:

![genotype-background-test-4](https://user-images.githubusercontent.com/90474/40350073-b2cb420a-5dfc-11e8-8959-cd18d9062f6d.png)

**Comment by kimrutherford** [comment]
Due to a slight screw up and an emergency bug fix, the main site has now been updated.  You should now find that there's one page per genotype, ignoring backgrounds.

Please let me know if you spot any weirdness.
