### ISSUE TITLE
Better front page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#285]
Maybe we should tidy the front page a bit before the conference.  Maybe a sentence or two about the beta status of the site?

It's probably good to make it clear that it isn't the real PomBase (yet).

**Comment by ValWood** [comment]
Good plan. 

Something about the beta status.
A list of new pages and features maybe?
and  a list of the "big things" that are coming up over the next few months...


We can also  change to our favourite example pages. I'll make a  list of these.

- [ ]  add link to FAQ

**Comment by ValWood** [comment]
@mah11  could you edit this blurb?

This beta version of the PomBase website is under development, but has many new features including:
* Nightly updates
* Publication pages
* Genotype pages
* Improved gene pages with reduced redundancy in "summary displays" 
* Improved ontology term pages showing annotated descendant terms, links to ancestor terms

New features over the coming months will include:
* Improved query tool
* JBrowse   genome browser
* Protein Viewer
* Network viewer

**Comment by mah11** [comment]
quick stab at it:

Welcome to the new PomBase website. Although it's still under development, nightly data updates are working and several new features are now available:

- Publication pages
- Genotype pages
- Improved gene pages with reduced redundancy in annotation summary views
- Improved ontology term pages showing annotated descendant terms and links to ancestor terms

Over the next few months we plan to add:

- Improved query interface
- JBrowse genome browser
- Protein feature viewer
- Network viewer

Please tell us what you think of the new look and function of the PomBase pages, and what you'd most like to see next. [helpdesk mail linky]

**Comment by ValWood** [comment]
much better...

**Comment by kimrutherford** [comment]
I've added that text but I haven't done any formatting.  Let me know if you have any suggestions.

**Comment by ValWood** [comment]
I think it's fine just needs a little space top and left.

Can we change/update the examples

genes:
cdc2
pom1
wee1
sty1

Example GO terms
DNA replication (GO slim process)
mitotic sister chromatid segregation (GO slim process)
tRNA metabolic process (GO slim process)

Example phenotype terms
abnormal cytokinesis
abnormal mitotic cell cycle
branched elongated multinucleate aseptate vegetative cell

The example papers should be from community curation
We should use:
Nurse lab
Yanagida lab(s) 
Sophie Martin
Paul Russell
Espenshade
Gould
Takegawa
Toda

Will dig out PMIDs, please add any suggestions.

@mah11  @Antonialock  please add examples genes/terms which look particularly good.
Can delete some of mine if too many.....

**Comment by ValWood** [comment]
Should we grey out the "query builder"?

**Comment by ValWood** [comment]
Can add a "GO slim page" link to this front page

**Comment by kimrutherford** [comment]
> I think it's fine just needs a little space top and left.

I've done that.  And changed the example genes and terms.  You'll need to shift reload.

If you'd like to make changes yourself, the page is here:
  https://github.com/pombase/website/blob/master/frontend/src/app/front/front.component.html

But I'm happy to do changes.

> Should we grey out the "query builder"?

I've removed it for now.

> Can add a "GO slim page" link to this front page

Under the docs section?

**Comment by ValWood** [comment]
I made some changes, when do they show up ;)

**Comment by kimrutherford** [comment]
> I made some changes, when do they show up ;)

Should be there now if you reload.

**Comment by ValWood** [comment]
- [x]  add slim & stats
- [ ] add rotating images @Antonialock 
- [ ] remove dead links

**Comment by kimrutherford** [comment]
Thanks for the images Antonia.  I've added them to the front page.

I've moved the Docs section to the left edge because in a smaller window it was wrapping onto a new row which made it hard to spot.

**Comment by mah11** [comment]
I have a mad little idea: since the lists of example pages are only on the front page because they're effectively the news, let's change the headers from "example x page" to make them more interesting. Maybe:

- Improved gene pages
- New ontology term pages
-- GO terms
-- phenotypes
- New publication pages

**Comment by ValWood** [comment]
That works, go for it!

**Comment by mah11** [comment]
OK, headers edited (I think Kim will have to push a button for it to be visible)

**Comment by kimrutherford** [comment]
> OK, headers edited (I think Kim will have to push a button for it to be visible)

It's re-released now.  Thanks, I think those headers are an improvement.

**Comment by kimrutherford** [comment]
> add link to FAQ

I've added that to the Docs section.

> remove dead links

I've made a separate issue for that since this one is a bit long.

Any other front page fixes?

**Comment by ValWood** [comment]
OK will close this, any updates in new ticket,

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/318
