### ISSUE TITLE
Genotype pages don't need the single/multi-allele label

### ISSUE THREAD

**Issue by mah11** [pombase/website#286]
The labels "Single allele phenotype" and "Multi allele phenotype" are superfluous on the genotype pages. Each genotype has either one allele of interest or more than one, and therefore no genotype page will have both single- and multi-allele phenotypes. (Note that this is disregarding background, even after the lumping described in https://github.com/pombase/website/issues/284#issuecomment-297967038).

tangential note: in "Multi-allele phenotype", "Multi-allele" should be hyphenated, because "multi" is not a word on its own; it's a prefix.

**Comment by kimrutherford** [comment]
I've changed it to "Annotations for this genotype" for now.  Might need changing when we do https://github.com/pombase/website/issues/284#issuecomment-297967038

**Comment by kimrutherford** [comment]
> "Multi-allele phenotype", "Multi-allele" should be hyphenated

I've changed that in the config and re-released.
