### ISSUE TITLE
extension missing on gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#287]
GO:1904776	regulation of protein localization to cell cortex IDA	Hersch M et al. (2015)

has extension 
pom1 which is not displayed. However, it must have been in this run

because it is on the publication page
http://pombase2.aska.gen.nz/reference/PMID%3A26150232

**Comment by kimrutherford** [comment]
It's there now I think.

**Comment by ValWood** [comment]
yes, I think I was misreading the publication page, it wasn't there either ;)

all good now...
