### ISSUE TITLE
Same allele treated differently

### ISSUE THREAD

**Issue by ValWood** [pombase/website#288]

**Comment by ValWood** [comment]
![background](https://cloud.githubusercontent.com/assets/7359272/25555353/476f56ba-2cdc-11e7-9d67-30b3b8140908.jpg)


here I wondered what the background could be to make these different, but it turns out there isn't one.

The only difference I see is that 

prp2-1(unknown)
prp2-1(G1160A)

so it seems that the web pages fill in the description for an unknown earlier allele, but still treat as a different genotype.

@mah11  the PMID:11350031  ones should be pipe separated I think?

**Comment by kimrutherford** [comment]
Are these the annotations that you're talking about?:

> prp2-1(C387Y)  affecting mba1 , ade2 , nab2 , naa10 , rbd4 , taf111 , rpl702 , rad24 , cdc2 , rpl701 , nda3
> prp2-1(C387Y)  affecting cdc2
> prp2-1(C387Y)  affecting rpl3002 , tbp1

The middle one has a different expression for the allele ("Not specified" vs "Not assayed") from line 1 and 3 here so that makes sense.  Do we need to show the expression?

I think the first and last should be merged into the same summary line.  I think they are separate because they have different extensions which confuses the code.  There is a hidden "has expressivity high" on the rpl3002 and tbp1 annotations that you can see only in the detailed view.  The code is removing "has expressivity" from the summary but doing it at the wrong time so the ordering of the summary (and hence merging of line) isn't working here.  I think I can fix that.

(If the middle genotype with the different expression wasn't there the first and last of those three summary rows would have ended up beside each other after sorting and the lines would have merged.  Which is probably why we haven't seen other cases like this.)

**Comment by ValWood** [comment]
"Not assayed" and "not specified" sound the same.

In canto we only have
![default](https://cloud.githubusercontent.com/assets/7359272/25555661/709c6156-2ce4-11e7-8d85-936cff7aeebb.jpg)
and I have  used "not specified" for "not assayed"

**Comment by kimrutherford** [comment]
There are lots of "not specified" expression levels the PHAF files.

**Comment by ValWood** [comment]
> Do we need to show the expression?

only in the pop up, and we already do...

**Comment by ValWood** [comment]
I wonder if we used "not assayed" earlier, and then switched...rings a bell... can you tell by dates?

**Comment by kimrutherford** [comment]
> can you tell by dates?

The most recent annotations in the PHAF files are from 2016-02-24.

**Comment by mah11** [comment]
> I wonder if we used "not assayed" earlier, and then switched

We did switch about a year and a half ago - https://github.com/pombase/canto/issues/971 - but I don't think we retrofitted any existing extensions in Canto or in PHAFs.

The simplest thing would be for the loader to treat "not assayed" and "not specified" as synonymous for allele expression.

> @mah11 the PMID:11350031 ones should be pipe separated I think?

They appear on separate lines in the full-detail view. We're not using pipes in the PomBase web page displays.

I can see no further reason for this to be assigned to me.

**Comment by ValWood** [comment]
Assigning back to Kim, but I am still confused why some of these are comma separated, and some have and.... surely they should all be comma?
The phenotype is 
decreased mRNA splicing, via spliceosome

I'll open a curation tracker ticket about this...

**Comment by mah11** [comment]
don't bother; found comma-separated extensions and fixed 'em (not in the paper you mentioned above; PMID:9917066)

**Comment by ValWood** [comment]
See whether rendering properly

**Comment by ValWood** [comment]
The difference between these  is still "not assayed" vs "not spec

![not](https://cloud.githubusercontent.com/assets/7359272/25701965/aa9e21f6-30c6-11e7-86de-c4f6b7167243.jpg)
ified"

**Comment by ValWood** [comment]
The other issue (comma vs and) is fixed

**Comment by kimrutherford** [comment]
> The simplest thing would be for the loader to treat "not assayed" and "not specified" as synonymous for allele expression.

> The difference between these is still "not assayed" vs "not specified"

I've changed the loader so the "Not specified" gets stored as "Not assayed".  It should be fixed by Saturday morning.

**Comment by kimrutherford** [comment]
> I've changed the loader so the "Not specified" gets stored as "Not assayed". It should be fixed
> by Saturday morning.

Sorry, I should have checked that the code actually work before releasing.  I introduced an error in the phenotype loading code so I caused the load to fail.  It's now fixed and the load should include the fix in the morning.

(I thought "one line change - what could go wrong?" and it went wrong)

**Comment by ValWood** [comment]
Nice!

![yay](https://cloud.githubusercontent.com/assets/7359272/25779153/676480a2-3309-11e7-9001-7e98e3a1fd37.jpg)
