### ISSUE TITLE
regenerate static GO slim page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#289]
http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

(I don't think I opened a ticket for this yet?)

So basically its just each GO slim term and  the total number with a  link to the ontology term page.
It might be good to add this for demoing, and so we don't need to link this to the old site, which will link to the old ontology pages.

There are 2 additional links at the bottom.
Proteins with a biological process annotation not covered by the slim (gene count: 214)
Proteins with no GO slim or biological process annotation (gene count: 795)

(Not that in the current release the 214 number is overinflated because the annotations to "mitochondrial translation" are in here. I think this number is now down to around 115....

**Comment by kimrutherford** [comment]
It should be straightforward to generate the table automatically and embed it in Markdown docs page.

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/278

To tie up the slims, once this page is in place we should link to it from the slim section of the gene pages.
We should change the help link to go directly to the documentation.

**Comment by kimrutherford** [comment]
I've started copying the PomBase v1 GO slim docs page:
  http://pombase2.bioinformatics.nz/browse-curation/fission-yeast-go-slim-terms

It's only a start - most links don't work and the gene count column is missing.

**Comment by ValWood** [comment]
URL doesn't work for me...

**Comment by kimrutherford** [comment]
> URL doesn't work for me...

Sorry, should be fixed now.

**Comment by ValWood** [comment]
Looking good so far.

good enough to link to from here : "Biological process overview" in process section

**Comment by kimrutherford** [comment]
> good enough to link to from here : "Biological process overview" in process section

I've added the link.

**Comment by ValWood** [comment]
This is the actual GO slim page, not just "help"
("Help" is linked from the GO slim itself)

I think we should hyperlink the phrase "Biological process overview (GO slim)"
to the slim.  
and not say "help" here
(we can add various help links later).

**Comment by ValWood** [comment]
- [ ] small fix for slim, add a space between the GO  ID and the esyN links

**Comment by kimrutherford** [comment]
> I think we should hyperlink the phrase "Biological process overview (GO slim)"

Done.

Is there anything else to do to the slim page?

**Comment by ValWood** [comment]
all in
https://github.com/pombase/website/issues/316
