### ISSUE TITLE
retrieve sequence with flanking regions but without introns

### ISSUE THREAD

**Issue by mah11** [pombase/website#29]
Add another option for customizing squence downloads: include flanking regions of user-specified length, and omit introns.

**Comment by ValWood** [comment]
Because the old site will  still be available, and the sequence features will not change, we can, for a while refer users to the old site for  individual sequence download from the gene pages, and implement this later.

**Comment by ValWood** [comment]
transferred to
https://github.com/pombase/website/issues/21
which covers "sequence download from the query builder"
