### ISSUE TITLE
involved in, involved in

### ISSUE THREAD

**Issue by ValWood** [pombase/website#292]
I was sure I opened a ticket about this last week, but apparently not....

So sometimes we link a MF term to 2 processes.

When we link functions to processes, or processes to processes, we use the relationship part_of.

Becasue when we first began doing this, we were only connecting only functions to processes

MF involved in process sounds fine.

Nowe we have things like

MF involved in process involved in process

For example

pom1
protein serine/threonine kinase activity
directly inhibits cdr2  involved in negative regulation of protein localization to cell tip involved in signal transduction involved in G2 cell size control checkpoint

which means pom1 protein kinase inhibits cdr2.
it is  involved in negative regulation of protein localization to cell tip  as part of  signal transduction involved in G2 cell size control checkpoint

So we only join when one of the processes is part of the other and GO will not let us precompose.

I wonder if, for the display label for the  "involved ins"  linking processes the display label "part of" would be better?

does
protein serine/threonine kinase activity
directly inhibits cdr2  involved in negative regulation of protein localization to cell tip  (as) part_of in signal transduction involved in G2 cell size control checkpoint

@Antonialock 
@mah11

**Comment by mah11** [comment]
https://github.com/pombase/curation/issues/1414

I have no preference ... don't have the brain space at the moment ...

**Comment by Antonialock** [comment]
It's probably better than what we have now...I'm not entirely sold but I certainly can't think of a better way of doing it.

**Comment by ValWood** [comment]
we can leave until we have more examples of where GO will not precompose, might be clearer which display labels to use....

**Comment by ValWood** [comment]
Go ahead with this change. Non urgent but seems quick.

**Comment by ValWood** [comment]
Probably only *I* want this, definitely a post release enhancement!

**Comment by mah11** [comment]
I have changed the configuration for part_of to display "involved in" for MF range, and "part of" for BP range (assuming I did it right; reopen if I broke it).
