### ISSUE TITLE
ordering on term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#295]
Do we have an order proposed here,
in the absence of anything else,  alphabetical would be useful, I think...

**Comment by ValWood** [comment]
or earlier if a decision is made and is quick

**Comment by kimrutherford** [comment]
>  alphabetical would be useful

I've made it alphabetical - might need a shift-reload.

**Comment by ValWood** [comment]
Hmm, that's good, but one thing which was helpful was that in the previous ordering, the term in question was always at the top.

Because this is necessarily the broadest term, since all others are descendants, and the display is non-redundant , you can see immediately the "least characterised genes".

Would it be strange to put the term itself at the top, and everything else alphabetical? I think I prefer that the rest is alphabetical rather than random, in case people think there is some meaning to the random order.....but if people don't like this we  should probably go back to random, with the "actual term" at the top...

**Comment by ValWood** [comment]
so this, does not work quite so well......

Subject: 	protein kinases and substrates status

Kim removed some more of the redundancy last night so now you only see 
the very most specific annotation.

This shows clearly which kinases are unstudied/ do not have an annotated 
substrate.

We should target the ones at the top of the list, I am sure we can get 
substrates and processes on a lot more of these....(cdk9, orb6, cek1, 
nak1, sid1, fin1)

http://pombase2.aska.gen.nz/term/GO%3A0004674

**Comment by kimrutherford** [comment]
> Would it be strange to put the term itself at the top, and everything else alphabetical?

I think it would be strange but it's also strange to have the term itself at the top and everything random.

Also in some cases the term itself doesn't appear on the page at all: http://pombase2.bioinformatics.nz/term/GO%3A0006274

**Comment by ValWood** [comment]
Good point...OK, let's keep it alphabetic.

My only other idea was to organise so that the most annotated terms came first. This would mean that "leaf nodes" which usually had fewer annotations and "broader" terms with more annotations towards the top. Its a heuristic solution and it would probably work quite well,but it might  be a little obscure. Maybe we should keep as is....

**Comment by ValWood** [comment]
This is fine as is. We might think of cleverer displays on term pages later. There are other tickets about this anyway. We'll discuss when we have nothing else to do ;)
