### ISSUE TITLE
toggle/link to gene list and back to "ontology descendants view"  is sticky

### ISSUE THREAD

**Issue by ValWood** [pombase/website#296]
I think when you go to other pages it is better if the default is always the new "ontology" view

**Comment by kimrutherford** [comment]
Sorry, I don't understand.  Are you talking about the term pages?  Could you give me an example page?

**Comment by ValWood** [comment]
Actually it isn't always the case...

I haven't figured it out

When you first go to a term page its this view:
http://pombase2.aska.gen.nz/term/GO%3A1905785

Then if you go to this gene  list view
http://pombase2.aska.gen.nz/term_genes/GO%3A1905785

and leave the page and return later
http://pombase2.aska.gen.nz/term/GO%3A1905785
oh, you are back to the default.... that's what I expected



even if its another gene

or a different term

so I no longer see what I saw yesterday (I I was seeing the gene list on subsequent pages, instead of ontology view)

will open a new  ticket if I see it again...
