### ISSUE TITLE
 section links to  other gene pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#298]
Are these configured to behave in any particular way depending what page section you are in?

In cdc2 target of section  link  to wee1 plonks me in the literature section, which seems odd....

The GO section links appear to stay in the vicinity of the GO section.

I'm not sure if all interpage links shouldn't send you to the top of the page you land on?

Thoughts @mah11 @Antonialock  ?

**Comment by kimrutherford** [comment]
> In cdc2 target of section link to wee1 plonks me in the literature section, which seems odd....

Sorry, I've been meaning to fix that.  If it's what I think the problem is that the page contents changes but the page doesn't scroll.  It should scroll to the top.  It's only a problem when you go to a gene page from a gene page.

**Comment by kimrutherford** [comment]
I've fixed the gene and term pages links so they go to the top of the page which is probably a good default for now.

**Comment by ValWood** [comment]
For me, genes linked form cdc2 target_of section still go to literature section...

**Comment by kimrutherford** [comment]
> For me, genes linked form cdc2 target_of section still go to literature section...

Sorry, I forgot to re-release.  It works now for me after a shift-reload.

**Comment by ValWood** [comment]
yep that's much less disorienting  as default....
