### ISSUE TITLE
Hiding redundant relations and ordering  annotation by gene within "target of" section (GO)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#299]
![ordering within section](https://cloud.githubusercontent.com/assets/7359272/25558423/36c3d5e2-2d1e-11e7-8c35-eb60297d04c9.jpg)

  default
if a by gene (i.e  group same gene together) , but the first gene(s) will be those which have

a)
directly activated by 
directly inhibited 

b) 
substate of

c) binds

d) regulated by

Relationships can be considered to be redundant here so the most "specific"
relation is the only one we need to show in summary.

This would collapse to
directly activated by cdc25,
directly inhibited by wee1
substrate of mcs6 
substrate of  mik1
substrate of  pyp3
substrate of csk1
regulated by cdc13
regulated by cdc16
binds suc1
binds spd1
regulated by mcs2
regulated by clp1
regulated by srw1

This does not collapse much, it only removes 4  entries from this list, but biologically it makes more sense, because the ones closest to cdc2 biochemically  are listed first.
This is also a curation aid because we can see where annotation is lacking....
For example really cdc13 should be annotated as a direct activator of cdc2. 
In fact we can't get the specificity in GO between a  "direct activator"  (cdc13) and a  "direct positive regulator" (wee1). Go decided not to differentiate....(I wonder if this is a good long term plan...)

**Comment by ValWood** [comment]
Yes  please implement, but non- urgent. 
Will keep it in the milestone but it really isn't critical for release at all.

**Comment by ValWood** [comment]
I don't think this will bother our users, but it will be a long term improvement...

**Comment by ValWood** [comment]
can remove milestone if  time > a couple of hours

**Comment by kimrutherford** [comment]
> default
> if a by gene (i.e group same gene together) , but the first gene(s) will be those which have
> a) ...

So sort by the relationships, in the order you listed?

> "group same gene together"

Or do you mean sort by gene, then by relationship?  We can't group the genes together if we order by relationships.

Ordering won't take too long.  This will take longer:

> Relationships can be considered to be redundant here so the most "specific"
> relation is the only one we need to show in summary.

**Comment by ValWood** [comment]
Lets leave this one for a while. I'll remove next. Will mull over....

**Comment by ValWood** [comment]
-by relationship as listed above first.
- alphabetical gene name 2nd
(was that the question?)

**Comment by ValWood** [comment]
@kimrutherford did this make sense?

**Comment by kimrutherford** [comment]
> did this make sense?

Yes, except for:

> Relationships can be considered to be redundant here so the most "specific"
> relation is the only one we need to show in summary.

Which relationships are the most specific?

**Comment by Antonialock** [comment]
directly activated by
directly inhibited by
substate of
binds
localized by
regulated by
activity affected by mutation in
affected by mutation in

**Comment by ValWood** [comment]
yes
directly activated by/ directly inhibited by (show both by default although unliekly to occur together?)
substrate_of
binds
localized by/ regulated by (show both by default)
activity affected by mutation in
affected by mutation in

**Comment by ValWood** [comment]
So in summary

Show only the most specific relationship type be default (but show all annotation in 'show details"
Using

directly activated by/ directly inhibited by (show both by default although unliekly to occur together?)
substrate_of
binds
localized by/ regulated by (show both by default)
activity affected by mutation in
affected by mutation in

for the precedence.

Then order within a specific relationship alphabetically by gene name

**Comment by kimrutherford** [comment]
I did a query to see if any relations aren't covered and found that "transported by" isn't in your list.  Where should that go in the priority order?

**Comment by ValWood** [comment]
binds
transported
localized.

If we ever use a new relationship type that is not  currently used, will we get a log message?

**Comment by kimrutherford** [comment]
> If we ever use a new relationship type that is not currently used, will we get a log message?

Yep, you'll see a complaint in the log.

Currently the list is sorted by the gene column.  Should it be sorted by relation?

**Comment by ValWood** [comment]
Yes, relation first, and then gene.

**Comment by kimrutherford** [comment]
OK, thanks.  I've got the sorting by priority done.  I'll add sorting by gene and then it should be ready for tonight's load.  I haven't implemented the filtering by priority yet.

**Comment by kimrutherford** [comment]
I forgot to ask about GO versus FYPO.  Should they be treated separately or an GO annotation take priority over a FYPO annotation in the summary?

**Comment by ValWood** [comment]
GO takes priority over FYPO.

**Comment by kimrutherford** [comment]
> GO takes priority over FYPO.

Great.  That's how implemented it.  The changes are in the main site now, including filtering by priority.  Please let me know if you spot any problems.

**Comment by ValWood** [comment]
Looks great!, much easier to consume ( cdc2 target of is a good eg)

Just to check, do ALL the annotations show in show details? (I think they do)

**Comment by kimrutherford** [comment]
> Just to check, do ALL the annotations show in show details? (I think they do)

Yep, the order has changed but only the summary will have less annotations.

**Comment by kimrutherford** [comment]
Hi Val.  Where should "phosphorylated by" and "ubiquitinated by" appear in the ordering?  They've popped up in the log file.  Currently the go to the end of the table because they aren't configured.

**Comment by ValWood** [comment]
Before substrate_of I think

**Comment by kimrutherford** [comment]
> Before substrate_of I think

Thanks.  I've changed the config and I'll check Friday night's load.

**Comment by kimrutherford** [comment]
> Thanks. I've changed the config and I'll check Friday night's load.

It's fixed now.

**Comment by kimrutherford** [comment]
Hi Val.

Where should annotations with these relations appear in the target of table?:
 - promoter bound by
 - read by

They aren't configured so the current get put at the end, like here:
https://www.pombase.org/gene/SPAC1834.04
(You'll need to show details to see them)

Thanks.

**Comment by ValWood** [comment]
Well spotted. 
They can go in the GO list above 'binds'

**Comment by kimrutherford** [comment]
Thanks.  That's done for tonight's load.
