### ISSUE TITLE
tRNA secondary structure graphics

### ISSUE THREAD

**Issue by mah11** [pombase/website#30]
On tRNA gene pages, show a graphic of the (known or predicted) secondary structure.

Todd Lowe's group can provide simple images, e.g. http://lowelab.ucsc.edu/cgi-bin/draw_trna.cgi?%20chrII.trna2

Also follow up on a program that would map the tRNA sequence onto a model and translate the coordinates into human readable comments such as "in D-loop", "in TPsiC stem", "at wobble base of anticodon", etc. (they told Antonia it was being developed in 2012).

(Mark M. also said "The following web service is able to draw the images on the fly. http://pseudoviewer.inha.ac.kr/", but that page now times out for me.)

**Comment by ValWood** [comment]
Actually we  are really unlikely to do this, but Rfam plan to so we can just ass link outs....

**Comment by ValWood** [comment]
Look for  a web service which works...
Things which would never get up the list now seem infinitely feasible within current time frame...
Still low priority though...

**Comment by ValWood** [comment]
future doc
