### ISSUE TITLE
gene page display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#300]
just seen this:

![bug](https://cloud.githubusercontent.com/assets/7359272/25558997/299d55d0-2d2a-11e7-912c-994b065c04c4.jpg)

and this

![default](https://cloud.githubusercontent.com/assets/7359272/25559001/38ae736a-2d2a-11e7-9869-c4307d844ecb.jpg)

when I try yo resize the page widthways

**Comment by ValWood** [comment]
I think that might be the same, or similar, issue as here:

https://github.com/pombase/website/issues/227

**Comment by kimrutherford** [comment]
Yep, I think it's the same as Antonia's issue and the same as #275 too.  Tables are a bit of a pain in HTML.

**Comment by ValWood** [comment]
duplicate
