### ISSUE TITLE
add to coordinate changes page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#305]
SPAC12B10.09 - now shorter, 5' end

SPAC22F3.11c and SPAC29A4.23 - exon/intron boundary changes

**Comment by mah11** [comment]
dates? refs?

**Comment by ValWood** [comment]
based on the warnings, I think SPAC22F3.11c must be
https://www.pombase.org/spombe/result/SPAC22F3.11c#warning

SPAC22F3.11c and SPAC29A4.23 - exon/intron boundary changes
http://pombase2.aska.gen.nz/reference/PMID%3A26494834

SPAC12B10.09 - now shorter, 5' end
http://pombase2.aska.gen.nz/reference/PMID%3A26615217
