### ISSUE TITLE
"multi allele phenotypes"  difficult to locate start in long term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#306]
http://pombase2.aska.gen.nz/term/FYPO%3A0000059

( a casual user probably wouldn't know they were there anyway...maybe need some "quicklinks"
type feature at the top? Thoughts @mah11 @Antonialock

**Comment by ValWood** [comment]
They are there sorry, but point 2 is still relevant, difficult to find their start point on long pages, I missed it scrolling....

**Comment by kimrutherford** [comment]
It's there, but easy to miss.

> maybe need some "quicklinks" type feature at the top?

I think so and on the reference pages too.

**Comment by Antonialock** [comment]
Yeah quicklinks would help

**Comment by kimrutherford** [comment]
I've added a menu on the term details and reference/publication details pages.  You'll need to reload.

To be consistent, currently the menu is there even if there is only one type of annotation.  eg.
http://preview.pombase.org/term/GO%3A0006260

Should we just hide it in that case?

It also looks a bit daft in the case where there are only a few sections on the page like in Val's example:
http://preview.pombase.org/term/FYPO%3A0000059

Any suggestions?

**Comment by ValWood** [comment]
hmm, it is a waste of space when only one type, but the inconsistency is also weird.

let's discuss and see if we can think of a better way on the next call.

**Comment by ValWood** [comment]
OK we think it's good to have on all term pages for consistency. Also we might think of other uses for it. We feel a few percolating already ;)
