### ISSUE TITLE
"NOT" annotations in term view

### ISSUE THREAD

**Issue by ValWood** [pombase/website#307]
causes this, which looks like redundancy, but one is a NOT (ate1)

![not annotation](https://cloud.githubusercontent.com/assets/7359272/25654118/c8bf3cf4-2fe7-11e7-8626-df35d2b9f02b.jpg)

I think we should only display NOTs on gene pages, but not in term lists

**Comment by kimrutherford** [comment]
> I think we should only display NOTs on gene pages

I've done that but I've left them on reference pages too.

**Comment by ValWood** [comment]
makes sense
