### ISSUE TITLE
preserve input order for gene list search

### ISSUE THREAD

**Issue by mah11** [pombase/website#31]
We don't know if this will be feasible, but we've had users request it, so:

Option for the gene name and systematic ID filters, to have results returned with genes in the same order as in the input list.

User requests in https://rt.sanger.ac.uk/Ticket/Display.html?id=303908 & https://rt.sanger.ac.uk/Ticket/Display.html?id=456638

**Comment by ValWood** [comment]
moved to "gene list" upload ticket
