### ISSUE TITLE
are term class filters useful on term pages?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#310]
![are filters useful on term pages](https://cloud.githubusercontent.com/assets/7359272/25670331/413a9aac-3024-11e7-89f7-959985387ecf.jpg)

usually the annotation is in a single class?
Even if multiple it seems arbitrary to filter here?
Thoughts?

**Comment by kimrutherford** [comment]
I vote for hiding the term filter on the term details pages.

**Comment by ValWood** [comment]
Yep, "allele type" filter, when we have it, will be relevant on these pages,  evidence too in full view......

**Comment by ValWood** [comment]
Not urgent, but looks quick.

**Comment by kimrutherford** [comment]
I've hidden the term filter on the term pages.
