### ISSUE TITLE
search working but not showing autocomplete

### ISSUE THREAD

**Issue by ValWood** [pombase/website#312]
search working but not showing autocomplete

**Comment by mah11** [comment]
is this the gene name search in the header? that's working for me, with autocomplete suggestions

**Comment by ValWood** [comment]
Odd, def not working for me...

**Comment by mah11** [comment]
okaaay, now it's stopped working for me too, post-reload. (so at least you're not going mad)

**Comment by ValWood** [comment]
phew....good news today...

**Comment by kimrutherford** [comment]
That was caused by the same library change.  Sorry!  It's working again now.
