### ISSUE TITLE
block some xrefs for some feature types

### ISSUE THREAD

**Issue by ValWood** [pombase/website#313]
Peptide Atlas
ModBase
UniPRot 
DIOPT
(i.e any protein only resource) links should not appear for ncRNAs

We might need to extend the config file format?

**Comment by ValWood** [comment]
Punt if not quick, as not critical

**Comment by kimrutherford** [comment]
That should be quick.

> We might need to extend the config file format?

Yep, we just need to add an extra setting that can restrict the feature type for each xref.

**Comment by kimrutherford** [comment]
I've hidden those four external references for ncRNAs by extending the external_gene_references configuration.
