### ISSUE TITLE
term page "tree branch" connections

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#315]
I know it is not straight-forward because one term may have multiple different parent terms, 
but e.g. when looking at this term page 
http://pombase2.aska.gen.nz/term/FYPO%3A0000059
it would be quite helpful (I think?) to see how the terms fit together

![screen shot 2017-05-04 at 13 53 21](https://cloud.githubusercontent.com/assets/12727506/25704386/13a5c5e6-30d1-11e7-8f87-139e37a148c3.png)

If not possible on the page itself...then maybe a click to a page where you can see the ancestry like the quickGO shared ancestry view

just blue sky thinking...would this be useful?

![screen shot 2017-05-04 at 13 51 30](https://cloud.githubusercontent.com/assets/12727506/25704323/e1298cec-30d0-11e7-8519-e65e25c17a17.png)

**Comment by ValWood** [comment]
We should link this to the other tickets about how to organise this page.

**Comment by Antonialock** [comment]
did you mean to close it?

**Comment by ValWood** [comment]
nope

**Comment by ValWood** [comment]
I thought that you added to this ticket  the URL syntax to highlight the ancestors in  QuickGO in the URL.

I think it would be useful to  add a quickgo  ancestor link tot he term pages if this is quick and easy...

**Comment by ValWood** [comment]
MAiled quickgo about webservices
