### ISSUE TITLE
GO slim page and summary final

### ISSUE THREAD

**Issue by ValWood** [pombase/website#316]
Proteins with a biological process annotation not covered by the slim (gene count: 214)
Proteins with no GO slim or biological process annotation (gene count: 795)

- [x] should be linked lists

The numbers will be quite a bit different when generated because of the ontology change.
(I think the list of genes with a BP which is not int he slim is only around 110-115 now)

- [x] Add counts

**Comment by kimrutherford** [comment]
> should be linked lists

That's going to take a while to implement as it needs bit more processing.  In the meantime I've temporarily removed the two non-links.

**Comment by ValWood** [comment]
Is this tricky?
It isn't critical but it would be useful. I (finally) drafted a paper about the "unknowns" on the plane and I need this to complete. Not urgently....

**Comment by ValWood** [comment]
.....I still have lots of other stuff to do for the paper...

**Comment by kimrutherford** [comment]
From the current code, genes that don't have annotation covered by the slim:
  https://www.dropbox.com/s/s0p4ahy94c26hdi/non_bp_go_slim_genes.txt?dl=0

**Comment by ValWood** [comment]
I had a look, all look fine except 

https://github.com/pombase/website/issues/364

**Comment by kimrutherford** [comment]
The counts and links are there now (if you reload).  Let me know if the wording is OK:

    Genes not covered by the slim (1002 in total):
    Genes with a process annotation, but not in any of the categories above: 128
    Genes with no biological process annotation: 874

Could you let me know what title and/or description you'd like at the top of the two linked pages:

http://preview.pombase.org/gene_subset/non_go_slim_with_bp_annotation
http://preview.pombase.org/gene_subset/non_go_slim_without_bp_annotation

**Comment by ValWood** [comment]
-  [ ] Links  work but lists are empty

- [ ]  refine text for links to "Genes products with"

**Comment by ValWood** [comment]
- [ ]  Titles
Genes products with a biological process annotation, not covered any of the PomBase<<http://preview.pombase.org/browse-curation/fission-yeast-go-slim-terms link GOslim>> categories: 128

Genes products with no biological process annotation:

**Comment by kimrutherford** [comment]
> Links work but lists are empty

Sorry about that.  It was a last minute screw up before going to bed.  Fixed now.

**Comment by ValWood** [comment]
fab!

**Comment by kimrutherford** [comment]
I've added those titles.  Could you check them?

**Comment by ValWood** [comment]
Gene products with a biological process annotation, not covered any of the PomBase GOslim categories

hmm, i made a type anyway but perhaps:

Gene products with biological process annotation, not covered the PomBase GOslim categories


Also both lists have the same title. The other list should be simply:
Gene products with no biological process annotation: 874

**Comment by kimrutherford** [comment]
> Also both lists have the same title. The other list should be simply:
> Gene products with no biological process annotation: 874

Do you mean the text by the link?  That is what it is already.

**Comment by ValWood** [comment]
from here
http://preview.pombase.org/browse-curation/fission-yeast-go-slim-terms

the list
Gene products with no biological process annotation: 874
lists to a page with the title:
Gene products without biological process annotation, not covered by the PomBase GOslim categories: 874
