### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#317]
Quite a bit of stuff seems to have changed very subtly in the past hour or two (maybe the new library)

- The font looks different. Its definitly a different colour... (and its a different colour from the menu font, more garish blue)
- I think the menu formatting might have changed too

how it looks now:
![changes](https://cloud.githubusercontent.com/assets/7359272/25705934/dda45754-30d6-11e7-9014-a1fe44dbb7ba.jpg)

**Comment by ValWood** [comment]
from my last screenshot, def different font, and colour...

![phenotype filter](https://cloud.githubusercontent.com/assets/7359272/25706011/233914ee-30d7-11e7-8113-fcec86e08032.jpg)

**Comment by ValWood** [comment]
I don't know which is better

**Comment by ValWood** [comment]
- [ ]  Show details no linger looks like a linky

**Comment by ValWood** [comment]
What are the fonts? The  new one seems to be the one which everything is moving to.
I like the new one in the big blocks, but the old font works better in the menu, it must be slightly narrower so its a bit more compact....

**Comment by mah11** [comment]
I've done some screenshots (with a convenient tab containing a gene page loaded last night) and convinced myself that with the computer/browser combination I used, it's the same typeface; only the size has changed.

I do see the color changes, and I think I like the new left-hand menu color, but not the new color for all the links in the page body. I'm fairly sure that it was just using my browser default link color before the changes.

It would be very good if show/hide details resumed looking linkish.

**Comment by kimrutherford** [comment]
> Quite a bit of stuff seems to have changed very subtly in the past hour or two (maybe the new library)

Sorry about that.  On my screen it didn't look very different with the new library.  But I've been spotting little quirks too now I look closer.

I've completely reverted that change and I'll have another go after release.  Upgrading would have made a few things easier but it can wait.

It should now be back as it was.  Could you have a quick look and close this if it's OK?

**Comment by ValWood** [comment]
I haven't spotted any problems.

That's a pain....

**Comment by kimrutherford** [comment]
OK, please open new issues if you spot any other problems.
