### ISSUE TITLE
Tidy up the documentation links to missing docs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#318]
We should hide or grey out links to docs that are not in PomBase v2 yet.

(Or link to the old site when appropriate)

**Comment by ValWood** [comment]
Probably should still link tot he FAQ on the  old site, maybe?

**Comment by kimrutherford** [comment]
> Probably should still link tot he FAQ on the old site, maybe?

I've left the Docs section FAQ link pointing to the old site for now.  But I'm hoping to move more of the documentation across before the conference, including the FAQ.

**Comment by kimrutherford** [comment]
I've spent today moving the documentation to markdown.  It's maybe half done.  There are still a lot of broken links and bad formatting.  Also all images (mostly screenshots) are missing.  I'll fix that tomorrow and do more link fixing and other tidying.

**Comment by kimrutherford** [comment]
I've added more documentation and put the images in.  Although now I look at the screenshots, they are for the old site and in some cases things have changed a lot.  Should we just hide the "Documentation" link for now?

**Comment by mah11** [comment]
I've had it on my mental to-do list for a while now to update screenshots, but I've been waiting for the look of the new site to settle down (and some screenshots are of things we haven't even started porting over, like the query interface).

Are there things that are stable enough to screen-grab now? If so, which ones? I can make a start, but it's kind of time-consuming so I can't promise to have even the gene pages done for the conference, let alone the new pages.

In the meantime, I guess we could either hide the documentation link, or add a big screaming disclaimer to say they need updating - whichever you (plural) prefer.

**Comment by ValWood** [comment]
I would wait a little while and add a disclaimer...no point in doing stuff twice. We can evaluate after meeting which pages are "settled" enough...

**Comment by mah11** [comment]
I like that answer a lot ;)

**Comment by kimrutherford** [comment]
> I would wait a little while and add a disclaimer

So add a disclaimer rather than just hiding those pages?

**Comment by ValWood** [comment]
..I think so...

**Comment by kimrutherford** [comment]
> I would wait a little while and add a disclaimer

I've added a ugly disclaimer on every page.  It might be overkill but it makes it harder to miss.  Let me know if you'd like to change the wording.

Currently it says:

    Note: because of changes in this preview, many of the screenshots in this documentation
    are out of date.

**Comment by mah11** [comment]
Yep, that ain't pretty, but it should be effective. I have no better ideas in the short term. (It's on .nz but not babraham at the moment - expected?)

**Comment by kimrutherford** [comment]
> (It's on .nz but not babraham at the moment - expected?)

I've updated the Babraham version now.  Up until now I've been updating the web code by hand (by copying files to the right place) but I've just change the release script to make it easy to release to any destination.  So now I'll update the .nz site and the .babraham.ac.uk site each time I make a change that should be released to both.  If it's a change that needs testing or discussion I'll just release it to the .nz site.

For now though I'm not updating the data (genes, refs, terms etc.) automatically because we don't want any surprises caused by dodgy Chado builds.  I'll update the data tomorrow if everything looks good but I won't update during the conference unless there's a big-ish bug or Val or Antonia ask for an update 
of fix.

**Comment by mah11** [comment]
That all sounds good.

**Comment by kimrutherford** [comment]
I've now copied and formatted most of the remaining documentation and I've fixed a bunch of broken links.  There is a more to do but the core is there.  Some things are definitely broken or missing and I've made separate issues for the things I've spotted: #334, #335 and #336.

I'm going to close this issue.  Please open new issues as you find problems.
