### ISSUE TITLE
"faceted" simple search

### ISSUE THREAD

**Issue by mah11** [pombase/website#32]
We want to mimic the search feature that's available in the header on WormBase pages. They have a pulldown in the header search, and autocomplete function once you start typing a string.

We don't need all of WB's options (nor all of the . The selections we'd like (in the first instance) are:
- Gene name/ID*
- Gene product
- Ortholog
- PubMed ID
- All

*DEFAULT selection: searches gene names and systematic IDs

Additonal thoughts:
- If there's a single match to a gene name or ID, go straight to that page; otherwise, show results on a page much as it does now.
- Later, we might want to add phenotypes , GO terms, and (when we have the relevant data and pages) papers.
- For 'all', it would still be nice to organize search results into genes, ontology terms, web pages (originally floated in PB-620). We'll still want to exclude the pages listed in PB-692.
- The simple search page and the header search box should work the same way (which means the simple search page is just for completeness, but that's fine with us).

(some background in Jira PB-1127)

**Comment by ValWood** [comment]
We can run through this on the next call just to make sure we got everything we require for the first pass

**Comment by ValWood** [comment]
Search on systematic ID and synonym for live

**Comment by ValWood** [comment]
we don't absolutely need the facetted search for public release but it would be able to search  products, ortholog IDs ....
can decide later...

**Comment by ValWood** [comment]
We don't need this for public release since we don't have it at the moment. However it would be nice to be able to continue to search on cerevisiae ORF names and HGNC names (HGNC search is currently broken on P1, although it did work periodically)

**Comment by kimrutherford** [comment]
> search on cerevisiae ORF names and HGNC names

If you put in a ceravisiae ID should it go to the pombe ortholog (if any)?

**Comment by ValWood** [comment]
yes, thats a fudge we have currently
http://www.pombase.org/faqs/how-can-i-search-s-cerevisiae-orthologshomologs-s-pombe-gene
http://www.pombase.org/faqs/how-can-i-find-s-pombe-orthologs-human-gene

but it works....

Eventually we would like to be more specific about the field. Luckily search on S.cerevisiae orf name is never going to retrieve anything but an ortholog. A few cases where human names might, but this should be blatantly obvious why to users....

**Comment by kimrutherford** [comment]
So if there's no ortholog, there's no match?

> A few cases where human names might, but this should be blatantly obvious why to users....

What should it do in that case?  Should it go to a results page if there is more than one pombe ortholog?

**Comment by ValWood** [comment]
this is current behavior:
http://www.pombase.org/search/ensembl/YOR086C
no match, no results

**Comment by kimrutherford** [comment]
We decided to treat ortholog IDs a bit like synonyms when autocompleting.  If an ortholog matches we'll show the pombe gene(s) and show the ortholog ID below the match.

**Comment by kimrutherford** [comment]
I've added the orthologs to the search box.  It now works like this:

![yjl187c-box](https://user-images.githubusercontent.com/90474/28207883-5b9d6ad4-68df-11e7-8b01-fa9dce98a128.png)

**Comment by ValWood** [comment]
Nice. Can you add for human (HGNC IDs) too?

**Comment by kimrutherford** [comment]
> Can you add for human (HGNC IDs) too?

I've done that.  It had the Ensembl human gene IDs but not the HGNC ones.  It now has both.

**Comment by ValWood** [comment]
Might do the PMID search before release as it's quick, but not necessary before release.

**Comment by ValWood** [comment]
- author (long term a page per author might be good, suggested here https://github.com/pombase/website/issues/457

**Comment by ValWood** [comment]
We can do this, but it isn't obvious.
Antonia mentions it in the NAR paper. We should think about whether to do a quick fix to make it clearer or  implement as we want it for the paper.

(there is quite a lot of time before submission)

**Comment by mah11** [comment]
> We can do this, but it isn't obvious.

What's the "this" here?

**Comment by ValWood** [comment]
edited

**Comment by Antonialock** [comment]
A quick fix could be to have a little "?" icon next to the search box that lists things that are searchable ?

**Comment by kimrutherford** [comment]
> A quick fix could be to have a little "?" icon next to the search box that lists things that are searchable ?

I've made a first attempt at that.  I've added a help icon and put this placeholder text in.  Please let me know what you'd like instead:

- Start typing to search for genes
- For publications: type or paste a PubMed ID and press enter
- For ontology terms: type or paste the term ID and press enter

The help icon could be clickable and link to the documentation if that helps.

**Comment by ValWood** [comment]
I can't see it?

**Comment by kimrutherford** [comment]
It's a little "i" to the left of the search box.  You'll need to reload.

![search-info-1](https://user-images.githubusercontent.com/90474/41279647-2f8d9862-6e81-11e8-9d48-e09fe65f27d5.png)

**Comment by ValWood** [comment]
That seems a good stop gap to me.

**Comment by kimrutherford** [comment]
> That seems a good stop gap to me.

Great.  Let me know if you think the icon size needs tweaking.  It's maybe a bit small?

**Comment by kimrutherford** [comment]
> I think the main problem is that is "disappears" a bit on the blue background...

I agree.  I'll add a small light background and see if it helps.

**Comment by kimrutherford** [comment]
Would inverting the colours help?:

![search-info-2](https://user-images.githubusercontent.com/90474/41286464-b44d4dd8-6e93-11e8-9a0b-43dcb6545c22.png)

**Comment by ValWood** [comment]
I think it looks OK...anyone else? my only though is that it would be different to the others, although I guess it's a stop gap...

**Comment by kimrutherford** [comment]
> my only though is that it would be different to the others

Do you mean different to the other help icons?  It's currently the same icon, so it would look like:

![annotation-help-icon-1](https://user-images.githubusercontent.com/90474/41288498-a8da2f32-6e9a-11e8-8e9b-a482ebe57c13.png)

**Comment by ValWood** [comment]
OK, it looks fine to me...

**Comment by mah11** [comment]
What would help me is to move it to the right-hand side of the search box. I just realized I have a very slight subconscious expectation to see the box and then carry on reading to see the 'i'. It would also match the placement of other 'i's on pombase pages, and the '?' in Canto.

But ignore if I'm the only one who thinks this ;)

**Comment by ValWood** [comment]
probbly more consistent on the other side, but I think people are more like;y to mouse over it where it is. dunno..... @Antonialock ?

**Comment by kimrutherford** [comment]
I tried to put the icon on the right initially but I wasn't sure how it should interact with the "No matching genes" message.

![search-rhubarb-1](https://user-images.githubusercontent.com/90474/41319572-59e39a7a-6ef0-11e8-92ed-fa1d817ad9fb.png)

**Comment by Antonialock** [comment]
> I tried to put the icon on the right initially but I wasn't sure how it should interact with the "No matching genes" message.

Interesting, I don't see that message anymore (I am _sure_ I have in the past...)

**Comment by ValWood** [comment]
i still see it with chrome...

**Comment by Antonialock** [comment]
I would also expect the icon on the right

I think the width of the searhc box should be decreased relative to its height

the "no matching genes" message could show in the dropdown?

**Comment by ValWood** [comment]
> i still see it with chrome...

well I did earlier today, now I don't ;)

**Comment by Antonialock** [comment]
I don't see it in chrome or firefox

**Comment by kimrutherford** [comment]
Sorry about that.  I caused it to disappear when I added the help icon.  I fixed it on my machine but forgot to commit the change.  I've done that now and the fix which will be visible in the morning update.

**Comment by kimrutherford** [comment]
> I don't see that message anymore (I am sure I have in the past...)

Sorry about that.  It's fixed now.

I've made the help icon slightly bigger while we think about changing how it looks.

> What would help me is to move it to the right-hand side of the search box.

How's this?  I haven't committed these changes yet.  I'll wait for comments:

![search-womble-1](https://user-images.githubusercontent.com/90474/41331555-b17ab704-6f2d-11e8-8019-2eccac6fa10b.png)

![search-womble-2](https://user-images.githubusercontent.com/90474/41331562-b6216366-6f2d-11e8-9594-ae3b3092b2de.png)

**Comment by ValWood** [comment]
That's better. I still think the search box *could* be slightly shorter though (~25%)

**Comment by kimrutherford** [comment]
> I still think the search box could be slightly shorter though (~25%)

I've made it shorter.  The other changes are live too.

**Comment by mah11** [comment]
I think that looks fine, and I'm happy to move on to other things rather than tweak it further ;)

**Comment by kimrutherford** [comment]
I've been avoiding high priority tasks today and instead I had a go at implementing term searching in the search box.  It's working locally for me.  I haven't committed the changes as I wanted to get feedback first.

I've included some screenshots below.  Does this look useful?

The gene matching works the same as ever except that it shows a maximum of 10 instead of 15 matches.

The term name matching should return the same matches as in the query builder except that it queries GO and FYPO at the same time.  (That can be changed if needed)

![search-box-term-1](https://user-images.githubusercontent.com/90474/43063778-f4a130b0-8eb0-11e8-9e8f-2f7379dce6a4.png)

![search-box-term-2](https://user-images.githubusercontent.com/90474/43063782-f878b424-8eb0-11e8-8748-930f1f4f504f.png)

![search-box-term-3](https://user-images.githubusercontent.com/90474/43063785-fc7f3976-8eb0-11e8-888a-1e678436537b.png)

**Comment by ValWood** [comment]
Yes. Very, very very useful ;)

**Comment by ValWood** [comment]
If I had thought it would be  a quick job it would have been at the top of the list ;)

**Comment by kimrutherford** [comment]
> If I had thought it would be a quick job it would have been at the top of the list ;)

I only worked out how to do it over the weekend.  :-)

I think auto-completing on publication titles, authors and years would be possible too.

**Comment by ValWood** [comment]
Is it possible to make it possible to select the facet from the search box like WB?

![facetted](https://user-images.githubusercontent.com/7359272/43121033-4c2a6848-8f14-11e8-801f-9dbedc1beada.jpg)

Otherwise, you will either never see the GO terms if the product lists are long, OR you will arbitrarily need to serve up a set of products.

FOr example -transmembrane , 178 products

**Comment by ValWood** [comment]
I'm also in favour of 
GO biological process, GO component, GO molecular function separately

**Comment by ValWood** [comment]
Authour and publication title  and year also very cool....

**Comment by kimrutherford** [comment]
> Is it possible to make it possible to select the facet from the search box like WB?

I think so, but I was thinking that we want to keep the quick search simple and have a dedicated faceted search page.

**Comment by ValWood** [comment]
Hmm, I thought one or the other maybe? Either only on a dedicated faceted search page,  or we do the faceted search on the page. 

I don't know which though....

Would be interesting what the others think...

**Comment by kimrutherford** [comment]
Putting the publication year in the search box works now so you type things like: nurse 2002

**Comment by Antonialock** [comment]
If possible would be good to avoid duplicate results (e.g. cdc42 shows twice in your example beause of ortholog + gene name match)

**Comment by kimrutherford** [comment]
> If possible would be good to avoid duplicate results

Thanks for the reminder.  I've been meaning to fix that.  That's fixed now.

**Comment by ValWood** [comment]
but weren't we going to separate out ortholog?

**Comment by kimrutherford** [comment]
> but weren't we going to separate out ortholog?

We can still do that.  But duplicates are a bit of an edge case.  Do we want to show cdc42 more than once if the ortholog(s) has the same name?  For cdc42 the human and cerevisiae orthologs are also "cdc42".

The product contains "cdc42" as well: "Rho family GTPase Cdc42".  Do we want to show the match in the product section?

**Comment by ValWood** [comment]
Good point, it may be duplicated in orthologs, only need to show once.
Also do not need to show product if there is a gene name match.

**Comment by ValWood** [comment]
I'm closing this it is very long.
We should open a new ticket for the next stages.

As far as I can see this  is to
i) allow specific 'factes' to be selected (if we still want to do that)?
and
provide a 'results page' option for long lists.

 Is that correct?

**Comment by kimrutherford** [comment]
> i) allow specific 'facets' to be selected (if we still want to do that)?
> and
> provide a 'results page' option for long lists.

I think options like specifying facets will need to be on a separate search page so these two items seem the same to me.
