### ISSUE TITLE
Add "background" and "lab strain name" to genotype pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#322]
http://pombase2.aska.gen.nz/genotype/a78d5a33655067b7-genotype-1

(find an example with lab strain name for checking)

**Comment by ValWood** [comment]
related to
https://github.com/pombase/curation/issues/1429

**Comment by kimrutherford** [comment]
What is the "lab strain name"?  Is that the genotype name from Canto?

The genotype name and background are both shown on the genotype details pages:
  http://pombase2.aska.gen.nz/genotype/1bc92c0f892db627-genotype-1
  http://pombase2.aska.gen.nz/genotype/9f25f26d17f2ec78-genotype-8

Although the formatting is a bit naff.

**Comment by ValWood** [comment]
yes thats the one.
If we do  https://github.com/pombase/canto/issues/1321
So deltaCCPR would be a synonym of cig2Δ cig1Δ puc1Δ rem1Δ

but the "other name" is there so we can close this...

**Comment by ValWood** [comment]
We'll open a ticket later if we change things...
