### ISSUE TITLE
add social media links to temp pombase2 front page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#325]
We will be doing some posting to coincide with conference start...

**Comment by kimrutherford** [comment]
I've added a link to Twitter and to the Facebook page.  There's no fancy formatting yet but it's a start.

**Comment by ValWood** [comment]
and pombelist
we will have a bit of a membership drive at the meeting...
good to have it in a prominent place
http://listserver.ebi.ac.uk/mailman/listinfo/pombelist

(we could do with a little icon for this!)

**Comment by kimrutherford** [comment]
I've added the mailing list.  Tomorrow I'll dig up some little icons for the three links.

**Comment by kimrutherford** [comment]
> Tomorrow I'll dig up some little icons for the three links.

I've added icons.  Any suggestions about formatting or headers?

**Comment by Antonialock** [comment]
I think the text can be cut to
[bird icon] Twitter
[f icon] Facebook
[mail icon] Mailing list

**Comment by kimrutherford** [comment]
> I think the text can be cut to

I've done that.

**Comment by Antonialock** [comment]
Perhaps also:
1. Move the "contact curators" link down one row so that it is grouped with the other links 
2. change the text to "contact"
3. use the mail icon with the "contact" link, and change the mailing list icon to something like this
<img width="200" alt="screen shot 2017-05-11 at 07 41 06" src="https://cloud.githubusercontent.com/assets/12727506/25935932/53b21a76-361d-11e7-8fab-f11d8afed0b4.png">

**Comment by ValWood** [comment]
or this,  quick mock-up...
maybe no text as it would be to small, but somthing to make it clearer its a mailing list about pombe...

![pombelist icon](https://cloud.githubusercontent.com/assets/7359272/25939431/be035144-362a-11e7-80f5-f64bc3a32778.jpg)

**Comment by ValWood** [comment]
>Move the "contact curators" link down one row so that it is grouped with the other links
>change the text to "contact"

I think the contact curators link should stay as it is, Its a bit different from the others....

But the other links can be just icons in a row as they are on the old front page.
Can add  linked in, google and Github (why not let users/funders see what we are doing/participate ...
WormBase  and GO use GitHub as their help desk now....).
Can we make "curation" a default pinned repository as this one is most the relevant for the community?

**Comment by ValWood** [comment]
> Github 
we have nothing to hide except my typos....must try harder...

**Comment by kimrutherford** [comment]
> or this, quick mock-up...

It's quite tricky to make it clear when it's so small, but I've had a go.

I've also added icons and links for GitHub, Google+ and LinkedIn.

> But the other links can be just icons in a row as they are on the old front page.

Done.

> Can we make "curation" a default pinned repository as this one is most the relevant for the community?

That's done too.

**Comment by kimrutherford** [comment]
> But the other links can be just icons in a row as they are on the old front page.

I had never noticed those icons before.  Perhaps the could be a bit more prominent in PomBase v2?

**Comment by kimrutherford** [comment]
I think this is done so I'm closing it.
