### ISSUE TITLE
speed of page loading

### ISSUE THREAD

**Issue by ValWood** [pombase/website#327]
I notice yesterday and  today that page loading is slightly slower than usual. I see the "fotter" message  for a second or so before the page loads. Of course this could be my increasingly bad connection....

**Comment by kimrutherford** [comment]
I think it's probably at your end.  I haven't changed anything that could make a difference.  shift-reload might be a little slower because the documentation has added to the size a bit.

**Comment by ValWood** [comment]
yeah its really rubbish this week, will phone Virgin media shortly (again)
