### ISSUE TITLE
community curated pub page flag

### ISSUE THREAD

**Issue by mah11** [pombase/website#328]
On the publication page for any paper with community curation in Canto, add a note saying (wait for it) "Community curated in Canto by $name(s)". Maybe include the Canto logo.

Kim has checked, and Chado does store the curator(s), so showing the names should work.

Everyone think about whether to include link to canto /ro session - not for meeting, but maybe later.

**Comment by kimrutherford** [comment]
I've added the "Curated by ..." message.  It's not very prominent at the moment.  Let me know if you'd like the formatting changed.

We also have the submission date and approval date available if you'd like to display that.  It could be shown when you mouse-over.

Here's an example: http://pombase2.bioinformatics.nz/reference/PMID%3A25987607
(You might need to reload)

**Comment by ValWood** [comment]
nice!

**Comment by ValWood** [comment]
canto link should go to pombe canto -get them straight to the PMID search box ;)

**Comment by Antonialock** [comment]
i don't like having the hyperlink and favicon in the middle of the sentence....could it read
"Community curated by Charalampos Rallis in Canto [icon]" instead?

Also, just a thought, could the name link to a person page with perhaps a curation summary for the person (number of annotations added for number of publications)

even further into the future..
People could be able to claim pages (like on the biosharing resource) to add info like contact details, affiliations, or whatever (and link a pombase account with canto account....then you can have the option of snazzy customization of gene pages etc etc)

**Comment by mah11** [comment]
What if we put the Canto icon at the starte (i.e. left-hand end) of the "community curated by" message? I think it would set off the message nicely - there's no need for the icon to be next to the link.

I also have a slight preference for maintaining the "Community curated in Canto by $name" order because that gives the community curator the last word in a way (and if the icon moves to the beginning there's no interruption).

Person pages are a viable idea but *must* go in a separate ticket.

**Comment by ValWood** [comment]
should it say something like
"community contributions in canto by"
or something  similar which does not correctly imply that they curated *everything*

The author might think it strange if they only submitted a couple of annotations.

or doesn't it matter?

**Comment by Antonialock** [comment]
"annotation contributions by"?

do we need to say "in canto" since the icon is there?

**Comment by ValWood** [comment]
I thought it was useful  to say "where" only because a large percentage of our users are not going to be pombe people,  and won't know about canto, but maybe it isn't necessary to say... not sure....

**Comment by mah11** [comment]
I think we want "community" in the text because we advertise the phenomenon as "community curation" consistently in several contexts. Random ideas for phrasing:

Community curation provided by x
Includes community curation from x

**Comment by ValWood** [comment]
Yes either of those...

**Comment by kimrutherford** [comment]
I've swapped the message around and put the Canto icon at the front.  I hope I've got the right idea from the discussion.  The Canto icon now links to the pombe Canto.

**Comment by mah11** [comment]
Well, I like it :)

**Comment by kimrutherford** [comment]
> Also, just a thought, could the name link to a person page

I made an issue for that so I could close this issue: #332
