### ISSUE TITLE
Identify GO slim term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#329]
add something to the GO slim term pages to identify that they are in the pombe slimset
(maybe also a link to the slim from these term pages?)

On this page:
http://pombase2.aska.gen.nz/browse-curation/fission-yeast-go-slim-terms
I don't think we need to say esyN, just the icon should do?

**Comment by ValWood** [comment]
quick

(as we already have the esyyN link on the slim term pages)

I suggest just adding the text "This term is part of the biological process overview ( GO slim)"
link to
http://pombase2.aska.gen.nz/browse-curation/fission-yeast-go-slim-terms

**Comment by kimrutherford** [comment]
I've added that text.
