### ISSUE TITLE
link to PANTHER ortholog web service

### ISSUE THREAD

**Issue by mah11** [pombase/website#33]
Quote from email from Paul Thomas:
"We've set up a web service for querying the ortholog data in PANTHER.  The service allows you to retrieve orthologs in other organisms, for a given gene of interest.  It could be used, for example, in your website gene page code to generate links to orthologous gene pages in other MODs.  We also offer the entire ortholog set in a flatfile, but use of the web service rather than loading the flatfile into a database will ensure that the results are always up-to-date."

entire email included in Jira PB-1158

**Comment by ValWood** [comment]
If we were going to expand the ortholog section to include a larger range of species, I think this would be the best way to do it. PANTHER is consistently good -and will  also tie in with GO  PAINT when we begin to import (although I suspect most we will cover and filter).

There were a few user requests in the survey  for more extensive ortholog representation...

**Comment by ValWood** [comment]
I put this as future..... I don't think it will add much and we have links to Diopt (and soon HCOP) which are amalgamated resources.

**Comment by ValWood** [comment]
We have links so this isn't a priority. Moved to "future" doc
