### ISSUE TITLE
community curation highlight for front page

### ISSUE THREAD

**Issue by mah11** [pombase/website#330]
Have a spot on the front page to spotlight the most recent 2 or 3 papers to come through community curation. Display brief citation, and link to publication page (which in turn will credit community curator, per #328).

**Comment by kimrutherford** [comment]
This isn't urgent but I wanted a break from urgent issues.

I've added a "Recently community curation:" section on the front page.  Let me know if you'd like it to look different.

It would also (now) be easy to add a section with recently approved admin sessions or a list of pombe papers recently added to PubMed (actually recent added to Canto, but that's more or less the same thing).

**Comment by kimrutherford** [comment]
Is that enough for now?  Can we close this issue?

**Comment by ValWood** [comment]
yep...can do more later...

**Comment by mah11** [comment]
It's wonderful except that "Recently community curation:" is bad English. It should be ""Recent community curation:" or "Recently community curated:".

**Comment by ValWood** [comment]
whoops, that's not actually English ;)

**Comment by kimrutherford** [comment]
Thanks.  Changed to "Recent community curation:" if you reload.
