### ISSUE TITLE
Odd documentation link behavior at preview site

### ISSUE THREAD

**Issue by mah11** [pombase/website#331]
If I go to the Babraham preview home page (http://pombase-preview.babraham.ac.uk/), I can click the Documentation link and see the page content. But if I try to reload the page, or open the page in a new tab, or copy/paste its URL to a new tab, window, etc., I get a 404 Not Found error. The same thing happens with any of the links on that page - I can reach it if I click the link in the same window/tab, but not reload and not open it in any other tab or window.

If I use the back button, the result depends on whether I reload a page or not - I can go back and forth between successfully loaded pages, but once I reload one, every page in a path is 404'd until I get back to the home page.

It only seems to affect the Documentation link on the front page and links on the Documentation page (http://pombase-preview.babraham.ac.uk/documentation) itself. All of the others behave normally (although the "Browsing and searching" and "GO Slim terms" links give normal 404-not-found behavior at the moment).

e.g. Documentation -> Protein features -> Modifications -> back through previous pages = all show up

whereas Documentation -> Protein features -> Modifications [reload] = all 3 pages give 404s

in contrast, for Documentation -> Basic Information -> Gene characterisation [reload] - back through previous pages = all pages show content because the reloaded one didn't go 404.

**Comment by kimrutherford** [comment]
Sorry about that.  I hadn't updated the web server configuration to handle /documentation and /browse-curation correctly.  It should be OK now.

**Comment by mah11** [comment]
'tis indeed - thanks!
