### ISSUE TITLE
Fix counts on "Gene characterisation" page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#335]
The numbers on this page don't update automatically:
  http://pombase-preview.babraham.ac.uk/status/gene-characterisation

**Comment by ValWood** [comment]
I presume this is quick since you have the numbers...

**Comment by ValWood** [comment]
Let me know if you need any info...

**Comment by ValWood** [comment]
from https://github.com/pombase/website/issues/241

auto generated table
http://www.pombase.org/status/gene-characterisation

history is static content:
http://www.pombase.org/status/gene-characterisation-statistics-history
(updates ~anually)

**Comment by kimrutherford** [comment]
> Let me know if you need any info...

I need help.  :-)

Do these numbers come from the species_dist annotation?

**Comment by ValWood** [comment]
Sorry more information required.
This comes from "annotation status" aks 	"PomBase gene characterisation status"

https://curation.pombase.org/pombe/view/object/cv/21?model=chado

**Comment by ValWood** [comment]
Ideally we will display like this:

![characterisation](https://cloud.githubusercontent.com/assets/7359272/26491677/7a8dbfe6-4208-11e7-9cc2-0efed1757138.jpg)


https://github.com/pombase/pombase-chado/issues/566

its an old ticket on the Canto tracker from when we were doing the stats page

 This would  need to use the "historical data" not stored in canto though
its here on the old site:
http://www.pombase.org/status/gene-characterisation-statistics-history

I'm drafting a paper about the "unknowns"

**Comment by kimrutherford** [comment]
> This comes from "annotation status" aks "PomBase gene characterisation status"

OK, thanks.  That should be a quick-ish fix.  Graphing the historic data will take longer.

**Comment by ValWood** [comment]
Thats ok, we have the old ticket open for that. Its my "interesting" boring graph ;) It tells us that people aren't really getting a handle on the unknown 20%.....

**Comment by kimrutherford** [comment]
The table on the characterisation status page now has up to date counts and the counts are links to the gene lists:
 http://preview.pombase.org/status/gene-characterisation

The counts are more or less the same as the PomBase v1 page.  Are the differences expected?

Let me know if there is any text to update, especially on the gene list pages.  Here's an example:
 http://preview.pombase.org/gene_subset/characterisation_status_conserved_unknown

**Comment by ValWood** [comment]
I think that's fine for now. When we are closer we can review text. Perhaps when we do docs FAQ rather than  lots of ad hoc changes.

**Comment by ValWood** [comment]
The numbers are good too.... they are changing.....It still looks pretty static in a graph though....

**Comment by ValWood** [comment]
Wow! The numbers are exactly the right numbers. You don't know how unreal that feels. ...
I'll close this and open a new low priority ticket about the graph for later
