### ISSUE TITLE
Move the FAQ over to PomBase v2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#336]

**Comment by ValWood** [comment]
For public release we can link to the old FAQ

**Comment by ValWood** [comment]
Hmm no we can't can we... it will be under pombase URl

**Comment by ValWood** [comment]
We will get a list of FAQs which need new content.
Midori will start to update content in a file to slot in, where new answers are known.

Notes,
FAQs have labels (lists)
Questions can appear under multiple lists
We want to migrate, but not  be stuck if we want to


Curators look at classification.

**Comment by mah11** [comment]
@mah11 to review and update FAQ content
@ValWood (and @Antonialock ?) to review categories
@kimrutherford to find FAQs in EBI dump and start converting to shiny new PomBase (or at least thinking about it)

**Comment by ValWood** [comment]
I think we can git rid of a few labels.

[FAQ categories.txt](https://github.com/pombase/website/files/1149115/FAQ.categories.txt)

**Comment by kimrutherford** [comment]
We have the FAQ text and the rest of the Drupal stuff now.  Unfortunately it's in HTML rather than something easy to edit like Markdown but we should be able to cope.

I haven't put the text in Git yet but I should be able to do that tomorrow.

We should chat about what functionality is needed for the FAQ (one question per page or all in one page?  A search function?).  We don't have to copy the current site.

**Comment by ValWood** [comment]
- [ ] split by categories, add menu
- [ ] independent mechanism to adjust content and identify categories (decoupled)
One file per question and a tag to say which categories to appear in.

**Comment by kimrutherford** [comment]
This tar file contains two directories, "faq_html" and "faq_markdown":
https://www.dropbox.com/s/z5e4try2m6yqssp/new_faq.tar.gz?dl=0

In "faq_html" I've left the HTML from Drupal as is about from adding a Markdown format header with the question, and a line containing the categories for this question and answer.

In "faq_html" I've used Pandoc to convert the HTML to Markdown.  It does an OK job but it's not perfect.

Let me know which you prefer to edit.  I've haven't checked either version into Git yet.  I will when I hear back from you.

**Comment by mah11** [comment]
Let's go with Markdown - I think it'll be a bit easier to maintain, and as a one-off for pb2 release I can just check each one as I go through my notes on content edits.

**Comment by kimrutherford** [comment]
> Let's go with Markdown

OK.  I've checked in the files here:
  frontend/src/docs/faq/

I've auto-generated matching file names for each question but the file names get ignored when creating the site.  The header line in each file (ie. the question) is used to create HTML IDs like:

    <h1 id="can-i-get-a-file-with-a-specific-set-of-genome-features">Can I get a file with a specific set of genome features?</h1>

I haven't created a page for each category yet.  I plan to do that on Monday.

**Comment by kimrutherford** [comment]
I've finished moving the FAQ content and the categories now have separate pages:
  http://pombase-dev.bioinformatics.nz/faq/locating-genomic-regions

There is still work to do - the headers are too big and there is no summary of the questions at the top of the pages.  Also internal links aren't working correctly yet.  I'll work on these problems on Monday.

**Comment by kimrutherford** [comment]
> the headers are too big

I've improved that.

> there is no summary of the questions at the top of the pages

Do we still want the list of questions at the top?

> Also internal links aren't working correctly yet.

Links to FAQ categories and questions should work now.

The changes are in the preview.

**Comment by mah11** [comment]
> Links to FAQ categories and questions should work now.

The links to categories (left-hand menu) are working, but not links from one FAQ to another. Let me know if you need an example.

I spotted that the URLs for faq-to-faq links had "/faqs/" instead of "/faq/" in the paths (inherited from the organization in EBI drupal), so I changed them. (I'm feeling all clever now because to do it I used sed for the first time in way too many years.) Will that make the links work?

**Comment by kimrutherford** [comment]
> but not links from one FAQ to another

I fixed some of the problems.  My code doesn't cope with links split over two lines.  There were a lot of cases like this from converting the HTML to Markdown:

    [Some
    label](/some/path)

I've fixed those in the Markdown.

Links directly to questions (rather than FAQ categories) weren't working, but mostly should be now.

Unfortunately some won't work because the section IDs from Drupal have some small words removed.  See there are annoying differences like: 
  how-can-i-find-transcription-factors-and-their-targets-pombase
vs
  how-can-i-find-transcription-factors-and-their-targets-in-pombase

I'll have a think about how we can fix those automatically.

**Comment by kimrutherford** [comment]
Those fixes are visible on the dev site.

**Comment by kimrutherford** [comment]
> Unfortunately some won't work because the section IDs from Drupal have some small words removed.

I've fixed the ones I could see with a bit of Perl but I'm sure I've missed some.

**Comment by mah11** [comment]
Thanks - a lot of it is looking good now.

I may or may not get to it before our curator meeting, but soon I'll start going through each FAQ entry manually to update the ones that need it, so I'll take the opportunity to do any more link fixes I spot. Grumble grumble expletive Drupal ...

I'll also draft a blurb for the main FAQ page soon.

**Comment by kimrutherford** [comment]
I've fixed a bunch more bad formatting, some from Drupal and some from Pandoc.  Mostly problems with emphasis using asterisks.  I've committed all the changes.

**Comment by mah11** [comment]
This is as DONE as I can make it for the release. Open new tickets for any problems, further updates, etc.

I have removed "Old" from the main menu FAQ listing. Woohoo!

**Comment by ValWood** [comment]
Brilliant! Thankyou!

**Comment by ValWood** [comment]
wow is that everything..it seems much shorter...

**Comment by mah11** [comment]
that's how repetitious the old one was :P
