### ISSUE TITLE
Update screenshots in the v2 documentation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#337]
Here for example: http://pombase-preview.babraham.ac.uk/documentation/gene-page-gene-ontology

The Markdown files are here:
  https://github.com/pombase/website/tree/master/frontend/src/docs/documentation

The screenshots are here:
  https://github.com/pombase/website/tree/master/frontend/src/assets

**Comment by mah11** [comment]
I'll take new screenshots when everybody agrees things have settled enough.

**Comment by mah11** [comment]
OK, I have made a start - I've committed updated text and a new image file for the basic info at the top of the gene page. If that hasn't broken things, I'll carry on. Woohoo.

**Comment by kimrutherford** [comment]
> If that hasn't broken things, I'll carry on.

It's all OK and is live in the preview.

**Comment by mah11** [comment]
hooray! (not to mention: whew!!)

**Comment by mah11** [comment]
This is as done as it can be, apart from the FAQ (#336) and the advanced search (#507), which have their own tickets. I have removed the message about out-of-date screenshots, as it is now itself out of date. YAY ME!

If you spot anything wrong, odd, or missing after Kim updates the dev site, open new tickets.

**Comment by ValWood** [comment]
YAY you, thanks a bunch for doing this. I'll attempt to write something for the search soon for editing...

I'll have a  quick scan....
