### ISSUE TITLE
ensembl browser links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#338]
We should add links from the new gene pages to Ensembl fungi, so folks can still get to the browser

http://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/Summary?g=SPBC11B10.09;r=II:1500197-1502095;t=SPBC11B10.09.1;db=core

(this is the same as pombase except it is brown....)

**Comment by kimrutherford** [comment]
I've added a text link and made the inline browser image a link too.  If that's what you were thinking of could you close this issue?

**Comment by ValWood** [comment]
no hurry but in P1 we go to the location tab. I think this should continue as the other tabs are just to confusing (and don't load easily)

**Comment by kimrutherford** [comment]
Do you mean this page?:

http://fungi.ensembl.org/Schizosaccharomyces_pombe/Location/View?db=core;g=SPAC24B11.06c

**Comment by ValWood** [comment]
yes, i think thats the one people like to land on....

**Comment by kimrutherford** [comment]
I've changed the link.

**Comment by kimrutherford** [comment]
I didn't mean to close that.  Please let me know if the link is OK now.
