### ISSUE TITLE
line wrapping of genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/website#339]
![ark1 wrapping](https://cloud.githubusercontent.com/assets/7359272/26119216/6f7600e2-3a64-11e7-8f77-61693e9b5471.jpg)

can we prevent this wrapping?

**Comment by kimrutherford** [comment]
> can we prevent this wrapping?

If we do that the table gets too wide on narrow screens like mobile phones.  I'll work on it.

**Comment by ValWood** [comment]
hmm, maybe line wrap is OK, but minimunm 5/6 chars, that way   most deletion /short names will not be split?

**Comment by ValWood** [comment]
remove milestone if not quick

**Comment by kimrutherford** [comment]
> maybe line wrap is OK, but minimunm 5/6 chars

That's tricky.  But I've made some changes that may help (#227).  I checked the ark1 page and it looked OK for me.

**Comment by ValWood** [comment]
yep
