### ISSUE TITLE
organize external links

### ISSUE THREAD

**Issue by mah11** [pombase/website#34]
Two thought on external links:
- In the big set of all external links, group them by type (requires curators to pick some groups, and preferred order)
- Some links should also appear in the relevant gene page section (curators to identify which ones go where)

**Comment by ValWood** [comment]
shiny new ticket for this ;)
https://github.com/pombase/website/issues/88

includes your thoughts already...

**Comment by mah11** [comment]
> shiny new ticket for this ;)

Why? What's the benefit? If there's already a ticket for a topic, just use it, instead of pointless ticket proliferation.

**Comment by ValWood** [comment]
Because I did not find this until I had made the new ticket which is much more comprehensive.

No ticket pointless ticket proliferation. This one is closed.

**Comment by ValWood** [comment]
Note that I am creating a grouping ticket for each section as requested by Kim.

I thought I would do this one as its easy. Then I was collecting the related tickets to link to and I found this one.

**Comment by mah11** [comment]
There are now two tickets where one was doing the job. That's ticket proliferation.

**Comment by ValWood** [comment]
I DID NOT SEE THIS FUCKING TICKET!!!!
