### ISSUE TITLE
link PR ID+ gene

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#340]
Can we link the PR ID to the gene?

E.g.
gef1Δ is annotated to 
normal duration of protein localization to cell division site
affecting **cell division control protein 42, GTP-bound form (Schizosaccharomyces pombe)**

but cdc42 is not shown in the target of section, would be neat if it did. Guessing the mapping isn't straight forward, I think we have discussed this before?

<img width="444" alt="screen shot 2017-05-17 at 11 09 20" src="https://cloud.githubusercontent.com/assets/12727506/26166657/6429d96a-3af1-11e7-970e-1caac96f1511.png">

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/67
