### ISSUE TITLE
duplicated "show details" in MF section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#342]
On the rsv1 gene page the "show details" link is shown twice in the MF section

<img width="756" alt="screen shot 2017-05-18 at 14 22 39" src="https://cloud.githubusercontent.com/assets/12727506/26222015/ab260e58-3bd5-11e7-8bfd-2e95abfa24a0.png">

**Comment by kimrutherford** [comment]
It's because of this change:
  https://github.com/pombase/website/issues/159#issuecomment-299691474

Let's have a chat about it on the next call and decide how to improve things.

**Comment by ValWood** [comment]
Kim said in other ticket:
Next I'll fix things so there is just one "Show details ..." at the top. I'm releasing before that's done so you can have a look at the MF section to make sure you're happy with grouping binding terms separately.

**Comment by ValWood** [comment]
#159 (comment) duplicate
