### ISSUE TITLE
2016 gene characterization totals

### ISSUE THREAD

**Issue by ValWood** [pombase/website#345]
need to add 2016 totals
http://www.pombase.org/status/gene-characterisation-statistics-history
to history

last time!

can get these either via kim, or old contigs and grepping colour also works.
closest date will do...
will did them out, will include this graph in "unknowns" paper...

**Comment by mah11** [comment]
beginning, middle, or end of 2016?

**Comment by ValWood** [comment]
I usually do the totals close to the end of the year. No hurry for this so if we do high priority stuff and see who gets to it first....I guess it isn't a big task, I can dig numbers out  later ....

**Comment by ValWood** [comment]
actually doing it now. I meant to dig the number out for you to add.

**Comment by ValWood** [comment]
inferred 2034
published 2227
unknown 503
pombe 149
schizo 190
dubious 55
Dec 2012

**Comment by mah11** [comment]
should that date be Dec. 2016?

(also, v small point, but previous entries have the day as well. 2016-12-31?)

**Comment by mah11** [comment]
still 13 transposon?

**Comment by ValWood** [comment]
Yep that will never change without more sequence...

**Comment by ValWood** [comment]
The reason there were 11 for a while is that the 2 frame-shifted ones were classified as pseudos...

**Comment by ValWood** [comment]
I used 20160912/

(I really don't know if that is  12th Dec or 09 Sept.  As you know I am useless with dates and times...its all a blur to me...)

**Comment by mah11** [comment]
That's 12 Sept. Dates are YYYYMMDD, so I can either run with 12 Sept. or you can use 20161231. Most of the other entries in the history table aren't tidy year-end dates anyway.

**Comment by ValWood** [comment]
I didn't spot  20161231 (I probably would have figured out that was the end of the year)

These numbers are OK...its slightly arbitrary/ball park because the classification has got stricter over time too...

**Comment by mah11** [comment]
went with 2016-09-12
