### ISSUE TITLE
ordering of extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#346]
can we put binds before during (its odd because I was sure we already did).

Isn't this in a config somewhere?

v

![order](https://cloud.githubusercontent.com/assets/7359272/26285605/1633fcb0-3e4b-11e7-9ce0-8df7d3cc5764.jpg)

**Comment by kimrutherford** [comment]
Which gene page is that?

The order is configured in pombe-embl/website/pombase_v2_config.json and the various binds extensions should come before during.

Currently these relations should appear first (in the order shown):

      "directly_positively_regulates",
      "directly_negatively_regulates",
      "has_direct_input",
      "has_input",
      "has_regulation_target",
      "binds",
      "involved_in",
      "part_of",
      "occurs_at",
      "occurs_in",
      "added_by",
      "added_during",
      "present_during",
      "in_presence_of",
      "removed_by",
      "removed_during",                                                                                                                                                                       
      "absent_during",
      "has_expressivity",
      "has_penetrance"

then all other extension are shown next in an arbitrary order.

except "happens_during" and "exists_during" always come last.

**Comment by ValWood** [comment]
not sure but this page has an e.g. too
http://preview.pombase.org/gene/SPCC736.12c

**Comment by ValWood** [comment]
heres another with "binds" at the end
http://preview.pombase.org/gene/SPCC645.07

**Comment by kimrutherford** [comment]
This is fixed now.  The ordering code was getting it wrong in the case where some extension relations had a gene as the range and some had an ontology term.
