### ISSUE TITLE
Should we show a product length for pseudogenes?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#347]
In v2 we show the product length for pseudogenes?  Should we?  PomBase v1 doesn't show it.

eg. "349 aa" here: http://preview.pombase.org/gene/SPAC212.10

**Comment by ValWood** [comment]
we also need to review all pseudo genes.
https://github.com/pombase/curation/issues/21

If a gene has a single frameshift, it could be an error in the sequence we represent as a frameshift and call it "coding". We should only use pseudogene for things which are really degraded...

**Comment by ValWood** [comment]
oh this was the comment I put earlier, but fogot to click "comment"

I don't think we should show length or size for pseudo.
