### ISSUE TITLE
Add sequence download section on the gene pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#348]
For now make it more or less like in PomBase v1.

**Comment by kimrutherford** [comment]
I've added a basic sequence download section on the gene page.  It's just called "Sequence" for now.

It's not finished yet - there is no way to download the translation or the up or downstream sequences.  And I haven't implemented the "Highlight Sequence Regions" option yet.  I'll do those bits next.

**Comment by kimrutherford** [comment]
I've added an ugly toggle button that lets you get the translated sequence.  You might need to shift-reload.

I've also added a prototype for fetching the flanking sequence.  Tomorrow I'll check that it actually returns the right sequence.

**Comment by ValWood** [comment]
Wow its very nice!!!! and its very late!

Sorry I didn't look before, just went to dentist..... I have to have a tooth extracted Thursday ;(

**Comment by kimrutherford** [comment]
> Tomorrow I'll check that it actually returns the right sequence.

It didn't.  :-)

The up and downstream sequence were swapped for reverse strand genes.  Fixed now.

**Comment by kimrutherford** [comment]
I've added the sequence length and a few other details to the header of the downloaded sequence.  Mostly because I found that useful when using other databases in the past.

Show we keep the "Show sequence ..." / "Hide sequence ..." toggling or always show the full sequence section?

**Comment by kimrutherford** [comment]
I think the only thing missing compared to PomBase v1 is colouring of the transcript parts.  Is that needed for the release of v2?

**Comment by ValWood** [comment]
I don't think so.
Its very nice...

**Comment by ValWood** [comment]
>keep the "Show sequence ..." / "Hide sequence ..." toggling or always show the full sequence section?

not sure..... any prefs?

**Comment by ValWood** [comment]
> The up and downstream sequence were swapped for reverse strand genes. Fixed now.

Always a gotcha. I have to admit...i'm not even checking  this stuff ;)

**Comment by ValWood** [comment]
I used to check everything because It was usually wrong...

**Comment by kimrutherford** [comment]
I'd like to close this issue.  We haven't decided about this:

> Show we keep the "Show sequence ..." / "Hide sequence ..." toggling or always show the full sequence section?

After seeing it in action my preference is to default to showing the full section by default.

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
> After seeing it in action my preference is to default to showing the full section by default.

The sequence section is now visible by default.  It's easy to change if needed.  I've left the "Hide sequence ..." link.  Let me know if I should remove it.
