### ISSUE TITLE
Gene page Transcript section?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#350]
PomBase v1 has a "Transcript" section.  Which bits from that section do we want in v2?

**Comment by ValWood** [comment]
shoud we just have:
Exons	1500197..1500243, 1500286..1500376, 1500445..1500613, 1500686..1500986, 1501088..1501393, 1501448..1502095	
CDS	1500340..1500376, 1500445..1500613, 1500686..1500986, 1501088..1501393, 1501448..1501528

in the sequence section for reference and dump the rest?
I don't think we need the transcript map particularly, its huge and you can see this in the browser image...

**Comment by kimrutherford** [comment]
> I don't think we need the transcript map particularly, its huge and you can see this in the browser image...

I've grabbed the PomBase v1 images for the transcript map.  Since it's much like the protein domain image, it's very easy add them (and a link to Ensembl) to the page now if you change your mind.

**Comment by ValWood** [comment]
We decided we don't need the image map at the moment

The sequence section can be"sequence and coordinates"
and coordinates can be in a separate sub section.

**Comment by ValWood** [comment]
I don't think this is critical for public release.....even though it is on the current site I never used it. If people miss it it can be at the top of the list after release....

**Comment by ValWood** [comment]
need to find out which parts people use and if we need to reinstate fully

**Comment by Antonialock** [comment]
have asked Jurg/s group

**Comment by ValWood** [comment]
also from
https://github.com/pombase/website/issues/60
add "coding sequence length" to transcript section #60


This would be the length of the predicted coding sequence, i.e. the sum of the lengths of coding exons (or coding parts of exons). I guess this could go under "Transcript Structure", either above or below the table of coordinates, if the display organization remains relatively unchanged.
--

**Comment by ValWood** [comment]
@Antonialock  any response from Jurg's group?

**Comment by Antonialock** [comment]
No replies to that email. I had a look at the tickets I opened after the last group meeting but I didn't open anything with regards to this.

have asked again..

**Comment by ValWood** [comment]
I'm closing this as we don't have any definite actions and nobody ever said that they missed this section.
We can reconsider in the future when we have alternative transcripts it will be much more useful.
Making a note in the "future" doc
