### ISSUE TITLE
genotype grouping

### ISSUE THREAD

**Issue by ValWood** [pombase/website#352]
There might be an open ticket for this...

here is an example
http://preview.pombase.org/genotype/e70a1374f7a8719d-genotype-3

Gene	Allele	Type	Expression
nda3	nda3-KM311(unknown)	unknown	Not assayed

http://preview.pombase.org/genotype/1275ee66e3ff4666-genotype-2
Gene	Allele	Type	Expression
nda3	nda3-KM311(unknown)	unknown	

Expression here is blank...not sure why, maybe these are from Artemis but they seem to be newer phenotypes

Anyway these should group together.

We also need a page which groups a particular genotype regardless of background...
(can discuss this on Thursday)

**Comment by kimrutherford** [comment]
> We also need a page which groups a particular genotype regardless of background...

That's mentioned here too: https://github.com/pombase/website/issues/284#issuecomment-297967038

**Comment by ValWood** [comment]
moved to https://github.com/pombase/website/issues/284
