### ISSUE TITLE
allele/genotype filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#353]
I think we decided we did not need to do this since we have the genotype page.

However I think it might still be useful.

Especially if you could filter out specific alleles that you were not interested in too.

for example
http://preview.pombase.org/gene/SPBC26H8.07c

Also  an allele/genotype list/table might be useful.
If you could see a list of which alleles are available and their descriptions without needing to scroll through the phenotype list...

We should discuss this on a call after @mah11 back

**Comment by mah11** [comment]
One use case in legacy PomBase is in the FAQ on finding essential genes: we direct people to search for viable or inviable cell population terms, and only null alleles.

We can omit that part from the updated FAQ and just send people to the viability summary file if you prefer.

**Comment by ValWood** [comment]
yep lets do that. We can bump this ticket up if all of the others get done...

**Comment by ValWood** [comment]
Des this fully overlap with 
https://github.com/pombase/website/issues/250
?

I  don't really understand/remember what this one is.....

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/250 we think these are the same
