### ISSUE TITLE
term landing pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#357]
From here:
http://pombase2.aska.gen.nz/browse-curation/fission-yeast-go-slim-terms

I land on this page

![land](https://cloud.githubusercontent.com/assets/7359272/26491209/8adb633c-4206-11e7-9de0-06d76f48a1da.jpg)

**Comment by ValWood** [comment]
rather than
![page](https://cloud.githubusercontent.com/assets/7359272/26491248/b448f784-4206-11e7-80b7-4b730f133fa6.jpg)


(this is the same issue in the ticket I closed yesterday, which I thought had not happened for a while...after I closed the ticket I did notice  it again).

This happens *even * if the last type of page I was viewing was the "default" page.

**Comment by ValWood** [comment]
aside: should we also put the def on the "genes annotated" page ?

**Comment by kimrutherford** [comment]
> rather than this "default" page

I've changed the links on the go slim page to point to the main term details pages rather than the term gene list.

**Comment by kimrutherford** [comment]
> aside: should we also put the def on the "genes annotated" page ?

I'm neutral on this.  Should I add the definition?

**Comment by ValWood** [comment]
it's not so important if the landing page is consistently the one with the def.

I'll close, can reopen if anyone thinks we should.
