### ISSUE TITLE
missing data in target of section?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#359]
mal3 has

ATPase activator activity has_direct_input tea2

this doesn't show in the target of section for tea2

**Comment by ValWood** [comment]
come to think of it the relationship must be odd in some way because we usually convert has_direct_input to has_substrate (note to self this one could be "directly positively regulates)

so first question  find out what is wrong, and how it slips through

**Comment by mah11** [comment]
This needs a configuration entry, analogous to the one for GO:0005085 in pombe-embl/website/pombase_v2_config.json .

**Comment by mah11** [comment]
done
