### ISSUE TITLE
display all annotated features  in genome browser (cen, dg, repeat, etc)

### ISSUE THREAD

**Issue by mah11** [pombase/website#36]
Make sure the genome browser shows all of the features within centromeres such as the cores (cnt) and various repeat units (imr, dg, dh, etc.). Coordinates are in the Artemis contig files.

**Comment by ValWood** [comment]
All annotated  features in config files with SO labels.....

**Comment by kimrutherford** [comment]
There was a bug in the GFF writer which meant only one non-gene feature of each type was written to the GFF files.  I've fixed that so the centromeres and all the other non-gene genome features should be visible in JBrowse tomorrow.

(I thought there weren't many non-gene features in JBrowse but I didn't think to investigate)

**Comment by kimrutherford** [comment]
Fixed.  You might need to shift-reload:
https://www.pombase.org/jbrowse/index.html?loc=II%3A1575051..1671050&tracks=DNA%2CPomBase%20features&highlight=

**Comment by ValWood** [comment]
fab!
