### ISSUE TITLE
Show ontology versions on website

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#361]
I can't see an issue about this so:

When we have a page with detailed stats and information about each release we should include the dates or versions of each ontology we use.

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/38

this is the current version history. I thought this used to be linked from the bottom of the gene page, but maybe I imagined this.

http://www.pombase.org/about/version-history

**Comment by kimrutherford** [comment]
Ah, I copied it across but it doesn't update automatically:
 http://preview.pombase.org/about/version-history

**Comment by ValWood** [comment]
yeah we don't have ontology versions in there....

**Comment by kimrutherford** [comment]
First we need to get the ontology versions into Chado.  I've made an issue for that: pombase/chobo#9

**Comment by kimrutherford** [comment]
I've changed Chobo to store the CV version in Chado when loading an OBO file.  It stores the 'data-version' or 'date' header depending on what's available in the OBO file.

Tomorrow's Chado should have the ontology versions.  If that works I can add the versions to a page on the web site.

**Comment by kimrutherford** [comment]
The ontology versions now appear at the end of the data sources page: https://www.pombase.org/about/data-sources

The formatting is a bit odd  because the versions are as they appear in the OBO files.  PSI-MOD for example looks like "04:11:2011 16:54" which is a bit daft.  Who decided that would be a good date format?  We can fix that.  

In the page it looks like:

 - GO: releases/2018-02-02
 - FYPO: releases/2018-02-13
 - PSI-MOD: 04:11:2011 16:54

We can probably drop the "releases/" bit from the GO and FYPO versions.

I've only included GO, FYPO and PSI-MOD to start with.  Others can be added by editing data-sources.md

Tags like this in the docs will be replaced by the version number from Chado when the page is shown:

    <app-cv-version cvName="fission_yeast_phenotype"></app-cv-version>

Here is the full list of ontology names and versions from the current Chado.  Any of these can be included in the docs:

name             |value
-----------------------------|---------------------------
 PSI-MOD                     | 04:11:2011 16:54
 PSI-MOD_extension_relations | 13:07:2012 17:15
 SO_feature_relations        | 13:07:2012 17:15
 biological_process          | releases/2018-02-02
 cell                        | 13:01:2012 09:59
 cellular_component          | releases/2018-02-02
 chebi_ontology              | 89
 disease_associated          | 03:08:2017 11:53
 feature_property            | 10:06:2005 15:07
 fission_yeast_phenotype     | releases/2018-02-13
 fypo_extension_relations    | 06:07:2012 17:25
 fypo_extensions             | 13:08:2012 11:25
 iao                         | 13:08:2012 11:25
 molecular_function          | releases/2018-02-02
 pato.ontology               | releases/2015-11-18
 pb_quiescence               | 27:02:2013 10:05
 phenotype_condition         | 02:02:2018 19:13
 pombase_has_qualifier_range | 13:07:2012 17:15
 pombase_relations           | 1.0.
 protein                     | 49.0.
 quality                     | releases/2015-11-18
 sequence                    | so-xp/releases/2015-11-24/so-xp.owl

**Comment by mah11** [comment]
Nice. Yeah, let's use the ISO yyyy-mm-dd format generally. Good to know we can add more to the page. Thanks :)

**Comment by kimrutherford** [comment]
> Yeah, let's use the ISO yyyy-mm-dd format generally.

I've fixed that for tomorrow morning's update.

**Comment by kimrutherford** [comment]
> Yeah, let's use the ISO yyyy-mm-dd format generally.

That change is in the main site now.
