### ISSUE TITLE
GO slim  links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#363]
Just discussed with Kim, current links are unclear

- [x] Change the text for the links at the bottom of the slim page:
Genes not covered by the slim (Total)
then:
Genes with a process annotation, but not in any of the categories above
Genes with no biological process annotation

- [ ]  We could also include the "total slimmed"
but we need to make it clear that this is not to be confused with the sum total of the categories.

**Comment by ValWood** [comment]
reminder: 
The GO slim annotation counts do NOT correspond to a gene product count. Although each total gives the number of gene products annotated to a term, the total number of annotations to slim terms will not equal the number of gene products in the genome because many gene products are annotated to multiple terms. It is therefore not meaningful to sum the numbers and present GO slim data as a pie chart, because the fraction of the total for each term represents the froction of total annotations rather than the fraction of gene products annotated.

**Comment by kimrutherford** [comment]
> reminder:

Where on the page should the reminder go?  Just before the table?

**Comment by ValWood** [comment]
We said we would reduce this text. 
I now think it isn't very anyway clear.   

We say  "The GO slim annotation counts do NOT correspond to a gene product count....."

but this should be refined to

The individual totals for GO slim classes represent a gene product count for a class. However, that sum total of these numbers IS NOT equivalent to a count of an organism's gene products with an annotated process, because gene products can be annotated to multiple terms. It is therefore not meaningful to sum these numbers and present GO slim data as percentages in a pie chart.
The total provided here is the  count of unique gene products with one or more annotations to one or more GO slim classes.

when we decide on actual text, replace point 1 here:
http://preview.pombase.org/browse-curation/fission-yeast-go-slimming-tips

I think this text should go somewhere at the bottom.

**Comment by ValWood** [comment]
no hurry lets discuss  on call.

**Comment by ValWood** [comment]
Midori will draft

**Comment by mah11** [comment]
I'll polish the comment and bleat at Kim if I can't find where to put it.

**Comment by mah11** [comment]
It really boils down to a short pithy statement:

Note that the counts in the "Genes" column are not additive, because many gene products are annotated to more than one term in the GO slim.

**Comment by mah11** [comment]
page edited

**Comment by mah11** [comment]
oops, overlooked outstanding checkbox

**Comment by ValWood** [comment]
Perfect ;)

**Comment by kimrutherford** [comment]
> We could also include the "total slimmed"

Is that the text you'd like for that total?

**Comment by ValWood** [comment]
I think that text should go immediately  below the table.

The total should be described as
"Total slimmed gene products"

I think then most people will be able to figure it out....

**Comment by ValWood** [comment]
This is non critical, but it's really really quick.
...and the Go slim pages are very frequently accessed....

Outstanding actions
http://pombase2.aska.gen.nz/browse-curation/fission-yeast-go-slim-terms
 
- [ ] Add "Total slimmed gene products"
with text
Note that the counts in the "Genes" column are not additive, because many gene products are annotated to more than one term in the GO slim.

**Comment by kimrutherford** [comment]
> Add "Total slimmed gene products"

That's done if you reload.  The total is 4457.  Does that sound about right?

**Comment by ValWood** [comment]
Yes it does.
It's a bit odd because the slimmed includes protein coding and RNA.

The un-slimmed is only protein.
So could we change:

Total slimmed gene products: 4473
to
Total slimmed gene products (protein and ncRNA) : 4473


and

Genes not covered by the slim (876 in total):
to 
"Protein coding genes not covered by the slim"

I don't want to add ncRNAs to this because there are 1000s, it wouldn't make sense to include right now.

**Comment by kimrutherford** [comment]
> So could we change:

I've made those changes too.  Please close the issue if it looks OK.

**Comment by ValWood** [comment]
yep!
