### ISSUE TITLE
GO slim terms not annotated lists

### ISSUE THREAD

**Issue by ValWood** [pombase/website#364]
- [x]  exclude dubius
- [x]  exclude transposons

That will probably do it. The other issues are related to GO, or curation. I'm working on reducing the number which do not map to the slim today. Should improve tomorrow.

**Comment by ValWood** [comment]
another "Gotcha"

- [ ]  exclude NOT annotations from slim set
 http://preview.pombase.org/gene/SPCC736.09c
http://preview.pombase.org/gene/SPAC30.03c
(I think these are the only ones which cause a gene to be slimmed that would otherwise have no slim process, but applies to any other NOTs

**Comment by kimrutherford** [comment]
I've removed dubious and transposon genes and excluded NOT annotations.

Those changes bring the count down to 1005.

I'm still working on adding the counts and links for the non-slim genes to the go slim page.

**Comment by ValWood** [comment]
> I've removed dubious and transposon genes and excluded NOT annotations.

Did this work only partially?
![not](https://cloud.githubusercontent.com/assets/7359272/26731885/6b99cd2c-47ad-11e7-8200-3d9f6137629c.jpg)


Note that I am now adding an explicit annotation to "transmembrane transport". Its a transmembrane transporter, just not biotin, so it WILL slim to TM transport tomorrow.
v

**Comment by ValWood** [comment]
OK, this  (SPAC1B3.15c) already has

/GO="aspect=P; term=transmembrane transport; GOid=GO:0055085; evidence=ISM; db_xref=GO_REF:0000050; with=Pfam:PF07690; date=20160526"

so the problem seems to be that  the term is recognsed, and SPAC1B3.15c is slimmed appropriately. However, "transmembarne transport is not displayed (presumably the NOT is ignored for filtering)

**Comment by kimrutherford** [comment]
> OK, this (SPAC1B3.15c) already has

Looks like there are two bugs.  :-(

The transmembrane transport annotation is missing from Chado.  Maybe there is a problem with the GO filtering and NOT annotation.

But a slim term is showing anyway so look like there's a web problem too.

I'll work on that.

**Comment by kimrutherford** [comment]
> Maybe there is a problem with the GO filtering and NOT annotation.

Turns out that we have an very old issue about this that we punted to the future:
  https://github.com/pombase/pombase-chado/issues/35

I guess we need to think about it?

**Comment by kimrutherford** [comment]
> But a slim term is showing anyway so look like there's a web problem too.

I've fixed that problem at least.  The web code now correctly handles NOT annotations.  We still need to fix the GO filtering.

**Comment by ValWood** [comment]
http://preview.pombase.org/gene/SPAC1B3.15c
needs to map to "transmembrane transport " in the slim

**Comment by ValWood** [comment]
- [ ]  So, the outstanding task in this ticket is to  fix the GO filtering so that 
non NOT annotations are not filtered against NOT annotations.  Would the easiest way to do this be just to "ignore NOT annotations for the purposes of filtering/slimming "?
http://preview.pombase.org/gene/SPAC1B3.15c

If anything else needs to happen here please update the ticket.
If it isn't clear add "discuss". 
It isn't critical for release, and I don't know of another example.
I will add the quick label here without the  milestone.

**Comment by ValWood** [comment]
Turns out that we have an very old issue about this that we punted to the future:
pombase/pombase-chado#35
closing as duplicate
