### ISSUE TITLE
don't show slim header when no slim terms

### ISSUE THREAD

**Issue by ValWood** [pombase/website#366]
![don t show if no slim terms](https://cloud.githubusercontent.com/assets/7359272/26554449/083c476e-4488-11e7-8676-41f892c065af.jpg)

because it isn't clear what it is for...

**Comment by ValWood** [comment]
Or maybe we should keep it as it provides the link to the slim...thoughts?

**Comment by kimrutherford** [comment]
Maybe in that case it should say "This gene is not in any biological process GO Slim category"  (and link to the GO slim page in case someone is curious)

**Comment by ValWood** [comment]
That would be good....another way to hook people in to the degree of characterisation....

**Comment by kimrutherford** [comment]
I've added that text and a link.  Let me know if it's OK.

**Comment by ValWood** [comment]
yep, small refinement...

"This gene *product* is not *currently assigned to* any biological process GO Slim category"

**Comment by kimrutherford** [comment]
> "This gene product is not currently assigned to any biological process GO Slim category"

Fixed.  But you'll need to reload.
