### ISSUE TITLE
updating the slim set

### ISSUE THREAD

**Issue by ValWood** [pombase/website#367]
For now we have a static slim set, eventually will be generated using ontology sub sets.

In the meantime if we alter the slim we will  ned to edit the file where the slim is defined.

The slim should currently contain
	"meiotic nuclear division" not	"meiotic cell cycle"

**Comment by kimrutherford** [comment]
> In the meantime if we alter the slim we will ned to edit the file where the slim is defined.

The file is in SVN: pombe-embl/website/[pombase_v2_config.json

The key is: go_slim_terms

> "meiotic nuclear division" not "meiotic cell cycle"

Fixed.
