### ISSUE TITLE
browser track for TSS atlas identified by CAGE (Olaf)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#368]
Once we get JBrowse up and running we should make this  one of the first datasets to host as we will need it to refine gene structures as proposed:
https://github.com/pombase/curation/issues/633

**Comment by ValWood** [comment]
Note from Olaf:

We are very excited about the interest in the community of having our TSS atlas identified by CAGE publicly available through PomBase. How should we proceed?

 

We already have most data ready as files suitable for most genome browser. In details:

 

•                          For every stress/medium combination we have the average CAGE signal as a BigWig-file (one for each strand)

•                          CAGE tag clusters, representing discrete TSS events, as a bed-file (including the TSS peak in the thickStart/thickEnd columns)

 

Additionally, we could include bed-files containing only CAGE TSS that are expressed differentially between the different conditions.

 

We are quite  flexible about file formats though, so please do let us know if some other way of storing the data is more appropriate for PomBase.

**Comment by ValWood** [comment]
@MalteThodberg
Need to keep Malte and Olaf posted

**Comment by kimrutherford** [comment]
Olaf says some of their data is in BigWig format so maybe we could try this soon?

**Comment by ValWood** [comment]
OK, 
@MalteThodberg
We can use this as a test case for a new dataset as we set up the procedure for submission.

our beta JBrowse instance is here:
https://www.pombase.org/jbrowse/index.html?loc=II%3A485563..499792&tracks=DNA&highlight=

val

**Comment by MalteThodberg** [comment]
Dear all,

Our preprint is out (The paper itself is still in revision): https://www.biorxiv.org/content/early/2018/03/13/281642

We have already deposited all the data on GEO Series GSE110976 (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110976).

I'll be happy to assist in uploading the data!

**Comment by kimrutherford** [comment]
I've put the spreadsheet from Malte in Dropbox:
  pombase/PomBase_website/thodberg_cage_dataset/ThodbergWithEdits2.xlsx

**Comment by Antonialock** [comment]
should I copy it into the master doc?

**Comment by Antonialock** [comment]
@MalteThodberg do we need to wait with displaying the data until paper is out or canwe just go live (seeing the data is in GEO in any case?)

**Comment by kimrutherford** [comment]
> should I copy it into the master doc?

Do you mean into the JBrowse configuration table?  Yes, please.  It will be a while before I can get the datafiles set up though.

**Comment by MalteThodberg** [comment]
@Antonialock Yes, it's perfectly fine to make it public, as it is already public on GEO and bioRxiv

**Comment by Antonialock** [comment]
ok, makes sense, just thought I'd make sure :-) @MalteThodberg

**Comment by kimrutherford** [comment]
I've put the BED file and the bigwig files in the right place on the web server.  I needed to change some of the the chromosome IDs in the bigwig files to match what JBrowse expects:
 - MT -> mitochondrial
 - AB325691 -> chr_II_telomeric_gap

The URLs are:

https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_EMM_exp_minus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_EMM_exp_plus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_EMM_nitro_minus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_EMM_nitro_plus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_TSSs.bed
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_exp_minus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_exp_plus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_H2O2_minus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_H2O2_plus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_heat_minus.bw
https://www.pombase.org/external_datasets/Thodberg_GSE110976/GSE110976_YES_heat_plus.bw

**Comment by Antonialock** [comment]
Thodberg data added to metadata file. 

@MalteThodberg would it make sense to relabel the track description of the bed file:
'Most frequently observed transcription start sites across 5 growth conditions'
to clarify that it shows the commonest TSSs?

**Comment by ValWood** [comment]
That's very long!

Maybe just "consensus transcription start sites"

**Comment by Antonialock** [comment]
yeah agree 'Most frequently observed' is long, but I thought it isn't really a "consensus"? (or is it? semantics! "Commonest" sounds ridiculous)

**Comment by ValWood** [comment]
@MalteThodberg ?

**Comment by kimrutherford** [comment]
> Thodberg data added to metadata file.

Thanks!  I needed to add "forward strand" and "reverse strand" to the track labels to make them unique, otherwise only one of the strand was visible.

The new tracks are live in the main site.  You might need to shift-reload if you've used JBrowse within the last hour (the track info is cached in the browser for an hour).

If you make any fixes to pombase_jbrowse_track_metadata.csv let me know and I'll re-release the site.  It's quite quick to re-release if only the JBrowse data is the only change - only 2-3 minutes.

**Comment by ValWood** [comment]
Oh it looks very nice.

I'm not clear about how the scale bar works.   Does the scale bar scale according to *everything* in a view? or just the proximal element.
It's really neat...

**Comment by ValWood** [comment]
@MalteThodberg 
 We would like to feature on the front page "Research Spotlight" https://www.pombase.org/.
Could you provide an image of the correct aspect ratio? (it can be a composite)...just something eye-catching from the paper.

**Comment by ValWood** [comment]
We will make an announcment and the front page rotation coincide with publication.

**Comment by kimrutherford** [comment]
> I'm not clear about how the scale bar works. Does the scale bar scale according to everything in a view?

Yep, it changes the scale based on what's currently in view.

**Comment by ValWood** [comment]
Something like

![eg](https://user-images.githubusercontent.com/7359272/40544946-e0c30d6a-6021-11e8-8bc5-aba783d3f9ae.jpg)

but it's better not to have "small text" if possible

**Comment by Antonialock** [comment]
> To me it is a consensus if it's the commonest TSS across all conditions?
>....it isn't necessarily a consensus sequence, but it's a consensus position ;)

yeah fine, sounds good...stay tuned for track description updates :)

**Comment by Antonialock** [comment]
> Thanks! I needed to add "forward strand" and "reverse strand" to the track labels to make them unique, otherwise only one of the strand was visible.

Ah shoot, I had started that task but then went for group meeting, lunch etc. 

> If you make any fixes to pombase_jbrowse_track_metadata.csv let me know and I'll re-release the site. It's quite quick to re-release if only the JBrowse data is the only change - only 2-3 minutes.

I have done quite a few changes to the descriptions so it would probably be good to reload!

**Comment by MalteThodberg** [comment]
Coming in late to the discussion:

- For the BED-track naming: I think "TSSs across 5 growth conditions" or "Consensus TSSs across 5 growth conditions" would both be good.

- I can provide a pretty looking figure from the preprint as a PDF: What is you desired aspect ratio?

- I can see the BED-track in the new browser, however I get "Error: jDataView length or (byteOffset+length) value is out of bounds" when trying to view BigWig tracks.

**Comment by kimrutherford** [comment]
> I can see the BED-track in the new browser, however I get "Error: jDataView length or
> (byteOffset+length) value is out of bounds" when trying to view BigWig tracks.

Thanks for checking.  Could you let us know which web browser you're using?  I tested in Firefox and Chrome before the announcement went out.  But now it doesn't work for me in Chrome which is strange.  I'll try to fix that today.

**Comment by kimrutherford** [comment]
When I reloaded the page in Chrome it worked fine.  That makes it tricky to debug.  Antonia notice a similar problem a few days ago that also went away after a reload.  I'll do some Google searching to see if others have had this problem.

**Comment by MalteThodberg** [comment]
You are right: I only get the error message using Safari, using Chrome it renders with no errors.

How do you determine the color of tracks? Since CAGE is stranded, it would be nice to match the colors of the consensus TSSs to their corresponding coverage tracks (i.e. forward strand = red and reverse strand = blue).

Is it possible to get the new browser to render the Consensus TSS peaks in the thickStart/thickEnd columns of the BED-file?

**Comment by ValWood** [comment]
Hi @MalteThodberg  I didn't replay about the image aspect ration.
It is https://www.pombase.org/ images on the front page. Approx  1:1.5 (?) @kimrutherford  can say exactly  but it does not need to be precise we can trim.

**Comment by kimrutherford** [comment]
Sorry, I forgot to reply too.  The aspect ratio of our current images is 1:1.62.  An image close to that would be best but as Val says, we can trim or we can pad the images with a little bit of white space if needed.

Thanks!

**Comment by MalteThodberg** [comment]
Sorry for the delay, we have been busy with paper revisions! Here's a possible figure for a research spotlight:

[PomBase_ResearchSpotlight.pdf](https://github.com/pombase/website/files/2098718/PomBase_ResearchSpotlight.pdf)

**Comment by ValWood** [comment]
Hi Malte,

That will be great.

I was also wondering, not I had a closer look at the data, I think Antonia  was correct and the 
"combined" file isn't really a consensus. Its a combined view of all  observed sites.

I think users would find it really useful to see the "consensus" sites, as features on a track. It is difficult to see these on the individual tracks because the expression levels can be so different. In the combined track you can not distinguish  the real features of interest.

i.e the  major  here:

![peaks](https://user-images.githubusercontent.com/7359272/41364590-07bc901e-6f2f-11e8-9a52-2131990187d6.jpg)

**Comment by MalteThodberg** [comment]
That's a very pretty browser picture! :-)

I'm not entirely sure what you mean: The BED-file summarises the basepair-resolution BigWig files into discrete Tag Clusters, corresponding to TSSs. 

You are absolutely right, that there's a huge difference in scale between the BigWig-tracks. Because the CAGE-tags are so accurate they tend to pile up extremely high. That means that some Tag Clusters  superficially look very lowly expressed if they are in the same view as a very highly expressed Tag Cluster. The BED-file is made with and expression cutoff of at least one count-per-million, in at least three samples (out of 15), so they should all be expressed in biological meaningful amounts.

Normally one would force the same scale across all BigWig tracks for better comparison, for example like we do in the paper:

![image](https://user-images.githubusercontent.com/10612774/41465525-c88a56c6-709e-11e8-9ef1-12465ce95960.png)

I don't know if that's a possibility in the new browser?

**Comment by ValWood** [comment]
> That's a very pretty browser picture! :-)

It is!

> I'm not entirely sure what you mean:

It might be useful to see the "consensus" rather than the spread (or in addition)

i.e.
![cons_crop](https://user-images.githubusercontent.com/7359272/41544204-0f31efc6-7310-11e8-8c2e-1280c5487a97.jpg)

...because the CAGE is so sensitive, and many sites will be used hardly at all but are included in the cluster even if 99.99% are at a  discrete site.

Note that here I mean for a single gene/loci, rather than normalizing  levels *between* loci

>You are absolutely right, that there's a huge difference in scale between the BigWig-tracks. 
>Normally one would force the same scale across all BigWig tracks for better comparison, for example like we do in the paper:
> I don't know if that's a possibility in the new browser?

I think it is, but my understanding is that the files need to be pre-processed in some way?
@Antonialock  @kimrutherford  is that correct?

**Comment by ValWood** [comment]
Your first suggestion sounds good.

yup CAGE data from the Li et al
https://github.com/pombase/website/issues/736
https://github.com/pombase/website/issues/735
on our radar.

**Comment by MalteThodberg** [comment]
Thank you!

I can see there's a couple of tracks:
LiTSS_TS1.bed
LiTSS_TS2.bed
LiTSS_TS6.bed
new/LiTSS.bed
new/LiTSS_TS6.bed

Do you happen to know which file was used in the old browser?

**Comment by ValWood** [comment]
I'm not sure, any idea anyone?

**Comment by Antonialock** [comment]
Nope

**Comment by mah11** [comment]
I think the old browser may have had two tracks, one for each file in the "new" subdirectory. I've put more details in #736, since that ticket is dedicated to that dataset.

**Comment by ValWood** [comment]
This was done ages ago.
https://www.pombase.org/reference/PMID:30566651
closing.
If anything is still to do please open a new ticket .
