### ISSUE TITLE
new quantitative expression file

### ISSUE THREAD

**Issue by ValWood** [pombase/website#369]
I created a file for
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=191174

from Matt spreadsheet

Akamatsu_PMID28539404_quantitative.txt

This is a heads up incase I did it incorrectly

**Comment by ValWood** [comment]
Note to self, I stuffed in mass spec, need to double check when in approval. I'll take this one  when it comes through since its one of my pathways (G2/M)

**Comment by mah11** [comment]
Is this really a website task? Checking a file seems more like a curation tracker item ...

**Comment by ValWood** [comment]
Well actually I meant to put it on the chado tracker...

**Comment by mah11** [comment]
surely we don't have too many trackers?? ;)

but once you add the new file in svn I'll eyeball it to see if any problems stand out

**Comment by ValWood** [comment]
It should be there?

**Comment by mah11** [comment]
I didn't see it go by when I did svn update an hour or so ago ... lemme update again ...

**Comment by mah11** [comment]
nope ... sure you committed it?

**Comment by ValWood** [comment]
Oh I just did commit, not add, there now.

**Comment by mah11** [comment]
got it now

did some small fixes:
- added headers
- changed to unix line endings
- fixed date format (removed stray / )

so it looks like it should go into the next load without problems

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
yes wrong tracker but...
http://preview.pombase.org/reference/PMID%3A28539404
