### ISSUE TITLE
addition to enrichment FAQ

### ISSUE THREAD

**Issue by ValWood** [pombase/website#372]
Add something along the lines:

We also recommend that you only use an enrichment tool that allows you to upload a background set representing the genes used in your experiment. This is critical even if you believe your background is the whole genome. Some gene products will likely be absent from any dataset used in an experiment, and  many results exclude ncRNAs which will be increasingly annotated.   To illustrate, if you do not upload a background set for a protein coding gene result list, any small but significant enrichment  to translation  could be obscured by the large number or tRNAs annotated to this term.

http://www.pombase.org/faqs/how-can-i-find-significant-shared-go-annotations-genes-list

**Comment by mah11** [comment]
added a less wordy version on dev
