### ISSUE TITLE
S. cerevisiae gene names for orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#375]
I think these need updating.  Do you get them from SGD periodically?

I spotted this 
![website tracker](https://cloud.githubusercontent.com/assets/7359272/26684267/62dc3424-46de-11e7-92c7-eed6c0d2bdef.jpg)

YDRO89W is names  VTC5 at SGD.

There is no hurry for this but I just wanted to flag.  A 2-monthly update cycle would probably work for this...

**Comment by kimrutherford** [comment]
> Do you get them from SGD periodically?

They come via Ensembl which is probably why they are so out of date.

Related: https://github.com/pombase/pombase-chado/issues/598

**Comment by ValWood** [comment]
Is it possible to tell when the list last changed content? (only if its v. quick). I'll bet you any money that Ensembl update the genome sequence (not important, rarely changing) than they do the gene names (important, changing frequently).

**Comment by kimrutherford** [comment]
2011 :-(

http://www.ensembl.org/Saccharomyces_cerevisiae/Info/Annotation

After the new web site is live, fixing the cerevisiae and human genes is a high priority for me.

**Comment by ValWood** [comment]
I wonder if the gene names  are updated independently of the assembly?
(like GO data). Gene names must have been updated within 5 years ?????

**Comment by kimrutherford** [comment]
Maybe - it's a bit hard to tell from that information page.  It's not clear.

**Comment by ValWood** [comment]
Nothing is.....The front pages are an indication of what lies beneath....

**Comment by mah11** [comment]
S. cerevisiae gene names really _must_ come from SGD, not Ensembl. Would we want anyone to look to Ensembl for pombe gene names?

Promising linky in the Chado ticket where I said the same thing a while back: https://github.com/pombase/pombase-chado/issues/598

**Comment by ValWood** [comment]
They will...

**Comment by ValWood** [comment]
this will resolve itself when the chado ticket is adressed
