### ISSUE TITLE
don't show translation option for RNA gene sequence

### ISSUE THREAD

**Issue by mah11** [pombase/website#377]
In the Sequence part of the gene page, "Translation" is only relevant for protein-coding genes, so don't offer that option for non-coding RNA genes.

**Comment by kimrutherford** [comment]
I've hidden the "Show translation" button and the UTR buttons unless the gene is protein coding.  Currently the button are hidden for psuedogenes too.  Does that make sense?  Would anyone ever need the translation of a psuedogene?

**Comment by kimrutherford** [comment]
> Currently the button are hidden for psuedogenes too.

Actually there is no "Show translation" button for psuedogenes because it just shows "This gene has no transcripts available" in the sequence section.  Should we be showing a transcript sequence for psuedogenes?

**Comment by ValWood** [comment]
hmm, lets say no until
https://github.com/pombase/curation/issues/21 is done (which will be post release for sure)

**Comment by mah11** [comment]
decisions specific to pseudogenes:
1. add ability to see DNA sequence even if we change our minds about point 2.
1a. Only need start coord. to end coord; no fuss about introns vs. exons
2. don't offer translation option for now

**Comment by mah11** [comment]
... and leave out UTRs, upstream & downstream too; let people ask if they want any of that

**Comment by ValWood** [comment]
I'm assuming that  what is left here is post release. I think the general rule is "offer nothing for pseudogenes".

IS this ticket now  related to any feature type other than "pseudogenes".
If not does
https://github.com/pombase/website/issues/428

cover?  can then close?

**Comment by kimrutherford** [comment]
I was about to close this but then I checked a pseudogene page and it failed badly.  :-)

I'll fix that then close the issue.

**Comment by kimrutherford** [comment]
> I'll fix that then close the issue.

I made a new issue since this issue is unrelated: #465.
