### ISSUE TITLE
PubMed search link for literature list

### ISSUE THREAD

**Issue by mah11** [pombase/website#378]
One thing I miss from legacy PomBase is the link to search PubMed for the gene - it sometimes finds papers that aren't cited for annotations, either because they're not curatable types or we just haven't got round to curating them yet.

The legacy placement at the top of the Literature section and "Search PubMed" hyperlink text are fine.

The search is for "(systematic ID or standard gene name OR synonym(s)) AND  (pombe OR fission yeast)".

examples as they appear in search box:

    (SPAC1687.04 OR mcb1) AND (pombe OR fission yeast) 
    (SPBC32H8.12c OR act1 OR cps8 OR pi012) AND (pombe OR fission yeast) 

examples in URL context:

    https://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&term=(SPAC1687.04+OR+mcb1)+AND+(pombe+OR+fission+yeast)
    https://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&term=(SPBC32H8.12c+OR+act1+OR+cps8+OR+pi012)+AND+(pombe+OR+fission+yeast)

We don't need the EuropePMC link in the first instance, and won't unless any users ask for it. It was only ever included as a political sop to EBI, and I've found it useless (further rant available upon request).

**Comment by ValWood** [comment]
Me too, been meaning to mention that.

**Comment by kimrutherford** [comment]
I've added the link (if you reload).  Could you check it and let me know if you'd like the style or formatting of the link changed?

**Comment by mah11** [comment]
that looks fine as is - thanks!
