### ISSUE TITLE
Recent community curated papers

### ISSUE THREAD

**Issue by ValWood** [pombase/website#379]
I notice that the "recently community curated papers"
on the front page are actually "recently approved papers" We frequently tweak annotations and re-approve sessions.

Is there a way to restrict this list to the data of first approval?

![recent](https://cloud.githubusercontent.com/assets/7359272/26724851/73b2433c-4793-11e7-9745-2c5c354c3086.jpg)

**Comment by kimrutherford** [comment]
> Is there a way to restrict this list to the data of first approval?

Not at the moment.  Canto only records the most recent approval.  We could change that though.

In the meantime, we could show the most recently submitted papers that have been approved.  Would that be better?

**Comment by ValWood** [comment]
yes that would work.

**Comment by kimrutherford** [comment]
> we could show the most recently submitted papers that have been approved

I've done that.  Might need a reload.
