### ISSUE TITLE
new page for unmapped genes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#380]
See
https://github.com/pombase/curation/issues/1501

To replace the list of physically unmapped genes on the SF tracker
https://curation.pombase.org/pombase-trac/wiki/PhysicallyUnmappedGenesProteins

now moved to "deprecated pages"

I'm attching a tab delimited file
Format  (alphabetically by allele)

1    allele 
2    PMIDs(comma separated)
3    allelic with x (alleles comma separated)

**Comment by ValWood** [comment]
[physically unmapped.txt](https://github.com/pombase/website/files/1047856/physically.unmapped.txt)

**Comment by ValWood** [comment]
There are a few to track down but these can be added once the file is in place on the website

**Comment by ValWood** [comment]
new file with "mis"

[physically unmapped.txt](https://github.com/pombase/website/files/1047886/physically.unmapped.txt)

**Comment by mah11** [comment]
page now exists

assigning to Kim and leaving open in case I botched adding it to the main Status page and the menu

**Comment by kimrutherford** [comment]
Thanks Midori.  The Markdown looks good.

I needed to adjust the page style slightly to leave a gap between columns to stop it looking look:

![screenshot from 2017-06-03 14-21-05](https://cloud.githubusercontent.com/assets/90474/26749837/f7c89da4-4867-11e7-91e6-03f533a539f8.png)

**Comment by ValWood** [comment]
Looks good. I was going to suggest we link the genes. Durr...

**Comment by kimrutherford** [comment]
> I was going to suggest we link the genes.

I'll fix that.

**Comment by ValWood** [comment]
Good luck trying ;)

**Comment by kimrutherford** [comment]
Oh yeah.  I get why you said "Durr" now.

Should unmapped genes have gene pages?

**Comment by ValWood** [comment]
Hmm I think we have discussed that, but then we would need a way to annotate them. I like the idea but the information isn't particularly useful until you know which gene it is. Then again, if people were aware of the phenotypes they may want to map them.

For now lets not. We could begin to note the phenotypes somewhere if we feel inclined. We'll decide later....
