### ISSUE TITLE
include coiled coil and tm domains in protein feature section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#381]
Need to figure out the best place to get this info. Might be worth asking Rob &  Co

**Comment by kimrutherford** [comment]
I'm looking at the TMHMM output.  There are "inside" and "outside" predictions in the output that we don't show in PomBase V1.

Here's a (truncated) sample for SPAC3H1.09c:

# SPAC3H1.09c-peptide-sequence Length: 656
# SPAC3H1.09c-peptide-sequence Number of predicted TMHs:  10
# SPAC3H1.09c-peptide-sequence Exp number of AAs in TMHs: 225.82069
# SPAC3H1.09c-peptide-sequence Exp number, first 60 AAs:  0
# SPAC3H1.09c-peptide-sequence Total prob of N-in:        0.46158
SPAC3H1.09c-peptide-sequence    TMHMM2.0        outside      1   304
SPAC3H1.09c-peptide-sequence    TMHMM2.0        TMhelix    305   327
SPAC3H1.09c-peptide-sequence    TMHMM2.0        inside     328   352
SPAC3H1.09c-peptide-sequence    TMHMM2.0        TMhelix    353   375
SPAC3H1.09c-peptide-sequence    TMHMM2.0        outside    376   389
...

Compared with:
http://www.pombase.org/spombe/result/SPAC3H1.09c#translation

Do you want to include the inside/outside bits?

**Comment by ValWood** [comment]
no ignore "outside"

**Comment by kimrutherford** [comment]
> no ignore "outside"

So ignore "outside" but include "inside"?

**Comment by ValWood** [comment]
yep. the "inside" are the actual TMM predictions. Outside are just the coordinates between tmm domains....

**Comment by kimrutherford** [comment]
I thought the "TMhelix" rows would be the TM domains?  That seems to be what we have on the V1 pages.

**Comment by ValWood** [comment]
OK in that case I don't understand what inside/ outside means...?

**Comment by ValWood** [comment]
Oh I see. Its just "this region is in-between 2 helices" this region is outside  the helices. 
Ignore , I think this is for computers. Humans can use their eyes for this.

**Comment by kimrutherford** [comment]
The TM data is now included on the gene pages.
