### ISSUE TITLE
transfer of inventories from wiki

### ISSUE THREAD

**Issue by ValWood** [pombase/website#386]
https://curation.pombase.org/pombase-trac/wiki/DrugTargets
already on P1
http://www.pombase.org/browse-curation/drugs-knowns-s-pombe-targets
but not sure it is linked from anywhere obvious?

**Comment by kimrutherford** [comment]
I've added the page to P2:
http://preview.pombase.org/browse-curation/drugs-known-pombe-targets

We need to have a re-think about what goes in each doc section.
