### ISSUE TITLE
Re-implement the motif search, integrated into V2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#387]
Need to copy the motif search script to V2 or maybe re-implement it.  Either way it would be good if it updated automatically.

**Comment by ValWood** [comment]
Did you know that you wrote the original script at the Sanger?   This one has been following  us around.....

And guess what, it still works, it does exactly what we want, it has never broken,  people use it,  and they have never asked for any additional functionality (except the ability to get from the output  to a gene page, and export  a list of gene IDs as a list to import.

It just sits there being quietly useful.

**Comment by ValWood** [comment]
Might be good to fix this, which seems a bit strange?

Amino acid group codes (Please note these options do not work in combination with square brackets):


but not urgent, can all be done after porting. And we could even point to the EBI one from P2 for a while if you like....

**Comment by kimrutherford** [comment]
> Did you know that you wrote the original script at the Sanger?

I still think it was Martin.  :-)

> except the ability to get from the output to a gene page, and export a list of gene IDs as a list to import.

I'm hoping we can eventually integrate it into the new query builder so we can do all of that and more.  For the initial release of V2 I'll try to make the minimal changes needed to get it working.

**Comment by ValWood** [comment]
Maybe it was as  you clearly don't recognise  the code. I know I did something  for this but I think I did a cgi wrapper for a previous version. Actually that means it even predated GeneDB!

Yes integrating into the query builder has always been a hope. And nothing is complicated any more.....

**Comment by ValWood** [comment]
we could punt this to after release because we can just point to  this URL

https://curation.pombase.org/cgi-bin/sanger_motif_search

**Comment by kimrutherford** [comment]
I've started working on this in the background.  I'm going to reimplement it so that it can be nicely integrated into the rest of the site.

> Might be good to fix this, which seems a bit strange?
> `Amino acid group codes (Please note these options do not work in combination with square brackets):`

I can understand why that restriction is there - the AA groups are implemented by substituting some residues in square brackets into the query search.  And it's not possible to have nested square bracket groups.  It should be possible to fix it but it's a bit fiddly.

Are there any other changes to the interface or functionality that would be useful?  There's no rush to decide but maybe have a think about once things are quieter?

**Comment by ValWood** [comment]
That would be nice before the workshop that @Antonialock  teaches (data?), so that lists from the motif search can be easily put to the advanced search.

I don't think any additional functionality is required at this point (at least none has been requested).

**Comment by kimrutherford** [comment]
> That would be nice before the workshop that @Antonialock teaches

Should be no problem.  Antonia could you let me know when the workshop is?

I think this will take a day-ish to implement.

**Comment by kimrutherford** [comment]
A prototype of the new motif search is now running on pombase-dev:
   http://pombase-dev.bioinformatics.nz/motif_search

It's unfinished and buggy.  In particular these characters don't work and are just ignored: "[", "]" and "|".

I plan to turn the gene names into links to the gene pages and I plan a button to send the list of gene to the advanced search.

**Comment by ValWood** [comment]
Perfect.


>I plan to turn the gene names into links to the gene pages and I plan a button to send the list of gene to the advanced search.

are the only things it need once the characters are working.

Will be nice to have this fully integrated.

We can ask the community id they want any further tweeks...

**Comment by kimrutherford** [comment]
As a small improvement, "[" and "]" now work but "|" still doesn't.

**Comment by ValWood** [comment]
I'll put next on this since it is so close to complete ;)

**Comment by kimrutherford** [comment]
> "[" and "]" now work but "|" still doesn't.

That works now.

Things to do:
  - implement the "Amino acid group codes"
  - tidy up the formatting of the help text and add a header
  - decide how many matching genes to show, I'd prefer to limit to the first 100 or 200 and then just say "X matching genes, showing the first 100"
     - we could still send the complete list to the advanced search
  - decide how many matches to show within each gene, I think a limit makes sense in case someone uses a daft pattern that matches in many places

**Comment by kimrutherford** [comment]
I've improved how it looks and fixed a few bugs:
  https://www.pombase.org/motif_search

> Things to do:

Also:
 - [ ] add a button to send the results to the advanced search
 - [ ] remove the "*" at the end of the protein sequences so this search works "LAA$"

**Comment by kimrutherford** [comment]
> add a button to send the results to the advanced search

That's done now and the gene IDs are now links to the gene pages.

**Comment by ValWood** [comment]
That looks brilliant. It all seems to work. only 1 more task:

- [ ]  add columns with the gene name and product (currently only had ID)

**Comment by kimrutherford** [comment]
> add columns with the gene name and product (currently only had ID)

I've added a product column and the ID column now shows the gene name when there is one.  Is that what you had in mind?

**Comment by ValWood** [comment]
yes that looks great!

**Comment by kimrutherford** [comment]
>  decide how many matching genes to show, I'd prefer to limit to the first 100 or 200 and then just say
> "X matching genes, showing the first 100" 

I have put a message like this at the bottom of the table:
`321 other matching genes not shown - send list to advanced search to see all genes`

It shows the first 100 genes in the table.  We could easily make that more.

**Comment by kimrutherford** [comment]
The main thing left to do here is the "Amino acid group codes"

**Comment by kimrutherford** [comment]
> The main thing left to do here is the "Amino acid group codes"

Done!

I put my thinking head on and made the changes needed to handle the AA group codes.  I've also tweaked the docs including adding some examples of how to use the group codes.  Let me know if you have any suggestions:
https://www.pombase.org/motif_search

There is no link to new motif search yet.  I'll hold off on that until we're ready.

**Comment by kimrutherford** [comment]
>  Let me know if you have any suggestions

Let's open new issues for changes.
