### ISSUE TITLE
annotations not visible

### ISSUE THREAD

**Issue by ValWood** [pombase/website#389]
Annotations from this paper are not visible
http://preview.pombase.org/reference/PMID%3A28539404

although they are present on the gene page
(see quantitive expression section for blt1 for example)

This might be because the session is not approved? I just wanted to check....

**Comment by ValWood** [comment]
(the expression data comes from a spreadsheet in external data)

**Comment by kimrutherford** [comment]
Looks like I had forgotten to include quantitative and qualitative on the publication pages.  We hadn't noticed because it's only obvious when a publication only has quant. and qual. annotation.

I've fixed the problem.
