### ISSUE TITLE
Search autocomplete list sometimes contains duplicates

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#391]
![screenshot from 2017-06-16 19-10-46](https://user-images.githubusercontent.com/90474/27215961-c1a1ad64-52c7-11e7-91ec-3347922b885c.png)

**Comment by ValWood** [comment]
Actually, isn't tis fixed? reopen if not...

**Comment by ValWood** [comment]
it is...

**Comment by kimrutherford** [comment]
It's still broken - try cdc11.

**Comment by kimrutherford** [comment]
Fixed now.  The problem started after I changed it to allow searching of products.  Some products contain the gene name and that was causing the gene to appear twice.
