### ISSUE TITLE
priority unstudied genes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#392]
is blank
http://preview.pombase.org/status/priority-unstudied-genes

**Comment by kimrutherford** [comment]
I've added a temporary static version of that page.  We should:

- [ ] create the list from the live data in Chado
- [ ] calculate the counts at the top of the page from the live data
      (eg. "inventory is around 836 entries")

**Comment by ValWood** [comment]
Oh sorry there was no huge hurry. I though it was there and had disappered...

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/website/issues/242
