### ISSUE TITLE
change transcript sequence length to protein sequence length for translation?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#394]
>SPAC977.02-transcript-sequence length:448
MALLKKINTQVNRIMKNSSLVQNICFDRVPLFIPRLSLTVKYCLAVKLLIYLLYCWYIYS
EVPSASSKFRSFTFGCVVVYHNKFFPRFIRTHSINSIRTFSKFQVIILFSIEKVTRSESK
NHSYSKTDISDLHQGYNNPPSRFISR*

**Comment by kimrutherford** [comment]
The length not including the stop codon I guess?

**Comment by ValWood** [comment]
Yep, should be the already reported 
	Product size	104 aa,  (hmm maybe that should say protein length)

**Comment by ValWood** [comment]
on the old site its
Product Size	297aa, 34.36 kDa

which makes sense as both are "sizes"

**Comment by kimrutherford** [comment]
> Product Size 297aa, 34.36 kDa

I copied that for v2.

**Comment by ValWood** [comment]
change
>SPBC11B10.09-transcript-sequence length:908
to say
>SPBC11B10.09-protein-sequence length:908
for proteins

**Comment by kimrutherford** [comment]
That's fixed now if you reload.
