### ISSUE TITLE
blast links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#395]
These can be in the sequence section for now,  (or a better place?)

 We can use NCBI blast for everything, it works...
![blast links](https://user-images.githubusercontent.com/7359272/27275153-1da55f0e-54ce-11e7-954f-57764e41e179.jpg)

**Comment by ValWood** [comment]
This looks pretty quick. It might not be how we want to do it long term, but to replace P1 functionality I think we should have Blast links from the suquence section for now.
Should just be Links and a URL call with  sequence/ID ?

**Comment by kimrutherford** [comment]
> Should just be Links and a URL call with sequence/ID ?

The links need the NCBI accession numbers like: ref|NM_001021523|

We don't have those in Chado at the moment so we can't link directly.

**Comment by ValWood** [comment]
I think you can use UniProt IDs for protein, or directly send the sequence?

**Comment by kimrutherford** [comment]
> I think you can use UniProt IDs for protein, or directly send the sequence?

You're right we can use the UniProt ID for protein blast.  I don't know how to send the sequence but I'll investigate.

**Comment by kimrutherford** [comment]
I still haven't worked out how to send sequence to the NCBI blast page.

But Ensembl blast is easy so I've added a button for that in the sequence section in the mean time.

**Comment by ValWood** [comment]
they actually do different things, Ensembl blast searches pombe  genome only... (which might be what most want to do with nt sequence.....)...but then from a gene page it is unlikely that anyone would want to blast the  sequence against the genome (they know where it is).



The main use for this server is to locate an unknown fragment. So, we should link to is from somewhere, but not from the gene pages.
...and when we do we should use 
http://fungi.ensembl.org/Schizosaccharomyces_pombe/Tools/Blast?db=core;g=SPBC11B10.09;r=II:1500197-1502095;t=SPBC11B10.09.1

**Comment by ValWood** [comment]
Actually this link is  much better, it includes the ability to add other species (which you can't with the pombase version, we always had an issue with that) . So here people can add octosporus and japonicus etc (which is the most likely thing they will be looking for with  a DNA blast), so we CAN include this link on the gene page.

**Comment by ValWood** [comment]
Oh you can add remove from the pombase blast. I think that might be quite new (at least I never noticed it before). But this server will go away so we should luse the EG link instead.

v

**Comment by kimrutherford** [comment]
> Oh you can add remove from the pombase blast.

I don't understand that.

> But this server will go away so we should luse the EG link instead.

I've swapped over to the fungi.ensembl.org BLAST server.  You'll need to shift-reload.

**Comment by kimrutherford** [comment]
> I don't know how to send the sequence but I'll investigate.

I think I've worked out how to send sequence to the NCBI blast server.  It works for me but I'd appreciate if you could do a quick test.  You'll need to shift-reload to see the new button in the sequence section.

**Comment by ValWood** [comment]
that works for me!

**Comment by kimrutherford** [comment]
OK to close this then?

**Comment by ValWood** [comment]
Is it easy to send the fasta header corresponding to the sequence too?

>SPBC11B10.09-transcript-sequence length:894 includes:exons

**Comment by ValWood** [comment]
>Oh you can add remove from the pombase blast.

That's because it doesn't make any sense. I was observing that you can now add other organisms to the blast when you go to the ensembl nucleotide search. I think this might be new, although it is entirely possible this feature has been there for a while and I hadn't noticed it.....

**Comment by ValWood** [comment]
The Ensembl protein blast link also goes to the NCBI. I don't think we should offer an Ensembl protein blast link, it won't search everything, and it doesn't allow the different blast flavours, so it's always going to be suboptimal for a protein search.

When I go to the NCBI blast, and then use  the browser "back" button, I come back to the PomBase homepage. I expected to come back to the page I left from. Is that possible?

**Comment by kimrutherford** [comment]
> Is it easy to send the fasta header corresponding to the sequence too?

Could you try it now?

**Comment by kimrutherford** [comment]
>  I expected to come back to the page I left from. Is that possible?

That's odd.  It comes back to the same page for me, in Firefox and in Chrome.  Could you have pressed back twice?

**Comment by kimrutherford** [comment]
> The Ensembl protein blast link also goes to the NCBI.

Whoops, fixed now.

>  I don't think we should offer an Ensembl protein blast link, it won't search everything

I don't follow that.  The Ensembl DNA blast won't search everything either.

> it doesn't allow the different blast flavours,

It offers me TBLASTN and BLASTP, which makes sense doesn't it?

**Comment by ValWood** [comment]
Works now.

Ensembl protein blast doesn't offer PSI blast, and it doesn't search all  proteins, only Ensembl Genomes organisms. For DNA blast this is fine, but for most purposes for proteins you need more.

We could keep it but we should put the NCBI blast links first...

**Comment by ValWood** [comment]
> That's odd. It comes back to the same page for me, in Firefox and in Chrome. Could you have pressed back twice?

I could have.....

**Comment by kimrutherford** [comment]
> We could keep it but we should put the NCBI blast links first...

I've moved the NCBI BLAST button to be first.

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
not for now I think....I should probably do a bit more testing but  OK close
