### ISSUE TITLE
Sequence section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#397]
Feedback from Martin Kollmar, book chapter editor

- Gene page: there is something completely wrong with the "Sequence" part. I clicked on the example "cdc2" on the homepage. "Include exons" is preselected, introns and UTRs are de-selected by default. But the nucleotide sequence does not correspond to the cdc2 gene. The sequence is reverse-complement (personally, I prefer to have sequence data for genes in the 5' to 3' direction, but this is maybe just my personal view), and it only comprises only the C-terminal 26 aa followed by 817 bp of UTR, and maybe already intergenic region and the next gene. Shouldn't one see the cds here? At least I would expect this here given the selectable options.

**Comment by kimrutherford** [comment]
I think I've fixed this.  You'll need to reload.

I've done a bit of testing and the sequences I tried matched the old site and I get the right strand and sequence match if I do a blast.  Would you be able to try one or two genes as a double check?

(The problem was that I was so keen to make sure that the reverse strand genes were reverse-complemented that it was accidentally rev-comping the forward strand too)

Thanks to Martin for reporting that.

**Comment by ValWood** [comment]
I should  have tested it ;) 

It seems to be doing the right thing now.

A couple of thing should maybe discuss.


>SPBC11B10.09-transcript-sequence length:1189 includes:exons+introns
header might be a bit misleading.
If you looked at this later, because it is labelled as transcript you might expect that it included UTRS

There is also an option "include introns" which coves just concatenated introns if uses it on its own. This isn't so useful, and should only be available *with* exons*

So, I am wondering also if the labelling was better on the old site
CDS + UTRs
 CDS + UTRs + Introns
etc (and this could be in the header too), I think we should avoid "transcript" here- its a bit loaded.

This isn't super urgent, now that the sequence is correct,  I think it would be good to discuss  together when M&A are back

**Comment by kimrutherford** [comment]
> So, I am wondering also if the labelling was better on the old site
> CDS + UTRs
> CDS + UTRs + Introns

I like that except for "CDS" which I've always thought was a bit jargony.  Will all the web lab people understand it?

**Comment by ValWood** [comment]
It is a bit jargonny but I'm sure most biologists should know what it means. I think it is common enough that they will of had exposure to it if they have ever done anything at the sequence level like "design primers" so I don't think its a big problem to use this terminology...

**Comment by kimrutherford** [comment]
OK I change the text to that.  Although I think it worth asking about how clear this is when we do user testing with some new users (if we can).

**Comment by ValWood** [comment]
Yeah we should do some.

I  think this is a very used section of the gene pages and nobody appeared to ever have a problem with it. @mah11  might be able to think of better words...

**Comment by kimrutherford** [comment]
> So, I am wondering also if the labelling was better on the old site
> CDS + UTRs
> CDS + UTRs + Introns

The options are slightly different if you go for the "Customise ..." option:
 http://www.pombase.org/spombe/download/sequence/SPAP8A3.08

Which is best?

**Comment by kimrutherford** [comment]
To make it more like the old site, I've changed the sequence section so that the exon sequence is included by default.  The downside is that you can't download just the up- or down-stream sequence for a gene.  Is that OK?

**Comment by ValWood** [comment]
@mah11 @Antonialock 
 preferences?

**Comment by mah11** [comment]
New behavior looks fine to me. Let's leave it that way unless users (plural!) squawk. It seems unlikely that there'll be demand for sequence without the coding exons.

We've never had anyone tell us they didn't know what "CDS" means, so it's probably fine.

The important thing is that it allows you to include upstream and downstream sequences whether introns are included or not. That's broken on the legacy site, and we got multiple complaints about it, but EBI steadfastly refused to do what our users clearly want.

**Comment by kimrutherford** [comment]
OK, I'll leave it as it is for now.

I've just noticed the the up and down stream sequence retrieval doesn't do the right thing if you show the UTR as well.  I'm fixing that now.

**Comment by ValWood** [comment]
All good? Any testing required?

**Comment by ValWood** [comment]
Removed discuss label anyway, so if anything outstanding to chat about on call, please add back.

**Comment by kimrutherford** [comment]
> All good? Any testing required?

The UTR / upstream / downstream sequence is still wrong.  I've been looking at how to save the history between sessions.

> Removed discuss label anyway, so if anything outstanding to chat about on call, please add back.

Yep, I think it's fine but we can chat if there are more changes needed.

**Comment by ValWood** [comment]
OK just let us know when testing required.

**Comment by ValWood** [comment]
> The UTR / upstream / downstream sequence is still wrong. I've been looking at how to save the history between sessions.

and this one. We can wait for history saving ...  I'm only doing simple queries and they are easy to re-run... also fine if I don't leave the page

**Comment by kimrutherford** [comment]
I think I've fixed this now.  I've compared the results to PomBase V1:

 - with/without introns and UTRs
 - with and without up/down stream sequence 
 - and forward and reverse strand

The case that caused the most trouble with transcripts that have introns in the UTR.  I had forgotten that case but it's handled now.

I'm fairly confident that it's OK now but please keep an eye out for bugs.
