### ISSUE TITLE
dicrepancy between reported protein coding numbers

### ISSUE THREAD

**Issue by ValWood** [pombase/website#400]
Martin Kollmar

 "Genome statistics, gene characterisation: The total number (in the table) differs from the total number of genes at the main statistics page. If this table is only about protein-coding genes, then there are 20 too much, if this is about all genes, I would add a category such as "no characterization yet""

So this is  the numbers generated by Ensembl here
http://www.pombase.org/status/gene-characterisation
and here
http://www.pombase.org/status/statistics
don't agree

Could you provide totals from chado (status for each chromosome/contig) so we can figure out what is going on....Its possible Ensembl get these form different places (PomBase and Ensembl fungi) which are not aligned but even that doesn't completely add up....

**Comment by kimrutherford** [comment]
> Could you provide totals from chado

The numbers on the gene-characterisation page are from Chado.  The statistics page is just static HTML.

**Comment by ValWood** [comment]
I still think something is awry....

The only genes added since 2015 have been non-protein coding.

The protein coding gene set  is fairly static and should be the same everywhere. I'll do some digging....

**Comment by ValWood** [comment]
Up until now, I thought the query builder was correct.  I always use this number
Protein coding 5138

that is what you have here
http://preview.pombase.org/status/gene-characterisation

I have no idea where
http://preview.pombase.org/status/gene-characterisation
and
http://www.pombase.org/status/statistics
come from

But I'm happy that our new number is the correct one.
