### ISSUE TITLE
Current menu "tabs" for site navigation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#402]
Question from Martin:

 Main menu: will this be added again, similar to the one in the top right corner of PomBase_v1?

Kim,  did you have any ideas for  within site navigation? Did you plan to replace with tabs? I remember  vaguely discussed doing something else....

**Comment by kimrutherford** [comment]
> Kim, did you have any ideas for within site navigation? Did you plan to replace with tabs? I remember
> vaguely discussed doing something else....

I think it's worth having a small discussion about the navigation to see if we can come up with a better idea than tabs.  If we can't come up with anything better we should just do something similar to the old site.

**Comment by ValWood** [comment]
not tabs, menu style

![not tabs](https://user-images.githubusercontent.com/7359272/28161862-0bedd654-67bd-11e7-83b0-6f290c5e8de7.jpg)

**Comment by ValWood** [comment]
SGD to the rescue:
![sgd](https://user-images.githubusercontent.com/7359272/28161939-5802c8ba-67bd-11e7-888f-921f41158982.jpg)

**Comment by ValWood** [comment]
We need to add our categories and sub categories

**Comment by ValWood** [comment]
Search [ Simple, Advanced, Motif, List search, Region]
Submit [ Same list]
Download [same or updated]
Genome status [ exisiting stuff, plus GO slim Historical Data]
Community
About PomBase
Help

**Comment by mah11** [comment]
Need to decide where the genome browser link goes (it's under Tools in legacy PomBase)

**Comment by kimrutherford** [comment]
I've added a basic menu bar to http://pombase2.bioinformatics.nz (not the preview yet).  Unfortunately it works differently from PomBase v1, you have to click to see the menu rather than just hovering the mouse over.  It's the best I can do for now.

It's a work in progress.  In the Search menu only the "Advanced" item works and there's nothing in the Download menu yet.

**Comment by kimrutherford** [comment]
Val, the "Find" menu from PomBase v1 is missing from your list of menu to include in V2.  I guess that was just an omission?

**Comment by ValWood** [comment]
Was the horizontal banner menu, rather tabby unsuccessful then?

**Comment by ValWood** [comment]
I think we decided that everything under"find" could be relocated?

**Comment by kimrutherford** [comment]
> Was the horizontal banner menu, rather tabby unsuccessful then?

It's as close to the SGD style as I can get at the moment, but I'll work on it.

**Comment by ValWood** [comment]
Oh it looks fine now. I'm sure it looked like "actual tabs" when I looked a while ago?

**Comment by ValWood** [comment]
I like it....

We should add this.
https://curation.pombase.org/pombe/stats/annotation
It does not quite fit "genome status" but I feel it belongs under this menu


How could we label the  menu to encompass?
"genome and annotation status" is too long
"project status"
"status and statistics"

**Comment by ValWood** [comment]
I like it, what do you want to change? My only issue is that it hiding the wonderful spore pic, which is trivial, but  I wonder if we should adjust the image so that the " biological business" 
is more in the non menu/search box space?

**Comment by kimrutherford** [comment]
> Oh it looks fine now. I'm sure it looked like "actual tabs" when I looked a while ago?

I did some fixing to make it look a bit less tabby.

> "project status"

That sounds OK to me.

> My only issue is that it hiding the wonderful spore pic

I liked having it right-aligned but we could maybe move the image to be more centred and visible.

I've just made the menu bar a bit transparent.  Does that help?

**Comment by ValWood** [comment]
> I've just made the menu bar a bit transparent. Does that help?

Hmm, I quite like it. It's visually appealing but not "in your face". Lets see what others think....

**Comment by kimrutherford** [comment]
Now the the query builder works, I've added the Search menu to preview.pombase.org.
