### ISSUE TITLE
Gene characterization, clarification

### ISSUE THREAD

**Issue by ValWood** [pombase/website#404]
I think we should call this page 
"protein characterisation"
http://preview.pombase.org/status/gene-characterisation

more precise. that's what we call it in the poster too.....

**Comment by ValWood** [comment]
Also, should be on the gene pages summary section  for protein coding only

**Comment by mah11** [comment]
changed to "protein-coding gene"

the part about gene pages is for Kim, and maybe should have its own ticket

**Comment by ValWood** [comment]
Let's keep as is... Can change later...
