### ISSUE TITLE
Add filter options for single, multi allele genotypes in query builder

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#405]
From Val:

> maybe we want to include all and have "single-allele" "multi-allele" as filter options?

(rather than just showing the genes from the single allele genotype annotation in the results)

**Comment by kimrutherford** [comment]
> maybe we want to include all and have "single-allele" "multi-allele" as filter options?

Should we have a discussion about this?

**Comment by ValWood** [comment]
Yes this should be top priority for Thursday call....

and this ties in
https://github.com/pombase/curation/issues/1407

**Comment by ValWood** [comment]
1. Single or multigene allele (or all)

2. allele expression
 default all 
 null (knockdown, deletion)
 wild type overexpression

3. conditions
auto complete?
set of options....
standard conditions/ non standard
Look at condition ontology and make a slim?
chemical sensitivity?
temperature?
growth medium?
conditional?

How to deal with the incompleteness of annotation
not recorded would be lumped with "standard"

**Comment by ValWood** [comment]
I had a brief look at the PECO terms and I'm struggling to come up with  meaningful groupings.
Any ideas....

**Comment by ValWood** [comment]
I think we have problems whichever way we do it.
Even conditional isn't really possible. Fr instance I have rarely used permissive/non-permissive as I have et the user figure that out from the combination of phenotype and condition....

I wonder if we could begin with some very general
standard non standard growth condition groupings, but many would be difficult to partition. I'm a bit stuck. Especially when i also start to think that we don't always know and how that might affect results...

**Comment by Antonialock** [comment]
I don't like the idea of lumping "standard conditions"...there are no standard conditions really....a person might think of "YES" and standard medium because it has everything WT yeast needs, and EMM as a "starvation medium"
Another might think of EMM as standard because it is defined

This might be difficult to implement but my preference would be to run the query, and get the result list. some text would say "these annotations have been associated with these conditions, are there any that you would like to exclude or include"

we could organise them under a few headers, and for the temperature and growth medium headers we could offer to include or exclude anything where this was not recorded.

So it is like a filtering step after you have run the query.

**Comment by ValWood** [comment]
Yes,   negative filtering is definitely required, and post query filtering  would be neat...

I still thing we would probably need a "restricted list" so we omit the  chemicals which are only used to assess sensitivity  (maybe). Or something even cleverer.

Anyway "conditions" can be "post release" as we continue to think about it....

**Comment by kimrutherford** [comment]
I'm working on the single vs multi-allele and expression filtering first to give us more time to decide what to do about the conditions.

**Comment by kimrutherford** [comment]
I've added single and multi allele checkboxes for phenotype searches in the query builder.

It currently looks like this:

    Include genes from:  [ ] Single-allele genotypes [ ] multi-allele geneotypes

Please let me know if you have ideas for improving how it looks or works.

**Comment by kimrutherford** [comment]
> This might be difficult to implement but my preference would be to run the query, and get the result list.

Yep, that's sounds like a good way to do it as it will mostly keep the list of possible conditions to a manageable size.  It's trickier though.  :-)

**Comment by kimrutherford** [comment]
I've add allele expression filtering, hopefully in the way you wanted.  It looks like:

![screenshot from 2017-08-01 00-00-57](https://user-images.githubusercontent.com/90474/28776867-bffef87e-764c-11e7-866d-c60b37f90480.png)

Please let me know if you find any problems.  And as usual, any suggestions for formatting or wording would be very helpful.  For example one of the labels is currently "Wild type + overexpression".  Can you suggest a better way to word it?  Maybe "Overexpressed wild type"?

Looking at the screenshot I noticed that the text isn't aligned on the right.  I'll fix that.

**Comment by Antonialock** [comment]
> I still thing we would probably need a "restricted list" so we omit the chemicals which are only used to assess sensitivity (maybe). Or something even cleverer.

I don't like this...for example, you might annotate a gene to an "elongated" phenotype +chemical_commonly_used_in_sensitivity_screens 

you might want to filter those out....

**Comment by Antonialock** [comment]
> Yep, that's sounds like a good way to do it as it will mostly keep the list of possible conditions to a manageable size

I'm sure that for some genes it would still be long :-) this filtering section could be expandable so that if you only see them if you want to do the filtering (this is how it is done in the biomart...not suggesting we replicate exactly how it looks, but I like that it is collapsible so you don't get presented with a huge form)
 
![screen shot 2017-08-03 at 09 48 28](https://user-images.githubusercontent.com/12727506/28913726-f6935bba-7830-11e7-9800-e2313d0b0235.png)

**Comment by Antonialock** [comment]
Overexpressed wild type sounds better than WT+overexpression...

**Comment by kimrutherford** [comment]
> Overexpressed wild type sounds better than WT+overexpression...

I've changed that.

>

**Comment by kimrutherford** [comment]
> but I like that it is collapsible so you don't get presented with a huge form

I like that too.

**Comment by ValWood** [comment]
So, it seems this ticket is now about condition filtering, so I will change the title.
We don't need to do this for public release, the required part of multi vs single is done.

**Comment by ValWood** [comment]
I think the relevent parts of the discussion are not  on the "conditions filtering" ticket
https://github.com/pombase/website/issues/56

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/website/issues/56
