### ISSUE TITLE
human orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#407]
-  [x] remove compara ref from  orthologs not from compara

- [x] make links go directly to HGNC
http://www.genenames.org/cgi-bin/gene_symbol_report?match=ABCA1

**Comment by ValWood** [comment]
I'm putting at public release. Its annoying to need to go thorough ensembl to get to functional information . HGNC is a much better landing site to get to annotated data, and an up to date description (and easy to get to Ensembl from here ).

Can be relegated if time consuming, not critical.

**Comment by ValWood** [comment]
Kim suggested a simple solution,
2 hours work.

**Comment by kimrutherford** [comment]
> remove compara ref from orthologs not from compara

I've removed the Compara reference from pombe-embl/orthologs/conserved_multi.txt and pombe-embl/orthologs/conserved_one_to_one.txt

Are those the right files?

The change will be visible after the load is working again.

**Comment by kimrutherford** [comment]
> make links go directly to HGNC

That's done now.

**Comment by ValWood** [comment]
Still go to Ensembl for me?

**Comment by ValWood** [comment]
Are those the right files?
yes.

and any from artemis. Only keep for compara_orths.tsv

**Comment by mah11** [comment]
>> links go directly to HGNC
> 
> Still go to Ensembl for me?

shift-reload makes them go to HGNC for me

**Comment by ValWood** [comment]
Of course!
