### ISSUE TITLE
page missing domain descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#408]
http://preview.pombase.org/gene/SPAC977.08

**Comment by kimrutherford** [comment]
There are no InterPro matches for Q9P324:
  https://www.ebi.ac.uk/interpro/protein/Q9P324

Maybe the UniProt mapping needs updating?

**Comment by ValWood** [comment]
OK will look into...

**Comment by ValWood** [comment]
Oh I know what that is, InterPro asked about it this week... it's de-merged entry.
I mailed UniProt helpdesk about it already...
