### ISSUE TITLE
put the syscode of the protein above the antisense RNAs with the same name in the basic search drop down

### ISSUE THREAD

**Issue by ValWood** [pombase/website#409]
This seems a bit picky, but I always want to be able to select the top entry when doing a simple search if that's what I'm looking for ...and I never want the antisense RNA...

(I keep going to these
![fix](https://user-images.githubusercontent.com/7359272/27516945-438e6264-59bb-11e7-94c9-6c89f0a2d414.jpg)
 page though!)

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  I've updated http://pombase2.bioinformatics.nz

If that is working how you'd like I'll update the preview.

**Comment by ValWood** [comment]
It is for SPACUNK4.09 so go for it!

**Comment by kimrutherford** [comment]
I've updated the preview.
