### ISSUE TITLE
link to Interactome server

### ISSUE THREAD

**Issue by mah11** [pombase/website#41]
Add links to PomBase gene pages for genes that have static pages in Colm Ryan's Interactome DB (URL e.g. http://interactome-cmp.ucsf.edu/pombe2012/modules/genes/SPAC11E3.01C.html). Genes that have pages are listed at http://interactome-cmp.ucsf.edu/pombe2012/modules/search.html, and in the attached spreadsheet.

Email from Colm Ryan explains why the gene list is important - not all genes have static pages:

> Hi Val,
> 
> Sorry for the delay on this.
> 
> Yes - it would be great to have a link from the Pombase site to our interactome server.
> 
> The delay has been because the dynamic part of our interactome DB is running quite slowly for pombe queries - e.g. click on http://interactome-cmp.ucsf.edu/index.php?framesrc=Dataset/sgi.cgi&amp;action=search&amp;dataset=479&amp;names=SPAC1002.02 and wait.
> 
> This is partially because the pombe map is significantly bigger than any of the other E-MAPs & partially because the server needs an upgrade.
> 
> To get around this I have created a static page for every gene in the pombe screen, containing both the interactions and similarities. See http://interactome-cmp.ucsf.edu/pombe2012/modules/genes/SPAC11E3.01C.html for an example, and http://interactome-cmp.ucsf.edu/pombe2012/modules/search.html for a list of all genes covered.
> 
> I would propose that Pombase linkout to these static pages. Whenever our server is upgraded & the dynamic pages are behaving nicely we could discuss a switch. The one hitch at the moment is that not every gene has a static page - only those which were included in our screen. So a link out to http://interactome-cmp.ucsf.edu/pombe2012/modules/genes/SPCC417.02.html would result in a 404, as that gene was not included in the screen.
> 
> To get around this - either Pombase could only add links for genes included in the screen (i.e. not on every gene page) or else I can add something better than the standard 404 error. I prefer the former, as it saves someone visiting our site only to find we have no data on their gene of interest, but if the latter is preferable to you I can look into it.
> 
> Let me know if the above is clear, and if you are interested in adding the linkout.
> 
> Thanks,
> 
> Colm

**Comment by ValWood** [comment]
I don't think we will do this. But if there are more datasets in future and an external service, we will link to it.
