### ISSUE TITLE
do we want to link the DB name here

### ISSUE THREAD

**Issue by ValWood** [pombase/website#411]
![don t link db name](https://user-images.githubusercontent.com/7359272/27517640-b4cc27de-59c7-11e7-99c6-63b222f0ef3f.jpg)

I keep clicking on it expecting to get to the entry. I think we should probably only link to the entry, because people can easily get to the home page of the other databases.

**Comment by ValWood** [comment]
I don't think the database name should be hyperlinked here. I keep clicking on it and I expect to go directly tot eh protein family. I don't think we need to provide the option to the database top level  from here.
@mah11 @Antonialock ?

**Comment by mah11** [comment]
I think if I see the db name by itself, not as the prefix for an ID, I would expect a link to go to the main page for that db. It probably would annoy me to have the db name hyperlinked to anything more specific than the db main page (e.g. a specific entry).  But I don't think I'd mind if the name wasn't a hyperlink at all.

**Comment by ValWood** [comment]
I'd prefer it not to be hyperlinked, because the ID (which is where people really want to go), is hyperlinked right next door. If they want to go to the home page, I'm sure they can get there...

**Comment by Antonialock** [comment]
I'd have a slight preference for showing the DB name in the lefthand column unhyperlinked and the ID in the right hand column hyperlinked

**Comment by ValWood** [comment]
I have a very slight preference to keep the order as it is. The link to the family is the thing you want so it's better to have that first (possibly).The only purpose for the DB name is to let people who are not familiar with the IDs know the originating database, but they seem secondary to the ID to me?

That makes this a really really quick ticket.
- [ ] Action, Unhyperlink the database name

**Comment by Antonialock** [comment]
yeah, I think in my head it makes more sense to have "less specific" (database) to the left and more specific (term) to the right...
(like in the target of section the ontology is on the left, and the relationship is on the right, or in external references the classification is on the left and the specific resource is on the right)

but as I said I don't have a strong preference, it is slightly different...

**Comment by kimrutherford** [comment]
I've removed the hyperlink.
