### ISSUE TITLE
community curation feed/ curation attribution check

### ISSUE THREAD

**Issue by ValWood** [pombase/website#413]
I notice that a  paper of Juan's that I  put through "temporarily' is a the top  of the list:

https://github.com/pombase/curation/issues/1525

This  session, although it has been community assigned, has no actual community curation. Can we restrict the feed to only papers where the community was assigned, and some curation was made by them?

(I only changed this yesterday in the session, it was attributed to Juan the day before, so it is possible that  the website hasn't caught up...

**Comment by ValWood** [comment]
Also this session is attributed to Takashi, but he didn't appear to do the annotation for this one?
http://preview.pombase.org/reference/PMID%3A26900649

**Comment by ValWood** [comment]
So I took Juan's paper out of approval temporarily.
I  wanted to announce that (among other things) the communiyt curation feed was showing the most recent curation sessions, and I thought it looked bad that very incompletly curated session was at the top of the list.

It's still there though?
http://pombase2.aska.gen.nz/
(but not sure when this update is from, I think its very recent though)

**Comment by kimrutherford** [comment]
> So I took Juan's paper out of approval temporarily.

It looks like it's still approved:
  https://curation.pombase.org/pombe/curs/3233320f8849c7ea

**Comment by ValWood** [comment]
OK thanks reactivated, will check tomorrow!
