### ISSUE TITLE
families and domains

### ISSUE THREAD

**Issue by ValWood** [pombase/website#414]
- [x] Add Gene3D back
https://github.com/pombase/website/issues/96

They can it provide access to larger family groupings to give functional clues...
Sorry about the U-turn

**Comment by ValWood** [comment]
prints
this is by no means the worst example
http://preview.pombase.org/gene/SPBC11B10.10c

but
PR00620	PRINTS	HISTONEH2A	IPR002119	Histone H2A	22-126
would be much better...

**Comment by ValWood** [comment]
moved the prints part to
https://github.com/pombase/website/issues/434

Is it a pain to add Gene3D?   It might be useful for the "unknowns" clues.  I forgot when the next InterPro release was planned for.

**Comment by ValWood** [comment]
I  forgot when the next InterPro release will be. Maybe can wait, but it  will be useful for assessing "unknowns"

**Comment by ValWood** [comment]
How much of a pain is this?

**Comment by ValWood** [comment]
Actually we could role in with the update to get the latest version.


Hi Val,
Our latest release (v64) came out last week. The next one is scheduled for 28th
Sept.
Alex

I can announce this to see the user spike ;)

**Comment by kimrutherford** [comment]
> How much of a pain is this?

I've added it back.

**Comment by ValWood** [comment]
Is it  the current InterPro release or the new one?

**Comment by ValWood** [comment]
We need to check Gene3D url format

http://pombase2.aska.gen.nz/gene/SPAC19G12.09
has
http://gene3d.biochem.ucl.ac.uk/superfamily/?accession=G3DSA:3.20.20.100
page not found?

**Comment by ValWood** [comment]
appears to be general
http://pombase2.aska.gen.nz/gene/SPAC19G12.10c
http://gene3d.biochem.ucl.ac.uk/superfamily/?accession=G3DSA:3.40.50.1820

**Comment by kimrutherford** [comment]
> Is it the current InterPro release or the new one?

I've haven't downloaded the new release.  I'll do that now.

**Comment by ValWood** [comment]
no worries it isn't uget. I just thought if you needed to re-parse to get Gene3d it was worth updating too....but can wait...

**Comment by kimrutherford** [comment]
> no worries it isn't ugent.

It just needs one command to re-process the InterPro XML file.  It's done now.

>I just thought if you needed to re-parse to get Gene3d it was worth updating too..

The command pulls out all pombe data and we were then filtering out the Gene3D results when generating the web data.

**Comment by kimrutherford** [comment]
> It's done now.

Actually only the starting the command bit is done.  It takes a few hours to run.

**Comment by kimrutherford** [comment]
The new InterPro data is now in the preview, including the Gene 3D stuff.

> http://gene3d.biochem.ucl.ac.uk/superfamily/?accession=G3DSA:3.20.20.100

It looks like the GO.xrf_abbs file needs updating.  I can't work out what the URL should be.

**Comment by ValWood** [comment]
Great, that will be useful for unknowns.

**Comment by ValWood** [comment]
>
It looks like the GO.xrf_abbs file needs updating. I can't work out what the URL should be.

@mah11  do you know how we get this done?

**Comment by mah11** [comment]
> It looks like the GO.xrf_abbs file needs updating.

I have created a pull request (for future reference, GO abbreviations now live at https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml).

**Comment by kimrutherford** [comment]
> for future reference, GO abbreviations now live at

Should we be parsing the JSON file instead of GO.xrf_abbs or are they synchronised?

**Comment by ValWood** [comment]
From June 4th here
>And I've had to add a special case for Gene3D because the URL in the GO.xrf_abbs file seems to be out of date. Where should I report that?

At this point we decided to omit Gene3D for now.

I'll get the xref.

**Comment by ValWood** [comment]
OK, I have drawn a blank.
If I search Gene3D  for the IDs we display from InterPRO
i.e G3DSA:3.30.200.20 I get no result.

I can\'t find any information on linking in at Gene3d.

If I google the ID G3DSA:3.30.200.20, all of the hits are to other resources.

I will mail them.

v

**Comment by kimrutherford** [comment]
> At this point we decided to omit Gene3D for now.

OK, I'll remove it again.

> If I search Gene3D for the IDs we display from InterPRO

Midori's pull request uses URLs like:
 http://gene3d.biochem.ucl.ac.uk/search?mode=family&sterm=3.30.390.30

**Comment by ValWood** [comment]
OK Midori has done it already!

**Comment by ValWood** [comment]
No don't remove it. Sorry for the confusion.

**Comment by ValWood** [comment]
yep
