### ISSUE TITLE
sequence download

### ISSUE THREAD

**Issue by ValWood** [pombase/website#415]
e.g. pil1

When I first look, it seems fine (this is a single exon gene):

![pil1](https://user-images.githubusercontent.com/7359272/27537083-18d5880e-5a6a-11e7-8072-5e110edafa96.jpg)

include introns no change- good

include 5'UTR
![5 utr](https://user-images.githubusercontent.com/7359272/27537136-52d5ded2-5a6a-11e7-8523-519beeaa23dc.jpg)

looks fine this is 5' UTR
>SPCC736.15 SPCC736.15 undefined product 348692:349171 forward
ATATATATATAATCTTTTTTTTTTTTATATATACCCCATCACATTTTTGTTATACCCAGA
GAATAGCCGCTAAGCAAAAGTTAAGCTAAGCTAAGTGAATTTGAAAGAAATCCAAAAGGA
AAATTTCCTCGTTTTTCCCTTTCCCCAAAAAAAAATCCCGACTCCTTTCCATTTTTTCAT
ATAGTCGACAAATTTTTTTATTTTTGGGCTTTTTTTATACACACTCTCTCTATCTAACTA
TCTATCCTATTTAACTATATACCCACGAAATTTCGTATCGCCCTTTGGTAAAGTGTTAAA
CATTTTTCGTCCTACTCTTTTTTTTTTACTTATAACTCGTCCTCTCTCTACTAAATTATT
CTCACTATAATTGTTCTTATTAGTATCATCACATACTAATATACTACTACTACTACCACT
TATTTTTATTATTACTACCATCTCTTCTTATTTACCCACATCTATTTCTATTTCTGCAAG

**Comment by ValWood** [comment]
Add 100 upstream of annotated UTR:

![upstream](https://user-images.githubusercontent.com/7359272/27537306-32a9b556-5a6b-11e7-90be-bb4323b431c6.jpg)

This is correct too...I did it in Artemis...

**Comment by ValWood** [comment]
I think the issue could be that you can take the UTR out at this point, but still include bases upstream of UTR. This doesn't really make sense as an option (although it is doing what the label says).

I think we should change the behavior so that  it is 
 "include 1000 bases upstream of selected region" 
so you would get bases upstream of the CDS if you excluded the UTR. 

This mirrors  PomBase1  custom download if you choose not to include UTRs

**Comment by Steefkens** [comment]
Hi Pombase,
yes you're right my problem was not reading the label correctly. However in the old version you would retrieve the flanking regions of the CDS rather than the region when you deselected the UTR option and did select the flanking sequences. In my opinion this made more sense than cutting out the UTR but still retrieve sequences outside of it. Cheers, Steve

**Comment by ValWood** [comment]
yes I think so too, these constructs would not exist in biology!

**Comment by kimrutherford** [comment]
Good points.  I'll make it more biologically sensible.

See also: #397.

**Comment by ValWood** [comment]
Should do this one after the GO loading (or is it done). Then I can say it's all working.

**Comment by kimrutherford** [comment]
> Should do this one after the GO loading (or is it done).

It's not fixed yet.

**Comment by kimrutherford** [comment]
> It's not fixed yet.

Sorry, I answered too quickly.  I think this is done if you're happy with the new labels and how the options act now.

It's #397 that isn't done: the sequences are still wrong if you select the UTR or up/down stream option.  I'm working on that one.

**Comment by ValWood** [comment]
I think we still need to be able to retrieve "bases upstream of CDS"


Often people want to ignore the UTRs and just include 100 bp upstream an downstream (for example).
Previously when they did this, it  started from the end of the UTR.
Sorry I wasn't paying attention.

Flag as discuss if you don't know what I mean...

**Comment by kimrutherford** [comment]
> I think we still need to be able to retrieve "bases upstream of CDS"

If I'm understanding you correctly, I think that's done now.  If you don't check the UTR box you get sequences up or downstream of the CDS rather than the UTR.  Could you have a look at the currently version and see if it works how you'd expect?

**Comment by ValWood** [comment]
I think that works !
Can  somebody double check I didn't miss anything before closing.
v

**Comment by ValWood** [comment]
@mah11  could you once over this one too?

**Comment by mah11** [comment]
I haven't tested extensively, but the quick prod I just did looks fine.
