### ISSUE TITLE
Some physical interactions (but not all) showing in duplicate

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#417]
Some interactions are duplicated.  See sad1, https://github.com/pombase/pombase-chado/issues/632

**Comment by ValWood** [comment]
we'll keep this in the "public release" set but it isn't critical....

**Comment by ValWood** [comment]
in fact, you can do it soon after. People will benefit more from P2 than waiting for this fix...

**Comment by ValWood** [comment]
Labelled as a bug to keep it high priority afterwards.

**Comment by kimrutherford** [comment]
Val, from the Chado issue:
>  BUT, that we don't need to do this for self-self binding .

Yep!  Thanks for the hint.

The code adds each interaction annotation to the bait gene page and the prey gene page so it gets added twice if the bait and prey are the same.  I'm testing the fix now and will check it after Friday night's load.
