### ISSUE TITLE
RT migration

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#418]
Not quite website but maybe we should have a ticket for it? Maybe we can just migrate it? 
https://bestpractical.com/request-tracker/

**Comment by mah11** [comment]
I thought we wanted to find different software with something closer to a usable interface?

**Comment by Antonialock** [comment]
yes but we might need it for archive?

**Comment by ValWood** [comment]
I'm working on   the migration issue. We will use RT and it will  most likely be housed at genetics...
Will explain Thursday.

**Comment by ValWood** [comment]
this is close.

**Comment by ValWood** [comment]
this seems out of date...
