### ISSUE TITLE
Sequence section, residue number

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#419]
I think it would be super neat if when you mouse-over a residue/base in the sequence section, its number is indicated in a pop-up

**Comment by ValWood** [comment]
I agree that would be very nice.

**Comment by Antonialock** [comment]
We thought about this again in #541 would this be quick to do?

**Comment by kimrutherford** [comment]
Do you want to see the residue number relative the start of the visible sequence or from the start of the coding sequence?  So should the numbering change when you turn on the UTR(s) or introns?

**Comment by Antonialock** [comment]
ATG is at +1, anything else counts from -1?

**Comment by Antonialock** [comment]
to deal with introns we could show both c and g?
e.g. http://www.hgvs.org/mutnomen/refseq.html

**Comment by kimrutherford** [comment]
> ATG is at +1, anything else counts from -1?

Sorry, I don't understand that.  What do you mean by counts from -1?

**Comment by ValWood** [comment]
yep when we are describing nucleotide positions  we treat the nucleotide1 of the ATG as "1" and number backwards negatively....

**Comment by kimrutherford** [comment]
> to deal with introns we could show both c and g?

Sorry I don't understand that either.

**Comment by ValWood** [comment]
Let's future this one! It might be  a time sink...;)

**Comment by ValWood** [comment]
and is partially overlapping with future "protein viewer"

**Comment by kimrutherford** [comment]
> yep when we are describing nucleotide positions we treat the nucleotide1 of the ATG as "1" and
> number backwards negatively....

So the hovering would only show a base number in exons and UTRs, not in introns?

**Comment by ValWood** [comment]
too complicated, especially for nucleotide...

**Comment by Antonialock** [comment]
For proteins it should be straight forward: initiator mehionine is "1".

For nucleotides it is more complicated:
Positive numbering always starts at the ATG codon (+1), upstream of ATG numbering is negative starting at -1 (closest to ATG).

nucleotide numbers are often prefixed with a letter to indicate what type of sequence you are talking about. It is a bit complicated. 

For example "c" = coding sequence
This number refers to nucleotides translated into protein (starts at ATG)
c12 is nucleotide number 12 (A=1, T=2, G=3)
c-12 is 12 nucleotides upstream from the ATG
c100+5 means 5 nucleotides into the intron spliced out after nucleotide c100

could we do it like this @ValWood ?

**Comment by ValWood** [comment]
@kimrutherford  could give an estimate of how feasible. Its not worth a huge time investment right now if it would take a while.... Need to get on with other stuff. But could stay on the back burner.

**Comment by Antonialock** [comment]
Kim it would be fab to have it for protein sequence if that's not too time consuming to do, but maybe keep nucleotide sequence for later / once we decide on a good system to follow

**Comment by kimrutherford** [comment]
> Kim it would be fab to have it for protein sequence if that's not too time consuming to do

I'm not sure how to do it but I'll investigate and if it's quick I'll do it soon.

**Comment by kimrutherford** [comment]
I haven't been able to work out an easy way to do this using a mouse over.

But I was able to change things so that if you select some sequence, it shows the start and end coordinates.  This only works for nucleotide sequence at the moment.  If it's useful I do the same thing for the protein sequences.

The positions are calculated from the start of the visible sequence and it counts everything visible.  So if you turns introns or UTRs on the coordinates within the exons will change.

Unfortunately Firefox and Chrome use yellow to highlight the selection which makes the selected bases look like an intron.  We can fix that.  (And it wouldn't be a problem for protein sequence)

Also the bold style for the exons that you're hovering over doesn't work well while selecting bases.  You'll see lots of flashing of bold versus normal as you select bases if the gene has many exons.

Here's how it looks in pombase-dev:

<img width="577" alt="screenshot 2017-11-13 18 01 15" src="https://user-images.githubusercontent.com/90474/32710417-e34b1d4c-c89c-11e7-9ece-d1d46fde24d9.png">

**Comment by ValWood** [comment]
Very nice, yes do it!

(we could always change default colour for introns if easier).

We should announce this as its really useful and people won't see its available until told...
(I still l go to Artemis if I need to work out  sequence residue numbers because it's often easier)

**Comment by kimrutherford** [comment]
> Very nice, yes do it!

OK.  I'll fix the protein sequence to do the same thing tomorrow.

> We should announce this as its really useful and people won't see its available until told...

It's quite rough under the hood at the moment.  Tomorrow I'll do some more testing, including on Internet Explorer.

**Comment by ValWood** [comment]
We won't announce until its been there a few days for testing ;)

**Comment by Antonialock** [comment]
super!

**Comment by kimrutherford** [comment]
(From Antonia)

seems to work for most intervals but some don't show

<img width="624" alt="32783071-685c0596-c942-11e7-9522-1194bbdaee96" src="https://user-images.githubusercontent.com/90474/32809888-958c7ee0-c9fd-11e7-8a13-42e41406fd3b.png">

**Comment by kimrutherford** [comment]
> seems to work for most intervals but some don't show

Was that on Firefox?

I mostly tested on Chrome where it works well for me. It seems to work, er, less well in Firefox.

I'll work on the problem.

**Comment by kimrutherford** [comment]
> seems to work for most intervals but some don't show

I've been able to fix the problem in the development/alpha version of Firefox and in Microsoft Edge (which is the new version of Internet Explorer).  But in the other browsers, including the current Firefox, I can't see how to fix it.  Since it works in Edge and should work in the released version of Firefox soon, I think it's likely that Chrome will be fixed at some point too.

(The fix will be in the main site mid-morning)

**Comment by ValWood** [comment]
Let me know when implemented for protein.

val

**Comment by Antonialock** [comment]
If it is difficult then don't fix for old browsers imo....we can just tell people to update their browsers.

**Comment by ValWood** [comment]
Agree....don't worry about that...

**Comment by kimrutherford** [comment]
> If it is difficult then don't fix for old browsers imo....we can just tell people to update their browsers.

I can't work out how to fix it for older browsers so I'm glad it's not a serious bug.

**Comment by Antonialock** [comment]
leave this ticket open until we know that chrome is fixable too?

**Comment by ValWood** [comment]
It works for me on chrome, what is the problem?

**Comment by kimrutherford** [comment]
> It works for me on chrome, what is the problem?

There a slight gaps between line (just a pixel or two).  If you are selecting and pause your mouse over the gap the "Selected residues: ..." bit disappears.  It comes back if you move your mouse up or down.  

> Let me know when implemented for protein.

I've implemented that now.  It will be in the main site tomorrow.

**Comment by kimrutherford** [comment]
I quite like the idea of marking up the exons in the protein sequence but I don't know if that's useful.

**Comment by ValWood** [comment]
It's not super useful but it might help people a little to orient themselves between the nucleotide and the protein sequence.....

**Comment by kimrutherford** [comment]
A display like Artemis would be good.  :-)

**Comment by kimrutherford** [comment]
> leave this ticket open until we know that chrome is fixable too?

I've done some more testing and it seems OK on Chrome on Mac.  I saw the problem with Chrome on Linux.  I'm going to close this since it's only a minor problem and there won't be many Linux users (possibly just me).
