### ISSUE TITLE
query builder annotation status

### ISSUE THREAD

**Issue by ValWood** [pombase/website#423]
when I did "conserved unknown"
I got 496

acb1 (SPBC1539.06)	fatty-acyl-CoA transporter protein Acb1 (predicted)
is included. This is   colour 7 (biological role inferred)

**Comment by ValWood** [comment]
also lam6. So it just seems that its not using quite the same data as
http://pombase2.aska.gen.nz/
or
http://preview.pombase.org/

**Comment by kimrutherford** [comment]
I've just synchronised the two sites.  Is it OK now?

**Comment by ValWood** [comment]
The query builder still reports  
acb1 (SPBC1539.06)	fatty-acyl-CoA transporter protein Acb1 (predicted)
as "conserved unknown"
(first one in the list)

**Comment by kimrutherford** [comment]
Sorry, the prototype query server was pointing at some old test data.  I've fixed it.  There are 491 conserved unknown now.

**Comment by ValWood** [comment]
Yes this list looks great when sorted by product. I can clean it up today now, I'm sure I can squash it some more...
