### ISSUE TITLE
query history  saving

### ISSUE THREAD

**Issue by ValWood** [pombase/website#424]
reporting this because it was working before...

**Comment by kimrutherford** [comment]
It's not disappearing for me.  Perhaps try reloading?

**Comment by ValWood** [comment]
Its there , but as soon as you leave the page to look at a gene and return, it has disappeared.
I can work around by opening a new browser to look at the genes ;)

**Comment by kimrutherford** [comment]
> Its there , but as soon as you leave the page to look at a gene and return, it has disappeared.

Ah, I'm pretty sure it's always been like that.  The history isn't saved at all.

**Comment by ValWood** [comment]
1. Make history list sticky
2. Add delete query button

**Comment by kimrutherford** [comment]
As a first step towards saving the history, I've fixed things so that the history doesn't disappear when you navigate away from the query builder.

**Comment by kimrutherford** [comment]
The query history is now stored in the browser's local storage.  So it should stick around if you restart your browser.

There are still some issues.  The main one is that if you have have two tabs open it will only save the history from the tab where you most recently ran a query.  It will overwrite changes in the older tabs.  I think that can be fixed but I'll come back to it after finishing some of the higher priority stuff.

**Comment by kimrutherford** [comment]
I've updated the preview.  The history should now be persistent even if you reload or restart your browser.  Please let me know if you spot any weirdness.

**Comment by kimrutherford** [comment]
We need to avoid duplicates in the history by only saving queries that aren't in the history already.  If we run a query that's already there, probably the least surprising behaviour is for the existing query to be moved to the top of the list.

**Comment by kimrutherford** [comment]
> Add delete query button

That was done a while ago although I fixed a delete bug yesterday.

**Comment by kimrutherford** [comment]
> We need to avoid duplicates in the history by only saving queries that aren't in the history already.

I've fixed that.

I've also changed the query displaying to show the expression level and if you selected single or muilti allele for the phenotype querying.  Previously it just shows the term ID and name in the history.  It looks a bit like this now:

     abnormal cell wall (FYPO:0002946) [Overexpressed wild-type - single allele genotypes]

Any suggestion for a better format for this?

**Comment by ValWood** [comment]
I think thats fine unless anyone has any "shortening" suggestions

**Comment by ValWood** [comment]
can close?

**Comment by kimrutherford** [comment]
Yep, I think we can close this and open issues as we think of them.
