### ISSUE TITLE
comma separated  "from" field not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/website#425]
/GO="aspect=C; term=mitochondrial membrane; GOid=GO:0031966; evidence=IC; db_xref=GO_REF:0000036; from=GO:0005739,GO:0016021; date=20080218"

is resolving to a single GO term (note it is the incorrect term due to transposed GO ID, now fixed).

Worth checking ISS/M/O  with= too

**Comment by ValWood** [comment]
This should be quick. Ping me if does not make sense.

**Comment by kimrutherford** [comment]
> is resolving to a single GO term

That's now fixed if you reload.  Luckily everything was OK in Chado so it was quick to fix.

> Worth checking ISS/M/O with= too

Fixed too.  For example the first process annotation here:
  http://preview.pombase.org/gene/SPAC16C9.05
