### ISSUE TITLE
pombase slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#426]
mitochondrial gene expression was recently swapped for mitochondrial translation in the pombase slim.
I can't remember if you are importing or if we have a hard coded temporary list?

**Comment by kimrutherford** [comment]
For now the slim list is in the config file in Subversion:
  pombe-embl/website/pombase_v2_config.json

Look for the "go_slim_terms" section.

If you make changes, let me know so I can re-release.

**Comment by ValWood** [comment]
I just updated the slim....

**Comment by kimrutherford** [comment]
> I just updated the slim....

I've re-released and mitochondrial gene expression is there now.

**Comment by ValWood** [comment]
yep thanks!
