### ISSUE TITLE
Uniprot link broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#427]
http://preview.pombase.org/gene/SPAC4H3.11c

external ref section
http://preview.pombase.org/[object%20Object]

Everything which uses this link

**Comment by ValWood** [comment]
Is this quick...It looks quick and its a bit annoying ;)

**Comment by kimrutherford** [comment]
Should be fixed now,

**Comment by ValWood** [comment]
thanks, all links using uniport work.
