### ISSUE TITLE
Fix the protein feature section for pseudogenes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#428]
It's empty - we shouldn't show the section for psuedogenes.

**Comment by ValWood** [comment]
http://pombase2.bioinformatics.nz/gene/SPAPB24D3.05c

Name should show (systemtic iD), and image map, location?

Not sure we need anything else for now...

**Comment by ValWood** [comment]
added quick, correct me if not

**Comment by kimrutherford** [comment]
Fixed.
