### ISSUE TITLE
change labels in query builder  

### ISSUE THREAD

**Issue by ValWood** [pombase/website#429]
In query list of 
"Annotation status" to "Characterisation status"
"Taxon distribution" to Taxonomic conservation

**Comment by ValWood** [comment]
The box now overlaps a bit:

![hidden](https://user-images.githubusercontent.com/7359272/27951133-c7f3de96-62fb-11e7-89d0-08b14b08c9d8.jpg)

**Comment by kimrutherford** [comment]
I've fixed the box overlap but we still have the problem that the Characterisation status dropdown can be wider than the box.  That's harder to fix.

Can we make the labels shorter?  Maybe drop the word "protein" from "Schizosaccharomyces pombe specific protein, uncharacterized"?

**Comment by mah11** [comment]
or abbreviate to "S. pombe ..."?

**Comment by ValWood** [comment]
I was just going to say the same...

**Comment by mah11** [comment]
great minds and all that ...

**Comment by kimrutherford** [comment]
I'll do that for the S.pombe one.  This one will still be long though:

"Schizosaccharomyces specific protein, uncharacterized"

Any suggestion for shortening it?

**Comment by ValWood** [comment]
tricky..

fission yeast specific is true, but confusing...

**Comment by ValWood** [comment]
This should not be so tricky, I'm sure we can resolve tomorrow.

My suggestion:
Schizos. specific protein, uncharacterized

**Comment by kimrutherford** [comment]
Done.
