### ISSUE TITLE
Reactome links

### ISSUE THREAD

**Issue by mah11** [pombase/website#43]
Add links to gene pages to relevant Reactome entries. Waiting for Reactome to have stable IDs for computationally inferred events; may also require UniProt to update their Reactome links more regularly, depending on where & how we get link info.

We may even want to wait until Reactome has some directly curated entries for pombe, and in any case we'll want it to be obvious when a Reactome event is inferred by orthology.

**Comment by ValWood** [comment]
https://reactome.org/linking-to-us

**Comment by ValWood** [comment]
we could add this  link to gene specific  external links,
https://reactome.org/content/query?q=P04551
and, a  link from the GO term pages...

then this can close?

**Comment by kimrutherford** [comment]
I've added entries like this to the "External references" section:
```
Pathways   Reactome   P07527   Manually curated and peer-reviewed pathways
```

That's live now.

Which GO aspect term pages should have links to Reactome?  I've added it to MF and BP for now.

**Comment by ValWood** [comment]
I'm not sure how uesful these are. Some have a pombe entry but many don't.... they might be more annoying then useful....

Thoughts @Antonialock  @mah11

**Comment by ValWood** [comment]
they are there now so closing
