### ISSUE TITLE
Searches to add

### ISSUE THREAD

**Issue by ValWood** [pombase/website#430]
- [x]  Product type (protein coding, tRNA etc)

- [x] PBO disease associated

- [x]  Number of  TMM domains (Need TMHMM data)

- [x]  protein  size (mass and length)

Lower priority, could be hidden by default

- [ ]  Chromosomal filters 
            genes on chromosome
            genes between co-ordinates
            genes in a region (maybe theses could be in the canned queries list, I did not know they were there!)

- [x]  Genes with N exons

- [ ]  Interactors of

- [x]  Any domain

**Comment by ValWood** [comment]
I would say only the top four are critical for making query builder public in preview

**Comment by kimrutherford** [comment]
> Number of TMM domains (Need TMHMM data)

I've installed the tmhmm command line tool on oliver0.  It shouldn't be too hard to use the output.

**Comment by kimrutherford** [comment]
> PBO disease associated

The list looks too long to be a pop up list so should be an autocomplete box?  Is it obvious what to search for?

**Comment by ValWood** [comment]
Not completely, but that's ow it works ATM.
Users probably largely arrive from here:
http://www.pombase.org/faqs/how-can-i-find-s-pombe-genes-associated-human-disease
to find all disease genes (to support grants and the like). Cancer or metabolic disorder might be a common one and people would probably think to type that. I doubt that many people would search on a specific disease, you would find out the ortholog and get to a gene that way. That said, query aficionados probably realise they can plug in any term from a  gene page.

**Comment by ValWood** [comment]
The disease search option should probably go under "specialist" filters eventually. It isn't an ever day query.

**Comment by kimrutherford** [comment]
> Product type (protein coding, tRNA etc)

I've added that to http://pombase2.bioinformatics.nz/query

**Comment by ValWood** [comment]
working great!

**Comment by kimrutherford** [comment]
> protein size (mass and length)

I've added these queries:
Protein mol. weight
Protein length

**Comment by kimrutherford** [comment]
> Protein mol. weight

Currently that is in daltons, but I'm fixing it now.

**Comment by ValWood** [comment]
Ok, protein length working fine, Thanks!

**Comment by kimrutherford** [comment]
> Currently that is in daltons, but I'm fixing it now.

I've fixed it so that it searches for kD rather than daltons.

**Comment by kimrutherford** [comment]
> PBO disease associated

Unfortunately that's tricky for now because we're using Canto for auto-completion and we don't load that ontology in Canto.  I'll working on a plan to replace Canto for completion.

**Comment by mah11** [comment]
Do you still want "all genes"? asking for a FAQ update ...

**Comment by ValWood** [comment]
I guess its useful, but people can do it by summing...

**Comment by mah11** [comment]
If we're not going to have an "all genes" query option, then I'll rejig the get-all-the-genes FAQ to point to the downloadable file. I won't tell people to do 8 or more queries for the info!

**Comment by ValWood** [comment]
Oh probably we should have the query. If the choice is 8 queries, of download a file and upload the list....?
Or it could be a "canned" query when we have those.

**Comment by kimrutherford** [comment]
> Number of TMM domains (Need TMHMM data)

See also: #381.

**Comment by kimrutherford** [comment]
> Number of TMM domains (Need TMHMM data)

We've got the TM data now.  The Protein features section of gene pages now shows the coordinates of the TM predictions.  It's formatted like this at the moment because I thought it would use too much vertical space to have the numbers in a table.  I can changed though.  Let me know what you think.

It's formatted like this at the moment:

    Coordinates of predicted trans-membrane domains:
    12..34, 56..78, 91..113, 118..140, 147..169, 174..196, 284..306, ...

Now the TMHMM results are available I can implement the query for number of TM domains.

**Comment by kimrutherford** [comment]
> results are available I can implement the query for number of TM domains.

That's done and seems to work OK for me.  Let me know if you have any problems.

**Comment by kimrutherford** [comment]
>  Any domain

That's done I think.

>  Genes with N exons

Should that count include UTR exons?  There aren't that many genes but there are a few, eg. SPCC553.05c.  If it helps your decision, it's easier to implement if it just counts coding exons.

**Comment by kimrutherford** [comment]
>  it's easier to implement if it just counts coding exons.

That was easy enough that I went ahead and did it.

**Comment by ValWood** [comment]
Lets call  the search "coding exons".

**Comment by kimrutherford** [comment]
> Lets call the search "coding exons".

OK, I've made that change.

**Comment by ValWood** [comment]
I'd find the "any domain" query useful   if it's quick to add.
Otherwise, punt all this until after public release.
Some will work better as "query templates" https://github.com/pombase/website/issues/416

**Comment by ValWood** [comment]
How easy is "any domain"? If it is quick, could you do it next?
It would make my classification for the unknowns paper much quicker if I could easily identify the subsets with and without domains...

**Comment by ValWood** [comment]
Is "any domain" easy?

if this could be added I can finish my figure and the version2 label can be removed from this ticket.
v

**Comment by kimrutherford** [comment]
> PBO disease associated

That's done now although we should discuss how to label it.

**Comment by ValWood** [comment]
I can't search on PBO:5000000 - disease_associated
(this is the term which gives all disease associated)

**Comment by kimrutherford** [comment]
> I can't search on PBO:5000000 - disease_associated

We don't have an ontology for disease_associated in Chado, just a flat CV.  Do you have an OBO file we can load?

**Comment by ValWood** [comment]
Not at the moment. Long term plan is to use the official disease ontology.
Can we fudge it?
Any ideas anyone.
can discuss on next call how best to handle.

**Comment by kimrutherford** [comment]
> Any ideas anyone.

I think it's best to make a very simple OBO file.  We don't need definitions or any of the other fiddly stuff so it would only take a few minutes to do.  I'm happy to do that if you think it's a good idea.

Currently there isn't a term page for PBO:5000000.  If we made an OBO file containing PBO:5000000 and the relations to the other terms we get a disease_associated term page for free.

**Comment by kimrutherford** [comment]
> I think it's best to make a very simple OBO file.

I went ahead and did that.  I will be in the next load.  It's here:
  pombe-embl/mini-ontologies/disease_associated.obo

**Comment by kimrutherford** [comment]
The disease_associated.obo file loads fine but I forgot that as well as being loaded into Chado, ontologies need to be processed with OWLTools so that the relationships are available in the website.

Until now we have only been processing the big ontologies like FYPO and GO with OWLTools because that's all that was needed.  I've fixed the load script to process all ontologies and I'll check the load on Thursday morning.

Summary: you can't search for PBO:5000000 yet in the query builder but hopefully it will be in tomorrow.

**Comment by kimrutherford** [comment]
> Summary: you can't search for PBO:5000000 yet in the query builder but hopefully it will be in
> tomorrow.

Sorry I still haven't successfully finished a load due to my typos and oliver0 dying.  Hopefully soon.

**Comment by kimrutherford** [comment]
> Summary: you can't search for PBO:5000000 yet in the query builder but hopefully it will be in tomorrow.

That's working now.
