### ISSUE TITLE
query builder bug

### ISSUE THREAD

**Issue by ValWood** [pombase/website#438]
I retrieve a protein kinase inhibitor  (rum1) when I search on "MAP kinase activity"

This might be because we are making "regulates" relationship  transitive over MF as well as biological process. 

(Although I'm still not sure whey rum1 comes up because it isn't a MAP kinase inhibitor).

Anyone?

**Comment by ValWood** [comment]
actually this list also has
atf1
lsk1
rnc1
ste11

and the regulates relation does not seem to be the reason here

**Comment by ValWood** [comment]
GO:0004707 - MAP kinase activity
has only pmk1 and sty1
http://pombase2.bioinformatics.nz/term/GO%3A0004707

**Comment by ValWood** [comment]
OH I see, its including the substrates too :)

**Comment by kimrutherford** [comment]
> OH I see, its including the substrates too :)

Yep.  Drat.  I've just committed a fix.  The query builder data will be updated in 5 minutes or so.

**Comment by kimrutherford** [comment]
It should be OK now.

> GO:0004707 - MAP kinase activity
> has only pmk1 and sty1 and spk1

Yep!  That's what it gives now.
