### ISSUE TITLE
outage warnings on gene pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#44]
If we have to post a warning about downtime for all or part of PomBase, the warning should appear on all pages, including gene pages.

**Comment by ValWood** [comment]
soon after , but since we don't have it now, not required before

**Comment by ValWood** [comment]
will  up the priority if we have outages soon....

**Comment by ValWood** [comment]
I'll close and when we need it a new ticket can be opened which I'm guessing would be implemented quickly/immediately if we had notification of an impending outage....
Let's deal with this in "fire fighting mode" when/if we have one.
