### ISSUE TITLE
GO molecular function section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#440]
from
https://github.com/pombase/website/issues/159

Should we have "show details" twice, only one "show details" at the top, or something else?

**Comment by ValWood** [comment]
A quick  fix here would be

"show activity details"
and
"show binding details"

(would make the 2 parts of **Molecular Function** clearer

**Comment by ValWood** [comment]
If people don't like this suggestion will punt to "low priority" while we think of something else.

**Comment by kimrutherford** [comment]
> A quick fix here would be
> "show activity details"
> and
> "show binding details"

It was quick so I implemented this but now I have second thoughts.

The other place we split a section like this is for phenotypes, "Population phenotype" versus "Cell phenotype" but in that case we just label the two different classes on phenotype (population vs cell).  Can we do that in the MF section too?  It would be more consistent.

**Comment by ValWood** [comment]
I don't mind if you do

Activity terms
show details

and

Binding terms
show details

**Comment by ValWood** [comment]
I wonder if there was a reason we  didn't suggest that?

**Comment by kimrutherford** [comment]
> I don't mind if you do

OK, I'll do that and see how it looks.

> I wonder if there was a reason we didn't suggest that?

I think you initially just wanted the binding terms sorted to the bottom of the list but it was easier to implement by splitting into two tables.  It was a temporary-ish fix.  I think I also we talked about filtering and how that could help.

**Comment by kimrutherford** [comment]
> I don't mind if you do
> Activity terms
> ...

Done and released on the main site.

Does that look OK?

**Comment by ValWood** [comment]
yeah it looks good actually.....

**Comment by Antonialock** [comment]
I like it, the split doesn't feel cryptic any longer

**Comment by kimrutherford** [comment]
> I like it, the split doesn't feel cryptic any longer

Great.  I'll close this then.
