### ISSUE TITLE
query builder bug?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#441]
abnormal negative regulation of mitotic DNA replication initiation resulting in slow rereplication FYPO:0001427

giving zero results.
was repeating 
https://github.com/pombase/website/issues/284
to check status

**Comment by kimrutherford** [comment]
FYPO:0001427 has no single gene phenotypes:
http://preview.pombase.org/term/FYPO%3A0001427

so zero results is right isn't it?

**Comment by ValWood** [comment]
odd, where did these go?

https://cloud.githubusercontent.com/assets/7359272/25489967/5c2300fe-2b63-11e7-87a0-75809c38135a.jpg

from https://github.com/pombase/website/issues/284

**Comment by ValWood** [comment]
I know that cdc13 is involved in re-replication...

**Comment by ValWood** [comment]
oh it's a different term
http://pombase2.bioinformatics.nz/term/FYPO%3A0004596

**Comment by ValWood** [comment]
would expect
FYPO:0004596 - abnormal negative regulation of DNA replication initiation during mitotic G2 phase resulting in complete rereplication
to both, need @mah11  to comment.

**Comment by ValWood** [comment]
OK its fine
http://preview.pombase.org/term/FYPO%3A0000216
its late...
