### ISSUE TITLE
GO substrate  does not have reciprocal target_of annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#442]
rum1
- | GO:0004861 | cyclin-dependent protein serine/threonine kinase inhibitor activity

has direct input cdc2 has direct input cdc13

but does not appear in cdc2 or cdc13 GO target_of section

**Comment by kimrutherford** [comment]
It looks like that term doesn't match the configuration in pombe-embl/website/pombase_v2_config.json

The config is in the "extension_display_names" section.

To appear in the "Target of" part of the gene page the annotation must have a extension relation that matches a "rel_name" in that section.  Some configs have a "if_descendent_of" setting.  If that is present then the term in the annotation must be a descendent of the configured term.

eg.

    {
      "rel_name": "has_direct_input",
      "if_descendent_of": "GO:0003824",
      "display_name": "has substrate",
      "reciprocal_display": "substrate of"
    },

This will match any annotation where the term is a descendent of "GO:0003824" and has "has_direct_input" as a extension relation.

The string in the "reciprocal_display" field is used in the "Relationship" column of the target of gene page section.

For has_direct_input, currently only descendants of these terms are configured:

GO:0003824
GO:0005085
GO:0005215
GO:0005488
GO:0006810
GO:0008047
GO:0051179

"cyclin-dependent protein serine/threonine kinase inhibitor activity" has these parents:

    cyclin-dependent protein serine/threonine kinase regulator activity | GO:0016538
    protein kinase regulator activity                                   | GO:0019887
    protein kinase inhibitor activity                                   | GO:0004860
    molecular function regulator                                        | GO:0098772
    molecular_function                                                  | GO:0003674
    enzyme inhibitor activity                                           | GO:0004857
    enzyme regulator activity                                           | GO:0030234
    protein serine/threonine kinase inhibitor activity                  | GO:0030291
    kinase inhibitor activity                                           | GO:0019210
    kinase regulator activity                                           | GO:0019207

**Comment by ValWood** [comment]
I think we need to add
enzyme regulator activity                                           | GO:0030234

**Comment by kimrutherford** [comment]
> I think we need to add
> enzyme regulator activity | GO:0030234

OK, I've added that, recreated the web data and updated the preview.  rum1 appears in those Target of sections now.

I've also documented that part of the configuration here: 
https://github.com/pombase/website/wiki/Config-file#extension_display_names

**Comment by ValWood** [comment]
Fab!
