### ISSUE TITLE
Add JBrowse to PomBase v2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#443]
We need to add all tracks from v1 not just the genes.  Is there a list of the extra data that we have in the Ensembl browser?

This a major JBrowse blocker: https://github.com/GMOD/jbrowse/issues/772

**Comment by ValWood** [comment]
This is where the datasets live:
ftp://ftp.ebi.ac.uk/pub/databases/pombase/DATASET/

Current list
BindingSites/		
Bitton_IBP_24709818/		
DJeffares_Diversity/		
Daigaku/		
ERP001075/		
ERP001483/	
GSE24360/	
GSE41773/	
GSE62108/	
GSM1519714/		
GSM1519715/		
GSM1519716/		
HuaLiTSS/		
JuanMata_polyA/		
MSchlackow_polyA/		
NRhind_RepProfile/		
NRhind_Transcriptome/		

- [ ]  make a better directory naming system

**Comment by ValWood** [comment]
I'm not sure if we display all data in each directory.
It isn't clear from the individual  dataset naming how the individual data correspond to the tracks, we need to ask for/find a mapping between track names and our labels in the Ensembl.


This is our system  for display  data
https://curation.pombase.org/pombase-trac/wiki/TrackRelabelling
I suggest we name  data-sets correspondingly with
A datatype
C differentia
E citation
(should be enough to unique-ify each track)

**Comment by ValWood** [comment]
we will start moving with this, but the browser can come after move  of pombase to www

**Comment by kimrutherford** [comment]
We should chat about how we want JBrowse to look.  Here's the demo with some options we can look at:
  http://jbrowse.org/code/JBrowse-1.12.3/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A14958..24958&tracks=DNA%2CTranscript&highlight=

If any one knows of a database that uses JBrowse and it looks particularly good, we should think about copying their configuration.

**Comment by kimrutherford** [comment]
Enough stuff is working now that we have a basic, dodgy JBrowse for genes:
https://www.pombase.org/jbrowse/index.html?loc=chromosome_2%3A2276331..2290670&tracks=DNA%2CPomBase%20features&highlight=

Non coding genes are currently have just a label showing.  I'll work on that.

I'll chip away at getting the other Chado features into JBrowse and I'll investigate how to configure the external files (BAM, BED etc).

**Comment by ValWood** [comment]
Wowsers....i'll have a poke around after pascale.

**Comment by ValWood** [comment]
SGD is pretty nicely organized:

https://browse.yeastgenome.org/?loc=chrI%3A178499..215155&tracks=DNA%2CAll%20Annotated%20Sequence%20Features%2CDoube_strand_break_hotspots%2CXrn1-sensitive_unstable%20transcripts_XUTs%2CScGlycerolMedia%2C3%27UTRs%2CPolII_occupancy_WT&highlight=

**Comment by kimrutherford** [comment]
I've added the UTRs to the view and fixed the RNA features so they display properly:
  https://www.pombase.org/jbrowse/index.html?loc=chromosome_1%3A496871..511210&tracks=DNA%2CPomBase%20features&highlight=

I've changed the GFF output so that misc. features like "low_complexity_region" and "mating_type_region" get written, but it didn't make it into today's update.  They'll be there in the morning.

**Comment by kimrutherford** [comment]
The misc. features like "low_complexity_region" and "mating_type_region" are now shown.  We should discuss that.  Which misc. features should be shown?  Should they be in their own track(s)?

I've had a try at adding BAM files to JBrowse but got stuck on this issue: #669

There's a search box in JBrowse that didn't seem to allow searching.  After reading the documentation a bit more carefully, I've changed the overnight load to run "generate-names.pl" to fix that.  So in tomorrow's update searching by gene identifiers will work.

We should talk about these points sometime soon:

> - Kim put this data on new ftp site (provide us details how to access, edit, add files etc)
> - curators, make a better directory naming system
> - curators check that everything displayed in Ensembl browser is in here

**Comment by kimrutherford** [comment]
I haven't made any progress on this.

For testing, I made a JBrowse configuration file on my desktop with a track for every row in the table extracted from the Ensembl configuration (see #672).  Unfortunately none of them worked as is.

 - the NRhind_Transcriptome BAM files have the wrong chromosome reference (CU329672.1 instead of III etc.)
 - all of the other tracks are bigWig files and none of them loaded

The Marguerat dataset includes bigWig and BAM files.  Ensembl was using bigWig files but they don't work in JBrowse.  When I swapped to use the BAM files that worked except for the mitochondrial and mating_type_region features which had the wrong chromosome ID in the files.

I'm fixing the all the BAM files at the moment.  It might take a day or two because converting BAM format (binary) to SAM format (text) is slow, especially on oliver0.  Once in SAM format I will fix the chromosome IDs with a bit of Perl.  Then I'll convert back to BAM and re-index the BAM files.  That's all very slow so I'm just leaving running in the background.  I 

None of the bigWig/.bw files seem to work either.  This in the JBrowse docs implies there might be compatibility problems:
  http://gmod.org/wiki/JBrowse_Configuration_Guide#BigWig_File_Compatibility
so I'm recreating the bigWig files using the latest version of wigToBigWig.  I'm running that as a background job too.

I had started fixing the BAM and bigWig files just in the NRhind_Transcriptome directory.  Then I realised that we need to fix all the files.  So I'm now fixing the chromosome IDs in all files and recreating all the BAM and .bw files.

**Comment by ValWood** [comment]
Uggh what a pain.

When you come on line later let me know if you want a  quick chat. Maybe we can close off a few quick tickets in advance of our curator meeting tomorrow. I want to focus on Canto interface stuff especially the genotype interface... (especially since community curation is picking up so much).......but we can discuss others  that are holding you up too.

PS I have my laptop back...

**Comment by kimrutherford** [comment]
The ERP001483 dataset uses these chromosome IDs:

AB325691
CU329670.1
CU329671.1
CU329672.1
X54421.1
contig_4

By process of elimination it looks like "contig_4" is the mating type region.  Before I make that change in the bigWig files, is there anything else this ID could be?

**Comment by ValWood** [comment]
I can't think of anything else it can be...do you have a fragment of sequence?

**Comment by kimrutherford** [comment]
For testing I've added all the Ensembl tracks to the JBrowse configuration.  They are mostly displaying OK now.

It's only in pombase-dev at the moment, so it's slow to load:

http://pombase-dev.bioinformatics.nz/jbrowse/index.html?loc=I%3A204565..218794&tracks=DNA%2CPomBase%20features%2CTranscripts%20-%20tiling%20microarray%20-%20meiosis%200h%2C%20pat1.114%2C%20diploid%20(forward%20strand)%20-%20Soriano%20(2013)%2CChromatin%20binding%20-%20DamID%20%2F%20tiling%20array%20-%20Arb1%20binding%20sites%2C%20repeat%203%20-%20Woolcock%20(2011)&highlight=

Next, I'm going to try to work out how to configure things to display the table of tracks like SGD has.

**Comment by ValWood** [comment]
You think that is slow? Hahahahaha. I can load all of them more quickly than one in another browser...and then I  can scroll and zoom (which I can't do with one track!)......

**Comment by kimrutherford** [comment]
The tracks are now visible on the main site so should load a bit faster:

https://www.pombase.org/jbrowse/index.html?loc=II%3A485561..499790&tracks=DNA%2CPomBase%20features%2CChromatin%20binding%20-%20DamID%20%2F%20tiling%20array%20-%20Dcr1%20binding%20sites%2C%20clr4(delta)%2C%20repeat%203%20-%20Woolcock%20(2011)%2CTranscripts%20-%20RNA-Seq%20-%20stationary%20phase%20(forward%20strand)%20-%20Rhind%20(2011)&highlight=

**Comment by kimrutherford** [comment]
There's a new version of JBrowse:
  https://sourceforge.net/p/gmod/mailman/gmod-ajax/thread/CAAFvUQ_%2B_yG1tu2bThooQ3y1Z4cFf5XoSXU-UvzcxnixKxgf%2Bg%40mail.gmail.com/#msg36227189

I don't think the new release is going to be particularly good or bad for us but I'll give it a go.  Probably next week.

**Comment by kimrutherford** [comment]
> There's a new version of JBrowse:

Just tried it locally and it's _much_ faster to load.  We've been using the un-optimised development version instead of the one meant for production use.  Whoops.  I'll deploy the new version soon, possibly tomorrow morning if the changes I just made work OK in the overnight load.

**Comment by ValWood** [comment]
wonderful! It was damn fast anyway for us!

**Comment by kimrutherford** [comment]
> I'll deploy the new version soon, possibly tomorrow morning if the changes I just made work OK
> in the overnight load.

I made the changes but forgot to update the right config file, so today's release is still on the older JBrowse.  I've fixed the config so hopefully it will be in tomorrow.

**Comment by kimrutherford** [comment]
> I'll deploy the new version soon

It's deployed now and the start-up time is much better.

**Comment by ValWood** [comment]
now in here
https://github.com/pombase/website/issues/691
