### ISSUE TITLE
extension not showing in collapsed view

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#444]
pka1 is annotated to cytoplasm during cellular response to glucose starvation, but this extension is only showing in full view, not the collapsed view
![screen shot 2017-07-14 at 11 59 12](https://user-images.githubusercontent.com/12727506/28209777-e8745f16-688b-11e7-88b7-a4263bc2660d.png)
![screen shot 2017-07-14 at 11 59 06](https://user-images.githubusercontent.com/12727506/28209783-ec679ed0-688b-11e7-8a33-6c62d1dcdffc.png)

**Comment by Antonialock** [comment]
also this protein modification annotatin is not showing in summary view, it has a unique extension:

![screen shot 2017-07-14 at 12 03 04](https://user-images.githubusercontent.com/12727506/28209890-8cafd628-688c-11e7-9da7-069a0af0c67d.png)


![screen shot 2017-07-14 at 12 02 58](https://user-images.githubusercontent.com/12727506/28209894-918966a0-688c-11e7-9d9a-0ec8a742ab69.png)

**Comment by kimrutherford** [comment]
> pka1 is annotated to cytoplasm during cellular response to glucose starvation, but this extension
> is only showing in full view, not the collapsed view

Thanks, that's an odd one.  I'll look into it.

> also this protein modification annotation is not showing in summary view, it has a unique extension

The code ignores extensions for modifications (because of #180) then after ignoring the extensions if decides that the phosphorylated residue annotation can be ignored because there are more specific annotations.  Does it need to be cleverer in this case?

**Comment by Antonialock** [comment]
Val?

**Comment by kimrutherford** [comment]
> pka1 is annotated to cytoplasm during cellular response to glucose starvation, but this extension is only
> showing in full view, not the collapsed view

This confused me but it's working as planned.  I think that extension is hidden in the summary because there is an annotation to a more specific term that has the same extension:

    vacuole  - during cellular response to glucose starvation

Perhaps we're removing too much in the summary?

**Comment by Antonialock** [comment]
Ah, I see. No it is working as intended...we could annotate to cytosol if we wanted to make this explicit (I think)

**Comment by ValWood** [comment]
I think we made a decision at some point  not to show modification extensions by default.
Should we revisit this decision. Is it odd to be inconsistent. Can we remember our reasoning?

**Comment by ValWood** [comment]
>Ah, I see. No it is working as intended...we could annotate to cytosol if we wanted to make this explicit (I think)

that would work! I think we always use cytoplasm /cytosol a bit interchangeably. I know I'm not very thorough. Good reason to be specific.

**Comment by mah11** [comment]
From #180 it looks like we took extensions out of the modification summary view because it wouldn't be easy to make residues play nicely with other types of extension in anything short of the full detail view. We also decided to see if users complained before we changed it again ;)

**Comment by ValWood** [comment]
OK! I know we had thought about it!
