### ISSUE TITLE
process view possible anomaly

### ISSUE THREAD

**Issue by ValWood** [pombase/website#446]
Here
http://preview.pombase.org/term/GO%3A0000165

wis4 appears

MAPK cascade
  | mkh1, pek1, shk2, sin1, wis4

and

stress-activated MAPK cascade
  | wis4 during cellular response to heat

but based on our current procedure
MAPK cascade
  | mkh1, pek1, shk2, sin1, wis4
should not display because its redundant with  stress-activated MAPK cascade

**Comment by mah11** [comment]
Our current procedure allows less specific terms to show up in the summary view if they have extensions that the more specific terms don't. It looks like that's the case in this example.

**Comment by ValWood** [comment]
oh yes, it has response to heat.
Ignore. That is what we want!
