### ISSUE TITLE
gene product search no longer working

### ISSUE THREAD

**Issue by ValWood** [pombase/website#447]
Probably broke when you fixed the duplication in the drop down issue?

**Comment by kimrutherford** [comment]
What was your search text?

**Comment by ValWood** [comment]
"MAP kinase" I think?

**Comment by ValWood** [comment]
weird, it's working?

**Comment by kimrutherford** [comment]
The space in "map kinase" is the problem.  If you enter "map" or "kinase" it works fine.  I'm about to update with a fix for that.

**Comment by ValWood** [comment]
Ah right I was only typing "MAP" this time  ;)

**Comment by kimrutherford** [comment]
> I'm about to update with a fix for that.

I thought I had a quick fix but product searching is still a bit broken. I'll have a think about how to fix it properly.  In the meantime, searching for an identifier (including orthologs) should work but there will be duplicates if you search for a gene name where is part of the product string (like cdc11).

**Comment by ValWood** [comment]
Yeah thats OK, not urgent...

**Comment by kimrutherford** [comment]
Cross fingers, I think it's all working now.  The autocomplete works on names, systematic IDs, synonyms, products and orthologs.

The product search isn't very clever.  It only searches for exact sub-strings so if you type "MAP kinase phosphatase" it will match "dual-specificity MAP kinase phosphatase Pmp1" but not "MAP kinase threonine phosphatase Ptc1".  That might have to wait until we have a full search implementation.

If you find problems please open new issues.

**Comment by ValWood** [comment]
Well that would be so clever we didn't ask for it, so it should work pretty well, as is....
Any further  enhancements on this can wait until after release
