### ISSUE TITLE
describing QB queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#449]
I notice that in the query results list the description of the query  effectively appears twice. This make it much harder to read the lists.

![kim](https://user-images.githubusercontent.com/7359272/28287263-e19dc2d2-6b32-11e7-9ff6-d18ea5f8fbec.jpg)

So,
characterization status: conserved unknown
characterization_status_conserved_unknown

can we omit the second one?

**Comment by kimrutherford** [comment]
Done!  It was showing both the internal ID and the user friendly name.
