### ISSUE TITLE
use ontology paths to reduce GO display redundancy

### ISSUE THREAD

**Issue by mah11** [pombase/website#45]
Extend the "compacting" behavior of the compact display to hide terms that (a) are is_a or part_of ancestors of other terms used to annotate the gene, unless the less specific term has extensions that the more specific term doesn't.

Curators to discuss
- whether to count other relations (besides is_a and part_of) for hiding
- whether to attempt any ordering fancier than plain old alphabetical

Examples:

cdc2
hide GO:0097472 cyclin-dependent protein kinase activity - it has no unique extensions, and cdc2 is annotated to GO:0004693 cyclin-dependent protein serine/threonine kinase activity

rng2
would hide
small GTPase mediated signal transduction
mitotic actomyosin contractile ring assembly actin filament organisation
mitotic actomyosin contractile ring assembly
mitotic cytokinesis

clr3
would hide
2 annotations to histone deacetylase activity
histone deacetylation
chromatin silencing at silent mating type cassette

rum1
would hide
regulation of mitotic DNA replication initiation
negative regulation of protein serene throning kinase activity
negative regulation of protein phosphorylation
cellular response to nitrogen starvation

sir2
In the sir2 MF section only show
NAD+ binding
histone deacetylase activity (H3-K14 specific)
NAD-dependent histone deacetylase activity (H3-K9 specific)
NAD-dependent histone deacetylase activity (H4-K16 specific)
zinc ion binding
histone deacetylase activity (H3-K4 specific)

These MF terms would be hidden
histone deacetylase activity
histone deacetylase activity (H3-K9 specific)
histone deacetylase activity (H4-K16 specific)

**Comment by ValWood** [comment]
This is the ticket I was looking for
https://github.com/pombase/website/issues/157

Kim could you have a look at both of these, close  mine and list  any questions.
I can't remember why I added discuss label now...

**Comment by ValWood** [comment]
Hide any GO terms /extension which do not add any information based on hierarchy.

So for example:

![hide redundancy](https://cloud.githubusercontent.com/assets/7359272/22852871/3928dffc-f03e-11e6-910b-1bd551082fe3.jpg)

This will mean that "protein kinase activity"  becomes totally redundant in compact view and only appears in full view with  supporting refs 



here, we do not need to show
protein kinase activity has substrate cdr2 
because it is covered by
serine/threonine protein kinase activity directly_activates cdr2 part_of regulation of cell size

(we can also  probably equivalize extensions on pom1 which seem to be describing the same thing)

**Comment by kimrutherford** [comment]
> Kim could you have a look at both of these, close mine and list any questions.

I think I understand what's needed.

**Comment by ValWood** [comment]
Kim says doable but had melty.
We know what is required to remove redundancy in summary view.

**Comment by kimrutherford** [comment]
I've done some of this now, but it's a bit restricted so far.  I wanted to get this on the main site so you could tell me of any problems with what I've done so far.

Restrictions:

 - only terms with no extension are removed
 - only on the gene pages
 - doesn't work for the phenotype/genotypes section

Midori's examples seem to be fixed:

> cdc2
> hide GO:0097472 cyclin-dependent protein kinase activity - it has no unique extensions, and cdc2 is
> annotated to GO:0004693 cyclin-dependent protein serine/threonine kinase activity

but Val's example with extensions isn't - I'll do that next.

**Comment by ValWood** [comment]
Great start. We waited even for this part for a few years.

This is something where none of our users will notice the change, but it will improve the  data interpretation on individual pages - a lot, and increasingly over time.

**Comment by ValWood** [comment]
one thing, non redundant IEAs are now hidden by default....

**Comment by ValWood** [comment]
On this page
http://pombase2.aska.gen.nz/gene/SPBC16D10.10
"tRNA modification"  is hidden by default
but 
GO:0006382	
adenosine to inosine editing
is not a child of tRNA modification


This might be because you are considering redundancy from F-P links?
If a BP term is redundant because of links between an MF and a BP we should still display it.

**Comment by kimrutherford** [comment]
> one thing, non redundant IEAs are now hidden by default....

Can you give me an example?

**Comment by kimrutherford** [comment]
> but GO:0006382
> adenosine to inosine editing
> is not a child of tRNA modification 

Oh dear.  And in the MF section kinase activity is missing.

I'll fix that.

**Comment by ValWood** [comment]
I think it is just ignoring ISO and IEA, that would fix both issues

see,
http://pombase2.aska.gen.nz/gene/SPCC895.06
no BP by default

**Comment by ValWood** [comment]
hmm, thats not  the reason because
http://pombase2.aska.gen.nz/gene/SPAC23C4.08

GO:0003924	
GTPase activity
IDA

hidden here

**Comment by kimrutherford** [comment]
I seems very broken.  I've swapped the previous dataset back while I fix things.

**Comment by kimrutherford** [comment]
I hope I've fixed that problem.  It's likely that any other bugs will appear is cases with a complex hierarchy and complex extensions.  Let me know when you see problems.

**Comment by ValWood** [comment]
Seems better now....

**Comment by kimrutherford** [comment]
> only terms with no extension are removed

It now hides annotations where either:

 - the annotation has no extension and there is an annotation that uses a more specific term; the more specific term can have an extension
 
or:

 - the annotation has an extension and there is an annotation that uses a more specific term which has an identical extension

**Comment by ValWood** [comment]
so based on the above I expected 
protein kinase activity has substrate dsk1,srp1, srp2 to  hide by default for  dsk1

![dsk1](https://cloud.githubusercontent.com/assets/7359272/24301446/82baaec8-10a7-11e7-9732-2975ef6c4b79.jpg)

**Comment by kimrutherford** [comment]
> so based on the above I expected
> protein kinase activity has substrate dsk1,srp1, srp2 to hide by default for dsk1

Yep, it should be hidden.  I'll fix that.

**Comment by kimrutherford** [comment]
> so based on the above I expected
> protein kinase activity has substrate dsk1,srp1, srp2 to hide by default for dsk1

I think I've fixed that now, although the protein kinase activity annotations seem to be gone from dsk1.  Have you removed them manually?

Please let me know if you see weirdness in other places.

**Comment by kimrutherford** [comment]
> hide terms that (a) are is_a or part_of ancestors of other terms

I've realised that it's including other relations when looking for ancestors, not just is_a and part_of.  I'll fix that.

**Comment by ValWood** [comment]
oh yes I did sorry!
https://github.com/pombase/curation/issues/1344
will have a check at some others...

**Comment by kimrutherford** [comment]
I think this is OK now.  Let me know if you find any problems.

**Comment by Antonialock** [comment]
I had a look at a few genes and it looks good.

One q:
on Ste11 page, should row 1+3 of this extension be shown on the same line in compact view?

![screen shot 2017-03-27 at 09 25 25](https://cloud.githubusercontent.com/assets/12727506/24347441/3f1a46f8-12d0-11e7-88f6-333f91d38696.png)

**Comment by kimrutherford** [comment]
> on Ste11 page, should row 1+3 of this extension be shown on the same line in compact view?

Thanks Antonia.  Yep, that's a bug.  I'll fix it in the morning.

**Comment by kimrutherford** [comment]
> on Ste11 page, should row 1+3 of this extension be shown on the same line in compact view?

Val open another (short) issue about this bug (#228) so I'll close this.
