### ISSUE TITLE
show Boolean operators for combined queries

### ISSUE THREAD

**Issue by mah11** [pombase/website#450]
The query entries in the history really need to use Boolean operators (AND, OR, NOT) in the display for combinations. The descriptions with "union" and "intersect" are downright incomprehensible, as well as inconsistent with the rest of the internet's search engines.

As I've said on calls, I also want the Boolean operators show on the query-combining buttons; there I don't mind whether it's instead of or in addition to the union/intersection/subtraction language but I look for AND, NOT, and OR, so it slows me down not to see them.

**Comment by ValWood** [comment]
The problem is that we have (lot's) of evidence that many people misinterpret Boolean AND/NOT or OR..... Lots of biologists don't know the difference between logical AND and well, ordinary  "AND" unfortunately.... (or even AND and OR come to that), and  at least  the Union/intersect is unambiguous. 

But I guess as the visual clue is on the buttons, so  it doesn't make *that*  much difference so I'm happy for it to swap...although I think this way is clearer for the average user.

**Comment by mah11** [comment]
I still don't have a problem with the query-building buttons having both - it's the presence of AND (etc.) that I need, more than the absence of "intersection" (tho the latter doesn't communicate anything useful to me). I.e, I would find "OR (union)" and "AND (intersection" labels long-winded but basically OK.

I also don't have any first-hand observations of my own where people have problems understanding AND, NOT, and OR. Nor have I seen data from any studies.

The results really _really_ need to use AND/NOT/OR, though, because the brevity is essential to making them readable. And if we have dual-labeled buttons, people will learn what AND means. They can then use the info all over the rest of the web, which uses Boolean operators.

**Comment by kimrutherford** [comment]
I've made the buttons look a bit more buttony but now the AND, OR and NOT images look bad.  I'll work on that.

**Comment by kimrutherford** [comment]
> but now the AND, OR and NOT images look bad. I'll work on that.

They are slightly better now.

**Comment by ValWood** [comment]
I don't see them after shift reload?

**Comment by kimrutherford** [comment]
> I don't see them after shift reload?

It wasn't a big change.  I only mentioned it in the issue so I wouldn't forget to fix them..

**Comment by ValWood** [comment]
Label buttons
UNION/AND
INTERSECT/OR

Change labels in  history to Boolean

**Comment by kimrutherford** [comment]
This change will appear in the dev overnight and in the preview sometime during the morning.
