### ISSUE TITLE
Implement the forms in the "Submit" menu of PomBase v1

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#451]
Menu items in v1:

 - [ ] Submit gene names
 - [x] Curate a paper
 - [ ] HTP sequence-linked data
~~GO annotation data submission form~~
~~Batch modification data~~
~~Batch phenotype data~~
~~Qualitative gene expression data~~
~~Quantitative gene expression data~~

See also: #402

2017-10-30: edited to strike out forms we decided not to reinstate

**Comment by mah11** [comment]
This morning we realized that we actually only need two forms - gene name and HTP data (i.e. destined for browser tracks).

"Curate a paper" is just a link to Canto, and nobody uses the web forms for flat-file batch annotation submission - they all bleat at the helpdesk instead, or we approach them. Use links to file format docs and the helpdesk.

**Comment by ValWood** [comment]
and in fact these can be punted until after release. People can just mail the helpdesl.

**Comment by mah11** [comment]
I am also making the executive decision to move the file format documentation pages to the "documentation" department of the website (well, add them back there, since they were among the missing from the dump Kim got ...).

**Comment by mah11** [comment]
note to self: confirm what the link will be for the HTP data submission form; update documentation if it changes from submit-data/data-submission-form

**Comment by ValWood** [comment]
Should we add links to the description of the formats somewhere even before we get "submit" forms back?

Or do we have these somewhere already?

**Comment by mah11** [comment]
https://www.pombase.org/documentation and https://www.pombase.org/submit-data/bulk-annotation

**Comment by ValWood** [comment]
This seems to be just a case of checking of the links and the documentation match up.

**Comment by kimrutherford** [comment]
Do we ever want to have the submit forms again?
