### ISSUE TITLE
query result download: add headers; change "mRNA" to "protein coding"

### ISSUE THREAD

**Issue by mah11** [pombase/website#452]
1. In the downloadable details for query results, it would help to have column headers.

2. The column that I think must be feature type has "mRNA gene" for protein-coding genes. I think "protein coding" or "protein-coding gene" would be much better.
(sort of related to #394, I guess)

**Comment by kimrutherford** [comment]
> In the downloadable details for query results, it would help to have column headers.

Done.  You'll need to reload.

Please let me know if you'd like changes to the headers.

> I think "protein coding" or "protein-coding gene" would be much better.

I changed it to "protein coding".

**Comment by mah11** [comment]
That looks lovely; thanks!
