### ISSUE TITLE
change "Query builder" to "Advanced search"

### ISSUE THREAD

**Issue by mah11** [pombase/website#453]
Can we change the search tab/page title from "Query builder" to "Advanced search"?

- it will make for less text editing throughout the FAQs and other documentation;

- it's a more accurate description of the page, since it includes results, and will eventually also have result-customization stuff, as well as the query-building gubbins; and

- small thing, but it'll be more consistent with the plain box being called the "simple search".

**Comment by kimrutherford** [comment]
I've changed it, although I couldn't find many occurrences.  If I've missed any please let me know.

**Comment by ValWood** [comment]
I really dislike like the name "advanced search" there isn't  really anything  "advanced" about it.

Query builder doesn't  accurately describe what it does, but neither does "search".

I don't have any ideas though so we are probably stuck with this.

**Comment by kimrutherford** [comment]
> I really dislike like the name "advanced search" there isn't really anything "advanced" about it.

I'm neutral on the name but I think the search is quite advanced, or at least it will be soon.  :-)

**Comment by ValWood** [comment]
OK. I think its simple. but renaming things is a pain....
