### ISSUE TITLE
wild card at beginning of simple search string

### ISSUE THREAD

**Issue by mah11** [pombase/website#454]
This doesn't work in the simple search right now, but we know from past experience that people want it and use it. If it's easy, do it for the pombase2 release (if it's hard, remove the milestone).

I don't think there's anything in the advanced search that needs it.

**Comment by ValWood** [comment]
I spotted that last week, and then I noticed you can do name substrings, just miss the wild card, so probably it's a documentation issue. I was going to tell people they could do this when I let them know that they could now search orthologs...

**Comment by mah11** [comment]
OK, I tried when I got to the old FAQ ... I'll just update it to reflect the current behavior.

**Comment by ValWood** [comment]
I had a mental note to submit a ticket, then I realised it worked better when I cut and pasted an ID missing the front part by mistake!
