### ISSUE TITLE
"binds" relationship not shown for protein binding IPI

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#455]
on cyr1

  | IPI                   with                                  gpa2
-- | --

**Comment by Antonialock** [comment]
(paper has not been through canto yet, maybe that is the issue?)

**Comment by kimrutherford** [comment]
> (paper has not been through canto yet, maybe that is the issue?)

If it's not in an approved session it won't show up yet.

**Comment by ValWood** [comment]
I think Antonia means that it is  data in Artemis. This should show?
@Antonialock  can you confirm?

Actually did we ever implement the "binds" display yet? I can't remember but I thought we had.

**Comment by Antonialock** [comment]
yeah binds display is implemented. 
The annotation is showing (the binds extension is showing for other genes), 
this paper has not been through canto so I guess it is a legacy one from artemis.

**Comment by ValWood** [comment]
but "binds" should still display for data in Artemis?

**Comment by Antonialock** [comment]
which is why I opened a ticket :-)

**Comment by kimrutherford** [comment]
Could you explain this to me in smaller words?  I'm not following.

What data is in the contig files and where is it not displaying?

**Comment by Antonialock** [comment]
cyr1 gene page only shows "protein binding" no extension in collapsed view
![screen shot 2017-07-19 at 23 48 21](https://user-images.githubusercontent.com/12727506/28393074-d944c896-6cdc-11e7-8879-1b6e24403f8b.png)

full view:
![screen shot 2017-07-19 at 23 48 27](https://user-images.githubusercontent.com/12727506/28393082-e171cf78-6cdc-11e7-9f3b-11ff961870cc.png)

**Comment by Antonialock** [comment]
in contrast gpa2 gene page shows the binding extension in summary view
![screen shot 2017-07-19 at 23 50 17](https://user-images.githubusercontent.com/12727506/28393121-09e5cedc-6cdd-11e7-925d-6a5f9dc866f2.png)

**Comment by kimrutherford** [comment]
Thanks!  Sorry for being slow.  Got it now.  I forgot we change IPI+with to binds() extensions.

The code was relying on the order that annotation properties were stored in Chado.  Sometimes it was failing to get the evidence code before checking for "with".

It's fixed now.
