### ISSUE TITLE
PMIDs with publication pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#456]
in #32 we wanted to be able to search on PMID and be directed to a publication page. 
As a quick fix Kim said he could enable searching on a complete PMID for a publication that has been curated. If a paper had not been curated "page could not be found" would be displayed.

This ticket is for: 
- searching for partial PMIDs (maybe not needed if not straight-forward? more likely you would copy and paste these IDs...)
- making publication pages for papers that haven't been curated yet, but that have been identified as containing pombe specific data (https://curation.pombase.org/pombe/view/list/curatable_publications?model=track)
for those papers, perhaps a message could me displayed on the publication page "publication has not yet been through PomBase curation" or something (paper could still have biogrid annotation..).

**Comment by kimrutherford** [comment]
> making publication pages for papers that haven't been curated yet, but that have been identified as
> containing pombe specific data

I checked and all the publications in Canto make it into Chado so they all have a page in PomBase v2.

I'll see if I can do a quick fix to allow searching for pubmed IDs.

**Comment by kimrutherford** [comment]
> I'll see if I can do a quick fix to allow searching for pubmed IDs.

I've changed it so that that you can search for PMIDs and GO,FYPO etc. terms in the search box.  It's not obvious at the moment because if you type or paste in a PMID or term it will say "No matching genes".  But if you press return it will try to go to the right page.

**Comment by Antonialock** [comment]
can we allow PMIDs without the prefix PMID: or is that complicated?

**Comment by ValWood** [comment]
That will need to wait until later....until the full faceted search is implemented. This is a stop gap, but it has to be the entire ID.

**Comment by kimrutherford** [comment]
> That will need to wait until later....until the full faceted search is implemented. This is a stop gap, but it has to be the entire ID.

It was just a two line fix so the PMID: prefix is now optional.

**Comment by ValWood** [comment]
I thought you said it had to be complete strings/IDs for now, I must have misunderstood!

**Comment by kimrutherford** [comment]
> I thought you said it had to be complete strings/IDs for now, I must have misunderstood!

It's a bit of a cheat at the moment: if you put in a number the code assumes it's a pubmed ID, adds "PMID:" and hopes for the best.  :-)

**Comment by ValWood** [comment]
but won't that be a problem if you  put in the numeric part of a systematic ID (I guess this wouldn't happen very often)

**Comment by kimrutherford** [comment]
> but won't that be a problem if you put in the numeric part of a systematic ID

I was worried about that too.  I checked and there are no pubmed IDs in Chado that are also part of gene systematic ID or gene name.  So it's a hack but it probably OK.

**Comment by ValWood** [comment]
@kimrutherford - you are so on it! I can't quite believe what time you were working until this morning.  Our late is sometimes very late but it doesn't match yours....Anyway I hope you had a nice lie-in today...

**Comment by kimrutherford** [comment]
> I've changed it so that that you can search for PMIDs and GO,FYPO etc. terms in the search box.

Searching by UniProt ID was very easy to add so I've done that too now.

**Comment by ValWood** [comment]
useful ;)

**Comment by ValWood** [comment]
Closing this ,  next thing is implementation of full facetted search 
https://github.com/pombase/website/issues/32
