### ISSUE TITLE
searching for authors

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#457]
Following on from #456...

would it be useful to be able to see all publications/annotations associated with one* author? Difference from searching for [author] in PubMed is that we would only display pombe papers for that author. 

*as long as their name is unique..

**Comment by ValWood** [comment]
this will presumably be part of facetted search, or at least that would be a start.

I'll transfer this suggestion to the facetted search ticket, and it can spawn its own ticket  when we get there....

https://github.com/pombase/website/issues/32

**Comment by ValWood** [comment]
Actually the author pages are more  closely aligned with this ticket:
https://github.com/pombase/website/issues/332
