### ISSUE TITLE
when I search on fub2  in pombase  I only get 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#459]
fub2 SPBP4G3.03

but I should also get
uba2 | Characterisation status | biological role inferred
Product | SUMO activating enzyme E1-type Uba2 (predicted) | Feature type | protein coding
Systematic ID | SPBC16H5.03c

in canto, correctly
There is more than one gene matching gene, try a systematic ID instead: SPBP4G3.03, SPBC16H5.03c

**Comment by mah11** [comment]
is likely because fub2 is an obsolete name, and the gene pages don't show those (#301)

**Comment by ValWood** [comment]
OK I will change that to synonym because it is in the paper I am curating...
