### ISSUE TITLE
ontology browser links for term pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#460]
In legacy PomBase, ontology term pages have links to available browsers where people can see the term in context. We should add those links to shiny new PomBase term pages.

GO: AmiGO, QuickGO and BioPortal
FYPO: BioPortal
PSI-MOD: BioPortal
SO: MISO

example links:
QuickGO http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005829
AmiGO http://amigo.geneontology.org/amigo/term/GO:0005829
GO in BioPortal bioportal.bioontology.org/ontologies/GO/?p=terms&conceptid=GO:0005829#details
FYPO in BioPortal http://bioportal.bioontology.org/ontologies/FYPO?p=classes&conceptid=FYPO%3A0002019#details
MOD in BioPortal http://bioportal.bioontology.org/ontologies/PSIMOD?p=classes&conceptid=MOD%3A00046#detail
MISO http://www.sequenceontology.org/browser/current_svn/term/SO:0001796

adding to the release milestone because it's in old PomBase, and looks fairly straightforward

**Comment by kimrutherford** [comment]
Thanks for the example links.  That's useful because only AmiGO is in the GO.xrf_abbs file.

**Comment by kimrutherford** [comment]
I've added those links.  Let me know if you spot any problems.

Also, please let me know how you'd like the list of link formatted.  Currently it just says:

     External links: GO QuickGO BioPortal

Do we want small icons next to the DB names like we do for esyN here?:
  http://preview.pombase.org/term_genes/GO%3A0006914

**Comment by mah11** [comment]
Those are working nicely, so thanks.

I think the AmiGO link should have the full "AmiGO" name as the hyperlinked text.

Maybe a bit of punctuation to separate the links for GO terms would help make it clearer that there are three different ones - commas or pipes would be fine.

Logos would be nifty but not essential (and I don't have one handy for MISO or BioPortal).

**Comment by kimrutherford** [comment]
> I think the AmiGO link should have the full "AmiGO" name as the hyperlinked text.

Thanks.  Fixed.  The "GO" leaked through from the GO.xrf_abbs where there the AmiGO entry has the abbreviation "GO".

> commas or pipes would be fine.

Good idea.  I've gone for:

    External links: AmiGO | QuickGO | BioPortal

**Comment by kimrutherford** [comment]
Shall we close this issue?

**Comment by mah11** [comment]
sure :)
