### ISSUE TITLE
Add a function to delete queries from the history

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#462]

**Comment by ValWood** [comment]
Has anybody any suggestions how this should work?
I can't think of anything except the "intermediate step" that we have in P1....

**Comment by kimrutherford** [comment]
> I can't think of anything except the "intermediate step" that we have in P1....

I tried it and I didn't see an intermediate step.

**Comment by ValWood** [comment]
it looks like this:

![orientation](https://user-images.githubusercontent.com/7359272/28610033-d0e911dc-71de-11e7-8d5e-0fcbf515f381.jpg)

**Comment by kimrutherford** [comment]
Ah, wrong issue: #463

**Comment by ValWood** [comment]
Oh yes sorry entire thread is "wrong issue", will delete

**Comment by kimrutherford** [comment]
I've added a delete button to the query history.  I've had to much about with how the history is implemented so that delete will work.  Please let me know if you spot any weirdness.

**Comment by ValWood** [comment]
works fine for me!
