### ISSUE TITLE
Add the ability to switch the order in a NOT/substract query

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#463]

**Comment by ValWood** [comment]
currently it is done like this:

![orientation](https://user-images.githubusercontent.com/7359272/28610374-07775ca8-71e0-11e7-9531-53f1330ac158.jpg)

**Comment by ValWood** [comment]
the only vague idea I had was if you could "juggle" the order of the queries in the list somehow, then make it so the query below was always subtracted. That sounds like a complicated thing to do though....

**Comment by kimrutherford** [comment]
We could make the order you select queries significant.

So if we had:

    .   GO_ID(...
    .   FYPO_ID(...
    .   OTHER(...

and then you click 3rd line then top line, it could select them and add numbers to show the order.

So after one click:

    .   GO_ID(...
    .   FYPO_ID(...
    x 1 OTHER(...

Then second click:

    x 2 GO_ID(...
    .   FYPO_ID(...
    x 1 OTHER(...

Then order of the operation would be more obvious, maybe.  It's not going to be the most elegant interface though.

(Sorry for the dodgy text diagrams)

**Comment by ValWood** [comment]
not sure... any other ideas /thought anyone?

**Comment by mah11** [comment]
I think it will help generally to number the queries in the history list, and show the numbers all the time (not just after you click something - that would be unexpected and off-putting).

The legacy PomBase way is clunky and makes me suspect it's a kludge, a hack, or the bastard offspring of a kludge and a hack. There's no need for shiny new PomBase to copy it.

Check out the PubMed Advanced Search - its builder lets you specify one or more terms, then does two clever things: 1) it lets you either perform the search or put the query parameter(s) straight into the history; 2) each entry in the history has an "add to builder" link that does exactly what it says. You control the (1 minus 2) vs. (2 minus 1) by the order you add items from the history to the search you're currently building.

Oh, and "add to history" also shows the number of matches, linked to the result list. It's actually pretty cool.

https://www.ncbi.nlm.nih.gov/pubmed/advanced

**Comment by ValWood** [comment]
That's quite nice.

**Comment by ValWood** [comment]
I was just having another look. Why is numbering the queries useful? Isn't labelling better (numbers will end up a bit random as you delete queries from your history).
Or maybe the numbers field could be a placeholder for a "label"?
https://github.com/pombase/website/issues/481

**Comment by ValWood** [comment]
Just chatted with Kim.

Will prototype
i) Having it more like NCBI but instead of needing to choose "search" or "history"
search preview (first 10 rows), will appear at top right.
Click to see full results.

ii) results history will be tabulated to make it more readable, and this will allow to go full page width
iii) Add a column for the results number 

Subtraction will be a pop-up to select query order.

**Comment by ValWood** [comment]
We can go live without this, and implement soon after.

 There is a "workaround" that we could document in the meantime.

To perform a subtraction query, click on the query you would like to subtract *from* to position it at the top of your query history. Currently the subtract feature will  subtract the bottom list from the top list.

Or similar.

**Comment by kimrutherford** [comment]
> Subtraction will be a pop-up to select query order.

I've had a go at this as a Friday afternoon job.  I'm only experimenting locally at the moment so I haven't changed the main site.  Let's chat about it on Thursday.

You can test it here until 1pm-ish: https://desktop.kmr.nz/

![not-direction-1](https://user-images.githubusercontent.com/90474/114968666-ec4d3f80-9eca-11eb-987d-84c0b2de646a.png)

**Comment by ValWood** [comment]
On the list.

**Comment by ValWood** [comment]
could not test, get an error.

**Comment by kimrutherford** [comment]
> could not test, get an error.

It's back in action now.

**Comment by ValWood** [comment]
That works very nicely.

**Comment by mah11** [comment]
Agreed - nice. Want me to get some updated documentation going now?

**Comment by kimrutherford** [comment]
Thanks.  There's no rush as the text and formatting in the dialog needs to be work-shopped.  :-)

**Comment by mah11** [comment]
OK. It probably makes sense to wait until that work is done so I can get accurate screenshots.

**Comment by ValWood** [comment]
1. header: -> choose a query direction
2. remove the word 'query' above the querry
3. remove indentation

**Comment by kimrutherford** [comment]
How's this?:

![not-direction-2](https://user-images.githubusercontent.com/90474/117221438-5ff4c380-ae5d-11eb-8924-83073674cb7c.png)

**Comment by ValWood** [comment]
I think that is clear.

**Comment by mah11** [comment]
Looks good. I'll do documentation next week (i.e. after GOC mtg).

**Comment by kimrutherford** [comment]
Thanks.  I'll release the change on Monday.

**Comment by kimrutherford** [comment]
>  I'll release the change on Monday.

Done!  (after a quick fix for bug that only happened on the server)

**Comment by mah11** [comment]
I finally got the documentation updated.

**Comment by kimrutherford** [comment]
Thanks Midori.  Let's open new issues if we need any changes.
