### ISSUE TITLE
changes to top matter of term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#464]
Make the "top matter" on
http://pombase2.bioinformatics.nz/term/GO%3A0006914
also appear on
http://pombase2.bioinformatics.nz/term_genes/GO%3A0006914

Needs some rearranging

Put 
term
def
parents
external links?

on the left

Put "actions" on the right (or wherever you think best)

Re Download details,
I think this is temporary.
Its  just offering a little more than the basic  list (same as the current QB download)
When its done, I think this link should go to the same "download options" that the advanced search provides. This would be user configureable and could be GAF,  sequence etc.
Different options might be available  (or more prominent) depending where you arrive from?

Link for send to query
"Use these genes in query"

Kim why don't you  you have a play and we can see how it looks (particularly representing the top matter  and links on both pages). Or wait until Thursday and  we can decide more...

If anyone has further ideas, or I missed anything  please add here.

**Comment by mah11** [comment]
> Re Download details,
> I think this is temporary.
> It's just offering a little more than the basic list (same as the current QB download)
> When it's done, I think this link should go to the same "download options" that the advanced search provides. This would be user configureable and could be GAF, sequence etc.

Hmm. Perhaps I could be brought round, but my initial gut feeling is that we should keep it simple on term pages, and just offer two options - systematic IDs and "what you see here". Keep all the more complicated options in the query results department, and let the "use these genes in a query" handle sending people over to where they can configure what to download.

It just seems like it'd be cluttering and overkill to have all the download-configuration tooling taking up space on the term pages.

> Different options might be available (or more prominent) depending where you arrive from?

That sounds like it has considerable potential to confuse people (and annoy me).

**Comment by kimrutherford** [comment]
I'm moved things around a bit but I'm not finished yet.

My changes so far are in the preview and in pombase2.bioinformatics.nz

**Comment by kimrutherford** [comment]
Val noticed that the definition, parents and external links were missing from the phenotype term gene list pages like:
  http://pombase2.bioinformatics.nz/term_single_allele_genotype_genes/FYPO%3A0002998
  http://pombase2.bioinformatics.nz/term_genotypes/FYPO%3A0002998

I've fixed that now.

**Comment by ValWood** [comment]
I don't think this is urgent for public release, can discuss Thursday...

**Comment by ValWood** [comment]
I'm not sure what we still need to do here? Open new tickets if we still want to change things.
