### ISSUE TITLE
refine front page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#466]
We can begin to refine the front page a little now we have the menus.

I suggest we just begin to remove things which are "surplus"

1. remove "New publication pages" as the "community curation feed provides examples

2. Remove Docs links to "about" "FAQ" and anything else now housed under a menu

So we should discuss what we do want on the page
images?
news feed
community curation feed
Highlighted area?

no hurry for this one...can do just before we go live

**Comment by mah11** [comment]
superseded by #513
