### ISSUE TITLE
hiding redundant annotations

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#469]
pa1 is annotated to:
protein kinase activity has_substrate ste11
and
protein/serine threonine kinase activity directly_negatively_regulates ste11

I would expect the former annotation to be hidden?

**Comment by kimrutherford** [comment]
Currently annotations are only hidden if there is a more specific annotation with the same extension.

**Comment by ValWood** [comment]
yes, this will be dealt with later.
It's related to
https://github.com/pombase/website/issues/277

I'm trying to find the correct relation to use. Then we'll figure it out....
