### ISSUE TITLE
dealing with HTP papers in literature section

### ISSUE THREAD

**Issue by mah11** [pombase/website#47]
Michal has requested a feature to hide large scale papers from the references/literature section. We haven't wanted to do exactly that because there's not a clean distinction between "small scale" and "large scale" or high vs. low throughput (the extremes are obvious but there are plenty of papers in the grey area in between).

Instead, add a column to the literature list\* for a gene count, and make the list sortable on it.

Can be had using the view at
https://github.com/pombase/pombase-legacy/blob/master/script/make-db#L115

With that view in place, you can count the genes per publication with:
select count(*), pmid from pombase_annotated_gene_features_per_publication group by pmid;

*Curators decide - visible by default?

**Comment by ValWood** [comment]
Done! How easy is this....done without even requiring a ticket....
