### ISSUE TITLE
pap1 not top hit in simple search

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#470]
see screenshot

![screen shot 2017-08-03 at 15 41 57](https://user-images.githubusercontent.com/12727506/28927419-62e5adbe-7862-11e7-86df-08999eff028f.png)

**Comment by ValWood** [comment]
yep, its getting "drowned out" by the SPAP1* hits....

**Comment by ValWood** [comment]
sligtly similar rpn1 (mts4 synonym, probalby should be primary)

is below
rpn10,11 12 etc

I think the general rule should be that exact match to gene or synonym is higher than a substring match?

**Comment by kimrutherford** [comment]
> I think the general rule should be that exact match to gene or synonym is higher than a substring match?

That makes sense.  I'll do that.

**Comment by kimrutherford** [comment]
> I think the general rule should be that exact match to gene or synonym is higher than a substring match?

What about an exact match to an ortholog like human "RPN1".

**Comment by ValWood** [comment]
I think that should come above partial matches.

If I typed rpn1 i'd expect rpn1 gene or otholog to be above rpn11
(and most of the problematic lust seem to be the systematic ids where people can just type an additional letter....

**Comment by ValWood** [comment]
yep,   
exact name>synonym>ortholog,  
partial match name>synonym>ortholog,

**Comment by kimrutherford** [comment]
I think this is all fixed now.
