### ISSUE TITLE
ortholog section reference should go to resource

### ISSUE THREAD

**Issue by ValWood** [pombase/website#474]
Is this in another ticket?

Anyway , in this example this link should go to Panther

![link should go to panther](https://user-images.githubusercontent.com/7359272/28997636-4f48f9c2-7a11-11e7-89d4-c380e605f64e.jpg)

but incase there is more than one S. c ortholog there should be a "count" and that would link to a page like this.
In fact this count  would link to 3 genes

http://preview.pombase.org/gene/SPBPB2B2.18
http://preview.pombase.org/gene/SPAC977.18
http://preview.pombase.org/gene/SPAC1952.04c
which all have  YBL029C-A as ortholog

**Comment by kimrutherford** [comment]
That should be fixed now.  The problem was that the GO.xrf_abbs has "PANTHER" in capitals but the reference was "Panther".  I've changed the code to be case insensitive.  You'll need to reload.

**Comment by ValWood** [comment]
Ah yes. I have always written Panther, but it should be PANTHER....
