### ISSUE TITLE
show pombase curated domain data in full

### ISSUE THREAD

**Issue by ValWood** [pombase/website#475]
an example
http://pombase2.aska.gen.nz/gene/SPAC750.04c

I don't think it makes sense to have the details/summary option here, better to treat them like protein families and show by default with the count.

![just show](https://user-images.githubusercontent.com/7359272/28997670-21364f2a-7a12-11e7-9a13-0eb64ee40ffe.jpg)

**Comment by kimrutherford** [comment]
Should I get rid of the Evidence and Reference columns?

**Comment by kimrutherford** [comment]
I've changed it to show only the detailed view for that table.

**Comment by ValWood** [comment]
yep....
I can get rid of some of these once I know they are stably fully covered by interpro, but it isn't priority.....

**Comment by kimrutherford** [comment]
I've removed the Evidence and Reference columns.

**Comment by kimrutherford** [comment]
I'll close this because I think it's done.
