### ISSUE TITLE
Links to iPTMnet

### ISSUE THREAD

**Issue by ValWood** [pombase/website#477]
Add x-refs from gene pages to to iPTMnet
http://annotation.dbi.udel.edu/iptmnet/entry/Q9P6L9/#asSub

(I forgot where I need to go to do this)

Maybe we should wait as Ceci says
Here is a link to our soon to be public latest release (dev site) http://annotation.dbi.udel.edu/iptmnet/

When this goes live we should announce the usefulness, particularly the nice feature which allows you to access the multiple alignment to see conserved modification sites.

**Comment by ValWood** [comment]
@mah11  will assign this to you. Can you also remind me how to do it for future...

**Comment by kimrutherford** [comment]
It's more complicated than it should be at the moment.  There are two places to change.

The first is in this file:
  https://github.com/pombase/website/blob/master/frontend/etc/build_app.sh

The "abbreviation" from the GO.xrf_abbs needs to be added to this line:

    ABBREVS="AGI_LocusCode CDD DDJB EC ECOGENE EMBL  ...

Then the rest of the configuration need to be added to the "external_gene_references" section in this file in SVN:
  pombe-embl/website/pombase_v2_config.json

I thought some of this was in https://github.com/pombase/website/wiki/Config-file but it isn't.  I'll add it.

**Comment by mah11** [comment]
I've done the file changes at our end, but iPMTnet isn't in GO.xrf_abbs yet. I guess the links won't work until the pull request I just did (https://github.com/geneontology/go-site/pull/422) goes through (note: it uses human CDK1 as example). Roll back if it breaks anything else!

**Comment by kimrutherford** [comment]
Those links are working now.

**Comment by kimrutherford** [comment]
> I thought some of this was in https://github.com/pombase/website/wiki/Config-file but it isn't.  I'll add it.

I've done that now:
  https://github.com/pombase/website/wiki/Configuration
