### ISSUE TITLE
protein images

### ISSUE THREAD

**Issue by ValWood** [pombase/website#479]
some of the protein images look like this:
![ensembl images](https://user-images.githubusercontent.com/7359272/29063603-516ff4ee-7c1e-11e7-8ba6-3736056939ae.jpg)

but when you click through to ensembl they are correctly labelled?

(this is cut7)

**Comment by ValWood** [comment]
http://fungi.ensembl.org/Schizosaccharomyces_pombe/Transcript/ProteinSummary?g=SPAC25G10.07c;r=I:4306511-4310340;t=SPAC25G10.07c.1

**Comment by kimrutherford** [comment]
Those images are from PomBase v1:
  http://www.pombase.org/spombe/result/SPAC25G10.07c#translation

I don't know of a quick fix.

**Comment by ValWood** [comment]
OK it isn't a big deal..... but we can't get them from 
http://fungi.ensembl.org/Schizosaccharomyces_pombe/Transcript/ProteinSummary instead?

It doesn't matter really as the info is on the page

**Comment by kimrutherford** [comment]
> but we can't get them from

It's tricky because that's not one image - each track is a separate image with a URL like:
  http://fungi.ensembl.org/img-tmp/temporary/2017_08_08/LGEYGVCcNbefKCAObEAAAKGB.png

It would be difficult to get a single image for each gene without help from Ensembl.

**Comment by ValWood** [comment]
ok, lets stick with what we have.
