### ISSUE TITLE
mapping between genome assembly versions

### ISSUE THREAD

**Issue by mah11** [pombase/website#48]
Kim: figure out whether to use/recommend LiftOver, Ensembl's thingy, or something else.

Curators (read: Midori): add a FAQ (oh my I hope there'll be existing documentation to link to) for whatever we use

**Comment by ValWood** [comment]
I'll keep this in live version for now.

Mainly because we need to discuss a potential project/publication.
We can all chat about this on Monday.

**Comment by ValWood** [comment]
Kim found this
  http://crossmap.sourceforge.net/

**Comment by ValWood** [comment]
Although we need to do this it won't be until the sequence is updated and  that won't be for ages (need a feature update first, UTRs RNAs etc). I still think this is a couple of years off realisticly

**Comment by ValWood** [comment]
Future doc
