### ISSUE TITLE
combining queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#480]
cant combine queries on http://pombase2.bioinformatics.nz/

**Comment by ValWood** [comment]
or on preview...I think it  only doesn't work when you have an uploaded list.

well so,e queries work, but I haven't figured what. A list never works.

**Comment by kimrutherford** [comment]
> cant combine queries

> or on preview...I think it only doesn't work when you have an uploaded list

I had a try on pombase2 and I was able to combine queries even with gene list.  I did notice that queries with gene lists weren't being saved to the history properly.  I've fixed that in pombase2.bioinformatics.nz.  Maybe that was the problem?  Could you shift-reload and try again?

**Comment by ValWood** [comment]
It worked fine for me, I reloaded, did some new lists and combined fine.
I went away and uploaded a new list later. Then I could not combine.
But, after reloading  page I could. So I need to know that I need to "refresh" if I go away and return, I think?

**Comment by kimrutherford** [comment]
> But, after reloading page I could. So I need to know that I need to "refresh" if I go away and return,
> I think?

Very strange.  I don't know what's going on.

**Comment by ValWood** [comment]
I'll document  the order properly next time. all I got was a scennshot.

![lists](https://user-images.githubusercontent.com/7359272/29114134-35517ce2-7ceb-11e7-91d4-b3017fd7e754.jpg)

**Comment by ValWood** [comment]
I think this occured after I had deleted one list. Will try to replicate...

**Comment by ValWood** [comment]
I think it happens if you select, and then deselet check boxes. I jut went back to the query builder. it orked first time. I got the box xolour change but I didn't run the query. Then I deselected and reselected different boxes. This time it didn't work....

**Comment by ValWood** [comment]
It's not that, because I did it again and it worked...

**Comment by ValWood** [comment]
Now its working like a dream....

**Comment by ValWood** [comment]
closing, will reopen if it happens again....
