### ISSUE TITLE
Allow queries to be named

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#481]
How should this work?  Do we want an edit button or link beside each history entry?  Or should we just be able to name the "current" query, ie the one we are displaying results for.

Does this need to be done for the first public release?

**Comment by ValWood** [comment]
Does not need to be done for public release.
Will be nice addition later.

**Comment by ValWood** [comment]
An edit button to the left or right.
Replace the query with the user defined query name
Allow the query details to be accessed

**Comment by kimrutherford** [comment]
I have a prototype of this feature running on http://desktop.kmr.nz:4242/query
(until 1pm or so)

It's still buggy so I won't be deploying this to the main site today.

**Comment by ValWood** [comment]
Oh nice!

**Comment by mah11** [comment]
It's working nicely for me -- cool!

**Comment by kimrutherford** [comment]
> It's still buggy so I won't be deploying this to the main site today.

I've fixed the bugs I've found.  I haven't fixed the bugs I haven't found.  :-)

I've changed the query system so that whenever possible, all queries get an automatic name which the use can then edit.  For example if you use the "Select subset" button on a results page you might get a query name like "153 genes from: hematologic disease (MONDO:0005570)".  Or if you upload a gene list you get a query name like: "uploaded gene list of 27 genes".  If it's a very short list it looks like: "uploaded gene list: cdc42 apl5 gwt1 SPAC14C4.07 atm1"

I've taken a guess at what the names should be.  It's easy to fix if any don't make sense.

These changes are still only on my desktop (unavailable 1pm-9pm -ish UK time): http://desktop.kmr.nz:4242/query

My plan is to release the change to the dev server one morning this week when one or both of you have a little time to do some testing.  The thing that's most likely to break is your existing history.
Val, can I do a 5 minute Skype/Zoom with you sometime to extract the query history from your browser for testing?  If requires using the Firefox developer tools and it's easier to talk you through it.  Once we have your query history in a file we can import it into the development version and test it's OK.

I've also implemented import/export of the query history list.  That feature is hot off the press so I haven't tested it well and it's also only available on my desktop version.  I've just noticed that the order is reversed if you export then import.  I'll fix that tomorrow.

![import-export-1](https://user-images.githubusercontent.com/90474/83966131-740e0900-a90c-11ea-8203-8ddffdc009c1.png)

**Comment by ValWood** [comment]
yes sure, we can do Monday or Tues evening, whichever suits you

**Comment by kimrutherford** [comment]
> I've also implemented import/export of the query history list. That feature is hot off the press
> so I haven't tested it well and it's also only available on my desktop version.  I've just
> noticed that the order is reversed if you export then import. I'll fix that tomorrow.

I've fixed the reversed ordering.  It all works for me but I'd appreciate if one of you could give import/export a test on my desktop: http://desktop.kmr.nz:4242/query

I've done more testing of query naming/editing and fixed a few little bugs.  Seems OK to me now.  Please let me know if you don't agree.  :-)

**Comment by kimrutherford** [comment]
The query naming and history import/export functions are now live on http://dev.pombase.kmr.nz/

Let me know if you see anything that needs fixing.

**Comment by ValWood** [comment]
Looks good to me....

**Comment by kimrutherford** [comment]
Thanks for checking. Could you try uploading your query history?

**Comment by mah11** [comment]
both export and import are working for me

**Comment by mah11** [comment]
pombelist email, news item, and documentation update done for query naming

**Comment by kimrutherford** [comment]
> pombelist email, news item, and documentation update done for query naming

Thanks for the quick work!

I'll put something on Twitter later once the UK is awake.

**Comment by kimrutherford** [comment]
> I'll put something on Twitter later once the UK is awake.

I did that on Friday.
