### ISSUE TITLE
query builder results

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#484]
could we include the product description in the downloaded results?

**Comment by kimrutherford** [comment]
Good timing!  I've just finished implementing a prototype that lets you pick the columns you'd like in the output and I've included the product in the options.  There's now just a single Download button on the gene list that pops up a dialog, eg.
  http://pombase2.bioinformatics.nz/term_genes/GO:0071554

It's likely to have bugs so I haven't released it to the preview yet.  The formatting and text in the dialog need work too.

**Comment by Antonialock** [comment]
Super! To start with "product" should change to "product description" :-)

**Comment by kimrutherford** [comment]
> To start with "product" should change to "product description" :-)

Fixed!  If you shift-reload.

**Comment by kimrutherford** [comment]
I'll close this but #21 is still in progress.
