### ISSUE TITLE
synonyms on ncRNAs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#487]
/systematic_id="SPSNORNA.20" has synonym  SPNCRNA.906 but this is not searchable

/systematic_id="SPNCRNA.82" has   /synonym="SPNCRNA.727"

SPSNORNA.07    has   /synonym=  SPNCRNA.723

but these are not findable (queried by Jurg)

**Comment by kimrutherford** [comment]
There was a typo: /synonymn=SPNCRNA.906

The other two synonyms work OK for me.

I've fixed that in the contig file and I've made an issue about this:
  pombase/pombase-chado#642

The loader does make a note of qualifiers that it doesn't know how to deal with.  I'll make sure that goes into a log file.

**Comment by kimrutherford** [comment]
>  SPNCRNA.906 but this is not searchable

It's in the preview now.
