### ISSUE TITLE
some external references have disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/website#488]
http://pombase2.bioinformatics.nz/gene/SPAC1952.17c

**Comment by mah11** [comment]
probably due to changes for #477 - the iPMTnet entry has only reached GO.xrf_abbs today

reopen if it doesn't fix itself in a day or two (or if Kim has a clever way of making a missing entry not break the rest of them)

**Comment by kimrutherford** [comment]
> probably due to changes for #477 

Yep!

I've fixed the code so it doesn't bail out if the config is missing from GO.xrf_abbs so this shouldn't happen again.
