### ISSUE TITLE
summary of discussion for query interface changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#489]
I'm not sure which of this is already in tickets, so 

1) make the history a "table"  which has full page width (to separate queries)
2) Add a column for results number(items found) clickable to go to resuls
3)  This link (2) will take you to a search results page with a "back button"
4) Do not show results straight away  (although there could be an other button which takes you straight to the search results) [Add to history] [ View results]?

Solicit feedback. If users want to see results immediately, add a little "results preview" window.

Later
Make the query builder more like the PubMed in that you  select queries from the history (or 2 new queries) and combine BUT if we do this we should constrain to "pairwise" querying so that people don't create nonsense querying.
(advantage of this is that the operater is selected in between the 2 query lists. rather than generating 2 lists and then combining).

Ideally before implementing this we would ask  users  @Antonialock  (Jurg's lab) , to compare the PUbMed and PomBAse QB  and say which they find most intuitive).

Did i miss anything?

**Comment by kimrutherford** [comment]
If results aren't displayed by default, where should the "Use these genes in query..." link here go to:
  http://preview.pombase.org/term_genes/GO:0006915

Should it put the genes query in the history and take you to the query builder front page?  Or should we show the results but change the link text?

**Comment by kimrutherford** [comment]
I've made some to http://pombase2.bioinformatics.nz/query for testing:

1. The history is now a full width table and I've added a "counts" column

2. When you make a query it now doesn't show you the results, instead it puts the query in the history

3. You can click on the result count in the history to get to the results

4. The results are now on a different page that has a back button

**Comment by ValWood** [comment]
It looks much nicer.
I don't know if I miss seeing the results straight away or not.
So  we keep it like this for a while and ask users.

We could go stright to the result with a back button, which is incidentally what happens when you combine 2 queries from the history)

@Antonialock ?

**Comment by ValWood** [comment]
>If results aren't displayed by default,

I think for now put it in the history.

**Comment by kimrutherford** [comment]
> which is incidentally what happens when you combine 2 queries from the history

Whoops.  That was an accident.

**Comment by kimrutherford** [comment]
> I think for now put it in the history.

OK, I'll make that change.

**Comment by ValWood** [comment]
> Whoops. That was an accident.

I quite liked it. I do like seeing the list immediately when I run the query. I just don't know if  I *need* to....

**Comment by kimrutherford** [comment]
> I quite liked it. I do like seeing the list immediately when I run the query. I just don't know if I need to....

OK, I'll leave it for now.

**Comment by kimrutherford** [comment]
> Should it put the genes query in the history and take you to the query builder front page?

Done, if you reload.

**Comment by ValWood** [comment]
I think it will help us to decide which behaviour is best....
straigt to l results of straight to history...

**Comment by Antonialock** [comment]
Hmm, personally I prefer to NOT see the results straight away so that I can keep combining queries until I have the list that I want.

Gut feeling though is that most users would prefer to see the results straight away....it might also be reassuring to see them?

I think combining queries should behave the same way as running a query.

**Comment by ValWood** [comment]
OK, decided to make consistent.

**Comment by kimrutherford** [comment]
> OK, decided to make consistent.

Should we consistently see the results straight away or go to the history straight away?

**Comment by Antonialock** [comment]
I think we said to go to history straight away?

**Comment by ValWood** [comment]
yep, I don't think it will confuse anyone, but we will solicit feedback early on.

**Comment by kimrutherford** [comment]
> I think we said to go to history straight away?

Thanks.  If you reload the preview, it now only shows the results if you click on the count.  Everything else just adds to the history.

**Comment by ValWood** [comment]
Closing this. I am not really missing seeing the results immediately.

I'm happy to revisit this, but we can close for now and open a new ticket  for changes based on user feedback.
