### ISSUE TITLE
transposon LTR insertion data

### ISSUE THREAD

**Issue by mah11** [pombase/website#49]

**Comment by ValWood** [comment]
which dataset was this? Henry Levine?

**Comment by mah11** [comment]
Huh. I don't remember why no content got copied into this ticket, but I think it's the GitHub successor to Jira ticket PB-2329, which went with a helpdesk exchange with ID 479295 in the old RT at Sanger.

Briefly, Kurt Runge's lab constructed a library of barcoded Hermes transposon insertion mutants and intended to submit a BED file of insertion site and barcode data. I gather that after much email back & forth we haven't actually got the data yet.

The full dataset may not be published yet, although PMID:29018935 alludes to the work. I think we could either ping them or wait and see if they ask about including it without us prompting.

in case you still have access, links:
https://www.ebi.ac.uk/panda/jira/browse/PB-2329
https://rt.sanger.ac.uk/Ticket/Display.html?id=479295

**Comment by ValWood** [comment]
Ah I remember now. Let's close this one. They will let us know and we have lots to do in the meantime!
