### ISSUE TITLE
display tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/website#490]
Before and after

![before](https://user-images.githubusercontent.com/7359272/29411407-9a0a651a-834c-11e7-8bf2-769892ce468e.jpg)

;_)

after

![after](https://user-images.githubusercontent.com/7359272/29411412-9f0e13e0-834c-11e7-95ba-ff5734df8d6d.jpg)

**Comment by ValWood** [comment]
I think I prefer it.

Is it possible to make the within box grey lines thinner and paler?
That might help?

I think the labels might work if they were a subtle colour too....

thoughts?

**Comment by kimrutherford** [comment]
I've made those changes in the preview to see how they look live.

**Comment by mah11** [comment]
looks like we're done wit this one (but reopen if not)
