### ISSUE TITLE
query builder labelling

### ISSUE THREAD

**Issue by ValWood** [pombase/website#491]
Instead of

![history](https://user-images.githubusercontent.com/7359272/29489263-827c8134-8514-11e7-94b5-b96b5403da93.jpg)

It might be better to label the History Table as
"Query History"

And  where it currently says "History" above the icons 

"Combine queries from the history"

?

**Comment by Antonialock** [comment]
Query history - fine
and "Combine queries"

("..from the history" seems a bit redundant)

**Comment by ValWood** [comment]
This is only a small text change.
Do we want to implement?

Query history 
and 
"Combine queries"

**Comment by ValWood** [comment]
this looks quick, small text change

**Comment by kimrutherford** [comment]
I've made those changes.  They'll be in the preview by mid morning.
