### ISSUE TITLE
Add a way to export and import queries

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#492]
The queries are passed to the server as JSON so it should be easy to export and import that format.

It will help with #416.

**Comment by ValWood** [comment]
Is this done?

**Comment by kimrutherford** [comment]
> Is this done?

We can export, but it's quite hidden functionality.  There's no way to import.

**Comment by ValWood** [comment]
Is this done now?

**Comment by kimrutherford** [comment]
There's no change since this comment:

> We can export, but it's quite hidden functionality. There's no way to import.

I don't think importing is that important now that the result URLs can be bookmarked and shared.

**Comment by ValWood** [comment]
That's what I wondered. OK ;)
