### ISSUE TITLE
display SO protein feature annotations

### ISSUE THREAD

**Issue by mah11** [pombase/website#494]
Some genes have SO annotations for protein sequence features, e.g. NLS or KEN box. The protein feature search finds them by name or SO ID, but they don't show up anywhere on gene pages.

In legacy PomBase they're listed in the Protein features section, and we could do the same in shiny new PB2 (examples - mcm2, rad54).

Added to the v2 release milestone because they're available in old-PB, but actually not critical.

**Comment by mah11** [comment]
note: documentation update needs this, so it'll appear in updated screenshot

**Comment by kimrutherford** [comment]
I've add a SO features table in the Protein features section.

**Comment by ValWood** [comment]
nice http://preview.pombase.org/gene/SPAC890.02c

**Comment by kimrutherford** [comment]
Instead of "Protein sequence features" should it say something like "Curated protein sequence features" to distinguish it from the InterPro feature above?

**Comment by ValWood** [comment]
Let's discuss on Thursday. I'm likely to make it worse on my own!
A domain is a "sequence feature" but it's a different type of feature to a "SO feature", but it's difficult to convey the difference to users.....

**Comment by kimrutherford** [comment]
OK, I've labelled with "discuss" and I'll reopen.

**Comment by mah11** [comment]
I don't have a problem with the current labels, since we use "Protein families and domains" for the InterPro stuff. We don't need to push the angle that domains are a type of sequence feature.

And I'm only influenced a little bit by the fact that if the labels don't change, I won't have to redo the documentation page and its screenshot ;)

**Comment by ValWood** [comment]
OK  Kim, just rejig so protein families is above protein features...

**Comment by kimrutherford** [comment]
> OK Kim, just rejig so protein families is above protein features...

I don't follow that.  When you say "protein families" do you mean "Protein families and domains"?

"Protein families and domains" is currently inside the Protein features section of the page.  Do you want to make "Protein families and domains" into it's own section outside of the Protein features section?

**Comment by ValWood** [comment]
sorry not clear.

just in the query list:

![list](https://user-images.githubusercontent.com/7359272/30313097-15281a5c-9794-11e7-88bb-59f0c64cba04.jpg)

bump protein domains up  so above and adjacent to protein features.

**Comment by kimrutherford** [comment]
> bump protein domains up so above and adjacent to protein features

Done!

**Comment by mah11** [comment]
No wonder Kim was confused - this ticket is not about the query builder!

**Comment by ValWood** [comment]
Oh yes, wrong ticket  whoops.

**Comment by ValWood** [comment]
I think it's OK to close?

**Comment by mah11** [comment]
moved some comments to more suitable ticket #504
