### ISSUE TITLE
FYPO term/evidence combined filtering not working

### ISSUE THREAD

**Issue by mah11** [pombase/website#495]
From this comment when evidence filtering was deployed:
https://github.com/pombase/website/issues/249#issuecomment-293464984

I got the impression that we should be able to filter on FYPO terms and evidence simultaneously, and see annotations that match "term x AND evidence y" (if any). But that appears to be broken.

Whichever filter I select first works, but then nothing happens when I make a selection from the other filter pulldown (i.e. if I pick a term filter first, it works, but if I then pick an evidence filter no further filtering happens, and vice versa).

Oddly, if I remove the first filter, the second one I tried to set then magically starts working, a la

1. term filter -> annotations filtered by term
2. add evidence filter, yielding term filter + evidence filter -> no change
3. remove term filter, leaving evidence filter -> annotations filtered by evidence

 ... and vice versa, again.

Seems to affect gene pages and publication pages (not relevant on FYPO term pages, which are effectively already term-filtered). Doesn't seem to be browser-specific.

Probably ought to be fixed for release unless it's really hairy.

**Comment by kimrutherford** [comment]
Thanks for catching that.  It looks like combining filters never worked.  Sorry for the poor testing.

It should be fixed now.

**Comment by mah11** [comment]
thanks - trying to document how it should work is a great way of finding things that don't ...
