### ISSUE TITLE
more controlled curation to display

### ISSUE THREAD

**Issue by mah11** [pombase/website#496]
following on from #494, I found a few other controlled curation types that we probably want to show on PomBase2 gene pages:

* catalytic activity	(example: hsp3102)
* experimental tools (lys3)
* genome organization	(pol4)
* misc functional group	(prz1)

On legacy-PomBase gene pages, these each have their own little sections, but that may be overkill. Unless @Antonialock or @ValWood objects, I'd be happy to lump the lot in with the Miscellaneous listing.

v2 milestone only because these are visible in old pb

There are also a few "pathway" annotations, but those will probably be superseded by cleverer GO/interaction/etc. curation and displays ...?

**Comment by ValWood** [comment]
I agree they could be lumped.

"pathway" annotations could be reported in the logs and we can then target them for GO 
with annotation extension annotations (if they are not covered already).

v

**Comment by Antonialock** [comment]
yeah may as well keep it concise

**Comment by kimrutherford** [comment]
> I agree they could be lumped.

Do we need sub-headings in the Miscellaneous section, like this?:

- Catalytic activity
- Experimental tools 
- Genome organization
- Misc functional group

**Comment by ValWood** [comment]
I guess it wouldn't hurt because it would make grouping more sensible.

**Comment by mah11** [comment]
I think sub-headings would be neither harmful nor essential, so I don't have a strong preference.

**Comment by kimrutherford** [comment]
> I guess it wouldn't hurt because it would make grouping more sensible.

A lot of genes only have one of the four types so in a lot of cases there will be the main "Miscellaneous" heading, then a sub-heading and then a one line table.  It looks a bit odd.  pombase-dev now has a "Miscellaneous" section for you to have a look at.  I'll add it to the preview tomorrow if it's OK.

**Comment by mah11** [comment]
I think it looks fine on pombase-dev now; I still don't have a strong preference wrt keeping or losing the sub-headings.

I did notice one finicky nit-picky little thing: anything that's not catalytic activity, experimental tools, or genome organisation gets the "miscellaneous functional group" sub-heading. That's not quite correct, because in Artemis and Chado there are two separate CVs, the functional group one and the "really really miscellaneous" one. Strictly speaking only the m_f_g (89 annotations to 6 terms at present) should get "miscellaneous functional group".

Should we have something other than plain "miscellaneous" for the misc CV? Maybe something as simple as "Comment" would do.

example gene pages: rad54, sid2, our old poster child sty1

CV linkies
https://curation.pombase.org/pombe/view/object/cv/misc?model=chado
https://curation.pombase.org/pombe/view/object/cv/m_f_g?model=chado

**Comment by ValWood** [comment]
" comment" works

**Comment by kimrutherford** [comment]
> Maybe something as simple as "Comment" would do.

I've made that change.  It will appear in pombase-dev.bioinformatics.nz next time I update and in the preview a bit after that.

**Comment by kimrutherford** [comment]
> Maybe something as simple as "Comment" would do.

Done in the preview.
