### ISSUE TITLE
"showing x of y annotations" and combining FYPO filters

### ISSUE THREAD

**Issue by mah11** [pombase/website#497]
almost there, per #495, but ...

This is a bit subtle, so I hope the explanation makes sense.

With FYPO annotation display filtering, if I filter on one thing the "Showing x of y annotations" message makes sense, but if I do both at term filter and an evidence filter the denominator changes (doesn't keep showing the overall total number of annotations).

e.g. cdc2 has 211 single-allele cell phenotype annotations at the moment

If I filter for localization phenotype I see "Showing 10 of 211 annotations"

and filter for microscopy -> "Showing 115 of 211 annotations"

but filter for localization phenotype AND microscopy -> it says "Showing 8 of 115 annotations" if I apply the evidence filter first, or "Showing 8 of 10 annotations" if I do the term filter first.

It ought to show the total annotation count every time, i.e. "Showing 8 of 211 annotations" in the cdc2 example.

**Comment by kimrutherford** [comment]
Thanks for the good description of the problem.  Should be fixed now if you reload.

**Comment by mah11** [comment]
yep, looks good now. thanks!
