### ISSUE TITLE
tweak query builder display

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#498]
can the deep colored box be tweaked so that it either looks like this:

Include genes from: 
[ ] Single-allele genotypes 
[ ] Multi-allele 

or
Include genes from: [ ] Single-allele genotypes [ ] Multi-allele 

(and same for expression level?

This is what it looks like (for me) at the mo:

<img width="1185" alt="screen shot 2017-08-31 at 08 53 13" src="https://user-images.githubusercontent.com/12727506/29912673-611e668c-8e2a-11e7-8d2a-ba8eefe21dfe.png">

**Comment by Antonialock** [comment]
also the box slightly overlaps "history"

**Comment by kimrutherford** [comment]
I think I've fixed those problems in the preview.  Could you reload and see what you think?

**Comment by Antonialock** [comment]
looks great now :)
