### ISSUE TITLE
query builder lucene search issue

### ISSUE THREAD

**Issue by ValWood** [pombase/website#500]
"signal transduction"
does not show exact match
GO:0007165 signal transduction

**Comment by ValWood** [comment]
probably a weighting issue? but exact match should always be top of the list.

**Comment by kimrutherford** [comment]
Short matches are supposed to be pushed to or near the top.  I'll dig into Solr/Lucene to find the problem.

**Comment by kimrutherford** [comment]
The problem was that the weight the term synonyms was too high and that was skewing the results.

I've improved things and the changes will be in the preview in the morning.

**Comment by kimrutherford** [comment]
signal transduction is now at the top in the preview.  Let me know when you spot other oddities.
