### ISSUE TITLE
Query builder, change text "count"

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#502]
1. I think "count" (in the history section) should be changed to "results". 
(more obvious wording to prompt people that there is a hyperlink that can be clicked to get through to the results?)
2. I think the "count" column should be moved to the left of the "query" column. Again, this is just to make it more obvious for users that there is a hyperlink that can be clicked to get through to the reults. Due to the width of the query column it's very much tucked away at the moment.

**Comment by Antonialock** [comment]
2. I think the "count" column should be moved to the left of the "query" column. Again, this is just to make it more obvious for users that there is a hyperlink that can be clicked to get through to the reults. Due to the width of the query column it's very much tucked away at the moment.

**Comment by ValWood** [comment]
I'd be happy for these changes. Looks quick?

**Comment by kimrutherford** [comment]
> Again, this is just to make it more obvious for users that there is a hyperlink that can be clicked to get
> through to the reults

Yep, that's a problem.

I've made those changes and they'll be in the dev and preview soon.

That change helps but I think it's still easy to miss that the count is a link.
