### ISSUE TITLE
reorder queries?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#504]
I think it would be better to put
phenotype 
protein domain
protein feature ->protein sequence feature
protein modification

Users might think "protein feature" is where they search for "domain" if they don't read the rest of the list. Especially since we call the  gene page section "protein features".

Putting protein domain first, and protein sequence feature, adjacent will make any confusion less likely.

Also need to add prompts for "protein sequence feature"
"NLS" and "KEN box" should do?

**Comment by mah11** [comment]
transferring some comments from #494, which is not about the search:

>> Val: OK  Kim, just rejig so protein families is above protein features...
>> 
> Kim: I don't follow that.  When you say "protein families" do you mean "Protein families and domains"?
> 
> "Protein families and domains" is currently inside the Protein features section of the page.  Do you want to make "Protein families and domains" into it's own section outside of the Protein features section?

Val: sorry not clear.

just in the query list:

![list](https://user-images.githubusercontent.com/7359272/30313097-15281a5c-9794-11e7-88bb-59f0c64cba04.jpg)

bump protein domains up  so above and adjacent to protein features.

**Comment by mah11** [comment]
more transferred: 

> bump protein domains up so above and adjacent to protein features

Done!
