### ISSUE TITLE
order target of section by relationship

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#506]
I'm sure it used to be ordered by the relationship but not anymore e.g. 
http://preview.pombase.org/gene/SPBC29B5.01

![screen shot 2017-09-08 at 08 34 21](https://user-images.githubusercontent.com/12727506/30200877-99369516-9470-11e7-8869-b691aad4ed96.png)

**Comment by Antonialock** [comment]
substrate of first

**Comment by ValWood** [comment]
I think there is another ticket about target_of section ordering...

**Comment by ValWood** [comment]
can't find it though...

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/website/issues/299
