### ISSUE TITLE
main page header menu adjustments

### ISSUE THREAD

**Issue by mah11** [pombase/website#508]
- delete "Staff" from About menu

The linked page has nothing but the helpdesk email link and the Cambridge postal address. Now that we've moved that info to the main "About PomBase" page, there's no need to keep the Staff page or its menu entry. 

- delete "Curation pilot project" from Community menu

For this one we're keeping the linked page, but it's not important enough to have its own entry in the main menu. The links on the Community page and within the current "Community curation project" page suffice.

Assign to me if you want to teach me how to do this sort of thing.

**Comment by kimrutherford** [comment]
I've made those changes.  They'll appear in the preview next time I update, which hopefully will be this morning.

The changes went into here:
  https://github.com/pombase/website/blob/master/frontend/src/app/main-nav-bar/main-nav-bar.component.html

Apart from the funky routerLink="..." stuff that file is normal HTML.  If you add and remove menus or menu items let me know and I'll re-deploy.

Here is the change I just made:
   https://github.com/pombase/website/commit/990231044a602d75e5cd05a90db487771a97c1d1
