### ISSUE TITLE
missing pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#509]
In our chat yesterday (7 Sept) Kim noted that the data dump from EBI, which was supposed to have _everything_, is in fact missing quite a bit from the Drupal side.

I have manually added back the missing non-FAQ documentation pages and the file format descriptions that were under submit-data (now also in documentation).

This is a list of other pages that I've noticed are missing:

- submit-data/gene-name-registry	may move from submit-data; need all sub-pages too:
  - Gene Naming Committee members
  - S. pombe gene naming guidelines
  - Reserved gene names
  - Gene name conflicts
  - Gene name reservation form

- downloads page	and all sub-pages, i.e.
  - downloads/datasets - go through and decide which sub-pages to keep; make list of edits
  - downloads/documents - and all sub-pages and linked files (also see https://github.com/pombase/website/issues/355#issuecomment-328075868)
  - downloads/chado-database-dumps	(note to self: edit text)

- news archive (in #239 it seems we decided not to continue adding news items as a separate thing, but do we want to link the old ones somewhere out of the way but accessible if you look?)

**Comment by ValWood** [comment]
Why did we decide not to have news items? I don't remember that...

**Comment by mah11** [comment]
It's entirely possible I misinterpreted the old ticket. The important point is that the news items are among the missing, so if we want the old news for a pombase v2 archive either Kim has to get them in his second attempt or we'll have to screen-scrape 'em.

I also don't see a ticket about news in pombase 2 - how it'll work, where we put items, etc. Should I create one?

**Comment by ValWood** [comment]
OK, in  #239 we have
-news feed
-events (dump this as news feed is sufficient?)
-jobs (dump this as news feed mailing list is sufficient?)

(I think this just means that jobs and events are not required (IIRK, were never asked for), we would just put such things on the news feed....

But I don't think we discussed anything about how we want it to be....

**Comment by mah11** [comment]
ok, #510

**Comment by mah11** [comment]
download page now in #512, and gene names in #515, so I think everything's covered
