### ISSUE TITLE
default sorting for phenotypes

### ISSUE THREAD

**Issue by mah11** [pombase/website#51]
Quoth Antonia:
"When looking at the phenotype annotations in full view I think it would be nice if the table was sorted so that the annotations for each individual phenotype:
1. sort the alleles by type (deletion, WT, point mutant...)
2. by the description (to group point mutants, specific partial deletions, etc)
3. by expression (so that WT overexpression/knockdown gets grouped)
4. by reference (decreasing chronological age - oldest reference shown at the top)"

**Comment by ValWood** [comment]
Ability to sort on the term list pages too
Here is a  nice example where sorting by product/description would provide a much nicer "functional grouping" for "parsing by head"
http://www.pombase.org/spombe/related/FYPO:0003559
(product/descriptions tend to be much more consistent than gene naming conventions)

**Comment by ValWood** [comment]
I think this  ticket supersedes?

https://github.com/pombase/website/issues/93

@Antonialock if not please elaborate on  https://github.com/pombase/website/issues/93
