### ISSUE TITLE
new news feed

### ISSUE THREAD

**Issue by mah11** [pombase/website#510]
We've clarified that we do want a news feed of some sort in PomBase 2 (after M getting confused in #509).

Kim to investigate options; curators to discuss what we want to be able to do and where news should appear.

Also set up a news archive, to be populated once we extract the content from EBI (again, per #509).

The release itself will be great big news but I don't know if that means we need the news feed itself in time for it ...

**Comment by kimrutherford** [comment]
> Kim to investigate options; curators to discuss what we want to be able to do and where news
> should appear.

I think the easiest way to get this done soon is to add news items in the same way we add documentation.  If we include the date stamp in the file name, I can pull out the most recent items for display on the main page.  The older items can hang around in a "News" or "News archive" section of the site.

For now this would be mean we need to redeploy the site to see the new news.  The re-deploy is manual but it's quite quick.

Later I'll change it so that the new news goes live when we add a new item at GitHub.

To get things started, I've created a "news" sub-directory: https://github.com/pombase/website/tree/master/frontend/src/docs/news

I'll work on including the news on the front page.

**Comment by kimrutherford** [comment]
I've added a news feed component.  For now it's squashed into the front page so we can see it in action.

News can be added here, in Markdown format:
  https://github.com/pombase/website/tree/master/frontend/src/docs/news

If you put the date at the short of the file name (eg. "2017-06-02-new-pombase.md") the news will appear in the correct date order.

**Comment by ValWood** [comment]
great start.

**Comment by kimrutherford** [comment]
>  For now it's squashed into the front page so we can see it in action.

It's a bit too squashed at the moment.  I'll fix that.  I'm also adding a heading and tweaking the font size.

**Comment by mah11** [comment]
> e. g. "2017-06-02-new-pombase.md"

hooray for ISO 8601 date format!

**Comment by kimrutherford** [comment]
> hooray for ISO 8601 date format!

Yep, it makes sorting straightforward.

**Comment by Antonialock** [comment]
if I make my browser window narrower it overlaps the image
![screen shot 2017-09-15 at 10 12 39](https://user-images.githubusercontent.com/12727506/30475370-8231b024-99fe-11e7-9908-af93a9f27da2.png)

**Comment by kimrutherford** [comment]
> if I make my browser window narrower it overlaps the image

Me too.  :-)

I'm going to move it.

**Comment by kimrutherford** [comment]
In the dev version I've moved the recent news section down a bit:
  http://pombase-dev.bioinformatics.nz/

That's temporary until we've decided how the front page should look.

The change will appear in the preview soon.

**Comment by kimrutherford** [comment]
I've tidied up the front page a bit and fixed a bug or two in the news feed.

And I've now added all the old news.  The items should be visible here in the morning:
  http://preview.pombase.org/news

We should talk about how that page and the recent news items feed are formatted.

**Comment by ValWood** [comment]
Front page on the list for curator meeting this week. It's our "fun task".

Oh we also have another task which will be lots more fun.....more on this later.....

**Comment by ValWood** [comment]
I think we done here. Will open new for further. Update to front page organization to follow when eduroam working.

**Comment by mah11** [comment]
> We should talk about how that [news archive] page and the recent news items feed are formatted.

Watch the front page ticket (#513) for Val's mockup, which includes where the news feed should go. We're basically happy with the feed format.

For the archive page, each news item should show its date, at least in the page body.

We think the contents (i.e. old news items) should all be in the body of the page, in reverse chronological order. The left-hand menu can still be there to link to any specific item, but just jump to the right point in the page (anchor).

(If within-page anchoring is a pain, the menu links could go to individual pages as they do now. In that scenario, also include a "back to news archive" link.)

**Comment by kimrutherford** [comment]
> For the archive page, each news item should show its date, at least in the page body.

That's done.  Let me know if you'd like the style or formatting changed.

> We think the contents (i.e. old news items) should all be in the body of the page, in reverse
> chronological order. The left-hand menu can still be there to link to any specific item, but just
> jump to the right point in the page (anchor).

That's done too.

**Comment by mah11** [comment]
I like it. Thanks!

**Comment by mah11** [comment]
Hang on, one odd thing: the left-hand menu is in chronological, not reverse chronological, order. I meant for the menu to be in the same order as the body, newest first (so both go back in time as you scroll down - that's what's "reverse" about it).

I do like it otherwise, though. And apologies for any confusion.

**Comment by kimrutherford** [comment]
> I meant for the menu to be in the same order as the body

Oh yes, that makes sense.  I'll fix that.

**Comment by kimrutherford** [comment]
> That's fixed in the preview

Sorry, I meant in dev.  It will be in the preview tomorrow.

**Comment by ValWood** [comment]
Can close this?
 Will need repositioning as part of front page revamp, but all else done?

**Comment by kimrutherford** [comment]
Yep, I think it's all done and released.
