### ISSUE TITLE
Improve the front page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#513]
Remove Docs section on front page.  Move GO Slim terms and Curation statistics to Genome status menu.

Remove "New publication pages (examples)".

This will give us more room for the news feed.

**Comment by kimrutherford** [comment]
I've done this but I forgot to ask where the GO Slim terms and Curation statistics should appear in the menu.  Here's what it looks like for now.  Please let me know any changes you'd like.

![screenshot from 2017-09-18 09-20-16](https://user-images.githubusercontent.com/90474/30525164-d43eb20a-9c55-11e7-9ba9-19a000a2679f.png)

**Comment by ValWood** [comment]
Put
GO slim terms -> GO slim overview
Curation statistics
Sequencing status -> Genome Sequence status
Sequence updates -> Genome Updates
Genome statistics -> Genome Feature Overview
Gene Coordinate Changes
New and Removed Genes
Gene Characterisation -> Gene Characterization Status
Priority Unstudied Genes

**Comment by kimrutherford** [comment]
I've made those changes in the dev vesion.

http://pombase-dev.bioinformatics.nz/

**Comment by ValWood** [comment]
New front page mock up

![presentation2](https://user-images.githubusercontent.com/7359272/30640603-71c83eaa-9dfb-11e7-890e-49b28b69bcdf.jpg)

we want to highlight the GO slim and the advanced search permanently.

For the time being the current text can go in the  rotating text box. Here we till highlight areas of biology, papers, feature (orthlog, unknowns) etc etc.

**Comment by kimrutherford** [comment]
Looks good!  I'll rearrange it tomorrow so we can have a look when we chat on Thursday morning.

I'm slightly concerned that three columns won't look good, but we can discuss that after I move things.

What else should go in the "Explore" section?

**Comment by ValWood** [comment]
Its going to be a bit "empty"
More like a big botton.

Can't quite believe my example but a little like
http://www.ebi.ac.uk/QuickGO/
a very simple graphic or icon maybe?

Should we try to make an "icony thing" a bit like this?

**Comment by kimrutherford** [comment]
> a very simple graphic or icon maybe?

I think graphics and icons can help.  I don't like sites that just have a wall of text on the front page.  Graphics and icons and sometimes colours and borders can help make pages easier to take in.

**Comment by kimrutherford** [comment]
Where should the social media icons GO in the new arrangement?

**Comment by ValWood** [comment]
top right in figure, directly under menu.

**Comment by kimrutherford** [comment]
I've done some of the rearranging.  You'll see it in dev if you reload.  It doesn't look quite like Val's mock up yet as I'm still tweaking the layout.  http://pombase-dev.bioinformatics.nz/

I haven't tried it but I think the layout might look better if the rotating image was at the top right.

**Comment by ValWood** [comment]
![temp icon](https://user-images.githubusercontent.com/7359272/30690739-18bac3ec-9ebd-11e7-84bd-751d2b707baf.jpg)

**Comment by ValWood** [comment]
I just had a quick pay around. 
I think we should go more like this:

![presentation6](https://user-images.githubusercontent.com/7359272/30735865-6d3bc19e-9f78-11e7-8109-aec2c6aa3f51.jpg)

**Comment by ValWood** [comment]
So we could have 3 blocks across, or  2 up 2 down.

We would always try to have a "research or gene focus" we could have more than one, rotating.
The community curation feed could be permanent ( but could have its own rotating set of icons to focus on different metrics  or canto link for eg.
A database or data spotlight (orthologs, unknowns, searching), a set of rotations.

Example popular pages could be above....we could even change these (gene, term etc)  based on analytics maybe?) .  We would just need an icon and a text snippit.

News feed could be horizontal across the bottom.

Something like this would keep the front page fresh and draw the eye to new stuff.

**Comment by Antonialock** [comment]
yeah I think this would look cool

**Comment by kimrutherford** [comment]
I like the shadows on the boxes.

**Comment by ValWood** [comment]
Title :Step into the unknown
Body: PomBase maintains an inventory of proteins with no known biological role, including their taxonomic conservation…..more
More: link to http://preview.pombase.org/status/priority-unstudied-genes

**Comment by ValWood** [comment]
![layout](https://user-images.githubusercontent.com/7359272/31224755-2115b44c-a9c7-11e7-9e26-a094f35f9d51.jpg)

**Comment by kimrutherford** [comment]
I've made some progress on the front page changes.  Here's the prototype:
  http://pombase-dev.bioinformatics.nz/

All the text and links are just placeholders at the moment so we have something to talk about.

The configuration is in:
   pombe-embl/website/pombase_v2_config.json
Look for the "front_page_panels" section if you're curious.

and the two test images are in this directory in Git:
  https://github.com/pombase/website/tree/master/frontend/src/assets

There is only one "Research spotlight" and one "Explore PomBase" configuration at the moment but the code is in place to randomly change what's on the front page.

I'll do a bit more work on this on Monday and then on Tuesday we can discuss it.

**Comment by ValWood** [comment]
Great start.

I don't think there will be too much to change!

- [ ]  can the boxes be wider and deeper?  so the images can be larger. This will make more room for text  too... don't worry if the text spots are a little empty for now.

- [ ]  I think the shading will be more effective if the box does not have the black line around

- [ ]  Titles and text need slight indentation 

- [ ]  can we collapse the news a bit by
either

2017-06-01 
or 
New PomBase 2017-06-01

**Comment by ValWood** [comment]
; ) https://elifesciences.org/articles/28865/figures#video1
this will be so cool!

**Comment by kimrutherford** [comment]
> deeper

If you mean taller, no problem.  They will be taller once we add more text in the boxes - the height varies depending on content.

**Comment by ValWood** [comment]
OK . I was thinking that the image would be a "fixed size" at the top, and the text would also be a "fixed size at the bottom.

Overall I think the images should be larger.

**Comment by ValWood** [comment]
I have put 2 images for the top of the  "community curation feed" rotation in the dropbox
frontpage_rotations/community_curation_feed
(we can rotate the images on this feed even though the text will stay the same...well will change but in a different manner...)

**Comment by ValWood** [comment]
I added another "Pombase spotlight" to the images folder.
This is the accompanying draft text:

Title: Biological processes Overview
Text: The fission yeast “GO slim” provides a summary of genes
annotated to broad biological processes…more(link)
Link http://preview.pombase.org/browse-curation/fission-yeast-go-slim-terms


so now we have 2
i) unknowns
ii) slims
iii) to do, query builder

**Comment by ValWood** [comment]
> Overall I think the images should be larger.

don't worry about pushing the news feed down.... I think that is OK as long as the top of it will be normally visible on a small page....

**Comment by kimrutherford** [comment]
> Overall I think the images should be larger.

Can you suggest an X and Y resolution?  The current sample images are 240 x 150.

When you have time, can you suggest some text for the Gould lab spotlight?  I only put in "Cytokinestic ring assembly." as a placeholder.

> so now we have 2
> i) unknowns

What should the title, text and link be for the Unknowns?

**Comment by kimrutherford** [comment]
> The current sample images are 240 x 150.

Here they are for reference:

http://pombase-dev.bioinformatics.nz/assets/explore-poster-2017-10-06.png
http://pombase-dev.bioinformatics.nz/assets/spotlight_gould-2017-10-06.png

**Comment by ValWood** [comment]
I can't reconcile the measurements because they look a different size to me but I think they should be ~25 % bigger.

**Comment by ValWood** [comment]
Title :Step into the unknown
Body: PomBase maintains an inventory of proteins with no known biological role, including their taxonomic conservation…..more
More: link to http://preview.pombase.org/status/priority-unstudied-genes

**Comment by ValWood** [comment]
we'll write the other text soon. I'll do cytokinesis today.

**Comment by kimrutherford** [comment]
> they should be ~25 % bigger

OK, I'll try that.

**Comment by kimrutherford** [comment]
- add more space between news items
- fix Markdown for "9th International Fission Yeast Meeting registration open" - too much space before "Conference Organizers"

**Comment by kimrutherford** [comment]
The dev site now has the new front page.  I'll update the preview tomorrow after doing some checking and tidying.

**Comment by ValWood** [comment]
yes we can close this and put new requests in a new ticket.
v

**Comment by kimrutherford** [comment]
The preview now has the new front page layout.  The Gould lab text hasn't changed yet but it's ready to go.

**Comment by Antonialock** [comment]
shiny!

**Comment by ValWood** [comment]
freed from the limitations of Drupal....
