### ISSUE TITLE
gene coordinate update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#514]
/controlled_curation="term=warning, gene coordinates updated; db_xref=PMID:28469148; date=20170914"

**Comment by mah11** [comment]
do you have the old & new coordinates handy? (would save me extracting them from svn)

**Comment by ValWood** [comment]
whoops, 
old
complement(join(757566..757746,757796..757951,758130..758197))

new
complement(join(757566..757746,757796..757951,758002..758042))

**Comment by mah11** [comment]
thanks

**Comment by mah11** [comment]
also, I see from the helpdesk ticket that it's rec27 / SPBC577.05c

that would also be a good thing to remember to put in tickets!

**Comment by ValWood** [comment]
whoops, critical part.
