### ISSUE TITLE
gene naming page

### ISSUE THREAD

**Issue by mah11** [pombase/website#515]
Where do we want to put the pombase2 successor to the Gene Name Registry (pb1 version at http://www.pombase.org/submit-data/gene-name-registry)?

Per #451, we only need submission forms for gene names and HTP data. Do we still want a "submit" tab/section in the main menu with only two (or 3, if we keep "curate a paper") entries? If not, where should the links go?

We also need to get the files into GitHub (that would be @kimrutherford's part of this ;) ) but maybe curators should decide where the gene name stuff fits first, so we don't have to faff with moving them.

@ValWood - do we still use the "reserved names" page?

**Comment by ValWood** [comment]
WE can get rid of

Reserved gene names
Gene name conflicts

it's extra admin we don't really require. 

I will also simplify the guidelines, since nobody reviews their reserved names, and once they have been added we don't  withdraw them if not published, because usually they will be the ones other people will use. If an alternative name is eventually used as primary, I can just relegate to synonym.

We only have ~1000 protein coding genes to name now...

**Comment by ValWood** [comment]
https://www.pombase.org/submit-data/gene-name-registry
![err](https://user-images.githubusercontent.com/7359272/32138599-5b13fbb8-bc2d-11e7-806b-c3720ef80393.jpg)

**Comment by ValWood** [comment]
Love it...

**Comment by ValWood** [comment]
I probably need to do something ?

**Comment by mah11** [comment]
Yep - decide where you want it. Back under "Submit data"?

Slightly longer term, we should also add back a gene name submission form. It does still get used (or did before we did the otherwise awesome 'n wonderful release).

**Comment by ValWood** [comment]
I guess under "Submit" is best....

**Comment by mah11** [comment]
OK, I _think_ I have done the edits that will make the gene naming stuff visible. @kimrutherford might have to release something manually - I've lost track of which bits are and aren't auto-pipeline-magic at this point.

I edited the naming guidelines a bit, and can change more if you want (once you can see the content).

I'll close this when it's live and we're happy with the text.

**Comment by mah11** [comment]
new paths: pombase/submit-data (linked on About page) and pombase/gene-names (linked in Submit menu)

**Comment by mah11** [comment]
had to fix some paths, so some 404s will persist until tomorrow, but essentially done.

**Comment by kimrutherford** [comment]
> new paths: pombase/submit-data (linked on About page) and pombase/gene-names (linked in Submit menu)

Those paths are working now.
