### ISSUE TITLE
remove term from slim

### ISSUE THREAD

**Issue by ValWood** [pombase/website#516]
GO:0006797 - polyphosphate metabolic process

This  will disappear from our slim shorlty
http://preview.pombase.org/term/GO:0006797

but can removed locally sooner. 

I need to remember where, again

**Comment by kimrutherford** [comment]
The config file is pombe-embl/website/pombase_v2_config.json

Search for "go_slim_terms"

**Comment by kimrutherford** [comment]
That should be live in the preview now.

**Comment by ValWood** [comment]
yep, tks
