### ISSUE TITLE
Make the Document menu bar look and act like the gene page menu bar

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#517]
The current docs menu bar is a bit naff.

**Comment by ValWood** [comment]
This might even be done. Not sure what it is...

**Comment by kimrutherford** [comment]
> This might even be done. Not sure what it is...

The gene page menu looks different to the documentation page menu.  See the screenshots below.  I don't really like either style but it would be better if they matched at least.  They don't act the same either - the gene page menu stays on screen when you scroll but the docs one doesn't.

We don't need to fix for the release but I'd like to fix it soon-ish.

![naff_pombase_menus](https://user-images.githubusercontent.com/90474/31591632-102394be-b27e-11e7-824e-23bf0a2db1db.png)

**Comment by ValWood** [comment]
I see, I had never noticed.
I don't know what my pref is....
We could look at options on a call?

**Comment by kimrutherford** [comment]
> We could look at options on a call?

I think so.

Here's another sort of style to think about:

![screenshot from 2017-10-16 21-14-16](https://user-images.githubusercontent.com/90474/31601656-1467151c-b2b7-11e7-8cc9-8333234cf0de.png)

**Comment by ValWood** [comment]
Preferences anyone, will discuss on next call...

**Comment by kimrutherford** [comment]
> Preferences anyone?

I prefer the front page menu to the menu on the documentation pages.  The front page menu isn't great but I'm not too unhappy with it but I prefer if we can get rid of the lines and boxes.

Here's another option:

![menu_experiment](https://user-images.githubusercontent.com/90474/36755753-0de02538-1c72-11e8-8d43-653d684c9ef5.png)

**Comment by Antonialock** [comment]
Yeah I prefer it with no lines (and possibly a bit of shading + indented from "wee1 summary" to show that is at "the top" if you want to navigate back up quickly)

**Comment by kimrutherford** [comment]
We can try some options on the call.

![menu_experiment_2](https://user-images.githubusercontent.com/90474/36760048-46edc086-1c7e-11e8-9668-2000a0d7c03c.png)

**Comment by ValWood** [comment]
I don't know. I didn't like the bars when I saw them last night, but  they grew on me already!

**Comment by kimrutherford** [comment]
> I didn't like the bars when I saw them last night, but they grew on me already!

That's good because I'm prototyping it on pombase-dev: http://pombase-dev.bioinformatics.nz/datasets

:-)

(It's still a bit rough)

**Comment by ValWood** [comment]
Here I go with my colours ;)
I think what I don't like is the lilac.
I think if we picked up the spore colour, it is a) more neutral, and b) would contrast better with the grey bar and the text, it might look more appealing.


![presentation1](https://user-images.githubusercontent.com/7359272/36782988-9e00d400-1c72-11e8-8246-d31dad62243d.jpg)

**Comment by ValWood** [comment]
RAL1001? (buff, not too yellowy and not too pale)

**Comment by kimrutherford** [comment]
Do you want to have a play around here and send me a hex value to try?: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool

Apparently RAL1001 is #d0b084

**Comment by kimrutherford** [comment]
This site is fun, you can put in a colour and it suggests complementary colours:
  http://rgb.to/hex/bbc3de

For our header colour it suggests this, which is a bit paler than RAL1001:
  http://rgb.to/hex/ded6ba

**Comment by kimrutherford** [comment]
I think RAL1001 is too dark:

![menu_experiment_3](https://user-images.githubusercontent.com/90474/36783534-33a94456-1ce1-11e8-9254-0559fe8a7f80.png)

**Comment by kimrutherford** [comment]
We can play we things like the colour live on a Skype call.

Here's the "complementary" colour:

![menu_experiment_4](https://user-images.githubusercontent.com/90474/36783662-aa3eca00-1ce1-11e8-86b2-e4915b0e59ed.png)

**Comment by kimrutherford** [comment]
For completeness, this is what it looks like if we use the colour from the header.  I'm going to leave this for now and we can chat tomorrow.

![menu_experiment_5](https://user-images.githubusercontent.com/90474/36783817-2c82b63e-1ce2-11e8-9f21-c0be9e145034.png)

**Comment by ValWood** [comment]
Comments below each of the above. we can do tomorrow...

**Comment by kimrutherford** [comment]
> the gene page menu stays on screen when you scroll but the docs one doesn't.

That fix is ready to go whatever we decide to do with the menu.

**Comment by kimrutherford** [comment]
I've updated the main site with to use the new style of menu.  And the docs menu is now the same style as the gene page menu.  Let me know about any changes you'd like.

**Comment by kimrutherford** [comment]
No one has complained so I'll close this.
