### ISSUE TITLE
modification data/ database

### ISSUE THREAD

**Issue by ValWood** [pombase/website#519]
Add to our list of resources

https://www.ncbi.nlm.nih.gov/pubmed/28889911?dopt=Abstract

and see if we missed any.

We should also look if we can get any from  iptmnet
(if they share data we could get from a single source)

**Comment by ValWood** [comment]
should we add this link to the modification section in the meantime? We plan to provide similar longer term.
https://github.com/pombase/website/issues/17

we should add to external refs at least
http://research.bioinformatics.udel.edu/iptmnet/entry/P04551/

note to self, alignment across species does not seem to work for fission yeast?

**Comment by mah11** [comment]
The part about iPMTnet is redundant with #477 and #15.

**Comment by ValWood** [comment]
OK this ticket is about 2 things.

1, add external link to  FPD if possible (quick)

2. See if we can obtain modification data directly from FPD and IPTMNet (later, low priority)

**Comment by ValWood** [comment]
I don't think you can link in by ID, you can search on Uniprot ID but it is converted to ....
http://bis.zju.edu.cn/FPD/index.php?mod=detail&fpdid=FPD0010686

**Comment by ValWood** [comment]
doesn't seem very comprehensive anyway....

**Comment by ValWood** [comment]
Added to futuer doc
