### ISSUE TITLE
query by nucleotide length

### ISSUE THREAD

**Issue by mah11** [pombase/website#52]
Add a search option to query genes by length in nucleotides (analogous to protein length, and particularly useful for ncRNAs).

Requested in https://rt.sanger.ac.uk/Ticket/Display.html?id=493894

**Comment by kimrutherford** [comment]
It would be straight forward to add querying by length in nucleotides.

**Comment by ValWood** [comment]
OK, add when you can if quick. I'll change to "medium priority" and you can do when it suits...

**Comment by kimrutherford** [comment]
> Add a search option to query genes by length in nucleotides

Do we need to query for the length of the gene in nucleotides or the length of the transcript?  If it's the transcript, should the length include introns when querying coding genes?

**Comment by ValWood** [comment]
I envisaged length of the transcript. However, these are highly inaccurate in the current annotation....so I don't know how meaningful the query resuls would be right now.....

**Comment by ValWood** [comment]
Lets leave this until features are refined. Only one person has asked and they can do it  bioinformatically.

**Comment by ValWood** [comment]
We won't dop this until the non-doiding RNAs are refined. I will open a new ticket later. I 'future' for now
