### ISSUE TITLE
community curation feed not updating

### ISSUE THREAD

**Issue by ValWood** [pombase/website#520]
A paper completed a few days ago didn't appear.

PMID: 28552615

v

**Comment by ValWood** [comment]
I still don't see this in the feed. Ant ideas why?

**Comment by kimrutherford** [comment]
The feed is currently ordered by the date of submission rather than the date of approval and the session for that publication was submitted 2017-07-14.

**Comment by kimrutherford** [comment]
It's definitely in the database: http://pombase-dev.bioinformatics.nz/reference/PMID:28552615

**Comment by ValWood** [comment]
Hmm, can we order by approval date. This one was in approval for a long time and was therefore never  on the front  page feed....

**Comment by kimrutherford** [comment]
> can we order by approval date. 

No problem.  I'll do that for tomorrow.

**Comment by kimrutherford** [comment]
> can we order by approval date.

I've made that change.  It should show up in the dev site in the morning.  The overnight load was delayed because I tripped over the power cord (metaphorically speaking) but it should be ready by 11am or so.

**Comment by ValWood** [comment]
great!

**Comment by kimrutherford** [comment]
Fixed in the preview.

**Comment by ValWood** [comment]
I just want to check something.

I think if we  update and reapprove a paper it may also show in the list using this mechanism.
Is there a way to restrict to first approval? That is tricky isn't it?

**Comment by ValWood** [comment]
Going forward, add an additional time stamp, first approval date.

I think in the meantime date submitted is less confusing and should catch everything provided we don't have them in approval for too long.

**Comment by kimrutherford** [comment]
See: https://github.com/pombase/canto/issues/1343

**Comment by kimrutherford** [comment]
> I think in the meantime date submitted is less confusing

From tomorrow they'll be ordered by the submission date unless there is a "first approval date" in which case that will be used instead.  Only sessions approved from yesterday onwards will have a "first approval date".  I'll close this issue once a few sessions like that have come through and everything works OK.

**Comment by ValWood** [comment]
Great!
