### ISSUE TITLE
query builder broken?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#521]
I think the query builder is broken on preview?

**Comment by ValWood** [comment]
and dev. Seems to be broken for everything other than status?

**Comment by kimrutherford** [comment]
What isn't working?  I tried a FYPO query, a feature_type query and number of exons and it was all OK.

**Comment by kimrutherford** [comment]
The dev server is working for me too.

**Comment by ValWood** [comment]
![untitled](https://user-images.githubusercontent.com/7359272/30589401-2384ff04-9d32-11e7-912d-9b25ad540f49.jpg)

**Comment by ValWood** [comment]
So that is what dev shows me ATM. All queries went to 0

But the preview seems to be working for me again now

**Comment by ValWood** [comment]
preview now:

![preview](https://user-images.githubusercontent.com/7359272/30589801-cd640032-9d33-11e7-9a68-44bef9b30c15.jpg)

**Comment by kimrutherford** [comment]
I've just updated the preview to last night's load.  Could you try reloading?

**Comment by ValWood** [comment]
still all zero :(

**Comment by ValWood** [comment]
The totals on preview just came back....then disapeared again......

**Comment by kimrutherford** [comment]
It's all gone rather wrong.  I think the missing terms is a separate problem.  I'm going to revert to load night's load.  preview will be briefly offline.

**Comment by kimrutherford** [comment]
Could you try again now?

**Comment by ValWood** [comment]
All seems fine now!
Thanks!

**Comment by kimrutherford** [comment]
I'm not sure what the problem was.  I'll investigate more tomorrow.

**Comment by kimrutherford** [comment]
pombase-dev updated automatically after last night's load.  There is still a problem with the query builder.  GO term queries seem fine but FYPO queries return no results.  So I haven't updated the preview, it's still the data from 2 days ago.  I'll work on fixing the missing FYPO results.

**Comment by kimrutherford** [comment]
All fixed now, including FYPO queries.
