### ISSUE TITLE
optimize search 'snippets'

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#524]
We should try and optimize the search snippets to reflect what we at PomBase offer, so that it is obvious why someone should click on our link (or not), I personally really dislike when snippets aren't informative. It would probably also improve search ranking (for example, when googling "mam2" I can't even find the preview site in the first few pages of search results). 

For example, if you google a publication title (I did this in an incognito tab) Preview is currently result number 6, not bad?! But the blurb doesn't really reflect what we do....
<img width="547" alt="screen shot 2017-09-20 at 16 25 38" src="https://user-images.githubusercontent.com/12727506/30652628-c2188d4a-9e20-11e7-8536-dfe8f2a493c6.png">

Maybe instead:
PomBase - publication page for PMID:xxx - Deub...
The PomBase publication page displays manual curation ~annotations extracted~ from PMID:xxx for S. pombe genes. ~These are manually assigned by PomBase curators and covers~ Curation includes Gene Ontology + terms+, phenotypes, protein modifications, and genetic and physical interactions.

Also do something similar for other pages (gene pages..)

**Comment by Antonialock** [comment]
for example see
http://www.practicalecommerce.com/influencing-how-google-displays-your-page-description

**Comment by mah11** [comment]
Not a bad idea in principle, but I don't like the suggested snippet text. It looks like everything except the PMID would be the same for every publication page, which would get very boring and lose attention rapidly (and violate that e-commerce site's advice to make snippets unique and page-specific).

To be honest, I don't have a problem with what Google shows for PomBase publication pages now. I actively like that the paper title shows up because it gives some biological info.

I don't object to changing "Reference - PMID:nnn" to "Publication page for PMID:nnn".

**Comment by Antonialock** [comment]
Gene product description for gene hits

**Comment by mah11** [comment]
clever idea for gene pages: copy the product description into the meta tag

**Comment by kimrutherford** [comment]
> I can't even find the preview site in the first few pages of search results

I'm not too surprised by that because it's not very visible to Google yet.  There are very few links to the preview.

> http://www.practicalecommerce.com/influencing-how-google-displays-your-page-description

Thanks.

> To be honest, I don't have a problem with what Google shows for PomBase publication pages now.

According to that article that Antonia found, one advantage of the snippet / meta tags is that the formatting won't change when Goggle changes its algorithms.

I suggest a snippet like this for the publication pages:

    PomBase publication page for PMID:28552615 - SUMO-Targeted DNA Translocase Rrp2 Protects the
    Genome from Top2-Induced DNA Damage.

> copy the product description into the meta tag

We can do that.

Note to self: https://github.com/vinaygopinath/ng2-meta

**Comment by kimrutherford** [comment]
I've added the meta tags (I think).  Once they start appearing in the Google search results we can tweak them text if it doesn't look right.

**Comment by ValWood** [comment]
Antonia could you review this some time?

**Comment by Antonialock** [comment]
Hm, publication pages look fine but it doesn't look like it is working as intended for gene pages

i.e.
 
**tco89**

![screen shot 2017-10-11 at 14 51 55](https://user-images.githubusercontent.com/12727506/31444331-df7af336-ae93-11e7-80f0-e9dfc7e12445.png)

![screen shot 2017-10-11 at 14 52 02](https://user-images.githubusercontent.com/12727506/31444353-ee7d8902-ae93-11e7-997b-43bf3d3019ba.png)

**uvi15**

![screen shot 2017-10-11 at 14 48 58](https://user-images.githubusercontent.com/12727506/31444369-f75a5b7c-ae93-11e7-9c3d-827470aad2e0.png)

![screen shot 2017-10-11 at 14 49 05](https://user-images.githubusercontent.com/12727506/31444377-fed8aaf2-ae93-11e7-8f20-2aa48d401bef.png)

**Comment by kimrutherford** [comment]
Thanks for checking.  That's a bit disappointing.  The publication pages look OK but it's not the text I put in the meta tag.

I'll do some Googling and try again.

**Comment by kimrutherford** [comment]
I've changed to use the official Google provided method for setting the meta tags.  Hopefully that will help.

**Comment by ValWood** [comment]
anything else to do her immediately?

**Comment by ValWood** [comment]
changed from "discuss" to "needs checking"

**Comment by Antonialock** [comment]
looks fine for a lot of them. Sometimes you get some weird results, but maybe this will straighten out & probably best we can do if you used the official google method?

example:

![screen shot 2017-11-01 at 14 10 34](https://user-images.githubusercontent.com/12727506/32278838-d4beefa2-bf0e-11e7-8528-9b51d3cbcdda.png)

**Comment by ValWood** [comment]
OK will close,
new ideas, new tickets...
