### ISSUE TITLE
Rotating images, click to embiggen

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#526]
The size of the rotating images makes it hard to see some of the detail. We don't necessarily want to make them bigger on the front page, but we want to make them 'clickable' and to open up a bigger version of the image. 

We don't simply want to link to a large version of the infographic poster because eventually we will want to add in additional rotating images.

**Comment by ValWood** [comment]
Sometimes we might want to go to a bigger version of the image, but the current ones are really only "decoration"
