### ISSUE TITLE
Add the downloads menu to V2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#528]
It should more or less look like V1

**Comment by mah11** [comment]
put it between Genome status and Community in the menu bar

items for the menu:
1. Datasets
2. Documents
3. Chado database dumps

**Comment by kimrutherford** [comment]
A while ago I grabbed a copy of the whole of the PomBase v1 site.  I then robo-converted all the HTML into Markdown using Pandoc.  The results are a bit poor but it's a start.

I've copied the generated Markdown to /data/pombase/pombase-v1-archive/v1_site_markdown/ on oliver0.

There should be a .md file for each page on PomBase v1.  If you can't find a page let me know.

Unfortunately, each .md file has a large ugly HTML header and footer that Pandoc didn't convert.  The useful Markdown is in the middle of each file.

**Comment by mah11** [comment]
> Unfortunately, each .md file has a large ugly HTML header and footer that Pandoc didn't convert.

That's not a show-stopper. I want to look at each page anyway, because most of them will need a bit of text editing, and kill-region is my friend.

Thanks for gathering the files.

**Comment by kimrutherford** [comment]
The menu is added and should be in the preview soon.

**Comment by kimrutherford** [comment]
The Downloads menu is in the preview now.

**Comment by mah11** [comment]
Looks good, and works as expected. I the outstanding stuff for the downloads department is all in #529 (or any new tickets that may arise).
