### ISSUE TITLE
Add the text from /downloads on V1 to the git docs directory

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#529]
http://www.pombase.org/downloads

See also:  #528

**Comment by kimrutherford** [comment]
I've added the downloads and datasets Markdown to Git.  I've done a first pass to remove excess header and footer HTML from the translation process.  I've fixed some links and syntax problems but there are still quite a few links that don't work because the file the other end is missing.

Some of the PDFs and other files links from this page are on the FTP site and some aren't:
  http://www.pombase.org/downloads/documents

I think the FTP site good place to archive old documents so should I move things there?

The downside at the moment is that I'm the only one with access to the Babraham server.  We can fix that though.

**Comment by mah11** [comment]
> I've added the downloads and datasets Markdown to Git. I've done a first pass to remove excess header and footer HTML from the translation process. I've fixed some links and syntax problems 

Thanks! I can get on with going through them manually to update the contents, and I'll see what else I can fix.

> Some of the PDFs and other files links from this page are on the FTP site and some aren't:
> http://www.pombase.org/downloads/documents

I suspect that may be a historical anomaly.

> I think the FTP site good place to archive old documents so should I move things there?

Sounds fine. Mainly I need to know where they are, wherever that is, so I can get the links to them correct. If they're all in one consistent location that's even better.

For meetings, I'll add a page for pombe2017, and we may also be able to track down a few more documents from the older pombe confs. I'll shout when I have documents to add.

**Comment by kimrutherford** [comment]
> I think the FTP site good place to archive old documents so should I move things there?

I have a new idea.

The "pombe" directory on the FTP site is big but not ridiculously so (currently 14GB) so I'm wondering if we should just check it into Subversion.  The big advantage is that we can then version control the FTP contents.  It would be a bit of extra local disk space but Subversion handles large repositories quite well.

If we did that the straightforward plan is to add the directory to the current pombe-embl Subversion repository.  We could just as easily have a separate repository.  Any preference?

If the pombe directory is in a Subversion repository we could update the main FTP directory automatically nightly by copying the SVN repo across to the FTP server.

**Comment by mah11** [comment]
> I'm wondering if we should just check it into Subversion. The big advantage is that we can then version control the FTP contents.

I can see the appeal - it would save us many rounds of curators-pestering-Kim for changes. I already have a list ...

> current pombe-embl Subversion repository ... [or] a separate repository. Any preference?

nope

**Comment by kimrutherford** [comment]
Thanks.  I'll have a deeper think about it tomorrow to try and come up with a good reason to pick one plan over the other.  At the moment I'm leaning toward having it all in one repository to make backup and management simpler.  At some point renaming "pombe-embl" to something better would nice since it's not a great name even now, but it's not urgent.

**Comment by mah11** [comment]
If it's all one repository, we don't have to faff around with checking out a new one. That's a one-off concern but not a bad one.

We could keep the historical curiosity of "pombe-embl" or go for descriptive accuracy; I don't mind.

**Comment by kimrutherford** [comment]
I looked into moving the files to SVN.

I noticed a bunch of "OLD" directories like:
  ftp://ftp.pombase.org/pombe/exports/OLD/

All together the "OLD" directories use the majority of the space in the pombe/ directory.

Would it be OK to move the "OLD" directories to the top level "Archived_directories" directory?:
  ftp://ftp.pombase.org/Archived_directories/

eg. move 
  ftp://ftp.pombase.org/pombe/exports/OLD/
to
  ftp://ftp.pombase.org/Archived_directories/old_exports/  (or some similar name)

Doing that would keep the pombe-embl SVN directory at a manageable size.

**Comment by ValWood** [comment]
I wonder how many people come back and look for older files/versions of. I suspect quite a lot (I know for the genome sequence they do).

They might be difficult to locate if we put then in the archive. I guess we could 
put the new location in the README though......

**Comment by kimrutherford** [comment]
> I guess we could put the new location in the README though

Or create a separate file "README-OLDER-VERSIONS" or something if we wanted to be very clear.

**Comment by mah11** [comment]
I'm not that fussed about where OLD files live. If they get moved to /Archived_directories/old_*/ I can add a note to that effect on the web pages that link to FTP locations (Downloads, Datasets, and/or their linked sub-pages).

**Comment by kimrutherford** [comment]
After all that I think it's better to leave the directory structure as is, with the OLD directories checked into SVN.  If we don't have them in SVN then copying old data to the OLD directories becomes a pain.  If the OLD dirs are in SVN then any of us can move things around with normal SVN commands.

So, I'm now moving this directory into SVN:
  ftp://ftp.pombase.org/pombe/

Your next "svn update" could take quite a while.

Once that's done I'll change the nightly load to update the pombe dir on the FTP site with the latest from SVN.

Thanks for all your input on this.

**Comment by mah11** [comment]
And thank you! Hooray, I can get on with adding files for the documents pages ...

**Comment by kimrutherford** [comment]
Sorry it's taken so long.  I haven't changed the nightly load to update the FTP automatically yet.  That's my first job tomorrow.

**Comment by kimrutherford** [comment]
I've just updated the FTP site manually with yesterday's SVN changes.  And I've changed the load script to do it nightly too.
