### ISSUE TITLE
add expression to compact view for phenotypes

### ISSUE THREAD

**Issue by mah11** [pombase/website#53]
show genes (multi-allele only), alleles and expression in compact view as in full view

**Comment by ValWood** [comment]
Another difference for expression from the current site. I think we want to show the expression level for WT alleles by default (in full view).  This should be in another old ticket from jira  somewhere so could link to this...

**Comment by ValWood** [comment]
Need to display "genotype" details first

**Comment by mah11** [comment]
Genotype details are displayed now (tho not in compact view; have to click "show details" and then click "genotype details).

**Comment by kimrutherford** [comment]
We don't have the expression or genes in the compact view either at the moment.  Could you give me an example of how it should look?

**Comment by Antonialock** [comment]
I just opened a new ticket for this because I thought it looked too bare :-) 
#163 

at a minimum I think we need to show the allele + expression level...there is space...
e.g.
yfg1-101 overexpression (or OP)
yfg1-101 knockdown (or KD)

the "detailed" view can show the genotype, any other expression levels (WT, unknown etc), conditions, and so on. I don't know how compact you want the compact view..

**Comment by ValWood** [comment]
yep...

**Comment by ValWood** [comment]
Is this ticket still valid?

**Comment by ValWood** [comment]
We don't appear to show expression in summary or full view for phenotypes?
Do we want this in summary or only in full? Seems odd to have it in  summary now?

**Comment by ValWood** [comment]
- [ ] Show genotype expression level only in full view (as current site)

(Note ability to filter out WT alleles will be come available with filtering options
https://github.com/pombase/website/issues/93
and
it will be come more obvious why wt alleles are present  when you can see details for a single section 
 https://github.com/pombase/website/issues/171 )

**Comment by ValWood** [comment]
did this get superseded by another decision? I can't quite remember. That said, I don't see expression in the "full view" either, so some action is required.

**Comment by ValWood** [comment]
I added discuss back here, but if anyone can help to get this one back in play, please do...

**Comment by mah11** [comment]
This ticket is one of the lot transferred from Jira, so it's based on the legacy gene page display.

For now, just decide whether you still want expression to show in the summary view. If yes, leave it open; if not, close it.

**Comment by ValWood** [comment]
Do we? I can't remember, but I though we decided. I remember we thought yes at one point because  of WT, but then I vaguely remember a discussion where we thought people would realise and it was only one click away, so I'm not sure now...

**Comment by ValWood** [comment]
don't need to show expression in sumamry view
