### ISSUE TITLE
chado database snapshots

### ISSUE THREAD

**Issue by mah11** [pombase/website#530]
We decided to keep monthly snapshots of Chado in the brave new daily-update world. Will they have their own directory, perhaps named "snapshots"?

Also, will the existing "releases" directory stay where it is? Fine if so; just need info.

I need to know for link(s) that will be on the downloads/chado-dumps page (successor to http://www.pombase.org/downloads/chado-database-dumps). I'll amend the text to say something about old-pb releases vs new-pb snapshots.

**Comment by ValWood** [comment]
soon after public release...

**Comment by ValWood** [comment]
- archive monthly snapshot
- chado dump
- decision, should all files for a month be in a single directory

Kim to decide which he prefers.

(could include symbolic links from old directories)

**Comment by ValWood** [comment]
Curators seem happy with eaither solution.

**Comment by kimrutherford** [comment]
I've made a releases directory containing all the older releases (from Ensembl days) and I've copied in a snapshot from the first of each month of 2018 and 2019:
  ftp://ftp.pombase.org/releases/

The snapshots for each month contain all the stuff from the build directories (like https://curation.pombase.org/dumps/latest_build/).  It's a bit untidy but it's easy.

**Comment by kimrutherford** [comment]
> ftp://ftp.pombase.org/releases/

Now also available by HTTP, which is faster: https://www.pombase.org/releases/

We could put either of those URLs in the documentation, they are the same place on the server.

**Comment by mah11** [comment]
I used HTTP for the main link, but also included a note saying FTP is available too.

Yay, we get to close an old ticket!

**Comment by kimrutherford** [comment]
> I used HTTP for the main link, but also included a note saying FTP is available too.

Good plan.  Thanks.

For completeness I've now added a copy of the website (in "Docker" image format) to each snapshot directory, going back to June 2018.  I don't expect this to be very useful but it does allow us to retrieve any gene for any of those dates if we needed to check something.
