### ISSUE TITLE
default list sorting

### ISSUE THREAD

**Issue by ValWood** [pombase/website#531]
By default, we always sort gene lists alphabetically by gene name.
When I look at a list I always immediately sort by product as  a list is always much easier to scan this way (much more biologically meaningful).

Would anybody object if we  defaulted to sort alphabetically by product?

**Comment by mah11** [comment]
I find myself looking for a specific gene in a list by name far more often than by product, so for me the current default is better. I don't know which way round is more common among users - but that should be what determines our defaults, not the preference of any one curator.

**Comment by ValWood** [comment]
well the gene organization is more common because that is what it presents.

Why would  you look for a single gene in the list (you could control F? or search for the gene and see if it is annotated to a specific term)
.
The list is more useful to provide a list of everything involved in a process.
All of these lists are much more "consumable" when ordered by product . All of the complexes  and functionally similar things group together.  Ordered by gene name the list is largely arbitrary.

It isn't just the preference of one curator because when I showed Antonia last night  she realised that its much   better to read  the list when organized by product (try it and see!).
And easy to reorganize (it makes it more obvious the gene ordering is also available when arranged by product too).

**Comment by mah11** [comment]
I have tried it, and my preference did not change.

We need to ask the community.

**Comment by kimrutherford** [comment]
If it helps we can make the sort order choice "sticky" so that if you sort by product once it sorts all gene list like that in future (until you change your mind a sort a list by gene).  I'm not super keen on interfaces that do that but I thought I should let you know that it's an option.

**Comment by ValWood** [comment]
I don't like sticky either, but thats not a bad idea for this.  Once you have switched once it's obvious that you can. I'm sure sorting by product is more generally useful if you are surveying a list....but I don't think we should do anything right away....

**Comment by kimrutherford** [comment]
OK, I won't add this to the V2 release milestone.  We can think it over.

We should probably have a larger discussion about what things should be configurable by website users.

**Comment by ValWood** [comment]
@Antonialock  could you ask Jurg's labnext time?

I much much prefer sorting by product, it groups things much more sensibly biologically which is great for long lists. 
If you are looking for a specific gene (which Im doing much less than consuming the entire list contents), I can switch (i prefer to read the list this way so much that I "control F" from here if I want a specific gene).

**Comment by kimrutherford** [comment]
I think this issue is superseded by #1534.
