### ISSUE TITLE
FAQ category label

### ISSUE THREAD

**Issue by mah11** [pombase/website#534]
In #336, Val proposes lumping these old-FAQ categories together: Querying/Searching, Datasets, Locating Genomic Regions, Sequence Retrieval. That's fine, but raises a question: What should the new category be called?

The text file with Val's suggested organization has "Querying/Finding/Retrieving data/datasets", but that sort of looks like a placeholder, and I think it would be better to use a much shorter label on the web pages, preferably without any slashes.

Any objection to just "Finding data"?

I'll use that for now, and it can be changed if @valwood or anyone else thinks up something equally brief but otherwise better.

**Comment by ValWood** [comment]
"finding data" sounds good to me.

**Comment by mah11** [comment]
Great. I'll run with that.
