### ISSUE TITLE
query links for FAQs

### ISSUE THREAD

**Issue by mah11** [pombase/website#535]
Several of the FAQs describe how to do searches for various things, and have links to the legacy advanced search with example parameters filled in. Example:

http://www.pombase.org/faqs/how-can-i-find-s-pombe-genes-associated-human-disease

It would be very nice indeed to be able to do the same in PomBase FAQ V2. Is that possible?

For now, I've commented out (or so I think & hope) the query links. Happy to go through and restore them when I learn what to put there. Not required for release.

**Comment by mah11** [comment]
seems related but not identical to #492

**Comment by kimrutherford** [comment]
I think this is covered by: https://github.com/pombase/website/issues/540#issuecomment-338554646

**Comment by mah11** [comment]
Yup. Now I just need to do it ...
