### ISSUE TITLE
trac error

### ISSUE THREAD

**Issue by ValWood** [pombase/website#536]
https://curation.pombase.org/pombase-trac

says
Authentication error. Please contact your administrator.
Error with navigation contributor "BrowserModule"
Can't synchronise with repository "(default)" (Unable to get database connection within 0 seconds. (OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"))). Look in the Trac log for more information.

&

Unable to get database connection within 0 seconds. (OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"))

**Comment by kimrutherford** [comment]
Sorry about that.  oliver0 was a bit low on memory so I turned off some services I thought weren't in use anymore.  I forgot that Trac needs MySQL.

Is it possible to move the remaining Trac wiki pages to GitHub or do they need to be private?

**Comment by ValWood** [comment]
We have nothing on trac that needs to be private.

**Comment by kimrutherford** [comment]
> We have nothing on trac that needs to be private.

Great.  I made a low priority issue about it:  https://github.com/pombase/curation/issues/1696
