### ISSUE TITLE
another FTP file move

### ISSUE THREAD

**Issue by mah11** [pombase/website#537]
pombe/genome_sequence_and_features/ has an empty /UTR/ subdirectory

meanwhile, there are two UTR data files (3UTR.fa.gz and 5UTR.fa.gz) sitting in a different subdirectory, /feature_sequences/

I don't have a strong preference whether the /UTR/ subdirectory disappears or moves to pombe/genome_sequence_and_features/feature_sequences/UTR/ and has the files in it, but the current arrangement is a bit nuts

**Comment by mah11** [comment]
OK, I've now got a slight preference for moving the UTR directory to be a subdirectory of feature_sequences, mainly so we can keep the UTR_README file in all its glory.

If the SVN plan happens I'll just do it myself.

**Comment by kimrutherford** [comment]
I've done that (I think).  Can you check and close the issue if it's OK?

**Comment by mah11** [comment]
Yep, that looks fine. thanks
