### ISSUE TITLE
resolving "substrates" for enzyme regulators

### ISSUE THREAD

**Issue by ValWood** [pombase/website#538]
On Monday I added.
![relation](https://user-images.githubusercontent.com/7359272/30897615-2146e28e-a34f-11e7-8dc1-273447217351.jpg)

This seems to have worked partially, because it has appeared in the esyN model as a directional arrow:
https://github.com/pombase/curation/issues/1699

but it does not appear on the gene pages as a Has_substrate.

I think this might be because, behind the scenes it is "regulates activity of" (although in Canto it displays as has_substrate, so I'm not sure.

Is this a configuration issue?
I can't think....

**Comment by kimrutherford** [comment]
The annotation is there now:
  http://pombase-dev.bioinformatics.nz/gene/SPAC23H3.13c

I'll update the preview soon.  There will be about a minute of downtime.

**Comment by ValWood** [comment]
yay, auto fixing.
