### ISSUE TITLE
provide links to human HGNC entries  in ortholog section

### ISSUE THREAD

**Issue by mah11** [pombase/website#54]
Add HGNC links to the human ortholog listings (ortholog section, obvs). Use the HGNC ID to link directly to a page.

E.g. for CDK1, the ID is HGNC:1722, and it fits into this URL format:
http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:1722

You can download a file with just the IDs and symbols via this page:
http://www.genenames.org/cgi-bin/download

**Comment by ValWood** [comment]
and to DIOPT 

linkout to DIOPT all species using PomBase ID of pombe gene
http://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPBC3E7.02c

**Comment by mah11** [comment]
this seems to have been done somewhere along the line (albeit with human gene symbols rather than HGNC:nnn IDs ... if it works, leave it).
