### ISSUE TITLE
Confusing links on "Priority unstudied genes" page (query builder)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#540]
There are some links in the paragraph at the top of this page that are confusing:
  http://preview.pombase.org/status/priority-unstudied-genes

When you click it goes to the query builder and the query is at the top of the history.  Should the link go to a results page instead?

The "Use these genes in query..." link on the term_genes page is confusing too if you don't know what to expect:
  http://preview.pombase.org/term_genes/GO:0000070

**Comment by ValWood** [comment]
> Should the link go to a results page instead?

Yes, good point!

**Comment by kimrutherford** [comment]
> Should the link go to a results page instead?

I've changed the links in the text on the "Priority unstudied genes" page to go directly to the results.  But it's a bit odd on the results page because the "Back" button doesn't go to the "Priority unstudied genes" page, it goes to the query builder.  What should we do?

> The "Use these genes in query..." link on the term_genes page is confusing too if you don't know what to expect

I find it confusing because it's not obvious that you have added a query to the history.  Maybe we should highlight the most recent addition to the history?  Any other ideas?

**Comment by ValWood** [comment]
It is a bit odd but not a show stopper.

let's discuss on call....

**Comment by kimrutherford** [comment]
Last week I talked with Midori about the general problem of linking to the query builder and to query results pages.  I've made some improvements so that we can link to either from the documentation.

The queries links on the priority unstudied genes page are defined in the "predefined_queries" section in the config file (pombe-embl/website/pombase_v2_config.json in SVN).  I think that's a good way to do it because all of the query definitions are then in one place and can be referred to by name.

There is an HTML like syntax for adding these inline links to predefined queries.  It's like this:

    <app-query-link [goToResults]="true" [linkText]="'List of unknown genes'"
        [predefinedQueryName]="'priority-unstudied-genes:unknown_genes'">
    </app-query-link>

Sorry it's so verbose.  That can all be on one line if that's tidier.

These links can appear anywhere in the Markdown documentation including in the panels on the front page.

If the goToResults attribute is set to "false" the link will go to the query builder instead.

The linkText attribute is optional.  If it's not specified the result count will be used as the link text.  That's what we do on the priority unstudied genes page.

The predefinedQueryName attribute is required and must match an entry in the "predefined_queries" section of the config file.

Unfortunately value of the linkText and predefinedQueryName attribute need to be doubly-quoted, there have to be two nested sets of matching quotes, one double-quote and one single quote, like:

    "'List of unknown genes'"

It's easy to forgot and the page won't load if it's forgotten.  :-/

Annoyingly, the goToResults attribute _shouldn't_ be doubly-quoted, so eg. `[goToResults]="false"`

**Comment by kimrutherford** [comment]
I've added the text from my comment to the wiki: https://github.com/pombase/website/wiki/Links-to-the-query-builder

> It is a bit odd but not a show stopper.
> let's discuss on call....

We should discuss what to do about the "Back" button.

**Comment by ValWood** [comment]
Is it possible that, if you do not come to the query builder results via a direct search, or your history, you see only a link to the “main query builder page”

Need to discuss Thurs

**Comment by ValWood** [comment]
Label the button "Advanced search"
Mouse over "this take you to the Query builder interface"

**Comment by kimrutherford** [comment]
> Label the button "Advanced search"

I've done that for tomorrow's update.

> Mouse over "this take you to the Query builder interface"

I used "Go to the Advanced Search interface" for the mouse over as it seemed more consistent.  Does that sound OK?

**Comment by ValWood** [comment]
ok to me...
