### ISSUE TITLE
Use colours to mark the introns and UTRs in the gene page sequence section

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#541]
This happens in PomBase V1 and at least one user has asked for it.

**Comment by mah11** [comment]
+1 from another user

**Comment by kimrutherford** [comment]
> +1 from another user

And another today.  I'll have a go at this in the next couple of days.

**Comment by ValWood** [comment]
+1

**Comment by ValWood** [comment]
and another...

**Comment by kimrutherford** [comment]
This is nearly done but not released yet.  We need to talk about colours.  I'm not happy with the current choice:

<img width="559" alt="screenshot 2017-11-02 21 08 25" src="https://user-images.githubusercontent.com/90474/32315715-24c76b92-c012-11e7-9cdb-edac7ca39781.png">
<img width="521" alt="screenshot 2017-11-02 21 08 08" src="https://user-images.githubusercontent.com/90474/32315727-2e52c1f2-c012-11e7-9da0-30c1989f0dad.png">

**Comment by ValWood** [comment]
i prefer the second one. How about replacing the "lilac" by yellow for introns. Garish, but this isn't about pretty its about clear demarkation of regions.

**Comment by kimrutherford** [comment]
Sorry, I should have made clear that the only difference between the screen shots is that in the first one has introns toggled on.  The introns are the italic bits.

**Comment by kimrutherford** [comment]
You can see it in action here: http://pombase-dev.bioinformatics.nz/gene/SPCC24B10.14c

**Comment by kimrutherford** [comment]
I've remove the bold from the exon and made the intron background a bit brighter.

As an experiment if you move your mouse pointer over part of the sequence (like a UTR) if temporarily makes that bit bold to highlight it.

The changes will be live in the morning (hopefully).

**Comment by kimrutherford** [comment]
> The changes will be live in the morning (hopefully).

The change is in pombase-dev now: http://pombase-dev.bioinformatics.nz/gene/SPBC29A3.14c

**Comment by ValWood** [comment]
very nice.
I like the way the text changes for the flanking region depending what is selected.

**Comment by ValWood** [comment]
changes seem to be live?

**Comment by ValWood** [comment]
ignore, that's what you said...

**Comment by kimrutherford** [comment]
Are there any other tweaks or should I close this?

**Comment by Antonialock** [comment]
It looks great to me! I can announce

**Comment by ValWood** [comment]
>Are there any other tweaks or should I close this?

moon on a stick:
It would be really great if,

when you did this:
As an experiment if you move your mouse pointer over part of the sequence (like a UTR) if temporarily makes that bit bold to highlight it.

a little pop up said 
24-37
etc
;)

I hate counting residues...

**Comment by Antonialock** [comment]
I would prefer if the pop-up gave you the number of the residue you are mousing over (not necessarily the start/end of an exon/intron

**Comment by Antonialock** [comment]
new ticket..

**Comment by ValWood** [comment]
I meant number of the residue, but it would be a range if you selected a block....
