### ISSUE TITLE
publication pages missing gene expression data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#543]
I'm sure there is gene expression stuff for this paper
(added in artemis)
http://preview.pombase.org/reference/PMID:26132084

(don't need to do this to go live)

**Comment by kimrutherford** [comment]
> added in artemis

Do you mean in the contig files?  I can't see any annotations for PMID:26132084 in those files.

**Comment by mah11** [comment]
and where there is gene expression annotation in the contig files, it shows up on publication pages.

e.g. http://preview.pombase.org/reference/PMID:22840777 , http://preview.pombase.org/reference/PMID:24003116

**Comment by ValWood** [comment]
yep wrong paper.
