### ISSUE TITLE
Front page text update for resource spotlight 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#544]
Research spotlight: Gould lab (hyperlink lab to https://medschool.vanderbilt.edu/gould-lab/)
Super-resolution microscopy to determine the spatial relationship of contractile ring proteins at nanoscale resolution   published in eLife  link to https://elifesciences.org/articles/28865

video https://elifesciences.org/articles/28865#video1 (downloadable MP4 is it possible to clip the first bit?) I’m tracking down how we need to do the image attribution

**Comment by ValWood** [comment]
I forgot where to look!

**Comment by ValWood** [comment]
Steve thinks we should stick with the wordcloud for CC feed. I think it is a better image. I still want to make a version with a coloured background as discussed today. 

I will use the graph one for focus on resource metrics page later.

**Comment by kimrutherford** [comment]
> downloadable MP4 is it possible to clip the first bit?

The video is clipped and ready to put in the front page once we decide what to do about attribution.

**Comment by ValWood** [comment]
We can put on the front page already. The picture is there  already and we don't link to the attribution yet ;)

From eLife:

PomBase can display it in their own website, provided that attribution is properly acknowledged. For that purpose, please ask them to include a note along these lines:

"Figure from McDonald et al, 2017. Nanoscale architecture of the Schizosaccharomyces pombe contractile ring. eLife. © 2017, McDonald et al. Available at https://elifesciences.org/articles/28865 under the terms of the Creative Commons Attribution License, permitting unrestricted use and redistribution provided that the original author and source are credited."

Please note that a link to the Creative Commons Attribution License must be included, as in the text above.


Because we supply the info about the source of the paper  (albeit worded slightly differently the primary image source is obvious)
I think we can shorten this  to:

Research spotlight: McDonald et al, 2017
Super-resolution microscopy to determine the spatial relationship of contractile ring proteins at nanoscale resolution published in eLife (link to https://elifesciences.org/articles/28865)
Image Attribution (link to https://creativecommons.org/licenses/by/2.0/legalcode)

**Comment by ValWood** [comment]
I hope to make the annotation  reflect the results too, waiting for new GO terms:
https://github.com/geneontology/go-ontology/issues/14337

**Comment by mah11** [comment]
I would like to rearrange the text to put the biological point first. If there are no objections I'll change it in the yaml file to:

Contractile ring structure at nanoscale resolution. Image from [eLife 2017;6:e28865](https://elifesciences.org/articles/28865), used under [CC-BY](https://creativecommons.org/licenses/by/4.0/) license terms.

(This also adds a bit to show which CC license applies, which I think will help us play nice with the legal bods.)

**Comment by ValWood** [comment]
better.

**Comment by mah11** [comment]
glad you like it :)
I've committed it in the file in svn
