### ISSUE TITLE
make download pages prettier

### ISSUE THREAD

**Issue by ValWood** [pombase/website#548]
everything seems to be present.... but the pages  are not very pretty....

**Comment by ValWood** [comment]
actually they are not that bad.

This one maybe needs a bit of space before annotation datasets?

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/datasets
Gene names and Ids gets a bit lost.

**Comment by mah11** [comment]
We're gonna need something a little more specific than "prettier" to guide any changes ...

**Comment by mah11** [comment]
For the moment, I've tried adding some horizontal rules between the headed sections. See what you think when it's visible (on the dev site tomorrow?).

**Comment by mah11** [comment]
well, the lines are pretty faint, but they do add a little bit of vertical space, so I think it helps a bit
