### ISSUE TITLE
default order for gene names in extensions on (gene pages, term pages, publication pages)

### ISSUE THREAD

**Issue by mah11** [pombase/website#55]
Where gene names or IDs appear in annotation extensions (e.g. activity substrates), the default should be to order by gene standard name. If possible, list named genes first, then systematic IDs for genes without standard names.

**Comment by ValWood** [comment]
I  think we might want to do something more.  I thing as numbers get larger rit might be better to order   by similar  involved in extension:

i.e

has substrate bbb4, involved in positive regulation of septation initiation signaling
has substrate ddd4, involved in positive regulation of septation initiation signaling
has substrate eee9, involved in negative regulation of mitotic spindle elongation
has substrate ddd4, involved in positive regulation of mitotic spindle elongation
has substrate xxx4, involved in positive regulation of mitotic spindle elongation
has substrate ffff2, involved in negative regulation of conjugation with cellular fusion

perhaps?

**Comment by ValWood** [comment]
I think we could have a configuration for the most biologically meaningful default view.

I have a feeling that if there are lots of "during" annotations, this is the best way to order,
followed by part of/involved_in, and then   substrate. 
This needs extending and will differ  for different ontologies....

**Comment by ValWood** [comment]
hmm, this is about this
https://github.com/pombase/website/issues/186

It would be super-cool for interpretation
If the default ordering was by phase extension, so that things which occur together group together


![temp](https://cloud.githubusercontent.com/assets/7359272/23331276/85cc40c0-fb5a-11e6-972c-48b1c49dabb3.jpg)


So 
mitotic G1 phase
mitotic S phase
mitotic G2 phase
mitotic M phase
- mitotic prophase
- mitotic prometaphase
- mitotic metaphase
- mitotic anaphase
- mitotic telophase
no phase
(could be expanded for meiosis etc)


This way, where there a lot of annotation, things which occur simultaneously would group together which would make much more sense biologically.

**Comment by ValWood** [comment]
Super clever ordering would defaukt display by
1)  during (order specified in config list)
  2) alphabetically by involved in
    3) gene name
(so if you haven't got any 1. or 2. gene name would be the default anyway.....)

**Comment by ValWood** [comment]
During discussion:
Other suggestions included subheadings for phases, phase column

**Comment by kimrutherford** [comment]
Should I go ahead and change the ordering to this:

> 1)  during (order specified in config list)
> 2) alphabetically by involved in
> 3) gene name (so if you haven't got any 1. or 2. gene name would be the default anyway.....

Or does this need discussion first?:

> Other suggestions included subheadings for phases, phase column

**Comment by ValWood** [comment]
I think this ordering makes sense, but if anyone else has alternative suggestions we can discuss...

**Comment by kimrutherford** [comment]
> the default should be to order by gene standard name

That's done.  Val suggestion for ordering by during, involved in then gene name isn't done yet.

**Comment by kimrutherford** [comment]
> 1. during (order specified in config list)
> 2. alphabetically by involved in
> 3. gene name

Is that just for GO and modifications?  What should the order be for phenotypes?

**Comment by ValWood** [comment]
alphabetically by gene name (affecting) I think (  is anything else except  penetrance and expressivity?)

**Comment by kimrutherford** [comment]
Sorry, I should have read this more carefully.  Which config list do you mean when you say?:

> during (order specified in config list)

**Comment by Antonialock** [comment]
I think Val means this list, typed out above

mitotic G1 phase
mitotic S phase
mitotic G2 phase
mitotic M phase

    mitotic prophase
    mitotic prometaphase
    mitotic metaphase
    mitotic anaphase
    mitotic telophase
    no phase
    (could be expanded for meiosis etc)

**Comment by kimrutherford** [comment]
Thanks Antonia.  That makes sense.

**Comment by ValWood** [comment]
yes, so we don't have an actual config file for this yet...

**Comment by ValWood** [comment]
I think what we need to do for ordering is done.
This would benefit from a new shiny ticket  for afterwards. There might be other related tickets hanging around too!

**Comment by ValWood** [comment]
and...
If a GP has an substrate +involved_in it should come above anything which has substrate+ phase (only)...more information.

**Comment by mah11** [comment]
this must be out of date ...
