### ISSUE TITLE
include WT logo

### ISSUE THREAD

**Issue by ValWood** [pombase/website#550]
Thumbs up from Steve.

He suggested 
About PomBase" page, we should include the Wellcome Trust's logo

I wonder if we should also put at the bottom of the front page like we do on Canto?
https://curation.pombase.org/pombe/
(we will need to update the Canto one)

**Comment by kimrutherford** [comment]
> About PomBase" page, we should include the Wellcome Trust's logo

Good idea!  I'll do that.  Should we have Cambridge and UCL too?  Or just highlight Wellcome because they provide funding?

> I wonder if we should also put at the bottom of the front page like we do on Canto?

I can try it to see how it fits.

> we will need to update the Canto one

I didn't realise they had changed the logo.  I'm not a fan.  :-(

**Comment by ValWood** [comment]
> I'm not a fan. :-(

nope, that's the general  opinion

**Comment by mah11** [comment]
I guess that makes me a general too ;)

ugh, why did they do that??

**Comment by kimrutherford** [comment]
I've added the logo at the bottom of the About page.  Is that prominent enough?

**Comment by ValWood** [comment]
I think so ;)
