### ISSUE TITLE
store, and make accessible  front page items in "archive"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#552]
Maybe a small "archive" link at the bottom of  1st and last panel?

**Comment by kimrutherford** [comment]
As a start, I've added an "is_current" flag to each panel configuration.

**Comment by kimrutherford** [comment]
I've added archive pages and an "Archive ..." link on the third panel.  The link for the first panel is there, but commented out as there is only one Spotlight item far.  It will be live in the main site soon.

**Comment by ValWood** [comment]
nice.

**Comment by kimrutherford** [comment]
I think the archive page(s) will look good once there are a few more items.
