### ISSUE TITLE
Fission Yeast GO slim terms

### ISSUE THREAD

**Issue by ValWood** [pombase/website#553]
http://preview.pombase.org/browse-curation/fission-yeast-go-slim-terms

Fission Yeast GO slim terms

could the header be

Fission yeast GO lim annotations?
or
Fission yeast GO slim terms and annotations?

(Its more about the annotation than the terms....)

**Comment by mah11** [comment]
I have changed it to just "Fission yeast GO slim" because titles can be brief, especially when the rest of the page makes its contents clear.
