### ISSUE TITLE
phenotype queries failing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#555]
preview and -dev

**Comment by kimrutherford** [comment]
Do new queries fail or just those in your history?  I temporarily broke things at one point and invalid queries were being added to the history.

**Comment by ValWood** [comment]
reran, still getting zero on preview
![rerean](https://user-images.githubusercontent.com/7359272/31555343-98951176-b038-11e7-8763-d84c166ded00.jpg)

**Comment by ValWood** [comment]
Ah I see what you man. If I re run from the interface rather than reloading from the history, they work

**Comment by kimrutherford** [comment]
> Ah I see what you man. If I re run from the interface rather than reloading from the history, they work

Sorry about that.  Is it a hassle to re-run them and delete the ones from your history?

**Comment by ValWood** [comment]
No I can do that when i need them, no problem.
