### ISSUE TITLE
new rotation "data mining"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#556]
I added another "Pombase spotlight" to the images folder.
This is the accompanying draft text:

Title: Explore PomBase: Data mining
Text: Use the <link: Advanced Search> to construct complex queries (GO, phenotypes, taxonomic distribution, domain, chromosomal location). 

Link http://preview.pombase.org/query

**Comment by kimrutherford** [comment]
I've added that section.  It will be in the preview soon.
