### ISSUE TITLE
PomBase 2017 infographic?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#557]
After the front page redesign there is no link to the excellent infographic.  Should we have a link to it?  If so where?

**Comment by ValWood** [comment]
We should have somewhere for talks, posters and publications linked from the menu I guess. I think we discussed this but we didn't decide what to do.

Suggestions, how, where...

**Comment by ValWood** [comment]
I use slideshare
https://www.slideshare.net/ValerieWood/presentations
and we could have a PomBase version?

Or, these links are "enbeddable"

**Comment by kimrutherford** [comment]
> and we could have a PomBase version?

If we have a page of presentation and posters I think it makes sense to have a link to SlideShare and a download link beside for each presentation.

> Or, these links are "embeddable"

Looks like that's possible:
  https://en.support.wordpress.com/slideshare/#embedding-a-slideshow

**Comment by mah11** [comment]
I have a big long list of files, including the infographic, to add to the Documents download page (http://pombase-dev.bioinformatics.nz/documents) or to one of the meeting-specific page linked there. We haven't discussed changing the organization of that page at all so far.

Assuming we don't reorganize, the infographic can be linked to the main Documents page as well as the pombe 2017 page.

What I'm waiting for is for Kim to decide whether to go ahead with the plan to maintain FTP-destined files in SVN (https://github.com/pombase/website/issues/529#issuecomment-332400879). If we do that, it'll be straightforward for me to add files there and link them up.

In addition to posters, some of the presentations are also PDFs not in SlideShare, but I don't think it'll be a problem if some presentations only have download links.
