### ISSUE TITLE
display binds relation for RNA binding + IPI evidence

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#558]
Like with the protein binding annotations we want to display the "binds" relationship with RNA binding e.g. see
http://www.pombase.org/spombe/result/SPCC736.12c
vs http://preview.pombase.org/gene/SPCC736.12c

**Comment by kimrutherford** [comment]
Do we need this for the release?

**Comment by ValWood** [comment]
nope, can be after...

**Comment by kimrutherford** [comment]
Unfortunately the like to the old site goes to the new site now.  Could you explain what I need to do?

**Comment by mah11** [comment]
I _think_ we just need to adjust the website configuration so it matches the Canto config for the terms in question.

Canto does:

    GO:0000988      is_a    has_substrate   ProteinID       binds           0,1     user
    GO:0001653      is_a    has_substrate   ProteinID       binds ligand            0,1     user
    GO:0003676      is_a    occurs_at       SO:0001411      binds region            0,1     user
    GO:0003682      is_a    occurs_at       SO:0001411      binds chromatin region          0,1     user

whereas pombase_v2_config.json only does:

    {
      "rel_name": "occurs_at",
      "display_name": "at"
    },

I can try it if you're willing to risk me screwing it up with typos ;)

**Comment by ValWood** [comment]
There is some code which treats  
protein  biding IPI with as a "binds" extension.

We need to do the same thing with "RNA binding" terms

**Comment by ValWood** [comment]
needs checking

**Comment by mah11** [comment]
If the "IPI with gene" gets displayed as "binds gene", we can leave the occurs_at configuration unchanged.

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/gene/SPCC736.12c
;)

**Comment by Antonialock** [comment]
Also include children of RNA binding @kimrutherford

**Comment by kimrutherford** [comment]
> Also include children of RNA binding

I've fixed that now, I think.

**Comment by kimrutherford** [comment]
> I've fixed that now, I think.

Sorry, I meant that the fix is in today's update.  Does it look OK?: https://www.pombase.org/gene/SPCC736.12c

**Comment by Antonialock** [comment]
yep!
