### ISSUE TITLE
Canto is offline - oliver0 is dead

### ISSUE THREAD

**Issue by ValWood** [pombase/website#559]
curate a paper
https://curation.pombase.org/pombe/

is giving an error?

**Comment by ValWood** [comment]
Oh canto is "down"....
oliver zero?

**Comment by kimrutherford** [comment]
> oliver zero?

Unfortunately, yes.  Other machines at System Biology are OK so I think it's just oliver0.

When oliver0 has problems it's always at the weekend.  :-(

**Comment by mah11** [comment]
closing because it's back

... but how does it know when it's the weekend, so it can fail then?

**Comment by ValWood** [comment]
trying to figure that one out.....
