### ISSUE TITLE
phenotype queries failing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#560]
on www & dev

**Comment by kimrutherford** [comment]
What query is failing?  I just did this one on both servers and got 38 results:

    abnormal cell wall (FYPO:0002946) [single allele genotypes]

**Comment by ValWood** [comment]
Sorry, I forgot, I need to physically rerun, not just "reload".

val

**Comment by ValWood** [comment]
But what is odd, is I think I had already re-run these queries but they had gone back to zero again. I could be wrong so will close and re-open if so later one checker properly.

**Comment by kimrutherford** [comment]
Yep, unfortunately you'll need to manually delete the broken queries.

**Comment by kimrutherford** [comment]
The broken ones in the history list are those that don't have the expression after them.  So this is fine:

    abnormal cell wall (FYPO:0002946) [single allele genotypes]

but this is broken:

    abnormal cell wall (FYPO:0002946)

If you have any that have the expression in square brackets and zero results that might be a bug (or myabe that query really does have no results).

**Comment by ValWood** [comment]
I ran a query yesterday (preview)

1 | decreased subtelomeric chromatin knob formation (FYPO:0005528) [single allele genotypes]

and today it had gone back to zero?

I  had to re run again?

**Comment by kimrutherford** [comment]
> and today it had gone back to zero?

Drat!  It does the same for me when I reload.  I'll fix it.

**Comment by kimrutherford** [comment]
I think that's fixed now in the preview.

**Comment by ValWood** [comment]
yep all yesterdays still have numbers ;)
