### ISSUE TITLE
news archive menu links don't work

### ISSUE THREAD

**Issue by mah11** [pombase/website#561]
On the news archive page, if I click a link in the left-hand menu, it goes to the PomBase home page instead of the selected news entry (although the news item URL shows in the location bar).

example: http://pombase-dev.bioinformatics.nz/#our-model-organism-database-commentary

tested in Chrome, Firefox and Safari (found whilst testing generally in the latter but turns out not to be browser-specific)

**Comment by kimrutherford** [comment]
I've fixed the news page links.  It will be in the preview soon.
