### ISSUE TITLE
query builder does not recognise reciprocal queries as identical

### ISSUE THREAD

**Issue by ValWood** [pombase/website#563]
like:

![identical](https://user-images.githubusercontent.com/7359272/31771312-8e16382a-b4d3-11e7-8c34-1761ad5d5ab0.jpg)

**Comment by kimrutherford** [comment]
The easiest fix is to put the bits of each AND or OR in alphabetical order in the query description.  The description is what the history code uses to find duplicates.  Would that be an OK fix?

**Comment by ValWood** [comment]
I think so...
Anyone object?
We could also always  put certain "types" first maybe?

**Comment by kimrutherford** [comment]
> We could also always put certain "types" first maybe?

Definitely.  Alphabetical is the quick fix but as long as we have a consistent order it would be fine.

I've changed the code to put things in alphabetical order so you can try it.  I'll update the preview with that change soon.

**Comment by Antonialock** [comment]
I don't mind however they are ordered.

**Comment by mah11** [comment]
Alphabetical makes sense to me. I don't think there's much point in trying to come up with any different order, because which "type" is most important can depend on the specific query and why someone is doing it.

**Comment by kimrutherford** [comment]
OK, I'll close one.  If we need to change the order later, please open a new issue.
