### ISSUE TITLE
ftp download files, mapping files

### ISSUE THREAD

**Issue by ValWood** [pombase/website#564]
mapping files
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Mappings/
- [x]  sysID2product.tsv
- [x]  sysID2product.rna.tsv  (current version contins proten coding psudos!)
- [x]  allNames.tsv

Kim @kimrutherford , you wanted feedback on these?

The RNA one is not critical for release

**Comment by kimrutherford** [comment]
Exclude pseudogenes from all three files.  But create a pseudogeneIDs.tsv.

**Comment by kimrutherford** [comment]
All those files, including pseudogeneIDs.tsv, now get written nightly to ftp://ftp.pombase.org/nightly_update/misc/ starting tonight hopefully.

I'll check it's OK in the morning.

**Comment by mah11** [comment]
I've copied pseudogeneIDs.tsv over to the svn ftp department, and added a link to the downloads/names-and-identifiers web page.
