### ISSUE TITLE
gff files

### ISSUE THREAD

**Issue by ValWood** [pombase/website#567]
- [ ]  gff    (We need to list the features required in the gff file)
needs to include

**Comment by ValWood** [comment]
These appear to be the gff feature types

4592 CDS
 591 biological_region
5477 exon
2204 five_prime_UTR
2335 gene
 670 ncRNA_gene
  16 pseudogene
  12 rRNA
  12 rRNA_gene
   2 snRNA
   2 snRNA_gene
  33 snoRNA
  33 snoRNA_gene
  56 tRNA_gene
2170 three_prime_UTR
3061 transcript


- introns are  currently exported as "biological region, not sure why?
- we should also include LTRs
- Use of gene seems slightly inconsistent...
I'm not sure why there would be
4592 CDS and 2335 gene

_ I'm not even sure if we need "gene"  "transcript" or "exon" but I'm not really sure how people are using these....

We could start with a more minimal file and see if folks complain?

**Comment by kimrutherford** [comment]
This is on the V2 milestone, but it's not done yet.

> 4592 CDS and 2335 gene

That's very odd.  It also makes using the GFFs file challenging because GFF readers often need the gene features.

> 5477 exon

That seems low?

**Comment by ValWood** [comment]
That seems low?  
yes it does....!

**Comment by mah11** [comment]
Another question about the GFF3 files, this time just about the names: There's one called schizosaccharomyces_pombe.chr.gff3.gz, but I had to look in it to see that it appears to cover the whole genome. Can we rename it to schizosaccharomyces_pombe.genome.gff3.gz?

**Comment by kimrutherford** [comment]
> Can we rename it to schizosaccharomyces_pombe.genome.gff3.gz?

Sounds good to me.

**Comment by mah11** [comment]
OK, I've renamed the 'chr' file to 'genome', and 'MT' to 'mitochondrial'.

**Comment by kimrutherford** [comment]
We'll need the GFF files for loading JBrowse, so I've changed this to high priority

See: #443 

> introns are currently exported as "biological region, not sure why?

I suspect the reason is just "Ensembl".  :-)
There is definitely a SO term for intron so that can't be the reason.

**Comment by kimrutherford** [comment]
I've added enough of the GFF writer code to get a file out that JBrowse approves of.  It only writes the genes, mRNA and exons for now.  Things missing:

 - non-gene features
 - non-coding genes
 - dbxrefs and other qualifiers
 - introns and UTRs
 - probably other stuff

**Comment by kimrutherford** [comment]
> These appear to be the gff feature types
> 4592 CDS
> ...

In the new GFF files we have 12140 CDS, which seems right as we have a CDS line for each exon.

>    introns are currently exported as "biological region, not sure why?

In the new file we have 5355 introns instead.

>    we should also include LTRs

They're included in the new files.
 
>   Use of gene seems slightly inconsistent...
>    I'm not sure why there would be
 >   4592 CDS and 2335 gene

In the new file we have 12140 CDS and 7000 gene.

> _ I'm not even sure if we need "gene" "transcript" or "exon" but I'm not really sure how people are using these....

JBrowse is happy with "gene", "CDS" and the UTRs and introns.

> We could start with a more minimal file and see if folks complain?

I think so.  Everyone puts different features in the GFF files anyway.

**Comment by ValWood** [comment]
@kimrutherford What else is still to do for this one?

**Comment by kimrutherford** [comment]
> What else is still to do for this one?

- dbxrefs and other qualifiers
- chromosome features

**Comment by ValWood** [comment]
Are the gff files currently updated on the ftp site ...it's difficult to know because the date file modified doesn't change (presumably because this is a link).

If so, we can add low priority to this one for now.

**Comment by kimrutherford** [comment]
> Are the gff files currently updated on the ftp site ...it's difficult to know because the date file modified
> doesn't change (presumably because this is a link).

Yep, they're updated each night:
ftp://ftp.pombase.org/pombe/genome_sequence_and_features/gff3/

**Comment by ValWood** [comment]
What is still to do here? If any outstanding maybe we should close this and  open new tickets?

**Comment by kimrutherford** [comment]
We just have these things to add:

 - dbxrefs and other qualifiers
 - chromosome features

I'd be happy to close this issue and wait for someone to ask for those things.
