### ISSUE TITLE
more fasta files - UTRs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#568]
can be done later

UTR 
- [x]  5'  (non urgent)
- [x]  3'  (non urgent)

**Comment by ValWood** [comment]
If this is fiddly you can add the label "low priority" and it can be done after the initial browser installation.

We can bump up if anyone asks but the current files should be good enough (since they rarely change)

**Comment by ValWood** [comment]
Actually will put as "low priority" and you can remove if you would rather get it out of the way while you are doing the output files...

**Comment by kimrutherford** [comment]
The UTR fasta files are now written out each night:
ftp://ftp.pombase.org/nightly_update/fasta/feature_sequences/
