### ISSUE TITLE
protein data files

### ISSUE THREAD

**Issue by mah11** [pombase/website#569]
The files in the ftp Protein_data directory didn't get transferred from #355 to a new ticket yesterday, but will need to be generated. They probably don't need to be updated frequently.

- [x] PeptideStats.tsv - also change to report mass in kDa (instead of Da) (Requested late 2014, done once, backslid thereafter. Not gonna miss that cycle a bit.)
- [x] ProteinFeatures.tsv
- [x] aa_composition.tsv

Note that I have also corrected the ProteinFeatures.tsv file so the source databases are listed using correct case, and corrected a couple of tool names to the corresponding database, consistent with the column header. Updates should follow suit.

 blastprodom -> ProDom
 pfscan -> Prosite
 scanprosite -> Prosite

For me: update README when PeptideStats.tsv has mass in kDa.

**Comment by ValWood** [comment]
These files should be easy/quick to generate since the data is already on the gene pages?
Let me know if you have any questions.... If it is more difficult than I envisage we can discuss Thurs...

**Comment by ValWood** [comment]
Will remove discuss label, but add back if anything to discuss....not sure :)

**Comment by kimrutherford** [comment]
The Chado load script should now write out a PeptideStats.tsv file each night which will appear here if everything works out:
  ftp://ftp.pombase.org/nightly_update/misc/

I haven't copied the new file over the top of the existing PeptideStats.tsv yet.

> report mass in kDa

It's in kDa in the new file.

**Comment by kimrutherford** [comment]
I've added code to generate ProteinFeatures.tsv each night.  I think the database names should be OK now but let me know if you spot any mistakes.

I've added a new item to the configuration to catch odd database names and map them to the actual name.  So "MOBIDBLT" gets written/displayed as "MobiDB".  The new config option is called `extra_database_aliases` in `pombe-embl/website/pombase_v2_config.json`.  There a little bit of documentation about it here:
https://github.com/pombase/website/wiki/Config-file

**Comment by kimrutherford** [comment]
It now writes the `aa_composition.tsv` file nightly too.  The new file should appear in tonight's load in ftp://ftp.pombase.org/nightly_update/misc/

**Comment by ValWood** [comment]
Great stuff!

**Comment by ValWood** [comment]
So does that get copied to ftp site automatically?

**Comment by kimrutherford** [comment]
> So does that get copied to ftp site automatically?

All of the files that are re-generated every night are copied to this directory on the FTP site:
  ftp://ftp.pombase.org/nightly_update/

The documentation points to the older files under this directory: ftp://ftp.pombase.org/pombe/

Once we're happy with the nightly files we can either copy or symbolic link them to the documented places.
