### ISSUE TITLE
include definition with results of ontology term/ID search

### ISSUE THREAD

**Issue by mah11** [pombase/website#57]
For results of a search for an ontology term or ID, add the term definition to matter above table of matching genes.

**Comment by ValWood** [comment]
transferred to
https://github.com/pombase/website/issues/99

**Comment by kimrutherford** [comment]
> For results of a search for an ontology term or ID, add the term definition to matter above table
> of matching genes.

I guess we should only do that only when the term or ID isn't part of complex query with ANDs, ORs or NOTs?

**Comment by ValWood** [comment]
Maybe we need to discuss this, I would be happy to see the definition when I search (to confirm I have the right thing), but only the term label on the results?

**Comment by kimrutherford** [comment]
Slightly related to this: I've just change the query builder to show the term definition once you pick a term from the autocomplete.  Is that I good plan?

http://pombase2.bioinformatics.nz/query

**Comment by ValWood** [comment]
I like it that way.... anyone else?

**Comment by Antonialock** [comment]
Agreed
-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
I'm happy. New ticket if changes wanted to this.
