### ISSUE TITLE
don't always know whether a mutant is AA or NT?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#570]
I spotted this on dbl2 page?
![aa or nt dbl2](https://user-images.githubusercontent.com/7359272/31840338-cf4e4e54-b5dc-11e7-9d61-bab716fa9d26.jpg)

**Comment by kimrutherford** [comment]
Should I go ahead and add "nt" or "aa" after the residue range based on the allele type?

**Comment by ValWood** [comment]
I'm confused as I thought we already did....
Maybe not...Let me check old site....

**Comment by ValWood** [comment]
hmm, we don't (maybe we only do this in Canto?). We should.... otherwise unclear....

**Comment by mah11** [comment]
I think it's in a mouseover on old pombase

**Comment by ValWood** [comment]
Do with mouseover?

**Comment by Antonialock** [comment]
I think it would be clearer with e.g. 
Δnt_321-430
Δaa_321-430

**Comment by Antonialock** [comment]
(I don't think details that are essential to understand the allele should be hidden)

**Comment by ValWood** [comment]
I don't like the underscore...
aaΔ321-430  ?

**Comment by Antonialock** [comment]
sure

**Comment by ValWood** [comment]
321-430nt

**Comment by Antonialock** [comment]
321-430 Δaa ?

**Comment by ValWood** [comment]
nda4-108 (A50C aa)

**Comment by ValWood** [comment]
nda4-108 (A50Caa)

**Comment by ValWood** [comment]
OK!!!!!!

**Comment by kimrutherford** [comment]
There are some special cases to handle.

Most of the amino acid partial deletion alleles have a description in Chado something like `123-456`, but there is an occasional odd one like "C-terminal protein deleted from transcript" (from nup189c-Δ).

For the amino acid partial deletions there is a lot of variety:

    1066-1080
    -220--33
    -110 - -54
    -35 to -27  
    +84 to +135
    106-144,347-440
    deletion of second intron (1397-2095)
    N-terminal protein deleted from transcript

It looks like it would be OK if we only added Δaa or Δnt only if the description ends in a digit.  I'll try that and we can see how it looks.

**Comment by kimrutherford** [comment]
That change is in pombase-dev now and will be in the main site in an hour or two.  Let me know if you spot any problems.

**Comment by ValWood** [comment]
nup189c-Δ sounds OK but it is the description that's a bit odd (deleted from transcript?). This could be done with a standard description of nucleotides?

and nup189-CΔ (upper case C usually used for N and C term?)

**Comment by ValWood** [comment]
These are standard
1066-1080
106-144,347-440
-220--33  (although maybe we should introduce a space here to make more legible?) @Antonialock @mah11 

These are non-standard:
-35 to -27  
+84 to +135
-110 - -54 
deletion of second intron (1397-2095)

Some could be in the name if critical/useful (i.e. genex Δintron2)
but the "standard descriptions" should be standardized wherever possible so that they are "computable" over. All of the  non standard descriptions should be type "other"

Occasionally I have used a non standard description (I think) if the  residues are not reported in the paper. In this case I mail the author. I am still waiting back for some....

We should report *any* non standard descriptions in the logs and fix....




Will reopen for now to remind us to ticket (may already be open ticket)

**Comment by ValWood** [comment]
> That change is in pombase-dev now and will be in the main site in an hour or two. Let me know if you spot any problems.

Looks good for this ticket though...

**Comment by Antonialock** [comment]
I think we should use different fonts (bold/regular) to distinguish between a dash that mean "to" from a dash that means "minus"
e.g.
-45**-**-50

**Comment by ValWood** [comment]
that would work.

**Comment by mah11** [comment]
Returning to this comment from Kim:

> For the amino acid partial deletions there is a lot of variety:
> 
>     1066-1080
>     -220--33
>     -110 - -54
>     -35 to -27  
>     +84 to +135

.. snip

That's a bit worrying. There shouldn't be any _amino acid_ descriptions with negative numbers (minus signs); that's only meant to be used for nucleotide positions upstream of the start codon for a protein-coding gene (or upstream of the 5' end of the mature product for an ncRNA).

The plus signs are also completely redundant for amino acid positions (Val noted they're not our standard).

**Comment by ValWood** [comment]
I think that  should have been "any partial deletion"....

Kim are there many that do not match our standard?

**Comment by kimrutherford** [comment]
> There shouldn't be any amino acid descriptions with negative numbers

Sorry!  That was a typo.  The long list with a lot of variety was nucleotide partial deletions.

> Kim are there many that do not match our standard?

Not many.  There are only 88 nucleotide partial deletions in total.

Here's the list.  Some of these are just whitespace differences like "240 -242" which we could fix when loading.  There are a few with two ranges like "96-141,514-596" which I'm guessing are OK so I haven't included those.

     SPCC338.08:allele-56    | ctp1-5                     | frameshift at W288 truncating at position 292
     SPBC32H8.11:allele-13   | mei4delta(828-1554nt)::GFP | C-terminal truncation (828-1554)
     SPAC5D6.01:allele-2     | rps2202-idelta             | deletion of intron (-156--10)
     SPBC11B10.09:allele-54  | cdc2-DL50                  | 240 -242
     SPAC1486.05:allele-3    | nup189n-delta              | N-terminal protein deleted from transcript
     SPBC3D6.03c:allele-8    | trz2-1/pJK148-delta-HomolD | -35 to -27
     SPNCRNA.98:allele-25    |                            | A149
     SPBC3D6.03c:allele-4    | pJY9                       | -110 - -54
     SPBC3D6.15:allele-2     | pJY30                      | -45 - -38
     SPBC3D6.03c:allele-3    | trz2-1/pJK148-delta-TATA   | -25 - -37
     SPBP8B7.16c:allele-3    | dbp2-i2delta               | deletion of second intron (1397-2095)
     SPAC6F6.17:allele-7     | rif1-1                     | +84 to +135
     SPBC119.10:allele-3     | asn1-1                     | -195 to -145

**Comment by ValWood** [comment]
so is this the list after the "96-141,514-596" are ignored (only 13), we can fix tomorrow. 

Were there any AA oddities?

If this is all the issues I'm quite impressed!

**Comment by kimrutherford** [comment]
For AA partial deletions, these don't match the pattern.  The first one (for pdc2) looks OK but the character between the numbers is a dash ("–") instead of a minus ("-").  I presume "1,519,784-882" is OK but I thought I'd leave it in so you could confirm.

     SPBC19G7.10c:allele-2   | pdc2-(DelC)                       | 499–754
     SPCC736.14:allele-13    | dis1-C4                           | 1,519,784-882
     SPAC1486.05:allele-4    | nup189c-delta                     | C-terminal protein deleted from transcript
     SPAC2C4.05:allele-2     | cor-C-GFP                         | cor-C-GFP
     SPAC688.11:allele-3     | end4delta-talin-GFP               | delta talin GFP
     SPAC688.11:allele-5     | end4delta-talin                   | delta talin
     SPAC6F6.16c:allele-39   | tpz1-[1-485]                      | Deletion of amino acids 485-508 (poz1-interaction domain)
     SPBC14C8.07c:allele-24  | cdc18 150-577 G204A K205A         | 150-577 (G204A K205A)
     SPAC688.07c:allele-7    | rng10(1-200)                      | 201-1038)
     SPBC4F6.10:allele-3     | Vps9-CUE                          | truncated
     SPCC777.14:allele-8     | prp4                              | unknown
     SPBC725.16:allele-4     | 1-47                              | 1->47

**Comment by mah11** [comment]
Is the task for me just to look at the lists in Kim's [last](https://github.com/pombase/website/issues/570#issuecomment-344415708) and [next-to-last](https://github.com/pombase/website/issues/570#issuecomment-344407881) comment above and fix where necessary?

**Comment by ValWood** [comment]
yep.

**Comment by mah11** [comment]
Some of these are done. In most cases I just had to fix position entries, but of course there are some exceptions.

There are a few that I changed to type "other" instead:

     SPCC338.08:allele-56    | ctp1-5             | frameshift at W288 truncating at position 292 | nt; changed to type "other" (not enough detail in paper to record actual nt insertion or deletion)
     SPAC1486.05:allele-3    | nup189n-delta      | N-terminal protein deleted from transcript    | was nt; special case because two proteins encoded on one transcript
     SPAC1486.05:allele-4    | nup189c-delta      | C-terminal protein deleted from transcript    | was aa; special case because two proteins encoded on one transcript


I don't see these on the gene pages, so I don't know where they're coming from or where to go to fix them:

     SPAC6F6.17:allele-7     | rif1-1      | +84 to +135 (nt)
     SPBC119.10:allele-3     | asn1-1      | -195 to -145 (nt)
     SPCC736.14:allele-13    | dis1-C4     | 1,519,784-882 (aa)


Val, do you want to ask Jacky about coordinates for these, since you did the approval?

1.

     SPAC688.11:allele-3     | end4delta-talin-GFP    | delta talin GFP
     SPAC688.11:allele-5     | end4delta-talin        | delta talin

PMID:15827087 (eab9a81ad211e62f) doesn't have position (x thru 1102 deleted, but no value of x).

2.

     SPAC2C4.05:allele-2     | cor-C-GFP              | cor-C-GFP

This one is from PMID:10574765 (88d2e1acdc9993bc). Also see https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=184734, where you asked J about it before, tho not specifically about coordinates (also looks like some changes didn't actually get done?)

**Comment by ValWood** [comment]
Note for me from RT,  will get to this later:

I agree that this doesn't affect the experiments, so here I will just delete the Cor1 annotation.
I'll add "CorC fragment" as a synonym of nse6
and a 
"Warning" with a link to this paper.

Bizarre...

**Comment by mah11** [comment]
Yep, it's an oddball. I also suspect that Jacky would've supplied the position info then if she knew it, but I suppose it won't hurt to ask.

**Comment by ValWood** [comment]
I remember that we do not know the exact change, only that it is partial deletion of some sort

**Comment by mah11** [comment]
In that case there's not really anything left to do for that Cor-C allele for this ticket. The warning and nse6 stuff still appears outstanding, tho.

**Comment by ValWood** [comment]
changed to cor-CΔ(partial deletion) type "other" since we cannot specify

**Comment by ValWood** [comment]
Actually the CorC  in the sawin apper is an allele of nse6  not cor1. I fixed this, and added a warning, so all done...
