### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#572]
"actomyosin contractile ring, "

does not find

actomyosin contractile ring, distal actin filament layer
actomyosin contractile ring, intermediate layer
actomyosin contractile ring, proximal layer

(primary names)

**Comment by kimrutherford** [comment]
Unfortunately there are 15 GO terms that start with "actomyosin contractile ring" and 56 that contain those three words and it's not showing the three you're actually interested in.  We could make the autocomplete list longer but that's not going to solve the general problem.

I'm still getting the hang of Solr/Lucene but we might be able to tweak the results to make them more relevant.

**Comment by ValWood** [comment]
OK, I thought I would find them if I  included the comma

actomyosin contractile ring, 

since these are the only ones with a comma  which is why I was confused....

but no worries

**Comment by kimrutherford** [comment]
> OK, I thought I would find them if I included the comma

Only letters are significant when searching all other characters are ignored.

**Comment by ValWood** [comment]
ok, makes sense
