### ISSUE TITLE
 3 minor/quick things for front page rotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#573]
- [x]   I remade  the image for
Explore PomBase: Data mining
so that it is a bit more zoomed in and hasless "vertical height". This should allow it to resolve a bit better.  It is in the drop box.

- [ ]  the images in general look slightly "stretched" in a left right direction.
I think we could resolve this by changing the aspect ration so that the images are slightly deeper but not as wide? (about 10% deeper I think would work...)
Picky, I know!

- [x]  Steve mentioned that we should  just use the infographic icon for the community curation feed, and I agree that this works better than the graph....

**Comment by kimrutherford** [comment]
> I remade the image for Explore PomBase: Data mining

I've put that in and I'll be re-releasing the preview soon.

>  the images in general look slightly "stretched" in a left right direction.

it's mostly the Gould video that looks a bit wide, and that's the one that's hardest to change.

> I agree that this works better than the graph

I've removed the graph from the config.

**Comment by ValWood** [comment]
All good

No worries about the stretching... we can deal with that later if necessary...
