### ISSUE TITLE
write announcements and post Tues

### ISSUE THREAD

**Issue by ValWood** [pombase/website#574]
We need to write announcments today! Midor your skills are required

- [x] pombelist 
- [x] linked in (own and Pombase) @Antonialock 
- [x] twitter @kimrutherford 
- [ ] google+ @Antonialock 
- [x] facebook @Antonialock 

What should we post....front page snapshot?

![pombase](https://user-images.githubusercontent.com/7359272/31877638-27de6286-b7cf-11e7-849c-8ac92e3787d0.jpg)

**Comment by ValWood** [comment]
- [ ]  news item for front page news feed
 - [ ]  notice for the front page for the "whoa what happened here?" people

**Comment by mah11** [comment]
The pombelist announcement and news item will be text only.

**Comment by mah11** [comment]
suggestion for 

> banner/notice for the front page

You are using the new PomBase site, released on October 24, 2017.

**Comment by mah11** [comment]
OK, here's what I've got so far. I've gone for brevity in these drafts - we have soooo much exciting new stuff that I thought if we included explanations and examples for everything the email would be so long no one would read it.

------

news:

New, improved PomBase goes live

The new PomBase web site, which has been under development during 2017, has been released.
The new site features:

- Nightly data updates
- New publication pages
- New genotype pages
- Improved ontology term pages
- Improved summary views for annotation displays
- Phenotype annotation display filtering
- Faster querying in the advanced search
- Front page research and community curation highlights
- Streamlined back-end data storage and retrieval

We thank the members of the fission yeast research community who have followed its progress via the preview site, and welcome feedback from all users.

------
email:

subject: The new, improved PomBase is here!

body:
Dear fission yeast researchers,

Today, Tuesday 24 October 2017, the new, improved PomBase web site is going live at www.pombase.org.

The new site carries on our mission to integrate all types of information to support your research, and now offers:

- Nightly data updates
- New publication pages
- New genotype pages
- Improved ontology term pages
- Improved summary views for annotation displays
- Phenotype annotation display filtering
- Faster querying in the advanced search
- Streamlined procedures "behind the scenes"

The new PomBase home page links to examples of the new and updated pages as well as highlighting recent fission yeast research, community curation, and selected PomBase features.

Many of you have explored these changes via the preview site (preview.pombase.org), where we will continue to test further additions and enhancements to PomBase. We appreciate your helpful comments on the preview, and your patience while we have worked to bring the new site to you.

If you have any problems, questions, or comments on the new site, please let us know - email <helpdesk@pombase.org>.

------

I'm happy to send the email out tomorrow.

**Comment by ValWood** [comment]
Nice, you go for it with the e-mail  and news tomorrow ....

**Comment by ValWood** [comment]
and @kimrutherford  # wellcome in the twitter post.;)

**Comment by ValWood** [comment]
and post a news item to the biocurator mailing list.

"Generic website for a MOD using Chado" ;)

**Comment by kimrutherford** [comment]
> suggestion for banner/notice for the front page
> You are using the new PomBase site, released on October 24, 2017.

Should we have a "Read more ..." link as well that goes to the text of the announcement?

**Comment by kimrutherford** [comment]
> news:

I've added the text as a news item.  I'll check in a bit later.

**Comment by kimrutherford** [comment]
> You are using the new PomBase site, released on October 24, 2017.

I've added that text.

**Comment by kimrutherford** [comment]
> Should we have a "Read more ..." link as well that goes to the text of the announcement?

I've done that, but it's easy to remove the link if we don't need it.

The link goes here:
  https://preview.pombase.org/about/new-pombase

A while ago we talked about having a page where we promote the site and especially show off new features.  Could the "new-pombase" page do that?  Currently I've just pasted Midori's announcement text but perhaps we could add links to example gene, term and publication pages?  I agree with Midori that it's good to keep the announce text short but we can be a bit more verbose on a web page.

**Comment by mah11** [comment]
OK, I've sent the pombelist announcement. Do you want me to muck about adding stuff to the new-pombase web page?

**Comment by kimrutherford** [comment]
> Do you want me to muck about adding stuff to the new-pombase web page?

If you think that page is a good idea, yes please.

I'm happy to help.

**Comment by mah11** [comment]
back to this idea ...

> and post a news item to the biocurator mailing list

Kim - is there anything inaccurate about this part of the draft I've got going? :

"Unlike the previous PomBase site, the new site is updated daily, and generates pages for genes, genotypes, publications, and ontology terms directly from an underlying Chado database, using modular code that can easily be reused for any other MOD-style organism database."

**Comment by mah11** [comment]
For the new-pombase page, I've added more text and linkies. If it's horrible, go ahead and revert it, or make whatever further changes you want.

**Comment by mah11** [comment]
sent the biocurator list mail

**Comment by kimrutherford** [comment]
> For the new-pombase page, I've added more text and linkies. If it's horrible, go ahead and revert it,
> or make whatever further changes you want.

Thanks for that.  I think it looks good.  It went up on the site yesterday.

**Comment by ValWood** [comment]
I think we sufficiently saturated the market with our posts.
Nearly 1500 unique users in 3.5 days ......43.8% returning already  :)
