### ISSUE TITLE
customizable information retrieval (download)  for search results

### ISSUE THREAD

**Issue by ValWood** [pombase/website#576]
follow on from:

https://github.com/pombase/website/issues/20#issuecomment-339002515

- [x] length, (have start and end)
- [x] chromosome
- [x] orthologs
- [ ]  interacting genes
- [ ]  substrates
- [ ]  ~GAF~ - moved to #949 

etc

**Comment by mah11** [comment]
GAF, phenotypes, and modifications are listed in #21, but we could close that one because it also includes sequence download, most of the comments focus on sequence, and sequence is basically done.

**Comment by ValWood** [comment]
We would love this but I think it needs to come after initial browser installation...

**Comment by kimrutherford** [comment]
> GAF

When implement GAF export, we can used the same code to fix:
https://github.com/pombase/pombase-chado/issues/305

**Comment by ValWood** [comment]
user feedback from survey
> Easier downloads of data shown on pages

This ticket will solve this problem. I guess we also need a gene page link to the "download" at this point so users can download GO terms an interactions from a single page?

**Comment by ValWood** [comment]
also from survey:
- New tools for gene list analysis (e.g. download human and budding yeast orthologs...).
- One thing I've wanted is to be able to get a gene list through advanced search and then download the corresponding S. cerevisea (or human, etc) ortholog names, if they exist. Rather than having to navigate to each gene page to get that information.

**Comment by kimrutherford** [comment]
See also: #1238

**Comment by kimrutherford** [comment]
> One thing I've wanted is to be able to get a gene list through advanced search and then download
> the corresponding S. cerevisea (or human, etc) ortholog names, if they exist. Rather than having to
> navigate to each gene page to get that information.

I've added human and cerevisiae orthologs as download options.

![download-orthologs-1](https://user-images.githubusercontent.com/90474/56454310-c60b6c80-63a2-11e9-935a-a8b00cda2c38.png)

**Comment by ValWood** [comment]
Brillian. This will be very popular.

I think I found a bug

Systematic ID	human ortholog
SPAC15A10.08	ACTN1,ACTN2,ACTN4
SPAC3A12.14	CALM1,CALM2,CALML3,CALML5,CALML4
SPAC29A4.05	CALM1,CALM2,CALM3,CALML3,CALML5,CALML4
SPCC1682.04	CETN1,CETN2,CETN3
SPAP8A3.08	MYL6B,MYL1,MYL3,MYL4,MYL6
SPCC830.06	PPP3R1,PPP3R2
SPBC11G11.02c	EPS15L1,EPS15
SPBC1778.06c	LCP1,PLS1,PLS3
SPCC320.04c	RHOT1,RHOT2
SPCC1259.11c	TBC1D9,TBC1D8B,TBC1D9B
SPAC1687.09	EPS15L1,EPS15
SPAC3A11.05c	SYNE4
SPAC18B11.04	NCS1
SPAC25G10.09c	ITSN1,ITSN2
SPAC22F8.11	PLCB1,PLCH2,PLCH1,PLCB2,PLCB3,PLCB4,PLCD1,PLCD3,PLCD4,PLCL1,PLCL2,PLCG1,PLCG2
SPAC926.03	MYL9,MYL12A,MYL7,MYLPF,MYL10,MYL12B,MYL2,MYL5
SPBC83.01	EPS15L1,EPS15
SPAC1687.14c	
SPBC215.01	TBC1D9,TBC1D8B,TBC1D9B
SPBC800.10c	EPS15L1,EPS15
SPCC613.03	NUCB1,NUCB2

SPAC22F8.11 has human orthologs....

**Comment by ValWood** [comment]
very weird... they are there...

**Comment by ValWood** [comment]
s'okay...line wrapping

![line wrapping](https://user-images.githubusercontent.com/7359272/56467399-5767f680-6416-11e9-8008-642326c6630b.jpg)

**Comment by kimrutherford** [comment]
>  interacting genes

That's probably the easiest one to do next. It's quite similar to the orthologs download so it would probably only take an hour or two to implement.

>  substrates

Could you give me a bit more detail on that one?

**Comment by ValWood** [comment]
I will but I'll open a new clean ticket (s)

**Comment by Antonialock** [comment]
removing annoouncee label, annooucned back in may
