### ISSUE TITLE
blast errors

### ISSUE THREAD

**Issue by ValWood** [pombase/website#578]
when I select  translation

the link to NCBI
https://blast.ncbi.nlm.nih.gov/Blast.cgi
gives
Access to blast.ncbi.nlm.nih.gov was denied

You don't have authorization to view this page.
HTTP ERROR 403

**Comment by ValWood** [comment]
and the Ensembl blast says Ensembl DNA blast, I would expect protein blast here.

**Comment by mah11** [comment]
OK, that's weird. The protein BLAST links are working fine for me right now from home, and were working yesterday from the office.

**Comment by Antonialock** [comment]
All the links work for me too.

I get a "security warning" when I click on the ensembl blast, both for protein seq and DNA seq

**Comment by ValWood** [comment]
Ignore the Ensembl part. I needed to reset to translation.

but the security warning is an issue...

**Comment by mah11** [comment]
I have seen no security warnings.

Weirdness cotinues, though. In Safari, NCBI is now giving me an empty page if I go from a gene page, but nothing about permission problems, and nucleotide vs protein doesn't make any difference. Firefox is still fine and dandy.

**Comment by mah11** [comment]
OK, I finally got 403'd by NCBI BLAST -- in Chrome.

It's only the link from a gene page that goes awry, though. In both Chrome (403) and Safari (blank page), I can go directly to the NCBI BLAST home page, e.g. by navigating from anywhere else in NCBI or by pasting the link.

**Comment by Antonialock** [comment]
I had the security warning multiple times but now it has gone away..maybe it was temporary.

I also get a blank page in Safari for the NCBI blast (protein&DNA)
Ensembl links seem to work in Safari

In chrome DNA/protein blast NCBI sends me to a page saying:
Access to blast.ncbi.nlm.nih.gov was denied

In chrome ensembl links behave

**Comment by kimrutherford** [comment]
That's annoying.  I think NCBI must have added some restrictions.  I've changed the way we link to NCBI (changed from HTTP POST to HTTP GET) and it seems OK for me.  I've updated the main site with the change.  Could you try it?

I think it's something we need to check regularly in case NCBI change things again.

> I had the security warning multiple times but now it has gone away..maybe it was temporary.

I noticed a warning from Chrome yesterday because we were using an HTTP link to Ensembl instead of an HTTPS one.  I fix that yesterday so it's possible that's why you saw a warning but now it's gone.  Please let me know if it comes back.

**Comment by mah11** [comment]
In a whirlwind check (1 gene each), NCBI BLAST links are now OK in all three of the browsers I tested.

**Comment by kimrutherford** [comment]
> NCBI BLAST links are now OK in all three of the browsers I tested.

Thanks for checking.

I'll try Internet Explorer then I'll close this unless any other problems pop up.

**Comment by ValWood** [comment]
close?

**Comment by kimrutherford** [comment]
Yep, it's all fine in Internet Explorer.
