### ISSUE TITLE
Blast links, open in new tab

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#579]
I really like to have the option of staying on a page, and open links in new tabs.

Would it be difficult to implement the option to right click on the blast links so that they can be opened in a new tab? 

![screen shot 2017-10-26 at 10 03 31](https://user-images.githubusercontent.com/12727506/32044260-fde56700-ba34-11e7-96f6-341a56330f4a.png)
They don't look like links at the moment:

**Comment by mah11** [comment]
I'd like that too

**Comment by kimrutherford** [comment]
I think so.  I'll give it a go.

**Comment by kimrutherford** [comment]
Sorry, I was wrong.  I can't find a way to fix that.

If it helps it is possible to make both blast buttons open in a new tab all the time.

Or we can add an "Open BLAST in new tab" checkbox at the bottom like this:

![screenshot from 2017-10-27 13-30-13](https://user-images.githubusercontent.com/90474/32086276-92b4f5d4-bb30-11e7-8f55-ff65048e01c4.png)

**Comment by mah11** [comment]
I think I could go with either the checkbox or just a message saying "opens in new tab" -- either would be better-for-me than going to BLAST in the current tab.

**Comment by kimrutherford** [comment]
I've added a checkbox for now.  We can easily change that to just always open in a new tab if the checkbox is annoying (which it probably is).

**Comment by ValWood** [comment]
will close if working. Any  alternative ideas, new ticket

**Comment by kimrutherford** [comment]
> will close if working. Any alternative ideas, new ticket

Let me know if the "Open BLAST in new tab" button is annoying.
