### ISSUE TITLE
ensure that all ftp subdirectories have mutually consistent READMEs

### ISSUE THREAD

**Issue by mah11** [pombase/website#58]
Some READMEs have information about the file contents (e.g. ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Chromosome_contigs/README); others have information about previous releases (e.g. ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Chromosome_Dumps/gff3/README). All should have both (unless there are any for which previous release info isn't applicable).

At least one is missing -
ftp://ftp.ebi.ac.uk/pub/databases/pombase/FASTA/ has no README

**Comment by ValWood** [comment]
after
https://github.com/pombase/website/issues/355

**Comment by mah11** [comment]
this is finally DONE! yay!!! happydance

**Comment by ValWood** [comment]
Thank you! thank you! thank you!. You rock!
