### ISSUE TITLE
links to single FAQ

### ISSUE THREAD

**Issue by ValWood** [pombase/website#581]
I quite miss that you cannot get a URL for an individual FAQ answer. This was useful for answering helpdesk queries.

(I also liked the single page for finding things, in retrospect, but we can see how we go)

**Comment by mah11** [comment]
Each FAQ does have an individual URL. It's just no longer as easy to find out what it is, because the FAQ category pages don't have the questions as links.

**Comment by ValWood** [comment]
Do we know how to find it?

**Comment by mah11** [comment]
Well, Kim and I do ... but it's a faff-and-a-half. One of us can demo it on a call, or I can show you next time we're both in the office.

**Comment by kimrutherford** [comment]
I've modified the FAQ so that if you click on a heading it will take you to a permanent link.  Should be in the next website update.

**Comment by kimrutherford** [comment]
> Should be in the next website update.

It's there now.
