### ISSUE TITLE
add license info

### ISSUE THREAD

**Issue by mah11** [pombase/website#582]
use CC-BY; add note to about/citing-pombase

also add recommendation for citing pages by date, modeled on SGD's

reply to Seth via helpdesk when done

**Comment by mah11** [comment]
Oof. This has the potential to be much more complicated than I thought when I opened the ticket.

helpdesk 220218

**Comment by mah11** [comment]
Some progress! I have
- created a Terms of Use page with some text that we and Seth thought looked pretty good;
- created a Data Sources page that is somewhat less impressive, but at least makes a start. 

Both are in the About department. I'll happily consider suggestions for content edits, more or different places for links, etc. We may want to think about automating updates to the publication list on the data sources page someday, but at the moment we can manage manual updates for the number of browser track pubs we have to list.

Also think about anything else we could list as an external data source ...

There's still some room to investigate various aspects of licensing and copyright (notably, PomBase's copyright-holding entity status), but that's probably new-ticket territory.

@kimrutherford, can you push the button to make the new stuff live soon (not urgent, but will be good to have it up before too long because then we can have the data reuse folk re-evaluate PomBase)? I'll close this ticket when that's done.

**Comment by mah11** [comment]
oops. I have just committed a fix for a typo that made a link (from one of the new pages to the other) not work. So another update would help ... sorry for the added bother!

**Comment by kimrutherford** [comment]
> So another update would help

The fixes will be in the update in the morning.

**Comment by mah11** [comment]
Thanks again. You can stand down from this one until further notice (we may do more page edits, but not for a while) ;)

**Comment by ValWood** [comment]
Seems to be done as far as this ticket is concerned?
