### ISSUE TITLE
bug, gene lists advanced search

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#583]
pointed out in the group meeting.

If you input a gene list in the "gene list input option" of the advanced search then you can't download any results

- from a comparison of two searches, it looks fine if you input systematic IDs, but not if you input gene IDs

e.g. gene names inputted
<img width="1231" alt="screen shot 2017-10-27 at 22 08 25" src="https://user-images.githubusercontent.com/12727506/32125349-6815c0aa-bb63-11e7-80b3-4aa163e7a088.png">

e.g. sys ids inputted
<img width="1239" alt="screen shot 2017-10-27 at 22 11 34" src="https://user-images.githubusercontent.com/12727506/32125470-07319dee-bb64-11e7-8406-6be3da45c8ce.png">

**Comment by kimrutherford** [comment]
It currently only looks up systematic IDs not gene names.  I'll change that.

**Comment by kimrutherford** [comment]
I've fixed the query builder so that you put gene names in the "Gene IDs" query type.  It's still a bit primitive though.

We should talk about how to handle synonyms.

**Comment by ValWood** [comment]
Old behaviour was that if you used gene names you had to use the primary name. Nobody complained about that.  I think an error was  if you used a name which "primary"  there was an error.
It might be nice longer term to do something more robust....

**Comment by kimrutherford** [comment]
> Old behaviour was that if you used gene names you had to use the primary name.

I think that's the correct behaviour for the query builder.

Users can look up individual synonyms in the search box at top right.  If there is demand to look up multi synonyms (maybe they have a gene list from a old paper), I think it would be better to have a separate "Look up old identifiers" tool.

**Comment by ValWood** [comment]
So we can close this one as it works like the old site?

**Comment by kimrutherford** [comment]
Yep, I think this is done.  We can open other issues for new functionality.
