### ISSUE TITLE
Add a date to the front page panel config

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#587]
I think it is good future-proofing to add a date stamp to each of the front page panel configurations. We don't necessarily have to display the date (although that might make sense on the archive page), but it's good to have for our records.

**Comment by ValWood** [comment]
deprioritise if not quick

**Comment by kimrutherford** [comment]
I've done this so that it's in place to when we add your new front page panels.

**Comment by kimrutherford** [comment]
Each front item now has a date field.  The dates aren't displayed but they could be on the archive page if that made sense.

The entries on the archive page are currently in the order they appear in the config file.  I might make sense to order by date.  Should the most recent items appear at the top or at the bottom of the page?

**Comment by mah11** [comment]
> The dates aren't displayed but they could be on the archive page if that made sense.

I think it does.

> [on the archive page it] might make sense to order by date.

Definitely agree, for the research spotlights. For "explore PomBase" it doesn't really matter, but might as well do everything the same way.

> Should the most recent items appear at the top or at the bottom of the page?

I vote top.

**Comment by kimrutherford** [comment]
Reopening to remind myself to add dates to the archive pages and order the items.

**Comment by kimrutherford** [comment]
> add dates to the archive pages and order the items.

That's done for tonight's update.
