### ISSUE TITLE
FTP genome directory tweaks

### ISSUE THREAD

**Issue by mah11** [pombase/website#588]
I'm trying to finish updating READMEs for #58, and it's revealed some loose ends in the ftp directory organization.

As I understand it, the files in the two subdirectories of https://curation.pombase.org/dumps/latest_build/fasta/ get generated with every build but are not yet copied to svn. (@kimrutherford is that correct?) Most of the file names there make more sense than the ones we've inherited from EBI/EG, with these two exceptions:

Schizosaccharomyces_pombe_chromosome_AB325691.fa.gz
Schizosaccharomyces_pombe_chromosome_MISPCG.fa.gz 

Does anybody mind if I do a bit more tidying? Specifically:

- [x] Manually copy over the files from the latest build to ftp in svn, and put the EBI-derived ones in OLD subdirectories as appropriate
- [x] Rename Schizosaccharomyces_pombe_chromosome_AB325691.fa.gz -> Schizosaccharomyces_pombe_chromosome_telomeric_contig.fa.gz and Schizosaccharomyces_pombe_chromosome_MISPCG.fa.gz -> Schizosaccharomyces_pombe_chromosome_mitochondrial.fa.gz
- [x] Rename the /fasta/ subdirectory to /genome_sequence/ (because it's not all of the files we have in fasta format)
- [x] Create a subdirectory /centromeres/ for the cen*.gz files

If I do all that, then I can make the READMEs consistent with it, and the whole thing will be a lot less annoying.

If you have any questions or objections, squawk soon, because I would really love to have the README job over and done with.

**Comment by ValWood** [comment]
I have no objections!

**Comment by mah11** [comment]
all done. the end of the README slog is in sight ...
