### ISSUE TITLE
display supporting refs for term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#589]
It might be quite nice if we could display refs for FYPO/GO terms on  the term pages (they could be hidden under a link).
Then we could link these to the PomBase publication pages.....

**Comment by kimrutherford** [comment]
> It might be quite nice if we could display refs for FYPO/GO terms

We don't current load the reference for the definition.  We'd need to fix that first.  It's not a huge job.  I've made an issue about that: https://github.com/pombase/chobo/issues/8

**Comment by ValWood** [comment]
@mah11  @Antonialock  what do you think?

I thought it would be nice for users to see how  pombe publications are used to support defs...

**Comment by mah11** [comment]
Well, FYPO is pretty sparse - I don't cite a paper if a definition is easily inferrable from the quality ("abnormal", "increased", etc.) plus the entity (GO BP or CC, etc.) def, so most of them will just have my initials, sometimes with a GO ID as well. But no objection to displaying the info.

**Comment by Antonialock** [comment]
No objections, I take it this would include references that are not pombe papers?

**Comment by ValWood** [comment]
> include references that are not pombe papers?

yep. It would be "slightly hidden" under a link I think...
lets leave for now anyway....  people can see GO ones in QuickGO

**Comment by ValWood** [comment]
I think maybe 
i) don't hide...it doesn't matter if the papers are not pombe, it makes it clearer to our users that these  are the papers supporting the GO term , and that it's very nice if it is *their * paper...Most will be pombe papers anyways (for leaf nodes, which is where most of our annotation is)

but 
2) only display reference that are PMID:
to keep it neat

**Comment by kimrutherford** [comment]
I've spent today fixing bugs in the OBO reading code and adding code to store the dbxrefs from term definitions.  They should be in Chado from tomorrow.  After that, adding the PMID reference for definitions is straight forward.

**Comment by ValWood** [comment]
This seems quick now so may as well do soon and close?

**Comment by kimrutherford** [comment]
Were we just going to show the PMIDs from the term definitions?  There are lots of other references.  Currently we load them all into Chado, except for the URLs.  Perhaps we should filter out some of these?  There's no much use loading references we don't display on the web site.

Here's a sample, there are others:

- PMID:10873824
- PMIG:10085024
- PMID:pm
- GOC:mcc
- GOC:mtg_transport
- GOC:jl
- ISBN:0815340729
- PO:0000029
- KEGG:R05612
- RHEA:20836
- EMBL:AF304352
- http://www.ultranet.com/~jkimball/BiologyPages/D/DNArepair.html
- http://www.earthlife.net
- EC:3.2.1.108
- BioCyc:PWY-882
- BRENDA:1.11.1.15
- BTO:0002164
- CHEBI:10022
- CORUM:2870
- DDANAT:0000068
- dictyBase_REF:2530
- DOI:10.1002/1096-9861
- FBbt:00005786
- FB:FBrf0039640
- Intact:EBI-9345927
- intAct:EBI-9636287
- InterPro:IPR000001
- IUPHAR_GPCR:1506
- IUPHAR_RECEPTOR:1276
- MeSH:C04.697.152
- MetaCyc:1.10.2.1-RXN
- NIF_Subcellular:sao1470140754
- Pfam:PF03166
- phi:0000005
- PHI:0000011
- Wikipedia:Gamma_ray
- Wiki:Cystic_fibrosis_transmembrane_conductance_regulator

**Comment by mah11** [comment]
Val suggested [earlier](https://github.com/pombase/website/issues/589#issuecomment-362375821) that we only show PMIDs. I have mixed feelings, because some refs (e.g. ISBNs, IDs from other ontologies) are potentially informative, and showing incomplete information always makes me a little twitchy, but I also see the advantage of not showing odd stuff that won't make sense to anyone.

So I'll stay wishy-washy & neutral ;)

**Comment by ValWood** [comment]
Let's go with PMID's, ISBNs, DOI, Wikipedia, Wiki maybe?

I object to all of these being lumped together. They have completely different meanings.
i)  A reference supporting the definition
ii) mappings to other resources
iii) the person who crafted the definition
iv) I have no idea. For example EMBL:AF304352 is a DNA database entry. I'm not sure how that gets in? 
v) PMID:pm?????

And just look at the prefixes...not a great advertisement for excellence in data standardization :)
@cmungall wasn't there talk about 'typing' these db_xrefs?

**Comment by mah11** [comment]
> Let's go with PMID's, ISBNs, DOI, Wikipedia, Wiki maybe?

Well, if we're not using all, I'd leave out wiki (which isn't a single site site, and I think the occurrences in GO xrefs are typos) and Wikipedia ... but I'll stay neutral.

> I object to all of these being lumped together. They have completely different meanings.

If these are all coming from the definition dbxref field, they _should_ all have meaning 1 (reference supporting the definition) or 3, because that field is _supposed_ to identify the source(s) consulted to craft the def. A lot of them (tho admittedly not that EMBL entry) are believable def sources.

That said, I know GO has shoehorned xrefs identifying the group that requested the term into the def dbxref field for quite a while. I've thought all along it's wrong to do that, but I was outvoted years ago :P

> ii) mappings to other resources

Mappings to other resources have a separate dbxref field. Any in the _definition_ dbxref field are errors that should be reported and corrected.

> v) PMID:pm?????

pretty obviously a typo (as is PMIG:10085024)

**Comment by cmungall** [comment]
This is for definition dbxrefs?

We don't distinguish between these explicitly, this goes back to oboedit
days. We could have some kind of shared mapping, eg GOC=curator. But I'm
not sure who much we can distinguish between the others. E.g. sometimes a
PMID will be used for a review, not dissimilar from a book ISBN or a
wikipedia article, sometimes it is a very specific experimental publication
the curator was working on when they requested (I would prefer we didn't do
this latter).

Agreed, EMBL should NEVER be a def xref, if this is in GO make a bug report.

**Comment by ValWood** [comment]
> This is for definition dbxrefs?

Yes.
>sometimes it is a very specific experimental publication the curator was working on when they requested

oops, I do this all the time

I was just shocked to see the InterPRo domains etc in the list. Surely these are mappings not db_xrefs?

Although it isn't as bad as I thought. I originally thought this was a list for one term, but I think it is just  selection.

I'll open a ticket on the ontology tracker.

**Comment by ValWood** [comment]
@kimrutherford  before I open a GO ticket for this (I forgot to do this), are you sure that all these are db_xrefs supporting definitions and not just any db_ref associated with a GO term?

**Comment by kimrutherford** [comment]
They are all from the "def:" lines.  There's only one with an EMBL ID:

```
[Term]
id: GO:0004453
name: juvenile-hormone esterase activity
namespace: molecular_function
def: "Catalysis of the reaction: methyl (2E,6E)-(10R,11S)-10,11-epoxy-3,7,11-trimethyltrideca-2,6-dienoate + H2O = (2E,6E)-(10R,11S)-10,11-epoxy-3,7,11-trimethyltrideca-2,6-dienoate + methanol. A carboxylesterase that hydrolyzes the ester linkage of juvenile hormone." [EC:3.1.1.59, EMBL:AF304352]
subset: goslim_chembl
synonym: "JH esterase activity" EXACT [EC:3.1.1.59]
synonym: "JH-esterase activity" EXACT [EC:3.1.1.59]
synonym: "juvenile hormone analog esterase activity" EXACT [EC:3.1.1.59]
synonym: "juvenile hormone carboxyesterase activity" EXACT [EC:3.1.1.59]
synonym: "methyl-(2E,6E)-(10R,11S)-10,11-epoxy-3,7,11-trimethyltrideca-2,6-dienoate acylhydrolase activity" EXACT [EC:3.1.1.59]
xref: EC:3.1.1.59
xref: MetaCyc:JUVENILE-HORMONE-ESTERASE-RXN
xref: RHEA:16393
is_a: GO:0052689 ! carboxylic ester hydrolase activity
```

The "PMIG:10085024" ref has been fixed.

**Comment by ValWood** [comment]
so we will display supporting references for definitions
PMID's, ISBNs, DOI

**Comment by ValWood** [comment]
I put "next" on this. Not super urgent but seems almost done, and quite quick....

**Comment by kimrutherford** [comment]
> so we will display supporting references for definitions
> PMID's, ISBNs, DOI

Do these need to be links?

**Comment by ValWood** [comment]
I guess that would be consistent with  display of an ID.

**Comment by ValWood** [comment]
PMID's, ISBNs, DOI
Some IDs in PomBase and some now.
Link to PomBase or PubMed


In square backets at the end of the definition.
@mah11  will supply ISBN link

**Comment by mah11** [comment]
DOI: `https://dx.doi.org/[ID]`

For ISBN I've found this: https://www.perlmonks.org/?node_id=84121 (it recommends `http://isbn.nu/[ID]`). There's also this [factsheet](https://www.doi.org/factsheets/ISBN-A.html) at the DOI site but it doesn't seem to have a conveniently noddy "stick the ID in this URL" as far as I can tell.

**Comment by kimrutherford** [comment]
> it recommends http://isbn.nu/[ID]

Thanks.  Just tried that and it seems to work.

**Comment by kimrutherford** [comment]
> PMID's, ISBNs, DOI

I've added those to the terms pages for tomorrow morning.  Only the PomBase PMIDs are links at the moment.  I'll fix that later.

Here are some examples to check in the morning:
  - https://www.pombase.org/term/FYPO:0004520
  - https://www.pombase.org/term/FYPO:0006037

**Comment by kimrutherford** [comment]
> For ISBN I've found this:

I ended up using the config from the GO xrfs file for all three xref types (PMID, ISBN and DOI).

> Here are some examples to check in the morning:
>     https://www.pombase.org/term/FYPO:0004520

Unfortunately that was a bad example because Wiley's DOI handling is broken.

This one works:
  https://www.pombase.org/term/MONDO:0400004

Here's a ISBN example:
  https://www.pombase.org/term/MONDO:0021752

It's very easy to add other xref types if it's useful in the future.

**Comment by ValWood** [comment]
Looks good, except the publications in the front page community curation feed now appear as PMIDs, was that an unintended consequence of these changes?

**Comment by kimrutherford** [comment]
That sounds like an unrelated bug.  But I'll fix it either way.

**Comment by kimrutherford** [comment]
You were right, it was an unintended consequence.  The fix is deploying now and should be there in 15-20 minutes.
