### ISSUE TITLE
mailto link oddity

### ISSUE THREAD

**Issue by mah11** [pombase/website#590]
Some of the helpdesk mailto links work (to spawn a compose-message window in my mail client), but others go to the sad-pombe "not found" page. The ones that go 404 do so because they're adding https cruft to the URL, i.e. they're trying to reach

     https://www.pombase.org/mailto:helpdesk@pombase.org

But I have stared and stared at the markdown and I cannot see any difference in it between the links that work and the links that go 404 - all have:

     [some text](mailto:helpdesk@pombase.org)

Examples: on the datasets page (https://www.pombase.org/datasets), the first mailto link (contact the PomBase curators) works, but the second (ask the helpdesk) doesn't. The one on the home page works; the one of the "about PomBase" page doesn't.

Any idea wtf is going on?!?

**Comment by kimrutherford** [comment]
I think the Markdown processing Perl script was mangling the second case but not the first on the datasets page because the first one was split over two lines.  I've fix the script to not mangle mailto: in either case and the fix will be in tomorrow.

**Comment by mah11** [comment]
Could something similar be going on with the About page? It uses the helpdesk address as the hyperlink text, so is the '@' causing mangling?

    Email: [helpdesk@pombase.org](mailto:helpdesk@pombase.org)

**Comment by kimrutherford** [comment]
All mailto: links were being mangled except for the ones that happened to be split over 2 lines.  The About page links should be fixed tomorrow too.

Splitting over 2 lines is legal Markdown syntax.  My dodgy Perl script to handle internal links was failing to mangle the split links because it didn't notice they were links.

**Comment by mah11** [comment]
well, thanks for the fix!

**Comment by ValWood** [comment]
close?
