### ISSUE TITLE
Lab pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#591]
Jurg seemed a bit upset his stats won't look so good if we make "people pages" #332  - unless we add a details for # of sessions delegated :-) 

It might be nice to also have "lab" pages. 
The lab page could list publications associated with the lab, and stats (number of papers community curated, annotations made...? etc) and a link to the lab webpage (entered at point of community curation?)

A lab name could be created based on the name of the last author of publications (e.g. Bahler lab, Wu lab, Gould lab...).

I think this should work for most publications. I can think of two cases where it is not ideal:
- two labs might collaborate. I guess more often than not however this would involve one pombe lab and one technique/biological area-specialized lab, who probably wouldn't care about pombe stats pages anyway, so not a biggy
- new lab heads might still use an old supervisor as last author to get into more high profile journals (probably not many cases...but not ideal)

**Comment by Antonialock** [comment]
From Val (email:
> this is really tricky because of people moving lab.... and increasingly papers are collaborative.
I guess final author would  work for lab in the first instance, but  labs need to be able to "claim" additional papers too.

**Comment by ValWood** [comment]
We'll  discuss this next time to see how easy.
Then  we can punt for a while but I could go through and check that the correct lab heads were 
assigned to publications

**Comment by ValWood** [comment]
see
https://github.com/pombase/website/issues/332
