### ISSUE TITLE
front page: "recent community curation"

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#592]
From lab feedback:
The "recent community curation" box on the front page looks underwhelming. They didn't know what the papers were from the first author, so it didn't look very interesting. Maybe ask the community curator to summarise the paper with a set number of words, or display the first X number of words from the title, or use keywords (from pubmed meta data, or input by community curator)

from Val (email):
hmm, in that case maybe we need to change the way we do the feed....
First x words might work...

**Comment by ValWood** [comment]
It might  be a crazy suggestion, but I wondered if we could 

1) start the "words" on this panel higher up, (i.e actually on the image, the grey portion of the pie. This would give more text space)
also

2) reduce to  4 most recent sessions (make a history for the others?)

and
3) then change from author to titles, let them go over 2 lines, and then trencate?


I envisage it will look a bit like this (with less line spacing):

The conundrum of UDP-Glc 
entrance into the yeast….

Shugoshin forms a specialized
 chromatin domain at subt….

Alp7/TACC recruits kinesin-8-
PP1 to the Ndc80 kinetochore…

MADS box transcription factor 
Mbx2/Pvg4 regulates invasive…

**Comment by ValWood** [comment]
It would be a bit more exciting  than the names (for everyone except  the authors!)

**Comment by ValWood** [comment]
I origianally thought this would be OK, because we get to know the papers as "xxx et al" but obviously when they are new papers and people, we have no clue!

**Comment by Antonialock** [comment]
yeah that could work?

**Comment by ValWood** [comment]
Kim if you think this could work, have a go, otherwise we can discuss  on next call

**Comment by kimrutherford** [comment]
> Kim if you think this could work, have a go, otherwise we can discuss on next call

I've had a go.  The change will be in pombase-dev in a few minutes and on the front site at 7am-ish (hopefully).

**Comment by ValWood** [comment]
I think that works well.
Note that on dev, at the moment the recently approved session seems to show rather than the recently curated (I think...)

**Comment by kimrutherford** [comment]
> Note that on dev, at the moment the recently approved session seems to show rather than the recently curated 

For me the list is the same on both sites.

**Comment by ValWood** [comment]
Yep, I don't think it doing the funky clever  order show in list if approval date  is later than submission date (or whetever it was).

I'm seeing things in the list that I reapproved yesterday, usually I don't...

**Comment by ValWood** [comment]
So the papers that I actually approved yesterday, is not in the list, the visible papers are much older

http://pombase-dev.bioinformatics.nz/reference/PMID:28945192

**Comment by kimrutherford** [comment]
I checked in Chado.  There are lots of papers the were first approved more recently than PMID:28945192 (not all are community curated though):

 PMID:21300781 | 2017-11-01 11:57:43
 PMID:28438891 | 2017-11-01 16:03:40
 PMID:23101633 | 2017-11-01 16:38:51
 PMID:25131669 | 2017-11-01 16:46:59
 PMID:11884512 | 2017-11-01 21:31:31
 PMID:24818994 | 2017-11-01 21:32:31
 PMID:11136464 | 2017-11-02 08:26:04
 PMID:26687354 | 2017-11-02 12:45:36
 PMID:24937146 | 2017-11-02 13:10:14
 PMID:21357609 | 2017-11-02 13:15:00
 PMID:21703453 | 2017-11-02 19:23:03
 PMID:25492408 | 2017-11-02 19:31:39

**Comment by ValWood** [comment]
Thats weird

 PMID:11884512  and PMID:21703453 were curated ages ago (maybe it is because these were "reactivated")

also I'm sure thought I "first approved" PMID:28945192 yesterday (although it did have  PHAF annotations visible before then)

**Comment by kimrutherford** [comment]
> also I'm sure thought I "first approved" PMID:28945192 yesterday

Looks like you approved it 2017-11-02 16:42:22 but first approved it 2017-10-31 16:01:51

**Comment by ValWood** [comment]
> Looks like you approved it 2017-11-02 16:42:22 but first approved it 2017-10-31 16:01:51

OK, I remember I did!

It still isn't clear why PMID:11884512 and PMID:21703453 are recent though...their first approved dates must be *ages* ago

**Comment by kimrutherford** [comment]
According to Chado the first approved dates for those are:

PMID:11884512 | 2017-11-01 21:31:31
PMID:21703453 | 2017-11-02 19:23:03

**Comment by ValWood** [comment]
They aren't the first approved dates, but I  did "reapprove" them.

**Comment by mah11** [comment]
Is it plugging in a reapproval date as "first" if the actual first approval date was before the first-approved datestamp was separately tracked?

**Comment by kimrutherford** [comment]
> Is it plugging in a reapproval date as "first" if the actual first approval date was before the
> first-approved datestamp was separately tracked?

Yep, that could explain things.  I'll see if I can improved on that plan.

**Comment by kimrutherford** [comment]
> Is it plugging in a reapproval date as "first" if the actual first approval date was before the
> first-approved datestamp was separately tracked?

I've fixed that now.  It will take a few days for it to make a difference.  The front page list will change once enough approvaals are made.

That was a side-issue.  Antonia's first comment was about how the recent curation panel looks.

**Comment by ValWood** [comment]
Well the feed is showing recent papers at the moment, that is probably just because  the proper recent ones trump the old reapproved ones by the old method.

I don't think the image needs a legend (it's only really a visual hook), but I think we should change this image anyway so it is just the  word cloud wedge (which can be bigger), then we skirt the problem.

**Comment by ValWood** [comment]
I think this is OK,
if anything is odd we can open new...
