### ISSUE TITLE
External links tweak

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#593]
- Missing link to cycle base in external references section on the gene pages
- Pint link missing from the eternal resources section https://www.pombase.org/community/internet-resources
- Expression viewer - they want separate links for each time point/ condition (e.g. cell cycle, stress, meiosis, mating)

**Comment by ValWood** [comment]
Jurg might be annoyed...we will add it back if it is still maintained....  But  it isn't really a power user thing, its just misleading because the data was validated using  proteomics data unfiltered IMHO.
 I am going to delete this comment, and the ones above ;)

**Comment by ValWood** [comment]
Can you track down  the URL format, and then update the config file?

**Comment by mah11** [comment]
I can find no record in tickets or email of discussing Cyclebase, so I have added it to the relevant configuration files.

**Comment by Antonialock** [comment]
and I broke down the expression viewer and emailed Jurg about Pint. Can reopen if they still want it included & update it (not updated since 2012)

**Comment by kimrutherford** [comment]
> I can find no record in tickets or email of discussing Cyclebase, so I have added it to the relevant 
> configuration files.

Thanks.  I needed to change "SPCC1739.11c" to "SPCC1739.11c.1" in the URL to get the links to work.

The new links will be in www in the morning.

**Comment by Antonialock** [comment]
I did the expression viewer tweak in external_reference_config 

they are not visible online, I can't see cyclebase in there either so I guess it is not the right one to update? What file is it that needs modifying?

**Comment by mah11** [comment]
Ah. We should move external_reference_config out of svn - it's been superseded. Edit the JSON config file as described [here](https://github.com/pombase/website/wiki/Config-file#external_gene_references) and [here](https://github.com/pombase/website/wiki/Configuration#adding-a-new-external-reference).

**Comment by Antonialock** [comment]
Ok I have done this

**Comment by Antonialock** [comment]
I think..

**Comment by kimrutherford** [comment]
> Ok I have done this

The edits look OK and it works for me in my local version.  It should be visible in the main site tomorrow.

**Comment by Antonialock** [comment]
cheers, I'll recheck
