### ISSUE TITLE
advanced search: separate genes from sys IDs in results

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#594]
In the group meeting there were requests to display the sys ID and gene names in separate columns to facilitate copy + paste of one column (they know about the download option but would still like this feature)

**Comment by ValWood** [comment]
If this is very quick you could do it soon, if not add low priority

**Comment by ValWood** [comment]
Do this if quick (< 1 hour) otherwise make low priority

**Comment by kimrutherford** [comment]
That's done.  It wasn't a big change so I don't think I'm likely to have broken anything, but please keep a look out.

**Comment by ValWood** [comment]
looks good
