### ISSUE TITLE
advanced search: send gene list results to external resource

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#595]
In the lab meeting, there was a request to be able to send a query result list to an external resource such as KEGG, string, ageli
i.e. a "send to" option

**Comment by Antonialock** [comment]
from Val (email)
"I think this would  clutter the results page, but we can add this as a download extension option..."

**Comment by ValWood** [comment]
consider with
https://github.com/pombase/website/issues/576

**Comment by Antonialock** [comment]
yes they want the option to cherry pick within their list.

maybe this should be a separate option to "trim" a query list to create a new results list?

**Comment by ValWood** [comment]
Hmmmm

**Comment by ValWood** [comment]
moon on a stick ;)
They can make  a new user defined  list  ;)

The check boxes would work.... but I'll put this at low priority

**Comment by Antonialock** [comment]
> moon on a stick ;)
> They can make a new user defined list ;)

yes but that would require downloading the results and do the manipulation outside of pombase....guess they wanted the ability to avoid the extra step :-)

**Comment by ValWood** [comment]
They can make a sub-list of the things they want to delete and subtract it ;)

**Comment by ValWood** [comment]
replaced by 
https://github.com/pombase/website/issues/595
?

**Comment by Antonialock** [comment]
no this ticket is about a "send to" external resource

**Comment by ValWood** [comment]
I don't think we should do that. How would we decide which resources. They can easily do this themselves.

**Comment by ValWood** [comment]
It would be a hassle I think... For instance for some (like string)  I don't think you can do an automatic list submission because you  need to answer questions and confirm things...

I'll keep it open as blue sky, it might be something which becomes a possibility later

**Comment by ValWood** [comment]
I'm moving this to future as  I don't know how it would work really.
