### ISSUE TITLE
new menu item: upload gene list

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#596]
In the old pombase there was a menu item that took you to the gene list upload option in the advanced search. Would it be possible to reinstate this? (user request)

**Comment by ValWood** [comment]
Should we add this back under search menu?

**Comment by Antonialock** [comment]
I guess so, it's just really a quick link (and a bit ugly imo - I seem to remember we added it because not everyone thought it was intuitive to find this option in the advanced search).

**Comment by mah11** [comment]
I cannot do this at present, because I don't know how to link to the search with any specific "starting point" selected (or even if it's possible).

**Comment by ValWood** [comment]
Ah right, that is more complicated then.

**Comment by kimrutherford** [comment]
> or even if it's possible

It's not possible at the moment.  It add a way to do that.

**Comment by ValWood** [comment]
Do this if quick, if not swap "quick" for "low priority" for now...

**Comment by kimrutherford** [comment]
The done now and in the main site.  Let me know if you'd like to change any wording.
