### ISSUE TITLE
Rewording in sequence download section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#597]
In the lab meeting, people thought that "include X bases upstream/downstream" sounds ambiguous. Change wording to "include flanking regions"?

**Comment by ValWood** [comment]
Any objections?

**Comment by ValWood** [comment]
Will this work? They need to specify a base number

That would be 
include   bases  of flanking region

Its quite a bit longer...

(although we have the word "include" twice currently....)
 Include 5'UTR
Include  [ ]   bases upstream

maybe this can combine?

**Comment by ValWood** [comment]
Oh I see. Scrub that.

Include UTR
Include x bases flanking UTR
?

**Comment by Antonialock** [comment]
but it's not just flanking the UTR, it could also be CDS if you don't have UTR ticked

**Comment by ValWood** [comment]
How many people thought that it was confusing currently?

**Comment by ValWood** [comment]
OK so just
Include x bases flanking

is that what we want?

**Comment by mah11** [comment]
Actually, I like the current wording better than any of the suggestions in this ticket, but I don't know whether it's me or Jürg's lab who is/are he outlier. In any case, I am not choosing this hill to die on.

**Comment by Antonialock** [comment]
personally I don't have a preference, they seem to mean the same thing to me? 

Maybe the problem is not the wording but how it is spaced from the UTR tick box?

Currently it looks like it is an option to extend from the UTR (if you have that ticked) - but it is not, if you don't have the UTR ticked you extend from the CDS

possible fixes:
-swap the ordering of "include 5'UTR" & "include X bases upstream"
- remove the indentation from "include X bases upstream"

![screen shot 2017-11-02 at 11 33 00](https://user-images.githubusercontent.com/12727506/32323961-a49dcf6a-bfc1-11e7-85fe-b7747c6f6f7f.png)

**Comment by Antonialock** [comment]
or like this

CDS sequence and:
- Include X bases upstream
- include 5' UTR [ ]

**Comment by ValWood** [comment]
I think you are correct, reordering might work better. I admit it is a little confusing. I got confused initially....

**Comment by ValWood** [comment]
I think the reason it is like it is, is to try to make it clear that if you select the UTRs the flanking regions will be in addition.

Of course, all of this will be less confusing when the colouring is back......

**Comment by kimrutherford** [comment]
> "include X bases upstream/downstream" sounds ambiguous

I thought "upstream" and "downstream" were quite common?

> I think the reason it is like it is, is to try to make it clear that if you select the UTRs the
> flanking regions will be in addition

Yep!

**Comment by Antonialock** [comment]
Yes, I don't think the problem is in the wording, I think it is in the placement of the "Include X bases upstream..." row. It currently looks like it's an option IF you have UTRs ticked. But it is not dependent on ticking the UTR box.

I think we just need left align these two rows, and (maybe) put the checkbox on the RHS of the text:
Include 5' UTR [] 
Include X bases upstream

**Comment by kimrutherford** [comment]
> It currently looks like it's an option IF you have UTRs ticked. 

Ah, thanks.  I understand now.

I like your idea of putting "Include X bases upstream" first.

**Comment by kimrutherford** [comment]
I've made some tweaks to the text and style of the sequence section.  I haven't put the tick boxes last yet.

Does this layout help?:

![screenshot from 2017-11-07 13-45-33](https://user-images.githubusercontent.com/90474/32471460-4a753a3c-c3c2-11e7-8d6a-5717af8c5825.png)

**Comment by Antonialock** [comment]
I think it looks good now :-)

**Comment by kimrutherford** [comment]
> I think it looks good now :-)

Great!
