### ISSUE TITLE
BIoGRID data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#598]
There appear to be duplicate annotations.
See psm3 page (psm1 annotations duplicated)
![psm3 page](https://user-images.githubusercontent.com/7359272/32282871-b29cc9ce-bf1a-11e7-9446-74e2e24e9d1c.jpg)

**Comment by mah11** [comment]
I don't see any duplication - every psm1 interaction there has something different from the rest (i.e. each is a unique combination of direction, evidence, and paper).

**Comment by ValWood** [comment]
Oh some are western...

**Comment by ValWood** [comment]
wouldn't it be nicer to group by gene than evidence type?

**Comment by Antonialock** [comment]
yes
