### ISSUE TITLE
physical/genetic interactions section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#599]
Could we group by gene rather than evidence type? #598

**Comment by kimrutherford** [comment]
I've changed the order.  It should be in tomorrow morning's update.

**Comment by Antonialock** [comment]
Perfect! could you also alphabetize on gene name?

**Comment by kimrutherford** [comment]
It's now ordered by "Interacting gene".

How should the interactions be ordered on publication pages.  eg. https://www.pombase.org/reference/PMID:26771498

**Comment by ValWood** [comment]
alphabetically by gene first, interactor second?

**Comment by ValWood** [comment]
@mah11  @Antonialock  OK?

**Comment by mah11** [comment]
no prob

**Comment by kimrutherford** [comment]
> alphabetically by gene first, interactor second?

OK, that's done and will be in the next update.
