### ISSUE TITLE
add "coding sequence length" to transcript section

### ISSUE THREAD

**Issue by mah11** [pombase/website#60]
This would be the length of the predicted coding sequence, i.e. the sum of the lengths of coding exons (or coding parts of exons). I guess this could go under "Transcript Structure", either above or below the table of coordinates, if the display organization remains relatively unchanged.

**Comment by ValWood** [comment]
This has a dependency. 
We have no ticket about  the transcript section contents etc.
Although I think it has little use until we curate alternative transcripts, so even this part can wait.

- [ ]  open ticket for transcript section contents

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/350

move this to transcript section ticket if we decide to reinstate that section.

**Comment by ValWood** [comment]
moved to https://github.com/pombase/website/issues/350
