### ISSUE TITLE
gene page coordinates

### ISSUE THREAD

**Issue by ValWood** [pombase/website#600]
I notice that we represent the transcript coordinates.

Don't we want this to be the CDS start and end? I think that is what most people would expect?

rec27 is
Genomic location | II, 758042-757399 (644nt)

rather than
758042..757566..

**Comment by ValWood** [comment]
Instead add CDS start and end in addition

**Comment by mah11** [comment]
see https://github.com/pombase/website/issues/59#issuecomment-305459606 and the earlier comment it links to

**Comment by ValWood** [comment]
Longer term, consider putting all  coordinate flavours in the sequence section

**Comment by kimrutherford** [comment]
See: #59
