### ISSUE TITLE
Advanced search: trim the results list

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#601]
From feedback in the group meeting, and following on from #595  .

They would like the ability to trim a results list in the advanced search (e.g. using tickboxes or similar) to create a customized results list

**Comment by kimrutherford** [comment]
> create a customized results list

Does that mean we'll need to store these lists for when the user comes back later?  Will the lists need to be named?

Or do they need to select some genes because they just want to download a subset of the results?

**Comment by Antonialock** [comment]
I think the neatest way would be to trim the list and save it as a new query result. It would probably be good to be able to name the new list. 

The people requesting it have obviously missed this functionality and it seems like it would be useful to them, but I'll stick this at low priority, we could bump after naming lists is implemented?

**Comment by ValWood** [comment]
This will be a long way  away...

**Comment by ValWood** [comment]
We can discuss the feasibility of this when you get onto more customization options. This probably won't be until the spring....

In the meantime i will add "curators discuss" so you know you don't need to look at it yet. We can think about how it could mech with other download options

**Comment by kimrutherford** [comment]
> I think the neatest way would be to trim the list and save it as a new query result.

I've done an experimental implementation of that in pombase-dev.  If you go to a results page with less the 500 genes, there's now a button labelled "Selection mode" (I don't think that's a great name).

If you click "Selection mode", tick boxes appear beside the genes and a "Filter" button replaces the "Download ..." button.  If you tick some boxes, then click "Filter" you get a new results page and the query that creates the results is added to the query history.

This is only in pombase-dev: http://pombase-dev.bioinformatics.nz/query

If it's useful I'll add it to the main site.

> It would probably be good to be able to name the new list.

That's not done.  :-)

**Comment by Antonialock** [comment]
Great!

Two things:
- add the ability to select all or none
- add a mouseover to explain that this can only be done for lists shorter than 500 genes (if there really needs to be restricted?)

**Comment by Antonialock** [comment]
seems to work for most intervals but some don't show
<img width="624" alt="screen shot 2017-11-14 at 13 46 30" src="https://user-images.githubusercontent.com/12727506/32783071-685c0596-c942-11e7-9522-1194bbdaee96.png">

**Comment by kimrutherford** [comment]
> seems to work for most intervals but some don't show

Was that on Firefox?

I mostly tested on Chrome where it works well for me.  It seems to work, er, less well in Firefox.

I'll work on it.

**Comment by kimrutherford** [comment]
(Deleting two comments on the wrong issue)

**Comment by kimrutherford** [comment]
> add the ability to select all or none

Good plan.  I'll do that.

> add a mouseover to explain that this can only be done for lists shorter than 500 genes

It does that already.  If you mouse over the "Selection mode" button when it's a long list, there's a popup that says:

    Too many genes for select mode, try the "Gene list" option from the Search menu

> (if there really needs to be restricted?)

I tried a long list and it's very slow.  The browser freezes for seconds after the "Selection mode" button is pressed.  I think we'll be able to make it less restrictive over time as browsers and computer speed improves.

**Comment by kimrutherford** [comment]
> If you go to a results page with less the 500 genes, ...

I've increased that limit.  I've tested on a few different browsers now, including IE, and the speed is OK up to 1000-ish.  So the limit is now 1000.

> add the ability to select all or none

I've added that.  It will be available on the main site mid-morning.

**Comment by Antonialock** [comment]
Maybe small text change from "selection mode" to "trim list" or "cut results"? @mah11 @ValWood

**Comment by mah11** [comment]
Short answer: How about "filter results" or "filter gene list"?

Longer blather: "Filter" would be consistent with the friendly blue "Filter" button that you push after you've picked some genes. That said, I don't mind "selection" much because selecting is what you're doing at the box-ticking step.

I don't like "trim list" or "cut results" - I'm not even sure I would understand that either one meant "choose some of these". It might mean "show less about each of these" or "delete this from the query history".

**Comment by Antonialock** [comment]
"Select results"?

Maybe it's the "mode" I don't like.

**Comment by ValWood** [comment]
"Cherry picker" ;)

**Comment by ValWood** [comment]
Select subset?

**Comment by ValWood** [comment]
Change to "select subset"

**Comment by kimrutherford** [comment]
> Change to "select subset"

It's changed in the code and will be in tommorrow's update.
