### ISSUE TITLE
URGENT advanced query FYPO and GO search broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#605]
~~dev~~ preview and www ;(

**Comment by kimrutherford** [comment]
I've restarted the server which seems to have fixed the immediate problem.  I'll see if I can find out why it broke.

**Comment by kimrutherford** [comment]
I've made some fixes, including updating the version of Lucene/Solr (which powers the query builder autocompletion).  I hope that makes things more reliable from tomorrow.

**Comment by ValWood** [comment]
seems ok  (GO FYPO), but I don't think modification is working
(tried phosphorylated)

**Comment by kimrutherford** [comment]
It looks like modification searching been incorrectly configured for ages.  It's fixed that and should be working tomorrow.

**Comment by ValWood** [comment]
Its pretty difficult to know what to type in this box if you just  start typing you are exposed  to the full ontology which is a bit scary and makes you think you don't know how to describe what you are looking for.

maybe a prompt would be useful  to show that simple strings like "phosphorylated residue" work too

**Comment by kimrutherford** [comment]
> It's fixed that and should be working tomorrow.

It's fixed now.

**Comment by kimrutherford** [comment]
I haven't been able to work out why the auto-complete stopped working.  I've set up a monitor so I'll now at least get an email alert if it fails again.
