### ISSUE TITLE
New front page rotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#608]
Explore PomBase: Over 200,000 curated annotations…
PomBase has integrated over 200,000 manually curated gene specific annotations. See our \<Resource Metrics> page for more literature curation progress reports.

Explore PomBase: Building Networks:
PomBase is using manually curated Gene Ontology annotation to generate biological process specific networks. Part of the cytokinesis network is displayed. Currently available networks can be accessed from the \<GO slim> page.

Explore PomBase: Help! 
PomBase provides extensive <documentation> and answers to *xxx* \<FAQs>
but please mail the \<helpdesk> if you can’t find the information you are looking for

Community Curation in Canto
PomBase has pioneered a community curation system that enables researchers to contribute publication-based annotations directly to database curators. To participate, search for the PuBMed ID of your paper \<here> or contact the \<helpdesk>.
(use Canto logo as image)

Explore PomBase: Motif search
The \<Protein Motif Search Tool> finds any user-defined amino acid sequence. Search supports exact match queries, wildcards, gaps, and ambiguity codes.

(I put images for these in the drop box folder)

**Comment by ValWood** [comment]
Note that some of the text is not visible because git hub thinks it is mark up... you can see it in edit mode..

**Comment by ValWood** [comment]
Name that Gene.
4020/5070 fission yeast protein coding genes now have assigned primary names. We encourage all authors and reviewers to ensure that gene names are registered prior to publication. Visit our <Gene Registry page>, and the <S. pombe gene naming guidelines> for mor info.

**Comment by ValWood** [comment]
Disease Gene Orthologs
Over 500 S. pombe genes whose human orthologs have been implicated in disease are manually annotated with terms from a small in-house vocabulary. See the <disease gene FAQ> for information on searching these genes.

**Comment by ValWood** [comment]
![the pics](https://user-images.githubusercontent.com/7359272/32408818-3d6e67f0-c197-11e7-816a-d0a5fad93146.jpg)

**Comment by kimrutherford** [comment]
> Note that some of the text is not visible because git hub thinks it is mark up... you can see it in edit mode.

Fixed by adding some backslashes.

**Comment by kimrutherford** [comment]
After a bit of bug fixing, the new panels are in the dev site:
  http://pombase-dev.bioinformatics.nz/archive/explore

They look good!  Thanks Val.

If you spot any typos, please let me know.  Or edit the config file (pombe-embl/website/pombase_v2_config.json in SVN) and then let me know so I can re-release.

**Comment by kimrutherford** [comment]
Now live on the main site:
https://www.pombase.org/archive/explore

**Comment by Antonialock** [comment]
does this need a legend?
![screen shot 2017-11-07 at 17 18 36](https://user-images.githubusercontent.com/12727506/32507610-d2ef2004-c3df-11e7-8e1f-b0eaf2579121.png)

**Comment by kimrutherford** [comment]
> I have fixed a bunch of typos in the config

Thanks.  I've re-released the site with those fixes.

**Comment by ValWood** [comment]
Didn't you like my "gene naming " picture?
It was a bit cutesy  I guess ;)

**Comment by ValWood** [comment]
need to italicize *S. pombe* on the gene naming do-dah...
Where does it live again?

**Comment by mah11** [comment]
> Didn't you like my "gene naming " picture?

That wasn't me; I didn't touch that line ;)

There are 10 items in the archive but only 9 images in the relevant GitHub directory. Dunno what happened to the naming one.

> need to italicize S. pombe on the gene naming do-dah...
> Where does it live again?

svn pombe-embl/website/pombase_v2_config.json

I tried the markdown syntax when I did my typo fixes, but that doesn't look right on the archive page. I've just committed with html \<em\> tags. If that's not how to do it either I'll leave it for Kim!

**Comment by kimrutherford** [comment]
> Didn't you like my "gene naming " picture?

It was an oversight.  I'll add it.

> I've just committed with html `<em>` tags

Yep, that works.  You can also use underscores or asterisks like:

     _S. pombe_ or *S. pombe*

**Comment by kimrutherford** [comment]
> Didn't you like my "gene naming " picture?

I've added that now.  You'll need to reload: https://www.pombase.org/archive/explore

Is there anything else to do here?

**Comment by ValWood** [comment]
new tickets, for  tweaks, can wait for the next batch....I have more planned...
