### ISSUE TITLE
make sure genome & chromosome files include LTRs

### ISSUE THREAD

**Issue by mah11** [pombase/website#61]
The manually curated LTRs (sys ID beginning with SPLTR) are missing from here:

ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Chromosome_Dumps/gff3/

**Comment by ValWood** [comment]
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=167128

**Comment by ValWood** [comment]
we need a complete list of ftp site data.
describing specific file contents for each file
 I need to do this

**Comment by ValWood** [comment]
transferred to
https://github.com/pombase/website/issues/355
