### ISSUE TITLE
Add a prompt or help text for the query builder modification auto-complete

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#610]
From @ValWood in #605:

Its pretty difficult to know what to type in this box if you just start typing you are exposed to the full ontology which is a bit scary and makes you think you don't know how to describe what you are looking for.

maybe a prompt would be useful to show that simple strings like "phosphorylated residue" work too

**Comment by kimrutherford** [comment]
Let me know what text prompt you'd like for modifications.

**Comment by ValWood** [comment]
"phosphorylated residue"  will do.

**Comment by ValWood** [comment]
e.g phosphorylated residue (MOD:00696)

**Comment by kimrutherford** [comment]
That's done for tomorrow's update.

**Comment by kimrutherford** [comment]
> That's done for tomorrow's update.

I can't the configuration but found that the configuration for the prompt was being ignored.  I've fixed that for tomorrow.
