### ISSUE TITLE
Sequence box and browser image too wide on small display

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#613]
Doesn't look great on my phone. Just cosmetic I suppose.

![img-2383](https://user-images.githubusercontent.com/12727506/32602583-84d18f32-c53e-11e7-90e8-963813050295.JPG)

<img width="496" alt="screen shot 2018-07-05 at 08 18 16" src="https://user-images.githubusercontent.com/12727506/42307951-01b355aa-802c-11e8-89c2-77a54e742095.png">

**Comment by ValWood** [comment]
@Antonialock  can we live with this?

 a) it isn't terrible. I guess this is due to the fact  that it is convention to display sequence at 60 residues per line?

b) Anyone who is looking at sequence on their phone is a nutter....

**Comment by Antonialock** [comment]
I'll put at low priority, but I don't think we should close for closing's sake (maybe easily fixable as part of something else..) plus then we'll know we know about it even if we forget..

**Comment by ValWood** [comment]
OK, phone label is good, then I can filter easily :)

**Comment by kimrutherford** [comment]
The sequence section now looks like this on small screens:

![small-screen-seq-2](https://user-images.githubusercontent.com/90474/46271828-d1d04680-c5aa-11e8-839e-99b91b9f6fcd.png)

It looks more or less the same on big screens.
