### ISSUE TITLE
no "given name" if not assigned

### ISSUE THREAD

**Issue by ValWood** [pombase/website#615]
historically we populated this column with the "sys id"

I think we might need to, because if you download with this column and is unassigned it will be blank?
@mah11 @Antonialock  thoughts?

![prob](https://user-images.githubusercontent.com/7359272/32606154-1ff39cc8-c54c-11e7-9e1d-02fa4a8057c1.jpg)

**Comment by ValWood** [comment]
Let's "leave  it and see".

The only issue might be if you do a query and only download primary names....

**Comment by Antonialock** [comment]
> The only issue might be if you do a query and only download primary names....

Yeah I think people might moan for that reason. Then again, the primary names are just really an extra for people's heads when reading papers/talking about genes. People should be encouraged to use sys IDs as far as possible when dealing with gene lists.

**Comment by ValWood** [comment]
Yeah that's what I was thinking.... they should use sys IDs really...let's wait and see...

**Comment by ValWood** [comment]
ignoring for now
