### ISSUE TITLE
Advanced search, missing chromosome number in result download

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#616]
Maria requested that we re-implement stating what chromosome a gene is on when downloading results from the advanced search (e.g. I II or III). 

Hoping this will be quick to do..

**Comment by kimrutherford** [comment]
I've added a Chromosome option to the download pop-up.  It will be in the main site by the morning.

**Comment by kimrutherford** [comment]
The Chromosome option is available in the main site now.  Could you close this issue if that's what Maria needed?

**Comment by Antonialock** [comment]
Maria says thanks!
