### ISSUE TITLE
What happens to NOT annotations with the slim?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#617]
I don't know if this was fixed, but I can no longer find an example

It used to be the case that if a gene had a NOT annotation to a specific term, and an annotation to a more general term, it did not get slimmed to the more general term.

There used to be an example
biotin transporter/biotin transport, I think
https://github.com/pombase/website/issues/364

but I can no longer find this annotation

**Comment by Antonialock** [comment]
looks fine, see chp1?

**Comment by Antonialock** [comment]
(it slims to chromatin organization despite NOT annotations)

**Comment by ValWood** [comment]
Brill, I can x that off the list ....
Paper first draft still not ready....sooon....

**Comment by ValWood** [comment]
This seems to be still an issue
SPAC1B3.15c	transmembrane transporter (predicted)

has filtered  annotations to  "transmembrane transport"
(or I thought it did?)

( maybe the IEA is filtered), this probably isn't bad....need to think about this one...


it IS a  transmembrane transporter, just NOT biotin

**Comment by kimrutherford** [comment]
I'll need help to understand this one.   Maybe a quick Skype chat sometime?

**Comment by ValWood** [comment]
and another
https://www.pombase.org/gene/SPBC1289.16c

yep....  can discuss thurs...

**Comment by ValWood** [comment]
migrate to chado tracker
