### ISSUE TITLE
Pages with sidebar on iphone

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#619]
![de4db20b-c1da-41ab-a5d2-e503cc8ad90b](https://user-images.githubusercontent.com/12727506/32828246-6f5a20d6-c9e6-11e7-814c-720433419f3d.png)

**Comment by Antonialock** [comment]
![9ccf5114-72a5-4465-bb4e-2e468f3f3776](https://user-images.githubusercontent.com/12727506/32828351-c1d0ecfa-c9e6-11e7-85d6-f79e1cfb7d31.png)

**Comment by ValWood** [comment]
OK, this one doesn't look so good...

**Comment by Antonialock** [comment]
static pages still look a bit rubbish. However, I guess most of these pages are not suitable for "phone browsing" (unlike gene pages e.g. when you quickly want some info on a gene you hear about in a talk) and you'd use a laptop/desktop to access them, so not high priority in any way...

**Comment by Antonialock** [comment]
looks different now
