### ISSUE TITLE
file or PMID list for LinkOut

### ISSUE THREAD

**Issue by mah11** [pombase/website#621]
We have the go-ahead to send NCBI a file of URLs to add to PubMed records under the "LinkOut" listings.

I am about to create and send a small sample file for testing. (I'me going to start with their .csv format. If they hate that, they've got an XML format to try next.) When they're happy with it, we can start making the file for all of PMIDs that we want to link.

1. I can get a list of PMIDs and use a quick script to create the file; or

2. We (meaning Kim) can automate file generation, and I can send updates to NCBI periodically.

3. File submission is via FTP, so I don't know if Kim could automate both file generation and submission. But if it's both technically feasible and allowed by the NCBI setup, it'd be an option.

In any case, we have to decide which papers to link. I'm leaning towards papers in Canto that fit:

    triaged BUT NOT (wrong organism OR loaded in error)

@kimrutherford @Antonialock @ValWood - Two questions for all:

- any counter-proposals for which papers to include?

- any preference between options 1 and 2? I'd be happy either way. Or any knowledge relevant to option 3 (what we'd need to know from them)? I don't have our login credentials yet; I get 'em when the sample file passes their tests.

For option 1 I'll need the list of PMIDs from Kim. For any of the options we should create a home for the files (PMID list, providerinfo.xml, and resources.csv link file) somewhere - svn seems like a good place.

**Comment by kimrutherford** [comment]
> 2. We (meaning Kim) can automate file generation, and I can send updates to NCBI periodically.

We could definitely do that as part of the overnight Chado load.  

> 3. File submission is via FTP, so I don't know if Kim could automate both file generation and submission.

I think that should be possible.

> triaged BUT NOT (wrong organism OR loaded in error)

The Chado query below gives 9062 publications for that.  I've copied the output to:
  https://www.dropbox.com/s/me8demfj3oz5n7j/triaged_publications_issue_621.tsv?dl=0

SQL:
```sql
select uniquename, pp.value from pub
  join pubprop pp on pp.pub_id = pub.pub_id
  join cvterm ppt on ppt.cvterm_id = pp.type_id
 where ppt.name = 'canto_triage_status' and
       pp.value <> 'Loaded in error' and pp.value <> 'Wrong organism'; 
```

We can generate the file from the command line with:
  psql --field-separator=$'\t' --no-align pombase-build-2017-11-11 -c "select uniquename, pp.value from pub join pubprop pp on pp.pub_id = pub.pub_id join cvterm ppt on ppt.cvterm_id = pp.type_id where ppt.name = 'canto_triage_status' and pp.value <> 'Loaded in error' and pp.value <> 'Wrong organism';"

**Comment by mah11** [comment]
Cool, thanks.

I guess the next thing is to see what the LinkOut folks say about the test files I sent, and take it from there. If the CSV works, it'll be dead easy for either of us to generate it from the PMID list. I'm assuming I'll also find out how to use their FTP setup so we'll know whether we can automate .....

**Comment by Antonialock** [comment]
Def not pass on loaded in error :-)

Wrong organism could have some complementation or expression data - did we
check for that or just canto? I think I normally change triage status but
things can be forgotten..

> --
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
I checked  all "wrong organism" with annotation yesterday. The ones with complementation data are now "curated".

I think we shouldn't display the pages for  "wrong organism" ....we can reassign if we find data in them, but no need to display the pages right now unless we reference them.

**Comment by mah11** [comment]
I don't think it's that big a loss if a few papers don't have LinkOut links to us from PubMed, if they fit the "wrong organism apart from a snippet of complementation or whatever" description.

**Comment by mah11** [comment]
Blue touch paper lit - I have uploaded our data for LinkOut at NCBI.

On Thursday's call we should have a quick chat about updates. The LinkOuts may be live by then ...

**Comment by mah11** [comment]
It works (hooray!). Now all we need for updates is a list of PMIDs, just the numerical part, with the filename 'holdings.uid'. Update it at the NCBI ftp site (URL and login details emailed to Kim to be stored someplace sensible). Can still chat on Thursday if there are any questions.

**Comment by mah11** [comment]
Update: we've heard from NCBI that they don't want to link to all of our publication pages, just the ones that have curated data. So we need a list of PMIDs for any paper that has any annotation in Chado. No other criteria - any type, and any triage status, as long as the annotations are in place to appear on our pub page.

**Comment by kimrutherford** [comment]
Chado query to return the PMID of publications with annotation, ordered by PMID:

```sql
SELECT uniquename
FROM pub
WHERE uniquename LIKE 'PMID:%'
  AND pub_id IN
    (SELECT pub_id FROM feature_cvterm
     UNION
     SELECT pub_id FROM feature_relationship_pub)
ORDER BY substring(uniquename FROM 'PMID:(\d+)')::integer;
```

**Comment by kimrutherford** [comment]
I've added the PMID query to the load script so from tomorrow we should get a file of the PMIDs each day.

**Comment by mah11** [comment]
Excellent. The latest email from NCBI says they don't want daily updates at their end, but weekly or monthly would be fine (I have no preference). I'm still happy do manual updates for a while if need be.

Quite a bit of that email boils down to "just update the holdings.uid file of IDs at least once a year but no more than once a week". The rest is either additional info that doesn't require action by us, or about to go in a new ticket.

**Comment by kimrutherford** [comment]
> I've added the PMID query to the load script so from tomorrow we should get a file of the PMIDs each day.

For the record, it's here and updated nightly:
  https://curation.pombase.org/dumps/latest_build//publications_with_annotations.txt

**Comment by ValWood** [comment]
@mah11  could you make a post to pombelist to  explain this feature?

Also  could you send me you NCBi contact e-mail and I'll mail to suggest that the "PomBase link" is always there. I was going to do it at the weekend but I could not find  the person's e-mail (I know it is unlikely to happen but  you never know....). The current behaviour is a bit crazy because the link expires really quickly. This means the link may be there when you access a perp, but then it isn't there a short while later...it's all a bit confusing.

I will wait until they are getting paid again.....

**Comment by mah11** [comment]
I'll announce that PomBase is in LinkOut.

LinkOut contact info at https://www.ncbi.nlm.nih.gov/projects/linkout/

To be honest, I now regret drawing attention to the icons, because they've eaten up far too much of our time already. I've come to think we should just revert to "normal" links to PubMed for predictable behavior; I don't really understand why they would put a PomBase icon in what is otherwise the section for full text links anyway, since we aren't providing full text. It's turning out to be more confusing than useful.

**Comment by ValWood** [comment]
It would bring lots more people into the site if it were there permanently though...(despite the odd name for the section heading). The current links are so hidden away. I think it is worth a short time investment to ask if it is possible to have the icon there permanently so I'm happy to follow up on that...

**Comment by Antonialock** [comment]
Yeah, they should make the links more prominent. I had never seen them before (I asked 3 or 4 others if they ahd seen them and they hadn't either..)

**Comment by ValWood** [comment]
can close this.
