### ISSUE TITLE
add ortholog gene description

### ISSUE THREAD

**Issue by ValWood** [pombase/website#622]
we used to have this
feedback from survey

**Comment by ValWood** [comment]
SGD

For SGD display first part of description (upto ;) and have rest visible as (more...)
Protein kinase that regulates the G2/M transition; negative regulator of the Cdc28p kinase; morphogenesis checkpoint kinase; positive regulator of sphingolipid biosynthesis via Orm2p; phosphorylates a tyrosine residue in the N-terminus of Hsp90 in a cell-cycle associated manner, thus modulating the ability of Hsp90 to chaperone a selected clientele; localizes to the nucleus and to the daughter side of the mother-bud neck; homolog of S. pombe Wee1p; potential Cdc28p substrate 1 2 3 4 5

**Comment by ValWood** [comment]
HGNC
display "approved name" which is a short product description

**Comment by ValWood** [comment]
SGD-> or mouse over....

**Comment by kimrutherford** [comment]
> Protein kinase that regulates the G2/M transition; negative regulator of the Cdc28p kinase; morphogenesis ...

I just noticed that there is a shorter column that looks a bit like the pombe products.  It's column 6 in the SGD file:
  http://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.tab

(Docs: https://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.README )

Is that better or worse than the description in column 16?

**Comment by kimrutherford** [comment]
I've added the code to load the SGD and HGNC gene descriptions into Chado.  I'll make the web code changes once I have a Chado with the description in.

**Comment by ValWood** [comment]
>Is that better or worse than the description in column 16?

that is the alias (akin to our gene name description), and not always populated (I think)

we should stick with the description as it is more informative.

**Comment by kimrutherford** [comment]
This should be working after today's update.
