### ISSUE TITLE
multiple identical entries not merged in gene list upload

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#623]
When using the gene list upload feature in the advanced search, identical entries are not merged (both when adding sys IDs and when adding primary gene names)

![screen shot 2017-11-17 at 18 48 37](https://user-images.githubusercontent.com/12727506/32963485-0331f51c-cbc8-11e7-82ae-6d7f01d9d25d.png)

**Comment by kimrutherford** [comment]
I've fixed that.  It's in pombase-dev now and should be in the main site on tomorrow morning after a bit of testing.

**Comment by kimrutherford** [comment]
That in the main site now.
