### ISSUE TITLE
query history gene list "name"

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#624]
When you upload a gene list, if you add sys IDs these are displayed as sys IDs (even if the genes have primary IDs), if you add gene names then the name is displayed.

Do we want to change the sys IDs to primary names? I know we will implement  the ability to add a name to the list at some point but until then? Sys IDs are so hard to read

![screen shot 2017-11-17 at 18 48 37](https://user-images.githubusercontent.com/12727506/32963610-72abc53a-cbc8-11e7-8ee0-6d769bffa1c0.png)

**Comment by ValWood** [comment]
I agree names would be nicer for display (but you can't really see the full list and  most people would probably just change the list for a more sensible query description when this is available).

**Comment by mah11** [comment]
Names are nice to look at. Another thing I think might be helpful is (if technically feasible without too much hassle for Kim) to add a snippet of text as a reminder that a history item was a gene list search, e.g. "gene list [yfg1 yfg2 yfg17 ]".

**Comment by kimrutherford** [comment]
I've change the query history to show the gene names where possible.  It's in pombase-dev now.  It should be in he main site mid-morning tomorrow after I do some testing.

One catch is that it will only show the gene names for new queries.  Queries that are already in your history won't change.

**Comment by kimrutherford** [comment]
> e.g. "gene list [yfg1 yfg2 yfg17 ]"

That's a quick change.  Is that the format you'd like?

**Comment by ValWood** [comment]
looks good

**Comment by kimrutherford** [comment]
There was a bug in the query history which meant the gene names weren't being saved.  I think I've fixed that now in pombase-dev.  Could one of you do a quick test that you can run a gene list query?  I'd appreciate if you could then reload and check the the history looks as expected.  If that's all OK I'll re-release the main site.

**Comment by ValWood** [comment]
all good from list and file

**Comment by kimrutherford** [comment]
Thanks for checking.  The main site is updated now.

> e.g. "gene list [yfg1 yfg2 yfg17 ]"

That done too.
