### ISSUE TITLE
duplicate in query history

### ISSUE THREAD

**Issue by ValWood** [pombase/website#626]
This isn't a big deal but I never saw this before. Usually when I run an identical query it just reruns the exisitng one (or at least that is what I thought).

This is the first time I ever saw a duplicated identical query:

![duplicate](https://user-images.githubusercontent.com/7359272/33046645-c7dd4f5a-ce49-11e7-8d26-a51cc5d426ea.jpg)

**Comment by kimrutherford** [comment]
They aren't quite the same, the bracketing is different.  The code is not smart enough to spot that they're equivalent.

**Comment by ValWood** [comment]
so it is!
