### ISSUE TITLE
Should we have pages for "Wrong organism" and "Loaded in error"?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#628]
Just to check: is there any reason to have publication pages for "Wrong organism" and "Loaded in error" pages?

Currently all papers in Chado get an automatic page which I assume isn't what we want.  eg. https://www.pombase.org/reference/PMID:11064363  - "Wrong organism"

Should I filter out the "Wrong organism" and "Loaded in error" papers?

**Comment by ValWood** [comment]
Yes. You can even delete "loaded in error papers". They are usually manual load.
But there is no reason to have publication pages for either of these categories.

**Comment by mah11** [comment]
I agree.

**Comment by kimrutherford** [comment]
I tried remove the "Wrong organism" and "Loaded in error" but got a error.

There are a bunch of publications triaged as "Wrong organism" that have annotations:
  https://www.dropbox.com/s/4rqsnptcvhojyit/wrong_organism_annotation_counts.txt?dl=0

Should we have publication pages for those?

**Comment by ValWood** [comment]
We need to change these to "curatable". They were  initially triaged as "wrong organism", but  I think  @Antonialock  went through at some point and re-assessed and found curated data in lots of them.

We should also double check that they went through canto in case they are BIOGRID annotation only so far....

**Comment by kimrutherford** [comment]
>  should also double check that they went through canto in case they are BIOGRID annotation only so far....

I'll check which ones were annotated in Canto.

**Comment by kimrutherford** [comment]
> We should also double check that they went through canto in case they are BIOGRID annotation only so far....

I checked and 3 of the "Wrong organism" publications have a Canto session:

aa4b7241dfd0162e
1ac42b2513a020e8
b05133c13a54a182

The 1st and 3rd of those having been started and the middle one has one gene added and says "Reason given for no annotation: wrong organism"

So no annotation from Canto.

I did a grep of the contig files too.  All of the "Wrong organism" publication PMIDs are in the contig files so probably there is annotation for each of them.  I didn't check though.

**Comment by ValWood** [comment]
I looked at these 99, I retriaged  quite a few  but  all those remaining are a paper used to support either

disease association
or ISS to a GO term 

we could include any paper which  is  in a dbxref, but exclude any wrong organism that we do not "cite" for anything?

**Comment by mah11** [comment]
> we could include any paper which is in a dbxref, but exclude any wrong organism that we do not "cite" for anything?

I like this idea. It would also be good for the LinkOut set in #621.

**Comment by kimrutherford** [comment]
> we could include any paper which is in a dbxref, but exclude any wrong organism that we do not "cite" for anything?

I've changed the code so that "Wrong organism" and "Loaded in error" get removed, but only if they have no annotation.  Is that what you meant?

**Comment by ValWood** [comment]
I think so....

**Comment by kimrutherford** [comment]
Great.  The change will be in the main site tomorrow.
