### ISSUE TITLE
unresolved external link? for expression profiling etc (see also issues/1821)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#629]
/controlled_curation="term=external_link, deletion mutant expression profiling; db_xref=ArrayExpress:E-MTAB-2543"

**Comment by kimrutherford** [comment]
What do I need to do here?

**Comment by ValWood** [comment]
not urgent, but

any
controlled_curation="term=external_link

should be displayed in the External link section  as

Type: Expression
Name: deletion mutant expression profiling
Link:  ArrayExpress:E-MTAB-2543    =https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-2543/samples/?full=true

I think? @Antonialock ?

**Comment by Antonialock** [comment]
You asked me to hold off this ticket last summer but raise the priority if it is needed now:

https://github.com/pombase/curation/issues/550

**Comment by ValWood** [comment]
yep we should bring this back in now...

**Comment by ValWood** [comment]
I flagged this one as "waiting for feedback" until
pombase/curation#550 is done

**Comment by kimrutherford** [comment]
Am I missing something or could we add `/db_xref="ArrayExpress:E-MTAB-2543"` or `/db_xref="EMD:2542"` to the gene annotation?
We can then configure things so those prefixes generate entries in the External links section.  Like we do for `/db_xref="SPD:51/51C03"`.

**Comment by ValWood** [comment]
I tgink that is the plan, but we don't wasn't to do it in Artemis.

following back though 
pombase/curation#550 
there is a spreadsheet
https://docs.google.com/spreadsheets/d/1unk_qLm1C41DB_82Qtu7xbe6D5rx3w566vaxgFnVN9E/edit#gid=0

we planned to put these in the external references section, but they could appear on the publication pages too.

We can look at this on an upcoming call. Probably not this week.

**Comment by ValWood** [comment]
pombase/curation#550 is done
forwards to 
https://github.com/pombase/website/issues/1821

**Comment by ValWood** [comment]
PMID:29235477
Links need adding to external links spreadsheet:

Mal3 
pdb https://www.rcsb.org/structure/5MJS (Should the the pdb linking should happen automatically eventually?)
Electron Microscopy Data Bank https://www.ebi.ac.uk/emdb/EMD-3522

These links could also be included on the publication page using:
https://github.com/pombase/website/issues/1802

**Comment by ValWood** [comment]
Decided not to do this.
