### ISSUE TITLE
browser track for Dutrow UTR/ncRNA dataset

### ISSUE THREAD

**Issue by mah11** [pombase/website#63]
Val:
"We should [include] this dataset in transcriptomes too, since the curated Lantermann dataset is based on it.

This is the dataset in GEO.
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE11619
I don't see it in Array Express.

We only want the transcriptome data on a track so the microarray hybridization can be ignored. It isn't very clear which files this would be......"

**Comment by ValWood** [comment]
see https://github.com/pombase/website/issues/1441
