### ISSUE TITLE
Confusing not to see expression level

### ISSUE THREAD

**Issue by ValWood** [pombase/website#632]
https://www.pombase.org/reference/PMID:11683390

Confusing not to see expression level of wt here
cig1Δ cdc13+ cig2Δ   (knockdown)

We might already have a ticket by this opened by Antonia

(Nurse lab)

**Comment by kimrutherford** [comment]
In Canto we format it like: "cdc13+[Knockdown]".

Should we do the same in the web site?

**Comment by Antonialock** [comment]
I think I have at least mentioned it before, I seem to have said something similar in  #163 but that ticket isn't relevant any longer because of other changes.

Kim I think that would work

**Comment by kimrutherford** [comment]
> Kim I think that would work

Great, I'll do that then.

**Comment by ValWood** [comment]
yes  I thought that you also mentioned it @Antonialock , but I could not find the old ticket.

agree that would work.

v

**Comment by kimrutherford** [comment]
I've added the expression, but it makes the phenotype annotation summaries a bit hard to read.  eg.
  https://www.pombase.org/gene/SPCC18B5.03

Any suggestions for improving things?

**Comment by ValWood** [comment]
I think we only need to include for  [Overexpression]

(isn't that what we did on the old site?)

**Comment by Antonialock** [comment]
On the old site we excluded [Not Assayed]

We included overexpression and knockdown

**Comment by kimrutherford** [comment]
> On the old site we excluded [Not Assayed]
> We included overexpression and knockdown

Thanks.  I removed "Not assayed" and that has helped.
