### ISSUE TITLE
Please remove from pombe slim GO:1901135

### ISSUE THREAD

**Issue by ValWood** [pombase/website#635]
I know I can do this, but I forgot where
Please remove from pombe slim GO:1901135

**Comment by mah11** [comment]
If you mean the table on https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms, it gets filled in by a script, so will automagically catch up after the change is done in GO (and wends its way through the GO release pipeline and our Chado load ...).

**Comment by ValWood** [comment]
I wasn't sure it was changed over yet, I thought it was still hard coded. Kim can you confirm?

v

**Comment by mah11** [comment]
you can see the source here:

https://raw.githubusercontent.com/pombase/website/master/frontend/src/docs/browse-curation/fission-yeast-go-slim-terms.md

The last line calls a script that fills in everything below the documentation links.

**Comment by mah11** [comment]
ok, found the config bit it calls and updated that
(the file in svn)

**Comment by kimrutherford** [comment]
> ok, found the config bit it calls and updated that

Thanks.  The term is gone on the main site now.
