### ISSUE TITLE
add to config wiki

### ISSUE THREAD

**Issue by mah11** [pombase/website#636]
The Config-file wiki page could do with more info about setting up predefined queries, because I got confused trying to follow it for #11.

example (pasted one of Kim's so I know it's good):

    "canned_query:all_diseases": {
      "name": "All disease associated genes",
      "constraints": {
        "term": {
          "termid": "PBO:5000000",
          "name": "disease_associated",
          "single_or_multi_allele": null,
          "expression": null
        }
      }
    },

my questions:
- I figured out that the outermost text ("canned_query:all_diseases" in the example above) is what goes in the app-query-link predefinedQueryName field, but are there any requirements or restrictions on what can go in that field in the config file?

- What's the first "name" used for (the one outside the "constraints" braces, ""All disease associated genes" in the example)? Is it required? For #11 I included some text in the config, but I haven't used it anywhere else.

@kimrutherford - I'm happy to do some wiki edits if you can answer the above questions.

**Comment by ValWood** [comment]
@kimrutherford  ?

**Comment by kimrutherford** [comment]
I haven't done this yet.  I've added the "next" label to remind myself.

**Comment by kimrutherford** [comment]
> but are there any requirements or restrictions on what can go in that field in the config file

It think more or less anything is legal as long as it's a unique for the predefined queries.  That field is the unique ID that the web site uses to look up the query in the configuration.

> What's the first "name" used for (the one outside the "constraints" braces, ""All disease associated genes" in the example)? Is it required?

I probably should have called it `display_name`.  It's currently only required for canned queries because that's the link text that gets displayed to the user for the canned queries list.  For the other predefined queries it's not used but makes sense for it to be the mouse-over text for those links where possible.  I'll have a go at that.

I've started documenting the `predefined_queries` setting but I'm still working on it:
https://github.com/pombase/website/wiki/Config-file#predefined_queries

**Comment by kimrutherford** [comment]
> but makes sense for it to be the mouse-over text for those links where possible. I'll have a go at that.

I had a look and that's possible if we want to do that.  But in most places it's not very useful because the text of the link is quite descriptive - a mouse-over text isn't useful.

So for now that "name" can be left off for non- canned queries.

**Comment by kimrutherford** [comment]
> I probably should have called it display_name. 

And in the `<app-query-link  ...` , `predefinedQueryName` should have been `predefinedQueryId`.  I'm going to make that change locally and see if anything breaks.  It will prevent future confusion.

**Comment by kimrutherford** [comment]
> I'm going to make that change locally and see if anything breaks

I've updated the code and all the embedded query-links in the Markdown files and it all seems OK.  I'll check pombase-dev tomorrow before updating the main site.

**Comment by kimrutherford** [comment]
Midori, could you have a look at the docs and see if there is anything I haven't covered?:
  https://github.com/pombase/website/wiki/Config-file#predefined_queries

Thanks!

**Comment by kimrutherford** [comment]
Thanks.  We can open other issues for other missing docs.
