### ISSUE TITLE
ontology annotations  in advanced search

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#638]
I like that you only see a 'clean' gene list after running an advanced search query. However, it would be nice to be able to see what specific terms different genes are annotated to.

To do this at the moment I have to find the term in the advanced search, go to a gene page of a gene annotated to the term, and then navigate to the ontology term page from there, which is a bit convoluted.

Could we either 
A) hyperlink the ontology terms (see screenshot)  so that one can go there quickly without having to sidestep through a gene page

![screen shot 2017-12-08 at 10 49 59](https://user-images.githubusercontent.com/12727506/33762738-8cc5f5b0-dc05-11e7-9f84-72e5830de8d1.png)

B) be able to toggle to an "ontology view" where we see what child terms the terms are annotated to (may look awkward for combined queries, but shouldn't be a problem? - having said that however I'm not overly interested in seeing what ontology child soup all genes annotated to Nucleus AND sensitive to cyclosporin AND protein kinase, are annotated to so option A might be more logical to do).

**Comment by ValWood** [comment]
Yes that is a bit irritating, hyperlinking the term ID to go to the term page would be great.
+1

**Comment by ValWood** [comment]
DOn't need to discuss...

**Comment by kimrutherford** [comment]
> hyperlinking the term ID to go to the term page would be great.

I've done that.  The change will be in pombase-dev in 15 minutes or so.  pombase-dev will be offline for a minute or two while it updates.

**Comment by ValWood** [comment]
Thanks, useful!
