### ISSUE TITLE
display of protein biding, bridging

### ISSUE THREAD

**Issue by ValWood** [pombase/website#639]
protein binding, bridging,

is when  x binds a and b like:
a-x-b

we need to add 2 binding partners for this and in Canto are forced to do so, in extensions.
However we still need to add a with,IPI  for GO

we have this situation:

![bqt1](https://user-images.githubusercontent.com/7359272/33774075-fb48e8e0-dc31-11e7-80d4-21f81b4881e5.jpg)

from

![from](https://user-images.githubusercontent.com/7359272/33774107-143e385a-dc32-11e7-877a-17d2d0410e63.jpg)

Ideally we would use the "2 binding partners to populate the "with" field  for GO, 
but only display once

**Comment by ValWood** [comment]
from https://github.com/pombase/curation/issues/1793

**Comment by ValWood** [comment]
I'm guessing that I explained this badly, and will need discussion.

**Comment by mah11** [comment]
Try doing it as IPI with=geneA,geneB, and nothing in extensions (has to be in Artemis until https://github.com/pombase/canto/issues/1094 is done). There are a few IPIs with comma-separated 'with' entries already, and the "bridging" annotation for cdt2 looks fine.

**Comment by ValWood** [comment]
OK transferring back to pombase/curation#1793
