### ISSUE TITLE
adjustment to extension ordering

### ISSUE THREAD

**Issue by mah11** [pombase/website#64]
Order annotation extensions by relation. (originally prompted by ticket on where involved_in should fit, as it's newer than the rest.) Documenting preferred order here:

GO:
1. directly_positively_regulates/has_direct_input/ has_input/ has_regulation_target/ binds (these should always be mutually exclusive)
2. involved_in
3. occurs_at, occurs_in (mutually exclusive)
4. any others (e.g. coincident_with)
5. happens_during, exists during (mutually exclusive)

modifications:
1. added by
2. added during
3. present_during
4. in presence of
5. removed_by
6. removed_during
7. absent_during

**Comment by ValWood** [comment]
display labels are usually different (more human readable than official)

has_direct_input "has substrate"
has_input ?
has_regulation_target "regulates"
binds  (derived from IPI and with field, see https://github.com/pombase/website/issues/108)
involved_in  "part of"
occurs_at, occurs_in  (no hyphen)

any others (e.g. coincident_with) (no hyphen)
happens_during,  "during"
exists during  "during"

config file?

**Comment by ValWood** [comment]
Once the extension ordering is in place, extensions which are comma separated can be "joined"
like this:

![like this](https://cloud.githubusercontent.com/assets/7359272/21309048/87b992b8-c5d4-11e6-9944-c0def826a761.jpg)

**Comment by kimrutherford** [comment]
> display labels are usually different

Do you have a complete list of the mappings between relation name and display name?  Maybe Mark has the list?

**Comment by mah11** [comment]
I told you where the config file is in #107 - pombe-embl/supporting_files/Annotation_extension_and_reciprocal_display.txt

Kim - any comments on format/syntax welcome

**Comment by ValWood** [comment]
But you know you have to tell me everything twice. I have an excuse now. Symptom: brain fog.....

**Comment by ValWood** [comment]
That was the second time wasn't it : )

**Comment by mah11** [comment]
yup, that was my point ;)

**Comment by kimrutherford** [comment]
The extensions are now in the order you gave.

For now the order is configured here:
  https://github.com/pombase/website/blob/master/frontend/src/app/config.ts#L79

I added has_expressivity and has_penetrance to the config so they would be displayed in a consistent order.

**Comment by kimrutherford** [comment]
> Once the extension ordering is in place, extensions which are comma separated can be "joined"
like this:

Is that covered by #111 ?

**Comment by ValWood** [comment]
yes all done, new things new tickets. Looks  great. I think we can do some cleverer stuff later....
