### ISSUE TITLE
enhanced PubMed links

### ISSUE THREAD

**Issue by mah11** [pombase/website#640]
In the latest missive from NCBI LinkOut, we learned that we can link to a version of the PubMed abstract view that's spiffed up with a little PomBase icon that links back to our publication page (same link as in the LinkOut list below the abstract, but a lot less hidden).

To do so is conceptually very simple; in practice it's a little more complicated because it introduces conditionality.

If a PMID is on the list generated for LinkOut (criteria in #621; briefly, anything with annotation), then instead of the old URL syntax, use the new:

    old: http://www.ncbi.nlm.nih.gov/pubmed?term=<<IDENTIFIER>>
    new: https://www.ncbi.nlm.nih.gov/pubmed?holding=pombase&term=<<IDENTIFIER>>

The PubMed links should stay unchanged for papers without annotation.

**Comment by kimrutherford** [comment]
I'll change the links but I'm a bit confused.  When I look at the old and new links the pages look the same to me.  What am I missing?

**Comment by mah11** [comment]
The PomBase icon is only there in the new version - upper right part of page:

![screen-capture](https://user-images.githubusercontent.com/5196259/33889549-53d972fe-df48-11e7-8fa8-c99c1601672a.png)

**Comment by mah11** [comment]
... unless there's something more complicated going on with browser cache or cookies or some such - now I get the icon with either URL in the browser (Safari) I used to check the new version earlier, but not in a different browser (no icon with the old URL in Firefox).

I'm confused now too. But maybe do the change in case it makes a difference for users ... ??

**Comment by ValWood** [comment]
We should priorities this if Kim needs to do anything. I think it will really up our traffick with the big prominent icon next to the full text link....

**Comment by kimrutherford** [comment]
> I'm confused now too. But maybe do the change in case it makes a difference for users ... ??

I've changed the link from the publication pages.  Should I change the links in the documentation too?

> unless there's something more complicated going on with browser cache or cookies or some such

I think that's it.  If I load the URL containing "holding=pombase" it sets a browser cookie so that the "PomBase" logo is shown next time.

So currently in Firefox I see the PomBase logo here:
https://www.ncbi.nlm.nih.gov/pubmed/8887552
But I don't see it in Chrome.

I assume they do this so that the logo for a resource shows only for users who have come to pubmed from that resource.  That's not what we want!

**Comment by mah11** [comment]
>  Should I change the links in the documentation too?

I guess so - I don't _think_ we have any documentation links to papers that don't have any annotations, so they would all be in the LinkOut list. Good to have our various links to one paper do the same thing.

> [cookie weirdness]

headdesk.

**Comment by ValWood** [comment]
So is it possible to get the PomBase icon to display? I got a bit lost......

**Comment by ValWood** [comment]
oddly there are linkouts to Xenbase from this paper
https://www.ncbi.nlm.nih.gov/pubmed?term=22665807
so the  part about requiring added value wasn't totally true.....

**Comment by mah11** [comment]
> So is it possible to get the PomBase icon to display?

Yes - use the URLs with "holdings" (the "new" syntax in the original ticket summary). Those will always show the icon, I think regardless of cookie settings.

**Comment by ValWood** [comment]
ok got it...

**Comment by Antonialock** [comment]
That doesn't make sense at all. Can't we request they change it? Surely it makes more sense to alert potential new users of the resource, rather than telling old users 'hey, you can come back to us'.

**Comment by ValWood** [comment]
I think we can, but we need to supply a different link?

**Comment by mah11** [comment]
When the links are updated to the new syntax, we'll be doing pretty much all we can. (note to Kim: change doesn't seem to be live yet.)

> Surely it makes more sense to alert potential new users of the resource, rather than telling old users 'hey, you can come back to us'.

That's why we're going to use the new link syntax - that's what it does. We have no control over which version anyone else uses to link to PubMed, nor over what PubMed's own default display is; the best we can do is update our links to the ones that reliably have our icon.

> I think we can, but we need to supply a different link?

No, the links we supply are how to link from PubMed to us. This ticket is about link syntax we can use to link to them, to get the pombase icon to display for people who reach PubMed from one of our publication (or documentation) pages.

**Comment by kimrutherford** [comment]
> note to Kim: change doesn't seem to be live yet.

Sorry about that.  I've had some problems with updating because some libraries that the web site depends on broke over Christmas.

I'm about to try the work-around mentioned here: https://github.com/SergioBenitez/Rocket/issues/513

**Comment by kimrutherford** [comment]
> The PubMed links should stay unchanged for papers without annotation.

I missed that.  I've fixed it for the next update.

**Comment by kimrutherford** [comment]
> I've fixed it for the next update.

It's updated now.

I think this is done.  Please let me know if I've missed any links.

**Comment by kimrutherford** [comment]
I can't see the PomBase logo on the PubMed pages any more.

**Comment by kimrutherford** [comment]
Val has been in contact with NCBI about duplicate PMIDs.  In one reply they said:

> Library holdings data are no longer supported. Please consider changing your links from https://pubmed.ncbi.nlm.nih.gov/?holding=pombase&term=34279633 to https://pubmed.ncbi.nlm.nih.gov/34279633/.

I don't understand the holding=pombase bit but maybe it's related to the missing logos.

**Comment by mah11** [comment]
This has **nothing whatsoever** to do with duplicate PMIDs, so I'm going to edit some comments to remove that distraction.

> I can't see the PomBase logo on the PubMed pages any more.
> ...
>>  Library holdings data are no longer supported. Please consider changing your links from https://pubmed.ncbi.nlm.nih.gov/?holding=pombase&term=29343550 to https://pubmed.ncbi.nlm.nih.gov/29343550/.
> 
> I don't understand the holding=pombase bit but maybe it's related to the missing logos.

"Library holdings data" looks like internal NCBI/pubMed jargon, but the older comments on this ticket explain what the `holding=pombase` bit of the URL *used* to do. I gather, from their comment and from what I'm seeing on PubMed pages these days, that MOD links are no longer shown under "full text links" and no longer have logos displayed.

The urls with `holding=pombase` now just redirect to the version without, so we don't absolutely have to change our links to PubMed but if it's a one-minute task we might as well, since it now makes no difference.

(I also swapped in a randomly selected working PMID in the URL examples.)

Note that LinkOut is still a thing, and I still update our list of PMIDs to be linked to PomBase (all nicely documented for handoff, too). It's just a hell of a lot harder to find MOD links now because they're only listed at the bottom of the page, with no graphics :/

**Comment by kimrutherford** [comment]
> Please consider changing your links from https://pubmed.ncbi.nlm.nih.gov/?holding=pombase&term=29343550 to https://pubmed.ncbi.nlm.nih.gov/29343550/.

I've made that change.
