### ISSUE TITLE
Add  a way to load interactors from gene page into query builder

### ISSUE THREAD

**Issue by ValWood** [pombase/website#642]
Have a button "view all interactors" on gene page
Will provide a list, send to the query builder,  and put you on the results page.

**Comment by kimrutherford** [comment]
I've implemented this and it will be in tomorrow morning's update.  It will be in pombase-dev by 7am if the nightly load works and I'll update the main site after we've done some testing.

**Comment by kimrutherford** [comment]
The links to the query build from the interaction sections is now live in pombase-dev.  Please let me know if you spot any problems.

**Comment by ValWood** [comment]
That's great too!

**Comment by Antonialock** [comment]
Maybe text change from "view interactors" to "load interactors"?

**Comment by ValWood** [comment]
It says "view interactors in query builder" so I think that works if people want to look at them or use them in a query....

**Comment by ValWood** [comment]
"list interactors OR load into query builder"  ?

**Comment by Antonialock** [comment]
port to query builder?

**Comment by ValWood** [comment]
Nah, "port" is too er, wine-y?
I don't know but I would never use it in any other context  than a drink or an internet port. Too ambiguous...esp for foreign language speakers....

**Comment by ValWood** [comment]
One thing we should deal with is the label  "back" here:

![label back query interface](https://user-images.githubusercontent.com/7359272/35177855-5f31deb0-fd7b-11e7-8ce3-f5365a05795a.jpg)

**Comment by ValWood** [comment]
I think Kim has mentioned this before but we need this label to day something else (either always, or in this instance). It is not always "back" 

"Query interface" (I'm not totally enamoured with that but what else?)

**Comment by Antonialock** [comment]
send to query builder?

view and list just sounds so static.

**Comment by Antonialock** [comment]
> I think Kim has mentioned this before but we need this label to day something else (either always, or in this instance). It is not always "back"

"Advanced search" to match the menu?

**Comment by ValWood** [comment]
OK to both (I think?)

**Comment by kimrutherford** [comment]
So just to check:
  - change "<-- Back" on the results pages to say "<-- Advanced search"
  - change link from the gene page interactions sections to say "Send to query builder"

?

**Comment by ValWood** [comment]
let's wait for @mah11   she will probably have a better suggestion ;)

**Comment by kimrutherford** [comment]
The back button weirdness is mentioned here: https://github.com/pombase/website/issues/540#issuecomment-337085256

**Comment by mah11** [comment]
"Query using interacting genes" ... ?

**Comment by ValWood** [comment]
OK, (I prefer using, it's clearer that it is using this list in a query).

What about the "back button"?
@Antonialock  @mah11

**Comment by kimrutherford** [comment]
> "Query using interacting genes"

I've made that change for tomorrow's update.

**Comment by mah11** [comment]
> What about the "back" button?

I don't know what to do about this, and I have FYPO tickets to occupy today's brain space :P

**Comment by ValWood** [comment]
We'll decide on Thursday

**Comment by ValWood** [comment]
All done

**Comment by ValWood** [comment]
announced 29/08/2018
