### ISSUE TITLE
add chromosome filters back to search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#643]
Add a chromosomal filters query builder section.  These should both be in the same section with the coordinate part as an option:
 - genes on chromosome
 - genes between co-ordinates

**Comment by ValWood** [comment]
* announce when done

**Comment by kimrutherford** [comment]
The functionality is done for querying by chromosome and by chromosome range but I think the user interface needs works.  The change will be included in this morning's update so you can have a look.

**Comment by kimrutherford** [comment]
The chromosome and by chromosome range querying is in pombase-dev.  I'd appreciate if you could give it a quick test.

http://pombase-dev.bioinformatics.nz/query

**Comment by kimrutherford** [comment]
> The chromosome and by chromosome range querying is in pombase-dev.

The new query type is just labelled "Chromosome" at the moment.  Is that descriptive enough?

**Comment by ValWood** [comment]
seems pretty good to me!

How about "chromosomal location"? (I think it is only one extra character to the current longest one....

Or even "genome location", shorter...

**Comment by kimrutherford** [comment]
I've changed it to "Genome location" for tomorrow's update.  It's easy to change again if we're not happy.

**Comment by kimrutherford** [comment]
> I've changed it to "Genome location" for tomorrow's update. It's easy to change again if we're not happy.

The change is live now.  I'll close this issue but let me know if you have any wording changes.
