### ISSUE TITLE
check SGD links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#645]
At the weekend I spotted that some of our link outs to SGD gave an error

https://www.yeastgenome.org/locus/S000346142

I was about to report this, but the links on the gene pages seem fine today.
Do we have 2 link formats to SGD?

I'm a bit confused, but I definitely did see this....

**Comment by ValWood** [comment]
ok this one might be a typo in the ID, i'll do it.

**Comment by ValWood** [comment]
SPBC146.04 and erv14

**Comment by ValWood** [comment]
The problem is in the ortholog section
I knew I had seen it more than once!
https://www.pombase.org/gene/SPAC222.14c
https://www.yeastgenome.org/locus/YOR165W

**Comment by ValWood** [comment]
should be
https://www.yeastgenome.org/locus/S000005691
for linking, I think?

**Comment by kimrutherford** [comment]
> https://www.pombase.org/gene/SPAC222.14c
> https://www.yeastgenome.org/locus/YOR165W

The link to SGD in the ortholog section works for me.  Was it not working for you?

**Comment by Antonialock** [comment]
works for me too

**Comment by Antonialock** [comment]
Why does it matter if you arrive at locus S000005691 or YOR165W, I thought these were used synonymously?

**Comment by ValWood** [comment]
Ah its an SGD issue.
I knew i was getting a page not found error sometimes

See!
![page not found](https://user-images.githubusercontent.com/7359272/34884891-11f1a0ba-f7b6-11e7-9aea-9a86b88343e2.jpg)

I'll report to SGD.
Its intermittant...which is why It has been confusing me...

**Comment by ValWood** [comment]
Oh that was a typo in an ID wasn't it.

Lets just assume there isn't a problem...

**Comment by Antonialock** [comment]
:D

**Comment by ValWood** [comment]
I'm just sometimes a bit rubbish at cutting and pasting, but I have got the basic principle ;)

I once had Hannah on an "work placement"  at Sanger and one of her tasks was  fixing truncated PMID's....
