### ISSUE TITLE
check search urgent

### ISSUE THREAD

**Issue by ValWood** [pombase/website#646]
For me, the query builder is not working for ontology terms on www, although dev is?
v

**Comment by kimrutherford** [comment]
I've updated the main site to use latest nightly load which has fixed things.

The same autocomplete problem has happened before and I don't know the cause.  I'm going leave this issue open as a reminder to add more logging so I can work this out.

**Comment by ValWood** [comment]
yep it's weirdly sporadic....

**Comment by ValWood** [comment]
not working again for me.....

**Comment by kimrutherford** [comment]
> not working again for me.....

I restarted and it's fixed.

**Comment by ValWood** [comment]
back again.

**Comment by kimrutherford** [comment]
This time it's still working for me.  Could it be your connection?

**Comment by ValWood** [comment]
odd, working for me now. I don't think it was the connection because dev was working but not www....

**Comment by kimrutherford** [comment]
I'll check the logs.  I have a monitor set up that alerts me if the autocomplete is failing.  The monitor didn't notice a problem in this case.

**Comment by ValWood** [comment]
will reopen next time :)
