### ISSUE TITLE
add  few more visible characters to community curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#647]
could we display a few more characters here?

![truncation](https://user-images.githubusercontent.com/7359272/34558308-7bdbc33e-f135-11e7-9630-01637cef50d4.jpg)

**Comment by kimrutherford** [comment]
> could we display a few more characters here?

It's currently 50-ish characters.  What should we increase it too?

**Comment by ValWood** [comment]
I think you could add another 15, that would give a bit more context to some of them..

like Conserved and unique features of the fission yeast ( was autophagy system)

It would be nice to have an archive link for this list too maybe ... although it might get a bit long... (maybe by year?)

**Comment by ValWood** [comment]
Its 36 per line,  so just increase the size but keep it to 2 lines  (i.e under 36x2)

**Comment by kimrutherford** [comment]
I've changed it to 70 characters.  Hopefully that will mostly keep things on two lines.  It will be in tomorrow morning's update.

**Comment by ValWood** [comment]
Oh I see, I thought the line wrapping point was fixed, but I guess the character widths  vary or something.
It now goes to 3 lines sometimes. Maybe it was better before. Sorry about that...

**Comment by kimrutherford** [comment]
> I guess the character widths vary

Yep, annoyingly.

> It now goes to 3 lines sometimes.

It's tricky to make this perfect.  It was 50 characters and is now 70.  So should I change to 60?

**Comment by ValWood** [comment]
yes that should always be below 2.

sorry I thought this would be a few seconds ;)

**Comment by kimrutherford** [comment]
OK, done.
