### ISSUE TITLE
ensure that all ID/accessions hyperlink

### ISSUE THREAD

**Issue by mah11** [pombase/website#65]
use GO.xrf_abbs
#16 reports example where it's not working: SPAC1F12.10c GO:0003958 ISO with RGD:621834 (RGD ID isn't linked and the prefix isn't displayed)

**Comment by kimrutherford** [comment]
The GO.xrf_abbs file is now being read and the extension links for PR terms and Pfam IDs work correctly.

The process isn't completely automatic.  Each ID prefix ("SGD", "MGI", etc.) that we need has to be add to this file:
  https://github.com/pombase/website/blob/master/frontend/etc/build_prod.sh

GO.xrf_abbs is read each time the site is deployed so updates from GO should get through quickly.

So far I've only fixed the extension links code to use the GO.xrf_abbs links.  I'll now go through are fix the other places where we have external IDs.

**Comment by kimrutherford** [comment]
The with/from links now use the GO.xrf_abbs file data.  Please let me know if you spot any with/from links that are missing.

You might need to shift-reload.

**Comment by ValWood** [comment]
ones i saw look fine. can open new tickets if any missing.
