### ISSUE TITLE
binding partners are not displayed as "binds" extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#650]
spc7:

![binding](https://user-images.githubusercontent.com/7359272/34930580-1509387c-f9c2-11e7-8af6-5da98ad4d7e0.jpg)

**Comment by kimrutherford** [comment]
What should it look like?

**Comment by ValWood** [comment]
I was fixed here:
https://github.com/pombase/website/issues/558
?

**Comment by ValWood** [comment]
and here it seemed to work fine:
https://github.com/pombase/website/issues/639

so something changed recently?

**Comment by kimrutherford** [comment]
Sorry, I made a typo when fixing pombase/curation#1767

I've fixed the problem and I'll re-release the main site soon.

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now.
