### ISSUE TITLE
evidence codes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#651]
we seem to have a mixture of styles. 
hyperlinked abbreviations
non-hyperlinked text string

What do we want to use?

![evidece codes](https://user-images.githubusercontent.com/7359272/34944049-f6a28c4c-f9f5-11e7-9ddf-f317b8ae1ad4.jpg)

**Comment by kimrutherford** [comment]
Which page was that?

**Comment by ValWood** [comment]
I thought it was everywhere, but now I only see the short version...

**Comment by kimrutherford** [comment]
> I thought it was everywhere, but now I only see the short version...

I fixed a bug a few days ago that could have caused this problem.  So hopefully it's fixed now.  Please let me know if you see it again.
