### ISSUE TITLE
new HTP evidence code not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#652]
e.g
![new evidence](https://user-images.githubusercontent.com/7359272/35112864-50a6f164-fc77-11e7-879f-c37bc6aebb84.jpg)

**Comment by ValWood** [comment]
eg is https://www.pombase.org/gene/SPCC18B5.06


I'm sure that I *have* seem them alreeady? or are we waiting for GO for something?

**Comment by kimrutherford** [comment]
Sorry, I configured the evidence codes for Chado but forgot to do it for the website.  Should be fixed in the next update.

**Comment by kimrutherford** [comment]
The evidence codes are all OK again in pombase-dev.

**Comment by ValWood** [comment]
Yes ! Once documentation is in place for HDA we'll establish link outs.

**Comment by ValWood** [comment]
we should be able to instantiate these links now... (I'm assuming they will be available for the  HTP paper)

**Comment by kimrutherford** [comment]
I've added the links for the high throughput evidence codes.
