### ISSUE TITLE
new image for curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#653]
@Antonialock I keep forgetting about his, Steve asked ages ago.

Could you create a new image for this which just has the wedge and not the pie so that it can be larger (he thought it would be better if you could read more names in addition to Jacky's and I agree).

If it is possible it might be good to have it on a non-white background, but I am guessing that this is not an option! (only because the non white backgrounds stand  out more).

**Comment by ValWood** [comment]
![redo image](https://user-images.githubusercontent.com/7359272/35113812-b63d740a-fc7a-11e7-8fcc-689eda438322.jpg)

**Comment by ValWood** [comment]
I see you did this so closing, Kim can replace here:
https://github.com/pombase/website/issues/655

**Comment by Antonialock** [comment]
ok I was going to make a new one but not if it is good enough

For information numbers as of Jan 2018


Jacky Hayles | 27
-- | --
Paul Russell | 14
Kathy Gould | 13
Kaoru Takegawa | 13
Sophie Martin | 11
Peter Espenshade | 10
Elena Hidalgo | 10
Jian-Qiu Wu | 9
Takashi Toda | 9
Rasmus Hartmann-Petersen | 8
Ryoko Mandeville | 7
Songtao Jia | 7
Li-Lin Du | 7
Henar Valdivieso | 6
Mitsuhiro Yanagida | 6
Ying Huang | 6
Makoto Kawamukai | 6
Michael Boddy | 5
Marc Buehler | 5
Per Sunnerhagen | 5
Hirofumi Aiba | 5
James Moseley | 4
Janel beckley | 4
Takayoshi Kuno | 4
Simon Whitehall | 4
Yoshinori Watanabe | 4
Snezhana Oliferenko | 4
Eishi Noguchi | 4
Pilar Perez | 4
Haruhiko Asakawa | 4
Yasushi Hiraoka | 4
Tomas Pluskal | 4
Kaz Shiozaki | 4
Jurg Bahler | 3
Jonathan Millar | 3
Martin Převorovský | 3
Chris Norbury | 3
Charlie Hoffman | 3
Janni Petersen | 3
Hiroaki Kato | 3
Ronit Weisman | 3
Tony Carr | 3
Arancha Sanchez | 3
Feng Qiao | 3
Jun-Song Chen | 3
Virginia Zakian | 3
Nasim Sabouri | 3
Shakil Ahmed | 3
Shigeaki Saitoh | 3
Norihiko Nakazawa | 3
Minghua Nie | 3
Juan Mata | 2
Haitong Hou | 2
Kayoko Tanaka | 2
Akira Yamashita | 2
Taro Nakamura | 2
Isabelle Jourdain | 2
Gordon Chua | 2
Elizabeth Bayne | 2
Masayuki Yamamoto | 2
Dannel McCollum | 2
Robin Allshire | 2
Pernilla Bjerling | 2
Matthew Whitby | 2
Rocky Cheung | 2
Claudia Keller | 2
Janet Partridge | 2
Dan Mulvihill | 2
Kenji Kitamura | 2
Katrina Woolcock | 2
Sarah Lambert | 2
Yasu Kakui | 2
Quan-wen Jin | 2
Yolanda Sanchez | 2
Juan Carlos Ribas | 2
Dan Zhang | 2
Larry Fliegel | 2
ES Chen | 2
Jun-ichi Nakayama | 2
Daochun Kong | 2
Junko Kanoh | 2
Gerald Smith | 2
Jose Ayte | 2
Minoru Yoshida | 2
Tomohiro Matsumoto | 2
Valerie Coffman | 2
Genevieve Thon | 2
Akio Nakashima | 2
Hiroshi Iwasaki | 2
Megan King | 2
Alessandro Bianchi | 2
Tokuko Haraguchi | 2
Frank Uhlmann | 2
Geetanjali Sundaram | 2
a. john callegari | 2
Jun Li | 2
Kentaro Nakano | 2
Masak Takaine | 2
Patricia Garcia | 2
Jung-Hye Roe | 2
Vincent Vanoosthuyse | 2
Toshiaki Isobe | 2
Pierre Hentges | 2
Masato Taoka | 2
stephane Coulon | 2
Takeshi Sakuno | 2
Gulsen Uz | 2
Lynda Groocock | 1
Dominique Helmlinger | 1
Nick Rhind | 1
Ursula Fleig | 1
Raphael Ioannoni | 1
Damien Hermand | 1
Colm Ryan | 1
Michael Bond | 1
Francisco Navarro | 1
Tommy Vo | 1
Benoit Arcangioli | 1
Matthew O'Connell | 1
Shataparna Banerjee | 1
Hitoshi Kurumizaka | 1
Karl Ekwall | 1
Simon Labbé | 1
Melanie Styers | 1
Juraj Gregan | 1
Shiv Grewal | 1
Ken Sawin | 1
François Bachand | 1
Jean-Paul Javerzat | 1
Tako Nakagawa | 1
Danesh Moazed | 1
Chikashi Shimoda | 1
Graham Ladds | 1
Attila Csikasz-Nagy | 1
Howard Hang | 1
Fuyuki Ishikawa | 1
Xiaojiang Chen | 1
David Williams | 1
Lidia Vasilieva | 1
Wayne Wahls | 1
Zsolt Szilagyi | 1
Hiroshi Uemura | 1
César de Haro | 1
Araceli G. Castillo | 1
Hiro Masuda | 1
Nadeem Shaikh | 1
Christopher Herbert | 1
Mark Corkins | 1
Fred Winston | 1
Aleksandar Vjestica | 1
Masafumi Yohda | 1
Amanda Bird | 1
Stevan Marcus | 1
Hisao Masukata | 1
Laurence Pearl | 1
Mario Halic | 1
Yan Ma | 1
Tom Kelly | 1
Fuyuhiko Tamanoi | 1
Fei Li | 1
Xin Zhou | 1
David Bradley | 1
Elizabeth Veal | 1
Nathan Lee | 1
Charalampos Rallis | 1
Yongjie Xu | 1
Yusuke Tarumoto | 1
Geetha M | 1
Phong Tran | 1
Dharanidhar Dubey | 1
Paul Young | 1
Payal Bhatia | 1
Toru Nakamura | 1
Melissa Moore | 1
Hisao Masai | 1
Susumu Morigasaki | 1
Silvia Polakova | 1
Daniel Jeffares | 1
Alejandro Carpy | 1
Rafael Daga | 1
Nancy Walworth | 1
Shinya Takahata | 1
Haim Manor | 1
Hiroshi Nojima | 1
Minoru Yoshida | 1
Naoko Imamoto | 1
Tatsuki Kunoh | 1
Takeshi Hayashi | 1
Jennifer Gerton | 1
Thomas Caspari | 1
Hideto Miyoshi | 1
Hong Lu | 1
Anthony Annunziato | 1
Shajahan Anver | 1
Laura Busenlehner | 1
Nicole Rachfall | 1
Kariona Grabinska | 1
Emily Egan | 1
Rosa Aligue | 1
Pascal Bernard | 1
Perry Blackshear | 1
Daeyoup Lee | 1
Kazunori Tomita | 1
Yasuhiro Tsutsui | 1
Luis Blanco | 1
Bedia Palabiyik | 1
Jia-Min Zhang | 1
Nicola Zilio | 1
Rafael Lucena | 1
Chris McInerny | 1
Nimisha Sharma | 1
Aidan Doherty | 1
Julie Cooper | 1
Janet Leatherwood | 1
Dennis Wykoff | 1
Reine Protacio | 1
Daniele Oberti | 1
Rob Martienssen | 1
Arshad Desai | 1
Deepak Kumar | 1
Stephen Shears | 1
Huanchen Wang | 1
Patrick Varga-Weisz | 1
Steven Henikoff | 1
Edoardo Petrini | 1
Rob De Bruin | 1
Ann Ehrenhofer-Murray | 1
Yasukazu Daigaku | 1
Shogo Ikeda | 1
Erik Boye | 1
Anuja George | 1
Hernan Diego Folco | 1
Adi Cohen | 1
Ayumu Yamamoto | 1
Alexander Lorenz | 1
Atsushi Matsuda | 1
Hui-Ju Yang | 1
Daniela Eckert | 1
Tomoyuki Furuyashiki | 1
Javier Encinar del Dedo | 1
Katarzyna Kowalczyk | 1
Risa Burr | 1
Yoonjung Choi | 1
Takahiro Tougan | 1
Weijun Chen | 1
Melissa Wells | 1
Hisashi Tatebe | 1
Edita Balkoova | 1
Isabelle Sagot | 1
Lubomir Tomaska | 1
Ramsay McFarlane | 1
Ruben Cauchi | 1
Cong Liu | 1
Avelino Bueno | 1
Vincent Géli | 1
Akshay Vishwanatha | 1
Cornelia Kilchert | 1
Vanesa Álvarez | 1
Abantika Ganguly | 1
Daniela Eckert | 1
Tomo Sugiyama | 1
Tomoyasu Sugiyama | 1

**Comment by Antonialock** [comment]
I made a new one, sizes proportionate to the number of approved sessions per community curator. Except for Jacky, I decreased her (by a third!)

<img width="1143" alt="community curation jan2018" src="https://user-images.githubusercontent.com/12727506/35159391-1619a230-fd08-11e7-8681-4a56c6864c14.png">

**Comment by Antonialock** [comment]
@ValWood

**Comment by Antonialock** [comment]
<img width="1243" alt="community curation jan2018 2" src="https://user-images.githubusercontent.com/12727506/35159757-4210807e-fd09-11e7-8fa7-029061e81d81.png">

**Comment by Antonialock** [comment]
<img width="1212" alt="community curation jan2018 3" src="https://user-images.githubusercontent.com/12727506/35159846-8b934bd2-fd09-11e7-9f47-b15f6eb09d7c.png">

**Comment by Antonialock** [comment]
<img width="1192" alt="community curation jan2018 4" src="https://user-images.githubusercontent.com/12727506/35160142-502a9a86-fd0a-11e7-9095-296bc9cbfa67.png">

**Comment by Antonialock** [comment]
now you have a few to pick from :)

**Comment by ValWood** [comment]
OK cool lets keep it fresh and up to date.

**Comment by ValWood** [comment]
I lke second from the bottom...

**Comment by ValWood** [comment]
as an aside:
Tomo Sugiyama | 1
Tomoyasu Sugiyama | 1

Is probably same person...need to check...

**Comment by ValWood** [comment]
pop the one I tagged in the drop box if you agree....looks fab!

**Comment by Antonialock** [comment]
done!

note to self, need to use safari now to make these.
