### ISSUE TITLE
Publication pages need to hit "reload" button to load fully

### ISSUE THREAD

**Issue by ValWood** [pombase/website#654]
I think, I thought it was my connection earlier, but  it is still happening

**Comment by Antonialock** [comment]
It is working fine for me. I cross checked to what is in canto for a few papers, and what I see on the website is the same as canto.

try restarting your computer/browser?

**Comment by ValWood** [comment]
yep fine for me too....

**Comment by kimrutherford** [comment]
Sorry!  I found a bug in the publication page displaying after I had released.  So I quickly fixed it and re-released.  I obviously wasn't quick enough.

**Comment by ValWood** [comment]
;)  We are all too fast, It makes the rest of the world feel like sloth's. Well some in particular. (I am going to delete this comment immediately)
