### ISSUE TITLE
new front page research rotation, new word cloud

### ISSUE THREAD

**Issue by ValWood** [pombase/website#655]
text:

title

Research spotlight: ©Bestul AJ et al., 2017. 
Body

Molecular model of fission yeast centrosome assembly determined by superresolution imaging
Originally published in JCB <link JCB to http://jcb.rupress.org/content/216/8/2409>. 

Publication record in PomBase ...https://www.pombase.org/reference/PMID:28619713

**Comment by ValWood** [comment]
Also, add an "archive link"

**Comment by ValWood** [comment]
pretty...

![centrosome](https://user-images.githubusercontent.com/7359272/35156223-1b49f596-fd28-11e7-86b2-65f9a681efbf.jpg)

**Comment by ValWood** [comment]
There is also a new word cloud in the community curation feed directory

**Comment by Antonialock** [comment]
Val I generated some more images, take a look  #653, see if you want anything tweaked (easier to do today when how to do it is fresh in my head)

**Comment by kimrutherford** [comment]
The new images and Spotlight are live now.

**Comment by ValWood** [comment]
Nice, I'll let the Jaspersen lab know....
