### ISSUE TITLE
Query builder, don't store redundant queries

### ISSUE THREAD

**Issue by ValWood** [pombase/website#656]
At  the moment, if you click on an existing query it re-runs and pops it to the top.

I though that, also, if I reran a query from the menu, if the query existed in my histore it was going the same, but in this case it is duplicating, so I have  lots of queries stored over and over in my history, making it pretty difficult to manage over time.

![duplicate](https://user-images.githubusercontent.com/7359272/35161645-b43494ae-fd38-11e7-9cd9-eb754fee99c1.jpg)

**Comment by ValWood** [comment]
soon if easy...

**Comment by kimrutherford** [comment]
That should be fixed in the main site now.

The duplicates will disappear next time you run the query.

**Comment by ValWood** [comment]
great thanks!

**Comment by ValWood** [comment]
Seems to work!
