### ISSUE TITLE
GO term pages not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/website#658]
see
https://www.pombase.org/term/GO:0031362

**Comment by kimrutherford** [comment]
Sorry about that.  I made a change to the annotation display but forgot to test it on the term pages.  I've fixed the bug and I'm redeploying.  It should be live in 10 minutes or so.

**Comment by kimrutherford** [comment]
That's now fixed if you reload.

**Comment by ValWood** [comment]
Great!
