### ISSUE TITLE
ortholog section not updating properly when looking at a different gene

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#659]
User reported, I have the same issue (pom1 orthologs showing for cdc2 when navigating from pom1 page to cdc2 page using the basic search interface)

"the ortholog section is somehow
faulty. For me it always shows the orthologs of the last gene I looked
up. The other information is not affected. When I refresh I get the
right orthologs.

An example: If I first look up snr1 and then pyk1, I'll see EHD3
(YDR036C) <http://www.yeastgenome.org/locus/YDR036C/overview> as the
ortholog. At the same time I already see the correct GO annotations for
pyk1. When I refresh the page I also see the correct orthologs."

**Comment by kimrutherford** [comment]
This is fixed now if you reload.
