### ISSUE TITLE
edit community curation static page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#66]
Based on this
https://github.com/pombase/canto/issues/1204#issuecomment-241252602

I have some suggested tweaks to this page
http://www.pombase.org/community/fission-yeast-community-curation-project

===
Comprehensive manual curation of the S. pombe literature is a primary goal of the PomBase project, and among the most important activities of thecuration staff. Increasing numbers of new publications, and a large backlog of older papers, however, mean that complete literature curation will require input from the research community as well as the efforts of dedicated professional curators (*** to support this statement  can we provide a link here to the new stats page?).

The PomBase Community Curation system enables researchers to contribute annotations directly to PomBase based on their publications. The <***new*** -delete?>  system uses Canto, a web-based tool that allows both curators and researchers to create annotations <*** using only a web browser- delete, we say its web-based***> . Canto supports GO, phenotype, interaction, and modification annotations, and can be configured for use with other ontologies as the need arises. Annotations made in the community curation system will be prioritized for inclusion in PomBase and will therefore also be more rapidly disseminated to other databases (e.g. GenBank/ENA/DDBJ, UniProt, BioGRID and GO). < ***We will also highlight the publications most recently curated by the community on the PomBase site. - delete until we implement?***>
(We could however add a sentence about this increasing visibility of curated publications here?)

For newly published papers, PomBase curators < ***will - delete> email authors inviting them to participate, with specific instructions and links. Lab members are also welcome to evaluate existing annotations and create new annotations from past publications -- use the PubMed ID search on the main PomBase Canto page.

Add something like this? (more about 'motivation').

To make it easier to  describe your data curation efforts  in the  data dissemination sections of your grant proposals, we are currently investigating ways to formalise attribution for the community contributions. This  will  involve  registering your ORCID identifier in Canto, and probably a mechanism to display a summary of your curation contribution in either ORCID  openRIF or both. In the meantime, you could provide the permanent URLs  of your publication’s curation sessions  to indicate your curation contributions to funders.

Maybe we can remove this section, there is a link to “canto” which will provide this info if followed?
Documentation for the PomBase tool is available, and there is a demo version of Canto where anyone can become familiar with the interface and data types.
The Canto home page links to PomBase and other implementations, general Canto documentation, and the demo tool. Canto is a free, open source application, and is a component of GMOD.

**Comment by mah11** [comment]
done on dev
