### ISSUE TITLE
AmiGO link has disappeared from GO ontology  term pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#661]
It used to be there ...now its bioportal (did we have bioportal for GO? I thought we only had this for FYPO, but I'm not sure...)

**Comment by kimrutherford** [comment]
Sorry about that.  I broke it while trying to fix the database abbreviations we write to the exported files.  It's fixed for tomorrow's update.

(Broken by 295a200cc775791)

**Comment by kimrutherford** [comment]
The AmiGO link is back now.
