### ISSUE TITLE
New research spotlight feature

### ISSUE THREAD

**Issue by ValWood** [pombase/website#663]
From Fenq  Qiao

http://www.cell.com/cms/attachment/2118866132/2086016298/mmc3.mp4

Research spotlight: J-K Kim et al., 2017
Structural Basis for Shelterin Bridge Assembly
Originally published in <Mol. Cell>  

http://www.cell.com/molecular-cell/fulltext/S1097-2765(17)30809-2?_returnURL=http%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1097276517308092%3Fshowall%3Dtrue

Publication record in PomBase ..
https://www.pombase.org/reference/PMID:29149597

**Comment by kimrutherford** [comment]
> http://www.cell.com/cms/attachment/2118866132/2086016298/mmc3.mp4

Just so you know, within each spotlight item you can have multiple images that rotate at random.  I noticed that Feng Qiao mentioned two videos.  If you wanted we could add both to the spotlight item.

**Comment by ValWood** [comment]
yeah one of them appeared to be broken, I will tell him...

**Comment by ValWood** [comment]
Oh actually they both work for me now.

they are both good but the aspect ratio of this one is better. I'll put both in the drop box tho'

**Comment by kimrutherford** [comment]
I've scaled the video to the right size for the front page.  Last time I had trouble creating a video that worked in Safari.  I don't have a Mac any more so you you try this link and see if it works in Safari?:

https://curation.pombase.org/kmr44/mmc3-small.mp4

**Comment by ValWood** [comment]
Yep!

**Comment by ValWood** [comment]
Oh hang on, that was chrome '...

**Comment by ValWood** [comment]
still yes!

**Comment by Antonialock** [comment]
Works for me but the size is very different in case that is important (maybe that has to do with my settings...?)
Safari
<img width="1248" alt="screen shot 2018-01-23 at 22 55 37" src="https://user-images.githubusercontent.com/12727506/35305291-babc890c-0090-11e8-9e22-e55d431dc575.png">

Firefox
<img width="1247" alt="screen shot 2018-01-23 at 22 55 54" src="https://user-images.githubusercontent.com/12727506/35305300-c35a6cbe-0090-11e8-8d26-38ef008cb8b7.png">

Chrome
<img width="1235" alt="screen shot 2018-01-23 at 22 56 09" src="https://user-images.githubusercontent.com/12727506/35305308-cc986f9c-0090-11e8-9c7b-822c2f479a6f.png">

**Comment by kimrutherford** [comment]
> Works for me but the size is very different in case that is important

I think (hope) that's probably Safari scaling it up because it's not in a page.  I'll put it in the page on pombase-dev and we can check how it looks.

Thanks to both of you for checking.

**Comment by kimrutherford** [comment]
I've made a note for myself on the Wiki about creating embedded videos:
  https://github.com/pombase/website/wiki/Creating-an-embedded-video

**Comment by kimrutherford** [comment]
The new Spotlight and video are live on the main site now.  Could you have a quick check in Safari?

I'm about to check in Internet Explorer as I haven't done that in a while.

**Comment by Antonialock** [comment]
Fine in Safari, chrome & firefox

**Comment by kimrutherford** [comment]
> Fine in Safari, chrome & firefox

Thanks for checking.

**Comment by ValWood** [comment]
It's live and I saw it working, but its often blank when I return to it. This might be  because I'm using the wifi at work
