### ISSUE TITLE
mobile phone view issues

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#664]
Putting this at low priority and not posting screenshots at this moment - these are really minor cosmetics. Can bump if a user requests it or when Kim is "done" with more important stuff :)

1. on an iphone, in both portrait and landscape, the text "the scientific resource..." is very slightly obscured by the menu

2. in landscape mode, the quicklinks menu sits above the annotations and isn't "pinned" to the side as you scroll down, even if there visually is space for it to float with the scrolling

**Comment by ValWood** [comment]
Isn't  1 on an older ticket? I'm sure I saw that yesterday?

It might be better to list these phone things  in one ticket  so we cane see more easily if its the same issue? (although @kmr may prefer separate ones... leave if so)

**Comment by Antonialock** [comment]
Just make a label for "phone/tablet display" :-) 

Personally I hate having 20 issues in one ticket, it is a good feeling to close them :p plus sometimes it is not clear if you have done everything in a ticket if there are multiple things (especially when the tick boxes are spread over several comments)

**Comment by Antonialock** [comment]
> Isn't 1 on an older ticket? I'm sure I saw that yesterday?
I think it used to be a lot worse...now it is not too bad, hence why I said it is not ideal but not a huge issue.

**Comment by Antonialock** [comment]
2 isnt an issue any longer, page is filled. 1 still an issue, will open separate issue.
