### ISSUE TITLE
GO annotation not showing  on page and not in logs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#665]
/GO="aspect=F; term=calcium:cation antiporter activity; GOid=calcium:proton antiporter activity; evidence=TAS; db_xref=PMID:27075443; date=20170303"

Is it because of the colon in the term name?
(could be others)

We should report anything which does not parse in the logs maybe

**Comment by kimrutherford** [comment]
That error was spotted but I had forgotten to write it to a log file.  I've added a new log file "misc_term_warnings.txt".

Here's what it will look like in the morning:

mRNA SPAC17G8.08c.1:   GOid doesn't start with 'GO:' for SPAC17G8.08c.1: calcium:proton antiporter activity                                                                                   
mRNA SPAC1805.08.1:   no GOid for SPAC1805.08.1 annotation: 'meiotic spindle pole body'        
mRNA SPAC186.05c.1:   GOid doesn't start with 'GO:' for SPAC186.05c.1: calcium:proton antiporter activity                                                                                     
mRNA SPBC725.12.1:   GOid doesn't start with 'GO:' for SPBC725.12.1: O:0072686                 
mRNA SPBC16D10.07c.1:   GOid doesn't start with 'GO:' for SPBC16D10.07c.1: O:0031618           
mRNA SPBC8E4.04.1:   GOid doesn't start with 'GO:' for SPBC8E4.04.1: alditol:NADP+ 1-oxidoreductase activity

**Comment by kimrutherford** [comment]
I've done a bit of an audit to check for other missing warning.  Unfortunately there were a few.  The  qualifier_problems.txt log file will have some extra lines in the morning.

**Comment by kimrutherford** [comment]
Here is the new log file:
  https://curation.pombase.org/dumps/latest_build/logs/misc_term_warnings.txt

And there are extra warnings here:
  https://curation.pombase.org/dumps/latest_build/logs/qualifier_problems.txt

**Comment by ValWood** [comment]
brilliant. I think this might fix another open ticket about logs!...will check later.

**Comment by ValWood** [comment]
fixed the log problems.
