### ISSUE TITLE
Research spotlight videos not playing

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#666]
The research spotlight videos don't play on my iPhone. I've tried both Safari and Chrome.

**Comment by kimrutherford** [comment]
> The research spotlight videos don't play on my iPhone.

Does it not display or does it just not animate?

**Comment by ValWood** [comment]
tell apple?

**Comment by Antonialock** [comment]
doesn't animate

**Comment by kimrutherford** [comment]
> doesn't animate

That's not so bad then.

Does it animate if you go to this link?: https://curation.pombase.org/kmr44/test.mp4

**Comment by Antonialock** [comment]
yep, both browsers

**Comment by Antonialock** [comment]
still not playing in safari on iphone

**Comment by kimrutherford** [comment]
It was challenging to create videos that would work on the desktop version of Safari.

I don't think I can fix this so I'm glad it's low priority.

**Comment by ValWood** [comment]
I'm closing this since it seems to be out of our control?
