### ISSUE TITLE
Future display of modifications in sequence context (protein feature viewer)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#667]
This ticket replaces 
https://github.com/pombase/website/issues/17

Long term we would like  to  deploy a generic viewer that would  enable us to diplay
residues/modifications
protein features
amino acid mutations -> phenotypes etc
simultaneously

Making it easy for the user to combine info like this:

E substitution at G78, and is located in the amino-terminal ssDNA-binding domain called DBD F, which ensures binding to short stretches of ssDNA [41](figure 2d).

From Midori
https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer
(http://www.ebi.ac.uk/about/news/service-news/new-view-proteins). To see it deployed go to a UniProt entry page, and click the "Feature viewer" link in the left-hand menu.

It's much prettier than the PTM view on the main entry page.

e.g. [human CDK1 (cdc2 ortholog)](http://www.uniprot.org/uniprot/P06493#showFeaturesViewer)
[human p53](http://www.uniprot.org/uniprot/P04637#showFeaturesViewer) has loads of stuff

From ANtonia
 iPTMnet
https://github.com/pombase/website/issues/15
http://research.bioinformatics.udel.edu/iptmnet/entry/P06493/
also their sequence alignment is cool, see here
http://research.bioinformatics.udel.edu/iptmnet/visual/msa/tree/P06493/

**Comment by ValWood** [comment]
I think this is probably a better fit than the nextprot one:

https://cloud.githubusercontent.com/assets/7359272/20640045/d8406fb4-b3cc-11e6-847d-35a040d0ab0d.jpg

and it does the sequence row as a track which was what I wished that the nextprot one did:

![nextprot](https://cloud.githubusercontent.com/assets/7359272/25479228/15886cfa-2b3c-11e7-9754-03233d34d8a8.jpg)

so this seems that it will work nicely for us....

**Comment by ValWood** [comment]
also  we should compare to
http://149.171.5.168:8009/P04637

**Comment by ValWood** [comment]
@manulera  would like this feature viewer too. We think that  labs would find it very useful to be able to easily access phenotypes associated with regions.

We need to figure out which is the best tool to adopt.

**Comment by kimrutherford** [comment]
> We need to figure out which is the best tool to adopt, taking into account search capability

We'll also need to talk into account how difficult each tool is to implement on the website.  The ones I've looked at have tended to be big and complicated.

**Comment by manulera** [comment]
Maybe a naive question, can we host pombe data in those services and simply redirect people there instead of having the section in the gene page?

The one they use in NextProt is this one, I think:
https://github.com/calipho-sib/feature-viewer

Then I saw someone has made a typescript version (of an old version of the repo I imagine)
https://github.com/BioComputingUP/FeatureViewerTypeScript

From the docs of the original one it seems that adding the features is relatively simple, but having the list below that is linked to the graph like in NextProt and so it's probably quite some work.

**Comment by ValWood** [comment]
It is worth spending some time on. We put it as a major grant aim:

For example, we will integrate the ProtVista protein viewer to display curated mutants (and their phenotypes) and
modifications in the context of protein domains (this was the most desired single new feature in the 2019 survey, with >380 requests, and ranked first of 11 options by
23% of respondents). We will map these to equivalent human disease variants. To make complex data more accessible, we will deploy new data visualisation options that allow users to query, aggregate, and filter data directly within the website. For
example, we will provide interactive summaries that dynamically integrate data across classes, such as phenotype

Users clearly want it...

**Comment by ValWood** [comment]
> Maybe a naive question, can we host pombe data in those services and simply redirect people there instead of having the section in the gene page?

NextPROT is only human. I think the resources that use this such viewers (UNirpto for eg)  on their  data. That does not stop us sharing the data of course.

**Comment by ValWood** [comment]
From the survey:

For example, we will integrate the ProtVista protein viewer to display curated mutants (and their phenotypes) and
modifications in the context of protein domains (this was the most desired single new feature in the 2019 survey, with >380 requests, and ranked first of 11 options by
23% of respondents).

**Comment by ValWood** [comment]
We also say "We will map these to equivalent human disease variants."
This isn't trivial. But it is something we can think about later.
