### ISSUE TITLE
Discuss how to sort out the chromosome names in the FTP datasets

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#669]
The current chromosome names in Chado are:
 - chromosome_1
 - chromosome_2
 - chromosome_3
 - mating_type_region
 - MISPCG
 - AB325691

These names come from the contig files.

On the website we show I, II, III, "Mating type region", "Mitochondria" and AB325691.  These display names are in a map in the configuration file.

I've been looking at the data files on the FTP site.  There is a bit of variety in chromosome naming.

The ERP001483 dataset has: I, II, III, MTR, MT and AB325691

The BED files have I, II, III and MT

The GSE41773 dataset and NRhind_Transcriptome have CU329670.1, CU329672.1 and CU329671.1 - that's a pain.

**Comment by ValWood** [comment]
We tried for a long time to standardize with the EBI but we gave up.
I don't think they understood why we had an issue that different names were used...
My pet hate was the abbreviation MT for mitochondria (used by no one anywhere and confused with mating type region).

We can do this today.

IIRK when we polled a sample, the  community generally use roman numerals for chromosomes?

AB325691 is a subtelomeric contig. In pombe_embl we call it telomeric.contig

maybe this should be  chromosome_II_left_tel_80202_80301_gap_fill.contig (or something very explicit)
(this is currently 100N's)

**Comment by ValWood** [comment]
W can rename any of the data files, we did not call them these random names...

ftp://ftp.pombase.org/DATASET/

we can do this today.

we will decide what we want to include in the file names to recognise them.
and organism by "type of track" (biologically)

(or whatever we think best when we go through them)

**Comment by ValWood** [comment]
this was our simple track naming system
https://curation.pombase.org/pombase-trac/wiki/TrackRelabelling

**Comment by ValWood** [comment]
A suggestion

1. Keep the tracks in directories for each biological data type
transcript
chromatin binding
replication profiling
nucleosome positioning
etc

2. Name the files 
First_author_PMID_(some distinguishing criteria for multiple data)

3.
Have a table in each directory with the required metadata tab delimited
https://curation.pombase.org/pombase-trac/wiki/TrackRelabelling
(data type (CV), method (CV), track details, strand, citation)

**Comment by mah11** [comment]
This ticket is not about browser tracks, so the last thee comments should be deleted. They can move to a new ticket if we need to do any work on track names.

**Comment by ValWood** [comment]
OK I moved to a new ticket but this doeas appear to be about files ont he ftp site?

>
The GSE41773 dataset and NRhind_Transcriptome have CU329670.1, CU329672.1 and CU329671.1 - that's a pain.

**Comment by mah11** [comment]
yeah, I spotted that bit afterward (oops), and amended my comment to be more specific for the actually extraneous stuff ... (and I've even had a cup of tea ....)

**Comment by ValWood** [comment]
transferred to
https://github.com/pombase/website/issues/671
