### ISSUE TITLE
Decide on the chromosome IDs to use in contig, GFF,  BAM and BigWig files

### ISSUE THREAD

**Issue by ValWood** [pombase/website#671]
- [x]  put real EMBL IDs into contig files (late at night)

**Comment by ValWood** [comment]
| test| test|

**Comment by ValWood** [comment]
- [ ]  send a message to pombelist to use the  correct names for chromosomes and contigs in their browser files

- [ ]  do a one off fix for all legacy files

**Comment by kimrutherford** [comment]
I've added the data from the table above to the configuration file in SVN (pombe-embl/website/pombase_v2_config.json)

And I've changed the fasta and GFF writing code to use that configuration to put the right IDs in the right places.  So it's now "II", "mitochondrial" etc. instead of "chromosome_2", "MISPCG" etc.

Tomorrow morning, JBrowse should have the right IDs.

**Comment by ValWood** [comment]
This is the mating type region  EMBL entry
https://www.ebi.ac.uk/ena/data/view/FP565355&display=text
will add to the table above and in the json if I can....

**Comment by ValWood** [comment]
@kimrutherford  You will need to do the json.
I'm a bit confused by things like this:

  },
    "AB325691": {
      "display_name": "AB325691"
    }


why is  "AB325691" a display name?

**Comment by kimrutherford** [comment]
> why is "AB325691" a display name?

I didn't what to put as the display name when I first implemented the gene pages so I put that in as a place holder.

I've now updated the config file to match your table.

**Comment by kimrutherford** [comment]
> I've now updated the config file to match your table.

Ah, sorry.  I see the confusion now.  I had made the changes but hadn't checked them in.

**Comment by kimrutherford** [comment]
> do a one off fix for all legacy data files

Do we want to keep the original files (as submitted) or just the fixed up ones.  If we keep the originals, where should the go on the FTP site?

I've just renamed the "DATASET" directory to "external_datasets" on the FTP site.

**Comment by ValWood** [comment]
I don't think there is any pressing need to keep the older files .......

**Comment by ValWood** [comment]
definitely not on the ftp site anyway, it would be confusing...

**Comment by kimrutherford** [comment]
> I don't think there is any pressing need to keep the older files .......
> definitely not on the ftp site anyway, it would be confusing...

OK, I'll move the originals to oliver0 and put the fixed ones in their place.

**Comment by kimrutherford** [comment]
I'm trying to fix the chromosome names in the NRhind_Transcriptome BigWig files.  To do that I've converted the .bw files to .wig files because .wig is text not binary.  I've fixed the .wig files with Perl.

But when I try to convert the .wig back to .bw I get some warnings like this for chromosome 3:

line 3413451 of Spom_all_61G9EAAXX_and_61G9UAAXX.-.sorted.wig: chromosome III has 2452883 bases, but item ends at 2452936

There aren't many warnings but it's a worry that the coordinates of the files don't match the chromosome.  Any idea what could have gone wrong?  Is there a different chr 3 sequence that they could have used?

**Comment by ValWood** [comment]
Asked Nick, not aware of another version. We should check incase the spurious bases are at beginning rather than the end.....

**Comment by kimrutherford** [comment]
Sorry, false alarm!  The EMBL IDs in the table were in the wrong order so the converter was checking the wrong chromosome sizes.  I've fixed the table and change the Perl and now it's all fine.

**Comment by kimrutherford** [comment]
> Sorry, false alarm!

I let Nick know.

**Comment by ValWood** [comment]
What need to happen in this ticket still, can you list.
I put an announce label but what do we need to tell people? Just that the file names have changed? anything else?

**Comment by kimrutherford** [comment]
We still need to do this bit:

> put real EMBL IDs into contig files (late at night)

The nightly load starts at 7:45pm at the moment so any time after that would be good.  We need to coordinate so I can make matching changes to the loader code.

**Comment by ValWood** [comment]
OK can do anytime you think suitable...

**Comment by kimrutherford** [comment]
> OK can do anytime you think suitable...

I've checked in the code changes and the contig changes.  I'm running the load on my desktop to make sure it's all OK.

**Comment by kimrutherford** [comment]
> I've checked in the code changes and the contig changes. I'm running the load on my desktop
> to make sure it's all OK.

Last night's load was fine.

This still needs doing:

> send a message to pombelist to use the correct names for chromosomes and contigs in their browser files

Do we need to tell pombelist or just document it for labs who submit data in future?


> do a one off fix for all legacy data files

The data files we use in JBrowse are fixed.  If there are other files we can fix them as we find them.

**Comment by ValWood** [comment]
Shortly after we release a beta browser we should point everyone to the format we *require* the data to be submitted, and point out the chromosome labelling then....

**Comment by ValWood** [comment]
can close this then....

**Comment by ValWood** [comment]
Antonia you are composing a list of  specification/documentation for browser files. COuld  you roll in the chromsome number with that?
