### ISSUE TITLE
add hyperlinks to term  supporting dbxref on term page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#673]
https://www.pombase.org/term/GO:1990811
ie would link to
PMID:25987607
(as quickGO do)
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990811

include db xrefs supporting term  on term pages
this would be really nice as so many of them are pombe papers.... (well all ogf the FYPo ones obviusly but a good deal of the GO ones)

**Comment by kimrutherford** [comment]
Is this the same as: #589?

**Comment by ValWood** [comment]
yup
