### ISSUE TITLE
ontology term pages, main view, report annotation number

### ISSUE THREAD

**Issue by ValWood** [pombase/website#674]
To see the number of ~annotations~ annotated gene producs from the term page you need to switch to the "gene list view" It might be nice if the number was  in the header regardless.

**Comment by kimrutherford** [comment]
I'm confused.  I can't see the number of annotations on either page.  I can see the number of annotated genes.  Is that what you mean?

**Comment by ValWood** [comment]
yep, annotated genes sorry...

**Comment by kimrutherford** [comment]
> It might be nice if the number was in the header regardless.

I've added the count to the link like this for the next site update:

    View 129 genes annotated with this term ...

Is that OK?  (I put it there so I could avoid having to decide where else on the page it should go)

It's only done for non-phenotype terms at the moment because it was easy.  I'll do phenotypes next.

**Comment by kimrutherford** [comment]
> I'll do phenotypes next.

That's done.  It currently looks like:

    View 141 genes from single-allele genotypes associated with this term ...
    View 168 single-allele genotypes associated with this term ...

It's easy to change things if you'd like the counts somewhere else.

**Comment by ValWood** [comment]
I don't mind it like this. Its slightly inconsistent to have int eh header and out of the header depending on the view but I don't know which place is best. 
Anyone?

**Comment by ValWood** [comment]
will close. We might  tweak where the number is displayed later... but the number is visible from both places.
