### ISSUE TITLE
add archive link for community curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#676]
Should we?

**Comment by kimrutherford** [comment]
It wouldn't be hard to add a community curation archive.  How should the page look?

**Comment by ValWood** [comment]
I think just a list of the full titles with links to the page (maybe with a weekly date heading?)
I often find myself wanting to look at something that was on the front page recently and I suspect others do too, but when it's gone, it's gone....I think it would look good now we have a good number coming in. Maybe only go back as far as the beginning of new PomBase.

We may need to make it more sophisticated later as the page gets long (archiving by month perhaps?)

**Comment by kimrutherford** [comment]
> I think just a list of the full titles with links to the page

Would is be helpful to have the first author and year as well?

**Comment by kimrutherford** [comment]
> maybe with a weekly date heading?

Should the weekly dates groups be based on the submission dates?

**Comment by kimrutherford** [comment]
> Should the weekly dates groups be based on the submission dates?

The list on the front page is ordered by first approved dates, so I'll stick to that initially.

**Comment by kimrutherford** [comment]
This is done but won't be in the main site under Saturday morning.  I needed to make some small changes to the nightly load to implement it so it has to wait until Friday night's load.

**Comment by ValWood** [comment]
> Would is be helpful to have the first author and year as well? 

I think so

**Comment by kimrutherford** [comment]
Here's what it looks like at the moment:
  https://www.pombase.org/reference_list/community

It not grouped by week yet and there is no link from the main page.  This is just so we can see how it looks.

**Comment by ValWood** [comment]
Nice,

what should we call it
"recent community curation"?

**Comment by mah11** [comment]
Call it what it is: "Community curation spotlight archive"

**Comment by kimrutherford** [comment]
> what should we call it "recent community curation"?

How far back counts as recent?

> "Community curation spotlight archive"

Currently it isn't an archive because it shows all community curation from Canto, not just curation that has been on the front page.

**Comment by kimrutherford** [comment]
> I think just a list of the full titles with links to the page (maybe with a weekly date heading?)

We should chat about this.  Are weekly heading what we want?

**Comment by ValWood** [comment]
Will close. We can open a new ticket if we want to slightly reorganize the page in any way.
