### ISSUE TITLE
check source of PRO url root

### ISSUE THREAD

**Issue by ValWood** [pombase/website#677]
see 

https://sourceforge.net/p/pro-obo/term-requests/120/

**Comment by ValWood** [comment]
What do we use? I forget.

**Comment by ValWood** [comment]
should use 
http://pir.georgetown.edu/cgi-bin/pro/entry_pro?stanza_id=PR:000044735

**Comment by mah11** [comment]
actually, as both Darren's latest comment and the current GO metadata say, the best thing to use is the PURL syntax

    http://purl.obolibrary.org/obo/PR_[example_id]

... where example_id is just the part after the prefix (e.g. as in the example URL in the file - http://purl.obolibrary.org/obo/PR_000025380)

GO xrefs now at https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by kimrutherford** [comment]
> What do we use? I forget.

We're using `http://purl.obolibrary.org/obo/PR_[example_id]` which redirects to pir.georgetown.edu

> GO xrefs now at https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

We're currently using doc/GO.xrf_abbs from GO SVN.  A comment at the top of the file says it's generated from db-xrefs.yaml

**Comment by ValWood** [comment]
Sorry I copied the incorrect URL from the ticket.

what we are using seems to be the correct thing?

**Comment by ValWood** [comment]
the link we are using here:
https://www.pombase.org/gene/SPAC20G8.05c
which was non functional yesterday, is working now...
http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PR_000044734
just a  time lag issue...

**Comment by kimrutherford** [comment]
When I tried one of the gene page links earlier I got an error message from pir.georgetown.edu so it's not just you.

**Comment by ValWood** [comment]
Oh actually it might  be a general issue, PubMed has been inaccessible most of today too.....
