### ISSUE TITLE
FAQ for unmapped genes

### ISSUE THREAD

**Issue by mah11** [pombase/website#678]
to make it easier to find https://www.pombase.org/status/unmapped_genes

**Comment by Antonialock** [comment]
is this cloning what's on the wiki or should we just use this for now?

**Comment by mah11** [comment]
The web page is the current home for this info. I've edited the wiki page.

Note to self: add these to page:
- all cps genes add PMID:1524835
- glu1-115 PMID:7903653
- ird genes PMID:24301766, PMID:16377914, PMID:26301056
