### ISSUE TITLE
describe how to prepare flat file GO data submission

### ISSUE THREAD

**Issue by ValWood** [pombase/website#68]
Unlikely anyone will want to do this, but we should add  to submission docs/website for completion (we can already  process GAFs)

pombe-embl/external_data/external-go-data

**Comment by ValWood** [comment]
For example PMID: 23770677 might use it.......

**Comment by mah11** [comment]
Form created on dev, and linked to main Submit Data page. Open a new ticket if you want it added to the menu, since I can't do that bit anyway.

**Comment by ValWood** [comment]
No hurries to link, its not as if its likely to be used much, and at least we can point people to it if they ask now...

Will include it in the next menu update request. I don't want to ask for too many things  simultaneously until update sorted and "list search" and "all genes" search are back....
