### ISSUE TITLE
add curation date  to publication page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#680]
so that it it clear when curated (especially that pombase staff are curating older papers)
(date  first approved, date first submitted )

**Comment by ValWood** [comment]
use whatever we use on our stats page.

**Comment by ValWood** [comment]
see "canto curator summary"
here, and use the same date
 https://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
KMR : submitted date

**Comment by kimrutherford** [comment]
> (date first approved, date first submitted)

Should we have both dates?

**Comment by ValWood** [comment]
We could, one will do tho'

**Comment by kimrutherford** [comment]
I went for the "first approved" date:
   https://www.pombase.org/reference/PMID:689088

Do we want a few words in front of the date, like: "Added to PomBase on 2015-07-20"

**Comment by ValWood** [comment]
Yes, it keeps people informed that we are busy doing this too, right now...

**Comment by kimrutherford** [comment]
I've changed the text for tomorrow's update.
