### ISSUE TITLE
filtering with NOT annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/website#683]
This is *nearly *right

![transmembrane](https://user-images.githubusercontent.com/7359272/36328997-31acbb80-135c-11e8-9308-749ba4660584.jpg)
but, you should see the hidden "transmembrane transport" annotation by default

(this could be because IGI trumps IEA rather than anything specific to the NOT annotation,
but NOT should be ignored for any filtering scenario

**Comment by ValWood** [comment]
it's very non-urgent

**Comment by kimrutherford** [comment]
What gene was that so I have an example?

**Comment by ValWood** [comment]
SPAC1B3.15c

**Comment by kimrutherford** [comment]
This is low priority but it was a quick fix so I did it anyway.  It will be in tomorrow's update.

**Comment by ValWood** [comment]
still the same?

**Comment by kimrutherford** [comment]
Sorry, when I said tomorrow, I meant Friday.

**Comment by kimrutherford** [comment]
Fixed.
