### ISSUE TITLE
annotation counts sometimes missing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#684]
I screen-shotted this and stupidly forgot to record which gene.

![no count](https://user-images.githubusercontent.com/7359272/36329218-1567f43e-135d-11e8-88c3-4b8a6d5f4edc.jpg)

However, I found another one 

https://www.pombase.org/gene/SPBC215.02
(here the nucleus total is missing)

**Comment by kimrutherford** [comment]
I've fixed that for the next update.  The changes I made when playing with #473 triggered a display bug.  It's doing the right thing now.

**Comment by kimrutherford** [comment]
Now fixed on the main site.
