### ISSUE TITLE
new canned query

### ISSUE THREAD

**Issue by ValWood** [pombase/website#685]
Add "protein coding genes, unknown process"
to canned queries

710	(subset: characterisation_status:conserved unknown OR subset: characterisation_status:S. pombe specific protein, uncharacterized OR subset: characterisation_status:Schizo. specific protein, uncharacterized)

We already have it on this page:
https://www.pombase.org/status/priority-unstudied-genes

**Comment by kimrutherford** [comment]
I've added that for tomorrow's update.
