### ISSUE TITLE
broken link in FAQ

### ISSUE THREAD

**Issue by ValWood** [pombase/website#688]
from HGNC:

"When looking around the PomBase website to determine how to retrieve the data for HCOP I noticed a few broken links on one of your FAQ pages https://www.pombase.org/faq/genome-browser "

**Comment by mah11** [comment]
That was not exactly a helpful error report. It would have been sporting to indicate which links were broken in which specific FAQ(s). But I found by checking manually that it was browser URLs, and they're updated now.

**Comment by ValWood** [comment]
I thought it was quite informative!
