### ISSUE TITLE
trac log in error

### ISSUE THREAD

**Issue by ValWood** [pombase/website#689]
log in gives:
Authentication information not available. Please refer to the installation documentation.

**Comment by kimrutherford** [comment]
I've just turned the logging on.  Can you try again?

**Comment by ValWood** [comment]
I still get this:

![untitled](https://user-images.githubusercontent.com/7359272/36474888-d783bdbe-16f0-11e8-9552-32e814bf83a6.jpg)

little message like a file for download saying server error...

**Comment by kimrutherford** [comment]
Could it be that you're using http://curation.pombase.org/pombase-trac/ instead of https://curation.pombase.org/pombase-trac/ ?

ie. HTTP instead of HTTPS

**Comment by ValWood** [comment]
durr, I need to fix my bookmark...not paying attention, too busy moaning ;)

**Comment by kimrutherford** [comment]
No problem.  I would normally have set it up to redirect HTTP to HTTPS but I was in a hurry.
