### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#694]
old ensembl browser
https://www.pombase.org/status/centromeres

**Comment by ValWood** [comment]
also
https://www.pombase.org/genotype/e5a15cdcd4aa21c4-genotype-6
from
https://www.pombase.org/about/new-pombase
@kimrutherford  are these "stable" links?

**Comment by kimrutherford** [comment]
Genotype links aren't stable.

**Comment by kimrutherford** [comment]
> mah11 closed this in dc9be91 5 hours ago

The changes will be in tomorrow's update.
