### ISSUE TITLE
Document JBrowse configuration

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#696]

**Comment by kimrutherford** [comment]
Done, but let me know if I've forgotten anything:
 https://github.com/pombase/website/wiki/JBrowse-Configuration

**Comment by Antonialock** [comment]
I've added in extra columns, I thought I checked it in last Sunday but doesn't look like I did. I'm not finished anyway, I'll update the docs once I'm finished.

**Comment by Antonialock** [comment]
done
