### ISSUE TITLE
Split feature track into forward, reverse and unstranded 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#697]
Have all three on by default.

**Comment by kimrutherford** [comment]
We need to fix the unstranded features to complete this: pombase/pombase-chado#668

**Comment by kimrutherford** [comment]
Done for tomorrow's load.

**Comment by kimrutherford** [comment]
It's live now.  I'm not sure it makes the display clearer though:
  https://www.pombase.org/jbrowse/index.html?loc=II%3A1..349000&tracks=PomBase%20reverse%20strand%20features%2CDNA%2CPomBase%20forward%20strand%20features&highlight=

**Comment by ValWood** [comment]
I think it is MUCH clearer, but I'm used to looking at it this way. It saves a lot of  thinking about what is where.

One thing, forwards strand at the top please ;)

**Comment by ValWood** [comment]
at this resolution it doesn't help so much but if you zoom in its MUCH better.

**Comment by kimrutherford** [comment]
> One thing, forwards strand at the top please ;)

It is by default but I had been playing around.  You can drag the tracks to where you want them.

**Comment by ValWood** [comment]
Oh cool...I'm not used to this fanciness!

**Comment by kimrutherford** [comment]
If you click through to JBrowse from the pombase-dev gene pages both strands are displayed.  With forward at the top.  :-)

**Comment by ValWood** [comment]
lovely ;)
