### ISSUE TITLE
Replace the inline Ensembl image on the gene pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#698]
We'd like a very simple view.

This is a possibility: https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer

**Comment by kimrutherford** [comment]
> This is a possibility: https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer

Instructions for loading GFF files:
https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/2

**Comment by ValWood** [comment]
Something very simple like this is fine:

![simple](https://user-images.githubusercontent.com/7359272/37457893-339b6dee-283b-11e8-88d9-83a0c8d8ec1c.jpg)

**Comment by ValWood** [comment]
suggest
- [ ] feature labelled with name and type
- [ ] coordinates
- [ ] x  features  or bases upstream and downstream (how should we decide this. I remember long discussions last time)
- [ ]  ideally you could click on genes in the image to navigate to  other pages (so we would not need to duplicate the gene list  underneath

**Comment by kimrutherford** [comment]
I had a look at that package but it wasn't clear that GFF so a supported file format.  I'll dig deeper.

**Comment by kimrutherford** [comment]
The latest result of JBrowse has made it easy to embed JBrowse in another page.  It's probably worth investigating.

http://jbrowse.org/jbrowse-1-14-0-release/

**Comment by ValWood** [comment]
that's good!

**Comment by kimrutherford** [comment]
Closing in favour of: #987
