### ISSUE TITLE
difference in numbers "conjugation with cellular fusion"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#699]
see mfm1 is annotated to
http://pombase-dev.bioinformatics.nz/term/GO:0000747
but not slimmed to this process?
http://pombase-dev.bioinformatics.nz/gene/SPAPB8E5.05

**Comment by ValWood** [comment]
(Alert: I could have done something silly, but I can't see what...)

**Comment by kimrutherford** [comment]
I'm confused.  I can't see an annotation to GO:0000747 on the SPAPB8E5.05 page.  What am I missing?

**Comment by ValWood** [comment]
not a direct annotation, but it is annotated to a child term

pheromone-dependent signal transduction involved in conjugation with cellular fusion

I would presume this was  a GO issue, but I'm wondering why we have it  annotated to  GO:0000747 by the term list but not by the slim. I think it might be GO still, but I'm wondering why we are internally slightly out of synch? It seems that we get the GO slim data from a different place/ or time to the annotation maybe?

**Comment by kimrutherford** [comment]
> not a direct annotation, but it is annotated to a child term

I can't see it in the list of child terms here:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000747

It appears in the "Co-occurring Term" list though.

> annotated to GO:0000747 by the term list but not by the slim

What do you mean by term list?  SPAPB8E5.05 isn't on the GO:0000747 page?

**Comment by ValWood** [comment]
hmm, you are right. I said I probably did something  silly...

**Comment by ValWood** [comment]
The plot thickens:

http://pombase-dev.bioinformatics.nz/term/GO:0000747

not here

https://www.pombase.org/term_genes/GO:0000747

**Comment by kimrutherford** [comment]
I still don't understand.

I can't see an annotation for SPAPB8E5.05 on http://pombase-dev.bioinformatics.nz/term/GO:0000747 and it's not here either: https://www.pombase.org/term_genes/GO:0000747

The only mention of mfm1 is this on the term page:

    peptide pheromone transmembrane export involved in positive regulation of conjugation with cellular fusion
	  mam1 transports mfm1 , mfm2 , mfm3

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/gene/SPAPB8E5.05
is annotated to 
http://pombase-dev.bioinformatics.nz/term/GO:0000750

from here..I can go
http://pombase-dev.bioinformatics.nz/term/GO:0032005
http://pombase-dev.bioinformatics.nz/term/GO:0031139
http://pombase-dev.bioinformatics.nz/term/GO:0031137
http://pombase-dev.bioinformatics.nz/term/GO:0000747

mfm1 is on this page?

but GO:0000747 is not recognised as  a slim catagory for mfm1?

**Comment by kimrutherford** [comment]
> http://pombase-dev.bioinformatics.nz/term/GO:0000747
> mfm1 is on this page?

I still can't see mfm1 on that page.  But I've noticed a bug when I click "Show details..."  I'll fix that and then check again.

**Comment by ValWood** [comment]
Oh sorry, it's a substrate, not an annotated gene. I'll go back to my old ticket... I now think it's a GO issue again...

**Comment by kimrutherford** [comment]
> I still can't see mfm1 on that page. But I've noticed a bug when I click "Show details..."

I've fixed that.  There was an internal javascript error when "Show details.." was clicked.  It caused some of the annotation details to not display.
