### ISSUE TITLE
BioGRID attribution

### ISSUE THREAD

**Issue by ValWood** [pombase/website#700]
In the old PomBase we used to acknowledge that the genetic and physical interactions were curated by bioGrid. We no longer do this. we should discuss how to reinstate on Thursday....

**Comment by ValWood** [comment]
This is straightforward. We just need to decide what to add at the top of the page section (genetic and physical).

@mah11  @Antonialock   do you know what we used to say?
![text](https://user-images.githubusercontent.com/7359272/37457803-ec780030-283a-11e8-829a-5cbfe76146e9.jpg)

**Comment by ValWood** [comment]
@Antonialock  find old text

**Comment by Antonialock** [comment]
this is what it used to look like:
![screen shot 2018-03-15 at 13 25 17](https://user-images.githubusercontent.com/12727506/37465968-801e65fe-2854-11e8-91a4-430444b64ce6.png)


this is the relevant JIRA ticket:

![screen shot 2018-03-15 at 13 26 52](https://user-images.githubusercontent.com/12727506/37466002-933b5d36-2854-11e8-8df3-2d1f9fa891f3.png)

https://www.ebi.ac.uk/panda/jira/browse/PB-260?jql=project%20%3D%20PB%20AND%20text%20~%20%22biogrid%22%20ORDER%20BY%20created%20DESC

**Comment by kimrutherford** [comment]
So should we just add "Source: BioGRID" with a hyperlink?

**Comment by ValWood** [comment]
I think that will do.

**Comment by ValWood** [comment]
this seems quick ( just going through the"discuss" tasks on the last agenda)

**Comment by kimrutherford** [comment]
I've added a link to BioGRID.  It will be in tomorrow's update.
