### ISSUE TITLE
links busted/ and table rendering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#701]
annotation file formats
https://www.pombase.org/submit-data/bulk-annotation

**Comment by ValWood** [comment]
I was seeing the gene page menu before, its all fine now anyway...maybe you fixed

**Comment by ValWood** [comment]
Oh no the problem is after you click for the format. You get the gene page menu.

**Comment by ValWood** [comment]
and when you get there the table formatting  in the modification file format 
https://www.pombase.org/documentation/modification-data-bulk-upload-format
is not rendering.

(i'm going to send the link to somebody)

**Comment by ValWood** [comment]
note to self send to jamie re 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4424399/

**Comment by kimrutherford** [comment]
> Oh no the problem is after you click for the format. You get the gene page menu.

Could you add a link to the page where you see that?

I've fixed the table formatting on the modification file format page.  And fixed the links to the qualitative and quantitative format page from the "Annotation dataset submission" page.  It will be re-released in 10-ish minutes.

**Comment by ValWood** [comment]
click on  any "file format" from here

https://www.pombase.org/submit-data/bulk-annotation

**Comment by ValWood** [comment]
still table:
https://www.pombase.org/documentation/modification-data-bulk-upload-format

**Comment by kimrutherford** [comment]
I'm getting some system errors from the server at Babraham so I haven't been able to re-release.  The main site will be offline for a few seconds while I restart things.

**Comment by kimrutherford** [comment]
> click on any "file format" from here

Ah, thanks.

@mah11, I think the fix is to remove the "gene-names" directory in the documentation and put it all under "submit-data" with whatever sub-menus are needed.  I'm happy to do that if you think that's right.

**Comment by kimrutherford** [comment]
> still table:

Fixed now.

**Comment by mah11** [comment]
@kimrutherford 

> I think the fix is to remove the "gene-names" directory in the documentation and put it all under "submit-data" with whatever sub-menus are needed.

Nope, it was wrong URLs (missing 'data-' in the middle of some). I see you fixed them on the submit-data/bulk-annotation page, and I've done a straggler I found in a FAQ. The ones you fixed are working now. One more update will make that last fix live, and this can close.

I think if the problem had been menus or directory structure, the links from the main Documentation page wouldn't have worked, and they've been fine all along.

**Comment by ValWood** [comment]
Kim will add the submenu of gene names to the main submit menu

**Comment by kimrutherford** [comment]
Fixed on the main site.
