### ISSUE TITLE
Show the matching synonym when autocompleting

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#705]
I think we should show the matching synonym somehow when autocompleting terms in the advanced search.  Like in Canto:

![iron_transport_complete](https://user-images.githubusercontent.com/90474/37322627-a0c1f4fa-26e3-11e8-9564-076c0edbc834.png)

and then show the matching synonym after the user selects a term:

![iron_transport_details](https://user-images.githubusercontent.com/90474/37322634-a7df77f8-26e3-11e8-9ad0-e74dd2c5cc89.png)

**Comment by kimrutherford** [comment]
Maybe there should be a link to the term page once the user selects a term?  Maybe it should open in a new tab?  I'm not a fan of that but I think it would be appropriate in this case.

**Comment by ValWood** [comment]
Above looks fine to me.
Can discuss Thursday.

**Comment by ValWood** [comment]
I'm not sure how this would work. I think showing that something is a synonym is good. But you don't immediately go to the results page from a search, you see:
![search](https://user-images.githubusercontent.com/7359272/37457601-5eb5af40-283a-11e8-80ee-f93d1e7fbe44.jpg)

**Comment by ValWood** [comment]
then
![syn](https://user-images.githubusercontent.com/7359272/37457688-9018ea5c-283a-11e8-8104-aa5c89e9c316.jpg)


(I guess it could be listed somewhere)

**Comment by kimrutherford** [comment]
I was thinking it should show the details and a link after you autocomplete, but before you click "submit".

**Comment by ValWood** [comment]
**Biological process** The directed movement of iron (Fe) ions into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. **Matched synonym: iron transport**

**Comment by ValWood** [comment]
Short term
Show matched synonym

Long term
preferred behaviour, pop out at the side like canto so you see def before selection.

**Comment by kimrutherford** [comment]
I changed the term name autocomplete to show the matching synonym.  It will be live in the morning.

**Comment by kimrutherford** [comment]
I've added new issues for the remaining things: #718 and #719
