### ISSUE TITLE
lucene

### ISSUE THREAD

**Issue by ValWood** [pombase/website#706]
I don't know if this happened recently or it has always been like this, but I noticed recently that a couple of times I could not easily access terms which were exact matches but  where the string was a substring of many  longer term names

examples include:
endoplasmic reticulum
nuclear membrane
mitochondrion

**Comment by kimrutherford** [comment]
That's not good!  I'll see if it can be tweaked.

**Comment by ValWood** [comment]
transferase activity
(definitely very recent,  it was better before the recent changes when it didn't find some synonyms...)

**Comment by ValWood** [comment]
transmembrane transport
not found

**Comment by ValWood** [comment]
DNA repair not found

(I think it was better before the changes to find the synonyms, at least for exact term matched). There are quite a few others I  could not find that I didn't record (I'm going to QuickGO for look up quite a bit and pasting the ID in to get to the term)

If you are busy with other stuff I would revert to how it was before we fixed for "V-shaped spindle" because it was pretty good then!

**Comment by kimrutherford** [comment]
I've just updated the main site with some fixes.  All of the terms you've been looking for are now back on the list but not always at the top.  I have some other fixes ready to go that I'll try tomorrow.

**Comment by ValWood** [comment]
It's OK if they aren't at the top, as long as we see them. It would be better if exact match was at the top, but not critical.

**Comment by kimrutherford** [comment]
> I have some other fixes ready to go that I'll try tomorrow.

I've done that and it's live on the main site.  Most of your examples now come up as top-ish hit.  Let me know if you spot other problems.
