### ISSUE TITLE
can't access motif search

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#709]
https://curation.pombase.org/cgi-bin/sanger_motif_search

![screen shot 2018-03-15 at 14 04 00](https://user-images.githubusercontent.com/12727506/37468045-ca81841e-2859-11e8-8009-abdb430e572e.png)

**Comment by ValWood** [comment]
This probably happened with the move to the virtual server?

**Comment by kimrutherford** [comment]
I forgot to copy it over to oliver1.  It's fixed now although the image at the top is missing.  I fix that before closing.

**Comment by kimrutherford** [comment]
> the image at the top is missing.

I've fixed that.
