### ISSUE TITLE
advanced search, retrieving proteins 

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#710]
To get all protein coding genes, my student used the query builder
product type -> protein

Could we have some help-text or similar stating that this will retrieve all protein coding genes including dubious and transposons, and if they don't want those they can retrieve the canned query?

**Comment by kimrutherford** [comment]
I think this is related: #657

**Comment by ValWood** [comment]
added to
https://github.com/pombase/website/issues/657#issuecomment-373667611
