### ISSUE TITLE
Change community curation word cloud size

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#712]
I'd prefer if the word cloud image for the community curation was the same height as the images to the left and right.  I think it would look better.

We have room for that I think.

What do you think?

![community_curation_1](https://user-images.githubusercontent.com/90474/37684255-50fc3a9a-2cf4-11e8-8a7b-cdac81b24e68.png)

**Comment by ValWood** [comment]
Yes I was going to suggest this soon. It is only a smaller size because of my suggestion to include more of the titles text. I would  prefer if it went back to the same size as the other images and the  title length was shorter if this helps.

**Comment by Antonialock** [comment]
I don't think the title length needs to shorten? tehre is a lot of white space at the bottom.

"all community curation" could change to "archive" too?

**Comment by kimrutherford** [comment]
> I don't think the title length needs to shorten? 

Yep, I'll try it first without changing the title length.

Do you have an updated word cloud?

**Comment by Antonialock** [comment]
it takes a while to make. That one is just a month and a bit old, I don't think it is worth making a new one already

**Comment by ValWood** [comment]
Yeah I think every 6 months  or so for the word cloud. It won't change so much. There was a big change last time because Antonia changed from number of annotations to number of papers.

**Comment by kimrutherford** [comment]
OK.

I don't have the original image file.  Is it in Dropbox?

**Comment by ValWood** [comment]
Yep, "front page rotations/community curation feed"

**Comment by ValWood** [comment]
What is our preferred aspect ration?
That way it can probably be tailored more next time?

**Comment by kimrutherford** [comment]
The images are 300x185 pixels.

For now, we can pad and crop quite a bit without it looking much different.

**Comment by kimrutherford** [comment]
> Yep, "front page rotations/community curation feed"

Thanks!

I've changed the image height and fixed a bit of HTML style.  It should be in tomorrow's update.

**Comment by ValWood** [comment]
yep, much better.

**Comment by ValWood** [comment]
> The images are 300x185 pixels.

I put a note in the readme in the front page rotations drop box folder. We can aim to this size
