### ISSUE TITLE
Colour coverage tracks by strand

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#713]
User request: colour the stranded data.

The easiest way is to add a "strand" column to `pombase_jbrowse_track_metadata.csv`

**Comment by Antonialock** [comment]
the strand column is in the config file

**Comment by kimrutherford** [comment]
> User request: colour the stranded data.

The forward strand data is now a different colour from the reverse strand tracks.  The colours might not be the best though.  Any suggestions?

**Comment by Antonialock** [comment]
I think red and blue is fine! It's commonly used. I think it is more common however to set the plus strand to blue and reverse strand to red, so swap around?

**Comment by kimrutherford** [comment]
> so swap around?

Done for tomorrow's update.

**Comment by Antonialock** [comment]
looks great!
