### ISSUE TITLE
Download option from query builder not working (www and dev)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#714]
for me, I can't download anything.

Also on www I have not been able to search on GO terms or IDs

v

**Comment by kimrutherford** [comment]
The autocomplete in the advanced search isn't working either.  I'm looking at it now.

**Comment by kimrutherford** [comment]
I've restarted and it's working again.

I think this is the same as #646 but this time I have a clue in the logs as to what's going on.  It looks like if a very long blob of text is pasted into the autocomplete box (accidents happen), Lucene reports an error about the query being too long, then my code falls over.  I'll change my code to:

  - handle errors gracefully

and 

  - send a sensible maximum query to Lucene (maybe 200 characters)

**Comment by ValWood** [comment]
I could have easily cut and pasted  an essay into there by mistake ;)

**Comment by kimrutherford** [comment]
I've changed the server code to cope with errors from Lucene/Solr.  And I've changed it to send a maximum of 200 characters to Solr.  That should improve reliability.  The change will be live on Monday.
