### ISSUE TITLE
protein features not showing on gene pages 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#715]
http://pombase-dev.bioinformatics.nz/gene/SPBC146.10

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/gene/SPBC146.12

**Comment by kimrutherford** [comment]
That's fixed now.  In this case it was the display code that was failing.

In the latest InterPro update they changed the database name for Gene3D to CATHGENE3D.  The URL for that database name wasn't configured which cause the display code to fall over and not display the table of InterPro results.

I've fixed the display code to cope with that sort of change more gracefully and I've added an alias to the configuration for CATHGENE3D see the link from the ID works.
