### ISSUE TITLE
Show definition and other details when looking at term autocomplete results

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#718]
Ideally in a similar way to Canto:

![term_complete_details_1](https://user-images.githubusercontent.com/90474/37943613-bf48ce8e-31d4-11e8-846f-8c243c6a1c75.png)

**Comment by ValWood** [comment]
Is this quick. If so do soon, otherwise change label to "low priority"

**Comment by kimrutherford** [comment]
> Is this quick. If so do soon, otherwise change label to "low priority"

I haven't worked out how to do it on the website so I don't think it will be quick.

**Comment by kimrutherford** [comment]
It was tricky to implement this in the same way as Canto so I've changed things so that the definition is shown as you mouse-over the completion suggestions.  Let me know if that's too annoying.

![term-complete-def-1](https://user-images.githubusercontent.com/90474/92542744-b2b1b780-f29d-11ea-9400-c2bd26b7669b.png)

**Comment by kimrutherford** [comment]
Can I close this?

**Comment by ValWood** [comment]
I think it's OK, but I find the white on blue quite difficult to read.

**Comment by kimrutherford** [comment]
> I find the white on blue quite difficult to read.

I'll see if I can make it more readable, maybe by using the same style as Canto.

**Comment by kimrutherford** [comment]
How's this?:
![name-complete-colour-1](https://user-images.githubusercontent.com/90474/106139439-4e52ae80-61d2-11eb-9c8d-3ef1f66df534.png)

**Comment by ValWood** [comment]
.I'm not sure...it is probably more readable. But now my eye is drawn more to the non-highlighted terms ....I think I marginally prefer the existing now I am used too it. Maybe the definition font size is my main problem....

**Comment by kimrutherford** [comment]
OK.  I'll leave it as is for now.

**Comment by kimrutherford** [comment]
I think this can be closed now.
