### ISSUE TITLE
Highlight the matching words in the term name autocompletions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#719]
Like Canto:

![term_complete_details_2](https://user-images.githubusercontent.com/90474/37943851-e049e4dc-31d5-11e8-82bc-a2e8d25ea262.png)

**Comment by ValWood** [comment]
nice but none urgent. Is it quick?

**Comment by kimrutherford** [comment]
> nice but none urgent. Is it quick?

It's probably an hour or two.

**Comment by ValWood** [comment]
OK we can keep it on the back burner....

**Comment by ValWood** [comment]
I think you have  done this?

**Comment by kimrutherford** [comment]
The highlighting works nicely in the quick search but not in the query builder yet.  It's not a big job as it's mostly re-using the same code.

I almost did this yesterday but got distracted by Canto work for James.

**Comment by kimrutherford** [comment]
> The highlighting works nicely in the quick search

That's not true.  :-)  I don't know why I thought it was.

Most of the work is this finished.  I'll complete it in the next week or two.

**Comment by kimrutherford** [comment]
I've implemented this now.  I think I committed the change in time for tonight's load.  If it's not working in the morning, it should be by Saturday morning.

I'll leave this issue open until I've confirmed that.

**Comment by kimrutherford** [comment]
That's working now.

**Comment by ValWood** [comment]
nice thanks
