### ISSUE TITLE
modified form display

### ISSUE THREAD

**Issue by ValWood** [pombase/website#72]
For this 
I added 
has_input SPAC27F1.02c , has_input PR:000037082

![add protein too](https://cloud.githubusercontent.com/assets/7359272/18324040/642c943c-7532-11e6-96cf-5ef5f8d2cefd.jpg)

so we can see that its cut 8.  

However, this will look like 2 inputs.

MAybe longer term we want to display as
cdc8(PRO ID)

**Comment by mah11** [comment]
duplicates #67
