### ISSUE TITLE
JBrowse config file outstanding tasks

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#720]
- Intron branch point data is not showing (was showing in old browser)
 - Variation track is missing
 - track selector filter for "curated sequence and features" for forward/reverse strand + genome sequence and sticky at the top of the filters? (I can't see those tracks in the config file so maybe belongs to a different ticket..)

DONE- Display forward and reverse strand tracks in different colours
 

DONE - Wilhelm data is not live (wasn't in ensembl either) I curated the labels
 DONE - I added some additional columns that we could be showing (at least in the "about this track" section)
DONE - I think it would be nice to have a couple of additional filters e.g. "gene" (filter on label called "target_gene" and "allele" (filter on  column headed "allele(s)) - if this is unpopulated then it is sort of like a WT dataset, but there may be background mutations (how could we label those those? @ValWood ), and for the column headed cycle/phase/strand (feel free to relabel these headers by the way, I just came up with some quick grouping term)
DONE - "publication date" (year) is probably not a useful filter? study ID, PMID, and first author information should suffice for people to find the right dataset if they come from "that route"

Note, Val requested in old ticket that we "don't show" dbXrefs other than GEO, but we need to because some data was deposited in arrayexpress, etc. I therefore split this into "study_ID" and "DB" eg. 
GSE24360 | GEO

**Comment by kimrutherford** [comment]
> Intron branch point data is not showing (was showing in old browser)

Where can I get the file for that data?

> Variation track is missing

If that's a VCF file I think JBrowse can display it.  Do you know where the data is?

> Wilhelm data is not live (wasn't in ensembl either) I curated the labels

You can change the `display_in_jbrowse` column in the CSV file to "yes" when you think it's ready.

> I added some additional columns that we could be showing 

You can add columns by editing the `displayColumns` section of `pombe-embl/website/trackList.json` in SVN.

**Comment by ValWood** [comment]
I was looking here. I shift reloaded lots. Am I looking in the wrong place?

http://pombase-dev.bioinformatics.nz/jbrowse/?loc=III%3A713804..733804&tracks=PomBase%20forward%20strand%20features%2CDNA%2CPomBase%20reverse%20strand%20features&highlight=

**Comment by ValWood** [comment]
> I think it would be nice to have a couple of additional filters e.g. "gene" (filter on label called "target_gene" and "allele" (filter on  column headed "allele(s)) - if this is unpopulated then it is sort of like a WT dataset, but there may be background mutations (how could we label those those? @ValWood

good idea....not sure what to call it

 > SGD label the "annotated sequence features" "canvas features" we could go with that for forward/reverse strand + genome sequence and sticky at the top of the filters? (I can't see those tracks in the config file so maybe belongs to a different ticket..)

I'm not keen on "canvas features" I prefer "curated sequence features". Is that too long?

**Comment by ValWood** [comment]
spreadsheet looks great.

for "target gene" is it always a chromatin localized protein?

**Comment by Antonialock** [comment]
@kimrutherford 

- the intron branch point data is here: https://www.ebi.ac.uk/panda/jira/secure/attachment/16497/BranchPointForVal.bed.txt
PB-2080 deals with loading this into ensembl. Mark said _"I have had to slightly modify the bed file to be more descriptive, but it now works as a user loaded file. Will modify the config file and place a copy on the FTP"_ but no more detail

 - You are right the variation data is a VCF file. I have no idea where it lives. This ticket suggests that the variation data was uploaded to the EBI? https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=132563
I can't find the file though
some detail here:https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=130286

Also found a comment on track labelling for this: Change track labelling from
Jeffares_Indels and Jeffares_SNPs 
To
Variation- NGS -Indel -Jeffares (2015)
Variation- NGS -SNP -Jeffares (2015)

@ValWood 
 - ""curated sequence features" doesn't work I think because there's genome sequence in addition to for/rev sequence features. -> Sequence and features?

 - at the moment target_gene is always chromatin localization (maybe there is some assay that I can't think off on top of my head...but basically where a gene product has been physically assayed

**Comment by mah11** [comment]
Quoth @Antonialock 
>  You are right the variation data is a VCF file. I have no idea where it lives.

I think I may have found the data, deep in the bowels of the ftp-private.ebi.ac.uk site (path upload/pombase/jeffares-diversity-data). I'll email files to @kimrutherford off-ticket to check.

**Comment by Antonialock** [comment]
thanks Midori.

I've made some changes which, as long as I haven't broken things..., should update what is displayed in the tarck selector and the "about this track" information.

@kimrutherford 
 - we also wanted forward and reverse strand tracks to display in different colours 
 - can we make a label for the "key" (sequence features and genome sequence) tracks so that they are shown at the top of the track selector (name it genome sequence and features)

**Comment by ValWood** [comment]
curated features?
I think it might be useful to say curated. If not go with "sequence and features"

I think target_genes works unless @mah11  has any ideas?

**Comment by kimrutherford** [comment]
> we also wanted forward and reverse strand tracks to display in different colours

Is that this issue?: #713

**Comment by Antonialock** [comment]
Looks like it!

**Comment by Antonialock** [comment]
I have deleted some old comments. Three outstanding tasks here (sorry for not making separate tickets from the start, I should have done).

I'll make new tickets.
