### ISSUE TITLE
PomBase tracks

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#723]
Can we add another column (which will show at the top of the "select tracks" menu) for "PomBase tracks"?
(DNA / forward features / reverse features)

Also hide any instances of (no data) from the filters?

**Comment by ValWood** [comment]
Doesn't  the  "No data" just need different labels?

i.e data type  "sequence features" or whatever we decided to call it?

reference  PMID: 11859360

etc

**Comment by Antonialock** [comment]
Well, there's "no data" for more than those datasets.

Sometimes you get "all data" within a study (I don't know if that actually incldues "all data" - e.g. a study spanning looking at glucose starvation, heatshock etc etc why would they bung all data into one track? Maybe it means something else..)

**Comment by Antonialock** [comment]
But yes I guess you could add author PomBase and ref PMID 11859360 to those three PomBase tracks @kimrutherford

**Comment by ValWood** [comment]
so if it is "all data" it should stay  "all data" but I don't know how this would be used.

the labels should be explicit...

growth phase or response 9 have "no data" ...6  look as though  they should have?

we should make it so that "no data" really is "no data" and then it need not be displayed?

ideally there would be something visible though???

**Comment by Antonialock** [comment]
what should say all data?

The 6 look like they should have what label?

**Comment by ValWood** [comment]
I don't know but presumably most likely  "vegetative growth" ?

**Comment by Antonialock** [comment]
well, they also show meiosis in that paper...so if the description says "all tracks"..?

**Comment by Antonialock** [comment]
I tried looking at www.pomba.co.uk which is where the shlackow dataset was deposited but it's down

**Comment by Antonialock** [comment]
the other dataset is from rhind

**Comment by Antonialock** [comment]
we could just not show these tracks? but maybe they are useful?

**Comment by ValWood** [comment]
Ah right these are the "combined tracks" you referred to....
"all tracks" is definitely more informative than "no data"

So, I don't know if people use these so I would be happy to hide them. People might want to see all polyadenylation sites at the same time if they are viewing lots of other tracks simultaneously, so it's difficult to know. No harm in leaving them in for now...

**Comment by Antonialock** [comment]
ok so they say
Results from all data sets are combined and accessible in our Pomb(A) database, which also allows customizable motif search around the CS.

Should we disable the combined tracks? or create a label for "multiple (combined data)"

**Comment by ValWood** [comment]
I don't really mind, so whatever you think is most sensible. I only think it shouldn't say "no data" if it exists ;)

**Comment by ValWood** [comment]
> I tried looking at www.pomba.co.uk which is where the shlackow dataset was deposited but it's down

I think this is the case for a while, we should see if it is maintained.....

**Comment by Antonialock** [comment]
Yeah I remember looking at it ages ago (months...can't remember how many) but it's been down at least the last couple.

I added multiple (combined data), no harm leaving them in and Im guessing they are more likely to be useful than not to someone, the filters make it easy anyway
