### ISSUE TITLE
browser track lablels

### ISSUE THREAD

**Issue by ValWood** [pombase/website#724]
I see
![i see](https://user-images.githubusercontent.com/7359272/38488848-9adced5c-3bdc-11e8-8dde-bd50cb642484.jpg)

am I looking in the right place?

https://www.pombase.org/jbrowse/index.html?loc=II%3A485561..499790&tracks=DNA&highlight=

**Comment by ValWood** [comment]
Also, l what is an example of a dataset with forward and reverse strand data?

**Comment by Antonialock** [comment]
Here's an example of a forward and reverse track:
https://www.pombase.org/jbrowse/index.html?loc=II%3A564641..602220&tracks=DNA%2CPomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CTranscripts%20during%20meiosis%200h%20in%20pat1-114%20background%20(forward%20strand)%2CTranscripts%20during%20meiosis%200h%20in%20pat1-114%20background%20(reverse%20strand)&highlight=

**Comment by Antonialock** [comment]
it doesn't look like there is a task here.
