### ISSUE TITLE
display track list alphabetically by track label?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#725]
Or is there a way to specify the display order?

It's odd at the moment that  by default the forward and revere strands are not next to each other 
when you first arrive.

i.e
![soriano](https://user-images.githubusercontent.com/7359272/38509522-046ea368-3c1a-11e8-9da1-1e9e43b61fbe.jpg)
Soriano

but some are?
(or maybe this is because i changed the tack order myself, but I wanted to check...)

**Comment by ValWood** [comment]
I'm not sure that they do, they look pretty random...

![random order](https://user-images.githubusercontent.com/7359272/38512110-3a09b082-3c22-11e8-8e2a-e553d669a269.jpg)

**Comment by kimrutherford** [comment]
It looks like it sorts by the first column by default.  So maybe we should put the label column first?

**Comment by Antonialock** [comment]
I think it makes sense to have the data type first and label second (you need to know what type of data it is!). After datatype it sorts by label.

Val, if you try reload your browser then it should look ok. 

You can also sort on the track label (ignoring the data type) by clicking on the column header for track label

**Comment by ValWood** [comment]
Will try, I agree  data type first and label second. My complaint was that after the first column, the second column was "random", but I will try now...
