### ISSUE TITLE
JBrowse label PomBase tracks

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#727]
Could you label the PomBase tracks?

**DNA track**
data_type: PomBase track
alleles: WT
first_author: Wood
growth_phase_or_response: vegetative growth
pmed_id:11859360
study_ID:not specified

**Reverse and Forward strand features tracks:**
data_type: PomBase track
alleles: WT
first_author: Wood
growth_phase_or_response: multiple (combined data)
pmed_id:22039153
study_ID:not specified

**Comment by kimrutherford** [comment]
This is done now in pombase-dev: http://pombase-dev.bioinformatics.nz/jbrowse/?loc=III%3A713819..740481&tracks=PomBase%20forward%20strand%20features%2CDNA%2CPomBase%20reverse%20strand%20features&highlight=

I assumed that it got be (or had to be) done in the JBrowse config file but it has to go in the big table: pombe-embl/website/pombase_jbrowse_track_metadata.csv

If you need any tweaks you edit that file and check it into SVN.

**Comment by kimrutherford** [comment]
It's now in the main site too.

**Comment by mah11** [comment]
gene page links aren't live yet, but URLs with pombase.org/jbrowse/ work, e.g.  http://www.pombase.org/jbrowse/?loc=III%3A713819..740481&tracks=PomBase%20forward%20strand%20features%2CDNA%2CPomBase%20reverse%20strand%20features&highlight=

**Comment by ValWood** [comment]
ok super...
