### ISSUE TITLE
Intron branch point data

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#728]
This is in ensembl browser so I think we should prioritise getting this back in.

the intron branch point data is here: https://www.ebi.ac.uk/panda/jira/secure/attachment/16497/BranchPointForVal.bed.txt
PB-2080 deals with loading this into ensembl. Mark said "I have had to slightly modify the bed file to be more descriptive, but it now works as a user loaded file. Will modify the config file and place a copy on the FTP" but no more detail

transferred from ticket 
https://github.com/pombase/website/issues/720

**Comment by Antonialock** [comment]
this is in bed format. The Thodberg TSS data also have bed tracks #368

**Comment by kimrutherford** [comment]
I've had a go at adding the intron branch point data track.  It's only in pombase-dev for now.  The JBrowse tracks won't load in Firefox on pombase-dev because Firefox doesn't like that JBrowse is on pombase-dev but we load the track data from www.pombase.org.

You'll need to use Chrome or maybe Safari.

http://pombase-dev.bioinformatics.nz/jbrowse/?loc=III%3A652803..672803&tracks=PomBase%20forward%20strand%20features%2CDNA%2CPomBase%20reverse%20strand%20features%2CBitton%20(2014)%20Intron%20Branch%20Points&highlight=

The BED files need to be sorted and indexed before use: https://github.com/pombase/website/wiki/Formatting-data-files-for-JBrowse

**Comment by Antonialock** [comment]
Cool, I had a quick look. It looks a bit different compared to how I remember it being displayed in ensembl. I'm pretty sure that in ensembl it was just displayed as "vertical lines", like variation data (unfortunately the dataset doesn't appear to load in ensembl at the moment, I emailed them)

this is how it now looks in jbrowse:
<img width="730" alt="screen shot 2018-05-17 at 09 47 47" src="https://user-images.githubusercontent.com/12727506/40167576-4b854e2a-59b9-11e8-8871-866475969c2a.png">


I think it used to be displayed (in ensembl browser) similarly to the variation data (i.e. vertical lines, all one color):

<img width="709" alt="screen shot 2018-05-17 at 10 02 43" src="https://user-images.githubusercontent.com/12727506/40167669-84014eb6-59b9-11e8-97fd-e6afe945d81a.png">


I'm sure Danny will be happy to ask questions if we need to check anything

**Comment by kimrutherford** [comment]
> (i.e. vertical lines, all one color)

No problem.  What colour should we go for?  Something dark?

The labels and arrows can be removed in the configuration.  Shall I go ahead and do that?

**Comment by Antonialock** [comment]
I think dark grey or black is fine?

The "position" numbers don't look very useful, they are not stable IDs. Also the direction should be inherently obvious from the strand I guess? 

I think they can both be removed..

**Comment by kimrutherford** [comment]
OK, thanks.  I've made those changes so we can see how it looks.  I accidentally updated the main site too but I think it's all working.

**Comment by kimrutherford** [comment]
I think this is done now.  Please re-open if I've missed something.

**Comment by Antonialock** [comment]
almost:
still doesn't display in firefox (fine in chrome), same as in #773

**Comment by kimrutherford** [comment]
It looks like none of the tracks display properly in Firefox.  It's very strange as they were working last week and I haven't changed the other tracks.

**Comment by kimrutherford** [comment]
> still doesn't display in firefox (fine in chrome),

I think it's OK now.

**Comment by Antonialock** [comment]
yes!
