### ISSUE TITLE
temporary webstats

### ISSUE THREAD

**Issue by ValWood** [pombase/website#73]
So we have something up there, I wonder if we could just include  2 screenshots (like this once the stats are updated at the end of Sept which is usually a good month)

and then update every 6 months or so until we get new stats?
![pages](https://cloud.githubusercontent.com/assets/7359272/18628409/ffe205a0-7e57-11e6-89d2-f31f5fce1088.jpg)

![hosts](https://cloud.githubusercontent.com/assets/7359272/18628404/f7293eba-7e57-11e6-970a-02e1198a34ec.jpg)

**Comment by mah11** [comment]
ugh, you know I hate manually updating things that should be automated ;)

More seriously, one major and one minor issue:
- Major: The graphs might benefit from slightly longer, more explanatory titles, and will need legends explaining what's counted (and maybe what isn't). I'm happy as usual to edit text, but I don't actually know enough to do an initial draft.
- Minor: the x-axis labels look messy. Can they use numerical dates (e.g. 2012-03) or month abbreviations (e.g. Nov 2014) so the lengths are more similar?

**Comment by ValWood** [comment]
I know that's why I asked tentatively ;)

I think I could make better screenshots, they are directly from the graphs generated in the spreadsheets

https://docs.google.com/spreadsheets/d/1tR8Z7MLcikHdBd2LHpHzobB6slIcDDKcbJxHAitBkSg/edit#gid=784354464

I'm not even sure these are the correct ones to use (I think I should be using K-stats, which are  better graphs). 

It would mean there were some webstats visible in the next 12-24 months when we are unlikely to be able to automate, and that they are equivalent to  other major model access statistics.

I won't so anything for now,  but it might happen later.... if so I will make it so that all that needs to happen is slotting the new images in every 6 months or so....

**Comment by mah11** [comment]
> I'm not even sure these are the correct ones to use (I think I should be using K-stats, which are better graphs). 

I can't help you with that - this is all out of my depth. I'm good for plugging piccies into a web page ...

**Comment by ValWood** [comment]
>I'm good for plugging piccies into a web page ...

That all you would need to do...once you have approved the content

**Comment by ValWood** [comment]
well things are moving faster than expected, so lets not bother with this.
