### ISSUE TITLE
Reorder indexFacets

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#730]
Look into whether the indexFacets in trackListTemplate.json can be ordered by "the order they are listed" instead of "alphabetically".

**Comment by kimrutherford** [comment]
The documentation doesn't mention a way to do that.

**Comment by Antonialock** [comment]
Ok, silly. Can close if too difficult / impossible

**Comment by Antonialock** [comment]
I'll have a look at your browser for the for/rev track ordering...it's  fine in my browser,

**Comment by ValWood** [comment]
ah right!

**Comment by kimrutherford** [comment]
I think this is what we need.  There is an open JBrowse issue about it: https://github.com/GMOD/jbrowse/issues/1203

**Comment by cmdcolin** [comment]
Made a  "categoryOrder" concept for the hierarchicahl track selector in the latest JBrowse 1.15.4 :) Let me know if it helps!

**Comment by kimrutherford** [comment]
Thanks very much Colin!  We'll give it a go.

**Comment by Antonialock** [comment]
We're on 1.15.4 but the indexFacets are still alphabetical?

**Comment by cmdcolin** [comment]
I think I probably misunderstood, the 1.15.4 added an option `categoryOrder` for the hierarchical data selector not the faceted one. I can look into how to do a similar thing for faceted track selector

**Comment by Antonialock** [comment]
Thanks! That would be superneat

**Comment by Antonialock** [comment]
neater than thinking of viable synonyms that places a term lower than other terms at least :-)

**Comment by ValWood** [comment]
@cmdcolin  is there a ticket for this on the JBrowse tracker we can follow?

**Comment by cmdcolin** [comment]
So we are interested in disabling this sort pictured in the screenshot below? You'd want this to be not alphabetical?

![localhost_jbrowse__data=sample_data%2Fjson%2Fmodencode loc=ctgA%3A20002 30002 tracks=DNA highlight=](https://user-images.githubusercontent.com/6511937/69817110-d650b900-11c7-11ea-9cf8-957d245dcc65.png)

**Comment by cmdcolin** [comment]
@ValWood a proposed change to disable sorting is on the dev branch on https://github.com/gmod/jbrowse


It is specified by setting "sortFacets": false (note: false is not quoted) in the "trackMetadata" part of the config e.g.

```
   "trackMetadata" : {
      "sortFacets": false,
      "sources" : [
         {
            "url" : "sample_data/json/modencode/modencodeMetaData.csv",
            "type" : "csv"
         }
      ],
      "indexFacets" : [
         "category",
         "organism",
         "target",
```

**Comment by ValWood** [comment]
Yes, that is exactly what we wanted. 

In our list

<img width="201" alt="Screenshot 2019-11-28 at 20 27 20" src="https://user-images.githubusercontent.com/7359272/69834085-23687580-1230-11ea-8750-e74141ace047.png">


We wanted the "Datatype" to be first as we think that is the most important filter (at least more important the "Allele" which is currently in our top spot.

**Comment by ValWood** [comment]
Will it be clear how to specify the preferred order?

**Comment by kimrutherford** [comment]
> a proposed change to disable sorting is on the dev branch

Thanks.  I'll give the dev branch a go and report back.

**Comment by ValWood** [comment]
@kimrutherford  any news on this?

**Comment by ValWood** [comment]
I removed "next" , bad move, I  added back ;)

**Comment by kimrutherford** [comment]
I haven't gotten around to trying it.  I'll update to the latest JBrowse soon as a first step.

**Comment by kimrutherford** [comment]
> I'll update to the latest JBrowse soon as a first step.

We're now using the latest version of JBrowse (1.16.9).

I've added `"sortFacets": false` to the config as suggested by @cmdcolin and the order now matches what we have in "displayColumns":
```
    "displayColumns" : [
      "data_type",
      "label",
      "alleles",
      "mutant(s)",
      "growth_phase_or_response",
      "assayed_gene_product",
      "background",
      "conditions",
      "assay_type",
      "study_id",
      "sample_id",
      "first_author",
      "pmed_id",
      "publication_year",
      "comment"
    ],
```

It's live on the main site: https://www.pombase.org/jbrowse/

Thanks for your help Colin!

**Comment by cmdcolin** [comment]
Really glad we can help :)

**Comment by Antonialock** [comment]
thanks!

**Comment by kimrutherford** [comment]
Thanks for adding the option so quickly - sorry it took me so long to test the fix.
