### ISSUE TITLE
add Li TSS track(s)? PMID:25747261

### ISSUE THREAD

**Issue by mah11** [pombase/website#735]
We appear to have the data for promoter locations from PMID:25747261 - 
ftp://ftp.pombase.org/external_datasets/HuaLiTSS/

Back in the original summary of #672, Val noted that this track wasn't visible 
But the [promoters FAQ](https://www.pombase.org/faq/can-i-find-promoters-pombase) strongly implies that it was visible in the now-deactivated PomBase-specific ensembl browser. (I don't think it's the only one that didn't migrate.)

Do we want to add it back? The answer will affect how I update the FAQ.

**Comment by ValWood** [comment]
yes we want to add back at some point....

**Comment by mah11** [comment]
swapping open vs. closed because #736 has more information
