### ISSUE TITLE
JBrowse linking

### ISSUE THREAD

**Issue by ValWood** [pombase/website#737]
option 1

![option 1](https://user-images.githubusercontent.com/7359272/38808769-3426fdee-4179-11e8-8736-450871189c6b.jpg)

option 2
if you don't like this, you could just bump the names down a little to create more space
(they have space underneath that would be better above)

![option2-1](https://user-images.githubusercontent.com/7359272/38808829-6a33005e-4179-11e8-891a-fabd89e7d0f9.jpg)

**Comment by ValWood** [comment]
Or Kims suggestion, "Above"

I think above would be better in that case. At present it merges a bit with the gene names...

**Comment by mah11** [comment]
I don't have a strong preference between above and below. Either is better than at the side (option 1), which looks odd.

**Comment by ValWood** [comment]
I think above...
