### ISSUE TITLE
new research spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#738]
PMID:29358048
image: Dropbox Research spotlight feed/Murayama_cohesin_establishment

Research spotlight:  Murayama Y. et. al. 2018
Molecular model of fission yeast centrosome assembly determined by superresolution imaging. Originally published in JCB.

Study shows second ssDNA capture by the SMC complex during establishment of sister chromatid cohesion. Originally published in  <Cell url>

url:
http://www.cell.com/cell/fulltext/S0092-8674(17)31501-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867417315015%3Fshowall%3Dtrue

**Comment by ValWood** [comment]
PMID:29358048
image: Dropbox Research spotlight feed/Murayama_cohesin_establishment

Research spotlight:  Murayama Y. et. al. 2018
Molecular model of fission yeast centrosome assembly determined by superresolution imaging. Originally published in JCB.

Study shows second ssDNA capture by the SMC complex during establishment of sister chromatid cohesion. Originally published in  <Cell url>

url:
http://www.cell.com/cell/fulltext/S0092-8674(17)31501-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867417315015%3Fshowall%3Dtrue

**Comment by kimrutherford** [comment]
> but there is no hurry as it won't be in the community curation feed.

OK, let me know when it's curated.  It's quick to add a new spotlight and it makes sense to add it at the same time.

**Comment by kimrutherford** [comment]
> OK, let me know when it's curated.

Sorry, I misread what you said.  I've added the item.  Does it look OK?:
https://www.pombase.org/archive/spotlight

**Comment by ValWood** [comment]
and 
Molecular model of fission yeast centrosome assembly determined by superresolution imaging.
deleted, thats also from the old one...I forgot to remove!

**Comment by kimrutherford** [comment]
OK, I've changed the text and it will be in the main website in 10 minutes-ish.

**Comment by kimrutherford** [comment]
I thought I'd send a PomBase tweet about it for a change: https://twitter.com/PomBase/status/987266087875039232
