### ISSUE TITLE
JBrowse track fails to load - "Transcripts - all data (forward strand)"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#739]
Same problem on all chromosomes.  It might be a mismatch between the chromosome IDs in JBrowse and the IDs in the data file.

![jbrowse_track_error](https://user-images.githubusercontent.com/90474/38864791-eb7c4a96-428f-11e8-8650-8b1a5e9ceac6.png)

**Comment by Antonialock** [comment]
The Rhind dataset? seem to work for me..

![screen shot 2018-05-04 at 09 45 42](https://user-images.githubusercontent.com/12727506/39619512-05029874-4f80-11e8-9c74-62314d4dc7e2.png)

**Comment by Antonialock** [comment]
(on www, I get an error message on http://pombase2.bioinformatics.nz/ )

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by kimrutherford** [comment]
> The Rhind dataset? seem to work for me..

Thanks for checking.  It works for me too.  I don't understand that.  I'll close this until I see it again.

> I get an error message on http://pombase2.bioinformatics.nz/

That one was temporary.  http://pombase-dev.bioinformatics.nz/ is the dev server.
