### ISSUE TITLE
update column names on PHAF format page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#74]
![does this match what we currently do](https://cloud.githubusercontent.com/assets/7359272/18628452/32c64850-7e58-11e6-9f2f-d031cc0dab2c.jpg)

**Comment by ValWood** [comment]
i.e don't we wnat people to supply the background separately (do we need another column?)

**Comment by mah11** [comment]
Next time I'm editing web pages (it's a good Friday afternoon task type) I'll change the table to use the same text as the PHAF column headers. Everything else is fine - see the column notes below the table. Column 7 _is_ the background.

**Comment by ValWood** [comment]
OK, 

Would a different example be better here:

h+ ura4-D18 leu1-32 ade6-M210

ura4-D18 leu1-32 and ade6-M210 are normally  all selective markers....perhaps  better not to  have what are usually  'background' markers as genotype example?

**Comment by mah11** [comment]
That column is for the background genotype. Remember that this is the single-allele format, and the allele-of-interest data are in columns 3 and 9-11.

**Comment by ValWood** [comment]
OH doh.   got it....

**Comment by mah11** [comment]
column names updated on dev
