### ISSUE TITLE
jbrowse/ analytics

### ISSUE THREAD

**Issue by ValWood** [pombase/website#741]
is it included in?

**Comment by ValWood** [comment]
Also, we need to add under menu (how and to where, i.e where should you land)

https://www.pombase.org/jbrowse/ defaults to a location...what should this be...is there a "generic" landing page

Also we should add a direct link on the front page maybe?

**Comment by kimrutherford** [comment]
It's not going to be recorded at the moment.  With a bit of work we could probably get analytics to tell us when a user goes to JBrowse but not a lot else.

**Comment by ValWood** [comment]
Maybe it would be odd to add JBrowse to the pull down menu since we would need to add a random gene and just  something like:

https://www.pombase.org/jbrowse/?loc=III%3A713817..733817&tracks=PomBase%20forward%20strand%20features%2CDNA%2CPomBase%20reverse%20strand%20features&highlight=

but it seems odd that it is not accessible from the front page and that you have to go to a gene first...I'm not sure what the best option is here.... adding to discuss list (it should be quick)

**Comment by mah11** [comment]
> Maybe it would be odd to add JBrowse to the pull down menu since we would need to add a random gene and just something like ...

That does seem to be what SGD, MGI, and FlyBase do - the latter still use GBrowse, but all 3 have a general genome browser link that goes to a location that looks randomly selected.

**Comment by ValWood** [comment]
OK we will do that too!

**Comment by kimrutherford** [comment]
Which pull down menu should it go in?

**Comment by ValWood** [comment]
We used to have it under "searhc"

I can't remember the text.

it could be
 JBrowse?
 Genome?
Genome (JBrowse)
@mah11

**Comment by kimrutherford** [comment]
> I'd toss a coin between "JBrowse" and "Genome browser".

I've deployed it with "Genome browser" for now.  Easy to change though.

**Comment by Antonialock** [comment]
see https://github.com/GMOD/jbrowse/issues/589

**Comment by kimrutherford** [comment]
> see GMOD/jbrowse#589

Thanks, that was very helpful.

**Comment by kimrutherford** [comment]
I've checked the Analytics page and it looks like this is working.
