### ISSUE TITLE
add a link to help section from 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#742]
Would it be useful to have a direct help link

https://www.pombase.org/documentation/advanced-search
from here
https://www.pombase.org/query

**Comment by ValWood** [comment]
and from specific gene page sections (I think we used to have that?)

**Comment by kimrutherford** [comment]
> Would it be useful to have a direct help link
> https://www.pombase.org/documentation/advanced-search
> from here
> https://www.pombase.org/query

We have a link now but it's not very clear.  Does anyone have any suggestions for making it looks better and more obvious?

> and from specific gene page sections (I think we used to have that?)

I'll work on that.

**Comment by kimrutherford** [comment]
I've added help links on the gene page sections.  The links are at the top right and not obvious.  Any suggestions?

SGD do this which looks OK:

![sgd-help-example](https://user-images.githubusercontent.com/90474/40207101-da0b1620-5a86-11e8-8f54-c2dd4c9af826.png)

**Comment by Antonialock** [comment]
> I've added help links on the gene page sections

where?

**Comment by kimrutherford** [comment]
Sorry, I forgot to commit the change.  The links are there now in the top right corner of the annotation sections.

**Comment by ValWood** [comment]
good to have that back!
I also  like the little "i" icon that SGD use .....

**Comment by kimrutherford** [comment]
> I also like the little "i" icon that SGD use .....

I've moved the help link and turns it into an "i" icon.

**Comment by Antonialock** [comment]
great!
