### ISSUE TITLE
2 small things

### ISSUE THREAD

**Issue by ValWood** [pombase/website#745]
Antonia needs to do a screen shot of the "home page" for the WT workshop, describing features.

- [x] Can we remove the 

"You are using the new PomBase site, released on October 24, 2017. Read more ..."
banner?

- [x]  I think it would be better to keep the advanced search at the top of the menu items (currently displaced  to second by JBrowse)

**Comment by kimrutherford** [comment]
> Can we remove the
> "You are using the new PomBase site, released on October 24, 2017. Read more ..."

I've removed it but left the code in place in case we need a prominent announcement in future.

> I think it would be better to keep the advanced search at the top of the menu items

I've changed things that so JBrowse is second in the list.
