### ISSUE TITLE
telomere status

### ISSUE THREAD

**Issue by mah11** [pombase/website#747]
Transferred from curation tracker, wherein quoth Val:

"we should add the telomeric contig to this page with a note about position and overlap
https://www.pombase.org/status/sequencing-status"

Val to supply content for the note.

**Comment by mah11** [comment]
Q: Does the existing Telomeres page cover what you want?

https://www.pombase.org/status/telomeres

If not, should anything on the telomere page change, or just sequencing status, or both?

The sequencing status and telomere pages are already mutually linked, but the links on the sequencing status page are at the bottom and fairly easy to overlook. Should some or all of them move up?

**Comment by mah11** [comment]
OK. I take it we should keep both pages with their links to each other.

**Comment by ValWood** [comment]
Yes, (I tried to get rid of the Sugaru clones once and people still wanted to find them....)
