### ISSUE TITLE
link to ancestor chart

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#748]
I think it would be nice (maybe in external link section) to have a link to QuickGO that when clicked loads all the BP terms the gene is annotated to into the quickgo "basket", and then opens up the ancestor chart for those terms.

**Comment by ValWood** [comment]
I don't think there is a web service or URL for that?

**Comment by ValWood** [comment]
i.e.
I think Quick basket is done with cookies. ...it always contains what you last put in it....
You can't configure basket contents via a link.....

**Comment by kimrutherford** [comment]
Handy!  You mention BP, does this make sense for the other ontologies?

Perhaps the link should go in the BP section of the page?

**Comment by Antonialock** [comment]
No it wouldn’t be very interesting for MF or BP.

Side track: would it be possible to get an ancestor chart for phenotype terms? It wouldn’t be useful on gene pages in the same way as BPs, but I think it would be useful on FYPO term pages (to see ancestry of a single term). 
(We are supposed to be able to see this using bio portal but their visualisation is rubbish compared to quickgo. 

Ancestor charts to more than one phenotype terms could be useful in order to understand how different terms are related. Not sure it would fit in pombase / canto...

**Comment by kimrutherford** [comment]
I've added a link to the BP ancestor chart in pombase-dev.  If it's OK I'll add it to the main site.

The link is not very prominent (it's at the top right).

The ancestor chart is a bit unusable for cdc2.

**Comment by kimrutherford** [comment]
> I've added a link to the BP ancestor chart in pombase-dev.

... which would be more useful if pombase-dev was working.  Whoops.

I'm fixing it now.

**Comment by kimrutherford** [comment]
> ... which would be more useful if pombase-dev was working.

It's fixed now.

**Comment by Antonialock** [comment]
I'm not sold on where it is located (it looks like it goes together with the slim terms, which it doesn't).

Perhaps have a link underneath the process annotations?
(personally I prefer when external links open in a new window)

Maybe something like this? Not sure what the best wording for the link is:
<img width="500" alt="screen shot 2018-05-17 at 11 30 47" src="https://user-images.githubusercontent.com/12727506/40172263-ccd10bfc-59c5-11e8-9228-501511e42447.png">

**Comment by kimrutherford** [comment]
> Perhaps have a link underneath the process annotations?

I wondered about that but thought that it might be easy to miss if there are a lot of process annotations, like for cdc2.

**Comment by Antonialock** [comment]
i think it is fine... more advanced users would spot it at some point & know where to look. I don't think it is useful to everyone.

also this doesn't look great...I think it would be better underneath

<img width="988" alt="screen shot 2018-05-18 at 00 56 44" src="https://user-images.githubusercontent.com/12727506/40209374-af1fb236-5a36-11e8-9151-238916184c74.png">

**Comment by kimrutherford** [comment]
> more advanced users would spot it at some point & know where to look. I don't think it is useful to everyone.

Good point.  I'll move it below.

> also this doesn't look great...

Ah, I hadn't tried on a narrow screen.  On my screen it looks like this for cdc2:

![ancestor-link-1](https://user-images.githubusercontent.com/90474/40209605-5f32b62a-5a94-11e8-996a-458d7714c0e6.png)

**Comment by kimrutherford** [comment]
I've moved the link underneath and it now opens the link in a new tab.

**Comment by ValWood** [comment]
I'm not convinced that this is super-useful.
It's tricky. In cases  where its viewable (like wee1) it isn't very useful.
For cdc2 it's   not really possible to navigate the graph.

If we keep it, I  think the best place would be  on the same 'line' as show details, but to the right. However then I would worry that it seemed more prominent than "show details" which also bothers me.

Another option is only to have the link once  you have done "show details"  (so it isn't visible by default)

**Comment by kimrutherford** [comment]
> Another option is only to have the link available once you have done "show details"

That makes sense.

**Comment by Antonialock** [comment]
> I'm not convinced that this is super-useful.

I find this really useful in order to check "how" terms are related (if I look at a gene page and I see two terms that are sort of related but don't collpase into each other...just to see what the common parentage is etc)....saves a bit of time compared to going to quickgo, pasting in IDs etc.

Maybe I'd be the only one using it so I don't mind if it is hidden but I would like it to be available :-)

**Comment by ValWood** [comment]
I think it's fine in the full view...it is useful sometimes ;)

**Comment by kimrutherford** [comment]
> Another option is only to have the link available once you have done "show details" 

I've made that change now.

**Comment by kimrutherford** [comment]
>
