### ISSUE TITLE
new common query, all inviable /viable

### ISSUE THREAD

**Issue by ValWood** [pombase/website#753]
https://www.pombase.org/faq/can-i-get-list-essential-pombe-genes

Null alleles annotated to "inviable vegetative cell population" (FYPO:0002061)
Null alleles annotated to "viable vegetative cell population" (FYPO:0002060)

**Comment by kimrutherford** [comment]
> Null alleles annotated to "inviable vegetative cell population" (FYPO:0002061)
> Null alleles annotated to "viable vegetative cell population" (FYPO:0002060)

Are those the names you want display to the users?

**Comment by ValWood** [comment]
I think probably just:
viable deletions
inviable deletions

**Comment by kimrutherford** [comment]
Those are added now.
