### ISSUE TITLE
Acceptable file formats

### ISSUE THREAD

**Issue by ValWood** [pombase/website#754]
https://www.pombase.org/submit-data

need to complete this. Which file formats are OK for JBrowse?

@kimrutherford 
@Antonialock

**Comment by Antonialock** [comment]
bigwig? 

bed and whatever the variation format is?

**Comment by kimrutherford** [comment]
> bed and whatever the variation format is?

Yep, VCF.

**Comment by ValWood** [comment]
duplicate of 
https://github.com/pombase/website/issues/814
