### ISSUE TITLE
new image for community curation feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#755]
To rotate with the word cloud

in the drop box, called "papers curated"

**Comment by kimrutherford** [comment]
I've added that image to the main page.

**Comment by ValWood** [comment]
It was a 'colour pop' to give a bit of definition when embedded in the white page, but you can remove it it looks rubbish!

**Comment by ValWood** [comment]
It would have been better if it was closer to the graph colour, but it was a 'default slide format in google slides...

**Comment by ValWood** [comment]
I made a new one with the green not so garish

![papers_curated](https://user-images.githubusercontent.com/7359272/39661304-3a507f42-5047-11e8-9713-b851b861d334.jpg)

**Comment by ValWood** [comment]
![papers curated](https://user-images.githubusercontent.com/7359272/39661314-56791472-5047-11e8-97d6-a4bf3f561fef.jpg)

**Comment by kimrutherford** [comment]
It looks like this after scaling:

![2018-04-05-community_papers_curated](https://user-images.githubusercontent.com/90474/39661385-e791d09a-50a4-11e8-9bdc-d26313314308.png)

**Comment by ValWood** [comment]
I think it would work OK as a 'teaser' bet maybe we need to make the complete graph available via a link?

https://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
I'll also redo the key  so it's  larger and in the body of the graph....the "key" is key.....

I'll also replace the years by 5 year interval markers...

**Comment by kimrutherford** [comment]
<img width="144" alt="2018-04-05-community_papers_curated" src="https://user-images.githubusercontent.com/90474/39661886-8d316102-50ad-11e8-9a83-a74c3d3627ed.png">

**Comment by kimrutherford** [comment]
> I think it would work OK as a 'teaser' bet maybe we need to make the complete graph available via a link?

Easy enough to do.  Where should the link go?  We could make the image a link.

**Comment by kimrutherford** [comment]
I've updated the image and set modified the config so that the images don't rotate.

It will be visible tomorrow.

**Comment by kimrutherford** [comment]
> It will be visible tomorrow.

The new image is available now.  I think I might have cropped it too much.  Let me know what you think.

**Comment by ValWood** [comment]
Is it possible to only have one image in the rotation, but the archive to still be visible (in this instance, but we might   sometimes want to phase out  older front page images but still keep them in the archive....

**Comment by kimrutherford** [comment]
> phase out older front page images but still keep them in the archive....

We could do but I think having an archive of images would be strange as the context would be missing.  Unless we put a column of images on the left or right of this page?: https://www.pombase.org/reference_list/community

**Comment by ValWood** [comment]
we could label them  there was a batch at the top under "current rotation"

and then  the rest under "archive" ?

I think it would be nice to see the old ones , or those which are not currently rotating. If we have a focus on a particular thing (like community curation), we might want to 'freeze' an image on the front page for a week......
