### ISSUE TITLE
ftp archive

### ISSUE THREAD

**Issue by ValWood** [pombase/website#756]
ftp://ftp.pombase.org/

we have

Archived_directories/ 
archived_files/

I think we should just have

Archive?

I never know which one to look in until I get there?

(then we can ask the EBI README  to link to the  new Archive)

**Comment by ValWood** [comment]
@mah11 @Antonialock  sound OK, or was there a 'special" reason that we did this? I can't think of one?

**Comment by ValWood** [comment]
Oh actually that won't work. There are "archived" as in deprecated, really, really archived, not previous datasets which are in OLD/subdirectories.

I won't ask them to link, but just to mention that the files are archived  at PomBase too.

So in this case should the Contigs  directory move somewhere else?

**Comment by mah11** [comment]
> So in this case should the Contigs directory move somewhere else?

You would know better than I do, but I suggested putting Contigs/ in Archived_directories/ because Contigs/ contains nothing more recent than 2007, and the README says they're deprecated.

**Comment by ValWood** [comment]
OK that clearly belongs in archive!

**Comment by ValWood** [comment]
It sounds like we can go ahead with this (it might be done, I can't access the ftp site right now)

any question @kimrutherford ?

**Comment by ValWood** [comment]
Also, from, https://github.com/pombase/website/issues/692 (closing)

our primary link to the ftp site is
ftp://ftp.pombase.org/pombe/

because we follow the old structure. A lot of stuff is "hidden" one level up
in the parent directory
ftp://ftp.pombase.org/

can we consolidate into one directory?

also I don't think we need "archived files" and "archived directories" (archived files has the old Sanger ftp site only!)

**Comment by kimrutherford** [comment]
> also I don't think we need "archived files" and "archived directories"

Should I go ahead and move everything to one "archive" directory?

**Comment by mah11** [comment]
> Should I go ahead and move everything to one "archive" directory?

That would make sense to me.

**Comment by ValWood** [comment]
Agreed!

**Comment by kimrutherford** [comment]
> Should I go ahead and move everything to one "archive" directory?

OK, done.
