### ISSUE TITLE
simple search - pressing "enter" (only where a gene name is a synonym of another name)

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#758]
Currently when yo type in something in the basic search and then hit enter, you get taken to the page of the top hit. It would probably be better to be taken to a results page listing all the "hits" that are shown in the dropdown menu

(a lot of users were having issues with this in the workshop...they type into the simple search looking at the keyboard and press enter so they dont see the dropdown)

**Comment by ValWood** [comment]
maybe tag this onto the faceted search ticket

**Comment by ValWood** [comment]
OK this is only an issue where a primary name is a synonym of another gene,  and people do not know this.

One eg is lsd1. In canto we disambiguate and we should do this in these instances.

**Comment by ValWood** [comment]
see https://github.com/pombase/website/issues/929
