### ISSUE TITLE
new canned queries

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#759]
Could we also have a canned query for genes with orthologs in human and genes with orthologs in cerevisiae?

**Comment by mah11** [comment]
That would be nice, but it would require a new query type - at present there isn't a query for genes with human or cerevisiae orthologs to can. Relevant FAQs point to the simple search and the downloadable files.

@kimrutherford can say how much work it would be to add the queries.

**Comment by ValWood** [comment]
We can do these queries  now though? I do them all the time...

"conserved in fungi" minus   "no apparent S. cereviaiae ortholog" 
gives conserved in S. cerevisiae)

conserved in vertebrates == conserved in human 
(there are no genes conserved in vertebrates that are not conserved in human...well there is one, but it is  present in mouse and pseudo in human, some amino acid pathway enzyme), but I can live with that...

**Comment by mah11** [comment]
ah, I thought Antonia was asking to query the ortholog annotations directly

**Comment by Antonialock** [comment]
Oh god, ignore me. I _thought_ this was possible but I kept getting the wrong numbers for conserved in human. ...looking back I had selected conserved in metazoa, not vertebrates, d'oh!

**Comment by kimrutherford** [comment]
I've added:

 - Conserved in S. cerevisiae
 - Conserved in human/vertebrates

If the descriptions need changing let me know, or edit them in pombe-embl/website/pombase_v2_config.json
