### ISSUE TITLE
feature book chapter on front page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#760]
Explore PomBase:  Discover PomBase features in our new book chapter
Free to download from  (link)

Can we put it as the only option for a couple of weeks (with a  snapshot of the cover....maybe we need to make a composite image with  the cover and a screenshot from our chapter becase its the wrong aspect ration.

@Antonialock  could you have a go? or put the cover image  in the ftp directory and I will ?

**Comment by ValWood** [comment]
also a short news item, @Antonialock could you draft?

**Comment by ValWood** [comment]
?

Curation philosophy and data organization,  a user guide to getting the most from PomBase.

in "Eukaryotic Genomic Databases" (Methods and Protocols)

download free from 

https://link.springer.com/protocol/10.1007/978-1-4939-7737-6_4

If this is OK, can we put this as the only front page  "explore pombase" feature for a couple of weeks?

**Comment by ValWood** [comment]
news item yes also.

That can be longer. The pombelist post will do I think.

PomBase has a new book chapter in "Eukaryotic Genomic Databases" (Methods and 
Protocols)
https://link.springer.com/book/10.1007/978-1-4939-7737-6
This chapter provides insight into the curation philosophy and data 
organization at PomBase, and provides a guide to using PomBase for 
infrequent visitors and anyone considering exploring *S. pombe* in their 
research.

free to download from https://link.springer.com/protocol/10.1007/978-1-4939-7737-6_4

**Comment by kimrutherford** [comment]
> If this is OK, can we put this as the only front page "explore pombase" feature for a couple of weeks?

Yep, no problem.

What should the title be?  ie. the bit after "Explore PomBase:".  It needs to be quite short.

**Comment by ValWood** [comment]
OK how about

Explore PomBase: In Methods and Protocols

Curation philosophy and data organization, a user guide to getting the most from PomBase.
download free from

https://link.springer.com/protocol/10.1007/978-1-4939-7737-6_4

**Comment by kimrutherford** [comment]
Do we want to keep the news list on the front page to 3 items?  Shall I move the GSA item to the archive?  We currently have:

 - PomBase releases JBrowse 2018-04-16
 - In memory of André Goffeau 2018-04-05
 - Congratulations to GSA award winners 2017-11-24

**Comment by ValWood** [comment]
yes we can bump the oldest.

**Comment by kimrutherford** [comment]
The news item and the Explore item are now live on pombase-dev.  Please let me know if you spot any typos.  You can edit the news item directly here:
  https://github.com/pombase/website/blob/master/frontend/src/docs/news/2018-05-22-book-chapter.md

The text for the explore items is in the website config file in SVN:
  pombe-embl/website/pombase_v2_config.json

I'm happy to do the edits.

**Comment by ValWood** [comment]
Thats fine.

Can we switch from

Curation philosophy and data organization, a user guide to getting the most from PomBase

to

A user guide to getting the most from PomBase, curation philosophy and data organization.

Then it can go live when you are ready.

Val

**Comment by kimrutherford** [comment]
> Then it can go live when you are ready.

I've made that change in pombase-dev.  I want to hold off going live until we've done a bit more checking of #284.

**Comment by kimrutherford** [comment]
> Then it can go live when you are ready.

It's live now.
