### ISSUE TITLE
Add small thumbnail image option for news feed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#761]
I've been meaning to mention for a while that I think it would be nice to have a small thumbnail image accompanying the news items (it will highlight them, and  make it clearer when they change).
I'm thinking about 1 inch squared. I'd be happy to provide them (and we can have a default icon if I can't come up with anything)

**Comment by kimrutherford** [comment]
> I'm thinking about 1 inch squared

I like the idea but that might be too big.

**Comment by ValWood** [comment]
2 cm?

**Comment by ValWood** [comment]
a little bigger than these git hub photo icons?

**Comment by kimrutherford** [comment]
Yep, that could work.  I think we'll need to make the "Recent news" header a little bit more prominent at the same time so it stands out.

**Comment by ValWood** [comment]
Can we do this next.
I have made a folder with little thumbnails for all of the items currently in the news feed.
I have made icons for the pending newsfeed items in the PomBase  Dropbox called 
newsfeed_thumbnails.

preview:
Existing
![existing](https://user-images.githubusercontent.com/7359272/47369158-fa93b980-d6da-11e8-9818-6c1e2bf0cbaa.jpg)

Pending:

![pending](https://user-images.githubusercontent.com/7359272/47369176-08493f00-d6db-11e8-8a79-0518261348ec.jpg)

The browser one isn't great but it doesn't translate well to a thumbnail...

**Comment by ValWood** [comment]
It can be very tiny (as small as 1 cm alongside the title ). It's really just to alert that there is a new/different  post.
It could also look less cluttered if there is some separation between the new items (maybe the same  faint line as separates twitter posts).

Let's see what it looks like. I also think there are other tiny tweaks we could make to improve the  cluttering.

Bear with me....

**Comment by kimrutherford** [comment]
The news archive page looks different - the dates are underneath the titles.  Perhaps that's how the front page should look?

![news-icons-3](https://user-images.githubusercontent.com/90474/47409412-225c4d80-d7bf-11e8-8cd4-38997e9bc2c8.png)

**Comment by kimrutherford** [comment]
Here's a possible new look for the front page:

![news-icons-4](https://user-images.githubusercontent.com/90474/47409732-20df5500-d7c0-11e8-9a3b-79073aec92cc.png)

**Comment by ValWood** [comment]
I like it ;)

I thnk it will look cleaner than the current page to have this visual separation between the news items, which currently looks like a big block of text. 
Can we  see what it looks like on the live site. We might be able to tweak it but the images above look good.

I'm not sure which titles I prefer. We might need to test them both :)

**Comment by kimrutherford** [comment]
The changes are live on pombase-dev.

I've added brief documentation to the wiki: https://github.com/pombase/website/wiki/Documentation-with-Markdown#news-items

**Comment by ValWood** [comment]
I think it improves the display. 
Anyone hate it?

**Comment by ValWood** [comment]
anyway for now let's go live with this and JBrowse. We can always revert or improve.

**Comment by kimrutherford** [comment]
The news item thumbnails are now on the main site.  JBrowse in gene page will be there in 10-ish minutes.

**Comment by ValWood** [comment]
Oh, maybe I was on dev...I'm back in the past...

**Comment by mah11** [comment]
I still prefer news without the images, but I know I am not the target audience.

I do like having the date below the headline.

and re:
> The JBrowse news item did not come through on the news feed yet.

Looks like Kim didn't add the flag to make it appear. I'll commit that now.

**Comment by kimrutherford** [comment]
The news item is on the front page now.

**Comment by ValWood** [comment]
OK you are noted as a thumbs down.
