### ISSUE TITLE
link to kegg maps from term pages?

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#763]
I think these look really nice...and they are interactive 
for example galactose metabolism
http://www.genome.jp/kegg-bin/show_pathway?spo00052

green boxes hightlight where we have identified genes

**Comment by ValWood** [comment]
we used to link to KEGG in the past from GeneDB. I think we did it by EC number, but we don't always have these any more.

It's a bit complicated to link because we need a mapping 9many genes are not represented in KEGG pathways)

**Comment by Antonialock** [comment]
I thought GO terms were mapped to EC numbers?

**Comment by ValWood** [comment]
well they are, but  they don't unambiguously resolve to pathways, and we don't store them locally anymore (at least not associated with the genes). It is do-able  but it will require a little pipeline

**Comment by ValWood** [comment]
Actually we can link by sys ID,

http://www.genome.jp/dbget-bin/www_bget?spo:SPCC1739.07

but I don't know if there is a way to figure which genes have kegg entries

**Comment by kimrutherford** [comment]
> Actually we can link by sys ID,
> http://www.genome.jp/dbget-bin/www_bget?spo:SPCC1739.07

In that case it's easy to add to the External references section of the gene pages.  We just need to decide what goes in each column in the table.

**Comment by ValWood** [comment]
Isn't it a problem that not every gene  will have  a KEGG entry though?

**Comment by kimrutherford** [comment]
> Isn't it a problem that not every gene will have a KEGG entry though?

I forgot about that.

**Comment by ValWood** [comment]
AI:  Try to download a list of pombe genes included in KEGG

**Comment by ValWood** [comment]
If this can't be accessed,  we can link with a "search link" so the 404 error is unsurprising

**Comment by Antonialock** [comment]
I think I have found something useful:

gene-pathway mappings: http://rest.kegg.jp/link/pathway/spo
links to pathway display example: https://www.genome.jp/kegg-bin/show_pathway?spo00010

**Comment by Antonialock** [comment]
that would be nice from gene pages?

**Comment by Antonialock** [comment]
also kegg to go mappings for term pages? http://geneontology.org/external2go/kegg2go

**Comment by ValWood** [comment]
Great stuff, Yes to both.

Can you describe to Kim what is required.

**Comment by Antonialock** [comment]
This should be easy to implement:

1. Gene page link to KEGG pathway that highlights the position of the gene product within the pathway. 

Example pathway+gene: LRP1/cti1 (shown in red) within RNA degradation
https://www.genome.jp/kegg-bin/show_pathway?spo03018+SPCC1739.07

Here is a pathway - pombe gene name mapping file:
http://rest.kegg.jp/link/pathway/spo

Some genes have more than one pathway mapped to them, but I think it's max 3 or 4 in those cases.

2. Term pages to KEGG pathways

Now it gets a bit more complicated....
Some pathways have GO mappings
e.g.
KEGG phagosome maps to GO phagocytic vesicle
https://www.genome.jp/dbget-bin/www_bget?spo04145
similarly, some Biological Process terms have mappings
e.g. glycolysis/gluconeogenesis
https://www.genome.jp/dbget-bin/www_bget?pathway+rn00010
https://www.genome.jp/kegg-bin/show_pathway?rn00010

There is a reaction -> GO molecular function mapping file here:
http://geneontology.org/external2go/kegg2go
Also there is an EC to GO mapping file in case useful: http://geneontology.org/external2go/ec2go

I don't think there is a biological process -> KEGG mapping file - I have asked them, they clearly have the information (maybe there is another way to access this programmatically...)


I am not sure how to access these mappings
http://geneontology.org/external2go/kegg2go

**Comment by Antonialock** [comment]
I would really like being taken to this view:
https://www.genome.jp/kegg-bin/show_pathway?rn00510+R06258

the term you were looking at is highlighted in red

**Comment by ValWood** [comment]
but that would be from the gene page, not the "GO MF" page?

**Comment by Antonialock** [comment]
Yep, it would be good to have a link to the reaction, 

Just thought it would also be nice to see how the reaction fits in a larger picture.

e.g.
EC:1.1.1.28 maps to GO:0008720 maps to KEGG:R00704

R00704 maps to pyruvate metabolism
https://www.genome.jp/dbget-bin/get_linkdb?-t+pathway+rn:R00704

EC:1.1.1.28  in pyruvate metabolism mapped to pombe
https://www.genome.jp/kegg-bin/show_pathway?spo00620+EC:1.1.1.28

**Comment by ValWood** [comment]
I agree but this would be  OK on the gene pages

**Comment by ValWood** [comment]
To do the  GO term page mapping we really need a mapping of KEGG pathways to processes.
Without that file this will stay at low priority (but I agree it must exist).
@Antonialock  Once located open  new simple ticket for the  ontology term page mappings.
I opened one for the gene page mappings.
https://github.com/pombase/website/issues/1239

**Comment by kimrutherford** [comment]
Is this the same as: #1239?

**Comment by ValWood** [comment]
Not quite. But I think if we do  #1239? and you can get to the map from a gene that is part of the pathway, we don't particularly need another access point from the GO term page. This would be more tricky because it would involve a mapping between the GO process  term and KEGG (I only see mappings between activities here http://current.geneontology.org/ontology/external2go/). Anyway I don't think this is completely necessary  if we have  #1239 so closing.
