### ISSUE TITLE
Jeffares hermes transposon insertion data, nucleosome data and HMM model data

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#767]
We have some data from a manuscript that we’d like to have displayed on your beautiful new genome browser.

It is Hermes transposon insertion data, nucleosome data and HMM model data data (one state for each position in the genome, derived from the insertion data). Also conservation measures from a new alignment of new Schizosaccharomyces species genome assemblies.

So four tracks in all. It is displayed here at the moment: http://bahlerweb.cs.ucl.ac.uk/bioda/ <http://bahlerweb.cs.ucl.ac.uk/bioda/> (best viewed with Forefox).

I have bigWig files at the moment, but would be happy for reformat if need be.

**Comment by Antonialock** [comment]
will assign to Kim once track labelling sorted.

**Comment by Antonialock** [comment]
will assign to @kimrutherford Kim once track labelling sorted.

**Comment by Antonialock** [comment]
From Dan:
"Also, Ive realised that I would like to add another track (Hermes HMM-defined elements), which is a standard chr,start,end,name,score type so could be in bed or bigBed format."

Note to self: could call this type sof data transposon mutagenesis


[Track data description upload format - Jeffares 2018(1).xlsx](https://github.com/pombase/website/files/2031386/Track.data.description.upload.format.-.Jeffares.2018.1.xlsx)

**Comment by Antonialock** [comment]
@kimrutherford do you have a preference bigbed or bed? (I'm guessing bed since we have other datasets in that format?)

**Comment by Antonialock** [comment]
Dan didn't you also mention "and nucleosome density (From Maria)"?

**Comment by djeffares** [comment]
Yes I have the nucleosome density  as bigbed. /Dan

**Comment by Antonialock** [comment]
ah I see, cheers. we can give it a shot but might be a bit trickier than the formats we have already tried our hands at - we are on a  learning curve :-)

**Comment by kimrutherford** [comment]
> @kimrutherford do you have a preference bigbed or bed? (I'm guessing bed since we have
> other datasets in that format?)

JBrowse supports BED and bigBed formats so I think either would be fine.

**Comment by Antonialock** [comment]
I can't see this data here yet:
ftp://ftp.pombase.org/external_datasets/

does anything else need doing? 

Would you mind if I have a look at the manuscript Dan?

**Comment by kimrutherford** [comment]
> I can't see this data here yet:
> ftp://ftp.pombase.org/external_datasets/
> does anything else need doing?

Sorry, I've lost track of where we're at.  What are the file names?

**Comment by Antonialock** [comment]
Dan said he had bigwig files he could send and also pointed us to here:
http://bahlerweb.cs.ucl.ac.uk/bioda/
(I never managed to view the data on the Bahler page in any of my browsers)

You said you had a quick look and that it looked straightforward because
" had a quick look and I think this would be easy to add.  We can
handle bigWig files and the files mostly use the chromosome IDs we need
(I, II, III, etc)."

and you said you had a quick look and it looked easy :p

**Comment by djeffares** [comment]
I’m happy to send the bigwig files, or links to them.

Cheers,
Dan



On 15 Jun 2018, at 08:22, Antonia <notifications@github.com> wrote:

Dan said he had bigwig files he could send and also pointed us to here:
http://bahlerweb.cs.ucl.ac.uk/bioda/ <http://bahlerweb.cs.ucl.ac.uk/bioda/>
(I never managed to view the data on the Bahler page in any of my browsers)

You said you had a quick look and that it looked straightforward because
" had a quick look and I think this would be easy to add. We can
handle bigWig files and the files mostly use the chromosome IDs we need
(I, II, III, etc)."

and you said you had a quick look and it looked easy :p

**Comment by Antonialock** [comment]
Either would be great Dan! Would you mind if I have a look at the manuscript?

Just one request: could you make sure that wherever a chromosome is specified, that this is done in the format "I" "II" or "III"? 

So looks like 5 files in total

Hermes transposon   insertions
Hemes HMM state
Hermes HMM-defined elements
Nucleosome positioning in WT
Conservation (phyloP)

Thanks!

**Comment by ValWood** [comment]
> Just one request: could you make sure that wherever a chromosome is specified, that this is done in the format "I" "II" or "III"?

We should make another announcement in a month or so specifying all of the things that providers should do to make this hosting easier. I'll start a list on the website tracker.

**Comment by Antonialock** [comment]
@djeffares  - Kim just reminded me there's more to the genome than just the chromosomes.
chromosome IDs: I, I, III, mating_type_region, mitochondrial and chr_II_telomeric_gap

**Comment by kimrutherford** [comment]
> I’m happy to send the bigwig files, or links to them.

Hi Dan.  Links would be great.  Either bigwig or wig format is OK.

**Comment by Antonialock** [comment]
Did you get this data Kim?

**Comment by djeffares** [comment]
Hello @Antonialock  and @kimrutherford,

I'd like to reopen this ticket, as the paper is now accepted and on early access at MBE:
https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msz113/5488193

I now have 5 tracks to provide:

PhyloP conservation estimates from the four Schizosacharomyes species. 
File: Conservation-SchizPom_phyloP.bigWig 

Nucleosome density data from log phase cells
File: Nucleosome-density-wtNucWave-reps-median.depth_wl_trimmed_PE2.bigWig

Hermes transposon insertion counts from log phase cells
File:  ermes-all-log.counts-incl-VT.2016-10-03.txt.bigWig 

HMM states from log phase insertions, reflecting the importance of each position in the genome
File: all-log-data.hmmstate.model5A.bigWig

HMM-defined elements (HDEs), representing functional units
File: hermes-log.av.mapping.ratio0.9.states.stateblocks.100ntlength.bed 

I have made a tar file available on google drive that contains all these files:
https://drive.google.com/file/d/1bWqy8luMLY71thv-51JSldpUNzUHFnlu/view?usp=sharing

All these bigWig files should function, as they do on the Bioldalliance browser that Danny Bitton set up:
http://bahlerweb.cs.ucl.ac.uk/bioda/

If you navigate to position I:198,640..290,753 this will display (on Firefox, and perhaps Chrome).

best wishes
Dan

**Comment by Antonialock** [comment]
Wonderful news, congratulations!

@kimrutherford do the files need tweaking?

Dan could you also provide track metadata? it is described in here:

[Track data description upload format.xlsx](https://github.com/pombase/website/files/3238469/Track.data.description.upload.format.xlsx)


columns A-Q (some obviously not applicable, I can add the PMID once it has one...)

**Comment by kimrutherford** [comment]
Hi Dan.  Thanks for the files.  I've grabbed a copy.

> @kimrutherford do the files need tweaking?

I need to change some of the chromosome IDs.  I'll do that sometime next week.

**Comment by djeffares** [comment]
Hi @kimrutherford 

Any chance you'd found time to look at this?

I'm asking because the paper is now out, and the tweet is getting some likes, so people may want to browse the data.
https://twitter.com/danieljeffares/status/1141006963112890369

Happy to help reformat files, if need be.

cheers
Dan

**Comment by kimrutherford** [comment]
Hi Dan.

Sorry, I haven't got to that.  I'll have a look on Monday.  I'll let you know if I have any questions.

**Comment by kimrutherford** [comment]
> Any chance you'd found time to look at this?

Hi Dan.

I've had a look at the files.  I needed to tweak the chromosome IDs in some cases (eg. change "MT" to "mitochondrial") to match what JBrowse expects but they are ready to go now.

Did you see Antonia's comment about the metadata?: https://github.com/pombase/website/issues/767#issuecomment-497456515
I think an extra column has been inserted in the examples in the track description spreadsheet Antonia's attached to that comment.  Here's a fixed version:
[Track.data.description.upload.format.xlsx](https://github.com/pombase/website/files/3317718/Track.data.description.upload.format.xlsx)

Cheers!

**Comment by djeffares** [comment]
Hi @kimrutherford 

Is this metadata file OK?

[Jeffares-2019-track.data.description.upload.format xlsx.xlsx](https://github.com/pombase/website/files/3343266/Jeffares-2019-track.data.description.upload.format.xlsx.xlsx)

**Comment by kimrutherford** [comment]
Thanks Dan.  That looks good.  I'll try to get the tracks into the browser today.

This label might be a bit too long:
  Conservation level estimated using phyloP method, from Cactus alignment of S. pombe, S. japonicus, S. octosporus and S. cryophilus genomes (Grech 2019)

Can we shorten it?

**Comment by djeffares** [comment]
Thanks Kim,

How about:

Conservation, estimated using phyloP from alignment of four Schizosaccharomyces genomes (Grech 2019)


Best wishes,
Dan


On 30 Jun 2019, at 19:38, Kim Rutherford <notifications@github.com> wrote:

Thanks Dan. That looks good. I'll try to get the tracks into the browser today.

This label might be a bit too long:
Conservation level estimated using phyloP method, from Cactus alignment of S. pombe, S. japonicus, S. octosporus and S. cryophilus genomes (Grech 2019)

Can we shorten it?

**Comment by kimrutherford** [comment]
> How about:
> Conservation, estimated using phyloP from alignment of four Schizosaccharomyces genomes (Grech 2019) 

That's great.

I've had to change the commas to semicolons because JBrowse doesn't support commas in track labels.  I'd forgotten that.  I'm happy to change any labels if they look too naff with the semicolons.

The new tracks are visible now:  <a href="https://www.pombase.org/jbrowse/?loc=III%3A809683..905132&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CConservation%3B%20estimated%20using%20phyloP%20from%20alignment%20of%20four%20Schizosaccharomyces%20genomes%20(Grech%202019)%2CHMM-derived%20elements%20(HDEs)%3B%20genome%20windows%20with%20runs%20of%20one%20HMM%20state%20(Grech%202019)%2CHMM%20state%20generated%20from%20transposon%20insertion%20data%20(Grech%202019)%2CHermes%20transposon%20insertion%20sites%20from%20multiple%20insertion%20libraries%20(Grech%202019)%2CNucleosome%20density%20from%20exponentially%20growing%20wild-type%20(972%20h%E2%88%92)%20cells%20in%20EMM2%20(Atkinson%202018)&highlight=">new tracks</a>

Just to check, the "Nucleosome density from exponentially growing wild-type" row has a different PubMed ID from the other 4.  Was that on purpose?

**Comment by ValWood** [comment]
Conservation estimated from (the) alignment of four Schizosaccharomyces genomes using phyloP 

and doesn't require a comma or colon

**Comment by ValWood** [comment]
We can announce this (i'm not sure if Antonia is announcing browser hosting in batches though)

We could also add a "research spotlight" to the front page if you have a suitable image Dan,

**Comment by djeffares** [comment]
Fine with me, thanks


Best wishes,
Dan


On 1 Jul 2019, at 05:54, Val Wood <notifications@github.com> wrote:

Conservation estimated from (the) alignment of four Schizosaccharomyces genomes using phyloP

and doesn't require a comma or colon

**Comment by djeffares** [comment]
Hi Val,

That would be great, thanks Val. what about an image from the browser? My memory is that cdc2 looks nice.

I’ll send some other possibilities tonight.

Best wishes,
Dan


On 1 Jul 2019, at 05:55, Val Wood <notifications@github.com> wrote:

We can announce this (i'm not sure if Antonia is announcing browser hosting in batches though)

We could also add a "research spotlight" to the front page if you have a suitable image Dan,

**Comment by ValWood** [comment]
That sounds as though it would work. Just bear in mind the aspect ratio and the resolution:
https://www.pombase.org/archive/spotlight

**Comment by kimrutherford** [comment]
Here's what it looks like in the region around cdc2, at Spotlight image resolution:

![grech-spotlight-image-1](https://user-images.githubusercontent.com/90474/60488864-226dff00-9cf7-11e9-822e-5d0dcf3c378b.png)

**Comment by ValWood** [comment]
I think that looks good but wait for Dan.

**Comment by djeffares** [comment]
Hi Kim and Val,

This image looks great to me. Clearly fewer transposon insertions in the gene (and even fewer in the antisense ncRNA), different HMM state sin the UTRs, and higher conservation (phyloP) in the coding axons.

I’d be happy to us Ethiopian as a research spotlight. Thanks!

Best wishes,
Dan


On 2 Jul 2019, at 03:29, Kim Rutherford <notifications@github.com> wrote:

Here's what it looks like in the region around cdc2, at Spotlight image resolution:

**Comment by ValWood** [comment]
Is 

Research spotlight: Grech et al., 2019
The fitness Landscape of the fission yeast genome.
Published in Mol Biol Evol. 
PMID: 31077324

OK?

Ethiopian? @djeffares

**Comment by kimrutherford** [comment]
> Research spotlight: Grech et al., 2019

I've added that to the configuration.  It's won't be visible until tomorrow morning so there's still time to tweak things.

I haven't included the usual "Publication record in PomBase ..." link because there isn't a publication page for PMID:31077324.  Is that expected?

There's room for a longer text if you like.  Now I've added the config I realise that a link to JBrowse makes sense.  I'll add that.

It will look like this when it appears on the website (plus a JBrowse link once I add that):

![grech-spotlight-image-2](https://user-images.githubusercontent.com/90474/60577929-6be04c00-9dd4-11e9-91ff-d0f000e12fb7.png)

**Comment by kimrutherford** [comment]
> Now I've added the config I realise that a link to JBrowse makes sense. I'll add that.

That's done.  Let me know if you'd like any wording changes.

![grech-spotlight-image-3](https://user-images.githubusercontent.com/90474/60578695-c5954600-9dd5-11e9-85a3-f70b8e1aa971.png)

**Comment by djeffares** [comment]
Looks great, thanks Kim and Val.

**Comment by djeffares** [comment]
Looking at the browser now, I see that the HMM track description is unhelpful. 

Could this be altered to the text below? 

HMM fitness model (more important regions have lower scores). 

Thanks again for displaying and highlighting this. 

PS: 'Ethiopian' was a autocorrect typo, amongst many in that message. 🤔

**Comment by kimrutherford** [comment]
No problem.  There are two descriptions that mention HMM.  Which is the one to change?:

 - HMM state generated from transposon insertion data (Grech 2019)
 - HMM-derived elements (HDEs); genome windows with runs of one HMM state (Grech 2019)

**Comment by ValWood** [comment]
If you are linkint to the browser instead this is fine. However, if there is not "small scale  data" in the session we can approve it so that it shows as curated.

Although how come there isn't already a publication page? Isn't the publication loaded  into Pombase yet?

**Comment by Antonialock** [comment]
Excellent!

I have a few questions/comments on the track descriptions.

There are 4 tracks:

1. _Hermes transposon insertion sites from multiple insertion libraries_
In this track each line represent an insertion site (and height reflects how many times it was observed in the cells in the libraries)
2. _HMM state generated from transposon insertion data_
Here the transposon insertion sites are smoothened to states S1-S5. The height of the scale bar corresponds to the state (0=S1, 2=S2, 3=S3...)
3. _Conservation estimated from alignment of four Schizosaccharomyces genomes using phyloP_ 
This track shows the conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus
I'm really not sure how to interpret the track itself? Could you explain?
4. _HMM-derived elements (HDEs); genome windows with runs of one HMM state_
This track shows continuous runs of states S1-S3


this is what they look like in the browser:
<img width="1063" alt="Screenshot 2019-07-03 at 17 45 02" src="https://user-images.githubusercontent.com/12727506/60609745-4e9e8400-9dba-11e9-8120-9365125e8539.png">


Secondly, I'm not keen on having 3 new "data types" (transposon insertions, HMM state blocks, transposon HMM state) - can we fit these in under "transposon insertions" and tweak the track descriptions?

New track descriptions:
Track 1:  Transposon insertion sites (Grech 2019)
Track 2: Transposon insertion sites smoothened to states S1-S5 (Grech 2019)
Track 3: (needs elaborating so that it is obvious what it is showing) Conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus (Grech 2019)
track 4: HDE units, continuous runs of states S1-S3 (Grech 2019)

I suggest specification of "assay type" (not great terminology for modelling.. perhaps "method" would be better?) as follows: 

Track 1: Hermes
Track 2: HMM
Track 3: PhyloP
Track 4: HMM

I also suggest to move the "sample ID" into "study ID" column ? (it looks like a study ID not a sample ID?)

Is it really applicable to both tracks 1 and 4 - should it only be added to track 1? 

cheers!
@djeffares

**Comment by Antonialock** [comment]
also @kimrutherford can we show the labels for the "HMM-derived elements (HDEs); genome windows with runs of one HMM state" track by default?

**Comment by ValWood** [comment]
> Secondly, I'm not keen on having 3 new "data types" (transposon insertions, HMM state blocks, transposon HMM state) - can we fit these in under "transposon insertions" and tweak the track descriptions?

I agree- we need the "types" to be  broader groupings, and to limit the number.
This specificity should be in the description.

**Comment by kimrutherford** [comment]
> also @kimrutherford can we show the labels for the "HMM-derived elements (HDEs); genome
> windows with runs of one HMM state" track by default?

The labels are on but they only show when you zoom in:

![grech-tracks-1](https://user-images.githubusercontent.com/90474/60625589-5bfc5280-9e3c-11e9-939d-a63ddaeced59.png)

**Comment by Antonialock** [comment]
Ah.. I did see those but because of the coordinates I didn’t see (what I thought was the) interesting bit - whether the feature is S1, S2, S3 - didn't see the forest for the trees - the coordinates are available when you click on a feature (see screenshot below), perhaps it is better to keep the label simple?

<img width="741" alt="Screenshot 2019-07-03 at 22 26 45" src="https://user-images.githubusercontent.com/12727506/60626200-ecf21000-9de1-11e9-9ee6-a98ab47f0b1b.png">

**Comment by Antonialock** [comment]
also @kimrutherford does it not have a pub page because of this flag

Browser datasets, to host
?
...maybe we only do pub pages for 'curatable' pubs?

**Comment by Antonialock** [comment]
ah yes I think that is it...for example the Soriano dataset also does not have a pub page
https://curation.pombase.org/pombe/view/object/pub/PMID:24256300?model=track

**Comment by kimrutherford** [comment]
> It will look like this when it appears on the website (plus a JBrowse link once I add that):

It's on the main site now and is one of the Spotlights that will be shown on the front page:
  https://www.pombase.org/archive/spotlight

**Comment by kimrutherford** [comment]
> ..maybe we only do pub pages for 'curatable' pubs?

That could be it.  I'll investigate.

**Comment by kimrutherford** [comment]
> ..maybe we only do pub pages for 'curatable' pubs?

You were right.  I've modified things so that the "Browser datasets, to host" sessions are exported too.  The publication page for PMID:31077324 should on the main site on Friday - tonight's load has already finished.

**Comment by ValWood** [comment]
I think there was a plan (ticket) to have pub pages, but to link the pub pages to the browser tracks?

**Comment by ValWood** [comment]
We still need to  to assess the browser hosted datasets briefly  for additional  curation.
Most probably don't have any....

**Comment by Antonialock** [comment]
> We still need to to assess the browser hosted datasets briefly for additional curation.
> Most probably don't have any....

They do :-) see
https://www.pombase.org/reference/PMID:29914874

**Comment by Antonialock** [comment]
> I think there was a plan (ticket) to have pub pages, but to link the pub pages to the browser tracks?

Yeah so currently you can load the tracks from a clickable link on a pub page, see:
https://www.pombase.org/reference/PMID:29914874

There is a problem in that in case there is a lot of tracks then not all tracks will load (URL gets too long so there's cut off based on length of URL)

We have a ticket to implement "tickable loading":
https://github.com/pombase/website/issues/801

**Comment by ValWood** [comment]
I know "many" do, but I doubt it is "most"

Once hosted browser sets should move to this list:
https://curation.pombase.org/pombe/view/list/triage_browser_datasets_hosted?model=track
to be assessed for other curation 
then can be curatable and->curated

@kimrutherford  can
triage_browser_datasets_hosted
 show up as publication pages (eventually with a link to the browser track).
@Antonialock there should be more than 5 papers in here?

**Comment by Antonialock** [comment]
we're going off topic of Dans data. I will open new tickets and delete the comments that are irrelevant to Dans data

**Comment by djeffares** [comment]
Hi Kim,

Please adjust the first one:

HMM state generated from transposon insertion data (Grech 2019)


Best wishes,
Dan


On 3 Jul 2019, at 07:43, Kim Rutherford <notifications@github.com> wrote:

No problem. There are two descriptions that mention HMM. Which is the one to change?:

HMM state generated from transposon insertion data (Grech 2019)
HMM-derived elements (HDEs); genome windows with runs of one HMM state (Grech 2019)

**Comment by kimrutherford** [comment]
> Could this be altered to the text below?
> HMM fitness model (more important regions have lower scores).

Hi Dan.

I've made that change.  It will on pombase.org on Saturday morning.

Antonia has a different suggestion for that track and some of the others:
  https://github.com/pombase/website/issues/767#issuecomment-508185063

Let us know what you think.

**Comment by Antonialock** [comment]
Hi @djeffares Did you see my questions above?

**Comment by djeffares** [comment]
> Excellent!
> 
> I have a few questions/comments on the track descriptions.
> 
> To clarify what "they are about":
> 
> There are 4 tracks:
> 
> 1. _Hermes transposon insertion sites from multiple insertion libraries_
>    In this track each line represent an insertion site (and height reflects how many times it was observed in the cells in the libraries)
> 2. _HMM state generated from transposon insertion data_
>    Here the transposon insertion sites are smoothened to states S1-S5. The height of the scale bar corresponds to the state (0=S1, 2=S2, 3=S3...)
> 3. _Conservation estimated from alignment of four Schizosaccharomyces genomes using phyloP_
>    This track shows the conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus
>    I'm really not sure how to interpret the track itself? Could you explain?
> 4. _HMM-derived elements (HDEs); genome windows with runs of one HMM state_
>    This track shows continuous runs of states S1-S3
> 
> this is what they look like in the browser:
> <img alt="Screenshot 2019-07-03 at 17 45 02" width="1063" src="https://user-images.githubusercontent.com/12727506/60609745-4e9e8400-9dba-11e9-8120-9365125e8539.png">
> 
> Secondly, I'm not keen on having 3 new "data types" (transposon insertions, HMM state blocks, transposon HMM state) - can we fit these in under "transposon insertions" and tweak the track descriptions?
> 
> New track descriptions:
> Track 1: Transposon insertion sites (Grech 2019)
> Track 2: Transposon insertion sites smoothened to states S1-S5 (Grech 2019)
> Track 3: (needs elaborating so that it is obvious what it is showing) Conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus (Grech 2019)
> track 4: HDE units, continuous runs of states S1-S3 (Grech 2019)
> 
> I suggest specification of "assay type" (not great terminology for modelling.. perhaps "method" would be better?) as follows:
> 
> Track 1: Hermes
> Track 2: HMM
> Track 3: PhyloP
> Track 4: HMM
> 
> I also suggest to move the "sample ID" into "study ID" column ? (it looks like a study ID not a sample ID?)
> 
> Is it really applicable to both tracks 1 and 4 - should it only be added to track 1?
> 
> cheers!
> @djeffares

HI @Antonialock,

Sorry, I missed these questions. Answers below:

 
> To clarify what "they are about":

> 
> 1. _Hermes transposon insertion sites from multiple insertion libraries_
>    In this track each line represent an insertion site (and height reflects how many times it was observed in the cells in the libraries)
DJ: Yes, correct.

> 2. _HMM state generated from transposon insertion data_
>    Here the transposon insertion sites are smoothened to states S1-S5. The height of the scale bar corresponds to the state (0=S1, 2=S2, 3=S3...)
DJ: Yes, correct. But why is is that 0=S1? Surely S1 (state1) should have height=1 ?

> 3. _Conservation estimated from alignment of four Schizosaccharomyces genomes using phyloP_
>    This track shows the conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus
>    I'm really not sure how to interpret the track itself? Could you explain?
DJ: No, this track is not generated from the Hermes transposon insertions.
It is the conservation of each site over the phylogeny os the four Schizosaccharomyces species (S. pombe S. octosporus, S. japonicus, and S. cryophilus). Higher values mean more conservation (the scale is a negative logged P-value). The values were generated from an genome alignment, using the phyloP algorithm.


> 4. _HMM-derived elements (HDEs); genome windows with runs of one HMM state_
>    This track shows continuous runs of states S1-S3
DJ: Yes.

> Secondly, I'm not keen on having 3 new "data types" (transposon insertions, HMM state blocks, transposon HMM state) - can we fit these in under "transposon insertions" and tweak the track descriptions?
DJ: Yes, this is fine.

 
> New track descriptions:
> Track 1: Transposon insertion sites (Grech 2019)
> Track 2: Transposon insertion sites smoothened to states S1-S5 (Grech 2019)
> Track 3: (needs elaborating so that it is obvious what it is showing) Conservation of S. pombe fitness consequence states S1-S5 in S. octosporus, S. japonicus, and S. cryophilus (Grech 2019)
> track 4: HDE units, continuous runs of states S1-S3 (Grech 2019)
DJ: Yes, but I think "smoothed" is simpler & in more common use.


> I suggest specification of "assay type" (not great terminology for modelling.. perhaps "method" would be better?) as follows:
> 
> Track 1: Hermes
> Track 2: HMM
> Track 3: PhyloP
> Track 4: HMM

DJ: What about Transposon rather than Hermes, which is more generic.

 
> I also suggest to move the "sample ID" into "study ID" column ? (it looks like a study ID not a sample ID?)
Yes, fine.

> Is it really applicable to both tracks 1 and 4 - should it only be added to track 1?
DJ: Yes, fine.

cheers
Dan

**Comment by Antonialock** [comment]
Thanks! I updated the descriptions
Transposon insertion sites - Grech et al. (2019)	
HDE units, continuous runs of states S1-S3 - Grech et al. (2019)
Transposon insertion sites smoothed to states S1-S5 (lower states have fewer insertions) - Grech et al. (2019)	
Conservation of sites over the phylogeny of S. pombe, S. octosporus, S. japonicus, and S. cryophilus (higher values are associated with higher degree of conservation)- Grech et al. (2019)	

I thought it was smoothened not smoothed - I blame the Drosophila researchers! :-) 

"Hermes" is perfect in the assay desciption - in this field we want the exact method. In comparison "data type" is a grouping term for different datasets with similar data types (e.g. transcripts, chromatin binding sites...).

Let me know if you want anything tweaked, otherwise I'll announce tomorrow

**Comment by ValWood** [comment]
The fitness landscape data is hosted and announced so I am clodsing this ticket..
