### ISSUE TITLE
Make genes pages look more like publication pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#769]
I think the publication pages look better than the gene pages.  I like that they are left-aligned.

The gene name and the details are centred on the gene page.  I think we should consider left-aligning the gene page too.

I also think that the top of the SGD gene pages looks better than our gene pages:

![sgd-gene-page-1](https://user-images.githubusercontent.com/90474/40350357-afa08134-5dfd-11e8-8970-0dd06e1a4dee.png)

I think the gene name looks a bit small and lost on our gene pages:

![pombase-gene-page-1](https://user-images.githubusercontent.com/90474/40350459-faf82362-5dfd-11e8-9e2b-0fbc571a7f32.png)

**Comment by kimrutherford** [comment]
I think the publication pages look good.  The title size is a better match for the page:

![pombase-pub-page-1](https://user-images.githubusercontent.com/90474/40350590-59aa7770-5dfe-11e8-95e9-1ab7fadbacd2.png)

**Comment by ValWood** [comment]
I agree. The only bit of our website I'm not keen on is the top of the gene pages.
I think we should go with left aligned. This will hoever make the section somewhat longer (although there is always line wrapping, so it will only be 2 lines longer.
Closing the gap between the name and the other top matter will help a bit.

Go for it!

**Comment by kimrutherford** [comment]
I'll change it locally at some point and attach a screenshot for us to discuss.

**Comment by kimrutherford** [comment]
I've been playing with the look of the gene pages.  Below is a sample.

![new-gene-page-look](https://user-images.githubusercontent.com/90474/40467021-40e8befc-5f7c-11e8-86aa-5a5d6413b51c.png)

**Comment by ValWood** [comment]
well thats better already!

**Comment by Antonialock** [comment]
Yes though I think the size of the text in the quicklinks could be increased slightly...it's relatively hard to read

**Comment by kimrutherford** [comment]
> Yes though I think the size of the text in the quicklinks could be increased slightly

I'll increase it a bit.  I don't want to make it too big to avoid the menu going off the bottom of the screen.

**Comment by kimrutherford** [comment]
> well thats better already!

I'll do a bit more tuning before releasing the changes.  (Also my changes have made the publication pages worse - need to fix that)

**Comment by kimrutherford** [comment]
I'm about to deploy my changes.  I'd like to improve the annotation tables too, but that will have to be later.

As well as the gene pages, I've tweaked the term pages to put the term name first as it's more meaningful to most users.  Easy to undo if you don't like that change.

Term page before:

![term-before-1](https://user-images.githubusercontent.com/90474/40591348-aba5ce62-6263-11e8-995a-57e8234ea7ef.png)

Term page after:

![term-after-1](https://user-images.githubusercontent.com/90474/40591351-bb46de42-6263-11e8-9a1e-98833d8c40d8.png)

**Comment by ValWood** [comment]
I prefer it your way.
