### ISSUE TITLE
tab on dev (GO annotations)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#77]
![tab](https://cloud.githubusercontent.com/assets/7359272/18703183/b9788324-7fdc-11e6-8b59-65d23acad065.jpg)

**Comment by mah11** [comment]
Should be fixed with #75 (not something I can control)

**Comment by ValWood** [comment]
OK so I need to ask Uma to remove it?

**Comment by ValWood** [comment]
Or add it correctly?

**Comment by mah11** [comment]
I think you have to tell her that "GO Annotations" should be an item in the "Submit" tab menu, and not a separate tab. If you have a preference where it appears in the list, also tell her that (I don't mind).

**Comment by mah11** [comment]
they've fixed it at last
