### ISSUE TITLE
Add a link to tutorial

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#771]
Midori could you please add a link on the mating type region page https://www.pombase.org/status/mating-type-region

to this tutorial:  

"For a detailed description of the mating type region please see this online tutorial by the Nielsen lab:
http://www1.bio.ku.dk/english/research/fg/cellecyklus_genomintegritet/mating/ "

cheers

**Comment by ValWood** [comment]
Also for @Antonialock 
write  a bit more explanatory text for the  docs about what we provide and why it is like ti is (similar to your ticket response)

Do we need to  a more prominent menu link to genome regions. The   pages for cen, tel, MT are quite hidden...

**Comment by mah11** [comment]
If you want a menu link, open a new ticket for it so it doesn't get lost when the rest is done.

**Comment by ValWood** [comment]
Antonia needs to write a bit of text  from the same help-desk ticket. Assigned ver to @Antonialock

**Comment by ValWood** [comment]
This might be covered?

**Comment by Antonialock** [comment]
tweaked
