### ISSUE TITLE
JBrowse track meta-issue

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#772]
This is a tracking issue for all missing or new JBrowse data.  I've added what I think are the corresponding issue so I know which is which. 

~- Gagneur/Eser #50~
~- variation data (then everything 'old and visible in ensembl' is hosted) - #729~ hosted
- Update DNA binding motif file #802 
~- Li TSS promoter locations #736 #735~
~- Dutrow ncRNA #63~
~- Lanterman ncRNA #62~
- promoter collection #1185
- Gerry data #1198
~- Juan ribosome profiling #1245~

**Comment by Antonialock** [comment]
_Tracks announced 2018-05-27_
_- Promoter elements (bed file) #774_
_- Yadav SIDD data (bed file) #773 - now live but needs feature labels_
_- Thodberg data - #368_
_- intron data - #728_

**Comment by ValWood** [comment]
#768
 #736
 #735
 #368
 #63
 #62
 #49
 #50

**Comment by Antonialock** [comment]
whats that list of tickets Val? It would be good if you could add any new ones to the top master comment. Things get buried in comments.

**Comment by ValWood** [comment]
tracks to be announced. 
I would announce any that are already live now (there may not be any?)

**Comment by Antonialock** [comment]
upur list is a bit of a grabbag of tickets:

736/735 not yet live
768 we only received fastq files, we need bigwig
368 already announced (see above ticket for the ones already announced)
50 may not be worth pursuing at this stage (ticket also closed)
63 62 low priority I think
49 already in the top list

**Comment by ValWood** [comment]
OK, I have no idea what it was supposed to be  then ;)

**Comment by ValWood** [comment]
double check which of these datasets were announced because for some that are listed as announce I put them in my new ticket for hosting (I did not know about this one)

https://github.com/pombase/website/issues/1441

**Comment by ValWood** [comment]
replaced by
https://github.com/pombase/website/issues/1441
