### ISSUE TITLE
JBrowse SIDD G(x) data from Yadav and Dubey

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#773]
Submitted in 2014, but files weren't completely in the right format and the RT ticket stalled.

I have wangled the files into what I think is a .bed compliant format, see attached - I don't know where this data lives! Will put track descriptions into the metadata file.

The file has 4 fields
chromosome, start, end, score

I think in bed format the score will just display as text...in bedgraph it might show as a bar? I can't workout how to load it into the genome browser to play with it...any ideas?

[PMID23163955.txt](https://github.com/pombase/website/files/2033112/PMID23163955.txt)

**Comment by Antonialock** [comment]
also need to describe the track, to do...I am tired.

**Comment by kimrutherford** [comment]
The raw data is here on oliver1: /data/pombase/external_datasets/originals/

I've made a new directory and copied the file to:
  /data/pombase/external_datasets/originals/Yadav_and_Dubey_SIDD_PMID23163955/

**Comment by mukeshpyadav** [comment]
Hi All
Thankyou so much for initiating again this, I remember, long back, I had given the .bed file to Valerie Wood (November 4, 2015). Please let me know If you need any help while curating data.
With best Regards.
Mukesh

**Comment by Antonialock** [comment]
I thought they went here but I cant see 'originals'
ftp://ftp.pombase.org/external_datasets/

**Comment by Antonialock** [comment]
@mukeshpyadav thanksfor being so understanding!

**Comment by Antonialock** [comment]
track has been described in the metadata file

**Comment by kimrutherford** [comment]
> track has been described in the metadata file

Great, thanks.  I'll have a go at loading it into JBrowse tomorrow.

**Comment by kimrutherford** [comment]
> ok, I'm not sure if I have access to oliver1?

Ah, sorry, it looks like you don't.  We should sort that out.

**Comment by kimrutherford** [comment]
I> thought they went here but I cant see 'originals'
> ftp://ftp.pombase.org/external_datasets/

The "originals" directory is on oliver1.  There's also a "processed" directory and that's the one that gets copied to the FTP when there's new data.

The files in the "processed" directory contain any changes we've had to make like fixing chromosome IDs.

**Comment by Antonialock** [comment]
ok, let me know if I did something wrong (I did make it in excel so maybe the file has weird hidden stuff in it). Also it looked like bedGraph would be a nicer format for it. According to ucsc documentation 
(https://genome.ucsc.edu/goldenpath/help/bedgraph.html)
the first line of the file just needs to say 
track type=bedGraph
in order to do this, but I don't know if it is this simple in reality, and since I couldn't load the actual data in plain bed format I didn't want to complicate things

I've never had to prep data files before for genome browsers so it's excellent for personal learning - please let me know whatever I do 'wrong'!

**Comment by kimrutherford** [comment]
The new track is on the main site now.  Let me know if you spot any problems:
  https://www.pombase.org/jbrowse/?loc=I%3A2499301..2691300&tracks=DNA%2CPosition%20specific%20G(x)%20scores%20(free%20energy%20needed%20to%20separate%20a%20base%20pair%20-%20scores%20near%2010%20kcal%2Fmol%20are%20stable)%2CDNA%20sequence&highlight=

**Comment by Antonialock** [comment]
2 things:

1. the data doesn't display in firefox
2. can we display the scores next to the bars ?

**Comment by kimrutherford** [comment]
> the data doesn't display in firefox

I think I've fixed that.  Could you give it a go?  You might need to shift-reload.

> can we display the scores next to the bars ?

I'll give that a go.

**Comment by Antonialock** [comment]
yes loads now in firefox :-)

**Comment by ValWood** [comment]
closing, open   if anyting else to do.
