### ISSUE TITLE
promoter elements bed file

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#774]
moved from #693
 
updated bed file located here:
https://www.pombase.org/pombase_datasets/genome_sequence_and_features/feature_coordinates/TF_binding_motifs.bed

I have entered the meta data in the meta data file (data type | description):
genome sequence and features | Promoters matched computationally to S. pombe consensus promoter sequences

I removed the underscores as requested on the original JIRA ticket.

**Comment by kimrutherford** [comment]
> I have entered the meta data in the meta data file (data type | description)

Which metadata file?

**Comment by Antonialock** [comment]
pombase_jbrowse_track_metadata.csv

**Comment by kimrutherford** [comment]
Ah thanks.  I forgot to do svn update so I couldn't see the TF motifs entry.

I'll process the BED file and give it a go.

**Comment by kimrutherford** [comment]
The TF binding motif tracks is live now.

**Comment by ValWood** [comment]
@Antonialock  could you send a pombelist announcement next week to announce the new tracks ?
