### ISSUE TITLE
update docs after txn overhaul

### ISSUE THREAD

**Issue by ValWood** [pombase/website#775]
https://www.pombase.org/faq/how-can-i-find-transcription-factors-and-their-targets-pombase

**Comment by ValWood** [comment]
This might be a useful "commonly used query" but we can add it after I have finished the transcription updates. The FAQ terms will change.

**Comment by mah11** [comment]
That FAQ has links to the pombase pages for GO:000976 and GO:0003700. What others should be added?

**Comment by ValWood** [comment]
Don't worry about this. We might need to change the terms used after the migration (it should become easier). Minimally term names will change. Once I finish the transcription overhaul (probably not before I go off now), I will revise the FAQ for you.

**Comment by ValWood** [comment]
from 
https://github.com/pombase/website/issues/897

FAQ will need to be updated

https://www.pombase.org/faq/how-can-i-find-transcription-factors-and-their-targets-pombase
when GO transcription factor activity work done (see https://github.com/geneontology/go-ontology/projects/7)
Also

How can I find transcription factor binding sites in PomBase?
A data track showing transcription factor binding sites was available in the previous version of the PomBase genome browser. We will soon make this track available in JBrowse.
Also see the FAQ on finding transcription factors.
(can update about the tracks availability already)

**Comment by ValWood** [comment]
I can do this now....

**Comment by ValWood** [comment]
All sequence-specific DNA-binding transcription factors are annotated to 
DNA-binding transcription factor activity (GO:0003700) (to describe the transcription factor activity)
and
transcription regulatory region sequence-specific DNA binding (GO:0000976))
(to describe the DNA binding activity)

Annotation extensions are used to capture two types of “target” data (where available):
Annotations to GO:0003700 (or a descendant) may have extensions identifying target genes.
Annotations to GO:0000976 (or a descendant) may have extensions that capture DNA binding specificity using Sequence Ontology (SO) terms.
A list of DNA binding sites identified in S. pombe is available on the DNA Binding Sites page.


(things may change further in future but this is current)

**Comment by ValWood** [comment]
@mah11 This FAQ can be done, I think.

**Comment by mah11** [comment]
This ticket has not specified any changes from the existing FAQ content.

**Comment by ValWood** [comment]
Actually reading hte FAq, I think  nothing has changed that will affect it so closing.
