### ISSUE TITLE
Hide DNA track label

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#776]
The DNA track label is redundant with the DNA sequence track label (they point to the same data)

e.g.
<img width="597" alt="screen shot 2018-05-25 at 07 52 13" src="https://user-images.githubusercontent.com/12727506/40530457-d2dc8752-5ff0-11e8-9fdb-1201f459d675.png">

<img width="785" alt="screen shot 2018-05-25 at 07 52 42" src="https://user-images.githubusercontent.com/12727506/40530459-d31cd69a-5ff0-11e8-9085-10d558407db9.png">

**Comment by kimrutherford** [comment]
I've removed the anonymous DNA track so now we just have the Wood 2002 DNA track.
