### ISSUE TITLE
Load tracks by default

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#778]
Should we load DNA sequence, forward features and reverse features by default?

**Comment by ValWood** [comment]
I think so!

**Comment by kimrutherford** [comment]
The front page links now show the DNA and features by default.

The down side is that if you go to JBrowse with those links, it forgets what tracks you had already loaded.

**Comment by ValWood** [comment]
> The down side is that if you go to JBrowse with those links, it forgets what tracks you had already loaded.

hmm, that's a bit annoying, if you have a set of 'favourite tracks, and you need to turn the on each time....

**Comment by kimrutherford** [comment]
I had another look and there is a configuration option to set some default tracks:
  http://www.gmod.org/wiki/JBrowse_FAQ#How_to_get_default_tracks_to_display_every_time_a_user_opens_the_browser.3F

I'll try that.

**Comment by ValWood** [comment]
Wonderful....

**Comment by kimrutherford** [comment]
> I'll try that.

It didn't work.  It looks like there is a bug in that JBrowse functionality that has been fixed in more recent versions.  I've been meaning to upgrade anyway.

**Comment by kimrutherford** [comment]
> It didn't work. It looks like there is a bug in that JBrowse functionality that has been fixed in more
> recent versions. I've been meaning to upgrade anyway.

I've upgraded.  It loads faster, which is nice.

The update seems to have fixed the problem with setting default tracks.  The front page "Genome browser" links now show the default tracks.
