### ISSUE TITLE
Tracks don't always load properly but are then fine on reloading

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#779]
Sometimes, data doesn't display at all.

It might display when viewing a part of the chromosome, but then disappears after scrolling to the side.

e.g.
<img width="1083" alt="screen shot 2018-05-27 at 07 26 32" src="https://user-images.githubusercontent.com/12727506/40583111-84c1902c-617f-11e8-9c0b-aa6d09a6b68a.png">

Here the promoter track shows no data (it was showing stuff before I scrolled to this part of the genome). After shift-reloading the promoter track again displayed the promoters.

Also noticed this dataset not loading yesterday, it was also ok after reloading the page:

<img width="1052" alt="screen shot 2018-05-26 at 21 43 50" src="https://user-images.githubusercontent.com/12727506/40583131-c889110e-617f-11e8-853a-89d22b1dc2dc.png">

**Comment by Antonialock** [comment]
Haha, the promoter track wasn't showing anything when I was looking at it, but I guess the data was there since it is in the screenshot!

**Comment by kimrutherford** [comment]
Some of the rows have quite big data files and track a few seconds to load.

The error message is a worry.  If it happens again could you copy your current URL from your browser?

**Comment by Antonialock** [comment]
> Some of the rows have quite big data files and track a few seconds to load.

yes this must have something to do with it. First when I started scrolling it took a while for the data to load, but then after a few scrolls it was like the browser gave up trying (I waited for probably a minute and nothing appeared), maybe nothing you can do about it & it is not a showstopper since the data did load when reloading the page

> The error message is a worry. If it happens again could you copy your current URL from your browser?

yep. Don't worry too much :-) I have looked at the browser quite a bit and this was the first and only time I've seen that error. I was loading "one of each" of many different datatypes though so maybe I just confused the system a bit.

**Comment by kimrutherford** [comment]
I'm going to close this since it seems to have settled down.  Please re-open if you see more track loading problems.
