### ISSUE TITLE
FAQ item needs updating

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#780]
E.g.

<img width="798" alt="screen shot 2018-05-27 at 07 22 20" src="https://user-images.githubusercontent.com/12727506/40583080-d3f142a6-617e-11e8-9457-cb3ee9117617.png">

we now have a track based on https://www.pombase.org/browse-curation/dna-binding-sites

This link will launch the browser with the track loaded:
https://www.pombase.org/jbrowse/?loc=I%3A2518981..2531220&tracks=DNA%20sequence%2CPomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CConsensus%20promoters%20(computationally%20matched)&highlight=

**Comment by ValWood** [comment]
Ah it's here.

How did you find this page?
https://www.pombase.org/browse-curation/dna-binding-sites
