### ISSUE TITLE
update track description  for consensus promoters

### ISSUE THREAD

**Issue by ValWood** [pombase/website#781]
genome sequence and features -> promoters

Consensus promoters (computationally matched) -> consensus transcription factor DNA binding motifs

Alleles  WT -> N/A

(so this won't be a Genome sequence and feature track, it will be a separate data type, because it isn't part of the core annotation)

Also, where is that page with the  consensus promoter sequence?
I think it should be listed
here under "other pombase pages"
Other PomBase Pages

and I  also couldn't find a link to it from the FAQ? (I looked through everything "transcription/factor" and "promoter"
I also couldn't find it by Googling....

**Comment by ValWood** [comment]
Also for this track   it  isn't

**Comment by ValWood** [comment]
also  mating type and ploidy  for consensus promoters h- -> not applicable

**Comment by ValWood** [comment]
I guess it was easier to find when we had a browse tab.
I think we need somewhere more prominent for these lists (like the drug targets).
But not sure where!

 I guess for the FAQ:
"What are the known  transcription factor DNA-binding motifs ?"

**Comment by Antonialock** [comment]
done

this page is referenced in the track metadata
https://www.pombase.org/browse-curation/dna-binding-sites
