### ISSUE TITLE
JBrowse front page link?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#782]
Should we add "JBrowse" to the more prominent links on the front page?

About ● Advanced search ● GO process overview

About ● Advanced search ● GO process overview ● JBrowse
?

**Comment by kimrutherford** [comment]
> About ● Advanced search ● GO process overview ● JBrowse

We'll need to tweaks the widths and font sizes to make sure it doesn't wrap:

![jbrowse-front-page-link-1](https://user-images.githubusercontent.com/90474/40584222-6e9a4aba-61f1-11e8-85ff-057080ca4a58.png)

**Comment by ValWood** [comment]
I think we can ditch "About". It isn't so interesting and it is already a prominent menu item in its own right...?

**Comment by kimrutherford** [comment]
> I think we can ditch "About".

Yep, I think so.

**Comment by kimrutherford** [comment]
> Advanced search ● GO process overview ● JBrowse

In the Search menu the item is labelled "Genome browser".  Should we do that here too?

**Comment by kimrutherford** [comment]
I've removed "About" and added "JBrowse".  Should I change it to "Genome browser"?

**Comment by ValWood** [comment]
Change to "Genome Browser"
