### ISSUE TITLE
add gene specific links to HCOP

### ISSUE THREAD

**Issue by ValWood** [pombase/website#789]
Now includes Pombase manual orthologs!
And pombe as an organism!

https://www.genenames.org/cgi-bin/hcop

**Comment by ValWood** [comment]
Orthologs | HCOP | SPCC18B5.03 | Ortholog predictions, Integrated methods multispecies

**Comment by ValWood** [comment]
where do  we add these again...I need to  make a not of this!

I'd like to get the xrefs in so  before I announce on pombelist.

**Comment by kimrutherford** [comment]
Here are the docs:
  https://github.com/pombase/website/wiki/Configuration#adding-a-new-external-reference

Happy to help.

**Comment by ValWood** [comment]
OK done. Could you update website?

**Comment by ValWood** [comment]
hmmph, those links don't work at all. I thought  you could search with a pombe ID, you can't. I'm deleting them....

**Comment by ValWood** [comment]
done, can you let me know when you next update the website?

I won't send the announcment until the links have disappeared as they will be confusing...

**Comment by Antonialock** [comment]
I can only get searching by entrez ID to work (not systematic IDs...I was going to try an ensembl ID, I thought they started with ENS...but I can't find a pombe example. e.g. https://fungi.ensembl.org/Schizosaccharomyces_pombe/Gene/Summary?g=SPCC1183.03c;r=III:595451-597344;t=SPCC1183.03c.1;db=core )

They must have a way to link to this, I had a look around but couldn't find anything...email them?

**Comment by Antonialock** [comment]
Didn't look like it. I'll email them and ask, want to point out that sys ID search doesn't work anyway

**Comment by ValWood** [comment]
I already did. If any ID should work it's the systematic ID as that is what we provided.

**Comment by mah11** [comment]
The systematic ID is also what's in their downloadable human-pombe ortholog file (yes, I just checked). They're in a column headed s.pombe_ensembl_gene (why??).

One issue seems to be that if you start with a non-human species, it only finds human orthologs. So we should probably call it a human ortholog finder, not multispecies. But it's also definitely broken for pombe, because starting with other species does retrieve human genes (I tried S. cerevisiae, Drosophila, and mouse).

**Comment by mah11** [comment]
p.s. it's just possible that when they fix the bug/problem/oversight/whatever that is making S. pombe searches fail from the web interface, this URL syntax will work:

https://www.genenames.org/cgi-bin/hcop?species_a=284812&species_b=9606&column=ensembl&ortholog=all&Search=Search&query=<<IDENTIFIER>>

e.g.
https://www.genenames.org/cgi-bin/hcop?species_a=284812&species_b=9606&column=ensembl&ortholog=all&Search=Search&query=SPBC14C8.07c

the equivalent works for cerevisiae, e.g.
https://www.genenames.org/cgi-bin/hcop?species_a=4932&species_b=9606&column=ensembl&ortholog=all&Search=Search&query=YJL194W

**Comment by ValWood** [comment]
The  bug is fixed, I re-added the  correct link. Will be present in next update if I didn't mess the file up!

**Comment by kimrutherford** [comment]
> done, can you let me know when you next update the website?

I've just updated.

**Comment by Antonialock** [comment]
I also prodded them before I saw that you had emailed them too :-) 

From Beth: "I’ve just added an option to the HCOP webpage that allows you to specify a PomBase ID as the query type when searching using S.pombe as the primary species. You should already have been able to search with PomBase IDs using the ‘Ensembl GeneID’s’ field as these two IDs are largely interchangeable, however there was a bug in the code that was stopping this working for IDs of the format used by PomBase, I’ve fixed this now so you should be able to use either PomBase ID or Ensembl Gene ID as your input type. 

In terms of linking to HCOP you should be able to use either of these methods where there query term gets switched out for whatever PomBase ID you are linking from.

https://www.genenames.org/cgi-bin/hcop?species_a=284812&species_b=9606&ortholog=all&column=pombase&Search=Search&query=SPCC1183.03c
https://www.genenames.org/cgi-bin/hcop?species_a=284812&species_b=9606&ortholog=all&column=ensembl&Search=Search&query=SPCC1183.03c

"

**Comment by Antonialock** [comment]
I think the update happened before the commit :-)

**Comment by ValWood** [comment]
I don't understand. Don't you see the update?

**Comment by Antonialock** [comment]
no? I tried a hard refresh and a gene I haven't been to for years

**Comment by ValWood** [comment]
I only updated the config. Kim needs to update the website for it to appear?

**Comment by kimrutherford** [comment]
> I think the update happened before the commit :-)

I've just updated again.

**Comment by kimrutherford** [comment]
Can this be closed?  There are now HCOP links in the external refs section now but I don't know if they are correct.

**Comment by ValWood** [comment]
Yep, all good at our end
