### ISSUE TITLE
Add arrows to BED features except for Yadav et al (2012) dataset

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#792]
Might need a new column in the metadata file - "show_feature_arrows".

**Comment by Antonialock** [comment]
cheers that worked
(show feature label in table)

**Comment by kimrutherford** [comment]
I haven't changed the code yet ?

**Comment by Antonialock** [comment]
d'oh, I was looking at the labels

**Comment by Antonialock** [comment]
If it is easier we could just display them? For introns I don't think it adds value but it is not wrong either?

**Comment by ValWood** [comment]
I think it's useful for introns too.....
So I would say display them all?

**Comment by kimrutherford** [comment]
I changed the code and there are now arrows showing except for the Yadav dataset.  It turns out that in the Yadav Bed file the features don't have strands so JBrowse doesn't add an arrow.  No extra configuration needs.
