### ISSUE TITLE
community curation feed.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#794]
I approved  a session of Jackys 2 days ago and it didn't appear in the coommunity curation feed on the front page. I'm sure I approved others too. Is the CC feed updating?

**Comment by ValWood** [comment]
Actually, there are quite a lot in the feed...
https://www.pombase.org/reference_list/community
 but the front page rotation appears to be "stuck"
(maybe when we froze the image? can this be 'decoupled'

**Comment by ValWood** [comment]
Actually, I don't think it's that. those on the front page seem to be 'random'?

**Comment by kimrutherford** [comment]
Drat.  It does seem random.  I'll fix it.

**Comment by kimrutherford** [comment]
Fixed!  The server code was completely messing up the job of ordering the publication by approval date.
