### ISSUE TITLE
what needs to happen here/ file renames

### ISSUE THREAD

**Issue by ValWood** [pombase/website#796]
ftp://ftp.pombase.org/pombe/names_and_identifiers/

 - [ ]  do we need to archive  allNames.tsv ? why does it have a newer timestamp than the new files

- [x]  I still think it si confusing that these are links that look like empty files

- [ ]  Do we need to announce? (I need to respond to Maria) when everything is synched on the ftp

**Comment by ValWood** [comment]
When you are ready....if its a quick job  aim to do in the next week or two and I can tell MAria...

**Comment by ValWood** [comment]
note that people are using these files
https://github.com/geneontology/helpdesk/issues/112#issuecomment-400804786

will we have forwarding links between any old and new file names?

**Comment by kimrutherford** [comment]
> will we have forwarding links between any old and new file names?

Yep, we can make those links.

**Comment by ValWood** [comment]
ACTION: add forwarding for the old names

**Comment by ValWood** [comment]
Hi Kim,

Can you look at this next? I don't think there is much to do here. I just want to let UniPROt know about the  final file location. It's hanging around in my inbox......

(maybe I can do that already...)
Val

**Comment by ValWood** [comment]
https://www.pombase.org/downloads/names-and-identifiers

@mah11  do we also need website updates here?

I got a bit lost with this renaming. I'll try to find the 'history' ticket and link it here.

**Comment by ValWood** [comment]
I can't find the ticket, but we now have 2 files
gene_IDs_names.tsv
and
gene_IDs_names_products-.tsv 
here
ftp://ftp.pombase.org/pombe/names_and_identifiers/

this isn't what the website says, But I can point Maria here.

allNames.tsv is deprecated but will be a forwarding link, correct?

**Comment by kimrutherford** [comment]
`gene_IDs_names.tsv` and `gene_IDs_names_products.tsv` are now real files checked into SVN and should update nightly from now on.

`allNames.tsv` is still link.  I'd prefer to keep it that way if we can because it's identical to `gene_IDs_names.tsv`.

**Comment by ValWood** [comment]
I told MAria. Which things are outstanding  here?
I think that is it?
