### ISSUE TITLE
new research spotlight

### ISSUE THREAD

**Issue by ValWood** [pombase/website#797]
file in drop box “kinesin-14’
Research spotlight:
Model illustrating collaborative inward force generation by kinesin-14s
publication record in pombase PMID:29167352
Published in journal of cell science
http://jcs.biologists.org/content/131/1/jcs210740.long

Approved today.
A perfect curation session....

**Comment by kimrutherford** [comment]
I've added the spotlight image and configuration so it should be visible along with the curation in the morning.

**Comment by kimrutherford** [comment]
We should let the authors know once it's on the front page.  :-)

**Comment by ValWood** [comment]
yes I always do. Usually I ask if it's OK first  as well ......but I just put Takishi's up, he can change the image if he  wants.....

**Comment by Antonialock** [comment]
looks like it could be cropped a bit on the width

**Comment by kimrutherford** [comment]
> looks like it could be cropped a bit on the width

It's the same width as the other spotlight images for consistency.  But maybe the authors have a wider image we can use.

**Comment by ValWood** [comment]
Yeah I couldn't make it any larger (I already omitted the key which was as big as  one of the images because I could not include it with the aspect ration.

I think it's still eye catching  and  spindle people will know what it means (it's how the  duplicated spindle pole body moves apart  as the spindle elongates, using  microtubule motors exerting forces in different directions)

**Comment by ValWood** [comment]
Yep it's the best for the  aspect ration I could do with the image without losing top or bottom.
I will ask tomorrow if they want to change it...

**Comment by ValWood** [comment]
It's only a 'teaser' though, it's to flag up the paper,  and point people towards it, not to use to interpret the data.

**Comment by kimrutherford** [comment]
The new spotlight item is live: https://www.pombase.org/archive/spotlight

**Comment by ValWood** [comment]
hanks, i mailed takashi.
