### ISSUE TITLE
GO slim documentation, link, list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#8]
related to
https://github.com/pombase/website/issues/7

I think it might be useful to have the raw list of pombe slim IDs on a page somewhere ( or do we already? I couldn't find it linked).
Its useful for cutting and pasting into tools like matrix, or as a starting point  if you want to make a user defined slim

**Comment by mah11** [comment]
It would be a bad idea to do this as a manually maintained static page, because it would go out of sync with the slim when it's updated.

**Comment by ValWood** [comment]
There have been changes recently, but if we provide this list *after* the next update I envisage it will be static for a long time. I think it is getting near to the point when  further changes will be very rare.

 I need to maintain a local  static list myself at present, so I am happy to update the list and open a ticket when it need updating until we have a better solution. I think it would be more effort right now to put programmer time on automating the page than it will take  to cut an paste the  list once a year.

Will  do this  after the next update when the new slim is in place.

Longer term, especially when we have F/C slims (which are likely to be in flux for a while) , we can automate....

**Comment by ValWood** [comment]
I think Go alos plan to make the raw lists avaible so can just link to that

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/pombase-chado/issues/685
