### ISSUE TITLE
 front page images

### ISSUE THREAD

**Issue by ValWood** [pombase/website#800]
I think we could make the fron page 3 images images a little bit wider  (say 0.75 cm, possibly 1 cm) , and  then correspondingly deeper, if we did 2 things

1. Decrease the space between the images a fraction. See my pocket feed compared below

![make bigger](https://user-images.githubusercontent.com/7359272/41373052-17a5e5a8-6f47-11e8-809b-9d95875c275e.jpg)

and

2. Let the edges of the images align with the text rather than indented.

If this doesn't work very well I think we could nick a bit from the margin space to make the images bigger.

Larger images would not only look better, but the boxes would also not need to be quite so deep because the text would   have more width too...

Clearly this isn't urgent but I think it's worth a little play around at some point. I still like the front page a lot....

**Comment by kimrutherford** [comment]
>  the edges of the images align with the text rather than indented.

I don't understand that bit.

If we scale the images they're all going to look a bit blurry.  They are currently 300x185 pixels and are saved at that resolution.  Should we start making images that are bigger?

**Comment by ValWood** [comment]
Ah Ok in that case not to worry. otherwise we would need to regenerate all the images.
