### ISSUE TITLE
Update TF binding site motif track to include new  TF binding motifs

### ISSUE THREAD

**Issue by ValWood** [pombase/website#802]
from#2006

Need to use Mark's code:
Git repo (pombase-loader). The script that you are interested in is {pombase-loader}/scripts/GenerateBindingMotifTrack.sh
The bash script downloads and prepares the files then runs the script misc_scripts/GenerateBindingSitTracks.py which generates the bed file.

This can be done once we have all of the new binding sites added.

@kimrutherford please let @Antonialock know how you need them presented to be referenced from the script

**Comment by ValWood** [comment]
do
https://github.com/pombase/website/issues/35
at the same time

**Comment by kimrutherford** [comment]
I've made a repo with the pombase-loader code:
 https://github.com/pombase/legacy-eg-loader

The script of interest is here:
  https://github.com/pombase/legacy-eg-loader/blob/master/scripts/GenerateBindingMotifTrack.sh

**Comment by ValWood** [comment]
SO:0002215 Zas1_recognition_motif has been added as a child of DNA_motif.
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/436#issuecomment-398793720

**Comment by ValWood** [comment]
Do we need to discuss this?
If so please add label.

val

**Comment by kimrutherford** [comment]
> Do we need to discuss this?

Could you explain what the new SO term is for?

**Comment by ValWood** [comment]
I put that part in the wrong ticket.

Antonia needs to add to the motif page:
https://github.com/pombase/curation/issues/2038
 you don't need to worry about that part.

so once the motif  above, is added here:

https://github.com/pombase/website/blob/master/frontend/src/docs/browse-curation/dna-binding-sites.md

I guess the script can be run for TF binding sites.

**Comment by ValWood** [comment]
People might be interested in this:
![dna binding sites](https://user-images.githubusercontent.com/7359272/41833353-e2468ef8-7847-11e8-9a46-c5aba5bd2186.jpg)

**Comment by ValWood** [comment]
wait for this motif to be added
https://github.com/pombase/curation/issues/1543

**Comment by Antonialock** [comment]
I don't think there is anything to add from that ticket

**Comment by ValWood** [comment]
I think users will be quite interested in this, and should be quick?

**Comment by kimrutherford** [comment]
> so once the motif above, is added here:

Which motif above?

> I think users will be quite interested in this, and should be quick?

Shouldn't be too bad thanks to having Mark's code.

**Comment by ValWood** [comment]
I thought there was still a motif to add to the  config (loz1)
but it it there.
https://www.pombase.org/browse-curation/dna-binding-sites

So the script needs to be run using these motifs to create tracks

**Comment by ValWood** [comment]
Maybe it was an old comment, because the file linked to is no longer there:
https://github.com/pombase/website/blob/master/frontend/src/docs/browse-curation/dna-binding-sites.md

**Comment by Antonialock** [comment]
it is here https://github.com/pombase/website/blob/master/src/docs/browse-curation/dna-binding-sites.md

**Comment by ValWood** [comment]
The motifs all need to be described using standard syntax  for parsing 

~So I think inverted forms can be done like this:
ACCCTACCCT/AGGGTAGGGT

**Comment by ValWood** [comment]
- [ ] Also remove [5'-
- [ ] Is the symbol for OR a "/" (sometimes a | is used)

**Comment by ValWood** [comment]
I think this is dependent on 
https://github.com/pombase/website/issues/1419

**Comment by ValWood** [comment]
We should display the motif name too. 
e.g. 
in the pop up some  motifs  have CAAT /GATAA (for example , although these are not in our list? https://www.pombase.org/browse-curation/dna-binding-sites), although some (most)  do not have the motif listed (it seems)
but  the  label for the motif should be added 

so 

WGATAA display label would be  "iron repressed GATA element"
ACAAT display label would be mating type M-box

if this would be too busy it needs to be somewhere so perhaps  it needs to be in the pop-up,

**Comment by ValWood** [comment]
I now see that it is the box header, but this text is smaller than the rest  on a grey background so it "disappears"
It might be worth repeating in the "primary data section"  or some other tweak (I  dislike redundancy|)

**Comment by ValWood** [comment]
also dependent on https://github.com/pombase/website/issues/903

**Comment by ValWood** [comment]
also a duplicate of https://github.com/pombase/website/issues/1654
