### ISSUE TITLE
what's the plan for this?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#810]
did we say we wanted to move all ncRNAs with no fuctional data to their own track and not have them in the main annotation (contig files)?

I think we discussed it but I can't remember...

. | Long non-coding RNA repertoire and targeting by nuclear exosome, cytoplasmic exonuclease and RNAi in fission yeast.

  | Atkinson  S, Marguerat S, Bitton D, Bachand F, Rodriguez-Lopez M, Rallis C, Lemay  JF, Cotobal C, Malecki M, Smialowski P, Mata J, Korber P, Bahler J.
  | RNA. 2018 Jun 18. pii: rna.065524.118. doi: 10.1261/rna.065524.118. [Epub ahead of print]
  | PMID: 29914874

**Comment by Antonialock** [comment]
https://github.com/pombase/curation/issues/2007
