### ISSUE TITLE
config file update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#811]
we want  prompt for has_input  to specify  the TF for

GO:0003713 transcription coactivator activity
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-binding transcription factor to activate the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications. The Mediator complex, which bridges transcription factors and RNA polymerase, is also a transcription coactivator

**Comment by mah11** [comment]
added the is_a parent, with relation has_regulation_target and text "regulates activity of transcription factor"
