### ISSUE TITLE
new research spotlight rotation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#813]
The community curation session isn't through yet but this is supplied:

[Fig 4g-Model.pdf](https://github.com/pombase/website/files/2125177/Fig.4g-Model.pdf)
for
https://www.ncbi.nlm.nih.gov/pubmed/?term=PMID%3A+29899453

I'm adding to the drop box in a dir called

parua_cdk9

I'll add text here after the curation session received/approved

**Comment by ValWood** [comment]
research spotlight 
Parua et al 2018
A Cdk9-PP1 switch for  RNA polymerase II elongation-termination.

Originally published in <<Nature   https://www.nature.com/articles/s41586-018-0214-z  >>


Can go live tonight

**Comment by kimrutherford** [comment]
The new item is live.
