### ISSUE TITLE
making submissions compliant,  (for pombelist, and docs)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#814]
We need to
i) update the docs preparing how to describe a sequence based   dataset for submission
ii)  post to pombelist "submitting high throughput datasets to pombelist for fast hosting" or similar

Please add to list anything to be covered:

Browser sequence data hosting
* use these chromosome IDs: I, I, III, mating_type_region, mitochondrial and chr_II_telomeric_gap
* file formats:
   * BED
   * bigBed
   * WIG/bigWig
   * BAM
   * VCF
* any specific info for display tweaking?
* any other issues arising so far?

update:
https://www.pombase.org/submit-data

Phenotypes
Make it easier to  find evidence codes (link to a term browser)

Other points
If you make your supp data compliant we can host more quickly
We can prepare datasets for hosting to coincide with publication

**Comment by kimrutherford** [comment]
I've added the other chromosome IDs and the file formats.

**Comment by ValWood** [comment]
Most of this is probably out of date, but once we have  documentation and the metadata spreadsheet an announcement to pombelist would be useful.

**Comment by mah11** [comment]
if it's out of date I'll just close it.
