### ISSUE TITLE
JBrowse link not loading datasets

### ISSUE THREAD

**Issue by ValWood** [pombase/website#816]
When I click on Malte's data for the front page rotation, the tracks don't load for me (I'm sure they did before? or maybe I didn't test?)

**Comment by kimrutherford** [comment]
Just tried and was OK for me. Are all the tracks failing to load or just Malte's data?

Which browser are you using?

**Comment by ValWood** [comment]
It is when I go from the link in the rotating spotlight

https://www.pombase.org/



![link](https://user-images.githubusercontent.com/7359272/41832743-3ae1f4e2-7845-11e8-8b95-cfdb32662d5d.jpg)

view in JBowse link.

I  can access them but I need to explicity turn them on. I expected the link provided here to pre-load them?

**Comment by kimrutherford** [comment]
It's fixed now.  The track names had changed slightly so the link need to be updated.
