### ISSUE TITLE
are these FAQs still current?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#823]
Can I access PomBase via an API?
Yes, the Ensembl API can be used with PomBase, as documented here:
	1.	Ensembl Genomes Perl API installation and basic use instructions (with links to additional Ensembl API documentation)
	2.	Tutorial for using the API with the core database - Includes examples about connecting to the database, retrieving chromosomes, genes, transcript and translations along with the corresponding xrefs.

Can I access PomBase via SQL?
PomBase does not have a publicly accessible SQL query server, but Chado database dumps (PostgresQL) are available to download and query locally.
The Ensembl Genomes (EG) MySQL database server does provide access to query S. pombe data. Note, however, that EG is updated much less frequently than PomBase, so EG data will rarely be as up-to-date as the PomBase web site.
MySQL dumps of EG data, including Schizosaccharomyces species, are available from EG's FTP site.

**Comment by mah11** [comment]
I've edited the first of these a bit. For the second, the content is still basically accurate - if it's not a Question that's actually Asked Frequently, we don't absolutely have to keep it, but if we do, the answer is correct.

**Comment by ValWood** [comment]
well probably best to rephrase the question

Can I access PomBase via an API?

because they aren't accessing "PomBase " anymore. Maybe

Can I access "PomBase  data" via an API?
(and with caveats added that the data will not be current data in PomBase but  that the  last Ensembl Fungi release notes should be checked?)

Ensembl don't update all organisms or GO data each release for example....and as far as I know they don't report which version of GO they are using. I fell into this trap using cerevisiae data from Ensembl fungi for the pichi paper. It turned out that neither the sequence features or the GO data had been updated for around 4 years....

With the old PomBase Ensemlb implementation at least we knew that the data was current....

The data needs a health warning.....
