### ISSUE TITLE
front page feature, and  look into  using GrapHi-C as a 3D structure browser

### ISSUE THREAD

**Issue by ValWood** [pombase/website#830]
https://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-018-3507-2

Research Spotlight:
Graph-based visualization of Hi-C datasets
link to paper, i'm triaging as a 'method'  no curation
If we  are able to use as a browser we would link to that.

Image in drop box folder "GrapHi-C"

**Comment by kimrutherford** [comment]
That's added to the main site now.

https://www.pombase.org/archive/spotlight

**Comment by ValWood** [comment]
Great. It's the best Hi-C visualization I've seen yet....

 I tried to interpret some in one of the  cohesin papers. The author took it back and took it all out. I thought it was great ;(
