### ISSUE TITLE
limit front page rotations to most recent 5

### ISSUE THREAD

**Issue by ValWood** [pombase/website#832]
can we do this to keep it fresh. The rest will be available in the archive.

**Comment by mah11** [comment]
This is controlled by the "show_on_front_page": true flag in pombe-embl/website/pombase_v2_config.json

I have changed it to "false" for the 4 oldest spotlights, leaving 5 "true". For future, we can either try to remember to set another one to false each time we add an item, or go in and switch a few every so often.

**Comment by ValWood** [comment]
Great. We'll just move things out when we get bored of them so that the new ones get seen. I guess this will kick in tomorrow.

Val
