### ISSUE TITLE
new front page rotation (cell cycle dependent phosphoproteome)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#833]
putting the file in dropbox

swaffer_CCDP

the aspect ratio isn't great for our box size, but if it looks funny I'm sure Matthew will re-jig it

- [ ] Quantitative phosphoproteomics reveals the signaling dynamics of cell-cycle Kinases; ~10K phosphorylation sites reported in PomBase.

paper
https://www.cell.com/cell-reports/fulltext/S2211-1247(18)30946-X?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS221112471830946X%3Fshowall%3Dtrue

**Comment by ValWood** [comment]
- [ ] announce pombelist with details about paper cut off, how to access below threshold annotations

**Comment by ValWood** [comment]
Draft pombelist post

We are now hosting data from 
Quantitative Phosphoproteomics Reveals the Signaling Dynamics of Cell-Cycle Kinases in the Fission Yeast Schizosaccharomyces pombe.
Swaffer MP, Jones AW, Flynn HR, Snijders AP, Nurse P.

<link to publication page>

This study uses quantitative phosphoproteomics to analyze the fission yeast cell cycle at sufficiently high temporal resolution to distinguish fine-grain differences in substrate phosphorylation dynamics on a proteome-wide scale. This dataset provides a useful resource for investigating the regulatory dynamics of cell-cycle kinases and their substrates. 

Nearly 10k phosphorylation events are identified (~1000 sites as heavy cell cycle regulated (both reported in PomBase). However, the authors encourage you to check the cell cycle quantifications in the paper for  the other ~9K sites  which show interesting behaviour but did not pass the threshold criteria for the analysis

**Comment by mah11** [comment]
What is the task for me?

**Comment by ValWood** [comment]
To do the post as I wasn't quite sure of the status. I can do it if you let me know when it's all live.

**Comment by mah11** [comment]
OK. We probably ought to wait until Matthew says whether there's any other curation to do in Canto - it would be tragic to announce the modification data and then have to take it away, even temporarily.

**Comment by ValWood** [comment]
Yes that's the plan...

**Comment by ValWood** [comment]
@kimrutherford   this spotlight can go live in the morning too, provided the  new file loads OK

**Comment by ValWood** [comment]
Can this Nurse lab spotlight go live today also? Midori plans to announce this dataset later. All loaded OK:

https://www.pombase.org/reference/PMID:29996109

v

**Comment by ValWood** [comment]
Hi kim, can this one go on the rotations?

Cheers

v

**Comment by kimrutherford** [comment]
That's added now.

**Comment by ValWood** [comment]
thanks! all done here then
