### ISSUE TITLE
Menu obscuring text on static pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#835]
On static pages on small displays, the menu obscures the text.

<img width="405" alt="screen shot 2018-07-05 at 08 23 29" src="https://user-images.githubusercontent.com/12727506/42308202-cd1f25ac-802c-11e8-89be-317e4f329fc0.png">

<img width="363" alt="screen shot 2018-07-05 at 08 24 29" src="https://user-images.githubusercontent.com/12727506/42308219-dcb9a0e6-802c-11e8-9ca6-9805412b51ea.png">

**Comment by kimrutherford** [comment]
This is fixed now.
