### ISSUE TITLE
more white space needed

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#838]
Minor thing; small displays could use some more white space between the image and the text "recent news"

<img width="547" alt="screen shot 2018-07-05 at 08 03 12" src="https://user-images.githubusercontent.com/12727506/42308672-2e4ecf5c-802e-11e8-8d5f-30a831725589.png">

**Comment by kimrutherford** [comment]
> Minor thing; small displays could use some more white space between the image and the text "recent news"

That's fixed now.  And I've made the "Recent news" heading bigger.
