### ISSUE TITLE
create pombase favicon

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#840]
for bookmark icon

**Comment by Antonialock** [comment]
Actually, we have one? And it is shown for me when I add it to my bookmarks toolbar. 

Then I don't understand what you wanted @ValWood  on the call today?

**Comment by kimrutherford** [comment]
> I wanted the icon on my phone....

I my phone there an "Add to home screen" option in the browser.  Is that what you mean?

That was working OK for me but the icon was low resolution.  I've now added icons and favicons of all sizes for all browsers using this site: https://realfavicongenerator.net/

It looks OK on my phone now:
![2018-07-21 10 56 02-cropped](https://user-images.githubusercontent.com/90474/43028818-38f8f4aa-8cd6-11e8-8c7a-7b1c408491fd.png)

**Comment by ValWood** [comment]
yes Eek! I am a saddo....
