### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by ValWood** [pombase/website#841]
I noticed a couple of weeks ago we had a bumper access day, (~558 I think in one day)

I took a screen-shot last night to remind me to tell you all, and because we were very close to 
0.5M  ~visitors~ page views
Then this morning everything has dropped. See:

![analytics](https://user-images.githubusercontent.com/7359272/42407073-a625dc8a-81ac-11e8-8e69-165dcb11e5ba.jpg)

Is that normal?

**Comment by kimrutherford** [comment]
> Is that normal?

It looks OK now.

**Comment by ValWood** [comment]
It definitely dropped (substantially).

We were on ~490,000  page views and we dropped back to  462,000

maybe GA recalculated ... just wondered.

**Comment by kimrutherford** [comment]
What time period were you looking at?  It says 512,330 when I look at Oct 20, 2017-Jul 15, 2018.

**Comment by ValWood** [comment]
Durrr, I was stuck in June!

Well, we have over half a million page views. Woo Hoo !
