### ISSUE TITLE
Quick little tool to analyse gene lists

### ISSUE THREAD

**Issue by ValWood** [pombase/website#842]
Kim wished that figure 3 was interactive.
![fig3_conserved_unknown_breakdown](https://user-images.githubusercontent.com/7359272/42409242-7bae578e-81cf-11e8-8ced-5bfd2675405c.jpg)

This lead to a little discussion.
We decided it would be nice to try to create a quick little gene list viewer that does this.

Basically user supplies  a list, and then choose from a set of pre-configured sorting options 
(later potential to extend)

Quick Mockup:

![kim_mock_up](https://user-images.githubusercontent.com/7359272/42409191-615dd2ac-81ce-11e8-948b-bd70b45c7606.jpeg)

Will try  it with a few simple of "classifiers"

- [x] ]1. Essentiality  (of deletion mutant)  
4  classes, essential, non-essential, no data, condition dependent

- [x] 2. GO component 
Begin with  nucleus>  ER>mitochondria> cytoplasm >other> none
Need to use a precedence since some will have more than one. We can also create combination bins later.

- [x] 3. presence/absence from S. cerevisiae (2 classes)

- [x] 4.  taxonomic distribution   
conserved in archae + bacteria, but not metazo
conserved in metazo
conserved in archae + bacteria, and  metazo
conserved in fungi only
other
(seems a bit complicated but that's what I have in my graph and these  5 classes should be mutually exclusive)

That's enough for now, will add more after prototype ;)

**Comment by kimrutherford** [comment]
I've had a look at how this could be implemented and I think I have a plan.  A prototype with one or two data types from your list would take two-ish days I think.  Getting something ready to release might take a week but I'm not sure.  I'll chip away at this in the background over the next couple of weeks and I'll let you know when there's a prototype.

**Comment by ValWood** [comment]
that would be brilliant, well worth the time investment!

**Comment by kimrutherford** [comment]
I know I was the one to suggest making the tool vertical but I now think horizontal might work better because most screens are wider than they are tall.

**Comment by ValWood** [comment]
I don't know. For long lists the  image will be  longer or wider than a screen It's easier to scroll up down than left/right

**Comment by kimrutherford** [comment]
Here's my progress so far:

![vis-tool-1](https://user-images.githubusercontent.com/90474/42452083-31247576-83dd-11e8-9cc6-6372229f244c.png)

**Comment by ValWood** [comment]
So exciting!
Feature size is a good one. This classifier will help me to "analyse" the species specific unknowns! I ditched this for the paper as I couldn't face doing another "figure 3"

**Comment by kimrutherford** [comment]
> Feature size is a good one.

In case it's not clear, "feature size" is the height of the genes lines.

**Comment by kimrutherford** [comment]
I've added a button on the gene lists to go into "Visualise" mode.  The button is only shown on pombase-dev for now because the visualisation doesn't do much and looks naff.  I'll let you as it improves.

![vis-tool-2](https://user-images.githubusercontent.com/90474/42494870-912fef0c-8475-11e8-8149-492a71fced64.png)

http://pombase-dev.bioinformatics.nz/term_genes/GO:0000070

**Comment by ValWood** [comment]
Oh fab...its useful already.

I just used on (GO:0140223), and I thought there was something wrong since the essentials was so high, but it really is 44/50 (not surprising now I think about it)

It will be so cool!

**Comment by ValWood** [comment]
- [ ]  gene name  pop up needs to scroll with mouse over for long lists

**Comment by kimrutherford** [comment]
I've added a GO component option and fixed a bunch of bugs (although there are more to fix).  If you click each sort button you get a nice pattern.  This screenshot is from http://pombase-dev.bioinformatics.nz/term_genes/GO:0046872

![vis-tool-4](https://user-images.githubusercontent.com/90474/42759237-65731148-895a-11e8-9e6a-ae6cbf9842a0.png)

**Comment by ValWood** [comment]
Cool, it seems like you got the basics!

**Comment by kimrutherford** [comment]
> presence/absence from S. cerevisiae (2 classes)

I've added this column.  I hope it's what you meant.  I also added a column for presence/absence of a human ortholog because it was easy.

I've fixed some display bugs too.

![vis-tool-5](https://user-images.githubusercontent.com/90474/42809711-57eec16a-8a0a-11e8-81dc-a2374657d883.png)

**Comment by ValWood** [comment]
Oh my god this is so cool!

It's great for a quick data check. For example with DNA replication, you can see immediately that  all are nuclear except 2 which are mitochondrial.

We can do slightly cleverer within column sorting  but it is  working really well already!

**Comment by ValWood** [comment]
Actually the sorting might be OK,  you can 'keep shuffling' to get what  you want.

A tiny tweak, in the "human present" can you put present to the top rather than absent?

**Comment by ValWood** [comment]
- [ ]  add product line next to gene ID

**Comment by ValWood** [comment]
Great for spotting "outliers"
tRNA metabolism. til1, top bar (no  cerevisiae, no human, inviable mitochondrial ....just doesn't happen)
That should definitely be on the student list for ortholog detection.

**Comment by kimrutherford** [comment]
> A tiny tweak, in the "human present" can you put present to the top rather than absent?

I've done that.  I've also changed it to sort "viable" ahead of "inviable" as that seemed more consistent.

> add product line next to gene ID

Done.

**Comment by ValWood** [comment]
Let me know  if/when you want suggestions/list of what to include.

Like
- [ ]  Probably when you 'primary sort' on a particular column, the column order should swap so that this is first
- [ ]  There is some issue with the sub-sorting, can discuss on call. One thing is to  sort initially once, then allow resorting. This would reduce the number of iterations to get the curation optimally 'clustered'
- [ ]  improve ruler with heading  protein, and number scale added
- [ ]  Make pop-up track down the page
- [ ] Only include selected features in 'pop-up'
- [ ]  GO component 'other' 'none' and 'mitochondrion' seem to be the same/ v. similar colour (not a biggie we can sort the colour palette at the end).
- [ ]  could  we track up and down the proteins on the ruler, but if you click on a column block, the bock highlights with the details of the major component (I think  you suggested something like this?)
- [ ]  Allow blocks to be selected as subsets, to enable drill down 
i.e nucleus  intersected with "decreased phosphorylation"  , or  whatever the query was
- [ ]   title with  the query/ number  (i.e decreased protein phosphorylation 135)
- [ ]  Add the column headers (maybe at a jaunty angle ?) 

I didn't mean to start  the list now ;) ...I think this will be very, very useful for some people.

**Comment by ValWood** [comment]
> I've done that. I've also changed it to sort "viable" ahead of "inviable" as that seemed more consistent.

- [ ]  inviable might be better above viable, (they are usually more interesting and a smaller number). Although maybe I'm suggesting this because all of the ones I have wanted to get to are inviable and they are currently out of reach of the scroller.

**Comment by kimrutherford** [comment]
>  Allow blocks to be selected as subsets, to enable drill down

I've done that now.  You can click on a block or a gene to toggle the selection.  control-click to add the hightlight genes to the selection rather than toggling.  I'm still working on the formatting of the list.

![vis-tool-select-1](https://user-images.githubusercontent.com/90474/43685191-9fb3b756-9902-11e8-9e37-9c41ccd7d890.png)

**Comment by Antonialock** [comment]
This looks great Kim!

It would be nice if the text + gene list moved when you look up and down the list. 

The text only displays at the top and disappears when you are not mousing over a block

Here I can see the text because I am mousing over a block at the top of the page:

<img width="812" alt="screen shot 2018-08-05 at 22 23 42" src="https://user-images.githubusercontent.com/12727506/43690224-910fd512-98fe-11e8-97d8-72bd0e976ade.png">


so here I have scrolled down the page and I am mousing over a block, but i can't see the text because it is displayed at the top

<img width="509" alt="screen shot 2018-08-05 at 22 23 51" src="https://user-images.githubusercontent.com/12727506/43690228-9ae2f56a-98fe-11e8-9b70-51dca27ab0d8.png">

**Comment by ValWood** [comment]
this is equivalent to the item above 
- [ ]  Make pop-up track down the page

**Comment by ValWood** [comment]
> You can click on a block or a gene to toggle the selection. 

nice. Maybe the list does not need to be presented on the page, but you  need to  load it  if you want to see it?

**Comment by kimrutherford** [comment]
> Maybe the list does not need to be presented on the page, but you need to load it if you want to see it?

I added to for debugging and for now it's the only way to navigate to a gene page - the genes in the selected list are links.

**Comment by ValWood** [comment]
I'm closing this it's too long.
I'll make a new ticket with outstanding tasks classified as pre-release and post-release.
