### ISSUE TITLE
canned queries text update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#849]
change

viable deletions -> viable  deletions protein coding (check, but I don't think we have any  data fro RNA's)

inviable deletions , ditto

Conserved in S. cerevisiae  -> proteins conserved in _S. cerevisiae_
Conserved in human/vertebrates proteins conserved in _human/vertebrates_

**Comment by mah11** [comment]
There are 14 ncRNA IDs in the viable deletions list, and 4 in the inviable list.

I did the name changes for the conserved protein queries.
