### ISSUE TITLE
what determines ordering of binding annotations?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#850]
I somehow expected here alphabetical by first gene name?
eso1
eso1, wpl
eso1, wpl
hrk1
hrk1

![what determines ordering](https://user-images.githubusercontent.com/7359272/42566378-4d7b1c12-84fe-11e8-9cf9-cd39c5d2e5e7.jpg)

is there any ordering currently (between annotations )?

**Comment by mah11** [comment]
It appears to be sorting first by column 17 (ones with an entry listed first, ordered by PRO ID; example on cdc2 page), then by extension (with extension sorting as you specified in #346), then by binding partner.

**Comment by ValWood** [comment]
Yes I think by phase makes sense longer term (and on   pages like cdc2 it helps a lot already)

It's not so obvious here!
It does make sense thought (and probably more when things are further connected up. I think, but I'm not sure,  that wpl does 'unloading ' during G2 and loading during M-phase.

**Comment by ValWood** [comment]
Oddly this was the next file I opened on my desk top!

And the curation almost captures the current model. I still need to refine a bit....


![hrk1](https://user-images.githubusercontent.com/7359272/42567396-87be33e8-8501-11e8-8c77-d010d502f254.jpg)
