### ISSUE TITLE
twitter feed on front page?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#852]
Since this has become increasingly popular I wonder if we should have it on the front page?
[tweets.pdf](https://github.com/pombase/website/files/2196008/tweets.pdf)

The posts are a bit more exciting than our "news feed" which could be narrower to accommodate it:

I think we would pick up even more users this way....

![tweets](https://user-images.githubusercontent.com/7359272/42737291-8b8005c2-8869-11e8-91a9-722270cea7af.jpg)

**Comment by ValWood** [comment]
also, it wouldn't need the "Tweets" title, just the twitter icon.

It seems twitter is having a bit of a resurgence...

**Comment by kimrutherford** [comment]
I'll give that a go.  I had a quick look and it seems that Twitter make it easy to do.

**Comment by kimrutherford** [comment]
I've added the twitter feed to the front page.  Does it look as you expected?

**Comment by ValWood** [comment]
I like it!

**Comment by ValWood** [comment]
I love  Sam's #fungifriday, and the fact that people are posting their preprints...... I check it much more these days....
