### ISSUE TITLE
Avoid multi gene phenotype display redundancy that is present on current site

### ISSUE THREAD

**Issue by ValWood** [pombase/website#86]
I just noticed that in the multi-gene phenotype section of the current pages, sometimes the same phenotype allele combination  is duplicated (with a different PMID)

Like so (top and bottom annotation in this screenshot)

![multigene redundancy](https://cloud.githubusercontent.com/assets/7359272/20458832/cfc77c08-aea7-11e6-936c-028b833d171d.jpg)

**Comment by ValWood** [comment]
The annotation should be displayed once, but supported by >1 PMID (same as other page sections)

**Comment by ValWood** [comment]
has dependency, genotype details so best handled at this point.

**Comment by mah11** [comment]
genotype details are there

**Comment by ValWood** [comment]
OK. I did not realise that I needed to click "genotype details" to see them. I don't think I am keen on displaying the "internal genotype ID" as default instead of the  user defined alleles.


also, sometimes the genotype is visible by default. See
FYPO:0000650	increased septation index T167Ecdc2-M63     7940bef1ad8a05ee-genotype-2
on cdc2 page

I guess we can discuss this tomorrow...

**Comment by mah11** [comment]
> OK. I did not realise that I needed to click "genotype details" to see them.

More info that I omitted earlier: clicking "genotype details" reveals desciptions etc. for all genotypes. You can see the details for any one genotype by clicking on its ID.

> I don't think I am keen on displaying the "internal genotype ID"

Kim told us ages ago that that's temporary, for his debugging purposes in these early days. He doesn't intend for it to go live looking like that! (And I reminded us when Antonia asked about it last week or the week before.)

That said, I guess we ought to discuss what to show for genotypes that don't have user/curator-assigned names.

> also, sometimes the genotype is visible by default. See
> FYPO:0000650 increased septation index T167Ecdc2-M63 7940bef1ad8a05ee-genotype-2
> on cdc2 page

In that one, T167Ecdc2-M63 is a genotype name, not the description with allele details.

**Comment by ValWood** [comment]
I'm not sure if this  is an issue on P2

**Comment by kimrutherford** [comment]
> same as other page sections

Which other page sections?

**Comment by ValWood** [comment]
this is no longer  the same issue as we don't show alleles in summary view, and  phenotypes are already non-redundant

In the full view you already seem to group identical alleles together. I spotted another related  issue, but that's a canto/chado ticket...
