### ISSUE TITLE
show residues in modification section on gene pages

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#861]
I think it would be good to show the residues in the "summary" view of modifications (summarised to one entry per residue). Can they also be numerically ordered?

Possibly also show the extensions?

<img width="1005" alt="screen shot 2018-07-18 at 22 49 23" src="https://user-images.githubusercontent.com/12727506/42909673-e0bfc6b0-8adc-11e8-91d6-cb2856f9ed70.png">

**Comment by mah11** [comment]
see #180 for history

**Comment by kimrutherford** [comment]
Should the residues be in a column or a row in the summary?

**Comment by ValWood** [comment]
I think they could be in a row maybe?

**Comment by kimrutherford** [comment]
I've added the residues to the summary.  It looks like:

![mod-residues-in-summaries-2](https://user-images.githubusercontent.com/90474/44194416-0c605a00-a18a-11e8-97f7-c5500f4c4e2e.png)

Is that OK?

**Comment by ValWood** [comment]
This looks great on all the pages I looked at. None of the ones I looked at have the gene name though?

Also "modifies" isn't quite the right  relation here.

(It would be correctly "modified residue" but I don't think this text is necessary?)
@Antonialock 
@mah11

**Comment by kimrutherford** [comment]
> None of the ones I looked at have the gene name though?

The gene names are included on the publication and term pages but not on the gene page.  Is that what you mean?

**Comment by ValWood** [comment]
In the image above it is a mixture.


Looks fine here:
https://www.pombase.org/reference/PMID:10036242

but cdc2 doesn't modify Y15.
cdc2 Y15 *Is modified*

**Comment by kimrutherford** [comment]
Ah, sorry.  I get it now.  That's wee1: https://www.pombase.org/gene/SPCC18B5.03

That's how it is in Chado.

**Comment by ValWood** [comment]
On the publication page
https://www.pombase.org/reference/PMID:10523629


O-phospho-L-serine
--
  | cdc25 modifies S148, S178, S192, S204, S206, S234, S359, S567, S99


would be, correctly

cdc25 **modified** S148, S178, S192, S204, S206, S234, S359, S567, S99


Ont eh gene pages we could use the same text "modified"

but I don't see anything like the example above where there is a mixture of

modified residue
and
midifies name-residue

Can you point me to this example?

**Comment by kimrutherford** [comment]
> Can you point me to this example?

It's from this session: https://curation.pombase.org/pombe/curs/98f0242de16564e8/feature/gene/view/2/ro

**Comment by ValWood** [comment]
OK to close this one just change the "label" form "modifies" to  "modified residue"

**Comment by kimrutherford** [comment]
> OK to close this one just change the "label" form "modifies" to "modified residue"

Done!

**Comment by ValWood** [comment]
announced
