### ISSUE TITLE
display filtering, phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#863]
![abnormal](https://user-images.githubusercontent.com/7359272/42989338-5f6eae20-8bf7-11e8-9817-d7971efcc2a3.jpg)

shouldn't 
"abnormal mRNA splicing via spliceosome' be hidden here?

(because abolished and decreased cover it)

**Comment by kimrutherford** [comment]
"abnormal mRNA splicing via spliceosome' be hidden here?

I thought so at first glance, but one says "abnormal" and the other"abolished".

**Comment by ValWood** [comment]
but  abolished  is abnormal, but more specific which should trump abnormal?

**Comment by kimrutherford** [comment]
I think it's because the extension is different and we don't handle that case yet.  It only hides parent term annotations with the exact same extension.

**Comment by kimrutherford** [comment]
If they both had "affecting dis2" the "abnormal" annotation would be hidden.

**Comment by ValWood** [comment]
Ah OK, I thought that if a parent had no extension, and  a descendant had an extension we still hid the parent.

We could do that I think @Antonialock @mah11 ?

**Comment by Antonialock** [comment]
I think that would be fine....

**Comment by ValWood** [comment]
closed in favour of
https://github.com/pombase/website/issues/930
