### ISSUE TITLE
add EPD links to gene pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#87]
In the External References section, add gene-specific links to the Eukaryotic Promoter Database (EPD).

Link syntax:
    http://epd.vital-it.ch/search_EPDnew.php?db=S_pombe&query=[systematic ID]

E.g. for tbp1
    http://epd.vital-it.ch/search_EPDnew.php?db=S_pombe&query=SPAC29E6.08

**Comment by mah11** [comment]
prompted by helpdesk ticket https://rt.sanger.ac.uk/Ticket/Display.html?id=558151

**Comment by ValWood** [comment]
covered by
https://github.com/pombase/website/issues/88
