### ISSUE TITLE
possible front page feature

### ISSUE THREAD

**Issue by ValWood** [pombase/website#870]
might use:
http://movie.biologists.com/video/10.1242/jcs.216580/video-1
Microtubule depolymerization in scd1Δ cells leads to PORTLI growth
video from XXXXX

if not:

![ken model front page](https://user-images.githubusercontent.com/7359272/43091181-53f621fc-8ea1-11e8-847b-3ebfdda649df.jpg)

need to write text/ remove "A"

@kimrutherford  would the video work?

**Comment by kimrutherford** [comment]
>  would the video work?

We'd have to scale it down a lot.  I can try if you like.  If the video is too small we could use a screenshot and then link to the video.

**Comment by ValWood** [comment]
let's do just the image.
The paper isn't through yet, so I'll activate this when it is.

**Comment by ValWood** [comment]
This image can also go on the  rotation tomorrow. Session should  be in the feed.

**Comment by kimrutherford** [comment]
Note to self: https://www.pombase.org/reference/PMID:29930085

**Comment by kimrutherford** [comment]
The new Spotlight is ready to go on pombase-dev.  The main site isn't updated yet.  Let me know if you spot any typos.

http://pombase-dev.bioinformatics.nz/archive/spotlight

**Comment by ValWood** [comment]
OK!

**Comment by ValWood** [comment]
I checked before we went back ;)
