### ISSUE TITLE
Improve links/actions section on term genes list pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#872]
I think this looks a bit messy.  I'm about to decrease the gap between "External links" and "Actions" because I think there's too much.

![term_genes-mess-1](https://user-images.githubusercontent.com/90474/43188504-60b85ce0-9048-11e8-9b65-e0109e0e4b23.png)

**Comment by ValWood** [comment]
yep, go for it....

**Comment by kimrutherford** [comment]
I made that change a while ago.
