### ISSUE TITLE
add ability to filter GO display on "phase"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#877]
enable filtering by "phase" extension on GO sections

would really help cdc2
https://www.pombase.org/gene/SPBC11B10.09

**Comment by ValWood** [comment]
phases to filter (relation happens during)

Mitotic M phase
Mitotic Interphase
Mitotic G2  phase
Moit

**Comment by kimrutherford** [comment]
> enable filtering by "phase" extension on GO sections

Just to check, should this just look at the phases from the "during" extensions?

**Comment by kimrutherford** [comment]
I've had a go at this.  There are some bugs to fix and we need to chat about the configuration so it's not released yet.

This is what my local version looks like:

![ext-filter-1](https://user-images.githubusercontent.com/90474/44266106-6ee65280-a27d-11e8-9630-62f698ae6c65.png)

**Comment by kimrutherford** [comment]
> There are some bugs to fix

I've fixed the problems I spotted.  The filter is not enabled yet because we need to chat about the configuration.

Here's the list of categories in my test config.  Please let me know what changes you'd like:

![ext-filter-2](https://user-images.githubusercontent.com/90474/44313350-52077600-a45b-11e8-9a25-eb8beea03e8b.png)

The code is general enough that we could add a filter in future for any extension that has terms as the range just by changing configuration.

Which ontologies should this filter be available for?  It looks like the Qualitative gene expression section has cell cycle extensions.  Does it make sense there?

**Comment by ValWood** [comment]
looks good.

I suggest ordering
interphase
G1 phase
S phase
G2 phase
M phase
+ prometaphase  (have we never used this?)
prophase
metaphase
anaphase
+ telophase  (have we never used this?)
G1 to G0
cell quiecence


I think it would make sense to add for gene expression too....

**Comment by kimrutherford** [comment]
> prometaphase

There are annotations to:
GO:0000236 mitotic prometaphase
eg. https://www.pombase.org/gene/SPAC110.02

Is that the term you mean?  I can't see a term named "prometaphase" in GO.

> telophase

Yep, there are annotations to descendants like mitotic telophase (GO:0000093).
eg. https://www.pombase.org/gene/SPBC29A3.17

I'll update the order and release the filtering in pombase-dev later.

**Comment by kimrutherford** [comment]
In the qualitative gene expression section we also have mitotic cell cycle (GO:0000278).  Should that go in the filter drop-down?

eg. https://www.pombase.org/gene/SPBC83.04

**Comment by kimrutherford** [comment]
There's an  annotation for SPBC83.04 that has this qualifier:
**during** cell quiescence following G1 arrest due to nitrogen limitation (PBQ:0000003)

Should that annotation be included when you pick "cell quiescence" from the filter?

That term isn't a descendant of  "cell quiescence" GO:0044838 but we can add "cell quiescence" PBQ:0000001 to "cell quiescence" category.  That way the filter would include descendants of both GO:0044838 and PBQ:0000001.

**Comment by kimrutherford** [comment]
Sorry, one more.

For SPBC83.04, Quantitative gene expression there is this extension:
**during** single-celled organism vegetative growth phase

It's not a cell-cycle phase but should that be included in the filter dropdown?

**Comment by kimrutherford** [comment]
The "during" extension filter is now available on the pombase-dev gene pages.  For now the filter is only visible it you "show details..."

> I think it would make sense to add for gene expression too....

That's done too.

**Comment by ValWood** [comment]
> In the qualitative gene expression section we also have mitotic cell cycle (GO:0000278). Should that go in the filter drop-down?


For expression yes, (and FOr GO MF and CC) but ideally not for GO  process (because that will be captured by the term). Is that possible?

**Comment by ValWood** [comment]
> That term isn't a descendant of "cell quiescence" GO:0044838 but we can add "cell quiescence" 

that would be perfect solution here

**Comment by kimrutherford** [comment]
> For expression yes, .... Is that possible?

Yep, the configuration is per-annotation type.

Where should mitotic cell cycle go in this list?:

interphase
G1 phase
S phase
G2 phase
M phase
prometaphase
prophase
metaphase
anaphase
telophase
G1 to G0
cell quiecence

**Comment by kimrutherford** [comment]
> that would be perfect solution here

Ah, good.  I tested that locally and accidentally released the change.  So that's how it's working now.

**Comment by ValWood** [comment]
> GO:0000236 mitotic prometaphase

yep

**Comment by ValWood** [comment]
> For SPBC83.04, Quantitative gene expression there is this extension:
during single-celled organism vegetative growth phase
It's not a cell-cycle phase but should that be included in the filter dropdown?


yes. This is a bit of an "annotation consistency issue"
MAybe we should always use this when we (I) sometimes use "mitotic cell cycle"

**Comment by kimrutherford** [comment]
> yes. This is a bit of an "annotation consistency issue"

Which sections should we add it to?  "Qualitative gene expression" and "Quantitative gene expression"?

**Comment by ValWood** [comment]
> Which sections should we add it to? "Qualitative gene expression" and "Quantitative gene expression"?

Yes I think this is where we have used it.
We should do a quick look and see which phases we have used with which ontologies. I will try to look at this but I don't think I'll get to it today so if anyone else can pull the numbers....

Otherwise assign to me and  I'll look next week....actually I'll do it in the context of the curation tracker ticket I just opened.

**Comment by kimrutherford** [comment]
So "mitotic G1 phase" instead of "G1 phase" etc.?

I can do that tomorrow.  I'll need to look up the more specific GO term IDs and do some cut and pasting in the config.

**Comment by ValWood** [comment]
Yep that's it. I can  do this bit  later but I'm popping to the shops now...

**Comment by ValWood** [comment]
.....Detour via Bray/Dublin for Hendrik....back now

GO:0098763    mitotic cell cycle phase
GO:0051329    mitotic interphase
GO:0000087    mitotic M phase
GO:0000236    mitotic prometaphase
GO:0000089    mitotic metaphase
GO:0000088    mitotic prophase 
GO:0000090    mitotic anaphase
GO:0000093    mitotic telophase

**Comment by ValWood** [comment]
GO:0000080    mitotic G1 phase
GO:0000085    mitotic G2 phase
GO:0000084    mitotic S phase
GO:0098762   meiotic cell cycle phase 
  
Are these two in PomBase ontology? @Antonialock  @mah11 
G1 to G0
cell quiecence

**Comment by mah11** [comment]
G1 to G0 = GO:0070314 G1 to G0 transition

cell quiescence is both GO:0044838 and PBQ:0000001. More specific types are defined in PBQ but not in GO. We've used GO:0044838 in GO extensions, and PBQ in some of the quantitative gene expression data files.

**Comment by kimrutherford** [comment]
It looks like I updated the configuration for the during filter 2 years ago.  Can this be closed?

**Comment by ValWood** [comment]
I forgot that we could do this!

I wonder if, since the extensions are visible in the summary view, this filter could also be visible on the summary view?

**Comment by kimrutherford** [comment]
> I wonder if, since the extensions are visible in the summary view, this filter could also be visible on the summary view?

That would be good.  I need to fix #1667 first.

**Comment by kimrutherford** [comment]
I think this is done now.
