### ISSUE TITLE
mad2/sgo2 new page rotation PMID:28178520

### ISSUE THREAD

**Issue by ValWood** [pombase/website#878]
Sharpening the anaphase switch 
from PMID:28178520
(need new terms so this won't be through until next week)

iamge in drop_box
mad2_anaphase_switch

That took ALL DAY!

**Comment by ValWood** [comment]
This session should be live in the feed tomorrow, so the new front page rotation can be actioned.

**Comment by kimrutherford** [comment]
Note to self: https://www.pombase.org/reference/PMID:28178520

**Comment by kimrutherford** [comment]
The new Spotlight is ready to go on pombase-dev.  The main site isn't updated yet.  Let me know if you spot any typos.

http://pombase-dev.bioinformatics.nz/archive/spotlight

**Comment by ValWood** [comment]
looks good

**Comment by mah11** [comment]
new one looks fine, but I've just committed some typo fixes for the Swaffer one ;)
