### ISSUE TITLE
Quick little gene list tool, user defined terms

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#879]
add the ability to specify one (or more?) terms to categorize on in its own column (e.g. a GO term, a phenotype term, domain? etc)

**Comment by ValWood** [comment]
We talked about this. Once working with basic features we can think about additional user configuration (of any term in PomBase)

(this also overlaps with the ability to change the defaults for a specific query)

**Comment by kimrutherford** [comment]
> later for this one

Yep.  :-)

> add the ability to specify one (or more?) terms to categorize on in its own column (e.g. a GO term,
> a phenotype term, domain? etc)

I think this is not too tricky.  It's probably a day or two of work.

If we allow more than one term per column we'd need to decide how to handle the case where a gene is annotated with more than one of the terms.

**Comment by kimrutherford** [comment]
(This is an old issue that I thought could use some attention)

> If we allow more than one term per column we'd need to decide how to handle the case where a gene is annotated with more than one of the terms.

The easiest option is only allow one term per user-added column.  It's relatively simple to implement and it's also clear to the user what's going on.  We could think about have multiple terms per column later on.

![quilt-user-term-mockup-1](https://user-images.githubusercontent.com/90474/124534336-285bc500-de68-11eb-99de-c3e6b832b7b2.png)

**Comment by ValWood** [comment]
I think that would be good!

**Comment by kimrutherford** [comment]
OK.  I might work on this sometime in the next few weeks if I need a change of pace.

**Comment by kimrutherford** [comment]
I had a first go at this.  It's a prototype at the moment so it's only available on the dev site:
http://dev.pombase.kmr.nz/vis/from/id/f1a709c7-a462-41f5-b0ca-dea2bf07d519

Look for "Add column ..." on the left under the list of columns.

Here's an example with two extra columns:

![quilt-user-columns-1](https://user-images.githubusercontent.com/90474/133886562-f5798111-af9d-4a3e-80e2-e635cbd193d8.png)

**Comment by ValWood** [comment]
This is looking good, but I think it's a bit buggy.

I used GO term 'chromosome segregation' there is an intersect with DNA metabolic process which contained. genes that  I didn't expect. When I filter this list, this is what I see:



<img width="1149" alt="Screenshot 2021-09-19 at 08 32 33" src="https://user-images.githubusercontent.com/7359272/133919362-2ac8a94c-98e3-40e3-aa6f-c48d61d8b1cf.png">

So the query description isn't what I expected, and the list of genes isn't what I expected.

**Comment by kimrutherford** [comment]
> So the query description isn't what I expected,

Hi Val.  The query description generation hasn't changed.  It has always worked like that: "X selected genes from visualisation of ..."

I think I know why the gene list is wrong.  I should be able to fix that tomorrow.

**Comment by ValWood** [comment]
The intersection I selected was DNA metabolic process  with. the term I. added (chromosome segregation).

**Comment by ValWood** [comment]
I guess. it thinks I moused over something else?

**Comment by kimrutherford** [comment]
> contained. genes that I didn't expect.

Now I've had a look, maybe it's OK?  I intersected your list with "chromosome segregation" and "DNA metabolic process" and got the same list back.  Here's my query:

http://dev.pombase.kmr.nz/results/from/id/5c936336-341f-4795-9b02-60e653b348fd

**Comment by kimrutherford** [comment]
Bugs and to-do:

  - disable the "Apply" button in the "Add QuiLT column" if no term has been selected
     - maybe also relabel the button to "Add"?
     - make it more clear that a term has been selected by displaying "Selected term: ..." 
  - sometimes the user term column is all red/not_annotated when I return to the QuiLT page after doing other queries
  - I think that FYPO terms aren't working but I need to double check
  - the diagram disappears briefly when a user term is added or removed (annoying but not a show-stopper)
  - currently we have the labels "annotated"/"not_annotated", coloured green and red - should those colours or labels be changed?

**Comment by kimrutherford** [comment]
> I think that FYPO terms aren't working but I need to double check

Yep, completely not working.  :-)

Supporting FYPO might need to be a phase 2 task as we need to decide which genes to include.  In the query builder we have options for:
  - multi vs single gene genotype
  - haploid/diploid
  - expression level
  - conditions

We might need some of that when selecting a FYPO term for a column.

For now I've removed FYPO from the list of possible CVs in the add column dialog.

**Comment by kimrutherford** [comment]
> sometimes the user term column is all red/not_annotated when I return to the QuiLT page after doing other queries

That's fixed now.

**Comment by kimrutherford** [comment]
> If we wanted to we could release an initial version without phenotypes and then do an update later.

I think we should!  Mostly because this has been sitting around for 3 years.  I completely forgot about it.  :-)

Here's the current status:
 - https://github.com/pombase/website/issues/879#issuecomment-922259605

**Comment by kimrutherford** [comment]
Job for Kim: update documentation

**Comment by kimrutherford** [comment]
> Could you do a quick test before release?

In the dev version: https://dev.pombase.org/query

**Comment by ValWood** [comment]
Looks good to me

**Comment by PCarme** [comment]
I couldn't find any issue either

**Comment by kimrutherford** [comment]
Thank you both.  I'll add a little bit to the documentation and then release the change.

**Comment by kimrutherford** [comment]
> I'll add a little bit to the documentation and then release the change.

I've updated the text and screenshot in the documentation.  I think it's all ready to go so I've pushed all the changes.  The "Add column" button will be on pombase,org on Tuesday morning.

**Comment by kimrutherford** [comment]
All released.  Let me know if there's any way we can improve the documentation.

The documentation is here if you'd like to edit directly - use the pencil icon, top right:
https://github.com/pombase/website/blob/master/src/docs/documentation/quick-little-tool.md
