### ISSUE TITLE
Gene Page Specification, External references

### ISSUE THREAD

**Issue by ValWood** [pombase/website#88]
Currently we have

![external refs](https://cloud.githubusercontent.com/assets/7359272/20492570/1c0c0c30-b00d-11e6-87ca-581866aca923.jpg)

Add screenshots of any other MODS or resources which could be emulated

**Comment by ValWood** [comment]
- [ ] List new links to be added

- [ ]  List links to be removed or replaced

**Comment by ValWood** [comment]
- [ ] List New links to be added (provide descriptions)
- [ ]  List links to be updated or removed (provide descriptions for new links)

**Comment by ValWood** [comment]
Changes required to  external links section

 - [ ]  Discuss. Maybe we should group the db-xrefs within the  gene page section  displaying data that they are relevant to (this might already be in a ticket?).

-  [ ]  Make it clearer what  type of data they are (sometimes it non obvious). Group links by "type" (ortholog interaction etc)

**Comment by ValWood** [comment]
Do we want to have these links associated with relevant page sections?

**Comment by ValWood** [comment]
- [ ]  For external links relevant to a page section, we have a landing page and list 
(what detail?)

**Comment by ValWood** [comment]
curators need to make a list for each site with
- [ ]  database
- [ ]  types (which section?)
- [ ]  Id if relevant
- [ ]  base URL or mapping file
- [ ]  Description (what it is)
- [ ] provider

**Comment by Antonialock** [comment]
Val, there are 18 tickboxes in this ticket xD what's to be done here?

**Comment by ValWood** [comment]
Just the final task above for now

**Comment by ValWood** [comment]
We can do this on a curator meeting.
Will be quickest.
I'll add discuss back so we can find it easily.

**Comment by ValWood** [comment]
OK we have a plan.
We need a config file with the following headings:

Type (classifier for grouping)
Name (name of the resource , hyperlink)
Description (what the user will find when they get there)
LINK format will be either base URL or details of hwere the lookup/mapping file lives

So far we have:

Strain and reagents || National BioResource Project (NBRP)|| Strains and clones|| http://viewer.shigen.info/yeastvw/wordsearch/search?word=SPBC11B10.09&fuzzy=y&action=mapview&ysttype=f

Strain and reagents ||SPD / RIKEN||Orfeome Localization Data||Mapping_file

Interactions || BioGRID ||Physical and genetic interactions||https://thebiogrid.org/276415/summary/schizosaccharomyces-pombe/cdc2.html

Interaction|| STRING|| Network display of known and predicted interactions and functional associations||

Expression||Gene Expression Omnibus||https://www.ncbi.nlm.nih.gov/geoprofiles/?term=SPBC11B10.09	

Expression||pombeTV|| tiling array & illumina sequencing profiles||http://bahlerweb.cs.ucl.ac.uk/cgi-bin/pombetv/pombetv?condition=13&genename=SPBC11B10.09&action=display

Expression||expression viewer cell cycle, stress, meiosis, or mating||http://bahlerweb.cs.ucl.ac.uk/cgi-bin/SPGE/geexview?group=4&scale=log2&scale_min=-2&scale_max=2&q=SPBC1215.02c

Proteomics||PeptideAtlas||Peptides identified in tandem mass spectrometry ||https://db.systemsbiology.net/sbeams/cgi/PeptideAtlas/GetProtein?action=QUERY&atlas_build_id=355&protein_name=SPBC11B10.09

Structure	Comparative protein structure models

Orthologs	



Sequence resources UniProtKB/SwissProt	protein database Mapping_file
Sequence resources NCBI	Query all NCBI databases	URL

**Comment by ValWood** [comment]
The file may need some tweaking but otherwise ready to go...

**Comment by ValWood** [comment]
@mah11 
- [ ] put URL in if not one in GO
- [ ] if there is one put ID in
- [ ] use same format for URL as GO file


@ValWood
chase up mapping file sources with Mark

**Comment by ValWood** [comment]
I mailed Mark. He thinks these mappings are in Canto already, I think he might be correct as one place they are stored is in Artemis.
He provided a text file from 2011, but he didn't use it.

Maybe it would be good to do a quick check to make sure everything in the original file is still in Artemis/Canto, but not critical

**Comment by mah11** [comment]
Config file edits as done as they can be for the moment (i.e. until/unless Kim has feedback or we have new entries).

For the "query all NCBI databases" I put yes for mapping file, because the search terms should include the gene systematic ID, standard name, and any synonyms.

**Comment by kimrutherford** [comment]
I've added a basic external references section.  It's not finished - the two links that need to use the go_xrfs file aren't wired up yet.

The configuration is in the section called "external_gene_references" in:
  pombe-embl/website/pombase_v2_config.json

I hope the syntax makes sense.  Here's an example:

    {
      "ref_type": "Expression",
      "name": "Gene Expression Omnibus",
      "description": "GEO profiles",
      "url": "https://www.ncbi.nlm.nih.gov/geoprofiles/?term=<<uniquename>>"
    },

In the URL the "<<uniquename>>" will be replaced with the systematic ID of the gene.  Other possibilities are "<<uniprot_identifier>>", "<<orfeome_identifier>>" and "<<NCBI_ALL_IDS>>".

"<<NCBI_ALL_IDS>>" tells the web code to retrieve all IDs and synonyms and join them together in a way suitable for the NCBI query.

For now, if you make any config changes I'll need to manually re-release the site.  It's quick though, less than 60 seconds.

I wasn't sure what you wanted to do with the "Type" from the config file so for now it's the first column.

I've added "External references" to the menu on the left of the gene pages.

As usual, a shift-reload might be needed.

**Comment by ValWood** [comment]
Looks great!

**Comment by kimrutherford** [comment]
All of the config file items are now displayed and the external links work.

I have simplified the config a bit.  It now looks like:

    {
      "ref_type": "Expression",
      "name": "Gene Expression Omnibus",
      "description": "GEO profiles",
      "field_name": "uniquename",
      "url": "https://www.ncbi.nlm.nih.gov/geoprofiles/?term=<<IDENTIFIER>>"
    },

The `<<IDENTIFIER>>` is all the URLs.  The "field_name" can be "identifier", "uniprot_identifier", "orfeome_identifier" or "NCBI_ALL_IDS" as described above.

What else needs doing?

**Comment by kimrutherford** [comment]
I'll close this.  Please open new issues for problems.
