### ISSUE TITLE
Quick little gene list tool, functional classification

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#880]
Jurgs group (loved the tool already!) and wanted to be able to sort on different molecular functions like in your fig3 Val.

Need to think about good broad categories...

**Comment by ValWood** [comment]
oxidoreductase activity (GO:0016491)
hydrolase activity (GO:0016787)
transferase activity (GO:0016740)
ligase activity (GO:0016874)
cyclase activity (GO:0009975)
lyase activity (GO:0016829)
catalytic activity (GO:0003824 (will catch the 32 not as specific as above)
enzyme regulator  activity (GO:0030234)
transcription regulator activity (GO:0140110)
transporter activity (GO:0005215)
cytoskeletal protein binding (GO:0008092)
unfolded protein binding (GO:0051082)
DNA binding (GO:0003677)
RNA binding (GO:0003723)
metal ion binding (GO:0046872)
lipid binding (GO:0008289)
cell adhesion mediator activity (GO:0098631)
299 | structural molecule activity (GO:0005198)

**Comment by ValWood** [comment]
This gets 3373/3829 of protein coding with MF without including plain "protein binding"

**Comment by ValWood** [comment]
maybe we can introduce some sort of shading  (hashing etc). I can see it must be challenging to have colours always contrast enough with the adjacent cells!
