### ISSUE TITLE
Quick little gene list tool, download image

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#881]
add the functionality to export the image in some image format

**Comment by kimrutherford** [comment]
I've added a Download link under the other controls.  The file you get is in SVG format because that was easy.  It may not be the most useful format though.

**Comment by ValWood** [comment]
- [ ]  change text to say "Download image"

Can add labels and key later.....

**Comment by ValWood** [comment]
can close?

**Comment by kimrutherford** [comment]
The remaining issue is #986 so I'll close this.
