### ISSUE TITLE
Quick little gene list tool, select and view cluster

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#882]
within a column, be able to see all genes with a specific colour coding (click on it -> see gene list)

(can we make this cleverer by going across columns and would that be useful?)

**Comment by ValWood** [comment]
I think this is:

https://github.com/pombase/website/issues/842
could we track up and down the proteins on the ruler, but if you click on a column block, the bock highlights with the details of the major component (I think you suggested something like this?)

plus 
- [ ]  Allow blocks to be selected as subsets, to enable drill down

**Comment by kimrutherford** [comment]
> Allow blocks to be selected as subsets, to enable drill down

I have a few ideas about selecting genes and blocks but it might be a bit ambitious.  Let's chat about this sometime.

**Comment by Antonialock** [comment]
yes sounds like 842
