### ISSUE TITLE
gene list tool: Decide colour palette add color legend

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#883]
add a colour legend for the different colours used

**Comment by ValWood** [comment]
and document/write legend

**Comment by ValWood** [comment]
Do this last after we know the palette etc. It might not even stay the same depending how many components and colours we have?

**Comment by ValWood** [comment]
Current issues
-  'other' 'none' and 'mitochondrion' seem to be the same/ v. similar colour 

Suggestions
- make anything which is "no data" white   (i.e component unknown, no viability data)

**Comment by ValWood** [comment]
see
https://github.com/pombase/website/issues/986

**Comment by ValWood** [comment]
I think this one can close?
