### ISSUE TITLE
Copy annotation files to FTP

### ISSUE THREAD

**Issue by mah11** [pombase/website#887]
There are some files that are getting regularly updated in the /nightly_update/ FTP directory, but aren't being copied over to the stable locations that we link to from the various downloads web pages.

Can files be copied over to pombe-embl svn automagically, or otherwise be updated in the stable FTP locations with little or no human intervention, at some regular interval (daily/nightly good but less frequent wouldn't be a showstopper)? I've made a little table of which file ought to go where if we go the svn route:

|example (most recent file at ticket time)|copy to svn location|
|-|-|
|pombase-build-2018-08-01.human-orthologs.txt.gz|/pombe-embl/ftp_site/pombe/orthologs/human-orthologs.txt.gz|
|pombase-build-2018-08-01.modifications.gz|/pombe-embl/ftp_site/pombe/annotations/modifications/pombase-chado-v62-2017-01-30.modifications.gz|
|pombase-build-2018-08-01.phaf.gz|/pombe-embl/ftp_site/pombe/annotations/Phenotype_annotations/phenotype_annotations.pombase.phaf.gz|

The particularly perceptive among you will have noticed that the table above doesn't include the GAF. That's because I would like _not_ to have the GAF copied over by magic, so I can continue to run owltools checks locally before committing it to the location where GO now gets it from. Shout if that would pose any problems.

**Comment by kimrutherford** [comment]
Those files are copied to SVN nightly now and the FTP is updated.

I renamed `pombase-build-2018-08-01.modifications.gz` to `pombase-chado.modifications.gz` because it's easier to cope with files in SVN that don't have dates in the name.

I you rename the file in SVN let me know so I can update the load script.

**Comment by mah11** [comment]
That all looks good - the desired files have updated, and I have no need to rename the modifications file.

Having checked, I'll close this. Thanks!
