### ISSUE TITLE
pombase publications page?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#893]
I thought we had a publications page with access to all Pombase publications (and the infographic poster). I can't find it from the menu??

**Comment by kimrutherford** [comment]
There are a few PomBase publications here: https://www.pombase.org/about/citing-pombase

There are some links on this page too: https://www.pombase.org/documents

Are there more somewhere else?

**Comment by ValWood** [comment]
yep It's this page:
https://www.pombase.org/documents

I scanned
https://www.pombase.org/documentation
but I missed it under
Other PomBase Pages
--Publication pages

might  be more obvious

How to Cite PomBase
- See the Citing PomBase page
- Other publications (papers, posters, book chapters)

or even somehow combining into the "citing pombase page"

"Pombase publications and citing Pombase"

this way we have a single prominent page to refer our funders etc. to.

**Comment by ValWood** [comment]
Oh that link isn't even our publications, it is Pombase Publication pages, so it really is quite hidden...

**Comment by mah11** [comment]
I've now added a page called "published by PomBase". It and the Citing PomBase page link to each other (other MODs keep separate pages).

Before I close this, check the list and decide whether to add any that aren't all-PomBase, e.g. the GO annotation extensions paper. Also make sure I haven't missed anything obvious!

**Comment by ValWood** [comment]
will check, but I couldn't find it...

**Comment by mah11** [comment]
mea culpa, I forgot to add it to the index and left-hand menu. Can do that today ...

**Comment by mah11** [comment]
URL is https://www.pombase.org/about/published-by-pombase

I've also just committed more links to it in the About department.

**Comment by ValWood** [comment]
great!

**Comment by Antonialock** [comment]
If the page was called "PomBase publications" then I would expect any papers that aren't all PomBase to not be on it.

I would expect e.g. the annotation extension paper on a page titled "Publications by PomBase staff"?

Close if you disagree?

**Comment by ValWood** [comment]
The page is called 
"publications by PomBAse staff"
https://www.pombase.org/about/published-by-pombase

but maybe change the link text on this page
https://www.pombase.org/about/citing-pombase

from
Also see the Terms of Use and the complete list of papers published by PomBase.

to
Also see the Terms of Use and the complete list of papers published by PomBase staff?

**Comment by ValWood** [comment]
I still don't see the list of Pombase  project publications under "about"

**Comment by mah11** [comment]
Do you mean you want it added to the menu bar that appears on every page?

If so, I'd like to leave that for Kim, because it's more fiddly than most of the rest of webpage editing.

**Comment by ValWood** [comment]
I think it could be under "About"

@Antonialock 
@kimrutherford ?

"Pombase Publications"
for all project related publications?

(I still can't find this page)

**Comment by ValWood** [comment]
yes. I think it could. the "about" menu is quite short and it's good to show  all of out outputs.

**Comment by mah11** [comment]
I opened #1049, since there's been a task done for this ticket already, and the follow-ups were risking confusion.
