### ISSUE TITLE
names files

### ISSUE THREAD

**Issue by ValWood** [pombase/website#894]
follow on from:
https://github.com/pombase/website/issues/796

- [x] update README to make it clear that  allNames.tsv is the old name for  gene_IDs_names.tsv

and that the file is a dummy link to the extant file?

- [ ] should we tell pombelist?

**Comment by ValWood** [comment]
from
- [ ] We would need to let people know.
pombelist, EsyN, danny Bitton, EBI ( ~Maria~ done, HGNC) anyone else?

**Comment by ValWood** [comment]
They were using:
ftp://ftp.pombase.org/nightly_update/misc/all_ids.tsv
but now should use:
ftp://ftp.pombase.org/pombe/names_and_identifiers/gene_IDs_names_products.tsv
which is the one we're going to keep and maintain in the future.

**Comment by mah11** [comment]
README updated

**Comment by kimrutherford** [comment]
> README updated

Thanks.  It's updated on the FTP site too now.

**Comment by ValWood** [comment]
TOD: Tell pombelist users about changed file name/content if appropriate, then this can be closed

**Comment by ValWood** [comment]
@mah11  @Antonialock 
do you think this needs to be announced?
If so  can someone do a quick message.

**Comment by mah11** [comment]
I think if we aren't getting frantic helpdesk questions from people who can't find a file they want, it's not a big deal so let's not bother.

**Comment by Antonialock** [comment]
If things aren't going to break (because there is a link in place) then I guess it is less important?

**Comment by Antonialock** [comment]
But if it could mess with scripts etc then it should be announced?

**Comment by mah11** [comment]
The changes took effect two months ago, and no howls of anguish. (We did email several individuals/groups that we knew would be affected.) So I'm gonna close this; we can revisit if we do get questions or complaints.
