### ISSUE TITLE
small update to InterPro section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#895]
we can make the new "attribute model" a link  

from
https://github.com/pombase/pombase-chado/issues/690

Some entries in the XML have a new attribute "model".  So we have `model="2bwnA02"` here:

```xml
<match id="G3DSA:3.40.640.10" name="G3DSA:3.40.640.10" dbname="CATHGENE3D"
       status="T" model="2bwnA02" evd="HMMPfam">
```

and `model="0046747"` here:

```xml
<match id="SSF53383" name="SSF53383" dbname="SSF" status="T"
       model="0046747" evd="HMMPfam">
```

It is:

SUPERFAMILY and Gene3D are a bit different to our other member databases, as
they use a set of different HMMs to represent their entries (there is not a 1
entry to 1 HMM relationship). We have now added a link to the exact HMM that a
sequence hits for these entries, which is what the model attribute represents.
It is only used in SUPERFAMILY and Gene3D matches.

**Comment by kimrutherford** [comment]
Do the model IDs need to be links?  If so, what should they link to?

InterPro show's the model if you hover over a domain but it's not a link.

![interpro-gene3d-1](https://user-images.githubusercontent.com/90474/44696107-43a80280-aaca-11e8-973f-127a5e9ef878.png)

**Comment by ValWood** [comment]
Oh let's leave this. I'm not sure it will be missed by our users!
