### ISSUE TITLE
Should we make the stats  page a static page?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#896]
I have been wondering for a while whether we should make the stats page static.
I often show people this page to impress them with our stats but then it takes quite a long time to load  (because it pulls all of the data from the database). So although I don't mind waiting 30 or so secs for the page to load myself, it isn't great when you are demoing to people (and it takes longer if I'm on some local wireless which I useually am if I am demoing anything). 

Also, this is a page we would like our funders to look at so we don't want them to get bored waiting and go away.

 I don't even think it needs to update more than once a month because the increments will hardly be noticable on smaller timescales....

**Comment by kimrutherford** [comment]
I have a long term plan to move the stats page to the main website and update it nightly with everything else.  I thought I'd made a issue about it but I can't see it now.

Maybe my plan shouldn't be long term?

**Comment by Antonialock** [comment]
Yeah would be good to have it in line with pombase versions/releases?

**Comment by mah11** [comment]
PomBase no longer has versions or releases. We didn't think it was worth assigning a release number to each nightly update ;)

There's a back-burner plan to stash monthly snapshots somewhere ftp-able.

**Comment by ValWood** [comment]
Yeah so maybe when we do monthly snapshots would be the time to make this change. It's not urgent. I was thinking "before renewal"

Although it might be nice before Biocurator, i can imagine me showing this page to anyone who will look :)

**Comment by kimrutherford** [comment]
> So although I don't mind waiting 30 or so secs for the page to load

I'm sure it used to be faster than that.

As a quick fix for the slowness, I've changed the config so that the page is cached in the web server for much longer (3 hours) and added a cron job that tries to get the page from the server every hour.  The effect should be that unless you're quite unlucky the page should now load quite quickly (definitely less than 5 seconds).

**Comment by ValWood** [comment]
37 and counting...

**Comment by ValWood** [comment]
can't get it to load now....

**Comment by kimrutherford** [comment]
I've restarted everything and it's now working better.

**Comment by ValWood** [comment]
instant!

**Comment by ValWood** [comment]
we can close this....
