### ISSUE TITLE
transcription factor FAQ update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#897]
FAQ will need to be updated

https://www.pombase.org/faq/how-can-i-find-transcription-factors-and-their-targets-pombase

**Comment by mah11** [comment]
when GO transcription factor activity work done (see https://github.com/geneontology/go-ontology/projects/7)

**Comment by ValWood** [comment]
Also

How can I find transcription factor binding sites in PomBase?
A data track showing transcription factor binding sites was available in the previous version of the PomBase genome browser. We will soon make this track available in JBrowse.
Also see the FAQ on finding transcription factors.

(can update about the tracks availability already)

**Comment by ValWood** [comment]
redundant with 
https://github.com/pombase/website/issues/775
