### ISSUE TITLE
links to browser from recent news etc.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#899]
news item
A PomBase-generated dataset of promoter elements across the genome (computational matching of the consensus promoter sequences to the reference DNA sequence)

link takes you to this page
https://www.pombase.org/browse-curation/dna-binding-sites

- [ ] it would be useful if there was a link to the configured browser track...

https://www.pombase.org/jbrowse/?loc=III%3A725762..736349&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CConsensus%20transcription%20factor%20DNA%20binding%20motifs&highlight=

In fact also for the other datasets, the news item could  also have a 'browser' link

- [ ]  this page
https://www.pombase.org/browse-curation/dna-binding-sites
could also have link to the 'promoters' track

- [x] the news item link to 
https://www.pombase.org/jbrowse
is broken

**Comment by ValWood** [comment]
Longer term we should also add a link from individual publication  pages to their browser tracks, if applicable. Is there already a ticket for that?

**Comment by kimrutherford** [comment]
> Longer term we should also add a link from individual publication pages to their browser tracks, if
> applicable. Is there already a ticket for that?

Yep: #801

**Comment by kimrutherford** [comment]
> the news item link to
> https://www.pombase.org/jbrowse
> is broken

I fixed that.  It will be in the main site later today.
