### ISSUE TITLE
can DNA binding motifs fit in under one of the menus?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#901]
https://www.pombase.org/browse-curation/dna-binding-sites

It might even be appropriate under search is we use this as a launch page to the browser track
https://www.pombase.org/browse-curation/dna-binding-sites

I can never find it. It is a popular page though...I'm not really sure how others get to it... (maybe it got a boost from the pombelist post)

**Comment by ValWood** [comment]
It would seem a bit strange.

Maybe we could change the "genome status" menu title to just "Status and inventories"?
too long?

**Comment by ValWood** [comment]
> It would seem a bit strange.

I meant strange under search, but under either...

**Comment by mah11** [comment]
> Maybe we could change the "genome status" menu title to just "Status and inventories"?

Long, and I think we want to keep "genome" so it isn't taken to mean "status of PomBase" or status of whatever else (curation, the community, the weather ...). I'll try to think of a word to replace "status" instead; the only things I've come up with so far are "notes" (boring and not very informative) and "highlights" (not really accurate).

**Comment by ValWood** [comment]
Can't we just have a "Find Data" menu for lists and browsable things?

**Comment by ValWood** [comment]
Or "Browse Data"

**Comment by ValWood** [comment]
discuss on call?

**Comment by ValWood** [comment]
"Browse data" ?

@mah11 @Antonialock  ?

**Comment by ValWood** [comment]
@Antonialock  @mah11 Should we add a "Browse" menu tab... there are quite a few 'browse' lists etc that are difficult  to locate

**Comment by Antonialock** [comment]
as a replacement for genome status? the GO slim overview is also browsable. 

> > Maybe we could change the "genome status" menu title to just "Status and inventories"?
> 
> Long, and I think we want to keep "genome" so it isn't taken to mean "status of PomBase" or status of whatever else (curation, the community, the weather ...). I'll try to think of a word to replace "status" instead; the only things I've come up with so far are "notes" (boring and not very informative) and "highlights" (not really accurate).

how about overview?

**Comment by Antonialock** [comment]
> @Antonialock @mah11 Should we add a "Browse" menu tab... there are quite a few 'browse' lists etc that are difficult to locate

would that be in addition to 'genome status' (the GO slim overview is also browsable?)

**Comment by ValWood** [comment]
GO slim overview would move to Browse"
although things could be under both lists

**Comment by mah11** [comment]
> "Browse data" ?

This does not distinguish the things  you're thinking of putting there from clicking around gene pages, term pages, other static pages, etc.

The implied sense of the word "browse" also clashes mildly with the "genome browser" sense.

I would rather use something more specifically informative. Assuming that we'd put these in the new menu:

- GO slim
- disease slim
- DNA binding sites
- Drug targets
- Curation statistics *
- Community curated publications *
- PomBase curated publications *

* these don't belong under "Genome status" but could appear under "About" as well as the new tab

"Summaries and inventories" feels too long, but would convey exactly what's in the list. Could maybe just go with one or the other, "summaries" or "inventories".

(tangent: add Unmapped genes to Genome status dropdown)

**Comment by ValWood** [comment]
I don't like to put these under "About". I only look under "about" for information about a resource, not for Data.

Browse is used in many contexts not just genome browsing (but to me these are similar), you are   discovering data, but not through searching. It's where you go when you don't know precisely what you are looking for.....and it is usually paired with search (Search or browse), so I don't have a problem with it.

I still prefer "Browse Data" or "Browsable lists"
Another option is "Explore data"

**Comment by mah11** [comment]
To clarify, I'm only proposing putting the ones with asterisks under About because, as curation stats, they are information about a resource - specifically, how much of the literature has been curated by the resource PomBase. They are not aspects of "genome status" in any way. And I specifically said they could go under both About and the yet-to-be-labeled new tab. (I've also edited the comment so the auto-formatting doesn't obscure my intent to flag a subset of the list.)

"Explore data" could apply to damn near everything at PomBase (or any other MOD).

**Comment by Antonialock** [comment]
I quite like summaries and inventories, and agree it is too long. 

"Inventories" perhaps overlaps with what you'd expect to find in the "downloads" section? Is 'summaries' descriptive enough on its own? (data summaries clearer but that's making it longer again).

**Comment by Antonialock** [comment]
and I guess DNA binding sites and drug targets aren't really summaries..

**Comment by Antonialock** [comment]
can we have a new section for the summaries, and merge the downloads section into inventories?

**Comment by ValWood** [comment]
Why is this one so hard???!?

Overviews
Data overviews
Data summaries

We could have a "Status and metrics" tab for all of the  asterisked ones and the existing metrics under "geneome status"  and "Data overviews" for the others?

**Comment by ValWood** [comment]
I don't think we should have anything in downloads except downloads.

**Comment by ValWood** [comment]
WE have another open discussion about this somewhere because I * know* we discussed it sometime since  Feb 2019...
consolidate...

**Comment by mah11** [comment]
This is the only ticket on this topic. We have talked about it in meetings/chats more recently than the last (but one) comment -- I think recently enough that Jacky was in on it -- but not added anything here because we didn't make a decision.

Was the latest plan for Val & Jacky to go through the existing menus and pages and come up with a set of suggestions for what should move where? Or did I dream that?

**Comment by ValWood** [comment]
Yes I think that was the plan. I  lost that note.

**Comment by ValWood** [comment]
From #1832


 I can't even find the link from here:
https://www.pombase.org/documentation

There's a link at the bottom of this page: https://www.pombase.org/datasets

And on this page: https://www.pombase.org/browse-curation (which I can't see a link to anywhere)

**Comment by ValWood** [comment]
@Antonialock suggested "inventories" and "catalogues"

**Comment by ValWood** [comment]
I always Google for these 2 lists. Not ideal !

**Comment by kimrutherford** [comment]
> I always Google for these 2 lists. Not ideal !

You could also type "drug" or "binding" in the documentation search:
https://www.pombase.org/documentation/docsearch
