### ISSUE TITLE
Various - transcription factor binding motif tracks 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#903]
mating type M-box	ACAAT

This is a very common motif, so it is hitting *everything*
The real region must be much longer I presume? If we could extend the motif to something more sensible we would exclude a lot of spurious hits.

Would need to be re-run, so we should see if any more could be refined.

@kimrutherford @Antonialock  how many hits to this are we generating?
Every gene I looked at seemed to have one....

**Comment by ValWood** [comment]
Is there a stricter consensus for the PCB?
Currently GNAACR


Most of the others appear to be quite specific

**Comment by ValWood** [comment]
@bahler may know about the PCB...

**Comment by kimrutherford** [comment]
> @kimrutherford @Antonialock how many hits to this are we generating?

I'm confused.  How do I count the hits?

> Would need to be re-run

What needs re-running?

> Is there a stricter consensus for the PCB?

What is a PCB?

**Comment by ValWood** [comment]
There should be some files somewhere with motifs in for these tracks

I can have a look if you tell me where the files live.

https://www.pombase.org/jbrowse/?loc=III%3A725765..736352&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features%2CConsensus%20transcription%20factor%20DNA%20binding%20motifs&highlight=

**Comment by ValWood** [comment]
A thought: If a motif occurs only once in the genome we shouldn't necessarily look for it, we just annotate it explicitly (although the results *could* be interesting, I suspect that the motif is not meaningful out of context, or the consensus is weak.

**Comment by kimrutherford** [comment]
> There should be some files somewhere with motifs in for these tracks

OK, I've got it now.  I didn't realise you were talking about JBrowse tracks.\

There's a BED file for the track.  There are 45439 feature with type "mating_type_M_box".  Is that what you were after?

**Comment by ValWood** [comment]
OK,
45439 feature with type "mating_type_M_box"

that is quite a lot of clutter for something that is presumbly only  functionally relevant in the mating type region......

**Comment by ValWood** [comment]
Yes I wasn't clear. I'm multi-tasking. It isn't working....

**Comment by ValWood** [comment]
Yes but just because it is described that way doesn't mean that we represent it like that.

 I suggest we manually annotate this and exclude from the track. Will remove  45438 unnecessary features.

**Comment by ValWood** [comment]
https://tinyurl.com/y7qg835a

These would be nice on individual tracks. One per motif, so you can combine how you want. There are so many difficult to consume. @bahler ? @Antonialock 

[ I'm putting  in this ticket because it would be done  in the next revisions of these tracks (there might be a set  of small  tweaks  to implement together]

**Comment by ValWood** [comment]
> PCB .. GNAACR

Yes but a more specific consensus might be described later...

**Comment by Antonialock** [comment]
I can't find a paper describing a stricter consensus for PCB

**Comment by ValWood** [comment]
1. The refined mat1-mc consensus will help a bit .to remove some false positives


2.
I also noticed a 4 bp  feature 
>I I:2796020..2796023 (+ strand) length=4
CAAT

for CCAAT box. Instead of 
CCAAT
Shouldn't this one be stricter?

3.
Can we make labels appear for these features. It is a bit impractical to need to click on them to see what they are.

4. 
I still struggle to find

**Comment by ValWood** [comment]
https://www.pombase.org/browse-curation/dna-binding-sites
did we decide where to put this to make it more prominent?

**Comment by ValWood** [comment]
It would be good to run this by @bahler lab next time you are in to see if we could improve.
Maybe ask about this before Kim regenerates the data...

**Comment by Antonialock** [comment]
Yes we announced this on 2018-05-27

We can ofc announce again if we regenerate...

> Would these be better on individual tracks? One per motif,

I think we could have one track with "all" + separate tracks one per motif?

**Comment by Antonialock** [comment]
ask for GFF

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/website/issues/1654
