### ISSUE TITLE
displaying features without coordinates

### ISSUE THREAD

**Issue by mah11** [pombase/website#904]
We now have some features in Chado that don't have sequence coordinates (https://github.com/pombase/pombase-chado/issues/110). The original use case was to put promoters in annotation extensions, even if the promoter sequence/site isn't known precisely. As far as I know, that's still the only way we've used them.

We never did get around to thinking about how to display those extensions on pombase pages, so I'm now opening this ticket for it. Right now, nothing is displayed (https://github.com/pombase/curation/issues/2145), which is suboptimal.

Curators (@Antonialock @ValWood) to discuss and decide how they should look, and then @kimrutherford  to implement.

**Comment by kimrutherford** [comment]
I've made a quick fix so it at least shows something while you decide how they should look.

![promoter-fix-1](https://user-images.githubusercontent.com/90474/44000162-33a006e2-9e6f-11e8-9f01-2c7f54ea3da0.png)

**Comment by mah11** [comment]
we may not be able to improve on that ;)

**Comment by ValWood** [comment]
yep that will do!
