### ISSUE TITLE
exact duplicates in annotations to term list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#91]
![duplicates](https://cloud.githubusercontent.com/assets/7359272/20576200/dc263948-b1b4-11e6-80d1-fd86c3fd807a.jpg)

**Comment by ValWood** [comment]
It isn't every term....

I can't remember which term I was looking at but you can see it from here
http://pombase2.aska.gen.nz/term/GO%3A0030989

**Comment by ValWood** [comment]
here http://pombase2.aska.gen.nz/term/GO%3A0010971
(only affects nod1)

**Comment by ValWood** [comment]
here the  deactivation of spindle checkpoint terms
http://pombase2.aska.gen.nz/term/GO%3A0045842

I can't see a pattern....

**Comment by kimrutherford** [comment]
Definitely a bug in the web code as the duplicates aren't in Chado.  My guess is that there are multiple paths through the ontology from those descendant terms to whatever term you were viewing.  I'll investigate.

**Comment by kimrutherford** [comment]
Should be fixed now.

**Comment by ValWood** [comment]
I think there are still exact duplicates (or for phenotype maybe)

![duplicate](https://cloud.githubusercontent.com/assets/7359272/20804801/330748aa-b7ec-11e6-9e84-fbf419873ae5.jpg)

forgot to note the gene page

**Comment by kimrutherford** [comment]
That example came from http://pombase2.bioinformatics.nz/gene/SPBC11B10.09

The alleles are identical too:

![screenshot 2016-12-07 09 32 22](https://cloud.githubusercontent.com/assets/90474/20942394/15413a56-bc60-11e6-8fdb-684a205131ca.png)

**Comment by ValWood** [comment]
We think this is 

	Cell growth assay	cdc2	cdc2-M63 (G227C)	Not assayed	high temperature	
cdc2	nmt::T167E (T167E)	Overexpression
Gould KL et al. (1998)	

(multi allele cdc2 but both alleles are cdc2)
