### ISSUE TITLE
Fix links to evidence code documentation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#911]
In the annotation tables the evidence code is a link to the documentation at geneontology.org
eg. ISM -> http://www.geneontology.org/page/ism-inferred-sequence-model

These used to work but now give "Access denied" - maybe the docs have moved?

**Comment by mah11** [comment]
Argh, yes, they have moved to the GO wiki: https://github.com/geneontology/go-site/issues/582

It seems the notion of redirects surfaced briefly, but it also seems that so far none have been implemented. I'll ask.

**Comment by kimrutherford** [comment]
I've changed the links except for these evidence codes which still have documentation on the main site.  Should I change those too?:

IMP - http://www.geneontology.org/page/imp-inferred-mutant-phenotype
IDA - http://www.geneontology.org/page/ida-inferred-direct-assay
IGI - http://www.geneontology.org/page/igi-inferred-genetic-interaction
IPI - http://www.geneontology.org/page/ipi-inferred-physical-interaction
EXP - http://www.geneontology.org/page/exp-inferred-experiment
IEP - http://www.geneontology.org/page/iep-inferred-expression-pattern
ISS - http://www.geneontology.org/page/iss-inferred-sequence-or-structural-similarity

**Comment by ValWood** [comment]
if the links work leave it as is I guess. If you changed its fine. We will link to the correct place when the GO ticket gets closed.

**Comment by kimrutherford** [comment]
I'll close this.  We can open a new issue when GO makes progress.
