### ISSUE TITLE
Improve tool-tip consistency

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#912]
We're using two different tool-tip styles and it annoys me.

![improve-tooltips-1](https://user-images.githubusercontent.com/90474/44298972-5f304200-a341-11e8-9777-50e470981941.png)
![improve-tooltips-2](https://user-images.githubusercontent.com/90474/44298975-622b3280-a341-11e8-9453-167d28de7738.png)

**Comment by mah11** [comment]
weird - I never see that dark background

reference mouseovers look like this (3 different browsers, all basically the same):

![screen shot 2018-08-20 at 10 41 11 am](https://user-images.githubusercontent.com/5196259/44333243-2d64cb80-a466-11e8-929e-e342bfd92146.png)

**Comment by ValWood** [comment]
I never saw the dark background either/

**Comment by kimrutherford** [comment]
> I never see that dark background

That's good.  It must be a Linux thing.

That's makes it even lower priority.

**Comment by kimrutherford** [comment]
I've fixed the reference tool tip.

There are a bunch of other tool-tips that don't look good (like the evidence code).  I'll fix those at some point. 

![ref-popover-1](https://user-images.githubusercontent.com/90474/44894131-6d6b5e80-ad42-11e8-9066-134f87750e32.png)

**Comment by kimrutherford** [comment]
> There are a bunch of other tool-tips that don't look good (like the evidence code).

I've now fixed the evidence code, the genes and the counts in the annotation tables.

**Comment by ValWood** [comment]
OK, close? I never saw a difference....

**Comment by kimrutherford** [comment]
There are still a few other places I'd like to fix so I'll leave this open.  I'm also improving the text as I go.

**Comment by ValWood** [comment]
I put this as future, only to get it off my lists of interest, but  you might want to do  since has "quick"

**Comment by kimrutherford** [comment]
> There are still a few other places I'd like to fix so I'll leave this open.

I now can't find the other places mentioned here so I'll close this issue.
