### ISSUE TITLE
Create a GO BP slim table from any result set

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#914]
~Would that be useful?  It's easy to implement.~

I've changed the issue title to match the other comments.

**Comment by ValWood** [comment]
This is timely. I was going to ask if we could have a way to slim user defined gene sets, because it seemed  that based on what we already have it would not be too difficult to implement.

. At present we point people to GO term mapper.  We may as well keep the traffic...users would then only need to use the GO term mapper for user-defined slims.

**Comment by ValWood** [comment]
I was thinking as a general option for any user defined list....would be really useful....
(we can 'kind of' do it with "quick little gene list tool" but on a very reduced slim).
I was thinking of a new button "GO- Slim this list"

**Comment by ValWood** [comment]
I think you must already have the code to do this , so it should be quick (you already do something more complicated with the QLT, where you do a slim filter with precedence)

This will just be a button to slim any list.
The output would look like this:


![slim](https://user-images.githubusercontent.com/7359272/49047929-e9096a00-f1d0-11e8-878a-6e2d4a67feb1.jpg)

it would be really really useful.

**Comment by kimrutherford** [comment]
I'll have a think about this. Maybe we can make it a little bit more general than just the BP slim. Perhaps we could do a similar table for any column in QuiLT. That might be a bit ambitious.

Maybe the table should have a download option. I don't like tables that aren't easy to download.

**Comment by ValWood** [comment]
Thoughts:

It won't be so  useful for some of the things in a quilt  (like presence or absence of TM domains, where you could just use quilt or a single query).

If we add lots of options it might detract from the "process slim", which is really useful and not possible to do easily.

We can definitely include a download option:
The "classical" slim output from the term mapper:
[final_S6_SP_slimTab.txt](https://github.com/pombase/website/files/2618660/final_S6_SP_slimTab.txt)
but we would want to add the "unknown" and "unslimmed" categories to the output. GO term mapper displays these in the output but they don't appear in the download output which is sub-optimal, and caused problems for unknowns paper, because we had to generate these lists retrospectively by subtracting  all the slimmed from the total!)

and later we can add for CC and MF for completion (we would need to define useful slims first and it isn't a high priority)

**Comment by kimrutherford** [comment]
> Since we want this feature anyway, and it says at the top that its easy I wondered if you could look at
> this one soon?

I think what you're after is different to the feature I thought was easy.  I was thinking of filtering the annotation tables on the gene pages like we do for evidence code.  Sorry my initial comment wasn't clear.

Creating a slim summary page from any gene list is a trickier job.

**Comment by ValWood** [comment]
Does the revised suggestion make sense to you?
If so could you give a time estimate for this instead ;)

**Comment by kimrutherford** [comment]
> If so could you give a time estimate for this instead ;)

I think probably a day, maybe two if it doesn't go well.

> Creating a slim summary page from any gene list is a trickier job.

I had a deeper look and I it's not as tricky as I thought.  All the information needed is available to the server in an easy to process table.

> This will just be a button to slim any list.

Would a new button beside "Visualise" make sense?  Can you suggest the text for the button label?

![results-slim-view-1](https://user-images.githubusercontent.com/90474/51731922-59edd500-20e1-11e9-8cc0-94aecd6bbdc3.png)

**Comment by ValWood** [comment]
"Slim List" ? @Antonialock

**Comment by Antonialock** [comment]
or just 'slim' to keep it short?

**Comment by ValWood** [comment]
can do, we can add a link to the slim documentation

**Comment by kimrutherford** [comment]
I'm quite near to finishing this.  I need to do a bit of tidying up in the morning.  I should be live by Thursday.  It needs a new overnight load to finish after I commit the changes.

In the case where there are no genes in a slim category (like "nitrogen cycle metabolic process" in the screenshot), should we show "0" for the gene count or just not show the row at all?  Or maybe sort the table by gene count?

![slim-results-table-1](https://user-images.githubusercontent.com/90474/52268555-b7670900-29a0-11e9-809f-b3e084ee6217.png)

Don't be alarmed by the odd count in the screenshot.  I queried for "exon_count(>6)"
:-)

**Comment by kimrutherford** [comment]
The "Slim" button is now live in pombase-dev:
  http://pombase-dev.bioinformatics.nz/term_single_allele_genotype_genes/FYPO:0000502

I think we should have a sentence at the top of the slim page describing what a slim is.  And probably something that gets shown when you mouse-over the "Slim" button.

Let me know what formatting (or other) changes you'd like before we release.

**Comment by ValWood** [comment]
We should use our boiler plate slim text:

A "GO slim" is a subset of the Gene Ontology terms selected for a specific purpose in interpreting large-scale data, such as functional annotation of a genome or high-throughput experimental results. PomBase uses a GO slim to provide a simple summary of S. pombe's biological capabilities by grouping gene products using broad classifiers.

I think we should tweak this slightly (in both places)

A "GO slim" is a subset of the Gene Ontology terms selected for a specific purpose in interpreting  THE FUNCTIONAL ANNOTATIONS IN AN ENTRIE ORGANISM,  OR A GENE PRODUCT LIST ~large-scale data, such as functional annotation of~ OFTEN DERIVED FROM A GENOME-WIDE EXPERIMENT ~genome or high-throughput experimental results~. PomBase ~uses~ HAS CREATED  a GO slim to provide a simple summary of S. pombe's biological capabilities by grouping gene products using broad BIOLOGICAL PROCESS classifiers.

**Comment by ValWood** [comment]
This will be seriously popular.....

**Comment by ValWood** [comment]
Only one addition...
Could you add these  classifiers:

Total slimmed gene products (protein and ncRNA): XXXX
Note that the counts in the "Genes" column are not additive, because many gene products are annotated to more than one term in the GO slim.
Protein coding genes not covered by the slim (XXX in total):
Gene products with biological process annotation, but not in any of the categories above: 2XX
Gene products with no biological process annotation: XXX

This data is often totally omitted from slims, which is crazy because these are the most interesting things....

**Comment by ValWood** [comment]
ANd from  user-defined slim, in addition to the text we should add a link to the "mother slim page"

View the "Full slim <<https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms>>"

**Comment by Antonialock** [comment]
I liked the idea of grouping the ones with ‘0’ at the bottom of the table. 

The ones with genes in the count I think I would still prefer alphabetical (rather than ordered by number of genes)

**Comment by kimrutherford** [comment]
> Protein coding genes not covered by the slim (XXX in total):

What is the XXX in "XXX in total" here?

**Comment by kimrutherford** [comment]
On pombase-dev, I've added:
  "Total slimmed gene products (protein and ncRNA): ..."
and
  "Protein coding genes not covered by the slim: ..."


These counts are going to take longer to implement because additional processing on the server is needed:

> Gene products with biological process annotation, but not in any of the categories above: 2XX
> Gene products with no biological process annotation: XXX

**Comment by kimrutherford** [comment]
> I liked the idea of grouping the ones with ‘0’ at the bottom of the table.

I've done that on pombase-dev so you can see if it makes sense.

**Comment by ValWood** [comment]
"The "in total" numbers are essentially the "genome" numbers for these slots, so the numbers on this page.

The wording doesn't make exact sense for the slim, but I ;think we want the numbers for the user set and the genome wide set if possible (would be nice, but doesn't need to happen immediately,)

This is also one of those things that can be a bit slow. The only service that performs slims that I know of (GO term mapper) takes a few minutes....

**Comment by ValWood** [comment]
This looks great. I think we can release.

We probably don't need to add genome totals, but instead, maybe we could add

"See full GO slim set (http://pombase-dev.bioinformatics.nz/browse-curation/fission-yeast-go-slim-terms) for more information" 
?

and the totals are here, one click away, if required

**Comment by kimrutherford** [comment]
> I think we should tweak this slightly

I've added the "what is a slim" text and the link to the full GO slim.  Is there anything else needed?

I don't like the current page layout.  Any suggestions?

**Comment by ValWood** [comment]
> I don't like the current page layout. Any suggestions?

I think it is difficult to improve on. Whatever we do it's a list. I don't think it's too bad? Maybe we will have a better idea later, but I would go with this.

**Comment by ValWood** [comment]
I just noticed that lots of stuff is not slimming that should, so I'm going to track down the GO issue causing this now....

**Comment by mah11** [comment]
>  lots of stuff is not slimming that should

here we go again!

**Comment by kimrutherford** [comment]
> Maybe we will have a better idea later, but I would go with this.

OK, we can tweak it later.

> I just noticed that lots of stuff is not slimming that should, so I'm going to track down the GO issue
> causing this now....

Oh dear.  Let me know if I can check anything.

**Comment by mah11** [comment]
it's probably https://github.com/geneontology/helpdesk/issues/192

**Comment by ValWood** [comment]
Yup, Ingrid beat me to it- I was distracted yesterday!

**Comment by kimrutherford** [comment]
> Maybe we will have a better idea later, but I would go with this.

It's ready to release once GO is fixed.

**Comment by ValWood** [comment]
Well you can release it anyway. The GO issue is already out there on our main site.

**Comment by kimrutherford** [comment]
> it's probably geneontology/helpdesk#192

I just downloaded the latest snapshot of go-basic.obo and I think the fix has got through the pipeline.  But unfortunately the nightly Chado load started before the new snapshot was ready so the slim problems will probably still be there today.

**Comment by kimrutherford** [comment]
Last night's load failed because the download of the new BioGRID release failed.  I've downloaded it manually so the load should be OK tonight.

**Comment by kimrutherford** [comment]
The load worked and the parents are correct again on this page: https://www.pombase.org/term/GO:0009231

Does that fix the GO slim problems you spotted?

It sounds like there are some other fixes in progress but I don't know if they are an issue for us:
https://github.com/geneontology/helpdesk/issues/192#issuecomment-466518304
https://github.com/geneontology/helpdesk/issues/192

**Comment by ValWood** [comment]
It is much improved. there are a few odd ones but they appear to be different issues. I will report them separately on the GO tracker.

**Comment by kimrutherford** [comment]
Great.  Thanks.

I'll close this then and we can open other issues for anything else.
