### ISSUE TITLE
Default section ordering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#92]
Maybe you have not ordered yet because you are going to make this configurable.

I think the default order should be the same as the current gene pages (although we might tweak slightly)

GO
- MF
- BP
- CC
phenotype
- single
- multi
-complementation
- target of (note this is missing from the current pages, it failed for this update)
- protein features
- sequence and genome features (eventually "transcript map" can also go in this section, but don't worry about this its low priority can even happen after we go live)
- expression
- misc
- genome something
- interactions
- warnings
- external refs ( maybe we will still have a section? even if we have links within specific sections)
- literature

did I miss any?

**Comment by kimrutherford** [comment]
Ah thanks, I was going to ask about that.

Currently it's in alphabetical order.  :-)

**Comment by ValWood** [comment]
Ah now, hold that thought.....ticket coming

**Comment by ValWood** [comment]
I'd love this one next....the current order is a bit annoying. Nothing else is ;)

**Comment by kimrutherford** [comment]
> did I miss any?

Orthologs?

**Comment by kimrutherford** [comment]
Also species_dist and taxonomic_conservation.

**Comment by kimrutherford** [comment]
Here's the current order:
  https://github.com/pombase/website/blob/c78ef7db0372ce5d58e792172fd8c3c6345d101f/frontend/src/app/config.ts#L34

**Comment by ValWood** [comment]
That's great for now, at least we have MF at the top. If we decide to tweak later we can.
It's looking amazing!

**Comment by kimrutherford** [comment]
Use the same order on the reference pages.
