### ISSUE TITLE
Hide or disable filter if there is nothing to filter

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#920]
This is a bad user experience:

![ext-filter-empty-1](https://user-images.githubusercontent.com/90474/44377490-1949c880-a551-11e8-85a9-454f2ddc3f53.png)

**Comment by ValWood** [comment]
Is this quick? If so I will bump it up? may as well close it...

**Comment by kimrutherford** [comment]
Yep. It should be a 30 minute job.

**Comment by kimrutherford** [comment]
> It should be a 30 minute job.

I've had a look and it's going to take longer than that.  I'm also now not sure it's a good idea.

So I'll close this as you suggested and come back to it later if it makes sense.
