### ISSUE TITLE
front page news resolving weirdly

### ISSUE THREAD

**Issue by ValWood** [pombase/website#921]
you may have fixed...

**Comment by kimrutherford** [comment]
I think I've fixed things.

There were two problems.  Links in Markdown can't contain round brackets without quoting or encoding them.  The easiest fix is to use HTML link syntax, so I did that.

It also looks like there was a cut and paste problem with the first link (the link text is "transcription start sites").  I've had a guess about what the link should be so I could release something.  Midori, could you replace it with the correct link when you get a chance?

**Comment by mah11** [comment]
OK, I swapped in a link with just the PomBase features and all Thodberg tracks.

I also edited the file to deploy reference-style links to make it more readable - https://daringfireball.net/projects/markdown/syntax#link

**Comment by kimrutherford** [comment]
> I also edited the file to deploy reference-style links to make it more readable

I didn't know about that syntax.  Handy!

I've updated the main site with your changes.
