### ISSUE TITLE
Display /db_xrefs from features

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#925]
These /dbxrefs are in Chado but need to be passed to the web site.

From Val:
> They support the "coordinates' of a feature so it would be nice longer term to make them a pop
> up somehow on genomic location
> I, | 3086472-3086930 (459nt)

Example from chromosome1.contig:

```
FT   ncRNA           complement(40916..41770)
FT                   /systematic_id="SPNCRNA.601"
FT                   /product="intergenic RNA (predicted)"
FT                   /db_xref="PMID:21511999"
```

**Comment by kimrutherford** [comment]
It's now improved so that the publications from the feature /db_xrefs appear in the literature section.

**Comment by kimrutherford** [comment]
> They support the "coordinates' of a feature so it would be nice longer term to make them a pop
> up somehow on genomic location
> I, | 3086472-3086930 (459nt)

We can do that now that the feature db_xrefs are available to the web code.

Could we have a link beside or underneath the location with text like "Source ..." that's a link to the reference?  And/or we could have a popup when you hover over "Source ..."

**Comment by ValWood** [comment]
I like "Source ..."

**Comment by kimrutherford** [comment]
> I like "Source ..."

OK, I'll try that and we can see how it looks.

**Comment by kimrutherford** [comment]
I've added the "Source ..." link:
https://www.pombase.org/gene/SPNCRNA.57

but I wasn't sure how it should be formatted if there are two db_xrefs.  So currently it looks different.  There aren't that many with more than one ref so maybe it doesn't matter.  Here's an example:
https://www.pombase.org/gene/SPNCRNA.1187

Let me know what you think.

**Comment by ValWood** [comment]
I think its fine. we can always rethink when we rearrange top matter later. Is it possible to do a single pop up with 2 independent links?

**Comment by kimrutherford** [comment]
> Is it possible to do a single pop up with 2 independent links?

Yep, but that would have taken longer.  :-)

**Comment by kimrutherford** [comment]
I'm going to close this.  We can open new issues for changes.
