### ISSUE TITLE
new frontpage rotation for swaffer

### ISSUE THREAD

**Issue by ValWood** [pombase/website#927]
I made a different image as it is difficut to get anything from the existing one as it is quite small. This crops some  graphs, it is more of a 'teaser' but it gives a better feeling  what the datast is about.
It is in the front page rotations, 'swaffer_new'

**Comment by kimrutherford** [comment]
So change the image but keep everything else the same?

**Comment by ValWood** [comment]
yep

**Comment by kimrutherford** [comment]
It's updated now if you re-load.
