### ISSUE TITLE
filter for annotation tables, e.g. phenotypes  slim term/ term/ allele/ allele type etc

### ISSUE THREAD

**Issue by ValWood** [pombase/website#93]
The default ordering within sections is currently alphabetical.

This works pretty well (although eventually we would like  to be able to sort on other columns, particularly "allele" in the phenotype section, for example.

**Comment by ValWood** [comment]
- [ ] order GO   terms alphabetically
- [ ] order phenotype terms alphabetically

**Comment by ValWood** [comment]
alphabetical sorting is done.
Need to be able to  sort on columns longer term

**Comment by ValWood** [comment]
We decided just that   table sorting might not  be the optimal way to do this because 
a) if you  sort on genotype  you would need to duplicate many terms
b) other...

Anyway long discussion, decided that  sensible filtering and toggling at the top of the section is the way forward to allow users to quickly reduce the number of phenotypes to look at to a more relevant subset.

We will  devise "phenotype slim" for this, and get community input

Need to be able to filter phenotypes by:

i)  term  to see  phenotypes of a specific type (classes to be decided)
normal process, abnormal process, abolished process, vegetative phenotype, meiotic phenotype, drug sensitivity, morphology phenotype, altered activity, altered localization, altered modification, cell cycle phenotype, other specific processes.....

ii) allele type (I guess for multigene this will be a fudge?)
to separate  deletion, amino acid change, wt

iii) genotype name (to see all of the phenotypes for a particular genotype)

iv) condition (this one will be tricky because we don't always record a condition...some thought required if included here).

**Comment by ValWood** [comment]
Output should filter all page sections under separate headers.

**Comment by kimrutherford** [comment]
>  term to see phenotypes of a specific type (classes to be decided)

The classes need discussion.

> allele type (I guess for multigene this will be a fudge?)

What sort of fudge were you thinking of?

> genotype name (to see all of the phenotypes for a particular genotype)

Is this necessary since you can click on a genotype to go to the genotype details page?

**Comment by ValWood** [comment]
Suggested classes for filtering/display are also mentioned in:
https://github.com/pombase/website/issues/80
We might only use them in the "summary view" at the top of the page....not sure...needs discussion...

**Comment by ValWood** [comment]
> ii) allele type (I guess for multigene this will be a fudge?)

This might not be necessary if single and multi gene phenotypes are separate. Although I don't know how we describe allele type for multi-gene,  because it can often be a combination of types...
I 'm not sure what it might be useful for users to filter on  for multigene phenotypes (things like effects gain of function, loss of function might be more useful but we don't record that.......)

**Comment by ValWood** [comment]
> genotype name (to see all of the phenotypes for a particular genotype)
Is this necessary since you can click on a genotype to go to the genotype details page?

you're right, that might not be required as a filtering option...

**Comment by ValWood** [comment]
Superseded by
https://github.com/pombase/website/issues/187
