### ISSUE TITLE
use RNA_Central- PomBase mapping file to create external DB-refs on RNA pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#931]
https://github.com/RNAcentral/rnacentral-webcode/issues/417

ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/pombase.tsv

**Comment by kimrutherford** [comment]
I've finally got around to adding a link to RNAcentral from the RNA pages.  It's configured in the "external_gene_references" section of the main website config file.  It currently look like this.  Let me know if you'd like any changes.

![rnacentral-link-1](https://user-images.githubusercontent.com/90474/111924524-f8cbbb80-8b09-11eb-86e6-1d201ec54880.png)

**Comment by kimrutherford** [comment]
Sorry, forgot to say that this change won't be visible until the morning.

**Comment by ValWood** [comment]
Great!
