### ISSUE TITLE
query about file differences

### ISSUE THREAD

**Issue by ValWood** [pombase/website#932]
It seems that we are not currently providing gff files for
i) the mating type region contig
ii) the subtelomeric contig

We should export these too .

![pombe_screenshot](https://user-images.githubusercontent.com/7359272/44865825-4e55c980-ac7b-11e8-8d7a-0128676af252.png)

**Comment by ValWood** [comment]
https://pomrt.gen.private.cam.ac.uk/rt/Ticket/Display.html?id=6421

**Comment by kimrutherford** [comment]
The GFF files are now generated nightly:
  ftp://ftp.pombase.org/nightly_update/gff/

I need to fix things so that the directory you found is updated automatically:
  ftp://ftp.pombase.org/pombe/genome_sequence_and_features/gff3/

**Comment by kimrutherford** [comment]
The current FTP site directory has the gff3 files split by chromosome:
  ftp://ftp.pombase.org/pombe/genome_sequence_and_features/gff3

Is that useful?  The current nightly load has a file with everything and forward and reverse strand files
  ftp://ftp.pombase.org/nightly_update/gff/

**Comment by ValWood** [comment]
I think people like the individual chromosomes for  Artemis loading etc.
I find it annoying if I want to do something by chromosome and I need to split them up because it isn't possible  using grep because chromosome is just a number.....

**Comment by kimrutherford** [comment]
OK, no problem.  The current files were made for loading into JBrowse.  I'll add per-chromosome files too.

**Comment by ValWood** [comment]
Yeah, I think bench biologist will appreciate separate files. They are likely want to do manipulations involving spreadsheets etc. They will inevitably want to split them up anyway.

**Comment by kimrutherford** [comment]
The nightly load now generates GFF3 files per chromosome.  I'll check the FTP site in the morning to make sure it all got through.

**Comment by kimrutherford** [comment]
I've checked the FTP site and everything is in the right place after the nightly load.
