### ISSUE TITLE
text too wide

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#933]
paragraph 3 on this page is too wide and is hidden by the menu
https://www.pombase.org/faq

<img width="509" alt="screen shot 2018-08-31 at 08 35 15" src="https://user-images.githubusercontent.com/12727506/44899155-ec3ba980-acf8-11e8-865a-4712431f1116.png">

**Comment by Antonialock** [comment]
I can't find where to edit this? I've found the stuff for actual FAQ items or sub pages but not this 'top level' page?

**Comment by Antonialock** [comment]
No, it is the text "PomBase is funded by the Wellcome trust.."

**Comment by kimrutherford** [comment]
> No, it is the text "PomBase is funded by the Wellcome trust.."

It's at the bottom of this page:
https://github.com/pombase/website/blob/master/frontend/src/app/app.component.html

**Comment by kimrutherford** [comment]
This should be fixed now.  Let me know if you still have problems.

**Comment by Antonialock** [comment]
yep looks good
