### ISSUE TITLE
(intron) files to update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#934]
Re:

Ticket URL: https://pomrt.gen.private.cam.ac.uk/rt/Ticket/Display.html?id=6402
Dear Dr. Harris,
Thank you very much for resolving this issue. We are now able to access the intron data from Pombase. This data is very useful to us in our day to day experiments. 

Thanks again for your support.

--

I don't think we  talked about updating these yet! I forgot about them !
(but they won't change very much)

ftp://ftp.pombase.org/pombe/genome_sequence_and_features/feature_sequences/

**Comment by kimrutherford** [comment]
Turns out I did most of the work for this ages ago.  The nightly load already writes most of the files we need:
  ftp://ftp.pombase.org/nightly_update/fasta/feature_sequences/

I've just update the nightly script to copy the sequences to the main FTP location:
  ftp://ftp.pombase.org/pombe/genome_sequence_and_features/feature_sequences/

The change wasn't in time for today's load.  It will be visible on Tuesday morning.

The nightly load doesn't write out introns yet.  Should the introns.fa file contain all the introns or just the introns in the coding region?

**Comment by kimrutherford** [comment]
> Should the introns.fa file contain all the introns or just the introns in the coding region?

I've added the code to write the introns file, including all introns.  It's easy to change if that's not what we need.

**Comment by ValWood** [comment]
hmm, maybe we should do both. Historically we only did introns in CDS and this is what most people are concerned with as they affect the coding sequence.

More recently we have added introns in UTRs but they are very incomplete.

One day we need to look at this

"Our data reveal hundreds of new introns in S. pombe and numerous others that were previously misannotated."
https://www.ncbi.nlm.nih.gov/pubmed/29727662

this sounds alarmist, but I suspect that most of the "hundreds of new" are in coding regionds.

The quickest way to assess these would be to host all of the  identified introns as a track @Antonialock . I can then quickly whizz through the genome in a couple of hours and do any necessary fixes.

**Comment by ValWood** [comment]
So I think CDS introns is currently the most useful as it is "complete".

**Comment by kimrutherford** [comment]
> hmm, maybe we should do both.

No problem.  Would it make sense to have:

 - a file of CDS introns and a separate file of UTR introns

or:

 - a file of all (CDS+UTR) introns and a separate file with just the CDS introns

?

**Comment by kimrutherford** [comment]
> So I think CDS introns is currently the most useful as it is "complete".

OK, I'll leave out the UTR introns for now.  I think it makes sense to rename the file from "introns.fa" to "cds-introns.fa".

**Comment by ValWood** [comment]
yes, rename the file and we can add the other one later.
I''ll open a new ticket to host the intron data

**Comment by kimrutherford** [comment]
>  I think it makes sense to rename the file from "introns.fa" to "cds-introns.fa".

I think I'll come back to this tomorrow.  We already have a file called "cds+introns.fa" so I think "cds-introns.fa" isn't right.

**Comment by kimrutherford** [comment]
I've called the file "introns_within_cds.fa" for now so it's clear.  We might need to come back at some point and rethink all the sequence file names.

ftp://ftp.pombase.org/pombe/genome_sequence_and_features/feature_sequences/
