### ISSUE TITLE
pombelist update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#935]
update links to pombe mailing list everywhere on website  from

https://listserver.ebi.ac.uk/mailman/admin/pombelist/members
to
https://lists.cam.ac.uk/mailman/admin/ucam-pombelist/members

and address from pombase@ebi.ac.uk to pombelist@pombase.org

@Antonialock  do you mention in NAR, if so please update

**Comment by kimrutherford** [comment]
There are some links in the documentation to specific messages like:
  http://listserver.ebi.ac.uk/pipermail/pombelist/2007/000128.html
Should we just leave those for now?

I'll fix the other links.

**Comment by ValWood** [comment]
I think we should do the news item now. I have no idea how long the archive will take.

**Comment by kimrutherford** [comment]
I've added a news item.  You can edit it here: https://github.com/pombase/website/blob/master/frontend/src/docs/news/2018-08-31-mailing-list-move-to-cam.md
or I'm happy to make changes.

It you edit it, let me know and I'll re-release the site.

**Comment by ValWood** [comment]
@mah11  any documentation to fix
@Antonialock  did the correct URL go in NAR paper?

If so @kimrutherford  can this one close?

**Comment by kimrutherford** [comment]
> If so @kimrutherford can this one close?

I think it's OK to close once Midori and Antonia give the go ahead.

**Comment by mah11** [comment]
> @mah11 any documentation to fix

I committed a change to one FAQ. All other pombelist links are in old news, so may not be worth changing.

**Comment by kimrutherford** [comment]
> I committed a change to one FAQ.

I just updated the site with that FAQ change.

**Comment by Antonialock** [comment]
Which URL?

**Comment by Antonialock** [comment]
if you mean email address then it is not mentioned in the update paper.

**Comment by ValWood** [comment]
OK.
