### ISSUE TITLE
host intron data on a track

### ISSUE THREAD

**Issue by ValWood** [pombase/website#936]
@Antonialock 
https://www.ncbi.nlm.nih.gov/pubmed/29727662

@kimrutherford 
Once done,  compare to existing gff? (report of differences)

Val to fix any anomalies (reannotate features)

@mah11  to list gene structure alterations

**Comment by ValWood** [comment]
Yes, it would probably, but I think it should be hosted as a  browser track anyway.

We decided that we were going to ditch the manual curation of UTRs  and let people decide for themselves based on  the transcriptome profiles (because they are so heterogeneous and variable).

So people will need the track to see the UTR introns.

I don't think we ever followed up with  the procedure to drop the UTRs. I need to make a ticket about that.

I only really want to assess the gene structures of the ones reported in CDS.  The paper may even provide a list of these that I can work through. I didn't look yet.

**Comment by ValWood** [comment]
Yes I'll make a list. Not soon ;)

**Comment by Antonialock** [comment]
what sort of tracks do you want for this? 

branch points?
anything else?

Looking at the publication we'll need to ask them for the tracks
 https://ac.els-cdn.com/S0092867418303945/1-s2.0-S0092867418303945-main.pdf?_tid=1acf3485-824c-44c9-b90a-4432becc5ffb&acdnat=1538664758_69db6f6c634910605f15f3b7f28ac690

**Comment by kimrutherford** [comment]
> @kimrutherford what is the preferred file format for basic features (bed?)

If the features are just start, end, name and maybe a score, BED would be good.

**Comment by ValWood** [comment]
> better reach to intron data.

from user survey column BQ

**Comment by ValWood** [comment]
were these authors ever contacted? if not is 
https://github.com/pombase/website/issues/1441 an accurate summary?
