### ISSUE TITLE
social media links menu

### ISSUE THREAD

**Issue by ValWood** [pombase/website#937]
Is currently only at the top of the home page, but a lot of people don't go here.

Add to the top of every page?

Also, swap  "contact curators" so that it is at the right maybe?  at present it  looks like you click on the pombe list icon to contact curators.

**Comment by kimrutherford** [comment]
I'm keen on both those suggestions.  I'll make the change locally and make a screen shot.

**Comment by kimrutherford** [comment]
I think it looks OK:

![social-icons-gene-page-1](https://user-images.githubusercontent.com/90474/45082339-3edbf200-b14d-11e8-8a98-60a8616748a9.png)

**Comment by ValWood** [comment]
yep.

**Comment by kimrutherford** [comment]
The change caused some display problems on some pages but it's fixed and deployed now.
