### ISSUE TITLE
is it possible to allow sorting here on systemtic ID?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#938]
https://www.pombase.org/status/priority-unstudied-genes

If it is really really quick. I had a situation last night where it would have been useful, because I was trying to look at expression profiles under different conditions, one chromosome at a time.

Close if it would take more than 5 mins though, it isn't important.

**Comment by kimrutherford** [comment]
It took 5 minutes.  :-)

If you reload you'll be able to sort by systematic ID.

**Comment by ValWood** [comment]
great thanks, thought that would be a quick one!
