### ISSUE TITLE
Hiding annotation redundancy   (multiple data types)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#94]
Once the annotation  is ordered alphabetically , you will see that there is a lot of redundancy.

We shield this from the user in the "summary view"

So have a look here

 http://www.pombase.org/spombe/result/SPBC11B10.09#go-molecular_function

In the summary view  we only show the "biology"
term, extension, count

In the full view we show all the meta-data
term ID/ evidence/ with-from / reference

Note:  Mark had a fudge to make the "with" of a GO protein binding annotation emulate a "has_substrate" extension  but with a "binds" rlation (because for physical interactions, the binding partner is biologically relevant, for genetic interactions it is not required to interpret the term 'biologically').
This could happen within chado rather than on the gene pages if you prefer (can discuss)

This way we present the user with  the most biologically relevant immediate view, and allows us to "collapse" annotation which is provided identically from multiple PMIDs.

- [ ] The FYPO collapsing is possibly a little more complicated. It might be easiest if @mah11  makes tickets which either link to the old jira tickets if these are clear, or pulls out the relevant parts.

- [ ] There is also  stuff related to extension ordering and  display. I'll ticket this tomorrow this is to remind me.

**Comment by mah11** [comment]
The current FYPO displays were described in Jira PB-1836 and its subtasks (https://www.ebi.ac.uk/panda/jira/browse/PB-1836). The "summary" GO display is in PB-1854. I'll let Kim shout if he has specific questions that I may be able to address.

Extension ordering stuff is in #64.

**Comment by ValWood** [comment]
I think we emulate the old site?
and future additional stuff is described here:
https://github.com/pombase/website/issues/45

if not we will open new tickets with precise instructions
