### ISSUE TITLE
query builder

### ISSUE THREAD

**Issue by ValWood** [pombase/website#945]
does not seem to work for GO, phenotype today?
dev & www

**Comment by ValWood** [comment]
it could be my connection though....

**Comment by ValWood** [comment]
no, I think ontology searching is broken...

**Comment by kimrutherford** [comment]
I temporarily fixed things by switching back to yesterday's version.  I'll re-release today's data when I've fixed things.

**Comment by kimrutherford** [comment]
All fixed.  Sorry about that.
