### ISSUE TITLE
Missing Ensembl images for SPAC110.06

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#946]
https://www.pombase.org/gene/SPAC110.06

It's odd.  I've never noticed a missing image before.

**Comment by ValWood** [comment]
SPAC110.06 | identified by ribosome profiling (PMID:24929437) | July 2014
-- | -- | --
SPAPB1A11.06 | previously SPNCRNA.31 (PMID:26494834) | November 2015
SPAC110.06 | PMID:26494834 | November 2015

https://www.pombase.org/status/new-and-removed-genes

Implies Ensembl is using pre 2015 data.....
I will let Nishadi known....

**Comment by ValWood** [comment]
not sure why we have 2 enrtries, we probably did not add when we originally thought that we did...

**Comment by kimrutherford** [comment]
I didn't say it above but we use copies of the Ensembl inline browser images that I grabbed from the Ensembl version of pombase.org ages ago, probably nearly 2 years.

I thought I had checked that we had an image for every gene but I clearly didn't.

**Comment by kimrutherford** [comment]
I've checked and there are a few genes that we don't have images for.  I've changed the web code to handle it better and it now doesn't show the broken image icon for those cases.  This will be fixed when #698 is done.

Here's the list of genes with missing images:

  - SPNCRNA.1701
  - SPAC110.06
  - SPAPB1A11.06
  - SPNCRNA.1705
  - SPNCRNA.1703
  - SPNCRNA.1702
  - SPNCRNA.1704
  - SPNCRNA.1698
  - SPNCRNA.1712
  - SPNCRNA.1709
  - SPNCRNA.1708
  - SPNCRNA.1707
  - SPCC4G3.20
  - SPNCRNA.1706
  - SPNCRNA.1711
  - SPNCRNA.1710
  - SPCC1840.13
  - SPMITNCRNA.01
