### ISSUE TITLE
separate "cell" and "population" phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#95]
I'll let @mah11  describe how to do that. Again the old jira ticket might suffice.

**Comment by kimrutherford** [comment]
> If the FYPO term has an is_a path to FYPO:0000002, it goes under "cell phenotypes". If the
> term has an is_a path to FYPO:0000003, it goes under "population phenotypes". That's it.

OK, thanks.  I'll make that change.

**Comment by kimrutherford** [comment]
The phenotype section is now split into cell and population sections.
