### ISSUE TITLE
Better publication example

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#951]
It's a small thing but I think it would be nice to have an example publication with more datatypes.  The current one just has "GO molecular function" and "Modification".

Perhaps a publication that has phenotype annotations and/or interactions?

**Comment by ValWood** [comment]
I think we should change this sometimes anyway 
one option
https://www.pombase.org/reference/PMID:29167352

btw  the meadows research spotlight in the archive 
https://www.pombase.org/archive/spotlight
links to the nurse proteomics paper

another option
https://www.pombase.org/reference/PMID:29514920

**Comment by kimrutherford** [comment]
> btw the meadows research spotlight in the archive
> links to the nurse proteomics paper

Whoops.  Is this the right paper?:
https://www.pombase.org/reference/PMID:28178520

**Comment by ValWood** [comment]
Yes that's the correct one.
v

**Comment by kimrutherford** [comment]
OK, thanks.  The link is correct now.

**Comment by kimrutherford** [comment]
I've updated the example publication.
