### ISSUE TITLE
PMID:30148840 for front page rotation?

### ISSUE THREAD

**Issue by mah11** [pombase/website#954]
PMID:30148840 https://curation.pombase.org/pombe/curs/54db84e4ca91c654

This looks like a contender for the research spotlight because it:

- has a slightly unusual topic;
- has a human health angle;
- uses AnGeLi; 
- _does a phenotype cluster analysis_ (woohoo!)
- has Canto curation from one of our best contributors

The only downsides are minor:

- It has no pretty pictures; the least-boring graphic is the YABYA (yet another blue & yellow array) in Figure 1.
- The only annotation types are phenotype and genetic interaction.

@ValWood @Antonialock - If you agree that the cons don't outweigh the pros, I can email Paul, and do the config etc. to get it ready.

**Comment by ValWood** [comment]
Yes for sure! I have been hoping we can feature something of Paul's soon....
great to see phenotype analysis!

**Comment by ValWood** [comment]
I think the array will look OK....

**Comment by mah11** [comment]
Cool. I emailed Paul and got an image ready.

**Comment by mah11** [comment]
PR says it's a "lovely idea", so I've added the config. @kimrutherford, shout if I've botched anything.

**Comment by kimrutherford** [comment]
Thanks.  That's live now.

**Comment by ValWood** [comment]
or more attention grabbing

"chromate toxicogenomic profile  closely resembles the cancer  drug camptothecin"

;)
