### ISSUE TITLE
Gene Page Specification Section 4 , Protein domains and features data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#96]
Currently

protein family display
![this could be consdensed into](https://cloud.githubusercontent.com/assets/7359272/20600533/0e8bbe34-b24c-11e6-9bbe-53969b08752b.jpg)

followed by
- curated family group (I can ditch some of these, will explain later)
- sequence ontology protein features

Protein Properties
- Ave. residue weight	115.69 Da
- Charge	4.50
- Codon Adaptation Index	0.43
- Isoelectric point	7.68
- Molecular weight	34.36 kDa
- Number of residues	297

- [x] all calculated,  do we store these in chado, or generate post chado?

**Comment by ValWood** [comment]
- [ ] We will need to run interPRO scan locally on the fasta protein database
- [ ]  Find out if InterPRO have a web service for image map generation
(Or Kim do you want to generate, if we have all of the coordinate...its only boxes on a scale bar ;)

**Comment by ValWood** [comment]
- [ ]  arrange lowest to highest number of hits. This is more logical is it moves from sub-family to family to superfamily information

**Comment by ValWood** [comment]
Section done, piece of piss ;)

**Comment by ValWood** [comment]
- [ ] Longer term we  want to display protein modifications and  region specific phenotypes as decorations on the  protein feature map

**Comment by ValWood** [comment]
style wise this looks quit nice:

![style](https://cloud.githubusercontent.com/assets/7359272/20605839/410eb424-b265-11e6-980f-4adb8f739d1a.jpg)

**Comment by ValWood** [comment]
this might do....
http://www.biojs.io/d/feature-viewer

**Comment by ValWood** [comment]
This is very nice.
So, you can click on a variant, modification, and the region is highlighted in the sequence.

![nextprot](https://cloud.githubusercontent.com/assets/7359272/20640045/d8406fb4-b3cc-11e6-847d-35a040d0ab0d.jpg)

**Comment by ValWood** [comment]
I think we can punt the domain section and just add a simple "link" to the old site as a place holder.
http://www.pombase.org/spombe/result/SPBC11B10.09#translation

The domains will not change much over a 6 month period which will give us time to really think about the display options and viewers for protein features, mutants, modifications etc and enable you to do this part as a focussed project (phase II).

**Comment by ValWood** [comment]
One next call I'll show you all what I like about this and we can  compare to 
https://github.com/pombase/website/issues/17 (if its about the same thing).

Then make a list of what we would like ideally...

**Comment by ValWood** [comment]
- [ ]  For now emulate current site grabbing image from Ensembl fungi
- [ ]  Further discussion required about future viewers (after new website)

**Comment by mah11** [comment]
I put some info on UniProt's "ProtVista" thingy in ticket #17. Example: [human p53](http://www.uniprot.org/uniprot/P04637#showFeaturesViewer)

**Comment by ValWood** [comment]
I made a new ticket for future stuff
https://github.com/pombase/website/issues/143

**Comment by ValWood** [comment]
I made a new ticket for future stuff and removed from this ticket.
https://github.com/pombase/website/issues/143

**Comment by ValWood** [comment]
I have removed_not_required to go live from this. However, I realise the sequence related stuff requires quite a bit of work,  so if it isn't done  before the conference it's  absolutely fine. 

We can just add a temporary link to  the old site in the section so people know that it is coming.... and the protein families won't change for ages anyway.....

**Comment by kimrutherford** [comment]
> However, I realise the sequence related stuff requires quite a bit of work

Some of the work is now done so the Protein Properties bit would be quite easy to implement now.

Note to self: https://github.com/pombase/pombase-chado/commit/4f9460a06d605d03dd6d025b5642afd7ab66b050

**Comment by ValWood** [comment]
great! we can put that in the basic info  because the gap looks odd. Can worry about all of the other sequence related stuff for "stage II"

**Comment by kimrutherford** [comment]
> we can put that in the basic info

Which bit do you mean by basic info?

For the "Charge" is that the charge at neutral pH?

**Comment by kimrutherford** [comment]
I've added code to put the protein properties in Chado for the next load.  Once they're in Chado I'll add them to the gene page.

**Comment by ValWood** [comment]
>Which bit do you mean by basic info?

Product size	297 aa, 34.36 kDa

You have done this already.

all of the other "protein related info can go in the "protein features " section

**Comment by ValWood** [comment]
>For the "Charge" is that the charge at neutral pH?

I believe so.

**Comment by kimrutherford** [comment]
The protein properties are ready to go.  Just as a check: in PomBase v1 the properties are in the "Protein Features" section.  In V2 the "Protein features" section is quite different.  Should the protein properties go in that section, or somewhere else?

**Comment by kimrutherford** [comment]
> Should the protein properties go in that section, or somewhere else?

I went ahead and put the protein properties in that section just to get them on the page.  It's easy to move later.

**Comment by ValWood** [comment]
Yep thats fine. The protein features section is different because the domain data isn't there yet...

**Comment by kimrutherford** [comment]
I've added the protein feature images from the PomBase v1 pages.  If you click the image it goes to the Ensembl browser.

**Comment by ValWood** [comment]
The links should go to Ensembl Genomes so that they work when P1 disappears.

**Comment by kimrutherford** [comment]
> The links should go to Ensembl Genomes so that they work when P1 disappears.

I've fixed the links.

**Comment by kimrutherford** [comment]
Val asked InterPro and they suggested downloading their XML file containing all the matches.

I've done that in this directory on oliver0:

    /var/pomcur/sources/interpro/

with this command:

    wget -N ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/match_complete.xml.gz

We'll write a small program to parse out what we need each time InterPro has an update.

Note to self - query UniProt IDs from Chado:

    select value from featureprop p join cvterm t on p.type_id = t.cvterm_id
       where name = 'uniprot_identifier';

**Comment by kimrutherford** [comment]
I've written a program that gets the UniProt identifiers from a Chado database then parses the InterPro match_complete.xml.gz looking for those proteins.  The results are written to an easy to read JSON file for the web code.

https://github.com/pombase/pombase-interpro

I'm running it now.  The next step is to add that data to the gene pages.

**Comment by ValWood** [comment]
You are soooo amazing....

**Comment by kimrutherford** [comment]
I've added a table to the gene pages containing the raw data from the InterPro match_complete.xml.gz
file.  It's missing headings and links from IDs to Pfam, InterPro etc.  It's also missing the counts column.

I'll fix all that next.

The PomBase v1 gene pages have TMHMM data but that's not in the InterPro file.  Is showing that data high priority for v2?  If so I'll work out how to get it from somewhere else.

**Comment by kimrutherford** [comment]
> The PomBase v1 gene pages have TMHMM data but that's not in the InterPro file

Same with coiled-coils.

**Comment by kimrutherford** [comment]
I've added headers and most of the ID links are working.

I've added a special case in the code for MobiDB as it's not in the GO.xrf_abbs file.

And I've had to add a special case for Gene3D because the URL in the GO.xrf_abbs file seems to be out of date.   Where should I report that?

The DB names in the "DB name" column are currently the internal ID from the InterPro data and are all UPPERCASE.  I'll make them more user friendly.

**Comment by ValWood** [comment]
phew, that was *fast*

 GENE3D is a bit  (I don't fully understand what they are trying to display here, or how people would use it). Actually I think we should omit it. 
we can always add if people ask for it (which is highly unlikely to happen).
Pfam would then be at the top anyway....

Yes we need to use the correct capitaization.

I have never heard of MobiDB 

It's nice to see all the Panther links working. These often don't work (I notice they were broken at SGD last week).
Some do have a "family name" in panther
Family:	CELL DIVISION PROTEIN KINASE (PTHR24056)
but that must not make it through to the XML. I will report  it if that is the case.
(Panther is really useful because it provides the easiest way to see the taxonomic distribution of a domain and  the genes assigned to the sub family

CDD is new to me too.

**Comment by ValWood** [comment]
cdc2 page has

http://www.pantherdb.org/panther/family.do?clsAccession=PTHR24056
which lists fission yeast members

and
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR24056:SF313
which does not.

So if that is in the pombe XML we should report that to InterPro

**Comment by ValWood** [comment]
We don't *absolutely*  need TMMS to go live so we can open a new ticket for that and keep it on the back burner.

**Comment by ValWood** [comment]
- [ ]  This section need a "count" column. Maybe the most useful way to organise the table is by count (lowest to highest). This would  loosley organize from "orthologous  protein family"  to "protein family or domain" to "super family". All are useful in different contexts  but for protein families I often use the count to determine which resource I would use.

For instance, if there is no information available from the orthologous group, i would move outwards to see if I could get a  functional clue  from the  broader families.

**Comment by ValWood** [comment]
We should ask why some things in the XML do not have an InterPRO ID too, I have always wondered why....

**Comment by ValWood** [comment]
- [ ]  you have added  generic InterPro links too. Thats useful.
A nice feature on this page is the "residue" annotation. We might be able to do something with that data later.

InterPro is pretty damn good.....

**Comment by kimrutherford** [comment]
> Some do have a "family name" in panther
> Family: CELL DIVISION PROTEIN KINASE (PTHR24056)
> but that must not make it through to the XML. 

Yep, I check a few and for Panther the "name" attribute in the XML is always just the ID.  For other sources the name is more useful.

**Comment by kimrutherford** [comment]
> Actually I think we should omit it.

I've removed the Gene3D data.

**Comment by ValWood** [comment]
Yeah I have been aware of this for a while. I think its because the Panther entries are not fully integrated into InterPro. That however would not prevent the correct description being imported...

**Comment by kimrutherford** [comment]
I've added the counts column and the counts are links to the list of genes with the InterPro domain.  I haven't done any sorting yet.

**Comment by kimrutherford** [comment]
> Maybe the most useful way to organise the table is by count (lowest to highest)

Let me know if I should go ahead and do that.

> Yes we need to use the correct capitaization.

The displayed database names are now from the GO.xrf_abbs file.  They aren't all obvious (eg. "CDD", "PIRSF") but I've made the database name into a link so the user can always click through to find out more.

**Comment by ValWood** [comment]
> The displayed database names are now from the GO.xrf_abbs file. They aren't all obvious (eg. "CDD", "PIRSF") but I've made the database name into a link so the user can always click through to find out more.

Thats weird.I know that the correct capitalization for Pfam is "Pfam" not PFAM

@mah11 should capitalization be correct in this file, do you know? I always thought it was?

**Comment by ValWood** [comment]
- [ ]  Let's sort by count if its quick, punt it  to a new ticket if its slow

**Comment by ValWood** [comment]
>  The displayed database names are now from the GO.xrf_abbs file. They aren't all obvious (eg. "CDD", "PIRSF") but I've made the database name into a link so the user can always click through to find out more.

I think thats ok

**Comment by kimrutherford** [comment]
> Thats weird.I know that the correct capitalization for Pfam is "Pfam" not PFAM

It should show "Pfam".  You might need to reload or shift-reload.

> Let's sort by count if its quick, punt it to a new ticket if its slow

It's quick.  Should the rows with no count sort to the top of bottom of the table?

**Comment by ValWood** [comment]
>It should show "Pfam". You might need to reload or shift-reload.
yep

>Should the rows with no count sort to the top of bottom of the table?

why are there no counts ? if they are on the page there must be a way to count them?
(or do the counts come from the XML....if so are these all PANTHER? this is an easy way to provide the examples which  don't have a pombe e.g. to Rob )

**Comment by kimrutherford** [comment]
> why are there no counts ?

Because I hadn't thought about things.  :-)

Currently it's only calculating the counts for the rows with an InterPro ID.  It's not hard to add counts for the other IDs, I just hadn't thought to do it.  I'll do that now.

**Comment by ValWood** [comment]
well I can understand why you would expect everything in the InterPRO file to have an InterPro ID! anyway  for the record its because not  all family signatures are yet integrated int InterPro.

**Comment by kimrutherford** [comment]
I've added the missing counts.  Except for the MobiDB matches because there is no unique ID to do the counting with.  All the MobiDB matches have the ID "mobidb-lite".

**Comment by ValWood** [comment]
Looks good, will close this off, read through and  anything outstanding I'll put in a new ticket. This one is too long;)
