### ISSUE TITLE
community web page  for fission yeast international meetings

### ISSUE THREAD

**Issue by ValWood** [pombase/website#962]
It would be great to have a list of these, with a link to the conference website and , if avaiable to the electronic abstract book.
I'm trying to find something of Takashi's, that I *think* was in Japan  (Tokyo meeting).
Lost...

**Comment by ValWood** [comment]
I'm stuck because I can't remember the gene name :(

**Comment by ValWood** [comment]
Not urgent (I found the gene).
Do we already link to some abstract books anyway? 
I thought we did but O could n't find them

**Comment by mah11** [comment]
The last four meetings are listed on the Documents download page, https://www.pombase.org/documents. The list could move to its own page if you prefer, but the individual meeting pages already link to almost everything I've been able to find to date.

The 2013 London meeting is the only one with its only abstract book PDF linked right now. I also have a password-protected PDF for the 2015 Kobe meeting. The password may be the reason we haven't linked it up, but I think I could make a passwordless copy.

I don't have any of the information on the meetings before I joined PomBase, i.e. before 2011. I can see how many conference website URLs I can dig out of the email archive, and which ones still work.

**Comment by ValWood** [comment]
OK, once we have a bosic list we can ask if any ex conferrence organiszers can supply an electronic abstract book, or link.

I will also see what I have Re past meetings. 

@bahler probably you have a list maybe?

**Comment by ValWood** [comment]
Hi Jurg,

If you click on the link in the bottom of this e-mail it will take you to the full thread ;)

We want to create a page with links to past conferences, and if possible abstract books.
I wondered if you had any info....or is there a scientific committee who can provide the info?

Val

**Comment by bahler** [comment]
I don’t have a list of pombe meetings, but this could be put together based on distributed information. I should have a PDF of Pombe 2013.

Cheers,
-Jürg

**Comment by ValWood** [comment]
I think we can close this ticket.
But how do I get to this page (which menu is it under?)
https://www.pombase.org/documents

**Comment by mah11** [comment]
> which menu is it under?

Downloads

**Comment by ValWood** [comment]
makes sense!

**Comment by ValWood** [comment]
I looked under 3 others, I don't know why I didn't look here!
