### ISSUE TITLE
unknowns research spotlight update

### ISSUE THREAD

**Issue by ValWood** [pombase/website#969]
retire from rotation, keep on archive
2017-10-10
Explore PomBase: Step into the unknown
Browse PomBase's inventory of conserved proteins with no known biological role

instate
Explore PomBase:  Unknown process now down to 696,  conserved unknowns 410.
Our "unknowns" manuscript  will be on bioRxiv.org soon
link to "conserved unknowns 410"
https://www.pombase.org/gene_subset/characterisation_status_conserved_unknown

pin to front page

image in dropbox Pombase spotlight/ unknowns2

tweet?

**Comment by kimrutherford** [comment]
How's this?  (Not live yet)

Please ignore the second "Explore PomBase:".  I'll remove that.

![explore-unknowns-1](https://user-images.githubusercontent.com/90474/46578296-20715b00-ca59-11e8-92b1-88ac2bc536ce.png)

Or slightly less cropped:

![explore-unknowns-2](https://user-images.githubusercontent.com/90474/46578340-519e5b00-ca5a-11e8-8cc0-7a13529acda3.png)

Which do you prefer?

**Comment by kimrutherford** [comment]
For Twitter, how about this text?:

Genes with unknown process now down to 696, conserved unknowns 410.
Our "unknowns" manuscript will be on bioRxiv.org soon.
In the meantime, here's our list of conserved genes with unknown function:
https://www.pombase.org/gene_subset/characterisation_status_conserved_unknown

**Comment by ValWood** [comment]
top one I think...

tweet good....

**Comment by ValWood** [comment]
sorry revise tweet
~unknown function~ -> unknown physiological role
(sometimes we know 'molecular function'  semantics confusing)

**Comment by ValWood** [comment]
revised tweet, is it now too long?

**Comment by ValWood** [comment]
yep good plan!

**Comment by kimrutherford** [comment]
I forgot to send a tweet on Monday but I have now.

**Comment by kimrutherford** [comment]
The tweet has attracted a bit of interest!

**Comment by ValWood** [comment]
Yes  I saw...... I think we can get a lot of interest in the article on  bioRxiv
We need to have a plan about:
 
Existing tweets we can respond to
Hashtags to include 

etc.
