### ISSUE TITLE
links from biogrid section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#970]
Can anyone remember. Did we used to have the BIoGRID links from the genetic and physical interaction section of the gene pages go directly to the biogrid page for that gene?
Should we?

**Comment by mah11** [comment]
We might as well now, whatever the old pages did (I think they did link).

**Comment by kimrutherford** [comment]
I think we've had this discussion before.  We got stuck on what to link to.  BioGRID have gene pages like this:
  https://thebiogrid.org/276415/table/schizosaccharomyces-pombe/cdc2.html

but they don't have a page per interaction.

So should we have a link above the interactions table "View interactions for cdc2 at BioGRID ..." ?

**Comment by ValWood** [comment]
oh yes. one link at the top then.

**Comment by kimrutherford** [comment]
We need to sort out #972 first.

**Comment by kimrutherford** [comment]
I've added a link to BioGRID from the interaction sections.  It will be visible on Tuesday morning.

**Comment by kimrutherford** [comment]
The link is in the top left of the interaction sections so it's maybe not obvious enough.  I'm going to close this issue but please open a new one if you'd like the link moved.
