### ISSUE TITLE
add to complex file filter

### ISSUE THREAD

**Issue by ValWood** [pombase/website#971]
DNA replication preinitiation complex (GO:0031261

is covered by sub complexes. The networks will resolve better if this is filtered.
I can't remember where to do it now... its not under svn anymore I think there must be a config somewhere?

**Comment by ValWood** [comment]
need this to generate a cleaner network for my teaching slides... (thurs)

**Comment by kimrutherford** [comment]
It's in pombe-embl/website/pombase_v2_config.json in SVN.

I've added the term.  If you need to add more look for "macromolecular_complexes" in that file and add to the end of the "excluded_terms" list.

The config change missed Saturday night's load but should be visible on Monday.

**Comment by ValWood** [comment]
I'll take this to remind me to check that the change  does what I intended to the network diagram

**Comment by kimrutherford** [comment]
> it worked, but now added "GO:0005656"

I've checked the output and that change has come through to:
ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv

**Comment by ValWood** [comment]
I'll check the esyN tomoror.

**Comment by ValWood** [comment]
replication complexes now resolve separately ;) Just in time for my talk slide :)

![woohoo](https://user-images.githubusercontent.com/7359272/46788825-ec38bb80-cd32-11e8-9509-85261b6b1db3.jpg)
