### ISSUE TITLE
Display  protein structures and change top page matter

### ISSUE THREAD

**Issue by ValWood** [pombase/website#98]
http://www.rcsb.org/pdb/software/wsreport.do
You can search  and then create a custom report:
https://www.rcsb.org/docs/programmatic-access/web-services-overview
e.g https://www.rcsb.org/3d-view/jsmol/2GFU/1

**Comment by ValWood** [comment]
sadly, because it will be very cool....we will do it soon after though...

**Comment by ValWood** [comment]
from
https://github.com/pombase/website/issues/80

- [ ] possible webservice for "structure"
this is my favourite structure viewer  (JSmol) for the mouse over of "structure tab" in "basic info section"
http://www.rcsb.org/pdb/explore/jmol.do?structureId=2GFU&bionumber=1
(rotating ribbon view)

(If there is now webservice, its only a viewer + a pdb file)

![structure](https://cloud.githubusercontent.com/assets/7359272/20605879/7e98260e-b265-11e6-826c-dcf88799e7d4.jpg)

Of course it could be more simply a static  structure image like:
http://www.rcsb.org/pdb/explore/explore.do?structureId=5IKK
in the basic info section..... but the rotating  3d view would be so cool!

**Comment by ValWood** [comment]
from
#80
I might prefer this for structure (simpler) http://biojs.io/d/bio-pv
rotatable manually

**Comment by Antonialock** [comment]
uniprot links to structures eg
https://www.uniprot.org/uniprot/Q6ZW76

**Comment by Antonialock** [comment]
uniprot displays structures eg
https://www.uniprot.org/uniprot/Q6ZW76

**Comment by Antonialock** [comment]
btw I don't find http://biojs.io/d/bio-pv useful
I would want to be able to zoom in to residue detail so that I see molecular detail, the linked ribbon is just a pretty picture

**Comment by ValWood** [comment]
The unprot one is only a secondary structure not 3D

We want 3D and ideally rotating

**Comment by ValWood** [comment]
I was reading the label underneath!
requirements

- 2D- ideally able to render ribbon, ball and stick
- residues visible on mouse over
- rotable, zoomable
- add yours

We should plan to do this at the same time as we change the thumbnail from Ensembl to 
JBrowse.
More later...... running late....

**Comment by ValWood** [comment]
I was thinking something like this.

There would be very minimal functionality (if any) on the gene page... but if you click on the icon  (or some obvious action icon) you would go to a full launch page  where you could do everything you wanted to do.

The  genome broswer is easy, you would just go to the browser.



[mockup  browsers on gene page.pdf](https://github.com/pombase/website/files/2250910/mockup.browsers.on.gene.page.pdf)

**Comment by ValWood** [comment]
We could begin with Genome browser and Structure viewer, then add pathways later.
It could also be a 4-way with the protein viewer eventually.... but then we might need to jiggle with the basic information....

**Comment by kimrutherford** [comment]
See also: #988

**Comment by kimrutherford** [comment]
> The uniprot one is only a secondary structure not 3D

UniProt have a 3D viewer or am I misunderstanding?: https://www.uniprot.org/uniprot/Q6ZW76#structure
(Although it won't load for me in Firefox)

**Comment by kimrutherford** [comment]
UniProt use LiteMol: https://webchemdev.ncbr.muni.cz/LiteMol/

I've had a look and I think we could implement it for PomBase.  We'd need to add the PDB entry IDs to Chado.  I'm sure we can bulk download them somehow using the UniProt IDs.

This page might be useful: https://www.ebi.ac.uk/pdbe/pdb-component-library/doc.html

**Comment by ValWood** [comment]
> I'm sure we can bulk download them somehow using the UniProt IDs.

yes that should be possible. Some will have more than one structure (probably),  and often have different "chains" broken up as separate entries. Some might only have the structure as part of a larger complex.  We will probably  only want to select one entry, so we may need some  heuristic to select the best one to display once we know what is available.

**Comment by ValWood** [comment]
LiteMol seems like the tool to use!

**Comment by kimrutherford** [comment]
> so we may need some heuristic to select the best one

That sounds tricky.  :-)

On the UniProt pages they have a selector on the right the lets the user select which structure to show.  Should we do that too?

![uniprot-structure-1](https://user-images.githubusercontent.com/90474/47188770-de6be180-d395-11e8-9d5d-ff4d70a01319.png)

**Comment by ValWood** [comment]
well it would be tricky to do space-wise  if we plan to have the structure viewer in the top panel, it would take up quite a bit of space.
we could default to one option and have a little drop down menu to switch to others maybe?

It doesn't need to take up as much space as it does at UniProt...

**Comment by kimrutherford** [comment]
> well it would be tricky to do space-wise if we plan to have the structure viewer in the top panel,
> it would take up quite a bit of space.

I might work if we have tabs like this:
  https://github.com/pombase/website/issues/988#issuecomment-430496265

**Comment by ValWood** [comment]
Yes I really like it too. I thought I commented before...

**Comment by ValWood** [comment]
I'm putting this as "next grant" because its totally non-urgent. However it would be really nice so if you fancy a diversion  from Canto at any point....

**Comment by ValWood** [comment]
A rough (high level) list of tasks
Download all pombe pdb structures
Download all pombe Alpha Fold structures https://alphafold.ebi.ac.uk/download
Decide between JSMol and LiteMol (these are probably even versions of the same thing?)
Decide how to display. Probably best  to include all  EXP structures so maybe just default the highest resolution  if there are more than one, and have tabs for others including Alpha fold.

**Comment by kimrutherford** [comment]
> Download all pombe pdb structures
> Download all pombe Alpha Fold structures

I'm hoping we don't need to download the structures once we have the PDB IDs to associate with the pombe genes.
The LiteMol docs imply that it can use these APIs to get the structures on demand from PDB:
  - https://www.ebi.ac.uk/pdbe/pdbe-rest-api
  - https://www.ebi.ac.uk/pdbe/coordinates/

**Comment by ValWood** [comment]
Even better!

**Comment by Antonialock** [comment]
> Do you know (or could you ask) which tool UniProt use for displaying
Alpha Fold and other pdb structures?

Aurelien says:
It's using Mol* https://molstar.org/ embedded within our own Nightingale components https://ebi-webcomponents.github.io/nightingale/#/structure

**Comment by Antonialock** [comment]
also might be usefule. Uniprot curate active sites, modified amino acids, metal binding sites + propagate between orthologs. I don't think that is integrated

**Comment by ValWood** [comment]
Thanks!
We have been discussing the UniPRot active site curation recently. InterMine will pull these into the pombemine so they could become available....

**Comment by ValWood** [comment]
If you do need strructures, I asked  rscb last night if you could get them by species.
Their response:

You can browse by species at https://www.rcsb.org/search/browse/taxonomy
After selecting the blue link in the branch of the tree that you are interested in, you can select the "Download Files" link at the top right of the results page.  If there are many entries you will probably want to use the batch script at https://www.rcsb.org/docs/programmatic-access/batch-downloads-with-shell-script

**Comment by ValWood** [comment]
A nice project if you want a change next week ;)

**Comment by kimrutherford** [comment]
> I like the viewer that AlphaFold pages use, but I can't tell what it is.

I had a look.  It's Mol*: https://molstar.org/

**Comment by ValWood** [comment]
I like that one.
what are the options?
Presumably this is a simpler tasks now that all we plan to do is display the AlphaFOLd and link to pdb in the main gene page structure viewer. We can, later  use the same, or a different viewer linked to the protein structure viewer as necessary...

**Comment by kimrutherford** [comment]
> I had a look. It's Mol*: https://molstar.org/

I've re-read the thread and seen that Antonia had already said that.  Sorry Antonia!

> I like that one.
> what are the options?

What sort of options do you mean?

**Comment by kimrutherford** [comment]
Here's an example of a minimal structure viewer using PDB's wrapper for Molstar: https://plnkr.co/edit/v0guJYMkyAIb43GT?preview

**Comment by kimrutherford** [comment]
An example with the AlphaFold structure: https://plnkr.co/edit/Z2BGbGMwr9qa1nQu?preview

**Comment by ValWood** [comment]
Sorry I meant what are the choices
1. Molstar
2. UniProt use LiteMol: https://webchemdev.ncbr.muni.cz/LiteMol/ (presumably this is Molstar)
It sounds like Molstar is the one to go for...

> An example with the AlphaFold structure: https://plnkr.co/edit/Z2BGbGMwr9qa1nQu?preview

Looks good. Exciting!

**Comment by ValWood** [comment]
Thinking (way) ahead. We have an open item to create complex pages. People are doing nice complex structure predictions using Alphafold, so we could represent these on the 'complex' pages. This would be super useful (obviously you  also  get complexes for structures, but it's very spotty...

**Comment by ValWood** [comment]
@manulera  in case you are not following..

**Comment by kimrutherford** [comment]
> presumably this is Molstar

Their website says:

-----------------
Mol* development was jointly initiated by PDBe and RCSB PDB to combine and build on
the strengths of [LiteMol](https://litemol.org/) (developed by PDBe) and [NGL](https://nglviewer.org/) (developed by RCSB PDB) viewers.

------------------

I found a few other protein structure viewers:
 - https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0155-1
 - https://www.ncbi.nlm.nih.gov/Structure/icn3d/icn3d.html
 - https://biasmv.github.io/pv/

But I think it makes sense to use the same viewer as AlphaFold and PDB.

**Comment by ValWood** [comment]
Yes no point in looking at any others, everyone is familiar with this one and it will always be well supported.

**Comment by manulera** [comment]
Yes! That one looks very nice.

**Comment by kimrutherford** [comment]
Prototype!  https://desktop.kmr.nz/gene/SPAPB1A10.15

I've removed JBrowse temporarily in this version while I work on the structure view.

The "View full Q9HDX5 Alphafold page" text is just a placeholder.

![image](https://user-images.githubusercontent.com/90474/213626882-6917c368-f25d-4107-866c-61d01c5ea8f6.png)

**Comment by ValWood** [comment]
This is going to be so awesome....... you will be the most popular person at the meeting in Japan ;)

**Comment by ValWood** [comment]
Will need a way to deal with entries with no alpha fold. 
There will be entries with no prediction,  but also entries with no uniprot accession number
https://desktop.kmr.nz/gene/SPAC110.06 (dubious proteins are excluded  I think)

**Comment by kimrutherford** [comment]
> There will be entries with no prediction 

I wonder if we can download a list of IDs with predictions from AlphaFold?  I'll check that soon.

> but also entries with no uniprot accession number

I'll fix that by not trying to show the structure if there's no UniProt ID for the gene.

**Comment by manulera** [comment]
I guess this is down now. I cannot see the page

**Comment by ValWood** [comment]
Yes it's on Kimd local machine and he switches it off at night.

**Comment by kimrutherford** [comment]
> I guess this is down now. I cannot see the page

On Monday I'll put a prototype in dev.pombase.kmr.nz.  That site runs on the PomBase server in Cambridge so it's available for more of the day.

**Comment by kimrutherford** [comment]
> On Monday I'll put a prototype in dev.pombase.kmr.nz.

I've done that: http://dev.pombase.kmr.nz/gene/SPCC18B5.03

The main site is unchanged for now.

On my desktop I'm working on adding buttons.  We should chat on Zoom about how that should work.

https://desktop.kmr.nz/gene/SPCC18B5.03

![image](https://user-images.githubusercontent.com/90474/213968465-546db5f0-a8bd-4005-ad1b-d1862e81c169.png)

**Comment by kimrutherford** [comment]
> On my desktop I'm working on adding buttons.

Here's my current work in progress: https://desktop.kmr.nz/gene/SPCC18B5.03
(That link will work until noon or so)

![image](https://user-images.githubusercontent.com/90474/214000973-6c4e49eb-8f33-45f3-a733-30039c83ca9e.png)

**Comment by ValWood** [comment]
Looks fab.

I think we should aim to make the windows a similar size.

some thoughts:
We should reduce the width, and increase the depth of the genome browser window so that it is the same aspect as the structure. It is set at the current width to cope with dynein at this resolution.

Increasing the depth will improve the scroll bar bug which means that often forward stran features are hidden by default.

I suggest also

Make the window width 14k which would show all of dynein but only a tiny proportion of the flanking region (at the same resolution)
then
zoom the view resolution until it fits the width fits. Some views will be more crowded but this is really only for orientation, and will encourage people to go to the browser
(the only other option is to change the scale in a gene-dependent way, which would be confusing
If it looks very squashed we can make Alphafold a bit wider.

As you suggested move the 'flanking genes' to only display on the browser view (I. like the Alpha fold external links). With the above changes, there will be fewer flanking genes.

**Comment by kimrutherford** [comment]
> As you suggested move the 'flanking genes' to only display on the browser view

I meant that we could have it at the top in all cases.  I think it's more useful when JBrowse isn't visible.

**Comment by manulera** [comment]
> Increasing the depth will improve the scroll bar bug which means that often forward stran features are hidden by default.

I agree with this. Even if I know it, sometimes it is confusing that I don't immediatelly see the gene from the gene page in JBrowse.

What do you mean by hiding the flanking genes?

**Comment by kimrutherford** [comment]
> We should reduce the width, and increase the depth of the genome browser window so that it is the same aspect as the structure.

Does it need to be the same width?  We can only see one widget at a time.

**Comment by ValWood** [comment]
> Does it need to be the same width? We can only see one widget at a time.

They don't absolutely need to be the same width, but it would look slicker.

Also I think it could be a slight improvement for the genome browser view to see more depth and fewer flaking genes.

**Comment by ValWood** [comment]
re "hiding flanking gnes" refers to this list:
<img width="567" alt="Screenshot 2023-01-23 at 10 23 25" src="https://user-images.githubusercontent.com/7359272/214016683-71a78e80-5713-44a6-bceb-22af420b69a6.png">

**Comment by kimrutherford** [comment]
I've made JBrowse the same height as the structure view on my desktop:
https://desktop.kmr.nz/gene/SPAC1093.06c

> They don't absolutely need to be the same width, but it would look slicker.

In that case could we make the structure viewer as wide as JBrowse?

> Also I think it could be a slight improvement for the genome browser view to see more depth and fewer flaking genes.

We can do that without making making it narrower though.

**Comment by ValWood** [comment]
Lets chat about the aspect ratios tomorrow. It seems there are quite a few variables that could be adjusted.

Interestingly AlphaFold doesn't have a prediction for dynein heavy chain - I wonder if it struggles with 4000 AA proteins???

**Comment by kimrutherford** [comment]
> Interestingly AlphaFold doesn't have a prediction for dynein heavy chain - I wonder if it struggles with 4000 AA proteins???

Yep: https://alphafold.ebi.ac.uk/faq#faq-19

"The minimum length is 16 amino acids, while the maximum is 2,700 for proteomes / Swiss-Prot and 1,280 for the rest of UniProt. For the human proteome only, our download includes longer proteins segmented into fragments."

So unfortunately no prediction for this one either: https://www.pombase.org/gene/SPBPJ4664.02

**Comment by ValWood** [comment]
I remember now that crazy didn't have a prediction, it was one of the first ones we looked at.

**Comment by kimrutherford** [comment]
To do:

  - [ ] link to Molstar instructions
  - [ ] hide structure on RNA pages
  - [ ] hide structure on pages of long proteins
  - [ ] Add link to documentation on right hand side
  - [ ] Add documentation

**Comment by kimrutherford** [comment]
>  - [x] link to Molstar instructions
>  - [x] hide structure on RNA pages
>  - [x] hide structure on pages of long proteins
>  - [x] Remove some of the control/config buttons on the right hand edge

All done.  These changes are only visible on my desktop: https://desktop.kmr.nz/gene/SPAC3H5.09c

>  - [ ] Add link to documentation on right hand side
>  - [ ] Add documentation

Do we need a documentation page of our own?  We have a link to the main Alphafold page.  Maybe that's enough?

Can you suggest better text for the links on the right hand?  Currently we have:
  - View full Alphafold page
  - Viewer control documentation

**Comment by kimrutherford** [comment]
>  - [x] Remove some of the control/config buttons on the right hand edge

How's this?:

![image](https://user-images.githubusercontent.com/90474/214482065-a156fe7c-34f0-40af-801a-cd81867b8537.png)

**Comment by ValWood** [comment]
I don't think we need an additional page, and I think the current text is fine.
You can go ahead and release - do you want to mail pombelist.

**Comment by kimrutherford** [comment]
Great.

I still have two things to fix before it's ready to release but I should be able to by tomorrow:

  - handle errors a bit better, like when EBI is completely offline
  - improve how it looks when there are no widgets shown, mostly by hiding the icons in that case.

> do you want to mail pombelist

That sounds scary.

**Comment by kimrutherford** [comment]
> improve how it looks when there are no widgets shown, mostly by hiding the icons in that case.

I decided to see how it looks with small inline icons:

![image](https://user-images.githubusercontent.com/90474/214752841-8ba24f88-3606-4df4-8a3b-7b26f018ab50.png)

**Comment by ValWood** [comment]
I think I preferred the icons to the left and to show protein structure by default.
probably the icons could be fractionally smaller.

**Comment by kimrutherford** [comment]
Protein structure is still the default. It remembers your last choice

**Comment by ValWood** [comment]
I see what you mean, that is the hide-all view. I think  this is better inline (i.e as you have it now)

**Comment by kimrutherford** [comment]
It's all checked in now so it will be on the main site at 6am tomorrow.

**Comment by manulera** [comment]
🚀🚀🚀

**Comment by ValWood** [comment]
Woo Hoo. You can announce when you release to catch the early birders ;)

**Comment by kimrutherford** [comment]
The structures will be on the JaponicusDB gene pages tomorrow.  It would have been available today but the japonicus load failed last night due to a misconfiguration.  169 japonicus proteins that are longer than 1280 aa don't have structures available.

**Comment by kimrutherford** [comment]
> The structures will be on the JaponicusDB gene pages tomorrow.

After a small fix to the URL for the structure files, the structures are now available for japonicus:

https://www.japonicusdb.org/gene/SJAG_01143

![image](https://user-images.githubusercontent.com/90474/215251764-d2463f19-0a34-4a72-a64a-84c06bf6e319.png)

**Comment by snezhkaoliferenko** [comment]
AMAZEBALLS
THANK YOU!!!!

**Comment by Antonialock** [comment]
so nice! 

Imo you should make it clear that it's a prediction, also perhaps a colour key as it relates to one of the two confidence scores, though I suppose people can go through to the alphafold page for that?

**Comment by ValWood** [comment]
If it stays like this we probably should improve the labelling to make it clearer. Kim is working now on importing pdb images, and a selector, so we will improve at that point.

**Comment by Antonialock** [comment]
Oh that sounds great! Perhaps substrate/metal binding sites would be nice complementary data? (uniprot propagate this info between organisms)

**Comment by kimrutherford** [comment]
> Imo you should make it clear that it's a prediction

Hi Antonia!

Val, maybe we could change the label of the left hand button from "Structure viewer" to "Predicted structure"?

> also perhaps a colour key as it relates to one of the two confidence scores

I'm about to make this change.   Does that help?

![image](https://user-images.githubusercontent.com/90474/215627318-1222a7d9-35a2-4167-83b8-b3c691818e08.png)

**Comment by kimrutherford** [comment]
> maybe we could change the label of the left hand button from "Structure viewer" to "Predicted structure"?

That's done now.

**Comment by snezhkaoliferenko** [comment]
Thank you!

________________________________
