### ISSUE TITLE
Quick little tool, documentation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#984]
Heres my first draft of dcumentation for refinement and including by @mah11 

“Quick Little Tool”  allows you to view multidimensional annotations relating to a list of genes simultaneously. Each line/row in the graph is a single protein. Clicking on a row or block will highlight a specific protein or proteins and add them to a selected sub-list that can be filtered into a new image. Clicking on the  ’sort’ feature will reorganise the lists to primarily cluster the annotated features of the list of interest.

The current version of the tool allows you to view deletion viability, presence or absence of budding yeast orthologs, presence or absence of human orthologs, GO process, GO function and GO component

GO processes are binned with the following precedent (if a gene product is annotated to more than one term)
signaling (GO:0023052) > gene expression (GO:0010467) > chromatin remodeling (GO:0006338)> protein folding (GO:0006457)> cellular component biogenesis (GO:0044085) > DNA metabolic process (GO:0006259)> cell cycle (GO:0007049) > cytoskeleton organization (GO:0007010) > membrane organization (GO:0061024) > organelle localization (GO:0051640) > lipid metabolic process (GO:0006629) > small molecule metabolic process (GO:0044281) > generation of precursor metabolites and energy (GO:0006091) > transport (GO:0006810) > cellular catabolic process (GO:0044248) > detoxification (GO:0098754) other (i.e none of the above)
none (change label to unknown)

GO functions are binned with the following precedent (if a gene product is annotated to more than one term)
oxidoreductase activity (GO:0016491)
hydrolase activity (GO:0016787)
transferase activity (GO:0016740)
ligase activity (GO:0016874)
cyclase activity (GO:0009975)
lyase activity (GO:0016829)
RELABEL “UNKNOWN catalytic activity (GO:0003824)
enzyme regulator activity (GO:0030234)
transcription regulator activity (GO:0140110)
transporter activity (GO:0005215)
cytoskeletal protein binding (GO:0008092)
unfolded protein binding (GO:0051082)
DNA binding (GO:0003677)
RNA binding (GO:0003723)
metal ion binding (GO:0046872)
lipid binding (GO:0008289)
cell adhesion mediator activity (GO:0098631)
structural molecule activity (GO:0005198)
other (i.e none of the above)
none (change label to unknown)

GO cellular components are binned with the following precedent (if a gene product is annotated to more than one term)
nucleus
ER
mitochondria
cytoplasm
other
none (change label to unknown)

**Comment by ValWood** [comment]
@kimrutherford  link to documentation from tool once in place.
Ideally a "I" icon would link directly to the  F, P and C  description, but if this is tricky it can go to the full page.

**Comment by kimrutherford** [comment]
> Ideally a "I" icon would link directly to the F, P and C description

That should be no problem.

**Comment by mah11** [comment]
I have now added a documentation file (with illustration) to the repo. I haven't linked it to anything yet, so it won't clog any other website updates in the meantime. Let's leave this open, and close when it's linked.

**Comment by mah11** [comment]
of course, I forgot to tag this ticket in the commit; it's 8e2d2b36b50fe4b2ae80c6bb9f1d4113e098c315

**Comment by ValWood** [comment]
Thanks for this. I think we can move this over to live when Kim is ready? 
I will write, announcement, news item, tweet for editing....

**Comment by mah11** [comment]
check GO precedence order per #990

**Comment by ValWood** [comment]
and "when linked " sorry

**Comment by kimrutherford** [comment]
The documentation is live: https://www.pombase.org/documentation/quick-little-tool

I haven't added a link to it.

**Comment by ValWood** [comment]
I'll check through eveything as first task tomorrow... and write announcement.

**Comment by ValWood** [comment]
yes docs look good. So we are going with "QuiLT", it looks like a QuiLT, I like it!

**Comment by ValWood** [comment]
closing this as the final  steps are in the 15 point plan
https://github.com/pombase/website/issues/1000

**Comment by mah11** [comment]
I am leaving this OPEN to remind me to add links to the documentation page. That is not listed in #1000, and should not be added there because that ticket is too confusing already.

**Comment by kimrutherford** [comment]
I've added a bit of configuration documentation too:
  https://github.com/pombase/website/wiki/Configuration#quilt--visualisation-tool
