### ISSUE TITLE
add a key to the download image

### ISSUE THREAD

**Issue by ValWood** [pombase/website#986]
![presentation3](https://user-images.githubusercontent.com/7359272/46985263-64133700-d0e1-11e8-9f49-920444ca3844.jpg)

**Comment by ValWood** [comment]
note that the background of the download image turned black, (at least here...)

**Comment by ValWood** [comment]
from https://github.com/pombase/website/issues/883
Current issues

'other' 'none' and 'mitochondrion' seem to be the same/ v. similar colour (this might be fixed)?


make anything which is "no data" white (i.e component unknown, no viability data)

**Comment by kimrutherford** [comment]
> 'other' 'none' and 'mitochondrion' seem to be the same/ v. similar colour (this might be fixed)?

I've tweaked those colours.  Hopefully there's more contrast now.

> make anything which is "no data" white (i.e component unknown, no viability data)

That's done now.

> note that the background of the download image turned black, (at least here...).Fix to white

Also the scale numbers are underneath the image and the column headers are too big.  I'll work on that and on adding a key.

**Comment by kimrutherford** [comment]
> note that the background of the download image turned black, (at least here...).Fix to white

> Also the scale numbers are underneath the image and the column headers are too big.

Those problems are fixed now.

**Comment by kimrutherford** [comment]
Now I've started implementing the key, I'm a bit concerned that it's going to be bigger than the main image in some cases.  The function and process list are long (20 terms for function, 18 for process).

I can make the font small but that's not great.  Any suggestions?

**Comment by kimrutherford** [comment]
It looks quite nice (I think) but it's rather long.

![vis-tool-key-1](https://user-images.githubusercontent.com/90474/47134748-57255c00-d30a-11e8-938a-0060081d3256.png)

**Comment by kimrutherford** [comment]
> It will only be long when you have a mixed bag of stuff and a long list

Currently the list shows all the possible field values not just those that are visible.  I'll work on that.

> Out of interest what was your list, was it a random list of genes?

It was genes with 5 exons so quite ramdom.

**Comment by ValWood** [comment]
> Currently the list shows all the possible field values not just those that are visible. I'll work on that.

would be good

Is it also possible to default no data (white) to the bottom of the list?

**Comment by kimrutherford** [comment]
> Is it also possible to default no data (white) to the bottom of the list?

That should be fixed when I fix this:

> the order of the values in the key doesn't match the sort order in the diagram.

("no data" at the bottom will be an easy check of the fix)

**Comment by ValWood** [comment]
Actually the  default order should be the order of the precedence.
So for BP signalling would be at the top becasue that trumps others

**Comment by ValWood** [comment]
...that's probably what you are doing ;)

**Comment by kimrutherford** [comment]
I think I've fixed the problems with the key.  Let me know if I've missed anything.

**Comment by ValWood** [comment]
Looks good. One small thing. I think the colour of cytoplasm  in the key and the image is slightly different.

when GO process is sorted default order should put signalling at the top.

**Comment by ValWood** [comment]
Iss, the colour changes when you mouse over.
1 no mouse over, colour does not match:
![grab1](https://user-images.githubusercontent.com/7359272/47256502-6ecf2280-d479-11e8-8ebc-82a7e4d6b6a0.jpg)

mouse over, it does!
![grab2](https://user-images.githubusercontent.com/7359272/47256507-75f63080-d479-11e8-8625-e5fe84c786b1.jpg)

**Comment by kimrutherford** [comment]
Thanks!  I know what's going on now so I'll be able to fix it tomorrow.

**Comment by kimrutherford** [comment]
>  I know what's going on now so I'll be able to fix it tomorrow.

The colours should match now.

**Comment by ValWood** [comment]
OK great closing...

**Comment by kimrutherford** [comment]
> it could even light up more... like background highlighting, for example

I've had a look and unfortunately that's tricky in an SVG image.  The colour and font weight and size can be changed but not the background.
