### ISSUE TITLE
welcome to the 21st century 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#987]
![wellcome to the 21st century](https://user-images.githubusercontent.com/7359272/46985306-af2d4a00-d0e1-11e8-8b49-c9d3e16bf2e7.jpg)

that's it.

Action, do I need to say?

**Comment by kimrutherford** [comment]
It's still a work in progress.  I've added it to pombase-dev for testing.

**Comment by ValWood** [comment]
It looks brill so far! you can zoom! on a gene page!

**Comment by kimrutherford** [comment]
![gene-page-jbrowse-1](https://user-images.githubusercontent.com/90474/47007549-ff191900-d194-11e8-96b9-ecb5e493e381.png)

**Comment by ValWood** [comment]
It wasn't really necessary. MAybe uncluttered is better. Also eventually want to put more than just the browser  thumbnail in this space:
I did  a mockup how this might look, anyone know which ticket this was in?

**Comment by ValWood** [comment]
thanks! that'ts the one

**Comment by kimrutherford** [comment]
I've set the maximum width to be 800 pixels, same as the Ensembl images.

**Comment by Antonialock** [comment]
fantastic!

**Comment by ValWood** [comment]
I noticed that it was a tad slow loading but that might be my wireless connection. I guess it is going to be slower than a  static image though ;)

**Comment by mah11** [comment]
> any alternative suggestions for the announcement?

Sure, how about:

On gene pages, the graphics depicting the genomic region around the gene are now interactive images from PomBase JBrowse. You can drag to scroll left and right, double-click to zoom in, shift-double-click to zoom out, and click a feature to see details in a popup, on the small graphic. The "Full-screen view" link in the corner opens the fully functional JBrowse in a new tab or window. Reloading a gene page restores the display to the default location and zoom level.

> Is there any way to zoom back out?

Found it - see text above ;)

> We can remove the link “view region in JBrowse” since we have the “full-screen view” link

I agree

> Proceed with the announcement when Kim is happy to move to live, and when you have a reasonable text...

... **AND** the gene page documentation is updated. I can work on it today or tomorrow.

**Comment by mah11** [comment]
Documentation update is done. A news item exists, but doesn't have the front page flag; Kim or I can add it when the lovely JBrowse piccies go live.

**Comment by ValWood** [comment]
> shift-double-click to zoom out

I knew you would  ;)

**Comment by ValWood** [comment]
I like the revised text.

So this can all go live  as soon as ready. Yipee!

**Comment by kimrutherford** [comment]
> So this can all go live as soon as ready. Yipee!

Next we need to remove the Ensembl protein feature image.

**Comment by ValWood** [comment]
yeah that's 'orrible....

**Comment by kimrutherford** [comment]
I've removed the "View region in JBrowse ..." link.

**Comment by ValWood** [comment]
next tasks are in teh 15 point plan

https://github.com/pombase/website/issues/1000

**Comment by mah11** [comment]
pombelist announcement sent
