### ISSUE TITLE
possible longer term top page matter

### ISSUE THREAD

**Issue by ValWood** [pombase/website#988]
mock -up

https://user-images.githubusercontent.com/7359272/43544856-22ccb654-95cc-11e8-973e-521202ccfd14.jpg

**Comment by kimrutherford** [comment]
Here's a mock-up with tabs.  I hope it would look better than this though in real life though.  The thumb nails might be overkill.

![gene-page-tool-tabs-1](https://user-images.githubusercontent.com/90474/47064326-7f925500-d23b-11e8-88b2-3eea717f9125.png)

**Comment by ValWood** [comment]
Thats a good plan, things won't be squashed but people can easily change their default. Like it.

**Comment by kimrutherford** [comment]
Do we know which genes have structures available?  It would be good if we could grey-out the tab if there's nothing to display.

**Comment by kimrutherford** [comment]
Note to self: see the Note to self in this comment: https://github.com/pombase/website/issues/143#issuecomment-629937035

**Comment by ValWood** [comment]
Looks fab.

I think we should aim to make the windows a similar size.

some thoughts:
We should reduce the width, and increase the depth of the genome browser window  so that it is the same aspect as the structure. It is set at the current width to cope with dynein at this resolution. 

Increasing the depth will improve the scroll bar bug  which means that often forward stran features are hidden by default.

I suggest also
1. Make the window width 14k which would show all of dynein but only a tiny proportion of the flanking region (at the same resolution)
then
2.  zoom the view resolution until it fits the width fits. Some views will be more crowded but this is really only for orientation, and will encourage people to go to the browser 
(the only other option is to change the scale in a gene-dependent way, which would be confusing 

If it looks very squashed we can make Alphafold a bit wider.

As you suggested move the 'flanking genes' to only display on the browser view (I. like the Alpha fold external links). With the above changes, there will be fewer flanking genes.

**Comment by ValWood** [comment]
closing, see
https://github.com/pombase/website/issues/98
for the active ticket
