### ISSUE TITLE
QLT: small thing with pop up tracking

### ISSUE THREAD

**Issue by ValWood** [pombase/website#992]
If you have long lists, with long blocks, you don't see the pop up for your block of interest.

This isn't a blocker because you can scroll up  and then re-click to see it, but it would be nice if you didn't need to.

![suboptima](https://user-images.githubusercontent.com/7359272/47256751-d20e8400-d47c-11e8-9af0-eac769e7221a.jpg)

**Comment by kimrutherford** [comment]
Unfortunately there's no easy short term fix for this.  The library I'm using to do the pop-ups only has four options for the pop-up position: left, right, top and bottom.  It puts the pop-up just outside the element that's highlighted and in one of those positions.  There's no option for popping up where the pointer is.

Initially I set it to pop up to the right like the gene pop-up does.  But that also had problems with long blocks.

I'll keep an eye out for solutions.

**Comment by ValWood** [comment]
yeah its not a show stopper since you can easily scroll up to see it.

**Comment by ValWood** [comment]
will close anyway since it cant currently be fixed...
