### ISSUE TITLE
browser labelling

### ISSUE THREAD

**Issue by ValWood** [pombase/website#999]
I only just noticed that we do some 'double labelling'

The genes are labeled with both the systematic ID (transcript ID actually) and the assigned name. I wonder if we need to display both (I particularly am not keen on the  ".1" notation  which is really Ensembl speak for the transcripts and isn't the gene label, where do we get this from?

![labelling](https://user-images.githubusercontent.com/7359272/47327475-591e5080-d665-11e8-8758-7a8bb4cc7a46.jpg)

**Comment by ValWood** [comment]
It might be better just to have the 'bold' labels?

**Comment by kimrutherford** [comment]
I'll check to see what's possible in JBrowse.

**Comment by kimrutherford** [comment]
I've read the documentation again.  The transcript ID can be hidden.  It's now much clearer which gene is which:

![gene-page-jbrowse-no-transcript-ids-1](https://user-images.githubusercontent.com/90474/47333750-907e1300-d6e0-11e8-8780-0decd446b2a3.png)

**Comment by kimrutherford** [comment]
> I particularly am not keen on the ".1" notation which is really Ensembl speak for the transcripts
> and isn't the gene label, where do we get this from?

The ".1" IDs are what we use in Chado for transcripts.  Each transcript feature needs a unique ID.  We write those IDs to the GFF3 files which is where JBrowse gets them from.

**Comment by mah11** [comment]
/me goes off to update the documentation screenshot ...

**Comment by ValWood** [comment]
Great, I can't believe I didn't spot that until last night. I was so excited about  zooming and scrolling!.

I don't mind the .1 IDs per se, it's just that we don't really use them yet. This might be where ENA gets them from (The  NCBI has links to pombase  .1 Ids on their pages (broken), and they say they get them from ENA. we don't put them there.....)

**Comment by kimrutherford** [comment]
> Great, I can't believe I didn't spot that until last night.

I had spotted it but I didn't know there was a fix until yesterday.  :-)
